### ISSUE TITLE
Suggestion: Minify common properties by creating a new string with the property name

### ISSUE THREAD

**Issue by kaaaahhhhnnnn** [google/closure-compiler#1000]
I don't _think_ this can cause any issues.

Minifiy:

```js
window.addEventListener('foo', foo);
window.addEventListener('bar', bar);
document.addEventListener('baz', baz);
```

to

```
var a='addEventListener';
window[a]('foo',foo);
window[a]('bar',bar);
document[a]('baz',baz);
```

Likewise for aliasing `var w=window` in this case

**Comment by dimvar** [comment]
The compiler already renames properties. Is the compression from renaming not sufficient for your needs?

The change you're proposing would probably hurt performance.

**Comment by nicks** [comment]
This would also make the code size bigger post-gzip, please read:
https://github.com/google/closure-compiler/wiki/FAQ#closure-compiler-inlined-all-my-strings-which-made-my-code-size-bigger-why-did-it-do-that

**Comment by kaaaahhhhnnnn** [comment]
It doesn't rename built-in properties (e.g. `addEventListener`), though the gzip argument is valid :)

**Comment by dimvar** [comment]
> It doesn't rename built-in properties

Right, I didn't say that it does. Just that the compression from renaming other properties should be sufficient.

**Comment by concavelenz** [comment]
There is compiler pass for this "AliasExternals". It was written when a majority of clients didn't receive gzip'd content. However, generally it is bad for performance and bad post-gzip.  You can access it via the  java API.

**Comment by Dominator008** [comment]
FYI, the "AliasExternals" pass has been removed.
