### ISSUE TITLE
Unknown Type Warning, When Clearly Known

### ISSUE THREAD

**Issue by si-robertson** [google/closure-compiler#1002]
Hi guys,

I think the compiler should be a bit smarter when it encounters something like the following.

````javascript
const example = {}; // namespace

(function(example){
    class Fruit {
        constructor() {}
    }

    example.Fruit = Fruit; // export
})(example);

(function(example){
    class Banana extends example.Fruit { // WARNING THROWN HERE
        constructor() {}
    }

    example.Banana = Banana; // export
})(example);
````

In that example, the compiler will complain that `example.Fruit` is an unknown type when `Banana` attempts to extend it. The code is valid though, V8 has no problem with it.

I have a feeling the `mismatch in declaration of superclass type` warning generated by the next bit of code is also related to that.

````javascript
const example = {}; // namespace

(function(example){
    example.Fruit = class {
        constructor() {}
    }
})(example);

(function(example){
    const Fruit = example.Fruit;

    example.Banana = class extends Fruit { // WARNING THROWN HERE
        constructor() {}
    }
})(example);
````

Is there any chance of resolving this at your end?

**Comment by dimvar** [comment]
We don't currently have plans to handle addition of types to namespaces in this dynamic way. It is hard to solve this in general, so we'd have to add special-case code to recognize the pattern presented here.

**Comment by ChadKillingsworth** [comment]
I have plans to tackle some of the most popular special cases. That's tracked in #789 

Specifically, tracing properties added to namespaces through IIFEs is the major blocker. Also promoting types to the global namespace when added as a property to the global object within an IIFE.

**Comment by si-robertson** [comment]
Thanks guys. This issue definitely isn't an important one, it's just one of those small niggly things.
