### ISSUE TITLE
Dangerous renaming of dynamic object attribute names under  ADVANCED_OPTIMIZATION 

### ISSUE THREAD

**Issue by Markoni85** [google/closure-compiler#1003]
Here is description of the problem.

I 've got server response (JSON or XML) :
{
         "name" : "Marko", 
	 "address" : "Addres 1/45",
	 "age" : 25
}

Parsing data: 

	var ajax = new XMLHttpRequest();
	ajax.open('GET', 'data.json'); 
	var result;
	ajax.onreadystatechange = function(data)
	{
	   //some code
	   result = JSON.parse(data.reposneText);
	}
		
Accessing result object with . notation:
	...
	var name = result.name;
	var address = result.address;
	var age = result.age;
	...
	   
After advanced compilation code turns into:
	  var a = r.a, c = r.d, d = r.d;

"result" object is dynamic object and compiler doesn't know which properties it owns. Hence, I believe compiler shouldn't change object's property names if it cannot determine the structure of the object that contains those properties.

Example above shows that properties "name", "address", "age" are changed to "a", "b", "c" and that cause program execution to fail ( cause in the result object there are no properties "a", "b" or "c" )

**Comment by ChadKillingsworth** [comment]
This is expected behavior and by design. You have two options:

1. Access the data using quoted properties to block renaming (most common).
2. Develop an extern of the type and typecast the result to your type.

https://developers.google.com/closure/compiler/docs/limitations

**Comment by ChadKillingsworth** [comment]
Also worth reading: http://closuretools.blogspot.com/2012/09/which-compilation-level-is-right-for-me.html
