### ISSUE TITLE
jscompiler.py generates incorrect compiler command

### ISSUE THREAD

**Issue by Markoni85** [google/closure-compiler#1004]
Problem description.

Consider Python script :
closure-library/closure/bin/build/closurebuilder.py \
	                    --root=closure \
	                    --root=com \
	                    --namespace="com.example.MainClass" \
	                    --output_mode=compiled \ 
	                    --compiler_jar=compiler.jar \
	                    --compiler_flags="--compilation_level=ADVANCED_OPTIMIZATIONS" \
	                    --output_file=final.min.js

Executing this command produces following error:

\closure\bin\build\closurebuilder.py: Compiling with the following command: java --compilation_level=ADVANCED_OPTIMIZATIONS -jar compiler.jar --js closure\goog\base.js ....

From error report we can see that jscompiler.py place  --compiler_flags in the wrong place right after java command, and this cause compilation to fail.

Generated command should start with java -jar compiler.jar ... and then other flags and options.

**Comment by dimvar** [comment]
closurebuilder.py is not part of the compiler. You should file an issue with Closure Library.
https://github.com/google/closure-library
