### ISSUE TITLE
CommandLineRunner should display a message stating it is waiting for input

### ISSUE THREAD

**Issue by skogsbaer** [google/closure-compiler#1008]
I wanted to use cc for optimizing javascript code written using commonjs modules. But when invoking cc, the compiler just loops and outputs nothing.

I then created a very simple test, it' only one file, with no requires and only one export:

```
$ cat cc-test.js
function genTs(date) {
    var d = date || new Date();
    var pad = function (n) {
        return (n < 10 ? '0' + n : n.toString());
    };
    return d.getUTCFullYear() + '-' + pad(d.getUTCMonth() + 1) + '-' + pad(d.getUTCDate()) + 'T' +
        pad(d.getUTCHours()) + ':' + pad(d.getUTCMinutes()) + ':' + pad(d.getUTCSeconds()) + 'Z';
}
exports.genTs = genTs;
```

But the compiler still runs forever, without producing any output (and without consuming much CPU time):

```
$ java -jar ./compiler.jar --compilation_level=WHITESPACE_ONLY --logging_level=FINEST --process_common_js_modules --common_js_entry_module cc-test.js
```

I guess I'm using the latest stable build:

```
$ java -jar compiler.jar --version
Closure Compiler (http://github.com/google/closure-compiler)
Version: v20150609
Built on: 2015/06/09 16:35
```

**Comment by ChadKillingsworth** [comment]
Your `common_js_entry_module` flag is missing a value. The compiler is assuming that `cc-test.js` is the entry point name and then is waiting forever for actual input from standard in.

    $ java -jar ./compiler.jar --compilation_level=WHITESPACE_ONLY --logging_level=FINEST --process_common_js_modules --common_js_entry_module MY.MODULE.NAME --js cc-test.js

**Comment by dimvar** [comment]
@ChadKillingsworth In this case, can the compiler show a message that it's waiting for input from stdin? Then the users won't be confused that it's stuck in an infinite loop.

**Comment by ChadKillingsworth** [comment]
That would interfere with the case where the output is being redirected - unless we displayed the message using standard error.

    cat myfile.js > java -jar compiler.jar -W=VERBOSE -O=ADVANCED > out.js

**Comment by dimvar** [comment]
stderr for the message sounds good to me.

**Comment by MatrixFrog** [comment]
Yeah I've made that mistake before too. Would be very helpful for it to just print "Reading JS from stdin" if it doesn't get any input within a second or so (or maybe just print it unconditionally).
