### ISSUE TITLE
Closure Compiler modifying end bracket in string

### ISSUE THREAD

**Issue by threviel** [google/closure-compiler#1020]
I try to run the following Javascript code through closure compiler:

var firstRun = eval("<?--#exec cmd_argument='command'-->");

And it comes out as:

var a=eval(" <?--#exec cmd_argument='command'--\x3e")

Since it is an SSI command I need i to not convert > to \x3e. I have tried using --charset=utf-8 and US-ascii as input to Closure Compiler. I have also tried using \u003e in the string. Whatever I do it outputs > as \x3e, which seems very odd, since it does not do the same to <.

The input command to closure compiler I use is:

java -jar compiler.jar --js file.js --js_output_file newfile.js

**Comment by si-robertson** [comment]
Cosmetically it may look wrong but, as far as I'm aware, the characters are interpreted correctly by the VM when the string is parsed.

Example...
````
var a = "\x3c-- hello --\x3e";
var b = "<!-- hello -->";

console.debug(a.codePointAt(0)); // 60
console.debug(b.codePointAt(0)); // 60

console.debug(a.codePointAt(13)); // 62
console.debug(b.codePointAt(13)); // 62
````
Does it actually break your code?

**Comment by concavelenz** [comment]
This is working as expected.

**Comment by anuragagarwal561994** [comment]
For those who have stumbled upon the same issue, I am using the java library to compress my js files and there is an option `setTrustedStrings(true)`, this should avoid the unexpected encoding. My reason for using it this way was to keep the size of my final js code smaller and to not make a lot of changes to the original string.
