### ISSUE TITLE
`arguments` has unknown type if --language_in is ES6

### ISSUE THREAD

**Issue by MatrixFrog** [google/closure-compiler#1021]
See https://codereview.chromium.org/1204023003/ -- it appears that by switching to ES6 (not actually using any ES6 features; just switching the flag) the value of `arguments` becomes unknown. Need to figure out why this happens.

**Comment by concavelenz** [comment]
Do you have a minimal repro in the debugger?

**Comment by Dominator008** [comment]
I wonder if it's a problem with externs.

**Comment by concavelenz** [comment]
I don't see that this is ES6 related:
http://closure-compiler-debugger.appspot.com/#input0%3Dfunction%2520f()%2520%257B%250A%2520%2520arguments%253B%250A%257D%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES%3D1%26MISSING_PROPERTIES%3D1

**Comment by Dominator008** [comment]
It seems that this is fixed already? 

http://closure-compiler-debugger.appspot.com/#input0%3Dfunction%2520f()%2520%257B%250A%2520%2520arguments%253B%250A%257D%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES%3D1%26MISSING_PROPERTIES%3D1

doesn't show an error.

**Comment by MatrixFrog** [comment]
I removed a bunch of the suppressions from that Chrome change and it still builds. My guess is this is obsolete.
