### ISSUE TITLE
jscomp_warning lintChecks produce "java.lang.RuntimeException: INTERNAL COMPILER ERROR." if used without "--compilation_level ADVANCED"

### ISSUE THREAD

**Issue by tdelmas** [google/closure-compiler#1022]
```bash
java -jar compiler-20150609.jar --version
```
>Version: v20150609
>Built on: 2015/06/09 16:35

```bash
echo "/** @param {boolean=} arg */ function test(arg) { if (arg) alert('ok'); }" | java -jar compiler-20150609.jar
```

> function test(a){a&&alert(ok)};

```bash
echo "/** @param {boolean=} arg */ function test(arg) { if (arg) alert('ok'); return 0; }" | java -jar compiler-20150609.jar --jscomp_warning lintChecks --compilation_level ADVANCED
```

> WARNING - Optional parameter name arg must be prefixed with opt_
>/** @param {boolean=} arg */ function test(arg) { if (arg) alert('ok'); return 0; }
>                                           ^
>
>0 error(s), 1 warning(s)

```bash
echo "/** @param {boolean=} arg */ function test(arg) { if (arg) alert('ok'); }" | java -jar compiler-20150609.jar --jscomp_warning lintChecks
```
>java.lang.RuntimeException: INTERNAL COMPILER ERROR.
>Please report this problem.
>
>null
>  Node(BLOCK): stdin:1:48
>/ * * @param {boolean=} arg */ function test(arg) { if (arg) alert(ok); }
>  Parent(FUNCTION test): stdin:1:29
>/ * * @param {boolean=} arg */ function test(arg) { if (arg) alert(ok); }
>
>        at com.google.javascript.jscomp.lint.CheckNullableReturn.isReturnTypeNullable(CheckNullableReturn.java:118)
>        at com.google.javascript.jscomp.lint.CheckNullableReturn.hasReturnDeclaredNullable(CheckNullableReturn.java:73)
>        at  ...

**Comment by MatrixFrog** [comment]
The nullable-return check depends on typechecking information so maybe we should skip it (but run the other lint checks) if typechecking is off.

**Comment by Dominator008** [comment]
Looks like this has been fixed, closing.
