### ISSUE TITLE
Confusing logic in CheckEventfulObjectDisposal

### ISSUE THREAD

**Issue by xiemaisi** [google/closure-compiler#1024]
I'm confused by [this](https://github.com/google/closure-compiler/blob/master/src/com/google/javascript/jscomp/CheckEventfulObjectDisposal.java#L823) bit of code:

```java
/*
 * If member with qualified name gets disposed of when this class
 * gets disposed, consider the member type as an eventizer of this
 * class.
 */
JSType disposedType = maybeReturnDisposedType(n, inDisposalScope());
if (!collectorFilterType(disposedType)) {
  addEventize(getTypeOfThisForScope(t), disposedType);
}
```

The comments says that "the member type [becomes] an eventizer of this class", but the call to `addEventize` seems to do the opposite, registering `getTypeOfThisForScope(t)` (i.e., the current class) as an eventizer for `disposedType` (i.e., the member type).

**Comment by concavelenz** [comment]
This is not the place to ask questions, please post your question to closure-compiler-discuss@.
