### ISSUE TITLE
Compiler removes simple try/catch used to prevent Uncaught ReferenceError

### ISSUE THREAD

**Issue by schnerd** [google/closure-compiler#1025]
A library I was using ([persist-js](https://github.com/jeremydurham/persist-js)) contains code similar to the following:

```js
function test() {
	try {
		if (!swfobject) return false;
	} catch(e){
		return false;
	}
}
test();
```

Closure compiler v20150609 throws the following warning when compiling the snippet above:

```
> java -jar compiler.jar --js_output_file test-out.js test.js
test.js:4: WARNING - unreachable code
	} catch(e){
	  ^

0 error(s), 1 warning(s)
```

And the output file looks like the following:

```js
function test(){if(!swfobject)return!1}test();
```

The problem here is that if swfobject is not defined, we start seeing a `ReferenceError: Can't find variable: swfobject` in production. Changing `if (!swfobject)` to `if (!window.swfobject)` fixes the issue and closure compiler preserves the try/catch statement.

I apologize in advance if this is the way closure compiler is intended to work, but it seems like a very strange assumption to make when in simple optimization mode. The only documentation I could find related to external references applies to the advanced optimizations mode (see [Undeclared External References](https://developers.google.com/closure/compiler/docs/limitations)), so I decided it'd be best to submit an issue here first before submitting a pull request to the library in question. This issue can be closed if this is the intended functionality.

**Comment by MatrixFrog** [comment]
I think we used to remove try/catch's but it looks like we stopped doing so in https://github.com/google/closure-compiler/commit/289447102b1e0e6b11c20152cd4b3d2ae49365ba 

Maybe this is caused by `swfobject` not being defined in the externs?

**Comment by schnerd** [comment]
I'm only using `SIMPLE_OPTIMIZATIONS`, the closure compiler documentation makes it seem like externs are only required when `ADVANCED_OPTIMIZATIONS` is enabled, but I could be mistaken.

**Comment by concavelenz** [comment]
The RemoveTryCatch is not related to this issue.  We still remove try/catch blocks from side-effect free code.  The RemoveTryCatch pass was a debugging feature to unconditionally remove unannotated try/catch blocks so the debuggers would report them.  The debuggers have generally gotten much better and we decided the pass wasn't worth maintaining.

I believe this issue is documented here: 
https://github.com/google/closure-compiler/wiki/Compiler-Assumptions

**Comment by schnerd** [comment]
Ahh, thanks for pointing that out @concavelenz . I had looked deep into documentation on developers.google.com but didn't think to take a look at the Github Wiki. Seems like this is **not** a bug then, and I can submit a PR to the library in question.
