### ISSUE TITLE
Group definitions in the same scope

### ISSUE THREAD

**Issue by infusion** [google/closure-compiler#1029]
Hi,

when I have a structure like this:

    function a() {

        var k = 0;
        console.log("foo")
        var i = 0;
        var j = 0;
        while (i < 10) {
            var tmp = i / 10;
            ...
        }
    }

wouldn't it make sense to group all "var" definitions together as they are in the same scope? This snippet would result in 3 remaining "var" keywords, even in advanced mode.

**Comment by dimvar** [comment]
There is a pass that does that
https://github.com/google/closure-compiler/blob/master/src/com/google/javascript/jscomp/CollapseVariableDeclarations.java
and it's enabled by default in advanced mode.
https://github.com/google/closure-compiler/blob/master/src/com/google/javascript/jscomp/CompilationLevel.java#L109

**Comment by infusion** [comment]
Yes I know, but consider this example:

```javascript
// ==ClosureCompiler==
// @output_file_name default.js
// @compilation_level ADVANCED_OPTIMIZATIONS
// ==/ClosureCompiler==

    x.test=function(x, y) {

        var r = [];
        var j = y.length;
        var i = x.length;

        console.log(x, i, y, j)

        var k;
        while (i >= j) {

            var tmp = bar(x[i], y[j]);
            for (k = y.length; k--; ) {
                x[k] = foo(x[k], tmp);
            }
        }
        return r;
    }
```

which result in this compressed version with still 3 "var" occurrences

```javascript
x.a=function(a,b){var d=b.length,e=a.length;console.log(a,e,b,d);for(var c;e>=d;){var f=bar(a[e],b[d]);for(c=b.length;c--;)a[c]=foo(a[c],f)}return[]};
```

**Comment by dimvar** [comment]
Yes, the CollapseVariableDeclarations pass doesn't group distant declarations. We actually have an older pass that does that (GroupVariableDeclarations), but we don't use it anymore, because AFAIU it wasn't a size win post gzip. That pass can only be enabled from Java, not from the command line. And it's possible that we will delete it at some point, since it's mostly unused.
