### ISSUE TITLE
Exported virtual methods are inlined and renamed

### ISSUE THREAD

**Issue by LorenzoDV** [google/closure-compiler#1035]
Under ADVANCED_OPTIMIZATIONS, the compiler will sometimes inline and rename __exported__ functions that can be re-defined by external code:
* interface prototype functions,
* non-`@const` constructor prototype functions.

This may be incorrect because external code may provide additional definitions that are not known at compile time, making inlined code behave incorrectly. Furthermore, the additional definition are provided under the original (exported) name, causing renaming to also break the code.

For example, take the following code.

```javascript
/** @export @interface */
function External() {};

/**
 * @export
 * @param {string} label
 * @return {!Object}
 */
External.prototype.externalMethod = function(label) {};

/**
 * @export
 * @param {!External} externalObject
 * @param {string} param
 * @return {!Object}
 */
function createItem(externalObject, param) {
    return externalObject.externalMethod(param);
};
```

The compiler assumes that the only implementation of `External.prototype.externalMethod` is a trivial void function. Consequently, the call inside `createItem` is removed, making that function always return `undefined`, without even calling `externalMethod` on the passed `externalObject` parameter.
In addition, even when the call is preserved, it targets a short renamed property (e.g. `b`) and not `externalMethod`.

**Comment by ChadKillingsworth** [comment]
`@export` does not imply that all other optimizations cease. It is not designed to do this nor should it.

To achieve this, you should have your code implement an external interface:

Externs:

```JavaScript
/** @interface */
function myExternalInterface() {}

/** @type {function(string):!Object} */
myExternalInterface.prototype.externalMethod;
```

Then in your actual code:

```JavaScript
/**
 * @constructor
 * @implements {myExternalInterface}
 * @export
 */
function External() {}

/**
 * @param {string} label
 * @return {!Object}
 */
External.prototype.externalMethod = function(label) {};
```

**Comment by LorenzoDV** [comment]
Oh, I see. So, in practice, compiled code is not intended to define a new interface for others to follow: only externs can do that.
Thanks for the clarification.

**Comment by ChadKillingsworth** [comment]
You can, but you have to explicitly export your methods. You also have to be aware of the differing export methods. `@export` uses an alias which doesn't work. Quoted properties would both export the interface method and force it to be external:

```JavaScript
/**
 * @param {string} label
 * @return {!Object}
 */
External.prototype['externalMethod'] = function(label) {};
```
