### ISSUE TITLE
jQuery call discarded with ADVANCED_OPTIMISATION

### ISSUE THREAD

**Issue by mrudelle** [google/closure-compiler#1037]
I am using closure compiler to compile a huge application with many externs (including Tween.js and jQuery and suprisingly one jQuery call is just discarded:
```
var test = new TWEEN.Tween({opacity:1})
	.to({opacity:0.2}, 500)
	.repeat(7)
	.delay(100)
	.yoyo(true)
	.onStart(function(){
		$("#tour").css('transition', 'none');
	})
	.onComplete(function(){
		$("#tour").css('transition', '');
	})
	.easing(TWEEN.Easing.Linear.None)
	.onUpdate( function() {
		$("#tour").css({'opacity': this.opacity});
});
```
And transformed into:
```
new TWEEN.Tween({opacity:1})).to({opacity:.2},500).repeat(7).delay(100).yoyo(!0).onStart().onComplete(function(){$("#tour").css("transition","")})...
```
Which breaks TWEEN.JS

I think this is not a desired behavior.

**Comment by ChadKillingsworth** [comment]
What externs are you using for TWEEN.js and jQuery? Somehow the compiler believes that the callback function passed to `onStart` has no side effects. The jQuery externs in this project for `jQuery.prototype.css` do not include the `@nosideeffects` annotation.

**Comment by mrudelle** [comment]
I am using the minified scripts available for download [here](https://github.com/tweenjs/tween.js) and [here](https://jquery.com/download/). Does it mean I have to get special purpose externs of all my libraries?

**Comment by ChadKillingsworth** [comment]
Those aren't externs - that is the actual source for jQuery and Tween.js. Make sure you [read the tutorial on advanced compilation](https://developers.google.com/closure/compiler/docs/api-tutorial3#comptoex).

The short answer is "yes" - you need externs for all of your code which is not compatible with Closure-compiler ADVANCED_OPTIMIZATIONS. [Community maintained externs are available for jQuery](https://github.com/google/closure-compiler/blob/master/contrib/externs/jquery-1.9.js) are available in the [contrib/externs folder of the compiler project](https://github.com/google/closure-compiler/tree/master/contrib/externs). I don't know of externs for tween.js.

You may also want to read more about the [differences in the compilation levels](http://closuretools.blogspot.com/2012/09/which-compilation-level-is-right-for-me.html).
