### ISSUE TITLE
different warning_level impacts success of compiling

### ISSUE THREAD

**Issue by K-Thompson** [google/closure-compiler#1038]
`--warning_level`

A setting for the above flag implies that one the reported warnings are going to be impacted if the flag is changed. That's not the case. That this popular public domain script:

[Cookies v1.2.1 by Scott Hamper](https://github.com/ScottHamper/Cookies)

Using the command line compiler with a release date of about April 17, 2015, if the warning_level is set to `DEFAULT` the code compiles with `SIMPLE_OPTIMIZATIONS`. If the warning level is changed to `VERBOSE` the code fails to compile and 3 errors are raised.

This has been driving me crazy with other libraries trying to figure out how they compile when I wasn't able to get them to. The problems were all caused by this flag.

Possibly this is the intended behavior. If so, then the documentation for `warning_level` should be change to indicate at a `VERBOSE` level code may not compile that compiles at the `DEFAULT` level.

**Comment by ChadKillingsworth** [comment]
This is expected.

While you might think that `--warning_level=VERBOSE` simply turns on more warnings, it is simply a convenient shortcut for `--jscomp_LEVEL=` flags. `VERBOSE` actually promotes certain classes of warnings to errors by default.

You can demote these errors back to warnings by specifying the associated warning guard: example: `--jscomp_warning=checkTypes`.
