### ISSUE TITLE
Closure compiler emits two versions of the same constructor, and one is missing a field

### ISSUE THREAD

**Issue by samuong** [google/closure-compiler#1044]
Selenium WebDriver is a browser automation tool that uses minified JavaScript from Closure to automate browser actions. Since upgrading to a newer version of the compiler, one of the JavaScript functions that we're calling is giving a different value. Here are the last known good, and first known bad versions, respectively:

$ java -jar compiler.jar --version
Closure Compiler (http://github.com/google/closure-compiler)
Version: v20141215
Built on: 2014/12/17 09:05

$ java -jar compiler.jar --version
Closure Compiler (http://github.com/google/closure-compiler)
Version: v20150609
Built on: 2015/06/09 16:35

For reference, I'm building [version 7b1e33b of selenium](https://github.com/SeleniumHQ/selenium/commit/7b1e33ba15a36ed662da4db21862aafae5175f66) using the command "./go //javascript/chrome-driver:atoms", which builds with ADVANCED_OPTIMIZATIONS (the full list of compiler switches is set [here](https://github.com/SeleniumHQ/selenium/blob/01399fffecd5a20af6f31aed6cb0043c9c5cde65/rake-tasks/crazy_fun/mappings/javascript.rb#L847)).

In [xpath.js:163](https://github.com/SeleniumHQ/selenium/blob/7b1e33ba15a36ed662da4db21862aafae5175f66/javascript/atoms/locators/xpath.js#L163) we throw an exception of type [bot.Error](https://github.com/SeleniumHQ/selenium/blob/7b1e33ba15a36ed662da4db21862aafae5175f66/javascript/atoms/error.js#L76). With v20141215 this gets compiled into:

```
throw new v(32, "Unable to locate an element with the xpath expression " + b + " because of the following error:\\n" + fb);
```

And the generated "v" class has a constructor that matches bot.Error's:

```
         function v(a, b) {
             this.code = a;
             this.state = w[a] || x;
             this.message = b || "";
             var c = this.state.replace(/((?:^|\\s+)[a-z])/g, function(a) {
                     return a.toUpperCase().replace(/^[\\s\\xa0]+/g, "")
                 }),
                 d = c.length - 5;
             if (0 > d || c.indexOf("Error", d) != d) c += "Error";
             this.name = c;
             c = Error(this.message);
             c.name = this.name;
             this.stack = c.stack || ""
         }\
```

With v20150609 the compiler emits _two_ lines for the (single) throw statement in xpath.js:

```
throw new v(32, "Unable to locate an element with the xpath expression " + b + " because of the following error:\\n" + fb);
```

and

```
throw new t(32, "Unable to locate an element with the xpath expression " + b + " because of the following error:\\n" + $a);
```

The "v" class constructor is the same in both versions, but the "t" class constructor is only generated by v20150609. It looks like this:

```
         function t(a, b) {
             this.a = u[a] || v;
             this.message = b || "";
             var c = this.a.replace(/((?:^|\\s+)[a-z])/g, function(a) {
                     return a.toUpperCase().replace(/^[\\s\\xa0]+/g, "")
                 }),
                 d = c.length - 5;
             if (0 > d || c.indexOf("Error", d) != d) c += "Error";
             this.name = c;
             c = Error(this.message);
             c.name = this.name;
             this.stack = c.stack || ""
         }\
```

Note that it's missing "this.code = a;". The result is that the error code gets lost, and gets set to a default value (13 for "unknown error") which breaks all of the error handling code that checks for this value.

**Comment by samuong** [comment]
Small correction: I'm building 5fcceb3 of the selenium repo, not 7b1e33b.

**Comment by ChadKillingsworth** [comment]
I'm not seeing anything obvious - the class appears to be properly defined, extended and instantiated.

Can you try it with the `--use_types_for_optimization=false` argument?

**Comment by MatrixFrog** [comment]
I started looking at this a little bit but I forgot to comment. Is it possible there are actually two separate compilations that get cat'd together at some point?

**Comment by samuong** [comment]
I've just tried --use_types_for_optimization=false and it works! I also ran git-bisect this afternoon and it said:

```
The first bad commit could be any of:
1f85402e991ded989584ef5a40d7817ec3d90fc2
7a5767f486300023efa514ed0bffc55fe3fbe8ce
9357b9d668bf83c08d13352f7ae01d8840743878
3fe5361f7cb1611d95fe42e32b11a7b56c922d22
```

All of which seem related to this flag.

**Comment by ChadKillingsworth** [comment]
The culprit in this case is that flag was enabled by default with the [20150315 release](https://github.com/google/closure-compiler/wiki/Releases#march-15-2015-v20150315). Usually this type of issue occurs when you lie to the type system - which is pretty easy to do inadvertently.

I'll try to look through the code this week and see if I can find the issue. You've provided some pretty good clues so hopefully I'll be able to track down the problem.

I'm closing this for now as I don't believe it's a compiler bug.

**Comment by ChadKillingsworth** [comment]
I built the source, but added the `--formatting=PRETTY_PRINT` flag. I'm not seeing a duplicated throw statement though. Did this occur in all the built files or just one in particular?

**Comment by samuong** [comment]
I can't remember if the throw statement was duplicated, but the class constructor definition definitely was.

I was seeing it occurring in build/javascript/chrome-driver/atoms.cc. This is a C++ file with some const string definitions that each contain JS code. There's a string called FIND_ELEMENT, which is the webdriver.chrome.findElement() function from javascript/chrome-driver/atoms.js. It's not easy to get at - I ran the following command and threw the result at jsbeautifier.org.

sed -n '/FIND_ELEMENT\[\]/,/NULL/p' build/javascript/chrome-driver/atoms.cc | sed -ne 's/^    "//p' | sed -e 's/",$//' -e 's/\\"/"/g' | tr -d '\n'

There's probably an easier way to do this (before it gets converted to C++) but I don't know the selenium build system well enough so this was the simplest way for me.

**Comment by ChadKillingsworth** [comment]
`build/javascript/chrome` doesn't exist on my computer even after building. I also can't find a definition of the constructor without the `this.code=` assignment.

If you can get me reproducible steps to create the file (preferably the raw closure-compiler command), then I'm willing to take a look.
