### ISSUE TITLE
[feature request] using language_out when building with ant

### ISSUE THREAD

**Issue by araker** [google/closure-compiler#1045]
I'm trying to convert from ECMA6 to ECMA5, but it seems that using closure in combination with ant doesn't support this. I'm getting this error message. I'm using the latest version of closure (v20150609).

BUILD FAILED
/Users/someDir/publish/html5/build.xml:15: jscomp doesn't support the "languageout" attribute

This is the top part of my build file 

#<?xml version="1.0"?>
<project name="Javascript compress project" basedir="/Users/someDir" default="compile">

    <taskdef name="jscomp" classname="com.google.javascript.jscomp.ant.CompileTask"
             classpath="/Users/someDir/bin/compiler-1.7.jar"/>

    <target name="compile">
        <jscomp compilationLevel="simple" 
                warning="quiet"
                debug="true" 
                output="/Users/someDir/html5/game.min.js"
                languagein="ECMASCRIPT6"
                languageout="ECMASCRIPT5"
                
                >

It would be convenient to have this functionality when using ant.

**Comment by ChadKillingsworth** [comment]
The ant task is community maintained. A PR for this feature would be welcome.

**Comment by Dominator008** [comment]
Closed by https://github.com/google/closure-compiler/pull/1342
