### ISSUE TITLE
Better Documentation of Compiler Assumptions Regarding Function Arguments

### ISSUE THREAD

**Issue by valderman** [google/closure-compiler#1046]
The Closure compiler optimizes away unused arguments from function declarations without emitting any sort of warning or other indication that dead code was encountered and removed. Additionally, this behavior does not seem to be documented.

This may break code that depends on function arities, which IMO maybe makes even unused arguments live code, if the function in question is inspected. If the current behavior is intended, it should still be explicitly documented, produce a warning when triggered, and a way provided to turn this particular optimization off on a function by function basis.

The following program will print "Length is 1, closure broke it!" when compiled with `--compilation_level ADVANCED_OPTIMIZATIONS --language_in ECMASCRIPT5_STRICT --debug`. The compiler does not print any warnings, even when explicitly turning on the `uselessCode` warning/error.

    function f(a, b) {
      return a+a;
    }
    
    function g(f) {
      if(f.length === 2) {
        console.log("Length is 2, all is well!");
      } else {
        console.log("Length is " + f.length + ", closure broke it!");
      }
    }
    
    g(f);

**Comment by ChadKillingsworth** [comment]
It's documented in two different places:

 * [Limitations for Simple Optimizations - String representations of function or parameter names](https://developers.google.com/closure/compiler/docs/limitations#restrictions-for-simple_optimizations)
 * [Github Wiki - Compiler Assumptions](https://github.com/google/closure-compiler/wiki/Compiler-Assumptions)

Since this has come up a couple of times now, I'll see about changing the documentation on Google Developers.

**Comment by dimvar** [comment]
The developers.google.com doesn't mention Function.length, only the wiki does. I can add it to the developers page as well.

**Comment by ChadKillingsworth** [comment]
Thanks @dimvar

**Comment by valderman** [comment]
Is there a rationale for no warning being thrown about dead code being eliminated? It seems to me that `uselessCode` should complain about this. (It's not called `unreachableCode` after all.)

**Comment by dimvar** [comment]
The rationale is that most optimizations don't warn when they change the code. And not everyone agrees on which subset of changes deserves a warning.

Advanced mode generally breaks code that uses reflection, is very dynamic, etc.

**Comment by valderman** [comment]
OK, got it. Thanks @dimvar!

**Comment by dimvar** [comment]
OK, done. I ended up just linking to the wiki page from the main page.

(The wiki pages are less polished, but more up to date, because they can be edited also by external contributors.)
