### ISSUE TITLE
slow/failing to compile heavily nested calls with array literals

### ISSUE THREAD

**Issue by snoe** [google/closure-compiler#1049]
Similar to #699 but using nested calls. This is a test case derived from output of the ClojureScript compiler, which translates nested clojure data structures into similar call structures.

If I put this: https://gist.github.com/snoe/b8f7b8514e48a8a8e748

in here: http://closure-compiler.appspot.com/home

It fails to compile, possibly because it is timing out.

Locally, with HEAD and latest releases I get.

```
$ time java -jar compiler.jar --js_output_file=out.js test.js

real	0m12.763s
user	0m16.760s
sys	0m0.528s
```

Increasing the nesting seems to double the compile time for each level.

**Comment by concavelenz** [comment]
See #1115 1115
