### ISSUE TITLE
Instance property incorrectly inferred as null when base class is in another module.  in ES6.

### ISSUE THREAD

**Issue by rintaro** [google/closure-compiler#1053]
test.js
```javascript
import {Base} from './test_Base';

class Child {
  constructor() {}
}

class Foo extends Base {

  constructor() {
    /** 
     * @type {Child}
     */
    this._child = null;
    super();
  }

  /** 
   * @return {!Child}
   */
  child() {
    if(this._child == null) {
      this._child = new Child();
    }   
    return /** @type {!Child} */(this._child);
  }
}

let foo = new Foo();
console.log(foo.child());
```

test_Base.js
```javascript
export class Base {
  constructor() {
    console.log("Base.construct")
  }
}
```

It seems, the compiler infers `Foo._child` as `null`, not `(Child|null)`
```
$ java -jar closure-compiler/build/compiler.jar --version
Closure Compiler (http://github.com/google/closure-compiler)
Version: v20150609-412-gbe020b8
Built on: 2015/07/31 11:57

$ java -jar closure-compiler/build/compiler.jar --jscomp_error checkTypes --language_in=ECMASCRIPT6_STRICT --language_out=ES5 --manage_closure_dependencies true test_Base.js test.js
test.js:21: ERROR - condition always evaluates to true
left : null
right: null
    if(this._child == null) {
       ^

1 error(s), 0 warning(s), 97.7% typed
```

It correctly compiles when `class Base` is in the same file of `class Foo`.

**Comment by rintaro** [comment]
Explicit cast solves the problem. 
```
    this._child = /** @type {Child} */(null);
```
 Should I always do this?

**Comment by MatrixFrog** [comment]
Interesting, I'm not sure why this would happen. You can also replace `this._child == null` with `!this._child`

**Comment by MatrixFrog** [comment]
I'm trying to understand what's happening here by building with `--skip_non_transpilation_passes --pretty_print --preserve_type_annotations`. If this._child is annotated as {Object} then it's printed as {Object} in the output. But if you make the nullability explicit ({?Object}) then it's printed as {?}. I'm guessing that's just a bug in the `--preserve_type_annotations` implementation though.

**Comment by MatrixFrog** [comment]
Smaller test case that doesn't rely on any ES6isms: https://closure-compiler-debugger.appspot.com/#input0%3D%252F**%2520%2540constructor%2520*%252F%250Afunction%2520Base()%2520%257B%257D%250A%250A%252F**%2520%2540const%2520*%252F%250Avar%2520ns%2520%253D%2520%257B%257D%253B%250A%250A%252F**%2520%2540const%2520*%252F%250Ans.Base%2520%253D%2520Base%253B%250A%250A%252F**%2520%2540constructor%2520%2540extends%2520%257Bns.Base%257D%2520*%252F%250Afunction%2520Sub()%2520%257B%250A%2520%2520%252F**%2520%2540type%2520%257B%253FObject%257D%2520*%252F%250A%2520%2520this.child%2520%253D%2520null%253B%250A%257D%250Agoog.inherits(Sub%252C%2520ns.Base)%253B%250A%250A%252F**%2520%2540return%2520%257Bvoid%257D%2520*%252F%250ASub.prototype.setChild%2520%253D%2520function()%2520%257B%250A%2520%2520if%2520(this.child%2520%253D%253D%2520null)%2520%257B%250A%2520%2520%2520%2520this.child%2520%253D%2520%257B%257D%253B%250A%2520%2520%257D%250A%257D%253B%26input1%26conformanceConfig%26externs%3Dvar%2520goog%253B%250Agoog.inherits%253B%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES%3D1%26MISSING_PROPERTIES%3D1

**Comment by MatrixFrog** [comment]
And if you change the `@extends {ns.Base}` there to just `@extends {Base}` then there's no error. So it's something to do with the fact that creating an alias with

    /** @const */
    ns.Base = Base;

doesn't quite 100% work.
