### ISSUE TITLE
Make "@constructor @extends {SomeInterface}" an error

### ISSUE THREAD

**Issue by MatrixFrog** [google/closure-compiler#1055]
It should be `@implements` rather than `@extends` of course. We make this mistake in at least one place already (fix in progress) : https://github.com/google/closure-compiler/blob/fb11a841c1aed35fc89f880a510ab3295782ead5/contrib/externs/angular-1.3-q_templated.js#L38

**Comment by Dominator008** [comment]
This is caught by TypeCheck: http://closure-compiler-debugger.appspot.com/#input0%3D%252F**%2520%2540interface%2520*%252F%250Afunction%2520Foo()%2520%257B%257D%250A%250A%252F**%2520%2540constructor%2520%2540extends%2520%257BFoo%257D%2520*%252F%250Afunction%2520Bar()%2520%257B%257D%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES%3D1%26LANG_IN_IS_ES6%3D1%26MISSING_PROPERTIES%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1%26TRANSPILE%3D1.
