### ISSUE TITLE
Repeated warning for redeclared variables

### ISSUE THREAD

**Issue by concavelenz** [google/closure-compiler#1058]
VarCheck and VariableReferenceCheck both generate warnings, however the VarCheck version is better in that is references the original location.

For reference see: 

https://travis-ci.org/google/closure-library/builds/73954039

./closure/goog/storage/mechanism/iterablemechanismtester.js:31: WARNING - Redeclared variable: mechanism
var mechanism = null;
    ^
.
.
.

./closure/goog/storage/mechanism/iterablemechanismtester.js:31: ERROR - Variable mechanism first declared in ./closure/goog/storage/mechanism/mechanismtestdefinition.js
var mechanism = null;

**Comment by blickly** [comment]
I think this is fixed now
