### ISSUE TITLE
Inline type annotations not working for @return

### ISSUE THREAD

**Issue by supersteves** [google/closure-compiler#1061]
I've been experimenting with inline type annotations as documented here (search "inline" on page):
https://developers.google.com/closure/compiler/docs/js-for-compiler

I'm putting together a WebStorm feature request for support for inline types, but am struggling to put together a comprehensive example to illustrate the syntax.

I can't get the ```@return``` example to work [EDITED]:
``` javascript
goog.module("test");
function /** number */ foo(x) { return x - 1; }
```

First, it's not clear what the ```var x = function(...)``` syntax should be.

And when I try this (which appears to be the same as the documented syntax):
``` javascript
goog.module("test");
function /** string */ fooShort(/** number */ someParam) {
    var /** string */ name = 'Jamie';
    //return name;
    return 5;
};
```
I don't get the expected compilation failure about returning 5 for a string return type, but instead get:
```
ERROR - assignment to property fooShort of $jscomp.scope
found   : function (number): ?
required: string
```
Is this a bug with the compiler or are the docs wrong?

It would also be useful to have inline types for casts, currently you seem to need to do the full ```@type {...}``` when doing a cast.

This is all part of a personal quest to reduce the verbosity of strongly typed JS development. Other ideas I've had are using flowtype (if it were a compatible syntax) or typescript (won't run in the browser directly, and closure compiler support appears to be on hold).

My long/short example I'm working on, to show all inline forms (which once confirmed would be useful to include in your wiki) - is as follows:

### Long form
``` javascript
/**
 * @param {number} someParam
 * @return {string} 
 */
var fooLong = function(someParam) {
    /** @type {string} */
    var name = 'Jamie';
    return name;
};
```
### Short form
``` javascript
function /** string */ fooShort(/** number */ someParam) {
    var /** string */ name = 'Jamie';
    return name;
};
// alternatively...
var fooShort2 = function/** string */(/** number */ someParam) {
    // ...
};
```

**Comment by supersteves** [comment]
It would also help to get clarification on the short inline form of:
``` javascript
    /**
     * @type {number?}
     * @private
     */
    this._resizeTimeoutID = null;
```
It appears I can fold this onto one line which doesn't seem to be valid jsdoc but it seems to understand it correctly (as tested by misspelling either annotation):
``` javascript
    /** @private @type {number?} */ this._resizeTimeoutID = null;
```
But for cases without ```@private```, this inline type appears to work but actually is silently ignored (no error with deliberate typo):
```
/** numbexr? */ this._resizeTimeoutID = null;
```

Also ```@type``` seems to tolerate missing braces, is it good practice to omit them?

Finally after browsing my codebase, it seems by far the most common type annotation is a cast - hence my question about a shorter inline form.

**Comment by concavelenz** [comment]
@supersteves There isn't a short form for properties.  However, for your example, "@private {?number}" is also valid.  const/public/private/protected/package all accept the associated type without the explicit @type.

**Comment by dimvar** [comment]
> First, it's not clear what the var x = function(...) syntax should be.

We currently don't support an inline return annotation for anonymous functions. Please file an issue for that. Would you prefer the annotation to be between <code>function</code> and the parentheses, to match the named-function syntax?

> And when I try this (which appears to be the same as the documented syntax):

I tried the example here http://closure-compiler.appspot.com/home and it worked fine for me (pick advanced mode which runs type checking). Maybe you did sth wrong when you tried it?

> But for cases without @private, this inline type appears to work but actually is silently ignored (no error with deliberate typo)

We only support inline types for variable declarations and functions, not property definitions. You can file an issue about that as well.

Last, to reduce verbosity of multiple annotations, I think we support the following syntax (if I remember correctly).

    /** @private {number?} */ this._resizeTimeoutID = null;

**Comment by Dominator008** [comment]
I tried the "fooShort" example on our debugger and it seems to work fine:
https://closure-compiler-debugger.appspot.com/#input0%3Dfunction%2520%252F**%2520string%2520*%252F%2520fooShort(%252F**%2520number%2520*%252F%2520someParam)%2520%257B%250A%2520%2520%2520%2520var%2520%252F**%2520string%2520*%252F%2520name%2520%253D%2520'Jamie'%253B%250A%2520%2520%2520%2520%252F%252Freturn%2520name%253B%250A%2520%2520%2520%2520return%25205%253B%250A%257D%253B%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES%3D1%26MISSING_PROPERTIES%3D1

We do recognize that some compiler passes don't quite understand inline types yet.
@supersteves Can you provide a more concrete repro case? Thanks.

**Comment by supersteves** [comment]
Hi @Dominator008 you were missing goog.module:

https://closure-compiler-debugger.appspot.com/#input0%3Dgoog.module(%2522test%2522)%253B%250A%250Afunction%2520%252F**%2520string%2520*%252F%2520fooShort(%252F**%2520number%2520*%252F%2520someParam)%2520%257B%250A%2520%2520%2520%2520var%2520%252F**%2520string%2520*%252F%2520name%2520%253D%2520'Jamie'%253B%250A%2520%2520%2520%2520%252F%252Freturn%2520name%253B%250A%2520%2520%2520%2520return%25205%253B%250A%257D%253B%250A%250Aexports%2520%253D%2520fooShort%253B%250A%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES%3D1%26CLOSURE_PASS%3D1%26MISSING_PROPERTIES%3D1

Same for 'foo' example.

**Comment by Dominator008** [comment]
I think https://github.com/google/closure-compiler/commit/3bf8ec7959abf42b6bf8dae1a0cd484d468a0002 should have fixed the issue. Could you sync to HEAD and confirm that?

**Comment by supersteves** [comment]
Doesn't the link in my last comment (same failure) go against HEAD?

**Comment by MatrixFrog** [comment]
No, it goes against whatever was the latest version when we last pushed a build of the debugger. It's a few weeks back from HEAD at the moment so I'll do a push now.

**Comment by MatrixFrog** [comment]
Having trouble with the push at the moment, but you can try building from head and I think it should be okay.

**Comment by supersteves** [comment]
OK thanks. I'll check it when I'm next working on that area.

**Comment by supersteves** [comment]
Debugger appears to have been updated. Yes, indeed fixed.
