### ISSUE TITLE
Shorter syntax for property definitions: 2. implicit @private

### ISSUE THREAD

**Issue by supersteves** [google/closure-compiler#1066]
It's very common to use underscore prefix to mark a JS property as private. We currently standardise on this in addition to explicit @private annotations.

Currently:
``` javascript
/**
 * @private
 */
this._resizeTimeoutID = null;
```

Desired:
``` javascript
this._resizeTimeoutID = null;
```

Via some compiler option such as:
```
underscorePrefixedPropertiesDefaultPrivacy = PRIVATE|PROTECTED
```

Allowing explicit @protected or @private to override it if needed.

See also https://github.com/google/closure-compiler/issues/1065

**Comment by dimvar** [comment]
We already consider trailing underscores to indicate private names, in the google coding convention.
https://github.com/google/closure-compiler/blob/a1488d59c11fd535ded79d37c11cd418927782ce/src/com/google/javascript/jscomp/GoogleCodingConvention.java#L178
Having a 2nd convention for private names in the compiler is not necessary. You can define your own coding convention if you want leading underscores.

**Comment by supersteves** [comment]
@dimvar Didn't see that before. Thanks for pointing it out! Is there any difference between using the convention and using explicit @private?

**Comment by dimvar** [comment]
> Is there any difference between using the convention and using explicit @private?
I can't think of any compilation difference.

I'd prefer <code>@private</code> for documentation purposes; someone reading your code wouldn't have to know that you're using some coding convention for private names.

**Comment by supersteves** [comment]
But in terms of enforcing privacy it's equivalent?

**Comment by dimvar** [comment]
Right.

**Comment by concavelenz** [comment]
The private coding convention isn't enforced property.  Thus we have the enforceAccessControlCodingConventions compiler option.  If this is enabled, we do.  It isn't on by default.

**Comment by supersteves** [comment]
Thanks for clarifying.
