### ISSUE TITLE
@package visibility level does not work in Windows

### ISSUE THREAD

**Issue by liolick** [google/closure-compiler#1070]
I am never getting "Access to package-private property XXX of YYY not allowed here" when compile on Windows. While on Linux I get them.
It seems that problem is in method getPackageName of DefaultCodingConvention class.
It uses platform-independent forward slashes.

Example:
```javascript
test/ns1/class1.js:
goog.provide('NS1.Class1');
/** @constructor */
NS1.Class1 = function(a)
{
    /** @package */
    this.a_ = a;
}

test/ns2/class2.js:
goog.require('NS1.Class1');
goog.provide('NS2.Class2');
/** 
 * @constructor
 * @param {NS1.Class1} c1
 */
NS2.Class2 = function(c1)
{
    /** @type {NS1.Class1} */
    this.c1_ = c1;
}
NS2.Class2.prototype.meth = function()
{
    alert(this.c1_.a_);
}

test/main.js:
goog.require('NS1.Class1');
goog.require('NS2.Class2');
var c1 = new NS1.Class1('aaa');
var c2 = new NS2.Class2(c1);
c2.meth();
```

build.bat:
java -jar ..\compiler.jar --js ns1/class1.js --js ns2/class2.js --js main.js --compilation_level ADVANCED -W VERBOSE --jscomp_error visibility --jscomp_error accessControls 

Result: 
I get `@package` - access error on Linux
I get no `@package` - access error on Windows

**Comment by dimvar** [comment]
A solution could be to define your own coding convention that works for windows.

Windows-specific fixes are not a high priority for us, since most of our users develop on linux or osx.

**Comment by ChadKillingsworth** [comment]
They are a priority for me :-) I’ll try to take a look sometime.

Chad Killingsworth

On August 12, 2015 at 11:17:38 AM, Dimitris Vardoulakis (notifications@github.com) wrote:

A solution could be to define your own coding convention that works for windows.

Windows-specific fixes are not a high priority for us, since most of our users develop on linux or osx.

**Comment by dimvar** [comment]
Great! You're now our designated Windows fixer :)
