### ISSUE TITLE
Binary Downloads Wiki Page Error

### ISSUE THREAD

**Issue by mmacfadden** [google/closure-compiler#1073]
Just a small note.  This page:

https://github.com/google/closure-compiler/wiki/Binary-Downloads

lists v20150609 as the title for the 20150729 version.

**Comment by ChadKillingsworth** [comment]
Fixed. You know it's a wiki, right?

**Comment by mmacfadden** [comment]
Stupid me.  I just assumed I wouldn't have permissions to edit it.

**Comment by ChadKillingsworth** [comment]
No worries :-)
