### ISSUE TITLE
VERBOSE does not check module dependencies

### ISSUE THREAD

**Issue by nicks** [google/closure-compiler#1084]
Repro steps:

1) Create two files:
```js
// a.js
var x = {};
var y = new x.Foo();
```

```js
// b.js
/** @constructor */ x.Foo = function () {};
```

2) Run the compiler like so:
```sh
java -jar build/compiler.jar --warning_level=VERBOSE --module modA:1 --module modB:1:modA a.js b.js
```

Expected result:
An error because I tried to create x.Foo from modA

Actual result:
No errors or warnings

tldr: I think VERBOSE should turn on strictModuleDepCheck, not sure why it's not on by default

**Comment by concavelenz** [comment]
Seem reasonable to me, want to send a PR?

**Comment by nicks** [comment]
pr sent!
