### ISSUE TITLE
Make sure there is a suspicious code warning for blocks in => functions that look like objlits.

### ISSUE THREAD

**Issue by MatrixFrog** [google/closure-compiler#1088]
See https://twitter.com/aboodman/status/633724451020890112

`["foo"].map(s => {key:s})` kind of looks like it's returning an object literal `{key:s}` but actually (spoiler alert!) the {}'s are parsed as a block, so this is equivalent to

    ["foo"].map(function(s) {
      key:
        s;
    }

where `key` is a label and `s` is a useless EXPR_RESULT. We should make sure we emit some kind of warning for this case. It looks like we don't currently: http://closure-compiler-debugger.appspot.com/#input0%3D%255B%2522foo%2522%255D.map(s%2520%253D%253E%2520%257Bkey%253As%257D)%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SUSPICIOUS_CODE%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES%3D1%26LANG_IN_IS_ES6%3D1%26MISSING_PROPERTIES%3D1

**Comment by aboodman** [comment]
Great idea. Two specific checks I can think of are:

1. Array.map() with a function that doesn't return anything.
2. Arrow functions using the block syntax where the block also parses as an object literal.

**Comment by concavelenz** [comment]
I think an unused label check would catch these kinds of these problems everywhere without special casing places they are allowed.
