### ISSUE TITLE
force rename of native-named functions in non-native objects?

### ISSUE THREAD

**Issue by leeoniya** [google/closure-compiler#1092]
Is it possible to have `ADVANCED_OPTIMIZATIONS` rename functions such as `.pushState()` when not invoked on a native `history` object or rename `.push()` when not invoked on an array? What would be the correct way to annotate these cases so they get renamed?

For instance:

```js
/**
 * @constructor
 */
function Moo() {}

Moo.prototype = {
  pushState: function(foo) {
    console.log(foo);
  }
};

var moo = new Moo();
var y = moo.pushState("123");
```

If the function is not named `pushState`, the whole thing optimizes to `console.log("123");`. I would like this behavior, but without having to physically rename all functions to appease the compiler.

thanks!

**Comment by dimvar** [comment]
If you have type checking enabled for your project, you should be able to get type-based optimizations in advanced mode.

Here is an example where Foo#push is renamed but Array#push is not.
http://closure-compiler-debugger.appspot.com/#input0%3Dfunction%2520f(%252F**%2520!Array%253Cnumber%253E%2520*%252F%2520a)%2520%257B%250A%2520%2520a.push(123)%253B%250A%2520%2520console.log(a%255B0%255D)%253B%250A%257D%250A%250Af(%255B%255D)%253B%250A%250A%252F**%2520%2540constructor%2520*%252F%250Afunction%2520Foo()%2520%257B%250A%2520%2520this.prop%2520%253D%2520123%253B%250A%257D%250A%250AFoo.prototype.push%2520%253D%2520function%2520(x)%2520%257B%250A%2520%2520this.prop%2520%253D%2520x%253B%250A%257D%253B%250A%250Afunction%2520g(%252F**%2520!Foo%2520*%252F%2520x)%2520%257B%250A%2520%2520x.push(1)%253B%250A%2520%2520console.log(x.prop)%253B%250A%257D%250A%250Ag(new%2520Foo)%253B%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES%3D1%26DISAMBIGUATE_PROPERTIES%3D1%26MISSING_PROPERTIES%3D1%26PRETTY_PRINT%3D1%26PROPERTY_RENAMING%3D1

I can't get this behavior on http://closure-compiler.appspot.com/home, probably because it's running an older version of the compiler.

**Comment by leeoniya** [comment]
thanks for looking at it. you're right, in that case it does work, but try this one out:

```js
/** @constructor */
function Foo() {
	this.x = 0;
	this.y = 0;
};

Foo.prototype = {
	blah: function() {
		console.log("blah");
		return this;
	},
	kitteh: function() {
		console.log("kitteh");
		return this;
	},
	push: function() {
		console.log("push");
		return this;
	},
	pop: function() {
		console.log("pop");
		return this;
	},
	moveTo: function(x, y) {
		this.x = x;
		this.y = y;
		console.log("moveTo");
		return this;
	},
	moveBy: function(x, y) {
		console.log("moveBy");
		return this.moveTo(this.x + x, this.y + y);
	},
};

var myFoo = new Foo();

myFoo
	.moveTo(123,456)
	.moveTo(999,888)
	.moveTo(666,555)
	.kitteh()
	.kitteh()
	.kitteh()
	.push()
	.push()
	.push()
	.moveBy(4,6)
	.moveBy(4,6)
	.moveBy(4,6)
	.moveBy(4,6)
	.pop()
	.pop()
	.pop()
	.pop()
	.blah()
	.blah()
	.blah()
	.blah();
```

compiles to this for me (beautified):

```js
function b() {
    this.b = this.a = 0
}
b.prototype = {
    push: function() {
        console.log("push");
        return this
    },
    pop: function() {
        console.log("pop");
        return this
    },
    moveTo: function(a, c) {
        this.a = a;
        this.b = c;
        console.log("moveTo");
        return this
    },
    moveBy: function(a, c) {
        console.log("moveBy");
        return this.moveTo(this.a + a, this.b + c)
    }
};

function d(a) {
    console.log("kitteh");
    return a
}

function e(a) {
    console.log("blah");
    return a
}
e(e(e(e(d(d(d((new b).moveTo(123, 456).moveTo(999, 888).moveTo(666, 555)))).push().push().push().moveBy(4, 6).moveBy(4, 6).moveBy(4, 6).moveBy(4, 6).pop().pop().pop().pop()))));
```

**Comment by ChadKillingsworth** [comment]
Try individually assigning the prototype methods instead of using an object literal. That may be the real bug here.

**Comment by leeoniya** [comment]
no luck :(

```js
/** @constructor */
function Foo() {
	this.x = 0;
	this.y = 0;
};


Foo.prototype.blah = function() {
	console.log("blah");
	return this;
};

Foo.prototype.kitteh = function() {
	console.log("kitteh");
	return this;
};

Foo.prototype.push = function() {
	console.log("push");
	return this;
};

Foo.prototype.pop = function() {
	console.log("pop");
	return this;
};

Foo.prototype.moveTo = function(x, y) {
	this.x = x;
	this.y = y;
	console.log("moveTo");
	return this;
};

Foo.prototype.moveBy = function(x, y) {
	console.log("moveBy");
	return this.moveTo(this.x + x, this.y + y);
};

var myFoo = new Foo();

myFoo
	.moveTo(123,456)
	.moveTo(999,888)
	.moveTo(666,555)
	.kitteh()
	.kitteh()
	.kitteh()
	.push()
	.push()
	.push()
	.moveBy(4,6)
	.moveBy(4,6)
	.moveBy(4,6)
	.moveBy(4,6)
	.pop()
	.pop()
	.pop()
	.pop()
	.blah()
	.blah()
	.blah()
	.blah();
```
Output:
```js
function b() {
    this.b = this.a = 0
}

function c(a) {
    console.log("blah");
    return a
}

function d(a) {
    console.log("kitteh");
    return a
}
b.prototype.push = function() {
    console.log("push");
    return this
};
b.prototype.pop = function() {
    console.log("pop");
    return this
};
b.prototype.moveTo = function(a, e) {
    this.a = a;
    this.b = e;
    console.log("moveTo");
    return this
};
b.prototype.moveBy = function(a, e) {
    console.log("moveBy");
    return this.moveTo(this.a + a, this.b + e)
};
c(c(c(c(d(d(d((new b).moveTo(123, 456).moveTo(999, 888).moveTo(666, 555)))).push().push().push().moveBy(4, 6).moveBy(4, 6).moveBy(4, 6).moveBy(4, 6).pop().pop().pop().pop()))));
```

**Comment by dimvar** [comment]
Whenever you see some properties not disambiguated, it means that the compiler is missing type information at some property access. In this case, it can't figure out the return types of the methods, so it can't tell what types push and pop are acting on in the final expression. The following code works.

<code>
/** @constructor */
function Foo() {
    this.x = 0;
    this.y = 0;
};

/** @return {!Foo} */
Foo.prototype.blah = function() {
    console.log("blah");
    return this;
};

/** @return {!Foo} */
Foo.prototype.kitteh = function() {
    console.log("kitteh");
    return this;
};

/** @return {!Foo} */
Foo.prototype.push = function() {
    console.log("push");
    return this;
};

/** @return {!Foo} */
Foo.prototype.pop = function() {
    console.log("pop");
    return this;
};

/** @return {!Foo} */
Foo.prototype.moveTo = function(x, y) {
    this.x = x;
    this.y = y;
    console.log("moveTo");
    return this;
};

/** @return {!Foo} */
Foo.prototype.moveBy = function(x, y) {
    console.log("moveBy");
    return this.moveTo(this.x + x, this.y + y);
};

var myFoo = new Foo();

myFoo
    .moveTo(123,456)
    .moveTo(999,888)
    .moveTo(666,555)
    .kitteh()
    .kitteh()
    .kitteh()
    .push()
    .push()
    .push()
    .moveBy(4,6)
    .moveBy(4,6)
    .moveBy(4,6)
    .moveBy(4,6)
    .pop()
    .pop()
    .pop()
    .pop()
    .blah()
    .blah()
    .blah()
    .blah();
</code>

**Comment by dimvar** [comment]
Arguably it could infer those types, but it doesn't at the moment. Generally, disambiguation bugs are hard to track down. One option that helps is this one:
https://github.com/google/closure-compiler/blob/master/src/com/google/javascript/jscomp/CompilerOptions.java#L507
There is no command-line flag for it, so to use it you need to call the compiler from java, or use a custom build at the moment. (We should probably add a command-line flag to help people debug their code.)

**Comment by leeoniya** [comment]
excellent, works for me.

thanks!

**Comment by ChadKillingsworth** [comment]
> i'll also point out that the repetitive .prototype really adds up in byte size and could be avoided if the literal object prototype assignment - a very common practice - was handled, but that's for another bug/improvement.

This is actually already handled. The compiler uses a heuristic to determine that if a specific prototype reference is used often enough, it will alias it. It's trying to minimize the gzip size - not the byte count of the raw compiled source.

Also in most cases a direct prototype assignment works just fine. It was simply a hunch of mine that turned out to be incorrect.
