### ISSUE TITLE
Relative namespaces in goog.module

### ISSUE THREAD

**Issue by supersteves** [google/closure-compiler#1097]
On the quest to reduce verbosity even further, using Closure Compiler with goog.module still results in long lists of requires with verbose namespaces, often purely to satisfy type annotations in jsdoc.  In a typical source file these might be 20 lines of solid text, each 100 or more characters long. Adding to the perceived cost of strong typing:

``` javascript
goog.module("some.typical.quite.long.namespace.deep.in.some.code.Thing");
var x = goog.require("some.typical.quite.long.namespace.deep.in.some.Something");
var y = goog.require("some.typical.quite.long.namespace.deep.in.some.code.SomethingElse");
var z = goog.require("some.typical.quite.long.namespace.deep.in.some.code.sub.AnotherThing");
```

Are there any ideas for introducing relative paths like in ES6 and CommonJS?

``` javascript
goog.module("some.typical.quite.long.namespace.deep.in.some.code.Thing");
var x = goog.require("../Something");
var y = goog.require("./SomethingElse");
var z = goog.require("./sub/AnotherThing");
```

Since each JS has a goog.provide/module before this, it should be possible to resolve this even when using the bundled / non compiled approach.

I'd use ES6 modules once it hit Chrome Canary, to retain non-compiled rapid development, but it seems a way off.

**Comment by Dominator008** [comment]
Have you considered goog.scope?
http://stackoverflow.com/questions/21106791/how-to-solve-google-closure-namespace-hell

**Comment by Dominator008** [comment]
Having relative paths seems to imply that the namespace structure corresponds to file paths, which is usually not true and can cause confusion.

**Comment by concavelenz** [comment]
I would like to reserve paths for ES6 modules for the time being. But some short cut might be interesting.

**Comment by concavelenz** [comment]
Closing this as this is primarily a Closure Library issue which defines the meaning of "goog.module".
