### ISSUE TITLE
Default webservice to ES6

### ISSUE THREAD

**Issue by concavelenz** [google/closure-compiler#1105]
The closure-compiler webservice should default to translate ES6->ES5, this would make the service more useful for most folks without needing to figure things out.

**Comment by Dominator008** [comment]
As of the v20151216 release, the webservice defaults to transpiling from ES6 to ES3.
Example:
https://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540compilation_level%2520SIMPLE_OPTIMIZATIONS%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250A%252F%252F%2520ADD%2520YOUR%2520CODE%2520HERE%250Alet%2520x%2520%253D%25203%253B
