### ISSUE TITLE
[Feature Request] Support notation for Dictionary type in WebIDL.

### ISSUE THREAD

**Issue by blickly** [google/closure-compiler#111]
This issue was imported from Closure Compiler's previous home at http://closure-compiler.googlecode.com

The link to the original issue is:
https://blickly.github.io/closure-compiler-issues/#1312

**Comment by Dominator008** [comment]
@yosin The event externs are currently available in the form of `@typedef`s: https://github.com/google/closure-compiler/blob/f0bae7f1e918365c061e4b92d1a6f4ef70a4f4e1/externs/browser/w3c_event.js#L75-L81
