### ISSUE TITLE
Move externs definitions out of `CommandLineRunner`

### ISSUE THREAD

**Issue by jochenberger** [google/closure-compiler#1112]
When closure-compiler is used as a library, for example within a webapp, you need to set the externs for the compilation. Usually, you'll want to use the default externs that are shipped with the compiler, as in `compiler.compile(CommandLineRunner.getBuiltinExterns(options), inputs, options)`.
Those externs should not be accessible from the `CommandLineRunner` class only, because there is not necessarily a command line involved. I suggest moving the externs-related code to a separate utility class.
Also, I'd like to exclude args4j from my dependency list and that's not possible currently. Maybe there should be separate library (without command line stuff) and standalone distributions?

**Comment by ChadKillingsworth** [comment]
I really just don't see this as being a priority for any of the compiler devs. There is overhead involved in simply maintaining 3 different distribution repositories - let alone a separate build with trimmed down functionality.

**Comment by jochenberger** [comment]
Yes, I often forget how much work those things were back in the Maven times... :-/
And I understand that it's not a priority. It's not a bug, just an improvement of code style if you ask me and it shouldn't be too much work to just move the definitions to a separate class. Maybe I'll create a PR when I find the time.

**Comment by jochenberger** [comment]
I assume this was fixed in https://github.com/google/closure-compiler/commit/b4b20ae61fc68a786315c67a9f1443556075479a.
