### ISSUE TITLE
Test iojs support in Travis

### ISSUE THREAD

**Issue by ochafik** [google/closure-compiler#1113]
Filed https://github.com/creationix/nvm/issues/815 for next-nightly support in nvm, but in the meantime it should be trivial to have a before_install that curls a suitable build from the [iojs repo](https://iojs.org/download/next-nightly/).

**Comment by ChadKillingsworth** [comment]
I'm not exactly sure what you are asking for? Can you add more context?

**Comment by concavelenz** [comment]
Reopen if clarification is provided.

**Comment by ochafik** [comment]
Oops that's embarrassing, I filed that in the wrong project (was meant to go in [dart-lang/dev_compiler](https://github.com/dart-lang/dev_compiler)).
Sorry for the noise!
