### ISSUE TITLE
[ES6] @param annotations do not work with destructuring

### ISSUE THREAD

**Issue by ewinslow** [google/closure-compiler#1114]
Simple example:

```js
class Point {
  /**
   * @param {{x:number,y:number}} point A "point-shaped" object.
   */
  constructor({x,y}) {
    this.x = x;
    this.y = y;
  }
}
```

I end up with this error:

```
ERROR - parameter point does not appear in Point's parameter list
  constructor({x,y}) {
  ^
```

**Comment by MatrixFrog** [comment]
The way we currently map `@param` annotations to params is by the names. So, since there is no param called `point`, this doesn't work. We could instead map them by index (first `@param` annotation corresponds to the first argument) but that would have other implications (If you reorder the params in a function, you'd be required to reorder the JSDoc as well. If you annotate any params then you have to annotate all of them. Probably others...)

If you only care about the types, and not the comments, then inline JSDoc should work:

    class Point {
      constructor(/** {x:number,y:number} */ {x,y}) {
        this.x = x;
        this.y = y;
      }
    }

(and if it doesn't then we can fix it) but it's not great because you end up repeating the property names twice. Other ideas?

**Comment by ChadKillingsworth** [comment]
Something like this might work:

```Javascript
class Point {
  constructor({/** number */ x, /** number */ y}) {
    this.x = x;
    this.y = y;
  }
}
```

**Comment by MatrixFrog** [comment]
:+1: Chad

**Comment by concavelenz** [comment]
This works for types but doesn't really give you a generate docs that describe the parameters without being redundant.  I think that we could allow any name for destructuring parameters and these would only be used for documentation.   

To be specific, the original example would be valid.   For this we make it (1) an error to use the name elsewhere in the parameter list (2) not declare the parameters in the right order (3) for a mismatch in the syntactically declared destructuring and declared object.

**Comment by ewinslow** [comment]
Woohoo!

**Comment by ewinslow** [comment]
So, I waited a while for change to trickle down to me, but I am still getting an error for the original use-case mentioned.

It seems the fix was implemented for plain functions, but isn't working for class or object methods.

**Comment by MatrixFrog** [comment]
Okay, I can probably revisit this today. Thanks.

**Comment by Dominator008** [comment]
@MatrixFrog I assume this is closed by https://github.com/google/closure-compiler/commit/eeba5dd1284519eb508ddd6fb670e696edb93e2d?

**Comment by MatrixFrog** [comment]
Sneaky of @blickly to do MOE pushes without even being in the office. Yes. @ewinslow please reopen if you see any further problems. Sorry for the delay.

**Comment by ewinslow** [comment]
Still not working for class constructor, but maybe the change just hasn't trickled down to Google's version of closure compiler?

**Comment by ewinslow** [comment]
Works from the head compiler! Thanks!

**Comment by tanvirjoy** [comment]
forword

**Comment by mahhov** [comment]
is there similar syntax for supporting array destructuring, or is this limited to only object destructuring?

object destructuring works:
```js
/** @param {{one: number, two: number}} o */
let destructObject = ({one, two}) => one + two;

array destructuring does not works:
```js
/** @param {[one: number, two: number]} a */
let destructArray = ([one, two]) => one + two;
```
