### ISSUE TITLE
divide is locale sensitive

### ISSUE THREAD

**Issue by twildawnight** [google/closure-compiler#1118]
The divide function seems locale sensitive.
On a computer with fr_FR as the locale (Windows 7 pro) the compiled CSS for say:

width: divide(BIG_MARGIN, 2);

Where BIG_MARGIN equals "25px" is "12,5px" (a comma). One would expect "12.5px" (a dot)

**Comment by MatrixFrog** [comment]
What divide function? I think maybe this belongs in https://github.com/google/closure-stylesheets

**Comment by twildawnight** [comment]
Yes absolutly. So sorry.
