### ISSUE TITLE
sha256 for releases

### ISSUE THREAD

**Issue by avindra** [google/closure-compiler#1120]
Hi,

Is there currently any sha256 being maintained for zip releases? A zip release being in the form of  ```http://dl.google.com/closure-compiler/compiler-${version}.zip```

Granted, I can validate the checksum on my own, but I was wondering if anything is out there already.

The sha256 hash for the last release (20150901) should be 3607931907364603571ef17e0ac62e4286fcb6ae290bd4f7e14b9773bc393cf2. Searching  for this hash produces no results, so my guess would be that Google currently does not maintain any hashes.

Thanks.

**Comment by Dominator008** [comment]
We don't currently maintain the hashes.
