### ISSUE TITLE
Controlling function renaming

### ISSUE THREAD

**Issue by andrewplummer** [google/closure-compiler#1134]
Is it possible to turn off Closure Compiler manipulation of function names, either via a compiler flag or an annotation, while still using ADVANCED_OPTIMIZATIONS?

Apologies in advance if this question has been answered elsewhere. I'm quite familiar with exports and externs (as well as when to use which), however it seems that exporting is only possible for properties and there's no way to tell the compiler to preserve function names (even globally)?

**Comment by ChadKillingsworth** [comment]
You can preserve a function in a fashion by overwriting a function defined in an extern.

```JavaScript
// ==ClosureCompiler==
// @compilation_level ADVANCED_OPTIMIZATIONS
// @output_file_name default.js
// @warning_level VERBOSE
// ==/ClosureCompiler==

alert = function(msg) {
  console.log(msg);
};

alert('hello world');
```

However, the compiler will still change the argument names.

**Comment by andrewplummer** [comment]
Sorry, I should have been more clear. I meant function names as in an actual function object's `.name` property.

In the same example:
```
alert = function alert(msg) {
  console.log(msg);
};

alert('hello world');
```

While the global `alert` is preserved here the function name from `function alert()` is stripped away. Is there any way to preserve the function's name property itself?

**Comment by ChadKillingsworth** [comment]
No - that is not supported. See #942 for more discussion on the issue.

**Comment by andrewplummer** [comment]
Ah ok... I was assuming that it wasn't possible but I didn't manage to find this issue. Thanks!
