### ISSUE TITLE
ERROR - Parse error. cannot use keyword 'type' here.

### ISSUE THREAD

**Issue by Pauan** [google/closure-compiler#1135]
When I tried to compile my ECMAScript 6 program using the Closure Compiler, I ran into this error.

Here is the smallest reproducible test case:

```
var { type } = { type: 1 };
```

And here is the error message I get:

```
test.js:1: ERROR - Parse error. cannot use keyword 'type' here.
var { type } = { type: 1 };
           ^
```

As far as I know, `type` is not a keyword or reserved word in any version of ECMAScript.

----

In addition, this code compiles perfectly fine:

```
var type = 1;
```

So it seems Closure is only treating `type` as a keyword in certain situations.

**Comment by supersteves** [comment]
I came across this too. "type" is a reserved word in TypeScript:
http://stackoverflow.com/questions/31364693/what-is-the-type-reserved-word-in-typescript

The list of reserved words in CC doesn't differentiate between the language input. In some cases you may be able to fix it using quoted property names.

I guess this is a feature request: 
*Reserved words should be dependent upon LANGUAGE_IN*

**Comment by Dominator008** [comment]
Fixing this via #1135.

**Comment by Pauan** [comment]
Thank you, I appreciate it.
