### ISSUE TITLE
Undefined $jscomp during Class Inheritence (ES6 to ES5 Strict)

### ISSUE THREAD

**Issue by evenicoulddoit** [google/closure-compiler#1138]
The following class declaration:

``` js
class Job extends JobModelMixin { ... }
```

Yields the following line when compiled into ES5-Strict, 

``` js
$jscomp.inherits(Job, JobModelMixin);
```

But is missing the definition of `$jscomp` and so throws an error.

**Comment by evenicoulddoit** [comment]
Reproducible with the following:

```js
class Foo {}
class Bar extends Foo {
  zulu() {}
}
```

(beautified)
```js
'use strict';
var Foo = function() {};
var Bar = function(var_args) {
    Foo.apply(this, arguments)
};
$jscomp.inherits(Bar, Foo);
Bar.prototype.zulu = function() {};
//# sourceMappingURL=tmp.min.js.map
```

**Comment by evenicoulddoit** [comment]
Closure Compiler (http://github.com/google/closure-compiler)
Version: v20150729
Built on: 2015/08/03 13:40

**Comment by MatrixFrog** [comment]
Can you post the list of command line flags you're using? Maybe there is an option causing the "inject runtime library" step to get skipped.

**Comment by evenicoulddoit** [comment]
Sure - sorry I figured that would help but not calling via `gulp-closure-compiler` so its a little abstracted.

Hopefully this is enough to go off:

```js
{
  compilation_level: 'WHITESPACE_ONLY',
  create_source_map: path.join(ANGULAR.dist, fileName + '.map'),
  source_map_location_mapping: 'angular/|../',
  language_in: 'ECMASCRIPT6_STRICT',
  language_out: 'ECMASCRIPT5_STRICT',
  jscomp_off: ['misplacedTypeAnnotation'],
  output_wrapper: (
    '%output%\n//# sourceMappingURL=' + fileName + '.map'
  )
}
```

**Comment by evenicoulddoit** [comment]
Just switched to `SIMPLE_OPTIMIZATIONS` and `$jscomp` is declared.

**Comment by Dominator008** [comment]
Currently, WHITESPACE_ONLY will still perform the transpilation, but it won't inject the ES6 runtime library in which $jscomp is defined.

**Comment by MatrixFrog** [comment]
I think that's intentional so that you can do per-file transpilation. It's just a little weird because if the user asked for transpilation (because the language_in and language_out are different) then obviously we have to do more than just remove whitespace. But it's not obvious that whitespace_only mode skips the runtime library. The "fix" here might just be clearer documentation.

**Comment by evenicoulddoit** [comment]
From my perspective `WHITESPACE_ONLY` means that the transpiled code is just minified, but not with obfuscation. It would be fine it `WHITEPSPACE_ONLY` couldn't handle transpilation, but as it can, to not add the required poly-fills would be unexpected?

**Comment by Dominator008** [comment]
Maybe perFileTranspilation should be a separate option so that people can explicitly not inject the runtime library when doing so?

I do think it's broken that a WHITESPACE_ONLY whole-program compilation on ES6 code definitely won't work because the runtime library won't be injected.

**Comment by shicks** [comment]
I've run into the same problem with library polyfills, and I think we
should consider these two cases together, as the es6_runtime is essentially
a library polyfilling some language features.

Ideally, I think the output of a transpilation should include some sort of
indication (possibly among its goog.requires) that it needs the runtime or
certain polyfills to be injected.  Ideally this would be handled correctly
both by re-compilation as well as by uncompiled/debug loading.

**Comment by evenicoulddoit** [comment]
Just wondering if a resolution is planned for this? The reason that I'm using `WHITESPACE_ONLY`, is so that during development I can more easily debug (Chrome doesn't actually translate the variables as specified in the sourcemaps which is super disappointing). Essentially that means I can either switch to `SIMPLE_OPTIMIZATIONS` for development and lose clarity in debugging, or not use inheritance, which is upsetting :(

**Comment by MatrixFrog** [comment]
You know I hate adding more flags but I think this is probably a case where a separate flag to specify explicitly whether to include the runtime library is a good idea.

**Comment by shicks** [comment]
Can we chat about it this afternoon?  I have a number of thoughts about polyfills in general, and would like to make sure we're on the same page.

**Comment by evenicoulddoit** [comment]
Was a resolution ever reached on this?

**Comment by rhendric** [comment]
I'd like to see this resolved too.

**Comment by MatrixFrog** [comment]
@shicks added some new options a while back to have more control over the injection of the runtime library. I'm not sure if they're all exposed in the open source command line runner yet.

**Comment by jdb8** [comment]
@MatrixFrog hey, just wondering if this has been added yet? Trying to transpile es6 code in WHITESPACE_ONLY mode and $jscomp is undefined.

Alternatively if there's a way to manually inject this somehow that would also be fine for the time being.

**Comment by Dominator008** [comment]
@jd8 `var $jscomp` is defined at https://github.com/google/closure-compiler/blob/master/src/com/google/javascript/jscomp/js/base.js#L26.
`$jscomp.inherits` is defined at https://github.com/google/closure-compiler/blob/master/src/com/google/javascript/jscomp/js/es6_runtime.js#L91. You can manually inject those files for now.

**Comment by jdb8** [comment]
@Dominator008 thanks for the quick response! Would be great if a flag could be added to do this for us (include the runtime during WHITESPACE_ONLY compilation) to simplify things.

**Comment by Dominator008** [comment]
I think there's a flag `--noinject_library` to prevent the injection from happening, and a compiler option `forceLibraryInjection` to force the injection. Unfortunately that option is not available via the command line (yet).

@shicks @MatrixFrog Should we just remove `&& !options.skipNonTranspilationPasses` from https://github.com/google/closure-compiler/blob/master/src/com/google/javascript/jscomp/DefaultPassConfig.java#L314? I suspect it requires some internal cleanup but that should be the way to go? An alternative would be exposing the `forceLibraryInjection

**Comment by jdb8** [comment]
@Dominator008 great, we managed to get it working after adding the `--noinject_library=es6_runtime` for `ADVANCED` mode (since otherwise the runtime was being injected twice which caused issues). We also had to switch to using the `LOOSE` dependency mode to avoid the es6_runtime.js and base.js files from being dropped, due to their lack of `goog.provide`s. 

Some commandline flag that could be used to achieve all this would be great to simplify the logic in our wrapper code. Otherwise perhaps some documentation on these steps, as well as a note on the es6 page that the runtime is needed for `WHITESPACE_ONLY` mode, would be very helpful.

**Comment by MatrixFrog** [comment]
There are a few flags that are only being used by a single project internally. Sometime fairly soon we'll establish the "right way" for projects to do file-by-file transpilation and then we can do a lot of flag cleanup. Unfortunately there are a few other things we'll probably need to focus on first.

**Comment by jdb8** [comment]
@MatrixFrog no worries, thanks for looking into this! Just wanted to add the solution we ended up going with in case anyone else runs into the same issue before things get updated.

**Comment by caridy** [comment]
+1 on getting a new command line option for `--noinject_library` while still remapping the calls to polyfillable features.

**Comment by lewistg** [comment]
Alternatively the closure-library now seems to ship with [transpile.js ](https://github.com/google/closure-library/blob/master/closure/goog/transpile.js), which can be manually injected in the meantime. It provides the `$jscomp` and seems to work.

**Comment by shicks** [comment]
Polyfills are no longer remapped, and you probably don't want to inject the entire 600k obfuscated transpiler just to get a few kilobytes of polyfills.

I believe `--noinject_libraries` has been working for a while (though its documentation might be a little out of whack - the option listed in `CommandLineRunner.categories` is `noinject_library`, which is wrong).

I had thought `--inject_library` was also available but I'm not seeing it right now.  Maybe I'm missing something.  In any case, if it's missing, it's certainly worth adding.

**Comment by shicks** [comment]
To clarify, in the past we rewrote calls to `new Map` as `new $jscomp.Map` - we don't do that anymore.  Now all that `RewritePolyfills` pass does is inject a runtime library to ensure that the global `Map` symbol is defined and correct.

**Comment by fejesjoco** [comment]
I was just hit by this I think. I have a mixed project where I have some goog.module's with ES6 classes and some old-school goog.provide files with goog.inherits.

With ES6 to ES5, full compilation, I see separate $jscomp$inherits and goog$inherits functions. They seem similar, both are defined and they work. I'm curious, do they actually do different things? Could you just use one of them for both cases?

When I change compilation to whitespace only, goog.inherits is defined and used, but $jscomp$inherits is used without definition.

Is there a workaround currently available for this? I see several options above but not sure which would be the most future proof, I'm too new to decode this long conversation.

**Comment by shicks** [comment]
Are you using the internal or the public compiler?  If internal, I don't
know what "whitespace only" means, since that's not a flag as I understand
it.  It hasn't always been the case, but my understanding is that for the
last few months at least, whitespace only has included runtime injection,
but I could be misremembering.

To address the question of the difference, goog.inherits is for Closure
Library, and is related to the assumptions Closure Library makes about
class structure (I don't recall what these are first-hand).
 $jscomp.inherits is an ES6-to-ES5 polyfill for the ES6 'extends' keyword.
One important difference is that ES6's extends keyword causes both instance
properties *and* static properties to be inherited, so $jscomp.inherits
actually copies the static properties from the superclass to the subclass
(this isn't strictly correct, but there's not really a reliable way to make
a constructor with a prototype other than Function using non-ES6 features),
whereas goog.inherits does not do that.  That said, the style guide frowns
on so-called static inheritance, so it should generally not be relied on.

**Comment by shicks** [comment]
whitespace-only mode is used for file-by-file transpilation, and in those cases we don't want the runtime libraries injected in every file.  There's not currently a flag to tell it to inject libraries as needed i whitespace-only mode, but you *can* explicitly request the "es6_runtime" library be injected, which should take care of your case.

**Comment by dsanders11** [comment]
@shicks, can you expand on "but you can explicitly request the "es6_runtime" library be injected". I can't see how to explicitly request that from the compiler command line, been poking around at it for several hours on v20170218.

**Comment by shicks** [comment]
There's a  command-line flag, `--inject_libraries=es6_runtime`, IIRC.  You can look in `CommandLineRunner.java` for where it's defined.

**Comment by dsanders11** [comment]
@shicks, currently `--inject_libraries` is a boolean. So functionality it implements the aforementioned `--noinject_libraries` from your August 3rd comment. [Here's the relevant line in `CommandLineRunner.java`](https://github.com/google/closure-compiler/blob/master/src/com/google/javascript/jscomp/CommandLineRunner.java#L691).

The only way I was able to get this to work was to patch `CommandLineRunner.java` to wire up `--force_inject_library` to get that functionality. [Here's a commit implementing it](https://github.com/dsanders11/closure-compiler/commit/94192ea4b4512c90f935e16e64d04ae5d0034b48). I can open a pull request if it looks good.

**Comment by ChadKillingsworth** [comment]
We're going to have a discussion soon about more control over polyfills and libraries. Feel free to comment on how you would like it to work.

I'm inclined to have the open source `--inject_libraries` flag work in the same way that the internal one does for @shicks.

**Comment by shicks** [comment]
Good catch - I was in a rush to catch a bus so didn't notice the type.  I made some comments - looks good, but ultimately I'm not sure what the team wants to do.

**Comment by ChadKillingsworth** [comment]
@shicks I think ultimately we need to have a plan for both this and with cases like #2325.

**Comment by dsanders11** [comment]
@ChadKillingsworth, does that mean delaying implementation for said plan? Was really hoping this could make it into the next release, trying to bring a legacy open source project into 2017 and not being able to easily use `WHITESPACE_ONLY` to generate debug files is a bit of a show stopper.

**Comment by ChadKillingsworth** [comment]
No don't delay it. Just try to think through all the various issues and make the change as forward thinking as possible.

I don't think the flag has many users outside of Google currently.

**Comment by dsanders11** [comment]
@ChadKillingsworth, @shicks, is there any movement on this? I responded to the comments @shicks had on the commit adding the `--force_inject_library` flag.

**Comment by ChadKillingsworth** [comment]
@dsanders11 Is there a PR for the change? I don't see one linked to this issue.

**Comment by dsanders11** [comment]
@ChadKillingsworth, I can make one, but earlier I just linked directly to [a commit in my fork](https://github.com/dsanders11/closure-compiler/commit/94192ea4b4512c90f935e16e64d04ae5d0034b48) that @shicks commented on for a preliminary look to see if it was worth opening a PR.

**Comment by dsanders11** [comment]
@ChadKillingsworth, created PR #2379 since there hasn't been any further discussion and I'd really like to see this functionality in the next release version.

**Comment by bradw2k** [comment]
FWIW, my workaround is to compile first with SIMPLE_OPTIMIZATIONS, grab the first ~214 lines produced which define $jscomp, save those lines off as jscompPolyfill.js, then load that file before including the file produced by a WHITESPACE_ONLY compilation. I'm using the google-closure-compiler-js gulp wrapper, so not sure I have access to all of the compiler options I'd otherwise need.

**Comment by sbc100** [comment]
We are trying to use `WHITESPACE_ONLY` in emscripten to perform transpilation and running into this issue (see https://github.com/emscripten-core/emscripten/pull/15763).

We would like the polyfills to be included on demand and we don't want to switch to `SIMPLE_OPTIMIZATIONS` because this will both slow down the linker and also made debugging harder.

I tried adding `--force_inject_library=es6_runtime` but that injects all 2705 lines of polyfill into the output.   The on-demand inclusion of the polyfills only injects 547 lines.

It seems like there should be some way to enabled `WHITESPACE_ONLY` without also disabling the injection of the polyfills.

**Comment by sbc100** [comment]
I should not that my initial attempt was to add  `--inject_libraries` with `--compilation_level WHITESPACE_ONLY` but it seems that `--inject_libraries` is completely ignored in this mode. 

I wonder if an easy fix for this would be honor `--inject_libraries` in `WHITESPACE_ONLY` mode?   If not it should probably generate an error.

**Comment by brad4d** [comment]
The logic for injecting polyfills relies on optimizations to remove the unused / unnecessary ones, so injecting them is incompatible with `WHITESPACE_ONLY` mode.

Your use-case is really pretty far outside of the primary aims of closure-compiler.
It's intended for compiling really large JS applications with as much optimization as possible.
It sounds like you only need JS glue code to wire up your WASM binaries.

If you only want basic minimization and transpilation of language features, there are better tools for you than closure-compiler. Perhaps Babel would be a better choice.

**Comment by sbc100** [comment]
Sorry, perhaps "glue code" is not the correct term to use here.  The JS code generated by emscripten can be fairly large.   We have customers with large code bases who rely on the code size optimization offered by closure compile that no other tool provides.  We depend on `ADVANCED_OPTIMIZATIONS` for release builds and we haven't found any other tool that can match it.

**Comment by brad4d** [comment]
If that's the case, why not use at least SIMPLE_OPTIMIZATIONS mode?

**Comment by sbc100** [comment]
IIRC it was because we want to be able to do transpilation in debug mode where we want to build to be fast and the output to be readable (ish).   But that is indeed an option...

**Comment by sbc100** [comment]
(I well re-investigate the option of forcing SIMPLE_OPTIMIZATIONS even for debug builds when transpiling is requested)

**Comment by sbc100** [comment]
We ended up switch to `SIMPLE_OPTIMIZATIONS` for now: https://github.com/emscripten-core/emscripten/pull/20700
