### ISSUE TITLE
Compilation slow/timeouts on deeply nested objects

### ISSUE THREAD

**Issue by aboks** [google/closure-compiler#1148]
Similar to #1049 and #699, the closure compiler appears to be extremely slow for deeply nested objects. The online compiler service (http://closure-compiler.appspot.com/home) fails with a timeout on https://gist.github.com/aboks/e09df634ab904587cb5d. 

With the current version of the compiler jar (v20150901), compilation of that sample takes about 45s on my machine. For comparison, an earlier version (v20121212) took only 1.7s.

**Comment by MatrixFrog** [comment]
https://github.com/google/closure-compiler/issues/1115 may help here.
