### ISSUE TITLE
Output source map does not use input source maps

### ISSUE THREAD

**Issue by blickly** [google/closure-compiler#115]
This issue was imported from Closure Compiler's previous home at http://closure-compiler.googlecode.com

The link to the original issue is:
https://code.google.com/p/closure-compiler/issues/detail?id=1296

**Comment by nalbion** [comment]
Would this make it possible to chain AtScript/ES6->ES5 transpilation using Traceur followed by minification using Closure?  ...and all you need to do is add the option to the command line handler?  Surely Google & Angular2 devs are doing this already?

**Comment by MatrixFrog** [comment]
It should work, but I don't know if anyone is using that particular workflow right now. And yes, we (by "we" I mean "someone" -- feel free to send a pull request) should probably add an option in the CommandLineRunner.

**Comment by mprobst** [comment]
I'll poke at this.

**Comment by tleunen** [comment]
Great thanks @mprobst

**Comment by mprobst** [comment]
To be clear @tleunen, this allows you to specify input source maps so that error messages print both the original and the post-transpilation (or whatever) location. It does not produce a merged source map after compilation.

**Comment by joelrich** [comment]
@mprobst are there any plans to produce a merged source map file?

**Comment by ChadKillingsworth** [comment]
@joelrich No - composed source maps are not planne, but they may be obtained via a post-compile step. Composing a source map automatically loses too much data when non-trivial transforms are encountered. See [the source maps wiki page](https://github.com/google/closure-compiler/wiki/Source-Maps) for details.  The [gulp plugin](https://github.com/chadkillingsworth/closure-compiler-npm) automatically composes source maps.

**Comment by joelrich** [comment]
@ChadKillingsworth thanks for the quick response. I cannot use gulp in this particular case, but I will check how it is implemented there.

**Comment by ChadKillingsworth** [comment]
@joelrich Here's the relevant lines: https://github.com/ChadKillingsworth/closure-compiler-npm/blob/master/lib/gulp/index.js#L146

**Comment by codecrackerx9** [comment]
Is there any plans for a grunt plugin for source maps? Thanks!

**Comment by ChadKillingsworth** [comment]
You can already use source maps in grunt. You just have to manually wire it all together. See the [`--source_map_input` flag](https://github.com/google/closure-compiler/blob/592a877e21c8ff2b3d60444da9f2cf5d833adf45/src/com/google/javascript/jscomp/CommandLineRunner.java#L331-L337)
