### ISSUE TITLE
Web interface occasionally removes pluses then errs when compiling

### ISSUE THREAD

**Issue by oneeyedziggy** [google/closure-compiler#1152]
Compiling:
```js
function hello(name) {
  alert('Hello, ' + name);
}
hello('New user');
```
with  http://closure-compiler.appspot.com/home

yields a page with this on the left (missing the '+'):
```js
function hello(name) {
  alert('Hello, '   name);
}
hello('New user');
```
and the error below on the right:
```
JSC_PARSE_ERROR: Parse error. ',' expected at line 3 character 20
alert('Hello, '   name);
                  ^
```

**Comment by frumbert** [comment]
Confirmed with me too under certain conditions:

Firefox 40.0.3 (OSX 10.10.5) will change this code:

    var a = "scale(" + scale + "," + scale + ") translateY(" + hdiff + "px)";
    var b = 'scale(' + scale + ',' + scale + ') translateY(' + hdiff + 'px)';
    var c = ["scale(",scale,",",scale,") translateY(",hdiff,"px)"].join();

into this code (after pressing Compile):

    var a = "scale("   scale   ","   scale   ") translateY("   hdiff   "px)";
    var b = 'scale('   scale   ','   scale   ') translateY('   hdiff   'px)';
    var c = ["scale(",scale,",",scale,") translateY(",hdiff,"px)"].join();

Chrome 45.0.2454.93 (64-bit)  (OSX 10.10.5)  will not change the input code at all, nor does Safari 8.0.8 (10600.8.9)

**Comment by ChadKillingsworth** [comment]
I can confirm this - thanks for the repo case.

The `+` operator is removed from the source side when the "compile" button is pressed. It also occurs with the initial sample code.

**Comment by blickly** [comment]
Smaller repro:
http://closure-compiler.appspot.com/home#code%3D3%2520%252B%25204%253B

**Comment by concavelenz** [comment]
Seems to be some side-effect of refreshing the snippet when the fragment is updated.  I'm not sure why the Firefox behavior is different.

**Comment by ChadKillingsworth** [comment]
This is becoming a bigger issue - we're getting more and more error reports.

https://groups.google.com/forum/#!topic/closure-compiler-discuss/zq4LYnZlmu0

**Comment by mprobst** [comment]
A common issue causing things like this is the ambiguity between whitespace encoded as + in URLs vs the actual plus character. Seems like either the sender doesn't encoded the + or the receiver double decodes (which seems less likely).

**Comment by concavelenz** [comment]
It just odd that it is ff only

**Comment by Dominator008** [comment]
Seems like this has been fixed after we moved to CodeMirror for the editor.
