### ISSUE TITLE
ES6 runtime uses ES5 features even with --language_out=ES3

### ISSUE THREAD

**Issue by ochafik** [google/closure-compiler#1153]
[Object.getOwnPropertyDescriptor](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/getOwnPropertyDescriptor) and [Object.defineProperty](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty) are referenced `$jscomp.inherit`.
```
echo "
  'use strict';
  class A {}
  class B extends A {}
  new B();
" | java -jar compiler.jar --language_in=ES6_STRICT --language_out=ES3 -O SIMPLE
```

Note that other features like getters/setters require ES5 output already, so it seems to me classes should do the same...?

**Comment by MatrixFrog** [comment]
They're referenced, but should never be called if you're in an ES3 browser. Are you seeing runtime errors?

**Comment by ochafik** [comment]
Oops sorry for the noise, awesome!
