### ISSUE TITLE
Cannot prevent renaming of static class property using externs

### ISSUE THREAD

**Issue by supersteves** [google/closure-compiler#1155]
React's ES6 classes approach to React Components requires a class / static property "childContextTypes" to be defined if using contexts (the same goes for the more familiar React concepts "propTypes" and "defaultProps"):
``` javascript
class X extends React.Component {}
X.childContextTypes = {};
```
I can't find a way to prevent this being renamed or removed (other than using [""] notation, or exportSymbol, which requires my non-CC-savvy developers to remember to use this pattern - somewhat error prone. Here are some externs I've tried:
``` javascript
Object.childContextTypes;
React.Component.childContextTypes;
React.Component.prototype.childContextTypes;
```
I would have thought that the ```Object.childContextTypes``` approach would prevent this property being removed or renamed on every type it was found upon.

I've tried to find the minimum options in the debugger that show this. However I think there's more than one combination. In my use case, I'm compiling using advanced level, and the propTypes and childContextTypes lines are both being removed. Not sure which of the debugger tickboxes correspond to advanced.

Here's one combination which shows it being renamed:
https://closure-compiler-debugger.appspot.com/#input0%3Dclass%2520X%2520extends%2520React.Component%2520%257B%250A%2520%2520%2520%2520constructor()%2520%257B%250A%2520%2520%2520%2520%2520%2520%2520%2520super(%257B%257D)%253B%250A%2520%2520%2520%2520%2520%2520%2520%2520console.log(%2522here%2522)%253B%250A%2520%2520%2520%2520%257D%250A%257D%250A%250AX.propTypes%2520%253D%2520%257B%257D%253B%250AX.childContextTypes%2520%253D%2520%257B%257D%253B%250A%250Anew%2520X()%253B%26input1%26conformanceConfig%26externs%3Dvar%2520React%2520%253D%2520%257B%257D%253B%250A%250A%252F**%250A%2520*%2520%2540constructor%250A%2520*%2520%2540param%2520%257BObject%253C%253F%252C%253F%253E%257D%2520props%250A%2520*%252F%250AReact.Component%2520%253D%2520function(props)%2520%257B%257D%253B%250A%250AObject.childContextTypes%253B%250AReact.Component.childContextTypes%253B%250AReact.Component.prototype.childContextTypes%253B%250A%250A%26refasterjs-template%26includeDefaultExterns%3D1%26CLOSURE_PASS%3D1%26COLLAPSE_PROPERTIES%3D1%26LANG_IN_IS_ES6%3D1%26VARIABLE_RENAMING%3D1

And here's one which shows it being removed:
https://closure-compiler-debugger.appspot.com/#input0%3Dclass%2520X%2520extends%2520React.Component%2520%257B%250A%2520%2520%2520%2520constructor()%2520%257B%250A%2520%2520%2520%2520%2520%2520%2520%2520super(%257B%257D)%253B%250A%2520%2520%2520%2520%2520%2520%2520%2520console.log(%2522here%2522)%253B%250A%2520%2520%2520%2520%257D%250A%257D%250A%250AX.propTypes%2520%253D%2520%257B%257D%253B%250AX.childContextTypes%2520%253D%2520%257B%257D%253B%250A%250Anew%2520X()%253B%26input1%26conformanceConfig%26externs%3Dvar%2520React%2520%253D%2520%257B%257D%253B%250A%250A%252F**%250A%2520*%2520%2540constructor%250A%2520*%2520%2540param%2520%257BObject%253C%253F%252C%253F%253E%257D%2520props%250A%2520*%252F%250AReact.Component%2520%253D%2520function(props)%2520%257B%257D%253B%250A%250AObject.childContextTypes%253B%250AReact.Component.childContextTypes%253B%250AReact.Component.prototype.childContextTypes%253B%250A%250A%26refasterjs-template%26includeDefaultExterns%3D1%26CLOSURE_PASS%3D1%26COLLAPSE_PROPERTIES%3D1%26LANG_IN_IS_ES6%3D1%26REMOVE_DEAD_CODE%3D1%26SMART_NAME_REMOVAL%3D1

**Comment by ChadKillingsworth** [comment]
A static property like that isn't inherited from a parent and therefore externs will have no impact on it's renaming - unless the type based optimizations are disabled (`--use_types_for_optimization=false`). To prevent renaming and collapsing of a static property on a class, your only option is to use quoted properties.

If you make it a class property, then externs will work:

```JavaScript
X.prototype.childContextTypes = {};
```

I realize that ES6 classes have no shortcut method to define a property like this as the spec pushes developers to use getters and setters.

Or as an instance property in the constructor:

```JavaScript
constructor() {
  super({});
  console.log("here");
  this.childContextTypes = {};
}
```

**Comment by supersteves** [comment]
Thanks @ChadKillingsworth. Unfortunately I'm not able to choose to use a class property since this is the React spec/requirement. 

Not sure what you mean about no shortcut method.

For cases like this and presumably others, some possibilities:

1. allow a way of giving a type name to the class object (well, constructor) itself, to allow extern'ing its properties;

2. allow some kind of wildcard extern that prevents tells CC "this property name might exist or be used on ANY object" hence don't rename or remove it?

Meanwhile I'll manage with quoted properties.

**Comment by ChadKillingsworth** [comment]
For 1) A class is a type. But static properties attached are not part of that type. They are an entirely different object/type. This is intrinsic to the compiler's type system.

For 2) This is the behavior when the type-based optimizations are disabled. See https://github.com/google/closure-compiler/wiki/FAQ#some-of-my-properties-are-getting-renamed-but-some-arent-why
You will also need the `@nocollapse` annotation to prevent the property from being removed from the class.

**Comment by supersteves** [comment]
Understood. It would be useful to be able to prevent this without using quoted property access and without disabling fundamental parts of the optimisation and obfuscation; React is a tiny part of our large codebase. I'm using quoted names and have added a custom eslint rule to my project to fail if a developer forgets.

**Comment by concavelenz** [comment]
There are two issues here:  property collapsing and property renaming.  Property collapsing converts properties to variables (see https://developers.google.com/closure/compiler/docs/limitations?hl=en#implications-of-object-property-flattening).  

You can work around the inheritance problem Chad talks about  by declaring the property name on Object.prototype or Function.prototype in the externs (prevents renaming). AND then use @nocollapse on the property in your code.      The compiler currently will never remove a non-collapse constructor property (see https://github.com/google/closure-compiler/wiki/Understanding-Property-Removal) unless then entire class isn't referenced.

We would like to soften property collapsing but when we do we will likely also enable direct unused constructor property removal (when that happens, your original external solution will work) and ES6 class promote "class-side" constructor property inheritance.

**Comment by joscha** [comment]
> I'm using quoted names and have added a custom eslint rule to my project to fail if a developer forgets.

@supersteves 🎉  would you be happy to share that rule?

**Comment by supersteves** [comment]
@joscha Sure, it's an eslint plugin you'll need to add to your .eslintrc:
``` javascript
"use strict";

module.exports = {

	// http://eslint.org/docs/developer-guide/working-with-rules
	// https://github.com/estree/estree
	// https://github.com/estree/estree/blob/master/es2015.md
		
	rules: {
		"no_react_dotted_static_props": function(context) {
			// Prevents you using class X extends React.Component
			// then adding X.defaultProps etc.; these must be accessed as X["defaultProps"]
			// as there is no way to avoid Closure renaming/removing them:
			// https://github.com/google/closure-compiler/issues/1155
			
			return {
				"AssignmentExpression": function(node) {
					
					// VERY primitive check:
					if (context.getSource().indexOf("React.Component")>=0) {
						var code = context.getSource(node);
						
						if (code.indexOf(".defaultProps")>=0 || 
							code.indexOf(".propTypes")>=0 || 
							code.indexOf(".childContextTypes")>=0)
						{
							context.report(node, 
									"Dotted access to defaultProps/propTypes/childContextTypes is not allowed " +
									"and will be renamed and/or removed by Closure Compiler. " +
									"You must use [\"\"] notation instead, e.g. MyClass[\"propTypes\"] = {...};");
						}
					}
				}
			};
		}
    },
    rulesConfig: {
        "no_react_dotted_static_props": [2]
    }
};
```
