### ISSUE TITLE
Transpiled ES6 getters / setters take a lot of space (& should not be enumerable)

### ISSUE THREAD

**Issue by ochafik** [google/closure-compiler#1158]
```javascript
class A {
  get x() { return 1 }
}
console.log(new A().x);
```
Is currently [compiled](http://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540compilation_level%2520ADVANCED_OPTIMIZATIONS%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%2540formatting%2520pretty_print%250A%252F%252F%2520%2540language%2520ES6%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250Aclass%2520A%2520%257B%250A%2520%2520get%2520x()%2520%257B%2520return%25201%2520%257D%250A%257D%250Aconsole.log(new%2520A().x)%253B) to:
```javascript
function a() {
}
Object.defineProperties(a.prototype, {x:{configurable:!0, enumerable:!0, get() {
  return 1;
}}});
console.log((new a).x);
```
(note: ideally, that specific getter should just be inlined, see #1157; discussing here what should happen to non-inlineable getters / setters)

According to the spec ([ClassDefinitionEvaluation](http://www.ecma-international.org/ecma-262/6.0/#sec-runtime-semantics-classdefinitionevaluation)): `PropertyDefinitionEvaluation for m with arguments proto and false` (i.e. `enumerable = false` in [PropertyDefinitionEvaluation](http://www.ecma-international.org/ecma-262/6.0/#sec-method-definitions-runtime-semantics-propertydefinitionevaluation)).

Eliding the `enumerable:!0` for getters/setters would make the generated code shorter (note that respecting this for methods as well would produce larger code than the current `A.prototype.m = body` output and would make ES6 classes behave differently from old-style Closure classes).

Regarding `configurable`, it should indeed be `true` for class members but I'm not sure how much this conflicts with the general idea of [@struct](https://github.com/google/closure-compiler/wiki/@struct-and-@dict-Annotations), any thoughts?

Note that respect of `enumerable` & `configurable` semantics + smaller output could be achieved with something like the following (with its own drawbacks, like complexity / size / speed of the extend helper):
```javascript
$jscomp.extend(a.prototype, {
  get x() { .... }
})
```

**Comment by rikuayanokozy** [comment]
https://github.com/rikuayanokozy/closure-compiler/commit/8167246f91f5439552ffa9f942f7ba5274a9b39e
I just rewrote the Es6ToEs3Converter.
It's still has problem in following:
- ** JSDoc is currently not works **, so type check test cannot be passed
- Computed property doesn't support, currently fallback to Object.defineProperties
- $jscomp.extend is direct copied from closure library and need rewrite

I have not time to fix it now, but i'll fix it as soon as possible, or contribute welcome.

**Comment by MatrixFrog** [comment]
Since #1217 was merged I assume we can close this.
