### ISSUE TITLE
static check: ES6 constructors whose class extends another class must call super

### ISSUE THREAD

**Issue by ChadKillingsworth** [google/closure-compiler#1159]
We should enforce (at an error level) when an es6 class extends a parent and defines a constructor, but fails to call super.

See http://stackoverflow.com/a/31079103/1211524

``` JavaScript
class foo extends bar {
  constructor() {
    // no call to super() - this is an error
    this.foobar = 'foobar';
  }
}
```

**Comment by MatrixFrog** [comment]
This should be easy-ish for someone wanting to land their first closure-compiler patch. Marking help-wanted though a good-first-bug label might be worth having too.

**Comment by MatrixFrog** [comment]
@sdierauf is giving this a shot.

**Comment by ChadKillingsworth** [comment]
It's not quite as easy at you make it seem. You have to trace through exit paths.

**Comment by MatrixFrog** [comment]
We could copy the Java rule that super() has to be the first call in the constructor, but I doubt we want to be that strict. Otherwise, you're right, you probably need the ControlFlowGraph.

**Comment by ChadKillingsworth** [comment]
I have implementations where super is definitely not the first call.

**Comment by sdierauf** [comment]
Just so I'm understanding correctly, a case such as 
```
constructor() {
  if () {
    if () {
      super()
    else {
      super()
  }
  super()
}
```
would still be valid?

**Comment by ChadKillingsworth** [comment]
I believe yes - but you are calling it twice with that last call. Switch statements, throws and returns make this even more complicated.

**Comment by concavelenz** [comment]
This isn't much different that "check missing return", you should use the same CFG assuming it has been updated to ES6.

**Comment by supersteves** [comment]
I've hit this a couple of times recently, forgetting to call super() in my constructor and getting weird non-initialised super state. 

@ChadKillingsworth regarding this:
> I have implementations where super is definitely not the first call.

I know this used to be allowed but no longer according to ES2015 spec:
http://stackoverflow.com/a/31079103/687702
(or am I misreading you?)

Perhaps this issue should be revised to specifically require super() call to be present and before any ```this.*``` access.

**Comment by ChadKillingsworth** [comment]
@supersteves See #1160

**Comment by supersteves** [comment]
OK, separate bug for that. I was questioning your above comment:
https://github.com/google/closure-compiler/issues/1159#issuecomment-159420015

**Comment by ChadKillingsworth** [comment]
You are misreading. `super()` is not required to be the first call. This is valid in ES6:

```js
class MyPromise extends Promise {
  constructor() {
    let resolve, reject;
    super(function(res) {
      resolve = res;
    }, function(rej) {
      reject = rej;
    });
    this.resolve = resolve;
    this.reject = reject;
  }
}
```

**Comment by supersteves** [comment]
Duh, my bad. Sorry!

**Comment by Dominator008** [comment]
This is related to #278.

**Comment by concavelenz** [comment]
I think the important thing is that "this" isn't valid until you can "super" (if I recall correctly)

**Comment by ChadKillingsworth** [comment]
@concavelenz It's also an error even if you don't explicitly reference the `this` keyword: https://jsfiddle.net/y9mjqe06/

```
VM93:50 Uncaught ReferenceError: this is not defined
```

**Comment by ChadKillingsworth** [comment]
This was fixed at some point.
