### ISSUE TITLE
Closure compiler incorrectly infers the type of 'this' in Function.prototype.bind.

### ISSUE THREAD

**Issue by blickly** [google/closure-compiler#116]
This issue was imported from Closure Compiler's previous home at http://closure-compiler.googlecode.com

The link to the original issue is:
https://code.google.com/p/closure-compiler/issues/detail?id=1298

**Comment by concavelenz** [comment]
I think this is fixed now?

**Comment by dimvar** [comment]
Yes, for the case when the bound function is a function literal.
