### ISSUE TITLE
'use strict' at the top of functions is removed by transpiler

### ISSUE THREAD

**Issue by shicks** [google/closure-compiler#1169]
```
exports = {
  includes(searchString, index) {
    'use strict';
    const str = this.toString(); // throws TypeError if this is null
    // ...
  }
}
```
transpiles to
```
string = {includes: function(searchString, index) {
  var str = this.toString(); // returns '[object Window]' if this is null
  // ...
}};
```
which, unfortunately, has different behavior.  We should take care to retain any `'use strict'` in function declarations.

**Comment by concavelenz** [comment]
The compiler doesn't track strick mode per function. goog module and es6 modules are always strict. So in those cases it isn't necessary.

**Comment by dimvar** [comment]
Relevant discussions:
https://code.google.com/p/closure-compiler/issues/detail?id=69
https://github.com/google/closure-compiler/issues/997

**Comment by shicks** [comment]
Gotcha - my output language was non-strict, so it was dropping the 'use strict' at the file level.  Setting the output language to ES5_STRICT fixes the issue.
