### ISSUE TITLE
Enabling instrumentation via command line switch

### ISSUE THREAD

**Issue by mweissbacher** [google/closure-compiler#1173]
The instrumentation feature of Closure is not usable externally, which is too bad as this seems rather useful. E.g., for tracing code execution in the client.

I implemented a [patch](https://github.com/mweissbacher/closure-compiler/commit/107a84e689cfc50122afa2d1161dbc1be6804fe8) to enable JS instrumentation via CLI as part of a larger project. If you think this should be part of mainline Closure I can send a pull request.

Thanks,

**Comment by dimvar** [comment]
Hi. Yes, please submit your patch as a pull request.
