### ISSUE TITLE
Document.prototype.registerElement extern should have an optional second argument

### ISSUE THREAD

**Issue by pstjvn** [google/closure-compiler#1174]
Currently in the extern file ```browser/html5.js``` annotation for ```registerElement``` does not return anything, however the specification says it should return constructor function. 

Unfortunately I am not sure how to annotate that in an extern file, but hopefully someone will know and it will be fixed so I can use named constructors for new custom elements.

**Comment by ChadKillingsworth** [comment]
Actually the lack of an `@return` annotation means that the function returns the unknown type. That's probably about the best we can do. It allows this code to work as expected:

```JavaScript
/**
 * @constructor
 * @extends {HTMLElement}
 */
var mytag = document.registerElement('foo-bar', {});

var mytagInstance = new mytag();
console.log(mytagInstance.innerHTML);
var a = mytagInstance.foobar; //gives the expected 'Property foobar never defined' warning.
console.log(a);
```

However, the second parameter to the `registerElement` function should be optional. I'll correct that.

**Comment by pstjvn** [comment]
This is exactly how I used it actually. Thanks for the explanation.
