### ISSUE TITLE
"var chrome" results in error

### ISSUE THREAD

**Issue by Profforgr** [google/closure-compiler#1180]
Hi.

```javascript
var chrome = navigator.userAgent.toLowerCase().indexOf("chrome") != -1;
```

results in error:

```javascript
Number of errors: 1

JSC_CONSTANT_REASSIGNED_VALUE_ERROR: constant chrome assigned a value more than once.
Original definition at http://closure-compiler.appspot.com/externs.js:13675 at line 2 character 4
var chrome = navigator.userAgent.toLowerCase().indexOf("chrome") != -1;
    ^
```

I understand, that "chrome" var is included in externs.js, but perhaps Closure Compiler should at least work correctly with the following code (which now results in the error either):

```javascript
if(typeof chrome != 'undefined') { var chrome = navigator.userAgent.toLowerCase().indexOf("chrome") != -1; }
```

**Comment by concavelenz** [comment]
Workaround should be:

/** @suppress {duplicate, const} */
var chrome = ...

Alternately, you can use a custom set of externs or wrap your code to prevent the use of globals (goog.module, ES6 modules, CommonJS modules can all be used to do this).

**Comment by Profforgr** [comment]
> Workaround should be:
> 
> /** @suppress {duplicate, const} */
> var chrome = ...
> 
> Alternately, you can use a custom set of externs or wrap your code to prevent the use of globals (goog.module, ES6 modules, CommonJS modules can all be used to do this).

Thanks. I were thinking it should be fixed globally (if this is an issue). If it's the logic of compiler and is not going to be fixed, then i'll use workaround.

**Comment by ChadKillingsworth** [comment]
It's not an issue - just that the symbol `chrome` is defined in the default extern set. Suppressing the duplicate is the correct answer (or preventing your code from executing in the global scope).
