### ISSUE TITLE
Type annotations don't work in enhanced object literals

### ISSUE THREAD

**Issue by supersteves** [google/closure-compiler#1185]
Using an enhanced object literal (e.g. when exporting a function directly), type annotations are silently ignored. This came to light when experimenting with 100% typing and report unknown types.

``` javascript
exports = {

    /**
     * @param {string} a
     * @return {number}
     */
    problem1(a) {
        return a.length;
    },

    /**
     * @param {string} a
     * @return {number}
     */
    problem1b(/* string */a) {
        return a.length;
    },

    /**
     * @param {string} a
     * @return {number}
     */
    notAProblem: function(a) {
        return a.length;
    }

};
```

Here both problem1a and problem1b are typed as
```
function (?): ?
```

but notAProblem is typed correctly as
```
function (string): number
```

Ideally there would be an error if type definitions were used in ways that wasn't yet supported. Otherwise you get a false sense of security only revealed by deliberately introducing mistakes and noticing it doesn't fail compilation, or by enabling report unknown types, which yields 1000s of errors in typical codebases.

https://closure-compiler-debugger.appspot.com/#input0%3Dexports%2520%253D%2520%257B%250A%250A%2520%2520%2520%2520%252F**%250A%2520%2520%2520%2520%2520*%2520%2540param%2520%257Bstring%257D%2520a%250A%2520%2520%2520%2520%2520*%2520%2540return%2520%257Bnumber%257D%250A%2520%2520%2520%2520%2520*%252F%250A%2520%2520%2520%2520problem1(a)%2520%257B%250A%2520%2520%2520%2520%2520%2520%2520%2520return%2520a.length%253B%250A%2520%2520%2520%2520%257D%252C%250A%250A%2520%2520%2520%2520%252F**%250A%2520%2520%2520%2520%2520*%2520%2540param%2520%257Bstring%257D%2520a%250A%2520%2520%2520%2520%2520*%2520%2540return%2520%257Bnumber%257D%250A%2520%2520%2520%2520%2520*%252F%250A%2520%2520%2520%2520problem1b(%252F*%2520string%2520*%252Fa)%2520%257B%250A%2520%2520%2520%2520%2520%2520%2520%2520return%2520a.length%253B%250A%2520%2520%2520%2520%257D%252C%250A%250A%2520%2520%2520%2520%252F**%250A%2520%2520%2520%2520%2520*%2520%2540param%2520%257Bstring%257D%2520a%250A%2520%2520%2520%2520%2520*%2520%2540return%2520%257Bnumber%257D%250A%2520%2520%2520%2520%2520*%252F%250A%2520%2520%2520%2520notAProblem%253A%2520function(a)%2520%257B%250A%2520%2520%2520%2520%2520%2520%2520%2520return%2520a.length%253B%250A%2520%2520%2520%2520%257D%250A%250A%257D%253B%250A%26input1%26conformanceConfig%26externs%26refasterjs-template%26CHECK_TYPES%3D1%26LANG_IN_IS_ES6%3D1

**Comment by MatrixFrog** [comment]
It looks like we're copying over the JSDoc in Es6ToEs3Converter.visitMemberFunctionDefInObjectLit so I'll have to find out why that's not actually working.

**Comment by MatrixFrog** [comment]
It looks like the debugger was just out of date; I just pushed a new version of it. Your link should work now (except you'll also need to check the TRANSPILE box).

**Comment by supersteves** [comment]
@MatrixFrog Great, thanks. I'll update my fork.
