### ISSUE TITLE
Closure compiler throws error when extending class named 'Tab' 

### ISSUE THREAD

**Issue by lwojciechowski** [google/closure-compiler#1189]
When compiling following code

``` javascript
class Tab {}
class MyTab extends Tab {}
```

The error is returned: `Multiple classes cannot share the same name.`

The error occurs when the `Tab` class is defined and some other class is extending it. It only happens when the name of the class is exactly `Tab`.

Link to closure compiler with example: http://goo.gl/eJfsgv

**Comment by MatrixFrog** [comment]
This is likely because of the Tab class at https://github.com/google/closure-compiler/blob/master/externs/browser/chrome.js#L317

As a workaround you can try using a custom set of externs that excludes that file.

**Comment by govis** [comment]
Similar issue with a class named "Profile"
<pre><code>ERROR - Multiple classes cannot share the same name.
export class Business extends Profile {
                              ^^^^^^^</code></pre>

**Comment by ChadKillingsworth** [comment]
@MatrixFrog The chrome externs should have never been put in the default externs set (but that happened LONG ago). With global names like that, it makes them very troublesome. What's the work effort to move them out to the contrib folder?

**Comment by MatrixFrog** [comment]
Shouldn't be too hard. We can keep it in the same spot internally and then add a line in the MOE config so that it's in contrib externally. This is what we did with svg.js

**Comment by MatrixFrog** [comment]
chrome.js was moved to contrib/externs a few months ago. Awkwardly, 26bd35be9e5b152826c2a6d4710a80ae05fb04d8 is the commit containing that move, even though the rest of that commit is unrelated.
