### ISSUE TITLE
Array.find is losing understanding of array element type (NTI too)

### ISSUE THREAD

**Issue by supersteves** [google/closure-compiler#1194]
I'm using ```Array.find()``` on a strongly typed array. Within the test function passed, the element type becomes unknown to Closure Compiler (noticed when using REPORT_UNKNOWN_TYPES):
``` javascript
function f(/** !Array<!Date> */arr) {
  arr.find(item => {
    console.log(item); // item has unknown type here
    return false;
  });
}
```

This happens with and without NTI; here's a test case with NTI ticked and with the brand new ```Array.find``` extern copied from HEAD. 
The arg to console.log is unknown within the function arg to ```Array.find()```:
Whereas the preceding console.log args are strongly typed:
https://closure-compiler-debugger.appspot.com/#input0%3Dfunction%2520f(%252F**%2520!Array%253C!Date%253E%2520*%252Farr)%2520%257B%250A%2520%2520console.log(arr)%253B%250A%2520%2520console.log(arr%255B0%255D)%253B%250A%2520%2520arr.find(item%2520%253D%253E%2520%257B%250A%2520%2520%2520%2520console.log(item)%253B%250A%2520%2520%2520%2520return%2520false%253B%250A%2520%2520%257D)%253B%250A%257D%26input1%26conformanceConfig%26externs%3D%252F**%250A%2520*%2520%2540param%2520%257B!function(this%253AS%252C%2520T%252C%2520number%252C%2520!Array%253CT%253E)%253A%2520boolean%257D%2520predicate%250A%2520*%2520%2540param%2520%257BS%253D%257D%2520opt_this%250A%2520*%2520%2540return%2520%257BT%257Cundefined%257D%250A%2520*%2520%2540template%2520T%252CS%250A%2520*%252F%250AArray.prototype.find%2520%253D%2520function(predicate%252C%2520opt_this)%2520%257B%257D%253B%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_TYPES%3D1%26CHECK_TYPES_NEW_INFERENCE%3D1%26CLOSURE_PASS%3D1%26LANG_IN_IS_ES6%3D1%26TRANSPILE%3D1

Possibly related to https://github.com/google/closure-compiler/issues/1151

**Comment by blickly** [comment]
This looks like an issue with the externs definition of Array.prototype.find, which doesn't refer to the type of the Array in question

**Comment by supersteves** [comment]
@blickly Note I've copied the Array.prototype.find extern directly out of the codebase into the debugger externs, and it appears to reference the element type correctly:
``` javascript
/**
 * @param {!function(this:S, T, number, !Array<T>): boolean} predicate
 * @param {S=} opt_this
 * @return {T|undefined}
 * @template T,S
 */
Array.prototype.find = function(predicate, opt_this) {};
```

**Comment by blickly** [comment]
Looks like this will be fixed by #1190

**Comment by supersteves** [comment]
You're right...
but I don't understand why!

https://closure-compiler-debugger.appspot.com/#input0%3Dfunction%2520f(%252F**%2520!Array%253C!Date%253E%2520*%252Farr)%2520%257B%250A%2520%2520console.log(arr)%253B%250A%2520%2520console.log(arr%255B0%255D)%253B%250A%2520%2520arr.find(item%2520%253D%253E%2520%257B%250A%2520%2520%2520%2520console.log(item)%253B%250A%2520%2520%2520%2520return%2520false%253B%250A%2520%2520%257D)%253B%250A%257D%26input1%26conformanceConfig%26externs%3D%252F**%250A%2520*%2520%2540param%2520%257B!function(this%253AS%252C%2520T%252C%2520number%252C%2520!Array%253CT%253E)%253A%2520boolean%257D%2520predicate%250A%2520*%2520%2540param%2520%257BS%253D%257D%2520opt_this%250A%2520*%2520%2540return%2520%257BT%257Cundefined%257D%250A%2520*%2520%2540this%2520%257B%257Blength%253A%2520number%257D%257CArray%253CT%253E%257Cstring%257D%250A%2520*%2520%2540template%2520T%252CS%250A%2520*%252F%250AArray.prototype.find%2520%253D%2520function(predicate%252C%2520opt_this)%2520%257B%257D%253B%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_TYPES%3D1%26CHECK_TYPES_NEW_INFERENCE%3D1%26CLOSURE_PASS%3D1%26LANG_IN_IS_ES6%3D1%26TRANSPILE%3D1

**Comment by supersteves** [comment]
It also fixes it in old type inference. Thanks.
