### ISSUE TITLE
Compiler is not transpiling certain statements

### ISSUE THREAD

**Issue by lwojciechowski** [google/closure-compiler#1195]
Following structure:

```javascript
let b = {
    b() {}
};
```
is transpiled into
```javascript
var b = {
    b() {}
};
````

The problem is that this code is used as Symbol polyfill so it's not cross browser (not working in Safari).

Expected output would be:
```javascript
var b = {
    b: function b() {}
};
````

Google Closure link: http://goo.gl/OEbuiT

**Comment by MatrixFrog** [comment]
I'm 88% sure I fixed this recently so it may just be that the web service is out of date.

**Comment by MatrixFrog** [comment]
Working on pushing the web service but it looks like the debugger is already showing the right thing.

https://closure-compiler-debugger.appspot.com/#input0%3Dlet%2520b%2520%253D%2520%257B%250A%2520%2520%2520%2520b()%2520%257B%257D%250A%257D%253B%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26LANG_IN_IS_ES6%3D1%26PRETTY_PRINT%3D1%26TRANSPILE%3D1

**Comment by lwojciechowski** [comment]
:+1:
