### ISSUE TITLE
Join

### ISSUE THREAD

**Issue by FMCalisto** [google/closure-compiler#1198]
How can I join to Google Organization so that I can contribute with OS ideas for this project?

Thank you!

**Comment by MatrixFrog** [comment]
To be in the Google "organization" I believe you have to be a Googler. So, um, google.com/jobs I guess :)

But ideas/questions/etc are definitely welcome from everyone! Please use the mailing list: https://groups.google.com/forum/#!forum/closure-compiler-discuss

**Comment by ChadKillingsworth** [comment]
There's no join - but that doesn't stop you from contributing!

Step 1: fork the project to your own account.
Step 2: Make changes in your fork on a feature branch.
Step 3: Submit a Pull Request - github helps you with this automatically when you submit a patch: https://help.github.com/articles/using-pull-requests/

A Pull Request is where a project owner will review your code for inclusion. If it's your first pull request, feel free to ask questions first.
