### ISSUE TITLE
VariableMap output has temporary local names

### ISSUE THREAD

**Issue by supersteves** [google/closure-compiler#1201]
For example when you get an error like this in production...
```
TypeError: yv.uS is not a function
```
... you consult the result of Compiler.getVariableMap() to find out what the original name of the variable is.

However it contains several entries like...
```
L 96:qT
L 97:yv
L 98:nN
```
... which appears to come from ```RenameVars.LOCAL_VAR_PREFIX```.

Is this a bug, and the variable map should in fact track the original names? Or do multiple local variables with different original names share this rename?

So this is either a bug report, or a feature request to track the original name(s) for a given local temporary rename variable, in the compiler outputs.

**Comment by MatrixFrog** [comment]
I think the variable map file predates source maps. You might get better information by generating a source map instead.

**Comment by supersteves** [comment]
I do; however the error only gives a line number, so the sourcemap won't help.

**Comment by concavelenz** [comment]
This is working as intended.  There isn't much information to recover from the local variable names, as the first parameter of every function is named the same, etc.  "L 97" is the 97th local parameter/variable in every function that has at least 97 locals.  If you can reproduce the problem locally, perhaps you can enable pseudo renaming?

**Comment by supersteves** [comment]
The (unfortunately very common) case is where an error happens in production at a remote site, and the client can't or won't give a reproducible test case. Often the browser is, say, IE9. We might only have the "yv.uS" error text.

As I understand it variable renaming for these cases goes like this: 
```
originalName1 --> L 53 --> zx
...
originalName2 --> L 97 --> yv
originalName3 --> L 97 --> yv
```
I can see the variable map itself is "working as intended", but am suggesting there is something missing from the outputs. 

I propose another map that tracks the list of possible original variable names for each "L nn" interim name that ultimately gets renamed to "yv".

A "local variable map" which contains:
L 53 --> [originalName1]
L 97 --> [originalName1,originalName2]

Probably using the same property map classes but with a JSON formatted array as the value.
Would this get accepted as a PR?

**Comment by acleung** [comment]
Well, John Lenz oversimplified the algorithm to keep the explanation short.

Variable renaming is very complex and the L # --> short-name stage is just
the very last step.

Locals are merged within scope, between scopes and with parent scopes in
all sort of ways. And that is before the idiom based passes and dataflow
passes have a crack at the local variables.

Sure, it is possible to track all those along the way to create the reverse
map you described but that would involve going through most of the analysis.

The engineering effort is not worth it. At least not for the purpose of
reverse engineering a project's bug because they refuse to share their
codebase for debugging.

**Comment by supersteves** [comment]
Thanks for explaining. I'm probably in the minority of users who has a closed-source commercial product which gets shrink-wrapped and installed by 3rd parties in servers far away in the murky and totally inaccessible corporate world of our clients. Not having access to a the problem other than the diagnostics we were able to capture in an old corporate browser (IE9 is still pretty common)  is unfortunately the norm. And typically the clients aren't very forthcoming with problem descriptions.

I think a solution I might develop is to use the AST and sourcemaps, post-compilation, to build a map of all output identifiers and the list of all source positions each originated from. That way one could look up a particular identifier such as "yv" or "xz" and figure out where it's likely to be. I'll do this external to this repo unless you think it would be welcome as a PR.

**Comment by ChadKillingsworth** [comment]
@supersteves You aren't in that big of a minority, but sourcemaps are definitely the answer here. We don't even expose variable maps from the command line anymore.

For remote installations like you describe, I recommend sourcemaps combined with an error reporting service like [Sentry](https://getsentry.com/welcome/). Older browsers are only going to report the line number, but hopefully as users continue to upgrade you'll get better reports - at least you'll get full UA information along with the report - even if the stack trace isn't as helpful as you'd like.

**Comment by supersteves** [comment]
@ChadKillingsworth Many thanks for the tip, much appreciated.
