### ISSUE TITLE
compiler swallows syntax errors with --manage_closure_dependencies

### ISSUE THREAD

**Issue by laszlocsomor** [google/closure-compiler#1209]
It seems that using `--manage_closure_dependencies` swallows syntax errors if the input contains a `goog.provide`:

No `goog.provide` in the input, compiler correctly reports syntax error:

    $ echo 'this is a syntax error' | java -jar compiler.jar --manage_closure_dependencies --js_output_file /dev/stdout ; echo "exit code: $?"
    The compiler is waiting for input via stdin.
    stdin:1: ERROR - Parse error. Semi-colon expected
    this is a syntax error
         ^
    
    1 error(s), 0 warning(s)
    exit code: 1

Adding a `goog.provide` makes the error go away:

    $ echo -e 'this is a syntax error\ngoog.provide("not.anymore");' | java -jar compiler.jar --manage_closure_dependencies --js_output_file /dev/stdout ; echo "exit code: $?"
    The compiler is waiting for input via stdin.
    
    exit code: 0

Removing the `--manage_closure_dependencies` flag brings the error back:

    $ echo -e 'this is a syntax error\ngoog.provide("not.anymore");' | java -jar compiler.jar --js_output_file /dev/stdout ; "exit code: $?"
    The compiler is waiting for input via stdin.
    stdin:1: ERROR - Parse error. Semi-colon expected
    this is a syntax error
         ^
    
    1 error(s), 0 warning(s)
    exit code: 1

**Comment by ChadKillingsworth** [comment]
This is working as intended. The compiler doesn't even fully parse the file before dropping it from the input. You would need a file that:

 1. doesn't have `goog.provide` statements
 2. contains a `goog.require` which includes the `not.anymore` namespace.

Make sure you have read the [Manage Closure Dependencies](https://github.com/google/closure-compiler/wiki/Manage-Closure-Dependencies) documentation fully and understand the deferences between the flags.
