### ISSUE TITLE
Element.scrollIntoView extern does not match MDN documentation.

### ISSUE THREAD

**Issue by mgilson** [google/closure-compiler#1211]
MDN documents the [`Element.prototype.scrollIntoView`](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView) function as accepting an optional boolean or an object.  The extern in `wc3_css.js` only accepts a boolean.  It appears that Chrome ignores the input object and Firefox has actually put in a little work to implement the spec on the MDN page.

It seems that the extern should be changed to:

```javascript
/**
 * @param {(boolean|{behavior: string, block: string})=} opt_top
 * @see http://www.w3.org/TR/cssom-view/#dom-element-scrollintoview
 */
Element.prototype.scrollIntoView = function(opt_top) {};
```

to support the Firefox case.

For more background on this, see the following StackOverflow post:  http://stackoverflow.com/q/33131516/748858

**Comment by ChadKillingsworth** [comment]
Fixed by #1212
