### ISSUE TITLE
[ES6] @export ignored when two classes have same exported name

### ISSUE THREAD

**Issue by calebegg** [google/closure-compiler#1215]
If you have two classes with the same property name exported, one is ignored.

See example:

http://closure-compiler-debugger.appspot.com/#input0%3Dclass%2520Foo%2520%257B%250A%2520%2520%252F**%2520%2540export%2520*%252F%2520xyz()%257B%257D%253B%250A%257D%250A%250Aclass%2520Bar%2520%257B%250A%2520%2520%252F**%2520%2540export%2520*%252F%2520xyz()%257B%257D%253B%250A%257D%250A%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26ALLOW_LOCAL_EXPORTS%3D1%26GENERATE_EXPORTS%3D1%26LANG_IN_IS_ES6%3D1%26MISSING_PROPERTIES%3D1%26PRETTY_PRINT%3D1%26PROPERTY_RENAMING%3D1%26TRANSPILE%3D1

**Comment by MatrixFrog** [comment]
Enabling --export_local_property_definitions seems to fix this. We should document this better.

**Comment by MatrixFrog** [comment]
I take it back, it seems that this already works. Your link does the right thing if you add a 'var goog;' somewhere.
