### ISSUE TITLE
Change @nosideeffects to @throws on RegExp constructor extern

### ISSUE THREAD

**Issue by blickly** [google/closure-compiler#122]
This issue was imported from Closure Compiler's previous home at http://closure-compiler.googlecode.com

The link to the original issue is:
https://blickly.github.io/closure-compiler-issues/#1288

**Comment by caridy** [comment]
This is a very old issue, but it seems that is still relevant:

```js
function tryPattern(pattern) {
      try {
           pattern = RegExp(pattern);
      } catch (e) {
           throw new Error("`pattern` attribute in <input> must be a valid javascript regular expression. " + e);
     }
}
```

By the spec, regexp might throw, but the closure compiler is folding it:

```js
function tryPattern(a){};
```

But this function is not side effects free since it can throw an error:

```js
foo('[');
```

**Comment by realityforge** [comment]
@brad4d This can be closed as the externs have been updated

**Comment by brad4d** [comment]
@realityforge thanks
