### ISSUE TITLE
When using ECMAScript 6 modules, cannot import a module that has no exports

### ISSUE THREAD

**Issue by Pauan** [google/closure-compiler#1220]
Consider these two modules:

```
// foo.js
alert("Hi");
```

```
// bar.js
import "./foo";
```

----

When compiling with `--language_in ECMASCRIPT6` I get the following error:

```
bar.js:1: ERROR - required "module$foo" namespace never provided
import "./foo";
^
```

However, if I add an export to `foo.js`, then it works correctly:

```
// foo.js
alert("Hi");

export const foo = 1;
```

----

In my application, I'm using `import "..."` to import a module solely for its side effects, so of course the module doesn't export anything, which is how I found this error.

**Comment by dimvar** [comment]
The compiler only considers a file to be an ES6 module if it has an import or an export statement. See:
https://github.com/google/closure-compiler/blob/master/src/com/google/javascript/jscomp/ProcessEs6Modules.java#L41

I'm not sure if we plan to support your usecase or not.

**Comment by Pauan** [comment]
What about treating *all* input JS files as modules, when using `--language_in ECMASCRIPT6`?

**Comment by bfricka** [comment]
@Pauan You have to `export` something for it to be `import`able, thus 'foo.js' is not considered a module.

http://www.2ality.com/2015/07/es6-module-exports.html

**Comment by concavelenz** [comment]
"export default undefined;" would make it clear that it is intended to be a module.  Do you have use case where you explicitly don't want to included any export.  Otherwise, "--language_in ECMASCRIPT6" is likely going to mix and match es6 modules for a long time.  I think a different command-line flag like: --js-module= ... in addition to --js would be a reasonable addition

**Comment by Pauan** [comment]
@bfricka In older versions of the ES6 specification, whether a file is a module or not was determined by heuristics (such as whether an `import` or `export` statement exists in the file).

However, in the current (and final) version of the specification, that is no longer the case.

Instead, what determines whether a file is a module or not is based upon how it is imported.

If you have two files `foo.js` and `bar.js`:

```
// foo.js
import "./bar";
```

```
// bar.js
alert("hi!");
```

Then the file `bar.js` is treated as a module, because it is imported by `foo.js`

If you instead load `bar.js` by using a `<script>` tag, then it is treated as a script (and not a module).

That means you cannot use the *contents* of the file to determine if it is an ES6 module, you must instead determine it by *how the file is being imported*.

The correct way to solve this in the Closure Compiler is to have an `--es6-entry-point` option, which specifies the root file of your program. It will treat that file (and any files imported by that file, recursively) as being ES6 modules.

----

@concavelenz I have a module which injects some CSS stylesheets into the DOM. It is used purely for its side effects, and has nothing meaningful to export.

Your hack might solve the problem in the Closure Compiler, but it is unnecessary in ES6, because ES6 has full support for modules that don't export anything:

http://www.2ality.com/2014/09/es6-modules-final.html#more_on_importing_and_exporting
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import
http://exploringjs.com/es6/ch_modules.html#_importing-and-exporting-in-detail

Therefore, the Closure Compiler does not accept perfectly valid ES6 code.

You could argue that the Closure Compiler was never intended to support all of ES6, and that's fine, but in that case it should throw a clear error saying that `import "foo";` is not supported.

**Comment by concavelenz** [comment]
You'll find a lot of tools (anything that operates file-by-file) will behave better if you include a dummy export.  As you say there is nothing about the file that indicates if it is a ES6 module or not.  Which means it is impossible to give correct errors/warnings about being in "strict" mode without some hint.  It is true however that if the file is "imported" from another ES6 module in the same compilations, we should force it to be an considered an ES6 module, but then you can't do file-by-file translation from ES6-to-ES5 with the same set of file (in that mode your import/export-less file's locals would then be global values, which you don't want).   In my mind, it would be worth putting in the export to make sure the file way loaded correctly.  

Still the compiler should have a way to force an input file to be considered an ES6 module.

**Comment by bfricka** [comment]
Interesting @Pauan. To verify your claims, I just read the ES6 module specification, and you are totally correct. To clarify (in case someone reads this later), there are two separate `import` statements per the spec:

```js
// The most common, using "importClause" "fromClause"
import foo from 'foo-module';
import * as fooNamespace from 'foo-module';
import {foo as x} from 'foo-module';

// The other is importing for side effects
import 'foo-module';
```
This was alluded to in links you posted, but it's worth restating. The first syntax creates a module record internally, bindings and a module execution context, while the second does not. It really just loads a script body and executes it (note: from what I can tell, since it doesn't create a new module record, it doesn't create a new module execution context either, so this really would be just loading and executing a script). The [details](http://www.ecma-international.org/ecma-262/6.0/#sec-abstract-module-records) are best described from 15.2.1.15 to 15.2.1.16 and the subsequent descriptions.

Okay, so back to your original issue. I think it's clear that having the compiler treat all files as modules when language is ECMASCRIPT6[_STRICT] doesn't make much sense, since as you said, files are only modules if they are imported. And you could really argue that they aren't even modules then if they aren't exporting anything since they aren't given a self-contained execution context. It's more like programmatic concatenation.

Anyways, thanks for clarifying, as I now know more about JS modules.

**Comment by Pauan** [comment]
@concavelenz You are right that there are many tools that do not currently understand ES6. But there are good tools like Babel that do.

I prefer to write clean ES6 and use tools which properly support it. But your hack is good to keep in mind, in case it's ever needed to work with a tool that doesn't properly handle ES6.

----

@bfricka I may be wrong, but my understanding is that when you use `import "foo";` it is exactly the same as using `import {} from "foo";` except that it's a bit shorter.

That means that the file `foo.js` is executed in strict mode, and it is executed in a new local scope, rather than in the global scope. It can also import other files and use them.

In other words, it's an actual real module. There's nothing special about it. It is *not* the same as concatenating the files, or using a `<script>` tag.

Even if `foo.js` exports things, it's still completely valid to use `import "foo";`

It just means that you don't care about the module's exports.

----

I'm not very good at reading specs, but I believe that using `import "foo";` does not create an ImportEntry Record, but it does create a Source Text Module Record.

[15.2.2.5](http://www.ecma-international.org/ecma-262/6.0/#sec-imports-static-semantics-modulerequests)

[15.2.1.16.1](http://www.ecma-international.org/ecma-262/6.0/#sec-parsemodule) (step 4)

[15.2.1.16.4](http://www.ecma-international.org/ecma-262/6.0/#sec-moduledeclarationinstantiation) (step 8)

**Comment by concavelenz** [comment]
@Pauan It isn't a matter of "properly supporting ES6" is a matter of "you can't tell if the code is intended to be a es6 module module or a script" without an external hint.    Adding an explicit export makes sure that it is never misused.

**Comment by marty-krishner** [comment]
Hi,

its also simple code working


```
//main.js
import Config from './config';

alert(Config.test);
```
```
//config.js
export default {
    test:10
};

```

**Comment by Boitumelo45** [comment]
Hi, everyone

I have: 

Files:
6_models/
    animal.js
6_creating_modules.js 

animal.js: 

export class Animal{
      //constructor
      constructor(legs = 2, arms = 2, gender, breed){
            this.legs = legs,
            this.arms = arms,
            this.gender = gender,
            this.breed = breed
      }

      //method
      information(){
            let data = {
                  legs : this.legs,
                  arms : this.arms,
                  gender: this.gender,
                  breed : this.breed
            }

            if((data.arms == 0 && data.legs > 4)){
                  delete data.arms        //animal has no arms
                  data.breed = 'Alien species'
                  return data
            }else if(data.arms == 0){
                  delete data.arms        //animal has no arms
                  return data
            }else{
                  return data
            }

      }
};

and
6_creating_modules.js

/*
  ECMAScript 2015
*/

import {Animal} from './6_models/animal.js';

let dog = new Dog(8, 0, 'male', 'bull dog')
console.log(dog.information())
/*
      { legs: 8, gender: 'male', breed: 'Alien species' }
*/


I am getting an error:
import {Animal} from './6_models/animal.js';
       ^

SyntaxError: Unexpected token {
    at new Script (vm.js:84:7)
    at createScript (vm.js:264:10)
    at Object.runInThisContext (vm.js:312:10)
    at Module._compile (internal/modules/cjs/loader.js:684:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:774:12)
    at executeUserCode (internal/bootstrap/node.js:342:17)

**Comment by brad4d** [comment]
@Boitumelo45 

It's purely an accident that I happened to see your update to this old issue, but since I did....

1. You'll be more likely to get help if you file a new issue.
2. Please include what options you're using to run the compiler.

The problem here could be that the compiler thinks you're not supposed to be using ES6 module syntax, so it considers it a syntax error.
