### ISSUE TITLE
"unreachable code" warning for some simple input with ES6 modules

### ISSUE THREAD

**Issue by MatrixFrog** [google/closure-compiler#1222]
Reported at https://www.reddit.com/r/javascript/comments/3pb750/ecmascript_6_is_now_officially_supported_by/cw4zff7

    $closure-compiler --language_in=ECMASCRIPT6 --js foo.js --js bar.js --js_output_file out.js
    bar.js:1: WARNING - unreachable code
    import Foo from "./foo";
    foo.js:9: WARNING - unreachable code
    export default Foo;

Looks similar to #894

**Comment by dimvar** [comment]
What are the inputs to reproduce this? I used the following and wasn't able to repro:

tmp1.js

    import Tmp2 from "./tmp2";

tmp2.js

    var Tmp2;
    export default Tmp2;

**Comment by dimvar** [comment]
Btw, if you don't think this is urgent, it can totally wait until after you come back. You don't have to dig in for repro now.

**Comment by dimvar** [comment]
Command line used:

    java -jar build/compiler.jar --language_in=ECMASCRIPT6 --js tmp/tmp1.js --js tmp/tmp2.js --language_out=ES5

**Comment by samwgoldman** [comment]
Original issue-haver here. Adding `--language_out` created the expected result (instead of an error). Thanks!

**Comment by dimvar** [comment]
Glad your issue is resolved.

There was probably another difference as well; when I omitted language_out initially I got a warning that the compiler doesn't support ES6 as an output language (which is expected) instead of an unreachable code warning.

**Comment by samwgoldman** [comment]
Probably a slightly stale version—I installed from Homebrew on Mac. Thanks again!
