### ISSUE TITLE
ES6 module imported bindings should be statically resolved and rewritten.

### ISSUE THREAD

**Issue by rintaro** [google/closure-compiler#1226]
I think current ES6 module processing has some problems.

* No "star re-export" (i.e. `export * from "moduleSpecifier"`) support.
* Type check/inference limitation.
* Re-exporting `@typedef` does not works.
* Mutating exported value not propagated to namespace object.
* etc.

So, I'm rewriting ES6 module processing logic.
https://github.com/rintaro/closure-compiler/tree/es6-module-rewrite
And summarizing the proposal.
https://github.com/rintaro/closure-compiler/wiki/ES6-module-processing
I would like to know what do you think of that, and any possibility for acceptance for pull request if I post.
Of course, I will write test cases as much as I can.

Since I don't have enough knowledge about whole architecture of this project, I'm not sure I'm on the right track or not.

---
P.S. I've tried to post this to [Closure Compiler Discuss](https://groups.google.com/forum/#!forum/closure-compiler-discuss), but somehow failed. Apologize if wrong place.

**Comment by concavelenz** [comment]
Closure Compiler Discuss is moderated.

**Comment by MatrixFrog** [comment]
https://groups.google.com/d/topic/closure-compiler-discuss/nW5nbGcerJw/discussion
