### ISSUE TITLE
Simple calculations not optimised

### ISSUE THREAD

**Issue by L3P3** [google/closure-compiler#1229]
Here are a few examples from original output from the newest version of GCC, advanced mode:
```javascript
d=p()-q-0
if(!(f<k))
t=2<=h&&!0&&!0
```
I know that the first example is from a (constant) function like this:
```javascript
var a=0,b=0;
/** @const */function getRelative(){
    return c()-a-b;
}
```
But in some compile targets, the value of `b` don't get modified, so it stays at 0.
Maybe, there is a connection. :unamused:

**Comment by L3P3** [comment]
There are many more of these. I nearly started to take out my :microscope: to find them. But this 3 examples are the most obvious ones. And for me as a :de:, it is double-disgusting to have errors like that in my beautiful-written code.

**Comment by ChadKillingsworth** [comment]
I'm really not sure what your point is and your example has errors:

    JSC_NOT_FUNCTION_TYPE: number expressions are not callable at line 3 character 11
    return b()-a-b;

Also, I can't see how `@const` would apply/add benefit to a function. To my knowledge it doesn't affect inlining.

**Comment by L3P3** [comment]
Oh, no. I am sorry. It is the time (midnight to me). I named the function in the example wrong.

**Comment by L3P3** [comment]
Here is a more detailed example:
```javascript
/** @const */ function getTime(){
    return (new Date).now();
}
var startTime=getTime();
/** @const */ function getRunTime(){
    return getTime()-startTime;
}
var pausedTime=0;
var pauseStart;
function pause(){
    pauseStart=getTime();
}
function unpause(){
    pausedTime+=getTime()-pauseStart;
}
/** @const */ function getActiveRunTime(){
    getRunTime()-pausedTime();
}
/** @define {boolean} */var doPause=false;
if(doPause){
    setTimeout(pause,1000);
    setTimeout(unpause,2000);
}

setTimeout(function(){
    alert(getActiveRunTime());
},3000);
```
When `doPause` stays false, the result code would be:
```javascript
setTimeout(function(){alert((new Date).now()-(new Date).now()-0)},3000);

```

**Comment by ChadKillingsworth** [comment]
Nit - you probably just meant `Date.now` not `(new Date).now()`

But as to the extra `-0`, I'm guessing the fold constants pass would have to run again (later) to handle this case - but the size savings are extremely small (2 bytes pre-gzip?). That's not worth it in my opinion.

**Comment by concavelenz** [comment]
fold constants runs in the optimization loop, the issue is `tryFoldArithmeticOp` only operate if both the left and right side are known values (0 + 1).  `tryFoldLeftChildOp` handles the associative operators, something similiar could be done for subtraction.
