### ISSUE TITLE
Iterator<> returned from standard defined ES6 classes doesn't implement Iterable<>

### ISSUE THREAD

**Issue by p2004a** [google/closure-compiler#1230]
ECMAScript6 states<sup>[1](#foot1)</sup> that

> All objects defined in this specification that implement the Iterator interface also inherit from %IteratorPrototype%.

and `%IteratorPrototype%` implements the `Iterable` interface.

Unfortunately when applying the spread operator to the `Iterator` object that is iterable the compiler returns:

````
input0:3: WARNING - actual parameter 1 of $jscomp.arrayFromIterable does not match formal parameter
found   : Iterator<VALUE>
required: (Array<?>|Iterable<?>|string)
const d = [...s.values()];
              ^

0 error(s), 1 warning(s), 97.0% typed
````

[Here is the code](https://closure-compiler-debugger.appspot.com/#input0%3Dconst%2520s%2520%253D%2520new%2520Set(%255B1%252C2%252C3%252C4%252C5%255D)%253B%250A%250Aconst%2520d%2520%253D%2520%255B...s.values()%255D%253B%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES%3D1%26LANG_IN_IS_ES6%3D1%26MISSING_PROPERTIES%3D1%26PRETTY_PRINT%3D1%26REMOVE_DEAD_CODE%3D1%26TRANSPILE%3D1)

<a id="foot1">1</a>: first sentence of note of point [25.1.2](http://www.ecma-international.org/ecma-262/6.0/#sec-%iteratorprototype%-object)

**Comment by concavelenz** [comment]
The "values" method should return "IterableIterator" or some such that implements both interfaces.
