### ISSUE TITLE
Incorrect peephole optimization of switch

### ISSUE THREAD

**Issue by bobzhang** [google/closure-compiler#1234]
```js
// ==ClosureCompiler==
// @compilation_level ADVANCED_OPTIMIZATIONS
// @output_file_name default.js
// @formatting pretty_print,print_input_delimiter
// ==/ClosureCompiler==

// ADD YOUR CODE HERE
var exit;

switch("Unix")
 {case "Cygwin":
   break;
  case "Unix":
   break;
  case "Win32":
   break;
  default:exit=21; break;}
switch(exit)
 {case 21: throw "x" ; default : console.log("good")}
```

output

```js
// Input 0
switch(21) {
  case 21:
    throw "x";;
  default:
    console.log("good");
}
;
```

**Comment by dimvar** [comment]
Thanks for the report. That's definitely a bug. Slightly simpler repro case:

    var exit;
    switch ("a") {
      case "a":
        break;
      default:
        exit = 21;
        break;
    }
    switch(exit) {
      case 21: throw "x";
      default : console.log("good");
    }

**Comment by dimvar** [comment]
The original program should not throw, and the compiled ones throws.

**Comment by bobzhang** [comment]
this works
```
var exit = undfined;

switch("Unix")
 {case "Cygwin":
   break;
  case "Unix":
   break;
  case "Win32":
   break;
  default:exit=21; break;}
switch(exit)
 {case 21: throw "x" ; default : console.log("good")}
```

**Comment by bobzhang** [comment]
However, the working version is a bit disappointing, there is no constant folding in this case

**Comment by dimvar** [comment]
If you want to try contributing a fix, here is where you can start:

https://github.com/google/closure-compiler/blob/master/src/com/google/javascript/jscomp/PeepholeRemoveDeadCode.java#L302

**Comment by bobzhang** [comment]
Thanks for the input, I am working on a compiler from OCaml-> Readable JS -> Google Closure, in the long term I would like to have an ocaml_pass to do some special optimization for the OCaml input.

My Java knowledge is a bit rusty, is there a set up instruction for IDEA users( I only find Eclipse set up)

**Comment by dimvar** [comment]
I don't think there is documentation. You can ask here:
https://groups.google.com/forum/#!forum/closure-compiler-discuss
or on StackOverflow. (I use Emacs so I don't know.)

**Comment by ChadKillingsworth** [comment]
You can steal my `.idea` folder and .iml file from here: https://github.com/chadkillingsworth/closure-compiler/tree/intellij
