### ISSUE TITLE
allow @nosideeffects annotation in plain js files

### ISSUE THREAD

**Issue by bobzhang** [google/closure-compiler#1237]
I know this feature is very dangerous, however, it makes sense for compiler writers who target to closure style javascript. It's especially helpful for functional languages (like OCaml), most functions are pure and does not have side effect.
Thanks -- Hongbo

**Comment by ChadKillingsworth** [comment]
We'd much rather improve the side effect analysis of the compiler. As you said, this is very dangerous.

Do you have specific examples that are being improperly marked as having side effects?

**Comment by bobzhang** [comment]
As said, it is helpful for compiler writers (especially for functional languages which are mostly pure and doing analysis on functional language is easier than javascript)

Below is an example

```js
// Input 0./caml_exceptions.js
'use strict';
// Input 1./caml_lexer.js
// Input 2./caml_array.js
// Input 3./caml_primitive.js
var a = 0;
// Input 4./caml_utils.js
// Input 5./caml_io.js
// Input 6./camlinternalFormatBasics.js
// Input 7./pervasives.js
a++;
// Input 8./array.js
a++;
// Input 9./caml_obj_runtime.js
// Input 10./sys.js
a++;
// Input 11./char.js
// Input 12./list.js
// Input 13./bytes.js
// Input 14./lexing.js
// Input 15parsing.js
var b = [0, "", 0, 0, -1];
function e(f) {
  var c;
  c = 100;
  for (var g = Array(c), d = 0;d < c;d++) {
    g[d] = f;
  }
}
a++;
a++;
e(0);
e(0);
e(b);
e(b);
```

function `e` is pure, ideally I should get an empty output

**Comment by dimvar** [comment]
Even though this can be helpful for some careful users, we generally don't want to allow too many directives to the optimizer because they can be abused by accident (eg, using a directive when it's actually not true). For externs it's necessary because we can't see the code.

**Comment by bobzhang** [comment]
As I said, it's not for code written by human, it's mostly helpful for generated code, can we allow it and spit a warning instead?

**Comment by ChadKillingsworth** [comment]
There's just no way to allow this without causing havoc.

**Comment by bobzhang** [comment]
indeed, I tried to enable it and remove checkInvariant, the compiler is not that smart (after those change I made) to remove this piece code
