### ISSUE TITLE
[NTI] Erroneous non-existent type warning when referring to a namespaced typedef

### ISSUE THREAD

**Issue by abrobston** [google/closure-compiler#1240]
Using Closure built from source at commit [f8ef141](https://github.com/google/closure-compiler/commit/f8ef141787fd9b0410a8620983898d0df5e45f5a).

Given a file `ignore-typedef.js`:

    var b = {};
    
    /**
     * @typedef {string}
     */
    b.c;
    
    /**
     * @param {b.c} p - test param
     */
    function a(p) {}

using the command line:

    java -jar closure-compiler.jar --js ignore-typedef.js --new_type_inf --js_output_file output.js

gives us the warning:

    ./ignore-typedef.js:9: WARNING - Type annotation references non-existent type b.c.
     * @param {b.c} p - test param
               ^

Adding a `@const` tag to the definition of `b` appears to eliminate the warning, though doing so is currently undesirable due to #1235.  OTI does not appear to have the same issue.

**Comment by dimvar** [comment]
NTI requires that namespaces be annotated as <code>@const</code>. OTI handles both const and no const, but we think it's better to be consistent and require it.
