### ISSUE TITLE
Improve type inference within callbacks

### ISSUE THREAD

**Issue by pallosp** [google/closure-compiler#1248]
The following code snippet emits "WARNING - actual parameter 1 of f does not match formal parameter. found: (null|string), required: string"

/** @param {string} x */
function f(x) {}

function g() {
  /** @type {?string} */
  var x = null;
  if (x) {
    [].forEach(function() {
      f(x);
    });
  }
}

I wish the compiler could prove that x can't be null when it's passed to f.

**Comment by dimvar** [comment]
This is too difficult to do in the general case, and I don't think the compiler's heuristics will improve anytime soon.

**Comment by concavelenz** [comment]
This is pretty common and it is reasonable to (a) annotate immediately invoked parameter functions in externs (b) check the passed function itself doesn't escape itself.  In those cases using the type of x from the outer scope is reasonable.  The escape analysis for (a) for non-extern functions is also possible.

The basic reason functions can't use the value from the outer scope is that it isn't know if the type tightening applies as the function may be called later:

    function f() {
         var x = null;
         return function() { return x++ }
    }

But if we know the function is immediately invoke this reasoning doesn't apply:

    function f() {
         var x = null;
         (function() { use(x) })();
    }

As long as "arguments.x" isn't referenced it isn't possible to invoke this function later.  The same logic extends to "Array.prototype.forEach" and many other common methods.  This would actually reduce the need for "nullablity" checks and similiar type tightening quite a bit.

**Comment by nicks** [comment]
it might also be possible to attack this from the other direction. rather than trying to figure out where the inner function is called (john's suggestion), we might notice that `x` is used in a very limited way. It's assigned once, and all uses are guarded by the `if (x)`.
