### ISSUE TITLE
Userscript comment block removed in simple & advanced compilation modes

### ISSUE THREAD

**Issue by lvh** [google/closure-compiler#1249]
I'm writing a userscript using Clojurescript. Clojurescript uses the Closure compiler for advanced compilation.

I've added a file with the following contents to `:foreign-libs`, given it a `provides`, and `required` said file:

```javascript
/**
 * @fileoverview
 * This file contains nothing but a comment block which is to be preserved
 * by the google closure compiler. This comment block contains a comment
 * block which is necessary to be in the output of the compiled javascript
 * even in advanced compilation mode.
 */
/**
 * @preserve
// ==UserScript==
// @description xyzzy
// @name crunch
// ==/UserScript==
 */
```

The comment block appears with whitespace optimization, but not with simple or advanced optimization.

I've tried every format of "please don't stomp on this comment" that I can think of, just in case #164 hadn't been kept up-to-date:

```javascript
/**
 * @license
 // ==UserScript==
 // @description xyzzy
 // @name Crunch
 // ==/UserScript==
 */

/**
 * @preserve
 * ==UserScript==
 * @description xyzzy
 * @name Crunch
 * ==/UserScript==
 */

/**
 * @license
 * ==UserScript==
 * @description xyzzy
 * @name Crunch
 * ==/UserScript==
 */

/**!
 * ==UserScript==
 * @description xyzzy
 * @name Crunch
 * ==/UserScript==
 */

/*!
 * ==UserScript==
 * @description xyzzy
 * @name Crunch
 * ==/UserScript==
 */
```

None of these made it. I'm just seeing if I can get comments to show up in the output; those last few aren't supposed to work as Userscripts because UserScripts insist on having `//` style comments starting at column 0.

**Comment by blickly** [comment]
Works for me:
http://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540compilation_level%2520ADVANCED_OPTIMIZATIONS%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%252F**%250A%2520*%2520%2540fileoverview%250A%2520*%2520This%2520file%2520contains%2520nothing%2520but%2520a%2520comment%2520block%2520which%2520is%2520to%2520be%2520preserved%250A%2520*%2520by%2520the%2520google%2520closure%2520compiler.%2520This%2520comment%2520block%2520contains%2520a%2520comment%250A%2520*%2520block%2520which%2520is%2520necessary%2520to%2520be%2520in%2520the%2520output%2520of%2520the%2520compiled%2520javascript%250A%2520*%2520even%2520in%2520advanced%2520compilation%2520mode.%250A%2520*%252F%250A%252F**%250A%2520*%2520%2540preserve%250A%252F%252F%2520%253D%253DUserScript%253D%253D%250A%252F%252F%2520%2540description%2520xyzzy%250A%252F%252F%2520%2540name%2520crunch%250A%252F%252F%2520%253D%253D%252FUserScript%253D%253D%250A%2520*%252F

**Comment by blickly** [comment]
It seems the link doesn't work. I just ran you first example with ADVANCED_OPTIMIZATIONS:
/**
 * @fileoverview
 * This file contains nothing but a comment block which is to be preserved
 * by the google closure compiler. This comment block contains a comment
 * block which is necessary to be in the output of the compiled javascript
 * even in advanced compilation mode.
 */
/**
 * @preserve
// ==UserScript==
// @description xyzzy
// @name crunch
// ==/UserScript==
 */

**Comment by lvh** [comment]
Link worked for me, FWIW. I guess the problem is elsewhere. Thanks for checking; sorry for the false positive.
