### ISSUE TITLE
jQuery extern definition for .text() should only have return type 'string'

### ISSUE THREAD

**Issue by Sahil5** [google/closure-compiler#1250]
Hi, I noticed that in jquery-1.8.2.externs.js, the return type of jQuery.prototype.text is {(string | !jQuery)}, but shouldn't this simply be {string}? Thanks in advance

**Comment by Dominator008** [comment]
When .text(str) is used as a setter, you can do things like $('#id').text('foo').text('bar'). In this case .text() is returning @type {!jQuery}.

Are you getting a type error from jQuery.prototype.text in this extern?

**Comment by Sahil5** [comment]
Ah ok, that makes sense then. Thanks for the feedback!
