### ISSUE TITLE
Class expressions not handled correctly

### ISSUE THREAD

**Issue by nicks** [google/closure-compiler#1255]
Consider the following code
```
(function () { var Y = class Foo {}; console.log(Y) })()
```

The spec says that this should not bind `Foo` to a variable. `Foo` is just the name of the class. But closure-compiler complains
```
 echo "(function () { var Y = class Foo {}; console.log(Y) })()" | java -jar build/compiler.jar --language_in=ES6 --language_out=ES5 --warning_level=VERBOSE

stdin:1: ERROR - variable Foo is undeclared
(function () { var Y = class Foo {}; console.log(Y) })()
```

**Comment by dimvar** [comment]
What's the use case for naming the class different from the var?

**Comment by nicks** [comment]
consider `foo.Bar = class Bar {}`

The default toString() representation will include `Bar`, but i don't actually want to bind it to a global variable `Bar`

I'm not sure why the use-case matters though, because it's an explicit part of the spec?

**Comment by ChadKillingsworth** [comment]
I'm assuming it also impacts `foo.Bar.name`

**Comment by dimvar** [comment]
> I'm not sure why the use-case matters though, because it's an explicit part of the spec

I was just asking because we explicitly don't support everything in the spec.

Your example seems good to support though (or at least fail with a correct error message). Assigned to Tyler.
