### ISSUE TITLE
new typeinference does not handle implicitly overridden methods correctly

### ISSUE THREAD

**Issue by nicks** [google/closure-compiler#1259]
```
/** @constructor */ function Foo() {}
/** @param {number=} x */ Foo.prototype.set = function (x) {};

/** 
 * @constructor
 * @extends {Foo}
 */ 
function SubFoo() {}
/** Hi */ SubFoo.prototype.set = function (x) {};

(new SubFoo()).set()
```

Old type inference handles this without warning. New type inference fails to infer the sub method type and gives two warnings:

```
input0:9: WARNING - Invalid redeclaration of property set.
inherited type  : function(this:Foo,number|undefined=):?
overriding type : function(this:SubFoo,?):?
/** Hi */ SubFoo.prototype.set = function (x) {};

input0:11: WARNING - Function : called with 0 argument(s). Function requires at least 1 argument(s) and at most 1.
(new SubFoo()).set()
```

If I add `@override` the problem goes away

**Comment by dimvar** [comment]
That's a cool repro. If you remove the second jsdoc, the problem also goes away.

http://closure-compiler-debugger.appspot.com/#input0%3D%252F**%2520%2540constructor%2520*%252F%2520function%2520Foo()%2520%257B%257D%250A%252F**%2520%2540param%2520%257Bnumber%253D%257D%2520x%2520*%252F%250AFoo.prototype.set%2520%253D%2520function%2520(x)%2520%257B%257D%253B%250A%250A%252F**%2520%250A%2520*%2520%2540constructor%250A%2520*%2520%2540extends%2520%257BFoo%257D%250A%2520*%252F%2520%250Afunction%2520SubFoo()%2520%257B%257D%250ASubFoo.prototype.set%2520%253D%2520function%2520(x)%2520%257B%257D%253B%250A%250A(new%2520SubFoo()).set()%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_TYPES_NEW_INFERENCE%3D1%26MISSING_PROPERTIES%3D1
