### ISSUE TITLE
Add support for optional fields in record types

### ISSUE THREAD

**Issue by blickly** [google/closure-compiler#126]
This issue was imported from Closure Compiler's previous home at http://closure-compiler.googlecode.com

The link to the original issue is:
http://blickly.github.io/closure-compiler-issues/#952

**Comment by teppeis** [comment]
Optional field type is inconsistent between @param and @type.
I think the behavior of @param is correct.

Example:

```javascript
/**
 * @typedef {{foo: (string|undefined)}}
 */
var Foo;

/**
 * @param {Foo} obj
 */
function bar(obj) {}

bar({}); // ok

/** @type {Foo} */
var f = {}; // warning!
```
```
JSC_TYPE_MISMATCH: initializing variable
found   : {}
required: {foo: (string|undefined)} at line 14 character 8
var f = {}; // warning
        ^
```

**Comment by ihsoft** [comment]
The warning looks fine to me. When you declare `f` you define it's type via annotation but then you assign an object of incompatible type, and this is what triggers the warning. Try the following:
```javascript
/** @type {Foo} */
var f = /** @type {Foo} */ ({}); // Works fine
```
Btw, in most cases you may skip first `@type` since in this case type of the variable can be dedicted from the assignment.

**Comment by teppeis** [comment]
@ihsoft If the warning is correct, the above @param and `bar({})` should be error.
and we need another type definition for optional field.

TypeScript has the optional type:
```typescript
var f: {foo?: string} = {};
```

**Comment by concavelenz** [comment]
There are two kinds of record types inferred and declared.  Declared record types are invariant and "optional" fields must be explicitly set to undefined, inferred record types are more lenient.  This is general source of confusion.

bar({}); // inferred.
/** @type {Foo} */ var f = {}; // declared

**Comment by gonzojive** [comment]
A agree with @teppeis' comments in the thread and would favor a simple solution that adds support for optional properties for `@typedef ` types.

If the compiler's current behavior is intended because of a distinction between inferred vs. declared record types, I don't see the reasoning behind that.  I like the syntax suggested in the comment above

```
/** @typedef {{foo?: string}} */
```

**Comment by pauldraper** [comment]
Bikeshedding, but `foo=: string` would be consistent with optional parameters.

Perhaps even `foo: string=`.

**Comment by mgiuffrida** [comment]
Declared record types aren't necessarily helpful:

```
/** @typedef {{foo: (string|undefined), bar: number}} */
var Foo;

/** @param {Foo} arg */
function f(arg) {}

f(/** @type {Foo} */ ({ bar: 'String', nonexistent: 42 })); // OK
```

I'd prefer to explicitly write out `foo: undefined` to appease the compiler than throw away type checking altogether.

**Comment by SLaks** [comment]
This should now work.

**Comment by Dominator008** [comment]
@SLaks I think the behavior of code like:
```
/**
 * @typedef {{foo: (string|undefined)}}
 */
var Foo;
```
is correct, but we still lack a short syntax for optional fields.

**Comment by fingerartur** [comment]
```js
/**
 * @typedef {{foo: (string|undefined)}}
 */
var Foo;

/**
 * @param {Foo} obj
 */
function bar(obj) {}

bar({}); // ok

/** @type {Foo} */
var f = {}; // Not longer an issue with Google Closure Compiler version 20191111
```

It seems to be working as expected now with Google Closure Compiler version **_20191111_** and still working also in version **_20230103_**.

@SLaks verified 👍.
