### ISSUE TITLE
Wrong constant-folding of the number to string conversion

### ISSUE THREAD

**Issue by sjrd** [google/closure-compiler#1262]
The constant-folder, or some other parts of GCC, wrongly handles the conversion from number to string. This happens both with Simple Opts and Advanced Opts. The following snippet reproduces the problem:
```javascript
function foldNumberToString() {
  alert('A number: ' + 1.2323919403474454e+21.toString());
  alert('A number: ' + 1.2323919403474454e+21);
}
foldNumberToString();
```
The first call is not constant-folded, and outputs the correct results, i.e., `1.2323919403474454e+21`. The second line, however, is constant-folded into
```javascript
  alert("A number: 1.2323919403474454E21");
```
which seems to indicate that a `.toString()` was used on the JVM to convert the number into a string.

ECMAScript [specifies pretty precisely](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-tostring-applied-to-the-number-type) how a number must be converted into a string, and the algorithm does *not* match what the JVM does.

**Comment by blickly** [comment]
Thanks for the report. Looks like the error is in NodeUtil:
https://github.com/google/closure-compiler/blob/831be0a9c003beb14645906357c31920c5888423/src/com/google/javascript/jscomp/NodeUtil.java#L240

**Comment by paullepoulpe** [comment]
Also in here apparently: https://github.com/google/closure-compiler/blob/eebd40b7c9512e771d2b64d9200bc3802c37651b/src/com/google/javascript/jscomp/parsing/IRFactory.java#L770

**Comment by concavelenz** [comment]
Care to send a PR?

**Comment by paullepoulpe** [comment]
#1267
