### ISSUE TITLE
Typedef not in externs file is ignored with ADVANCED_OPTIMIZATIONS

### ISSUE THREAD

**Issue by chrismiddleton** [google/closure-compiler#1269]
(Disclaimer: I don't have that much experience with Closure. I apologize if the issue here is just me and not the compiler.)

I'm trying to add a `@typedef` for a callback. The callback's API does not need to be exposed to the outside world. But so far I can only get Closure to recognize the `@typedef` by putting it into my externs file.

There are a few of them, here's one:

    /**
     * @typedef {function(string): string}
     * 		#param {string} url
     * 		#return {string} the redirect
    **/
    var RedirectUrlFunc;

(I'm using a `#` to do pseudo-documentation for the moment, since @param cannot go with @typedef in this manner.)

Then the reference to it looks like this:

    /**
	 * If set equal to a function, this property will ...
	 * @type {RedirectUrlFunc?}
	**/
	redirectUrl: null,
    ... more properties of a config object ...

If I include the `@typedef` piece (including the `var RedirectUrlFunc`) in the same file as the config object, I get this error from the compiler:

    WARNING - Bad type annotation. Unknown type RedirectUrlFunc
	     * @type {RedirectUrlFunc?}

When I put it in my `externs.js` file, it seems to be understood (no warning).

Does this have something to do with ADVANCED_OPTIMIZATIONS being turned on? Perhaps it is tree-shaking the RedirectUrlFunc declaration away and then not finding it?

**Comment by dimvar** [comment]
Typedefs are allowed in files and work with advanced optimizations. For example, you can try this code at http://closure-compiler.appspot.com/ using advanced mode and you'll see no warnings.

    /**
     * @typedef {function(string): string}
     *      #param {string} url
     *      #return {string} the redirect
     */
    var RedirectUrlFunc;
    /**
     * If set equal to a function, this property will ...
     * @type {RedirectUrlFunc?}
     */
    var x;

Something else is missing in the bug report that is causing the warning.

**Comment by dimvar** [comment]
Closing for now because I'm certain that typedefs can be defined in the source code without issues. If you can provide a repro with more specific instructions, let us know.

**Comment by ChadKillingsworth** [comment]
It's probably because the type is applied to a label/property - not a variable. I'm guessing it'll be treated as a typecast, which makes it difficult. However this should work:

```js
/**
 * @typedef {function(string): string}
 *      #param {string} url
 *      #return {string} the redirect
 */
var RedirectUrlFunc;

/**
 * @type {{redirectUrl:RedirectUrlFunc|null|undefined}}
 */
var foo = {
  redirectUrl: null
};

```

**Comment by chrismiddleton** [comment]
Well, I tried to reproduce the problem with a MWE both on appspot and on my own machine, and couldn't.

The following (with a `@type` above directly above a property) seems to work:

	/**
	 * @typedef {function(string): string}
	 *      #param {string} url
	 *      #return {string} the redirect
	 */
	var RedirectUrlFunc;
	var x = {

	/**
	 * If set equal to a function, this property will ...
         * // ** THIS WORKS FINE **
	 * @type {RedirectUrlFunc?}
	 */
	  y: function (url) {
		console.log('start');
		return url.indexOf('5') !== -1 ? 'foo' : 'bar';
	  }
	};

	/**
	 * @param {RedirectUrlFunc?} func
	 * @param {number} num
	**/
	var baz = function (func, num) {
	  console.log(func('test' + num));
	}

	for (var i = 0; i < 10; i++) {
	  baz(x.y, i);
	}

 So I'm going to assume that somehow something else that I'm doing is causing the issue.

Thanks, Chad, for that alternative method - I'll use that if I can't figure out why my bigger example doesn't work.
