### ISSUE TITLE
Ability to bypass default closure compiler externs (possibly by setting --env=NONE?)

### ISSUE THREAD

**Issue by dhai** [google/closure-compiler#1273]
Previously we were able to pass in all the externs by using the command line flag --use_only_custom_externs.  It appears that passing in env=CUSTOM still loads es3.js, among others.  I currently have custom externs all the way down to the Object level.  Is there a way we can re-include the use_only_custom_externs functionality?

**Comment by ChadKillingsworth** [comment]
This purposefully requires a custom build of the compiler. The compiler would crash when use_only_custom_externs were specified but core language externs were not provided.

**Comment by dhai** [comment]
That makes sense ... I can fork the repo.  Do you remember if there were specific definition(s) that were required to be included when you implemented this?  I remember it working really well with even only a small amount of basic externs.

**Comment by MatrixFrog** [comment]
I'm not sure of the full list off the top of my head, but things that are kind of "built into the language" like Function, Array, String, and Error, should probably all be there.

**Comment by dhai** [comment]
Thanks.  It seems like it's much more than just the basic es3 set, maybe due to @@iterator functionality and such.  Would you guys be interested in a pull request for a minimum required set?

**Comment by concavelenz** [comment]
What is the use case?
