### ISSUE TITLE
clarify which subset of jsdoc and jsdoc version is supported in closure compiler

### ISSUE THREAD

**Issue by samccone** [google/closure-compiler#1277]
> The Closure Compiler's type language derives from the annotations used by the JSDoc document-generation tool. This document describes the set of annotations and type expressions that the Closure Compiler understands.

https://developers.google.com/closure/compiler/docs/js-for-compiler?hl=en
https://github.com/google/closure-compiler/wiki/Using-JSDoc-Annotations-with-Closure-compiler

However when I go to read more about jsdoc tags and how to do some specific things I end up here
http://usejsdoc.org/tags-param.html

yet most of this syntax is unsupported

It would be super useful to provide some more explicit words around what exactly the subset is, and what version of jsdoc the rules are based off of

**Comment by ChadKillingsworth** [comment]
Those two pages are pretty complete. Is there functionality you know that works with the compiler that isn't covered by those pages?

If the syntax or annotations you are looking at isn't referenced on those pages, I would not expect it to work.

**Comment by MatrixFrog** [comment]
We've diverged pretty far from JSDoc at this point. The big table on that page is what we support. That first paragraph should maybe say "originally inspired by JSDoc, but has since added several Closure-specific annotations" or something like that.

**Comment by ChadKillingsworth** [comment]
As equally as important, jsdoc itself has added new syntax that the compiler doesn't support. Example

    /** @param {string} [opt_arg] optional argument */

That's not supported

**Comment by samccone** [comment]
> We've diverged pretty far from JSDoc at this po

:+1: good to know

I would just drop the jsdoc reference then because it is just confusing :grimacing: (at least was to me), as far as new functionality well, there are a bunch of nice things and syntax that jsdoc has that is not supported by closure, but given we are significantly diverged from jsdoc (TIL) I do not have a list of nice to haves off hand.

**Comment by MatrixFrog** [comment]
Added a little clarification to the developers.google.com page.

**Comment by samccone** [comment]
A+ thanks
