### ISSUE TITLE
Add suppress tag for "declaration of multiple variables with shared type information"

### ISSUE THREAD

**Issue by chrismiddleton** [google/closure-compiler#1279]
I don't tend to write code this way, but it would be nice to be able to suppress this warning without suppressing all warnings for the function. I don't see this particular warning (`MULTIPLE_VAR_DEF`) in a diagnostic group other than ALL.

E.g.

    /**
     * @suppress {multipleVars}
    **/
    function foo () {
      var a, b, c, d, e, f, g;
      ...
    }

**Comment by dimvar** [comment]
The code in your example doesn't produce a warning. You need a type annotation for the warning to happen. Eg:
http://closure-compiler-debugger.appspot.com/#input0%3Dvar%2520a%252Cb%252Cc%253B%250A%250A%252F**%2520%2540type%2520%257Bnumber%257D%2520*%252F%250Avar%2520x%252C%2520y%252C%2520z%253B%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES%3D1%26MISSING_PROPERTIES%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1

We generally avoid turning off individual type checking warnings. More customization to the type checker makes it harder to understand what is actually being checked, and if suppressions hide real bugs.

**Comment by ChadKillingsworth** [comment]
I wish we'd just git rid of that warning or move it to a lint check. All it does is serve to annoy me.

**Comment by Dominator008** [comment]
@ChadKillingsworth +1

**Comment by concavelenz** [comment]
The type annotation is being ignored, shouldn't there be a warning for that?

http://closure-compiler-debugger.appspot.com/#input0%3Dvar%2520a%252Cb%252Cc%253B%250A%250A%252F**%2520%2540type%2520%257Bnumber%257D%2520*%252F%250Avar%2520x%252C%2520y%252C%2520z%253B%250A%250Afunction%2520f(%2520%252F**%2520string%2520*%252F%2520a)%2520%257B%257D%250A%250Afunction%2520g()%2520%257B%250A%250Af(x)%253B%250Af(y)%253B%250Af(z)%253B%250A%250A%257D%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES%3D1%26MISSING_PROPERTIES%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1

**Comment by ChadKillingsworth** [comment]
Yes - if it's ignored we should warn. The warning just leave the impression that applying one type annotation to multiple variables may not have been intended by the user. So at a minimum we should update the error message to state that.

It would be better though to support this use case. In either case it's a pretty minor issue.
