### ISSUE TITLE
Skip some code and leave it unchanged

### ISSUE THREAD

**Issue by BlaM** [google/closure-compiler#1282]
My scenario: 
I want to use [browserify](browserify.org) to create a bundled version of the code I want to run on a webpage. I want to use closure-compiler to minify the created bundle. 

In general this works beautifully, but this time I have some code dependency that comes in a minified black-box package and I can't get the original source of that. In theory it shouldn't cause a problem to minify an already minified code - but there's no reason to risk anything. Doing so will sooner or later lead to weird errors that no one can locate or fix.

So let's assume I have this minified "long line of code"...

    function xyz() {blabla();this.is.doing.alotofstuff();1==4&&gettingmoreunreadable().....}

in the middle of my bundled code.

Is there any way to skip that blob of code and leave it unchanged? Something like `/* jshint ignore:start */` ... `/* jshint ignore:end */` for the closure compiler?

I've been trying to find a solution, but that seems to be a missing feature.

**Comment by Dominator008** [comment]
Nothing that I know of can skip a blob of code.

Can you somehow extract that minified code into its own .js file?

**Comment by BlaM** [comment]
That would be my current solution - actually concatenating the files after minification. It wouldn't be my preferred one, though, because it adds an additional build step.

**Comment by Dominator008** [comment]
If the already-minified code is compatible with the optimization mode you are using, then it should be fine to run it through the compiler.

Did you get warnings / errors from that blob of code?

**Comment by BlaM** [comment]
I tried and it seemed to be fine in my test. I'm just not sure if that's a risk I'm willing to take in the long run.

**Comment by ChadKillingsworth** [comment]
Then you're stuck with another build step. Skipping sections isn't something the compiler can do.
