### ISSUE TITLE
Missing extern `Array.from`

### ISSUE THREAD

**Issue by ambar** [google/closure-compiler#1296]

**Comment by Dominator008** [comment]
Care to send a PR?
Should be similar to https://github.com/google/closure-compiler/commit/6f7901cea15d96d3651ec1b190da18ccd1c50968

**Comment by ambar** [comment]
#1297

**Comment by Dominator008** [comment]
Updated in #1298

**Comment by Dominator008** [comment]
What about the two optional parameters? Some issues with them?

**Comment by MatrixFrog** [comment]
The issue is that I completely forgot about them. Sorry about that! The hard part was landing this in a way that doesn't break several Google projects. Now that that's done it should be easy to add those.

**Comment by Dominator008** [comment]
Sounds good :) I have them in #1298

**Comment by Dominator008** [comment]
Reworked in #1377, closing.
