### ISSUE TITLE
Pattern matching of union and nullable types

### ISSUE THREAD

**Issue by chrismiddleton** [google/closure-compiler#1300]
It is a common thing to have to deal with all the possible types of a union type (especially, object or null). In some languages, like Haskell or Rust, there are pattern matching constructs to allow compile-time checking of all the cases. AFAIK, the only way to deal with these union types in CC at the moment is to do casting. The problem with this is that it is tedious and prone to error. If you cast incorrectly, the compiler isn't going to catch that.

Here's a idea of how you could design pattern matching in closure:

    switch (goog.type(foo)) {
        case 'Foo':
            // do something with `foo` known to be a Foo object
            break;
        case 'null':
            // do something with `foo` known to be null
            break;
    }

This could be implemented like:

    if (foo instanceof Foo) {
        // ...
    } else if (foo === null) {
        // ...
    }

Where `goog.type` (or some other method) would just be a virtual thing which the compiler recognizes as a cue to do this pattern matching.

Ideally you would also be able to do it outside of a switch with something like

    if (goog.typeIs(foo, 'Foo')) {
    }

which allows you to do a sort of cast but without having to invent another variable.

Is there any support for this already? I think it would be a really useful feature that would find a lot of bugs and prevent having to do casting all over the place.

**Comment by dimvar** [comment]
The compiler type specializes these unions, casting is not the only option. You can IF-test a union type to get to the members of the union.

http://closure-compiler-debugger.appspot.com/#input0%3D%252F**%2520%2540constructor%2520*%252F%250Afunction%2520Foo()%2520%257B%250A%2520%2520this.prop%2520%253D%2520123%253B%250A%257D%250A%250Afunction%2520f(%252F**%2520%253FFoo%2520*%252F%2520x)%2520%257B%250A%2520%2520if%2520(x%2520%253D%253D%253D%2520null)%2520%257B%250A%2520%2520%2520%2520return%253B%250A%2520%2520%257D%2520else%2520%257B%250A%2520%2520%2520%2520var%2520%252F**%2520!Foo%2520*%252F%2520y%2520%253D%2520x%253B%250A%2520%2520%2520%2520return%2520y.prop%253B%250A%2520%2520%257D%250A%257D%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES%3D1%26MISSING_PROPERTIES%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1

**Comment by chrismiddleton** [comment]
Oh, nice. Is there a way to also check the the type when it's two non-null types, especially if one only exists in a typedef?

    /** @typedef {number} */
    var int;

    /** @param {int|string} foo */
    function bar (foo) {
        if (foo is int) {
        } else { // foo is string
    }

**Comment by dimvar** [comment]
if (typeof foo === "number") {
 ...
} else {
  ...
}

You can't do typeof for custom type names. Instanceof checks inside IFs also tighten the type.

**Comment by chrismiddleton** [comment]
Thanks, using instanceof well help. It would still be nice to be able to do custom types as well; otherwise, they're sort of third-class citizens to the compiler.

**Comment by dimvar** [comment]
This isn't really a compiler issue. typeof is a built-in operator, and it produces a specific set of strings. If you write (typeof foo === "mytype") it will never evaluate to true.

**Comment by chrismiddleton** [comment]
> typeof is a built-in operator, and it produces a specific set of strings. If you write (typeof foo === "mytype") it will never evaluate to true.

I understand that. What I meant was that it would be nice if Closure had the (extra) *capability* to utilize the virtual types in some way. Not with `typeof`, but some other Closure-recognized thing, like `goog.getType` or something like that. In any case, using `instanceof` is a lot better than what I was doing before, so thank you.
