### ISSUE TITLE
Object literals with functions fail to type match against structural interfaces

### ISSUE THREAD

**Issue by shicks** [google/closure-compiler#1304]
```javascript
/** @record */
var Rec = goog.defineClass(null, {
  /** @param {number=} opt_arg
   * @return {string} */
  f: function(opt_arg) {},
});

/** @type {!Rec} */
var rec = {
  /** @param {number=} opt_arg
   * @return {string} */
  f: function(opt_arg) { return '' + opt_arg; }
};
```

produces the following error:

```
input0:9: WARNING - initializing variable
found   : {f: function (number=): string}
required: Rec
var rec = {
          ^
```

https://closure-compiler-debugger.appspot.com/#input0%3D%252F**%2520%2540record%2520*%252F%250Avar%2520Rec%2520%253D%2520goog.defineClass(null%252C%2520%257B%250A%2520%2520%252F**%2520%2540param%2520%257Bnumber%253D%257D%2520opt_arg%250A%2520%2520%2520*%2520%2540return%2520%257Bstring%257D%2520*%252F%250A%2520%2520f%253A%2520function(opt_arg)%2520%257B%257D%252C%250A%257D)%253B%250A%250A%252F**%2520%2540type%2520%257B!Rec%257D%2520*%252F%250Avar%2520rec%2520%253D%2520%257B%250A%2520%2520%252F**%2520%2540param%2520%257Bnumber%253D%257D%2520opt_arg%250A%2520%2520%2520*%2520%2540return%2520%257Bstring%257D%2520*%252F%250A%2520%2520f%253A%2520function(opt_arg)%2520%257B%2520return%2520''%2520%252B%2520opt_arg%253B%2520%257D%250A%257D%253B%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES%3D1%26CLOSURE_PASS%3D1%26MISSING_PROPERTIES%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1

**Comment by blickly** [comment]
Looks like a bug in goog.defineClass rewriting. ES6 class rewriting seems to have the same issue.
