### ISSUE TITLE
@constructor no longer implies @struct

### ISSUE THREAD

**Issue by myphysicslab** [google/closure-compiler#1308]
When referring to a misspelled (non-existant) property name I would like the compiler to report an error.  The compiler does this when the the class is marked with `@struct`.  In the v20151015 compiler release `@constructor` would imply `@struct`, but this has changed at some point since then: I no longer get the desired error unless I mark the class with `@struct`.

Here is an example of the error I want to see:

```
src/sims/pendulum/CompareDoublePendulumApp.js:285: ERROR - Cannot add a property to a 
struct instance after it is constructed.
  this.energyGraph.FOO_BAR = "ugly foo error";   
                   ^
```

That error now only occurs if I add `@struct` to the class definition:

```javascript
/**
* @param {!myphysicslab.lab.model.EnergySystem} system the EnergySystem to display
* @constructor
* @struct
* @implements {myphysicslab.lab.view.DisplayObject}
*/
myphysicslab.lab.graph.EnergyBarGraph = function(system) {
  // code omitted
};
```

See the [announcement about the v20151015 compiler release](https://groups.google.com/forum/#!msg/closure-compiler-discuss/IcQfig9Bd1M/lwERBi4DAgAJ )

> *  ` @struct` is now supported for `@interface` and `@record` declarations in 
>    the "old" type inference (The NTI has this behavior by default). 
>    `goog.defineClass` `@interface`s are `@struct` by default (like 
>    `@constructor`)

**Comment by MatrixFrog** [comment]
`@constructor`-annotated functions have never been `@struct` (though that would be nice). That's only for classes defined with `goog.defineClass` or the `class` keyword.

**Comment by myphysicslab** [comment]
OK, I've updated the wiki page covering this accordingly:
https://github.com/google/closure-compiler/wiki/Using-NTI-(new-type-inference)
See the last section about "misspelled propery names and @struct"
