### ISSUE TITLE
externs/browser/w3c_encoding.js deviates from spec

### ISSUE THREAD

**Issue by inexorabletash** [google/closure-compiler#1311]
**First** off, the spec is a WHATWG publication, not a W3C publication:

```
 * @fileoverview Definitions for W3C's Encoding specification
 *     https://encoding.spec.whatwg.org
```
Right there in the URL. I don't know if the W3C has bothered to snapshot/republish the spec for giggles, but may want to fix that, rename the file, etc.

**Second**, the `decode()` method is annotated to take a non-nullable required Uint8Array as the first argument. Per spec, the first argument is an optional BufferSource.

**Third**, the `decode()` method is annotated to take a required string as the second argument. Per spec, it's an optional string.

extern:
```js
/**
 * @param {!Uint8Array} input
 * @param {Object=} options
 * @return {string}
 */
TextDecoder.prototype.decode = function decode(input, options) {};
```
spec:
```webidl
USVString decode(optional BufferSource input, optional TextDecodeOptions options);
```

**Fourth**, the TextEncoder constructor is given an `options` argument, but one is not present in the spec.

extern:
```js
/**
 * @constructor
 * @param {string=} encoding
 * @param {Object=} options
 */
function TextEncoder(encoding, options) {}
```
spec:
```webidl
[Constructor(optional DOMString utfLabel = "utf-8"),
 Exposed=Window,Worker]
interface TextEncoder { ... };
```

Fifthly (sorry), the `encode()` method is annotated to take a required string as the first argument. Per spec, it's an optional string:

extern:
```js
/**
 * @param {string} input
 * @return {!Uint8Array}
 */
TextEncoder.prototype.encode = function(input) {};
```
spec:
```webidl
 [NewObject] Uint8Array encode(optional USVString input = "");
```

**Comment by blickly** [comment]
Want to send a pull request? At least the required->optional changes should easy to land.

**Comment by inexorabletash** [comment]
Can do, but as I normally just rely on the downloaded .jar it may take a bit.

**Comment by inexorabletash** [comment]
Yay, thanks @phistuck !

**Comment by phistuck** [comment]
@inexorabletash - after https://code.google.com/p/chromium/issues/detail?id=435727 - I think I owe you! :)
