### ISSUE TITLE
Unlike var statements, const statements do not support multiple types

### ISSUE THREAD

**Issue by phistuck** [google/closure-compiler#1314]
Code -
```
// ==ClosureCompiler==
// @output_file_name default.js
// @compilation_level ADVANCED_OPTIMIZATIONS
// @language ECMASCRIPT6_STRICT
// ==/ClosureCompiler==
"use strict";
const
  /** @const {string} */ foo = "1",
  /** @const {number} */ bar = 1;

const
  /** @type {string} */ baz = "1",
  /** @type {number} */ taz = 1;
```

Warnings -
```
JSC_MULTIPLE_VAR_DEF: declaration of multiple variables with shared type information at line 2 character 0
const
^
JSC_MULTIPLE_VAR_DEF: declaration of multiple variables with shared type information at line 6 character 0
const
^
```

Note - changing them to `var` avoids the warnings, of course.

**Comment by phistuck** [comment]
Changing it to `var` works, of course.

**Comment by Dominator008** [comment]
Seems that the second type annotation is added to the first declaration.

http://closure-compiler-debugger.appspot.com/#input0%3Dconst%250A%2520%2520%252F**%2520%2540const%2520%257Bstring%257D%2520*%252F%2520foo%2520%253D%2520%25221%2522%252C%250A%2520%2520%252F**%2520%2540const%2520%257Bnumber%257D%2520*%252F%2520bar%2520%253D%25201%253B%250A%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES%3D1%26LANG_IN_IS_ES6%3D1%26MISSING_PROPERTIES%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1%26TRANSPILE%3D1
