### ISSUE TITLE
Add the ability to indicate that input is provided via stdin

### ISSUE THREAD

**Issue by mgreter** [google/closure-compiler#1315]
With https://github.com/google/closure-compiler/pull/1016 a message was added to stderr when input is coming from stdin. I have my own build tool-set which uses closure-compiler via run3 (it writes to stdin and reads stdout and stderr back). The compiler is invoked with `--warning_level QUIET`. 

With the new message on stderr my tool-set thinks that some error occurred and aborts. I already fixed that by simply filtering out that message from stderr. But I feel that it should not be printed if warning level is set to quiet. I would argue that this message is really just a warning and not an error, so I hope my arguing makes sense.

With best regards
Marcel Greter

**Comment by ChadKillingsworth** [comment]
It's neither warning or error. It's simply user feedback. Without that warning, if someone accidentally omitted a `--js` flag, the compiler would silently block forever as it waited for input to be piped in.

The original implementation deferred printing that message until input had not been received for 1 second. However, that was deemed overly complex and so the feedback was emitted immediately.

Checking for output on stderr seems to be a bad way to detect errors and abort builds. The exit code is a much better indicator. You can promote almost any warning to be an error by using the `--jscomp_error` flags which will fail the build via a non-zero exit code.

**Comment by mgreter** [comment]
I may was too paranoid by checking stderr to be clean/empty, to present it to the user to inspect. I guess I can relax that to include the return value. But not sure if I really want to see that message if I set `--warning_level QUIET`. I just expected a clean `stderr` if nothing relevant was happening. IMO it would be nice to have an option to suppress that message, and I though that it would fit nicely into the warning category. Anyway, thanks for your time.

**Comment by ChadKillingsworth** [comment]
We'd need a way to determine that the user intends to pipe input.

**Comment by MatrixFrog** [comment]
We could force it to be explicit (`--js=/dev/stdin` or something) but that seems overkill. It's nice to be able to just `echo someJs | java -jar compiler.jar` with no special flags. We'll have to think about this.

**Comment by ChadKillingsworth** [comment]
I've done some looking and it seems pretty common for build tools to emit logging data to standard in. I'm not sure it's worth the effort to change this.

@MatrixFrog Internally, the compiler uses `--js=-` to indicate standard input - it's just not allowed to be actually used as a flag value.

**Comment by MatrixFrog** [comment]
> I'm not sure it's worth the effort to change this.

I'm inclined to agree with that.

**Comment by ChadKillingsworth** [comment]
Without a PR, this will probably never be addressed.
