### ISSUE TITLE
Promise.prototype.then complains when the parameter is a method

### ISSUE THREAD

**Issue by phistuck** [google/closure-compiler#1316]
```
// ==ClosureCompiler==
// @output_file_name default.js
// @compilation_level ADVANCED_OPTIMIZATIONS
// @language ECMASCRIPT6_STRICT
// @language_out ECMASCRIPT5_STRICT
// @formatting pretty_print
// ==/ClosureCompiler==
"use strict";
class Foo
{
 constructor() { fetch("url").then(this.bar); }
 /** @param {Response} response */
 bar(response) { console.log(response) }
}

new Foo();
```

Warning -
```
JSC_TYPE_MISMATCH: actual parameter 1 of Promise.prototype.then does not match formal parameter
found   : function (this:Foo, (Response|null)): undefined
required: (function (this:undefined, Response): ?|null|undefined) at line 4 character 35
 constructor() { fetch("url").then(this.bar); }
```

It goes away if I add `@this undefined` to the method.
While this is correct, I consider it a weird complaint. Especially when `this` is not used in the method.

**Comment by MatrixFrog** [comment]
If `this` is not used, perhaps make it a static method, or even just a standalone function.

In general, there is a habit (certainly within Google and probably among other users of the compiler) of putting everything on a class. But this isn't Java -- functions are free to exist separate from any class, and as ES6 modules become more popular it will be even easier to do this without polluting the global namespace.

Or: `fetch("url").then(() => this.bar());`

**Comment by nicks** [comment]
Ya this is a deliberate design decision. "this" is part of the method contract, like any other argument. For example, if someone subclassed Foo, they would expect all callers of bar to be calling it with the right `this` context.

**Comment by phistuck** [comment]
Static methods make me call ClassName.staticMethodName which is a bit ugly within a class method. Ba.
