### ISSUE TITLE
New Type Inference doesn't check invalid object key types

### ISSUE THREAD

**Issue by SLaks** [google/closure-compiler#1330]
Source:

``` js
/** @type {Object<!Object, string>} */
var Y = {};
```

OTI warning:

> input0:2: WARNING - Object type "Object<Object,string>" contains non-stringifiable key and it may lead to an error. Please use ES6 Map instead or implement your own Map structure.  
> var Y = {};

NTI gives no warnings

**Comment by dimvar** [comment]
Yes, NTI doesn't handle parameterized Object yet.
