### ISSUE TITLE
"ES6 is only supported for transpilation to a lower ECMAScript version"

### ISSUE THREAD

**Issue by KOLANICH** [google/closure-compiler#1340]
https://github.com/google/closure-compiler/blob/master/src/com/google/javascript/jscomp/CompilerOptionsPreprocessor.java#L50-L55

Remove this, please, or provide the way to bypass.

**Comment by ChadKillingsworth** [comment]
The way around this is to use `--compilation_level=WHITESPACE_ONLY`. This will do module re-writing only.

This check is in place because many of the optimization passes do not yet fully understand ES6 syntax.

**Comment by KOLANICH** [comment]
>This check is in place because many of the optimization passes do not yet fully understand ES6 syntax.
Why not to allow to use them on user's own risk?

**Comment by ChadKillingsworth** [comment]
The compiler crashes

**Comment by phistuck** [comment]
Why is this issue closed? Closing this issue implies it will never be fixed. Depending on their support considerations, projects do not have to transpile nowadays, where modern browsers have great support for ECMAScript 2015 (and later).

**Comment by ChadKillingsworth** [comment]
See #949 and #950
