### ISSUE TITLE
Warning for functions with variable number of arguments

### ISSUE THREAD

**Issue by vobruba-martin** [google/closure-compiler#1355]
Hi, is this bug or not? IMO there should be no warning because types are OK.

```javascript
/**
 * @param {function(...number):undefined} fn
 */
function callFn(fn) {};

/**
 * @param {number} x
 */
var fnToCall = function(x) {};

callFn(fnToCall);
```

> WARNING - Invalid type for parameter 1 of function callFn.
> expected : function(...number):undefined
> found    : function(number):undefined
> 
> callFn(fnToCall);
>        ^
> 
> 0 error(s), 1 warning(s), 100.0% typed

**Comment by dimvar** [comment]
The argument function requires 1 argument, but if you pass it to callFn it may be called with 0 arguments, so it's not a subtype of function(...number):undefined.
