### ISSUE TITLE
DisambiguateProperties leaves conflicts with optional properties for implicit record implementation

### ISSUE THREAD

**Issue by SLaks** [google/closure-compiler#1358]
Source:

```js
/** @record */
function Record() {}

/** @type {number|undefined} */
Record.prototype.recordProp;

/** @constructor */
function Type() {
  /** @const */
  this.classProp = 'a';
}

/** @param {!Record} a */
function pass(a) { alert(a.recordProp); }

pass(new Type);
```

Compiled output:
```js
/**@record */function Record() {
}
/**@type {(number|undefined)} */Record.prototype.a;
/**@constructor */function Type() {
  /**@const */this.a = "a";
}
/**
@param {!Record} a */function pass(a) {
  alert(a.a);
}
pass(new Type);
```

DisambiguateProperties leaves both `classProp` and `recordProp` as `a`, even though they're both used on the same instance.

Instead, it should notice that `new Type` is used as `Record`, and therefore guarantee that their properties don't conflict.

**Comment by SLaks** [comment]
Demo: http://closure-compiler-debugger.appspot.com/#input0%3D%252F**%2520%2540record%2520*%252F%250Afunction%2520Record()%2520%257B%257D%250A%250A%252F**%2520%2540type%2520%257Bnumber%257Cundefined%257D%2520*%252F%250ARecord.prototype.recordProp%253B%250A%250A%252F**%2520%2540constructor%2520*%252F%250Afunction%2520Type()%2520%257B%250A%2520%2520%252F**%2520%2540const%2520*%252F%250A%2520%2520this.classProp%2520%253D%2520'a'%253B%250A%257D%250A%250A%252F**%2520%2540param%2520%257B!Record%257D%2520a%2520*%252F%250Afunction%2520pass(a)%2520%257B%2520alert(a.recordProp)%253B%2520%257D%250A%250Apass(new%2520Type)%253B%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26AMBIGUATE_PROPERTIES%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES%3D1%26DISAMBIGUATE_PROPERTIES%3D1%26ENABLE_ALL_DIAGNOSTIC_GROUPS%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1%26PROPERTY_RENAMING%3D1

**Comment by blickly** [comment]
Thanks for the repro case. Investigating.
