### ISSUE TITLE
"try" statement is improperly removed in some cases

### ISSUE THREAD

**Issue by digibusiness** [google/closure-compiler#1364]
If I compile this code (that test the sessionStorage/localStorage support)

```javascript
function checkStorageSupport()  {
	try {
		if ((sessionStorage) && (localStorage)) {
			var test = sessionStorage.test;
			test = localStorage.test;
			return (true);
		}
	}
	catch(e) { }
	return (false);
}
```
with simple optimization level, I obtain this code

```javascript
function checkStorageSupport(){return sessionStorage&&localStorage?!0:!1};
```
without the "try" statement.

So, if the browser blocks the sessionStorage/localStorage support (for example in Firefox when cookies are not allwed) the minified code generates an exception, while the unminified code works properly.

**Comment by ChadKillingsworth** [comment]
Because you are assigning the value of the property access to a variable but then never using it, the compiler is eliminating the code.

Try it without the variable assignment - there is special logic in the compiler that recognizes a property access without using the variable as having side effects.

```js
if ((sessionStorage) && (localStorage)) {
        sessionStorage.test;
        localStorage.test;
        return (true);
}
```

You should get a warning (which you can suppress) about suspicious code.

**Comment by digibusiness** [comment]
Thanks for your answer, without the variable assignment it works properly, with warnings.
I understand that the compiler eliminates the unecessary code, but the problem, for me, was the "try" statemement.


Even with this simple code the "try" statement is dropped:
```javascript
function checkStorageSupport()  {
	try {
		if ((sessionStorage) && (localStorage)) {
			return (true);
		}
	}
	catch(e) { }
	return (false);
}
```
```javascript
function checkStorageSupport(){return sessionStorage&&localStorage?!0:!1};
```
Is it normal?

With some tests I found that if I use a local variable, instead of the return false inside "if" statement, compiles correctly:
```javascript
function checkStorageSupport()  {
	var result = false;
	try {
		if ((sessionStorage) && (localStorage)) {
			result = true;
		}
	}
	catch(e) { }
	return (result);
}
```
```javascript
function checkStorageSupport(){var a=!1;try{sessionStorage&&localStorage&&(a=!0)}catch(b){}return a};
```

**Comment by ChadKillingsworth** [comment]
Name references are assumed to never throw - that's why the try statement got eliminated. It will probably work if you use properties:

```js
if (window.localStorage && window.sessionStorage)
```
