### ISSUE TITLE
NullPointerException in NTI's NamespaceLit

### ISSUE THREAD

**Issue by supersteves** [google/closure-compiler#1370]
I'm experimenting with enabling NTI on our large codebase and get this straight away:
```
java.lang.NullPointerException
	at com.google.javascript.jscomp.newtypes.NamespaceLit.toJSTypeIncludingObject(NamespaceLit.java:36)
	at com.google.javascript.jscomp.NTIScope.finalizeScope(NTIScope.java:659)
	at com.google.javascript.jscomp.GlobalTypeInfo.process(GlobalTypeInfo.java:401)
	at com.google.javascript.jscomp.PhaseOptimizer$NamedPass.process(PhaseOptimizer.java:285)
	at com.google.javascript.jscomp.PhaseOptimizer.process(PhaseOptimizer.java:217)
	at com.google.javascript.jscomp.Compiler.check(Compiler.java:793)
	at com.google.javascript.jscomp.Compiler.compileInternal(Compiler.java:698)
	at com.google.javascript.jscomp.Compiler.access$000(Compiler.java:89)
	at com.google.javascript.jscomp.Compiler$2.call(Compiler.java:651)
	at com.google.javascript.jscomp.Compiler$2.call(Compiler.java:648)
	at com.google.javascript.jscomp.CompilerExecutor$2.call(CompilerExecutor.java:93)
```

We use ClosureLibrary, and some custom externs, although I'm not sure if that's relevant.

I've debugged this a little, and in toJSTypeIncludingObject, obj is MaskType with UNKNOWN_MASK.
In finalizeScope, name is "window".

But I can't find out exactly what in our code, externs or Closure Library is triggering this, so can't figure out a standalone test case. How can I trace back a node to the script source filename when debugging? All I can see is "synthetic". 

(Suggestion: It would be useful to have a helper function you can call to diagnose program errors, which would be given a node, and would pretty print the context. This isn't the first time I've struggled to identify which source code triggers a bug in Closure Compiler.)

Anyhow I'd be happy to put together a test case if you can help me to debug it further.

**Comment by dimvar** [comment]
Found a repro. Somehow you are explicitly declaring window to have type ?. (You should probably change that to !Window.) I will fix the crash.

**Comment by dimvar** [comment]
Most of the time, the errors show the source, but sometimes we don't have an associated AST node where the error occurs, so we can't do much about that.

My personal strategy when debugging this is to find the closest place in the stack trace where I have access to a Node, then catch the exception there, print the Node and rethrow.

**Comment by supersteves** [comment]
Thanks @dimvar. Pretty sure we're not intentionally defining window to have type ?, any way I can diagnose where that is being inferred?

In this case I have a Node but a moderate scan of its properties didn't lead me to any input source file name, just "synthetic" in the toString.

**Comment by dimvar** [comment]
Try to look for assignments to window in your code (and externs) and see if you find something suspicious.

**Comment by supersteves** [comment]
Thanks for the quick fix, this should help me try out NTI. 

But I think there's something else going on here, I debugged it again, this time putting a conditional breakpoint on construction of NamespaceLit with "window", it was here:
```
	NamespaceLit.<init>(String) line: 26	
	NTIScope.addNamespaceLit(Node) line: 427	
	GlobalTypeInfo$CollectNamedTypes.mayCreateWindowNamespace(Node) line: 763	
	GlobalTypeInfo$CollectNamedTypes.processQualifiedDefinition(Node) line: 701	
	GlobalTypeInfo$CollectNamedTypes.visit(NodeTraversal, Node, Node) line: 687	
	NodeTraversal.traverseBranch(Node, Node) line: 621	
	NodeTraversal.traverseBranch(Node, Node) line: 615	
	NodeTraversal.traverseBranch(Node, Node) line: 615	
	NodeTraversal.traverse(Node) line: 297	
	NodeTraversal.traverseEs6(AbstractCompiler, Node, NodeTraversal$Callback) line: 564	
	GlobalTypeInfo.process(Node, Node) line: 345	
	PhaseOptimizer$NamedPass.process(Node, Node) line: 285	
	PhaseOptimizer.process(Node, Node) line: 217	
	Compiler.check() line: 793	
	Compiler.compileInternal() line: 698	
	Compiler.access$1(Compiler) line: 677	
```

This gave me the source node, which was the first line of one of my externs (no jsdoc here):
``` javascript
window.__vo_aut_record = function(json) {};
```

Inserting this didn't fix it (the same error happened at the above line):
``` javascript
/** @type {Window} */
var window;
```

I've tried to create a debugger link but can't get it to happen. I can't figure out which Java compiler options correlate to debugger tickboxes. Here's what I tried, no joy:

https://closure-compiler-debugger.appspot.com/#input0%3Dwindow.aaa()%253B%250A%26input1%26conformanceConfig%26externs%3Dwindow.aaa%253D%2520function(json)%2520%257B%257D%253B%26refasterjs-template%26includeDefaultExterns%3D1%26AMBIGUATE_PROPERTIES%3D1%26CHECK_CONSTANTS%3D1%26CHECK_GLOBAL_NAMES%3D1%26CHECK_GLOBAL_THIS%3D1%26CHECK_MISSING_RETURN%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES%3D1%26CHECK_TYPES_NEW_INFERENCE%3D1%26CLOSURE_PASS%3D1%26COALESCE_VARIABLE_NAMES%3D1%26COLLAPSE_ANONYMOUS_FUNCTIONS%3D1%26COLLAPSE_PROPERTIES%3D1%26COLLAPSE_VARIABLE_DECLARATIONS%3D1%26CROSS_MODULE_CODE_MOTION%3D1%26CROSS_MODULE_METHOD_MOTION%3D1%26DEAD_ASSIGNMENT_ELIMINATION%3D1%26DEVIRTUALIZE_PROTOTYPE_METHODS%3D1%26DISAMBIGUATE_PROPERTIES%3D1%26EXTRACT_PROTOTYPE_MEMBER_DECLARATIONS%3D1%26FLOW_SENSITIVE_INLINE_VARIABLES%3D1%26INLINE_CONSTANTS%3D1%26INLINE_FUNCTIONS%3D1%26INLINE_GETTERS%3D1%26INLINE_PROPERTIES%3D1%26INLINE_VARIABLES%3D1%26LABEL_RENAMING%3D1%26LANG_IN_IS_ES6%3D1%26MISSING_PROPERTIES%3D1%26OPTIMIZE_CALLS%3D1%26OPTIMIZE_PARAMETERS%3D1%26OPTIMIZE_RETURNS%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1%26PROPERTY_RENAMING%3D1%26REMOVE_DEAD_CODE%3D1%26REMOVE_UNUSED_PROTOTYPE_PROPERTIES%3D1%26REMOVE_UNUSED_PROTOTYPE_PROPERTIES_IN_EXTERNS%3D1%26REMOVE_UNUSED_VARIABLES%3D1%26REWRITE_FUNCTION_EXPRESSIONS%3D1%26SMART_NAME_REMOVAL%3D1%26SYNTHETIC_BLOCK_MARKER%3D1%26TRANSPILE%3D1%26VARIABLE_RENAMING%3D1

**Comment by dimvar** [comment]
I'm not following. Are you still seeing the same crash, or some other error?

**Comment by supersteves** [comment]
Your fix does indeed work. However your understanding of the cause wasn't right. I wasn't:
> explicitly declaring window to have type ?

I tried to debug what was actually causing this problem, it seems to happen in my externs, but I couldn't create an isolated case. See above.

**Comment by dimvar** [comment]
Oh, I see what you mean.Explicitly declaring window to ? would be just one way to cause this. The general issue was that NTI was crashing when window did not have an object type. So, somehow in your program, window does not have an object type.

**Comment by supersteves** [comment]
Thanks - any suggestions how to locate this please? I have a ton of files, externs, and Closure Library. I can debug the AST during and after compilation. I can put a conditional breakpoint somewhere (?) unless there's an easier way to diagnose and search for type inference.

**Comment by supersteves** [comment]
@dimvar: I found the cause of this Window issue. I use the Java API and was passing in the default externs in alphabetical (wrong) order. See https://github.com/google/closure-compiler/issues/1435.

**Comment by dimvar** [comment]
I've seen some issues with externs ordering recently, commit d3c33dbb50752d447c5baac4f7ec9c1d27d37544 should help when window definitions are out of order.

**Comment by nicks** [comment]
for what it's worth, we've also been running into this problem when running new type inference

**Comment by concavelenz** [comment]
@nicks  can you confirm if you are running head or the release?

**Comment by dimvar** [comment]
@nicks Closing for now. If you do indeed have this crash and can provide repro instructions, I'll take a look.
