### ISSUE TITLE
$ prefix on renamed properties causes angular.equals to misbehave

### ISSUE THREAD

**Issue by jpittenger** [google/closure-compiler#1371]
When allowing the compiler to rename properties, it sometimes results in properties beginning with a $ character (e.g. "$a"). Unfortunately, this causes those properties to be ignored by angular.equals, which means that calling $watch(foo, bar, true) doesn't invoke its callback reliably.

Is there any chance an option can be provided for preventing such a prefix from being used during the renaming process?

**Comment by Dominator008** [comment]
Seems unlikely that we are going to change the renaming. Can you provide a simple repro case?

**Comment by jpittenger** [comment]
I can construct an uncompiled example that demonstrates the undesirable behavior, but I don't have a simple example that results in such a prefixed property when compiled.

**Comment by MatrixFrog** [comment]
Are there other places where Angular makes different decisions based on the name of a variable or property? This seems like something where it would be nice to have Angular not do that, if it's feasible.

**Comment by ChadKillingsworth** [comment]
I'm assuming they do this because things prefixed with `$` are supposed to be reserved for core angular? That guideline isn't universally followed.

**Comment by jpittenger** [comment]
Not that I'm aware of, and I agree that it's a less-than-ideal implementation choice. I don't know that angular.equals is actually used much directly, but $watch is certainly used widely. The documentation starts explicitly mentioning the usage in 1.2.16. Prior to that, it mentions "object equality", though I don't know whether that actually reflects a change in the implementation. 

https://code.angularjs.org/1.2.15/docs/api/ng/type/$rootScope.Scope#$watch
https://code.angularjs.org/1.2.16/docs/api/ng/type/$rootScope.Scope#$watch

Given how critical $watch behavior to Angular applications, it seems unlikely that they would introduce a breaking change unless it was absolutely necessary.

**Comment by jpittenger** [comment]
And yes, Angular uses the $ prefix liberally to represent core constructs in their API. This is the first instance I've seen where it's used to actually alter runtime behavior.

**Comment by TEHEK** [comment]
angular.copy (makes a deep copy of an object), angular.extend (similar to jQuery.extend) and some others have special exceptions and ignore properties that start with "$". They are also used by the framework internally.

**Comment by dimvar** [comment]
We had some discussion about this among the team. It seems that `$` is a common enough symbol, so it's not very safe of Angular to assume that all properties starting with `$` are Angular-related. So, it would be better if there is a fix on the Angular side, to use a rarer prefix. Lowering the priority of this issue for now. If somehow it is not feasible to change Angular, we can revisit this and find a solution on the compiler side.

**Comment by concavelenz** [comment]
@mprobst can you comment?

**Comment by mprobst** [comment]
@dimvar: we have about 1.5 million people using the code like this, so any change like that would be difficult. Would it be possible to have a renaming filter of sorts?

**Comment by ChadKillingsworth** [comment]
Unless I'm missing something, it should be possible to add a special case for this. It would affect AmbiguateProperties and RenameProperties - are there others? While it's unfortunate, I wouldn't expect it to have a significant impact on gzip size.

This could also be temporarily fixed by adding externs for angular users. It's unlikely that symbol renaming would go beyond 2 characters. Adding methods with `@private` would in theory also block use of them. This would not be ideal or permanent though.

I have hopes that Angular 2 will be much closer aligned with ADVANCED mode usage.

**Comment by dimvar** [comment]
@mprobst OK, if it's a core thing that can't be easily changed in Angular, we can make the change in the compiler. Would you be willing to send us a patch to reserve `$` when the angular pass is enabled?

**Comment by mprobst** [comment]
Not sure I understand - when you say you'd make a change to the compiler, what'd I do then? Just enable that change when `--angular_pass` is being passed?

**Comment by dimvar** [comment]
Oh, I was just asking if you can contribute the change.

**Comment by mprobst** [comment]
@dimvar I don't think I know enough about how JSCompiler wants these changes (witness my last few attempts at contributing that failed). I'm also a bit overbooked at this point. So I don't think I'll be able to do that.

**Comment by dimvar** [comment]
OK no worries. Someone from the team will look into this then.

**Comment by ChadKillingsworth** [comment]
A similar situation has arisen with Polymer. I'll tackle both simultaneously.

**Comment by ChadKillingsworth** [comment]
Fixed by 8e55385

**Comment by mprobst** [comment]
Thanks Chad!

>
