### ISSUE TITLE
Unclear "Cannot access property X of non-object type *" [NTI]

### ISSUE THREAD

**Issue by supersteves** [google/closure-compiler#1373]
I have a very large closed codebase for which I'm experimenting with NTI.  I have this problem which I can't find how to reproduce in an isolated form in the debugger:

```ERROR - Cannot access property __t of non-object type *.```

``` javascript
/** 
 * @param {*} obj 
 * @param {!my.ns.SomeConfigObject} jsonConfig
 * @protected
 */
my.ns.NodeOptions.prototype.__buildInternalJSON = function(obj, jsonConfig) {
    obj.__t = my.ns.Helper.someMethod();
    obj.aaa = someOtherMethod();
    ...
};
```

Now there are thousands of identical cases in my codebase. I gather that this might be happening because NTI thinks this has multiple conflicting type definitions, but the param is unambiguously "*" which means any type according to https://developers.google.com/closure/compiler/docs/js-for-compiler
Is this a bug? How can I diagnose this, and hopefully find a way to improve the error message?

**Comment by supersteves** [comment]
OK, it's much simpler than that...
``` javascript
/** @param {*} o */
var a = function(o) {
    o.x = 1;
};
```

Test case:
https://closure-compiler-debugger.appspot.com/#input0%3D%252F**%2520%2540param%2520%257B*%257D%2520o%2520*%252F%250Avar%2520a%2520%253D%2520function(o)%2520%257B%250A%2520%2520%2520%2520o.x%2520%253D%25201%253B%250A%257D%253B%250A%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_TYPES%3D1%26CHECK_TYPES_NEW_INFERENCE%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1

My case is a method which coerces an arbitrary parsed JSON object into a proper class instance.

Didn't find anything about this here:
https://github.com/google/closure-compiler/wiki/Using-NTI-(new-type-inference)

But I looked here:
https://github.com/google/closure-compiler/wiki/A-word-about-the-type-Object

So perhaps I should be using ```Object<?,?>```?

**Comment by dimvar** [comment]
Right, this is working as intended. The * type is not an object, it includes objects but also scalar types. If what you were trying to say is "I don't care about the type, don't typecheck", you should be using the unknown type, written?.

To use * as an object, you have to downcast it first.

**Comment by supersteves** [comment]
Thanks @dimvar. The docs say:
> The ALL type	{*}	Indicates that the variable can take on any type

I take that to mean ```/** @type {*} */var x;``` *could* be an Object but could be something else. So under NTI you have to explicitly cast it to tell the type system it can only be an Object?

I've written the following ready to append to https://github.com/google/closure-compiler/wiki/Using-NTI-(new-type-inference):

**************

> ### ALL type {*} and warning "Cannot access property X of non-object type undefined"
> From the [docs](https://developers.google.com/closure/compiler/docs/js-for-compiler), The ALL type ```{*}``` means *any type* including Object.  Unlike the old type inference, with NTI, this must be downcasted if you want to use it as an Object.

> In old type system, this is OK:
> ``` javascript
/** @type {*} */
var x;
x.y = 1;
```
> In NTI, you get ```WARNING - Cannot access property y of non-object type undefined.```, and must change it to:
> ``` javascript
/** @type {*} */
var x;
/** @type {Object} */(x).y = 1;
```

**************

Firstly is this correct? And secondly this downcast doesn't work:
```
input0:3: WARNING - invalid cast - the types do not have a common subtype
from: undefined
to  : Object|null
/** @type {Object} */(x).y = 1;
```
https://closure-compiler-debugger.appspot.com/#input0%3D%252F**%2520%2540type%2520%257B*%257D%2520*%252F%250Avar%2520x%253B%250A%252F**%2520%2540type%2520%257BObject%257D%2520*%252F(x).y%2520%253D%25201%253B%250A%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES%3D1%26CHECK_TYPES_NEW_INFERENCE%3D1%26MISSING_PROPERTIES%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1

Is this a new bug?

**Comment by supersteves** [comment]
@dimvar I edited my comment (was being an idiot), it makes sense now. Please let me know if above wiki edit is OK before I go ahead.

**Comment by dimvar** [comment]
> Unlike the old type inference, with NTI, this must be downcasted if you want to use it as an Object.

Actually, even in OTI you have to downcast * to use it as an Object. See the example below. NTI doesn't change the meaning of *. The difference is that NTI is stricter about what you can access properties on. In OTI, when you access a property on some type T, it will (unsafely) not warn you if the property exists on any subtype of T. NTI warns. I can add a section in the wiki to explain the missing-property issues, it is not specific to *.

http://closure-compiler-debugger.appspot.com/#input0%3Dfunction%2520f(%252F**%2520*%2520*%252F%2520x)%2520%257B%250A%2520%2520var%2520%252F**%2520!Object%2520*%252F%2520y%2520%253D%2520x%253B%250A%257D%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES%3D1%26MISSING_PROPERTIES%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1

**Comment by supersteves** [comment]
@dimvar Thanks, understood. I take it you'd prefer I don't add my wiki edit above then.

**Comment by dimvar** [comment]
Yes, let's leave it out.
