### ISSUE TITLE
Missing parameters in implemented interface produces no warning

### ISSUE THREAD

**Issue by chrismiddleton** [google/closure-compiler#1376]
Marking a class as satisfying an interface seems to produce no warnings when that implementation is missing parameters. The *call* to the interface is checked, but not the underlying implementation.

With compilation_level=ADVANCED_OPTIMIZATIONS and warning_level=VERBOSE, the following produces no warning:

	/**
	 * @interface
	**/
	function IFoo () {}

	/**
	 * @param {number} baz
	**/
	IFoo.prototype.bar = function (baz) {};

	/**
	 * @constructor
	 * @implements {IFoo}
	**/
	function BigFoo () {}

	BigFoo.prototype.bar = function () {
	  console.log("big");
	};

	/**
	 * @constructor
	 * @implements {IFoo}
	**/
	function SmallFoo () {}

	SmallFoo.prototype.bar = function () {
	  console.log("small");
	};

	/**
	 * @constructor
	 * @param {(boolean?)=} useBig
	**/
	function Boo (useBig) {
	  /** @type {IFoo!} */
	  this.f;

	  this.f = useBig ? new BigFoo() : new SmallFoo();
	}

	//
	Boo.prototype.bar = function () {
		// !! This call is passing a parameter that the implementers aren't expecting.
		// Particularly, this means that if you want to change an interface, compile,
		// and then go look for unfulfilled contracts in the code, you cannot.
		this.f.bar(1);
	};

	var b = new Boo();
	b.bar();

Appspot link: http://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540compilation_level%2520ADVANCED_OPTIMIZATIONS%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%2540warning_level%2520VERBOSE%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250A%252F**%250A%2520*%2520%2540interface%250A**%252F%250Afunction%2520IFoo%2520%28%29%2520%257B%257D%250A%250A%252F**%250A%2520*%2520%2540param%2520%257Bnumber%257D%2520baz%250A**%252F%250AIFoo.prototype.bar%2520%253D%2520function%2520%28baz%29%2520%257B%257D%253B%250A%250A%252F**%250A%2520*%2520%2540constructor%250A%2520*%2520%2540implements%2520%257BIFoo%257D%250A**%252F%250Afunction%2520BigFoo%2520%28%29%2520%257B%257D%250A%250ABigFoo.prototype.bar%2520%253D%2520function%2520%28%29%2520%257B%250A%2520%2520console.log%28%2522big%2522%29%253B%250A%257D%253B%250A%250A%252F**%250A%2520*%2520%2540constructor%250A%2520*%2520%2540implements%2520%257BIFoo%257D%250A**%252F%250Afunction%2520SmallFoo%2520%28%29%2520%257B%257D%250A%250ASmallFoo.prototype.bar%2520%253D%2520function%2520%28%29%2520%257B%250A%2520%2520console.log%28%2522small%2522%29%253B%250A%257D%253B%250A%250A%252F**%250A%2520*%2520%2540constructor%250A%2520*%2520%2540param%2520%257B%28boolean%253F%29%253D%257D%2520useBig%250A**%252F%250Afunction%2520Boo%2520%28useBig%29%2520%257B%250A%2520%2520%252F**%2520%2540type%2520%257BIFoo!%257D%2520*%252F%250A%2520%2520this.f%253B%250A%250A%2520%2520this.f%2520%253D%2520useBig%2520%253F%2520new%2520BigFoo%28%29%2520%253A%2520new%2520SmallFoo%28%29%253B%250A%257D%250A%250ABoo.prototype.bar%2520%253D%2520function%2520%28%29%2520%257B%2520this.f.bar%281%29%253B%2520%257D%253B%250A%250Avar%2520b%2520%253D%2520new%2520Boo%28%29%253B%250Ab.bar%28%29%253B

I didn't try running this with the new type inference as I wasn't sure what deficiencies that might have, but this seemed like something that should've been working in the old type inference.

Note that although it fails to detect missing parameters, it does seem to detect mismatched parameters. If I change the above to implement the `baz` parameter in `BigFoo`, but make it a non-number type, then we will get a type mismatch warning, as expected:

	JSC_HIDDEN_INTERFACE_PROPERTY_MISMATCH: mismatch of the bar property type and the type of the property it overrides from interface IFoo
	original: function (this:IFoo, number): undefined
	override: function (this:BigFoo, string): undefined at line 20 character 0
	BigFoo.prototype.bar = function (baz) {
	^

**Comment by dimvar** [comment]
This is correct. When a class implements an interface, every property of the class must be a subtype of the property of the interface. A function without arguments is a subtype of a function that takes one argument.

**Comment by chrismiddleton** [comment]
> A function without arguments is a subtype of a function that takes one argument.

That seems like an easy way to write inconsistent interface implementations though. Is there a use case for this "feature"? Also, is this behavior documented somewhere?

**Comment by dimvar** [comment]
> That seems like an easy way to write inconsistent interface implementations though

There is nothing inconsistent/unsafe about it. You can always pass a function with fewer arguments to a context that expects a function with more arguments, because the extra arguments can be ignored. The opposite is not true, eg, a function with one argument is not a subtype of a function with 0 arguments. This is standard subtyping rules, we did not invent this. TypeScript also has the same behavior, eg, you can try the following snippet in the TypeScript playground:

    function f(x : (a1:number)=>number) {
      return x(123) - 1;
    }
    function g() { return 5; }
    f(g);
    
    function h(x : ()=>number) {
      return x() - 1;
    }
    function w(x: number) { return 5; }
    h(w);

>  is this behavior documented somewhere?

There is an old blog post that discusses function subtyping, but only related to the types of the arguments, not the number of arguments:
http://closuretools.blogspot.com/2012/06/subtyping-functions-without-poking-your.html

**Comment by chrismiddleton** [comment]
> You can always pass a function with fewer arguments to a context that expects a function with more arguments, because the extra arguments can be ignored.

I think you misunderstood my meaning of "safe". Yes, it is type safe. But the whole point of interfaces is to try and enforce contracts in the code. It will not produce a type error, but it is likely to produce an error in another way because the interface has changed and the implementation in question has not been updated.

**Comment by chrismiddleton** [comment]
To allow this sort of behavior, if there is ever a valid use case, one could have the convention that parameters in the interface marked *optional* could be omitted from an implementing class. That both allows for this behavior and prevents bugs.
