### ISSUE TITLE
Move assignments into function calls

### ISSUE THREAD

**Issue by infusion** [google/closure-compiler#1379]
Hi,

I wonder if it would be a good idea to let Closure Compiler optimize an expression like 
```js
x = a * b;
if (isNaN(x)) p();
```
to
```js
isNaN(x=a*b)&&p();
```

Most of the optimizations are already applied, except for avoiding the double-usage of the variable x - one for the assignment and one for the check in an "assignment-friendly" scope, like a function-invocation. 

I think this is a minor optimization, but as it shouldn't be that seldom to assign a var and checking it against something in this order, the optimized code for large libs could be shed some weight with this simple rule.

**Comment by MatrixFrog** [comment]
Looks reasonable to me.

**Comment by concavelenz** [comment]
The flow sensitive inline should already be doing this. Do you have an example in the debugger.  (Note it doesn't currently occur in global scope)

**Comment by concavelenz** [comment]
The flow sensitive inline should already be doing this. Do you have an example in the debugger.  (Note it doesn't currently occur in global scope)

**Comment by Dominator008** [comment]
This is already optimized with `ADVANCED_OPTIMIZATIONS`.
Input:
```js
// test.js
function p() {
  console.log("");
}

function f(x, a, b) {
  x = a * b;
  if (isNaN(x)) p();
}

f(1, 2, 3);
```
Command:
```sh
$ java -jar build/compiler.jar -O ADVANCED test.js
```
Output:
```js
isNaN(6)&&console.log("");
```

**Comment by infusion** [comment]
Hm? Sure it works with constant folding. But the question was to pass a var assignment directly to a subsequent function call.
