### ISSUE TITLE
[feature request] Add google earth API externs file (attached)

### ISSUE THREAD

**Issue by blickly** [google/closure-compiler#138]
This issue was imported from Closure Compiler's previous home at http://closure-compiler.googlecode.com

The link to the original issue is:
https://blickly.github.io/closure-compiler-issues/#866

**Comment by Dominator008** [comment]
An externs file for the Google Earth API is available at: https://github.com/vicb/VisuGps3/blob/f2e563c2ff5d51091843e01fb7dac1071372cac7/src/vgps3/plugins/earth/externs/google_earth_api.js
