### ISSUE TITLE
ES6 Rest parameter expansion is broken for invocations with new

### ISSUE THREAD

**Issue by cramforce** [google/closure-compiler#1384]
Example
http://closure-compiler-debugger.appspot.com/#input0%3Dnew%2520Foo(...arguments)%26input1%26conformanceConfig%26externs%3Dfunction%2520Foo()%2520%257B%257D%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES%3D1%26LANG_IN_IS_ES6%3D1%26MISSING_PROPERTIES%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1%26TRANSPILE%3D1

Stuff like

```js
new Foo(...arguments)
```

gets rewritten to 
```js
new Function.prototype.bind.apply(Foo, [].concat($jscomp.arrayFromIterable(arguments)));
```

where `new` "applies" to apply.

**Comment by concavelenz** [comment]
This may be a code printer bug.

**Comment by MatrixFrog** [comment]
It looks like it's actually two bugs! One in the code printer and one in the transpilation.
