### ISSUE TITLE
Array.prototype.find missing from polyfills?

### ISSUE THREAD

**Issue by supersteves** [google/closure-compiler#1388]
When running scripts under Java 8's nashorn interpreter (described as being ES 5.1), I found that ```[].find``` was undefined. 

According to MDN it is part of ES 6 / 2015.

Yet I can't see ```find``` anywhere within https://github.com/google/closure-compiler/blob/master/src/com/google/javascript/jscomp/js/es6_runtime.js, and had to add my own polyfill.

Is this missing? It seems some polyfills are present (https://github.com/google/closure-compiler/commit/3c06b5a953bac9e71300454c91184e1b898123aa), some are missing. What are the guidelines for polyfills (when not using Closure Library)? How can I tell which polyfills I need for core and browser JS, assuming ES5 runtime? I can't find any docs about this, and trial and error can't be right.

(Also are the sources for ```es6_runtime.js``` yet to be open-sourced?)

**Comment by supersteves** [comment]
Also presumably the externs system isn't sophisticated enough to be able to reflect language out - hence no compilation error when using Array.find and target lower than ES6?

**Comment by Dominator008** [comment]
I don't think es6_runtime.js is supposed to include all ES6 polyfills.
@shicks Can you explain why the Map/Set polyfills were added?
@MatrixFrog I think we are able to compile core-js now?

**Comment by MatrixFrog** [comment]
We (mainly @shicks) are starting to add polyfills so that users can use pretty much all of ES6, without worrying about which parts are language features and which parts are new APIs. These are not fully supported yet, but I'm sure we'll make an announcement soon. For now, only new language features are supported.

**Comment by supersteves** [comment]
Makes sense, otherwise it's not easy to feel confident you've got all the polyfills you need. Does this mean there should be one for Array.prototype.find(), for example? 

(Otherwise, does anyone have a suggestion for a good ES6 generic polyfill for browser (e.g. babel's?) and also headless JS such as nashorn? Something you can include and not worry about whether CC has it?)

**Comment by MatrixFrog** [comment]
Yes, we will probably write one for Array.prototype.find, so keep an eye out for that to be supported. In the meantime, I assume Babel has good polyfills for such things. There may be a mode where Babel won't modify your code at all, it will just insert the polyfills, but I haven't used Babel myself.

**Comment by ChadKillingsworth** [comment]
I looked into making the externs dependent on language features. It's completely doable, but it requires auditing and splitting all of the build in externs by language level. It wasn't deemed a priority.

It's also complicated when you try to use ES5 code with a polyfill. For instance, Promises are technically an ES6 type but are used in all kinds of ES5 code.

**Comment by Dominator008** [comment]
@supersteves https://github.com/zloirock/core-js?

**Comment by supersteves** [comment]
Wow, you guys are fast to reply. 

@MatrixFrog I didn't mean *run* babel, I meant using https://babeljs.io/docs/usage/polyfill/ or perhaps https://www.npmjs.com/package/babel-es6-polyfill

@ChadKillingsworth Would be cool. The ES5-with-promises case would need the user to supply an extern to indicate Promises was present, failing by default in ES5 mode.

@Dominator008 Thanks, I'll take a look.

**Comment by Dominator008** [comment]
This is fixed in 68953a4a27af1e7992443672910479402ca04b8d.
