### ISSUE TITLE
ES6 function with namespaced default parameter fails to compile

### ISSUE THREAD

**Issue by diegovar** [google/closure-compiler#1397]
```javascript
goog.provide('project.Dog');
project.Dog = class {};
var f = function(testing = new project.Dog()) {
  console.log(testing);
};
f();
```

This fails with the following error on line 3:
    Illegal variable reference before declaration: testing

**Comment by Dominator008** [comment]
The error was actually that "project" was considered undefined. The error message was wrong. I'm also changing the behavior of VariableReferenceCheck to not report error in this case.

**Comment by MatrixFrog** [comment]
I would probably discourage that pattern because it's not clear if the Dog constructor is called once when the function is defined, or every time the function is called, or every time the function is called with no args. (Off the top of my head I don't know which of those three is correct according to the spec.)

**Comment by concavelenz** [comment]
Is this fixed then @Dominator008 ?

**Comment by Dominator008** [comment]
@concavelenz Fixing this in #1398.

**Comment by diegovar** [comment]
According to the mdn (https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Functions/default_parameters) the @MatrixFrog arguments are evaluated at call time.

**Comment by MatrixFrog** [comment]
I'm sure MDN is correct, but equally sure that I will not remember that without having to look it up, when reading code that uses that pattern.

**Comment by concavelenz** [comment]
Personally, I don't find it the least confusing.
