### ISSUE TITLE
generate extern files

### ISSUE THREAD

**Issue by IorPerry** [google/closure-compiler#1399]
Hello,
I was secure to find this issue already written, but with search I don't found it.
My request is adds a output_info to generate files to add as extern in compilation of another file .

I see there is: http://www.dotnetwise.com/code/externs/ but I think it should be better add it on compiler.
As plus I use the post api to compile local files and should be great if I can generate externs files also.

I am pretty sure it was already discussed, but I don't find the old discussion...
Regards,
Antonino Perricone

Ps. I attached my simple builder in vb.net, maybe someone is curious.
[mybuild.vb.txt](https://github.com/google/closure-compiler/files/90118/mybuild.vb.txt)

**Comment by Dominator008** [comment]
There's an ExternExportsPass which creates an externs file containing all exported symbols and properties, but I don't think there's a command line flag for that (yet).

**Comment by IorPerry** [comment]
I see it was created almost 6 years ago, it looks abandoned...

**Comment by MatrixFrog** [comment]
There is a flag for it in the Google-internal version of the compiler, and it is used by a variety of projects.

**Comment by joeyparrish** [comment]
Is anyone planning to add this flag to the open-source compiler?  If not, I volunteer as tribute.

**Comment by Dominator008** [comment]
@joeyparrish I don't think anyone's actively working on adding this flag, so welcome!
