### ISSUE TITLE
Template type inference loses this type

### ISSUE THREAD

**Issue by SLaks** [google/closure-compiler#1400]
```js
/**
 * @param {function(this: SCOPE, ...): RETURN} func
 * @return {function(this: SCOPE, ...): RETURN}
 * @template SCOPE, RETURN
 */
function proxy(func) { return func; }

/** @param {function(this: {a: string})} fn */
function call(fn) { fn.call({a: ''}); }

call(proxy(function() { this.a = 2; }));
```

The `this` inside the callback on the last line loses its type.   The compiler should, but does not, complain that `this.a` is a string.

If you remove the call to `proxy` (which clearly should not affect the types), you'll get an error.

This fails with both OTI and NTI.

https://closure-compiler-debugger.appspot.com/#input0%3D%252F**%250A%2520*%2520%2540param%2520%257Bfunction(this%253A%2520SCOPE%252C%2520...)%253A%2520RETURN%257D%2520func%250A%2520*%2520%2540return%2520%257Bfunction(this%253A%2520SCOPE%252C%2520...)%253A%2520RETURN%257D%250A%2520*%2520%2540template%2520SCOPE%252C%2520RETURN%250A%2520*%252F%250Afunction%2520proxy(func)%2520%257B%2520return%2520func%253B%2520%257D%250A%250A%252F**%2520%2540param%2520%257Bfunction(this%253A%2520%257Ba%253A%2520string%257D)%257D%2520fn%2520*%252F%250Afunction%2520call(fn)%2520%257B%2520fn.call(%257Ba%253A%2520''%257D)%253B%2520%257D%250A%250Acall(proxy(function()%2520%257B%2520this.a%2520%253D%25202%253B%2520%257D))%253B%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES%3D1%26MISSING_PROPERTIES%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1

**Comment by dimvar** [comment]
The way the type checker knows the types in a function without a jsdoc, is when this function is passed as an argument, and the typechecker can grab some meaningful type from the caller. In this case, the caller is generic, so we don't have such a type. By the type `call` is called, `this` is unknown. I doubt that we'll fix this.

**Comment by SLaks** [comment]
Can you infer the type arguments of the caller from its own callsite first?

**Comment by dimvar** [comment]
In general, if you have a generic call `foobar(args)` used in some context that expects a type *A* (in this case `function(this: {a: string})`), you shouldn't use *A* to instantiate the type variables of `foobar`, because `foobar` should be able to return any subtype of *A*. One could probably find an ad-hoc heuristic that works in some cases, but it's unclear that it would provide much benefit.
