### ISSUE TITLE
Unknown types cannot be optional as record type members

### ISSUE THREAD

**Issue by SLaks** [google/closure-compiler#1402]
```js
/** @record */
function Record() {}

/** @type {?|undefined} */
Record.prototype.optional;

/** @type {!Record} */
var x = {};
```

This gives a conversion error that `{}` cannot be converted to `Record`.

Replacing the `?` with any actual type removes the error.

In fact, the error shouldn't happen even without `|undefined`, since `undefined` is a valid value for `?`.

http://closure-compiler-debugger.appspot.com/#input0%3D%252F**%2520%2540record%2520*%252F%250Afunction%2520Record()%2520%257B%257D%250A%250A%252F**%2520%2540type%2520%257B%253F%257Cundefined%257D%2520*%252F%250ARecord.prototype.optional%253B%250A%250A%252F**%2520%2540type%2520%257B!Record%257D%2520*%252F%250Avar%2520x%2520%253D%2520%257B%257D%253B%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES%3D1%26MISSING_PROPERTIES%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1

**Comment by SLaks** [comment]
Using `*` instead of `?` gives the same error.

**Comment by blickly** [comment]
If we interpreted ? as an optional property, then it would be impossible to create @records with required properties of unknown type, which seems like a reasonable desire.

I think that the way to fix this would be to add an @optional annotation (or /** @type {?=} */, etc.) that lets us distinguish between optional and required @record properties.

**Comment by SLaks** [comment]
How about `?|undefined`, to avoid adding new syntax?

**Comment by blickly** [comment]
That also SGTM, but we'd need to make sure to have a way of representing it differently from ? in the type system (currently it's just collapsed to ?)

**Comment by SLaks** [comment]
It looks like that same decision was already made for NTI; see #1051
