### ISSUE TITLE
Lint check for use of String, Boolean, etc.

### ISSUE THREAD

**Issue by MatrixFrog** [google/closure-compiler#1405]
You almost always want the primitive versions (`string`, `boolean`) not the object types.

**Comment by MatrixFrog** [comment]
`String(foo)` is fine (roughly equivalent to `foo.toString()`) but `new String(foo)` and `String` in a type annotation, should be warnings.

**Comment by brad4d** [comment]
I'll take this one.
Using this change as a model as suggested by @blickly 
#1510

**Comment by MatrixFrog** [comment]
#1510 is a good example, but since this will involve JSDoc, looking at [CheckJSDocStyle](https://github.com/google/closure-compiler/blob/master/src/com/google/javascript/jscomp/lint/CheckJSDocStyle.java) might also be helpful.
