### ISSUE TITLE
Extends Function is not compatible with function()

### ISSUE THREAD

**Issue by TheModMaker** [google/closure-compiler#1422]
When I define a type with extends {Function} it is not compatible with arguments that expect function(...).  This is different from variables that are of type Function.  Example:

```javascript
/**
 * @constructor
 * @extends {Function}
 */
function Spy() {}

/** @return {!Spy} */
function createSpy() {}

/** @param {function(number)} arg */
function consume(arg) {}

consume(createSpy());
```

This doesn't compile saying that the argument does not match formal parameter.  The behavior is different if createSpy returns {!Function} or {!Function|!Spy}.

**Comment by dimvar** [comment]
Every function inherits from Function, adding the extends to the constructor has no effect.

The type error you're seeing says that `consume` expects a function that takes a number, and you're passing a Spy instance instead.

**Comment by dimvar** [comment]
I left the wrong comment a second ago. Reopening.

**Comment by dimvar** [comment]
OK, so the issue is this. Every Spy instance is a subtype of `Function`, but that doesn't mean that every Spy instance is a subtype of `function(number)`. So the type error you're seeing is correct.

Another example to make it clearer: `number` and `string` are both subtypes of `(number|string)`, but that doesn't mean that `number` is a subtype of `string`.

**Comment by TheModMaker** [comment]
But if I change createSpy to return ```Function``` then it will work.  And passing ```(number|string)``` is invalid when expecting ```string```.

**Comment by dimvar** [comment]
Oh I see the confusion. `Function` is a loose type, intended for cases where the other function types aren't quite expressive. It basically matches any other function type, it is a subtype and supertype of all functions. So it's a subtype of `function(number)` in this example. It is the equivalent of `?` for function types.

**Comment by ChadKillingsworth** [comment]
@TheModMaker  You are trying to convey restrictions that are beyond what the type system can handle. The only way I know of to accomplish what you want is through some sort of custom pass that copies the type signature of the original and augments it.

**Comment by TheModMaker** [comment]
Ok, thanks for the explanations.  Having createSpy return ```(Function|Spy)``` has the desired effect.  I was just misunderstanding how the ```Function``` type worked.
