### ISSUE TITLE
const (& goog.module exports) unable to infer type (NTI)

### ISSUE THREAD

**Issue by supersteves** [google/closure-compiler#1430]
When using ES6 `const` I'm getting these NTI errors which require me to add unnecessary type annotations:

```
WARNING - All constants must be typed. The compiler could not infer the type of this constant. Please use an explicit type annotation.
```

This happens both with explicit const and when using goog.module exports (which presumably is rewritten internally to use `@const`).

``` javascript
goog.module("A");

class A {}

const a = new A();

exports = {
  A,
  a: new A()
};
```

https://closure-compiler-debugger.appspot.com/#input0%3Dgoog.module(%2522A%2522)%253B%250A%250Aclass%2520A%2520%257B%250A%257D%250A%250Aconst%2520a%2520%253D%2520new%2520A()%253B%250A%250Aexports%2520%253D%2520%257B%250A%2520%2520A%252C%250A%2520%2520a%253A%2520new%2520A()%250A%257D%253B%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES%3D1%26CHECK_TYPES_NEW_INFERENCE%3D1%26CLOSURE_PASS%3D1%26LANG_IN_IS_ES6%3D1%26MISSING_PROPERTIES%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1%26TRANSPILE%3D1

There are 3 cases here, resolved by:

``` javascript
const /** A */ a = new A();

exports = {
  /** @const {function(new:A)} */ A: A,
  /** @const {A} */ a: new A()
};
```

https://closure-compiler-debugger.appspot.com/#input0%3Dgoog.module(%2522A%2522)%253B%250A%250Aclass%2520A%2520%257B%257D%250A%250Aconst%2520%252F**%2520A%2520*%252F%2520a%2520%253D%2520new%2520A()%253B%250A%250Aexports%2520%253D%2520%257B%250A%2520%2520%252F**%2520%2540const%2520%257Bfunction(new%253AA)%257D%2520*%252F%2520A%253A%2520A%252C%250A%2520%2520%252F**%2520%2540const%2520%257BA%257D%2520*%252F%2520a%253A%2520new%2520A()%250A%257D%253B%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES%3D1%26CHECK_TYPES_NEW_INFERENCE%3D1%26CLOSURE_PASS%3D1%26LANG_IN_IS_ES6%3D1%26MISSING_PROPERTIES%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1%26TRANSPILE%3D1

So I've figured out how to work around it, but it looks (to a human!) obvious what the type of the const/exports is. I've also figured out how to explain the type of the constructor being exported.

However I don't know how to work around this case:

``` javascript
/** @enum {string} */
let X = {
  A: "A",
  B: "B"
}

exports = {
  X: X
}
```

https://closure-compiler-debugger.appspot.com/#input0%3Dgoog.module(%2522A%2522)%253B%250A%250A%252F**%2520%2540enum%2520%257Bstring%257D%2520*%252F%250Alet%2520X%2520%253D%2520%257B%250A%2520%2520A%253A%2520%2522A%2522%252C%250A%2520%2520B%253A%2520%2522B%2522%250A%257D%250A%250Aexports%2520%253D%2520%257B%250A%2520%2520X%253A%2520X%250A%257D%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES%3D1%26CHECK_TYPES_NEW_INFERENCE%3D1%26CLOSURE_PASS%3D1%26LANG_IN_IS_ES6%3D1%26MISSING_PROPERTIES%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1%26TRANSPILE%3D1

Is this correct for the type annotation for an enum being exported?

``` javascript
exports = {
  /** @const {Object<string, string>} */X: X
}
```

https://closure-compiler-debugger.appspot.com/#input0%3Dgoog.module(%2522A%2522)%253B%250A%250A%252F**%2520%2540enum%2520%257Bstring%257D%2520*%252F%250Alet%2520X%2520%253D%2520%257B%250A%2520%2520A%253A%2520%2522A%2522%252C%250A%2520%2520B%253A%2520%2522B%2522%250A%257D%250A%250Aexports%2520%253D%2520%257B%250A%2520%2520%252F**%2520%2540const%2520%257BObject%253Cstring%252C%2520string%253E%257D%2520*%252FX%253A%2520X%250A%257D%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES%3D1%26CHECK_TYPES_NEW_INFERENCE%3D1%26CLOSURE_PASS%3D1%26LANG_IN_IS_ES6%3D1%26MISSING_PROPERTIES%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1%26TRANSPILE%3D1

(I suspect not)

**Comment by ChadKillingsworth** [comment]
This may have been fixed by #1348

**Comment by supersteves** [comment]
Definitely not - I'm using today's head (eager to try your modules work).

**Comment by dimvar** [comment]
Smaller repro.

https://closure-compiler-debugger.appspot.com/#input0%3Dclass%2520A%2520%257B%257D%250A%250A%252F%252F%2520The%2520%2540const%2520on%2520the%2520key%2520confuses%2520NTI%2520somehow%250A%252F**%2520%2540const%2520*%252F%250Avar%2520x%2520%253D%2520%257B%2520%252F**%2520%2540const%2520*%252F%2520foo%253A%2520A%2520%257D%253B%250A%250A%252F**%2520%2540const%2520*%252F%250Ax.b%2520%253D%2520A%253B%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES%3D1%26CHECK_TYPES_NEW_INFERENCE%3D1%26CLOSURE_PASS%3D1%26LANG_IN_IS_ES6%3D1%26MISSING_PROPERTIES%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1%26TRANSPILE%3D1
