### ISSUE TITLE
Expose default externs grouping and dependency order

### ISSUE THREAD

**Issue by supersteves** [google/closure-compiler#1435]
[AbstractCommandLineRunner lines 124 and 132](https://github.com/google/closure-compiler/blob/0aab50d06dabb3f40544b8ed1dd1f0ec4d38edf4/src/com/google/javascript/jscomp/AbstractCommandLineRunner.java#L124) declares two private static lists of externs:
``` javascript
// The core language externs expected in externs.zip, in sorted order.
  private static final List<String> BUILTIN_LANG_EXTERNS = ImmutableList.of(
      "es3.js",
      ...
    );

  // Externs expected in externs.zip, in sorted order.
  // Externs not included in this list will be added last
  private static final List<String> BUILTIN_EXTERN_DEP_ORDER = ImmutableList.of(
    //-- browser externs --
    ...
    "browser/w3c_dom1.js",
    ...
    "browser/ie_dom.js",
    ...
  );
```

I use Closure Compiler via the Java API and pass my own compiler inputs directly using ```ClosureCompiler.compileModules(externs, modules, options)```.

I just figured out that an obscure error I was getting in the "ie_dom.js" extern was because I was passing all externs in alphabetical order. This was also the reason for https://github.com/google/closure-compiler/issues/1370#issuecomment-169415439.

So now I'm using reflection to extract these. Can I submit a PR which exposes these two fields as public in a new otherwise empty class ```DefaultExterns```?

**Comment by ChadKillingsworth** [comment]
Things are private by default. However, generally if something is needed to be non-private, PRs for such are accepted. Moving them out of AbstractCommandLineRunner or refactoring them to a new class would be unnecessary.

However, why doesn't the [getBuiltinExterns method](https://github.com/google/closure-compiler/blob/master/src/com/google/javascript/jscomp/AbstractCommandLineRunner.java#L470) work for you?

**Comment by supersteves** [comment]
Just got time to get around to this. @ChadKillingsworth Yes, it works for me. I should have spotted that - sorry.
