### ISSUE TITLE
Question about utilities such as Number.isFinite() and types

### ISSUE THREAD

**Issue by bfricka** [google/closure-compiler#1439]
Per the [ECMAScript spec](http://www.ecma-international.org/ecma-262/6.0/#sec-number.isfinite) `Number.isFinite` takes in `number`, but number can technically be anything without throwing a `TypeError`. This actually makes `Number.isFinite(*)` extremely useful, because the first thing the spec says is that if `number` is not of type number, return false.

Thus, when composing code it seems to follow that you could use:

```js
const DEFAULT_NUM = 1;
function foo(opt_number) {
  var number = Number.isFinite(opt_number) ? opt_number : DEFAULT_NUM;
  // do something w/ number
}
```
This unfortunately throws out a warning due to the es6.js externs requiring a number. Making this work would require reimplementing this useful built-in using more permissive types. Since `Number.isFinite`, `Number.isNaN`, etc., don't throw a `TypeError` when passed the wrong types, is there any reason to be so strict about this, considering the spec specifically outlines valid return values for these functions when types are not `number`?

At the same time, I could see you then arguing, "sure, but if we loosen the type requirements there, we have to loosen them elsewhere, like `parseInt`, etc". I can see that, although I don't necessarily buy that you have to do so.

I'd like to float this out for feedback / advice.

**Comment by MatrixFrog** [comment]
I would say that in general, if you're passing something to `isFinite` that may not be a number at all, it's likely you've already gone wrong somewhere. The exception might be if you're writing a library and you expect your code to be well-typed but that your users are likely not to be using a typechecker and thus their code is not going to be as well-typed. In that case, at the point where the user passes values into your library, you can accept `*` and then immediately throw an error if they pass something other than a number. Then you can cast to number and have all the rest of the code in your library assume it's definitely a number.

You can definitely maintain your own copy of the ES6 externs that are more forgiving on things like this though.

**Comment by bfricka** [comment]
Closing
