### ISSUE TITLE
cannot access properties on generic types with new type inference

### ISSUE THREAD

**Issue by nicks** [google/closure-compiler#1444]
Code:

``` js
/** @constructor */
function F() { this._data = {}; }

/**
  * @return {T}
  * @this {T}
  * @template T
  */
F.prototype.setFieldValue = function (key, val) {
   this._data[key] = val
  return this
}
```

with new type inference, this gives the warning:

```
input0:10: WARNING - Cannot access property _data of non-object type T.
   this._data[key] = val
   ^
```

This builder pattern was well-supported in the old type inference :(

**Comment by concavelenz** [comment]
I think this is WAI, you basically can do nothing with T except assign it to another T, the OTI handles this by treating T as unknown.   An upper bound for T would make this more usable.

**Comment by dimvar** [comment]
Thanks for the report. I'm considering loosening this up until we add bounded generics, because we've gotten a couple of complaints about it already.

**Comment by nicks** [comment]
type bounds would be great :pray:
