### ISSUE TITLE
goog.forwardDeclare is not compatible with goog.module-style requires

### ISSUE THREAD

**Issue by Caffeinix** [google/closure-compiler#1453]
It is currently not possible to replace this code:

``` js
var MyClass = goog.require('some.namespace.MyClass');

/** @type {!MyClass} */
var cls;
```

with this:

``` js
var MyClass = goog.forwardDeclare('some.namespace.MyClass');

/** @type {!MyClass} */
var cls;
```

Instead, one must write this:

``` js
goog.forwardDeclare('some.namespace.MyClass');

/** @type {!some.namespace.MyClass} */
var cls;
```

Which results in inconsistent naming, adds unnecessary boilerplate, and breaks the symmetry between `goog.require` and `goog.forwardDeclare`.

`goog.forwardDeclare` should, like `goog.require`, be optionally assignable to a variable whose name is bound to the forward-declared type for JSDoc purposes within that scope.

**Comment by MatrixFrog** [comment]
I agree this would be a really good thing to have.

**Comment by concavelenz** [comment]
I thought Ben added support for this.

**Comment by MatrixFrog** [comment]
Yes, this works now (I hadn't thought to check, sorry!) and is used a little bit within Google. It could use some documentation.

**Comment by concavelenz** [comment]
@Caffeinix can you confirm this works for you with the current release?

**Comment by blickly** [comment]
Right now, this only works if you also have a 
```
MyClass = goog.module.get('some.namespace.MyClass');
```
somewhere in an inner scope, in which case you can use the short name in both code and annotations.
I agree it would be useful to allow the goog.forwardDeclare without the goog.module.get as long as you are only using it in annotations.

**Comment by Caffeinix** [comment]
This looks to be working even without the goog.module.get now.  My original code snippet seems to function properly.  Thanks!
