### ISSUE TITLE
new type inference not using externs?

### ISSUE THREAD

**Issue by ghosttie** [google/closure-compiler#1456]
I'm using an extern for the Google Visualization API and it compiles fine using the old type system but with NTI I get warnings like this:

```
filevision/ui/field/PieChartField.js:70: WARNING - Type annotation references non-existent type google.visualization.PieChart.
     * @private {?google.visualization.PieChart}
                  ^
```

**Comment by dimvar** [comment]
Can you link to the externs file? Sometimes the definitions there are a bit loose for NTI, eg, namespaces may not be defined.

**Comment by ghosttie** [comment]
Here it is:

[gviz-api.zip](https://github.com/google/closure-compiler/files/106977/gviz-api.zip)

I downloaded it from somewhere (I don't remember) and modified it with some JSDoc annotation to match the textual description in the documentation.

Yesterday I noticed there was also an externs file for this API in the Closure repo at \contrib\externs\google_visualization_api.js but that's missing some of the JSDoc that mine has e.g.

```
/**
 * @override
 */
google.visualization.PieChart.prototype.draw = function(data, opt_options) {};
```

vs

```
/**
 * @param {google.visualization.DataTable|google.visualization.DataView} data
 * @param {Object=} opt_options
 */
google.visualization.PieChart.prototype.draw = function(data, opt_options) {};
```

I'll work on a PR to update the repo extern with the missing annotations.

**Comment by dimvar** [comment]
The definitions for google, google.visualization and google.visualization.PieChart in that file look good. I tried a minimal example with them and NTI recognizes the type without issues.
https://closure-compiler-debugger.appspot.com/#input0%3D%252F**%2520%2540type%2520%257Bgoogle.visualization.PieChart%257D%2520*%252F%250Avar%2520x%253B%26input1%26conformanceConfig%26externs%3Dvar%2520google%2520%253D%2520%257B%257D%253B%250Agoogle.visualization%2520%253D%2520%257B%257D%253B%250A%252F**%2520%2540constructor%2520*%252F%250Agoogle.visualization.PieChart%2520%253D%2520function(container)%2520%257B%257D%253B%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES%3D1%26CHECK_TYPES_NEW_INFERENCE%3D1%26LANG_IN_IS_ES6%3D1%26MISSING_PROPERTIES%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1%26TRANSPILE%3D1

So there is another problem and we don't have enough info here to reproduce. Maybe you didn't provide the externs in that compilation? I'm not sure. If you can give me a way to reproduce the bug, then I can look into it. Closing for now.
