### ISSUE TITLE
[NTI] Crash after compilation

### ISSUE THREAD

**Issue by ChadKillingsworth** [google/closure-compiler#1459]
```
java.lang.IllegalArgumentException: Cannot create Function instance without a FunctionType
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
	at com.google.javascript.jscomp.newtypes.ObjectType.<init>(ObjectType.java:88)
	at com.google.javascript.jscomp.newtypes.ObjectType.makeObjectType(ObjectType.java:129)
	at com.google.javascript.jscomp.newtypes.RawNominalType.createProtoObject(RawNominalType.java:423)
	at com.google.javascript.jscomp.newtypes.RawNominalType.finalize(RawNominalType.java:473)
	at com.google.javascript.jscomp.GlobalTypeInfo.checkAndFinalizeNominalType(GlobalTypeInfo.java:575)
	at com.google.javascript.jscomp.GlobalTypeInfo.process(GlobalTypeInfo.java:403)
	at com.google.javascript.jscomp.PhaseOptimizer$NamedPass.process(PhaseOptimizer.java:285)
	at com.google.javascript.jscomp.PhaseOptimizer.process(PhaseOptimizer.java:217)
	at com.google.javascript.jscomp.Compiler.check(Compiler.java:771)
	at com.google.javascript.jscomp.Compiler.compileInternal(Compiler.java:687)
	at com.google.javascript.jscomp.Compiler.access$000(Compiler.java:83)
	at com.google.javascript.jscomp.Compiler$2.call(Compiler.java:645)
	at com.google.javascript.jscomp.Compiler$2.call(Compiler.java:642)
	at com.google.javascript.jscomp.CompilerExecutor$2.call(CompilerExecutor.java:93)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

Haven't had time to track down a minimal repo case.

**Comment by dimvar** [comment]
Without any repro (not necessarily small) this is really hard to track down.

**Comment by ChadKillingsworth** [comment]
Here's the type definition that's causing the error: https://github.com/google/closure-compiler/blob/master/contrib/externs/jasmine-2.0.js#L208

That looks very suspicious to me. The `jasmine.Spy` method replaces and attaches properties to a function so you can test when it was called, if it was called, how many times it was called, etc. I think it should be changed to return the unknown type.

**Comment by dimvar** [comment]
> I think it should be changed to return the unknown type.

But it's a constructor. Do you mean it should return `?` when it is called without `new`?

**Comment by ChadKillingsworth** [comment]
It's not generally called directly.

 * [spyOn](https://github.com/google/closure-compiler/blob/master/contrib/externs/jasmine-2.0.js#L410)
 * [createSpy](https://github.com/google/closure-compiler/blob/master/contrib/externs/jasmine-2.0.js#L48)

#1422 has a really great discussion of the usage - though I'm using the contrib extern.

**Comment by dimvar** [comment]
Is it the return type of createSpy that you want to change in the externs then?

**Comment by ChadKillingsworth** [comment]
Yes that would be the case. Let me make sure that actually fixes the NTI crash first though.

**Comment by ChadKillingsworth** [comment]
@dimvar this happens with only using the jasmine-2.0.js file as externs:

http://closure-compiler-debugger.appspot.com/#input0%3Dalert('hi')%253B%250A%26input1%26conformanceConfig%26externs%3D%252F*%250A%2520*%2520Copyright%25202015%2520The%2520Closure%2520Compiler%2520Authors.%250A%2520*%250A%2520*%2520Licensed%2520under%2520the%2520Apache%2520License%252C%2520Version%25202.0%2520(the%2520%2522License%2522)%253B%250A%2520*%2520you%2520may%2520not%2520use%2520this%2520file%2520except%2520in%2520compliance%2520with%2520the%2520License.%250A%2520*%2520You%2520may%2520obtain%2520a%2520copy%2520of%2520the%2520License%2520at%250A%2520*%250A%2520*%2520%2520%2520%2520%2520http%253A%252F%252Fwww.apache.org%252Flicenses%252FLICENSE-2.0%250A%2520*%250A%2520*%2520Unless%2520required%2520by%2520applicable%2520law%2520or%2520agreed%2520to%2520in%2520writing%252C%2520software%250A%2520*%2520distributed%2520under%2520the%2520License%2520is%2520distributed%2520on%2520an%2520%2522AS%2520IS%2522%2520BASIS%252C%250A%2520*%2520WITHOUT%2520WARRANTIES%2520OR%2520CONDITIONS%2520OF%2520ANY%2520KIND%252C%2520either%2520express%2520or%2520implied.%250A%2520*%2520See%2520the%2520License%2520for%2520the%2520specific%2520language%2520governing%2520permissions%2520and%250A%2520*%2520limitations%2520under%2520the%2520License.%250A%2520*%252F%250A%250A%252F**%250A%2520*%2520%2540fileoverview%2520Externs%2520for%2520Jasmine%25202.0%2520(not%2520backwards%2520compatibile%2520with%25201.3).%250A%2520*%250A%2520*%2520TODO%253A%2520Missing%2520externs%2520for%2520JsApiReporter%252C%2520real%2520type%2520support%2520for%2520defining%250A%2520*%2520matchers.%250A%2520*%250A%2520*%2520%2540see%2520http%253A%252F%252Fjasmine.github.io%252F2.0%252Fintroduction.html%250A%2520*%2520%2540externs%250A%2520*%252F%250A%250A%250A%252F**%2520%2540const%2520*%252F%250Avar%2520jasmine%2520%253D%2520%257B%257D%253B%250A%250A%250A%252F**%250A%2520*%2520%2540param%2520%257BObject%257D%2520matchers%250A%2520*%252F%250Ajasmine.addMatchers%2520%253D%2520function(matchers)%2520%257B%257D%253B%250A%250A%250A%252F**%250A%2520*%2520%2540return%2520%257B!jasmine.Clock%257D%250A%2520*%252F%250Ajasmine.clock%2520%253D%2520function()%2520%257B%257D%253B%250A%250A%250A%252F**%250A%2520*%2520%2540param%2520%257Bstring%257D%2520name%250A%2520*%2520%2540return%2520%257B!jasmine.Spy%257D%2520spy%250A%2520*%252F%250Ajasmine.createSpy%2520%253D%2520function(name)%2520%257B%257D%253B%250A%250A%250A%252F**%250A%2520*%2520%2540param%2520%257Bstring%257D%2520baseName%250A%2520*%2520%2540param%2520%257BArray%257D%2520methodNames%250A%2520*%252F%250Ajasmine.createSpyObj%2520%253D%2520function(baseName%252C%2520methodNames)%2520%257B%257D%253B%250A%250A%250A%250A%252F**%2520%2540constructor%2520*%252F%250Ajasmine.Clock%2520%253D%2520function()%2520%257B%257D%253B%250A%250A%250A%252F**%2520*%252F%250Ajasmine.Clock.prototype.install%2520%253D%2520function()%2520%257B%257D%253B%250A%250A%250A%252F**%2520*%252F%250Ajasmine.Clock.prototype.uninstall%2520%253D%2520function()%2520%257B%257D%253B%250A%250A%250A%252F**%2520%2540param%2520%257Bnumber%257D%2520ms%2520*%252F%250Ajasmine.Clock.prototype.tick%2520%253D%2520function(ms)%2520%257B%257D%253B%250A%250A%250A%252F**%2520%2540param%2520%257B!Date%257D%2520date%2520*%252F%250Ajasmine.Clock.prototype.mockDate%2520%253D%2520function(date)%2520%257B%257D%253B%250A%250A%250A%250A%252F**%2520%2540constructor%2520%2540template%2520T%2520*%252F%250Ajasmine.Matchers%2520%253D%2520function()%2520%257B%257D%253B%250A%250A%250A%252F**%2520%2540type%2520%257Bjasmine.Matchers%257D%2520*%252F%250Ajasmine.Matchers.prototype.not%253B%250A%250A%250A%252F**%2520%2540type%2520%257BT%257D%2520*%252F%250Ajasmine.Matchers.prototype.actual%253B%250A%250A%250A%252F**%2520%2540param%2520%257B*%257D%2520value%2520*%252F%250Ajasmine.Matchers.prototype.toBe%2520%253D%2520function(value)%2520%257B%257D%253B%250A%250A%250A%252F**%2520%2540return%2520%257Bvoid%257D%2520*%252F%250Ajasmine.Matchers.prototype.toBeDefined%2520%253D%2520function()%2520%257B%257D%253B%250A%250A%250A%252F**%2520%2540return%2520%257Bvoid%257D%2520*%252F%250Ajasmine.Matchers.prototype.toBeFalsy%2520%253D%2520function()%2520%257B%257D%253B%250A%250A%250A%252F**%2520%2540param%2520%257B*%257D%2520value%2520*%252F%250Ajasmine.Matchers.prototype.toBeGreaterThan%2520%253D%2520function(value)%2520%257B%257D%253B%250A%250A%250A%252F**%2520%2540param%2520%257B*%257D%2520value%2520*%252F%250Ajasmine.Matchers.prototype.toBeLessThan%2520%253D%2520function(value)%2520%257B%257D%253B%250A%250A%250A%252F**%2520%2540param%2520%257B*%257D%2520value%2520*%252F%250Ajasmine.Matchers.prototype.toBeCloseTo%2520%253D%2520function(value%252C%2520precision)%2520%257B%257D%253B%250A%250A%250A%252F**%2520%2540return%2520%257Bvoid%257D%2520*%252F%250Ajasmine.Matchers.prototype.toBeNull%2520%253D%2520function()%2520%257B%257D%253B%250A%250A%250A%252F**%2520%2540return%2520%257Bvoid%257D%2520*%252F%250Ajasmine.Matchers.prototype.toBeTruthy%2520%253D%2520function()%2520%257B%257D%253B%250A%250A%250A%252F**%2520%2540return%2520%257Bvoid%257D%2520*%252F%250Ajasmine.Matchers.prototype.toBeUndefined%2520%253D%2520function()%2520%257B%257D%253B%250A%250A%250A%252F**%2520%2540return%2520%257Bvoid%257D%2520*%252F%250Ajasmine.Matchers.prototype.toBeNaN%2520%253D%2520function()%2520%257B%257D%253B%250A%250A%250A%252F**%2520%2540param%2520%257B*%257D%2520value%2520*%252F%250Ajasmine.Matchers.prototype.toContain%2520%253D%2520function(value)%2520%257B%257D%253B%250A%250A%250A%252F**%2520%2540param%2520%257B*%257D%2520value%2520*%252F%250Ajasmine.Matchers.prototype.toEqual%2520%253D%2520function(value)%2520%257B%257D%253B%250A%250A%250A%252F**%2520%2540return%2520%257Bvoid%257D%2520*%252F%250Ajasmine.Matchers.prototype.toHaveBeenCalled%2520%253D%2520function()%2520%257B%257D%253B%250A%250A%250A%252F**%2520%2540param%2520%257B...*%257D%2520var_args%2520*%252F%250Ajasmine.Matchers.prototype.toHaveBeenCalledWith%2520%253D%2520function(var_args)%2520%257B%257D%253B%250A%250A%250A%252F**%2520%2540param%2520%257B(string%257CRegExp)%257D%2520pattern%2520*%252F%250Ajasmine.Matchers.prototype.toMatch%2520%253D%2520function(pattern)%2520%257B%257D%253B%250A%250A%250A%252F**%2520%2540param%2520%257BError%253D%257D%2520opt_expected%2520*%252F%250Ajasmine.Matchers.prototype.toThrow%2520%253D%2520function(opt_expected)%2520%257B%257D%253B%250A%250A%250A%252F**%250A%2520*%2520%2540param%2520%257B(!Function%257Cstring%257C!RegExp)%257D%2520errorTypeOrMessageOrPattern%250A%2520*%2520%2540param%2520%257B(string%257CRegExp)%253D%257D%2520opt_messageOrPattern%250A%2520*%252F%250Ajasmine.Matchers.prototype.toThrowError%2520%253D%2520function(%250A%2520%2520%2520%2520errorTypeOrMessageOrPattern%252C%2520opt_messageOrPattern)%2520%257B%257D%253B%250A%250A%250A%252F**%250A%2520*%2520%2540param%2520%257B!Object%257D%2520clazz%250A%2520*%2520%2540return%2520%257B!jasmine.Matchers%257D%250A%2520*%252F%250Ajasmine.any%2520%253D%2520function(clazz)%2520%257B%257D%253B%250A%250A%250A%252F**%250A%2520*%2520%2540param%2520%257B!Object%257D%2520sample%250A%2520*%2520%2540return%2520%257B!jasmine.Matchers%257D%250A%2520*%252F%250Ajasmine.objectContaining%2520%253D%2520function(sample)%2520%257B%257D%253B%250A%250A%250A%250A%252F**%2520%2540constructor%2520*%252F%250Ajasmine.Spec%2520%253D%2520function()%2520%257B%257D%253B%250A%250A%250A%252F**%2520%2540type%2520%257Bundefined%257Cfunction()%253A%2520string%257D%2520*%252F%250Ajasmine.Spec.prototype.message%253B%250A%250A%250A%252F**%250A%2520*%2520%2540param%2520%257Bfunction(this%253Ajasmine.Spec)%257D%2520after%250A%2520*%252F%250Ajasmine.Spec.prototype.after%2520%253D%2520function(after)%2520%257B%257D%253B%250A%250A%250A%252F**%2520%2540param%2520%257BError%257Cstring%257D%2520e%2520*%252F%250Ajasmine.Spec.prototype.fail%2520%253D%2520function(e)%2520%257B%257D%253B%250A%250A%250A%252F**%250A%2520*%2520%2540param%2520%257Bfunction()%253D%257D%2520opt_onComplete%250A%2520*%252F%250Ajasmine.Spec.prototype.finish%2520%253D%2520function(opt_onComplete)%2520%257B%257D%253B%250A%250A%250A%250A%252F**%250A%2520*%2520%2540constructor%250A%2520*%2520%2540extends%2520%257BFunction%257D%250A%2520*%252F%250Ajasmine.Spy%2520%253D%2520function()%2520%257B%257D%253B%250A%250A%250A%252F**%2520%2540type%2520%257B!jasmine.SpyStrategy%257D%2520*%252F%250Ajasmine.Spy.prototype.and%253B%250A%250A%250A%252F**%250A%2520*%2520%2540return%2520%257Bvoid%257D%250A%2520*%252F%250Ajasmine.Spy.prototype.reset%2520%253D%2520function()%2520%257B%257D%253B%250A%250A%250A%252F**%2520%2540type%2520%257B!jasmine.CallTracker%257D%2520*%252F%250Ajasmine.Spy.prototype.calls%253B%250A%250A%250A%250A%252F**%250A%2520*%2520%2540constructor%250A%2520*%252F%250Ajasmine.CallTracker%2520%253D%2520function()%2520%257B%257D%253B%250A%250A%250A%252F**%250A%2520*%2520%2540return%2520%257Bboolean%257D%250A%2520*%252F%250Ajasmine.CallTracker.prototype.any%2520%253D%2520function()%2520%257B%257D%253B%250A%250A%250A%252F**%250A%2520*%2520%2540return%2520%257Bnumber%257D%250A%2520*%252F%250Ajasmine.CallTracker.prototype.count%2520%253D%2520function()%2520%257B%257D%253B%250A%250A%250A%252F**%250A%2520*%2520%2540param%2520%257Bnumber%257D%2520index%250A%2520*%2520%2540return%2520%257B!Array%257D%250A%2520*%252F%250Ajasmine.CallTracker.prototype.argsFor%2520%253D%2520function(index)%2520%257B%257D%253B%250A%250A%250A%252F**%250A%2520*%2520%2540return%2520%257B!Array.%253C%257Bargs%253A%2520!Array%252C%2520object%253A%2520Object%257D%253E%257D%250A%2520*%252F%250Ajasmine.CallTracker.prototype.allArgs%2520%253D%2520function()%2520%257B%257D%253B%250A%250A%250A%252F**%250A%2520*%2520%2540return%2520%257B%257Bargs%253A%2520!Array%252C%2520object%253A%2520Object%257D%257D%250A%2520*%252F%250Ajasmine.CallTracker.prototype.mostRecent%2520%253D%2520function()%2520%257B%257D%253B%250A%250A%250A%252F**%250A%2520*%2520%2540return%2520%257B!%257Bargs%253A%2520!Array%252C%2520object%253A%2520Object%257D%257D%250A%2520*%252F%250Ajasmine.CallTracker.prototype.first%2520%253D%2520function()%2520%257B%257D%253B%250A%250A%250A%252F**%2520%2540return%2520%257Bvoid%257D%2520*%252F%250Ajasmine.CallTracker.prototype.reset%2520%253D%2520function()%2520%257B%257D%253B%250A%250A%250A%250A%252F**%250A%2520*%2520%2540constructor%250A%2520*%252F%250Ajasmine.SpyStrategy%2520%253D%2520function()%2520%257B%257D%253B%250A%250A%250A%252F**%2520%2540return%2520%257B!jasmine.Spy%257D%2520*%252F%250Ajasmine.SpyStrategy.prototype.callThrough%2520%253D%2520function()%2520%257B%257D%253B%250A%250A%250A%252F**%250A%2520*%2520%2540param%2520%257B*%257D%2520value%250A%2520*%2520%2540return%2520%257B!jasmine.Spy%257D%250A%2520*%252F%250Ajasmine.SpyStrategy.prototype.returnValue%2520%253D%2520function(value)%2520%257B%257D%253B%250A%250A%250A%252F**%250A%2520*%2520%2540param%2520%257B...*%257D%2520var_args%250A%2520*%2520%2540return%2520%257B!jasmine.Spy%257D%250A%2520*%252F%250Ajasmine.SpyStrategy.prototype.returnValues%2520%253D%2520function(var_args)%2520%257B%257D%253B%250A%250A%250A%252F**%250A%2520*%2520%2540param%2520%257B*%257D%2520error%250A%2520*%2520%2540return%2520%257B!jasmine.Spy%257D%250A%2520*%252F%250Ajasmine.SpyStrategy.prototype.throwError%2520%253D%2520function(error)%2520%257B%257D%253B%250A%250A%250A%252F**%250A%2520*%2520%2540param%2520%257BFunction%257D%2520fn%250A%2520*%2520%2540return%2520%257B!jasmine.Spy%257D%250A%2520*%252F%250Ajasmine.SpyStrategy.prototype.callFake%2520%253D%2520function(fn)%2520%257B%257D%253B%250A%250A%250A%252F**%2520%2540return%2520%257B!jasmine.Spy%257D%2520*%252F%250Ajasmine.SpyStrategy.prototype.stub%2520%253D%2520function()%2520%257B%257D%253B%250A%250A%250A%250A%252F**%2520%2540constructor%2520*%252F%250Ajasmine.Suite%2520%253D%2520function()%2520%257B%257D%253B%250A%250A%250A%252F**%250A%2520*%2520%2540param%2520%257Bfunction()%253D%257D%2520opt_onComplete%250A%2520*%252F%250Ajasmine.Suite.prototype.finish%2520%253D%2520function(opt_onComplete)%2520%257B%257D%253B%250A%250A%250A%252F**%250A%2520*%2520%2540param%2520%257Bfunction(this%253Ajasmine.Spec)%257D%2520beforeEachFunction%250A%2520*%252F%250Ajasmine.Suite.prototype.beforeEach%2520%253D%2520function(beforeEachFunction)%2520%257B%257D%253B%250A%250A%250A%252F**%250A%2520*%2520%2540param%2520%257Bfunction(this%253Ajasmine.Spec)%257D%2520afterEachFunction%250A%2520*%252F%250Ajasmine.Suite.prototype.afterEach%2520%253D%2520function(afterEachFunction)%2520%257B%257D%253B%250A%250A%250A%250A%252F**%2520%2540constructor%2520*%252F%250Ajasmine.Env%2520%253D%2520function()%2520%257B%257D%253B%250A%250A%250A%252F**%2520%2540type%2520%257Bjasmine.Spec%257D%2520*%252F%250Ajasmine.Env.prototype.currentSpec%253B%250A%250A%250A%252F**%2520%2540return%2520%257Bvoid%257D%2520*%252F%250Ajasmine.Env.prototype.execute%2520%253D%2520function()%2520%257B%257D%253B%250A%250A%250A%252F**%2520%2540param%2520%257Bfunction(this%253Ajasmine.Spec)%257D%2520handler%2520*%252F%250Ajasmine.Env.prototype.afterEach%2520%253D%2520function(handler)%2520%257B%257D%253B%250A%250A%250A%252F**%2520%2540param%2520%257Bfunction(this%253Ajasmine.Spec)%257D%2520handler%2520*%252F%250Ajasmine.Env.prototype.beforeEach%2520%253D%2520function(handler)%2520%257B%257D%253B%250A%250A%250A%252F**%250A%2520*%2520%2540return%2520%257B!jasmine.Env%257D%250A%2520*%252F%250Ajasmine.getEnv%2520%253D%2520function()%2520%257B%257D%253B%250A%250A%250A%252F**%2520%2540param%2520%257Bfunction(this%253Ajasmine.Spec%252C%2520function())%257D%2520handler%2520*%252F%250Afunction%2520afterEach(handler)%2520%257B%257D%250A%250A%250A%252F**%2520%2540param%2520%257Bfunction(this%253Ajasmine.Spec%252C%2520function())%257D%2520handler%2520*%252F%250Afunction%2520beforeEach(handler)%2520%257B%257D%250A%250A%250A%252F**%250A%2520*%2520%2540param%2520%257Bstring%257D%2520description%250A%2520*%2520%2540param%2520%257Bfunction(this%253Ajasmine.Suite)%257D%2520handler%250A%2520*%252F%250Afunction%2520describe(description%252C%2520handler)%2520%257B%257D%250A%250A%250A%252F**%250A%2520*%2520%2540param%2520%257Bstring%257D%2520description%250A%2520*%2520%2540param%2520%257Bfunction(this%253Ajasmine.Suite)%257D%2520handler%250A%2520*%252F%250Afunction%2520fdescribe(description%252C%2520handler)%2520%257B%257D%250A%250A%250A%252F**%250A%2520*%2520%2540param%2520%257B*%257D%2520expectedValue%250A%2520*%2520%2540return%2520%257Bjasmine.Matchers%257D%2520matcher%250A%2520*%252F%250Afunction%2520expect(expectedValue)%2520%257B%257D%250A%250A%250A%252F**%250A%2520*%2520%2540param%2520%257Bstring%257D%2520description%250A%2520*%2520%2540param%2520%257Bfunction(this%253Ajasmine.Spec%252C%2520function())%257D%2520handler%250A%2520*%252F%250Afunction%2520it(description%252C%2520handler)%2520%257B%257D%250A%250A%250A%252F**%250A%2520*%2520%2540param%2520%257Bstring%257D%2520description%250A%2520*%2520%2540param%2520%257Bfunction(this%253Ajasmine.Spec%252C%2520function())%257D%2520handler%250A%2520*%252F%250Afunction%2520fit(description%252C%2520handler)%2520%257B%257D%250A%250A%250A%252F**%250A%2520*%2520%2540param%2520%257BObject%257D%2520spiedOnObject%250A%2520*%2520%2540param%2520%257Bstring%257D%2520methodName%250A%2520*%2520%2540return%2520%257B!jasmine.Spy%257D%2520spy%250A%2520*%252F%250Afunction%2520spyOn(spiedOnObject%252C%2520methodName)%2520%257B%257D%250A%250A%250A%252F**%250A%2520*%2520%2540nosideeffects%250A%2520*%2520%2540param%2520%257Bstring%257D%2520description%250A%2520*%2520%2540param%2520%257Bfunction(this%253Ajasmine.Suite)%257D%2520handler%250A%2520*%252F%250Afunction%2520xdescribe(description%252C%2520handler)%2520%257B%257D%250A%250A%250A%252F**%250A%2520*%2520%2540param%2520%257Bstring%257D%2520description%250A%2520*%2520%2540param%2520%257Bfunction(this%253Ajasmine.Spec%252C%2520function()%253D)%257D%2520handler%250A%2520*%252F%250Afunction%2520xit(description%252C%2520handler)%2520%257B%257D%250A%250A%250A%252F**%250A%2520*%2520%2540type%2520%257Bjasmine.Spec%257D%250A%2520*%252F%250Avar%2520currentSpec%253B%250A%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES%3D1%26CHECK_TYPES_NEW_INFERENCE%3D1%26LANG_IN_IS_ES6%3D1%26MISSING_PROPERTIES%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1%26TRANSPILE%3D1

**Comment by dimvar** [comment]
OK I was able to repro this.
