### ISSUE TITLE
Large compile time fluctuations depending on input shape and compiler version

### ISSUE THREAD

**Issue by jfparadis** [google/closure-compiler#1465]
### Summary: 
1. compile time fluctuates by several order of magnitude depending on the version of the compiler.
2. that fluctuation also depends on the structure of the file, such as the length of the individual lines.

Profiling indicates that the fluctuation comes from the parsing stage inside the compiler. In the past, we have mitigated the problem by inserting extra carriage returns into the source JS. 

The last two releases appear to be immune to this problem, but we need extensive testing before upgrading, which complicates our upgrade path.

### Questions: 
- Does anyone have insights about compile time sensitivity to input (any known trigger we could filter) and mitigating strategies?

- Since the problem appears to have been corrected in the last two releases, is there a test to guard agains that behavior reappearing?

### Sample results 
This is a sample run against `test1.js` (no carriage return) and `test2.js` (carriage return) as generated below. The results are capped at 60s, otherwise they can run for hours without any indication of convergence.

| Version  | test1.js (s)  | test2.js (s) |
| ------------- | ------------- | ------------- |
|compiler-20130411|37.28|1.97|
|compiler-20130603|37.54|2.09|
|compiler-20130722|37.64|2.02|
|compiler-20130823|37.59|2.22|
|compiler-20131014|36.96|2.05|
|compiler-20131118|2.01|2.12|
|compiler-20140110|2.22|2.02|
|compiler-20140303|2.13|2.88|
|compiler-20140407|2.39|2.29 
|compiler-20140508| > 60| > 60|
|compiler-20140625| > 60| > 60|
|compiler-20140730| > 60| > 60|
|compiler-20140814| > 60| > 60|
|compiler-20140923| > 60| > 60|
|compiler-20141023| > 60| > 60|
|compiler-20141120| > 60| > 60|
|compiler-20141215| > 60| > 60|
|compiler-20150126| > 60| > 60|
|compiler-20150505| > 60| > 60|
|compiler-20150609| > 60| > 60|
|compiler-20150729| > 60| > 60|
|compiler-20150901| > 60| > 60|
|compiler-20150920| > 60| > 60|
|compiler-20151015|2.79|2.90|
|compiler-20151216|2.57|3.16|

### Steps to reproduce:
 A. Generate a large synthetic JS file called it `test1.js` using this command:

```
#!/usr/bin/env node
var fs = require('fs');

function generateLargeObject(count, depth) {
    var foo = [];
    for (var i = 0; i < count; i ++) {
        var man = {};
        foo.push(man);
        for (var j = 0; j < depth; j ++) {
            var prop = "p" + j;
            var chu = {};
            man[prop] = chu;
            man = chu;
        }
    }
    return JSON.stringify(foo);
}

var code = generateLargeObject(1700, 100); // Around 1MB
code = code.replace(/"/g,"");
fs.writeFile('test1.js', code);
```

B. This file will contain an array of `count = 1700` objects each made of `depth = 100 ` objects:

`[{p0:{p1:{p2:{ ... p<depth>:{}}}}, ... <count>]`

C. Dowload and unzip several versions of the compiler, leaving them as-is in their own sub-directory:

```
$ ls
compiler-20130411
compiler-20130603
...
compiler-20151216

```

D. Use the following script to run each version against the test file, with a time limit of 60s, and create a log:

```
#!/bin/sh

LOG=test.log
FORMAT="%e seconds, %M KB max"
GTIME="gtime --output=$LOG --append --format"
TIMELIMIT='timelimit -t 60'
CLOSURE_OPT='--js_output_file /dev/null --warning_level QUIET'

date > $LOG
for f in ./compiler-*; do
    if [[ -d $f ]]; then
        echo $f >> $LOG
        $GTIME "$FORMAT" $TIMELIMIT java -jar $f/compiler.jar $1 $CLOSURE_OPT
    fi
done
```

`./test.sh  test1.js `

E. Use this script to insert line breaks in the source JS file after each array item and rerun the test against the updated file:

```
#!/usr/bin/env node

var fs = require('fs');

fs.readFile('test1.js', function(err, content) {
    var code = content.toString();
    code = code.replace(/,/g,",\n");
    fs.writeFile('test2.js', code);

});
```

`$ ./test.sh  test2.js `

**Comment by dimvar** [comment]
There were some parser bugs that were fixed at commits 07a16823826f44b01ca3cde33fd3ba97b3e9aa18 and 1dfbfb02f379284f181c35f1d72e0b91723298a1.

Newlines act as separators, so the lookahead stops and you don't get the issue.

> Since the problem appears to have been corrected in the last two releases, is there a test to guard agains that behavior reappearing?

We have some regression tests (not open sourced) but only a few, they don't catch every regression.
