### ISSUE TITLE
this is not recognized in functions in object literals

### ISSUE THREAD

**Issue by SLaks** [google/closure-compiler#1466]
I can't get the compiler to recognize the type of `this` inside a function in an object literal:

``` js
{ m: function() { return this.m; } }
```

This fails in both OTI and NTI (NTI warns about the global `this` object).

http://closure-compiler-debugger.appspot.com/#input0%3Dvar%2520x%2520%253D%2520%252F**%2520%2540type%2520%257B%257Bm%253A%2520function()%253A%2520function()%257D%257D%2520*%252F%2520(%257B%250A%2520%2520m%253A%2520function()%2520%257B%2520%250A%2520%2520%2520%2520var%2520%252F**%2520null%2520*%252F%2520v%2520%253D%2520this%253B%250A%2520%2520%2520%2520return%2520this.m%253B%2520%250A%2520%2520%257D%250A%257D)%253B%26input1%26conformanceConfig%3Drequirement%253A%2520%257B%2520%250A%2520%2520type%253A%2520CUSTOM%2520%250A%2520%2520java_class%253A%2520'com.google.javascript.jscomp.ConformanceRules%2524BanUnknownThis'%250A%2520%2520error_message%253A%2520'No%2520unknown%2520this!'%2520%250A%257D%250A%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES%3D1%26CHECK_TYPES_NEW_INFERENCE%3D1%26LANG_IN_IS_ES6%3D1%26MISSING_PROPERTIES%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1%26TRANSPILE%3D1

**Comment by dimvar** [comment]
As a first step, NTI should at least not warn about unknown THIS, but it would still not know the type. As a second step, it would recognize the type in some object literals (eg, ones that are assigned to a prototype property). Recognizing it for all object literals is not super straightforward.

**Comment by SLaks** [comment]
Why isn't that straightforward?

What if the object literal is assigned to an `@record` type (which is my actual use case)?

**Comment by ChadKillingsworth** [comment]
Property collapsing and aliasing make use of the `this` keyword unsafe in these situations - thus difficult.

**Comment by SLaks** [comment]
If it's assigned to an `@record`, all of those problems should go away.

**Comment by ChadKillingsworth** [comment]
I wasn't aware that it was ever guaranteed that interfaces were exempt from property collapsing. And if they are now, that it will always be that way. If so, then yes this could be inferred.
