### ISSUE TITLE
Update readme to say guava 19

### ISSUE THREAD

**Issue by supersteves** [google/closure-compiler#1471]
I believe guava was updated to v19, readme still says 18.

**Comment by Dominator008** [comment]
@supersteves Care to send a PR?

**Comment by supersteves** [comment]
@Dominator008 (ahem) sure... I just tried to and found that pom-main has 19 and pom-gwt has 20, is this a problem, or should I document both?

**Comment by ChadKillingsworth** [comment]
Just list both (comma separated) in the version field.

**Comment by Dominator008** [comment]
@supersteves Once Guava 20 is released we will switch both to 20.
