### ISSUE TITLE
Ability to require CommonJS modules from goog.modules

### ISSUE THREAD

**Issue by supersteves** [google/closure-compiler#1472]
I'm keen to try @ChadKillingsworth's integration of module interoperability/deps flags, but I would like to use be able to require a good.module from a CommonJS module and vice versa.

https://github.com/google/closure-compiler/wiki/JS-Modules says the following, I think because it doesn't current work and doesn't yet have a planned solution:

> Importing goog.module code from a CommonJS Module
> ```
// For goog.module, fall back go using goog.require
// ??
```

And:

> goog.module support is always enabled in the compiler.
>   How do we import other modules within a Closure-Library style file? Must we resort to using the normalized module identifier? If so, we should find a better way to do this.

I think this is more than just missing docs. I suspect trying this just won't work or is not recommended due to rewriting module names not being formally define.

Does / should any of these work and be recommended?

#### In a CommonJS module
```
const m = goog.require("my.ns.Thing");
const n = goog.require("goog:my.ns.Thing");
const o = goog.require("/legacy/my/ns/Thing");
const p = require("my.ns.Thing");
const q = require("goog:my.ns.Thing");
const r = require("/legacy/my/ns/Thing");
```

#### In a goog.module
```
const a = goog.require("/path/to/CJSModule");
const b = require("/path/to/CJSModule");
const c = goog.require("$path$to$CJSModule"); // or something like this
```

**Comment by ChadKillingsworth** [comment]
Thanks for writing up these examples. I'll add them to the wiki page.

While you can only use one type of *export* statement in a file/module, you should be able to mix imports (with the exception of the actual ES6 import statement - it's only valid in an ES6 module).

### CommonJS
In a CommonJS module, this should work:

```js
// These are both the standard usage
const m = goog.require("my.ns.Thing");
const r = require("/legacy/my/ns/Thing");
```

The remaining statements are mostly non-sensical:

```js
// The goog: prefix is only for use in path based import systems
const n = goog.require("goog:my.ns.Thing"); 

// goog.require imports namespaces, not paths
const o = goog.require("/legacy/my/ns/Thing");

// CommonJS requires import paths. Named imports are not yet supported.
// Namespaces will never be supported
const p = require("my.ns.Thing");

// I'm on the fence as to whether this should work or not. 
// It would never function in uncompiled mode. However I'm not sure mixing
// these module systems ever makes sense in an uncompiled state as
// goog.require works by using script tag insertion and `require` isn't a browser
// based loader.
//
// I think simply using the goog.require statement for this case makes more sense
// and would definitely let a CommonJS/node developer know what was going on. 
const q = require("goog:my.ns.Thing");
```

I do have planned for CommonJS modules that `require` statements alone won't trigger full module rewriting. It will rewrite the `require` statement, but not rescope the file. This will allow you to use `require` within closure-library style code to import modules.

### goog.module

These should work:

```js
// This should work, but currently will not if the file also has a goog.provide statement.
// It will also trigger full module rewriting on the file.
const b = require("/path/to/CJSModule");

// This should also work, but the module normalized name is considered
// an internal, and purposefully undocumented, implementation detail
// This usage is discouraged.
const c = goog.require("module$path$to$CJSModule");
```

The following is never intended to work. When the `require` statement doesn't trigger a full module rewrite, it can be used. Until then only the undocumented normalized module name would work.

```js
// goog.require imports namespaces - not paths
const a = goog.require("/path/to/CJSModule");
```

**Comment by ChadKillingsworth** [comment]
@joeltine @concavelenz Do either of you have thoughts on the goog.module/goog.require interop with other module systems?

**Comment by supersteves** [comment]
So in short, it should just work, and this is just missing docs, providing you use these two forms:

In a CommonJS module, when importing from a goog.module: ``` const m = goog.require("my.ns.Thing"); ```

In a goog.module, when importing from a CommonJS module: ``` const b = require("/path/to/CJSModule"); ```

(But ```require("/legacy/my/ns/Thing")``` was meant to indicate an alternate way of referencing a goog.module in an imaginary project with all namespaced code under a "legacy" folder; presumably this is also in fact nonsensical)

I understand that you can't do this in a ```goog.provide``` script, and imagine there is no equivalent of ```goog.module.declareLegacyNamespace()``` in CommonJS modules.

So, incidentally, does CommonJS, and the above 2 interop's, work in uncompiled state?

**Comment by ChadKillingsworth** [comment]
> So, incidentally, does CommonJS, and the above 2 interop's, work in uncompiled state?

No not really. CommonJS has limited use within a browser, and goog.require was really only designed for  use within a browser.

You can of course write custom definitions for each to make it work in both environments. I've seen polyfill definitions to make `require` work in a browser, but it's tricky because `require` is a synchronous call. Most of the polyfills I've seen require a pre-processor to bundle the files together at a minimum.

There is [some work for using Closure-Library directly within NodeJS](https://github.com/google/closure-library/blob/master/closure/goog/bootstrap/nodejs.js), but I'm definitely not the expert on such cases.

**Comment by ChadKillingsworth** [comment]
I freely admit that the argument for all code working uncompiled is quickly eroding. Using pre-processors has become the norm, thanks to ES6.

**Comment by concavelenz** [comment]
goog.require doesn't require inserting script tags, take a look at the node bootstrap for closure library (for uncompiled code).

**Comment by supersteves** [comment]
@ChadKillingsworth I wrote up a couple of examples, please let me know if these are right and I'll remove the comment.
https://github.com/google/closure-compiler/wiki/JS-Modules

**Comment by ChadKillingsworth** [comment]
@supersteves They look correct, but using `require` will automatically treat the file as a module. That's a problem for some. I've got a couple of PRs stacked up that will fix the issue.

**Comment by supersteves** [comment]
Which one? or both? They're titled "...from a goog.module", doesn't that mean they're already a module?

**Comment by supersteves** [comment]
I'm revisiting this, perhaps it has moved forwards? But I can't find a pattern that works for importing (this time around) ES6 modules from a goog.module.

**Comment by supersteves** [comment]
Update: this works:

``` javascript
class A {
}
export default A;
```
``` javascript
goog.module("some.namespace.B");
const A = goog.require("module$path$to$A").default;
new A();
```
Note the ```.default```.

**Comment by danmaas** [comment]
As of the 20160517 compiler release, for using CommonJS module from a Google module it now seems possible to just use:
const A = require('path/to/A');

**Comment by ChadKillingsworth** [comment]
Module import statements can now be intermixed.

**Comment by supersteves** [comment]
@ChadKillingsworth I'll try the ```const A = require('path/to/A');``` approach within a goog.module.  However will this work if I'm importing an ES6 module? And do I need to turn on CJS module processing to enable this at all?

**Comment by ChadKillingsworth** [comment]
You do need to turn on commonjs module processing. For ES6 modules, it's just `import Foo from 'path/to/A'` or `const Foo = require('path/to/A').Foo;`

**Comment by supersteves** [comment]
Thanks. I see the wiki page has changed greatly. I'll try it. Could do with clarification on the effect of the CJS flag, presumably it specifically enables processing of require() and module.exports? Also whether you can mix "import ..." into a goog.module?
