### ISSUE TITLE
WEBGL_draw_buffers extension missing in externs/browser/webgl.js

### ISSUE THREAD

**Issue by kranich** [google/closure-compiler#1475]
[WEBGL_draw_buffers extension](https://www.khronos.org/registry/webgl/extensions/WEBGL_draw_buffers/) is ratified by Khronos, but missing in [externs/browser/webgl.js](https://github.com/google/closure-compiler/blob/master/externs/browser/webgl.js).

**Comment by Dominator008** [comment]
Care to send a PR?

**Comment by kranich** [comment]
@Dominator008 See PR #1406.

**Comment by Dominator008** [comment]
Sorry didn't notice that PR was sent already.

**Comment by Dominator008** [comment]
Closed by #1406.
