### ISSUE TITLE
Ant tests failing on Windows

### ISSUE THREAD

**Issue by supersteves** [google/closure-compiler#1477]
Presumably this is an Ant-specific issue since the build is shown to be passing. I checked out today's 7af4fc1fa30d000b438c0acb9c34678c0b57cf16 and ```ant clean test``` produced 4 failures in CommandLineRunnerTest, e.g.:

```
testGlobJs1	Error	expected:<[var a;var b;]> but was:<[]>

org.junit.ComparisonFailure: expected:<[var a;var b;]> but was:<[]>
at com.google.common.truth.Platform.comparisonFailure(Platform.java:133)
at com.google.common.truth.Truth$1.failComparing(Truth.java:62)
at com.google.common.truth.StringSubject.isEqualTo(StringSubject.java:64)
at com.google.javascript.jscomp.CommandLineRunnerTest.compileFiles(CommandLineRunnerTest.java:1942)
at com.google.javascript.jscomp.CommandLineRunnerTest.testGlobJs1(CommandLineRunnerTest.java:1104)
```

I believe the plan is to drop support for Ant, but didn't think this was done yet.

I tried also ```mvn test``` and it hung on CommandLineRunnerTest (?) - after several minutes with zero CPU, I killed it. Running the test individually from Eclipse shows it is waiting for stdin in CommandLineRunner:682

Am I missing something, or is this a genuine issue? I'm trying to rebase a PR branch and can't tell if it's got a problem.

**Comment by Dominator008** [comment]
@supersteves They are passing on my machine. What's your platform?

**Comment by supersteves** [comment]
Yes, Windows

**Comment by Dominator008** [comment]
@supersteves #1480 Should fix it.

**Comment by ChadKillingsworth** [comment]
Might look at #1482 as well ...

**Comment by Dominator008** [comment]
@ChadKillingsworth Seems to be working for me.
