### ISSUE TITLE
Renaming of --transpile_only to --skip_non_transpilation_passes

### ISSUE THREAD

**Issue by kranich** [google/closure-compiler#1479]
Contrary to its commit message, [google/closure-compiler@8d8fe2a](https://github.com/google/closure-compiler/commit/8d8fe2a216a25c388e46e8095bbb3a095b096103) removed `--transpile_only` but forgot to add `--skip_non_transpilation_passes` instead.

So there currently seems to be no command line option to transpile only.

**Comment by Dominator008** [comment]
@blickly I suspect "--skip_non_transpilation_passes" is added to the internal runner, but not the external one?

**Comment by dimvar** [comment]
If I remember correctly, you can get just transpilation by using whitespace-only mode and setting lang-in to ES6 and lang-out to ES5 or ES3. You shouldn't need a new command line flag for this.
