### ISSUE TITLE
Compiling multiple input files

### ISSUE THREAD

**Issue by gagern** [google/closure-compiler#1482]
Since 62ca536d0a184a8852646e2bc2db178f700f5cfc it is no longer possible to write

    java -jar compiler.jar --js_output_file result.js --js input1.js input2.js input3.js

as was possible before. Instead I apparently have to prefix every single input file with `--js=`. Since the README doesn't mention `--js` at all, this makes me believe that the current state of affairs is unintentional. Correct me if I'm wrong.

**Comment by Dominator008** [comment]
This is working for me on the current master.

**Comment by Dominator008** [comment]
Thanks for the report. I'm adding a test to make sure this doesn't happen again.
