### ISSUE TITLE
Publish new releases to Maven Central

### ISSUE THREAD

**Issue by jochenberger** [google/closure-compiler#1485]
The latest version available from Maven Central is v20151216: http://search.maven.org/#search|gav|1|g%3A%22com.google.javascript%22%20AND%20a%3A%22closure-compiler%22

**Comment by Dominator008** [comment]
The v20160125 release introduced a regression in the usage of glob patterns so we have rolled it back. Hopefully a new release should be ready soon.

See https://groups.google.com/forum/?nomobile=true#!topic/closure-compiler-discuss/85OnmHMjytY

**Comment by jochenberger** [comment]
What about v20160208? It's not available from Maven Central either.

**Comment by Dominator008** [comment]
Looks like @lindner is the one who handles our Maven releases.

**Comment by jochenberger** [comment]
Reopen please

**Comment by Dominator008** [comment]
@jochenberger It will be there soon. Hang on.

**Comment by jjpeters67** [comment]
v20160208

**Comment by jart** [comment]
+1 to a Maven push. Right now I'm having to roll my Closure Compiler jars by hand and push them to Cloud Storage, because there's no way to build this project hermetically inside Bazel.

**Comment by Dominator008** [comment]
@jart Are you using the `closure_js_binary()` rule from the open source Bazel? I've just updated the Closure dependencies in https://github.com/bazelbuild/bazel/pull/910.

**Comment by jart** [comment]
@Dominator008 Those rules did not work due to a bug in Bazel (something about not being able to reference the foo.BUILD files) and they did not meet the requirements of my project. So I wrote my own rules for Closure, which have greatly expanded functionality. I'd like to contribute them back to the project.

**Comment by jochenberger** [comment]
The release is out for two weeks and still no sign in Maven Central. Maybe the Maven release should be made part of the release process.

**Comment by MatrixFrog** [comment]
@jochenberger That is on my todo list, in fact.

**Comment by lindner** [comment]
Sorry about the delay.  On it.

**Comment by lindner** [comment]
Good grief.  The java 8 javadoc thing rears it's ugly head again.  We should get a travis build going to catch these things...  I'm going to locally commit fixes on the branch so we can push a release.

**Comment by lindner** [comment]
v20160206 is now pushed to central.  Thanks for the patience.

**Comment by Dominator008** [comment]
@lindner http://search.maven.org/#search%7Cga%7C1%7Ca%3A%22closure-compiler%22 still says v20151216 is the latest version.

**Comment by lindner** [comment]
Might be some lag?

https://oss.sonatype.org/#nexus-search;quick~closure-compiler

has it as released.  If it doesn't show up in the next few hours I'll dig deeper.

**Comment by lindner** [comment]
actually  the artifacts are there:

http://repo1.maven.org/maven2/com/google/javascript/closure-compiler/v20160208/

might be an out-of-date search index.

**Comment by Dominator008** [comment]
@lindner Thanks!

**Comment by blickly** [comment]
Thanks Paul!

**Comment by jochenberger** [comment]
Reopen please, v20160517 is not available.

**Comment by jochenberger** [comment]
I still think that the Maven release should be made part of the release process, be it by automation or some kind of release checklist item.
