### ISSUE TITLE
goog.module applying @const on exports makes ES6 classes unable to be subclassed

### ISSUE THREAD

**Issue by hochhaus** [google/closure-compiler#1492]
When using goog.module() with ES6 subclasses [1] and accessControls enabled [2] the compiler errors with:

````
example/child.js:6: ERROR - example.Child is not allowed to extend final class example.Parent.
  constructor() {
  ^
````

Per John's comment on CLD this is because exports are marked as @const and @const on classes is an alias for @final. This same code compiles fine with accessControls disabled.

https://groups.google.com/forum/#!topic/closure-library-discuss/rAZZdcL9QM0

[1] example files

example/parent.js
-----------------

```javascript
goog.module('example.Parent');

exports = class Parent {
  constructor() {
    console.log('parent');
  }
};
```

example/child.js
----------------

```javascript
goog.module('example.Child');

const Parent = goog.require('example.Parent');

exports = class Child extends Parent {
  constructor() {
    super();
    console.log('child');
  }
};
```

example/app.js
--------------

```javascript
goog.module('example.App');

const Child = goog.require('example.Child');

let c = new Child();
console.log(c);
```

[2] compiler command line

```
java -jar third_party/closure-compiler/upstream/compiler.jar --compilation_level=ADVANCED_OPTIMIZATIONS --js example/*.js --jscomp_error=* --jscomp_off=inferredConstCheck --hide_warnings_for=[synthetic --language_in=ECMASCRIPT6_STRICT --language_out=ECMASCRIPT5_STRICT --entry_point=goog:example.App
```

**Comment by ChadKillingsworth** [comment]
I just came across this myself. Same thing happens with CommonJS Modules.

I'll need a fix for this pretty quick. What are the implications of requiring an explicit `@final`?

**Comment by concavelenz** [comment]
I think if we change from rewriting the JSDoc to using the AST "const" annotation we can get the "const"-ness we need for type inferrence without the @final implication

**Comment by pstjvn** [comment]
I think I have the same problem, but disabling accessControl might lead to other issue, is there another workaround?

**Comment by concavelenz** [comment]
If we aren't going to fix this, we should disable support for final classes.

**Comment by MatrixFrog** [comment]
We discussed this at the meeting yesterday. There was general support for chaning `@final` to mean only non-subclassable and `@const` to mean only non-reassignable, but @blickly seemed to think that @concavelenz had some objection to that at one point. John do you remember what the objection was?

**Comment by concavelenz** [comment]
No objection here except that we already use it to mean "@const".  I thought that this was true of jsdoc as well but I don't see that when I looked today.

**Comment by ChadKillingsworth** [comment]
I'm fine with `@final` implying `@const` - just not the other way around.

**Comment by shicks** [comment]
This is moot if you avoid "default"-style exports in favor of "exports.MyClass = ...".

Still, agree it should be fixed.

**Comment by hochhaus** [comment]
I believe this is fixed by https://github.com/google/closure-compiler/commit/ab9bf81.
