### ISSUE TITLE
@expose deprecated with no suitable replacement

### ISSUE THREAD

**Issue by danielgindi** [google/closure-compiler#1494]
Not much to say about this - it's just that the recommendation of `@export` or `@nocollapse` does not give the effect of `@expose`.

I want to prevent the rename of something... How do I do that?

**Comment by ChadKillingsworth** [comment]
Use quoted properties.

There is not a way with annotations to do this, but there has long been other options. You can also maintain an eternal interface and mark your type as implementing that interface.

I'd like to add such functionality, but it is a rather large piece of work and simply not a priority.

At the point that someone familiar enough with the whole compiler is willing to take this on, we can reopen.
