### ISSUE TITLE
v20160125 / v20160201 missing in Binary-Downloads

### ISSUE THREAD

**Issue by tdelmas** [google/closure-compiler#1498]

**Comment by Dominator008** [comment]
v20160125 broke usages of glob patterns so it was rolled back. Hopefully we will release another version soon. See https://groups.google.com/forum/m/#!topic/closure-compiler-discuss/85OnmHMjytY.

**Comment by tdelmas** [comment]
Thanks

**Comment by Dominator008** [comment]
@tdelmas v20160208 is out at https://github.com/google/closure-compiler/wiki/Binary-Downloads#v20150208

**Comment by tdelmas** [comment]
Thank you for the follow up !
