### ISSUE TITLE
@nosideeffects methods are not being removed - no warnings generated

### ISSUE THREAD

**Issue by ChadKillingsworth** [google/closure-compiler#1506]
Can someone setup to use git-bisect to figure out where this was introduced?

http://closure-compiler-debugger.appspot.com/#input0%3Dvar%2520foo%2520%253D%2520ns1.stringify('foo')%253B%26input1%26conformanceConfig%26externs%3D%252F**%2520%2540const%2520*%252F%250Avar%2520ns1%2520%253D%2520%257B%257D%253B%250A%250A%252F**%250A%2520*%2520%2540param%2520%257B*%257D%2520arg%250A%2520*%2520%2540nosideeffects%250A%2520*%252F%250Ans1.stringify%2520%253D%2520function(arg)%2520%257B%257D%253B%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SUSPICIOUS_CODE%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES%3D1%26CHECK_UNREACHABLE_CODE%3D1%26CHECK_VISIBILITY%3D1%26DEAD_ASSIGNMENT_ELIMINATION%3D1%26LANG_IN_IS_ES6%3D1%26MISSING_PROPERTIES%3D1%26PRETTY_PRINT%3D1%26SMART_NAME_REMOVAL%3D1%26TRANSPILE%3D1

**Comment by Dominator008** [comment]
Did it ever use to work?

**Comment by ChadKillingsworth** [comment]
External methods marked with @nosideeffects removed? Yes it most certainly did. I remember @concavelenz adding `@nosideeffects` to Document.prototype.createElement because he wasn't are of the hidden side effects and breaking my builds.

**Comment by ChadKillingsworth** [comment]
I recreated it on the web service and the debugger, but it is successfully removed from all versions I can find (including master) on the command line. I'm not sure there's anything to do at this point ...

**Comment by Dominator008** [comment]
What command did you use?

**Comment by ChadKillingsworth** [comment]
Further experimentation leads me to believe that this isn't in fact an issue. It has to do with using the 'stringify' name in the recreation example.
