### ISSUE TITLE
Compilation issues when trying to minify javascript

### ISSUE THREAD

**Issue by mpusarla** [google/closure-compiler#1517]
When trying to minify using closure compiler, i am getting the following errors:

```
    [ERROR] JSC_PARSE_ERROR. Parse error. syntax error at input line 145 : 23
    	getComputedStyle = $__0.getComputedStyle,
```
   
	
```
    [ERROR] JSC_PARSE_ERROR. Parse error. invalid property id at input line 1131 : 135
    	var WalkontableEvent = ($__event__ = require("event"), $__event__ && $__event__.__esModule && $__event__ || {default: $__event__}).WalkontableEvent;

```
The second error is happening whereever there is the default keyword.

Can you help me understand if I need to pass any additional options?

Thanks,
Madhu.

**Comment by Dominator008** [comment]
Those look like error messages from a very old compiler release using the old Rhino parser. Can you upgrade to v20160208?
https://github.com/google/closure-compiler/wiki/Binary-Downloads#v20160208

**Comment by mpusarla** [comment]
Thanks, updating to the latest version resolved the issue.
