### ISSUE TITLE
does not optimize if (result >= 0.0 && result <= 0.0)

### ISSUE THREAD

**Issue by glensc** [google/closure-compiler#1518]
```
$ cat a.js
```

```javascript
var result=0.0; if (result >= 0.0 && result <= 0.0) console.log(result);
```

results:
```javascript
var result=0;0<=result&&0>=result&&console.log(result);
```

but it should result:

```javascript
var result=0;0==result&&console.log(result);
```

or even:
```javascript
console.log(0);
```

ps: :dancer: 

![alt text](http://www.commitstrip.com/wp-content/uploads/2016/01/Strip-Un-code-inutile-650-finalenglish-1.jpg "Logo Title Text 1")

**Comment by MatrixFrog** [comment]
We do optimize this if you have advanced mode turned on.

http://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540compilation_level%2520ADVANCED_OPTIMIZATIONS%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250Avar%2520result%253D0.0%253B%2520if%2520(result%2520%253E%253D%25200.0%2520%2526%2526%2520result%2520%253C%253D%25200.0)%2520console.log(result)%253B
