### ISSUE TITLE
error when using --dependency_mode=LOOSE or NONE

### ISSUE THREAD

**Issue by ghosttie** [google/closure-compiler#1519]
If I use --dependency_mode=LOOSE or NONE I get this error:

```
_closure-library/protractor_spec.js:3: ERROR - Variable Promise first declared in externs.zip//es6.js
var Promise = require('promise');
    ^
```

I was told to tag @ChadKillingsworth

**Comment by Dominator008** [comment]
That file is declaring a global variable Promise which conflicts with the extern definition.

Looks like it's just a Protractor spec file for Closure Library's continuous integration.
You can safely exclude that file from your compilation using a glob, like here: https://github.com/google/closure-library/blob/master/scripts/ci/compile_closure.sh#L24.

**Comment by joeltine** [comment]
@ghosttie What pattern were you following that you were attempting to compile `protractor_spec.js`?

**Comment by ghosttie** [comment]
The js command line options I was using originally were

```
			--js=_closure-library ^
			--js=!/**_test.js ^
			--js=filevision ^
			--js=!**template.js ^
```

The second two are specific to my application.

I changed from --only_closure_dependencies to its equivalent --dependency_mode=STRICT but because [the documentation](https://github.com/google/closure-compiler/wiki/Managing-Dependencies) said

> If you're writing a library and you're primarily using Closure Compiler to do syntax checking on that library, then you should not use --dependency_mode=STRICT or --dependency_mode=LOOSE

I changed to default/NONE and got these errors.

**Comment by Dominator008** [comment]
@ghosttie I think the [FAQ](https://github.com/google/closure-compiler/wiki/Managing-Dependencies#faq) is saying that if you also want static checking on files that will be dropped during compilation, eg: files that don't `goog.provide` / `goog.require` anything, then you should not use `--dependency_mode=STRICT` or `--dependency_mode=LOOSE`.

If you want the compiler to manage all your Closure dependencies then please stick with `--dependency_mode=STRICT`.

**Comment by ghosttie** [comment]
My app is a toolkit rather than an end product - it provides ui widgets, database access etc. and other developers use it to create point solutions.

So when I run the compiler I'd like it to syntax check everything, not just the classes that are referenced by the toolkit.

From the wording of the FAQ I thought that meant I should use NONE and the developers creating solutions using the toolkit should use STRICT.

**Comment by Dominator008** [comment]
@ghosttie In that case `--only_closure_dependencie` or its equivalent `--dependency_mode=STRICT` would drop any file that isn't `goog.require`d. Did that fit your use case?

**Comment by ghosttie** [comment]
No, when I compile the toolkit I don't want it to drop any files - I want it to syntax check _everything_.

When other developers are creating solutions using the toolkit they should use STRICT because they'll only want to compile the parts of the toolkit they're using.

If you wanted to syntax check all of the Closure Library how would you do it?

**Comment by Dominator008** [comment]
@ghosttie You should go with NONE. I was just wondering how you were able to not drop anything with `--only_closure_dependencies`.

**Comment by ghosttie** [comment]
I wasn't, I tried to work around it by compiling it with a test implementation that exercised as much of the toolkit as possible.  Then when I read the FAQ it occurred to me that I might be able to compile everything without that.

**Comment by Dominator008** [comment]
@ghosttie Got it. Thanks.
