### ISSUE TITLE
Possible issue "restricted index type"

### ISSUE THREAD

**Issue by supersteves** [google/closure-compiler#1522]
The current head of the compiler on github has started giving this error for the following reasonably common pattern:
``` javascript
var arr = ["a"];
for (var key in arr) {
  console.log(typeof key); // "string"
  arr[key]; // complains
  arr[Number(key)]; // ok
  arr[+key]; // ok
}
```
```
WARNING - restricted index type
found   : string
required: number
  arr[key];
```
(OTI; something similar in NTI)

https://closure-compiler-debugger.appspot.com/#input0%3Dvar%2520arr%2520%253D%2520%255B%2522a%2522%255D%253B%250Afor%2520(var%2520key%2520in%2520arr)%2520%257B%250A%2520%2520console.log(typeof%2520key)%253B%2520%252F%252F%2520%2522string%2522%250A%2520%2520arr%255Bkey%255D%253B%2520%252F%252F%2520complains%250A%2520%2520arr%255BNumber(key)%255D%253B%2520%252F%252F%2520ok%250A%2520%2520arr%255B%252Bkey%255D%253B%2520%252F%252F%2520ok%250A%257D%250A%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES%3D1%26LANG_IN_IS_ES6%3D1%26MISSING_PROPERTIES%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1%26TRANSPILE%3D1

I can understand why it's complaining. In ```es3.js``` core extern, ```Array``` implements ```IArrayLike``` which extends ```IObject<number, VALUE2>```.

In this code snippet, NTI+OTI both think that ```key``` is of type string. I think this is correct (unless ```IArrayLike``` should somehow make "in" produce numbers - equally I don't think I should try to tell the compiler that ```key``` is a number - clearly ```key``` is indeed a string at runtime.)

But since an Array is a type of Object, are its keys are also strings internally? You can access properties using ```arr[0]``` or ```arr["0"]``` and both work. 

I understand if you feel this is not a bug - apologies for filing if so - and can easily adapt the small number (11) of occurrences in our codebase to specify a workaround (```Number(key)``` or ```+key``` - I'm not sure which is best / most correct). 

Presumably array access is a case where using a non-numeric string will always be invalid in a well-typed codebase, and this is a specific situation where you need to type-convert it (unnecessarily at runtime) to help the compiler, while getting the benefit of catching many other cases of passing the wrong index type.

**Comment by Dominator008** [comment]
http://stackoverflow.com/questions/500504/why-is-using-for-in-with-array-iteration-such-a-bad-idea
Fortunately, we have:
https://github.com/google/closure-compiler/blob/master/src/com/google/javascript/jscomp/lint/CheckForInOverArray.java

**Comment by supersteves** [comment]
Ahem, thanks!
