### ISSUE TITLE
Using --module for incremental compilation

### ISSUE THREAD

**Issue by pspeter3** [google/closure-compiler#1524]
Is it possible to use `--module` to invoke the Closure Compiler multiple times. The goal is to use it with Bazel to produce incremental libraries for development.

**Comment by dimvar** [comment]
For questions, please use: https://groups.google.com/forum/#!forum/closure-compiler-discuss

The issue tracker is to report bugs or for feature requests.

The compiler is only whole program, and there isn't a plan to do optimizations incrementally. Incremental type checking would be nice, and we are looking into it. (If you end up posting at the mailing list, please provide some specifics about what you're trying to accomplish.)

**Comment by ChadKillingsworth** [comment]
FYI `--module` still only invokes the compiler once. It simply splits the output into multiple files. It's pretty analogous to web pack split points: https://webpack.github.io/docs/code-splitting.html
