### ISSUE TITLE
Allow OTI + NTI warnings

### ISSUE THREAD

**Issue by supersteves** [google/closure-compiler#1525]
I have a large codebase some of which is legacy and almost static, and other parts are "fresh" clean code with higher quality standards. This is enforced using a combination of custom warnings guards in Java, since I don't use the command line in my project. (I also use eslint with .eslintrc files.)

Now I want to migrate to NTI in the new code, but disable all warnings in the old code. Currently I have about 10,000 NTI warnings, 90% of which are JSC_NTI_NULLABLE_DEREFERENCE, with a long tail of other exclusively NTI warnings.

(NB., @dimvar [reassures me](https://groups.google.com/d/msg/closure-compiler-discuss/RgIck4kFrFY/K_CAG-8cAgAJ) that I don't normally need to worry about NTI missing things that OTI catches).

So I plan on 
* disabling all these NTI warnings in the legacy areas of the code
* selectively enabling others (most of them) in the more recent areas
* and probably enabling all warnings for entirely new code being devleoped.

However this means that should an OTI-detected issue be introduced by a developer in the older parts of my codebase, **I won't see any warnings - not even OTI ones**.

Now I don't want to introduce two compilations to my build process. So I propose putting together a PR which allows you to customise the compiler and allow both types of warning simultaneously:

This would be ```CompilerOption.reportOldTypeInferenceErrors```, false by default. Configurable only by direct Java use (I don't propose a command-line flag on something which will ultimately be removed when NTI eventually replaces OTI). Relevant only when ```useNewTypeInference=true```.

When true it adjusts/disables the behaviour in:

``` javascript
    if (options.getNewTypeInference()) {
      options.checkTypes = true;
      options.setWarningLevel(DiagnosticGroups.OLD_CHECK_TYPES, CheckLevel.OFF);
      options.setWarningLevel(
          DiagnosticGroup.forType(RhinoErrorReporter.TYPE_PARSE_ERROR),
          CheckLevel.WARNING);
    }
```
(https://github.com/google/closure-compiler/blob/master/src/com/google/javascript/jscomp/Compiler.java#L351)

and also:
``` javascript
    if (options.getNewTypeInference()) {
      options.checkGlobalThisLevel = CheckLevel.OFF;
    }
```
``` javascript
      if (!options.getNewTypeInference() && !options.disables(DiagnosticGroups.MISSING_RETURN)) {
        callbacks.add(
            new CheckMissingReturn(compiler));
      }
```
``` javascript
    if (!options.disables(DiagnosticGroups.CHECK_USELESS_CODE) ||
        (!options.getNewTypeInference() && !options.disables(DiagnosticGroups.MISSING_RETURN))) {
      checks.add(checkControlFlow);
    }
```
``` javascript
    if (!this.runsAfterNTI) {
      compiler.report(error);
    }
```

I've not tried this, but am assuming this won't cause instability.

Is this likely to be accepted if I put this simple PR together? If not, I can keep a long-running fork, but would rather not, and can't see how else I can migrate to NTI without extending my build time + complexity significantly.

**Comment by dimvar** [comment]
Are you explicitly turning on JSC_NTI_NULLABLE_DEREFERENCE? It's off by default in NTI, just because it overwhelms all other warnings.

We will accept a PR for a compiler option to show warnings from both type systems. But I'd rather not re-enable the other passes currently off (global this, missing return). NTI should be sufficient for these errors.

Also, note that when you see warnings from both type systems, many warnings will be duplicated, which can become annoying quickly.

**Comment by supersteves** [comment]
I just want to be able to elect to opt in to double warnings.  So I can disable all NTI warnings via a guard in legacy code, but still catch OTI warnings. I have a zero warnings policy. I don't want to turn off NTI warnings in legacy code if OTI are universally silenced. But I have about 1000 NTI warnings I cannot afford to fix throughout the entire codebase. (That's not counting the nullable one.) Not sure if I'm explaining this well...

**Comment by dimvar** [comment]
I understand. What I'm saying is that, by default, when you enable NTI, the nullable-dereference warning is off. So, you are explicitly turning it on by using the diagnostic group newCheckTypesAllChecks, and I found that surprising.

**Comment by supersteves** [comment]
Yes, I did turn that on. Should I assume it is a no go area /not ready for general use?

As for the PR suggestion itself - I want in one compilation to run both NTI and OTI but use guards to reveal each for different parts of my source tree. As such this proposed opt-in option should remove all existing OTI suppressions, don't you think?

**Comment by dimvar** [comment]
The PR would add a new compiler option, and use it to guard this:
https://github.com/google/closure-compiler/blob/master/src/com/google/javascript/jscomp/Compiler.java#L349
and this:
https://github.com/google/closure-compiler/blob/master/src/com/google/javascript/jscomp/TypedScopeCreator.java#L216

So basically don't suppress any OTI warnings when that option is on. Then, when you invoke the compiler, you can control which warnings you want to see in which parts of your code, using path-suppressions. The command-line flag is called `--hide_warnings_for`, I don't recall at the moment how to do it from Java but it's possible.

**Comment by supersteves** [comment]
That's exactly what I mean. Those links correspond to the 1st and last (5th) code snippets from my original post. 

As for snippets 2,3,4 (global this, missing return, control flow): Presumably these are stable checks in NTI and can be left enabled in my legacy codebase, therefore don't need a carve-out. Do these checks emit errors with "NTI" somewhere in the DiagnosticType key, or do they share their DiagnosticTypes with OTI?

I'll need to look again at specifically which errors I am getting in bulk in my legacy code (other than the lion's share nullable one I shouldn't be enabling at all). I recall they all had "NTI" in the DiagnosticType key. Perhaps most are from newCheckTypesAllChecks... is this group to be avoided in general or in part, or is it sensible to use it in new projects?

I don't use command line in this project. Hide_warnings_for appears to hide *all* warnings in particular paths. I need to hide *specific* warnings in specific paths. So I use a custom WarningsGuard subclass which looks at the error source path and the type. 

(In fact I use a ".ccrc" JSON file of my own primitive invention to apply simple path based rules, rather like ".jshintrc" and ".eslintrc". This is all in my codebase rather than in a compiler fork.)

**Comment by dimvar** [comment]
> is this group to be avoided in general or in part, or is it sensible to use it in new projects?

The confilicting-shape warning has to do with struct/dict inheritance, and it's completely deleted from OTI, so we'll delete it from NTI too, we just haven't done it yet.

The nullable dereference finds true warnings, but they are so many that usually overwhelm all other warnings, so it's best to not even see them.

**Comment by supersteves** [comment]
I hadn't realised that newCheckTypesAllChecks was just those two checks - sorry. Now I've turned it off, I'm down to a much more manageable 1319 errors, 90% of which I'll suppress (with that PR) since they're in legacy code. Thanks for the advice.
