### ISSUE TITLE
Local variable cannot be used for @typedef

### ISSUE THREAD

**Issue by joelrich** [google/closure-compiler#1526]
If I compile the code below in the advanced mode, then it complains about the type annotation:
```
 WARNING - Bad type annotation. Unknown type MyType
     * @type {MyType}
```

```javascript
(function () {

    /**
     * @typedef {string}
     */
    var MyType;

    /**
     * @type {MyType}
     */
    var myString = "";

    window.myString = myString;

})();
```

The problem can be fixed by removing the function wrapper.

Version: 20151216.2.0

**Comment by dimvar** [comment]
It's a limitation of the old type checker, that typedefs should be defined in the global scope. It's unlikely that we'll fix this. It's fixed in the new type inference, see here if you want to try it out: https://github.com/google/closure-compiler/wiki/Using-NTI-(new-type-inference)

**Comment by joelrich** [comment]
Is this documented somewhere? It took me a while to figure out the problem. A simple error message would definitely be helpful for other people who run into this limitation.

I will give the new type inference a try. Thank you for the hint.

**Comment by dimvar** [comment]
> Is this documented somewhere?

Not that I know of. I'll add it to the docs.

> A simple error message would definitely be helpful for other people who run into this limitation.

Yes, but this will require a large internal cleanup of the bad typedef uses, and we probably won't have time to prioritize this soon.

**Comment by dimvar** [comment]
https://developers.google.com/closure/compiler/docs/js-for-compiler#tag-typedef

Since it's unlikely that someone will fix this, I'm closing the issue.
