### ISSUE TITLE
Extern for `Array.from` makes optional argument required and nullable

### ISSUE THREAD

**Issue by mgiuffrida** [google/closure-compiler#1529]
The extern added in #1377 incorrectly makes the 2nd param required & nullable, even though it is named `opt_mapFn` and [according to MDN is optional](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/from) but cannot be null.

```
 + * @param {string|!Array<T>|!IArrayLike<T>|!Iterable<T>} arrayLike
 + * @param {?function(this:S, string|T, number,
 + *     string|!Array<T>|!IArrayLike<T>|!Iterable<T>): R} opt_mapFn
 + * @param {S=} opt_this
```

The `?` should instead be a `=`. The function can be undefined but not null.

**Comment by MatrixFrog** [comment]
Aha good catch. This will be easier to fix internally since there is a chance it could break some projects.

**Comment by Dominator008** [comment]
Good catch, thanks!
