### ISSUE TITLE
NodeList not recognized as Array like class

### ISSUE THREAD

**Issue by blickly** [google/closure-compiler#153]
This issue was imported from Closure Compiler's previous home at http://closure-compiler.googlecode.com

The link to the original issue is:
https://code.google.com/p/closure-compiler/issues/detail?id=599

**Comment by Dominator008** [comment]
2c491045251bb4342aa0c8e14485b572bf8f2a85 declares NodeList to be IArrayLike<?>

**Comment by Dominator008** [comment]
Closed by https://github.com/google/closure-compiler/commit/9d52fed2c7da2a9e3807477c852c60b56edd2497
