### ISSUE TITLE
const for-in iterands should not be @const.

### ISSUE THREAD

**Issue by shicks** [google/closure-compiler#1532]
```js
for (const x in [1, 2, 3]) {
  console.log(x);
}
```

transpiles to

```js
for (/**@const */var x in[1, 2, 3]) {
  console.log(x);
}
```

But this seems questionable, since `x` shouldn't be `@const` since the `var` is function-scoped.

**Comment by shicks** [comment]
This causes problems in NTI.

**Comment by MatrixFrog** [comment]
I guess this would also be true for for/of, vanilla for loops, and any const inside a loop, right? Do you know if all those cases also cause problems with NTI?

**Comment by shicks** [comment]
Yes and no. They do indeed get rewritten as `/**@const*/var`, but NTI is okay with it because there's an immediate assignment (even if there may be a different assignment later in the same function-scope).

This could arguably be a bug in NTI, but doesn't seem to be harming anything.

**Comment by shicks** [comment]
To be more specific, all other types of loops (for-of and consts inside vanilla loops) transpile to

```
for (/* ... */) {
  /**@const */var something = whatever;
}
```

and NTI is fine with that (even though maybe it shouldn't be).

A const loop variable in a vanilla loop doesn't even transpile at all:
```
for (const i = 0; i < 10; i++) {}
```
generates an error at transpilation time, "Constant reassigned: i", which is correct.

So it's just the for-in case that needs changing somewhere.

**Comment by MatrixFrog** [comment]
Cool, thank you.
