### ISSUE TITLE
NTI confusing warning "Invalid type for parameter ... of function ..."

### ISSUE THREAD

**Issue by supersteves** [google/closure-compiler#1538]
The first NTI error of >100 in my "non-legacy" codebase was this:

``` javascript
/**
 * @param {string} suggestedName
 * @param {Array<string>} existingNames
 * @return {string}
 */
function getNewUniqueName(suggestedName, existingNames) {
    let suffix = -1,
        name;

    function getSuffixedName(originalName, numberSuffix) {
        return numberSuffix > 0 ? (originalName + " " + numberSuffix) : originalName;
    }


    function exists(newName, existing) {
        return existing.some(function(existingName) {
            return newName===existingName;
        });
    }

    do {
        suffix += 1;
        name = getSuffixedName(suggestedName, suffix);
    } while (exists(name, existingNames));

    return name;
}

```

```
input0:23: WARNING - Invalid type for parameter 2 of function exists.
expected : {some:function(bottom):bottom (loose)} (loose)
found    : Array<string>|null

    } while (exists(name, existingNames));
                          ^
```

([in debugger](https://closure-compiler-debugger.appspot.com/#input0%3D%252F**%250A%2520*%2520%2540param%2520%257Bstring%257D%2520suggestedName%250A%2520*%2520%2540param%2520%257BArray%253Cstring%253E%257D%2520existingNames%250A%2520*%2520%2540return%2520%257Bstring%257D%250A%2520*%252F%250Afunction%2520getNewUniqueName%28suggestedName%252C%2520existingNames%29%2520%257B%250A%2520%2520%2520%2520let%2520suffix%2520%253D%2520-1%252C%250A%2520%2520%2520%2520%2520%2520%2520%2520name%253B%250A%250A%2520%2520%2520%2520function%2520getSuffixedName%28originalName%252C%2520numberSuffix%29%2520%257B%250A%2520%2520%2520%2520%2520%2520%2520%2520return%2520numberSuffix%2520%253E%25200%2520%253F%2520%28originalName%2520%252B%2520%2522%2520%2522%2520%252B%2520numberSuffix%29%2520%253A%2520originalName%253B%250A%2520%2520%2520%2520%257D%250A%250A%2520%2520%2520%2520function%2520exists%28newName%252C%2520existing%29%2520%257B%250A%2520%2520%2520%2520%2520%2520%2520%2520return%2520existing.some%28function%28existingName%29%2520%257B%250A%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520return%2520newName%253D%253D%253DexistingName%253B%250A%2520%2520%2520%2520%2520%2520%2520%2520%257D%29%253B%250A%2520%2520%2520%2520%257D%250A%250A%2520%2520%2520%2520do%2520%257B%250A%2520%2520%2520%2520%2520%2520%2520%2520suffix%2520%252B%253D%25201%253B%250A%2520%2520%2520%2520%2520%2520%2520%2520name%2520%253D%2520getSuffixedName%28suggestedName%252C%2520suffix%29%253B%250A%2520%2520%2520%2520%257D%2520while%2520%28exists%28name%252C%2520existingNames%29%29%253B%250A%250A%2520%2520%2520%2520return%2520name%253B%250A%257D%250A%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES%3D1%26CHECK_TYPES_NEW_INFERENCE%3D1%26LANG_IN_IS_ES6%3D1%26MISSING_PROPERTIES%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1%26TRANSPILE%3D1))

This is pretty obscure and I don't have much hope of clearing through all my NTI errors if I get stuck this easily. After some experimentation it turns out the problem was the notorious and common nullable issue, this time with the `existingNames` param of the main function. Adding a `!` resolved it ([debugger](https://closure-compiler-debugger.appspot.com/#input0%3D%252F**%250A%2520*%2520%2540param%2520%257Bstring%257D%2520suggestedName%250A%2520*%2520%2540param%2520%257B!Array%253Cstring%253E%257D%2520existingNames%250A%2520*%2520%2540return%2520%257Bstring%257D%250A%2520*%252F%250Afunction%2520getNewUniqueName%28suggestedName%252C%2520existingNames%29%2520%257B%250A%2520%2520%2520%2520let%2520suffix%2520%253D%2520-1%252C%250A%2520%2520%2520%2520%2520%2520%2520%2520name%253B%250A%250A%2520%2520%2520%2520function%2520getSuffixedName%28originalName%252C%2520numberSuffix%29%2520%257B%250A%2520%2520%2520%2520%2520%2520%2520%2520return%2520numberSuffix%2520%253E%25200%2520%253F%2520%28originalName%2520%252B%2520%2522%2520%2522%2520%252B%2520numberSuffix%29%2520%253A%2520originalName%253B%250A%2520%2520%2520%2520%257D%250A%250A%2520%2520%2520%2520function%2520exists%28newName%252C%2520existing%29%2520%257B%250A%2520%2520%2520%2520%2520%2520%2520%2520return%2520existing.some%28function%28existingName%29%2520%257B%250A%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520return%2520newName%253D%253D%253DexistingName%253B%250A%2520%2520%2520%2520%2520%2520%2520%2520%257D%29%253B%250A%2520%2520%2520%2520%257D%250A%250A%2520%2520%2520%2520do%2520%257B%250A%2520%2520%2520%2520%2520%2520%2520%2520suffix%2520%252B%253D%25201%253B%250A%2520%2520%2520%2520%2520%2520%2520%2520name%2520%253D%2520getSuffixedName%28suggestedName%252C%2520suffix%29%253B%250A%2520%2520%2520%2520%257D%2520while%2520%28exists%28name%252C%2520existingNames%29%29%253B%250A%250A%2520%2520%2520%2520return%2520name%253B%250A%257D%250A%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES%3D1%26CHECK_TYPES_NEW_INFERENCE%3D1%26LANG_IN_IS_ES6%3D1%26MISSING_PROPERTIES%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1%26TRANSPILE%3D1)).

But I have no clue how to interpret the error message or the found/expected type ("bottom"?).

Also when looking at the debugger I'd like to see what types were inferred for every node in the AST. But it prints `?` (presumably because it doesn't know NTI yet).

I can understand that in this case, inferring the right types for the nested function might not work. It's the error message and the difficulty of understanding what NTI has actually inferred that I'm struggling with.

I tried assigning some properties to a var typed `{null}` to force the compiler to print its current inference about `existing.some` and `existingNames.some`. For the former it prints:
`function(this:IArrayLike<T>|null|string,function(this:S,T,number,Array<T>):?|null,S|undefined=):boolean`

Here, strangely it omits the `!` from `Array<T>` (I know I'm not using that arg in this example, but it is certainly confusing when the es3.js defines it as `!Array<T>`:
`@param {?function(this:S, T, number, !Array<T>): ?} callback`
Does this mean that when the compiler prints types, it explicitly writes `|null`, and if missing, it is assumed non-nullable? Unlike source annotations, where lack of `!` means implicitly nullable for object-based types.

For the latter `existingNames.some`, if I try to assign that to a var typed `{null}`, it breaks the inference, so I still have no clue as to the inferred type.

So this issue is a bunch of things; I'll split it once I have more clarification:
- Debugger needs to show NTI types for all nodes (is this possible?) or some alternative way of easily understanding what types are interpreted from (possibly wrong syntax) explicit type annotations, and inferred for all other nodes
- Lack of `!` on printed types in error messages (I think)
- Some explanation of "bottom" and "bottom (loose)" would be useful somewhere. Briefly in error messages, and also in wiki.

(Note - much of my codebase has been developed before we learnt about implicit nullability. We always assumed under OTI that `@type {MyClass}` meant non-nullable, and we've put "?" in cases where we wanted to mark it nullable. It would be useful to be able to disable implicit nullability, perhaps. But I doubt this would fly.)

**Comment by dimvar** [comment]
The error message should be improved to not refer to bottom; bottom is a type necessary for the type inference, but rarely useful to the end user.

    input0:24: WARNING - Invalid type for parameter 2 of function exists.
    expected : {some:function(?):?} (loose)
    found    : Array<string>|null
    
        } while (exists(name, existingNames));
                              ^

It would also be cool to have another kind of error message, where if there is a type mismatch, and removing null from the "found" type makes the mismatch disappear, then give a better error message.

**Comment by dimvar** [comment]
> It would also be cool to have another kind of error message, where if there is a type mismatch, and removing null from the "found" type makes the mismatch disappear, then give a better error message.

To be clear, OTI also doesn't do this, so you're not losing anything by moving to NTI.

**Comment by supersteves** [comment]
That would help, yes. Although often the type is more complex, with ```|null``` appearing in several places in either found or expected type expressions, presumably making it harder to figure out which nullable part is a mismatch.
I know OTI doesn't do this. In fact it doesn't report any error. So I'm in a false sense of security without NTI, I realise that.
