### ISSUE TITLE
Better documentation for @public and @export

### ISSUE THREAD

**Issue by Dominator008** [google/closure-compiler#1543]
@public is undocumented at [Annotating JavaScript for the Closure Compiler](https://developers.google.com/closure/compiler/docs/js-for-compiler).

Also, we should document that @export cannot be mixed with other visibility modifiers.

**Comment by blickly** [comment]
Looks like the current documentation is at https://github.com/google/closure-compiler/wiki/Annotating-JavaScript-for-the-Closure-Compiler, and @public is documented there
