### ISSUE TITLE
File order not maintained

### ISSUE THREAD

**Issue by bardware** [google/closure-compiler#1548]
I call the closure compiler like:

    java.exe -jar dev\jars\closure\compiler.jar --compilation_level WHITESPACE_ONLY --formatting PRETTY_PRINT --formatting PRINT_INPUT_DELIMITER --formatting SINGLE_QUOTES --js_output_file jQuery_a52d83c3.min.js --js jquery.js ui\core.js ui\widget.js ui\mouse.js ui\draggable.js ui\droppable.js ui\resizable.js ui\selectable.js ui\sortable.js ui\button.js ui\position.js

When I use the `compiler.jar` from github binary downloads `compiler-20151216.tar.gz` everything is fine. When I use `compiler-20160208.tar.gz` the file originial order is not maintained in the compressed file which breaks the code, as the js files have to be included in a specific order.
I tried the new parameter `--dependency_mode NONE` but it changed nothing. According to the docs should NONE be the default.

I'm on Windows 10, 64 bit JAVA 8 as provided by Oracle.

**Comment by Dominator008** [comment]
Thanks for the report. This should be fixed in #1549.

For now, the workaround is to specify multiple "--js" flags, like
`--js jquery.js --js ui\core.js --js ui\widget.js`, etc.
