### ISSUE TITLE
Linter complains about missing jsdoc on parameter-less ES6 class constructor

### ISSUE THREAD

**Issue by benvanik** [google/closure-compiler#1554]
Recently started getting lint warnings about missing docs on ES6 constructors that don't contain parameters. I can't imagine what the purpose of jsdoc on it would be if the class itself already has an annotation, so it'd be nice not to have either the extra noise of the unnecessary comments or the extra noise of the linter warnings.

Example:

```js
/**
 * Some stuff here.
 * @struct
 */
class MyClass {
  constructor() {}
}
```

Results in the following from `Linter_deploy.jar`:
```
WARNING: xxx.js:28: WARNING - Function must have JSDoc.
  constructor() {}
  ^
```

Workaround is to add `/** A constructor, obviously. */`, but that seems silly :)

**Comment by Dominator008** [comment]
Seems like this is the intended behavior as suggested by https://github.com/google/closure-compiler/commit/e5e391866d1f4aeba84e4a11a8dcb7b30405fe3d (https://github.com/google/closure-compiler/blob/e5e391866d1f4aeba84e4a11a8dcb7b30405fe3d/src/com/google/javascript/jscomp/lint/CheckJSDocStyle.java#L124-L135).

@MatrixFrog Can we relax this a little bit by making `constructor()` an exception?

**Comment by MatrixFrog** [comment]
Yes, that seems like a reasonable exception.
