### ISSUE TITLE
[RFC] Adding a custom pass for function entry/exit instrumentation

### ISSUE THREAD

**Issue by er91** [google/closure-compiler#1555]
Hey guys,

Recently at work we need to record arguments/retval for some functions. To do this, we manually add console.log() to every function we need to log (oh my...).

Therefore we are proposing to add an function annotation (maybe "@invocation"?) to the compiler, and a compiler pass to insert instrumentation code.

This can be done in two ways:

- Modify function body directly. The compiler translates this:
```js
/**
  * @invocation {entryFunc, exitFunc}
  *
  * @param {number} x
  * @return {number}
  */
var f = function(x) {
  return x + 1;
}
```
into this:
```js
var f = function(x) {
  entryFunc(arguments);

  var retExpr = x + 1;

  exitFunc(retExpr);
  return retExpr;
}
```
- Modify caller. The compiler translates this:
```js
var ret = f(x);
```
into this:
```js
entryFunc(x);
var ret = f(x);
exitFunc(ret);
```

This instrumentation can also be used to count how many times a function is called, how much time is spent on the function, etc.

Some open questions:
- Is this approach OK? If there's a simpler way to do this, please let me know :-) Otherwise, if we agree on this approach, I can contribute code for it.
- Can we add more instrument points, and make this a more general instrumentation framework?

Thanks for your time!

**Comment by Dominator008** [comment]
I'm not sure if https://github.com/google/closure-compiler/blob/master/src/com/google/javascript/jscomp/InstrumentFunctions.java does what you want?

**Comment by er91** [comment]
@Dominator008 Thanks for the pointer! That's exactly what we want :-)

One minor problem: report_call function does not carry arguments. Opening pull request [here](https://github.com/google/closure-compiler/pull/1581).
