### ISSUE TITLE
Type mismatch in array keys (string  vs number) in "for( a in b)" with advanced compilation

### ISSUE THREAD

**Issue by tdelmas** [google/closure-compiler#1556]
```js
/**
* @param {Array.<*>} l
*/
function f(l){
  for(var i in l ) {
    console.info( l[i] )
  }
}
```

Produce : 

> JSC_TYPE_MISMATCH: restricted index type
>found   : string
>required: number at line 8 character 20
>    console.info( l[i] )

Example :
https://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540compilation_level%2520ADVANCED_OPTIMIZATIONS%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250A%252F%252F%2520ADD%2520YOUR%2520CODE%2520HERE%250A%250A%252F**%250A*%2520%2540param%2520%257BArray.%253C*%253E%257D%2520l%250A*%252F%250Afunction%2520f(l)%257B%250A%2520%2520for(var%2520i%2520in%2520l%2520)%2520%257B%250A%2520%2520%2520%2520console.info(%2520l%255Bi%255D%2520)%250A%2520%2520%257D%250A%257D%250Afunction%2520hello(name)%2520%257B%250A%2520%2520f(%255B1%252C%2520%2522test%2522%252C%2520%257B%257D%255D)%253B%250A%2520%2520alert('Hello%252C%2520'%2520%252B%2520name)%253B%250A%257D%250Ahello('New%2520user')%253B%250A%250A

**Comment by Dominator008** [comment]
This is working as intended, also:
http://stackoverflow.com/questions/500504/why-is-using-for-in-with-array-iteration-such-a-bad-idea
