### ISSUE TITLE
NPE in Es6RewriteBlockScopedDeclaration

### ISSUE THREAD

**Issue by MatrixFrog** [google/closure-compiler#1557]
https://closure-compiler-debugger.appspot.com/#input0%3Dfor%2520(let%2520i%2520%253D%25200%253B%2520i%253C10%253B%2520i%252B%252B)%2520%257B%250A%2520%2520let%2520x%2520%253D%25201%252C%2520y%253B%250A%2520%2520const%2520f%2520%253D%2520()%2520%253D%253E%2520%257B%250A%2520%2520%2520%2520y%2520%253D%25202%253B%250A%2520%2520%2520%2520x%2520%253D%25203%253B%250A%2520%2520%257D%250A%257D%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES%3D1%26LANG_IN_IS_ES6%3D1%26MISSING_PROPERTIES%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1%26TRANSPILE%3D1

**Comment by MatrixFrog** [comment]
@Dominator008 want to take a look?

**Comment by MatrixFrog** [comment]
Notice that the crash goes away if we split the 'let' statement into two separate statements: `let x = 1; let y;` so it probably has something to do with the way we "normalize"

**Comment by Dominator008** [comment]
Thanks for the pointer @MatrixFrog!
