### ISSUE TITLE
NTI should handle Number.isInteger(), etc. better.

### ISSUE THREAD

**Issue by Dominator008** [google/closure-compiler#1563]
In https://github.com/google/closure-compiler/pull/1545, I made it so that NTI knows `value` is a `number` if `Number.isInteger(value)` is called. In retrospect, this wouldn't be necessary if the type system understood `Number.isInteger()` better.

In `externs/es6.js` we have:
```js
/**
 * @param {number} value
 * @return {boolean}
 * @nosideeffects
 */
Number.isInteger = function(value) {};
```

We should infer that `value` is still a `number` after the function call.

**Comment by dimvar** [comment]
Darn, I didn't realize that these are defined in the ES6 externs. I think we'll have to roll back #1545, sorry about that. NTI should be able to infer the right types by using these functions without any special handling. See:
http://closure-compiler-debugger.appspot.com/#input0%3Dfunction%2520f(arg)%2520%257B%250A%2520%2520if%2520(ns.isFinite(arg))%2520%257B%250A%2520%2520%2520%2520var%2520%252F**%2520string%2520*%252F%2520a%2520%253D%2520arg%253B%250A%2520%2520%2520%2520return%2520arg%253B%250A%2520%2520%257D%2520else%2520%257B%250A%2520%2520%2520%2520return%2520arg%253B%250A%2520%2520%257D%250A%257D%26input1%26conformanceConfig%26externs%3Dfunction%2520ns()%2520%257B%257D%250A%250A%252F**%250A%2520*%2520%2540param%2520%257Bnumber%257D%2520value%250A%2520*%2520%2540return%2520%257Bboolean%257D%250A%2520*%252F%250Ans.isFinite%2520%253D%2520function(value)%2520%257B%257D%253B%250A%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES_NEW_INFERENCE%3D1%26LANG_IN_IS_ES6%3D1%26MISSING_PROPERTIES%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1%26TRANSPILE%3D1

`nosideeffects` is not related in this case.

**Comment by Dominator008** [comment]
I haven't merged #1545 yet so it's fine.

I was thinking about `@nosideeffects` because if the type of `value` is a `@record`, and somehow `isFinite()` adds / removes property to it, we can't guarantee it's still the same type. But since `@record`s are `@struct` this should not happen.

**Comment by dimvar** [comment]
It's actually simpler than that. NTI doesn't currently track these kinds of side effects. So, for any call `f(x)`, if `x` has a declared type, it will continue to have that type after the call, regardless of what `f` does. The fact that NTI doesn't find it for `Number.isFinite` is a bug.

**Comment by Dominator008** [comment]
Fixed by https://github.com/google/closure-compiler/commit/f9317f38ca397b4313e88c442302c73a0ca81ae7.
