### ISSUE TITLE
* expressions are not callable at line 9 character 4

### ISSUE THREAD

**Issue by selkhateeb** [google/closure-compiler#1569]
I'm getting this error when compiling in VERBOSE level:
`JSC_NOT_FUNCTION_TYPE: * expressions are not callable at line 9 character 4`
I managed to reproduce it in  https://closure-compiler.appspot.com
Here is a quick link to the sample code:
[Sample code on closure-compiler.appspot.com](https://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540compilation_level%2520SIMPLE_OPTIMIZATIONS%250A%252F%252F%2520%2540warning_level%2520VERBOSE%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250A%252F%252F%2520ADD%2520YOUR%2520CODE%2520HERE%250A%252F**%250A%2520*%2520%2540param%2520name%250A%2520*%2520%2540return%2520%257B*%257D%250A%2520*%252F%250Avar%2520require%2520%253D%2520function(name)%2520%257B%257D%253B%250A%250Avar%2520e%2520%253D%2520require('e')%253B%250Aa%2520%253D%2520e()%253B%250A%250A%250A)

```js
// ==ClosureCompiler==
// @compilation_level SIMPLE_OPTIMIZATIONS
// @warning_level VERBOSE
// @output_file_name default.js
// ==/ClosureCompiler==

// ADD YOUR CODE HERE
/**
 * @param name
 * @return {*}
 */
var require = function(name) {};

var e = require('e');
a = e();
```

Any help is greatly appreciated.
Thanks

**Comment by Dominator008** [comment]
This is working as intended, `*` means `e` can be any possible type. Since the Compiler can't prove it's a function, it won't let you call it. The following code works:
```js
// ==ClosureCompiler==
// @compilation_level SIMPLE_OPTIMIZATIONS
// @warning_level VERBOSE
// @output_file_name default.js
// ==/ClosureCompiler==

// ADD YOUR CODE HERE
/**
 * @param name
 * @return {Function}
 */
var require = function(name) {};

var e = require('e');
a = e();
```

**Comment by selkhateeb** [comment]
`@return {Function}` works if I'm only returning a function. But this `require` function can return any other type also.
So what I which to define this type as `@return {Function|*}` which would produce the same warning since it basically means the same thing as *.
Is there a way to define the type so it can understand anything, including functions? Or is it better in this case to just cast `e`, `var e = /** @type {Function} */ (require('e'));`

**Comment by Dominator008** [comment]
If this `require` function can return any type, how are you certain that `e` is a function? You can always use type cast but then you might get `TypeError` at runtime.

**Comment by selkhateeb** [comment]
Agreed. This seems to be a fully untyped function that can return anything and it is impossible to know at compile time what its returning. It feels like the proper type for this function is the UNKNOWN type {?}.
Then use type casting to 'partially' check the rest of the app.

Thank you @Dominator008 for all the help.

**Comment by Dominator008** [comment]
Yes, uising `?` and type casting should work in your case. Is this trying to require a CommonJS module? Not sure if [this](https://github.com/google/closure-compiler/blob/master/contrib/nodejs/globals.js#L29-L33) is the `require` function you are talking about.

**Comment by selkhateeb** [comment]
Yes. This is exactly what I'm talking about. I'm trying to add closure compiler type checking in my project. I'm trying to understand the best way to integrate this where it can do full (or as much as possible) type checking without modifying/fixing third party source code. So, I'm using externs to do this.
