### ISSUE TITLE
Advanced optimizations produce incorrect code (eliminate too much)

### ISSUE THREAD

**Issue by josef-jelinek** [google/closure-compiler#1572]
The advanced optimizations remove the entire functionality of the string replacement in this simplified case producing an empty string as a result (or the original string in an older version).

Reproducible:
https://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540compilation_level%2520ADVANCED_OPTIMIZATIONS%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250A%252F%252F%2520ADD%2520YOUR%2520CODE%2520HERE%250Afunction%2520hello()%2520%257B%250A%2520%2520return%2520decorate('my%2520email%2520is%2520%257BEMAIL%257D'%252C%2520%257B'EMAIL'%253A%2520'abc%2540'%257D)%253B%250A%257D%250A%250Afunction%2520decorate(template%252C%2520replacements)%2520%257B%250A%2520%2520var%2520a%2520%253D%2520%255B%255D%252C%2520last%2520%253D%25200%253B%250A%2520%2520template.replace(%252F%255C%257B(%255BA-Z%255D%252B)%255C%257D%252Fg%252C%2520function%2520(s%252C%2520name%252C%2520i)%2520%257B%250A%2520%2520%2520%2520if%2520(i%2520%253E%2520last)%2520%257B%250A%2520%2520%2520%2520%2520%2520a.push(template.slice(last%252C%2520i))%253B%250A%2520%2520%2520%2520%257D%250A%2520%2520%2520%2520if%2520(replacements%255Bname%255D)%2520%257B%250A%2520%2520%2520%2520%2509a.push(replacements%255Bname%255D)%253B%250A%2520%2520%2509%257D%2520else%2520%257B%250A%2520%2520%2520%2520%2520%2520a.push(s)%253B%250A%2520%2520%2520%2520%257D%250A%2520%2520%2520%2520last%2520%253D%2520i%2520%252B%2520s.length%253B%250A%2520%2520%257D)%253B%250A%2520%2520return%2520a.join('')%253B%250A%257D%250A%250Aalert(hello())%253B

**Comment by MatrixFrog** [comment]
Looks like PeepholeOptimizations is doing something strange.

**Comment by MatrixFrog** [comment]
I think @concavelenz is on the verge of an "aha" moment.

**Comment by concavelenz** [comment]
oh, good catch, thanks for the report.

**Comment by Dominator008** [comment]
Closed by 6f24de22f41e0b4d8a7686313e2874fb4d228b5b
