### ISSUE TITLE
type of this in goog.events.listen's callback function

### ISSUE THREAD

**Issue by ghosttie** [google/closure-compiler#1582]
When I compile this code with --jscomp_error=reportUnknownTypes

```js
goog.events.listen(img, goog.events.EventType.CLICK,
    function(/** goog.events.BrowserEvent */ e) {
  filevision.i18n.state.setLocale(this.alt);
});
```

I get this error

```
filevision/index.js:130: ERROR - could not determine the type of this expression
                filevision.i18n.state.setLocale(this.alt);
                                                ^
```

I thought goog.events.listen defaulted to using the context of the event target, so shouldn't the compiler know that's what the type of "this" is?

If I specify img in the handler param the error goes away, which makes me think that if it knows what "this" is it'll know what "this.alt" is

I wanted to try and create a reproducer using http://closure-compiler-debugger.appspot.com/ but I couldn't see an option for reportUnknownTypes

**Comment by ghosttie** [comment]
I was able to create a reproducer for the fact that the compiler doesn't know the type of "this" in the callback:

http://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540compilation_level%2520SIMPLE_OPTIMIZATIONS%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250A%252F%252F%2520ADD%2520YOUR%2520CODE%2520HERE%250Avar%2520%252F**%2520!HTMLImageElement%2520*%252F%2520img%2520%253D%2520%252F**%2520%2540type%2520%257B!HTMLImageElement%257D%2520*%252F%2520(document.createElement('img'))%253B%250A%250Agoog.events.listen(img%252C%2520goog.events.EventType.CLICK%252C%2520function(%252F**%2520goog.events.BrowserEvent%2520*%252F%2520e)%2520%257B%250A%2520%2520%2520%2520var%2520%252F**%2520number%2520*%252F%2520x%2520%253D%2520this%253B%250A%257D)%253B

**Comment by concavelenz** [comment]
What would you like to see changed so that the compiler could infer the type of "this"?

**Comment by ghosttie** [comment]
I don't understand why it doesn't currently know the type - I'm passing it an object that it uses as the handler for the callback, so why would it not know the type of the handler?

**Comment by concavelenz** [comment]
How would you expect it to decide which this to use based on the function declaration?

**Comment by concavelenz** [comment]
How would you expect it to decide which this to use based on the function declaration?

**Comment by ghosttie** [comment]
Oh I see the problem - T is opt_handler not src.  I was confused that the runtime behavior differs from the compile-time behavior.

The only way I can think of it working is adding a template U, adding U to the type of src somehow (which I'm not sure is possible), changing the callback to use this:T|U and making the compiler able to collapse that down to just T if both are present.

**Comment by concavelenz** [comment]
If you look at goog.events.EventHandler.prototype.listen and goog.events.EventHandler.prototype.listenWithScope you can see how the problem was dealt with there.

This is really a hold over for when it was impossible for infer the type of "this" at all.

**Comment by ghosttie** [comment]
I see the benefit of splitting the function into a version with the handler and one without, but goog.events.EventHandler uses the SCOPE template as the handler on goog.events.EventHandler.prototype.listen so it doesn't interfere with the type of the src param and I don't know how you'd do that with the standalone goog.events.listen function
