### ISSUE TITLE
[NTI] Failed to infer instanceof in nested conditions.

### ISSUE THREAD

**Issue by Dominator008** [google/closure-compiler#1589]
```js
/** @constructor */
function Foo() {}

/** @constructor */
function Bar() {}

/**
 * @param {Foo|Bar} x
 * @param {Foo|Bar} y
 */
function f(x, y) {
  if ((x instanceof Foo) || (y instanceof Foo)) {
    var foo;
    if (x instanceof Foo) {
      foo = x;
    } else {
      foo = y;
    }
    var /** Foo */ foo2 = foo;
  }
}
```
gives
```
input0:19: WARNING - The right side in the assignment is not a subtype of the left side.
left side  : Foo|null
right side : Bar|Foo|null

    var /** Foo */ foo2 = foo;
                          ^

0 error(s), 1 warning(s), 100.0% typed
```
I guess the `y` was not inferred to be a `Foo` in the `else` branch.

http://closure-compiler-debugger.appspot.com/#input0%3D%252F**%2520%2540constructor%2520*%252F%250Afunction%2520Foo()%2520%257B%257D%250A%250A%252F**%2520%2540constructor%2520*%252F%250Afunction%2520Bar()%2520%257B%257D%250A%250A%252F**%250A%2520*%2520%2540param%2520%257BFoo%257CBar%257D%2520x%250A%2520*%2520%2540param%2520%257BFoo%257CBar%257D%2520y%250A%2520*%252F%250Afunction%2520f(x%252C%2520y)%2520%257B%250A%2520%2520if%2520((x%2520instanceof%2520Foo)%2520%257C%257C%2520(y%2520instanceof%2520Foo))%2520%257B%250A%2520%2520%2520%2520var%2520foo%253B%250A%2520%2520%2520%2520if%2520(x%2520instanceof%2520Foo)%2520%257B%250A%2520%2520%2520%2520%2520%2520foo%2520%253D%2520x%253B%250A%2520%2520%2520%2520%257D%2520else%2520%257B%250A%2520%2520%2520%2520%2520%2520foo%2520%253D%2520y%253B%250A%2520%2520%2520%2520%257D%250A%2520%2520%2520%2520var%2520%252F**%2520Foo%2520*%252F%2520foo2%2520%253D%2520foo%253B%250A%2520%2520%257D%250A%257D%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES_NEW_INFERENCE%3D1%26LANG_IN_IS_ES6%3D1%26MISSING_PROPERTIES%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1%26TRANSPILE%3D1

Real-world example: https://github.com/google/wicked-good-xpath/blob/master/src/binaryExpr.js#L125-L133

**Comment by dimvar** [comment]
> I guess the y was not inferred to be a Foo in the else branch.

That's not the issue. In the outer IF, NTI can't express that if x is not a Foo then y must be a Foo. It's out of scope for NTI to handle this.
