### ISSUE TITLE
v20160208 is not available nor on MavenCentral nor on bintray

### ISSUE THREAD

**Issue by xtracoder** [google/closure-compiler#1595]
According to https://github.com/google/closure-compiler/wiki/Releases version `v20160208` was released 20 days ago, but i do not see it deployed to neither of

http://mvnrepository.com/artifact/com.google.javascript/closure-compiler
https://bintray.com/bintray/jcenter/com.google.javascript%3Aclosure-compiler/view

Is there something wrong with deployment?

**Comment by Dominator008** [comment]
Duplicate of #1485.
