### ISSUE TITLE
goog.module files get stripped in WHITESPACE_ONLY mode

### ISSUE THREAD

**Issue by jart** [google/closure-compiler#1596]
I've noticed that when I compile with `--compilation_level=WHITESPACE_ONLY` and `--dependency_mode=LOOSE` that `goog.module` files will not be included in the output, unless I specify a `--entry_point=goog:namespace` flag for each module. This is not the behavior of files using `goog.provide`.

I don't think `WHITESPACE_ONLY` mode should strip any source files. I would like to see this behavior fixed because I'm using that flag to bundle sources together for a test runner. It would be an unreasonable burden to expect the user to explicitly state the entry point for all module tests.

**Comment by Dominator008** [comment]
@Chadkillingsworth.

**Comment by ChadKillingsworth** [comment]
Ordering dependencies is a primary purpose of `WHITESPACE_ONLY` - along with transpilation. It is frequently used to quickly create a js file to use during development. Ordering and pruning of dependencies is intended.

The `--dependency_mode` flag is doing what it is intended to do. You'll want to use the `--dependency_mod=NONE` option to keep all the files. However you will then be responsible for passing the files to the compiler in the correct order.

Alternatively, you can include one file that contains `goog.require` calls for each module but does NOT have a goog.provide call. This file will be kept as well as all the referenced modules.

We don't have a "re-order but keep all" option in the dependency management of the compiler.

**Comment by jart** [comment]
In that case, why does this behavior not happen with ES6 modules? ES6 appear to be outputted like the following:

```javascript
goog.require("module$closure$testing$test$arithmetic_es6module");
function testAdd$$module$closure$testing$test$arithmetic_es6module_test() {
  assertEquals(4, module$closure$testing$test$arithmetic_es6module.add(2, 2));
}
```

Speaking of which, shouldn't there be a `goog.scope` wrapper around that test function?

**Comment by ChadKillingsworth** [comment]
Because the ES6 module you referenced does not have an export and therefore there is no `goog.provide` statement.

With `--dependency_mode=LOOSE`, any file which does not have a `goog.provide` statement is assumed to be an entry point.

Why would the module need a `goog.scope` call? All of the symbols have been rewritten to be unique.

**Comment by jart** [comment]
OK that makes sense. Thank you for answering my questions Chad.

**Comment by ChadKillingsworth** [comment]
I'll freely admit that the documentation around this is somewhat lacking. I'm trying to improve it.
