### ISSUE TITLE
Warning about `this` in arrow function of object literal is useless.

### ISSUE THREAD

**Issue by DavidSouther** [google/closure-compiler#1598]
In [this code](https://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540compilation_level%2520SIMPLE_OPTIMIZATIONS%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250A%252F%252F%2520ADD%2520YOUR%2520CODE%2520HERE%250Aclass%2520Foo%2520%257B%250A%2520%2520constructor()%2520%257B%250A%2520%2520%2520%2520this.observable%2520%253D%2520new%2520RxJS.Subject()%253B%250A%2520%2520%2520%2520this.observable.subscribe(%257B%250A%2520%2520%2520%2520%2520%2520onNext(n)%2520%257B%2520console.log(n)%253B%2520%257D%252C%250A%2520%2520%2520%2520%2520%2520onErr%253A%2520(err)%2520%253D%253E%2520%257B%2520this.printError(err)%253B%2520%257D%250A%2520%2520%2520%2520%257D)%253B%250A%2520%2520%257D%250A%2520%2520%250A%2520%2520printError(err)%2520%257B%250A%2520%2520%2520%2520console.error(err)%253B%250A%2520%2520%257D%250A%257D) passing an object literal with a `this` reference, the compiler warns `JSC_THIS_REFERENCE_IN_ARROWFUNC_OF_OBJLIT`.

```javascript
class Foo {
  constructor() {
    this.observable = new RxJS.Subject();
    this.observable.subscribe({
      onNext(n) { console.log(n); },
      onError: (err) => { this.printError(err); }
    });
  }
  
  printError(err) {
    console.error(err);
  }
}
```

There is nothing ambiguous about what `this` inside the `onError` function should refer to - it can only refer to the instance of `Foo`. The warning is probably useless (so you could just remove [these lines](https://github.com/google/closure-compiler/blob/master/src/com/google/javascript/jscomp/Es6RewriteArrowFunction.java#L72-L74)), because JSCompiler captures the `Foo` in a closure. If a user expected `this` in an arrow function in an object literal to refer to the object literal, JSCompiler can't help them one way or the other. (The linter might be able to catch that, but even so, I'd argue that more people probably use this construct correctly than not. I make that claim based only on my own code that I have written :))

```javascript
var Foo = function() {
  var a = this;
  this.observable = new RxJS.Subject;
  this.observable.subscribe({onNext:function(a) {
    console.log(a);
  }, onErr:function(b) {
    a.printError(b);
  }});
};
Foo.prototype.printError = function(a) {
  console.error(a);
};
```

**Comment by blickly** [comment]
Yes, this is completely valid. I think we added this warning by mistake.

**Comment by MatrixFrog** [comment]
It was not a mistake, though it may have been over-eager. If code is well-typed, and users write `foo: () => { ... this ... }` in an object literal when they meant `foo() { ... this ... }` then the typechecker should generally help them realize it, unless they get unlucky and the object literal happens to have a method of the same name. So I'm okay with removing this warning.

**Comment by DavidSouther** [comment]
Thanks for the consideration and response!

> unless they get unlucky and the object literal happens to have a method of the same name.

Perhaps this should be the check, instead? When the object literal has `this.foo`, *and* `foo` on the object literal shadows `foo` in the instance?

**Comment by MatrixFrog** [comment]
Even in that case, how do we know which one the user meant? Is it more likely they'll use the arrow when they should have used method syntax or vice versa? I think typechecking might be about the best we can do here.

**Comment by DavidSouther** [comment]
Yeah, it's definitely not obvious. Possibly a lint warning when "no shadowed variables" is on? That would to me be a shadowed variable.
