### ISSUE TITLE
Externalize $jscomp polyfills

### ISSUE THREAD

**Issue by xtracoder** [google/closure-compiler#1603]
I tried using closure compiler for my use-case - programmatic on-the-fly transpilation of ES6 code to JS5 code.

In my environment I generate JS files which are loaded dynamically into target WEB page depending on various conditions - this means each file has to be transpiled individually and currently each of them contains plenty of polyfill code ($jscomp), 15K of polyfills per 5 lines of real code.

Is it possible to somehow configure compiler in the following way?

1. generate only polyfills into separate file, e.g. es6-gcc-polyfills.js
2. do not generate polyfills in target output, rather use them as externs from es6-gcc-polyfills.js

**Comment by shicks** [comment]
The CompilerOptions object contains a pair of flags for forceLibraryInjection and preventLibraryInjection (something along those lines - not sure exactly what the names are).  If these were exposed as command-line flags in the runner, then you could (a) force-inject "es6_runtime" on an otherwise empty input to get the runtime in a separate file, and then (b) prevent-inject "es6_runtime" (and maybe "base" as well) to prevent it from being added.  It should be a pretty easy pull-request to put together if you're up for it.

**Comment by xtracoder** [comment]
Just got chance to get back to this issue ...

- i've tried to use 'setPreventLibraryInjection()' - GCC fails with some INTERNAL COMPILER ERROR. Please check attached project for my test scenario

- another thing is - after removing of polyfills from the code, resulting JS5 code should stay debuggable in browser. I've tried removing polyfills manually (loaded them in browser from separate file) - but debugger shows blank code window - generated Source Map does not match manually altered file, of course.

[gcc_test.zip](https://github.com/google/closure-compiler/files/186794/gcc_test.zip)

**Comment by caridy** [comment]
any update on this?

**Comment by shicks** [comment]
We've significantly changed the way we handle polyfills.  Compiling an empty source with `--inject_library=es6_runtime` should bring in all polyfills, and does not require any source rewriting to use.  It's been a while, but if this does not meet your needs, please re-open.

**Comment by caridy** [comment]
@shicks if we want to compile a source, that does the remapping of the polyfills, and does not require the polyfills to be included in the output (because we have them in another file), will that work? what's the configuration option to remap without including the polyfills?

**Comment by mashedcode** [comment]
@caridy It might be possible to [split things into modules](http://stackoverflow.com/a/10401030/6572285) and have one module which provides `$jscomp` or which uses all the es6 polyfills on which the other modules depend.

**Comment by caridy** [comment]
that is an anti-pattern, modules should not import polyfills in any way, nor details of the transpiler.

**Comment by caridy** [comment]
@mashedcode to be more specific, if I have a `src/` folder with my ES Modules, I should be able to compile it with Closure or with babel, or with whatever transpiler I choose to use, and my source code should not change by any means. If it requires changes to accommodate the transpiler, what are you going to do when your runtime start supporting modules natively?

**Comment by caridy** [comment]
I have created a new issue to track down this particular request: https://github.com/google/closure-compiler/issues/1905

**Comment by mashedcode** [comment]
@caridy I didn't disagree - so you're probably right that the idea I had wasn't particularly great.
