### ISSUE TITLE
Ant task plugin fails with a NPE

### ISSUE THREAD

**Issue by kgston** [google/closure-compiler#1605]
The latest version is causing Ant to report a NPE when compiling from Ant. Code works fine on the previous version of the compiler.

**Comment by Dominator008** [comment]
Can you be more specific (eg. show a stack trace)? By "previous version of the library" did you mean Closure Compiler v20151216?

**Comment by kgston** [comment]
Will confirm again if it is related. Otherwise I will attempt to get a stack trace. Yes, v20151216.

**Comment by kgston** [comment]
Comfirm it is due to #1579. Thanks for the tip!
