### ISSUE TITLE
[enhancement] Maven plugin for compilation at build time

### ISSUE THREAD

**Issue by phax** [google/closure-compiler#1613]
Some time ago I started writing a Maven plugin that does the heavy lifting of JS compression at compile time. Since I'm using it for limited (and simple) scenarios only, I guess there is some room for improvement but nevertheless I think it might be valuable for others as well: https://github.com/phax/ph-jscompress-maven-plugin
If you want to integrate this into your ecosystem I'd be happy, or otherwise if you have some suggestions on how to improve it and make it more general usable, also fine :)
Keep up the good work!

**Comment by MatrixFrog** [comment]
My guess is we won't integrate this into our codebase, but it sounds like a great idea! You might want to mention it on the mailing list as well.

**Comment by phax** [comment]
Good point - thanks :)

**Comment by Dominator008** [comment]
Cool. Feel free to add a Wiki page like [this one](https://github.com/google/closure-compiler/wiki/Building-With-Ant).

**Comment by Dominator008** [comment]
Closing this but feel free to add a Wiki page.
