### ISSUE TITLE
enhancement: Reduce size of all variable, function and parameter names

### ISSUE THREAD

**Issue by odebroqueville** [google/closure-compiler#1617]
function parameters seem to have their names reduced to one character, but I haven't seen this applied to function and variable names.

The way I see this is that a js file would be traversed to identify all function and variable names, e.g. storing them as key values in a dictionary and the positions where they appear in the js file in an array as the associated values. Then you would replace all the instances of the first name with A, all the instances of the second name with B, etc. to lower case z. Then you would start adding a second single character of any of the following [A-Za-z0-9] to the first letter after having used up all the first single letters [A-Za-z].

This is rather simplistic, but I don't think it's being done and I think it's worth doing if we eliminate white spaces after all.

#enhancement

**Comment by Dominator008** [comment]
What compiler flags are you using?

**Comment by ChadKillingsworth** [comment]
`SIMPLE_OPTIMIZATIONS` does not rename symbols in the global scope. `ADVANCED_OPTIMIZATIONS` does. If you are using `SIMPLE_OPTIMIZATIONS`, try wrapping your code in an immediately invoked function expression and you should see renaming occur:

```js
(function() {
//your code here
})();
```
