### ISSUE TITLE
Rollforward PR #1266, #1476 and #1576.

### ISSUE THREAD

**Issue by ChadKillingsworth** [google/closure-compiler#1625]
#1476 and #1266 were rolled back with 641cf61b99280b8bb4b62ecce873e51208501fec

What needs to happen to re-apply those PRs?

**Comment by ChadKillingsworth** [comment]
Yes - I'll rebase all 3 to the top of the tree and resubmit.

**Comment by Dominator008** [comment]
All three PRs have been rolled forward \o/
