### ISSUE TITLE
some functions are rewrite "return local_var=something" instead of "return something"

### ISSUE THREAD

**Issue by blickly** [google/closure-compiler#163]
This issue was imported from Closure Compiler's previous home at http://closure-compiler.googlecode.com

The original discussion is archived at:
http://blickly.github.io/closure-compiler-issues/#1246

**Comment by Dominator008** [comment]
Input:
```js
function f1(){var r='a'; r+=f2();return r;}
```
Output under `SIMPLE_OPTIMIZATIONS`:
```js
function f1(){var a;return a="a"+f2()};
```

**Comment by realityforge** [comment]
@concavelenz This has been fixed and the issue can be closed.

Input:

```javascript
function f1(){var r='a'; r+=f2();return r;}
```

Output under `SIMPLE_OPTIMIZATIONS`:

```javascript
function f1(){return"a"+f2()};
```
See [example](https://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540compilation_level%2520SIMPLE_OPTIMIZATIONS%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250A%252F*%2520%2540export%2520*%252F%250Afunction%2520f1()%257Bvar%2520r%253D'a'%253B%2520r%252B%253Df2()%253Breturn%2520r%253B%257D%250A%250A)

**Comment by blickly** [comment]
Thanks for checking!
