### ISSUE TITLE
Type checking for HTMLFormControlsCollection.namedItem() doesn't know about RadioNodeList

### ISSUE THREAD

**Issue by jeffmin** [google/closure-compiler#1631]
Summary:
JSCompiler seems to think `HTMLFormElement.elements['name']` / `HTMLFormElement.elements.namedItem('name')` can only return `(HTMLElement|null)`.  But those methods can also return `RadioNodeList` when 'name' refers to a radio button group.

```
WARNING - actual parameter 1 of goog.array.forEach does not match formal parameter
found   : HTMLElement
required: (IArrayLike<?>|null|string)
      /** {RadioNodeList} */ form.elements['product'], function(element) {
```

**Comment by Dominator008** [comment]
It doesn't seem that `HTMLCollection.prototype.namedItem` can return any kind of `NodeList`: https://www.w3.org/TR/DOM-Level-2-HTML/html.html#ID-21069976.

**Comment by jeffmin** [comment]
Example: http://codepen.io/jeffmin/pen/RaROqE
Check the JS Console.  Shows as RadioNodeList for me on Chrome and FF.

**Comment by Dominator008** [comment]
@jeffmin Thanks. I see it in the HTML5 specs now: https://html.spec.whatwg.org/#the-htmlformcontrolscollection-interface. We are missing the externs for `HTMLFormControsCollection` and `RadioNodeList`.
