### ISSUE TITLE
NodeUtils methods are not publicly accessible. 

### ISSUE THREAD

**Issue by StefanLiebenberg** [google/closure-compiler#1632]
The NodeUtils class has many utility methods that could be very useful to custom compiler passes, but most of them are not marked public, restricting their use. Could you make these accessible?

**Comment by Dominator008** [comment]
I agree. Feel free to send a pull request for the methods that you would like to be public.

**Comment by StefanLiebenberg** [comment]
Pull Request: https://github.com/google/closure-compiler/pull/1634
