### ISSUE TITLE
Allow differentiation of prototypes in externs by the number of arguments 

### ISSUE THREAD

**Issue by tdelmas** [google/closure-compiler#1633]
A lot of externals tools used different function prototypes depending on the number of arguments.

The typical case is getter (returning the value) / setter (returning undefined or the element to allow chaining).

For example in the jQuery extern we have:

```js
/**
 * @param {(string|Object<string,*>)} arg1
 * @param {(string|number|boolean|function(number,string))=} arg2
 * @return {(string|!jQuery)}
 */
jQuery.prototype.attr = function(arg1, arg2) {};
```
Which force to cast the result in multiples situations.

A better way to declare it could be that way for example:

**The getter:**
```js
/**
 * @param {(string|Object<string,*>)} arg1
 * @return {(string)}
 */
jQuery.prototype.attr = function(arg1) {};
```

**The setter:**
```js
/**
 * @param {(string|Object<string,*>)} arg1
 * @param {(string|number|boolean|function(number,string))} arg2
 * @return {!jQuery)}
 */
jQuery.prototype.attr = function(arg1, arg2) {};
```

**Comment by Dominator008** [comment]
We need function overloads for this. See https://github.com/google/closure-compiler/issues/1616.

**Comment by tdelmas** [comment]
Yes, exactly that! I didn't saw it when I searched for issues about that.

I'll close this issue as it's a duplicate.
