### ISSUE TITLE
history var missing in externs ?

### ISSUE THREAD

**Issue by tdelmas** [google/closure-compiler#1635]
The History object is declared in https://github.com/google/closure-compiler/blob/master/externs/browser/html5.js#L2268
but not the history property of the window object in https://github.com/google/closure-compiler/blob/master/externs/browser/window.js .

**Comment by Dominator008** [comment]
It's here: https://github.com/google/closure-compiler/blob/master/externs/browser/ie_dom.js#L464.

Yeah our externs are kind of all over the place... :(

**Comment by ChadKillingsworth** [comment]
That's the constructor - the actual variable is: https://github.com/google/closure-compiler/blob/master/externs/browser/gecko_dom.js#L105-L110

**Comment by Dominator008** [comment]
@ChadKillingsworth Yeah thanks for the clarification.
