### ISSUE TITLE
Preserved "important" comments as indicated by "/*!"

### ISSUE THREAD

**Issue by blickly** [google/closure-compiler#164]
This issue was imported from Closure Compiler's previous home at http://closure-compiler.googlecode.com

The original discussion is archived at:
http://blickly.github.io/closure-compiler-issues/#275

**Comment by usmonster** [comment]
Suggestion: Also allow comments that start with `/**!` to be both preserved and treated as JSDoc.

Thoughts?

If the idea's any good, it would be nice to collaborate with other JS minifier folks out there on this. I imagine pure minifiers would be more open to supporting this than to implementing JSDoc comment parsing for `@license` or  `@preserve`.

(Note that this would be in addition to--not instead of--preserving `/*!` comments.)

**Comment by n0v1** [comment]
+1. Lots of libraries (that probably use or have used YUI Compressor) for minifying use /*! style comments to indicate that a comment should be preserved.

Examples: jQuery, Bootstrap, MooTools.

Would be great if Closure Compiler would also keep such comments.

**Comment by concavelenz** [comment]
@n0v1  No one has cared enough to actually put together a PR, want to try?

**Comment by usmonster** [comment]
At first glance, these files look like a good place to start:
https://github.com/google/closure-compiler/blob/master/src/com/google/javascript/jscomp/parsing/JsDocInfoParser.java
https://github.com/google/closure-compiler/blob/master/src/com/google/javascript/jscomp/parsing/JsDocTokenStream.java

Any other hints?

**Comment by Dominator008** [comment]
@usmonster https://github.com/google/closure-compiler/blob/master/src/com/google/javascript/jscomp/CodeGenerator.java has the logic for preserving type annotations.

**Comment by concavelenz** [comment]
https://github.com/google/closure-compiler/blob/master/src/com/google/javascript/jscomp/parsing/IRFactory.java for the logic that attaches comments to the AST, etc.

**Comment by n0v1** [comment]
Thank you for the hints. I'll have a look at it.

**Comment by silverhook** [comment]
I have not tested it yet, but it seems like this is fixed in https://github.com/google/closure-compiler/commit/81c1a44b21c047deaf376976a244060854611887

(friendly drive-by triaging)

**Comment by lauraharker** [comment]
Thanks @silverhook, I agree that we can close this after https://github.com/google/closure-compiler/commit/81c1a44b21c047deaf376976a244060854611887.
