### ISSUE TITLE
goog.i18n.DateTimeSymbolsType should declare the types of its properties

### ISSUE THREAD

**Issue by ghosttie** [google/closure-compiler#1654]
As discussed [here](https://groups.google.com/forum/#!searchin/closure-compiler-discuss/DateTimeSymbolsType/closure-compiler-discuss/BwFVlILLPJA/on0Zc9iBBgAJ), goog.i18n.DateTimeSymbolsType currently declares all of its types as unknown instead of

```js
/**
 * @typedef {{
 *   ERAS: !Array<string>,
 *   ERANAMES: !Array<string>,
 *   NARROWMONTHS: !Array<string>,
 *   STANDALONENARROWMONTHS: !Array<string>,
 *   MONTHS: !Array<string>,
 *   STANDALONEMONTHS: !Array<string>,
 *   SHORTMONTHS: !Array<string>,
 *   STANDALONESHORTMONTHS: !Array<string>,
 *   WEEKDAYS: !Array<string>,
 *   STANDALONEWEEKDAYS: !Array<string>,
 *   SHORTWEEKDAYS: !Array<string>,
 *   STANDALONESHORTWEEKDAYS: !Array<string>,
 *   NARROWWEEKDAYS: !Array<string>,
 *   STANDALONENARROWWEEKDAYS: !Array<string>,
 *   SHORTQUARTERS: !Array<string>,
 *   QUARTERS: !Array<string>,
 *   AMPMS: !Array<string>,
 *   DATEFORMATS: !Array<string>,
 *   TIMEFORMATS: !Array<string>,
 *   DATETIMEFORMATS: !Array<string>,
 *   FIRSTDAYOFWEEK: number,
 *   WEEKENDRANGE: !Array<number>,
 *   FIRSTWEEKCUTOFFDAY: number
 * }}
 */
```

Apparently this file is generated by a Python script

**Comment by MatrixFrog** [comment]
As far as I can tell, that part of the file is actually maintained manually. In any case this should be filed under closure-library.

**Comment by Dominator008** [comment]
Could you file it against closure-library instead? Thanks.

**Comment by dimvar** [comment]
Yep, it is manually generated. DateTimeSymbolsType used to be unspecified and I recently fixed it to at least provide the names of the properties at commit https://github.com/google/closure-library/commit/ea5a80b3b48b25f56ef7572894dd8e64a355bb3f. The reason I didn't provide the full types is that it required cleaning up projects that use Closure internally. I suspect it's not high priority either for the library team to clean those up.

**Comment by concavelenz** [comment]
I changes are pretty minor, I have a change pending but it needs to be farmed out, it will likely be a week or so
