### ISSUE TITLE
inferred fields on a derived class are not merged back with base class

### ISSUE THREAD

**Issue by rkirov** [google/closure-compiler#1655]
Consider the following code:

```javascript
/** @constructor */
ns.A = function() {
  /** @type {number} */
  this.a;
}

/**
 * @constructor
 * @extends {ns.A}
 */
ns.B = function() {};
```

When using JS compiler APIs to get fields of B (using `getTypeOfThis().getOwnPropertyNames()`), `a` is not returned. This makes sense, `a` is not *own* property, it is inherited from A.

now add the following method anywhere in the compilation unit:
```javascript
/**
 * @param {ns.B} b
 */
ns.messesWithB = function(b) {
  b.a = 0;
}
```

Now `a` becomes an *own* property of `B`, and it is returned as part of `getOwnPropertyNames`.

Is my understanding of `getOwnPropertyNames` wrong, or this is a bug?

Note: I added `goog.inherits` and `A.call(this)`, and they don't seem to change the observed behavior.

**Comment by dimvar** [comment]
I guess that if you make ns.B a `@struct`, then you will get what you expect.

Without struct, instances can have properties added after construction. So, during type checking, the compiler sees a property `a` added to some `ns.B`, and assumes that any `ns.B` can have that property.
