### ISSUE TITLE
Function inlining reuse var name

### ISSUE THREAD

**Issue by tdelmas** [google/closure-compiler#1656]
When the compiler inlines a function, sometimes a var name is (wrongly?) reused.
`var d` appears twice in that piece of code from example: 
```js
var d = a;
if (d && void 0 !== g) if (a = d) {
  var d = a.results,
```
I'm afraid that the behaviour introduce bugs. (and yes, the second line generated is strange, but, not incorrect)

Full compiled code:
https://searchcode.tdelmas.ovh/searchcode.js
Source code: 
https://github.com/tdelmas/searchcode_regexpr/blob/master/static/searchcode.js
Closure compiler version: 
v20160208 (the current HEAD version has the problem too)

**Comment by Dominator008** [comment]
I think the compiler tries to reuse a variable name when it's safe to do so. I'm curious why it did not change the the second var declaration into an assignment. @concavelenz

**Comment by dimvar** [comment]
There isn't enough information here. Which function was inlined into which one? What are the original variable names? It isn't obvious to figure out by looking at the uncompiled code.

**Comment by Dominator008** [comment]
@dimvar My guess: https://github.com/tdelmas/searchcode_regexpr/blob/master/static/searchcode.js#L165-L167 is the call site, and
https://github.com/tdelmas/searchcode_regexpr/blob/master/static/searchcode.js#L131-L140 is the function inlined.

**Comment by dimvar** [comment]
@tdelmas I think that the output you posted has been transformed by more passes than just function inlining (eg, the assignment inside the IF condition is probably from another pass). You should use the flag `--print_source_after_each_pass` and look at the code before and after inlining, to see if it makes sense. And then report back here.

**Comment by tdelmas** [comment]
Sure, I'll do it ASAP ( probably tomorrow ). Thanks.
Le 15 mars 2016 00:10, "Dimitris Vardoulakis" <notifications@github.com> a
écrit :

**Comment by concavelenz** [comment]
Whether "d" can be reused depends on whether the values is used afterwards. We would need to see the code to the end of the scope.

**Comment by tdelmas** [comment]
With the compiler v20160208 the command fail:
>java -jar ../compiler.jar --flagfile closure.flag --js
./static/searchcode.js --print_source_after_each_pass
"--print_source_after_each_pass" is not a valid option
How to pass it properly?

Tom

**Comment by Dominator008** [comment]
@tdelmas `--print_source_after_each_pass` is recently added so it's not part of the v20160208 release. Could you try it on HEAD instead?

**Comment by tdelmas** [comment]
The gist of --print_source_after_each_pass
https://gist.github.com/tdelmas/ae26215db85ea6aea048
In the second line of the generated code: 

> var c=a;if(c&&void 0!==g)if(a=c){var c=a.results

But in the send of the "if" the value of "c" is replace:

> c = a} else c = a;

So in that case no bug are introduce but be behaviour of the compiler is really odd.


A gist with the final code and questions about strange code generated:
https://gist.github.com/tdelmas/facfb04af233e814efe7

**Comment by concavelenz** [comment]
line 21: the compiler is being conservative.  JSON.parse has side-effects and g isn't defined in that scope (g may change).

line 75: f and m are set to void by the function inliner as the values are set/used inside a loop.

Generally, the code would look more like you would expect if the flow sensitive variable inlining ran in global scope

Generally, it doesn't sound like there is any bugs here just optimization opportunities.
