### ISSUE TITLE
Return value of super() calls not used for `this`

### ISSUE THREAD

**Issue by justinfagnani** [google/closure-compiler#1669]
If a constructor returns a value other than this, then in subclasses super() calls to that constructor should use the result as this in the subclass constructor.

This is specified in 12.3.5.1, step 10 of SuperCall: http://www.ecma-international.org/ecma-262/6.0/index.html#sec-super-keyword

Getting this behavior correct is going to be very important for supporting Custom Elements, which takes advantage of this to initialize browser-allocated elements with user-written constructors. See https://w3c.github.io/webcomponents/spec/custom/#htmlelement-constructor

Note, Babel 6 implements this correctly.

The folowing code should not fail the assertion, and doesn't in native ES2015:

``` javascript
class Foo {
  constructor() {
    return {
      x: 1,
    };
  }
}

class Bar extends Foo {

  constructor() {
    super();
    this.y = 2;
  }
}

let o = new Bar();
console.assert(o.x === 1 && y === 2);
```

The compiled version does fail the assertion:

``` javascript
// Input 0
var Foo = function() {
  return {x:1};
};
var Bar = function() {
  Foo.call(this);
  this.y = 2;
};
$jscomp.inherits(Bar, Foo);
var o = new Bar;
console.assert(o.x === 1 && o.y === 2);
```

The output for Bar should be:

``` javascript
var Bar = function() {
  var _this = Foo.call(this);
  _this.y = 2;
  return _this;
};
```

**Comment by concavelenz** [comment]
Thanks for the report!

**Comment by MatrixFrog** [comment]
I started working on this today by the way. I wonder if we should have an "in progress" label to distinguish "assigned to me because I intend to do it eventually" and "assigned to me because I'm working on it"

**Comment by concavelenz** [comment]
"assigned" vs "accepted"?

**Comment by MatrixFrog** [comment]
As it's called internally, yes, but Github doesn't have that distinction built in afaik.

**Comment by justinfagnani** [comment]
You can edit labels :) I use quite a different set from the default labels, it's more of a key: value system like old Google Code.

**Comment by MatrixFrog** [comment]
Forgot to update here. I'm not actively working on this right now. It's tricky to do in a way that the typechecker is happy with. We might need to do this after the typechecker understands ES6 classes natively.

**Comment by justinfagnani** [comment]
Thanks for the update Tyler. Any ETA on ES6 class understanding?

**Comment by dimvar** [comment]
No ETA. We won't be working on this in Q2.

**Comment by ChadKillingsworth** [comment]
@MatrixFrog Do you have any WIP code? I might take a look. This will be very important for Polymer going forward.

Hopefully we can find a way to handle this that does not require updating the type checker.

**Comment by concavelenz** [comment]
The type checker understands constructors with @return, we would we need native class support in the type checker?

**Comment by ChadKillingsworth** [comment]
This is why the change is needed: https://github.com/w3c/webcomponents/blob/gh-pages/proposals/Constructor-Dmitry.md

**Comment by MatrixFrog** [comment]
https://github.com/MatrixFrog/closure-compiler/commit/b7948b8541f3e1fe52cfc8f52ac50f941a162ef6

**Comment by ChadKillingsworth** [comment]
I finally found a good example of what this is needed for: https://gist.github.com/domenic/c1566e755c9e14613aa1

**Comment by justinfagnani** [comment]
Also see the custom elements polyfill I'm working on, which has an implementation of that technique: https://github.com/webcomponents/webcomponentsjs/pull/514/files#diff-41d0341d0c70774ca250552105b7a773R283

I just added a test on Closure output, which actually fails before running the constructor when trying to assign to `prototype.constructor`: https://github.com/webcomponents/webcomponentsjs/pull/514/files#diff-c657cdb21a04847ca249e1320e13d9c9R28

**Comment by justinfagnani** [comment]
Any update on this one? We're about to need to start compiling some code that relies on returning interesting things from the constructor. Thanks!

**Comment by MatrixFrog** [comment]
Not since the WIP CL I posted above (https://github.com/MatrixFrog/closure-compiler/commit/b7948b8541f3e1fe52cfc8f52ac50f941a162ef6) which AFAIK no one has attempted to pick up.

**Comment by MatrixFrog** [comment]
Work in progress at https://github.com/google/closure-compiler/pull/2024

**Comment by brad4d** [comment]
Status update:
Summary:
-   Allowing super() to change `this` in the most straightforward way by replacing all uses of `this` in the constructor with `$jscomp$super$this` confuses both type checkers by hiding class fields from them.
-   Doing it in other ways
    -   generates a lot more code
    -   requires calling the constructor a second time
    -   requires putting a temporary property on `this` to recognize the recursion, which also confuses type checking.
-   The chosen solution is to move transpilation of super() constructor calls to after type checking.
    -   We need to eventually move all type checking to before transpilation to support native ES6 output.
    -   We won't move transpilation of super.method() yet, because that is currently working,
        and it's actually a bit harder to typecheck in mostly-es5 code.

Order of changes to be made is:
-   @dimvar has a change nearly ready to submit to make NTI understand both super() and super.method(). I expect it will get submitted tomorrow.
-   I have a change built on that one that moves super() constructor transpilation to after type checking & makes OTI understand it.
-   Following that, I'll submit a change to actually implement the super()-changes-this feature.

One caveat, inheritance from native Error types won't work correctly, but then that doesn't work correctly now either. It's really [ugly](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error#Custom_Error_Types) to handle that in ES5 code.

ETA next Wednesday

**Comment by brad4d** [comment]
Just sent my change to move transpilation of super() constructor calls for review.

**Comment by justinfagnani** [comment]
Thanks for the updates Bradford, this is great news! :)

**Comment by brad4d** [comment]
@dimvar's NTI fix to make it understand `super` is in.
I had to do a bit of rework on my change to make old type inference understand `super()` constructor calls and move `super()` transpilation after type checking, but I believe it's ready for submission now. Review continues.

**Comment by brad4d** [comment]
My change to move transpilation of `super()` constructor calls will be in the next push to github.
Change to fix this issue will go to review today.

**Comment by brad4d** [comment]
Two changes are in review.
-   One removes `super()` calls in interfaces. 
-   One fixes #2098

Fix for this bug will depend on those.

**Comment by brad4d** [comment]
It looks like we also need to fix #2102 on the way to fixing this issue.
If we fix this without first making extension of `Error` work,
we're going to break code in the wild.

**Comment by brad4d** [comment]
I'm currently running tests for a change that fixes this.
If that goes OK, I expect it to be in tomorrow's push to githubl.

**Comment by brad4d** [comment]
The change to fix this was submitted to Google's internal repo last night.

**Comment by brad4d** [comment]
Drat! It caused failures and I had to roll it back.
Investigating...
