### ISSUE TITLE
Repeatable json_streams compilation 

### ISSUE THREAD

**Issue by markuskobler** [google/closure-compiler#1671]
I have been looking at the new `--json_streams` feature and wondering what the least intrusive way of adding support for repeatable builds from the same JVM process.

A cursory check of `CommandLineRunner` and `AbstractCommandLineRunner` looked like it might be a relatively straightforward addition but was keen to get people thoughts before I submit any patch.

**Comment by ChadKillingsworth** [comment]
I'm not sure how the `--json_streams` flag would influence this differently from the rest of the flags. It's technically possible though. You'd have to somehow ensure exit codes were handled since the process wouldn't technically exit.

**Comment by concavelenz** [comment]
Do you just mean running multiple compilation jobs?  Usually, I just recommend "nailgun" or "drip" or one of the friends.  It is possible to do better than just keeping the code hot in the JVM but it helps.

**Comment by ChadKillingsworth** [comment]
Closing this as I don't see any action items for the compiler.
