### ISSUE TITLE
Collections missing Iterable interface

### ISSUE THREAD

**Issue by bfricka** [google/closure-compiler#1672]
`HTMLCollection` and `NodeList` implement the Iterable interface (they define `Symbol.iterator` method on the prototype), but the compiler complains that they do not. This means that `for...of` and destructuring should work, but the compiler does not recognize this.

Since these appear to be defined internally (as opposed to in an extern), I'm not entirely sure where I would go to make a PR.

**Comment by MatrixFrog** [comment]
HTMLCollection and NodeList are defined in the externs: 

https://github.com/google/closure-compiler/blob/17904429dfc1e2506dfb0e6452b27a603ed92b57/externs/browser/w3c_dom2.js#L34

https://github.com/google/closure-compiler/blob/17904429dfc1e2506dfb0e6452b27a603ed92b57/externs/browser/w3c_dom1.js#L441

Another thing that should be Iterable is Array. I tried making that work recently but ran into some trouble for various reasons. For one it makes es3.js awkwardly depend on es6.js

**Comment by ChadKillingsworth** [comment]
@MatrixFrog We need to support later extern definitions overwriting early ones. While you can `@suppress {duplicate}`, I believe that still uses the first definition.

This is described by #1214

**Comment by bfricka** [comment]
That is indeed awkward. Forgive my ignorance, but is there a concept of inheritance with externs? So you could give later versions the proper `@implements` and define e.g. `Array.prototype[Symbol.iterator] = function() {};` and `Array.prototype.values`?

**Comment by MatrixFrog** [comment]
That would be another way to do it -- to allow you to kind of "retroactively" add an `@implements` to a class, that you didn't add when you defined it.

**Comment by bfricka** [comment]
Being able to override might be very nice, since it allows local overriding of compiler externs. For example, the current release has a bug in `Array.from` which was fixed weeks ago, but that fix won't be realized until the next release. Right now we just ignore that warning, (or you could pass `goog.functions.identity` as a second argument, but that's a bit icky.

**Comment by MatrixFrog** [comment]
This was fixed for HTMLCollection in 0d860120c342715ce8afc7ae7b97cb7d50c72f5a and for NodeList in 29ec598e4424db1d3466bb3c5726f1d14db5c6d0

**Comment by MatrixFrog** [comment]
And `Iterable` was moved into es3.js even though it wasn't defined until ES 2015, so if you find anything else that is lacking an `@implements {Iterable}` you should be able to just add it.
