### ISSUE TITLE
Object literal getters/setters

### ISSUE THREAD

**Issue by NekR** [google/closure-compiler#1677]
This code

```js
function Test() {}

Test.prototype = {
  get test() {
    
  },

  set test(val) {
    
  }
};
```

Produces this errors on https://closure-compiler.appspot.com/
```
Number of errors: 2

JSC_CANNOT_CONVERT: This code cannot be converted from ES6. ES5 getters/setters (consider using --language_out=ES5) at line 4 character 6
  get test() {
      ^
JSC_CANNOT_CONVERT: This code cannot be converted from ES6. ES5 getters/setters (consider using --language_out=ES5) at line 8 character 6
  set test(val) {
      ^
```

This is part of ES5 and following specs (see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/get) and is implemented by engines for a while.

So why it produces errors?

**Comment by Dominator008** [comment]
As the compiler itself, the web service defaults language_out to ES3, try adding:
```js
// @language_out ecmascript5
```
To the beginning of the file.

**Comment by StephanHoyer** [comment]
I think it's
```
// @language_out ES5
```

**Comment by aadityataparia** [comment]
It is ->
`// @language ECMASCRIPT5`
