### ISSUE TITLE
Unknown type warnings when using templates

### ISSUE THREAD

**Issue by blickly** [google/closure-compiler#168]
This issue was imported from Closure Compiler's previous home at http://closure-compiler.googlecode.com

The original discussion is archived at:
http://blickly.github.io/closure-compiler-issues/#1224

**Comment by supersteves** [comment]
Appears to be a dup of https://github.com/google/closure-compiler/issues/490

**Comment by Dominator008** [comment]
Duplicate of #490, which is fixed in NTI.
