### ISSUE TITLE
Consider not defaulting to "compiled.js" when js_output_file is null / empty

### ISSUE THREAD

**Issue by Dominator008** [google/closure-compiler#1684]
This behavior is undocumented and at least confusing.
https://github.com/google/closure-compiler/blob/master/src/com/google/javascript/jscomp/AbstractCommandLineRunner.java#L1258-L1260

Specifically, it causes problems when the compiler is called multiple times in a gulp run to minify different files. The output "compiled.js" gets overwritten every single time.

I feel that when the input is a single file, we should just reuse its path when `js_output_file` is not specified. When passed in multiple files, we should still pick a unique name based on one of the inputs instead of "compiled.js". This could be the name of the entry point if provided.

**Comment by ChadKillingsworth** [comment]
Other gulp plugins use the name of the first input file.

**Comment by Dominator008** [comment]
@ChadKillingsworth Do you think this would be easier to fix in the gulp plugin than in the compiler itself? I mean, we should fix the behavior in `AbstractCommandLineRunner`, but if we can get the gulp plugin to ignore the "compiled.js" path then it also works.

**Comment by ChadKillingsworth** [comment]
@Dominator008 I've thought about this. I'd rather not use a magic string to solve this on the plugin side. I think we should just use the web service solution and randomly generate a suffix to the filename. This is only for the case where the user doesn't provide an output filename.

What's the best way to approach this that will work with GWT?

**Comment by Dominator008** [comment]
@ChadKillingsworth It is not always easy / preferable to provide an output filename. For example, if I use [usemin](https://www.npmjs.com/package/gulp-usemin), `gulp-uglify` just reuses the input filename while Closure Compiler will output a magic `compiled.js` and keep overwriting that :(

**Comment by ChadKillingsworth** [comment]
I'm trying to avoid the case where the user specifies an output file name of `compiled.js`. In that case we would detect it as the default file name and do something different.

What if the compiler used something like `compiled-14d79437b368.js` where the suffix was randomly generated?

**Comment by Dominator008** [comment]
@ChadKillingsworth So I think the best solution is to just default to the name of the first file?

**Comment by ChadKillingsworth** [comment]
This hasn't really come up since. I'm closing this.
