### ISSUE TITLE
Private property prop_ should end with '_'

### ISSUE THREAD

**Issue by gumm** [google/closure-compiler#1691]
With compiler version v20160315 private properties, even though it does end with an underscore, erroneously generates a warning that it should end with an underscore.

```
/root/to/Workspace/project/blah.js:30: WARNING - Private property blee_ should end with '_'
  some.prototype.blee_ = function() {
  ^
```

**Comment by Dominator008** [comment]
Are you using a custom coding convention?

**Comment by gumm** [comment]
Nope - no custom conventions. We follow these: [https://google.github.io/styleguide/javascriptguide.xml#Visibility__private_and_protected_fields_](https://google.github.io/styleguide/javascriptguide.xml#Visibility__private_and_protected_fields_)

**Comment by Dominator008** [comment]
Ok this is the problem: https://github.com/google/closure-compiler/blob/master/src/com/google/javascript/jscomp/ClosureCodingConvention.java#L392-L395

`isPrivate()` in the default coding convention `ClosureCodingConvention` returns false for any property. Unfortunately, the property was annotated with `@private` so the compiler emitted a confusing warning.

AFAIK most internal Google projects use `GoogleCodingConvention`, which will recognize this as a private property: https://github.com/google/closure-compiler/blob/master/src/com/google/javascript/jscomp/GoogleCodingConvention.java#L182-L191. Unfortunately `GoogleCodingConvention` is not available via the command line.

If you happen to be using the Java API, then you can set the coding convention: https://github.com/google/closure-compiler/blob/master/src/com/google/javascript/jscomp/CompilerOptions.java#L1546-L1548, but I guess you are not using the API.

I think we should fix this check.

**Comment by MatrixFrog** [comment]
I recommend `--jscomp_off=lintChecks` for now. I'll make sure we explicitly enable the google coding convention in the Linter binary.
