### ISSUE TITLE
dependency_mode option not visible

### ISSUE THREAD

**Issue by fredj** [google/closure-compiler#1692]
The `--dependency_mode` option is not displayed when running `java -jar compiler.jar --help`.

See https://github.com/google/closure-compiler/blob/v20160315/src/com/google/javascript/jscomp/CommandLineRunner.java#L615

**Comment by ChadKillingsworth** [comment]
Yeah - I didn't find out about that change until much later as well. Caught me off guard. The flag is still there, just not documented from the command line. I'm going to audit those flags and make sure the appropriate ones are still documented.

**Comment by fredj** [comment]
And the `--define` option is also not visible.

**Comment by ChadKillingsworth** [comment]
There are a lot of flags not visible. I'm going to audit them all.

**Comment by fredj** [comment]
thanks

**Comment by ChadKillingsworth** [comment]
Closed by #1695
