### ISSUE TITLE
The js_module_root flag doesn't work as documented

### ISSUE THREAD

**Issue by hearnden** [google/closure-compiler#1697]
Currently, the ES6 module loader interprets import paths that start with `/` as absolute filesystem paths.  e.g., you can have:
```js
import { X } from '/home/hearnden/projects/myproj/app/x';
```

Surely it would be more useful, and probably closer in line with https://html.spec.whatwg.org/multipage/webappapis.html#integration-with-the-javascript-module-system, for the path to be interpreted with respect to (one of) the module root URIs.

e.g., with a module root URI of `/home/hearnden/projects/myproj/app`, you could have:
```js
import { X } from '/x';
```
which would do the right thing, regardless of the path of the importing script.

This appears trivial to make happen:
```diff
diff --git a/src/com/google/javascript/jscomp/ES6ModuleLoader.java b/src/com/google/javascript/jscomp/ES6ModuleLoader.java
index a36ff64..83e423a 100644
--- a/src/com/google/javascript/jscomp/ES6ModuleLoader.java
+++ b/src/com/google/javascript/jscomp/ES6ModuleLoader.java
@@ -102,9 +102,11 @@ public final class ES6ModuleLoader {
     URI uri = createUri(name);
     if (isRelativeIdentifier(name)) {
       URI referrerUri = normalizeInputAddress(referrer);
-      uri = referrerUri.resolve(uri);
+      uri = normalizeAddress(referrerUri.resolve(uri));
+    } else if (isAbsoluteIdentifier(name)) {
+      // Strip leading slash, to match the normalized entries in moduleUris.
+      uri = createUri(name.substring(1));
     }
-    URI normalized = normalizeAddress(uri);
     if (moduleUris.contains(normalized)) {
       return normalized;
     }
```

However, that change isn't backwards compatible, because it would break the use of absolute filesystem paths.  But surely that would be a good thing?

**Comment by ChadKillingsworth** [comment]
The compiler is actually pretty agnostic when it comes to where the absolute root actually is. It's based off the file path provided to it by the source flags `--js=/path/to/foo.js`. For instance, the grunt/gulp plugins anchor the root to the current working directory of the compiler.

Also, make sure you look at the `--js_module_root` flag.

The change you suggest above would break active projects.

I'm closing this issue for now. If the `--js_module_root` flag doesn't do what you want, then we can re-open.

**Comment by hearnden** [comment]
Bare import paths work fine with `--js_module_root`, and this issue report doesn't affect them. Please note I'm talking about absolute import paths, not bare import paths.  i.e., 
```
import { X } from '/x/x';
```
not
```
import { X } from 'x/x';
```

Absolute import paths only get interpreted as a path from the filesystem root.  They don't get interpreted as a path from a module root.

Failing example:
```
/tmp/x/x.js:
export const X = 1;

/tmp/y/y.js:
import { X } from '/x/x';
```

With `--js_module_root /tmp --js /tmp/x/x.js /tmp/y/y.js`, the import fails:
```
/tmp/y/y.js:1: ERROR - Failed to load module "/x/x"
import { X } from '/x/x';
^

1 error(s), 0 warning(s)
```

The import works fine with the bare path `x/x`, which is the `--js_module_root` behavior you're describing.

All these invocations fail with the same error when attempting to use an absolute import path.
 - `--js_module_root /tmp --js /tmp/x/x.js /tmp/y/y.js`
 - `--js_module_root /tmp --js x/x.js y/y.js`

Using `--js /x/x.js` fails with `ERROR - Cannot read: /x/x.js`.

**Comment by hearnden** [comment]
Ah - I think I see what you meant.

`--js_module_root / --js x/x.js y/y.js` does the trick, allowing an import of `'/x/x'` to get resolved as `x/x` relative to the the compiler's working directory.

So `--js_module_root` isn't a module root in the normal sense (i.e., a location from which to resolve module paths, like a classpath or an include path).  Rather, it's an arbitrary string prefix to strip off import paths before resolving the remainder against the current working directory of the compiler.  i.e., more like a mount point.

Thanks for your help.

**Comment by ChadKillingsworth** [comment]
I'm not sure I fully understand why this doesn't work:

```
--js_module_root /tmp --js /tmp/x/x.js /tmp/y/y.js
```

From my understanding of the flag, it should have. I may need to look into that more.

**Comment by supersteves** [comment]
Apologies if this is hijacking this issue but I can't find any other issue or wiki page more relevant.

I am struggling to figure out how to get node_modules and commonjs requires to work with Closure Compiler using ```--js_module_root```.

It would be really helpful if there was a node_modules example added here, showing the command line, directory structure, working dir (if relevant) and require line:
https://github.com/google/closure-compiler/wiki/JS-Modules

Also the command line usage could be more verbose. "Path prefixes to be removed from ES6 & CommonJS modules." I'm struggling to see why you'd want to put long prefixes in your require statements.

**Comment by ChadKillingsworth** [comment]
@supersteves The reason there is no documentation is it doesn't really work. You have to pre-process node_modules files so that the imports are paths instead of named modules.

There are changes to the compiler I have planned to address this, but nothing has been actually started yet.

**Comment by supersteves** [comment]
Thanks @ChadKillingsworth ... saw your response only now after posting https://github.com/google/closure-compiler/issues/1773

**Comment by ChadKillingsworth** [comment]
I believe this is working as documented/intended.
