### ISSUE TITLE
variable_renaming is not a valid option

### ISSUE THREAD

**Issue by gurmukhp** [google/closure-compiler#1706]
Hi all,

Is there a place I can find all the flags for the compiler? I'm going through the CompilerOptions file and found that I should be able to pass --variable_renaming to OFF or LOCAL but whenever I try to run the command, I get an error: 

```
"--variable_renaming" is not a valid option
```

I've tried using true, false and OFF, but still no joy:

```
Error: Command failed: java -jar -XX:-TieredCompilation node_modules/google-closure-compiler/compiler.jar --flagfile="/var/folders/hh/b4vmv50n08d0hd9657l7wqs0009j0s/T/34310de0-3b69-4795-aefd-cf667cbfaf05" --externs=node_modules/google-closure-compiler/contrib/externs/angular-1.5.js --externs=node_modules/google-closure-compiler/contrib/externs/angular-1.5-http-promise_templated.js --externs=node_modules/google-closure-compiler/contrib/externs/angular-1.5-mocks.js --externs=node_modules/google-closure-compiler/contrib/externs/angular-1.5-q_templated.js --closure_entry_point=d4g.app.module --compilation_level=ADVANCED_OPTIMIZATIONS --only_closure_dependencies=true --variable_renaming=OFF --warning_level=QUIET --angular_pass=true --output_wrapper=(function(){%output%}).call(window); --js_output_file="app.min.js"
```

Any tips on what I may be missing?

Thanks!

**Comment by ChadKillingsworth** [comment]
Here are all the command line flags for the compiler: https://github.com/google/closure-compiler/blob/master/src/com/google/javascript/jscomp/CommandLineRunner.java#L130-L655

Some flags have limited/special use an are purposefully hidden.
