### ISSUE TITLE
Explicit nullability for ES6 Symbol polyfill

### ISSUE THREAD

**Issue by icmdaf** [google/closure-compiler#1707]
Regardless of input, when using the flags

```
--language_in=ECMASCRIPT6_STRICT
--language_out=ECMASCRIPT5_STRICT
--jscomp_warning=analyzerChecks
```

I get these warnings in synthetic code:
```
 [synthetic:2] :41: WARNING - Name symbol in JSDoc is implicitly nullable.
Please add a ! to make it non-nullable, or a ? to make it explicitly nullable.
 @return {symbol}
          ^

 [synthetic:2] :45: WARNING - Name symbol in JSDoc is implicitly nullable.
Please add a ! to make it non-nullable, or a ? to make it explicitly nullable.
  return /** @type {symbol} */ ("jscomp_symbol_" + description + $jscomp.symbolCounter_++);
                    ^

 [synthetic:2] :640: WARNING - Name symbol in JSDoc is implicitly nullable.
Please add a ! to make it non-nullable, or a ? to make it explicitly nullable.
    /** @private @const @type {symbol} */ $jscomp.Map.key_ = Symbol("map-id-key");
                               ^
```
Looks like changing `{symbol}` to `{!symbol}` should fix that since it's just an alias for `string`.

**Comment by MatrixFrog** [comment]
The analyzerChecks are not intended to be turned on in your build. Eventually we need to make "symbol" a real type and then this will go away.

**Comment by hidachinoiro** [comment]
It seems --jscomp_error=* contains analyzerChecks, but I cannot filter out it by using --jscom_off.

**Comment by icmdaf** [comment]
The rest of the analyzerChecks are very useful though, so I would like to continue using them — why can't the synthetic code be fixed instead?

**Comment by MatrixFrog** [comment]
At some point the type system will really understand the `symbol` type but not this quarter. The analyzer checks are designed for systems like https://github.com/google/shipshape where warnings are shown only on source files, not synthetic files. If someone can come up with a short-term fix for that particular issue though, that would be nice, and then users could turn the analyzer checks on explicitly if they wanted to.

**Comment by icmdaf** [comment]
I haven't tried it out but when reporting the bug I basically thought the synthetic files were just [these auto-included polyfills](https://github.com/google/closure-compiler/blob/8a468ed4abb4ececc5f24928aac2f8c354fea54e/src/com/google/javascript/jscomp/js/es6/map.js#L394) and that fixing the types there would stop the analyzerChecks from complaining until `symbol` becomes a real type instead of an alias (some of the other code in these files has `@suppress` for similar reasons I guess?)

**Comment by MatrixFrog** [comment]
Essentially, yes. But `symbol` is just an alias for `?` (for now) and the implicit nullability check seems to think of that as "nullable" (which I suppose is technically true, though unhelpful in this case).

**Comment by Dominator008** [comment]
@MatrixFrog Well technically `?` should be ignored by the type checker. I'm not sure about the behavior of the implicit nullability check though.
