### ISSUE TITLE
runtime performance problem: math intensive test runs 3x slower using advanced-optimizations compile 

### ISSUE THREAD

**Issue by blickly** [google/closure-compiler#171]
This issue was imported from Closure Compiler's previous home at http://closure-compiler.googlecode.com

The original discussion is archived at:
http://blickly.github.io/closure-compiler-issues/#1226

**Comment by Dominator008** [comment]
Uploaded the provided source / test files.
[MatrixSpeed.zip](https://github.com/google/closure-compiler/files/102226/MatrixSpeed.zip)

**Comment by Dominator008** [comment]
Seems to have become worse. The compiled version runs in > 34 seconds on Chrome 49 and > 5 seconds on Firefox 43.

**Comment by Dominator008** [comment]
@myphysicslab @concavelenz According to V8 team's reply on https://bugs.chromium.org/p/v8/issues/detail?id=4702, the workaround is to pass "--output_wrapper=(function() {%output})()" to the Compiler. Non-toplevel code doesn't have the performance problem on either Chrome or Firefox. It is slightly faster than the uncompiled code on Chrome :)

**Comment by Dominator008** [comment]
Closing because this is technically a VM issue and there's an easy workaround.

**Comment by myphysicslab** [comment]
I'll test this within next couple weeks to confirm the output_wrapper fix.

**Comment by myphysicslab** [comment]
The output wrapper fix does solve the performance problem with the MatrixSpeed.zip test code.  But adding the output wrapper to my production (non-test) code results in errors at run time.

```
TypeError: undefined is not an object (evaluating 'goog.global.navigator')
getNavigator_PerformanceTests_en.js:117:711
getNativeUserAgentString_PerformanceTests_en.js:117:608
(anonymous function)PerformanceTests_en.js:117:809
(anonymous function)PerformanceTests_en.js:1556:112

ReferenceError: Can't find variable: myphysicslab
(anonymous function)PerformanceTests_en.html:67
```

Here is the compile command
```
java -jar ../javascript/closure-compiler/build/compiler.jar
--closure_entry_point=myphysicslab.test.PerformanceTests
--compilation_level=SIMPLE 
--define=goog.DEBUG=false
'--define=goog.LOCALE='\''en'\'''
--define=myphysicslab.lab.util.UtilityCore.ADVANCED=false
--generate_exports 
--js=../closure-library/ 
--js=src
--jscomp_error=accessControls
--jscomp_error=ambiguousFunctionDecl
--jscomp_error=checkTypes
--jscomp_error=checkVars
--jscomp_error=const
--jscomp_error=constantProperty
--jscomp_error=fileoverviewTags
--jscomp_error=globalThis
--jscomp_error=invalidCasts
--jscomp_error=misplacedTypeAnnotation
--jscomp_error=missingProperties
--jscomp_error=missingProvide
--jscomp_error=missingRequire
--jscomp_error=missingReturn
--jscomp_error=newCheckTypes
--jscomp_error=strictModuleDepCheck
--jscomp_error=suspiciousCode
--jscomp_error=typeInvalidation
--jscomp_error=undefinedNames
--jscomp_error=undefinedVars
--jscomp_error=unknownDefines
--jscomp_error=uselessCode
--jscomp_error=visibility
--language_in=ECMASCRIPT5_STRICT
--only_closure_dependencies=true
--warning_level=VERBOSE 
'--output_wrapper='\''(function(){%output%})()'\''' 
```

**Comment by concavelenz** [comment]
Are you missing an export?

**Comment by Dominator008** [comment]
You are probably missing an export.

**Comment by myphysicslab** [comment]
This test it is already annotated with `@export`.  I don't know what else to export.

Here is most of PerformanceTest.js minus comments and requires/provides:

```javascript
/**
* @constructor
* @struct
* @private
* @export
*/
myphysicslab.test.PerformanceTests = function() {
  throw new Error();
};
var PerformanceTests = myphysicslab.test.PerformanceTests;

/**
* @return {undefined}
* @export
*/
PerformanceTests.runTests = function() {
  Engine2DTestRig.startTests();
  MiscellanyTest.testPerformance();
  StraightStraightTest.testPerformance();
  PileTest.testPerformance();
  Engine2DTestRig.schedule(Engine2DTestRig.finishTests);
  Engine2DTestRig.runTests();
};
```

Here is most of the HTML file that runs the test:
```html
    <script src="../../MachineName.js"></script>
    <script src="PerformanceTests_en.js">
    </script>
    <script>
      myphysicslab.test.PerformanceTests.runTests();
    </script>
```

**Comment by Dominator008** [comment]
Can you show me the declaration of `myphysicslab`?

**Comment by myphysicslab** [comment]
As I understand it, `myphysicslab` is created as a byproduct of the various `goog.provide` statements. Here is the complete version of this file, minus comments:

```
goog.provide('myphysicslab.test.PerformanceTests');

goog.require('myphysicslab.lab.util.UtilityCore');
goog.require('myphysicslab.test.CircleCircleTest');
goog.require('myphysicslab.test.CircleStraightTest');
goog.require('myphysicslab.test.DoNothingTest');
goog.require('myphysicslab.test.Engine2DTestRig');
goog.require('myphysicslab.test.JointTest');
goog.require('myphysicslab.test.MiscellanyTest');
goog.require('myphysicslab.test.MultipleCollisionTest');
goog.require('myphysicslab.test.PileTest');
goog.require('myphysicslab.test.RopeTest');
goog.require('myphysicslab.test.SpeedTest');
goog.require('myphysicslab.test.StraightStraightTest');
goog.require('myphysicslab.test.ExpectedPerf');

goog.scope(function() {

var CircleCircleTest = myphysicslab.test.CircleCircleTest;
var CircleStraightTest = myphysicslab.test.CircleStraightTest;
var DoNothingTest = myphysicslab.test.DoNothingTest;
var Engine2DTestRig = myphysicslab.test.Engine2DTestRig;
var JointTest = myphysicslab.test.JointTest;
var MiscellanyTest = myphysicslab.test.MiscellanyTest;
var MultipleCollisionTest = myphysicslab.test.MultipleCollisionTest;
var PileTest = myphysicslab.test.PileTest;
var RopeTest = myphysicslab.test.RopeTest;
var SpeedTest = myphysicslab.test.SpeedTest;
var StraightStraightTest = myphysicslab.test.StraightStraightTest;
var UtilityCore = myphysicslab.lab.util.UtilityCore;

/**
* @constructor
* @struct
* @private
* @export
*/
myphysicslab.test.PerformanceTests = function() {
  throw new Error();
};
var PerformanceTests = myphysicslab.test.PerformanceTests;

/**
* @return {undefined}
* @export
*/
PerformanceTests.runTests = function() {
  Engine2DTestRig.startTests();
  MiscellanyTest.testPerformance();
  StraightStraightTest.testPerformance();
  PileTest.testPerformance();
  Engine2DTestRig.schedule(Engine2DTestRig.finishTests);
  Engine2DTestRig.runTests();
};

}); // goog.scope
```

There are a few hundred other files which are being dragged in by `goog.require` statements in other files.

**Comment by myphysicslab** [comment]
I found this comment on [stackoverflow](http://stackoverflow.com/questions/18449503/why-does-google-closure-compiler-adds-variable-to-the-global-namespace-when-the) which might be relevant?

> When compiling with --output_wrapper in ECMASCRIPT5_STRICT mode, it is worth mention that this value in anonymous wrapper function shall be bind manually to a window object: (function() {%output%}).call(window). Otherwise, this is not referenced to a global object in 'strict mode'. – manakor Apr 27 '15 at 6:58

**Comment by myphysicslab** [comment]
FYI, this might be a non-issue for me now.  I haven't been testing much with advanced compile for the last two years (because of this issue).  I'm trying to use advanced compile again and at least for this one test the performance is fine.  Note this is **without the output wrapper** because of the above issues when trying to use `--output_wrapper`.  I'll do some more tests using advanced compile.

**Comment by Dominator008** [comment]
Your example should work fine.

FYI, @export should not be used with other visibility modifiers like @private. We need better documentation on this. https://github.com/google/closure-compiler/issues/1543.

**Comment by myphysicslab** [comment]
I am using strict mode and the solution is to provide "this" as follows:

    --output_wrapper="'(function() {%output%}).call(window)'" \

With that in place it is all working now.

Is it a problem that the 'use strict' statement is no longer the first statement in the file?  It is now inside the wrapping function, so I guess that will also work.  But I think that with the flag

    --language_in=ECMASCRIPT5_STRICT \

then the 'use strict' should appear outside of the wrapping function as the first statement?

Here is the start of my advance-compiled program:

    (function() {'use strict';var h,aa=this;function r(a){return void 0!==a}function
