### ISSUE TITLE
Better handling of exports from ES6 modules that serve as entry points

### ISSUE THREAD

**Issue by Dominator008** [google/closure-compiler#1710]
Eg.: https://github.com/google/incremental-dom/blob/master/index.js
This file is an entry point to the library. There should be an easy way to indicate that these exports are "global" and should not be dropped by Advanced Compilation.
For now I have to rewrite the file into something like: https://github.com/Dominator008/incremental-dom/blob/build-with-closure/index_closure.js
which doesn't seem ideal.

**Comment by Dominator008** [comment]
@ChadKillingsworth

**Comment by Dominator008** [comment]
Also the handling of ES6 entry points seem buggy. Will file a separate issue for that when I have time.

**Comment by ChadKillingsworth** [comment]
The index_closure is what I would have expected. Or goog.exportSymbol/exportProperty. Something to indicate it's an export.

**Comment by alexeagle** [comment]
@Dominator008 did you file that separate issue for es6 imports from `index.js`? I think I'm hitting the same thing in the issue linked above.

**Comment by ChadKillingsworth** [comment]
We need a module loader for this. This crosses the script/module boundary.
