### ISSUE TITLE
Warn when accessing static properties subject to flattening

### ISSUE THREAD

**Issue by DavidSouther** [google/closure-compiler#1712]
[Object property flattening](https://developers.google.com/closure/compiler/docs/limitations#implications-of-object-property-flattening) has failed to warn me in two different contexts now, both applying meta-programming techniques to constructor functions.

```js
// When working with a list of Constructors
function Foo {}
Foo.bar = 3;

[Foo].map(x => x.bar);

// When writing parameterized tests about Constructors
function testSerialization(t, ctor) {
  const serialized = t.serialize();
  const deserialized = ctor.deserialize(serialized);
  expect(deserialized.serialize()).to.deep.equal(serialized);
}
```

This form is similar enough to using `this` in static methods I'd expect a warning. Better, it would detect this is happening and prevent property flattening.

**Comment by dimvar** [comment]
Yes, the collapse-properties pass assumes that it can see all property accesses to the constructor properties. There isn't currently a way to turn that specific pass off in the open-source compiler. The two workarounds are: change the code to avoid doing these accesses, or use simple optimizations.

**Comment by ChadKillingsworth** [comment]
There's an easier option: `@nocollapse`

**Comment by dimvar** [comment]
Oh yes, forgot about that. Thanks Chad!

**Comment by ChadKillingsworth** [comment]
@DavidSouther In general, the compiler doesn't recognize property accesses like that inside iterations of any type. It's hard to do that in all but the most trivial of cases.

**Comment by DavidSouther** [comment]
So the only option for using this type of code is to just know that you need to disable property flattening?

**Comment by ChadKillingsworth** [comment]
The short answer is yes. The long answer is you have to recognize these cases, but there are multiple techniques to keep the code more or less as-is without violating the constructs of the compiler.

For instance:

```js
/** @record */
function HasBar() {}
HasBar.prototype.bar = 3;

// When working with a list of Constructors
function Foo {}
/** @nocollapse */
Foo.bar = 3;

/** @type {Array<HasBar>} */
[Foo].map(x => x.bar);

// When writing parameterized tests about Constructors
function testSerialization(t, ctor) {
  const serialized = t.serialize();
  const deserialized = ctor.deserialize(serialized);
  expect(deserialized.serialize()).to.deep.equal(serialized);
}
```

**Comment by ChadKillingsworth** [comment]
I'm closing this issue. Unless someone has a brilliant idea of how to detect these cases, feel free to re-open.

**Comment by DavidSouther** [comment]
Ah, I'd never seen 

```
/** @nocollapse */
Foo.bar = 3;
```

as a thing before. 

I naively assumes @export would achieve that. Thanks for looking in to this.
