### ISSUE TITLE
document how `goog.module` is different from es6 module or commonjs modules

### ISSUE THREAD

**Issue by bobzhang** [google/closure-compiler#1723]
Following #1620 
Besides the obvious part `goog.require` vs `require`, `goog.module` seems to add more checks, I wish `goog.require` behaves the same as other module systems (except the path resolution), but if it is not achievable, it would be nice to have the difference documented clearly in case users hit other corner cases

**Comment by Dominator008** [comment]
Feel free to add a Wiki page for that.

**Comment by ChadKillingsworth** [comment]
Actually preferably just add it to this one: https://github.com/google/closure-compiler/wiki/JS-Modules

**Comment by bobzhang** [comment]
If I know the difference, would not ask here..

**Comment by Dominator008** [comment]
@bobzhang Well I guess you can start from what you've observed.

**Comment by concavelenz** [comment]
Is this what you are looking for?  https://github.com/google/closure-library/wiki/goog.module:-an-ES6-module-like-alternative-to-goog.provide

**Comment by bobzhang** [comment]
@Dominator008 @ChadKillingsworth I updated the wiki here https://github.com/google/closure-compiler/wiki/JS-Modules, still wish no such restrictions though!
