### ISSUE TITLE
[NTI] Missing warning about the second argument to Function.prototype.apply in global scope

### ISSUE THREAD

**Issue by Dominator008** [google/closure-compiler#1727]
With
```js
// apply.js
/** @const {Array<*>} */
const arr = [];

// Function.prototype.apply in function, warning
function g() {
  g.apply(null, arr);
};

// Function.prototype.apply in global scope, no warning
g.apply(null, arr);
```
do
```sh
java -jar build/compiler.jar -W VERBOSE --new_type_inf apply.js 
```
I get:
```
apply.js:6: WARNING - Invalid type for parameter 2 of function g.apply.
expected : Arguments<?>|Array<?>|undefined
found    : Array<*>|null

  g.apply(null, arr);
```

Note that the warning is missing in the global scope.

Personally I think NTI should infer that `arr` is not nullable since it's a `@const` initialized with `[]`, but that's a separate issue.

Real-world use case:
https://github.com/google/incremental-dom/blob/1f8324f39432d65bca62ed30640cb30b9b3e2304/src/virtual_elements.js#L172

**Comment by dimvar** [comment]
This is WAI. In g, the use of arr is in a different scope from the declaration, so we use the declared type. In the global scope, the use is in the same scope as the declaration, so we have more type information.
