### ISSUE TITLE
Preserving doc comments, but renamed, to enable partial compilation

### ISSUE THREAD

**Issue by chrismiddleton** [google/closure-compiler#1732]
I was working on a way to do partial compilation of my code to speed up the compile time and I realized that I couldn't really make it work without a new feature.

I'd like to put forward a request for a --preserve-doc-comments-minified option that would preserve all doc comments, with parameter names renamed, so that they can be used in a next step of compilation. Read on for why I think this would be useful.

Here's the way I was trying to have it work: you have files A, B, C (you would have more files in reality). Say that your script compiles them once. No changes there. Now say that when you run your script a second time, it notices that A and B have not been modified since the last compilation. Due to this, it precompiles A and B alone into one file and then compiles that with C. The third time the script is run, if C is still the only file being modified, it just uses the previous partial compilation of A and B along with C, decreasing the size of the files being compiled. (With SIMPLE_OPTIMIZATIONS on in the partial compile step to preserve function names for file C and ADVANCED_OPTIMIZATIONS on in the main compile step.). One question would be -- how much faster would such a precompiled compilation be? I don't know, but it must help somewhat, since the total input size would be smaller.

But the problem is that since A and B are compiled, all their type information has been removed, so when you compile A+B and C together, the compiler can no longer check if C is not compatible with A+B.

If we could preserve the doc comments in A+B, at least the function/interface/class doc comments (basically, any doc comments which the outside world might care about), then C could be type-checked against A+B and incremental compilation like this would be more possible.

I'm curious if anyone else was trying to accomplish  something similar and hit the same wall and/or solved it a different way.

**Comment by Dominator008** [comment]
Sounds like `--preserve_type_annotations` is what you need: https://github.com/google/closure-compiler/blob/master/src/com/google/javascript/jscomp/CommandLineRunner.java#L613-L617

**Comment by chrismiddleton** [comment]
I hadn't seen that option before - it looks like there isn't any wiki documentation for it anywhere. But unfortunately it doesn't rename the doc parameters.

E.g.
```javascript
/**
 * @param {Bar!} bar
* @param {Baz!} baz
**/
function foo (bar, baz) {}
```

becomes

```javascript
/**
 * @param {Bar!} bar
* @param {Baz!} baz
**/
function foo (c, d) {}

which will not allow it to go through another compilation step. Is this by design or just a bug?

**Comment by MatrixFrog** [comment]
The compiler is essentially a full-program compiler. I like the idea of what you're trying to do but the compiler is not designed for it so it will probably require a lot of changes.

**Comment by dimvar** [comment]
Right, this is not just an issue of preserving comments. The compiler optimizations change code significantly (code gets removed, namespaces get collapsed, etc), and there is no guarantee that the compiled output will compile cleanly.

**Comment by chrismiddleton** [comment]
> code gets removed, namespaces get collapsed, etc

This is a very good point. I completely forgot about the code removal. I guess if this were to work, it would require more options than the one I mentioned above, including a "--no-tree-shake" option. I'd be curious if there actually are a lot (if any) more things that the compiler would need to not do, or if this would be that would be the only extra thing.

That being said, I understand why this is more complicated than it first seemed. Perhaps someday in the future Closure can do staged compilation as a first-rate feature. If it matters, my scheme for doing this was basically dependent on the fact that in our code, we use a dependency-gathering script and "// @include" directives at the top of our files. This fact allowed my staged compilation script to essentially know when either the file itself *or any of its dependencies* got updated. If staged compilation were ever to become part of Closure, dependency management would have to be integrated with it.

Thanks for your insight, everyone.
