### ISSUE TITLE
[NTI] Confusing error message for type mismatch

### ISSUE THREAD

**Issue by shicks** [google/closure-compiler#1733]
The following is clearly a type error:

``` js
/** @param {!IArrayLike<string>} x
    @return {boolean}
    @this {{a: string}} */
function func(x) { return x[0] == this.a; }

['ab', 'cd'].find(func, {a: 'a'});
```

OTI fails to complain at all, but NTI gives an obscure [message](https://closure-compiler-debugger.appspot.com/#input0%3D%252F**%2520%2540param%2520%257B!IArrayLike%253Cstring%253E%257D%2520x%250A%2520%2520%2520%2520%2540return%2520%257Bboolean%257D%250A%2520%2520%2520%2520%2540this%2520%257B%257Ba%253A%2520string%257D%257D%2520*%252F%250Afunction%2520func%28x%29%2520%257B%2520return%2520x%255B0%255D%2520%253D%253D%2520this.a%253B%2520%257D%250A%250A%255B'ab'%252C%2520'cd'%255D.find%28func%252C%2520%257Ba%253A%2520'a'%257D%29%253B%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES%3D1%26CHECK_TYPES_NEW_INFERENCE%3D1%26MISSING_PROPERTIES%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1):

```
input0:6: WARNING - Illegal instantiation in function type function(this:IArrayLike<T>|null|string,function(this:S,T,number,Array<T>):boolean,S|undefined=):T|undefined for the type variable T.
 You can only specify one type. Found [string, IArrayLike<string>].
['ab', 'cd'].find(func, {a: 'a'});
^
```

Due to the very complicated type of `Array.prototype.find`, it's difficult to read and understand that this message is basically saying that there's a type mismatch.

Could we expand the message a bit - maybe with an explicit "type mismatch" somewhere in it, as well as text to indicate that `this` wants `T` to be `string`, but parameter 1 wants `T` to be `IArrayLike<string>`?

**Comment by shicks** [comment]
Including the name of the function (`Array.prototype.find` in this case) might also help to cut through the more difficult function type expression.

**Comment by dimvar** [comment]
Giving a good name for the function, or identifying which parts of the function type were responsible for the mismatch is non-trivial. (Useful, but not sth I can prioritize right now.) What about reorganizing the error message as follows. Would that help?

    When instantiating a polymorphic function, you can only specify one type for each type variable.
    Found 2 types for type variable T: [string, IArrayLike<string>],
    when instantiating function type function(this:IArrayLike<T>|null|string,function(this:S,T,number,Array<T>):boolean,S|undefined=):T|undefined.

**Comment by supersteves** [comment]
I was about to report a new issue when I found this. I'm getting the following (itself the improvement above), which is still really hard to read:
```
Web/View/Common/bigtable/BigTable.jsx:240: WARNING - 
  When instantiating a polymorphic function, you can only specify one type for each type variable.
   Found 2 types for type variable PP: [struct{gridLeft: number, gridWidth: number, headerHorizontalGridLineColour: string, headerHorizontalGridLineWidth: number, headerVerticalGridLineColour: string, headerVerticalGridLineWidth: number, isHeader: boolean, key: string, model: (HeaderFooterModel$$module$Web$View$Common$bigtable$model$HeaderFooterModel|null), setGridPosition: function((null|number),(null|number),boolean): ?, visibleColumns: Array<Tier$$module$Web$View$Common$bigtable$model$Tier>}, {gridLeft: number, gridWidth: number, headerHorizontalGridLineColour: string, headerHorizontalGridLineWidth: number, headerVerticalGridLineColour: string, headerVerticalGridLineWidth: number, isHeader: boolean, key: string, model: (HeaderFooterModel$$module$Web$View$Common$bigtable$model$HeaderFooterModel|null), setGridPosition: function(number,number): ?, visibleColumns: Array<Tier$$module$Web$View$Common$bigtable$model$Tier>}],
   when instantiating type: <PP,CC>function((function(new:React.Component<PP,?,CC>,PP,CC): ?|string),(PP|null|undefined)=,...(Array<(React.Element|null|number|string|undefined)>|Function|React.Element|null|number|string|undefined)): (React.Element|null)
  238|         }
  239|         const headerFooterComponents = headerFooterModels.map((headerFooterModel, index) =>
  240|         React.createElement(ColumnHeaderFooter, {
  241|             key: "colHeader_" + index,
  242|             isHeader: isHeader,
```
In fact typically it's wrapped on the console:
`  When instantiating a polymorphic function, you can only specify one type for each type variable.`
`   Found 2 types for type variable PP: [struct{gridLeft: number, gridWidth: number, headerHorizontalGridLineColour: string, headerHorizontalGridLineWidth: number, headerVerticalGridLineColour: string, headerVerticalGridLineWidth: number, isHeader: boolean, key: string, model: (HeaderFooterModel$$module$Web$View$Common$bigtable$model$HeaderFooterModel|null), setGridPosition: function((null|number),(null|number),boolean): ?, visibleColumns: Array<Tier$$module$Web$View$Common$bigtable$model$Tier>}, {gridLeft: number, gridWidth: number, headerHorizontalGridLineColour: string, headerHorizontalGridLineWidth: number, headerVerticalGridLineColour: string, headerVerticalGridLineWidth: number, isHeader: boolean, key: string, model: (HeaderFooterModel$$module$Web$View$Common$bigtable$model$HeaderFooterModel|null), setGridPosition: function(number,number): ?, visibleColumns: Array<Tier$$module$Web$View$Common$bigtable$model$Tier>}],`
`   when instantiating type: <PP,CC>function((function(new:React.Component<PP,?,CC>,PP,CC): ?|string),(PP|null|undefined)=,...(Array<(React.Element|null|number|string|undefined)>|Function|React.Element|null|number|string|undefined)): (React.Element|null)`

Good luck with that! And often I'm faced with 20 such problems.

What I have to do in extreme cases like this is put it into Beyond Compare and try and split up the two types onto either side of the visual diff to find the problem. Or, at least, put it into a text editor and reformat it.

I realise it is hard to provide more directed assistance in the error message. But it might help if this exact same message was simply formatted "pretty":
```
Web/View/Common/bigtable/BigTable.jsx:240: WARNING - 
  When instantiating a polymorphic function, you can only specify one type for each type variable.
   Found 2 types for type variable PP: 
    [
     struct{
      gridLeft: number, 
      gridWidth: number, 
      headerHorizontalGridLineColour: string, 
      headerHorizontalGridLineWidth: number, 
      headerVerticalGridLineColour: string, 
      headerVerticalGridLineWidth: number, 
      isHeader: boolean, 
      key: string, 
      model: (HeaderFooterModel$$module$Web$View$Common$bigtable$model$HeaderFooterModel|null), 
      setGridPosition: function((null|number),(null|number),boolean): ?, 
      visibleColumns: Array<Tier$$module$Web$View$Common$bigtable$model$Tier>
     }, 
     {
      gridLeft: number, 
      gridWidth: number, 
      headerHorizontalGridLineColour: string, 
      headerHorizontalGridLineWidth: number, 
      headerVerticalGridLineColour: string, 
      headerVerticalGridLineWidth: number, 
      isHeader: boolean, 
      key: string, 
      model: (HeaderFooterModel$$module$Web$View$Common$bigtable$model$HeaderFooterModel|null), 
      setGridPosition: function(number,number): ?, 
      visibleColumns: Array<Tier$$module$Web$View$Common$bigtable$model$Tier>}
    ],
   when instantiating type: 
    <PP,CC>function((function(new:React.Component<PP,?,CC>,PP,CC): ?|string),(PP|null|undefined)=,...(Array<(React.Element|null|number|string|undefined)>|Function|React.Element|null|number|string|undefined)): (React.Element|null)
```
Ah. Now I can see immediately it's the `setGridPosition` function arguments that is the problem.
