### ISSUE TITLE
Compiler warning when reassigning module exports

### ISSUE THREAD

**Issue by martine** [google/closure-compiler#1735]
```js
goog.module('reexportTest');
exports.foo = 3;
exports.foo = 4;
```
produces warnings like
```
JSC_CONSTANT_PROPERTY_REASSIGNED_VALUE: constant property foo assigned a value more than once at line 3 character 0
```

Perhaps this should be illegal, but I'm not sure what the rules are in this area.  (I guess exports are closest to commonjs exports in their semantics?)

Related: issue #1492.

Repro link:
https://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%2540compilation_level%2520ADVANCED_OPTIMIZATIONS%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250Agoog.module('reexportTest')%253B%250Aexports.foo%2520%253D%25203%253B%250Aexports.foo%2520%253D%25204%253B%250A

**Comment by dimvar** [comment]
> Perhaps this should be illegal, but I'm not sure what the rules are in this area.

Right, you can only assign once to a property of exports. If you want to reassign, you can silence the warning by using `/** @suppress {const|duplicate} */` on the second assignment, but the duplicate assignment may impact subsequent checks and optimizations.

Does this address your issue?

**Comment by martine** [comment]
That sounds acceptable -- it's not the behavior of commonjs but it's understandable that it'd be different.

Is this restriction documented somewhere, so I can point others at it?

**Comment by martine** [comment]
I think maybe a note on https://github.com/google/closure-compiler/wiki/JS-Modules would be good (?)

**Comment by ChadKillingsworth** [comment]
Yes - I'm planning to spend some time on that page after the next release. We're pretty much at feature parity across the 3 supported module formats now.

The `@const` restriction though is purely for the compiler. It enables the early inlining passes and other kinds of optimization.

**Comment by dimvar** [comment]
Chad, assigning to you since you're already planning to fix documentation on this.

**Comment by ChadKillingsworth** [comment]
👍

**Comment by ChadKillingsworth** [comment]
Documentation updated
