### ISSUE TITLE
Self-compiled soyutils problem with Imported test-only code

### ISSUE THREAD

**Issue by rejas** [google/closure-compiler#1738]
Not sure if you can help me here but I am trying to build the soyutils myself with the google closure compiler like this: 

`java  -server -XX:+TieredCompilation  -jar "../closure-compiler/build/compiler.jar"  --js ../closure-library/closure/goog/ --js ../closure-templates/javascript/soyutils_usegoog.js --js soyutils-exports.js --js_output_file=soyutils-no-amd.js --manage_closure_dependencies --only_closure_dependencies --closure_entry_point soy --closure_entry_point soydata --closure_entry_point soyutils.exports --define 'goog.DEBUG=false' --compilation_level ADVANCED_OPTIMIZATIONS --output_wrapper '(function(w){ %output% w.soy=this.soy; w.soydata=this.soydata; w.goog=this.goog})(window);'`

But using the generated soyutils-no-amd.js in my project leads to this error code: "Uncaught Error: Importing test-only code into non-debug environment."

Any idea / hint where this test-code comes from or how I can disable it?

**Comment by ChadKillingsworth** [comment]
It would be best to ask this on the [closure-compiler google group](https://groups.google.com/forum/#!forum/closure-compiler-discuss) or the [closure templates google group](https://groups.google.com/forum/#!forum/closure-templates-discuss). The issue tracker is reserved for bug reports a feature changes.
