### ISSUE TITLE
Support user-defined type guard functions

### ISSUE THREAD

**Issue by Dominator008** [google/closure-compiler#1740]
Inspired by https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#user-defined-type-guard-functions

I'm thinking of something like:
```js
/**
 * @param {*} a
 * @typeguard {Cat}
 * @return {boolean}
 */
function isCat(a) {
  return a.name === 'kitty';
}

var /** Cat | Dog */ x;
if (isCat(x)) {
  x.meow(); // OK, x is Cat in this block
}
```

This should be useful in cases like #1589.

**Comment by Dominator008** [comment]
@dimvar

**Comment by dimvar** [comment]
I was gonna mark this as low priority, but frankly, I don't see us working on it anytime soon. There are many many other things more important. So I'll just close.

**Comment by Dominator008** [comment]
@dimvar That's fine. Filed just for the record :)
