### ISSUE TITLE
Compiler doesn't recognize `has` check on es6 `Map`

### ISSUE THREAD

**Issue by uriva** [google/closure-compiler#1743]
A code similar to this will not compile. The compiler complains that the `get` function might return an undefined value, although this is not possible due to the check one line before.

```js
/** @type {!Map<string, !Object>} */
var myMap = new Map();

/**
 * @param {string} key
 * @return {!Object}
 */
var myFun = function(key) {
  if (myMap.has(key)) {
    return myMap.get(key);
  } else {
    return {};
  }
};
```

**Comment by Dominator008** [comment]
While it might be possible to support this particular case, I feel that it will be hard to support the general case. Will it compile if you cast the returned value to `!Object`, like
```js
...
return /** @type {!Object| */ (myMap.get(key));
```
?

**Comment by dimvar** [comment]
I'll change the es6 externs to fix this. For other collections, such as arrays, Object<KEY, VALUE> and IObject, we exclude `undefined` from the result, unless the user explicitly includes it in the type.

**Comment by Dominator008** [comment]
Closed by https://github.com/google/closure-compiler/commit/d83e3c2c7d032fda6bae8de0f94c59057eb88c3c
