### ISSUE TITLE
Bad "JSC_DETERMINISTIC_TEST" warnings with null checks

### ISSUE THREAD

**Issue by illandril** [google/closure-compiler#1748]
The compiler seems to assume that variables will never be changed by function calls.

Simple reproduction case:
```js
// ==ClosureCompiler==
// @compilation_level ADVANCED_OPTIMIZATIONS
// @output_file_name default.js
// ==/ClosureCompiler==

var i = 0;
var world = null;
var maybeSetWorld = function() {
  i++;
  if ( i == 2 ) {
    world = "World";
  }
};

maybeSetWorld();
if ( world == null ) {
  maybeSetWorld();
  if ( world != null ) {
	  alert('Hello, ' + world);
  }
}
```

I'd expect no warnings (or _maybe_ 1), but get 2...

```
Number of warnings: 2

JSC_DETERMINISTIC_TEST: condition always evaluates to true
left : null
right: null at line 11 character 5
if ( world == null ) {
     ^
JSC_DETERMINISTIC_TEST: condition always evaluates to false
left : null
right: null at line 13 character 7
  if ( world != null ) {
       ^
```

The first warning would be fine in this case (because it will be null), but I wouldn't expect the compiler to analyze things that thoroughly. The second warning is flat out wrong - the condition will evaluate to true in this example.

**Comment by Dominator008** [comment]
As of now, the new type inference does not have this kind of check. @dimvar Is this something to be added? My guess is no.

**Comment by ChadKillingsworth** [comment]
We do have this type of analysis. But for performance reasons it doesn't run in the global scope:

```js
// ==ClosureCompiler==
// @compilation_level ADVANCED_OPTIMIZATIONS
// @output_file_name default.js
// @warning_level VERBOSE
// ==/ClosureCompiler==

(function() {
var i = 0;
var world = null;
var maybeSetWorld = function() {
  i++;
  if ( i == 2 ) {
    world = "World";
  }
};

maybeSetWorld();
if ( world == null ) {
  maybeSetWorld();
  if ( world != null ) {
      alert('Hello, ' + world);
  }
}
})()
```

**Comment by Dominator008** [comment]
@ChadKillingsworth In that case the OTI shouldn't give false positives in the global scope.

**Comment by ChadKillingsworth** [comment]
I agree - but I'm guessing that fixing this in OTI won't be a priority.

**Comment by dimvar** [comment]
@ChadKillingsworth your guess is correct :)

**Comment by Dominator008** [comment]
Duplicate of https://github.com/google/closure-compiler/issues/380.
