### ISSUE TITLE
Type infeference fails when assignment is separate from declaration

### ISSUE THREAD

**Issue by ChadKillingsworth** [google/closure-compiler#1751]
Repo case for both OTI and NTI:
```js
(function() {
var xhr;
xhr = new XMLHttpRequest();
xhr.open("GET", "somefile", true);
xhr.addEventListener(
  'load',
  function() {    
    var data = new Uint8Array(xhr.response); // xhr is unknown
    console.log(data);
  }
);
xhr.send();
})()
```
If the initial assignment is on the same line as the declaration, the type is correctly inferred.

http://closure-compiler-debugger.appspot.com/#input0%3D(function()%2520%257B%250Avar%2520xhr%253B%250Axhr%2520%253D%2520new%2520XMLHttpRequest()%253B%250Axhr.open(%2522GET%2522%252C%2520%2522somefile%2522%252C%2520true)%253B%250Axhr.addEventListener(%250A%2520%2520'load'%252C%250A%2520%2520function()%2520%257B%2520%2520%2520%2520%250A%2520%2520%2520%2520var%2520data%2520%253D%2520new%2520Uint8Array(xhr.response)%253B%2520%252F%252F%2520xhr%2520is%2520unknown%250A%2520%2520%2520%2520console.log(data)%253B%250A%2520%2520%257D%250A)%253B%250Axhr.send()%253B%250A%257D)()%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_CONSTANTS%3D1%26CHECK_DEPRECATED%3D1%26CHECK_ES5_STRICT%3D1%26CHECK_GLOBAL_NAMES%3D1%26CHECK_GLOBAL_THIS%3D1%26CHECK_SUSPICIOUS_CODE%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES%3D1%26CHECK_TYPES_NEW_INFERENCE%3D1%26CHECK_UNREACHABLE_CODE%3D1%26ENABLE_ALL_DIAGNOSTIC_GROUPS%3D1%26LANG_IN_IS_ES6%3D1%26MISSING_PROPERTIES%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1%26TRANSPILE%3D1

**Comment by Dominator008** [comment]
This is WAI for both OTI and NTI. If you look at the AST, `xhr` is of type `XMLHttpRequest`. The unknown type is on `xhr.response`, which is because the externs file is missing that property: https://github.com/google/closure-compiler/blob/b85923365aa8571db47ac09a27c1adddb0d299a2/externs/browser/w3c_xml.js#L295.

**Comment by dimvar** [comment]
FWIW, even when you run NTI, the warning that you see is from OTI, because it runs after NTI. Normally OTI warnings are silenced, but there are a few that slip through the cracks, which I'm planning to fix.

NTI doesn't support reportUnknownTypes yet. I'll add support for it soon-ish.

**Comment by ChadKillingsworth** [comment]
Ahh that makes sense.
