### ISSUE TITLE
module pattern does not minify

### ISSUE THREAD

**Issue by myphysicslab** [google/closure-compiler#1757]
When using an [augmentation module pattern](http://www.adequatelygood.com/JavaScript-Module-Pattern-In-Depth.html) Closure Compiler doesn't minify the code. Here is an example:

```javascript
var module1 = {};
module1 = (function(export_to){
    export_to.add1 = function(arg) { return arg+1 }
    export_to.add2 = function(arg) { return arg+2 }
    export_to.add10 = function(arg) { return arg+10 }
    return export_to;
})(module1);

console.log(module1.add10(4))
```

The [result with Advanced Optimization](http://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540compilation_level%2520ADVANCED_OPTIMIZATIONS%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250A%252F%252F%2520ADD%2520YOUR%2520CODE%2520HERE%250Avar%2520module1%2520%253D%2520%257B%257D%253B%250Amodule1%2520%253D%2520(function(export_to)%257B%250A%2520%2520%2520%2520export_to.add1%2520%253D%2520function(arg)%2520%257B%2520return%2520arg%252B1%2520%257D%250A%2520%2520%2520%2520export_to.add2%2520%253D%2520function(arg)%2520%257B%2520return%2520arg%252B2%2520%257D%250A%2520%2520%2520%2520export_to.add10%2520%253D%2520function(arg)%2520%257B%2520return%2520arg%252B10%2520%257D%250A%2520%2520%2520%2520return%2520export_to%253B%250A%257D)(module1)%253B%250A%250Aconsole.log(module1.add10(4))%250A%250A) is

```javascript
var b={},b=function(a){a.a=function(a){return a+1};a.c=function(a)
{return a+2};a.b=function(){return 14};return a}(b);console.log(14);
```

The result should be

```javascript
console.log(14);
```

This is perhaps similar to [Closure Compiler Issue 891: missed property collapsing opportunity](https://github.com/google/closure-compiler/issues/891).

This came up from researching a question on StackOverflow [Closure compiler doesn't remove unused properties](http://stackoverflow.com/questions/36769662/closure-compiler-doesnt-remove-unused-properties/36827388#36827388)

**Comment by dimvar** [comment]
The compiler is somehow confused because you are passing module1 to the function and the assigning the result of the call to module1. Since the function adds properties to its argument, you can just omit the assignment to module1 (and the return statement) and then the program will optimize to a single statement.

**Comment by myphysicslab** [comment]
That works, but only if the input is an integer.  Here is the code you are suggesting, but with a non-integer  argument (4/3) we don't get optimized code:

```javascript
var module1 = {};
(function(export_to){
    export_to.add1 = function(arg) { return arg+1 }
    export_to.add2 = function(arg) { return arg+2 }
    export_to.add10 = function(arg) { return arg+10 }
})(module1);

console.log(module1.add10(4/3))
```

The [result with Advanced Optimization](http://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540compilation_level%2520ADVANCED_OPTIMIZATIONS%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250A%252F%252F%2520ADD%2520YOUR%2520CODE%2520HERE%250Avar%2520module1%2520%253D%2520%257B%257D%253B%250A(function(export_to)%257B%250A%2520%2520%2520%2520export_to.add1%2520%253D%2520function(arg)%2520%257B%2520return%2520arg%252B1%2520%257D%250A%2520%2520%2520%2520export_to.add2%2520%253D%2520function(arg)%2520%257B%2520return%2520arg%252B2%2520%257D%250A%2520%2520%2520%2520export_to.add10%2520%253D%2520function(arg)%2520%257B%2520return%2520arg%252B10%2520%257D%250A%257D)(module1)%253B%250A%250Aconsole.log(module1.add10(4%252F3))%250A%250A) is

```javascript
var b={};(function(a){a.b=function(a){return a+1};a.c=function(a){return a+2};
a.a=function(){return 4/3+10}})(b);console.log(b.a());
```
but it should be
```javascript
console.log(4/3+10);
```

**Comment by dimvar** [comment]
Are you building with the latest release? There is commit https://github.com/google/closure-compiler/commit/ef9ff6433890d76eb9bc66148cc02c7dd0f96517 at head, which will probably inline in this case as well.

**Comment by myphysicslab** [comment]
I was using the [online closure compiler](http://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540compilation_level%2520ADVANCED_OPTIMIZATIONS%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250A%252F%252F%2520ADD%2520YOUR%2520CODE%2520HERE%250Avar%2520module1%2520%253D%2520%257B%257D%253B%250A(function(export_to)%257B%250A%2520%2520%2520%2520export_to.add1%2520%253D%2520function(arg)%2520%257B%2520return%2520arg%252B1%2520%257D%250A%2520%2520%2520%2520export_to.add2%2520%253D%2520function(arg)%2520%257B%2520return%2520arg%252B2%2520%257D%250A%2520%2520%2520%2520export_to.add10%2520%253D%2520function(arg)%2520%257B%2520return%2520arg%252B10%2520%257D%250A%257D)(module1)%253B%250A%250Aconsole.log(module1.add10(4%252F3))%250A%250A).  I don't see any way to tell what version the online closure compiler is built from.

(I'm trying to update to the current compiler on my own machine, but having some problems with the new compiler).

**Comment by myphysicslab** [comment]
I'm getting similar results with the latest compiler:

    $ java -jar ../javascript/closure-compiler/build/compiler.jar --version
    Closure Compiler (http://github.com/google/closure-compiler)
    Version: v20160315-213-g4787bb5
    Built on: 2016/04/25 10:12
    $ java -jar ../javascript/closure-compiler/build/compiler.jar --js test.js
    var module1={};(function(b){b.add1=function(a){return a+1};
    b.add2=function(a){return a+2};b.add10=function(a){return a+10}})(module1);
    console.log(module1.add10(4/3));

Here is the file being compiled:

    $ cat test.js
    var module1 = {};
    (function(export_to){
        export_to.add1 = function(arg) { return arg+1 }
        export_to.add2 = function(arg) { return arg+2 }
        export_to.add10 = function(arg) { return arg+10 }
    })(module1);

    console.log(module1.add10(4/3))
