### ISSUE TITLE
existing output file does not update when compiling multiple files

### ISSUE THREAD

**Issue by ZanneZankyo** [google/closure-compiler#1761]
Hi, I'm a Windows user and I'm using Closure Compiler in IDEA file watcher to compile all my .js files into a single one. But I notice that the existing output file does not update after I change my code. I have to delete the output file then trigger the file watcher to get the newest compiled code.

I call the compiler directly in cmd finding that the exist output file does not update, too:
`java -jar compiler.jar --compilation_level WHITESPACE_ONLY --js_output_file=output.js --js *.js`
The existing output file only updates when compiling a single file:
`java -jar compiler.jar --compilation_level WHITESPACE_ONLY --js_output_file=output.js --js a.js`

I wonder how to update the output file without deleting it when compiling multiple files.

**Comment by Dominator008** [comment]
I doubt if `--js_output_file=output.js --js *.js` works. Looks like you will be reading `output.js` as an input starting from your second compilation. What about `--js_output_file=output.js --js *.js --js !output.js`?

**Comment by ZanneZankyo** [comment]
Oh, my apologize, it was because I use wildcard in such a wrong way
