### ISSUE TITLE
w3c_gamepad.js not included in Closure?!?

### ISSUE THREAD

**Issue by StewVed** [google/closure-compiler#1763]
I thought I'd look into why my basic gamepad code wasn't being kept`(navigator.getGamepads();` and `GamePad[x].axes.slice(0)` for example

It looks like whoever was going to move `w3c_audio.js` and `w3c_gamepad.js` into `closure-compiler/externs/browser/ forgot to move w3c_gamepad.js` along with `w3c_audio.js`;
`w3c_gamepad.js` still appears to be in `closure-compiler/contrib/externs/`

I'd love to not have to go into my compiled code to rename `navigator.getGamepads()`; and `GamePad[x].axes.slice(0)` every time :-)

in the interest of Open Source and to clarify, here is my gamepad code function thingy: (along with the w3c spec for my reference)

```js
//overwrite with the current gamepad statuses
var GamePad = navigator.getGamepads();
//Chrom[e/ium] appears to have a bug where it reports 4 undefined gamepads instead of nothing! woraround here:
for (var x = 0; x < GamePad.length; x++) {
  if (GamePad[x]) {//only add if the gamepad exists - NOT FOOLPROOF!
    //only shallow-copy the buttons and axes - don't need the rest (yet!)
    WinGamePads[x] = [];
    WinGamePads[x].buttons = GamePad[x].buttons.slice(0);
    WinGamePads[x].axes = GamePad[x].axes.slice(0);
  }
}
/*
interface Gamepad {
	readonly	attribute DOMString				id;
	readonly	attribute long					index;
	readonly	attribute boolean				connected;
	readonly	attribute DOMHighResTimeStamp	timestamp;
	readonly	attribute GamepadMappingType	mapping;
	readonly	attribute double[]				axes;
	readonly	attribute GamepadButton[]		buttons;
};
*/
```
-StewVed

**Comment by brad4d** [comment]
https://www.w3.org/TR/gamepad/

**Comment by Dominator008** [comment]
@StewVed Assuming you are using the command line runner, you can use the `--externs` flag like `--externs closure-compiler/contrib/externs/w3c_gamepad.js` for now.

**Comment by StewVed** [comment]
@Dominator008 Awesome! I'll do that, thank you!

could https://github.com/google/closure-compiler/tree/master/contrib/externs/w3c_gamepad.js
be moved to:
https://github.com/google/closure-compiler/tree/master/externs/browser
where w3c_audio.js was moved to though?

**Comment by Dominator008** [comment]
@StewVed Maybe. We will need to also move it internally at Google.
