### ISSUE TITLE
MUST_BE_PRIVATE doesn't work with @protected

### ISSUE THREAD

**Issue by jart** [google/closure-compiler#1769]
The latest release from March, `CheckJSDocStyle.MUST_BE_PRIVATE` does not take into consideration the fact that `@protected` members will have the trailing underscore.

**Comment by MatrixFrog** [comment]
You can check with the stylists but I thought protected members were supposed to not have the underscore.

**Comment by jart** [comment]
My mistake then. In that case, feel free to close. I guess it's just a
legacy issue with closure library.

**Comment by MatrixFrog** [comment]
> legacy issue with closure library

Yup, there are many of those :(
