### ISSUE TITLE
When's the next release?

### ISSUE THREAD

**Issue by jart** [google/closure-compiler#1770]
I work on [Closure Rules](https://github.com/bazelbuild/rules_closure). I'm really excited about integrating some of the new linting features in the codebase. But there hasn't been a release since March 15th.

1. When is the next release planned?
2. Would you consider adopting a regular release schedule?

I would be so happy if there was a release at the beginning of each month. Then I could sync up my release process with yours.

**Comment by MatrixFrog** [comment]
We try to release once a month but it doesn't always happen for various reasons. The next one should be out by early next week at the latest.

**Comment by hochhaus** [comment]
@MatrixFrog Any chance that closure-templates can be released on the same interval as closure-{compiler,library}?

**Comment by MatrixFrog** [comment]
I think @Ubehebe is the de-facto owner of that release cycle nowadays.

**Comment by jart** [comment]
Thanks for the clarification. Also +1 to @hochhaus's comment on Templates release at same time.

@Ubehebe would it be too much trouble to add "Ping Justine" to your release protocol, so I know when it goes live on Maven? That way I can get it integrated and released with Closure Rules immediately after. That way Closure users are super happy.

**Comment by hochhaus** [comment]
@iflan While we are discussing it, would it be possible to also sync closure-stylesheets with the release of closure-{compiler,library}?

**Comment by iflan** [comment]
Yes, if whoever releases the compiler and library is willing to do it.

**Comment by hochhaus** [comment]
Thanks Ian. @MatrixFrog Would the compiler team consider integrating stylesheets into your release process as well?

I left Google many years ago so I'm not sure how much I can do to help. Please let me know if I can though.

**Comment by Dominator008** [comment]
@hochhaus I don't think the Compiler team manages Closure Stylesheets releases. Looks like @iflan is the one doing the releases?

**Comment by hochhaus** [comment]
@Dominator008 Thanks. Yes, my understanding is that Ian is the current owner. I was hoping that the timing/version numbering for all of the closure tools could by synchronized. Doing so would simplify things a bit for external users.

My interpretation of Ian's comment above was that he is open to synchronizing the stylesheets release with the compiler/library if the owner of that release process would also do the stylesheets release.

Therefore I was wondering if whomever currently releases compiler/library would also be willing to release stylesheets. Did I misinterpret something?

**Comment by alexeagle** [comment]
+1 angular would like to demo closure-compiler with our new offline compilation but "version": "20160315.2.0" is not good enough :(

**Comment by dimvar** [comment]
> I was hoping that the timing/version numbering for all of the closure tools could by synchronized.

This would be fine if these tools were meant to always be used together. But in reality, they are separate tools and have been operating independently. It makes less sense to synchronize the versions if the actual coding efforts are not coordinated.

The compiler team does not own stylesheets, and there is no plan to start owning it, so we shouldn't be the ones doing their external releases.

So, assuming no ownership transfer for these projects, the best solution for someone who wants to use all these together, is to ping the individual owners for releases. If someone has other suggestions, please add them here. Otherwise, this issue can probably be closed.

**Comment by MatrixFrog** [comment]
Yup. Apologies for this release taking a while. We hope to have it out soon.

**Comment by hochhaus** [comment]
@dimvar Fair enough. Thanks!
