### ISSUE TITLE
Use with node_modules and commonjs requires

### ISSUE THREAD

**Issue by supersteves** [google/closure-compiler#1773]
I'm exploring using Closure Compiler with node_modules and have run into a couple of blocking issues:
- Moocher dropping. All CJS modules are being considered moochers because they don't "provide" anything. I need moocher dropping in my codebase to avoid pulling in tons of unused files for compilation.
- node_module path resolution. I'm happy to write my paths explicitly like `require("react-bootstrap/lib/Action.js")` but where the module I'm requiring itself requires e.g. "react" rather than "react/main.js", it's an error. For this I'd like to supply my own loader which implements node_modules rules and package json awareness.

As it stands I think I can only realistically use CJS requires (or ES6 imports) when importing my own code rather than complex pre-existing libraries.

**Comment by ChadKillingsworth** [comment]
> Moocher dropping. All CJS modules are being considered moochers because they don't "provide" anything. I need moocher dropping in my codebase to avoid pulling in tons of unused files for compilation.

Not sure why you see this - this definitely isn't occurring in my code bases. Make sure you use the `--process_common_js_modules` flag.

> As it stands I think I can only realistically use CJS requires (or ES6 imports) when importing my own code rather than complex pre-existing libraries.

This is currently true.

**Comment by ChadKillingsworth** [comment]
This is fixed by #2130 - use the `--module_resolution=NODE` flag.

**Comment by supersteves** [comment]
Great! Thanks Chad.
