### ISSUE TITLE
assert() type narrowing doesn't work with destructured import

### ISSUE THREAD

**Issue by SLaks** [google/closure-compiler#1786]
I can't figure out how to make `goog.module()` syntax work on jscomp-debug, so no demo for you.

Source:

``` js
const asserts = goog.require('goog.asserts');
const {assert} = goog.require('goog.asserts');

var /** !Object */ a = asserts.assert(null);
var /** !Object */ b = assert(null);
```

Result:

```
ERROR - initializing variable
found   : null
required: Object
var /** !Object */ b = assert(null);
                       ^
```

Calling `assert` doesn't apply the return type; calling `asserts.assert()` does.

**Comment by dimvar** [comment]
I'm gonna guess this is a bug in the InlineAliases pass. Here is a repro. I also define a type and import it using destructuring and it is not recognized.

https://closure-compiler-debugger.appspot.com/home#input0%3Dgoog.provide('goog.asserts')%253B%250A%250Agoog.asserts.assert%2520%253D%2520function(x)%2520%257B%257D%253B%250A%250A%252F**%2520%2540constructor%2520*%252F%250Agoog.asserts.MyFoo%2520%253D%2520function()%2520%257B%257D%253B%26input1%3Dgoog.module('foo.bar')%253B%250A%250Aconst%2520asserts%2520%253D%2520goog.require('goog.asserts')%253B%250Aconst%2520%257Bassert%257D%2520%253D%2520goog.require('goog.asserts')%253B%250A%250Aconst%2520%257BMyFoo%257D%2520%253D%2520goog.require('goog.asserts')%253B%250A%250Avar%2520%252F**%2520!Object%2520*%252F%2520a%2520%253D%2520asserts.assert(null)%253B%250Avar%2520%252F**%2520!Object%2520*%252F%2520b%2520%253D%2520assert(null)%253B%250A%250Avar%2520%252F**%2520!asserts.MyFoo%2520*%252F%2520x%2520%253D%2520null%253B%250Avar%2520%252F**%2520!MyFoo%2520*%252F%2520y%2520%253D%2520null%253B%26conformanceConfig%26externs%3Dvar%2520goog%253B%250Agoog.provide%253B%250Agoog.require%253B%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES%3D1%26CLOSURE_PASS%3D1%26LANG_IN_IS_ES6%3D1%26MISSING_PROPERTIES%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1%26TRANSPILE%3D1

**Comment by lauraharker** [comment]
Closing this, the original repro and dimvar's repro both work now.
