### ISSUE TITLE
Tests for Property Existance with Renaming

### ISSUE THREAD

**Issue by blickly** [google/closure-compiler#179]
This issue was imported from Closure Compiler's previous home at http://closure-compiler.googlecode.com

The original discussion is archived at:
https://blickly.github.io/closure-compiler-issues/#983

**Comment by ChadKillingsworth** [comment]
This is now possible with `goog.reflect.objectProperty`.

```js
console.log(goog.reflect.objectProperty('foobar', window) in window);
```
