### ISSUE TITLE
Type mismatch when passing in function that takes generic parameter more broad than required

### ISSUE THREAD

**Issue by chrismiddleton** [google/closure-compiler#1791]
The basic problem is that the compiler is treating `function(Foo<T?>)` as a type mismatch with `function(Foo<T>)`. I believe that this case should be allowed and not throw a mismatch (more on why below).

```
JSC_TYPE_MISMATCH: actual parameter 2 of Downloader.prototype.download does not match formal parameter
found   : function (Result<(null|string)>): ?
required: function (Result<string>): ? at line 20 character 35
  (new Downloader()).download(url, callback);
```

If I was passing in `Result<string?>` to a function that accepted only `Result<string>`, then it makes since that the compiler would complain. However, if I'm passing in a *function* that accepts `Result<string?>`, then my function is more permissive than is required, which should be fine. In other words, passing in a function that accepts more than the required parameter does not break type safety.

I believe this problem only surfaces when part of a template - a plain `function(string?)` is accepted when `function(string)` is required.

Here is the code and an Appspot link:

```js
/**
 * @constructor
 * @template T
 * @param {T} val
**/
function Result (val) {
  this.val = val;
}

/** @constructor */
function ImageDisplayer () {}

/**
 * @param {string} url
 * @param {function(Result<string?>!)} callback
**/
ImageDisplayer.prototype.display = function (url, callback) {
  (new Downloader()).download(url, callback);
};

/** @constructor */
function Downloader () {}

/**
 * @param {function(Result<string>!)} callback
**/
Downloader.prototype.download = function (url, callback) {
  callback(new Result('downloading'));
};

var myDiv = document.createElement('div');
document.body.appendChild(myDiv);

var imageDisplayer = new ImageDisplayer();
imageDisplayer.display('my-image', function (result) {
  if (result.val == null) myDiv.innerHTML = '';
  else myDiv.appendChild(document.createTextNode(result.val));
});
```

https://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540compilation_level%2520ADVANCED_OPTIMIZATIONS%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250A%252F**%250A%2520*%2520%2540constructor%250A%2520*%2520%2540template%2520T%250A%2520*%2520%2540param%2520%257BT%257D%2520val%250A**%252F%250Afunction%2520Result%2520(val)%2520%257B%250A%2520%2520this.val%2520%253D%2520val%253B%250A%257D%250A%250A%252F**%250A%2520*%2520%2540constructor%250A**%252F%250Afunction%2520ImageDisplayer%2520()%2520%257B%257D%250A%250A%252F**%250A%2520*%2520%2540param%2520%257Bstring%257D%2520url%250A%2520*%2520%2540param%2520%257Bfunction(Result%253Cstring%253F%253E!)%257D%2520callback%250A**%252F%250AImageDisplayer.prototype.display%2520%253D%2520function%2520(url%252C%2520callback)%2520%257B%250A%2520%2520(new%2520Downloader()).download(url%252C%2520callback)%253B%250A%257D%253B%250A%250A%252F**%250A%2520*%2520%2540constructor%250A**%252F%250Afunction%2520Downloader%2520()%2520%257B%257D%250A%250A%252F**%250A%2520*%2520%2540param%2520%257Bfunction(Result%253Cstring%253E!)%257D%2520callback%250A**%252F%250ADownloader.prototype.download%2520%253D%2520function%2520(url%252C%2520callback)%2520%257B%250A%2520%2520callback(new%2520Result('downloading'))%253B%250A%257D%253B%250A%250Avar%2520myDiv%2520%253D%2520document.createElement('div')%253B%250Adocument.body.appendChild(myDiv)%253B%250A%250Avar%2520imageDisplayer%2520%253D%2520new%2520ImageDisplayer()%253B%250AimageDisplayer.display('my-image'%252C%2520function%2520(result)%2520%257B%250A%2520%2520if%2520(result.val%2520%253D%253D%2520null)%2520myDiv.innerHTML%2520%253D%2520''%253B%250A%2520%2520else%2520myDiv.appendChild(document.createTextNode(result.val))%253B%250A%257D)%253B%250A

**Comment by chrismiddleton** [comment]
My workaround is to change

```
 * @param {function((Result<string?>))} callback
```

to 

```
 * @param {function((Result<string>|Result<null>))} callback
```

This isn't that much of a pain as long as the function name isn't too long, but can be very tedious if instead of `string?`, you have something like `(Foo|Bar|Baz)!`, or if the class name is longer than `Result` or you have nested generics.

Perhaps the above transformation could be done in the compiler? What do you think about the equivalence of the two above?

**Comment by ChadKillingsworth** [comment]
Make sure you have read http://closuretools.blogspot.com/2012/06/subtyping-functions-without-poking-your.html - because I believe this is related.

**Comment by chrismiddleton** [comment]
Thanks for the link, Chad. I think I'm using it correctly, right? A function taking a string or null is a function taking a string? Even though string is normally a subtype of string or null?

**Comment by chrismiddleton** [comment]
Thanks for the link, Chad. I skimmed the beginning (will read the whole thing when I can). If I understand correctly...

```
string IS-A string|null
=> Result<string> IS-A Result<string|null> ## this is the step that the compiler is not taking
=> function(Result<string|null>) IS-A function(Result<string>)
```

so it should work?

**Comment by dimvar** [comment]
Generics are invariant in the old type checker, so Result<string> is not a subtype of Result<string|null>.

They are covariant in the new type inference, so you can check that out: 
https://github.com/google/closure-compiler/wiki/Using-NTI-(new-type-inference)

Closing this since we won't be changing the semantics in the old type checker.
