### ISSUE TITLE
How to reference not-imported types from ES6 modules?

### ISSUE THREAD

**Issue by jGleitz** [google/closure-compiler#1793]
I have something like the following:

Foo.js:
```js
export default class Foo {
    // code
}
```

Bar.js:
```js
export default class Bar {
    /**
     * @param {!Foo} foo 
     */
    constructor(foo) {
        // code
    }
}
```

Note that `Bar.js` uses an instance of the class from `Foo.js` but does not need to import `Foo.js`. What is the correct way to declare that `Bar`’s constructor takes a `Foo` in that situation? In the old namespace system, I was able to reference `Foo` by its full namespace, without having to `goog.require('namespace.Foo');`. The code above doesn’t compile:

```
$ java -jar node_modules/google-closure-compiler/compiler.jar --js Foo.js --js Bar.js --compilation_level ADVANCED_OPTIMIZATIONS --jscomp_warning '*'
Bar.js:3: WARNING - Bad type annotation. Unknown type Foo
	         * @param {!Foo} foo 
	                    ^

0 error(s), 1 warning(s), 100,0% typed
```

That makes sense, because the compiler can’t know if I really mean the class in `Foo.js`. I’m looking for some way to reference the class in `Foo.js`.

I could import `Foo.js` into `Bar.js`:

```js
import Foo from './Foo';
export default class Bar {
    /**
     * @param {!Foo} foo 
     */
    constructor(foo) {
        // code
    }
}
```

But then I have an unused import:

```
$ java -jar node_modules/google-closure-compiler/compiler.jar --js Foo.js --js Bar.js --compilation_level ADVANCED_OPTIMIZATIONS --jscomp_warning '*'
Bar.js:1: WARNING - 'module$Foo' required but not used
import Foo from './Foo';
^

0 error(s), 1 warning(s), 100,0% typed
```

Which isn’t a good solution, either. In JSDoc, I believe I could do:

Foo.js:
```js
/**
 * @module namspace/Foo
 */
export default class Foo {
    // code
}
```

Bar.js:
```js
export default class Bar {
    /**
     * @param {!module:namespace/Foo} foo 
     */
    constructor(foo) {
        // code
    }
}
```

But closure compiler does not accept that syntax:

```
$ java -jar node_modules/google-closure-compiler/compiler.jar --js Foo.js --js Bar.js --compilation_level ADVANCED_OPTIMIZATIONS --jscomp_warning '*'
Bar.js:3: WARNING - Bad type annotation. expected closing }
	         * @param {!module:namespace/Foo} foo 
	                          ^

Bar.js:3: WARNING - Bad type annotation. expecting a variable name in a @param tag
	         * @param {!module:namespace/Foo} foo 
	                          ^

Bar.js:5: WARNING - Function must have JSDoc.
		    constructor(foo) {
		    ^

0 error(s), 3 warning(s), 100,0% typed
```

So what is the expected way to reference the class from `Foo.js` in `Bar.js` without importing `Foo.js`?

**Comment by ChadKillingsworth** [comment]
This is something best asked on stackoverflow or the Google group. In fact, it's already been answered there: https://groups.google.com/d/msg/closure-compiler-discuss/nW5nbGcerJw/RECwK40cBAAJ
