### ISSUE TITLE
absence of @return tag : documentation differ from compiler behaviour

### ISSUE THREAD

**Issue by tdelmas** [google/closure-compiler#1795]
The documentation ( https://developers.google.com/closure/compiler/docs/js-for-compiler#tag-return ) says : 
> If there is no return value, do not use a @return tag. 

But the Compiler treats unannotated extern functions as returning ?, not undefined:
http://closure-compiler-debugger.appspot.com/#input0%3Dvar%2520%252F**%2520number%2520*%252F%2520a%2520%253D%2520f()%253B%26input1%26conformanceConfig%26externs%3Dfunction%2520f()%2520%257B%257D%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES%3D1%26LANG_IN_IS_ES6%3D1%26MISSING_PROPERTIES%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1%26TRANSPILE%3D1

Follow up of https://github.com/google/closure-compiler/pull/1792#issuecomment-219219366

**Comment by MatrixFrog** [comment]
If I remember correctly there is a difference here between functions in externs and functions in regular code.

**Comment by tdelmas** [comment]
I'm not sure : 
https://closure-compiler-debugger.appspot.com/#input0%3Dvar%2520%252F**%2520number%2520*%252F%2520a%2520%253D%2520f()%253B%250A%250A%252F**%2520%2540return%2520%257Bundefined%257D%2520*%252F%2520function%2520f2()%2520%257B%2520return%2520f()%253B%2520%257D%250A%250Afunction%2520f3()%2520%257B%2520return%2520f()%253B%2520%257D%250A%250Avar%2520%252F**%2520number%2520*%252F%2520b%2520%253D%2520f2()%253B%250A%250Avar%2520%252F**%2520number%2520*%252F%2520c%2520%253D%2520f3()%253B%26input1%26conformanceConfig%26externs%3D%250A%252F**%2520%2540return%2520%257Bundefined%257D%2520*%252F%2520%250Afunction%2520f()%2520%257B%257D%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES%3D1%26LANG_IN_IS_ES6%3D1%26MISSING_PROPERTIES%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1%26TRANSPILE%3D1

**Comment by ChadKillingsworth** [comment]
The difference is that inference runs on source but not externs.  An externs function without annotation is assumed to take any number of arguments of any type and return any type. This does not occur in source.

The other quirk is that a partially annotated function is treated differently than a fully annotated one. Though I don't recall the exact difference.

**Comment by dimvar** [comment]
I updated the documentation of the `@return` tag to clarify.
https://developers.google.com/closure/compiler/docs/js-for-compiler#tag-return
