### ISSUE TITLE
Cannot access property name of non-object type truthy (NTI)

### ISSUE THREAD

**Issue by supersteves** [google/closure-compiler#1801]
Strange error, can't see what's wrong with my code:

``` javascript
function f(v) {
  if (v && v.constructor) return v.constructor.name;
  else return null;
}
```
```
input0:2: WARNING - Cannot access property name of non-object type truthy.
  if (v && v.constructor) return v.constructor.name;
```
https://closure-compiler-debugger.appspot.com/#input0%3Dfunction%2520f(v)%2520%257B%250A%2520%2520if%2520(v%2520%2526%2526%2520v.constructor)%2520return%2520v.constructor.name%253B%250A%2520%2520else%2520return%2520null%253B%250A%257D%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES%3D1%26CHECK_TYPES_NEW_INFERENCE%3D1%26LANG_IN_IS_ES6%3D1%26MISSING_PROPERTIES%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1%26TRANSPILE%3D1

Compiler version from a couple of weeks or so ago.

**Comment by Dominator008** [comment]
Fixed by https://github.com/google/closure-compiler/commit/0d8b50e8d2381abcc1def78379c37afdb18c6d14

**Comment by supersteves** [comment]
Nice. Thanks.
