### ISSUE TITLE
Ability to define loose types (NTI)

### ISSUE THREAD

**Issue by supersteves** [google/closure-compiler#1804]
I want to be able to define some React props and validate them in the compiler. Some or all of the props are optional. I want the compiler to check them, permit missing props, but complain if unrecognised props are present.

Here the [compiler fails](https://closure-compiler-debugger.appspot.com/#input0%3D%252F**%250A%2520*%2520%2540typedef%2520%257B%257B%250A%2520*%2520%2520%2520color%253A%2520string%252C%250A%2520*%2520%2520%2520size%253A%2520number%250A%2520*%2520%257D%257D%250A%2520*%252F%250Alet%2520MyType%253B%250A%250A%252F**%2520%2540type%2520%257BMyType%257D%2520*%252F%250Alet%2520everything%2520%253D%2520%257B%2520color%253A%2520%2522a%2522%252C%2520size%253A%25205%2520%257D%253B%250A%250A%252F**%2520%2540type%2520%257BMyType%257D%2520*%252F%250Alet%2520missing1%2520%253D%2520%257B%250A%2520%2520%2520%2520color%253A%2520%2522a%2522%250A%257D%253B%250A%250A%252F**%2520%2540type%2520%257BMyType%257D%2520*%252F%250Alet%2520missingAll%2520%253D%2520%257B%250A%257D%253B%250A%250A%252F**%2520%2540type%2520%257BMyType%257D%2520*%252F%250Alet%2520mistyped%2520%253D%2520%257B%250A%2520%2520%2520%2520color%253A%2520%2522a%2522%252C%250A%2520%2520%2520%2520sizes%253A%25205%250A%257D%253B%250A%250A%252F**%2520%2540type%2520%257BMyType%257D%2520*%252F%250Alet%2520mistypedAll%2520%253D%2520%257B%250A%2520%2520%2520%2520colour%253A%2520%2522a%2522%252C%250A%2520%2520%2520%2520sizes%253A%25205%250A%257D%253B%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES%3D1%26CHECK_TYPES_NEW_INFERENCE%3D1%26CLOSURE_PASS%3D1%26LANG_IN_IS_ES6%3D1%26MISSING_PROPERTIES%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1%26TRANSPILE%3D1) at all but the first 'everything' assignment:
``` javascript
/**
 * @typedef {{
 *   color: string,
 *   size: number
 * }}
 */
let MyType;

/** @type {MyType} */
let everything = { color: "a", size: 5 };

/** @type {MyType} */
let missing1 = {
    color: "a"
};

/** @type {MyType} */
let missingAll = {
};

/** @type {MyType} */
let mistyped = {
    color: "a",
    sizes: 5
};
```

I've tried adding the verbose ```|undefined``` way I assumed might work. Here NTI doesn't care about any of these cases and [passes without error/warning](https://closure-compiler-debugger.appspot.com/#input0%3D%252F**%250A%2520*%2520%2540typedef%2520%257B%257B%250A%2520*%2520%2520%2520color%253A%2520(string%257Cundefined)%252C%250A%2520*%2520%2520%2520size%253A%2520(number%257Cundefined)%250A%2520*%2520%257D%257D%250A%2520*%252F%250Alet%2520MyType%253B%250A%250A%252F**%2520%2540type%2520%257BMyType%257D%2520*%252F%250Alet%2520everything%2520%253D%2520%257B%2520color%253A%2520%2522a%2522%252C%2520size%253A%25205%2520%257D%253B%250A%250A%252F**%2520%2540type%2520%257BMyType%257D%2520*%252F%250Alet%2520missing1%2520%253D%2520%257B%250A%2520%2520%2520%2520color%253A%2520%2522a%2522%250A%257D%253B%250A%250A%252F**%2520%2540type%2520%257BMyType%257D%2520*%252F%250Alet%2520missingAll%2520%253D%2520%257B%250A%257D%253B%250A%250A%252F**%2520%2540type%2520%257BMyType%257D%2520*%252F%250Alet%2520mistyped%2520%253D%2520%257B%250A%2520%2520%2520%2520color%253A%2520%2522a%2522%252C%250A%2520%2520%2520%2520sizes%253A%25205%250A%257D%253B%250A%250A%252F**%2520%2540type%2520%257BMyType%257D%2520*%252F%250Alet%2520mistypedAll%2520%253D%2520%257B%250A%2520%2520%2520%2520colour%253A%2520%2522a%2522%252C%250A%2520%2520%2520%2520sizes%253A%25205%250A%257D%253B%250A%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES%3D1%26CHECK_TYPES_NEW_INFERENCE%3D1%26CLOSURE_PASS%3D1%26LANG_IN_IS_ES6%3D1%26MISSING_PROPERTIES%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1%26TRANSPILE%3D1):
``` javascript
/**
 * @typedef {{
 *   color: (string|undefined),
 *   size: (number|undefined)
 * }}
 */
let MyType;
```

I think the latter is a bug. But is this the right way to solve this problem or am I missing a technique? With NTI I often see "(loose)" in errors; is loose the behaviour I'm seeking and how to you define it?

**Comment by dimvar** [comment]
To have optional properties, the syntax is `|undefined`, like you did. This is supported well in NTI, and is buggy in the old type checker.

> complain if unrecognised props are present.

Records are checked structurally, meaning that the subtype can have extra properties without warning. The way to forbid extra properties for normal classes is with `@struct`. You can technically define a `@record` as `@struct`, but I would stay away from that for now. It's a grey area in the semantics and we haven't quite decided what we want to do there.

**Comment by dimvar** [comment]
The loose types you see in the error messages cannot be defined with annotations. They usually get created when inference of object or function types in taking place. We probably need to improve the error messages around those to avoid confusion.

**Comment by supersteves** [comment]
@dimvar Thanks. I'll move this into a discussion as I can see why it's not a bug now.

**Comment by supersteves** [comment]
Although in reply to your comment about ```@record``` and ```@struct```; I tried using a class to define the props but it won't work because ```{ color, size }``` is not the same as MyType:
``` javascript
class MyType {
  constructor() {
    /** @type {string|undefined} */ this.color;
    /** @type {number|undefined} */ this.size;
  }
}
```
```
input0:9: WARNING - The right side in the assignment is not a subtype of the left side.
Expected : MyType|null
Found    : {color:string, size:number}

let everything = { color: "a", size: 5 };
```
So clearly I do need the ability to define ```@record```+```@struct``` - or some other way to define the shape of an object without permitting new properties. Should I file this as a feature request?

**Comment by dimvar** [comment]
Right, it won't work because classes are checked nominally, not structurally.

Feel free to file a feature request about this. Just FYI, it's not a high priority in the short-term though.

**Comment by supersteves** [comment]
Understood. I've filed it anyway, should anyone else chime in.
