### ISSUE TITLE
Need DiagnosticGroups clarification for all OTI and NTI diagnostic types

### ISSUE THREAD

**Issue by supersteves** [google/closure-compiler#1806]
I'm building a large codebase with NTI enabled but with OTI errors also emitted. I'm enabling one or the other via a warnings guard, for different sections of the codebase, in a single compilation run.

I need to identify all diagnostic types which apply exclusively to each approach.

These appear to be the NTI ones (although (e.g.) GlobalTypeInfo appears to be created whether or not NTI is enabled):

NewTypeInference.ALL_DIAGNOSTICS
JSTypeCreatorFromJSDoc.ALL_DIAGNOSTICS
GlobalTypeInfo.ALL_DIAGNOSTICS

Can I safely use a warnings guard on these 3 groups to enable/disable NTI warnings?  Can I assume that "_NTI_" in the key means it's exclusively NTI?

(Magically it seems when I use a custom warnings guard which enables/disables NTI warnings by file path, the OTI warnings are automatically disabled/enabled (inverse effect). Not sure how this happens but it's what I want.)

So really I'm just asking for advice, and a DiagnosticGroup which encompasses everything enabled by setNewTypeInference(), and perhaps an inverse for anything turned off by setNewTypeInference() without setReportOTIErrorsUnderNTI().

**Comment by dimvar** [comment]
newCheckTypes is the diagnostic group for warnings from all NTI-related passes.
https://github.com/google/closure-compiler/blob/master/src/com/google/javascript/jscomp/DiagnosticGroups.java#L233

PS: the github issue tracker is for bugs/feature requests. For questions, please use:
https://groups.google.com/forum/#!forum/closure-compiler-discuss

**Comment by supersteves** [comment]
I missed that - thanks. Will do.
