### ISSUE TITLE
wiki page on id generators is inaccurate

### ISSUE THREAD

**Issue by blickly** [google/closure-compiler#181]
This issue was imported from Closure Compiler's previous home at http://closure-compiler.googlecode.com

The original discussion is archived at:
http://blickly.github.io/closure-compiler-issues/#1188

**Comment by lauraharker** [comment]
The wiki was updated at some point to discuss which types of id generator are stable across compilations.

https://github.com/google/closure-compiler/wiki/Id-Generator-Annotations#id-generator-strategies
