### ISSUE TITLE
Maven release for new version missing

### ISSUE THREAD

**Issue by jochenberger** [google/closure-compiler#1810]
Same as #1485

**Comment by ChadKillingsworth** [comment]
There is a checklist. Persons responsible for distributing releases get an early warning of pending release and each has their own process for releasing.

Please refrain from posting new issues related to this. Different contributors volunteer their time to release the compiler to different repositories. We recognize that this causes delays between releases hitting different mirrors. I myself spent time on my vacation last week to publish the compiler version to the npm registry.

The maven release in particular is having issues related to non-standard JSDoc comments. As soon as that is fixed it will be available.
