### ISSUE TITLE
Ability to disable more passes (inline aliases) for fastest possible compilation

### ISSUE THREAD

**Issue by supersteves** [google/closure-compiler#1813]
I've been trying to create a streamlined mode for Closure Compiler which does the bare minimum to get the code bundled and runnable in an up to date Chrome browser, for rapid in-browser debugging and development cycles.

(Because I'm using ES6 modules now, I can't use WHITESPACE_ONLY or ClosureBundler.)

This will allow my developers to choose between 

1. fastest (no checks) = 4 seconds
2. medium (checks, but no optimisations) =  10s
3. medium+NTI = 43s
4. production (advanced obfuscation and some other things enabled) =  26s
5. production+NTI = 64s

I've configured the fastest by using SIMPLE_OPTIMIZATIONS then profiling and disabling all significant passes (polyfills, check types, infer types, analyzer checks, missing/extra require, inline vars/funcs/props, check useless code).

So this is a request for 2 related changes, or for a green light to develop each/either as a PR:

1. Inline Aliases is now the sole biggest performance hit. I'd like to disable this, and it seems necessary (according to javadoc) only if you have checkTypes. I propose a compiler option, with some safeguards added such that it is forced to true if checkTypes is true.
2. Ability to transpile modules only, but leave all other ES6 transpilation out since it is unnecessary in current stable Chrome for most / all (?) of ES6.

**Comment by ChadKillingsworth** [comment]
This would be a short-term stopgap solution only and I don't think it's worth the time. https://groups.google.com/a/chromium.org/forum/#!msg/blink-dev/uba6pMr-jec/tXdg6YYPBAAJ

You have the option to use a different module format that does not require transpilation. Both CommonJS and goog.module supoort uncompiled mode in the browser.

**Comment by dimvar** [comment]
FYI, both of your requests will be worked on at some point. InlineAliases has some other issues that make it incompatible with incremental compiles, so we're looking into an alternative, and hopefully delete the pass altogether at some point. Emitting ES6 for the features that are supported natively in browsers is also something we want to do. So, not saying any hard timelines, but you'll eventually see progress on these.

**Comment by supersteves** [comment]
Thanks.
