### ISSUE TITLE
WhitespaceWrapGoogModules is incompatible with goog.ENABLE_DEBUG_LOADER=false

### ISSUE THREAD

**Issue by hochhaus** [google/closure-compiler#1815]
The [WhitespaceWrapGoogModule](https://github.com/google/closure-compiler/commit/5afe95683b3ed020f7dfed772b7f2eacd332c9fe#diff-aa11261c60c6153a08ba78365124971dR48) pass generates code which assumes that goog.loadModule() is defined. However, in [base.js](https://github.com/google/closure-library/blob/master/closure/goog/base.js#L800) goog.loadModule() is not defined when goog.ENABLE_DEBUG_LOADER is false. Therefore the combination of WHITESPACE_ONLY mode and goog.ENABLE_DEBUG_LOADER=false are currently incompatible.

```sh
ahochhaus@ahochhaus-pc:~/test2$ cat uncomp_defines.js
```
```js
var CLOSURE_UNCOMPILED_DEFINES = {
  "goog.ENABLE_DEBUG_LOADER": false
};
ahochhaus@ahochhaus-pc:~/test2$ cat module.js 
goog.module('foo');
ahochhaus@ahochhaus-pc:~/test2$ cat file.js 
goog.require('foo');

console.log('success');
```
```
ahochhaus@ahochhaus-pc:~/test2$ java -jar compiler.jar --js base.js --js module.js --js file.js --compilation_level=WHITESPACE_ONLY --formatting=PRETTY_PRINT --dependency_mode=LOOSE | ./phantomjs /dev/stdin 
success
^C
ahochhaus@ahochhaus-pc:~/test2$ java -jar compiler.jar --js uncomp_defines.js --js base.js --js module.js --js file.js --compilation_level=WHITESPACE_ONLY --formatting=PRETTY_PRINT --dependency_mode=LOOSE | ./phantomjs /dev/stdin 
TypeError: undefined is not a function (evaluating 'goog.loadModule(function(exports) {
  "use strict";
  goog.module("foo");
  return exports;
})')

  phantomjs://code/stdin:925 in global code
^C
```

**Comment by MatrixFrog** [comment]
Why do you want that particular combination? The debug loader is only needed if you're not using the compiler at all, if I remember correctly.

**Comment by hochhaus** [comment]
My limited understanding is that in WHITESPACE_ONLY mode all of the required namespaces should already be concatenated into a single file and should not need to be dynamically loaded off network/disk. The desired behavior for our use case is (a) not dynamically loading JS sources and (b) not writing out deps.js. Therefore we [set](https://github.com/bazelbuild/rules_closure/blob/master/closure/testing/phantomjs_runner.js#L256) the following:

```
var CLOSURE_NO_DEPS = true;
var CLOSURE_UNCOMPILED_DEFINES = {
  "goog.ENABLE_DEBUG_LOADER": false
};
```

In rules_closure `closure_js_test()` we use this configuration to run tests via phantomjs. Does anything seem incorrect to you?

However, I did not do the initial setup of `goog.ENABLE_DEBUG_LOADER=false` so my description is likely incomplete. @jart Can you clarify?

**Comment by jart** [comment]
What is whitespacewrapgoogmodules?

**Comment by hochhaus** [comment]
My limited understanding is that [WhitespaceWrapGoogModules](https://github.com/google/closure-compiler/commit/5afe95683b3ed020f7dfed772b7f2eacd332c9fe) is a new pass first included in the v20160517 release of the compiler. The commit message summarizes it:

```
Support for goog.module in WHITESPACE_ONLY mode (new pass).
Does the same handling for goog.module as ClosureBundler. Wraps all
goog.module in a goog.loadModule call. Without this, goog.module cannot
work in whitespace only mode.

New pass "WhitespaceWrapGoogModules" is the only pass within "whitespaceOnlyPasses",
enabled when options.skipNonTranspilationPasses=true.
```

In a nutshell, it wraps `goog.module()` files in calls to `goog.loadModule(...)` when compiling in WHITESPACE_ONLY mode:

```
 +    // As per ClosureBundler:
 +    /*
 +     // add the prefix on the first line so the line numbers aren't affected.
 +     out.append(
 +         "goog.loadModule(function(exports) {"
 +         + "'use strict';");
 +     append(out, Mode.NORMAL, contents);
 +     out.append(
 +         "\n" // terminate any trailing single line comment.
 +         + ";" // terminate any trailing expression.
 +         + "return exports;});\n");
 +     appendSourceUrl(out, Mode.NORMAL);
 +    */
 +
 +    Node block = IR.block();
 +    block.addChildToBack(
 +        IR.exprResult(IR.string("use strict"))); // needs to be explicit, to match ClosureBundler
 +
 +    Node loadMod =
 +        IR.exprResult(
 +                IR.call(
 +                    IR.getprop(IR.name("goog"), IR.string("loadModule")),
 +                    IR.function(IR.name(""), IR.paramList(IR.name("exports")), block)))
 +            .srcrefTree(scriptRoot);
```

**Comment by MatrixFrog** [comment]
It looks like goog.loadModule should be defined if COMPILED=true. Maybe we're failing to set COMPILED to true in whitespace only mode. On the other hand, for some uses of the COMPILED var, you could argue that's the correct behavior: For most code, whitespace-only mode is hardly "compiled"

So, I think we'll probably want to try setting COMPILED=true and see if that breaks anything.

**Comment by hochhaus** [comment]
> It looks like goog.loadModule should be defined if COMPILED=true.

Is that true?

```
goog.DEPENDENCIES_ENABLED = !COMPILED && goog.ENABLE_DEBUG_LOADER;

...

if (goog.DEPENDENCIES_ENABLED) {
  ...
    goog.loadModule = function(moduleDef) { ... };
  ...
}
```

To me it looks like `loadModule()` is only defined when the code is _not_ compiled _and_ `ENABLE_DEBUG_LOADER` is true. When `COMPILED` is true `loadModule()` will _not_ be defined.

What am I missing?

**Comment by MatrixFrog** [comment]
Okay maybe I got it backwards again, sorry. Sometimes `!`s really confuse me to be honest.

Anyway, it's probably safe to move goog.loadModule out of that `if` and guard it by a different condition. But that would be an issue for closure-library (and you probably want to cc @concavelenz on it)

**Comment by hochhaus** [comment]
Thanks for your help @MatrixFrog! No worries about flipping the condition.

I'll open the bug with closure-library shortly.
