### ISSUE TITLE
ES6 imports get rewritten out of order

### ISSUE THREAD

**Issue by jart** [google/closure-compiler#1819]
For example, if I write this:

```javascript
import 'goog:goog.testing.asserts';
import 'goog:goog.testing.jsunit';

import { add } from 'closure/testing/test/arithmetic_es6module';
```

Closure compiler generates the following synthetic code:

```javascript
goog.require("module$closure$testing$test$arithmetic_es6module");
goog.require("goog.testing.jsunit");
goog.require("goog.testing.asserts");
```

Which causes this to happen:

```
closure/testing/test/arithmetic_es6module_test.js:18: ERROR - goog.require() statements are not sorted.
import { add } from 'closure/testing/test/arithmetic_es6module';
^
```

This problem can not be fixed by changing the import order in my code. No matter what order I put my imports in, the error will still happen, because `concat(dependencyInfo.getRequires(), extraRequires)` in `CompilerInput#getDependencyInfo()`.

**Comment by MatrixFrog** [comment]
@Dominator008 any chance you want to take this? It sounds like we might just be updating an 'insertionPoint' var incorrectly, or we need to switch an `insertBefore` to `insertAfter` somewhere.

**Comment by Dominator008** [comment]
@MatrixFrog Done :)
