### ISSUE TITLE
Removal of code that lacks side effects will potentially alter the program behavior

### ISSUE THREAD

**Issue by blickly** [google/closure-compiler#182]
This issue was imported from Closure Compiler's previous home at http://closure-compiler.googlecode.com

The original discussion is archived at:
http://blickly.github.io/closure-compiler-issues/#1185

**Comment by Dominator008** [comment]
The example was:
```js
if (true) {
'' instanceof this;
}
var a = 3;
```
The compiled code will not throw a TypeError.

The behavior is clearly documented at [Compiler Assumptions](https://github.com/google/closure-compiler/wiki/Compiler-Assumptions): "instanceof is assumed to never throw". Closing.
