### ISSUE TITLE
Short term memory leak from static ObjectType.builtinObject

### ISSUE THREAD

**Issue by supersteves** [google/closure-compiler#1822]
After compiling my codebase, 130mb of memory is occupied by the AST nodes reachable from ObjectType.builtinObject -> rawType -> namespaces -> ....  

buildinObject is a static member that is assigned with Compiler instance-related data during compilation.

I run the compiler many times within the same JVM process, but it's not really a problem for me since the next run of the compiler presumably replaces that static property.

But I'm flagging this as a potential issue for other users, and also presumably an unintentionally unsafe approach (from threading and memory perspective).

**Comment by dimvar** [comment]
It is indeed unsafe, but it wasn't unintentional. We took a shortcut.
https://github.com/google/closure-compiler/blob/master/src/com/google/javascript/jscomp/newtypes/ObjectType.java#L74

Leaving the issue open because it'd be good to go back at some point and replace the static fields with instance fields.

**Comment by supersteves** [comment]
Presumably this means it is unsafe to run concurrent compilations in the same JVM?

**Comment by dimvar** [comment]
Yes. It will happen to work if they are all using the same externs for core objects (which should be true in most cases). But we will make it actually safe at some point.

**Comment by supersteves** [comment]
OK - presumably it's just the NTI pass that is affected, so using the compiler for anything else (e.g. parsing) is unaffected? I'm using reflection to erase these fields (non-concurrently with compilation) as part of a test for memory leaks in our wider build process' test suite.

**Comment by dimvar** [comment]
yes, this is NTI specific

**Comment by dimvar** [comment]
Closed by cc1ea4c4a1f67dd637de504d8e96dd5f873e5667
