### ISSUE TITLE
Transpile uses of Promise to ES3 & ES5

### ISSUE THREAD

**Issue by brad4d** [google/closure-compiler#1826]
Adding transpilation support for ES Promise will allow anyone using closure compiler to use standardized ES Promises. No need to use goog.Promise or some other library's implementation. It will also us to also transpile the soon-to-be-standard async functions (issue #1391)

**Comment by brad4d** [comment]
I've just submitted the fix for this within Google.
It should get pushed to github by some time tomorrow.

**Comment by Dominator008** [comment]
Closed by 22bb540d182d8ca9266e36dd952b9e0333b1f4d4.
