### ISSUE TITLE
externs update needed for jQuery 1.12

### ISSUE THREAD

**Issue by brad4d** [google/closure-compiler#1832]
jQuery is pushing everyone to upgrade to at least 1.12.

I found these jQuery 1.12 changes that may affect externs by searching their online API documentation.

jQuery.get([settings]) http://api.jquery.com/jQuery.get/
jQuery.htmlPrefilter(html) http://api.jquery.com/jQuery.htmlPrefilter/
jQuery.post([settings]) http://api.jquery.com/jQuery.post/
jQuery.uniqueSort(array) http://api.jquery.com/jQuery.uniqueSort/

**Comment by brad4d** [comment]
Hi @ChadKillingsworth.
I think this is in your domain.

**Comment by Dominator008** [comment]
Closed by 48c2df076046702f5c38bc4fcead99d10c300c8f in #1410.
