### ISSUE TITLE
Missing extern for angular material mdDialog.prompt()

### ISSUE THREAD

**Issue by ainsleyc** [google/closure-compiler#1833]
I noticed that there isn't currently an extern for angular material dialog's prompt() function. Is this something that is going to be added?

**Comment by ainsleyc** [comment]
Also, I'd be happy to do a pull request to add it if that is appropriate.

**Comment by MatrixFrog** [comment]
Yes, please do, and assign it to @mprobst for review.

**Comment by ainsleyc** [comment]
I've created the pull request, but don't think I have the permissions to assign it?

**Comment by Dominator008** [comment]
Closed by https://github.com/google/closure-compiler/pull/1835.
