### ISSUE TITLE
Compiler error compiling Typescript file to ES3

### ISSUE THREAD

**Issue by getzinj** [google/closure-compiler#1840]
I get the following error doing a compilation:

> 1>  java.lang.RuntimeException: INTERNAL COMPILER ERROR.
> 1>  Please report this problem.
> 1>  
> 1>  insertion point must be a statement: CLASS 5 [source_file: scripts/books/slideType.ts]
> 1>    Node(CLASS): scripts/books/slideType.ts:5:15
> 1>  export default class SlideType {
> 1>    Parent(EXPORT): scripts/books/slideType.ts:5:0
> 1>  export default class SlideType {
> 1>  
> 1>  	at com.google.common.base.Preconditions.checkState(Preconditions.java:199)
> 1>  	at com.google.javascript.jscomp.Es6ToEs3Converter.visitClass(Es6ToEs3Converter.java:546)
> 1>  	at com.google.javascript.jscomp.Es6ToEs3Converter.visit(Es6ToEs3Converter.java:159)
> 1>  	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:623)
> 1>  	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:617)
> 1>  	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:617)
> 1>  	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:617)
> 1>  	at com.google.javascript.jscomp.NodeTraversal.traverse(NodeTraversal.java:297)
> 1>  	at com.google.javascript.jscomp.NodeTraversal.traverseEs6(NodeTraversal.java:564)
> 1>  	at com.google.javascript.jscomp.Es6ToEs3Converter.process(Es6ToEs3Converter.java:99)
> 1>  	at com.google.javascript.jscomp.PhaseOptimizer$NamedPass.process(PhaseOptimizer.java:285)
> 1>  	at com.google.javascript.jscomp.PhaseOptimizer.process(PhaseOptimizer.java:217)
> 1>  	at com.google.javascript.jscomp.Compiler.check(Compiler.java:805)
> 1>  	at com.google.javascript.jscomp.Compiler.compileInternal(Compiler.java:710)
> 1>  	at com.google.javascript.jscomp.Compiler.access$000(Compiler.java:83)
> 1>  	at com.google.javascript.jscomp.Compiler$2.call(Compiler.java:659)
> 1>  	at com.google.javascript.jscomp.Compiler$2.call(Compiler.java:656)
> 1>  	at com.google.javascript.jscomp.CompilerExecutor$2.call(CompilerExecutor.java:93)
> 1>  	at java.util.concurrent.FutureTask.run(Unknown Source)
> 1>  	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
> 1>  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
> 1>  	at java.lang.Thread.run(Unknown Source)
> 1>  Caused by: java.lang.IllegalStateException: insertion point must be a statement: CLASS 5 [source_file: scripts/books/slideType.ts]
> 1>  	... 22 more
> 

slideType.ts is the following:

```
/// <reference path="../../../JeffreyGetzinProtobuffers/Compiled/books.d.ts" />

goog.provide('SlideType');

export default class SlideType {
    title: string;
    isReview: boolean;
    reviewLookupKey: string;
    image: string;
    text: string;
    buyUrl: string;
    quotes: Array <proto.Quote>;
    hasExcerpt: boolean;
    bookIndex: number;
}
```

I invoke the compiler with the following command:

```
java -jar c:\apps\closure\compiler\compiler.jar  ^
--angular_pass=true ^
--entry_point='jhg.website' ^
--common_js_entry_module="jhg.website" ^
--compilation_level=ADVANCED   ^
--debug=true ^
--create_source_map=app-compiled.map  ^
--define goog.DEBUG=true ^
--define goog.log.ENABLED=false ^
--define goog.dom.ASSUME_STANDARDS_MODE=true  ^
--define goog.debug.LOGGING_ENABLED=false ^
--define goog.debug.Logger.ENABLE_HIERARCHY=true ^
--externs=content\scripts\externs\angular-1.4-http-promise_templated.js  ^
--externs=content\scripts\externs\angular-1.4-q_templated.js  ^
--externs=content\scripts\externs\angular1.4.js ^
--externs=content\scripts\externs\angulartics.js ^
--externs=Content\Scripts\third_party\long.js-master\externs\long.js ^
--externs=Content\Scripts\third_party\bytebuffer.js-master\externs\bytebuffer.js ^
--externs=Content\Scripts\third_party\protobuf.js-master\externs\protobuf.js ^
--extra_annotation_name=notypecheck ^
--formatting=pretty-print ^
--generate_exports  ^
--jscomp_warning=accessControls ^
--jscomp_warning=ambiguousFunctionDecl ^
--jscomp_warning=checkEventfulObjectDisposal ^
--jscomp_warning=checkRegExp ^
--jscomp_error=checkTypes ^
--jscomp_warning=checkVars ^
--jscomp_error=closureDepMethodUsageChecks ^
--jscomp_error=conformanceViolations ^
--jscomp_warning=const ^
--jscomp_warning=constantProperty ^
--jscomp_warning=deprecated ^
--jscomp_warning=deprecatedAnnotations ^
--jscomp_error=duplicate ^
--jscomp_warning=duplicateMessage ^
--jscomp_warning=es3 ^
--jscomp_warning=es5Strict ^
--jscomp_warning=externsValidation ^
--jscomp_warning=fileoverviewTags ^
--jscomp_warning=globalThis ^
--jscomp_warning=internetExplorerChecks ^
--jscomp_error=invalidCasts ^
--jscomp_warning=misplacedTypeAnnotation ^
--jscomp_warning=missingGetCssName ^
--jscomp_warning=missingProperties ^
--jscomp_warning=missingProvide ^
--jscomp_warning=missingRequire ^
--jscomp_warning=missingReturn ^
--jscomp_warning=newCheckTypes ^
--jscomp_off=nonStandardJsDocs  ^
--jscomp_warning=suspiciousCode ^
--jscomp_warning=strictModuleDepCheck ^
--jscomp_warning=typeInvalidation ^
--jscomp_warning=undefinedNames ^
--jscomp_warning=undefinedVars ^
--jscomp_warning=unknownDefines ^
--jscomp_warning=useOfGoogBase ^
--jscomp_warning=uselessCode ^
--jscomp_error=violatedModuleDep ^
--jscomp_warning=visibility   ^
--jscomp_warning=newCheckTypes ^
--js_output_file=app-compiled.js ^
--language_in=ECMASCRIPT6_TYPED ^
--language_out=ECMASCRIPT5_STRICT ^
--dependency_mode=STRICT ^
--output_manifest=%outname%.MF ^
--output_module_dependencies=deps.js ^
--output_wrapper="%%output%%//# sourceMappingURL=app-compiled.map" ^
--process_closure_primitives=true  ^
--source_map_format=v3 ^
--summary_detail_level=3 ^
--use_types_for_optimization ^
--warning_level=VERBOSE     ^
--js=C:\Apps\Closure\closure-library-master\closure\goog\   ^
--js=C:\Apps\Closure\closure-templates-for-javascript\soyutils_usegoog.js ^
--js='!**_test.js' ^
--js=..\JeffreyGetzinProtobuffers\Compiled\DEBUG\*.js  ^
--js=C:\Apps\protobuf-master\js\*.js ^
obj\DEBUG\*soy.js ^
scripts\*.js ^
scripts\books\*.js ^
scripts\books\*.ts ^
scripts\books\reviews\*.js ^
scripts\buy\*.js ^
scripts\common\*.js ^
scripts\news\*.js ^
scripts\newsletter\*.js ^
scripts\newsletter\*.ts ^
scripts\readerQuotes\*.js ^
scripts\roguesGallery\*.js ^
scripts\timeline\*.js
```

I'm running this from within Visual Studio 2015 on Windows 10.

   - Jeff the Xoogler

**Comment by getzinj** [comment]
Anybody? Bueller?

**Comment by getzinj** [comment]
Something that strikes me as unusual is that I see the following in the stack track:

```
1> at com.google.javascript.jscomp.Es6ToEs3Converter.visitClass(Es6ToEs3Converter.java:546)
1> at com.google.javascript.jscomp.Es6ToEs3Converter.visit(Es6ToEs3Converter.java:159)
1> at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:623)
```

But I specify in my compile options that the target language is **ES5**.

    Jeff

**Comment by brad4d** [comment]
@MatrixFrog can probably best investigate the source of the compiler exception, but I can point out a few things.

1. Es6toEs3Converter runs for both ES3 and ES5 output. The name is misleading.
2. I don't think it makes sense to use both goog.provide() and an ES6 'export' statement in the same file. I believe it's an either-or sort of thing.
3. ES6 class syntax doesn't allow for member variable definitions, just methods. Although variable declarations are allowed for --language_in=ECMASCRIPT6_TYPED, I still suspect the problem lies somewhere there.

**Comment by getzinj** [comment]
Interesting. When I tried it without the goog.provide, I got an error saying the type wasn't provided. What IS the correct way to mix and match the newer ES6 dependency management older Closure-style?

    Jeff the Xoogler

**Comment by getzinj** [comment]
P.S. Are using the ES3 as a form of intermediate language? Is that why it's so-named?

**Comment by ChadKillingsworth** [comment]
ES6 module rewriting will bail on any script that has a goog.provide. See the [modules documentation](https://github.com/google/closure-compiler/wiki/JS-Modules). A module may only have a single type of export statement: Closure's `goog.provide` or `goog.module`,  CommonJS `module.exports` or `export` or ES6 `export`. You can freely mix import statements however.

So at that point, you have managed to escape ES6 content to passes of the compiler that do not yet understand ES6 syntax. Hence the crash - which is expected.

While we could warn about this, I'd rather spend time working on getting the simple mode passes to understand ES6 without transpilation.
