### ISSUE TITLE
java.lang.NoSuchMethodError: com.google.javascript.rhino.Node.getType()

### ISSUE THREAD

**Issue by vobruba-martin** [google/closure-compiler#1845]
My script stopped working after this commit 62f4c44590dc4c80315f399cfdc2e7ae1ef141b3 with error:

> 0 error(s), 0 warning(s)
> java.lang.NoSuchMethodError: com.google.javascript.rhino.Node.getType()Lcom/google/javascript/rhino/Token$Kind;
> 	at com.google.javascript.jscomp.PrepareAst$PrepareAnnotations.visit(PrepareAst.java:120)
> 	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:623)
> 	at com.google.javascript.jscomp.NodeTraversal.traverseFunction(NodeTraversal.java:634)
> 	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:607)
> 	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:617)
> 	at com.google.javascript.jscomp.NodeTraversal.traverse(NodeTraversal.java:297)
> 	at com.google.javascript.jscomp.NodeTraversal.traverseEs6(NodeTraversal.java:564)
> 	at com.google.javascript.jscomp.PrepareAst.process(PrepareAst.java:67)
> 	at com.google.javascript.jscomp.Compiler.prepareAst(Compiler.java:2028)
> 	at com.google.javascript.jscomp.JsAst.parse(JsAst.java:175)
> 	at com.google.javascript.jscomp.JsAst.getAstRoot(JsAst.java:53)
> 	at com.google.javascript.jscomp.CompilerInput.getAstRoot(CompilerInput.java:116)
> 	at com.google.javascript.jscomp.Compiler.parseInputs(Compiler.java:1370)
> 	at com.google.javascript.jscomp.Compiler.parse(Compiler.java:746)
> 	at com.google.javascript.jscomp.Compiler.compileInternal(Compiler.java:703)
> 	at com.google.javascript.jscomp.Compiler.access$000(Compiler.java:83)
> 	at com.google.javascript.jscomp.Compiler$2.call(Compiler.java:670)
> 	at com.google.javascript.jscomp.Compiler$2.call(Compiler.java:667)
> 	at com.google.javascript.jscomp.CompilerExecutor$2.call(CompilerExecutor.java:93)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> 	at java.lang.Thread.run(Thread.java:745)

Params:

> 	--js ... \
> 	--externs ... \
> 	--define="..." \
> 	--assume_function_wrapper \
> 	--create_renaming_reports \
> 	--create_source_map '%outname%.map' \
> 	--compilation_level ADVANCED \
> 	--js_output_file ... \
> 	--language_in ECMASCRIPT5_STRICT \
> 	--language_out ECMASCRIPT5_STRICT \
> 	--new_type_inf \
> 	--output_wrapper '(function(){%output%})()' \
> 	--source_map_format V3 \
> 	--summary_detail_level 3 \
> 	--use_types_for_optimization \
> 	--warning_level VERBOSE \
>

**Comment by blickly** [comment]
It looks like PrepareAst.java hasn't been recompiled since before that change. I think you'll need to recompile your java code.

**Comment by ChadKillingsworth** [comment]
Are you using the ant build? I've not ever had this happen with maven.

**Comment by vobruba-martin** [comment]
Thank you! `ant clean && ant jar` did the trick
