### ISSUE TITLE
Duplicate licenses within a single input file are still emitted

### ISSUE THREAD

**Issue by jbms** [google/closure-compiler#1848]
If the same "@license" text is contained in two separate input files, only a single copy will be written to the output.  However, if the same "@license" text is contained multiple times in the same input file, as can happen if the compiler is being run on output from another tool such as webpack that itself combines multiple files, then duplicate copies are emitted.

From investigating the source code, it seems that the problem is that all of the license texts for each input file are combined into a single string while loading, which prevents de-duplicating them later.  Instead, it would be better to store the license texts as a list of strings per file, so that they may be de-duplicated when emitting.

**Comment by Dominator008** [comment]
Are you interested in coming up with a PR for this?

**Comment by alexeagle** [comment]
This affects Angular as well, I'll send a PR.
