### ISSUE TITLE
Object.assign should be transpiled when language out is ES5

### ISSUE THREAD

**Issue by marcfallows** [google/closure-compiler#1853]
If I compile code with the language_in as ES6 and language_out as ES5 then `Object.assign` should undergo transpilation since the feature is not available in the ES5 spec.

**Comment by getzinj** [comment]
Maybe it uses a polyfill?

 

   Jeff

**Comment by dimvar** [comment]
This is a polyfill, defined here:
https://github.com/google/closure-compiler/blob/master/src/com/google/javascript/jscomp/js/es6/object.js#L34

To use the polyfilles, pass the flag `--rewrite_polyfills`.

**Comment by marcfallows** [comment]
Thanks @dimvar, I wasn't aware that this was a flag and just assumed it would be default behaviour. This addresses my issue completely.
