### ISSUE TITLE
NTI: Truthiness check discards unknown-ness

### ISSUE THREAD

**Issue by SLaks** [google/closure-compiler#1857]
```js
function f(x) {
  if (!x) return null;
  return /** @type {number} */ (x);
}
```

```js
input0:3: WARNING - invalid cast - the types do not have a common subtype
from: truthy
to  : number
  return /** @type {number} */ (x);
                               ^
```

https://closure-compiler-debugger.appspot.com/#input0%3Dfunction%2520f(x)%2520%257B%250A%2520%2520if%2520(!x)%2520return%2520null%253B%250A%2520%2520return%2520%252F**%2520%2540type%2520%257Bnumber%257D%2520*%252F%2520(x)%253B%250A%257D%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES%3D1%26CHECK_TYPES_NEW_INFERENCE%3D1%26CLOSURE_PASS%3D1%26LANG_IN_IS_ES6%3D1%26MISSING_PROPERTIES%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1%26TRANSPILE%3D1

The `if()` check that narrows it to truthy discards the possibility of any other type.
You ought to narrow it to a "non-falsy unknown" type.

**Comment by SLaks** [comment]
This is still broken for `instanceof`:

```js
function f(x) {
  if (!x) return null;
  return x instanceof Array;
}
```

```js
javascript/apps/fava/debug/debugservice.js:80: ERROR - Invalid type(s) for operator INSTANCEOF.
Expected : an object or a union type that includes an object
Found    : truthy

  return x instanceof Array;
         ^
```

(from a build that includes the fix)

**Comment by SLaks** [comment]
And for method type inference:

```js
function f(x) {
  if (!x) return null;
  forEach(x, y => {});
}

/**
 * @param {!Array<T>} arr
 * @param {function(T)} cb
 * @template T
 */
function forEach(arr, cb) {}
```

```js
ERROR - Could not instantiate type Array<T> with truthy.
  forEach(x, y => {});
          ^
```

**Comment by Dominator008** [comment]
Closed by https://github.com/google/closure-compiler/commit/cdf064187bd660fad4b5b65b12be5e2a043779eb
