### ISSUE TITLE
NTI: Overriding re-specified template parameters cause spurious type mismatch error

### ISSUE THREAD

**Issue by SLaks** [google/closure-compiler#1859]
``` js
/** @interface */
function Interface1(){}

/** @param {T} x @return {T} @template T */
Interface1.prototype.func;


/** @interface @extends {Interface1} */
function Interface2() {}


/** @constructor @implements {Interface1} */
function Class1() {}

/** @override @param {T} x @return {T} @template T */
Class1.prototype.func;


/** @constructor @extends {Class1} @implements {Interface2} */
function Class2() {}


/** @override */
Class2.prototype.func = function(x) { return x; };
```

``` js
ERROR - Interface Class2 has a property func with incompatible types in its super interfaces: [function(this:Class1,T):T, function(this:Interface1,T):T]
Class2.prototype.func = function(x) { return ''; };
```

Removing the duplicate specification in the `Class1` override fixes.  This works fine in OTI.

It looks like the compiler doesn't realize that the two declared `@template T`s are equivalent.  (template parameters should be compared by index)

No demo link, because the debugger is down :(

**Comment by SLaks** [comment]
Debugger is back up!

https://closure-compiler-debugger.appspot.com/#input0%3D%252F**%2520%2540interface%2520*%252F%250Afunction%2520Interface1()%257B%257D%250A%250A%252F**%2520%2540param%2520%257BT%257D%2520x%2520%2540return%2520%257BT%257D%2520%2540template%2520T%2520*%252F%250AInterface1.prototype.func%253B%250A%250A%250A%252F**%2520%2540interface%2520%2540extends%2520%257BInterface1%257D%2520*%252F%250Afunction%2520Interface2()%2520%257B%257D%250A%250A%250A%252F**%2520%2540constructor%2520%2540implements%2520%257BInterface1%257D%2520*%252F%250Afunction%2520Class1()%2520%257B%257D%250A%250A%252F**%2520%2540override%2520%2540param%2520%257BT%257D%2520x%2520%2540return%2520%257BT%257D%2520%2540template%2520T%2520*%252F%250AClass1.prototype.func%253B%250A%250A%250A%252F**%2520%2540constructor%2520%2540extends%2520%257BClass1%257D%2520%2540implements%2520%257BInterface2%257D%2520*%252F%250Afunction%2520Class2()%2520%257B%257D%250A%250A%250A%252F**%2520%2540override%2520*%252F%250AClass2.prototype.func%2520%253D%2520function(x)%2520%257B%2520return%2520x%253B%2520%257D%253B%250A%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES%3D1%26CHECK_TYPES_NEW_INFERENCE%3D1%26CLOSURE_PASS%3D1%26LANG_IN_IS_ES6%3D1%26MISSING_PROPERTIES%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1%26TRANSPILE%3D1

**Comment by realityforge** [comment]
@EatingW NTI was dropped so this issue should be able to be closed

**Comment by EatingW** [comment]
Thanks!
