### ISSUE TITLE
NTI: IObject<> isn't usable for simple maps

### ISSUE THREAD

**Issue by SLaks** [google/closure-compiler#1860]
```js
const /** IObject<number, string> */ x = {};
```

```js
input0:1: WARNING - The right side in the assignment is not a subtype of the left side.
Expected : IObject<number,string>|null
Found    : Object

const /** IObject<number, string> */ x = {};
                                         ^
```

https://closure-compiler-debugger.appspot.com/#input0%3Dconst%2520%252F**%2520IObject%253Cnumber%252C%2520string%253E%2520*%252F%2520x%2520%253D%2520%257B%257D%253B%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES%3D1%26CHECK_TYPES_NEW_INFERENCE%3D1%26CLOSURE_PASS%3D1%26LANG_IN_IS_ES6%3D1%26MISSING_PROPERTIES%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1%26TRANSPILE%3D1

**Comment by SLaks** [comment]
Actually, this doesn't work in OTI either.

What is `IObject<>` meant for?

**Comment by shicks** [comment]
My understanding is that the only reason IObject exists is to support type-checking getelem accesses for Arrays, in which IArrayLike<T> is IObject<number, T>; whereas Object<T> is IObject<string, T>.  So yes, as far as I understand it's entire purpose is as a base type.  Is there a reason you want to use it explicitly?

**Comment by SLaks** [comment]
Even so, `{}` should be convertible to it (just like `[]` is convertible to `IArrayLike<>`).

But, more importantly,

> Now, with `IObject` and ES6 maps, special-casing `Object` to be generic is not necessary, and NTI does not support it.

[src](https://github.com/google/closure-compiler/wiki/Using-NTI-(new-type-inference)#no-support-for-parameterized-objectkv)

**Comment by dimvar** [comment]
Yes, IObject is a non-hacky version of parameterized Object. The behavior you're requesting for {} is correct. I'll fix for NTI.

**Comment by SLaks** [comment]
Can you please fix it for OTI too?
Without that, it will be impossible to migrate the Google codebase to NTI, since the same code (that uses `Object<>` all over the place) must still compile under OTI too.

Once they both work, we can mass-replace `Object<` to `IObject<`

**Comment by dimvar** [comment]
We are generally not fixing OTI bugs unless they're crashes or very high priority. If this one is easy to fix in OTI, I'll take a shot, but no promises.

> we can mass-replace `Object<` to `IObject<`

There are no plans for this. Besides the bug here, they have different typing rules (Object is looser), so the mass migration won't be automatable.

**Comment by dimvar** [comment]
Fix for NTI will be pushed later today.

**Comment by SLaks** [comment]
Can you fix this in OTI?
