### ISSUE TITLE
--new_type_inf --strict doesn't elevate warnings to errors

### ISSUE THREAD

**Issue by icmdaf** [google/closure-compiler#1862]
For example this generates "WARNING - Type annotation references non-existent type Foo."
`/** @type {!Foo} */ var foo = null;` when using `--new_type_inf`.
But adding `--strict` will not elevate it to error, it remains a warning.
When not using `--new_type_inf`, warnings to become errors as expected.

**Comment by dimvar** [comment]
Can you file a bug in the internal bug tracker? `--strict` is not available externally. As a workaround, if you add `--jscomp_error=checkTypes` instead of `--strict`, the warning gets promoted to an error as expected.
