### ISSUE TITLE
WARNING - optional arguments must be at the end

### ISSUE THREAD

**Issue by WillsB3** [google/closure-compiler#1864]
I have this code (where myProject is a censored project name).

```javascript
/**
 * Scroll an element to the supplied x and y co-ordinates.
 *
 * @param {Element} scrollElement The element to scroll.
 * @param {number=} opt_left The horizontal coordinate to scroll to.
 * @param {number=} opt_top The vertical coordinate to scroll to.
 * @param {number=} opt_duration The duration of the scroll animation, in ms.
 * @param {function=} opt_callback A callback to run once the scroll ends.
 */
myProject.utils.scroll.toCoords = function(scrollElement, opt_left, opt_top,
    opt_duration, opt_callback) {

  ...do things...
};
```

`gjslint --strict` reports no linting errors, yet when trying to compile I receive an error:

```
Error: source/2016/js/utils/scroll.js:73: WARNING - optional arguments must be at the end
myProject.utils.scroll.toCoords = function(scrollElement, opt_left, opt_top,
```

The optional arguments are at the end...

Have I made a mistake or is this a bug? I've tried with with both `20151216.0.0` and `20160619.0.0`.

**Comment by dimvar** [comment]
The type of opt_callback is malformed, which causes the type parser to miss the optionality of the argument. Either change the type to `function()=` or `Function=`, not sure which one you meant.

**Comment by WillsB3** [comment]
@dimvar Thank you - that was it.

For anyone else that hits the issue, there is some useful documentation in [Closure: The Definitive Guide](https://books.google.co.uk/books?id=p7uyWPcVGZsC&lpg=PA29&dq=The%20use%20of%20wrapper%20%22types%20is%20prohibited%22%20in%20the%20Closure%20Library&pg=PA31#v=onepage&q=The%20use%20of%20wrapper%20%22types%20is%20prohibited%22%20in%20the%20Closure%20Library&f=false), Page 31 under "Function Types".
