### ISSUE TITLE
--new_type_inf fails to check nullness

### ISSUE THREAD

**Issue by rubenlg** [google/closure-compiler#1865]
/** @constructor @struct */
function Klass() {
  /** @type {number} */
  this.val = 1.0;
}

/** @return {Klass} */
function getNullable() {
  return new Klass();
}

/** @type {Klass} */
var best = null;

for (var i = 0; i < 5; i++) {
  var current = getNullable();
  if (best === null) {
    best = current;
  } else if (current !== null && current.val > best.val) {
    best = current;
  }
}

=================
closure-compiler --compilation_level ADVANCED  --new_type_inf test.js 
test.js:20: WARNING - Cannot access property val of non-object type null.
  } else if (current !== null && current.val > best.val) {

Note that best is known to be non null because this is the "else" branch, and there is code changing it during the loop.

**Comment by dimvar** [comment]
This is a known limitation of NTI. Basically, we don't analyze loops to a fixpoint, because types are generally stable inside loops. It's as if every loop is run either 0 or 1 times. The workaround is to change the initial assignment to
`var best = /** @type {Klass} */ (null);`
