### ISSUE TITLE
Curious behavior with obfuscation

### ISSUE THREAD

**Issue by zarov** [google/closure-compiler#1869]
Hello, I noticed a curious behavior with obfuscation for one method (I don't know if it occurs somewhere else in my code). So I have the following code : 

````js
/**
 * @method NS.Math.Quaternion.slerpNoInvert
 * @param {THREE.Quaternion} q0
 * @param {THREE.Quaternion} q1
 * @param {Number} t
 * @return {THREE.Quaternion}
 */
NS.Math.Quaternion.slerpNoInvert = function(q0, q1, t) {
  // do basic mathematical operations
  return result;
};


/**
 * @method NS.Math.Quaternion.squadNoInvert
 * @param {THREE.Quaternion} q0
 * @param {THREE.Quaternion} a0
 * @param {THREE.Quaternion} a1
 * @param {THREE.Quaternion} q1
 * @param {Number} t
 * @return {THREE.Quaternion}
 */
NS.Math.Quaternion.squadNoInvert = function(q0, a0, a1, q1, t) {
    var qq = NS.Math.Quaternion.slerpNoInvert(q0, q1, t);
    var qa = NS.Math.Quaternion.slerpNoInvert(a0, a1, t);
    return NS.Math.Quaternion.slerpNoInvert(qq, qa, 2 * t * (1-t));
};
````

What happened when I compile the code is that I obtain this : 
````js
f.Math.Quaternion.slerpNoInvert = function(a, b, c)
{
    return result
};
f.Math.Quaternion.squadNoInvert = function(a, b, c, d, g)
{
    a = f.Math.Quaternion.Pi(a, d, g);
    b = f.Math.Quaternion.Pi(b, c, g);
    return f.Math.Quaternion.slerpNoInvert(a, b, 2 * g * (1 - g))
};
````

Notice the difference between the first two call of `slerpNoInvert` versus the last one. Do you have any idea why it would be like this ? I always reach an understatement about this compiler, but here I have not a single clue.

My option are :
````
externs: three.js.externs
compilation_level: ADVANCED_OPTIMIZATIONS
warning_level: VERBOSE
language_in: ECMASCRIPT5
create_source_map: 'build.min.js.map
jscomp_off: checkTypes
````

NB: I couldn't find a simple case to reproduce it, I'll try to find one.

**Comment by dimvar** [comment]
We can't reproduce this without a standalone program to build.

Since you're turning off type checking, one thing you can try is `--use_types_for_optimization=false`. FYI, it is recommended to have type checking on when using advanced mode.
