### ISSUE TITLE
JSCOMPILER_PRESERVE error

### ISSUE THREAD

**Issue by supersteves** [google/closure-compiler#1875]
When running the compiler in checks-only mode, optimisations don't run. "Protect hidden side effects" might be configured to run, but "strip protection" isn't because it's in the optimisations. 

This means the temporary injection of JSCOMPILER_PRESERVE doesn't get stripped, and you get a runtime error.

The workaround is to turn off "protect hidden side effects" but to lose that protection.

I think the strip pass should not be considered an optimisation but a same-time-as-optimisations pass controlled by whatever defines whether the protect pass should run.

See another user's case of this (admittedly old): http://stackoverflow.com/questions/26665571/jscompiler-preserve-after-compiling-javascript-with-kjscompiler

**Comment by a701440** [comment]
Running into the same issue with SIMPLE_OPTIMIZATIONS level.
Mostly a problem with code in loops like this:

var i=0;
var cnt=10;
for (i; i<cnt;i++) {...}

In this case JSCOMPILER_PRESERVE(i) is not removed from the minified output.

**Comment by MatrixFrog** [comment]
Or we could just inject `var JSCOMPILER_PRESERVE = function() {}` somewhere near the beginning of the output.

**Comment by blickly** [comment]
I don't think it should be hard to avoid the protection in checks_only mode.

**Comment by supersteves** [comment]
👍 thanks!
