### ISSUE TITLE
Error on extended class

### ISSUE THREAD

**Issue by 2beers** [google/closure-compiler#1876]
The following js code from mozilla classes documentation https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes returns an error:

> SEVERE: main.js:14: ERROR - The class in an extends clause must be a qualified name.
> class Bar extends CalculatorMixin(RandomizerMixin(Foo)) { }

Here is the code I used:

```
var CalculatorMixin = Base => class extends Base {
  calc() {
  	console.log("calc");
  }
};

var RandomizerMixin = Base => class extends Base {
  randomize() {
  	console.log("randomize");
  }
};

class Foo { }
class Bar extends CalculatorMixin(RandomizerMixin(Foo)) { }

var bar=new Bar();
bar.randomize();
```

**Comment by MatrixFrog** [comment]
For transpilation, we only support patterns that we can analyze and typecheck, which is the reason for this restriction. Eventually the compiler will support ES6 "natively" (without transpiling down) and then this pattern might work (but will probably still be difficult to typecheck)
