### ISSUE TITLE
Optimization for empty functions

### ISSUE THREAD

**Issue by WhiteTrashLord** [google/closure-compiler#1884]
Sorry I am not a compiler expert. I just compiled some code with the ADVANCED_OPTIMIZATIONS level. I noticed that the Closure Compiler generated a lot of this code:

function da(){}function r(){}function ea(){}function t(){}function fa(){}function u(){}

Maybe it's possible to detect an empty function and use only 1 function for all empty functions in the code?

**Comment by concavelenz** [comment]
CompilerOptions#setRewriteFunctionExpressions is used to use a factory to create common functions but it isn't great for performance.  In the general case, you don't know when a function is going to have properties add it to.    

AddProp(da);

function AddProp(fn) {
  fn.prop = 1;
}

If empty functions that are not escaped are common in your code base, you may want to consider a custom compiler pass.

Feel free to discuss this on the mailing list.
