### ISSUE TITLE
Extending Error results in a broken subclass

### ISSUE THREAD

**Issue by shicks** [google/closure-compiler#1885]
If I transpile the following:

``` js
class FooError extends Error {}
throw new FooError('xyz');
```

I end up with

``` js
var $jscomp = {
  scope: {},
  getGlobal: function(a) {
    return "undefined" != typeof window && window === a ? a :
        "undefined" != typeof global ? global : a
  }
};
$jscomp.global = $jscomp.getGlobal(this);
$jscomp.inherits = function(a, b) {
  function c() {}
  c.prototype = b.prototype;
  a.prototype = new c;
  a.prototype.constructor = a;
  for (var d in b)
    if ($jscomp.global.Object.defineProperties) {
      var e = $jscomp.global.Object.getOwnPropertyDescriptor(b, d);
      e && $jscomp.global.Object.defineProperty(a, d, e)
    } else a[d] = b[d]
};
var FooError = function(a) {
  Error.apply(this, arguments)
};
$jscomp.inherits(FooError, Error);
FooError.captureStackTrace = Error.captureStackTrace;
throw new FooError("xyz");
```

But if you run this, you find that the error that's thrown has no message.  This seems to be due to the fact that `Error.apply` creates a new error.  There's [discussion on MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error) about how to "subclass" error, but the short of it seems to be that it needs special handling.

The native ES6 code does work correctly.

**Comment by MatrixFrog** [comment]
Is it just `Error` that is special, or other functions (like `Object`) that can be called either as a normal function or as a constructor? I suppose I don't mind making a special exception just for `Error` although it is definitely awkward.

**Comment by ChadKillingsworth** [comment]
Error is special.

**Comment by MatrixFrog** [comment]
So I guess we can generate a synthetic constructor like `constructor(message) { super(message); this.message = message; }` or something. But only if the user hasn't supplied one. If the user has supplied one then we need to add `this.message = message;` at the beginning of the one they gave us. This seems fragile; any better ideas? (I took a quick look at what Babel does, it looks like their use of `Object.create` might be making this a non-issue for them, but we can't do that without dropping IE8 support.)

**Comment by concavelenz** [comment]
You can't call the constructor from the subclass unless you call "new":

var self = new Error();

which might woek for ES6 classes if we handled all the ES6 classes this way but then you run into other problems (call subclass overriden methods that would normally be on the prototype).

**Comment by shicks** [comment]
This seems to have been fixed somewhere along the way.
