### ISSUE TITLE
Compiler crash on redefining a function inside the same function

### ISSUE THREAD

**Issue by blickly** [google/closure-compiler#189]
This issue was imported from Closure Compiler's previous home at http://closure-compiler.googlecode.com

The original discussion is archived at:
http://blickly.github.io/closure-compiler-issues/#1174

**Comment by Dominator008** [comment]
Can't reproduce crash with given code
`function x_68() {
  function x_68() {
    x_77: ;
  }
  ({839:Object(), 14:true[x_68()]()});
}`
, closing.
