### ISSUE TITLE
Support sourcesContent for sourcemaps

### ISSUE THREAD

**Issue by danielcompton** [google/closure-compiler#1890]
It is often handy to have all of the sources for an application in the source mapping file for ease of manipulation, upload, e.t.c. It would be great if the closure-compiler supported `sourcesContent` in source maps. Apologies if it does already, I couldn't find any docs or source on it.

**Comment by MatrixFrog** [comment]
We don't. It's just JSON so you can tack the sourcesContent onto the source map that the compiler produces, pretty easily, using any language with a JSON parser. But I agree it would be better if the compiler (optionally) just did this for you; it makes things a lot easier.

**Comment by ChadKillingsworth** [comment]
There are a lot of variations with sourcemaps (like creating a composed sourcemap or not). We've historically left this for post processing.

This is quite easy when using the [gulp-sourcemaps plugin](https://www.npmjs.com/package/gulp-sourcemaps).

**Comment by danielcompton** [comment]
Gotcha. This would be used from ClojureScript, so I'd prefer not to introduce gulp into the toolchain, but it's good to know. I'll look into that. Thanks!

**Comment by shicks** [comment]
This is actually something I was working on earlier this week.  I'm hoping to land it next week.

**Comment by phistuck** [comment]
The Chromium project would also find it handy in order to incorporate Closure Compiler in more than just its Developer Tools feature.
See -
https://groups.google.com/a/chromium.org/d/msg/chromium-dev/fgc2dfRvjsQ/vKgtteyGDAAJ

**Comment by shicks** [comment]
This is mostly implemented. I think it only lacks a command-line option to enable it. I forget what option it's behind, but IIRC it's checked near the bottom of `Compiler.java`, so feel free to send a PR exposing it to `CommandLineRunner`.

**Comment by danielcompton** [comment]
This is the commit https://github.com/google/closure-compiler/commit/c64418fd5518bb60aeb6a627d2bcc46a3d4be788.

and these are the options: https://github.com/google/closure-compiler/blob/c64418fd5518bb60aeb6a627d2bcc46a3d4be788/src/com/google/javascript/jscomp/Compiler.java#L2740-L2752

Would the command line option be something like:

`--source_map_include_sources_content`?

**Comment by lwhorton** [comment]
I bumped into this today and was wondering if anyone could clarify on the command line option @danielcompton mentioned above?

**Comment by jart** [comment]
The TypeScript compiler has an option called `--inlineSourceMap --inlineSources` and it makes source maps guaranteed to work perfectly without much fuss. It might be nice if the Closure Compiler supported this.

Working on Bazel Closure Rules I have to say that it's been really difficult for me to think of a way to auto-configure the `--source_map_location_mapping` flag and make runfiles / data files able to provide raw sources in expected locations, which will be easy for the user to map to web server paths that correspond to the generated source map. I guess what makes this nontrivial is that the user needs to make sure those sources on the web server don't end up being publicly accessible in production.

Having a flag that allows the user to compile a separate debug closure_js_binary that has the sources and sourcemap baked into the compiled js file would make life so much easier.

**Comment by jart** [comment]
Oh wait, I failed to read @shicks' comment. It seems I can just enable this via the Java API for Closure Rules. Fabulous.

**Comment by codecrackerx9** [comment]
This is included in the 20170218.0.0 release as `--source_map_include_content`.

**Comment by ChadKillingsworth** [comment]
Someday MOE will merge PRs correctly and auto-close issues ...
