### ISSUE TITLE
Advanced Mode Compilation For TypeScript Namespaces

### ISSUE THREAD

**Issue by pspeter3** [google/closure-compiler#1894]
TypeScript has a namespace feature which generates fairly simple code that the Closure Compiler seems to not optimize how I would expect.
###### `math_helpers.ts`

``` ts
namespace MathHelpers {
  export add(x: number, y: number): number {
    return x + y;
  }

  export sub(x: number, y: number): number {
    return x - y;
  }
}

export { MathHelpers };
```
###### `math_helpers.js`

``` js
var MathHelpers;
(function (MathHelpers) {
    function add(x, y) {
        return x + y;
    }
    MathHelpers.add = add;
    function sub(x, y) {
        return x - y;
    }
    MathHelpers.sub = sub;
})(MathHelpers || (MathHelpers = {}));

export { MathHelpers };
```
###### `root.js`

``` js
import { MathHelpers } from "./math_helpers";

console.log(MathHelpers.add(3, 4));
```
###### `actual`

``` js
'use strict';var a;(function(d){d.add=function(b,c){return b+c};d.sub=function(b,c){return b-c}})(a||(a={}));console.log(a.add(3,4));
```
###### `expected`

``` js
'use strict';console.log(7);
```

**Comment by dimvar** [comment]
@mprobst @evmar how do you deal with this? Do you preprocess and inline such code before passing on the compiler? I remember discussing this pattern before but I don't remember what the resolution was.

**Comment by evmar** [comment]
We "solved" this by disallowing use of namespace in google3 code.

I have some more examples of troublesome TypeScript patterns on this bug:
https://github.com/angular/tsickle/issues/132

**Comment by evmar** [comment]
PS: on the example in this bug in particular, the code is bad TypeScript (this pattern is explicitly called out in the TypeScript docs on how to use namespaces).  ES6 modules are themselves namespaces already so you don't need to introduce another.

Instead write:

```javascript
  export function add(x: number, y: number): number {
    return x + y;
  }

  export function sub(x: number, y: number): number {
    return x - y;
  }
```

The user of this then needs to use
```javascript
import * as MathHelpers from './MathHelpers'
```
instead of
```javascript
import MathHelpers from './MathHelpers'
```

**Comment by evmar** [comment]
(See "Needless Namespacing" at https://www.typescriptlang.org/docs/handbook/namespaces-and-modules.html .  However, this doesn't solve the larger problem of how namespaces and Closure compiler interact.)

**Comment by pspeter3** [comment]
If we use the `import *` syntax, will the Closure Compiler tree shake appropriately?

**Comment by pspeter3** [comment]
We were experimenting with namespaces under the assumption that `import *` was bad for minification

**Comment by ChadKillingsworth** [comment]
That particular code pattern has long been problematic. The biggest sticking point is the IIFE wrapper and the fact that type information is lost with it.

**Comment by pspeter3** [comment]
It seems like `import *` does the correct thing. I still think this issue is academically interesting but my issue is resolved.

**Comment by evmar** [comment]
The rewrite I suggested works around the problem one level of namespacing, but multiple levels of namespacing still introduce the IIFE.  However, perhaps that isn't Closure compiler's problem (the generated code is a pattern that is hard for it to understand).

**Comment by Dominator008** [comment]
I think nested namespaces should be flattened out into a form Closure Compiler is more used to. See https://github.com/google/closure-compiler/blob/master/test/com/google/javascript/jscomp/Es6TypedToEs6ConverterTest.java#L512 for examples.

**Comment by evmar** [comment]
I think the fix for this is https://github.com/angular/tsickle/issues/132 , and can be closed here.

**Comment by brad4d** [comment]
Agreed
