### ISSUE TITLE
generator transpilation: deeply nested variable declarations not handled correctly

### ISSUE THREAD

**Issue by JdeH** [google/closure-compiler#1895]
Hi,

Thanks for a great tool that saves me a lot of work!
I am using Closure v20160713 to minify autogenerated JS code.
It is started up by the [Transcrypt](http://www.transcrypt.org) Python to JS compiler with the options given below (javaScriptVersion == 6):

``` python
import os
import subprocess

from org.transcrypt import utils

closureCompilerPath = '{}/closure_compiler/compiler.jar'.format (os.path.dirname (os.path.abspath (__file__)) .replace ('\\', '/'))

def run (sourcePath, targetPath, postMapPath, javaScriptVersion):
    params = [
        'java', '-jar',
        closureCompilerPath,
        '--language_in=ES{}'.format (javaScriptVersion),
        '--language_out=ECMASCRIPT5_STRICT',
        '--compilation_level', 'SIMPLE_OPTIMIZATIONS',
        '--js', sourcePath,
        '--js_output_file', targetPath
    ]

    if utils.commandArgs.map:
        params += [
            '--create_source_map', postMapPath,
            '--source_map_format=V3'
        ]

    subprocess.run (params)
```

Function 'accumulate' (part of Python 3.5 itertools module) works correctly in Chrome without using Closure to minify, but doesn't work if minified by Closure.

**The value of variable  'sum' is forgotten after the yield.**

No error report or warning is given.

``` js
var accumulate = function* (iterable, func) {
    let first = true;
    if (func) {
        for (let item of iterable) {
            if (first) {
                var sum = item;
                first = false;
            }
            else {
                sum = func (sum, item);
            }
            yield sum;
        }
    }
    else {
        for (let item of iterable) {
            if (first) {
                var sum = item;
                first = false;
            }
            else {
                sum = sum + item;
            }
            yield sum;
        }
    }
}
```

Manually hoising variable 'sum' circumvents the problem:

``` js
var accumulate = function* (iterable, func) {
    let sum;
    let first = true;
    if (func) {
        for (let item of iterable) {
            if (first) {
                sum = item;
                first = false;
            }
            else {
                sum = func (sum, item);
            }
            yield sum;
        }
    }
    else {
        for (let item of iterable) {
            if (first) {
                sum = item;
                first = false;
            }
            else {
                sum = sum + item;
            }
            yield sum;
        }
    }
}
```

**Comment by brad4d** [comment]
https://github.com/google/closure-compiler/blob/master/src/com/google/javascript/jscomp/Es6RewriteGenerators.java#L318

I think the trouble is that none of the methods called by translateStatementInOriginalBody() check for child var statements.

**Comment by MatrixFrog** [comment]
Might be easiest to first move all hoisted vars to the top of the generator as a preprocessing step. Or if we want to be a little more extreme, disallow `var` inside of generators :)

**Comment by brad4d** [comment]
That sounds about right.
To be safe, I think we'll need to create top-level var declarations for all variables in the function, with unique generated names for any 'let' or 'const' variables in case the same name is declared in multiple code blocks.

**Comment by MatrixFrog** [comment]
We already unique-ify names of let/const variables. Not sure if any further uniquification is necessary. cc @matthewloring who did the original generator transpilation work.

**Comment by concavelenz** [comment]
I think hoisting "var" declarations in generator functions should be safe.  We should also verify that hoisted functions are handled correctly.

**Comment by brad4d** [comment]
@MatrixFrog is working on a change that will likely fix this problem.

Here's a simplified repro.

```javascript
function* f(n) {
  for (let i = 0; i < n; ++i) {
    if (i == 0) {
      var sum = 0;
    } else {
      sum += i;
    }
    yield i;
  }
  return sum;
}
```

https://closure-compiler-debugger.appspot.com/#input0%3Dfunction*%2520f(n)%2520%257B%250A%2520%2520for%2520(let%2520i%2520%253D%25200%253B%2520i%2520%253C%2520n%253B%2520%252B%252Bi)%2520%257B%250A%2520%2520%2520%2520if%2520(i%2520%253D%253D%25200)%2520%257B%250A%2520%2520%2520%2520%2520%2520var%2520sum%2520%253D%25200%253B%250A%2520%2520%2520%2520%257D%2520else%2520%257B%250A%2520%2520%2520%2520%2520%2520sum%2520%252B%253D%2520i%253B%250A%2520%2520%2520%2520%257D%250A%2520%2520%2520%2520yield%2520i%253B%250A%2520%2520%257D%250A%2520%2520return%2520sum%253B%250A%257D%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26MISSING_PROPERTIES%3D1%26TRANSPILE%3D1%26CHECK_TYPES%3D1%26CLOSURE_PASS%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1

**Comment by brad4d** [comment]
@MatrixFrog is close to submitting his change, but I don't think it's going to fix this after all.
His hoisting occurs in the normalize pass, which happens after transpilation of generator functions.

Probably the quickest fix for this would be to do explicit hoisting within the generator transpilation pass.
This isn't high priority relative to other stuff, though, for 2 reasons.

1. If you have generator functions, you have `let` and `const` and should be using them.
2. It's always been against our style guide and general good JS practice to use `var` within nested statements.

**Comment by SergejSalnikov** [comment]
I believe this one is fixed.

**Comment by blickly** [comment]
Thanks for checking
