### ISSUE TITLE
ES6 imports of paths with '.js' extension does not work

### ISSUE THREAD

**Issue by shicks** [google/closure-compiler#1897]
The compiler seems to want to add the extension.  I'm not super-clear on the spec, but my understanding is that an extension is allowed and if it's present, none will be added.

**Comment by ChadKillingsworth** [comment]
See discussion on #1774

**Comment by justinfagnani** [comment]
Any updates here? We're trying to write code that will load unmodified in browsers that support ES6 modules, like Edge, but they _require_ the file extension.

**Comment by MatrixFrog** [comment]
I'm still hesitant to support `.jsx` but supporting `.js` seems fine especially if browsers are accepting that.

**Comment by justinfagnani** [comment]
What the browsers are doing is just not modifying the URL passed to them, aside from resolving them to the base URL of the document they're contained in. This means you could use any extension, including the much maligned .mjs

**Comment by ChadKillingsworth** [comment]
This has been fixed by #2130 as long as the `--module_resolution` flag is either `BROWSER` or `NODE`.
