### ISSUE TITLE
Compiler cannot find entry point when using js_module_root without using exports

### ISSUE THREAD

**Issue by pspeter3** [google/closure-compiler#1900]
When running the below command, failing to export a symbol while using the `entry_point` and `js_module_root` flags causes the entry point to be unknown. I believe this is caused by the logic in these lines https://github.com/google/closure-compiler/blob/747aa4dfc5fb8c7a10dcaf96abb122cc72825fdb/src/com/google/javascript/jscomp/deps/Es6SortedDependencies.java#L192-L198

```sh
java -jar compiler.jar --compilation_level ADVANCED --dependency_mode STRICT --env BROWSER --language_in ECMASCRIPT6_STRICT --language_out ECMASCRIPT5_STRICT --entry_point failure --js_module_root example --js 'example/**.js'
```

###### example/failure.js

```js
const NAME = "example";
console.log(NAME);
```

###### example/success.js

```js
const NAME = "example";
console.log(NAME);
export { NAME };
```

**Comment by ChadKillingsworth** [comment]
Entry points must be module paths - they must either begin with a `/`, `../` or `./`.

Try something like:

```
java -jar compiler.jar --compilation_level ADVANCED --dependency_mode STRICT
    --env BROWSER --language_in ECMASCRIPT6_STRICT
    --language_out ECMASCRIPT5_STRICT --entry_point '/failure'
    --js_module_root example --js 'example/**.js'
```

**Comment by pspeter3** [comment]
Adding a leading slash for me does not work.

**Comment by ChadKillingsworth** [comment]
Just ran a test - looks like the js_module_root does not affect the entry_point. You'll need to specify the actual path:

```--entry_point './example/failure'```

**Comment by pspeter3** [comment]
Ah so `example/success.js` does work which is just a fluke then. I'll switch to using file paths

**Comment by pspeter3** [comment]
So interestingly enough, if you do pass the file name but have exports, the compiler cannot find the entry point.
