### ISSUE TITLE
`super` not correctly bound in arrow functions

### ISSUE THREAD

**Issue by marcfallows** [google/closure-compiler#1901]
In this contrived example:
```
class Foo {
  foo() {
    console.log('foo');
  }
}

class Bar extends Foo {
  foo() {
    (() => super.foo())()
  }
}
```
Closure compiler binds the super call to `this`, when instead it should be bound to the context of the arrow function. This is a snippet of what gets generated:
```
Bar.prototype.foo = function() {
  (function() {
    return Foo.prototype.foo.call(this);
  })();
};
```
But I would expect something like this:
```
Bar.prototype.foo = function() {
  var a = this;
  (function() {
    return Foo.prototype.foo.call(a);
  })();
};
```
(See [here](https://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540compilation_level%2520SIMPLE_OPTIMIZATIONS%250A%252F%252F%2520%2540language_in%2520ECMASCRIPT6%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%2540formatting%2520pretty_print%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250A%252F%252F%2520ADD%2520YOUR%2520CODE%2520HERE%250Aclass%2520Foo%2520%257B%250A%2520%2520foo()%2520%257B%250A%2520%2520%2520%2520console.log('foo')%253B%250A%2520%2520%257D%250A%257D%250A%250Aclass%2520Bar%2520extends%2520Foo%2520%257B%250A%2520%2520foo()%2520%257B%250A%2520%2520%2520%2520(()%2520%253D%253E%2520super.foo())()%250A%2520%2520%257D%250A%257D%250A%250A))

**Comment by MatrixFrog** [comment]
This is indeed contrived :)

Can you tell us more about how you ran into this case? I'm inclined to just ban `super` within arrow functions entirely but there might be a good reason not to.

**Comment by marcfallows** [comment]
Yes contrived, but the result is very clear that closure compiler is binding `super` calls to the wrong context.

I do not feel like banning `super` is the correct solution. Babel transpiles this case correctly.

This is perhaps a clearer example:
```
class View {
  remove() {
    //...
  }
}
class SubView extends View {
  remove() {
    this.cleanup().then(() => {
      this.postCleanup();  // bound correctly
      super.remove(); // bound incorrectly
    });
  }

  /**
   * @returns {!Promise}
   */
  cleanup() {
    //...
  }

  postCleanup() {
    //...
  }
}

var subView = new SubView();
subView.remove(); // will throw an error
```

The CC output for the `SubView`'s `remove` is:
```
SubView.prototype.remove = function() {
  var a = this;
  this.cleanup().then(function() {
    a.postCleanup();
    View.prototype.remove.call(this);
  });
};
```
As you can see, `postCleanup` call is bound to the right context by calling on `a`. 
`super` is bound to `this` when it should be bound to `a`.

**Comment by MatrixFrog** [comment]
Thanks. Closing this since #1907 is the same issue.

**Comment by DavidSouther** [comment]
Hah - I went searching for "super" and "arrow" before writing #1907! @marcfallows posted this between me searching the issues and writing my repro case! :)

**Comment by DavidSouther** [comment]
> Yes contrived, but the result is very clear that closure compiler is binding super calls to the wrong context.

Not contrived at all - in #1907 this is a common practice that was bound to happen with Promises.

**Comment by MatrixFrog** [comment]
The initial example was contrived, not the bug report.
