### ISSUE TITLE
ES6: Fails to bind correct `this` for `super` in arrow callbacks`

### ISSUE THREAD

**Issue by DavidSouther** [google/closure-compiler#1907]
Calling `super` from an arrow function doesn't use the defining method scope, but instead uses the calling scope.

Repro:

```javascript
// ==ClosureCompiler==
// @compilation_level SIMPLE_OPTIMIZATIONS
// @output_file_name default.js
// @formatting pretty_print
// ==/ClosureCompiler==

class Y {
  constructor() {
    this.message = 'IN Y FOO';
  }
  foo() {
    console.log(this.message);
  }
}
class X extends Y {
  foo() {
    Promise.resolve().then(() => {
	    super.foo();
    });
  }
}

var x = new X();
x.foo(); // Prints `undefined`
```

Specifically, we're looking at X's foo implementation, which gets compiled as:

```javascript
X.prototype.foo = function() {
  Promise.resolve().then(function() {
    Y.prototype.foo.call(this);
  });
};
```

It should be:

```javascript
X.prototype.foo = function() {
  var _this = this;
  Promise.resolve().then(function() {
    Y.prototype.foo.call(_this);
  });
};
```

or similar

**Comment by MatrixFrog** [comment]
Similar to https://github.com/google/closure-compiler/issues/1901 but this is a lot clearer. Might just be a matter of reordering things so that we handle `super` before rewriting `=>` functions.

**Comment by MatrixFrog** [comment]
https://closure-compiler-debugger.appspot.com/#input0%3Dclass%2520Y%2520%257B%257D%250A%250Aclass%2520X%2520extends%2520Y%2520%257B%250A%2520%2520foo()%2520%257B%250A%2520%2520%2520%2520Promise.resolve().then(()%2520%253D%253E%2520%257B%250A%2520%2520%2520%2520%2520%2520super.foo()%253B%250A%2520%2520%2520%2520%257D)%253B%250A%2520%2520%257D%250A%257D%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES%3D1%26CLOSURE_PASS%3D1%26LANG_IN_IS_ES6%3D1%26MISSING_PROPERTIES%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1%26TRANSPILE%3D1
