### ISSUE TITLE
Clash between externs and object properties using advanced optimization

### ISSUE THREAD

**Issue by morille** [google/closure-compiler#1908]
The compiler seems unable to rename instance properties when the same name appears in externs. For example the following code on the online compiler:

```javascript
// ==ClosureCompiler==
// @compilation_level ADVANCED_OPTIMIZATIONS
// @output_file_name default.js
// @js_externs var device = {};
// ==/ClosureCompiler==

/**
 * @constructor
 */
function Dog() {
  this.device = "test";
}

/**
 * @this {Dog}
 */
Dog.prototype.getDevice = function() {
  return this.device;
};

var roger = new Dog();
alert(roger.getDevice());
```

Will compile to:
```javascript
alert((new function(){this.device="test"}).device);
```

If I remove the extern, it compiles correctly to:
```javascript
alert((new function(){this.a="test"}).a);
```

Is there a way to help the compiler to make the difference between both ?

**Comment by ChadKillingsworth** [comment]
You need to enable the [type-based optimizations](https://github.com/google/closure-compiler/wiki/Type-Based-Property-Renaming) for this to be supported. They are on by default in the command line version of the compiler, but not in the web service:

```js
// ==ClosureCompiler==
// @compilation_level ADVANCED_OPTIMIZATIONS
// @output_file_name default.js
// @js_externs var device = {};
// @use_types_for_optimization true
// ==/ClosureCompiler==

/**
 * @constructor
 */
function Dog() {
  this.device = "test";
}

/**
 * @this {Dog}
 */
Dog.prototype.getDevice = function() {
  return this.device;
};

var roger = new Dog();
alert(roger.getDevice());
```

**Comment by morille** [comment]
I'm using the command line.
But I just realized that this functionnality is broken in the latest version from here: https://github.com/google/closure-compiler/wiki/Binary-Downloads
v20160713 => BROKEN
v20160619 => OK

**Comment by ChadKillingsworth** [comment]
I got the same results for your test case from the command line runner - latest version.

**Comment by morille** [comment]
Here is the test case:

```javascript
// app.js
/**
 * @constructor
 */
function Dog() {
  this.device = "test";
}

/**
 * @this {Dog}
 */
Dog.prototype.getDevice = function() {
  return this.device;
};

/**
 * @this {Dog}
 * @param {string} val
 */
Dog.prototype.updateDevice = function(val) {
  this.device = val;
};

var roger = new Dog();
roger.updateDevice("test2");

alert(roger.getDevice());
```

```javascript
// device.js
var device = {};
```

Test with latest compiler:
    java -jar closure-compiler-v20160713.jar --compilation_level ADVANCED_OPTIMIZATIONS --use_types_for_optimization true --externs device.js --js app.js --js_output_file app.min.js

Content of app.min.js:
    var a=new function(){this.device="test"};a.device="test2";alert(a.device);

Test with previous compiler:
    java -jar compiler-20160619.jar --compilation_level ADVANCED_OPTIMIZATIONS --use_types_for_optimization true --externs device.js --js app.js --js_output_file app.min.js

Content of app.min.js:
    var a=new function(){this.a="test"};a.a="test2";alert(a.a);

Thank you for your time.

**Comment by morille** [comment]
Should I open a new issue for this regression ?

**Comment by ChadKillingsworth** [comment]
I am still not able to reproduce your results. To demonstrate a problem, you would see different compilation results when `var device = {};` is included as an extern. I see exactly the same result - even with your latest test case:

```js
var a=new function(){this.a="test"};a.a="test2";alert(a.a);
```

Compile command:

```
java -jar compiler.jar -O=ADVANCED -W=VERBOSE --js=test.js --externs=externs.js
```
