### ISSUE TITLE
Wrong code produced for methods named like "addListener" when VERBOSE warning level is on

### ISSUE THREAD

**Issue by emaxx-google** [google/closure-compiler#1909]
Consider this sample code:
```
/** @constructor */
var A = function() {};
A.prototype.addListener = function() {};
A.prototype.removeListener = function() {};
A.prototype.foo = function() {};

var a = new A;
a.addListener();
a.removeListener();
a.foo();
```

**A.** Compiling this with compiler **v20160713** and **"--compilation_level=SIMPLE --formatting=PRETTY_PRINT --warning_level=VERBOSE"** command line options, the following output is produced:

```
var A = function() {
};
A.prototype.A_prototype$addListener = function() {
};
A.prototype.A_prototype$removeListener = function() {
};
A.prototype.foo = function() {
};
var a = new A;
a.A_prototype$addListener();
a.A_prototype$removeListener();
a.foo();
```

I.e., for some reason, the compiler **obfuscated** the names of the "addListener" and "removeListener" methods.

I also have a reproducible case when the compiler produces **wrong** code, inserting the obfuscated names in one places and unobfuscated names in the other places (all inside a single compilation unit). (Unfortunately, I didn't manage to transform that repro case into a small manageable sample code.)

**B.** However, with compiler **v20160713** and **"--compilation_level=SIMPLE --formatting=PRETTY_PRINT"** command line options, the following output is produced:
```
var A = function() {
};
A.prototype.addListener = function() {
};
A.prototype.removeListener = function() {
};
A.prototype.foo = function() {
};
var a = new A;
a.addListener();
a.removeListener();
a.foo();
```

I.e., removing the **"--warning_level=VERBOSE"** command line option somehow fixed the problem.

**C.** Compiling with an **older** version of the compiler produces the same output as in **"B"**, regardless of whether the "--warning_level=VERBOSE" option was present.

**Comment by MatrixFrog** [comment]
I believe 81eecbfda3d545987c2f9004952d9298a3d24611 fixes this. For now, I would recommend setting `--use_types_for_optimization=false` explicitly. Let us know if that doesn't work.

**Comment by emaxx-google** [comment]
Sorry, does this mean that fixing this incorrect optimization is tracked somewhere else? I don't get how suppressing the optimization in one of the compilation levels may be considered as a fix for the problem (especially given that this optimization is turned on by default in the ADVANCED mode).

Note that, as I referenced in the bug description, with this optimization the compiler may produce inconsistent code that attempts to call undefined object members instead of the correct methods (resulting in exceptions like "Foo.bar is not a function").

**Comment by MatrixFrog** [comment]
There are many ways that the type-based optimizations can go wrong. One possibility is that you've actually found a bug in DisambiguateProperties (in fact, this happens more than you might think; we're working on such a bug right now). Or, you may have code somewhere that is incorrectly typed. Look for any typecasts that seem suspicious.

**Comment by ChadKillingsworth** [comment]
One of the reasons type-based optimizations were considered experimental for so long is that it can be very hard to track down the source of the issue.
