### ISSUE TITLE
prototype method converted to global function

### ISSUE THREAD

**Issue by Wyzix33** [google/closure-compiler#1910]
Hi, i have this simple code: 
i removed some code to keep it simple...
````
if(!window['PSI']) window['PSI'] = {};
/**@constructor*/
window['PSI']['Select'] = function(pattern) {
	this.highlight(pattern);
}
window['PSI']['Select'].prototype = {
	highlight: function( pattern) {
		var regex = (typeof pattern === 'string') ? new RegExp(pattern, 'i') : pattern;
		var highlight = function(node) {
			if (node.nodeType === 3) {
				var pos = node.data.search(a);

			} else if (node.nodeType === 1 ) {
				for (var i = 0; i < node.childNodes.length; ++i) {
					i += highlight(node.childNodes[i]);
				}
			}
		}
		var items = document.getElementsByTagName("li");
		for (var i = 0; i < items.length; ++i) {
			highlight(items[i]);
		}
	}
}
````
and after i run 
`java -jar closure-compiler-v20160713.jar --compilation_level ADVANCED_OPTIMIZATIONS --js source.js --js_output_file source.min.js`

here is the output:
````
window.PSI || (window.PSI = {});
window.PSI.Select = function() { g() };
window.PSI.Select.prototype = {};
function g() {
    function e(b) {
    if(3 === b.nodeType) b.data.search(a);
    else if(1 === b.nodeType) for (var c = 0; c < b.childNodes.length; ++c)c += e(b.childNodes[c])
}
    for (var f = document.getElementsByTagName("li"), d = 0; d < f.length; ++d)e(f[d])
};
````
my highlight method becomes a global function, is there any way to keep my method as a prototype of PSI object?

PS, Sorry for my English, it's a little rusty :)

**Comment by MatrixFrog** [comment]
I'm guessing the compiler noticed that your method never referenced 'this' and it decided that removing it from the prototype was safe. If you want it not to do that, because there is external code which expects it to stay on the prototype, you can add `@export`:

    /** @export */
    PSI.Select.prototype.highlight = function(...

In fact, if you do this on `PSI.Select` as well then you don't need to use bracket notation all over the place.

This also requires the `--generate_exports` command line flag, and the Closure Library (since that flag tells the compiler to add calls to `goog.exportSymbol` from the library).

**Comment by Wyzix33** [comment]
Thanks, but if i set /** @export */ i get 
`ERROR - @export only applies to symbols/properties defined in the global scope.`, i had success defining my function inside the constructor like this:
````
if(!window['PSI']) window['PSI'] = {};
/**@constructor*/
window['PSI']['Select'] = function(pattern) {
	this.highlight= function( pattern) {
		var regex = (typeof pattern === 'string') ? new RegExp(pattern, 'i') : pattern;
		var highlight = function(node) {
			if (node.nodeType === 3) {
				var pos = node.data.search(a);

			} else if (node.nodeType === 1 ) {
				for (var i = 0; i < node.childNodes.length; ++i) {
					i += highlight(node.childNodes[i]);
				}
			}
		}
		var items = document.getElementsByTagName("li");
		for (var i = 0; i < items.length; ++i) {
			highlight(items[i]);
		}
	}
	this.highlight(pattern);
}
````
but it's not the best option since I'll have to do that with a lot of methods ... Any other suggestion ? 
Thanks

**Comment by MatrixFrog** [comment]
Oh yeah, you also need `--export_local_property_definitions` I think. (I tried to squash those into one flag, a while back, but it was not easy to do)

**Comment by Wyzix33** [comment]
Nice, it works, i have to set `/** @export */` before every method, it's not working on whole PSI.Select, but it;s OK :+1:  
Just to be clear for anyone reading, this is what i did
````
if(!window['PSI']) window['PSI'] = {};
/**@constructor*/
window['PSI']['Select'] = function(pattern) {
	this.highlight(pattern);
}

window['PSI']['Select'].prototype = {
	/** @export */
	highlight: function( pattern) {
		var regex = (typeof pattern === 'string') ? new RegExp(pattern, 'i') : pattern;
		var highlight = function(node) {
			if (node.nodeType === 3) {
				var pos = node.data.search(a);

			} else if (node.nodeType === 1 ) {
				for (var i = 0; i < node.childNodes.length; ++i) {
					i += highlight(node.childNodes[i]);
				}
			}
		}
		var items = document.getElementsByTagName("li");
		for (var i = 0; i < items.length; ++i) {
			highlight(items[i]);
		}
	}
}
````
and run `java -jar closure-compiler-v20160713.jar --compilation_level ADVANCED_OPTIMIZATIONS --generate_exports --export_local_property_definitions --js source.js --js_output_file source.min.js`
Thanks
