### ISSUE TITLE
goog.module top level declaration cannot be used in shorthand object literal assignments

### ISSUE THREAD

**Issue by mitchellwills** [google/closure-compiler#1912]
Given
```
goog.module('mymodule');
let y = 5;
let x = { y };
```
I get
```
ERROR - variable y is undeclared
let x = { y };
```
It looks like the y property assignment is not being updated for the new name of y, so the generated code looks like the following, hence the error.
```
/** @const */ var module$exports$mymodule = {};
let module$contents$mymodule_y = 5;
let module$contents$mymodule_x = {y};
```

**Comment by MatrixFrog** [comment]
Ben was looking at a similar issue to this I think.

**Comment by blickly** [comment]
Yeah, looks like an ordering issue between module rewriting and short object literal transpilation.
