### ISSUE TITLE
Prevent minification on a JSON definition

### ISSUE THREAD

**Issue by zarov** [google/closure-compiler#1913]
Hello all, can't seem to wrap my head around this one.

Let's assume I can only launch my compiled program (with advanced optimizations) if I pass a configuration in JSON:

````javascript
{
    module_foo: {
        smth: 54,
        othr: 'hello'
    },
    bar: true
}
````

So when launching, I'll get something like that:

````javascript
function init(json) {
    var foo = json.module_foo;
    var bar = json.bar;
    ...
}
````

The problem is at compilation, I will obtain something like :

````javascript
function a(a){var b=a.c,d=a.d;}
````

Is there a way to prevent the minification of these properties name, without using the classic ``["prop"]`` notation, as I still want typechecking ? I tried specifying my entire JSON with a ``@typedef``, as I thought it wouldn't collapse the properties name, but it failed.

Thanks in advance.

**Comment by ChadKillingsworth** [comment]
Questions are best asked on the google group or stackoverflow. We reserve the issue tracker for actual bugs and feature work.

You would need to specify your typedef in an extern file and annotate your init function with that type.

**Comment by zarov** [comment]
Thanks, will do, sorry about that !
