### ISSUE TITLE
Function declarations within conditional blocks assumed to be globals

### ISSUE THREAD

**Issue by mbarkhau** [google/closure-compiler#1914]
I've been able to reduce the issue I'm having down to this:

```javascript
(function() {
  if (1) {
    function test() {
      return 1;
    }
  }
  console.log(test());
})();
```

I would expect it to compile down to this, which is the same as if the declaration of `test` were not in the conditional block.

```javascript
(function(){console.log(1)})();
```

However it in fact compiles to this.

```javascript
(function(){console.log(test())})();
```

I'm guessing the compiler assumes that `test` may or may not be declared, so it can't assume it exists and so the `test` in `console.log(test());` must refer to a global. Then it sees that there is a local function `test` declared, however it (apparently) isn't used by anybody and so it gets eliminated.

I would have hoped the compiler could see that the condition is always true and therefore it could pull up the function declaration to the level of the conditional.

In practice I have a work around for our use case. I just pull the declaration out of the conditional myself and trust that the dead code elimination works.

**Comment by mashedcode** [comment]
Yeah sure in ECMAScript that should work but I can't see a reason why you would do such a weird scope declaration.
If it always evaluates to true then it doesn't make sense and even if it's a compile-time define it doesn't make sense because it would produce invalid code if it doesn't evaluate to true.
So IMHO you need to fix your code and the only thing that would be nice is if the compiler would throw an error but I wouldn't care too much.
This will work just as you expect it to work:
```
(function() {
  let test = function() {};
  if (1) {
    test = function() {
      return 1;
    }
  }
  console.log(test());
})();
```

**Comment by mbarkhau** [comment]
I'll be the first to admit that our code could be improved, but in our defence I just wrote the above example because it was the minimum to reproduce the issue. In practice we have both the function declaration as well as the usage code in conditional blocks behind a compile time constant. So it looks something like this:

```javascript
(function() {
    var FEATURE_FLAG = true;
    // ....
    if (FEATURE_FLAG ) {
        function test() {
            return 1;
        }
    }
    // ....
    if (FEATURE_FLAG ) {
        console.log(test());
    }
  }
})();
```

This isn't a critical issue for us now that we know it, but it did cause us some headache.

**Comment by MatrixFrog** [comment]
I would recommend just using `var test = function()...` instead of `function test() {...`

You're right that technically this should work but I don't think we're likely to fix it.
