### ISSUE TITLE
--jscomp_off='missingRequire' no longer seems to work

### ISSUE THREAD

**Issue by joeyparrish** [google/closure-compiler#1915]
In the context of [Shaka Player](https://github.com/google/shaka-player) unit and integration tests, the compiler flag `--jscomp_off=missingRequire` no longer seems to work.

Our test runner loads the entire Shaka Player library before the tests, so there should be no need for the tests to require anything.  When we check for type errors in the tests, we disable the `missingRequire` error.

I'm trying to upgrade the project to the latest compiler release, but the latest release gives us lots of 'missing require' errors, in spite of us passing `--jscomp_off=missingRequire`.

This was working in v20160208, but not in v20160713.  I'm in the middle of a git bisect now to try to determine when it changed.  I will also try to write a simple test case if I can so that you can reproduce it outside of Shaka Player's tests.

**Comment by MatrixFrog** [comment]
Do you have --jscomp_error=* on? Try --jscomp_off=strictMissingRequire as well.

**Comment by joeyparrish** [comment]
Yes, we do have jscomp_error=* on.  'strictMissingRequire' doesn't seem to be listed in --help.  What's the difference between missingRequire and strictMissingRequire?  Is this documented?

**Comment by MatrixFrog** [comment]
Apologies. We don't have a great system for keeping --help up to date. strictMissingRequire is more picky, as you can see. Eventually we'll merge the two but we'll need to fix a bunch of strictMissingRequire errors across Google first.

**Comment by joeyparrish** [comment]
Okay, I can use that for now.  I presume at some point we'll upgrade again and see an error that 'strictMissingRequire' doesn't exist, at which point we stop using it?

**Comment by MatrixFrog** [comment]
Yup.

**Comment by joeyparrish** [comment]
Okay, thanks for your help.
