### ISSUE TITLE
compiler.jar was renamed

### ISSUE THREAD

**Issue by teppeis** [google/closure-compiler#1917]
Previously the extracted jar file is `compiler.jar`, but now it's renamed to `closure-compiler-v20160713.jar`.

```console
$ wget https://dl.google.com/closure-compiler/compiler-latest.tar.gz && tar -xf compiler-latest.tar.gz && ls
COPYING                         closure-compiler-v20160713.jar
README.md                       compiler-latest.tar.gz
```

Is this an intentional change?

Now build script of [closure-gun](https://github.com/closure-gun/closure-gun) is broken by this change.
Should I fix the build script?

**Comment by MatrixFrog** [comment]
This was announced in the release notes. It seems to have broken a few unofficial build scripts / plugins. We recommend using an official supported one. See https://github.com/ChadKillingsworth/closure-compiler-npm/issues/29

**Comment by teppeis** [comment]
@MatrixFrog thanks, I missed the notes.
