### ISSUE TITLE
polyfill requires should be one-file-per-line for better maintainability

### ISSUE THREAD

**Issue by brad4d** [google/closure-compiler#1918]
Dependencies specified in polyfill JS code look like:

'require base some/thing some/thing/else';
'require a/third/thing';

It's hard to visually scan this for dependencies and hard to maintain deps in sorted order.
We should have one dependency per line instead.

Example change is
https://github.com/google/closure-compiler/commit/8d1bbe4fa4ae06337d4a1891f1180a5c61d589dc

@shicks says:
We should do this to all files and then "un-teach" Compiler.ensureLibraryInjected() and build_polyfill_table.js how to understand multiple per line.

**Comment by Dominator008** [comment]
Looks like this has already been fixed.

**Comment by brad4d** [comment]
Looks like @shicks did it. Ya should have said something! Thanks!
