### ISSUE TITLE
String array access to const index not simplified

### ISSUE THREAD

**Issue by krk** [google/closure-compiler#1920]
Input:
```js
alert("falseundefined"["10"]);
```
Output:
```js
alert("falseundefined"["10"]);
```

Expected:
```js
alert("i");
```

**Comment by mashedcode** [comment]
@krk this is unsafe anyway, you should use `"falseundefined".charAt(10)` for guaranteed browser support IE5-7.

**Comment by krk** [comment]
It is generated code by http://www.jsfuck.com/ and I was wondering if closure can "unfuck" it. Fuck is related to the Brainfuck language.

**Comment by MatrixFrog** [comment]
Fun, but probably a non-goal for Closure Compiler.

That said, it might be a fun side project for someone to do. Check out https://github.com/google/closure-compiler/wiki/Writing-Compiler-Pass if interested.

**Comment by Dominator008** [comment]
Could potentially be a peephole optimization.

**Comment by krk** [comment]
ended up writing jsunfuck: https://github.com/krk/jsunfuck
