### ISSUE TITLE
calls super method with the window as context when called from arrow function

### ISSUE THREAD

**Issue by davityle** [google/closure-compiler#1922]
When a super class method is called inside of an anonymous arrow function closure compiles the code to call the method with the window as context.
Minimum reproducible  case:

```
// ==ClosureCompiler==
// @output_file_name default.js
// @compilation_level SIMPLE_OPTIMIZATIONS
// @formatting pretty_print
// ==/ClosureCompiler==

class A {
	a() { console.log('a'); }
}

class B extends A {
  b() {
		return () => { super.a(); };
  }
}

new B().b()();
```

[Link](https://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%2540compilation_level%2520SIMPLE_OPTIMIZATIONS%250A%252F%252F%2520%2540formatting%2520pretty_print%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250Aclass%2520A%2520%257B%250A%2509a()%2520%257B%2520console.log('a')%253B%2520%257D%250A%257D%250A%250Aclass%2520B%2520extends%2520A%2520%257B%250A%2520%2520b()%2520%257B%250A%2509%2509return%2520()%2520%253D%253E%2520%257B%2520super.a()%253B%2520%257D%253B%250A%2520%2520%257D%250A%257D%250A%250Anew%2520B().b()()%253B%250A%250A)

If you compile this you get code that calls the `a` method on the class `A` with the window as the context:

```
B.prototype.b = function() {
  return function() {
    A.prototype.a.call(this);
  };
};
```
a workaround is to place `super.<method>()` with `<SuperClass>.prototype.<method>.call(this)`.
Closure then creates a local variable `a` that it assigns to `this` and uses that as the context.

```
//workaround

class C extends A {
  c() {
		return () => { A.prototype.a.call(this); };
  }
}

new C().c()();
```

which generates:

```
C.prototype.c = function() {
  var a = this;
  return function() {
    A.prototype.a.call(a);
  };
};
```

**Comment by MatrixFrog** [comment]
I think this is the same as https://github.com/google/closure-compiler/issues/1907 ?

**Comment by davityle** [comment]
It does look like the same issue
