### ISSUE TITLE
Parse error. Cycle detected in inheritance chain

### ISSUE THREAD

**Issue by vobruba-martin** [google/closure-compiler#1926]
``` javascript
/** @type {!Array<!MyItem2>} */
var MyList;

/**
 * @record
 * @struct
 */
var MyItem = function() {};

/**
 * @record
 * @struct
 * @extends {MyItem}
 */
var MyItem2 = function() {};
```

```
WARNING - Parse error. Cycle detected in inheritance chain of type MyItem2
/** @type {!Array<!MyItem2>} */
                   ^
```

There is no warning when:
1) `MyList` declaration goes after `MyItem2` OR
2) `MyItem` is annotated with `@interface` instead of `@record` OR
3) `MyList` is defined as `@type {!Array<!MyItem>}`

**Comment by MatrixFrog** [comment]
https://closure-compiler-debugger.appspot.com/#input0%3D%252F**%2520%2540type%2520%257B!Array%253C!MyItem2%253E%257D%2520*%252F%250Avar%2520MyList%253B%250A%250A%252F**%250A%2520*%2520%2540record%250A%2520*%2520%2540struct%250A%2520*%252F%250Avar%2520MyItem%2520%253D%2520function()%2520%257B%257D%253B%250A%250A%252F**%250A%2520*%2520%2540record%250A%2520*%2520%2540struct%250A%2520*%2520%2540extends%2520%257BMyItem%257D%250A%2520*%252F%250Avar%2520MyItem2%2520%253D%2520function()%2520%257B%257D%253B%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES%3D1%26CLOSURE_PASS%3D1%26LANG_IN_IS_ES6%3D1%26MISSING_PROPERTIES%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1%26TRANSPILE%3D1

**Comment by MatrixFrog** [comment]
Maybe the typechecker does something strange when you have an `@record` with no fields or methods?

**Comment by dimvar** [comment]
Looks like it. When MyItem2 has a property, the warning goes away.

https://closure-compiler-debugger.appspot.com/#input0%3D%252F**%2520%2540type%2520%257B!Array%253C!MyItem2%253E%257D%2520*%252F%250Avar%2520MyList%253B%250A%250A%252F**%250A%2520*%2520%2540record%250A%2520*%2520%2540struct%250A%2520*%252F%250Avar%2520MyItem%2520%253D%2520function()%2520%257B%257D%253B%250A%250A%252F**%250A%2520*%2520%2540record%250A%2520*%2520%2540struct%250A%2520*%2520%2540extends%2520%257BMyItem%257D%250A%2520*%252F%250Avar%2520MyItem2%2520%253D%2520function()%2520%257B%257D%253B%250A%250AMyItem2.prototype.p2%253B%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES%3D1%26CLOSURE_PASS%3D1%26LANG_IN_IS_ES6%3D1%26MISSING_PROPERTIES%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1%26TRANSPILE%3D1

@vobruba-martin When MyItem and MyItem2 have no properties, they are actually equivalent types, since they are both records, so they're checked structurally. So, the warning is somewhat legit, because a type is extending itself. (But the location of the warning is completely wrong; I don't know why that happens.)

**Comment by vobruba-martin** [comment]
That makes sense but why there is no warning when MyList is moved after MyItem2?

https://closure-compiler-debugger.appspot.com/#input0%3D%252F**%250A%2520*%2520%2540record%250A%2520*%2520%2540struct%250A%2520*%252F%250Avar%2520MyItem%2520%253D%2520function()%2520%257B%257D%253B%250A%250A%252F**%250A%2520*%2520%2540record%250A%2520*%2520%2540struct%250A%2520*%2520%2540extends%2520%257BMyItem%257D%250A%2520*%252F%250Avar%2520MyItem2%2520%253D%2520function()%2520%257B%257D%253B%250A%250A%252F**%2520%2540type%2520%257B!Array%253C!MyItem2%253E%257D%2520*%252F%250Avar%2520MyList%253B%250A%250A%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES%3D1%26CLOSURE_PASS%3D1%26LANG_IN_IS_ES6%3D1%26MISSING_PROPERTIES%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1%26TRANSPILE%3D1

**Comment by dimvar** [comment]
I'm not sure why.

To be clear, I agree that there is a compiler bug here. I'm just saying it's not super high priority to fix, because having an empty record extend an empty record isn't useful in practice.

**Comment by vobruba-martin** [comment]
Actually it's any record (not just empty) extended by an empty record. I did it this way because I knew that MyItem2 will have new properties in future and I wanted to prepare my code for this new type. Anyway I will add a dummy property. Thanks!

**Comment by jschaf** [comment]
I just hit this.  Here's the externs I was using:

```js
/**
 * @fileoverview An extern for the doctrine, a JSDoc parser at
 * https://github.com/eslint/doctrine
 * @externs
 */

/** @const */
const Doctrine = {};

/**
 * @typedef {(
 *     !Doctrine.NullableLiteral
 * )}
 */
Doctrine.TagType;

/** @record */
Doctrine.Typeable = function() {};
/** @type {string} */
Doctrine.Typeable.prototype.type;

/** @record @extends {Doctrine.Typeable} */ Doctrine.NullableLiteral = function() {};
/** @record @extends {Doctrine.Typeable} */ Doctrine.AllLiteral = function() {};
/** @record @extends {Doctrine.Typeable} */ Doctrine.NullLiteral = function() {};

/** @record @extends {Doctrine.Typeable} */ Doctrine.ArrayType = function() {};
/** @type {!Array<!Doctrine.TagType>} */ Doctrine.ArrayType.prototype.elements;

```

[Closure compiler debugger - doctrine externs](https://closure-compiler-debugger.appspot.com/#input0%3D%252F**%250A%2520*%2520%2540fileoverview%2520An%2520extern%2520for%2520the%2520doctrine%252C%2520a%2520JSDoc%2520parser%2520at%250A%2520*%2520https%253A%252F%252Fgithub.com%252Feslint%252Fdoctrine%250A%2520*%2520%2540externs%250A%2520*%252F%250A%250A%252F**%2520%2540const%2520*%252F%250Aconst%2520Doctrine%2520%253D%2520%257B%257D%253B%250A%250A%252F**%250A%2520*%2520%2540typedef%2520%257B(%250A%2520*%2520%2520%2520%2520%2520!Doctrine.NullableLiteral%250A%2520*%2520)%257D%250A%2520*%252F%250ADoctrine.TagType%253B%250A%250A%252F**%2520%2540record%2520*%252F%250ADoctrine.Typeable%2520%253D%2520function()%2520%257B%257D%253B%250A%252F**%2520%2540type%2520%257Bstring%257D%2520*%252F%250ADoctrine.Typeable.prototype.type%253B%250A%250A%252F**%2520%2540record%2520%2540extends%2520%257BDoctrine.Typeable%257D%2520*%252F%2520Doctrine.NullableLiteral%2520%253D%2520function()%2520%257B%257D%253B%250A%252F**%2520%2540record%2520%2540extends%2520%257BDoctrine.Typeable%257D%2520*%252F%2520Doctrine.AllLiteral%2520%253D%2520function()%2520%257B%257D%253B%250A%252F**%2520%2540record%2520%2540extends%2520%257BDoctrine.Typeable%257D%2520*%252F%2520Doctrine.NullLiteral%2520%253D%2520function()%2520%257B%257D%253B%250A%252F**%2520%2540record%2520%2540extends%2520%257BDoctrine.Typeable%257D%2520*%252F%2520Doctrine.UndefinedLiteral%2520%253D%2520function()%2520%257B%257D%253B%250A%252F**%2520%2540record%2520%2540extends%2520%257BDoctrine.Typeable%257D%2520*%252F%2520Doctrine.VoidLiteral%2520%253D%2520function()%2520%257B%257D%253B%250A%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES%3D1%26CLOSURE_PASS%3D1%26MISSING_PROPERTIES%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1%26TRANSPILE%3D1)

The error goes away if:

* I make !Doctrine.Typeable an interface.
* I remove the typedef.
* I inline the type attribute onto NullLiteral.

**Comment by mprobst** [comment]
Heres' another repro (we're hitting this too). Oddly enough, even the exports assignment below seems to be load bearing, at least it doesn't repro without it.

```javascript
goog.module('x');

/** @record */
function RequestOptionsArgs() { }
/** @type {string} */
RequestOptionsArgs.prototype.url;

/**
 * @record
 * @extends {RequestOptionsArgs}
 */
function RequestArgs() { }
exports.RequestArgs = RequestArgs;
/** @type {string} */
RequestArgs.prototype.url;

/** @param {RequestArgs} args */
function x(args) {}
```

**Comment by brad4d** [comment]
I believe this got fixed as part of the cleanups that @nreid260 has done.
At any rate the original repro link no longer produces an error.
