### ISSUE TITLE
The types of the getter and setter for property 'foo' do not match

### ISSUE THREAD

**Issue by SunboX** [google/closure-compiler#1927]
## Exception:
```
CONFLICTING_GETTER_SETTER_TYPE: The types of the getter and setter for property 'myprop' do not match. at line 13 character 6
  set myprop(trueOrFalse) {
      ^
```

### Live Demo:
[closure-compiler.appspot.com](http://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540compilation_level%2520SIMPLE_OPTIMIZATIONS%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%2540language_out%2520ES5%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250Aclass%2520MyClass%2520%257B%250A%2520%2520constructor()%2520%257B%250A%2520%2520%2520%2520%252F**%2520%2540type%2520%257Bboolean%257D%2520%2540private%2520*%252F%250A%2520%2520%2520%2520this.property_%2520%253D%2520false%253B%250A%2520%2520%257D%250A%250A%2520%2520%252F**%2520%2540return%2520%257Bboolean%257D%2520*%252F%250A%2520%2520get%2520myprop()%2520%257B%250A%2520%2520%2520%2520return%2520this.property_%253B%250A%2520%2520%257D%250A%250A%2520%2520%252F**%2520%2540param%2520%257Bboolean%257D%2520*%252F%250A%2520%2520set%2520myprop(trueOrFalse)%2520%257B%250A%2520%2520%2520%2520this.property_%2520%253D%2520trueOrFalse%253B%250A%2520%2520%257D%250A%257D%250A%250A)

### Demo Code:
```javascript
// ==ClosureCompiler==
// @compilation_level SIMPLE_OPTIMIZATIONS
// @output_file_name default.js
// @language_out ES5
// ==/ClosureCompiler==

class MyClass {
  constructor() {
    /** @type {boolean} @private */
    this.property_ = false;
  }

  /** @return {boolean} */
  get myprop() {
    return this.property_;
  }

  /** @param {boolean} */
  set myprop(trueOrFalse) {
    this.property_ = trueOrFalse;
  }
}
```

**Comment by SunboX** [comment]
@MatrixFrog or @aravind-pg, did I write something wrong or is the compiler failing?

**Comment by MatrixFrog** [comment]
The `@param` annotation requires the param name:

`/** @param {boolean} trueOrFalse */`

**Comment by MatrixFrog** [comment]
Or:

```
  set myprop(/** boolean */ trueOrFalse) {
    this.property_ = trueOrFalse;
  }
```
