### ISSUE TITLE
Code Printer prints code with syntax error

### ISSUE THREAD

**Issue by blickly** [google/closure-compiler#193]
This issue was imported from Closure Compiler's previous home at http://closure-compiler.googlecode.com

The original discussion is archived at:
http://blickly.github.io/closure-compiler-issues/#1167

**Comment by Dominator008** [comment]
Cannot reproduce with given code:
```javascript
for (var x_52 = /Precise Badger/ in {}) {}
```
. Parse error was correctly given. Closing.
