### ISSUE TITLE
Compiler crashed on using a catch parameter outside catch block

### ISSUE THREAD

**Issue by blickly** [google/closure-compiler#194]
This issue was imported from Closure Compiler's previous home at http://closure-compiler.googlecode.com

The original discussion is archived at:
http://blickly.github.io/closure-compiler-issues/#1162

**Comment by Dominator008** [comment]
Can't reproduce with given code:
```javascript
try {
} catch (x_15) {
} finally {
}
var a = x_15;
```
, closing.
