### ISSUE TITLE
"Property never defined on any type in the program" error exposes missed typedefs in externs [NTI]

### ISSUE THREAD

**Issue by supersteves** [google/closure-compiler#1941]
This should compile, but doesn't:

Externs:
``` javascript
var Hammer = {};
/** @constructor */
Hammer.Manager = function() {};

/**
 * @param {string} eventTypes
 * @param {function({
 *      type: string,
 *      center: { x: number, y: number },
 *      srcEvent: ?Event,
 *      target: ({className: string})
 * })} listener
 */
Hammer.Manager.prototype.on = function(eventTypes, listener) {};
```

Code:
``` javascript
new Hammer.Manager().on("someEvent", e => {
  let /** boolean */ yyy = e; // should fail, doesn't
  console.log(e.center.x); // fails
});
```

Error:
```
input0:3: WARNING - Property center never defined on any type in the program
  console.log(e.center.x); // fails
```

See [debugger](https://closure-compiler-debugger.appspot.com/#input0%3Dnew%2520Hammer.Manager().on(%2522someEvent%2522%252C%2520e%2520%253D%253E%2520%257B%250A%2520%2520let%2520%252F**%2520boolean%2520*%252F%2520yyy%2520%253D%2520e%253B%2520%252F%252F%2520should%2520fail%252C%2520doesn't%250A%2520%2520console.log(e.center.x)%253B%2520%252F%252F%2520fails%250A%257D)%253B%250A%26input1%26conformanceConfig%26externs%3Dvar%2520Hammer%2520%253D%2520%257B%257D%253B%250A%252F**%2520%2540constructor%2520*%252F%250AHammer.Manager%2520%253D%2520function()%2520%257B%257D%253B%250A%250A%252F**%250A%2520*%2520%2540param%2520%257Bstring%257D%2520eventTypes%250A%2520*%2520%2540param%2520%257Bfunction(%257B%250A%2520*%2520%2520%2520%2520%2520%2520type%253A%2520string%252C%250A%2520*%2520%2520%2520%2520%2520%2520center%253A%2520%257B%2520x%253A%2520number%252C%2520y%253A%2520number%2520%257D%252C%250A%2520*%2520%2520%2520%2520%2520%2520srcEvent%253A%2520%253FEvent%252C%250A%2520*%2520%2520%2520%2520%2520%2520target%253A%2520(%257BclassName%253A%2520string%257D)%250A%2520*%2520%257D)%257D%2520listener%250A%2520*%252F%250AHammer.Manager.prototype.on%2520%253D%2520function(eventTypes%252C%2520listener)%2520%257B%257D%253B%250A%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES%3D1%26CHECK_TYPES_NEW_INFERENCE%3D1%26CLOSURE_PASS%3D1%26LANG_IN_IS_ES6%3D1%26MISSING_PROPERTIES%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1%26TRANSPILE%3D1).

Probably exposed by @dimvar's https://github.com/google/closure-compiler/commit/72031d9defee7f1ad44e52041855fdea65ff8e7d.

A workaround is to avoid typedefs in externs like this; e.g. here I'm declaring a non-existent constructor purely for type hinting:

``` javascript
/** @constructor */
var HammerEvent = function() {};
/** @type {string} */
HammerEvent.prototype.type;
/** @type {{ x: number, y: number }} */
HammerEvent.prototype.center;
/** @type {?Event} */
HammerEvent.prototype.srcEvent;
/** @type {{className: string}} */
HammerEvent.prototype.target;

/**
 * @param {string} eventTypes
 * @param {function(!HammerEvent)} listener
 */
Hammer.Manager.prototype.on = function(eventTypes, listener) {};
```

This fixes the error, however it still fails to pick up the "should fail, doesn't" line (a trick I use to try and figure out what Closure Compiler has inferred). [Debugger](https://closure-compiler-debugger.appspot.com/#input0%3Dnew%2520Hammer.Manager().on(%2522someEvent%2522%252C%2520e%2520%253D%253E%2520%257B%250A%2520%2520let%2520%252F**%2520boolean%2520*%252F%2520yyy%2520%253D%2520e%253B%2520%252F%252F%2520should%2520fail%252C%2520doesn't%250A%2520%2520console.log(e.center.x)%253B%2520%252F%252F%2520fails%250A%257D)%253B%250A%26input1%26conformanceConfig%26externs%3Dvar%2520Hammer%2520%253D%2520%257B%257D%253B%250A%252F**%2520%2540constructor%2520*%252F%250AHammer.Manager%2520%253D%2520function()%2520%257B%257D%253B%250A%250A%252F**%2520%2540constructor%2520*%252F%250Avar%2520HammerEvent%2520%253D%2520function()%2520%257B%257D%253B%250A%252F**%2520%2540type%2520%257Bstring%257D%2520*%252F%250AHammerEvent.prototype.type%253B%250A%252F**%2520%2540type%2520%257B%257B%2520x%253A%2520number%252C%2520y%253A%2520number%2520%257D%257D%2520*%252F%250AHammerEvent.prototype.center%253B%250A%252F**%2520%2540type%2520%257B%253FEvent%257D%2520*%252F%250AHammerEvent.prototype.srcEvent%253B%250A%252F**%2520%2540type%2520%257B%257BclassName%253A%2520string%257D%257D%2520*%252F%250AHammerEvent.prototype.target%253B%250A%250A%252F**%250A%2520*%2520%2540param%2520%257Bstring%257D%2520eventTypes%250A%2520*%2520%2540param%2520%257Bfunction(!HammerEvent)%257D%2520listener%250A%2520*%252F%250AHammer.Manager.prototype.on%2520%253D%2520function(eventTypes%252C%2520listener)%2520%257B%257D%253B%250A%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES%3D1%26CHECK_TYPES_NEW_INFERENCE%3D1%26CLOSURE_PASS%3D1%26LANG_IN_IS_ES6%3D1%26MISSING_PROPERTIES%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1%26TRANSPILE%3D1).

**Comment by supersteves** [comment]
I figured out the real problem was a missing "!" non-nullable marker on the typedef.

Fixed externs:
``` javascript
var Hammer = {};
/** @constructor */
Hammer.Manager = function() {};

/**
 * @param {string} eventTypes
 * @param {function(!{
 *      type: string,
 *      center: { x: number, y: number },
 *      srcEvent: ?Event,
 *      target: ({className: string})
 * })} listener
 */
Hammer.Manager.prototype.on = function(eventTypes, listener) {};
```

So probably this issue is about the error being hugely misleading and leading me to lose a couple of hours. 

Also doing something like
``` javascript
let /** number */ xxx = new Hammer.Manager().on;
```
to find out the type seen by the compiler doesn't yield any indication that it's nullable. Is this a mistake in the type printing used in errors?
```
Found    : function(this:Hammer.Manager,string,function({center:{x:number, y:number}, srcEvent:Event|null, target:{className:string}, type:string}):?):?
```
Here the typedef arg of the function arg is missing the "!" which fixes the above problem... but the above error message is the same regardless. [Debugger](https://closure-compiler-debugger.appspot.com/#input0%3Dlet%2520%252F**%2520number%2520*%252F%2520xxx%2520%253D%2520new%2520Hammer.Manager().on%253B%250Anew%2520Hammer.Manager().on(%2522someEvent%2522%252C%2520e%2520%253D%253E%2520%257B%250A%2520%2520let%2520%252F**%2520boolean%2520*%252F%2520yyy%2520%253D%2520e%253B%2520%252F%252F%2520should%2520fail%252C%2520doesn't%250A%2520%2520console.log(e.center.x)%253B%2520%252F%252F%2520fails%250A%257D)%253B%250A%26input1%26conformanceConfig%26externs%3Dvar%2520Hammer%2520%253D%2520%257B%257D%253B%250A%252F**%2520%2540constructor%2520*%252F%250AHammer.Manager%2520%253D%2520function()%2520%257B%257D%253B%250A%250A%252F**%250A%2520*%2520%2540param%2520%257Bstring%257D%2520eventTypes%250A%2520*%2520%2540param%2520%257Bfunction(%257B%250A%2520*%2520%2520%2520%2520%2520%2520type%253A%2520string%252C%250A%2520*%2520%2520%2520%2520%2520%2520center%253A%2520%257B%2520x%253A%2520number%252C%2520y%253A%2520number%2520%257D%252C%250A%2520*%2520%2520%2520%2520%2520%2520srcEvent%253A%2520%253FEvent%252C%250A%2520*%2520%2520%2520%2520%2520%2520target%253A%2520(%257BclassName%253A%2520string%257D)%250A%2520*%2520%257D)%257D%2520listener%250A%2520*%252F%250AHammer.Manager.prototype.on%2520%253D%2520function(eventTypes%252C%2520listener)%2520%257B%257D%253B%250A%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES%3D1%26CHECK_TYPES_NEW_INFERENCE%3D1%26CLOSURE_PASS%3D1%26LANG_IN_IS_ES6%3D1%26MISSING_PROPERTIES%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1%26TRANSPILE%3D1).

**Comment by dimvar** [comment]
Thanks for the report! Will fix.

**Comment by supersteves** [comment]
I should add that this only happens with `ADVANCED_OPTIMIZATIONS` and not with `SIMPLE_OPTIMIZATIONS`.

This is also somewhat random. After updating Closure Library to the latest, randomly new cases of this cropped up in our own codebase.

**Comment by dimvar** [comment]
I've already submitted the fix for this internally. It should land externally later today.

**Comment by supersteves** [comment]
:+1:

**Comment by supersteves** [comment]
Fix confirmed. Thanks v much!
