### ISSUE TITLE
single function stops working after ADVANCED_OPTIMISATION

### ISSUE THREAD

**Issue by Megabyteceer** [google/closure-compiler#1947]
I tried optimize my simple code which uses jQuery. I included jQuery's code and close it in one function with my code, to avoid any external dependencies.

Code works fine in SIMPLE_OPTIMISATION mode, and gives:
'Uncaught TypeError: $ is not a function' in ADVANCED_OPTIMISATION

```js
(function(){

//jQuery without any modification included here. Omited.
/*! jQuery v1.11.1 | (c) 2005, 2014 jQuery Foundation, Inc. | jquery.org/license */

  /*this line works in SIMPLE_OPTIMISATION mode, and gives:
  'Uncaught TypeError: $ is not a function' in ADVANCED_OPTIMISATION */
  $(window);
})()
```

**Comment by Dominator008** [comment]
You will need to export what you would like to keep. Please see https://developers.google.com/closure/compiler/docs/api-tutorial3 as a starter.

**Comment by Megabyteceer** [comment]
Maybe im wrong but in sample i provided, i omited jQuery code and so i think it is not case when compiler removes function which never called, because function declaration and calling here, in one portion of code. 
Is anything i understand in wrong way?

**Comment by Megabyteceer** [comment]
Maybe im wrong but in sample i provided, i omited jQuery code and so i think it is not case when compiler removes function which never called, because function declaration and calling here, in one portion of code. 
Is anything i understand in wrong way?

**Comment by Dominator008** [comment]
It's likely that the jQuery code you included does not explicitly export the `$` symbol, so the compiler will remove it. AFAIK the jQuery code itself is not compatible with ADVANCED_OPTIMIZATION, so a better way would be compiling just your application with the jQuery externs file (https://github.com/google/closure-compiler/blob/master/contrib/externs/jquery-1.9.js), it's a bit outdated but should work in most cases.

**Comment by Megabyteceer** [comment]
Thanks Dominantor008, i think ill just use SIMPLE_OPTIMISATION. It is enought for me.
I just thought if compiler incompatible with jQuery, its problem of compiler, and not of jQuery : )

**Comment by Dominator008** [comment]
Most random code are compatible with SIMPLE _OPTIMIZATIONS, making them compatible WITH ADVANCED is a non-goal for the compiler :)
