### ISSUE TITLE
WHITESPACE_ONLY and ES6 modules emits incorrect "Illegal redeclared variable" errors

### ISSUE THREAD

**Issue by supersteves** [google/closure-compiler#1948]
When you have two ES6 modules which declare a `const` or `let` at the top scope of the module, and both use the *same name* e.g. ...
``` javascript
// module A
const xxx = "a";
...
```
``` javascript
// module B
import A from "./A"
const xxx = "b"
```
... they conflict in WHITESPACE_ONLY mode, and you get:
```
ERROR - Illegal redeclared variable: xxx
```

I can't find how to do WHITESPACE_ONLY and ES6 modules either the service or the debugger. But the local test case is very simple.

Are ES6 modules are simply not supported in WHITESPACE_ONLY mode? Previously (my last version of the compiler was around Feb this year) this used to 'compile' successfully in ws-only mode (but probably would never have worked at runtime) but today's compiler fails with this error.

Or is it the case that ws-only mode should now work with ES6 modules, and this is simply a bug with that? I think I recall seeing some commits go past relating to whitespace mode and ES6 modules.

I'd definitely be interested in using ws-only mode with ES6 modules to shorten dev build times, but can live without it.

**Comment by supersteves** [comment]
Equally:
```
Variable Tab first declared in closure-externs/browser/chrome.js
```

**Comment by brad4d** [comment]
@Dominator008, I believe this is another report of the bug you fixed earlier today.
Do you agree?

**Comment by Dominator008** [comment]
@brad4d I think so, @supersteves can you confirm it is now fixed?

**Comment by supersteves** [comment]
@Dominator008 Yep, fixed - thanks!
