### ISSUE TITLE
Compiler produces code with syntax error

### ISSUE THREAD

**Issue by blickly** [google/closure-compiler#195]
This issue was imported from Closure Compiler's previous home at http://closure-compiler.googlecode.com

The original discussion is archived at:
http://blickly.github.io/closure-compiler-issues/#1161

**Comment by Dominator008** [comment]
Can't reproduce with given code:
```javascript
function x_42() {
}
while (typeof function x_61() {
}) {
}
new undefined(x_42);
```
, closing.

**Comment by jkavalik** [comment]
@Dominator008 I was able to reproduce it for the `new undefined();` example from the linked issue with  `Version: v20150315`
