### ISSUE TITLE
Compiler breaks working ES6 code when compiling a class which extends Date()

### ISSUE THREAD

**Issue by beingmrkenny** [google/closure-compiler#1953]
I've written a class which extends the Date() object. When I use this class directly, before compilation, it works as expected.

This is a simplified example, which works in Chrome currently:

    <script type="text/javascript">

        class Dative extends Date {

            constructor (dateData) {
                super();
                super.setTime(Date.parse(dateData));
            }

            addMilliseconds (ms) {
                super.setTime(super.getTime() + ms);
            }

            addDays (days) {
                var self = this;

                var h = super.getHours(),
                    i = super.getMinutes(),
                    s = super.getSeconds(),
                    u = super.getMilliseconds();

                days = days || 0;

                while (days !== 0) {

                    if (days > 0) {
                        super.setHours(23, 59, 59, 999);
                        self.addMilliseconds(1);
                        days--;
                    } else {
                        super.setHours(0, 0, 0, 0);
                        self.addMilliseconds(-1);
                        days++;
                    }

                }

                super.setHours(h, i, s, u);
            }

        }

        var testDate = new Dative('24 december 2016');
        console.log(testDate.getHours());
        testDate.addDays(1)
        console.log(testDate);
        testDate.addMilliseconds(2 * 60 * 60 * 1000);
        console.log(testDate);
    </script>

The compiled version of the code breaks, returning
"Uncaught TypeError: Method Date.prototype.setTime called on incompatible receiver [object Object]" — on the line `Date.prototype.setTime.call(this, Date.parse(a))`.

    <script type="text/javascript">

        'use strict';
        var $jscomp = {
                scope: {},
                inherits: function(a, b) {
                    function d() {}
                    d.prototype = b.prototype;
                    a.prototype = new d;
                    a.prototype.constructor = a;
                    for (var c in b)
                        if (Object.defineProperties) {
                            var e = Object.getOwnPropertyDescriptor(b, c);
                            e && Object.defineProperty(a, c, e)
                        } else a[c] = b[c]
                }
            },
            Dative = function(a) {
                Date.call(this);
                Date.prototype.setTime.call(this, Date.parse(a))
            };
        $jscomp.inherits(Dative, Date);
        Dative.UTC = Date.UTC;
        Dative.parse = Date.parse;
        Dative.now = Date.now;
        Dative.prototype.addMilliseconds = function(a) {
            Date.prototype.setTime.call(this, Date.prototype.getTime.call(this) + a)
        };
        Dative.prototype.addDays = function(a) {
            var b = Date.prototype.getHours.call(this),
                d = Date.prototype.getMinutes.call(this),
                c = Date.prototype.getSeconds.call(this),
                e = Date.prototype.getMilliseconds.call(this);
            for (a = a || 0; 0 !== a;) 0 < a ? (Date.prototype.setHours.call(this, 23, 59, 59, 999), this.addMilliseconds(1), a--) : (Date.prototype.setHours.call(this, 0, 0, 0, 0), this.addMilliseconds(-1), a++);
            Date.prototype.setHours.call(this, b, d, c, e)
        };

        var testDate = new Dative('24 december 2016');
        console.log(testDate.getHours());
        testDate.addDays(1)
        console.log(testDate);
        testDate.addMilliseconds(2 * 60 * 60 * 1000);
        console.log(testDate);

    </script>

**Comment by brad4d** [comment]
If you're not overriding setTime() in your derived class, there's no need
to call super.setTime(). Just call this.setTime().
Does that resolve the error?

**Comment by ChadKillingsworth** [comment]
I think the problem is related to transpilation and extending native objects. Namely the class syntax is more than just syntactic sugar. I'd be interested to see how Babel transpiles this.

**Comment by beingmrkenny** [comment]
Same error, I'm afraid.

**Comment by Dominator008** [comment]
@ChadKillingsworth https://babeljs.io/repl/#?evaluate=false&lineWrap=true&presets=es2015&code=class%20Dative%20extends%20Date%20%7B%0A%20%20constructor%20(dateData)%20%7B%0A%20%20%20%20super()%3B%0A%20%20%20%20super.setTime(Date.parse(dateData))%3B%0A%20%20%7D%0A%7D

**Comment by ChadKillingsworth** [comment]
Highly probable that this is related/caused by #1669

**Comment by shicks** [comment]
Same issue as extending `Error`, maybe?

**Comment by ChadKillingsworth** [comment]
The Babel code doesn't work either. As pointed out [on stackoverflow](http://stackoverflow.com/a/38971189/1211524), native objects require ES6 class syntax to extend.
