### ISSUE TITLE
Collapse Properties has massive impact on ES6 module code size

### ISSUE THREAD

**Issue by cramforce** [google/closure-compiler#1954]
I have not tested this recently, but it is pretty bad, since this cannot (or can it?) be set via the command line. Without collapse properties, DCE basically doesn't work.

Could the generated code be changed to not rely on this?

**Comment by MatrixFrog** [comment]
For the open-source runner, collapse properties is enabled by turning on advanced mode. IIRC AMP is choosing not to use advanced mode?

**Comment by cramforce** [comment]
It doesn't. But the point is that there really is no reason why one
shouldn't get tight code with just --assume_function_wrapper. Normal ES6
code is completely unaffected by collapse properties except in the
transpiled (!) code.

My original CommonJS transpiler didn't have this issue. The current state
is an implementation choice in the transpiler that could be easily
optimized using special case property collapsing.

**Comment by ChadKillingsworth** [comment]
It should be possible and mostly safe to run collapse properties on module imports/exports in SIMPLE_OPTIMIZATIONS.

**Comment by Dominator008** [comment]
@cramforce IIRC you were trying to land a `SIMPLE_PLUS_OPTIMIZATIONS`? Is that related?

**Comment by cramforce** [comment]
That was John Lenz. Was removed in favor of assume _function_wrapper. This
seems invariant to optimizations as it only affects code that is generated
during transpilation.

**Comment by ChadKillingsworth** [comment]
I think the newer methods of module rewriting we are working on doesn't have to use properties period. However nobody is actively working on the ES6 module rewriting to my knowledge.

**Comment by cramforce** [comment]
I think good results in simple mode would benefit a lot of people.

In any case, having "sensible defaults" for ES6 compilation would be so nice. It is incredibly hard to get it to be well configured, leading to a lot of people just assuming CC doesn't work well or doesn't work.

**Comment by ChadKillingsworth** [comment]
So early indications on code bases tell me this causes roughly a 6% gzip win. I'm planning on implementing this.
