### ISSUE TITLE
Warning when constructing a derived class

### ISSUE THREAD

**Issue by evmar** [google/closure-compiler#1955]
```js
class Base {
}

class Derived extends Base {
}

let x = new Derived();
```

```
JSC_WRONG_ARGUMENT_COUNT: Function Derived: called with 0 argument(s). Function requires at least 1 argument(s) and no more than 1 argument(s). at line 7 character 8
let x = new Derived();
        ^
```

https://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540compilation_level%2520ADVANCED_OPTIMIZATIONS%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250Aclass%2520Base%2520%257B%250A%257D%250A%250Aclass%2520Derived%2520extends%2520Base%2520%257B%250A%257D%250A%250Alet%2520x%2520%253D%2520new%2520Derived()%253B%250A

**Comment by MatrixFrog** [comment]
Looks like #1929
