### ISSUE TITLE
Updating Three.js Closure Compiler Build path to ES6 Modules.

### ISSUE THREAD

**Issue by mrdoob** [google/closure-compiler#1956]
Hello,

This month we've moved `three.js` code base to ES6 Modules (https://github.com/mrdoob/three.js/pull/9310) and I've been trying to port the current [Closure Compiler-based build path](https://github.com/mrdoob/three.js/blob/dev/utils/build/build.py#L86-L94).

I'm having a really hard time finding command line examples of how to handle ES6 Modules.

As a simple reduced test case I'm doing this:

I have these two files: https://gist.github.com/mrdoob/7d75270a22b9d62da2e1e991ef846188

I run this:

```
java -jar closure-compiler-v20160713.jar --warning_level=VERBOSE --language_in=ECMASCRIPT6_STRICT --js index.js --js_output_file test.js
```

And I get this:

```
WARNING - Failed to load module "./Layers.js"

index.js:1: ERROR - required "module$Layers_js" namespace never provided
import { Layers } from './Layers.js';
^
```

This code compiles just fine in http://rollupjs.org/. Any ideas...?

Thanks in advance!

**Comment by mkeblx** [comment]
Yes.. you do need to omit the file extension in index.js: `import { Layers } from './Layers';`

==
And, for warning:
```js
/**
 * @constructor
 */
function Layers() {

	this.mask = 1;

}
```
And can use wildcard.
```
java -jar closure-compiler-v20160713.jar --warning_level=VERBOSE --language_in=ECMASCRIPT6_STRICT --js **.js --js_output_file test.js
```

**Comment by mrdoob** [comment]
Thanks @mkeblx!

Ok, so `Layers.js` needs to be included in the command line:

```
java -jar closure-compiler-v20160713.jar --warning_level=VERBOSE --language_in=ECMASCRIPT6_STRICT --js Layers.js index.js --js_output_file test.js;
```

And the import needs to not have the `.js` at the end.

The `@constructor` but seems to not really be needed.

This gives me this:

```js
var module$Layers={};function Layers$$module$Layers(){this.mask=1}Layers$$module$Layers.prototype={constructor:Layers$$module$Layers,set:function(a){this.mask=1<<a},Layers$$module$Layers_prototype$enable:function(a){this.mask|=1<<a},Layers$$module$Layers_prototype$toggle:function(a){this.mask^=1<<a},Layers$$module$Layers_prototype$disable:function(a){this.mask&=~(1<<a)},Layers$$module$Layers_prototype$test:function(a){return!!(this.mask&a.mask)}};module$Layers.Layers=Layers$$module$Layers;var test$$module$index=new module$Layers.Layers;console.log(test$$module$index);
```

Which seems a bit bloated...

**Comment by mrdoob** [comment]
Seems like I would need to keep track of dependencies manually...?

For reference, `rollup.js` only requires this [config file](https://github.com/mrdoob/three.js/blob/dev/rollup.config.js) which mainly points to [this file](https://github.com/mrdoob/three.js/blob/dev/src/Three.js) and it deals with the dependencies on its own.

**Comment by Dominator008** [comment]
@mrdoob Have you looked at https://github.com/google/closure-compiler/wiki/Managing-Dependencies? Please see if `--dependency_mode=STRICT` works.

**Comment by mrdoob** [comment]
```
java -jar closure-compiler-v20160713.jar --warning_level=VERBOSE --language_in=ECMASCRIPT6_STRICT --dependency_mode=STRICT --js index.js --js_output_file test.js
```

```
When --dependency_mode=STRICT, you must specify at least one --entry_point.
When dependency_mode=STRICT, you must specify at least one entry_point
```

I guess a `index.js` should be the entry point?

```
java -jar closure-compiler-v20160713.jar --warning_level=VERBOSE --language_in=ECMASCRIPT6_STRICT --dependency_mode=STRICT --entry_point index.js --js index.js --js_output_file test.js
```

```
WARNING - Failed to load module "./Layers"

index.js:1: ERROR - required "module$Layers" namespace never provided
import { Layers } from './Layers';
^

1 error(s), 1 warning(s)
```

**Comment by MatrixFrog** [comment]
That last invocation looks right except you also need a `--js` flag for layers.js, like you had in https://github.com/google/closure-compiler/issues/1956#issuecomment-239994106

**Comment by ChadKillingsworth** [comment]
Entry points are modules - leave of the `.js` extension for the entry point.

**Comment by mrdoob** [comment]
Ok, so...

```
java -jar closure-compiler-v20160713.jar --warning_level=VERBOSE --language_in=ECMASCRIPT6_STRICT --dependency_mode=STRICT --entry_point index --js Layers.js index.js --js_output_file test.js
```

Seems like I'm back again to what I had in https://github.com/google/closure-compiler/issues/1956#issuecomment-239994106

Bloated output:

```js
var module$Layers={};function Layers$$module$Layers(){this.mask=1}Layers$$module$Layers.prototype={constructor:Layers$$module$Layers,set:function(a){this.mask=1<<a},Layers$$module$Layers_prototype$enable:function(a){this.mask|=1<<a},Layers$$module$Layers_prototype$toggle:function(a){this.mask^=1<<a},Layers$$module$Layers_prototype$disable:function(a){this.mask&=~(1<<a)},Layers$$module$Layers_prototype$test:function(a){return!!(this.mask&a.mask)}};module$Layers.Layers=Layers$$module$Layers;var test$$module$index=new module$Layers.Layers;console.log(test$$module$index);
```

**Comment by MatrixFrog** [comment]
The way we translate ES6 modules, was designed with advanced compilation in mind. If you can switch to advanced mode that would be ideal. See https://developers.google.com/closure/compiler/docs/api-tutorial3

If not, there was some discussion recently about making ES6 modules work better with simple mode but I don't know that it will happen particularly soon.

**Comment by ChadKillingsworth** [comment]
Closing this. See #1954 for info on the module size in simple mode.
