### ISSUE TITLE
Uint8Array externs are incomplete

### ISSUE THREAD

**Issue by pallosp** [google/closure-compiler#1957]
https://github.com/google/closure-compiler/blob/master/externs/es6.js only declares set(), subarray(), fill() and copyWithin(), while according to https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array Uint8Array has 19 other methods.

**Comment by ChadKillingsworth** [comment]
Externs are manually maintained. If you'd like to submit a PR, we'd be happy to review it.

**Comment by vobruba-martin** [comment]
I submited a PR for this a few days ago: #1938

**Comment by vobruba-martin** [comment]
This issue has been fixed in https://github.com/google/closure-compiler/commit/cf3c1f5ba45d3154c80ce5eecbec45549e8641f6

**Comment by Dominator008** [comment]
Closed by  cf3c1f5
