### ISSUE TITLE
externs/w3c_event.js specifies Event argument as nullable

### ISSUE THREAD

**Issue by blickly** [google/closure-compiler#196]
This issue was imported from Closure Compiler's previous home at http://closure-compiler.googlecode.com

The original discussion is archived at:
http://blickly.github.io/closure-compiler-issues/#1159

**Comment by Dominator008** [comment]
Looks like this has been fixed: https://github.com/google/closure-compiler/blob/f0bae7f1e918365c061e4b92d1a6f4ef70a4f4e1/externs/browser/w3c_event.js#L34
