### ISSUE TITLE
missingRequire compiler check

### ISSUE THREAD

**Issue by robfig** [google/closure-compiler#1960]
It appears that the closure compiler only warns me if I fail to goog.require a particular type (something annotated with '@constructor'), but not if I fail to goog.require a namespace. For example, it does not warn me if I use goog.math.clamp and fail to require goog.math.

Is that expected? Is there any other way to avoid missing requires?  

It seems like the downside is that it may work incidentally if the dependency is included by virtue of another dependency, but break in the future.

**Comment by MatrixFrog** [comment]
The check for calls (as opposed to "new"s) is under strictMissingRequire
for now.

**Comment by robfig** [comment]
Excellent, thank you for the info! Time to update plovr..
