### ISSUE TITLE
"duplicate" suppression works only for properties, not variables

### ISSUE THREAD

**Issue by dimvar** [google/closure-compiler#1965]
Repro.

https://closure-compiler-debugger.appspot.com/#input0%3D%252F**%2520%2540const%2520*%252F%250Avar%2520ns%2520%253D%2520%257B%257D%253B%250A%250A%252F**%250A%2520*%2520%2540type%2520%257Bnumber%257D%250A%2520*%252F%250Ans.x%253B%2520%252F%252F%2520def%2520A%250A%250A%252F**%250A%2520*%2520%2540type%2520%257Bnumber%257D%250A%2520*%2520%2540suppress%2520%257Bduplicate%257D%250A%2520*%252F%250Ans.x%253B%2520%252F%252F%2520def%2520B%250A%250A%252F**%250A%2520*%2520%2540type%2520%257Bnumber%257D%250A%2520*%252F%250Avar%2520y%253B%2520%252F%252F%2520def%2520A%250A%250A%252F**%250A%2520*%2520%2540type%2520%257Bnumber%257D%250A%2520*%2520%2540suppress%2520%257Bduplicate%257D%250A%2520*%252F%250Avar%2520y%253B%2520%252F%252F%2520def%2520B%250A%250A%250A%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES%3D1%26CLOSURE_PASS%3D1%26LANG_IN_IS_ES6%3D1%26MISSING_PROPERTIES%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1%26TRANSPILE%3D1

Context: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/closure-compiler-discuss/g97i4metMwA/oCdEOTmZAQAJ
Their suppression doesn't work because the redeclaration is `var self` instead of a property.

As a side issue, we should be disabling the "declare global variables on window" when we're compiling for an environment other than the web.

**Comment by vobruba-martin** [comment]
I'm trying to update w3c_serviceworker.js extern file and I'm not able to suppress this warning:

```javascript
/**
 * @param {string} type
 * @param {!EventInit=} opt_init
 * @constructor
 * @extends {Event}
 * @see https://www.w3.org/TR/service-workers/#extendablemessage-event-interface
 */
function ExtendableMessageEvent(type, opt_init) {};

/**
 * @type {(!ServiceWorkerClient|!ServiceWorker|!MessagePort)}
 * @suppress {checkTypes}
 */
ExtendableMessageEvent.prototype.source;
```
```
externs.zip//w3c_serviceworker.js:517: WARNING - Invalid redeclaration of property source.
inherited type  : Window|null
overriding type : MessagePort|ServiceWorker|ServiceWorkerClient

ExtendableMessageEvent.prototype.source;
^
```

@dimvar is it somehow related to this issue? Thanks!

**Comment by vobruba-martin** [comment]
Here is a repro

https://closure-compiler-debugger.appspot.com/#input0%3D%252F**%250A%2520*%2520%2540constructor%250A%2520*%252F%250Afunction%2520A()%2520%257B%257D%253B%250A%250A%252F**%2520%2540type%2520%257Bnumber%257D%2520*%252F%250AA.prototype.prop%253B%250A%250A%252F**%250A%2520*%2520%2540constructor%250A%2520*%2520%2540extends%2520%257BA%257D%250A%2520*%252F%250Afunction%2520B()%2520%257B%257D%253B%250A%250A%252F**%250A%2520*%2520%2540type%2520%257Bstring%257D%250A%2520*%2520%2540override%250A%2520*%2520%2540suppress%2520%257BcheckTypes%257D%250A%2520*%252F%250AB.prototype.prop%253B%250A%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES%3D1%26CHECK_TYPES_NEW_INFERENCE%3D1%26CLOSURE_PASS%3D1%26LANG_IN_IS_ES6%3D1%26MISSING_PROPERTIES%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1%26TRANSPILE%3D1

**Comment by Dominator008** [comment]
@vobruba-martin Looks like a separate issue.

**Comment by vobruba-martin** [comment]
It seems to me that this issue hasn't been fixed. At least it is not fixed if you use some kind of object. There is also difference if the suppression is in externs file or not. And it affects NTI too not just OTI.

- [OTI](https://closure-compiler-debugger.appspot.com/#input0%3D%252F**%2520%2540const%2520*%252F%250Avar%2520ns%2520%253D%2520%257B%257D%253B%250A%250A%252F**%250A%2520*%2520%2540type%2520%257B!Object%257D%250A%2520*%252F%250Ans.x%253B%2520%252F%252F%2520def%2520A%250A%250A%252F**%250A%2520*%2520%2540type%2520%257B!Array%257D%250A%2520*%2520%2540suppress%2520%257Bduplicate%257D%250A%2520*%252F%250Ans.x%253B%2520%252F%252F%2520def%2520B%250A%250A%252F**%250A%2520*%2520%2540type%2520%257B!Object%257D%250A%2520*%252F%250Avar%2520y%253B%2520%252F%252F%2520def%2520A%250A%250A%252F**%250A%2520*%2520%2540type%2520%257B!Array%257D%250A%2520*%2520%2540suppress%2520%257Bduplicate%257D%250A%2520*%252F%250Avar%2520y%253B%2520%252F%252F%2520def%2520B%250A%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES%3D1%26CLOSURE_PASS%3D1%26LANG_IN_IS_ES6%3D1%26MISSING_PROPERTIES%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1%26TRANSPILE%3D1)
- [OTI in externs](https://closure-compiler-debugger.appspot.com/#input0%26input1%26conformanceConfig%26externs%3D%252F**%2520%2540const%2520*%252F%250Avar%2520ns%2520%253D%2520%257B%257D%253B%250A%250A%252F**%250A%2520*%2520%2540type%2520%257B!Object%257D%250A%2520*%252F%250Ans.x%253B%2520%252F%252F%2520def%2520A%250A%250A%252F**%250A%2520*%2520%2540type%2520%257B!Array%257D%250A%2520*%2520%2540suppress%2520%257Bduplicate%257D%250A%2520*%252F%250Ans.x%253B%2520%252F%252F%2520def%2520B%250A%250A%252F**%250A%2520*%2520%2540type%2520%257B!Object%257D%250A%2520*%252F%250Avar%2520y%253B%2520%252F%252F%2520def%2520A%250A%250A%252F**%250A%2520*%2520%2540type%2520%257B!Array%257D%250A%2520*%2520%2540suppress%2520%257Bduplicate%257D%250A%2520*%252F%250Avar%2520y%253B%2520%252F%252F%2520def%2520B%250A%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES%3D1%26CLOSURE_PASS%3D1%26LANG_IN_IS_ES6%3D1%26MISSING_PROPERTIES%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1%26TRANSPILE%3D1)
- [NTI](https://closure-compiler-debugger.appspot.com/#input0%3D%252F**%2520%2540const%2520*%252F%250Avar%2520ns%2520%253D%2520%257B%257D%253B%250A%250A%252F**%250A%2520*%2520%2540type%2520%257B!Object%257D%250A%2520*%252F%250Ans.x%253B%2520%252F%252F%2520def%2520A%250A%250A%252F**%250A%2520*%2520%2540type%2520%257B!Array%257D%250A%2520*%2520%2540suppress%2520%257Bduplicate%257D%250A%2520*%252F%250Ans.x%253B%2520%252F%252F%2520def%2520B%250A%250A%252F**%250A%2520*%2520%2540type%2520%257B!Object%257D%250A%2520*%252F%250Avar%2520y%253B%2520%252F%252F%2520def%2520A%250A%250A%252F**%250A%2520*%2520%2540type%2520%257B!Array%257D%250A%2520*%2520%2540suppress%2520%257Bduplicate%257D%250A%2520*%252F%250Avar%2520y%253B%2520%252F%252F%2520def%2520B%250A%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES%3D1%26CHECK_TYPES_NEW_INFERENCE%3D1%26CLOSURE_PASS%3D1%26LANG_IN_IS_ES6%3D1%26MISSING_PROPERTIES%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1%26TRANSPILE%3D1)
- [NTI in externs](https://closure-compiler-debugger.appspot.com/#input0%26input1%26conformanceConfig%26externs%3D%252F**%2520%2540const%2520*%252F%250Avar%2520ns%2520%253D%2520%257B%257D%253B%250A%250A%252F**%250A%2520*%2520%2540type%2520%257B!Object%257D%250A%2520*%252F%250Ans.x%253B%2520%252F%252F%2520def%2520A%250A%250A%252F**%250A%2520*%2520%2540type%2520%257B!Array%257D%250A%2520*%2520%2540suppress%2520%257Bduplicate%257D%250A%2520*%252F%250Ans.x%253B%2520%252F%252F%2520def%2520B%250A%250A%252F**%250A%2520*%2520%2540type%2520%257B!Object%257D%250A%2520*%252F%250Avar%2520y%253B%2520%252F%252F%2520def%2520A%250A%250A%252F**%250A%2520*%2520%2540type%2520%257B!Array%257D%250A%2520*%2520%2540suppress%2520%257Bduplicate%257D%250A%2520*%252F%250Avar%2520y%253B%2520%252F%252F%2520def%2520B%250A%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES%3D1%26CHECK_TYPES_NEW_INFERENCE%3D1%26CLOSURE_PASS%3D1%26LANG_IN_IS_ES6%3D1%26MISSING_PROPERTIES%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1%26TRANSPILE%3D1)

**Comment by Dominator008** [comment]
@vobruba-martin If the types don't match, the warning cannot be suppressed.

**Comment by vobruba-martin** [comment]
Then I don't understand why @dimvar mentioned my forum topic when created this issue because it is still not possible to do this in externs:

```javascript
/**
 * @type {!ServiceWorkerGlobalScope}
 * @suppress {duplicate}
 */
var self;
```

**Comment by vobruba-martin** [comment]
@Dominator008 Or was it a reaction to my previous comment about checkTypes suppression?

**Comment by Dominator008** [comment]
@vobruba-martin I'm talking about "duplicate". It's still not possible to define conflicting types of the same variable in externs. Is there a legitimate use case for that?

**Comment by vobruba-martin** [comment]
@Dominator008 Yes, if you want to define `self` variable in service worker for example. Or in my last PR #1972 there is a [ExtendableMessageEvent.prototype.source](https://github.com/vobruba-martin/closure-compiler/blob/72e0e4e00b060f5efc060848795569e655947939/externs/browser/w3c_serviceworker.js#L546) and you cannot define the right type if you don't want to retype this chain `ExtendableMessageEvent -> ExtendableEvent -> Event` where `Event` is spread out in multiple files.

**Comment by Dominator008** [comment]
@vobruba-martin In the ServiceWorker case, the `self` variable is technically not in the global scope then?

**Comment by vobruba-martin** [comment]
@Dominator008 It is in the global scope but it is totally different type. It is not `Window` type but `ServiceWorkerGlobalScope` type. Same applies to `navigator` or `location` variables. They all are global variables but not common types and I see no way how to annotate them.

**Comment by Dominator008** [comment]
@vobruba-martin Ah I see, we should probably make NTI "environment aware" and handle these special variables better.
