### ISSUE TITLE
[NTI] "checkTypes" suppression doesn't work when overriding properties

### ISSUE THREAD

**Issue by vobruba-martin** [google/closure-compiler#1973]
Here is a repro

https://closure-compiler-debugger.appspot.com/#input0%3D%252F**%250A%2520*%2520%2540constructor%250A%2520*%252F%250Afunction%2520A()%2520%257B%257D%253B%250A%250A%252F**%2520%2540type%2520%257Bnumber%257D%2520*%252F%250AA.prototype.prop%253B%250A%250A%252F**%250A%2520*%2520%2540constructor%250A%2520*%2520%2540extends%2520%257BA%257D%250A%2520*%252F%250Afunction%2520B()%2520%257B%257D%253B%250A%250A%252F**%250A%2520*%2520%2540type%2520%257Bstring%257D%250A%2520*%2520%2540override%250A%2520*%2520%2540suppress%2520%257BcheckTypes%257D%250A%2520*%252F%250AB.prototype.prop%253B%250A%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES%3D1%26CHECK_TYPES_NEW_INFERENCE%3D1%26CLOSURE_PASS%3D1%26LANG_IN_IS_ES6%3D1%26MISSING_PROPERTIES%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1%26TRANSPILE%3D1

**Comment by realityforge** [comment]
@EatingW NTI was dropped so this issue should be able to be closed

**Comment by EatingW** [comment]
Thanks!
