### ISSUE TITLE
Cannot resolve Promise from the value of type ALL when in new-type-inf mode

### ISSUE THREAD

**Issue by emaxx-google** [google/closure-compiler#1990]
This code:
`goog.Promise.resolve(foo)`
where `foo` is a variable having type `{*}` results in the following error:

> Could not instantiate type VALUE|undefined with *.

Given that the goog.Promise.resolve function is defined to have its parameter with a generic type (`@template VALUE`), my understanding is that it should accept a value of the `ALL` type, but it doesn't.

**Comment by MatrixFrog** [comment]
Added a wiki page about this, among other common pitfalls. https://github.com/google/closure-compiler/wiki/Typechecking-Pitfalls#invariant-generics

**Comment by emaxx-google** [comment]
Thanks, but in my case it fails for the "static" function goog.Promise.resolve:
```
/** @type {*} */
var foo;
goog.Promise.resolve(foo);
//                   ^ ERROR - Could not instantiate type VALUE|undefined with *.

```

**Comment by MatrixFrog** [comment]
I'm not able to repro this, at least in the web service.

https://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540compilation_level%2520ADVANCED_OPTIMIZATIONS%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250A%252F**%2520%2540type%2520%257B*%257D%2520*%252F%250Avar%2520foo%253B%250Agoog.Promise.resolve(foo)%253B

**Comment by emaxx-google** [comment]
This happens only with "--new_type_inf" flag. I don't know whether the web service can be set up to compile in this mode.

**Comment by MatrixFrog** [comment]
I entirely failed to read the title. Thanks!

**Comment by emaxx-google** [comment]
Seems that this bug is now (starting from 20170218) also triggered by the "newCheckTypes" diagnostics.
