### ISSUE TITLE
[NTI] Union of ... would create an impossible type

### ISSUE THREAD

**Issue by vobruba-martin** [google/closure-compiler#1992]
```javascript
/** @type {(function(number):number|function(string):number)} */
var x;
```
```
media/js/test.js:1: WARNING - Union of function(string):number with function(number):number would create an impossible type
/** @type {(function(number):number|function(string):number)} */
            ^
```

This example can be rewritten to ` {(function(number|string):number}` but then you would have to deal with union type `number|string` inside the function. With OTI I get no warning.

**Comment by ChadKillingsworth** [comment]
NTI is doing you a favor - we don't support unions like that.

See #202

**Comment by shicks** [comment]
Just to clarify, your type algebra is incorrect. `(function(a)|function(b))` is *either* a function that takes an `a` or a function that takes a `b`, which is very different from a function that can take an `(a|b)`. The former could possibly fail regardless of which you pass in, while the latter will never fail.

As far as I'm aware, You generally can't safely distribute type unions over functions - neither in parameter types nor in return types.

**Comment by Dominator008** [comment]
@vobruba-martin What you want is probably intersection type: https://flowtype.org/docs/union-intersection-types.html#intersection-example

Unfortunately we don't support this as of now, even in NTI. We do plan to add support for it but it's not a priority in the short term.
