### ISSUE TITLE
Methods transpiled from ES6 should not be enumerable

### ISSUE THREAD

**Issue by kevinoconnor7** [google/closure-compiler#1993]
It seems that enumerability is currently not handled by the compiler when transpiling methods from ES6 to ES5.

Take for example:
```javascript
class Foo {
  static bar() {}
}
Foo.buzz = 10;
for (var key in Foo) console.log(key);
// buzz
```

However, when transpiled the code would be:
```javascript
var Foo = function() {};
Foo.bar = function() {};
Foo.buzz = 10;
for (var key in Foo) console.log(key);
// bar
// buzz
```

Unfortunately making these non-enumerable will probably do terrible things for code size :(

**Comment by MatrixFrog** [comment]
> Unfortunately making these non-enumerable will probably do terrible things for code size :(

Exactly. I think that's why we decided to break from the spec slightly in this case. Is this causing problems for real-world code or is it just something you noticed?

**Comment by kevinoconnor7** [comment]
I ran into it where it was failing a test after we swapped in ES6. It piqued my interest since it only failed when transpiled. However, the original code wasn't exactly doing something nice so we just rewrote it.

**Comment by MatrixFrog** [comment]
Good to hear!
