### ISSUE TITLE
extend interface with generic type

### ISSUE THREAD

**Issue by myphysicslab** [google/closure-compiler#1996]
With new type inference (NTI) I get compile errors that don't occur with OTI. My guess is its because I have two interfaces with generic types where one interface extends another interface. 

Roughly the situation is that interface B extends interface A, and they share the same generic type. But the compiler seems to not know the type of interface A.

Here are relevant code snippets:

``` javascript
    /**
    * @interface
    * @template U
    */
    myphysicslab.lab.util.SubjectEvent = function() {};

    /** Returns the value of this SubjectEvent.
    @return {U} the value of this SubjectEvent
    */
    SubjectEvent.prototype.getValue;

    /**
    @interface
    @template T
    @extends {myphysicslab.lab.util.SubjectEvent<T>}
    */
    myphysicslab.lab.util.Parameter = function() {};

    /** Sets the value of this Parameter.
    @param {T} value the value to set this Parameter to
    */
    Parameter.prototype.setValue;

    /**
    @param {!myphysicslab.lab.util.Subject} subject the Subject whose value this
        ParameterBoolean represents
    @param {function(this: myphysicslab.lab.util.Subject): boolean} getter A method of
        `subject` with no arguments that returns the value of this Parameter
    @constructor
    @implements {myphysicslab.lab.util.Parameter<boolean>}
    */
    myphysicslab.lab.util.ParameterBoolean = function(subject, getter) {
      /**
      @type {!myphysicslab.lab.util.Subject}
      @private
      */
      this.subject_ = subject;
      /**
      @type {function(this:myphysicslab.lab.util.Subject): boolean}
      @private
      */
      this.getter_ = getter;
    };

    /** @inheritDoc */
    ParameterBoolean.prototype.getValue = function() {
      return this.getter_.call(this.subject_);
    };
```

The error with NTI is:

```
./lab/util/ParameterBoolean.js:141: WARNING - Returned type does not match declared return type.
Expected : U
Found    : boolean

  return this.getter_.call(this.subject_);
  ^
```

If I add a second @implements tag to ParameterBoolean like this

```
@implements {myphysicslab.lab.util.SubjectEvent<boolean>}
```

Then I get this error:

```
./lab/util/ParameterBoolean.js:140: WARNING - Interface myphysicslab.lab.util.ParameterBoolean has a property getValue with incompatible types in its super interfaces: [function():boolean, function():U]
ParameterBoolean.prototype.getValue = function() {
^
```

The attached zip file is a directory with all needed files and build instructions.

[test20160904-2.zip](https://github.com/google/closure-compiler/files/454156/test20160904-2.zip)

**Comment by myphysicslab** [comment]
FYI, I've modified these classes to not use generic types and my code is now compiling clean with NTI (except for 70 errors in closure library).  So this is no longer an important issue for me -- it's OK with me to close this issue.

I suspect my usage of generic types was incorrect.  I've come to understand that without bounded generics, one is extremely limited about what can be done with generic types currently.  They are suitable for collection classes, but that's about all.  A collection class can treat the generic type as an unknown and never actively try to use the objects of that unknown type, beyond storing them in arrays or such.

**Comment by dimvar** [comment]
Using `inheritDoc` for `ParameterBoolean#getValue` is not correct, because then its jsdoc contains `@return {U}`. You should declared its return type to be boolean explicitly.

**Comment by dimvar** [comment]
After doing that, is there any remaining warning that seems strange? If not, we can close this issue.

**Comment by myphysicslab** [comment]
That does fix the warnings, but then we are not inheriting the generic type.  For example:

```javascript
/** Returns the value of this ParameterBoolean.
@return {boolean} the value of this ParameterBoolean
*/
ParameterBoolean.prototype.getValue = function() {
  return this.getter_.call(this.subject_);
};
```

This goes against what is described here:
https://github.com/google/closure-compiler/wiki/Generic-Types
In the section "Inheritance of Generic Types".  From my reading of that I would expect the code shown above to work.

**Comment by dimvar** [comment]
The constructor implements the instantiated interface, so it's expected that the type variables in the interface should be replaced in the methods of `ParameterBoolean`.

However, while trying to create some related examples, I noticed that this happens automatically if a method is directly inherited, but not when it's inherited from two levels up. So, that's a discrepancy that should be fixed in NTI. We should either warn in both cases, or use the instantiated type in both cases. (Most probably the latter.)

    /**
     * @interface
     * @template T
     */
    function High() {}
    
    /** @return {T} */
    High.prototype.method1 = function() {};
    
    /** @return {T} */
    High.prototype.method2 = function() {};
    
    /**
     * @interface
     * @template T
     * @extends {High<T>}
     */
    function Mid() {}
    
    /** @return {T} */
    Mid.prototype.method1 = function() {};
    
    /**
     * @constructor
     * @implements {Mid<number>}
     */
    function Low() {}
    
    /** @inheritDoc */
    Low.prototype.method1 = function() {
      return 1;
    };
    
    /** @inheritDoc */
    Low.prototype.method2 = function() {
      return 2;
    };
    
    var /** null */ n;
    
    n = Low.prototype.method1; // function(this:Low):number
    n = Low.prototype.method2; // function(this:Low):T
