### ISSUE TITLE
divide-by-zero never checked

### ISSUE THREAD

**Issue by xylosper** [google/closure-compiler#1997]
I have run google closure compiler for next:

```js
alert(1 / 0);
```

with command:

```
java -jar node_modules\google-closure-compiler\compiler.jar --warning_level=VERBOSE test.js 
```

and it does not report anything.

I expected it says something about devide-by-zero because the reference(https://developers.google.com/closure/compiler/docs/error-ref) mentions about

>`JSC_DIVIDE_BY_0_ERROR`:

>Divide by 0

>This error means that you an arithmetical division expression with a denominator of 0. Dividing by zero at runtime produces a runtime error.

I've tried a short grep in this repository with `JSC_DIVIDE_BY_0_ERROR` but it hits nothing.
For comparison, I've also tried to find `JSC_BITWISE_OPERAND_OUT_OF_RANGE` and I could find it in `src/com/google/javascript/jscomp/PeepholeFoldConstants.java` file.

Apprently, `JSC_DIVIDE_BY_0_ERROR` does not even exists in source code.

Does closure compiler actually support checking for divide-by-zero, or not? If it does, what am I missing?

**Comment by ChadKillingsworth** [comment]
That check was removed a long time ago: 25829b0395164533782d608399096803321225a7
