### ISSUE TITLE
Thread unsafe and/or memory leak due to static members

### ISSUE THREAD

**Issue by supersteves** [google/closure-compiler#2004]
@dimvar's recent commit removes some static and thread unsafe members: https://github.com/google/closure-compiler/commit/cc1ea4c4a1f67dd637de504d8e96dd5f873e5667#commitcomment-18707738

Here's another potential issue:

https://github.com/google/closure-compiler/blob/master/src/com/google/javascript/jscomp/newtypes/JSType.java#L240

JsType.TOP_OBJECT, among others, is another case. This retains a bunch of stuff related to a past compilation and is thus probably thread unsafe. Examining a memory dump after compilation was long finished showed this retention path:

com.google.javascript.jscomp.newtypes.JSType.TOP_OBJECT
com.google.javascript.jscomp.newtypes.ObjsType.commonTypes
com.google.javascript.jscomp.newtypes.JSTypes.builtinFunction
com.google.javascript.jscomp.newtypes.RawNominalType.defSite
com.google.javascript.rhino.Node.typei
com.google.javascript.rhino.jstype.FunctionType.registry
com.google.javascript.rhino.jstype.JSTypeRegistry.reporter
com.google.javascript.jscomp.RhinoErrorReporter$OldRhinoErrorReporter.compiler

and thus retains the Compiler plus all its modules+sources, AST nodes etc.

also see https://github.com/google/closure-compiler/issues/1925 and https://github.com/google/closure-compiler/issues/1822

In practice if not doing concurrent compilation this might not matter, but it seems bad practice for AST nodes from a prior compilation to potentially bleed into subsequent compilations.

**Comment by dimvar** [comment]
I have a fix pending for this.
