### ISSUE TITLE
Feature Request : More control over SourceFile.getName() from CommandLineCompiler for JSConformance compatibility

### ISSUE THREAD

**Issue by mikesamuel** [google/closure-compiler#2006]
The [source file name](https://github.com/google/closure-compiler/blob/cf3c1f5ba45d3154c80ce5eecbec45549e8641f6/src/com/google/javascript/rhino/StaticSourceFile.java#L47-L50) is used to [check](https://github.com/google/closure-compiler/blob/05846a2161ecdc2c0572b6ea7feca321d7944076/src/com/google/javascript/jscomp/ConformanceRules.java#L173) whether a JSConfomance rule is applicable.

I'm writing tools that use the `CommandLineRunner`.  JS inputs are passed as flags that thread through to [`createInputs`](https://github.com/google/closure-compiler/blob/cf3c1f5ba45d3154c80ce5eecbec45549e8641f6/src/com/google/javascript/jscomp/AbstractCommandLineRunner.java#L661) where the flag value is used as the filename.

I ran into a problem where I have a bunch of generated JavaScript source files.  Those are sometimes in a temp directory like `/tmp/hjsdfgdsgygd675g7sd/target/generated-sources/src/main/js/...`.  Even when no temp directory is involved, I have no control over the working directory so end up passing canonical file paths which contain details about where the user cloned the project containing the conformance.proto.

I'd like a way to be able to specify that source files are relative to some root directory so that the conformance pass sees a stable relative file path regardless of how generated sources are moved around.

*StaticSourceFile.java* says
```java
  /**
   * The name of the file. Must be unique across all files in the compilation.
   */
  String getName();
```

so I was thinking that, we can just error out when we encounter 2 full paths that map to the same relative path.

I can think of two conventions for specifying the relationship between full paths and relative paths.

1. Extend CommandLineConfig with a `List<String> sourceRoots` and the root, if any, for a source file is the longest root which (suffixed with '/') is a prefix of the full path
2. Adopt a convention that `/path/to/root////relative/path.js` has relative path `relative/path.js` under root `/path/to/root/` because of the repeated file separators.

I'm fine with this being ignored when `--conformance_configs` is unspecified.

**Comment by ChadKillingsworth** [comment]
If you use the --json_streams flag and pipe your source into the compiler via stdin, you have full control over path names. The gulp plugin anchors paths to the compiler root folder for instance. See #1253 for the full discussion of the feature.

**Comment by jart** [comment]
This is sort of like what the `--js_module_root` flag does. could it be generalized to work for conformance too?

**Comment by mikesamuel** [comment]
@ChadKillingsworth, @jart, thanks for explaining.  I'm going to close this as invalid and look into those flags more.  It sounds like `--json_streams` will give me the fine-grained control I want.

**Comment by jart** [comment]
@mikesamuel What is `--json_streams`?

**Comment by ChadKillingsworth** [comment]
@jart See #1253
