### ISSUE TITLE
unable to use @abstract on a constructor

### ISSUE THREAD

**Issue by myphysicslab** [google/closure-compiler#2010]
I'm trying out the new `@abstract` tag in constructor of an abstract class but get

    ERROR - Misplaced @abstract annotation. 
    function with a non-empty body cannot be abstract

But an abstract constructor should be allowed to have a non-empty body.  If I remove `@abstract` from the constructor but leave it on the methods then I get:

    ERROR - Abstract methods can only appear in abstract classes. 
    Please declare the class as @abstract

Here is the declaration of the constructor

```javascript
/** An abstract base class for a ParametricPath.

This is package-private to ensure that any changes to it are coordinated
with all it's subclasses.

* @param {string} name language independent name
* @param {string} localName localized (internationalized) name
* @param {number} startTValue starting `t` value for defining path
* @param {number} finishTValue  ending `t` value for defining path
* @param {boolean} closedLoop `true` means the path is a closed loop
* @abstract
* @constructor
* @struct
* @package
* @implements {myphysicslab.lab.model.ParametricPath}
*/
myphysicslab.sims.roller.AbstractPath = function(name, localName, startTValue,
    finishTValue, closedLoop) {
```

I've tried this with the latest pre-built compiler:

    java -jar ../compiler-latest/closure-compiler-v20160822.jar --version
    Closure Compiler (http://github.com/google/closure-compiler)
    Version: v20160822
    Built on: 2016-08-23 13:31

I also tried to check out the latest code and build but I'm getting this error

```
[INFO] --- gwt-maven-plugin:1.0-rc-4:compile (default-compile) @ closure-compiler-gwt ---
[INFO] Compiling module com.google.JsComp
[INFO]    Tracing compile failure path for type 'com.google.debugging.sourcemap.SourceMapObjectParserJs'
[INFO]       [ERROR] Errors in 'file:/Users/erikn/Documents/Programming/closure-compiler/src/com/google/debugging/sourcemap/SourceMapObjectParserJs.java'
[INFO]          [ERROR] Line 78: The method builder() is undefined for the type SourceMapObject
[INFO]          [ERROR] Line 78: SourceMapObject.Builder cannot be resolved to a type
[INFO]    [ERROR] Aborting compile due to errors in some input files
```

That is based on this commit:

```
commit 851fabca660b95139939de905873e60eadc117da
Author: imokharau <imokharau@google.com>
Date:   Mon Sep 12 14:44:33 2016 -0700

    Adding Object as a valid type of the "require" property.
    
    -------------
    Created by MOE: https://github.com/google/moe
    MOE_MIGRATED_REVID=132920843
```

**Comment by Dominator008** [comment]
While we fix the open source GWT build, you can run `mvn -DskipTests -pl "!pom-gwt.xml"` to skip it.

**Comment by Dominator008** [comment]
The issue has been fixed by https://github.com/google/closure-compiler/commit/bd774e25ca187b7ae31687fc87a4fa32893883aa. The Maven GWT build can be fixed by running `mvn clean`. Your Maven cache is stale because we deleted a super source in https://github.com/google/closure-compiler/commit/24a4540ba13ca930397265e3f4dd4a42e3372de1.
