### ISSUE TITLE
Recursive type definitions

### ISSUE THREAD

**Issue by jart** [google/closure-compiler#2011]
In TypeScript, I can do the following

```ts
interface RecursiveArray<T> extends Array<T|RecursiveArray<T>> {}
```

But in Closure, I can't do this:

```js
/**
 * @typedef {!Array<T|RecursiveArray<T>>}
 * @template T
 */
var RecursiveArray;
```

**Comment by dimvar** [comment]
You can define recursive structural types with `@record`. Typedefs can only be used to define an alias for an existing type, not to define a new type.

**Comment by jart** [comment]
Amazing!
