### ISSUE TITLE
Add extern for the new Node.getRootNode API

### ISSUE THREAD

**Issue by dvoytenko** [google/closure-compiler#2018]
See https://dom.spec.whatwg.org/#dom-node-getrootnode

Important for Shadow DOM support.

**Comment by Dominator008** [comment]
Consider submitting a change internally? :)

**Comment by dvoytenko** [comment]
@Dominator008 Could you clarify this? We already added this extern to our project.

**Comment by Dominator008** [comment]
@dvoytenko I meant adding this to the compiler project, but it seems like you figured it out :)

**Comment by dvoytenko** [comment]
@Dominator008 submitted internally. Over to you.

**Comment by Dominator008** [comment]
Great. Thanks!

**Comment by MatrixFrog** [comment]
Thanks. This will get closed automatically the next time MOE runs (probably Monday at the latest)
