### ISSUE TITLE
NTI fails to detect missing property / OTI errors correctly

### ISSUE THREAD

**Issue by hochhaus** [google/closure-compiler#2021]
I'm using idom soy templates with the compiler. When a template invocation omits a required template parameter OTI results in a compile time error (as expected). However, NTI (`--new_type_inf`) compiles the code without error (which is undesired behavior).

``` sh
ahochhaus@ahochhaus-pc:~/Downloads$ cat template.soy.js 
```

``` js
goog.module('example.template');

/**
 * @param {{top: boolean}} data
 */
exports.hello = function(data) {};
ahochhaus@ahochhaus-pc:~/Downloads$ cat incremental-dom-closure.js 
goog.module('incrementaldom');

/**
 * @param {function(!function(T),T=)} run
 * @return {function(!function(T),T=)}
 * @template T
 */
const patchFactory = function(run) {
  /**
   * @param {!function(T)} fn
   * @param {T=} data
   * @template T
   */
  const f = function(fn, data) {
    run(fn, data);
  };
  return f;
};


/**
 * @param {!function(T)} fn
 * @param {T=} data
 * @template T
 */
exports.patchInner = patchFactory(function(fn, data) {
  fn(data);
});
ahochhaus@ahochhaus-pc:~/Downloads$ cat app.js 
goog.module('example.app');

const idom = goog.require('incrementaldom');
const tmpl = goog.require('example.template');

idom.patchInner(tmpl.hello, {});
```

``` sh
ahochhaus@ahochhaus-pc:~/Downloads$ java -jar closure-compiler-v20160911.jar --compilation_level=ADVANCED --warning_level=VERBOSE --jscomp_error=* --language_in=ECMASCRIPT6_STRICT --language_out=ECMASCRIPT5_STRICT --dependency_mode=LOOSE --hide_warnings_for=incremental-dom-closure.js --entry_point=goog:example.app --js template.soy.js --js incremental-dom-closure.js --js app.js
app.js:6: ERROR - actual parameter 1 of module$exports$incrementaldom.patchInner does not match formal parameter
found   : function ({top: boolean}): undefined
required: function (({top: (boolean|undefined)}|{top: boolean})): ?
idom.patchInner(tmpl.hello, {});
                ^

1 error(s), 0 warning(s), 92.3076923076923% typed
ahochhaus@ahochhaus-pc:~/Downloads$ java -jar closure-compiler-v20160911.jar --compilation_level=ADVANCED --warning_level=VERBOSE --jscomp_error=* --language_in=ECMASCRIPT6_STRICT --language_out=ECMASCRIPT5_STRICT --dependency_mode=LOOSE --hide_warnings_for=incremental-dom-closure.js --entry_point=goog:example.app --js template.soy.js --js incremental-dom-closure.js --js app.js --new_type_inf
'use strict';(function(a){return function(b,c){a(b,c)}})(function(a,b){a(b)})(function(){},{});
ahochhaus@ahochhaus-pc:~/Downloads$ sed -i 's/{}/{top:true}/' app.js
ahochhaus@ahochhaus-pc:~/Downloads$ java -jar closure-compiler-v20160911.jar --compilation_level=ADVANCED --warning_level=VERBOSE --jscomp_error=* --language_in=ECMASCRIPT6_STRICT --language_out=ECMASCRIPT5_STRICT --dependency_mode=LOOSE --hide_warnings_for=incremental-dom-closure.js --entry_point=goog:example.app --js template.soy.js --js incremental-dom-closure.js --js app.js
'use strict';(function(a){return function(b,c){a(b,c)}})(function(a,b){a(b)})(function(){},{top:!0});
ahochhaus@ahochhaus-pc:~/Downloads$ java -jar closure-compiler-v20160911.jar --compilation_level=ADVANCED --warning_level=VERBOSE --jscomp_error=* --language_in=ECMASCRIPT6_STRICT --language_out=ECMASCRIPT5_STRICT --dependency_mode=LOOSE --hide_warnings_for=incremental-dom-closure.js --entry_point=goog:example.app --js template.soy.js --js incremental-dom-closure.js --js app.js --new_type_inf
'use strict';(function(a){return function(b,c){a(b,c)}})(function(a,b){a(b)})(function(){},{top:!0});
```

The [upstream code](https://github.com/google/incremental-dom/blob/master/src/core.js#L59) lives here.

**Comment by dimvar** [comment]
What is the omitted template parameter you're referring to in this example?

**Comment by hochhaus** [comment]
In this example it is `top` which is of type `bool`. I can provide a higher level example with `*.soy` files and all of the code as well but I thought it might be harder to debug that way.

**Comment by dimvar** [comment]
I simplified the example to this:

    /**
     * @param {!function(T)} fn
     * @param {T=} data
     * @template T
     */
    function patchInner(fn, data) {}
    
    /**
     * @param {{top: boolean}} data
     */
    function hello(data) {};
    
    patchInner(hello, {});

The [warning](https://jscomp-debug.googleplex.com/#input0%3D%252F**%250A%2520*%2520%2540param%2520%257B!function(T)%257D%2520fn%250A%2520*%2520%2540param%2520%257BT%253D%257D%2520data%250A%2520*%2520%2540template%2520T%250A%2520*%252F%250Afunction%2520patchInner(fn%252C%2520data)%2520%257B%257D%250A%250A%252F**%250A%2520*%2520%2540param%2520%257B%257Btop%253A%2520boolean%257D%257D%2520data%250A%2520*%252F%250Afunction%2520hello(data)%2520%257B%257D%253B%250A%250ApatchInner(hello%252C%2520%257B%257D)%253B%250A%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES%3D1%26CLOSURE_PASS%3D1%26MISSING_PROPERTIES%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1%26TRANSPILE%3D1) by the old type checker is

    input0:13: WARNING - actual parameter 1 of patchInner does not match formal parameter
    found   : function ({top: boolean}): undefined
    required: function (({top: (boolean|undefined)}|{top: boolean})): ?
    patchInner(hello, {});
               ^

And the new type inference [also gives a warning](https://jscomp-debug.googleplex.com/#input0%3D%252F**%250A%2520*%2520%2540param%2520%257B!function(T)%257D%2520fn%250A%2520*%2520%2540param%2520%257BT%253D%257D%2520data%250A%2520*%2520%2540template%2520T%250A%2520*%252F%250Afunction%2520patchInner(fn%252C%2520data)%2520%257B%257D%250A%250A%252F**%250A%2520*%2520%2540param%2520%257B%257Btop%253A%2520boolean%257D%257D%2520data%250A%2520*%252F%250Afunction%2520hello(data)%2520%257B%257D%253B%250A%250ApatchInner(hello%252C%2520%257B%257D)%253B%250A%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES%3D1%26CHECK_TYPES_NEW_INFERENCE%3D1%26CLOSURE_PASS%3D1%26MISSING_PROPERTIES%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1%26TRANSPILE%3D1) here

    input0:13: WARNING - Invalid type for parameter 1 of function patchInner.
    Expected : function(Object):?
    Found    : function({top:boolean}):undefined
    More details:
    The expected and found types are functions which have incompatible types for argument 1.
    Expected a supertype of : Object
    but found               : {top:boolean}
    patchInner(hello, {});
               ^

**Comment by dimvar** [comment]
The old type checker has a weird behavior where it keeps record types unmerged in unions sometimes, eg, this one: `{top: (boolean|undefined)}|{top: boolean}`. Also, it instantiates generics in a weird way. 

The type of patchInner says, data is optional but if you pass it, its type is T. So, in the call to patchInner, the type of data is the empty object, and the warning of the new type checker is more representative IMO.
