### ISSUE TITLE
Compilation Bug using const 

### ISSUE THREAD

**Issue by f-e-r-o** [google/closure-compiler#2023]
Using closure compiler to transpile from ES6 to ES5, the order of a comma-separated list of constants gets flipped, f.e.

```js
const c1 = "foo", c2 = c1.doSomething();
```

will be transpiled to

```js
var c2 = c1.doSomething(), c1 = "foo";
```

Well, I am pretty confused nobody reported this bug so far (at least I couldn't find any issue here), so maybe there are more conditions to be met. I am currently using version v20160208 of closure compiler. The compilation level seems to be irrelevant. Anyone can confirm this issue?

**Comment by Dominator008** [comment]
I believe this was fixed in https://github.com/google/closure-compiler/pull/1660/commits/6398a1d5a132ffc6aa164730ec41e93f5246bf9b. Could you try upgrading?
