### ISSUE TITLE
type references between CommonJS modules are not recognized

### ISSUE THREAD

**Issue by vandenoever** [google/closure-compiler#2030]
According to the [wiki](https://github.com/google/closure-compiler/wiki/JS-Modules#type-references), it should be possible to reference types from other modules:
```js
var A = require('a').A;
/**@type{A}*/
var a = new A();
```
```js
var a = require('a');
/**@type{a.A}*/
var my_a = new a.A();
```
This seems to be broken in Closure Compiler 20160911. The files and command below can be used to reproduce the problem.

`a.js`
```js
/**
 * @constructor
 * @param {!number} size
 */
function A(size) {
    this.size = size;
}
exports.A = A;
```
`b.js`
```js
var A = require('a').A;

/**
 * @constructor
 * @param {!A} a1
 */
function B(a1) {
    this.a1 = a1;
    this.a2 = new A(10);
}
exports.B = B;
```
`c.js`
```js
var b = require('b');
var a = require('a');
new b.B(new a.A(10));
```
```bash
$ java -jar compiler.jar --process_common_js_modules --jscomp_error checkTypes \
    --entry_point c.js --js a.js --js b.js --js c.js --js_output_file out.js
b.js:5: ERROR - Bad type annotation. Unknown type A$$module$b
 * @param {!A} a1
            ^
1 error(s), 0 warning(s)
```

**Comment by ChadKillingsworth** [comment]
The imports need to be constants for this to work:

```js
/** @const */
var A = require('a').A;
```

**Comment by vandenoever** [comment]
I changed `b.js` as you indicated and still get the same error.

**Comment by Dominator008** [comment]
@vandenoever Did you change 'c.js' as well?

**Comment by ChadKillingsworth** [comment]
Also, the require statements have to be relative or absolute paths:

```js
/** @const */
var A = require('./a').A;
```

**Comment by vandenoever** [comment]
I have. I'm using relative paths now. Leaving out the `./` did not hinder compilations without the `@param` annotation. Using `@const` and paths that start with `./` does not fix the issue for me.
I'm running Linux 4.4 with OpenJDK 1.8.0.
I've tried both `var A = require('./a').A;` with `@param {A}` and `var a = require('./a');` with `@param {a.A}`. `@param {./a.A}` is also not recognized.

**Comment by vandenoever** [comment]
This is the test code with your hints applied.
`a.js`
```js
/**
 * @constructor
 * @param {!number} size
 */
function A(size) {
    this.size = size;
}
exports.A = A;
```
`b.js`
```js
/** @const */
var A = require('./a').A;

/**
 * @constructor
 * @param {A} a1
 */
function B(a1) {
    this.a1 = a1;
    this.a2 = new A(10);
}
exports.B = B;
```
`c.js`
```js
/** @const */
var b = require('./b');
/** @const */
var a = require('./a');
new b.B(new a.A(10));
```
```bash
java -jar compiler.jar --process_common_js_modules --jscomp_error checkTypes \
    --entry_point c.js --js a.js --js b.js --js c.js --js_output_file out.js
b.js:6: ERROR - Bad type annotation. Unknown type A$$module$b
 * @param {A} a1
           ^
1 error(s), 0 warning(s)
```

**Comment by vandenoever** [comment]
Is there a module system where this does work in Closure Compiler, perhaps with an example?

**Comment by Dominator008** [comment]
@vandenoever I think `goog.module` should work, although technically CommonJS should also work.

**Comment by ChadKillingsworth** [comment]
I'll take a look this weekend with the repo case posted.

**Comment by ChadKillingsworth** [comment]
So this is super tricky and not at all obvious: the export must be const.

```js
/**
 * @constructor
 * @param {!number} size
 */
function A(size) {
  this.size = size;
}
/** @const */
exports.A = A;
```

Also, the entry point is a module name - not a file name:

```
java -jar compiler.jar --process_common_js_modules --jscomp_error checkTypes \
    --entry_point=c --js a.js --js b.js --js c.js --js_output_file out.js
```

**Comment by vandenoever** [comment]
That works fine. It's indeed not so obvious. I'm happy that it works now.
This issues can hopefully help others to use CommonJS with Closure Compiler.

**Comment by ChadKillingsworth** [comment]
The `@const` is automatically added to `module.exports`, but apparently not just `exports`. I have work in progress that should make this smoother.

**Comment by vandenoever** [comment]
I've found another case where type exporting does not work. Here are a working `goog` version and a corresponding CommonJS modules version which does not work.
# goog modules
`a.js`
```js
goog.provide("a");
/**
 * @constructor
 */
a.A1 = function() {}
/**
 * @constructor
 */
a.A2 = function() {}
/**@typedef{Object.<string,string>}*/
a.A3;
```
`b.js`
```js
goog.provide("b");
goog.require("a");

/**
 * @constructor
 * @param {a.A1} a1
 */
b = function(a1) {
    this.a1 = a1;
    this.a2 = new a.A2();
    /**@type{!a.A3}*/
    this.a3 = {};
}
```
```bash
java -jar compiler.jar --entry_point goog:b --js_output_file out.js --jscomp_error checkTypes a.js b.js
```
# CommonJS
`a.js`
```js
/**
 * @constructor
 */
function A1() {}
/**
 * @constructor
 */
function A2() {}
/**@typedef{Object.<string,string>}*/
var A3;
/**@const*/
exports = {
    A1: A1,
    A2: A2,
    A3: A3
};
```
`b.js`
```js
var a = require('./a');

/**
 * @constructor
 * @param {a.A1} a1
 */
b = function(a1) {
    this.a1 = a1;
    this.a2 = new a.A2();
    /**@type{!a.A3}*/
    this.a3 = {};
}
/**@const*/
exports.B = B;
```
```bash
$ java -jar compiler.jar --process_common_js_modules --entry_point b --js_output_file out.js \
    --jscomp_error checkTypes a.js b.js
b.js:5: ERROR - Bad type annotation. Unknown type a$$module$b.A1
 * @param {a.A1} a1
           ^

b.js:10: ERROR - Bad type annotation. Unknown type a$$module$b.A3
    /**@type{!a.A3}*/
              ^

2 error(s), 0 warning(s)
```

**Comment by ChadKillingsworth** [comment]
That is not a valid way to export common js symbols. You didn't export anything - you just redefined the `exports` variable. This is one of the reasons commonjs rewriting is hard for the compiler. Here's your test case in NodeJS:

**a.js**
```js
/**
 * @constructor
 * @param {!number} size
 */
function A(size) {
  this.size = size;
}
exports = { // This assignment is wrong - it doesn't actually export
  A: A
};
```

**c.js**
```js
/** @const */
var a = require('./a');

console.log((new a.A(4)).size);
```

**output**
```
$ node c.js
/Users/chad/git/closure-compiler/c.js:5
console.log((new a.A(4)).size);
             ^

TypeError: a.A is not a constructor
    at Object.<anonymous> (/Users/chad/git/closure-compiler/c.js:5:14)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Function.Module.runMain (module.js:575:10)
    at startup (node.js:160:18)
    at node.js:456:3
```

See https://nodejs.org/docs/latest/api/modules.html#modules_module_exports

**Comment by vandenoever** [comment]
Ok, good to know. I tried some variations also does not work. I've ported quite some code from a custom module system to CommonJS with Closure Compiler now. The `@typedef` is where I'm currently stuck.
```js
/**@typedef{Object.<string,string>}*/
var A3;
modules.export.A1 = A1;
modules.export.A2 = A2;
modules.export.A3 = A3;
```

**Comment by ChadKillingsworth** [comment]
I haven't tried exporting typedefs personally, but I seem to remember someone else complaining it's a problem. Typedefs are kind of weird because they are just type information to the compiler.

Regardless, your test case should look something more like:

```js
/**@typedef{Object.<string,string>}*/
var A3;
module.exports.A1 = A1;
module.exports.A2 = A2;
module.exports.A3 = A3;
```

But again, I don't know if that actually works or not.

**Comment by vandenoever** [comment]
Right, the `modules.export` instead of `module.exports` was a typo in the comment, not in the code I tested. `@typedefs` indeed do not work. I might be able to work around that by copying the definition in the modules that use the type.
Shall I open a separate issue for `@typedef`?
