### ISSUE TITLE
Tighten Types With Array.isArray

### ISSUE THREAD

**Issue by ChadKillingsworth** [google/closure-compiler#2031]
```js
/** @type {*} */
var foo = null;

if (Array.isArray(foo)) {
  console.log(foo.length); // foo is guaranteed to be an array
}
```

**Comment by Dominator008** [comment]
I thought https://github.com/google/closure-compiler/commit/023d516e660616140f648060d00f96ef214726d3 fixed it already. Is that not the case?

**Comment by Dominator008** [comment]
Assigning `foo` to `null` causes the problem. OTI thinks `foo` is proven to be `null` in the `if` branch. The following works:
```js
/** @type {*} */
var foo;

if (Array.isArray(foo)) {
  console.log(foo.length); // foo is guaranteed to be an array
}
```

**Comment by ChadKillingsworth** [comment]
Ahh thanks.
