### ISSUE TITLE
super.x() not handled correctly in static methods.

### ISSUE THREAD

**Issue by brad4d** [google/closure-compiler#2037]
This code generates a compiler error.

```
class C {
static foo() {console.log('C.foo');}
}

class D {
static foo() {
super.foo();
console.log('D.foo');
}
}

D.foo();
```

```
input0:7: ERROR - super() not allowed except in the constructor of a subclass
super.foo();
^

1 error(s), 0 warning(s)
```

https://closure-compiler-debugger.appspot.com/#input0%3Dclass%2520C%2520%257B%250Astatic%2520foo()%2520%257Bconsole.log('C.foo')%253B%257D%250A%257D%250A%250Aclass%2520D%2520%257B%250Astatic%2520foo()%2520%257B%250Asuper.foo()%253B%250Aconsole.log('D.foo')%253B%250A%257D%250A%257D%250A%250AD.foo()%253B%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES%3D1%26CLOSURE_PASS%3D1%26LANG_IN_IS_ES6%3D1%26MISSING_PROPERTIES%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1%26TRANSPILE%3D1

**Comment by ChadKillingsworth** [comment]
You are missing an `extends`:

https://closure-compiler-debugger.appspot.com/#input0%3Dclass%2520C%2520%257B%250Astatic%2520foo()%2520%257Bconsole.log('C.foo')%253B%257D%250A%257D%250A%250Aclass%2520D%2520extends%2520C%257B%250Astatic%2520foo()%2520%257B%250Asuper.foo()%253B%250Aconsole.log('D.foo')%253B%250A%257D%250A%257D%250A%250AD.foo()%253B%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES%3D1%26CLOSURE_PASS%3D1%26LANG_IN_IS_ES6%3D1%26MISSING_PROPERTIES%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1%26TRANSPILE%3D1

**Comment by brad4d** [comment]
oops, thx
