### ISSUE TITLE
Support @record member variables defined within the type

### ISSUE THREAD

**Issue by grandin-j** [google/closure-compiler#2040]
The current way of writing @record types with members is a bit verbose:

```javascript
/** @record */
const ObjectLiteral = function() {};
/** @export {boolean} */
ObjectLiteral.prototype.foo;
/** @export {number} */
ObjectLiteral.prototype.bar;
```

It'd be nice if putting the members inside were supported like this:

```javascript
/** @record */
const ObjectLiteral = function() {
  /** @export {boolean} */
  this.foo;
  /** @export {number} */
  this.bar;
};
```

Once [class public fields](https://tc39.github.io/proposal-class-public-fields/) are supported, the format could be even better:

```javascript
/** @record */
const ObjectLit = class {
  /** @export {boolean} */ foo;
  /** @export {number} */ bar;
}
```

**Comment by Dominator008** [comment]
For your example, I think `@typedef` should work:
```js
/**
 * @typedef {{
 *   foo: boolean,
 *   bar: number
 * }}
 */
var ObjectLiteral;
```
But I agree that maybe we should have a less verbose way with `@record`.

**Comment by grandin-j** [comment]
@typedef doesn't work because the members are @exported. I could put it in an externs file but I've found those can get unwieldy and it feels odd when the types aren't truly external since they're part of my app. This comes up when dealing with frameworks such as angular and when passing json between the client and server.

**Comment by ChadKillingsworth** [comment]
But they are conforming to an external interface - namely the JSON the server expects or sends. The interface is external even if your code references are not.

These should definitely be externs.

**Comment by grandin-j** [comment]
That's fair on the JSON side but when working with angular, externs don't make as much sense. There are expressions in the html templates and the names in those expressions need to match the js identifiers. The templates really act and feel like part of the application code and not something external. In any case, unless you're arguing against record types in general, I just feel that the suggested syntax feels much more natural for any record use case involving properties.

**Comment by ChadKillingsworth** [comment]
Unless you somehow [compile your templates with the code](https://github.com/Banno/polymer-rename), they are indeed external references. Exporting members of a record though is definitely not how I would ever approach the problem.

**Comment by grandin-j** [comment]
The use cases really are irrelevant. Clearly you have some issues with mine. Regardless, I think the suggested syntax is an improvement.

**Comment by blickly** [comment]
I was pleasantly surprised to find that it looks like this already works:
http://closure-compiler-debugger.appspot.com/#input0%3D%252F**%2520%2540record%2520*%252F%250Afunction%2520Baz()%2520%257B%250A%2520%2520%2520%252F**%2520%2540type%2520%257Bnumber%257D%2520*%252F%2520this.x%253B%250A%257D%250A%250A%250Avar%2520%252F**%2520!Baz%2520*%252F%2520y%2520%253D%2520%257B%2520x%2520%253A%2520'string'%2520%257D%253B%250Avar%2520%252F**%2520!Baz%2520*%252F%2520z%2520%253D%2520%257B%257D%253B%250Avar%2520%252F**%2520!Baz%2520*%252F%2520noproblem%2520%253D%2520%257B%2520x%2520%253A%252077%2520%257D%253B%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES%3D1%26CLOSURE_PASS%3D1%26LANG_IN_IS_ES6%3D1%26MISSING_PROPERTIES%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1%26TRANSPILE%3D1
