### ISSUE TITLE
polymer_pass behavior error

### ISSUE THREAD

**Issue by tucamsam** [google/closure-compiler#2042]
I seem to be getting this error about our behavior definitions:

```
ERROR - Behaviors must be global names or qualified names that are declared as object literals or array literals of other valid Behaviors.
            behaviors: [MyNamespace.CustomBehavior],
                        ^
```

And they're defined as described in the Polymer documentation:

``` js
window.MyNamespace = window.MyNamespace || {};
/**
 *
 * @polymerBehavior
 */
MyNamespace.CustomBehavior = {
    // Behavior Definition
};
```

Is this a parse/compile issue or am I doing it wrong?

**Comment by MatrixFrog** [comment]
`MyNamespace.CustomBehavior` is a qualified name so that looks like a bug. Maybe try replacing

`window.MyNamespace = window.MyNamespace || {};`

with

`var MyNamespace = MyNamespace || {};`

as a workaround?

**Comment by tucamsam** [comment]
I ended up with that code because I was getting this error:

```
ERROR - Variable MyNamespace first declared in /index.js
var MyNamespace = MyNamespace || {};
    ^
```

**Comment by ChadKillingsworth** [comment]
Two ways to solve this:

```js
window.MyNamespace = window.MyNamespace || {};
/**
 *
 * @polymerBehavior
 */
window.MyNamespace.CustomBehavior = {
    // Behavior Definition
};
```

OR

```
var MyNamespace = typeof MyNamespace === 'undefined' ? {} || MyNamespace;
```

**Comment by tucamsam** [comment]
Unfortunately, neither of suggestions seem to fix it. The first suggestion continues to throw the first error I described, and the second suggestion throws the second error I described (albeit with slightly different code underneath)

**Comment by ChadKillingsworth** [comment]
Oh right - you have the backwards case I do. I needed to handle cases where it wasn't defined. I think you could add a suppress to it.

```js
/** @suppress {duplicate} */
var MyNamespace = typeof MyNamespace === 'undefined' ? {} || MyNamespace;
```

The Polymer Pass has some odd quirks. I think most of those should be dealt with in Polymer 2 though (at least that's my hope).

**Comment by kaspnilsson** [comment]
@tucamsam, @ChadKillingsworth, I'm experiencing this same issue in my Polymer project, and the suppress is not solving the issue. It's been a while, have you resolved this in any way?

**Comment by ChadKillingsworth** [comment]
I'm not really spending any time on Polymer 1 right now. All my focus is on Polymer 2 and class mixins.

The issue here isn't really related to Polymer either. You need to properly define a namespace, then hang all your behaviors off that namespace.

Also, you must be consistent. To the compiler, `window.myNamespace` and `myNamespace` are completely different references. Make sure you are consistent.

**Comment by kaspnilsson** [comment]
Understood, to your first point.

More specifically, my project behaviors look like this (with the suggested fix from your prior comment)....

```javascript
  ...
  /** @suppress {duplicate} */
  window.Gerrit = window.Gerrit || {};
  /** @polymerBehavior Gerrit.KeyboardShortcutBehavior */
  window.Gerrit.KeyboardShortcutBehavior = [
  ...
````

...and my errors look like this:

```shell
ERROR - Behaviors must be global names or qualified names that are declared as object literals or array literals of other valid Behaviors.
      Gerrit.KeyboardShortcutBehavior,
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

I totally understand if this isn't going to be fixed, I was just wondering if there was a suppress I could use that would work. This is currently preventing us from using any of the closure optimizations in our project.

**Comment by ChadKillingsworth** [comment]
Right - you are referencing your behavior wrong. From that error it should be:

```js
window.Gerrit.KeyboardShortcutBehavior
```

**Comment by kaspnilsson** [comment]
That does not seem to be the case either.

**Comment by davitykale** [comment]
Any update on this? Potentially a way to suppress the error?

**Comment by ChadKillingsworth** [comment]
This is probably a fatal error and so therefore not suppressible. I believe it has to do with the way the namespace is defined. You need:

1. A Well defined global namespace.
2. Behavior definition (which may or may not be able to be in an IIFE).
3. Reference everything consistently.

**Comment by davitykale** [comment]
Hey @ChadKillingsworth - could you tell me what you think is the easiest way to fix this implementation: https://github.com/vaadin/vaadin-grid/blob/master/vaadin-grid-active-item-behavior.html.

**Comment by ChadKillingsworth** [comment]
Like this:

```js
/** @const */
window.vaadin ={};
/** @const */
window.vaadin.elements = {};
/** @const */
window.vaadin.elements.grid = {};
/**
 * @polymerBehavior window.vaadin.elements.grid.ActiveItemBehavior
 */
window.vaadin.elements.grid.ActiveItemBehavior = {};


Polymer({
  is: 'foo-bar',
  behaviors: [window.vaadin.elements.grid.ActiveItemBehavior]
});
```

Once that is working, you can try conditionally defining your namespaces one at a time.
