### ISSUE TITLE
parser fails for string literal property names 

### ISSUE THREAD

**Issue by gorkem** [google/closure-compiler#2044]
Parser incorrectly fails to parse some ES6 shorthand method names if property names are string literals here is some examples 

``` javascript
var o = {
   'test'() {}
};
```

or a generator function

``` javascript
var o = {
   *'test'() {}
};
```

**Comment by MatrixFrog** [comment]
workaround:

```
var o = {
   ['test']() {}
};
```

though the typechecker won't tend to do well with such things.

**Comment by lauraharker** [comment]
This parses now.

https://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540compilation_level%2520SIMPLE_OPTIMIZATIONS%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250Avar%2520o%2520%253D%2520%257B%250A%2520%2520%2520'test'()%2520%257B%257D%250A%257D%253B
