### ISSUE TITLE
Support for Aliases (eg. @arg in place of @param)

### ISSUE THREAD

**Issue by machineghost** [google/closure-compiler#2045]
The JSDoc spec (http://usejsdoc.org/) defines several convenience/improved readability aliases for its annotations, such as `@arg` in place of `@param` (even as little as 2 characters adds up when you're writing a lot of annotations).  However, as far as I can tell closure-compiler doesn't support any of them.

It'd be great if Closure Compiler could support these aliases (and since normally aliases aren't hard to add, I would *imagine* this would be a fairly simple request).

**Comment by MatrixFrog** [comment]
It would be fairly simple, but we actually would like to move in the opposite direction: Whenever there are two different ways to say the same thing (`@override`/`@inheritDoc`, or `void`/`undefined`), it leads to confusion about which one should be used, so we'd stick to a "there's only one way to do it" situation when possible. If you wanted to use a slightly modified version of the compiler, you could change this map to include a mapping from `arg` to `Annotation.PARAM`: https://github.com/google/closure-compiler/blob/a0b884082dbef77d2d336705b32d99e0a930dc54/src/com/google/javascript/jscomp/parsing/Annotation.java#L87

Interestingly, we already have `argument` in there, which it looks like almost nobody uses.
