### ISSUE TITLE
Typed properties are allowed to be declared outside of constructor.

### ISSUE THREAD

**Issue by aghassemi** [google/closure-compiler#2050]
In both `class` and `@struct` cases, Closure Compiler does not produce the `Cannot add a property to a struct instance after it is constructed.` warning when a property is declared outside of the constructor **if** it is typed. (Advanced mode).

Please see the following test cases:
[Declared Outside and Typed (No warnings)](https://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540compilation_level%2520ADVANCED_OPTIMIZATIONS%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250A%250Aclass%2520X%2520%257B%250A%2520%2520constructor()%2520%257B%250A%2520%2520%2520this.x_%2520%253D%2520'x'%253B%250A%2520%2520%257D%250A%2520%2520%250A%2520%2520foo()%2520%257B%250A%2520%2520%2520%2520%252F**%2520%250A%2520%2520%2520%2520%2520*%2520%2540type%2520%257Bboolean%257D%2520%250A%2520%2520%2520%2520%2520*%252F%250A%2520%2520%2520%2520this.y_%2520%253D%2520false%253B%250A%2520%2520%257D%250A%257D%250A%250A%250A%252F**%2520%250A%2520*%2520%2540constructor%250A%2520*%2520%2540struct%250A%2520*%252F%250Afunction%2520Foo(x)%2520%257B%250A%2520%2520this.x_%2520%253D%2520'x'%253B%250A%257D%250A%250AFoo.prototype.foo%2520%253D%2520function()%2520%257B%250A%2520%2520%2520%2520%252F**%2520%250A%2520%2520%2520%2520%2520*%2520%2540type%2520%257Bboolean%257D%2520%250A%2520%2520%2520%2520%2520*%252F%250A%2520%2520%2520%2520this.y_%2520%253D%2520false%253B%250A%257D%250A)
[Declared Outside and Not Typed (Gets Warning)](https://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540compilation_level%2520ADVANCED_OPTIMIZATIONS%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250Aclass%2520X%2520%257B%250A%2520%2520constructor()%2520%257B%250A%2520%2520%2520this.x_%2520%253D%2520'x'%253B%250A%2520%2520%257D%250A%250A%2520%2520foo()%2520%257B%250A%2520%2520%2520%2520this.y_%2520%253D%2520false%253B%250A%2520%2520%257D%250A%257D%250A%250A%250A%252F**%250A%2520*%2520%2540constructor%250A%2520*%2520%2540struct%250A%2520*%252F%250Afunction%2520Foo(x)%2520%257B%250A%2520%2520this.x_%2520%253D%2520'x'%253B%250A%257D%250A%250AFoo.prototype.foo%2520%253D%2520function()%2520%257B%250A%2520%2520%2520%2520this.y_%2520%253D%2520false%253B%250A%257D%250A)

Is this by design? If so, how does this still ensure hidden classes can be created for better performance? I asumed the whole point of enforcing property declarations in constructor was so that  hidden classes can be created for the types.

Would appreciate a clarification.

**Comment by brad4d** [comment]
This appears to be a bug in the old Type Inference (OTI) engine. When I try the same "no warnings" example with NTI (New Type Inference), I get warnings as expected.

Side note: is there some way to enable NTI in the compilation service web UI used in the links above?

https://closure-compiler-debugger.appspot.com/#input0%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540compilation_level%2520ADVANCED_OPTIMIZATIONS%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250A%250Aclass%2520X%2520%257B%250A%2520%2520constructor()%2520%257B%250A%2520%2520%2520this.x_%2520%253D%2520'x'%253B%250A%2520%2520%257D%250A%2520%2520%250A%2520%2520foo()%2520%257B%250A%2520%2520%2520%2520%252F**%2520%250A%2520%2520%2520%2520%2520*%2520%2540type%2520%257Bboolean%257D%2520%250A%2520%2520%2520%2520%2520*%252F%250A%2520%2520%2520%2520this.y_%2520%253D%2520false%253B%250A%2520%2520%257D%250A%257D%250A%250A%250A%252F**%2520%250A%2520*%2520%2540constructor%250A%2520*%2520%2540struct%250A%2520*%252F%250Afunction%2520Foo(x)%2520%257B%250A%2520%2520this.x_%2520%253D%2520'x'%253B%250A%257D%250A%250AFoo.prototype.foo%2520%253D%2520function()%2520%257B%250A%2520%2520%2520%2520%252F**%2520%250A%2520%2520%2520%2520%2520*%2520%2540type%2520%257Bboolean%257D%2520%250A%2520%2520%2520%2520%2520*%252F%250A%2520%2520%2520%2520this.y_%2520%253D%2520false%253B%250A%257D%250A%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES%3D1%26CHECK_TYPES_NEW_INFERENCE%3D1%26CLOSURE_PASS%3D1%26LANG_IN_IS_ES6%3D1%26MISSING_PROPERTIES%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1%26TRANSPILE%3D1

**Comment by aghassemi** [comment]
Thanks @brad4d  I can confirm switching to NTI fixed the issue for me as well in out environment but we have bunch of work to do to be able to fully switch to NTI, can you think of any work-around to somehow get these warnings in OTI?

**Comment by brad4d** [comment]
I don't know of any workarounds for OTI.
In general we're not fixing anything in OTI, because we're trying to completely replace it.
@dimvar perhaps you know something that will help here?

**Comment by dimvar** [comment]
Sorry, nothing comes to mind.

**Comment by brad4d** [comment]
Sorry, we won't be fixing things in OTI, but we are working on something to ease the transition from OTI to NTI. I just cannot put my finger on the issue tracking that just now...

**Comment by aghassemi** [comment]
Thanks all. We will try to upgrade to NTI.
