### ISSUE TITLE
[1].map(String) is invalid according to NTI

### ISSUE THREAD

**Issue by pallosp** [google/closure-compiler#2052]
```
input0:1: WARNING - Invalid type for parameter 1 of function .
Expected : function(this:?,*,number,Array<*>):?|null
Found    : String<|function(new:String,*=):string|>

[1].map(String)
        ^

0 error(s), 1 warning(s), 100.0% typed
```

**Comment by dimvar** [comment]
Thanks for the report. The bug is that the `new:String` part of the `String` constructor should be ignored in this case, because the constructor has a return type, and can be called without new. Another repro with simpler function types below.

    /**
     * @param {function(number):number} x
     * @param {function(new: Object, number):number} y
     */
    function f(x, y) {
      x = y;
    }
