### ISSUE TITLE
Support @suppress (and possibly other compiler directives) in IIFEs

### ISSUE THREAD

**Issue by liitii** [google/closure-compiler#2057]
I have an IIFE that runs a performance benchmark that the compiler (nicely) says "WARNING - Suspicious code. This code lacks side-effects. Is there a bug?". I'd like to use `@suppress {suspiciousCode}` on it since it's intentional but I cannot find any arrangement where the directive is respected for the subsequent function.

**Comment by dimvar** [comment]
Putting the suppression at the beginning of the file should work. Or are there more things in the file that you want to check, and you want to specifically skip the IIFE?

**Comment by liitii** [comment]
Yeah, I only want to hide that single warning because the file in question is concatenated with others before the compiler sees it, I don't want to suppress warnings for the entire build. Even if it weren't, I would only want to suppress warnings I'm certain can be ignored.

**Comment by dimvar** [comment]
We don't provide anything for this at the moment. As a workaround, you can split the IIFE to a function definition and a call to avoid the warning.

**Comment by liitii** [comment]
The point is for the function to be GC'd. If I use the suggested workaround will it get turned into an IIFE?

**Comment by dimvar** [comment]
> The point is for the function to be GC'd.

I assume you mean inlined by the compiler (?) Yes, it will be inlined in this case, because there is only one call site to the function.

**Comment by liitii** [comment]
Yes, inlined so it can be garbage collected.

Thanks for the suggestion but it hasn't worked. Is as follows, but warning still appears:

```
/**
 * @suppress {suspiciousCode}
 */
function foo(x) {
    //...
}
foo(1000000);
```
