### ISSUE TITLE
webcrypto extern always returns `Promise<*>` instead of tighter types

### ISSUE THREAD

**Issue by aghassemi** [google/closure-compiler#2064]
For example https://github.com/google/closure-compiler/blob/55cf43ee31e80d89d7087af65b5542aa63987874/externs/browser/w3c_webcrypto.js#L302 should return `Promise<boolean>` instead of `Promise<*>`

**Comment by Dominator008** [comment]
Care to submit a fix internally :)?

**Comment by realityforge** [comment]
@brad4d This has been fixed and the issue can be closed

**Comment by brad4d** [comment]
@realityforge thanks
