### ISSUE TITLE
Spurious unknown type warning when declaring generic types

### ISSUE THREAD

**Issue by Dominator008** [google/closure-compiler#2069]
Sample code:

``` js
/**
 * @template T
 * @param {T} p
 */
function f(p) {
  var /** Array<T> */ x; // Bad type annotation. Unknown type T
}
```

https://closure-compiler-debugger.appspot.com/#input0%3D%252F**%250A%2520*%2520%2540template%2520T%250A%2520*%2520%2540param%2520%257BT%257D%2520p%250A%2520*%252F%250Afunction%2520f(p)%2520%257B%250A%2520%2520var%2520%252F**%2520Array%253CT%253E%2520*%252F%2520x%253B%250A%257D%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES_NEW_INFERENCE%3D1%26CLOSURE_PASS%3D1%26LANG_IN_IS_ES6%3D1%26MISSING_PROPERTIES%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1%26TRANSPILE%3D1

**Comment by concavelenz** [comment]
This is working as expected for the OTI (the type parameters are scoped to the function signature, not the entire function declaration), the NTI has different ideas about this.

**Comment by dimvar** [comment]
The error comes from the old type checker, as John mentions. But the jsdocinfoparser uses the simpleerrorreporter, so it's not straightforward to suppress the warning when NTI runs before OTI.

To see that NTI actually knows what T is in the body, see this (example)[https://closure-compiler-debugger.appspot.com/#input0%3D%252F**%250A%2520*%2520%2540template%2520T%250A%2520*%2520%2540param%2520%257BT%257D%2520p%250A%2520*%252F%250Afunction%2520f(p)%2520%257B%250A%2520%2520var%2520%252F**%2520!Array%253CT%253E%2520*%252F%2520x%2520%253D%2520%255Bp%255D%253B%250A%2520%2520var%2520%252F**%2520!Array%253Cnumber%253E%2520*%252F%2520arr%2520%253D%2520x%253B%250A%257D%250A%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES_NEW_INFERENCE%3D1%26CLOSURE_PASS%3D1%26LANG_IN_IS_ES6%3D1%26MISSING_PROPERTIES%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1%26TRANSPILE%3D1].

**Comment by dimvar** [comment]
I'd have to suppress this in a round-about way, eg, by passing the compiler instance to `JsDocInfoParser`, and guard the error by whether NTI runs or not.
