### ISSUE TITLE
ADVANCED_OPTIMIZATIONS does not eliminate dead code when checking if a function is defined

### ISSUE THREAD

**Issue by elad-yosifon** [google/closure-compiler#2073]
please see this reproducer:
 http://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%2540compilation_level%2520ADVANCED_OPTIMIZATIONS%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250Avar%2520h%2520%253D%2520function%2520(v)%2520%257B%250A%2520%2520return%2520v%250A%257D%253B%250A%250Avar%2520g%2520%253D%2520function%2520(v)%2520%257B%250A%2520%2520return%2520v.reverse()%250A%257D%253B%250A%250Avar%2520b%2520%253D%2520function%2520(h)%2520%257B%250A%2520%2520var%2520str%2520%253D%2520%2522string%2522%253B%250A%2520%2520if%2520(h)%2520%257B%250A%2520%2520%2520%2520return%2520h(str)%253B%250A%2520%2520%257D%2520else%2520%257B%250A%2520%2520%2520%2520return%2520g(str)%253B%250A%2520%2520%257D%250A%257D%253B%250A%250Aconsole.log(b(h))%253B%250A

I'm expecting the GCC to eliminate the `g` function, since it will **NEVER** be invoked.

**Comment by ChadKillingsworth** [comment]
This requires tracing through function calls. Most similar optimizations come from function inlining - which isn't sufficient in this case to know that `g` is never called.

**Comment by elad-yosifon** [comment]
@ChadKillingsworth  I'm not sure I understand..  
are you saying that GCC can't prove that ```g```  will never be invoked?

**Comment by ChadKillingsworth** [comment]
@elad-yosifon correct. It is theoretically possible for simple cases. Especially when a function is only called from a single place. That type of analysis is just not currently part of the compiler.

**Comment by elad-yosifon** [comment]
I think this case (or any other similar case) can be analyzed in compilation.
In the example, I'm simply checking if an argument of a function (which is a function) is 'falsy'. 
IMHO it's pretty straightforward to prove that the argument will never be 'falsy', thus eliminating the need for ```g```. 

I did manage to find weird inconsistencies with this issue.
see the following reproducers:

- 2 arguments (both functions) works as expected (eliminating ```g```)
http://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%2540compilation_level%2520ADVANCED_OPTIMIZATIONS%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250Avar%2520h%2520%253D%2520function%2520(v)%2520%257B%250A%2520%2520return%2520v%250A%257D%253B%250A%250Avar%2520g%2520%253D%2520function%2520(v)%2520%257B%250A%2520%2520return%2520v.reverse()%250A%257D%253B%250A%250Avar%2520b%2520%253D%2520function%2520(h%252Cc)%2520%257B%250A%2520%2520var%2520str%2520%253D%2520%2522string%2522%253B%250A%2520%2520if%2520(h)%2520%257B%250A%2520%2520%2520%2520return%2520h(str)%253B%250A%2520%2520%257D%2520else%2520%257B%250A%2520%2520%2520%2520return%2520g(str)%253B%250A%2520%2520%257D%250A%257D%253B%250A%250Aconsole.log(b(h%252Ch))%253B%250A

- 2 arguments (function and a number)  does not eliminate ```g``` ???
http://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%2540compilation_level%2520ADVANCED_OPTIMIZATIONS%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250Avar%2520h%2520%253D%2520function%2520(v)%2520%257B%250A%2520%2520return%2520v%250A%257D%253B%250A%250Avar%2520g%2520%253D%2520function%2520(v)%2520%257B%250A%2520%2520return%2520v.reverse()%250A%257D%253B%250A%250Avar%2520b%2520%253D%2520function%2520(h%252Cc)%2520%257B%250A%2520%2520var%2520str%2520%253D%2520%2522string%2522%253B%250A%2520%2520if%2520(h)%2520%257B%250A%2520%2520%2520%2520return%2520h(str)%253B%250A%2520%2520%257D%2520else%2520%257B%250A%2520%2520%2520%2520return%2520g(str)%253B%250A%2520%2520%257D%250A%257D%253B%250A%250Aconsole.log(b(h%252C1))%253B

- empty string eliminates ```h```
http://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%2540compilation_level%2520ADVANCED_OPTIMIZATIONS%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250Avar%2520h%2520%253D%2520function%2520(v)%2520%257B%250A%2520%2520return%2520v%250A%257D%253B%250A%250Avar%2520g%2520%253D%2520function%2520(v)%2520%257B%250A%2520%2520return%2520v.reverse()%250A%257D%253B%250A%250Avar%2520b%2520%253D%2520function%2520(h)%2520%257B%250A%2520%2520var%2520str%2520%253D%2520%2522string%2522%253B%250A%2520%2520if%2520(h)%2520%257B%250A%2520%2520%2520%2520return%2520h(str)%253B%250A%2520%2520%257D%2520else%2520%257B%250A%2520%2520%2520%2520return%2520g(str)%253B%250A%2520%2520%257D%250A%257D%253B%250A%250Aconsole.log(b(%2522%2522))%253B%250A

**Comment by elad-yosifon** [comment]
@ChadKillingsworth  any news ? (2 years and 1 day later...)

**Comment by brad4d** [comment]
@elad-yosifon 
I don't think we're likely to take any action on this issue as it is currently defined.

It demonstrates a case where the compiler fails to make an optimization that seems obvious to a human reader, but one can construct any number of such cases, and we definitely don't have time to work on every one. We have to focus on the ones that seem likely to lead to big improvements in output code size or perhaps a way of simplifying the compiler's implementation.

I'm afraid this case doesn't appear to meet that bar.
