### ISSUE TITLE
[FEATURE REQUEST] Optimization only

### ISSUE THREAD

**Issue by dalisoft** [google/closure-compiler#2075]
First was js been faster. But after adding some modularity tool compatilibity code my code was slowed down.
After minifed with `Closure compiler` my js again almost same as before.
Now i want, no variable shortening, no minify. Just optimize. I think this will be amazing.
Thanks

**Comment by ChadKillingsworth** [comment]
You could create a custom build of the compiler and turn off the renaming. However this rarely makes sense. The compiler performs whole-world optimizations and the assumptions allowing many of those optimizations are the same as is needed to do renaming.

Simple mode has all the optimizations that are proven safe without the whole world optimizations.

**Comment by Dominator008** [comment]
You can try using the Compiler via the Java API for finer control over which optimizations you want enabled.

**Comment by dalisoft** [comment]
I want move variables in need place. And loop optimization too

**Comment by ChadKillingsworth** [comment]
Have you tried using `SIMPLE` mode with the `--assume_function_wrapper` flag?

**Comment by dalisoft** [comment]
I trying with online way
