### ISSUE TITLE
if (x === null) gets optimized to !x

### ISSUE THREAD

**Issue by cldellow** [google/closure-compiler#2079]
I searched + [posted on the mailing list](https://groups.google.com/forum/#!topic/closure-compiler-discuss/qKm-TpZbFdU) -- seems like this might be a legit issue, so posting it here, too.

We noticed after a recent upgrade that:

```js
if (/** @type {Array|undefined} */ (window['c']) === null) {
  window['d'] = 12
}
```
which had previously (as of v20160619) compiled to:

```js
null===window["c"]&&(window["d"]=12);
```
was now (as of v20160713 and later) compiling to:

```js
window["c"]||(window["d"]=12);
```

This no longer discriminates between null and undefined, which was surprising to us. Is that a bug? Or are we maybe using annotations incorrectly?

There's a minimal repro at https://github.com/cldellow/closure-q/blob/master/src/main/java/q/Test.java that shows the precise set of options that we used.

**Comment by Dominator008** [comment]
Try annotating it with `?Array|undefined`?

**Comment by cldellow** [comment]
That produces the same output, as does `Object|undefined` and `?Object|undefined`.

**Comment by Dominator008** [comment]
Hmm. I can't seem to be able to reproduce this via the command line:
```sh
java -jar target/closure-compiler-1.0-SNAPSHOT.jar --use_types_for_optimization -O ADVANCED repro.js
```

**Comment by cldellow** [comment]
Yeah, this seemed crazy to us, but we needed to also enable the duplicate diagnostic group to repro this.

We stumbled across this in real usage because our settings are: enable advanced optimizations, enable use types for optimization, enable most diagnostic groups at error level.

https://github.com/cldellow/closure-q/blob/master/src/main/java/q/Test.java shows what we think the minimum set of flags to enable are--maybe it's not valid to enable certain flags in concert with others? My ignorance is showing here. :)

**Comment by ChadKillingsworth** [comment]
I think the type checking passes are needed at a minimum. You can try diagnosing the issue at http://closure-compiler-debugger.appspot.com/

**Comment by Dominator008** [comment]
@ChadKillingsworth Ah you are right. I'm able to reproduce it with:
```sh
java -jar target/closure-compiler-1.0-SNAPSHOT.jar --jscomp_error=checkTypes --use_types_for_optimization -O ADVANCED repro.js
```

**Comment by Dominator008** [comment]
Culprit commit: b59e62460b16c202f1583bb15664e9440df316b5

**Comment by Dominator008** [comment]
@cldellow Thanks for the bug report. I've submitted a fix for this internally. It will be mirrored externally tomorrow.
