### ISSUE TITLE
Incorrect type-based optimization for enum == null

### ISSUE THREAD

**Issue by butterflyhug** [google/closure-compiler#2084]
My team has a bunch of code that uses `/** @enum {number} */` that include an entry for 0.  We also have a lot of nullable references to these enum values.  If we want different behavior depending on whether the variable has a non-null value, then we'll usually check `value == null`.

When `--use_types_for_optimization` is turned on, these checks get optimized into a truthiness check.  This is incorrect when the enum contains 0.  For example:

```js
/** @enum {number} */
var Vehicle = {
  CAR: 0,
  TRUCK: 1,
  BICYCLE: 2,
  VAN: 3,
  UNKNOWN: 4,
};

/**
 * @param {?Vehicle} v
 * @return {Vehicle}
 */
function vehicleOrDefault(v) {
  if (v == null) {
    return Vehicle.UNKNOWN;
  }
  return v;
}

var testCases = [null, Vehicle.CAR, Vehicle.VAN];
console.log(testCases.map(vehicleOrDefault));
```

is incorrectly optimizing to:

```js
console.log([null,0,3].map(function(a){return a?a:4}));
```

If I use `--use_types_for_optimization=false`, this same code compiles correctly:

```js
console.log([null,0,3].map(function(a){return null==a?4:a}));
```

(We're also using ADVANCED_OPTIMIZATIONS, compiling ES6 input to ES5_STRICT output, etc.)

**Comment by MatrixFrog** [comment]
@Dominator008 this is pretty similar to the case you fixed recently right? It looks like we just need one more check to make sure that `@enum {string}` or `@enum {number}` isn't treated as Object.
