### ISSUE TITLE
PolymerPass and Polymer 2.0

### ISSUE THREAD

**Issue by ChadKillingsworth** [google/closure-compiler#2087]
Polymer 2.0 changes for the compiler look to be straightforward. The one stumbling block I see is detecting whether a class extends `Polymer.Element`. Ideally the PolymerPass would run after type checking and therefore be able to simply know this. However since it also adds type information needed by type inference, it also needs to run beforehand.

Possible solutions:
1. Use a special annotation like `@PolymerElement`. This is the most simple solution - but it feels like we should be able to do better.
2. Use a heuristic to detect a Polymer class by non-type means. This could include checking for a static `is` getter or a `config` getter. Or maybe even just checking to see if the class is referenced by a `customElements.define` call.
3. Ask the rest of the jscomp team if they can think of a way for the PolymerPass to participate in the "middle" of type checking.

cc @justinfagnani, @samthor

**Comment by ChadKillingsworth** [comment]
What's needed here is a way to extend the type inference system. Since that doesn't really exist, I'm planning on implementing a custom jsdoc annotation. However I hope that the annotation is only needed for classes which indirectly extend `Polymer.Element`.

**Comment by jklein24** [comment]
Hey Chad, feel free to cc @MatrixFrog and myself on a PR when you get there. Your analysis seems pretty right-on here. I chatted briefly with a couple folks on the Polymer team about this exact problem when 2.0 was announced. Tyler may have some thoughts about how we can make this work.

**Comment by ChadKillingsworth** [comment]
@jklein24 Will do. The proposed methods for mixins (behaviors) will also be challenging but I'm saving that for a separate issue as it's not Polymer specific.
