### ISSUE TITLE
Extending native classes breaks during transpilation.

### ISSUE THREAD

**Issue by brad4d** [google/closure-compiler#2098]
Native class constructors predating ES6 have non-standard behavior.
e.g. Object and Error always return a new object. They won't work correctly
with .apply(this).
Native class constructors in ES6 throw an exception if you try to call them
without `new`.

For these reasons the standard trick for doing the super constructor call in
a derived class will not work. The behavior will be even worse when we implement the fix
for #1669.

For Object, we can safely just drop the super() call.
For others dropping it will lead to surprising behavior, since the super class won't get initialized.

I believe the best thing we can do for now is generate an error for these cases. For extending `Object`, we'll only generate an error if the code tries to pass arguments to `super()`.

**Comment by ChadKillingsworth** [comment]
I don't believe any other transpilers handle these objects correctly either.

**Comment by brad4d** [comment]
@ChadKillingsworth, I'm sure you're right.
@concavelenz and I played with the Traceur and Babel transpiler tools & found they didn't do any special handling for Object or Error.

I just want to make sure we drop the super constructor call and generate an error or warning when we see this happening.

I'm considering filing an issue for specifically supporting extension of `Error` and its relatives,
since it seems quite reasonable to want to extend those. WDYT?
