### ISSUE TITLE
super() should return the (possibly modified) value of `this`

### ISSUE THREAD

**Issue by brad4d** [google/closure-compiler#2109]
According to the spec `super()` should return `this`.
See also #1669 regarding allowing the super constructor to replace the value of `this`.
If it does, the new value of `this` should be returned.

What happens now is `super(...)` returns the result of `BaseClass.call(this, ...)`,
which is most often `undefined`.
However, most native class constructors return a newly created object when called this way.
There's some code out there that takes advantage of this to work around the awkwardness of extending Error classes.

https://github.com/angular/angular/blob/745e10e6d2ea9097b7ec650ae54cea91e3d193f2/modules/%40angular/facade/src/errors.ts#L23

I'm fixing #2102, which will make this workaround unnecessary.
I'd like to also make `super()` return `this` as it is supposed to do,
but I don't want to break Angular.

**Comment by brad4d** [comment]
FYI @mprobst

**Comment by brad4d** [comment]
I expect the fix for this to be in today's push to github.

**Comment by mprobst** [comment]
@vikerman is currently on duty to merge and sync changes from github back in.

Vikram, can you ping this once that PR is merged and has made it into google3?
https://github.com/angular/angular/pull/12600
