### ISSUE TITLE
Why Gson classes are packaged inside of the closure-compiler JAR?

### ISSUE THREAD

**Issue by a701440** [google/closure-compiler#2120]
These classes would conflict with any other version of Gson that can be used in the same JVM. If packaging is really needed could you use JARJAR to do it?

**Comment by ChadKillingsworth** [comment]
If you need a version without bundled dependencies, we publish an unshaded version to Maven: https://mvnrepository.com/artifact/com.google.javascript/closure-compiler-unshaded
