### ISSUE TITLE
Incorrect override functions with optional parameter

### ISSUE THREAD

**Issue by ikabirov** [google/closure-compiler#2122]
When using ADVANCED_OPTIMIZATIONS option, the compiler ignores overriden functions that just call base class method without passing optional arguments:
 
```js
/**
 * @param {number=} width
 * @param {number=} height
 */
Foo.prototype.resize = function(width, height) {}
```
 
it is ok when undefined height is passed explicitly
```js
/** @inheritDoc */
Bar.prototype.resize = function(width, height) {
    goog.base(this, "resize", width, undefined);
};
```
 
However, if height is not passed, the compiler throws away Bar.prototype.resize method completely
```js
/** @inheritDoc */
Bar2.prototype.resize = function(width, height) {
    goog.base(this, "resize", width);
};
```
 
this bar will be removed from output code
```js
    bar.resize(100, 200);
    console.log(bar.width(), bar.height()); // 100 undefined
 
    bar2.resize(100, 200);
    console.log(bar2.width(), bar2.height()); // 100 200
```
 
Minimal code to reproduce this issue: [main.txt](https://github.com/google/closure-compiler/files/563906/main.txt)

**Comment by Dominator008** [comment]
Looks like a too aggressive optimization to me, but your code is actually confusing :)

**Comment by MatrixFrog** [comment]
I think there was an optimization added recently that removes overrides that do nothing but call the base method. Sometimes you need these so you can add more specific type annotations, but at runtime there's no value in keeping them. I'll see if I can find it.

**Comment by MatrixFrog** [comment]
https://github.com/google/closure-compiler/blob/master/src/com/google/javascript/jscomp/RemoveSuperMethodsPass.java
