### ISSUE TITLE
Compiler doesn't recognize an abstract method assigned in the constructor

### ISSUE THREAD

**Issue by shicks** [google/closure-compiler#2127]
The following should work, but the compiler produces an [error]:

```js
/** @abstract */
class Base {
  /** @abstract
      @param {*} arg
      @return {boolean} */
  method(arg) {}
}

class Derived extends Base {
  /** @param {function(*): boolean} method */
  constructor(method) {
    super();
    /** @override */
    this.method = method;
  }
}
```

```
input0:11: WARNING - property method on abstract class Base is not implemented by type Derived
  constructor(method) {
  ^
```

[error]: https://closure-compiler-debugger.appspot.com/#input0%3D%252F**%2520%2540abstract%2520*%252F%250Aclass%2520Base%2520%257B%250A%2520%2520%252F**%2520%2540abstract%250A%2520%2520%2520%2520%2520%2520%2540param%2520%257B*%257D%2520arg%250A%2520%2520%2520%2520%2520%2520%2540return%2520%257Bboolean%257D%2520*%252F%250A%2520%2520method(arg)%2520%257B%257D%250A%257D%250A%250Aclass%2520Derived%2520extends%2520Base%2520%257B%250A%2520%2520%252F**%2520%2540param%2520%257Bfunction(*)%253A%2520boolean%257D%2520method%2520*%252F%250A%2520%2520constructor(method)%2520%257B%250A%2520%2520%2520%2520super()%253B%250A%2520%2520%2520%2520%252F**%2520%2540override%2520*%252F%250A%2520%2520%2520%2520this.method%2520%253D%2520method%253B%250A%2520%2520%257D%250A%257D%250A%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES%3D1%26CLOSURE_PASS%3D1%26MISSING_PROPERTIES%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1%26TRANSPILE%3D1

**Comment by brad4d** [comment]
I would argue that the compiler really shouldn't try to understand code like this,
since it's not following normal practice.

If you want to specify the implementation of a method when you construct an object,
you can do it this way without confusing the compiler.
I'd also argue that it's more readable, because assignment to a field that
is defined as a class method is just weird.

```javascript
class Base {
  /** @abstract
      @param {*} arg
      @return {boolean} */
  method(arg) {}
}

class Derived extends Base {
  /** @param {function(*): boolean} method */
  constructor(methodImpl) {
    super();
    /** @private @const */
    this.methodImpl_ = methodImpl;
  }

  /** @override */
  method(arg) {
    return this.methodImpl_(arg);
  }
}
```
