### ISSUE TITLE
Add externs for `Element.animate` and family

### ISSUE THREAD

**Issue by dvoytenko** [google/closure-compiler#2134]
See https://www.w3.org/TR/web-animations/

**Comment by ChadKillingsworth** [comment]
Interested in sending a PR?

**Comment by dvoytenko** [comment]
Will do.

**Comment by yishayw** [comment]
Hi, is there a reason this wasn't implemented other than lack of resources? Just curious.

**Comment by EatingW** [comment]
It is actually already implemented internally. I'll expose it to the Github repo soon. Sorry for the delay!

**Comment by carlosrovira** [comment]
ok thanks! :)
