### ISSUE TITLE
[NTI] A new warning after the latest commit

### ISSUE THREAD

**Issue by vobruba-martin** [google/closure-compiler#2135]
@dimvar After the commit 0c079ac7fe6c22d4ba124ed64f09a46d39d0bb13 :

```javascript
/**
 * @record
 * @struct
 */
function MyType() {};

/** @type {(string|undefined)} */
MyType.prototype.foo;


/**
 * @param {!MyType=} x
 */
function fn(x) {
	/** @type {!MyType} */
	var y = x || {};
	
	if (y.foo || y.foo === '') {
		console.log(y.foo);
	}
};
```
```
media/js/test.js:19: WARNING - Property foo may not be present on y of type MyType|Object{}.
	if (y.foo || y.foo === '') {
	             ^

media/js/test.js:20: WARNING - Property foo may not be present on y of type MyType{foo:string|undefined=}|Object{}.
		console.log(y.foo);
		            ^
```

**Comment by vobruba-martin** [comment]
Workaround

```javascript
	/** @type {!MyType} */
	var y = x || /** @type {!MyType} */ ({});
```

**Comment by vobruba-martin** [comment]
Another problem after that commit:

```javascript
/**
 * @record
 * @struct
 */
function MyType() {};

/** @type {(string|undefined)} */
MyType.prototype.foo;


/** @type {!MyType} */
var x = {};

x.foo = 1;    // no warning
```

**Comment by dimvar** [comment]
The second example is not a bug. When you declare a variable and initialize it, if the initializer is a subtype of the declared type, then the type checker uses the type of the initializer from then on. So, in this case, x is an empty object literal, which doesn't have to obey the MyType restrictions.

In this [example](https://closure-compiler-debugger.appspot.com/#input0%3D%252F**%250A%2520*%2520%2540record%250A%2520*%2520%2540struct%250A%2520*%252F%250Afunction%2520MyType()%2520%257B%257D%253B%250A%250A%252F**%2520%2540type%2520%257B(string%257Cundefined)%257D%2520*%252F%250AMyType.prototype.foo%253B%250A%250A%252F**%2520%2540type%2520%257B!MyType%257D%2520*%252F%250Avar%2520x%2520%253D%2520%257B%257D%253B%250Ax.foo%2520%253D%25201%253B%2520%252F%252F%2520no%2520warning%250A%250Avar%2520y%2520%253D%2520%252F**%2520%2540type%2520%257B!MyType%257D%2520*%252F%2520(%257B%257D)%253B%250Ay.foo%2520%253D%25201%253B%2520%252F%252F%2520warning%250A%250Afunction%2520f(%252F**%2520!MyType%2520*%252F%2520z)%2520%257B%250A%2520%2520z.foo%2520%253D%25201%253B%2520%252F%252F%2520warning%250A%257D%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES%3D1%26CHECK_TYPES_NEW_INFERENCE%3D1%26CLOSURE_PASS%3D1%26MISSING_PROPERTIES%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1%26TRANSPILE%3D1), the variables that are of type MyType get the warning as expected.

**Comment by vobruba-martin** [comment]
IMO this leads to unpredictable behavior:

```javascript
/**
 * @record
 * @struct
 */
function MyType() {};

/** @type {string} */
MyType.prototype.bar;

/** @type {(string|undefined)} */
MyType.prototype.foo;
```

1) 2 warnings - OK
```javascript
/** @type {!MyType} */
var x = {};
x.foo = 1;
```
```
WARNING - The right side in the assignment is not a subtype of the left side.
Expected : MyType
Found    : Object{}
More details:
The found type is missing property bar
var x = {};
        ^
```
```
WARNING - The right side in the assignment is not a subtype of the left side.
Expected : string|undefined
Found    : number

x.foo = 1;
^
```

2) 2 warnings - OK
```javascript
/** @type {!MyType} */
var x = {
	bar : 1
};
x.foo = 1;
```
```
WARNING - The right side in the assignment is not a subtype of the left side.
Expected : MyType
Found    : {bar:number}
More details:
Incompatible types for property bar.
Expected : string
Found    : number
var x = {
        ^
```
```
WARNING - The right side in the assignment is not a subtype of the left side.
Expected : string|undefined
Found    : number

x.foo = 1;
^
```

3) No warning which is confusing:
```javascript
/** @type {!MyType} */
var x = {
	bar : ''
};
x.foo = 1;
```

**Comment by mgiuffrida** [comment]
under NTI with CommonJS modules, enums don't seem to work at all:

```enums.js
/** @enum {number} */ const MyEnum = { ONE: 1, TWO: 2, };
/** @type {MyEnum} */ let num = MyEnum.ONE;
module.exports = {MyEnum: MyEnum};
```

```sh
% java -jar closure-compiler.jar --language_in ECMASCRIPT6_STRICT \
    --language_out ECMASCRIPT5_STRICT --warning_level VERBOSE \
    --new_type_inf --process_common_js_modules --common_js_entry_module=enums.js enums.js

enums.js:1: WARNING - The right side in the assignment is not a subtype of the left side.
Expected : module$test.MyEnum{ONE:module$test.MyEnum^, TWO:module$test.MyEnum^}
Found    : {ONE:number, TWO:number}
More details:
Incompatible types for property ONE.
Expected : module$test.MyEnum
Found    : number
/** @enum {number} */ const MyEnum = { ONE: 1, TWO: 2, }; module.exports = {MyEnum: MyEnum};
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

0 error(s), 1 warning(s), 100.0% typed
```

**Comment by ChadKillingsworth** [comment]
@mgiuffrida The common js behavior is unrelated to anything else in this issue. Can you please post it separately?

**Comment by mgiuffrida** [comment]
@ChadKillingsworth Sorry, I saw https://github.com/google/closure-compiler/issues/2135#issuecomment-259941286 and didn't look closely at the original description.

Opened #2258.
