### ISSUE TITLE
Compiler doesn't understand @abstract annotation with goog.defineClass

### ISSUE THREAD

**Issue by ikabirov** [google/closure-compiler#2138]
is it possible to use @abstract annotation when using goog.defineClass?

```
	var Test = goog.defineClass(null, {
		/**
		 * @constructor
		 * @abstract
		 */
		constructor: function() {

		},
	});

// WARNING - Misplaced @abstract annotation. only functions or non-static methods can be abstract
```

**Comment by MatrixFrog** [comment]
I'm not sure what it would mean for a class to have an abstract constructor. Maybe you want to mark the class with `/** @interface */`?

**Comment by ikabirov** [comment]
https://github.com/google/closure-compiler/wiki/%40abstract-classes-and-methods

**Comment by MatrixFrog** [comment]
That page even says that the constructor of an ES6 class or goog.defineClass cannot be `@abstract`. However the *class* can be, and of course other methods in the class besides the constructor can be as well.

**Comment by ikabirov** [comment]
@MatrixFrog  but question is how to mark class as @abstract using goog.defineClass
http://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540compilation_level%2520ADVANCED_OPTIMIZATIONS%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250Avar%2520Test%2520%253D%2520goog.defineClass(null%252C%2520%257B%250A%2509%2509%252F**%250A%2509%2509%2520*%2520%2540constructor%250A%2509%2509%2520*%252F%250A%2509%2509constructor%253A%2520function()%2520%257B%250A%250A%2509%2509%257D%252C%250A%2520%2520%250A%2509%2509%252F**%250A%2509%2509%2520*%2520%2540abstract%250A%2509%2509%2520*%252F%250A%2520%2520%2520%2520foo%253A%2520function()%2520%257B%250A%2520%2520%2520%2520%257D%252C%250A%2509%257D)%253B%250A%250A

**Comment by MatrixFrog** [comment]
Oh you're right, sorry. There is now a fix for this which should be on Github tomorrow.
