### ISSUE TITLE
Object type is not inferred from multimap

### ISSUE THREAD

**Issue by naamaamir** [google/closure-compiler#2151]
Hi, 

I have this multimap with callback functions.
When I try to invoke one of the callback function I get "expressions are not callable" error.

Code example:
```js
/** @private {!Multimap<!string,!function(!Match)>} map  */
this.map = new Multimap();
....
for (let callback of this.map.get(key)) {
  callback(match);
}
```
Thanks

**Comment by brad4d** [comment]
@dimvar may be able to cast more light on why type checking is failing here, but the answer may be hidden in the `....` part.

Regardless of the reason, this should eliminate the error.

````javascript
for (let /** function(!Match) */ callback of this.map.get(key)) {
  callback(match);
}
````

BTW, in the type annotation `!function()`, the `!` is redundant and can be dropped.

**Comment by dimvar** [comment]
There isn't enough information here. What is the exact error that you are getting? This would say what the compiler thinks the type of `callback` is. Also, how have you defined `Multimap`? It would be helpful if you can provide us with a standalone snippet that reproduces the warning.

**Comment by naamaamir** [comment]
Thank you for your replies.
I use this Multimap:
https://github.com/google/closure-library/blob/master/closure/goog/labs/structs/multimap.js#L135
I think the main issue here is that the Multimap get function returns {!Array<*>} despite my declaration of map to be {!Multimap<!string,!function(!Match)>}.
Here is a code that reproduces the error (in the warnings tab):
http://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540compilation_level%2520ADVANCED_OPTIMIZATIONS%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250A%252F**%2520%2540type%2520%257BArray%253C*%253E%257D%2520*%252F%250Avar%2520callbackArray%2520%253D%2520%255Bfunction(x)%2520%257B%257D%255D%253B%250A%250Afor%2520(let%2520callback%2520of%2520callbackArray)%2520%257B%250A%2520%2520callback(5)%253B%250A%257D%250A

Also using:

for (let /** function(!Match) */ callback of this.map.get(key)) {
  callback(match);
}

didn't work:
http://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540compilation_level%2520ADVANCED_OPTIMIZATIONS%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250A%252F**%2520%2540type%2520%257BArray%253C*%253E%257D%2520*%252F%250Avar%2520callbackArray%2520%253D%2520%255Bfunction(x)%2520%257B%257D%255D%253B%250A%250Afor%2520(let%2520%252F**%2520%2540type%2520function(number)%2520*%252F%2520callback%2520of%2520callbackArray)%2520%257B%250A%2520%2520callback(5)%253B%250A%257D%250A

**Comment by dimvar** [comment]
In your example, we get the warning
`input0:5: WARNING - * expressions are not callable`
which is correct. If you want no warning, the `callbackArray` should be typed as an array of functions.

https://closure-compiler-debugger.appspot.com/#input0%3D%252F**%2520%2540type%2520%257B!Array%253C*%253E%257D%2520*%252F%250Avar%2520callbackArray%2520%253D%2520%255Bfunction(x)%2520%257B%257D%255D%253B%250A%250Afor%2520(let%2520callback%2520of%2520callbackArray)%2520%257B%250A%2520%2520callback(5)%253B%250A%257D%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES%3D1%26CLOSURE_PASS%3D1%26MISSING_PROPERTIES%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1%26TRANSPILE%3D1

Looking at the implementation of Multimap, the same problem happens there. Multimap is badly typed. It doesn't use generics, so the contents are not typechecked, and the get method returns `Array<*>`. The fix here would be to improve typing of the closure library. There is nothing the compiler can do here.
