### ISSUE TITLE
Allow non-function format for @record definitions.

### ISSUE THREAD

**Issue by brad4d** [google/closure-compiler#2153]
The current way of defining `@record` types is really annoyingly verbose and non-intuitive.

```javascript
/** @record */
function PNum() {};
/** @type {number} */
PNum.prototype.p;
```

The version above makes sense in terms of old-style class declarations when the fields are all methods,
but not so much when just defining a data holding type.
Why is `PNum` a function, when we're not defining a class, just a data holder?
Why do I have to keep repeating `PNum.prototype.` for every single field?

I'd like to propose we support this alternative syntax.

```javascript
/** @record */
const PNum = {};
/** @type {number} */
PNum.p;
```

I know it doesn't save a lot in terms of typing, but it makes a lot more sense to me as a developer.

**Comment by MatrixFrog** [comment]
I like
```
/** @interface */
class PNum {
  /** @return {number} */
  p() {}
}
```
but of course that only works for methods, not non-function properties, at least until https://tc39.github.io/proposal-class-public-fields/ lands.

**Comment by Dominator008** [comment]
I think the original idea was that `@record` would replace `@interface`, and people can implement `@record` type so it did make sense for them to look like interfaces. Also using the same syntax as `@interface` made the implementation easier, I think.

With ES6 shorthand object literal syntax we can simplify it a bit more into:
```js
/** @record */
const PNum = {
  /** number */ p;
};
```

**Comment by brad4d** [comment]
In this issue I'm concerned with objects that just have a bunch of data fields and no methods.

I really wanted to do something more like this, but couldn't see a way to avoid assigning a meaningless value to satisfy syntax.

```javascript
/** @record */
const PNum = {
  // This would seem to imply a default value, which isn't really true.
  /** @type {number} */
  p: 0,
  /** @type {string} */
  name: '',
  /** @type {string} */
  id: '',
  // This is a problem. I don't want to create a bogus MyFoo to satisfy the type info.
  /** @type {!MyFoo} */
  foo: undefined,
};
```

ES6 shorthand doesn't help us here. It requires a corresponding variable to exist.

**Comment by Dominator008** [comment]
@brad4d Yeah, looks like your original proposal is the most reasonable one.

**Comment by ChadKillingsworth** [comment]
Mixins rarely use prototypes and are ideal candidates for `@record`. Polymer Behaviors (see #2119) would be a classic example. It would be MUCH easier if it would work the way @brad4d listed.

**Comment by brad4d** [comment]
Another possibility would be to add an `@property` annotation similar to the one in non-closure-compiler JSDoc.

http://usejsdoc.org/tags-property.html

Here's how it might look for us.

```javascript
/**
 * @record
 * @property {string}  name
 * @property {?Date}  birthdate
 * @property {?string}  hairColor A hex color string.
 */
var Person = {};
```

I suspect we'd need a pass to create AST nodes for the properties.

**Comment by brad4d** [comment]
This method currently works at least for some cases, but I believe it has a problem I'm currently unable to recall.

```javascript
/** @record */
class Person {
  constructor() {
    /** @type {string} */
    this.name;
    /** @type {?Date} */
    this.birthdate;
    /**
     * A hex color string.
     * @type {?string}
     */
    this.hairColor;
  }
}
```

**Comment by brad4d** [comment]
Suppose we allow @record definitions using object literals with these limitations enforced by the compiler?

1. Field values must be specified as `undefined`.
2. Method values must have empty function bodies.

```javascript
/** @record */
const Person = {
  /** @type {string} */
  name: undefined,

  /** @type {?Date} */
  birthdate: undefined,

  /**
   * A hex color string.
   * @type {?string}
   */
  hairColor: undefined,

  /**
   * @return {string}
   */
  getDescription() {}
};
```

This seems like the clearest way.
Anyone object to it?

**Comment by ChadKillingsworth** [comment]
What's the reason `@record` properties can't have implementations? I've got lots of cases where I'd like to use an object literal as a mixin. In this case it would be both the `@record` definition and the default implementation.

**Comment by brad4d** [comment]
We don't want to mix up defining an interface, which is basically what `@record` is supposed to do, with defining a default implementation. It's clearer to define an `@record` and then separately define a class or object literal that implements it. If they're mixed together, then client code will end up depending on a specific implementation, which can prove problematic later.

**Comment by ChadKillingsworth** [comment]
Can that be a lint rule then? It's a lot of code duplication to maintain the type information separate from the implementation.

Specifically for Polymer Behaviors, it would have drastically improved the compiler type checking. It also comes up in a lot of other code like so:

```js
/** @record */
var Foo = {
    bar: 'bar',
    /** @return {boolean} */
    hasBar: function() { return true; }
};

/**
 * @implements {Foo}
 * @constructor
 */
function Bar() {}
Bar.prototype = Object.create(Baz.prototype);
Object.assign(Bar.prototype, Foo);
```
 
Without this, you are stuck writing code like so:

```js
/** @record */
var Foo = {
    /** @type {string} */
    bar: undefined,
    /** @return {boolean} */
    hasBar: function() {}
};

/** @implements {Foo} */
var fooImplementation = {
    bar: 'bar',
    hasBar: function() { return true; }
};

/**
 * @implements {Foo}
 * @constructor
 */
function Bar() {}
Bar.prototype = Object.create(Baz.prototype);
Object.assign(Bar.prototype, fooImplementation);
```

The code duplication becomes much greater for non-trivial cases.

**Comment by brad4d** [comment]
@ChadKillingsworth 
Are you aware of current usage of `@record` that defines an implementation?

**Comment by brad4d** [comment]
We currently generate a warning if you try to define a non-empty member function on an `@record`,
except in the case of using assignment in a class constructor. I believe that omission is actually a bug.

https://closure-compiler-debugger.appspot.com/#input0%3D%252F**%2520%2540record%2520*%252F%250Aclass%2520MyRecord%2520%257B%250A%2520%2520constructor()%2520%257B%250A%2520%2520%2520%2520%252F**%2520%2540type%2520%257Bstring%257D%2520*%252F%250A%2520%2520%2520%2520this.something%2520%253D%2520'hello'%253B%250A%2520%2520%257D%250A%250A%2520%2520%252F**%2520%2540return%2520%257Bstring%257D%2520*%252F%250A%2520%2520getRecordId()%2520%257B%2520return%2520'foo'%253B%2520%257D%250A%257D%250A%250A%252F**%2520%2540record%2520*%252F%250Aconst%2520MyOldRecord%2520%253D%2520function()%2520%257B%257D%253B%250A%252F**%2520%2540return%2520%257Bstring%257D%2520*%252F%250AMyOldRecord.prototype.getRecordId%2520%253D%2520function()%2520%257B%2520return%2520'foo'%2520%257D%253B%250A%252F**%2520%2540type%2520%257Bstring%257D%2520*%252F%250AMyOldRecord.prototype.something%2520%253D%2520'hello'%253B%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES%3D1%26CLOSURE_PASS%3D1%26MISSING_PROPERTIES%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1%26TRANSPILE%3D1

**Comment by concavelenz** [comment]
If you don't assign values, this seems to work as expected:

https://closure-compiler-debugger.appspot.com/#input0%3D%252F**%2520%2540record%2520*%252F%250Aclass%2520MyRecord%2520%257B%250A%2520%2520constructor()%2520%257B%250A%2520%2520%2520%2520%252F**%2520%2540type%2520%257Bstring%257D%2520*%252F%250A%2520%2520%2520%2520this.something%253B%250A%2520%2520%257D%250A%250A%2520%2520%252F**%2520%2540return%2520%257Bstring%257D%2520*%252F%250A%2520%2520getRecordId()%2520%257B%257D%250A%257D%250A%250A%252F**%2520%2540record%2520*%252F%250Aconst%2520MyOldRecord%2520%253D%2520function()%2520%257B%257D%253B%250A%252F**%2520%2540return%2520%257Bstring%257D%2520*%252F%250AMyOldRecord.prototype.getRecordId%2520%253D%2520function()%2520%257B%257D%253B%250A%252F**%2520%2540type%2520%257Bstring%257D%2520*%252F%250AMyOldRecord.prototype.something%253B%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES%3D1%26CLOSURE_PASS%3D1%26MISSING_PROPERTIES%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1%26TRANSPILE%3D1

So I don't think there is anything to do here?

**Comment by ChadKillingsworth** [comment]
@brad4d I have several code bases which work around the lack of support for this. However with ES6, I'd rather spend time fixing #2106.

**Comment by brad4d** [comment]
Ok, then. I'm closing this with this conclusion.

For now, we officially support this method for defining data-only `@record` types.

```javascript
/** @record */
class Person {
  constructor() {
    /** @type {string} */
    this.name;
    /** @type {?Date} */
    this.birthdate;
    /**
     * A hex color string.
     * @type {?string}
     */
    this.hairColor;
  }
}
```

We will revisit this when / if property definitions are added to the class syntax in the ES spec.
