### ISSUE TITLE
$jscomp.getGlobal not working when wrapped in function in strict mode

### ISSUE THREAD

**Issue by herrernst** [google/closure-compiler#2163]
I've this `main.js`:
```javascript
class SomeClass {
  get someValue() {
    return "bla";
  }
}
//...
```
I compile with
```sh
java -jar compiler.jar --output_wrapper "(function(){%output%})();" --language_out ECMASCRIPT5_STRICT main.js --js_output_file main.built.js --formatting PRETTY_PRINT
```

I get this `main.built.js`:
```javascript
(function(){'use strict';var $jscomp = {scope:{}, getGlobal:function(a) {
  return "undefined" != typeof window && window === a ? a : "undefined" != typeof global ? global : a;
}};
$jscomp.global = $jscomp.getGlobal(this);
var SomeClass = function() {
};
$jscomp.global.Object.defineProperties(SomeClass.prototype, {someValue:{configurable:!0, enumerable:!0, get:function() {
  return "bla";
}}});
var sc = new SomeClass;
console.log("someValue: " + sc.someValue);
})();
```
which does not work the expected way. It throws at `$jscomp.global.Object.defineProperties()` because `$jscomp.global` is undefined. This is because `$jscomp.getGlobal(this)` cannot find the global context because `this` is undefined in a strict function. Is there any way to work around this, or "am I using it wrong"?

**Comment by ChadKillingsworth** [comment]
Use a wrapper that sets `this`:

```js
(function(){%output%}).call(this)
```

**Comment by herrernst** [comment]
Haven't thought of this, you're right, thanks!

**Comment by dimvar** [comment]
FYI. A few days ago we submitted change 51dd82730ec76874a8de15a4b6b6d856d901fdb2, which lets you do `--isolation_mode=IIFE`. This is less error prone than writing your own output wrapper.
