### ISSUE TITLE
BanUnknownTypedClassPropsReferences spurious false positives under NTI

### ISSUE THREAD

**Issue by supersteves** [google/closure-compiler#2167]
I've a feeling this is a known limitation but couldn't find any hard evidence of this (e.g. existing issue).

I'm needing to disable this conformance check because I'm now getting a number of false positives where type information is categorically known for all values involved in an expression. This only happens when NTI is on. When OTI only is running, the check runs fine.

A version around mid summer did not have this issue.

I've not been able to put together a test case for this yet. If this is a known limitation, I'll leave it at that.

**Comment by dimvar** [comment]
Not a known issue. We definitely don't want to lose type information in NTI, so if you find a repro, please post it here and I'll fix. Closing for now since we can't do anything without a repro.

**Comment by supersteves** [comment]
https://closure-compiler-debugger.appspot.com/#input0%3Dclass%2520ST%2520%257B%250A%250A%2520%2520%2520%2520constructor()%2520%257B%250A%2520%2520%2520%2520%2520%2520%2520%2520window.setTimeout(()%2520%253D%253E%2520console.log(%2522a%2522)%252C%25200)%253B%250A%2520%2520%2520%2520%257D%250A%250A%257D%250A%250Aexport%2520default%2520new%2520ST()%253B%250A%26input1%26conformanceConfig%3Drequirement%253A%2520%257B%2520type%253A%2520CUSTOM%2520java_class%253A%2520'com.google.javascript.jscomp.ConformanceRules%2524BanUnknownTypedClassPropsReferences'%2520error_message%253A%2520'Unknown%2520typed%2520class%2520props%2520reference'%2520%257D%250A%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES%3D1%26CHECK_TYPES_NEW_INFERENCE%3D1%26CLOSURE_PASS%3D1%26MISSING_PROPERTIES%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1%26TRANSPILE%3D1

**Comment by supersteves** [comment]
@dimvar Here's one case where the unknown type is `setTimeout` on `window` from the default exterrns
I also had many more internal cases not related to externs, but hopefully this is the same problem. Should this be reopened or is this test case a different issue and known limitation?

**Comment by supersteves** [comment]
@dimvar did you get a chance to look at the new debugger link above? and perhaps reopen? I've currently disabled all benefit of this conformance check because of this issue.

**Comment by dimvar** [comment]
I didn't get a chance to look at this again yet. Will do. Hopefully this week.

**Comment by supersteves** [comment]
Thanks!
