### ISSUE TITLE
buildRegistry in ModuleLoader doesn't handle case of immediate node_modules

### ISSUE THREAD

**Issue by cramforce** [google/closure-compiler#2170]
E.g. if an input is `node_modules/left-pad/index.js` that never hits the split for `/node_modules/` and thus isn't subject to the resolve algorithm.

CC @ChadKillingsworth

**Comment by ChadKillingsworth** [comment]
Thanks. I hadn't seen this case because the grunt and gulp plugins don't use file paths like that.

**Comment by ChadKillingsworth** [comment]
The fix for this is part of #2130

**Comment by cramforce** [comment]
Nice, also fixes my next feature request :)

**Comment by ChadKillingsworth** [comment]
That PR is the culmination of a year's work.

**Comment by ChadKillingsworth** [comment]
Closed by #2130
