### ISSUE TITLE
Improve error messaging when extending native classes.

### ISSUE THREAD

**Issue by DavidSouther** [google/closure-compiler#2174]
Compiling

```javascript
class MyArray extends Array {}
```

Fails with:

```
input0:1: ERROR - ES6 transpilation of 'extending native class: Array' is not yet implemented.
class MyArray extends Array {}
^
```

Which was introduced in [156efeba](https://github.com/google/closure-compiler/commit/156efebaf52040ab5298e7111582dc2317c3f71d) to fix #2098, and as part of #1669. 

This is perfectly reasonably behavior - for numerous reasons, there's just no way to transpile this code sanely into pre-es6 semantics ([more discussion here](http://www.2ality.com/2015/02/es6-classes-final.html)).

I'm opening this issue to serve as a tracking issue if anyone finds it, and to possibly ask for a more forceful error message:

```
input0:1: ERROR - ES6 transpilation of 'extending native class: Array' has undefined semantics, and will not be supported [citation to discussion of why].
class MyArray extends Array {}
^
```

[Repro](https://closure-compiler-debugger.appspot.com/#input0%3Dclass%2520MyArray%2520extends%2520Array%2520%257B%257D%250A%250Aalert(new%2520MyArray())%253B%26input1%3D%2520%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES%3D1%26CLOSURE_PASS%3D1%26DEAD_ASSIGNMENT_ELIMINATION%3D1%26MISSING_PROPERTIES%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1%26REMOVE_DEAD_CODE%3D1%26REMOVE_UNUSED_CLASS_PROPERTIES%3D1%26REMOVE_UNUSED_PROTOTYPE_PROPERTIES%3D1%26REMOVE_UNUSED_PROTOTYPE_PROPERTIES_IN_EXTERNS%3D1%26REMOVE_UNUSED_VARIABLES%3D1%26TRANSPILE%3D1)

**Comment by ChadKillingsworth** [comment]
Are you volunteering to PR it?

**Comment by DavidSouther** [comment]
I could, sure. I'd want to discuss the appropriateness first, but I should be able to handle it.

**Comment by ChadKillingsworth** [comment]
I don't think we'd argue the appropriateness. Extending most native objects just requires the ES6 class syntax. There is a workaround for `Error`, but there is a long litany of others that will never be supported: `Date`, `Array`, `Promise`, ...

**Comment by brad4d** [comment]
The error message for the original example is now this.

```
input0:1: ERROR - This code cannot be converted from ES6. extending native class: Array
class MyArray extends Array {}
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

Is that forceful enough to close this issue?

**Comment by DavidSouther** [comment]
LGTM, TYVM
