### ISSUE TITLE
Missing a right curly brace in an example

### ISSUE THREAD

**Issue by bochunz** [google/closure-compiler#2177]
I guess the right curly brace is missing in the example code block of this section: https://github.com/google/closure-compiler/wiki/Annotating-JavaScript-for-the-Closure-Compiler#optional-parameter-in-a-param-annotation

**Comment by MatrixFrog** [comment]
For significant changes we appreciate you starting a discussion but for minor things like typos feel free to just edit the wiki directly.

**Comment by bochunz** [comment]
Just edited the wiki. Feel it's amazing I have the permission.
