### ISSUE TITLE
Constructor args not checked when imported and in scope [NTI]

### ISSUE THREAD

**Issue by supersteves** [google/closure-compiler#2179]
input0:
``` javascript
export default class I {
  /**
   * @param {number} a
   */
  constructor(a) {
    this.a = a;
  }
}
new I(); // 1
function f() {
  new I(); // 2
};
```
input1:
``` javascript
import I from "./input0";
new I(); // 3
function f() {
  new I(); // 4
};
```
([debugger](https://closure-compiler-debugger.appspot.com/#input0%3Dexport%2520default%2520class%2520I%2520%257B%250A%2520%2520%252F**%250A%2520%2520%2520*%2520%2540param%2520%257Bnumber%257D%2520a%250A%2520%2520%2520*%252F%250A%2520%2520constructor(a)%2520%257B%250A%2520%2520%2520%2520this.a%2520%253D%2520a%253B%250A%2520%2520%257D%250A%257D%250Anew%2520I()%253B%2520%252F%252F%25201%250Afunction%2520f()%2520%257B%250A%2520%2520new%2520I()%253B%2520%252F%252F%25202%250A%257D%253B%26input1%3Dimport%2520I%2520from%2520%2522.%252Finput0%2522%253B%250Anew%2520I()%253B%2520%252F%252F%25203%250Afunction%2520f()%2520%257B%250A%2520%2520new%2520I()%253B%2520%252F%252F%25204%250A%257D%253B%250A%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES%3D1%26CHECK_TYPES_NEW_INFERENCE%3D1%26CLOSURE_PASS%3D1%26MISSING_PROPERTIES%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1%26TRANSPILE%3D1))

With NTI: cases 1, 2, 3 emit NTI warnings about function arguments; case 4 does not.
With OTI: all four cases emit OTI warnings about function arguments.

Also, remove the `@param` jsdoc. 

With NTI: only case 2 emits a warning.
With OTI: as above, all four cases emit warnings.

**Comment by supersteves** [comment]
Another similar case which is pretty serious. Scoped type errors are lost under NTI, only OTI picks them up - we're now compiling with both OTI and NTI as separate passes, but OTI isn't clever enough for some of our cases.

Here, `test` fails in OTI + NTI. But `test2` fails only under OTI, NTI is silent:

A:
``` javascript
class B {}
export default B;
```
B:
``` javascript
import B from "./B";
let /** number */ test = B;
function a() {
    let /** number */ test2 = B;
}
export default a;
```

https://closure-compiler-debugger.appspot.com/#input0%3Dclass%2520B%2520%257B%257D%250Aexport%2520default%2520B%253B%250A%26input1%3Dimport%2520B%2520from%2520%2522.%252Finput0%2522%253B%250Alet%2520%252F**%2520number%2520*%252F%2520test%2520%253D%2520B%253B%250Afunction%2520a()%2520%257B%250A%2520%2520%2520%2520let%2520%252F**%2520number%2520*%252F%2520test2%2520%253D%2520B%253B%250A%257D%250Aexport%2520default%2520a%253B%250A%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES%3D1%26CHECK_TYPES_NEW_INFERENCE%3D1%26CLOSURE_PASS%3D1%26MISSING_PROPERTIES%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1%26TRANSPILE%3D1

**Comment by supersteves** [comment]
And another example. This time it's a real-world problem with React externs and ES6 classes and modules. Note I have simplified this and removed some aspects from our React externs which are not necessary to demonstrate the problem.

Externs:
``` javascript
var R = {}; // like React namespace

/**
 * @constructor
 * @template P
 * @param {P} props
 */
R.Component = function(props) {};

/**
 * @constructor
 */
R.Element = function() {};

/**
 * @template PP
 * @param {!function(new:R.Component<PP>, PP)} tag
 * @param {?PP} props
 */
R.createElement = function(tag, props) {};
```

B:
``` javascript
/**
 * @typedef {{
 *  somethingGood: number
 * }}
 */
let PropTypeDef;

/** @extends {R.Component<PropTypeDef>} */
class B extends R.Component {
    constructor(props) {
        super(props);
    }
}
export default B;
```

A:
``` javascript
import B from "./B";

R.createElement(B, { somethingGood: 5 });
R.createElement(B, { somethingBad: 5 });

function a() {
    R.createElement(B, { somethingGood: 5 });
    R.createElement(B, { somethingBad: 5 });
}

export default a;
```

Here, only the 1st `somethingBad` case fails NTI. the 2nd case is silent under NTI. 

https://closure-compiler-debugger.appspot.com/#input0%3D%250A%252F**%250A%2520*%2520%2540typedef%2520%257B%257B%250A%2520*%2520%2520somethingGood%253A%2520number%250A%2520*%2520%257D%257D%250A%2520*%252F%250Alet%2520PropTypeDef%253B%250A%250A%252F**%2520%2540extends%2520%257BR.Component%253CPropTypeDef%253E%257D%2520*%252F%250Aclass%2520B%2520extends%2520R.Component%2520%257B%250A%250A%2520%2520%2520%2520constructor(props)%2520%257B%250A%2520%2520%2520%2520%2520%2520%2520%2520super(props)%253B%250A%2520%2520%2520%2520%257D%250A%250A%257D%250A%250Aexport%2520default%2520B%253B%250A%26input1%3Dimport%2520B%2520from%2520%2522.%252Finput0%2522%253B%250A%250AR.createElement(B%252C%2520%257B%2520somethingGood%253A%25205%2520%257D)%253B%250AR.createElement(B%252C%2520%257B%2520somethingBad%253A%25205%2520%257D)%253B%250A%250Afunction%2520a()%2520%257B%250A%2520%2520%2520%2520R.createElement(B%252C%2520%257B%2520somethingGood%253A%25205%2520%257D)%253B%250A%2520%2520%2520%2520R.createElement(B%252C%2520%257B%2520somethingBad%253A%25205%2520%257D)%253B%250A%257D%250A%250Aexport%2520default%2520a%253B%250A%26conformanceConfig%26externs%3Dvar%2520R%2520%253D%2520%257B%257D%253B%2520%252F%252F%2520Proxy%2520for%2520React%2520namespace%2520typically%2520instead%2520as%2520externs%250A%250A%252F**%250A%2520*%2520%2540constructor%250A%2520*%2520%2540template%2520P%250A%2520*%2520%2540param%2520%257BP%257D%2520props%250A%2520*%252F%250AR.Component%2520%253D%2520function(props)%2520%257B%257D%253B%250A%250A%252F**%250A%2520*%2520%2540constructor%250A%2520*%252F%250AR.Element%2520%253D%2520function()%2520%257B%257D%253B%250A%250A%252F**%250A%2520*%250A%2520*%2520%2540template%2520PP%250A%2520*%2520%2540param%2520%257B!function(new%253AR.Component%253CPP%253E%252C%2520PP)%257D%2520tag%250A%2520*%2520%2540param%2520%257B%253FPP%257D%2520props%250A%2520*%252F%250AR.createElement%2520%253D%2520function(tag%252C%2520props)%2520%257B%257D%253B%250A%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES%3D1%26CHECK_TYPES_NEW_INFERENCE%3D1%26CLOSURE_PASS%3D1%26MISSING_PROPERTIES%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1%26TRANSPILE%3D1

**Comment by supersteves** [comment]
Aha! It's the use of the **default export**. Importing a named export works. But importing the default export drops errors in function/class scopes.

Externs as per last comment above.

B:
``` javascript
/**
 * @constructor
 * @param {{somethingGood: number}} props
 * @extends {R.Component<{somethingGood: number}>}
 */
function b(props) {}

export const B = /** @type {function(new:R.Component<{somethingGood: number}>, {somethingGood: number})} */(b); // not sure why I had to declare this here

export default B;
```
A:
``` javascript
//import B from "./input0"; // fails, 2nd error is dropped
import {B} from "./input0"; // works, both errors shown

R.createElement(B, { somethingGood: 5 });
R.createElement(B, { somethingBad: 5 });

function a() {
    R.createElement(B, { somethingGood: 5 });
    R.createElement(B, { somethingBad: 5 });
}
```

https://closure-compiler-debugger.appspot.com/#input0%3D%252F**%250A%2520*%2520%2540constructor%250A%2520*%2520%2540param%2520%257B%257BsomethingGood%253A%2520number%257D%257D%2520props%250A%2520*%2520%2540extends%2520%257BR.Component%253C%257BsomethingGood%253A%2520number%257D%253E%257D%250A%2520*%252F%250Afunction%2520b(props)%2520%257B%257D%250A%250Aexport%2520const%2520B%2520%253D%2520%252F**%2520%2540type%2520%257Bfunction(new%253AR.Component%253C%257BsomethingGood%253A%2520number%257D%253E%252C%2520%257BsomethingGood%253A%2520number%257D)%257D%2520*%252F(b)%253B%2520%252F%252F%2520not%2520sure%2520why%2520I%2520had%2520to%2520declare%2520this%2520here%250A%250Aexport%2520default%2520B%253B%26input1%3D%252F%252Fimport%2520B%2520from%2520%2522.%252Finput0%2522%253B%2520%252F%252F%2520fails%250Aimport%2520%257BB%257D%2520from%2520%2522.%252Finput0%2522%253B%2520%252F%252F%2520works%250A%250AR.createElement(B%252C%2520%257B%2520somethingGood%253A%25205%2520%257D)%253B%250AR.createElement(B%252C%2520%257B%2520somethingBad%253A%25205%2520%257D)%253B%250A%250Afunction%2520a()%2520%257B%250A%2520%2520%2520%2520R.createElement(B%252C%2520%257B%2520somethingGood%253A%25205%2520%257D)%253B%250A%2520%2520%2520%2520R.createElement(B%252C%2520%257B%2520somethingBad%253A%25205%2520%257D)%253B%250A%257D%250A%26conformanceConfig%26externs%3Dvar%2520R%2520%253D%2520%257B%257D%253B%2520%252F%252F%2520Proxy%2520for%2520React%2520namespace%2520typically%2520instead%2520as%2520externs%250A%250A%252F**%250A%2520*%2520%2540constructor%250A%2520*%2520%2540template%2520P%250A%2520*%2520%2540param%2520%257BP%257D%2520props%250A%2520*%252F%250AR.Component%2520%253D%2520function(props)%2520%257B%257D%253B%250A%250A%252F**%2520%2540constructor%2520*%252F%250AR.Element%2520%253D%2520function()%2520%257B%257D%253B%250A%250A%252F**%250A%2520*%2520%2540template%2520PP%250A%2520*%2520%2540param%2520%257B!function(new%253AR.Component%253CPP%253E%252C%2520PP)%257D%2520tag%250A%2520*%2520%2540param%2520%257B%253FPP%257D%2520props%250A%2520*%252F%250AR.createElement%2520%253D%2520function(tag%252C%2520props)%2520%257B%257D%253B%250A%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES%3D1%26CHECK_TYPES_NEW_INFERENCE%3D1%26CLOSURE_PASS%3D1%26MISSING_PROPERTIES%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1%26TRANSPILE%3D1

**Comment by dimvar** [comment]
I'll look into this in the next few days.

**Comment by supersteves** [comment]
Thanks. Note that this also doesn't work:
``` javascript
import {default as B} from "./input0";
```

**Comment by supersteves** [comment]
This kind of bugfix is beyond me, but I'd like to help if there's any way I can - let me know.

**Comment by dimvar** [comment]
Here is a simplified [repro](https://closure-compiler-debugger.appspot.com/#input0%3D%252F**%250A%2520*%2520%2540type%2520%257Bnumber%257D%250A%2520*%252F%250Avar%2520A%2520%253D%2520123%253B%250A%250Aexport%2520var%2520nonconstant%2520%253D%2520A%253B%250A%250Aexport%2520const%2520CONSTANT%2520%253D%2520A%253B%250A%250A%252F**%2520%2540const%2520*%252F%250Aexport%2520default%2520A%253B%26input1%3Dimport%2520A%2520from%2520%2522.%252Finput0%2522%253B%250Aimport%2520%257Bnonconstant%257D%2520from%2520%2522.%252Finput0%2522%253B%250Aimport%2520%257BCONSTANT%257D%2520%2520from%2520%2522.%252Finput0%2522%253B%250A%250Afunction%2520f()%2520%257B%250A%2520%2520%2520%2520%252F**%2520%2540type%2520%257Bnull%257D%2520*%252F%250A%2520%2520%2520%2520var%2520n%253B%250A%250A%2520%2520%2520%2520n%2520%253D%2520A%253B%250A%2520%2520%2520%2520n%2520%253D%2520nonconstant%253B%250A%2520%2520%2520%2520n%2520%253D%2520CONSTANT%253B%250A%257D%250A%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES%3D1%26CHECK_TYPES_NEW_INFERENCE%3D1%26CLOSURE_PASS%3D1%26MISSING_PROPERTIES%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1%26TRANSPILE%3D1). 

The gist of the issue is that when the exports are constants, NTI can infer their types and give warnings, otherwise it won't. So the workaround for you is to explicitly annotate the default export with `@const`. Can you also file an issue for ES6 module transpilation? When the default export is all caps, by the coding convention we should be annotating it with `@const` automatically. (You can remove the `@const` from the default export in my example to see which jsdoc goes away in the transpiled code.)

I think there is nothing to do for NTI here, the issue is with transpilation of ES6 modules.

**Comment by supersteves** [comment]
@dimvar Thanks for the analysis. I do see the capitalised const issue (non-obvious for non-google users) and will file that. But there's something else going on here.

Parent:
``` javascript
var a = /** @constructor */ function() {};
/** @const */ export default a;
```
Child:
``` javascript
import a from "./input0";
var /** null */ n1 = a;
function f() {
  var /** null */ n2 = a;
}
```
Here n1 warns, n2 is silent.

If you remove `@constructor`, both warn.

[Debugger](https://closure-compiler-debugger.appspot.com/#input0%3Dvar%2520a%2520%253D%2520%252F**%2520%2540constructor%2520*%252F%2520function()%2520%257B%257D%253B%250A%252F**%2520%2540const%2520*%252F%2520export%2520default%2520a%253B%250A%26input1%3Dimport%2520a%2520from%2520%2522.%252Finput0%2522%253B%250Avar%2520%252F**%2520null%2520*%252F%2520n1%2520%253D%2520a%253B%250Afunction%2520f()%2520%257B%250A%2520%2520var%2520%252F**%2520null%2520*%252F%2520n2%2520%253D%2520a%253B%250A%257D%250A%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES%3D1%26CHECK_TYPES_NEW_INFERENCE%3D1%26CLOSURE_PASS%3D1%26MISSING_PROPERTIES%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1%26TRANSPILE%3D1)

When I diff the debugger tree output, the only differences I can see (other than the `new:` function type info) are:

1. failing case has `jsdoc_info: JSDocInfo` for child's function, working case doesn't
2. failing case has `analyzed_during_gti: 1` for child's var, working case doesn't.

**Comment by dimvar** [comment]
Oh, you're right. It's a case of an aliased namespace definition not being detected. I'll fix it.

**Comment by supersteves** [comment]
Phew! Thanks :-)

**Comment by supersteves** [comment]
Thanks!
