### ISSUE TITLE
"Invalid generics instantiation" errors in Google Maps API extern using NTI

### ISSUE THREAD

**Issue by ghosttie** [google/closure-compiler#2188]
When compiling my project including the [Google Maps API extern](https://github.com/google/closure-compiler/blob/master/contrib/externs/maps/google_maps_api_v3.js) and using NTI I get these errors:

> _externs/google_maps_api_v3.js:2996: ERROR - Invalid generics instantiation for type google.maps.MVCArray.
> Expected 0 type argument(s), but found 1
>  * @type {Array<google.maps.MVCArray<Node>>}
>                 ^
> 
> _externs/google_maps_api_v3.js:3011: ERROR - Invalid generics instantiation for type google.maps.MVCArray.
> Expected 0 type argument(s), but found 1
>  * @type {google.maps.MVCArray<google.maps.MapType>}
>           ^
> 
> _externs/google_maps_api_v3.js:4124: ERROR - Invalid generics instantiation for type google.maps.MVCArray.
> Expected 0 type argument(s), but found 1
>  * @return {google.maps.MVCArray<google.maps.LatLng>}
>             ^
> 
> _externs/google_maps_api_v3.js:4130: ERROR - Invalid generics instantiation for type google.maps.MVCArray.
> Expected 0 type argument(s), but found 1
>  * @return {google.maps.MVCArray<google.maps.MVCArray<google.maps.LatLng>>}
>             ^
> 
> _externs/google_maps_api_v3.js:4130: ERROR - Invalid generics instantiation for type google.maps.MVCArray.
> Expected 0 type argument(s), but found 1
>  * @return {google.maps.MVCArray<google.maps.MVCArray<google.maps.LatLng>>}
>                                  ^
> 
> _externs/google_maps_api_v3.js:4165: ERROR - Invalid generics instantiation for type google.maps.MVCArray.
> Expected 0 type argument(s), but found 1
>  * @param {google.maps.MVCArray<google.maps.LatLng>|Array<google.maps.LatLng|google.maps.LatLngLiteral>} path
>            ^
> 
> _externs/google_maps_api_v3.js:4171: ERROR - Invalid generics instantiation for type google.maps.MVCArray.
> Expected 0 type argument(s), but found 1
>  * @param {google.maps.MVCArray<google.maps.MVCArray<google.maps.LatLng>>|google.maps.MVCArray<google.maps.LatLng>|Array<Array<google.maps.LatLng|google.maps.LatLngLiteral>>|Array<google.maps.LatLng|google.maps.LatLngLiteral>} paths
>            ^
> 
> _externs/google_maps_api_v3.js:4171: ERROR - Invalid generics instantiation for type google.maps.MVCArray.
> Expected 0 type argument(s), but found 1
>  * @param {google.maps.MVCArray<google.maps.MVCArray<google.maps.LatLng>>|google.maps.MVCArray<google.maps.LatLng>|Array<Array<google.maps.LatLng|google.maps.LatLngLiteral>>|Array<google.maps.LatLng|google.maps.LatLngLiteral>} paths
>                                 ^
> 
> _externs/google_maps_api_v3.js:4171: ERROR - Invalid generics instantiation for type google.maps.MVCArray.
> Expected 0 type argument(s), but found 1
>  * @param {google.maps.MVCArray<google.maps.MVCArray<google.maps.LatLng>>|google.maps.MVCArray<google.maps.LatLng>|Array<Array<google.maps.LatLng|google.maps.LatLngLiteral>>|Array<google.maps.LatLng|google.maps.LatLngLiteral>} paths
>                                                                           ^
> 
> _externs/google_maps_api_v3.js:4223: ERROR - Invalid generics instantiation for type google.maps.MVCArray.
> Expected 0 type argument(s), but found 1
>  * @type {google.maps.MVCArray<google.maps.MVCArray<google.maps.LatLng>>|google.maps.MVCArray<google.maps.LatLng>|Array<Array<google.maps.LatLng|google.maps.LatLngLiteral>>|Array<google.maps.LatLng|google.maps.LatLngLiteral>}
>           ^
> 
> _externs/google_maps_api_v3.js:4223: ERROR - Invalid generics instantiation for type google.maps.MVCArray.
> Expected 0 type argument(s), but found 1
>  * @type {google.maps.MVCArray<google.maps.MVCArray<google.maps.LatLng>>|google.maps.MVCArray<google.maps.LatLng>|Array<Array<google.maps.LatLng|google.maps.LatLngLiteral>>|Array<google.maps.LatLng|google.maps.LatLngLiteral>}
>                                ^
> 
> _externs/google_maps_api_v3.js:4223: ERROR - Invalid generics instantiation for type google.maps.MVCArray.
> Expected 0 type argument(s), but found 1
>  * @type {google.maps.MVCArray<google.maps.MVCArray<google.maps.LatLng>>|google.maps.MVCArray<google.maps.LatLng>|Array<Array<google.maps.LatLng|google.maps.LatLngLiteral>>|Array<google.maps.LatLng|google.maps.LatLngLiteral>}
>                                                                          ^
> 
> _externs/google_maps_api_v3.js:4284: ERROR - Invalid generics instantiation for type google.maps.MVCArray.
> Expected 0 type argument(s), but found 1
>  * @return {google.maps.MVCArray<google.maps.LatLng>}
>             ^
> 
> _externs/google_maps_api_v3.js:4319: ERROR - Invalid generics instantiation for type google.maps.MVCArray.
> Expected 0 type argument(s), but found 1
>  * @param {google.maps.MVCArray<google.maps.LatLng>|Array<google.maps.LatLng|google.maps.LatLngLiteral>} path
>            ^
> 
> _externs/google_maps_api_v3.js:4366: ERROR - Invalid generics instantiation for type google.maps.MVCArray.
> Expected 0 type argument(s), but found 1
>  * @type {google.maps.MVCArray<google.maps.LatLng>|Array<google.maps.LatLng|google.maps.LatLngLiteral>}
>           ^
> 
> _externs/google_maps_api_v3.js:4795: ERROR - Invalid generics instantiation for type google.maps.MVCArray.
> Expected 0 type argument(s), but found 1
>  * @type {Array<google.maps.MVCArray<Node>>}
>                 ^
> 
> _externs/google_maps_api_v3.js:5832: ERROR - Invalid generics instantiation for type google.maps.MVCArray.
> Expected 0 type argument(s), but found 1
>  * @param {Array<google.maps.LatLng>|google.maps.MVCArray<google.maps.LatLng>} path
>                                      ^
> 
> _externs/google_maps_api_v3.js:5859: ERROR - Invalid generics instantiation for type google.maps.MVCArray.
> Expected 0 type argument(s), but found 1
>  * @param {Array<google.maps.LatLng>|google.maps.MVCArray<google.maps.LatLng>} path
>                                      ^
> 
> _externs/google_maps_api_v3.js:5881: ERROR - Invalid generics instantiation for type google.maps.MVCArray.
> Expected 0 type argument(s), but found 1
>  * @param {Array<google.maps.LatLng>|google.maps.MVCArray<google.maps.LatLng>} path
>                                      ^
> 
> _externs/google_maps_api_v3.js:5906: ERROR - Invalid generics instantiation for type google.maps.MVCArray.
> Expected 0 type argument(s), but found 1
>  * @param {Array<google.maps.LatLng>|google.maps.MVCArray<google.maps.LatLng>} loop
>                                      ^
> 
> _externs/google_maps_api_v3.js:6620: ERROR - Invalid generics instantiation for type google.maps.MVCArray.
> Expected 0 type argument(s), but found 1
>  * @return {google.maps.MVCArray<google.maps.LatLng|google.maps.visualization.WeightedLocation>}
>             ^
> 
> _externs/google_maps_api_v3.js:6631: ERROR - Invalid generics instantiation for type google.maps.MVCArray.
> Expected 0 type argument(s), but found 1
>  * @param {google.maps.MVCArray<google.maps.LatLng|google.maps.visualization.WeightedLocation>|
>            ^
> 
> _externs/google_maps_api_v3.js:6655: ERROR - Invalid generics instantiation for type google.maps.MVCArray.
> Expected 0 type argument(s), but found 1
>  * @type {google.maps.MVCArray<google.maps.LatLng>}
>           ^
> 
> 23 error(s), 0 warning(s)
> 

I think the problem could just be that the definition of google.maps.MVCArray doesn't specify a @template.

I'm not sure who's responsible for this file so who to submit the bug to.

**Comment by dimvar** [comment]
yes, that's the issue. All of the redundant instantiations should be removed from these files.

**Comment by cwellsx** [comment]
Since it's an issue in an extern file, I hide it using the following option:

    --hide_warnings_for google_maps_api_v3_27.js

**Comment by cpcallen** [comment]
Since NTI is gone this could probably be closed.
