### ISSUE TITLE
Transpilation of async uses es6 Promise without polyfill

### ISSUE THREAD

**Issue by patstuart** [google/closure-compiler#2194]
Async/await code doesn't provide the Promise polyfill when transpiling into ECMASCRIPT5 or older.

For example, Internet Explorer breaks when it tries to run over transpiled async with the following error

```
ReferenceError: 'Promise' is undefined
    at $jscomp.executeAsyncGenerator (foo.min.js:120)
```

You can see from the transpiled code [here](https://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540compilation_level%2520SIMPLE_OPTIMIZATIONS%250A%252F%252F%2520%2540language_out%2520ECMASCRIPT5%250A%252F%252F%2520%2540language_in%2520ECMASCRIPT8%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250A%252F%252F%2520ADD%2520YOUR%2520CODE%2520HERE%250Aasync%2520function%2520foo()%2520%257B%250A%2520%2520await%2520bar()%253B%250A%257D%250A%250A) that the polyfill is not provided.

**Comment by brad4d** [comment]
@patstuart 
Thanks for the report.

You should specify a language input mode of `ECMASCRIPT_NEXT` and `--rewrite_polyfills` in order to get the polyfills needed for async/await.

If you look at the warnings tab on your example link you'll see this.

```
JSC_PARSE_ERROR: Parse error. this language feature is only supported for ECMASCRIPT8 mode or better: async function at line 2 character 0
async function foo() {
^
JSC_PARSE_ERROR: Parse error. this language feature is only supported for ECMASCRIPT8 mode or better: async function at line 3 character 2
  await bar();
  ^
```

**Comment by patstuart** [comment]
Brad,

Thanks. You'll note that I am already compiling with the ECMASCRIPT8, and [the service produces the same error occurs with your alternative syntax](https://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540compilation_level%2520SIMPLE_OPTIMIZATIONS%250A%252F%252F%2520%2540language_out%2520ECMASCRIPT5%250A%252F%252F%2520%2540language_in%2520ECMASCRIPT_NEXT%250A%252F%252F%2520%2540rewrite_polyfills%2520true%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250A%252F%252F%2520ADD%2520YOUR%2520CODE%2520HERE%250Aasync%2520function%2520foo()%2520%257B%250A%2520%2520await%2520bar()%253B%250A%257D%250A%250A). I don't know why, since I do not get any warnings on my own machine. I am using the latest compiler.

Regardless, the problem is not that the compiler can't handle async. It's that it handles async, but it doesn't automatically add the polyfill: `$jscomp.polyfill("Promise", ...`

My temporary workaround is to make reference to a promise elsewhere in the code, which forces the compiler will add the polyfill. E.g., `window.a = new Promise();`

Here are my compiler options as proof:
```
--language_in ECMASCRIPT_NEXT 
--language_out ECMASCRIPT5 
--rewrite_polyfills 
--compilation_level SIMPLE 
```

Let me know if there is anything else I can add which could help.

**Comment by brad4d** [comment]
@shicks Could some of your recent changes be preventing the Promise polyfill being included here?

**Comment by brad4d** [comment]
I'm trying to reproduce this with a runtime test.

**Comment by patstuart** [comment]
thank you!
