### ISSUE TITLE
Support JSDoc typedef and property

### ISSUE THREAD

**Issue by tSte** [google/closure-compiler#2195]
I'd love to use the compiler with JSDoc `typedef` and `property` annotations.

I know that `typedef` can be currently used, but it requires to define an actual JavaScript variable.

e.g.
```
/**
 * @typedef {{
 *  x:number,
 *  y:number
 * }}
 */
let Point;
```

According to [JSDoc typedef docs](http://usejsdoc.org/tags-typedef.html) it can be named within the annotiation itself => it does not require the `let Point;` code.

I know that it is not a big deal. Well, it is a bit, because we use the ESLint to lint our code and unused variables are considered to be an error (I am aware that I can add exception, but it's annoying).

It would be great if the compiler supported the [property annotation](http://usejsdoc.org/tags-property.html) too. Again, I know that I can use record-like annotation, but this seems to be a bit more readable.

```
/**
 * @typedef {Object} Point
 * @property {!number} x Longitude
 * @property {!number} y Latitude
 */
```

EDIT:
I tried to compile the following `typedef `with the rest of my code.

```
/**
 * @typedef {Object} Point
 * @property {number} lat
 * @property {number} lon
 */
var Point;
```

and it seems to work. But it is not listed in the [Closure annotation docs](https://github.com/google/closure-compiler/wiki/Annotating-JavaScript-for-the-Closure-Compiler). Is the `property` annotation already supported?

**Comment by dimvar** [comment]
> Is the property annotation already supported?

It's not supported. See this [example](https://closure-compiler-debugger.appspot.com/#input0%3D%252F**%250A%2520*%2520%2540typedef%2520%257BObject%257D%2520Point%250A%2520*%2520%2540property%2520%257Bnumber%257D%2520lat%250A%2520*%2520%2540property%2520%257Bnumber%257D%2520lon%250A%2520*%252F%250Avar%2520Point%253B%250A%250Afunction%2520f(%252F**%2520!Point%2520*%252F%2520x)%2520%257B%250A%2520%2520var%2520%252F**%2520null%2520*%252F%2520n%2520%253D%2520x.lat%253B%250A%257D%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES%3D1%26CLOSURE_PASS%3D1%26MISSING_PROPERTIES%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1%26TRANSPILE%3D1) where property lat is not recognized.

As for the original request, we don't have plans for these additions. Having many ways to annotate the same thing can be confusing.

**Comment by tschaub** [comment]
@dimvar - is there any chance this could be reconsidered?  I agree that multiple annotation styles can be confusing, but the `@typedef` and `@property` combo feels like it is clearly better syntax for these reasons:

 * it works (or could work) for both type checking and documentation
 * it doesn't require any code that might cause issues with other tools (e.g. [a rule](https://eslint.org/docs/rules/no-unused-vars) that errors on unused variables)

The Closure Compiler offers a lot of great functionality.  The development experience using it could be improved if it "played well" with other tools - specifically documentation and static analysis tools.

**Comment by mk0x9** [comment]
And about type name? In case we defining type as variable in the extern file it could be name-clashed with other identifier in minified code.

**Comment by phb** [comment]
Another vote to reconsider this. It's getting increasingly hard to justify following closure rules whenever someone googles jsdoc and picks the (cleaner?) syntax of @typedef + @property

**Comment by christiantjl** [comment]
If we could at least add some kind of explicit error, so that it's just just `JSC_UNRECOGNIZED_TYPE_ERROR` when nothing is wrong with syntax. Kinda silly:

```
/**
 * A callback that modifies Widget state in
 * response to an event or other trigger. Not
 * throttled.
 * 
 * @typedef {Function} StateGenerator
 */
```
Fails unless you add a dummy variable, `let StateGenerator;` below it.

Many thanks to @tSte for this workaround.
