### ISSUE TITLE
Expose NTI info to custom passes

### ISSUE THREAD

**Issue by supersteves** [google/closure-compiler#2199]
I'd like to be able to access NTI type information from custom passes (added to CompilerOptions via java API from external code) but find I only have weaker OTI information. 

It appears the NTI type information is erased after NTI checks are performed, leaving only weaker OTI type information, and it doesn't have the detail I need.

I gather that the codebase is slowly moving over to *support* NTI type information by using `TypeI` umbrella interfaces instead of the OTI-specific interfaces. Such that at some point in the future it will be retained. But presumably none of the other checks and optimisations actually use NTI information yet, since only OTI information is retained in the registry / on the nodes.

This would be useful for cases where I want to add custom passes that won't ever be accepted as PRs because they relate to something very specific to our codebase. For example, we use React extensively and want to be able to add custom passes that generate runtime PropTypes. Also, https://github.com/google/closure-compiler/pull/2198 is an example of a PR which I could have attempted using a custom pass (though prefer not to), but for this issue.

**Comment by dimvar** [comment]
All checks after NTI use NTI-generated type information. The old type checker runs at the very end of the checks. So if you are writing a custom check, the `TypeI` types you get from AST nodes are implemented by NTI types.

Is that sufficient for you, or are you asking for access to the NTI types directly instead of TypeI?

**Comment by supersteves** [comment]
I added a custom pass to the options to run in `CustomPassExecutionTime.BEFORE_OPTIMIZATIONS` stage. When it ran, the nodes I was given had OTI JSTypes attached to them. The options were configured with NTI and NTI definitely ran.

**Comment by dimvar** [comment]
Yeah, if you are using that option your pass [runs at the very end of checks](https://github.com/google/closure-compiler/blob/master/src/com/google/javascript/jscomp/Compiler.java#L887), so it's after the old type checker.

Can you configure the PassConfig to do what you want? Eg, by using [this method](https://github.com/google/closure-compiler/blob/master/src/com/google/javascript/jscomp/PassConfig.java#L200)?
If not, we'd probably take a PR that adds a non-static method to PassConfig saying "insert my custom pass after pass X". AFAIK, the custom passes are a seldom-used mechanisms, so we can assume that whoever uses it know what they're doing, and can insert the pass wherever.

**Comment by supersteves** [comment]
I imagine most users of the compiler use the command line, and I tend to use the fork route if customising the compiler (typically with the intent of creating a PR), but for some checks which are very far off the beaten track and perhaps which need interop with our own broader codebase, custom passes are useful. Next time this comes up, I'll create a PR to add a post-NTI option for when to run it, for example.

**Comment by realityforge** [comment]
@EatingW NTI was dropped so this issue should be able to be closed

**Comment by EatingW** [comment]
Thanks!
