### ISSUE TITLE
PureFunctionIdentifier incorrectly causing dead code removal

### ISSUE THREAD

**Issue by christiang88** [google/closure-compiler#2203]
I noticed that some code was getting incorrectly removed in newer versions of the compiler. The repro is simple:
```javascript
var SetCustomData1 = function SetCustomData2(element, dataName, dataValue) {
    var x = element['_customData'];
    x[dataName] = dataValue;
}

SetCustomData1(window, "foo", "bar");
```

When this is compiled in advanced mode, all this code gets incorrectly removed.

However, if I remove the name set directly on the function:
```javascript
var SetCustomData1 = function (element, dataName, dataValue) {
    var x = element['_customData'];
    x[dataName] = dataValue;
}

SetCustomData1(window, "foo", "bar");
```
I get the correct output:
```javascript
window._customData.foo="bar";
```

I also get the correct output if I inline the local variable x:
```javascript
var SetCustomData1 = function SetCustomData2(element, dataName, dataValue) {
    element['_customData'][dataName] = dataValue;;

}

SetCustomData1(window, "foo", "bar");
```

I can of course look for instances of this in my code and update it, but I am a bit concerned that this is just a symptom of a larger problem.

I did a git bisect to track down when this started happening and it appears to have been introduced with the changes made to PureFunctionIdentifier in 6b2d7b218c0e465346070c39ae912f1fb263cf26.

**Comment by MatrixFrog** [comment]
@tadeegan can you take a look?

**Comment by tadeegan** [comment]
Hmmm. We test for similar things here:

https://github.com/google/closure-compiler/blob/5943281a75f6171e337e757f7c72dd504bfb2b3f/test/com/google/javascript/jscomp/PureFunctionIdentifierTest.java#L1280

I will check this out when I have time (probably january). Feel free to assign to me.

**Comment by blickly** [comment]
Since this is a correctness issue, I think it'd be best to rollback first and then make sure to check this case when rolling forward.

**Comment by tadeegan** [comment]
This should be fixed now.

**Comment by Dominator008** [comment]
Closed by https://github.com/google/closure-compiler/commit/6ea1fb0a792682ead31d898828daacfb0c598e67.

**Comment by christiang88** [comment]
Confirmed this fixed the bug on our site. Thanks for taking the time to fix this!
