### ISSUE TITLE
INTERNAL COMPILER ERROR on recursive function with NTI

### ISSUE THREAD

**Issue by MrsKensington** [google/closure-compiler#2208]
I've been working on getting my library compiled with NTI turned on and have been getting a compiler error. I finally managed to narrow it down to one function which causes the issue.

```
var TPJL = {};
TPJL.FlattenObject = function(data) {
    var result = {};
    function recurse(cur, prop) {
        if (Object(cur) !== cur) {
            result[prop] = cur;
        } else if (Array.isArray(cur)) {
            for (var i = 0, l = cur.length; i < l; i++)
                recurse(cur[i], prop ? prop + '.' + i : '' + i);
            if (l == 0)
                result[prop] = [];
        } else {
            var isEmpty = true;
            for (var p in cur) {
                isEmpty = false;
                recurse(cur[p], prop ? prop + '.' + p : p);
            }
            if (isEmpty)
                result[prop] = {};
        }
    }
    recurse(data, '');
    return result;
};
```

When I try to compile that with the latest git version I get....
> [root@mikespc ~]# /usr/bin/java -jar closure-compiler-1.0-SNAPSHOT.jar  --new_type_inf test.js 
> java.lang.RuntimeException: java.lang.RuntimeException: INTERNAL COMPILER ERROR.
> Please report this problem.
> 
> Expected object type but found bottom
> In scope: recurse(cur,prop) with root: FUNCTION recurse 4 [length: 582] [source_file: test.js]
> 	at com.google.javascript.jscomp.CompilerExecutor.runInCompilerThread(CompilerExecutor.java:126)
> 	at com.google.javascript.jscomp.Compiler.runInCompilerThread(Compiler.java:740)
> 	at com.google.javascript.jscomp.Compiler.compile(Compiler.java:710)
> 	at com.google.javascript.jscomp.Compiler.compile(Compiler.java:680)
> 	at com.google.javascript.jscomp.AbstractCommandLineRunner.doRun(AbstractCommandLineRunner.java:1080)
> 	at com.google.javascript.jscomp.AbstractCommandLineRunner.run(AbstractCommandLineRunner.java:492)
> 	at com.google.javascript.jscomp.CommandLineRunner.main(CommandLineRunner.java:1841)
> Caused by: java.lang.RuntimeException: INTERNAL COMPILER ERROR.
> Please report this problem.
> 
> Expected object type but found bottom
> In scope: recurse(cur,prop) with root: FUNCTION recurse 4 [length: 582] [source_file: test.js]
> 	at com.google.common.base.Preconditions.checkState(Preconditions.java:518)
> 	at com.google.javascript.jscomp.newtypes.JSType.isStruct(JSType.java:377)
> 	at com.google.javascript.jscomp.NewTypeInference.analyzeFunctionFwd(NewTypeInference.java:1021)
> 	at com.google.javascript.jscomp.NewTypeInference.analyzeFunction(NewTypeInference.java:838)
> 	at com.google.javascript.jscomp.NewTypeInference.process(NewTypeInference.java:480)
> 	at com.google.javascript.jscomp.PhaseOptimizer$NamedPass.process(PhaseOptimizer.java:296)
> 	at com.google.javascript.jscomp.PhaseOptimizer.process(PhaseOptimizer.java:228)
> 	at com.google.javascript.jscomp.Compiler.check(Compiler.java:873)
> 	at com.google.javascript.jscomp.Compiler.compileInternal(Compiler.java:766)
> 	at com.google.javascript.jscomp.Compiler.access$000(Compiler.java:84)
> 	at com.google.javascript.jscomp.Compiler$2.call(Compiler.java:713)
> 	at com.google.javascript.jscomp.Compiler$2.call(Compiler.java:710)
> 	at com.google.javascript.jscomp.CompilerExecutor$2.call(CompilerExecutor.java:91)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
> 	at java.lang.Thread.run(Thread.java:745)
> Caused by: java.lang.IllegalStateException: Expected object type but found bottom
> 	... 17 more

**Comment by MrsKensington** [comment]
I've managed to narrow it down a bit further. It's nothing to do with the recursiveness of the function, it's actually where it loops over the properties of the object. It can be fixed by adding the following annotation...

```
            var isEmpty = true;
            cur = /** @type {Object} */ (cur);
            for (var p in cur) {
                isEmpty = false;
                recurse(cur[p], prop ? prop + '.' + p : p);
            }
```

**Comment by dimvar** [comment]
Thank you for the report. Narrowed it down to [this](https://closure-compiler-debugger.appspot.com/#input0%3Dfunction%2520f(x)%2520%257B%250A%2520%2520if%2520(Object(x)%2520%253D%253D%253D%2520x%2520%2526%2526%2520!Array.isArray(x))%2520%257B%250A%2520%2520%2520%2520for%2520(var%2520p%2520in%2520x)%2520%257B%257D%250A%2520%2520%257D%250A%257D%250A%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES%3D1%26CHECK_TYPES_NEW_INFERENCE%3D1%26CLOSURE_PASS%3D1%26MISSING_PROPERTIES%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1%26TRANSPILE%3D1). Will fix.
