### ISSUE TITLE
ES6 support

### ISSUE THREAD

**Issue by blickly** [google/closure-compiler#221]
This issue was imported from Closure Compiler's previous home at http://closure-compiler.googlecode.com

The link to the original issue is:
https://code.google.com/p/closure-compiler/issues/detail?id=1102

**Comment by agentx-cgn** [comment]
Just downloaded latest compiler and tried language_in with ECMASCRIPT6_STRICT with whitespace and simple. In both cases the process didn't finish within 20 minutes so I killed it. Looking at htop revealed it consumed CPU only a few seconds after start. 

Also it warned that ECMASCRIPT6_STRICT is not supported as output language. Is this planned?

Shouldn't at least whitespace work with ECMASCRIPT6_STRICT in and out?

**Comment by MatrixFrog** [comment]
The whitespace-only mode will probably work if you remove the check in CompilerOptionsPreprocessor. We just added that check so that users would get a clean error instead of random crashes in passes that don't understand ES6 yet. All passes will eventually understand ES6, it's just not a priority for us until browser support is most of the way there.

The compiler sitting idle for 20 minutes sounds like it was waiting to receive some JavaScript from stdin.

**Comment by agentx-cgn** [comment]
Thanks. I've got 3 types of warnings/errors:  

WARNING - Keywords and reserved words are not allowed as unquoted property names in older versions of JavaScript.
ERROR - this language feature is only supported in es6 mode: short function syntax
ERROR - Parse error. IE8 (and below) will parse trailing commas in array and object literals incorrectly.

Is there an option to disable them? Not sure which jscomp_error flag applies...

**Comment by MatrixFrog** [comment]
Can you provide the full command-line that you're using and the JS you're trying to compile?

**Comment by agentx-cgn** [comment]
java -jar compiler.jar --compilation_level WHITESPACE_ONLY --js hannibal.m.js --js_output_file hannibal.js
https://dl.dropboxusercontent.com/u/354885/0ad/hannibal.m.js

**Comment by MatrixFrog** [comment]
Switching to --language_in=ES6 (or ES6_STRICT) and --language_out=ES5 (or ES5_STRICT or ES3) should solve all of these:

Keywords as property names (`foo.class`) is allowed in ES5 and up.
Arrow functions (aka "short functions") are allowed in ES6 and up.
Trailing commas in object/array literals are allowed in ES5 and up.

**Comment by agentx-cgn** [comment]
Well, It should remain ES6. Transpiling Maps and arrow functions will probably slow down the code a lot and --language_in=ES6 *and* language_out=ES6  doesn't work. (ES6 is only supported for transpilation to a lower ECMAScript version...)

**Comment by MatrixFrog** [comment]
Right. We added the "ES6 is only supported for transpilation" check to avoid crashes, because the huge majority of passes don't support ES6. You're welcome to remove that check in your local version of the compiler, and whitespace-only mode will probably work.

**Comment by agentx-cgn** [comment]
> You're welcome to remove that check in your local version...

Not sure I understand, I only have "compiler.jar".

**Comment by MatrixFrog** [comment]
You'd have to build the compiler yourself with Ant or Maven if you want to make changes to it.

**Comment by agentx-cgn** [comment]
I see. Is it worth to create an issue to make this internal check a command line option? It would add out-of-the-box minimal ES6 support.

**Comment by MatrixFrog** [comment]
Yeah, we should probably do that. We'll want it eventually anyway. If you can open a new issue that would be great.

**Comment by concavelenz** [comment]
I think we should close this in favor of:
1) a bug for supporting ES6 with the NTI (type check only)
2) a bug for supporting ES6 for whitespace only (if it doesn't currently work)
3) a bug for supporting ES6 in simple mode end to end
4) a bug for supporting ES6 in advanced mode but we need to think what that would actually look like.

**Comment by MatrixFrog** [comment]
1) https://github.com/google/closure-compiler/issues/948
2) It does, with the --allow_es6_out flag
3) https://github.com/google/closure-compiler/issues/949
4) https://github.com/google/closure-compiler/issues/950

**Comment by MatrixFrog** [comment]
And, we can get rid of that flag once 948,949,950 are fixed. We just have it there right now, so that people get an error instead of a crash.

**Comment by dotnetCarpenter** [comment]
@MatrixFrog Can the webservice UI transpile ES6? I tried with
```js
// ==ClosureCompiler==
// @compilation_level SIMPLE_OPTIMIZATIONS
// @output_file_name default.js
// @language-in ECMASCRIPT6_STRICT
// @language-out ES5_STRICT
// ==/ClosureCompiler==

// ADD YOUR CODE HERE
"use strict";
let hello = name => {
  alert('Hello, ' + name);
}
hello('New user');
```

**Comment by concavelenz** [comment]
We should change the default to in as ES6 and out as ES5, but I update the wiki page to include the "language_out" option which is needed:

https://github.com/google/closure-compiler/wiki/Additional-Webservice-Options

Here is an example, with "language" and "language_out":

http://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540compilation_level%2520SIMPLE_OPTIMIZATIONS%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%2540language%2520ECMASCRIPT6_STRICT%250A%252F%252F%2520%2540language_out%2520ES5_STRICT%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250A%252F%252F%2520ADD%2520YOUR%2520CODE%2520HERE%250A%2522use%2520strict%2522%253B%250Alet%2520hello%2520%253D%2520name%2520%253D%253E%2520%257B%250A%2520%2520alert('Hello%252C%2520'%2520%252B%2520name)%253B%250A%257D%250Ahello('New%2520user')%253B

**Comment by dotnetCarpenter** [comment]
@concavelenz thanks!
