### ISSUE TITLE
Calling super causes NPE compiling an object.

### ISSUE THREAD

**Issue by sindilevich** [google/closure-compiler#2212]
Calling `super` in an overridden method causes a NPE at compile-time.

http://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%2540compilation_level%2520WHITESPACE_ONLY%250A%252F%252F%2520%2540formatting%2520pretty_print%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%2522use%2520strict%2522%253B%250A%250Avar%2520obj%2520%253D%2520%257B%250A%2520%2520%2520%2520%252F%252F%2520__proto__%250A%2520%2520%2520%2520__proto__%253A%2520theProtoObj%252C%250A%2520%2520%2520%2520%252F%252F%2520Shorthand%2520for%2520%25E2%2580%2598handler%253A%2520handler%25E2%2580%2599%250A%2520%2520%2520%2520handler%252C%250A%2520%2520%2520%2520%252F%252F%2520Methods%250A%2520%2520%2520%2520toString()%2520%257B%250A%2520%2520%2520%2520%2520%252F%252F%2520Super%2520calls%250A%2520%2520%2520%2520%2520return%2520%2522d%2520%2522%2520%252B%2520super.toString()%253B%250A%2520%2520%2520%2520%257D%252C%250A%2520%2520%2520%2520%252F%252F%2520Computed%2520(dynamic)%2520property%2520names%250A%2520%2520%2520%2520%255B%2520'prop_'%2520%252B%2520(()%2520%253D%253E%252042)()%2520%255D%253A%252042%250A%257D%253B

**Comment by brad4d** [comment]
A simplified version of the example:
```javascript
var obj = {
    toString() {
     return "d " + super.toString();
    },
};
```

I don't believe we intend to support use of `super` in object literals, just in classes.
The fix for this, then, would be to issue an error for this usage.
