### ISSUE TITLE
google closure compiler jar detected as Win.Trojan.Toa-5370297 by ClamAV since 23/12/16

### ISSUE THREAD

**Issue by vincent-guesnard** [google/closure-compiler#2216]
Hello,

That's not a very good "gift" if i can call it like this. I'm so sorry for this since it's Christmas Day

The .jar file is detected by ClamAV as a Trojan under this name : Win.Trojan.Toa-5370297 - All my weatherboards are in the red because of this.

If you have an idea to correct this it would be very appreciated.

http://www.gossamer-threads.com/lists/clamav/virusdb/68417

**Comment by Dominator008** [comment]
This seems like an issue with ClamAV :)
