### ISSUE TITLE
Null argument for Array.prototype.indexOf

### ISSUE THREAD

**Issue by kwkbtr** [google/closure-compiler#2218]
Calling `Array.prototype.indexOf` on an array of a non-nullable type with a parameter `null` is currently forbidden:

```javascript
/** @type {Array<string>} */ var arr = [];
var i = arr.indexOf(null);
// → WARNING - actual parameter 1 of Array.prototype.indexOf does not match formal parameter
```

The reason is [the following extern in es3.js](https://github.com/google/closure-compiler/blob/56aa496ea370f5101e5309e96685b82511278a28/externs/es3.js#L778-L788):
```javascript
/**
 * Available in ECMAScript 5, Mozilla 1.6+.
 * @param {T} obj
 * @param {number=} opt_fromIndex
 * @return {number}
 * @this {IArrayLike<T>|string}
 * @nosideeffects
 * @template T
 * @see http://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/indexOf
 */
Array.prototype.indexOf = function(obj, opt_fromIndex) {};
```

I think the `null` parameter should be allowed, though in that case `indexOf` will always return `-1`.

**Comment by MatrixFrog** [comment]
If you have an `Array<string>` (that is, you don't expect nulls in the array) then there is no good reason to pass null. Of course you _can_ do it just as you can pass a number, or an Object, but it makes no sense to do it.

If you _do_ expect nulls, annotate the array as `Array<?string>`.

**Comment by kwkbtr** [comment]
> Of course you *can* do it just as you can pass a number, or an Object

Right, so maybe the parameter `obj` can be annotated with `{*}`.

It seems to me that a shortcoming of the current annotation is that the following code is not allowed, which I believe is always safe:

```javascript
/**
 * @param {!Array<string>} arr
 * @param {?string} obj
 * @return {number}
 */
function foo(arr, obj) {
  return arr.indexOf(obj);
}
```

To avoid the warning, I need to rewrite the code as follows:

```javascript
/**
 * @param {!Array<string>} arr
 * @param {?string} obj
 * @return {number}
 */
function foo(arr, obj) {
  return obj ? arr.indexOf(obj) : -1;
}
```

I can put up with this limitation, but I prefer the first code for its conciseness.

**Comment by Dominator008** [comment]
You can cast `obj` to `string` with `/** @type {string} */ (obj)`.

**Comment by Dominator008** [comment]
I think the current behavior is correct. The use case you mentioned doesn't seem to warrant a relaxation on the type annotation, so I'm closing this.
