### ISSUE TITLE
INEXISTENT_PARAM to ERROR

### ISSUE THREAD

**Issue by marcfallows** [google/closure-compiler#2224]
If the annotation parameter names don't match the method signature I get a `JSC_INEXISTENT_PARAM` WARNING.

See this code which goes through without ERROR, where I really feel it should error:
https://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540compilation_level%2520ADVANCED_OPTIMIZATIONS%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250A%252F%252F%2520ADD%2520YOUR%2520CODE%2520HERE%250A%252F**%250A%2520*%2520%2540param%2520%257Bnumber%257D%2520foo%250A%2520*%2520%2540param%2520%257Bstring%257D%2520bar%250A%2520*%252F%250Afunction%2520hello(name)%2520%257B%250A%2520%2520alert('Hello%252C%2520'%2520%252B%2520name)%253B%250A%257D%250Ahello('123')%253B%250A%250A

There doesn't seem to be an exposed `DiagnosticGroup` to raise this [warning category](https://github.com/google/closure-compiler/wiki/Warnings#warnings-categories) to an ERROR.

**Comment by Dominator008** [comment]
I'll see if this can be added to the "functionParams" group: https://github.com/google/closure-compiler/blob/c7e6dda1586997b9f566cf91d2bf1c938b27f9c3/src/com/google/javascript/jscomp/DiagnosticGroups.java#L544

**Comment by marcfallows** [comment]
Thanks!
