### ISSUE TITLE
Is it possible to add an option to ignore extern variable checks

### ISSUE THREAD

**Issue by a701440** [google/closure-compiler#2225]
Minifying file below it complains about the undeclared variable window.Math.
Short of providing separate externs file there is currently no way to disable this check. It appears to fail in the sanityCheck pass. Had to rewrite the code as window['Math']. A special annotation would work as well. /* @extern Math */

(function(Math) {
....
})(window.Math);

**Comment by ChadKillingsworth** [comment]
Are you using a custom build or the Java API? I can't recreate this on the command line.

Math is part of the language externs and shouldn't be excludable. We also have a pass that declares it on window automatically.

**Comment by a701440** [comment]
Using embedded in a Java web app. Version closure-compiler-unshaded, v20161201.
With these options:

    protected CompilerOptions createOptions() {
        CompilerOptions options = new CompilerOptions();
        options.setCodingConvention(new ClosureCodingConvention());

        // Compilation optimization level
        CompilationLevel compileLevel = parseProperty(COMPILATION_LEVEL_PROPERTY, CompilationLevel.SIMPLE_OPTIMIZATIONS);
        compileLevel.setOptionsForCompilationLevel(options);

        // Source map detail level
        SourceMap.DetailLevel detailLevel = parseProperty(SOURCE_MAP_DETAIL_LEVEL_PROPERTY, SourceMap.DetailLevel.ALL);
        options.setSourceMapDetailLevel(detailLevel);

        // Source map format (only one format currently supported DEFAULT = V3)
        options.setSourceMapFormat(SourceMap.Format.DEFAULT);

        // Language in
        CompilerOptions.LanguageMode languageIn = parseProperty(LANGUAGE_IN_PROPERTY, CompilerOptions.LanguageMode.ECMASCRIPT3);
        options.setLanguageIn(languageIn);

        // Language out
        CompilerOptions.LanguageMode languageOut = parseProperty(LANGUAGE_OUT_PROPERTY, CompilerOptions.LanguageMode.ECMASCRIPT3);
        options.setLanguageOut(languageOut);

        // see: https://github.com/google/closure-compiler/issues/1875
        options.setProtectHiddenSideEffects(false);

        // allow trailing commas
        if (this.allowES3errors) {
            options.setWarningLevel(DiagnosticGroups.ES3, CheckLevel.WARNING);
        }

        options.setWarningLevel(DiagnosticGroups.EXTERNS_VALIDATION, CheckLevel.WARNING);

        return options;
    }

**Comment by ChadKillingsworth** [comment]
You MUST include the language extern set: https://github.com/google/closure-compiler/blob/cef519509411073f3955d6392428d40ef3d654b8/src/com/google/javascript/jscomp/AbstractCommandLineRunner.java#L439-L481
