### ISSUE TITLE
Update wiki with newest link for calling via API 

### ISSUE THREAD

**Issue by fxfactorial** [google/closure-compiler#2229]
http://hyegar.com/2017/01/09/calling-google-closure-and-with-jni/

**Comment by MatrixFrog** [comment]
I went ahead and added that link to https://github.com/google/closure-compiler/wiki/Using-the-Compiler's-Java-API

**Comment by fxfactorial** [comment]
Thanks

**Comment by Dominator008** [comment]
@fxfactorial Nit: Can you change the link to something like http://hyegar.com/2017/01/09/calling-google-closure-and-with-java-api/? "jni" means Java native interface and that's not accurate :)

**Comment by fxfactorial** [comment]
@Dominator008 Yea, I noticed that afterward. 

I'm working on an way to call this via the JNI so that I can call it to my ultimate goal, which is to call this via OCaml programmatically so I started the post off a bit more ambitiously lol. 

I'll try to change it later today, sorry about that.

**Comment by MatrixFrog** [comment]
The wiki is editable by anyone so if you change the URL of the blog post you can update it there too.

**Comment by fxfactorial** [comment]
Oh cool, I tried editing the wiki but didn't see the ability to, thought it was locked to only members of the repo.

**Comment by fxfactorial** [comment]
@Dominator008 @MatrixFrog Sorry, couldn't find a way to hit edit for that particular spot. 

I fixed the URL, also this should be updated too? https://github.com/google/closure-compiler/wiki/FAQ#how-do-i-call-closure-compiler-from-the-java-api

**Comment by jasonwee** [comment]
https://hyegar.com/2017/01/09/calling-google-closure-and-with-jni/ this link return 404, anyone know the fix?

**Comment by fxfactorial** [comment]
I will fix the post but you know you can use the wayback machine to get a cached copy.
