### ISSUE TITLE
NTI: parameters with unioned constructor and function lose constructor type.

### ISSUE THREAD

**Issue by WearyMonkey** [google/closure-compiler#2233]
```js
class Baa { }

/** @param {function(new: Baa) | function(number)} fn */
function foo(fn) { }

foo(Baa);
```

```
java -jar closure-compiler-v20161201.jar -O ADVANCED -W VERBOSE --js source.js --new_type_inf
source.js:8: WARNING - Invalid type for parameter 1 of function foo.
Expected : function(number):?
Found    : Baa<|function(new:Baa):undefined|>

foo(Baa);
    ^^^
```

However: 
` * @param {function(new: Baa)} fn` compiles with no warnings.

**Comment by dimvar** [comment]
In the body of `foo`, how do you expect `fn` to be used? With or without `new`? How can you meaningfully distinguish between the two functions in the union?

**Comment by WearyMonkey** [comment]
I could use a instanceof check:
`if (fn.prototype instanceof Baa) { ... } else { ... }`
Or I could check for the existence of a method on the prototype:
`if (fn.prototype.someMethodOnBaa)  { ... } else { ... }`

The use case is typing React's [createElement](https://facebook.github.io/react/docs/react-api.html#createelement) method, which can accept either a `React.Component` class, a `function` that returns a `React.Element` or a `string`.

e.g.:

```
  /**
   * @template Props
   * @template State
   * @param {function(new: React.Component<Props, State>, Props) | function(Props):!React.Element | string} component
   * @param {?Props} props
   * @param {...!React.Element|!Array<React.Element>|string} children
   * @return {!React.Element}
   */
  static createElement(component, props, children) {

  }
``` 

React differentiates between the two function types [here](https://github.com/facebook/react/blob/469e68542b0c12d3c3a8ffbed664bd87fb6eadcf/src/renderers/shared/stack/reconciler/instantiateReactComponent.js#L51).

**Comment by WearyMonkey** [comment]
@dimvar do you think a fix is possible? Or a work around? Cheers!

**Comment by dimvar** [comment]
It's low priority to improve this. A workaround is to use the type `Function`, which is quite loose and can be used both as a regular function and as a constructor.

**Comment by dimvar** [comment]
Note to self: the fix here should be to avoid the warning, not to do anything fancy with keeping more than one function in a union type.
