### ISSUE TITLE
[ES6] cannot extend default export

### ISSUE THREAD

**Issue by jleyba** [google/closure-compiler#2236]
```js
// one.js
export default class {}
export class A {}
```

```js
// two.js
import one from './one.js';
import {A} from './one.js';

export default class extends one {}
export class B extends A {}
```

Compiling under OTI:

```sh
$ java -jar closure-compiler-v20161201.jar --checks_only -W VERBOSE one.js two.js 
two.js: WARNING - Bad type annotation. Unknown type module$one.default

0 error(s), 1 warning(s), 96.3% typed
```

And under NTI:

```sh
$ java -jar closure-compiler-v20161201.jar --checks_only -W VERBOSE --new_type_inf one.js two.js
two.js:4: WARNING - $jscompDefaultExport$$module$two extends non-object type ?.

export default class extends one {}
               ^^^^^^^^^^^^^^^^^^^^

0 error(s), 1 warning(s), 98.8% typed
```

**Comment by ChadKillingsworth** [comment]
Can this be worked around by naming the classes?

**Comment by jleyba** [comment]
I actually found this while trying to update [js-dossier](https://github.com/jleyba/js-dossier) to the latest release of the compiler.

Explicitly naming classes will avoid this, but it's still a bug :)

**Comment by rconnamacher** [comment]
I'm encountering this bug too, and naming the _classes_ doesn't change it as long as they're still the default export. Using named _exports_ does work around the issue.

```js
// SuperClass.js
export default class SuperClass { }

//SubClass.js
import SuperClass from "./SuperClass.js";
export default class SubClass extends SuperClass { }
// Compiler Warning: Unknown type
```

```js
// SuperClass.js
export class SuperClass { }

//SubClass.js
import {SuperClass} from "./SuperClass.js";
export default class SubClass extends SuperClass { }
// No compiler warning
```

**Comment by rconnamacher** [comment]
This may or may not be related, but the compiler also produces the same unknown type warnings for type annotations using default-export constants.

```js
// DirectionType.js
/** @enum {number} */
export default {
    NORTH: 1,
    SOUTH: 2,
};

// Another file
import DirectionType from "./DirectionType.js";

/** @param {DirectionType} direction */
function computeDirection(direction) { }
// Compiler Warning: Unknown type
```

```js
// DirectionType.js
/** @enum {number} */
export const DirectionType = {
    NORTH: 1,
    SOUTH: 2,
};

// Another file
import {DirectionType} from "./DirectionType.js";

/** @param {DirectionType} direction */
function computeDirection(direction) { }
// No compiler warning
```

**Comment by ChadKillingsworth** [comment]
If I recall correctly, it works this way:

```js
class Foo {}
export default Foo;
```

**Comment by lauraharker** [comment]
This is fixed now:
https://closure-compiler-debugger.appspot.com/#input0%3D%252F%252F%2520one.js%250Aexport%2520default%2520class%2520%257B%257D%250Aexport%2520class%2520A%2520%257B%257D%26input1%3Dimport%2520one%2520from%2520'.%252Finput0'%253B%250Aimport%2520%257BA%257D%2520from%2520'.%252Finput0'%253B%250A%250Aexport%2520default%2520class%2520extends%2520one%2520%257B%257D%250Aexport%2520class%2520B%2520extends%2520A%2520%257B%257D%26conformanceConfig%26externs%26refasterjs-template%26CHECK_TYPES%3Dtrue%26CLOSURE_PASS%3Dtrue%26PRESERVE_TYPE_ANNOTATIONS%3Dtrue%26PRETTY_PRINT%3Dtrue
