### ISSUE TITLE
[ES6] Cannot reference imported type by local alias in type annotations

### ISSUE THREAD

**Issue by jleyba** [google/closure-compiler#2237]
```js
// a.js
export class A {}
```

```js
// b.js
import {A as B} from './a';

/** @return {!B} */
export function newB() { return new B; }
```

```sh
$ java -jar closure-compiler-v20161201.jar  --checks_only -W VERBOSE --new_type_inf a.js b.js
b.js:3: WARNING - Type annotation references non-existent type B$$module$a.
/** @return {!B} */
              ^

0 error(s), 1 warning(s), 100.0% typed
```

**Comment by l1bbcsg** [comment]
> 5ae3a8 may address this.

Can you elaborate? I think you're referencing an internal or otherwise hidden commit.

**Comment by jplaisted** [comment]
I think @concavelenz was expecting to copy a shorted hash and have github link it. Instead you need to paste a full hash and github will shorten it (like so: 5bec1109cf1991446e1d4d9857b0ab41ba320ee4).

Anyway, this is now fixed! Sorry it took so long, and thank you for bumping the issue.
