### ISSUE TITLE
Dynamically getting properties from typedef

### ISSUE THREAD

**Issue by KamranAsif** [google/closure-compiler#2241]
We are using a large amount of typedefs and grabbing objects on the tree using lodash.get

Is there a way to preserve the type checking in this scenario? 
I tried using typing similar to goog.object.get but that doesn't work. 

Surprisingly, obj[foo] also loses the path, and only obj.foo seems to work:  [demo](https://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%2540compilation_level%2520ADVANCED_OPTIMIZATIONS%250A%252F%252F%2520%2540formatting%2520print_input_delimiter%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250A%252F**%250A%2520*%2520%2540typedef%2520%257B%257Bfoo%253A%2520!Array.%253Cnumber%253E%252C%2520bar%253A%2520boolean%257D%257D%250A%2520*%252F%250Avar%2520objType%253B%250A%250A%252F**%250A%2520*%2520%2540type%2520%257BobjType%257D%250A%2520*%252F%250Avar%2520obj%2520%253D%2520%257B'foo'%253A%2520%255B1%255D%252C%2520'bar'%253A%2520false%257D%253B%250A%250A%250A%252F**%2520%2540type%2520%257Bnumber%257D%2520*%252F%250Avar%2520a%2520%253D%2520goog.object.get(obj%252C%2520'bar')%253B%250A%250A%252F**%2520%2540type%2520%257Bnumber%257D%2520*%252F%250Avar%2520b%2520%253D%2520obj%255B'bar'%255D%253B%250A%250A%252F**%2520%2540type%2520%257Bnumber%257D%2520*%252F%250Avar%2520c%2520%253D%2520obj.bar%253B)

I could live with something like get(obj, enum) => typedef but I'm not sure thats possible. 
Would appreciate any guidance on this issue

**Comment by dimvar** [comment]
For a property `foo`, the typechecker only checks accesses to `foo` using dot; bracket accesses are not typechecked.

The only bracket accesses that are checked are for "index-like" properties. For example, when you do `obj[expression]` and `obj` is an array, the type of `expression` must be number. When `obj` has type `IObject<Foo, Bar>`, the type of `expression` must be `Foo`.
