### ISSUE TITLE
NTI: Cannot override diamond-inherited interface methods in generic classes

### ISSUE THREAD

**Issue by shicks** [google/closure-compiler#2242]
[repro](https://closure-compiler-debugger.appspot.com/#input0%3D%252F**%2520%2540interface%2520%2540template%2520T%2520*%252F%250Aclass%2520Foo%2520%257B%250A%2520%2520%252F**%2520%2540return%2520%257BT%257D%2520*%252F%2520foo()%2520%257B%257D%250A%257D%250A%250A%252F**%2520%2540interface%2520%2540extends%2520%257BFoo%253CT%253E%257D%2520%2540template%2520T%2520*%252F%250Aclass%2520MutableFoo%2520%257B%250A%2520%2520%252F**%2520%2540param%2520%257BT%257D%2520foo%2520*%252F%2520set(foo)%2520%257B%257D%250A%257D%250A%250A%252F**%2520%2540abstract%2520%2540implements%2520%257BFoo%253CT%253E%257D%2520%2540template%2520T%2520*%252F%250Aclass%2520AbstractFoo%2520%257B%250A%2520%2520%252F**%2520%2540abstract%2520%2540return%2520%257BT%257D%2520*%252F%250A%2520%2520getFoo()%2520%257B%257D%250A%2520%2520%252F**%2520%2540override%2520*%252F%250A%2520%2520foo()%2520%257B%2520return%2520this.getFoo()%253B%2520%257D%250A%257D%250A%250A%252F**%2520%2540implements%2520%257BMutableFoo%253CT%253E%257D%2520%2540extends%2520%257BAbstractFoo%253CT%253E%257D%2520%2540template%2520T%2520*%252F%250Aclass%2520RealFoo%2520%257B%250A%2520%2520%252F**%2520%2540param%2520%257BT%257D%2520foo%2520*%252F%250A%2520%2520constructor(foo)%2520%257B%2520this.foo_%2520%253D%2520foo%253B%2520%257D%250A%2520%2520%252F**%2520%2540override%2520*%252F%250A%2520%2520getFoo()%2520%257B%2520return%2520this.foo_%253B%2520%257D%250A%2520%2520%252F**%2520%2540override%2520*%252F%250A%2520%2520foo()%2520%257B%2520return%2520this.foo_%253B%2520%257D%250A%2520%2520%252F**%2520%2540override%2520*%252F%250A%2520%2520set(foo)%2520%257B%2520this.foo_%2520%253D%2520foo%253B%2520%257D%250A%257D%250A%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES%3D1%26CHECK_TYPES_NEW_INFERENCE%3D1%26CLOSURE_PASS%3D1%26MISSING_PROPERTIES%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1%26TRANSPILE%3D1)

Basic premise is the following:
```java
interface BaseInterface<T> {
  method() {}
}
class BaseClass<T> implements BaseInterface<T> {
  /** @override */ method() { ... }
}
interface SubInterface<T> extends BaseInterface<T> {}
class SubClass<T> extends BaseClass<T> implements SubInterface<T> {
  /** @override */ method() { ... }
}
```

Here we have a diamond-inheritance situation where `SubClass` is getting `method` from both `SubInterface` and `BaseClass` - though they both ultimately come from `BaseInterface`, and NTI doesn't understand that this method has the same type - somehow the template types are getting confused.

**Comment by dimvar** [comment]
This is fixed.
