### ISSUE TITLE
Async arrow functions w/o parens give a parse error

### ISSUE THREAD

**Issue by alur** [google/closure-compiler#2244]
```js
async x => await Promise.resolve(x);
```
```
JSC_PARSE_ERROR: Parse error. Semi-colon expected at line 3 character 6
```
https://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540compilation_level%2520SIMPLE_OPTIMIZATIONS%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250A%252F%252F%2520ADD%2520YOUR%2520CODE%2520HERE%250A%250Aasync%2520x%2520%253D%253E%2520await%2520Promise.resolve(x)%253B

**Comment by brad4d** [comment]
A slightly better repro.

https://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540compilation_level%2520SIMPLE_OPTIMIZATIONS%250A%252F%252F%2520%2540language%2520ECMASCRIPT_NEXT%250A%252F%252F%2520%2540language_out%2520ECMASCRIPT5%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250A%252F%252F%2520Parse%2520error%2520if%2520you%2520substitute%2520'async%2520x'%2520for%2520'async%2520(x)'%250Avar%2520a%2520%253D%2520async%2520(x)%2520%253D%253E%2520await%2520Promise.resolve(x)%253B

The problem appears to be that Parser.parseAssignment() immediately calls parseConditional() which is not consistent with the spec.

**Comment by brad4d** [comment]
FYI, I have a draft change for this in review.
