### ISSUE TITLE
Typdef; Found undefined, required object

### ISSUE THREAD

**Issue by adam-rocska** [google/closure-compiler#2252]
## Version Info

```
Closure Compiler (http://github.com/google/closure-compiler)
Version: v20161201
Built on: 2016-12-02 14:56
```

## Command line arguments

```
  --compilation_level ADVANCED ./ --language_in ECMASCRIPT5_STRICT
```

## Source Code

```
goog.provide('Gram.Injectable.Entity');

/**
 * @summary  Represents an injectable entity.
 * @typedef  {(Object|Function)} Entity
 * @name     Entity
 * @memberof Gram.Injectable
 */
Gram.Injectable.Entity;
```

## Expected behavior

Recognize `Gram.Injectable.Entity` as a defined type which can either be an `Object` or a `Function`.

## Actual behavior

```
./Gram/Injectable/Entity.js:8: WARNING - No properties on this expression
found   : undefined
required: Object
Gram.Injectable.Entity;
^^^^^^^^^^^^^^^
```

**Comment by Dominator008** [comment]
Is `Gram.Injectable` defined anywhere in your code or externs?

**Comment by adam-rocska** [comment]
@Dominator008 Yes. Part of the code follows:

```
goog.provide('Gram.Injectable');
goog.require('Gram.Injectable.Exception.NotFound');
goog.require('Gram.Injectable.Exception.Collision');

/**
 * @class
 * @constructor
 * @memberof    Gram
 * @classdesc   — Content removed since it's insiginificant
 * @description — Content removed since it's insiginificant
 */
Gram.Injectable = function () {
};

```

**Comment by Dominator008** [comment]
Did you require `Gram.Injectable` in Entity.js?

**Comment by adam-rocska** [comment]
@Dominator008 No, since by my understanding goog.provide is expected to take care of it. Please correct me if I'm wrong and if possible point me to a documentation of the goog.provide/goog.require API.

My interpretation is, that the error message
```
./Gram/Injectable/Entity.js:8: WARNING - No properties on this expression
found   : undefined
required: Object
Gram.Injectable.Entity;
^^^^^^^^^^^^^^^
```

is about expecting `Gram.Injectable.Entity;` to be of object type, while it is an undefined. However based on [this documentation](https://github.com/google/closure-compiler/wiki/Annotating-JavaScript-for-the-Closure-Compiler#typedef-type) it seems like this is the way to go.

**Comment by Dominator008** [comment]
@adam-rocska I can't seem to reproduce this:
https://closure-compiler-debugger.appspot.com/#input0%3Dgoog.provide('Gram.Injectable')%253B%250A%250A%252F**%250A%2520*%2520%2540class%250A%2520*%2520%2540constructor%250A%2520*%2520%2540memberof%2520%2520%2520%2520Gram%250A%2520*%2520%2540classdesc%2520%2520%2520%25E2%2580%2594%2520Content%2520removed%2520since%2520it's%2520insiginificant%250A%2520*%2520%2540description%2520%25E2%2580%2594%2520Content%2520removed%2520since%2520it's%2520insiginificant%250A%2520*%252F%250AGram.Injectable%2520%253D%2520function%2520()%2520%257B%250A%257D%253B%250A%26input1%3Dgoog.provide('Gram.Injectable.Entity')%253B%250A%250A%252F**%250A%2520*%2520%2540summary%2520%2520Represents%2520an%2520injectable%2520entity.%250A%2520*%2520%2540typedef%2520%2520%257B(Object%257CFunction)%257D%2520Entity%250A%2520*%2520%2540name%2520%2520%2520%2520%2520Entity%250A%2520*%2520%2540memberof%2520Gram.Injectable%250A%2520*%252F%250AGram.Injectable.Entity%253B%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26MISSING_PROPERTIES%3D1%26TRANSPILE%3D1%26CHECK_TYPES%3D1%26CLOSURE_PASS%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1

**Comment by adam-rocska** [comment]
@Dominator008 I'll do my best to put together a sharable codebase this weekend and push it to github to share. Still facing the same issue :(
