### ISSUE TITLE
Object.keys on object with string keys and typed values

### ISSUE THREAD

**Issue by adam-rocska** [google/closure-compiler#2253]
## Version Info

```
Closure Compiler (http://github.com/google/closure-compiler)
Version: v20161201
Built on: 2016-12-02 14:56
```

## Command line arguments

```
  --compilation_level ADVANCED ./ --language_in ECMASCRIPT5_STRICT
```

### Gram.Injectable.Entity
```
goog.provide('Gram.Injectable.Entity');

/**
 * @summary  Represents an injectable entity.
 * @typedef  {(Object|Function)} Entity
 * @name     Entity
 * @memberof Gram.Injectable
 */
Gram.Injectable.Entity;
```

### Gram.Injectable.Pool
```
goog.provide('Gram.Injectable.Pool');

/**
 * @summary  Represents a pool of injectable entities.
 * @typedef  {Object.<string, Gram.Injectable.Entity>} Pool
 * @name     Pool
 * @memberof Gram.Injectable
 */
Gram.Injectable.Pool;
```

### Code where failure experienced

```
// ... method body
Object
		.keys(injectablePool)
		.forEach(function (injectableKey) {
			delete injectablePool[injectableKey];
		});
// ... method body
```

#### Where

| Value | Is of type |
|------|------|
|injectablePool|Gram.Injectable.Pool|

## Expected behavior

Recognize `Gram.Injectable.Pool` as an `Object` with `string` keys and `Gram.Injectable.Entity` values, where since `Object.keys` accepts a value of `Object` type by its signature, it should be passable to `Object.keys`

Assumption is based on http://usejsdoc.org/tags-type.html primarily but not exclusively.

## Actual behavior

```
./Gram/Injectable.js:134: WARNING - actual parameter 1 of Object.keys does not match formal parameter
found   : (Object<string,(Object|null)>|null)
required: Object
		.keys(injectablePool)
		      ^^^^^^^^^^^^^^
```

**Comment by adam-rocska** [comment]
A "workaround" is to use https://github.com/google/closure-compiler/wiki/Annotating-JavaScript-for-the-Closure-Compiler#nullable-type .

**Comment by MatrixFrog** [comment]
To the Closure Compiler, `@typedef  {Object.<string, Gram.Injectable.Entity>}` means a nullable object. Just adding a `!` should fix this I believe.

**Comment by adam-rocska** [comment]
@MatrixFrog Thank you very much for your help. Is there any way to configure the compiler to handle by default any type as "Non-nullable type" ? 
— sorry for asking here, I didn't manage to find a live forum around closure compiler yet

**Comment by MatrixFrog** [comment]
No. We really don't want to be in a state where the same type annotation has two different meanings depending on your compiler flags. Of course we have lots of flags that turn warnings on or off, but that's different from actually changing what the type annotation means. Forum is at https://groups.google.com/forum/#!forum/closure-compiler-discuss by the way.
