### ISSUE TITLE
Wrong type for lambda used in addEventListener?

### ISSUE THREAD

**Issue by applmak** [google/closure-compiler#2255]
What's the right code that assigns a lambda to a variable on an object that can be passed to addEventListener? 
The example:

```js
class Test {
  constructor() {
    /** @private @const */
    this.thing_ = 5;
    this.handler_ = e => {
      console.log(this.thing_);
    };
  }
  /** starts */
  start() {
    document.addEventListener('mousemove', this.handler_);
  }
  /** stops */
  stop() {
    document.removeEventListener('mousemove', this.handler_);
  }
}

let t = new Test;
t.start();
t.stop();
```

Doesn't work because `this.handler_`'s type cannot be deduced. If I add a type, say:

`/** @private @const {function(this:Test, !Event)} */`

I'm no longer allowed to pass it to addEventListener, because the handlers aren't allowed to have defined 'this'. Of course, this works fine uncompiled, it's only the type system that is wrong.

Any hints as to how to teach the compiler to do this?

**Comment by MatrixFrog** [comment]
It looks like your example works with the old typechecker but not the new one.

https://closure-compiler-debugger.appspot.com/#input0%3Dclass%2520Test%2520%257B%250A%2520%2520constructor()%2520%257B%250A%2520%2520%2520%2520%252F**%2520%2540private%2520%2540const%2520*%252F%250A%2520%2520%2520%2520this.thing_%2520%253D%25205%253B%250A%2520%2520%2520%2520this.handler_%2520%253D%2520e%2520%253D%253E%2520%257B%250A%2520%2520%2520%2520%2520%2520console.log(this.thing_)%253B%250A%2520%2520%2520%2520%257D%253B%250A%2520%2520%257D%250A%2520%2520%252F**%2520starts%2520*%252F%250A%2520%2520start()%2520%257B%250A%2520%2520%2520%2520document.addEventListener('mousemove'%252C%2520this.handler_)%253B%250A%2520%2520%257D%250A%2520%2520%252F**%2520stops%2520*%252F%250A%2520%2520stop()%2520%257B%250A%2520%2520%2520%2520document.removeEventListener('mousemove'%252C%2520this.handler_)%253B%250A%2520%2520%257D%250A%257D%250A%250Alet%2520t%2520%253D%2520new%2520Test%253B%250At.start()%253B%250At.stop()%253B%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES%3D1%26CHECK_TYPES_NEW_INFERENCE%3D1%26CLOSURE_PASS%3D1%26MISSING_PROPERTIES%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1%26TRANSPILE%3D1

So @dimvar may have a suggestion here.

**Comment by dimvar** [comment]
The warning, as you noticed, is that handlers shouldn't define `this`. Basically, a method should not be called as a function, only as a method. So, the solution in this case is to use the type annotation, but use a function type, not a method type.

https://closure-compiler-debugger.appspot.com/#input0%3Dclass%2520Test%2520%257B%250A%2520%2520constructor()%2520%257B%250A%2520%2520%2520%2520%252F**%2520%2540private%2520%2540const%2520*%252F%250A%2520%2520%2520%2520this.thing_%2520%253D%25205%253B%250A%2520%2520%2520%2520%252F**%2520%2540private%2520%2540const%2520%257Bfunction(!Event)%257D%2520*%252F%250A%2520%2520%2520%2520this.handler_%2520%253D%2520e%2520%253D%253E%2520%257B%250A%2520%2520%2520%2520%2520%2520console.log(this.thing_)%253B%250A%2520%2520%2520%2520%257D%253B%250A%2520%2520%257D%250A%2520%2520%252F**%2520starts%2520*%252F%250A%2520%2520start()%2520%257B%250A%2520%2520%2520%2520document.addEventListener('mousemove'%252C%2520this.handler_)%253B%250A%2520%2520%257D%250A%2520%2520%252F**%2520stops%2520*%252F%250A%2520%2520stop()%2520%257B%250A%2520%2520%2520%2520document.removeEventListener('mousemove'%252C%2520this.handler_)%253B%250A%2520%2520%257D%250A%257D%250A%250Alet%2520t%2520%253D%2520new%2520Test%253B%250At.start()%253B%250At.stop()%253B%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES%3D1%26CHECK_TYPES_NEW_INFERENCE%3D1%26CLOSURE_PASS%3D1%26MISSING_PROPERTIES%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1%26TRANSPILE%3D1

Some improvements for the new type inference:
- we should actually warn when annotating a method that uses `this` in the body with a function type
- when a method does not use `this`, we should infer a function type for it so it can be called as a function as well

**Comment by applmak** [comment]
When I omit the explicit 'this' in type of the handler (`function(this:Test, !Event)`), I end up with unknown type errors on this.thing. When I add it, I can't use it with addEventListener.

**Comment by dimvar** [comment]
In the example I posted there are no warnings. Can you post another example which shows the warnings you are seeing if you omit `this`, so I can suggest a workaround?

**Comment by applmak** [comment]
I think it only happens if you enable reportUnknownTypes.
