### ISSUE TITLE
Cannot use spread operator to call abstract template methods

### ISSUE THREAD

**Issue by shicks** [google/closure-compiler#2262]
[Example](https://closure-compiler-debugger.appspot.com/#input0%3D%252F**%2520%2540abstract%2520*%252F%250Aclass%2520Base%2520%257B%250A%250A%2520%2520%252F**%2520%2540abstract%2520*%252F%250A%2520%2520foo()%2520%257B%257D%250A%250A%2520%2520%252F**%2520%2540param%2520%257B!Array%257D%2520arr%2520*%252F%250A%2520%2520bar(arr)%2520%257B%2520this.foo(...arr)%253B%2520%257D%250A%257D%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26MISSING_PROPERTIES%3D1%26TRANSPILE%3D1%26CHECK_TYPES%3D1%26CLOSURE_PASS%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1):
```js
/** @abstract */
class Base {

  /** @abstract */
  foo() {}

  /** @param {!Array} arr */
  bar(arr) { this.foo(...arr); }
}
```

Error:
```
WARNING - Abstract method Base.prototype.foo cannot be called
  bar(arr) { this.foo(...arr); }
             ^^^^^^^^^^^^^^^^
```

It seems that this check is designed to prevent `super.foo()`, which transpiles to `Base.superClass_.foo.call(this)`.  The spread operator transpiles to `this.foo.apply(this, [].concat(args))` and it looks like the check is being over-eager here.

**Comment by Dominator008** [comment]
I have fixed this for OTI internally.

**Comment by Dominator008** [comment]
Actually, NTI doesn't have the problem so I'm re-closing this.
