### ISSUE TITLE
bug with namespaces in externs file

### ISSUE THREAD

**Issue by ikabirov** [google/closure-compiler#2266]
When using externs file with namespaces, e.g. externs for google maps compiler adds property maps to Object.prototype
```
/**
 * @const
 * @suppress {const|duplicate}
 */
var google = {};

/** @const */
google.maps = {};
```
```
const obj = {};
obj.maps(); // ignore
obj.foo();    // warning
```

**Comment by dimvar** [comment]
This is expected. Property existence checks are unfortunately very loose. Note that in this case, you are accessing maps on Object but its type is unknown, it is not the namespace type.

**Comment by dimvar** [comment]
I recommend trying the new type inference if you want better checking. https://github.com/google/closure-compiler/wiki/Using-NTI-(new-type-inference)
