### ISSUE TITLE
Using spread operator may generate non-ES5 compatible code

### ISSUE THREAD

**Issue by sindilevich** [google/closure-compiler#2267]
Transpiling ECMAScript 2015 code that uses the _spread operator_, to ES5, using the `--language_out=ES5` flag leads to a non-ES5 compatible code being generated.

This [example](http://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540compilation_level%2520SIMPLE_OPTIMIZATIONS%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%2540formatting%2520pretty_print%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250A%252F%252F%2520ADD%2520YOUR%2520CODE%2520HERE%250Afunction%2520testSpreadOperator()%2520%257B%250A%2520%2520var%2520arr1%2520%253D%2520%255B1%252C%25202%252C%25203%255D%253B%250A%2520%2520var%2520arr2%2520%253D%2520%255B...arr1%255D%253B%250A%257D%250AtestSpreadOperator()%253B%250A%250A) shows a simple script which uses the spread operator. The output contains an automatically added polyfill for `Object.defineProperty`, which throws an exception when the third parameter, a descriptor, has either `get` or `set` property defined.

This exception is invalid in ES5 context. Probably, the Google Closure Compiler should provide different implementations for the above polyfill, according to the `--language_out` parameter.

**Comment by Dominator008** [comment]
@shicks Looks like this part:
https://github.com/google/closure-compiler/blob/20e8f03d4c9b67ca6654e049c74e0b4d978ab012/src/com/google/javascript/jscomp/js/util/defineproperty.js#L42
needs to be conditional?

**Comment by shicks** [comment]
It is conditional on the existence of `Object.defineProperties`, which should be defined in all ES5 browsers.  So it's just a case of useless code when you know you're compiling to ES5; it's not actually incorrect.  We could certainly be smarter about what code we inject, but currently there's no mechanism at all to inject different code based on language out.

Additionally, `$jscomp.defineProperty` is *not* actually stored back to `Object.defineProperty`, and we never call it directly with anything that has a getter or setter.  So this codepath is actually completely dead anyway, and might as well be deleted - we'll save 30 or so bytes from most binaries as a result.

**Comment by sindilevich** [comment]
Hello @shicks,

You've closed the issue, but there is no commit associated with it that removes the dead codepath, as you've suggested. However, currently, the presence of `throw new TypeError('ES3 does not support getters and setters.');` will cause issues when Google Closure Compiler is used in the Dojo build ecosystem.

Can you please resolve the issue by either conditionally change the polyfill's contents according to the `--language_out` parameter, or remove the dead codepath for good.

Many thanks!

**Comment by ChadKillingsworth** [comment]
@sindilevich This was closed because your original case is not reproducible. This should only throw on browsers which do not have `Object.defineProperties`. If you can provide an environment in which this creates an error, we can re-open.
