### ISSUE TITLE
String.substr() improperly replaced with String.charAt()

### ISSUE THREAD

**Issue by Ondross** [google/closure-compiler#2268]
Hi. Somewhere, (I assume in `PeepholeReplaceKnownMethods.java`), String.substr() is replaced with String.charAt().

I think you missed an exception where this should be left as substr(). It seems `string.substr(-n)` (for positive n)  behaves like `string.substr(string.length - n)`, where `string.charAt()` returns an empty string for any negative argument.

Thanks!

**Comment by Dominator008** [comment]
I believe we don't replace it with `charAt()` if there's only one argument to `substr()`:
https://github.com/google/closure-compiler/blob/42b5447485da83a7730c2f0739bb7d8415a0f48b/test/com/google/javascript/jscomp/PeepholeReplaceKnownMethodsTest.java#L360
Is this replacement happening in your compilation?

**Comment by Ondross** [comment]
Ah, you're right, and my example is bad, sorry!

If we add a second argument, `string.substr(-5, 1)`, it does seem to use `charAt()`. Removing the second argument leaves it at `substr()`, but changes the behavior of `substr()`.

Note that this is not a problem for me. I changed my code to use `length - n`. Only trying to help :-)

**Comment by Dominator008** [comment]
@Ondross Hmm. Apparently I read the specs wrong or something. I'll fix this. Thanks for the report!
