### ISSUE TITLE
How to docs static class type?

### ISSUE THREAD

**Issue by tenorok** [google/closure-compiler#2269]
Hello!
Please, prompt me, how I should specify type for variable with static class declaration?

For example:
```js
/**
 * @constructor
 */
function My() {}
My.foo = function() { return ''; };

/**
 * @type {{staticMy: function(new:My)}}
 */
var d = { staticMy: My };

d.staticMy.foo();
```

Check of code above will throw an error:
```
WARNING - Property foo never defined on d.staticMy
d.staticMy.foo();
           ^^^
```

**Comment by Dominator008** [comment]
Not sure what you meant by "static class declaration". Should the last line be the following?
```js
(new d.staticMy()).foo();
```

**Comment by tenorok** [comment]
@Dominator008 no, presented code snippet is fully correct.
In your case the interpreter will throw an error, because function `foo()` is not in the prototype:
```
Uncaught TypeError: (intermediate value).foo is not a function(…)
```

I mean analogue of [`typeof`](https://flowtype.org/docs/typeof.html#another-example) or [`Class<T>`](https://flowtype.org/docs/classes.html#classt-type) from the [flow](https://flowtype.org/).

How describe this type:
```
/** @type {{ staticMy: ??? }} */
```

**Comment by Dominator008** [comment]
Oh I see. Unfortunately we don't have a way to express "function / constructor with property" in the type system. It's on the roadmap though. We have an internal proposal for it (https://github.com/google/closure-compiler/issues/946#issuecomment-102449359).

**Comment by dimvar** [comment]
Closing this since "functions in properties" are tracked elsewhere.
