### ISSUE TITLE
"Expected a constructor but found type function" when attempting to create instance of structural interface (NTI)

### ISSUE THREAD

**Issue by ghosttie** [google/closure-compiler#2270]
In the Google Maps API externs file there is structural interface defined like this:

    /**
     * @record
     */
    google.maps.places.AutocompleteOptions = function() {};

if I try to create an instance of it like this:

    var options = new google.maps.places.AutocompleteOptions();

I get this compiler warning:

    input0:1: WARNING - Expected a constructor but found type function(new:google.maps.places.AutocompleteOptions):?.
    var options = new google.maps.places.AutocompleteOptions();
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    
    0 error(s), 1 warning(s), 75.0% typed

[Here](https://closure-compiler-debugger.appspot.com/#input0%3Dvar%2520options%2520%253D%2520new%2520google.maps.places.AutocompleteOptions()%253B%26input1%26conformanceConfig%26externs%3D%252F**%250A%2520*%2520%2540const%250A%2520*%2520%2540suppress%2520%257Bconst%257Cduplicate%257D%250A%2520*%252F%250Avar%2520google%2520%253D%2520%257B%257D%253B%250A%250A%252F**%2520%2540const%2520*%252F%250Agoogle.maps%2520%253D%2520%257B%257D%253B%250A%250A%252F**%2520%2540const%2520*%252F%250Agoogle.maps.places%2520%253D%2520%257B%257D%253B%250A%250A%252F**%250A%2520*%2520%2540record%250A%2520*%252F%250Agoogle.maps.places.AutocompleteOptions%2520%253D%2520function()%2520%257B%257D%253B%250A%250A%252F**%250A%2520*%2520%2540type%2520%257BArray%253Cstring%253E%257Cundefined%257D%250A%2520*%252F%250Agoogle.maps.places.AutocompleteOptions.prototype.types%253B%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26MISSING_PROPERTIES%3D1%26TRANSPILE%3D1%26CHECK_TYPES%3D1%26CHECK_TYPES_NEW_INFERENCE%3D1%26CLOSURE_PASS%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1)'s a reproducer.

If instead I try to use a record type like this:

    var /** google.maps.places.AutocompleteOptions */ options = {types: ['geocode']};

I get this error:

    filevision/ui/field/TextField.js:451: ERROR - The right side in the assignment is not a subtype of the left side.
    Expected : google.maps.places.AutocompleteOptions|null
    Found    : {types:Array<string>}
    
    			    var /** google.maps.places.AutocompleteOptions */ options = {types: ['geocode']};
    			                                                                ^^^^^^^^^^^^^^^^^^^^

but I can't reproduce it using the JSCompiler Debugger

**Comment by dimvar** [comment]
You can only use `new` when calling a constructor. Using object literals as records is correct. The object literal must have all the required properties of the record type. In this case, it must have a `bounds` property of type `google.maps.LatLngBounds|google.maps.LatLngBoundsLiteral`. All others are optional as far as I can tell.
