### ISSUE TITLE
missing webkitFullscreenEnabled property in the externs/browser/html5.js file

### ISSUE THREAD

**Issue by nederland074** [google/closure-compiler#2274]

**Comment by ChadKillingsworth** [comment]
You are welcome to submit a PR for this.

**Comment by nederland074** [comment]
thanks, done it: https://github.com/google/closure-compiler/pull/2276

**Comment by realityforge** [comment]
@brad4d This can be closed as the PR was submitted and merged

**Comment by brad4d** [comment]
@realityforge thanks
