### ISSUE TITLE
Cannot assign function(this:X) to type function() [NTI]

### ISSUE THREAD

**Issue by supersteves** [google/closure-compiler#2278]
I would have thought that a function with unspecified 'this' is a supertype of a function with specified 'this' - not sure if my terminology is right but that I should be able to assign the latter to the former:
``` javascript
/**
 * @typedef {function(boolean)}
 */
let TypeDef;

class C {
  
  constructor() {

    /** @param {boolean} b */
    this.f = b => {};

  }

  test() {
    let /** TypeDef */ a = this.f;
  }

}
```
Warning:
```
input0:16: WARNING - The right side in the assignment is not a subtype of the left side.
Expected : function(boolean):?
Found    : function(this:C,boolean):?

    let /** TypeDef */ a = this.f;
                           ^^^^^^
```

[Debugger](https://closure-compiler-debugger.appspot.com/#input0%3D%252F**%250A%2520*%2520%2540typedef%2520%257Bfunction(boolean)%257D%250A%2520*%252F%250Alet%2520TypeDef%253B%250A%250Aclass%2520C%2520%257B%250A%2520%2520%250A%2520%2520constructor()%2520%257B%250A%250A%2520%2520%2520%2520%252F**%2520%2540param%2520%257Bboolean%257D%2520b%2520*%252F%250A%2520%2520%2520%2520this.f%2520%253D%2520b%2520%253D%253E%2520%257B%257D%253B%250A%250A%2520%2520%257D%250A%250A%2520%2520test()%2520%257B%250A%2520%2520%2520%2520let%2520%252F**%2520TypeDef%2520*%252F%2520a%2520%253D%2520this.f%253B%250A%2520%2520%257D%250A%250A%257D%250A%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26MISSING_PROPERTIES%3D1%26TRANSPILE%3D1%26CHECK_TYPES%3D1%26CHECK_TYPES_NEW_INFERENCE%3D1%26CLOSURE_PASS%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1)

Apologies if this is correct behaviour. I don't see any errors in OTI, though.

In the above example, TypeDef is an example of something in my externs. I can workaround it by editing the externs to read:
``` javascript
/**
 * @typedef {function(this:?,boolean)}
 */
let TypeDef;
```

**Comment by dimvar** [comment]
This is the correct behavior. Once a value has a function type, then you can call it without any receiver object, in your case, you can say `a(true)`. But then you end up calling a method where `this` is bound to the global object or undefined.

There is another improvement that can be made in NTI, where if a method doesn't use `this`, then we can give it a function type instead.

**Comment by supersteves** [comment]
Understood, thanks.
