### ISSUE TITLE
Allow destructuring assignment

### ISSUE THREAD

**Issue by blickly** [google/closure-compiler#228]
This issue was imported from Closure Compiler's previous home at http://closure-compiler.googlecode.com

The original discussion is archived at:
http://blickly.github.io/closure-compiler-issues/#1077

**Comment by Dominator008** [comment]
The given code:
```js
var [a] = [5];
```
is fully supported:

http://closure-compiler-debugger.appspot.com/#input0%3Dvar%2520%255Ba%255D%2520%253D%2520%255B5%255D%253B%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES%3D1%26LANG_IN_IS_ES6%3D1%26MISSING_PROPERTIES%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1%26TRANSPILE%3D1

Closing.
