### ISSUE TITLE
Add a flag to specify the polymer version

### ISSUE THREAD

**Issue by ChadKillingsworth** [google/closure-compiler#2288]
From discussion: https://github.com/google/closure-compiler/pull/2277#discussion_r99972133

Add a `--polymer_pass_version=X` flag so that the Polymer pass can have different behaviors between Polymer 1.x and 2.x. Since both the `Polymer({})` style and `class FooElement extends Polymer.Element {}` will potentially be supported in both versions, the compiler cannot infer this on it's own.

The 1.x version disables renaming (using synthetic externs) of any declared property. 2.x is going to follow the ALL_UNQUOTED property renaming policy.

How are behaviors handled? Currently behaviors are supported only by the `Polymer({})` style call for hybrid elements when using the 2.x version of Polymer.

* Should behaviors be supported by any potential class syntax that might be added to Polymer 1?
* Are Polymer 2 elements using the class style declaration ever going to support behaviors (I'm really hoping this answer is "no")?

**Comment by MatrixFrog** [comment]
`--polymer_pass_version` sounds weird to me. There's only one version of the _pass_ but it runs in two different modes depending on the version of Polymer. So `--polymer_version` feels more natural to me.

**Comment by ChadKillingsworth** [comment]
For the same reasons, `--polymer_version` is weird to me. Namely because `--polymer_version=0` would be how you turn off the pass?

In args4j, I think I can write a custom handler so that `--polymer_pass` is equivalent to `--polymer_pass=V1`. Is that an option for the internal runner?

**Comment by MatrixFrog** [comment]
I set the type of the flag to a nullable `Integer`, so to turn it off, you just don't pass the flag at all and `CompilerOptions.polymerVersion` being null tells the `DefaultPassConfig` to skip the pass.

Rather than a custom handler, I just did:

```
    if (flags.polymerPass) {
      options.polymerVersion = 1;
    } else {
      options.polymerVersion = flags.polymerVersion;
    }
```

and likewise for the internal command line runner.

**Comment by MatrixFrog** [comment]
(Or maybe `Optional<Integer>` is a better choice here.)

**Comment by justinfagnani** [comment]
@ChadKillingsworth regarding behaviors: we're making a function to convert them to mixins.
