### ISSUE TITLE
goog.global is strict_mode incompatible

### ISSUE THREAD

**Issue by b-strauss** [google/closure-compiler#2290]
Using the closure-library together with `strict_mode` and a function wrapper that looks like this:

```
(function(){%output%})();
```

produces the following js:

```
(function(){
  'use strict';
  // app here
  // all running in strict mode
})();
```

The source code for `goog.global` is:

```
goog.global = this;
```

`this` is undefined in `strict_mode` functions.

Would it be feasable to create a compiler flag that replaces the right hand expression for `goog.global`?

Something like:

`--goog_global_overwrite="window"`

tested on:
```
"google-closure-library": "v20161024.0.0",
"google-closure-compiler": "20161024.2.0",
```

**Comment by ChadKillingsworth** [comment]
Your output wrapper is losing the `this` context. Use:

```
--output_wrapper (function(){%output%}).call(this);
```
