### ISSUE TITLE
"Missing return statement" error on abstract method

### ISSUE THREAD

**Issue by myphysicslab** [google/closure-compiler#2295]
With NTI (new type inference) the compiler complains about abstract methods not having a return statement.

```
input0:125: WARNING - Missing return statement. Function expected to return number.
AbstractMassObject.prototype.getBottomBody = function() {};
                                             ^^^^^^^^^^^^^

0 error(s), 1 warning(s), 98.5% typed
```

Here is a simplified example which produces the error in https://closure-compiler-debugger.appspot.com with CHECK_TYPES_NEW_INFERENCE and CHECK_MISSING_RETURN options added.  Try clicking [here](https://closure-compiler-debugger.appspot.com/#input0%3D%252F**%250A%2520*%2520Base%2520namespace%2520for%2520the%2520Closure%2520library.%2520%2520Checks%2520to%2520see%2520goog%2520is%2520already%250A%2520*%2520defined%2520in%2520the%2520current%2520scope%2520before%2520assigning%2520to%2520prevent%2520clobbering%2520if%250A%2520*%2520base.js%2520is%2520loaded%2520more%2520than%2520once.%250A%2520*%250A%2520*%2520%2540const%250A%2520*%252F%250Avar%2520goog%2520%253D%2520goog%2520%257C%257C%2520%257B%257D%253B%250A%250A%252F**%250A%2520*%2520Inherit%2520the%2520prototype%2520methods%2520from%2520one%2520constructor%2520into%2520another.%250A%2520*%250A%2520*%2520Usage%253A%250A%2520*%2520%253Cpre%253E%250A%2520*%2520function%2520ParentClass(a%252C%2520b)%2520%257B%2520%257D%250A%2520*%2520ParentClass.prototype.foo%2520%253D%2520function(a)%2520%257B%2520%257D%253B%250A%2520*%250A%2520*%2520function%2520ChildClass(a%252C%2520b%252C%2520c)%2520%257B%250A%2520*%2520%2520%2520ChildClass.base(this%252C%2520'constructor'%252C%2520a%252C%2520b)%253B%250A%2520*%2520%257D%250A%2520*%2520goog.inherits(ChildClass%252C%2520ParentClass)%253B%250A%2520*%250A%2520*%2520var%2520child%2520%253D%2520new%2520ChildClass('a'%252C%2520'b'%252C%2520'see')%253B%250A%2520*%2520child.foo()%253B%2520%252F%252F%2520This%2520works.%250A%2520*%2520%253C%252Fpre%253E%250A%2520*%250A%2520*%2520%2540param%2520%257B!Function%257D%2520childCtor%2520Child%2520class.%250A%2520*%2520%2540param%2520%257B!Function%257D%2520parentCtor%2520Parent%2520class.%250A%2520*%252F%250Agoog.inherits%2520%253D%2520function(childCtor%252C%2520parentCtor)%2520%257B%250A%2520%2520%252F**%2520%2540constructor%2520*%252F%250A%2520%2520function%2520tempCtor()%2520%257B%257D%250A%2520%2520tempCtor.prototype%2520%253D%2520parentCtor.prototype%253B%250A%2520%2520childCtor.superClass_%2520%253D%2520parentCtor.prototype%253B%250A%2520%2520childCtor.prototype%2520%253D%2520new%2520tempCtor()%253B%250A%2520%2520%252F**%2520%2540override%2520*%252F%250A%2520%2520childCtor.prototype.constructor%2520%253D%2520childCtor%253B%250A%250A%2520%2520%252F**%250A%2520%2520%2520*%2520Calls%2520superclass%2520constructor%252Fmethod.%250A%2520%2520%2520*%250A%2520%2520%2520*%2520This%2520function%2520is%2520only%2520available%2520if%2520you%2520use%2520goog.inherits%2520to%250A%2520%2520%2520*%2520express%2520inheritance%2520relationships%2520between%2520classes.%250A%2520%2520%2520*%250A%2520%2520%2520*%2520NOTE%253A%2520This%2520is%2520a%2520replacement%2520for%2520goog.base%2520and%2520for%2520superClass_%250A%2520%2520%2520*%2520property%2520defined%2520in%2520childCtor.%250A%2520%2520%2520*%250A%2520%2520%2520*%2520%2540param%2520%257B!Object%257D%2520me%2520Should%2520always%2520be%2520%2522this%2522.%250A%2520%2520%2520*%2520%2540param%2520%257Bstring%257D%2520methodName%2520The%2520method%2520name%2520to%2520call.%2520Calling%250A%2520%2520%2520*%2520%2520%2520%2520%2520superclass%2520constructor%2520can%2520be%2520done%2520with%2520the%2520special%2520string%250A%2520%2520%2520*%2520%2520%2520%2520%2520'constructor'.%250A%2520%2520%2520*%2520%2540param%2520%257B...*%257D%2520var_args%2520The%2520arguments%2520to%2520pass%2520to%2520superclass%250A%2520%2520%2520*%2520%2520%2520%2520%2520method%252Fconstructor.%250A%2520%2520%2520*%2520%2540return%2520%257B*%257D%2520The%2520return%2520value%2520of%2520the%2520superclass%2520method%252Fconstructor.%250A%2520%2520%2520*%252F%250A%2520%2520childCtor.base%2520%253D%2520function(me%252C%2520methodName%252C%2520var_args)%2520%257B%250A%2520%2520%2520%2520%252F%252F%2520Copying%2520using%2520loop%2520to%2520avoid%2520deop%2520due%2520to%2520passing%2520arguments%2520object%2520to%250A%2520%2520%2520%2520%252F%252F%2520function.%2520This%2520is%2520faster%2520in%2520many%2520JS%2520engines%2520as%2520of%2520late%25202014.%250A%2520%2520%2520%2520var%2520args%2520%253D%2520new%2520Array(arguments.length%2520-%25202)%253B%250A%2520%2520%2520%2520for%2520(var%2520i%2520%253D%25202%253B%2520i%2520%253C%2520arguments.length%253B%2520i%252B%252B)%2520%257B%250A%2520%2520%2520%2520%2520%2520args%255Bi%2520-%25202%255D%2520%253D%2520arguments%255Bi%255D%253B%250A%2520%2520%2520%2520%257D%250A%2520%2520%2520%2520return%2520parentCtor.prototype%255BmethodName%255D.apply(me%252C%2520args)%253B%250A%2520%2520%257D%253B%250A%257D%253B%250A%250A%252F**%250A*%2520%2540interface%250A*%252F%250Avar%2520SimObject%2520%253D%2520function()%2520%257B%257D%253B%250A%250A%252F**%250A%2540return%2520%257Bstring%257D%250A*%252F%250ASimObject.prototype.getName%253B%250A%250A%250A%252F**%250A*%2520%2540param%2520%257Bstring%253D%257D%2520opt_name%250A*%2520%2540constructor%250A*%2520%2540struct%250A*%2520%2540abstract%250A*%2520%2540implements%2520%257BSimObject%257D%250A*%252F%250Avar%2520AbstractSimObject%2520%253D%2520function(opt_name)%2520%257B%250A%2520%2520%252F**%250A%2520%2520*%2520%2540type%2520%257Bstring%257D%250A%2520%2520*%2520%2540private%250A%2520%2520*%252F%250A%2520%2520this.name_%2520%253D%2520opt_name%2520%257C%257C%2520'SIM_OBJ'%253B%250A%257D%253B%250A%250A%252F**%2520%2540inheritDoc%2520*%252F%250AAbstractSimObject.prototype.getName%2520%253D%2520function()%2520%257B%250A%2520%2520return%2520this.name_%253B%250A%257D%253B%250A%250A%252F**%250A*%2520%2540interface%250A*%2520%2540extends%2520%257BSimObject%257D%250A*%252F%250Avar%2520MassObject%2520%253D%2520function()%2520%257B%257D%253B%250A%250A%250A%252F**%250A%2540return%2520%257Bnumber%257D%250A*%252F%250AMassObject.prototype.getBottomBody%253B%250A%250A%250A%252F**%250A*%2520%2540param%2520%257Bstring%253D%257D%2520opt_name%250A*%2520%2540constructor%250A*%2520%2540abstract%250A*%2520%2540struct%250A*%2520%2540extends%2520%257BAbstractSimObject%257D%250A*%2520%2540implements%2520%257BMassObject%257D%250A*%252F%250Avar%2520AbstractMassObject%2520%253D%2520function(opt_name)%2520%257B%250A%2520%2520AbstractSimObject.call(this%252C%2520opt_name)%253B%250A%257D%253B%250Agoog.inherits(AbstractMassObject%252C%2520AbstractSimObject)%253B%250A%250A%252F**%2520%2540inheritDoc%2520%2540abstract%2520*%252F%250AAbstractMassObject.prototype.getBottomBody%2520%253D%2520function()%2520%257B%257D%253B%250A%250A%252F**%250A*%2520%2540param%2520%257Bstring%253D%257D%2520opt_name%250A*%2520%2540constructor%250A*%2520%2540final%250A*%2520%2540struct%250A*%2520%2540extends%2520%257BAbstractMassObject%257D%250A*%252F%250Avar%2520PointMass%2520%253D%2520function(opt_name)%2520%257B%250A%2520%2520AbstractMassObject.call(this%252C%2520opt_name)%253B%250A%2520%2520%252F**%250A%2520%2520*%2520%2540type%2520%257Bnumber%257D%250A%2520%2520*%2520%2540protected%250A%2520%2520*%252F%250A%2520%2520this.height_%2520%253D%25201%253B%250A%257D%253B%250A%250A%252F**%2520%2540inheritDoc%2520*%252F%250APointMass.prototype.getBottomBody%2520%253D%2520function()%2520%257B%250A%2520%2520return%2520-this.height_%252F2%253B%250A%257D%253B%250A%250Avar%2520pm%2520%253D%2520new%2520PointMass('mass1')%253B%250Aconsole.log(pm.getName()%252B'%2520'%252Bpm.getBottomBody())%253B%250A%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26CHECK_MISSING_RETURN%3D1%26MISSING_PROPERTIES%3D1%26TRANSPILE%3D1%26CHECK_TYPES%3D1%26CHECK_TYPES_NEW_INFERENCE%3D1%26CLOSURE_PASS%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1) to see this code in the online closure debugger.

```javascript
/**
 * Base namespace for the Closure library.  Checks to see goog is already
 * defined in the current scope before assigning to prevent clobbering if
 * base.js is loaded more than once.
 *
 * @const
 */
var goog = goog || {};

/**
 * Inherit the prototype methods from one constructor into another.
 *
 * Usage:
 * <pre>
 * function ParentClass(a, b) { }
 * ParentClass.prototype.foo = function(a) { };
 *
 * function ChildClass(a, b, c) {
 *   ChildClass.base(this, 'constructor', a, b);
 * }
 * goog.inherits(ChildClass, ParentClass);
 *
 * var child = new ChildClass('a', 'b', 'see');
 * child.foo(); // This works.
 * </pre>
 *
 * @param {!Function} childCtor Child class.
 * @param {!Function} parentCtor Parent class.
 */
goog.inherits = function(childCtor, parentCtor) {
  /** @constructor */
  function tempCtor() {}
  tempCtor.prototype = parentCtor.prototype;
  childCtor.superClass_ = parentCtor.prototype;
  childCtor.prototype = new tempCtor();
  /** @override */
  childCtor.prototype.constructor = childCtor;

  /**
   * Calls superclass constructor/method.
   *
   * This function is only available if you use goog.inherits to
   * express inheritance relationships between classes.
   *
   * NOTE: This is a replacement for goog.base and for superClass_
   * property defined in childCtor.
   *
   * @param {!Object} me Should always be "this".
   * @param {string} methodName The method name to call. Calling
   *     superclass constructor can be done with the special string
   *     'constructor'.
   * @param {...*} var_args The arguments to pass to superclass
   *     method/constructor.
   * @return {*} The return value of the superclass method/constructor.
   */
  childCtor.base = function(me, methodName, var_args) {
    // Copying using loop to avoid deop due to passing arguments object to
    // function. This is faster in many JS engines as of late 2014.
    var args = new Array(arguments.length - 2);
    for (var i = 2; i < arguments.length; i++) {
      args[i - 2] = arguments[i];
    }
    return parentCtor.prototype[methodName].apply(me, args);
  };
};

/**
* @interface
*/
var SimObject = function() {};

/**
@return {string}
*/
SimObject.prototype.getName;


/**
* @param {string=} opt_name
* @constructor
* @struct
* @abstract
* @implements {SimObject}
*/
var AbstractSimObject = function(opt_name) {
  /**
  * @type {string}
  * @private
  */
  this.name_ = opt_name || 'SIM_OBJ';
};

/** @inheritDoc */
AbstractSimObject.prototype.getName = function() {
  return this.name_;
};

/**
* @interface
* @extends {SimObject}
*/
var MassObject = function() {};


/**
@return {number}
*/
MassObject.prototype.getBottomBody;


/**
* @param {string=} opt_name
* @constructor
* @abstract
* @struct
* @extends {AbstractSimObject}
* @implements {MassObject}
*/
var AbstractMassObject = function(opt_name) {
  AbstractSimObject.call(this, opt_name);
};
goog.inherits(AbstractMassObject, AbstractSimObject);

/** @inheritDoc @abstract */
AbstractMassObject.prototype.getBottomBody = function() {};

/**
* @param {string=} opt_name
* @constructor
* @final
* @struct
* @extends {AbstractMassObject}
*/
var PointMass = function(opt_name) {
  AbstractMassObject.call(this, opt_name);
  /**
  * @type {number}
  * @protected
  */
  this.height_ = 1;
};

/** @inheritDoc */
PointMass.prototype.getBottomBody = function() {
  return -this.height_/2;
};

var pm = new PointMass('mass1');
console.log(pm.getName()+' '+pm.getBottomBody());
```

**Comment by dimvar** [comment]
Here is a simplified [repro case](https://closure-compiler-debugger.appspot.com/#input0%3D%252F**%2520%2540interface%2520*%252F%250Avar%2520MassObject%2520%253D%2520function()%2520%257B%257D%253B%250A%250A%252F**%2520%2540return%2520%257Bnumber%257D%2520*%252F%250AMassObject.prototype.getBottomBody%253B%250A%250A%252F**%250A*%2520%2540constructor%250A*%2520%2540abstract%250A*%2520%2540implements%2520%257BMassObject%257D%250A*%252F%250Avar%2520AbstractMassObject%2520%253D%2520function()%2520%257B%257D%253B%250A%250A%252F**%250A%2520*%2520%2540inheritDoc%250A%2520*%2520%2540abstract%250A%2520*%252F%250AAbstractMassObject.prototype.getBottomBody%2520%253D%2520function()%2520%257B%257D%253B%250A%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26MISSING_PROPERTIES%3D1%26TRANSPILE%3D1%26CHECK_TYPES%3D1%26CHECK_TYPES_NEW_INFERENCE%3D1%26CLOSURE_PASS%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1).

The problem is with `@inheritDoc`. When NTI sees it, it ignores everything else in the jsdoc, so it ignores `@abstract`. If you remove the inheritDoc, then you get the expected warning.

I'll fix this in NTI, but in general it's an anti-pattern to have the type information of a method be computed as a combination of jsdocs; `@override` and `@inheritDoc` should be used without other jsdoc tags. For classes implementing interfaces, class methods inherit the signature of the interface methods without the need of any jsdoc annotations.

**Comment by myphysicslab** [comment]
Removing @inheritDoc and leaving just @abstract fixes it for me.

I never knew that about class methods inheriting the interface signature automatically.  This means I can remove almost all the @inheritDoc tags in my code, which is nice, but I think it will be more clear to leave the @inheritDoc tags for human readers.

I have only one error in my code with NTI now, I'll submit that as a separate issue.

**Comment by dimvar** [comment]
> I never knew that about class methods inheriting the interface signature automatically.

They do, and similarly a subclass inherits type signatures from its superclass without the need of annotations.

Basically, the only benefit of `@override/@inheritDoc` is that if you use it on a method that doesn't override anything, you get a warning. This can catch typos such as a method named foobar1 in the superclass and mistakenly named foobar2 in the subclass.

**Comment by myphysicslab** [comment]
FYI I've updated the [wiki entries](https://github.com/google/closure-compiler/wiki/Annotating-JavaScript-for-the-Closure-Compiler) about `@inheritDoc` and `@override` with this info:

> This tag is not required when a class extends a superclass or implements an interface - in those cases the documentation is automatically inherited. This tag is mainly useful to catch typos such as a method named `foobar1` in the superclass and mistakenly named `foobar2` in the subclass.


I also update the [Using NTI wiki page](https://github.com/google/closure-compiler/wiki/Using-NTI-(new-type-inference)) with a note about the `--jscomp_error=newCheckTypes` option.
