### ISSUE TITLE
@param Array<T extends U> accepts Array<U> 

### ISSUE THREAD

**Issue by dballesteros7** [google/closure-compiler#2297]
The type checker is too loose about array of subclasses T of a base class U, the following method:

```javascript
/** @param {!Array<T>} param */
function do(param) {

}
```

Will accept `!Array<U>` where T extends U. Even though, it won't accept `!Array<Z>`.

Concrete example:
https://closure-compiler-debugger.appspot.com/#input0%3Dclass%2520Animal%2520%257B%250A%250A%257D%250A%250Aclass%2520Cat%2520extends%2520Animal%2520%257B%250A%250A%257D%250A%250A%252F**%250A%2520*%2520%2540param%2520%257B!Cat%257D%2520cat%250A%2520*%252F%250Afunction%2520bellyRub(cat)%2520%257B%257D%250A%250A%252F**%250A%2520*%2520%2540param%2520%257B!Array%253C!Cat%253E%257D%2520cats%250A%2520*%252F%250Afunction%2520batchBellyRub(cats)%2520%257B%250A%2520%2520cats.forEach(bellyRub)%253B%250A%257D%250A%250A%252F**%2520%2540return%2520%257B!Array%253C!Cat%253E%257D%2520*%252F%250Afunction%2520provideCats()%2520%257B%250A%2520%2520return%2520%255Bnew%2520Cat()%255D%253B%250A%257D%250A%250A%252F**%2520%2540return%2520%257B!Array%253C!Animal%253E%257D%2520*%252F%250Afunction%2520provideDogs()%2520%257B%250A%2520%2520return%2520%255Bnew%2520Animal()%252C%2520new%2520Animal()%255D%253B%250A%257D%250A%250Aclass%2520Human%2520%257B%257D%250A%250A%252F**%2520%2540return%2520%257B!Array%253C!Human%253E%257D%2520*%252F%250Afunction%2520provideHoomans()%2520%257B%250A%2520%2520return%2520%255Bnew%2520Human()%255D%253B%250A%257D%250A%250A%252F**%250A%2520*%2520Runs!%250A%2520*%252F%250Afunction%2520run()%2520%257B%250A%2520%2520batchBellyRub(provideCats())%253B%250A%2520%2520batchBellyRub(provideDogs())%253B%250A%2520%2520batchBellyRub(provideHoomans())%253B%250A%257D%250A%250A%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26MISSING_PROPERTIES%3D1%26TRANSPILE%3D1%26CHECK_TYPES%3D1%26CLOSURE_PASS%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1

This is fixed in the NTI, so I guess there is no solution without using NTI, is that correct?

**Comment by Dominator008** [comment]
Currently our generics are invariant. We do plan to add bounded generics in NTI.

**Comment by dballesteros7** [comment]
However, the behavior I described suggests that for arrays the types are
actually contravariant.

**Comment by Dominator008** [comment]
@dballesteros7 Yeah, it's actually bivariant in OTI (https://github.com/google/closure-compiler/commit/bf017f11005ec970546a1daf27f0e606a2719284) and I don't think we will fix it, so NTI is the path forward.
