### ISSUE TITLE
Need `@readonly` annotation for externs.

### ISSUE THREAD

**Issue by brad4d** [google/closure-compiler#2306]
Currently there's no way to indicate that a property cannot be set, but might change.
According to @dimvar using `@const` for such a property probably won't break anything currently, but might in the future and is definitely a misuse of `@const`.

**Comment by ChadKillingsworth** [comment]
FYI this is a duplicate of #139

**Comment by brad4d** [comment]
@ChadKillingsworth Thanks! I'll close this one then.
