### ISSUE TITLE
HO

### ISSUE THREAD

**Issue by shicks** [google/closure-compiler#2311]
[](https://closure-compiler-debugger.appspot.com/#input0%3D%252F**%2520%2540interface%2520*%252F%250Aclass%2520BaseInterface%2520%257B%250A%2520%2520%252F**%2520%2540return%2520%257B!BaseInterface%257D%2520*%252F%2520foo()%2520%257B%257D%250A%257D%250A%250A%252F**%2520%2540interface%2520%2540extends%2520%257BBaseInterface%257D%2520*%252F%250Aclass%2520SubInterface%2520%257B%250A%2520%2520%252F**%2520%2540override%2520%2540return%2520%257B!SubInterface%257D%2520*%252F%2520foo()%2520%257B%257D%250A%257D%250A%250A%252F**%2520%2540implements%2520%257BBaseInterface%257D%2520*%252F%250Aclass%2520Abstract%2520%257B%250A%2520%2520%252F**%2520%2540override%2520*%252F%2520foo()%2520%257B%2520return%2520new%2520Abstract()%253B%2520%257D%250A%257D%250A%250A%252F**%2520%2540extends%2520%257BAbstract%257D%250A%2520%2520%2520%2520%2540implements%2520%257BSubInterface%257D%2520*%252F%250Aclass%2520SubAbstract%2520extends%2520Abstract%2520%257B%250A%2520%2520%252F**%2520%2540override%250A%2520%2520%2520%2520%2520%2520%2540this%2520%257B!Abstract%257D%250A%2520%2520%2520%2520%2520%2520%2540return%2520%257B!SubInterface%257D%2520*%252F%250A%2520%2520foo()%2520%257B%2520return%2520new%2520SubAbstract()%253B%2520%257D%250A%257D%250A%250A%252F**%2520%2540extends%2520%257BAbstract%257D%2520*%252F%250Aclass%2520Other%2520extends%2520Abstract%2520%257B%257D%250A%250A%252F**%2520%2540extends%2520%257BOther%257D%250A%2520%2520%2520%2520%2540implements%2520%257BSubInterface%257D%2520*%252F%250Aclass%2520SubOther%2520extends%2520Other%2520%257B%257D%250A%250A%252F**%2520%2540override%2520*%252F%250ASubOther.prototype.foo%2520%253D%2520SubAbstract.prototype.foo%253B%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26MISSING_PROPERTIES%3D1%26TRANSPILE%3D1%26CHECK_TYPES%3D1%26CLOSURE_PASS%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1)

**Comment by shicks** [comment]
Oops, fat-fingered.

**Comment by MatrixFrog** [comment]
https://media.giphy.com/media/l0HlNAi0HfmOvoWli/giphy.gif
