### ISSUE TITLE
Callback function with extern is being removed by ADVANCED_OPTIMIZATIONS dead code removal

### ISSUE THREAD

**Issue by davidtgq** [google/closure-compiler#2315]
In this example, `grc` is being removed by CC which is not what I intend:

```
var grc, captchaPromise;

function makeCaptcha(captchaElement, callback) {
  if (!captchaPromise) {
    captchaPromise = new Promise((resolve, reject) => {
      grc = function() {
        resolve();
      };
      $.getScript('//www.google.com/recaptcha/api.js?onload=grc&render=explicit');
    });
  }
```

This round-about logic is necessary because Google Recaptcha's library itself loads another bigger library before it's ready to use, i.e. when it calls `grc()`.

Extern:

`var grc = function () {};`

CC cannot see `grc` being used, but it clearly is being used in the `onload` callback. If there is a way to define an extern in such a way that the "unused" function won't be removed but will still be optimized, I'm not aware of it and would like to learn about it. Otherwise, I think an unused variable or function should not be removed by `ADVANCED_OPTIMIZATIONS` if it has an extern.

**Comment by davidtgq** [comment]
Found the solution: https://developers.google.com/closure/compiler/docs/api-tutorial3#export

For the benefit of future googlers: `window['grc'] = function () {stuff};`

**Comment by ChadKillingsworth** [comment]
You redeclared the variable and it was then no longer external.
