### ISSUE TITLE
Advanced Optimization Warning With For-Of Loop and TypedArray

### ISSUE THREAD

**Issue by dsanders11** [google/closure-compiler#2326]
```
// ==ClosureCompiler==
// @compilation_level ADVANCED_OPTIMIZATIONS
// @output_file_name default.js
// ==/ClosureCompiler==

var intArray = new Int32Array([1, 2, 3, 4]);
var sum = 0;

for (var int of intArray) {
  sum += int;
}

alert(sum);
```

The above code causes a compiler warning only when compiling as `ADVANCED_OPTIMIZATIONS`, but the compiled code executes fine (Chrome 56):

```
JSC_TYPE_MISMATCH: actual parameter 1 of $jscomp.makeIterator does not match formal parameter
found   : Int32Array
required: (Arguments<?>|Array<?>|Iterable<?>|Iterator<?>|string) at line 4 character 16
for (var int of intArray) {
```

Seems like TypedArray should be one of the possible types for for-of?

Also seems a bit odd that the type error doesn't appear under `SIMPLE_OPTIMIZATIONS` as I'd assumed the type checking itself would be the same between them as far as parameters go.

**Comment by MatrixFrog** [comment]
We probably just need to make the externs definition of `TypedArray` implement `Iterable`
