### ISSUE TITLE
passive event listener syntax triggers JSC_TYPE_MISMATCH warning

### ISSUE THREAD

**Issue by supraniti** [google/closure-compiler#2339]
the following code:
```
var elem = document.getElementById('elem');
elem.addEventListener('touchmove', function listener() {
  /* do something */
}, { passive: false });
```
triggers a type mismatch warning, (closure expects a boolean even though the third argument can also be an options object according to the [spec](https://dom.spec.whatwg.org/#dictdef-addeventlisteneroptions)).

**Comment by ChadKillingsworth** [comment]
This is covered by #2181

**Comment by brad4d** [comment]
Closed as a duplicate
