### ISSUE TITLE
Type checking disabled when assign template type values

### ISSUE THREAD

**Issue by ikabirov** [google/closure-compiler#2344]
http://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540compilation_level%2520ADVANCED_OPTIMIZATIONS%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%2540language%2520ECMASCRIPT8%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250A%2520%2520%252F**%2520%2540type%2520%257B!Object%253Cstring%252C%2520number%253E%257D%2520*%252F%250A%2509const%2520o%2520%253D%2520%257B%2522foo%2522%253A%2520%2522bar%2522%257D%253B%250A%250A%2509%252F**%2520%2540type%2520%257B!Array%253Cnumber%253E%257D%2520*%252F%250A%2509const%2520a%2520%253D%2520%255B%2522foo%2522%255D%253B%250A%250A%2509%252F**%2520%2540type%2520%257Bstring%257D%2520*%252F%250A%2509const%2520b%2520%253D%2520a%255B0%255D%253B%250A%250A

**Comment by dimvar** [comment]
It is a known bug that the type checker doesn't infer the contents of array literals. So, the right hand side has type `Array<?>`, and there is no warning. In the new type inference, this warns. There are no plans to fix this in the old type checker.
