### ISSUE TITLE
Feature request: TypeScript index signature types

### ISSUE THREAD

**Issue by bowenni** [google/closure-compiler#2356]
I would like to add the ability to parse and transpile [TypeScript index signature](https://www.typescriptlang.org/docs/handbook/interfaces.html#indexable-types) types. This would be similar to @Dominator008 's previous commit that added the [record type](https://github.com/google/closure-compiler/commit/468d46f25c8874453797c2e7f2d353b01d2ef293)

This is needed for Closure Object map type conversion to TS: https://github.com/angular/clutz/issues/390
@rkirov 

Is it all right if I add the index signature types support? Are there any concerns?

**Comment by Dominator008** [comment]
To clarify, you would like add CodeGenerator support for index signature types right? I thought I added parsing support already: https://github.com/google/closure-compiler/blob/ce5b2aae8644a084607426e8212c28986ecef990/src/com/google/javascript/jscomp/parsing/parser/Parser.java#L1131

**Comment by bowenni** [comment]
That's right. Sorry I missed that part.

I also want a way to instantiate a TypeDeclarationNode representing the index signature types. So something like [this](https://github.com/google/closure-compiler/blob/0a0a8ec45ab0df1f5d35bd2881a9dea2b4f7cceb/src/com/google/javascript/rhino/TypeDeclarationsIR.java#L148). Is this also supported already?

**Comment by Dominator008** [comment]
@bowenni Actually I think CodeGenerator support is in place already: https://github.com/google/closure-compiler/blob/d97a43d7cccfc2b2fe8dc7e3c9512382034011c2/src/com/google/javascript/jscomp/CodeGenerator.java#L1224

So only TypeDeclarationNode support needs to be added.

**Comment by dimvar** [comment]
@Dominator008 Michael, will you be able to do code reviews for this?

**Comment by Dominator008** [comment]
@dimvar Yes I can.
@bowenni It will be better if you submit the change internally.

**Comment by dimvar** [comment]
Thanks!

**Comment by bowenni** [comment]
will send a CL, thanks!

**Comment by bowenni** [comment]
It turns out that only Parser and IRFactory support for index signature type is needed (which is already in place). TypeDeclarationNode support is not necessary. We have customized compiler passes.

Thanks for helping and sorry for the confusion.
