### ISSUE TITLE
Compiler crash when mixing goog.module and export

### ISSUE THREAD

**Issue by evmar** [google/closure-compiler#2358]
This code is not valid, but the compiler shouldn't crash:
```js
goog.module('ice');
export class Ice {
}
```

```
java.lang.RuntimeException: java.lang.RuntimeException: INTERNAL COMPILER ERROR.
Please file a bug at http://go/jscompiler-bug with this stack trace, sponge link, and repro steps (a CL# and a build target).

insertion point must be a statement: CLASS 2 [length: 14] [source_file: input0]
  Node(CLASS): input0:2:7
export class Ice {
  Parent(EXPORT): input0:2:0
export class Ice {

	at com.google.javascript.jscomp.CompilerExecutor.runInCompilerThread(CompilerExecutor.java:126)
	at com.google.javascript.jscomp.Compiler.runInCompilerThread(Compiler.java:763)
	at com.google.javascript.jscomp.Compiler.compile(Compiler.java:733)
	at com.google.javascript.jscomp.Compiler.compileModules(Compiler.java:724)
```

https://closure-compiler-debugger.appspot.com/#input0%3Dgoog.module('ice')%253B%250Aexport%2520class%2520Ice%2520%257B%250A%257D%250A%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26MISSING_PROPERTIES%3D1%26TRANSPILE%3D1%26CHECK_TYPES%3D1%26COMPUTE_FUNCTION_SIDE_EFFECTS%3D1%26INLINE_VARIABLES%3D1%26SMART_NAME_REMOVAL%3D1%26REMOVE_UNUSED_PROTOTYPE_PROPERTIES%3D1%26REMOVE_UNUSED_PROTOTYPE_PROPERTIES_IN_EXTERNS%3D1%26COLLAPSE_PROPERTIES%3D1%26DEVIRTUALIZE_PROTOTYPE_METHODS%3D1%26VARIABLE_RENAMING%3D1%26PROPERTY_RENAMING%3D1%26CLOSURE_PASS%3D1%26GENERATE_EXPORTS%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1

**Comment by lauraharker** [comment]
The debugger link now doesn't crash and reports 
```
WARNING - File cannot be a combination of goog.provide, goog.module, and/or ES6 module: input0

input0:2: ERROR - A file cannot be both a goog.module and an ES6 module.
export class Ice {
^^^^^^^^^^^^^^^^^^^
```

Closing the issue.
