### ISSUE TITLE
One of the LINT_CHECKS is an error by default

### ISSUE THREAD

**Issue by supersteves** [google/closure-compiler#2359]
"These checks are not intended to be enabled as errors"

Yet [`DiagnosticGroup.LINT_CHECKS`](https://github.com/google/closure-compiler/blob/master/src/com/google/javascript/jscomp/DiagnosticGroups.java#L593) includes the diagnostic type [`ClosureCheckModule.GOOG_MODULE_IN_NON_MODULE`](https://github.com/google/closure-compiler/blob/master/src/com/google/javascript/jscomp/ClosureCheckModule.java#L49), recently updated to *error*.

Should this have been moved into a different group?

**Comment by MatrixFrog** [comment]
No, that one is a hard error, but we put it in the lint checks too so that it would show up in the linter. Would it be clearer to say "We do not recommend enabling the lint checks group as an error"?

**Comment by supersteves** [comment]
I see, the entire group shouldn't be enabled, but some can be errors. Looked like a mistake. Thanks.
