### ISSUE TITLE
calls to the querySelector method are cut off in case of ADVANCED_OPTIMIZATIONS and turned off checkTypes warnings

### ISSUE THREAD

**Issue by nederland074** [google/closure-compiler#2365]
The compilation of a file, which contains only one line: 
`document.querySelector(".test").some_prop = true;`

leads to an empty output when using the compiler with these flags:
`java -jar compiler.jar --compilation_level=ADVANCED_OPTIMIZATIONS --jscomp_off=checkTypes --js=in.js --js_output_file=out.js`

However, enabling the checkTypes warnings (`--jscomp_warning=checkTypes`) fixes it and the output is ok: `document.querySelector(".test").a=!0;`

It doesn't matter if the altered property is a custom "some_prop" or a built-in one like the "className" or "id". Also, the querySelectorAll method doesn't have such an issue and the following code is compiled without problems: 
`document.querySelectorAll(".test")[0].some_prop = true;`

It's reproduced in GCC v20161201.

**Comment by MatrixFrog** [comment]
Hm. I wonder if we accidentally made an assumption somewhere that anyone using advanced mode would also be using typechecking.

**Comment by tonsky** [comment]
any progress on this? Ran into it today with both v20170910 and v20171023

**Comment by brad4d** [comment]
I played around some with reproducing this today.
The `--print_source_after_each_pass` option seems to indicate that `peepholeOptimizations` pass is removing the whole statement.

Further node regarding the "it doesn't happen with `querySelectorAll()`" note in the description.
The important difference there is not the method being called, but the `[0]` array access before
accessing the property.

**Comment by ChadKillingsworth** [comment]
> In ADVANCED mode, property sets do not have arbitrary side-effects (it is ok to remove property writes if the property is never read), as described here

**Comment by brad4d** [comment]
@ChadKillingsworth thanks for that info.
It's a bit more than that, though.

Suppose we have code like this:
```javascript
someExternFunction().someProperty = something;
```

`someExternFunction()` might return a value that is part of global state, so setting `someProperty` on it affects global state and is unsafe to remove. We should assume that this is the case for extern functions unless type info tells us otherwise.
`PureFunctionIdentifier` is incorrectly assuming the opposite when it has no type information.

I have a change to fix this in internal review.

**Comment by ChadKillingsworth** [comment]
@brad4d Yeah - that was just a reminder for external viewers.
