### ISSUE TITLE
Compiler crash when using a simple class (?)

### ISSUE THREAD

**Issue by evmar** [google/closure-compiler#2366]
Not sure what I'm doing wrong here, this code seems pretty obvious.

```js
class X {
  foo() {
  }
}

var x = new X();
x.foo()
```

```
java.lang.RuntimeException: java.lang.RuntimeException: INTERNAL COMPILER ERROR.
Please file a bug at http://go/jscompiler-bug with this stack trace, sponge link, and repro steps (a CL# and a build target).

Unexpected variable X
  Node(NAME X): input0:6:12
var x = new X();
  Parent(NEW): input0:6:8
var x = new X();

	at com.google.javascript.jscomp.CompilerExecutor.runInCompilerThread(CompilerExecutor.java:126)
	at com.google.javascript.jscomp.Compiler.runInCompilerThread(Compiler.java:763)
	at com.google.javascript.jscomp.Compiler.compile(Compiler.java:733)
	at com.google.javascript.jscomp.Compiler.compileModules(Compiler.java:724)
	at com.google.javascript.jscomp.debugger.CompilationServlet.service(CompilationServlet.java:95)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
```

https://closure-compiler-debugger.appspot.com/#input0%3Dclass%2520X%2520%257B%250A%2520%2520foo()%2520%257B%250A%2520%2520%257D%250A%257D%250A%250Avar%2520x%2520%253D%2520new%2520X()%253B%250Ax.foo()%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26MISSING_PROPERTIES%3D1%26TRANSPILE%3D1%26CHECK_TYPES%3D1%26COMPUTE_FUNCTION_SIDE_EFFECTS%3D1%26INLINE_VARIABLES%3D1%26SMART_NAME_REMOVAL%3D1%26REMOVE_UNUSED_PROTOTYPE_PROPERTIES%3D1%26REMOVE_UNUSED_PROTOTYPE_PROPERTIES_IN_EXTERNS%3D1%26COLLAPSE_PROPERTIES%3D1%26DEVIRTUALIZE_PROTOTYPE_METHODS%3D1%26VARIABLE_RENAMING%3D1%26PROPERTY_RENAMING%3D1%26CLOSURE_PASS%3D1%26GENERATE_EXPORTS%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1

**Comment by evmar** [comment]
Wrapping the declaration of x in an IIFE seems to avoid this (?).  Using a goog.module doesn't.

**Comment by MatrixFrog** [comment]
Same cause as https://github.com/google/closure-compiler/issues/2364 perhaps.

**Comment by dimvar** [comment]
Wow, this code is too innocent to cause a crash. I [removed a few more flags](https://closure-compiler-debugger.appspot.com/#input0%3Dclass%2520X%2520%257B%250A%2520%2520foo()%2520%257B%250A%2520%2520%257D%250A%257D%250A%250Avar%2520x%2520%253D%2520new%2520X()%253B%250Ax.foo()%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26TRANSPILE%3D1%26COMPUTE_FUNCTION_SIDE_EFFECTS%3D1%26SMART_NAME_REMOVAL%3D1%26CLOSURE_PASS%3D1) from the repro. Removing either the side effect computation or smart name pass no longer repros.

**Comment by dimvar** [comment]
@brad4d can you take a look at this one?

**Comment by brad4d** [comment]
hacked debugger to enable printing code after each pass and ran repro locally.
Last output before crash was this.

```javascript
// Es6RewriteBlockScopedDeclaration yields:
// ************************************
/** @struct @constructor */ var X = function() {
};
X.prototype.foo = function() {
};
var x = new X;
x.foo();


// smartNamePass yields:
// ************************************
x.foo();
```

So it seems the (not-so) smartNamePass is removing the constructor.

**Comment by brad4d** [comment]
This was fixed a couple of months ago because we completely replaced smartNamePass with functionality in `RemoveUnusedCode`.
