### ISSUE TITLE
Eclipse setup instructions are incomplete

### ISSUE THREAD

**Issue by martinklepsch** [google/closure-compiler#2372]
When running `mvn -DskipTests` as outlined in [the readme](https://github.com/google/closure-compiler#building-it-yourself) it produces a `com.google.javascript/closure-compiler 1.0-SNAPSHOT"` release as promised. When adding that jar to my project though it looks for a `closure-compiler-parent` artifact that cannot be found.

The Eclipse instructions mention the `-parent` "project" so I assume it's created when going through the Eclipse steps. It would be nice to also have this installed into `~/.m2` when using plain `mvn`.

Right now the plain Maven instructions are basically broken because you can't use the produced jar as-is.

**Comment by MatrixFrog** [comment]
I don't use Eclipse. @ChadKillingsworth might have some good advice here.

**Comment by martinklepsch** [comment]
@MatrixFrog I'm actually asking about the Maven instructions that seem incomplete. When running the `mvn -DskipTests` command, I would expect a `closure-compiler-parent` jar of sorts to show up. Is that expectation misguided?

**Comment by MatrixFrog** [comment]
The maven command produces a jar that is runnable. That's all it's meant to do. Unless I misread, the parent jar is only needed for the Eclipse setup?

**Comment by martinklepsch** [comment]
@MatrixFrog so the jar resulting from the mvn process is not intended to be used as a dependency? How do you build a jar that packages the compiler as a maven-consumable artifact?

**Comment by MatrixFrog** [comment]
> @MatrixFrog so the jar resulting from the mvn process is not intended to be used as a dependency?

No, it's just intended to be run with `java -jar`.

> How do you build a jar that packages the compiler as a maven-consumable artifact?

I don't know, sorry.

**Comment by martinklepsch** [comment]
I'll close this in favor of #2373
