### ISSUE TITLE
Node module resolution does not normalize paths with trailing slashes

### ISSUE THREAD

**Issue by thosmos** [google/closure-compiler#2377]
closure fails to interpret `require('./lib/')` as pointing to `require('./lib/index.js')`
modifying the code to `require('./lib/index')` is a workaround

here's the relevant error:

WARNING: JSC_JS_MODULE_LOAD_WARNING. Failed to load module "./lib/" at /Users/thomas/Develop/cljs/rimdb/fauna-module/node_modules/qs/index.js line 1 : 17

**Comment by ChadKillingsworth** [comment]
What flags did you use? In particular, what did you specify for the `--module_resolution` flag?

**Comment by anmonteiro** [comment]
This is using the `NODE` module resolution mode

**Comment by anmonteiro** [comment]
@ChadKillingsworth it does work without the trailing slash.

FWIW, this can be reproduced with qs@2.3.3 (https://www.npmjs.com/package/qs)

**Comment by ChadKillingsworth** [comment]
The fix for this is part of #2343

**Comment by ChadKillingsworth** [comment]
Closed by e51b5bd
