### ISSUE TITLE
Repetitive Code in Compiler Output - When Using Modules [bug?]

### ISSUE THREAD

**Issue by orenmizr** [google/closure-compiler#2381]
this needs to be a function - it adds unneeded weight. 45 modules means 45 of these :

var r = {};
Object.defineProperty(r, "__esModule", {
    value: !0
});

var v = {};
Object.defineProperty(v, "__esModule", {
    value: !0
});

var E = {};
Object.defineProperty(E, "__esModule", {
    value: !0
});

**Comment by ChadKillingsworth** [comment]
That looks like babel code - not closure compiler.
