### ISSUE TITLE
Internal compiler failure when annotating a setter @param, but with type and param name swapped

### ISSUE THREAD

**Issue by markmcd** [google/closure-compiler#2384]
If the setter param annotation has the type and param name switched, the compiler crashes pretty hard.

[Repro here](https://closure-compiler-debugger.appspot.com/#input0%3Dclass%2520Works%2520%257B%250A%2520%2520%252F**%2520%2540param%2520%257B*%257D%2520v%2520*%252F%250A%2520%2520set%2520answer(v)%2520%257B%2520return%253B%2520%257D%250A%2520%2520%250A%2520%2520%252F**%2520%2540param%2520arg%2520%257B*%257D%2520*%252F%250A%2520%2520mymethod(arg)%2520%257B%2520return%253B%2520%257D%250A%257D%250A%250Aclass%2520Fails%2520%257B%250A%2520%2520%252F**%2520%2540param%2520v%2520%257B*%257D%2520*%252F%250A%2520%2520set%2520answer(v)%2520%257B%2520return%253B%2520%257D%250A%257D%250A%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26MISSING_PROPERTIES%3D1%26TRANSPILE%3D1%26CHECK_TYPES%3D1%26CLOSURE_PASS%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1) and here:
```js
class Works {
  /** @param {*} v */
  set answer(v) { return; }
  
  /** @param arg {*} */
  mymethod(arg) { return; }
}

class Fails {
  /** @param v {*} */
  set answer(v) { return; }
}
```

This appears to be specific to setters on classes, as the param swapping does not fail on normal class methods, or setters on plain objects. As partially demonstrated in the code above.

**Comment by brad4d** [comment]
@markmcd 
Thanks for reporting this.
Definitely a bug.

Looks like `Es6ToEs3Converter.visitComputedPropInClass` fails to notice it receives a null when it asks for the single parameter's JS doc.

Marked as help wanted since this could be a good fix for a volunteer to take.

**Comment by lauraharker** [comment]
This is fixed now.
