### ISSUE TITLE
Objects extending Function become non-callable, unless they are casted, using advanced optimizations

### ISSUE THREAD

**Issue by erickrgb** [google/closure-compiler#2385]
When I run the next code using the advanced optimizations:

```javascript
/** @constructor
@extends {Function} */
const A = function () {};

/** @constructor
@extends {A} */
const B = function () {};

let B1 = new B();
B1();

let B2 = /** @type {!Function} */ (new B());
B2();
```

When I don't cast the new B object (B1), it throws a warning: JSC_NOT_FUNCTION_TYPE: B expressions are not callable.
When running this on simple optimizations mode, it has no issues.

Is this an expected behaviour, or could be maybe a bug?

[Here](https://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%2540compilation_level%2520ADVANCED_OPTIMIZATIONS%250A%252F%252F%2520%2540formatting%2520pretty_print%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250A%252F**%2520%2540constructor%250A%2540extends%2520%257BFunction%257D%2520*%252F%250Aconst%2520A%2520%253D%2520function%2520()%2520%257B%257D%253B%250A%250A%252F**%2520%2540constructor%250A%2540extends%2520%257BA%257D%2520*%252F%250Aconst%2520B%2520%253D%2520function%2520()%2520%257B%257D%253B%250A%250Alet%2520B1%2520%253D%2520new%2520B()%253B%250AB1()%253B%250A%250Alet%2520B2%2520%253D%2520%252F**%2520%2540type%2520%257B!Function%257D%2520*%252F%2520(new%2520B())%253B%250AB2()%253B), the repro.

**Comment by brad4d** [comment]
This is correct behavior. `B1` is not a function, it's an object.
