### ISSUE TITLE
@nosideeffect annotation in ES6 collection constructors

### ISSUE THREAD

**Issue by localvoid** [google/closure-compiler#2396]
Are there any reasons why ES6 collection constructors doesn't have nosideeffect annotations?

https://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540compilation_level%2520ADVANCED_OPTIMIZATIONS%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250A%252F**%250A%2520*%2520%2540constructor%250A%2520*%252F%250Afunction%2520MapTest()%2520%257B%250A%2520%2520this.a%2520%253D%2520new%2520Map()%253B%250A%257D%250A%250A%250A%252F**%250A%2520*%2520%2540constructor%250A%2520*%252F%250Afunction%2520ArrayTest()%2520%257B%250A%2520%2520this.a%2520%253D%2520new%2520Array()%253B%250A%257D%250A%250Anew%2520MapTest()%253B%250Anew%2520ArrayTest()%253B%250A%250A

**Comment by MatrixFrog** [comment]
Probably just because we forgot to add them. Good catch.
