### ISSUE TITLE
Don't generate directive prologues from expressions

### ISSUE THREAD

**Issue by bmeck** [google/closure-compiler#2407]
In advanced compilation mode:

```
['use strict'][0];
foobar;
```

should not become

```
"use strict";
foobar;
```

**Comment by ChadKillingsworth** [comment]
There's no easy way to prevent this. We do a lot of arbitrary optimizations and every single one of them would have to be checked.

```js
(() => {
  return 'use strict'; // I might get inlined ...
})();
'use strict'.split('|')[0];
```

**Comment by brad4d** [comment]
Unless there turns out to be a really compelling use-case, I don't think this is something we want to spend time on. Sorry.
