### ISSUE TITLE
Don't inline functions with the "use strict" directive.

### ISSUE THREAD

**Issue by brad4d** [google/closure-compiler#2408]
Discovered during resolution of pull request #2279 
This is really a separate bug, but its interaction with that change caused a known failure, forcing us to roll it back temporarily.

**Comment by ChadKillingsworth** [comment]
So is this just don't inline functions with the `use strict` directive who's parent scope isn't also `use strict`?

**Comment by dimvar** [comment]
Why the parent scope? I'd think it would be "don't inline a strict function into a non-strict scope".

**Comment by brad4d** [comment]
We could specifically try to determine whether the enclosing scope is non-strict, but is it worth doing that?
It adds complication to the logic which could be a source of bugs for very little benefit, since functions with an explicit "use strict" are rare.

Am I wrong in thinking that they are rare?

**Comment by brad4d** [comment]
@concavelenz says we never output the "use strict" in functions anyway, so this really shouldn't be a problem.

Preventing inlining would have fixed the failure I'm encountering related to PR #2279, but it seems it's not the right solution.
