### ISSUE TITLE
Check why we aren't warning for an undeclared variable in advanced mode

### ISSUE THREAD

**Issue by dimvar** [google/closure-compiler#2411]
`var x = React123;`

Only tried this with the appspot compiler and got no warning. I thought we run checkVars but maybe we changed something recently. In any case, we should take a look and make sure we error for this.

**Comment by ChadKillingsworth** [comment]
Appspot runs in 3rd party mode. Undeclared vars are assumed to be external. This has been this way since the beginning and causes nothing but heartache. Can we change it?
