### ISSUE TITLE
ES6 module support breaks for paths containing some chars (eg `+`)

### ISSUE THREAD

**Issue by alexeagle** [google/closure-compiler#2414]
Here's a smallish repro:
https://github.com/FrozenPandaz/closure-compiler-angular-bundling/tree/plus_directories

If one of the files in the compilation uses ES6 syntax and a `+` in the name, we get
```
built/+basic.js:1: ERROR - "module$built$+basic" is not a valid ECMASCRIPT6 qualif
ied name
```

this is a problem because the Angular style guide recommends using a `+` prefix on directories containing lazy routes.

**Comment by ChadKillingsworth** [comment]
That's a trivial fix.

**Comment by alexeagle** [comment]
I can send a PR for this. I think the fix belongs here:
https://github.com/google/closure-compiler/blob/master/src/com/google/javascript/jscomp/deps/ModuleNames.java#L64
any idea where is the right place to add the test?

**Comment by MatrixFrog** [comment]
https://github.com/google/closure-compiler/tree/master/test/com/google/javascript/jscomp/runtime_tests/module_tests or https://github.com/google/closure-compiler/blob/master/test/com/google/javascript/jscomp/ProcessEs6ModulesTest.java I would guess.

**Comment by ChadKillingsworth** [comment]
Right here: https://github.com/google/closure-compiler/blob/master/src/com/google/javascript/jscomp/deps/ModuleNames.java#L45-L69

**Comment by alexeagle** [comment]
Mailed a google-internal change for it (I can also post a PR if you'd like to review, Chad. I didn't see how to run the runtime_tests without fighting with my IDE setup and Maven...)

**Comment by MatrixFrog** [comment]
We don't have a way to run the runtime tests externally, currently.

**Comment by ChadKillingsworth** [comment]
Yeah I can't review internal PRs and it's much easier for you to do internally. If it breaks something, I'll just PR the fix and have you review it 😄
