### ISSUE TITLE
warnings when inline type annotation appears within ES6 template literal

### ISSUE THREAD

**Issue by alexeagle** [google/closure-compiler#2422]
`${file.name}: File must be larger than ${ /** @type {?} */((minFileSize)) / 1000 | 0}kb`

ERROR - Misplaced type annotation. Type annotations are not allowed here. Are you missing parentheses?

https://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540compilation_level%2520ADVANCED_OPTIMIZATIONS%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%2540formatting%2520pretty_print%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250A%2560%2524%257Bfile.name%257D%253A%2520File%2520must%2520be%2520larger%2520than%2520%2524%257B%2520%252F**%2520%2540type%2520%257B%253F%257D%2520*%252F((minFileSize))%2520%252F%25201000%2520%257C%25200%257Dkb%2560%253B%250A

originally reported at https://github.com/angular/tsickle/issues/456
@MatrixFrog says "Maybe we're dropping a CAST node when converting the template literal, or something."

**Comment by lauraharker** [comment]
This was fixed in https://github.com/google/closure-compiler/commit/82547816ac041a219841bb3e42d89110510099ac.
