### ISSUE TITLE
Reduce --js_module_root verbosity

### ISSUE THREAD

**Issue by kylecordes** [google/closure-compiler#2423]
(feature request)

I've been working with Closure and Angular, writing lots of flagfiles similar to this one from @alexeagle :

https://github.com/alexeagle/closure-compiler-angular-bundling/blob/master/closure.conf

Such files typically have many pairs of lines/settings, like so:

```
node_modules/@angular/platform-browser/@angular/platform-browser.js
--js_module_root=node_modules/@angular/platform-browser
```

It would be great if one could write:

```
node_modules/@angular/platform-browser/^@angular/platform-browser.js
```

... where "^" is some character not otherwise legal in a path, to have the same meaning as the two lines above.

Another variation would be something like, a base dir followed by the path inside to import:

```
--js-include node_modules/@angular/platform-browser/ @angular/platform-browser.js
```

Here is a possible justification for such sugar. As Closure is used more and more with ES2015 modules and CommonJS modules (rather than `goog.` modules), many of us will have a large majority of our path specifications need an accompanying `--js_module_root=` for a portion of the path. Such syntax reduces opportunity for error, and reduces config verbosity. Such a syntax is concise and expressive.

Alternatively, an argument against it: a consuming application could easily generate the flagfile format, to work around the verbosity as needed.

**Comment by ChadKillingsworth** [comment]
My guess is were you to use the `NODE` module resolution mdoe, that you wouldn't need those at all.

**Comment by ChadKillingsworth** [comment]
`--module_resolution=NODE` is the actual flag. You'll also need to provide package.json files as source to the compiler. If for some reason that doesn't work, I'd like to know why.

See https://github.com/google/closure-compiler/wiki/JS-Modules#module-resolution-mode

**Comment by kylecordes** [comment]
@ChadKillingsworth Possibly, but:

* As far as I can tell, `NODE` mode is not yet aware of the `es2015` package.json field used by Angular. (Perhaps I should put in a feature request for this instead...)
* I have needed and used such pairs of config settings, even for code I'm not bringing in from node_modules.

**Comment by ChadKillingsworth** [comment]
> As far as I can tell, NODE mode is not yet aware of the es2015 package.json field used by Angular. (Perhaps I should put in a feature request for this instead...)

Please do. That's probably an easy change (though I have to go look up what it does for sure).

> I have needed and used such pairs of config settings, even for code I'm not bringing in from node_modules.

I'd really want to understand "why" you need those. I've never had to do that.

**Comment by kylecordes** [comment]
> understand "why" you need those

The use case: I am using some ES2015 module code, either as is or as build output. I want to bring it in to Closure. I don't want to locate that code right "here" at the same directory from which I'm configuring and running Closure; and I need the a module name to look like "foo" to Closure, not like "vendor/foo" nor "../some/other/directory/foo" or whatever.

**Comment by ChadKillingsworth** [comment]
But why not `/node_modules/@angular/platform-browser/^@angular/platform-browser.js`?

FYI that won't work until #2343 lands today. But that's what I would suggest you do.

**Comment by ChadKillingsworth** [comment]
It's clear that this issue is suggesting a fix caused by other workarounds. I'd rather spend time working on fixing those root causes.
