### ISSUE TITLE
NTI: cannot cast to type HTMLElement

### ISSUE THREAD

**Issue by myphysicslab** [google/closure-compiler#2427]
Using NTI (new type inference) I'm unable to get rid of the warning "Property offsetHeight never defined" on this fragment of code.

```javascript
    var docElement = /** {@type !HTMLElement}*/(document.documentElement);
    var /** null */ n = docElement;
    var documentHeight = docElement.offsetHeight;
```
The assign to n is to confirm what type the compiler infers.  Produces these errors:

```
src/test/Engine2DTestRig.js:361: WARNING - The right side in the assignment is not a subtype of the left side.
Expected : null
Found    : Element

    var /** null */ n = docElement;
                        ^^^^^^^^^^

src/test/Engine2DTestRig.js:362: WARNING - Property offsetHeight never defined on docElement of type Element
    var documentHeight = docElement.offsetHeight;
                         ^^^^^^^^^^^^^^^^^^^^^^^
```
Here is an [online example on the appspot debugger](https://closure-compiler-debugger.appspot.com/#input0%3D%2520%2520%2520%2520var%2520docElement%2520%253D%2520%252F**%2520%257B%2540type%2520!HTMLElement%257D*%252F(document.documentElement)%253B%250A%2520%2520%2520%2520var%2520%252F**%2520null%2520*%252F%2520n%2520%253D%2520docElement%253B%250A%2520%2520%2520%2520var%2520documentHeight%2520%253D%2520docElement.offsetHeight%253B%250A%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26MISSING_PROPERTIES%3D1%26CHECK_ES5_STRICT%3D1%26TRANSPILE%3D1%26CHECK_TYPES%3D1%26CHECK_TYPES_NEW_INFERENCE%3D1%26CLOSURE_PASS%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1)

Same inability to cast in OTI, but OTI doesn't provide the warning "Property offsetHeight never defined".

**Comment by Dominator008** [comment]
Did you mean `@type {!HTMLElement}`?
