### ISSUE TITLE
goog.reflect.objectProperty does not prevent inlining of methods breaking method annotations

### ISSUE THREAD

**Issue by WearyMonkey** [google/closure-compiler#2437]
[Closure Compiler Service example](https://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540compilation_level%2520ADVANCED_OPTIMIZATIONS%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250Aclass%2520Banana%2520%257B%250A%2520%2520eat()%2520%257B%250A%2520%2520%2520%2520console.log('hello')%253B%250A%2520%2520%257D%250A%257D%250A%250Aconsole.log(goog.reflect.objectProperty('eat'%252C%2520Banana.prototype))%253B%250A%250Anew%2520Banana().eat()%253B)

We are using TypeScript method decorators which transpiles:

```
class MyClass {
  @myAnnotation
  myMethod() { }
}
```

to

```
__decorate([myAnnotation], MyClass.prototype, "myMethod", null);
```

Which we further transpile into the CC compatible form:
```
__decorate([myAnnotation], MyClass.prototype, goog.reflect.objectProperty("myMethod"), null);
```

However, in some instances CC is inlining the invocation of the annotated methods, which effecively by passes the annotation.

This is breaking our usage of modern annotated driven libraries such as [MobX](https://mobx.js.org/refguide/action.html).

Can compiler treatment of `goog.reflect.objectProperty` be extended to prevent inlining?
Is there canonical way we can prevent inlining of specific methods which we can include in a transpilation?

Cheers!

**Comment by ChadKillingsworth** [comment]
> Can compiler treatment of goog.reflect.objectProperty be extended to prevent inlining?

No. That's beyond the scope of that intrinsic. 

Can you post an example of what it might look like when inlined?

**Comment by WearyMonkey** [comment]
TypeScript input (target es6):
```
function logger(target, key, descriptor) {
  const org = descriptor.value;
  descriptor.value = function() {
    console.log(`${key} ran`);
    return org.apply(this, arguments);
  };
  return descriptor;
}

class MyClass {
  @logger
  myMethod() {
    console.log('myMethod');
  }
}

new MyClass().myMethod();
```

TypeScript output and CC input (with `goog.reflect.objectPropery` injected):
```
var __decorate = (this && this.__decorate) || function (decorators, target, key, desc) {
    var c = arguments.length, r = c < 3 ? target : desc === null ? desc = Object.getOwnPropertyDescriptor(target, key) : desc, d;
    if (typeof Reflect === "object" && typeof Reflect.decorate === "function") r = Reflect.decorate(decorators, target, key, desc);
    else for (var i = decorators.length - 1; i >= 0; i--) if (d = decorators[i]) r = (c < 3 ? d(r) : c > 3 ? d(target, key, r) : d(target, key)) || r;
    return c > 3 && r && Object.defineProperty(target, key, r), r;
};
function logger(target, key, descriptor) {
    const org = descriptor.value;
    descriptor.value = function () {
        console.log(`${key} ran`);
        return org.apply(this, arguments);
    };
    return descriptor;
}
class MyClass {
    myMethod() {
        console.log('myMethod');
    }
}
__decorate([
    logger
], MyClass.prototype, goog.reflect.objectProperty("myMethod", MyClass.prototype), null);
new MyClass().myMethod();
```

[CC Advanced mode output](https://closure-compiler.appspot.com/home#code%3D%252F%252F%2520Copyright%25202017%2520Canva%2520Inc.%2520All%2520Rights%2520Reserved.%250Avar%2520__decorate%2520%253D%2520(this%2520%2526%2526%2520this.__decorate)%2520%257C%257C%2520function%2520(decorators%252C%2520target%252C%2520key%252C%2520desc)%2520%257B%250A%2520%2520%2520%2520var%2520c%2520%253D%2520arguments.length%252C%2520r%2520%253D%2520c%2520%253C%25203%2520%253F%2520target%2520%253A%2520desc%2520%253D%253D%253D%2520null%2520%253F%2520desc%2520%253D%2520Object.getOwnPropertyDescriptor(target%252C%2520key)%2520%253A%2520desc%252C%2520d%253B%250A%2520%2520%2520%2520if%2520(typeof%2520Reflect%2520%253D%253D%253D%2520%2522object%2522%2520%2526%2526%2520typeof%2520Reflect.decorate%2520%253D%253D%253D%2520%2522function%2522)%2520r%2520%253D%2520Reflect.decorate(decorators%252C%2520target%252C%2520key%252C%2520desc)%253B%250A%2520%2520%2520%2520else%2520for%2520(var%2520i%2520%253D%2520decorators.length%2520-%25201%253B%2520i%2520%253E%253D%25200%253B%2520i--)%2520if%2520(d%2520%253D%2520decorators%255Bi%255D)%2520r%2520%253D%2520(c%2520%253C%25203%2520%253F%2520d(r)%2520%253A%2520c%2520%253E%25203%2520%253F%2520d(target%252C%2520key%252C%2520r)%2520%253A%2520d(target%252C%2520key))%2520%257C%257C%2520r%253B%250A%2520%2520%2520%2520return%2520c%2520%253E%25203%2520%2526%2526%2520r%2520%2526%2526%2520Object.defineProperty(target%252C%2520key%252C%2520r)%252C%2520r%253B%250A%257D%253B%250Afunction%2520logger(target%252C%2520key%252C%2520descriptor)%2520%257B%250A%2520%2520%2520%2520const%2520org%2520%253D%2520descriptor.value%253B%250A%2520%2520%2520%2520descriptor.value%2520%253D%2520function%2520()%2520%257B%250A%2520%2520%2520%2520%2520%2520%2520%2520console.log(%2560%2524%257Bkey%257D%2520ran%2560)%253B%250A%2520%2520%2520%2520%2520%2520%2520%2520return%2520org.apply(this%252C%2520arguments)%253B%250A%2520%2520%2520%2520%257D%253B%250A%2520%2520%2520%2520return%2520descriptor%253B%250A%257D%250Aclass%2520MyClass%2520%257B%250A%2520%2520%2520%2520myMethod()%2520%257B%250A%2520%2520%2520%2520%2520%2520%2520%2520console.log('myMethod')%253B%250A%2520%2520%2520%2520%257D%250A%257D%250A__decorate(%255B%250A%2520%2520%2520%2520logger%250A%255D%252C%2520MyClass.prototype%252C%2520%2522myMethod%2522%252C%2520null)%253B%250Anew%2520MyClass().myMethod()%253B):
```
(this&&this.b||function(f,c,a,e){var g=arguments.length,d=3>g?c:null===e?e=Object.getOwnPropertyDescriptor(c,a):e,h;if("object"===typeof Reflect&&"function"===typeof Reflect.a)d=Reflect.a(f,c,a,e);else for(var k=f.length-1;0<=k;k--)if(h=f[k])d=(3>g?h(d):3<g?h(c,a,d):h(c,a))||d;return 3<g&&d&&Object.defineProperty(c,a,d),d})([function(f,c,a){var e=a.value;a.value=function(){console.log(c+" ran");return e.apply(this,arguments)};return a}],function(){}.prototype,"myMethod",null);console.log("myMethod");
```

From the above output, you can see `new MyClass().myMethod();` was inlined to: `console.log("myMethod");` which would not invoke the `logger` decoration as expected.

**Comment by ChadKillingsworth** [comment]
This is a problem with property reflection - the method call is hidden from the compiler. Polymer suffers from the same problem.

What's needed to block this is a sink value. See https://google.github.io/closure-library/api/goog.reflect.html#sinkValue

Ideally tsickle would be updated to output this for you.

[Example](http://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540compilation_level%2520ADVANCED_OPTIMIZATIONS%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%2540formatting%2520pretty_print%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%252F**%250A%2520*%2520To%2520assert%2520to%2520the%2520compiler%2520that%2520an%2520operation%2520is%2520needed%2520when%2520it%2520would%250A%2520*%2520otherwise%2520be%2520stripped.%2520For%2520example%253A%250A%2520*%2520%253Ccode%253E%250A%2520*%2520%2520%2520%2520%2520%252F%252F%2520Force%2520a%2520layout%250A%2520*%2520%2520%2520%2520%2520goog.reflect.sinkValue(dialog.offsetHeight)%253B%250A%2520*%2520%253C%252Fcode%253E%250A%2520*%2520%2540param%2520%257BT%257D%2520x%250A%2520*%2520%2540return%2520%257BT%257D%250A%2520*%2520%2540template%2520T%250A%2520*%252F%250Afunction%2520sinkValue(x)%2520%257B%250A%2520%2520sinkValue%255B'%2520'%255D(x)%253B%250A%2520%2520return%2520x%253B%250A%257D%253B%250A%250A%250A%252F**%250A%2520*%2520The%2520compiler%2520should%2520optimize%2520this%2520function%2520away%2520iff%2520no%2520one%2520ever%2520uses%250A%2520*%2520goog.reflect.sinkValue.%250A%2520*%252F%250AsinkValue%255B'%2520'%255D%2520%253D%2520input%2520%253D%253E%2520input%253B%250A%250A%250Avar%2520__decorate%2520%253D%2520(this%2520%2526%2526%2520this.__decorate)%2520%257C%257C%2520function%2520(decorators%252C%2520target%252C%2520key%252C%2520desc)%2520%257B%250A%2520%2520%2520%2520var%2520c%2520%253D%2520arguments.length%252C%2520r%2520%253D%2520c%2520%253C%25203%2520%253F%2520target%2520%253A%2520desc%2520%253D%253D%253D%2520null%2520%253F%2520desc%2520%253D%2520Object.getOwnPropertyDescriptor(target%252C%2520key)%2520%253A%2520desc%252C%2520d%253B%250A%2520%2520%2520%2520if%2520(typeof%2520Reflect%2520%253D%253D%253D%2520%2522object%2522%2520%2526%2526%2520typeof%2520Reflect.decorate%2520%253D%253D%253D%2520%2522function%2522)%2520r%2520%253D%2520Reflect.decorate(decorators%252C%2520target%252C%2520key%252C%2520desc)%253B%250A%2520%2520%2520%2520else%2520for%2520(var%2520i%2520%253D%2520decorators.length%2520-%25201%253B%2520i%2520%253E%253D%25200%253B%2520i--)%2520if%2520(d%2520%253D%2520decorators%255Bi%255D)%2520r%2520%253D%2520(c%2520%253C%25203%2520%253F%2520d(r)%2520%253A%2520c%2520%253E%25203%2520%253F%2520d(target%252C%2520key%252C%2520r)%2520%253A%2520d(target%252C%2520key))%2520%257C%257C%2520r%253B%250A%2520%2520%2520%2520return%2520c%2520%253E%25203%2520%2526%2526%2520r%2520%2526%2526%2520Object.defineProperty(target%252C%2520key%252C%2520r)%252C%2520r%253B%250A%257D%253B%250Afunction%2520logger(target%252C%2520key%252C%2520descriptor)%2520%257B%250A%2520%2520%2520%2520const%2520org%2520%253D%2520descriptor.value%253B%250A%2520%2520%2520%2520descriptor.value%2520%253D%2520function%2520()%2520%257B%250A%2520%2520%2520%2520%2520%2520%2520%2520console.log(%2560%2524%257Bkey%257D%2520ran%2560)%253B%250A%2520%2520%2520%2520%2520%2520%2520%2520return%2520org.apply(this%252C%2520arguments)%253B%250A%2520%2520%2520%2520%257D%253B%250A%2520%2520%2520%2520return%2520descriptor%253B%250A%257D%250Aclass%2520MyClass%2520%257B%250A%2520%2520%2520%2520myMethod()%2520%257B%250A%2520%2520%2520%2520%2520%2520%2520%2520console.log('myMethod')%253B%250A%2520%2520%2520%2520%257D%250A%257D%250A__decorate(%255B%250A%2520%2520%2520%2520logger%250A%255D%252C%2520MyClass.prototype%252C%2520goog.reflect.objectProperty(%2522myMethod%2522%252C%2520MyClass.prototype)%252C%2520null)%253B%250AsinkValue(MyClass.prototype.myMethod)%253B%250Anew%2520MyClass().myMethod()%253B%250A%250A)

**Comment by WearyMonkey** [comment]
Great thanks, we'll integrate `sinkValue`.

**Comment by ChadKillingsworth** [comment]
@WearyMonkey After thinking on this overnight - this may not be what you want. Adding the sink value will block inlining, but it will also block dead code elimination.

I don't know of a way to block inlining but not block dead code elimination. @concavelenz might have ideas though.
