### ISSUE TITLE
"Variable first declared in..." is not a very helpful error message

### ISSUE THREAD

**Issue by trinarytree** [google/closure-compiler#2454]
I had a variable declared > 1 time and it yielded this error message:
```
ERROR - Variable d3 first declared in third_party/javascript/d3/v3/externs.js
goog.provide('d3');
              ^
```
That's not very helpful.  It doesn't even sound like an error.  It sounds like some benign condition,
like, "ERROR - Nice pants."

To figure out what this actually meant, I grepped for what generated the error message
and noticed that it was in a constant in `VarCheck.java` called `VAR_MULTIPLY_DECLARED_ERROR`.

Could the error message be improved?  E.g.
```
ERROR - Variable d3 declared more than once.  First occurrence:
...
```

**Comment by hlolli** [comment]
Lol, I also encountered this. I have in extern file `var a = {};` and in code `var a = a || {};` and the compiler is telling me that a is first defined in the formentioned extern file. This is not a code that I wrote and this behavior differs between versions. Is there any way to turn this error off or bypass it?
