### ISSUE TITLE
April 2017 open source release

### ISSUE THREAD

**Issue by brad4d** [google/closure-compiler#2456]
This is a progress tracking issue for the April 2017 open source release.
It will be based on the r20170423 internal release.

**Comment by brad4d** [comment]
@ChadKillingsworth 
I'm getting started on this today.
I believe you wanted to coordinate some changes to the google/closure-compiler-npm project.

**Comment by ChadKillingsworth** [comment]
@brad4d Sure do. Just ping me when the maven version is pushed and I'll handle the java-npm one. I've got to make source changes in that repo at the same time as the new compiler version is pushed to account for the new behavior of the `--js_module_root` flag.

**Comment by anmonteiro** [comment]
@ChadKillingsworth can you point me to the PR that changed `--js_module_root`? We may need to account for that change in ClojureScript

**Comment by ChadKillingsworth** [comment]
@anmonteiro It's #2343. However, you shouldn't have to make changes. This PR allows you to use absolute module paths anchored to module roots - the way most people expect it to work. Before that change they just didn't resolve.

**Comment by anmonteiro** [comment]
Thanks! And you're probably right, by the looks of it we don't need to make changes

**Comment by brad4d** [comment]
Hit a snag.
PeepholeFoldConstantsTest fails because we added a constructor, but forgot to make it public.
Gonna need to fix that.

**Comment by brad4d** [comment]
We've submitted a fix internally.
I've cherrypicked it onto the maven-v20170423 branch and successfully completed `mvn release:prepare`.

**Comment by brad4d** [comment]
starting `mvn release:perform` now.

**Comment by brad4d** [comment]
I've completed the release at oss.sonatype.org.
According to our release instructions:

> It may take about 2 hours for the binaries to be available. They will first become available here
> http://repo1.maven.org/maven2/com/google/javascript/closure-compiler/
> And once the search index is updated, here
> http://search.maven.org/#search%7Cga%7C1%7Ca%3A%22closure-compiler%22
>

**Comment by ChadKillingsworth** [comment]
Npm is published - thanks.

**Comment by anmonteiro** [comment]
@brad4d it's showing up just fine in Maven, but shouldn't https://dl.google.com/closure-compiler/compiler-latest.zip serve the most recent release too?

Is this an oversight or am I expecting things to happen to fast?

**Comment by MatrixFrog** [comment]
There's another manual step to update dl.google.com so it will probably happen tomorrow.

**Comment by brad4d** [comment]
@MatrixFrog is correct.
I was waiting for the maven update and went on to other things.
I'm now waiting for submission of an internal change, then I'll be able to upload the binaries to dl.google.com.

**Comment by brad4d** [comment]
I've just uploaded the binaries to dl.google.com

**Comment by brad4d** [comment]
FYI, there are still items on my release checklist that I'm working through.
I won't close this issue until I send the release announcement.

**Comment by brad4d** [comment]
Just sent the release announcement.
