### ISSUE TITLE
Constructor annotation on a label raises "must be initialized" warning

### ISSUE THREAD

**Issue by blickly** [google/closure-compiler#246]
This issue was imported from Closure Compiler's previous home at http://closure-compiler.googlecode.com

The original discussion is archived at:
http://blickly.github.io/closure-compiler-issues/#1022

**Comment by Dominator008** [comment]
This seems to have been fixed.
```js
/** @const */
var foo = {
    /** @constructor */
    bar: function() { console.log('new bar'); }
};

new foo.bar();
```
compiles with no warnings.
