### ISSUE TITLE
NTI: Object passed to a function wherein a value is referenced through string notation produces type warnings while dot notation does not

### ISSUE THREAD

**Issue by smaren** [google/closure-compiler#2460]
Using new type inference, if an object is passed to a function, type checking only works with string notation whereas dot notation does not type check correctly.
Line 12 in the following example should produce a type error, but it does not.

http://closure-compiler-debugger.appspot.com/#input0%3D%252F**%250A%2520*%2520%2540param%2520%257Bstring%257D%2520string%250A%2520*%252F%250Avar%2520takesString%2520%253D%2520function(string)%2520%257B%250A%2520%2520alert(string)%250A%257D%253B%250A%250A%252F**%250A%2520*%2520%2540param%2520%257B!Object%253Cstring%252C%2520number%253E%257D%2520map%250A%2520*%252F%250Avar%2520takesMap%2520%253D%2520function(map)%2520%257B%250A%2520%2520takesString(map.n)%253B%2520%252F%252F%2520No%2520warning%250A%2520%2520takesString(map%255B'n'%255D)%253B%2520%252F%252F%2520Type%2520warning%250A%257D%253B%250A%250A%252F**%250A%2520*%2520%2540type%2520%257B!Object%253Cstring%252C%2520number%253E%257D%250A%2520*%252F%250Avar%2520o%2520%253D%2520%257Bn%253A%25201%257D%253B%250A%250AtakesMap(o)%253B%250AtakesString(o.n)%253B%2520%252F%252F%2520Type%2520warning%250AtakesString(o%255B'n'%255D)%253B%2520%252F%252F%2520Type%2520warning%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26TRANSPILE%3D1%26CHECK_TYPES_NEW_INFERENCE%3D1%26CLOSURE_PASS%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1

**Comment by dimvar** [comment]
This is intentional. The parameterized `Object` type only checks the "map like" property accesses. Dot accesses are assumed to refer to separately defined properties.

A more convincing example. If we have a class that implements `IArrayLike<Foo>`, we still want to be able to define other properties of that class, which we access with dot, and are not `Foo`s.
