### ISSUE TITLE
Generic type not recognized in rest parameter annotation (OTI only)

### ISSUE THREAD

**Issue by butterflyhug** [google/closure-compiler#2464]
With advanced optimizations turned on and NTI turned off, the compiler sometimes isn't recognizing a generic type used as part of a rest parameter's annotation.  Example code that produces the "bad type annotation" warning:

```js
/**
 * @param {...(!Set<T>)} sets
 * @return {!Set<T>}
 * @template T
 */
function union(...sets) {
  return new Set();
}
```

[Demo](http://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540compilation_level%2520ADVANCED_OPTIMIZATIONS%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250A%250A%252F**%250A%2520*%2520%2540param%2520%257B...(!Set%253CT%253E)%257D%2520sets%250A%2520*%2520%2540return%2520%257B!Set%253CT%253E%257D%250A%2520*%2520%2540template%2520T%250A%2520*%252F%250Afunction%2520union(...sets)%2520%257B%250A%2520%2520return%2520new%2520Set()%253B%250A%257D) -- change the optimization level to "advanced" and click "compile" to see the warning.

**Comment by brad4d** [comment]
Reproduced this & confirmed that NTI does not have generate the warning.
At this point, I don't believe we're fixing problems that are fixed in NTI.
