### ISSUE TITLE
whitelist_regexp for conformance rules not working

### ISSUE THREAD

**Issue by myphysicslab** [google/closure-compiler#2466]
I'm unable to get the `whitelist_regexp` for conformance rules to work.

https://github.com/google/closure-compiler/wiki/JS-Conformance-Framework states:

> The whitelist_regexp entry is an Java RegExp pattern and files that match the pattern are allowed to violate the requirement.

I've tried all the variations I can think of.  I want to whitelist files whose name ends with `_test.js`.

This should work but does not:

    whitelist_regexp: '.*_test.js'

or to make the "dot" be an explicit dot instead of a regexp dot:

    whitelist_regexp: '.*_test\\.js'

Here is my complete `conformance_config.textproto` file:

```
requirement: {
  type: CUSTOM
  error_message: 'Possible dereference of null value.'
  java_class: 'com.google.javascript.jscomp.ConformanceRules$BanNullDeref'
}

requirement: {
  type: CUSTOM
  error_message: 'Unresolved type which is referenced and known via'
    'forward declarations but not included in the compilation jobs dependencies'
  java_class: 'com.google.javascript.jscomp.ConformanceRules$BanUnresolvedType'
}

requirement: {
  type: CUSTOM
  error_message: 'Global variables must be goog.provided or whitelisted'
  java_class: 'com.google.javascript.jscomp.ConformanceRules$BanGlobalVars'
  whitelist_regexp: '.*_test\\.js'
}

requirement: {
  type: CUSTOM
  error_message: '“this” value is typed as “unknown”'
  java_class: 'com.google.javascript.jscomp.ConformanceRules$BanUnknownThis'
}

requirement: {
  type: CUSTOM
  error_message: 'property reference is typed as “unknown”'
  java_class: 'com.google.javascript.jscomp.ConformanceRules$BanUnknownTypedClassPropsReferences'
}
```

Luckily I can work around this problem for now.  I build unit tests with a special compile command and have a separate `test_conformance_config.textproto` file that leaves out the `BanGlobalVars` rule.

**Comment by brad4d** [comment]
@myphysicslab 
I tried to reproduce your problem, but everything worked as expected for me.

```
==== build.sh ====
#!/bin/bash
closure-compiler \
  --compilation_level ADVANCED \
  --conformance_configs conformance-configs.txt \
  --js main.js \
  --js main_test.js

==== conformance-configs.txt ====
requirement: {
  type: CUSTOM
  error_message: 'Global variables must be goog.provided or whitelisted'
  java_class: 'com.google.javascript.jscomp.ConformanceRules$BanGlobalVars'
  whitelist_regexp: '.*_test\\.js'
}

==== main.js ====
var x = 5;

==== main_test.js ====
var y = 5;
```

As expected, I get the global variable warning for `main.js` but not for `main_test.js`.

**Comment by myphysicslab** [comment]
confirmed: it's working for me now as well.
