### ISSUE TITLE
The speed of compiler

### ISSUE THREAD

**Issue by photopea** [google/closure-compiler#2467]
I am using Closure Compiler to obfuscate my JS code for a long time. Since I don't want to install the whole Java environment just because of this app, I compile my code by sending it to https://closure-compiler.appspot.com/compile  through HTTP. 

My code has about 1.2 MB (40 000 lines), I use Advanced compilation, it takes almost a minute to compile.

Is this an expected time in my case? Would it be faster, if I was running it on my own computer? Are there any ways to make it faster (e.g. I don't care about browsers, that are more than a year old). My goal is just to change the names (of variables, functions ...), I don't need changing the syntax (but I don't mind it).

**Comment by ChadKillingsworth** [comment]
That sounds about right. However we don't recommend using the web service for that size of code base. You can try the [experimental JavaScript version](https://github.com/google/closure-compiler-js).

**Comment by photopea** [comment]
Thanks. Are there any flags, that would disable the optimization and just perform the renaming? Would it be faster then?

**Comment by ChadKillingsworth** [comment]
You can set `--use_types_for_optimization=false`, but you'll also get less renaming.
