### ISSUE TITLE
const methods -> JSC_REDECLARED_VARIABLE_ERROR: Illegal redeclared variable

### ISSUE THREAD

**Issue by Brutusn** [google/closure-compiler#2471]
I am not sure if this is a bug, or "by design". 

Today we found an issue compiling our js code. Somewhere we had a global "const methods". During compilation it throws an error:

> JSC_REDECLARED_VARIABLE_ERROR: Illegal redeclared variable: methods at line 2 character 6
> const methods = [
>       ^

The strange thing is that both _const_ and _let_ throw the error, but _var_ doesn't.

These are the flags we use (cmd) during compilation:

>--warning_level QUIET \
>--language_in ECMASCRIPT6_STRICT \
>--language_out ECMASCRIPT5_STRICT \

Check the link to see the problem in action.
https://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540compilation_level%2520SIMPLE_OPTIMIZATIONS%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250A%252F%252F%2520ADD%2520YOUR%2520CODE%2520HERE%250Aconst%2520methods%2520%253D%2520%255B%250A%2520%2520%2520%2520%2520%2520%2520%2520%257B%250A%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520type%253A%2520%255B%2522--help%2522%252C%2520%2522-h%2522%255D%252C%250A%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520func%253A%2520()%2520%253D%253E%2520%257B%250A%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520console.log(%2522Something%2522)%253B%250A%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%257D%250A%2520%2520%2520%2520%2520%2520%2520%2520%257D%250A%2520%2520%2520%2520%255D%253B%250A%250Aif%2520(methods.includes(%2522-h%2522))%2520%257B%250A%2520%2520%2520%2520methods.func()%253B%250A%257D%250A%250A

**Comment by brad4d** [comment]
You're running afoul of this externs definition.
https://github.com/google/closure-compiler/blob/master/externs/browser/deprecated.js#L48

You don't get an error for `var` because the language allows redundant `var` statements.
