### ISSUE TITLE
inject_libraries options not working

### ISSUE THREAD

**Issue by Zeka13** [google/closure-compiler#2473]
**online** version https://closure-compiler.appspot.com/
**and offilne** https://dl.google.com/closure-compiler/compiler-latest.zip

**Works differently** for my code, because **"inject_libraries" totally broken** (default should be true, but now its false)

```
java -jar closure-compiler.jar --js deploy_build/Vigo.js --js_output_file Out.js --inject_libraries true
ERROR - Cannot read: true

1 error(s), 0 warning(s)
```

Possible reason:
no "handler = BooleanOptionHandler.class"
there https://github.com/google/closure-compiler/blob/master/src/com/google/javascript/jscomp/CommandLineRunner.java
(line 690)

**Comment by MatrixFrog** [comment]
The defaults for the online version do not necessarily match the defaults in the command line version. The online version is much more limited in what options you can set, though you can try closure-compiler-debugger.appspot.com which is somewhat more configurable.

**Comment by Zeka13** [comment]
@MatrixFrog it **works** good in online version, but there is a **bug (not working) in offline verison**

ERROR - Cannot read: true with `--inject_libraries true`

**Comment by MatrixFrog** [comment]
Gotcha. Yes all boolean flags should have our BooleanOptionHandler. I'll add it in.

**Comment by ChadKillingsworth** [comment]
@MatrixFrog Do you have any ideas on how we might enforce that? Like a test that fails if there is a boolean option without it?

**Comment by MatrixFrog** [comment]
We might be able to write an ErrorProne plugin for that actually.

**Comment by MatrixFrog** [comment]
Or maybe it'd be simpler to just write a test that uses reflect to find all fields of type boolean (or Boolean, which we have one of for some reason) that are annotated with `@Option`.
