### ISSUE TITLE
Angular Externs for $http.Config.transformRequest and $http.Config.transformResponse incorrect

### ISSUE THREAD

**Issue by DRayX** [google/closure-compiler#2476]
All recent versions of the angular externs lists the signature for transformRequest as `function(?, Object): ?` and transformResponse as `function(?, Object, Object): ?` (or undefined or arrays of these functions).  This doesn't match the actual signature of the transformRequest and transformResponse functions though.  The second argument to both is a header-getter that has type `function(string=): (?string | !Object<string>)` (if provided an argument it returns only the requested header, when no argument is provided it returns an object with all the headers) and the third argument to transformResponse is a `number` (this is a fairly major oversight).

I suggest adding a new typedef
~~~
/** @typedef {function(string=): (?string | !Object<string>)} */
angular.$http.HeadersGetter;
~~~
and then updating the type for transformRequest and transformResponse to
~~~
/**
 * @type {
 *   (undefined|
 *    function(?, angular.$http.HeadersGetter):?|
 *    Array<function(?, angular.$http.HeadersGetter):?>)
 * }
 */
angular.$http.Config.prototype.transformRequest;

/**
 * @type {
 *   (undefined|
 *    function(?, angular.$http.HeadersGetter, number):?|
 *    Array<function(?, angular.$http.HeadersGetter, number):?>)
 * }
 */
angular.$http.Config.prototype.transformResponse;
~~~
but there may be a better way to handle the HeadersGetter thing.

**Comment by brad4d** [comment]
Since this change tightens type information it's both a good thing to do and potentially a lot of work to land.
I'm seeing ~1000 uses of these two methods in Google code that may need to be fixed in order to land this change.

@jelbourn, would anyone on the angular team be interested in making this change?

**Comment by jelbourn** [comment]
Cc @mprobst since I'm on vacation until next week

**Comment by mprobst** [comment]
@dpurp is our externs-wranging hero as of late. David, do you think this is feasible?

**Comment by dpurp** [comment]
Sorry on the delay, I can take this up on Monday.

**Comment by dpurp** [comment]
Update: I have a fix in review, waiting on approval from a few teams for the change to fix their type declarations.

**Comment by dpurp** [comment]
FIXED by https://github.com/google/closure-compiler/commit/21c7547e51d3ff3996711b0702284567acf7d033
