### ISSUE TITLE
Guarded type promotion is failing in ES6 classes

### ISSUE THREAD

**Issue by simonsarris** [google/closure-compiler#2484]
Here is some simple JavaScript that has two classes, with B extending A.

```JavaScript
class A {
  constructor() {
    this.aprop = 5;
  }

  doThing() {
    if (this instanceof B) {
      console.log("I'm an instance of B " + this.bprop);
    } else {
      console.log("I'm an instance of A");
    }
  }
} // end class A

class B extends A {
  constructor() {
    super();
    this.bprop = 100;
  }
} // end class B

window['A'] = A;
window['B'] = B;
```

Historically this if statement would make the type effectively `B`:

```JavaScript
    if (this instanceof B) {
      console.log("I'm an instance of B " + this.bprop);
    }
```

But instead it results in an error.

```
C:\mini> java -jar closure-compiler.jar --js test.js --compilation_level ADVANCED_OPTIMIZATIONS
test.js:9: WARNING - Property bprop never defined on A
      console.log("I'm an instance of B " + this.bprop);
                                                 ^^^^^
```

**If I rewrite this to not use ES6 classes, it works just fine:**

```JavaScript
// This works:
/**
 * @constructor
 */
function A() {
   this.aprop = 5;
}

A.prototype.doThing = function() {
  if (this instanceof B) {
    console.log("I'm an instance of B " + this.bprop);
  } else {
    console.log("I'm an instance of A");
  }
}


/**
 * @constructor
 * @extends {A}
 */
function B() {

    A.constructor.call(this);
    this.bprop = 100;

}

window['A'] = A;
window['B'] = B;
```

Sorry if this is a known issue.

**Comment by MatrixFrog** [comment]
This is because `class`es are implicitly `@struct`. You can get the non-struct behavior by annotating them with `@unrestricted`

**Comment by simonsarris** [comment]
Oh dear, I see.

That seems odd to me for exactly the use case above, but I imagine the team has have thought much harder than I about this design decision, so I'll close this issue.

**Comment by MatrixFrog** [comment]
The new type inference might be smarter about narrowing the type after an `instanceof`, I'm not sure.

**Comment by dimvar** [comment]
The new type inference indeed narrows the type correctly. @simonsarris if you want to use it for your project, take a look at: https://github.com/google/closure-compiler/wiki/Using-NTI-(new-type-inference)

**Comment by simonsarris** [comment]
Very interesting, thanks @dimvar. Unfortunately I'm trying to convert a [large project](http://gojs.net/latest/index.html) to TS, then pass it on to closure so I'm working through a small (less than 80 now) number of warnings, and enabling NTI explodes the number to 3600 warnings :(

I'll keep an eye on it and will probably try to use it in the future, though.

p.s. The Closure Compiler is the most underrated Google project.

**Comment by dimvar** [comment]
Then you may want to try NTI in compatibility mode, with the flag `--jscomp_off=newCheckTypesExtraChecks`.

**Comment by simonsarris** [comment]
I see. Then it's a mere 1660 warnings, but most are related in some way so I am optimistic. I will investigate them in the near future.
