### ISSUE TITLE
@export does not substitute the functionality of @expose, yet deprecates it

### ISSUE THREAD

**Issue by simonsarris** [google/closure-compiler#2486]
Again very sorry if this has been discussed to death, but its not in the annotation docs as far as I can tell.

One can imagine two ways of not renaming a symbol (in this case, a class method). One is that the original name is kept as an alias, and the other is that all internal uses of that symbol are not renamed. The former is possible with `@export`, the latter with `@expose`. The problem is that `@expose` is deprecated.

Why is it deprecated, when `@export` (or `@nocollapse` for that matter) do not enable the same functionality?

This is very desirable sometimes when making a library:

```JavaScript
Class A {
 ...

  /**
    * @export
    * ...
    */
  requestUpdate() {
    ...
  }
```

```JavaScript
// Closure ouput:
R.prototype.Xb = function() {
  ...
};
R.prototype.requestUpdate = R.prototype.Xb;

// Then everywhere closure uses .Xb
```

But other times, we want the method name to never be renamed anywhere throughout the code. That way, users can override the method if they need to:

```JavaScript
// In user code, maybe some methods need to be overridable:
myClassInstance.requestUpdate = function() { /* do something different */ }
```

And have the library internally use this override.

I can achieve this only by using the `@expose` symbol, but that is deprecated, but nothing in the docs claims to replace its functionality. Is this an oversight or intentional?

Use case: Developing library that gets run through advanced compilations. Seemingly need both `@export` and `@expose` functionality.

**Comment by ChadKillingsworth** [comment]
`@expose` was originally added to do what `@nocollapse` does today. A side effect of the implementation was that it blocked renaming (and a lot of typechecking). The side effect quickly became the main use case.

For these reasons it was deprecated. However, we don't plan on removing it until there is a suitable replacement (and nobody is working on that right now).

Also, as you mentioned there is no consistent idea on what an export should do. Should it alias or simply block renaming? Different projects make different choices.

**Comment by simonsarris** [comment]
Thanks for the clarification.

I'm gonna close this, but maybe the annotation documentation should still mention the @expose flag if there's nothing else to duplicate its functionality at the moment.
