### ISSUE TITLE
StringIndexOutOfBoundsException when \0 is last character of a template string

### ISSUE THREAD

**Issue by erwinmombay** [google/closure-compiler#2488]
see:
http://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%2540compilation_level%2520SIMPLE_OPTIMIZATIONS%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250Avar%2520test%2520%253D%2520%2560%250Ahello%255C0%2560%253B%250Aconsole.log(test)%253B

**Comment by MatrixFrog** [comment]
I can't reproduce this now. Maybe it got fixed at some point...

**Comment by MatrixFrog** [comment]
Nevermind I was testing it wrong.
