### ISSUE TITLE
Reduce for loops by 2-3 bytes each in many cases

### ISSUE THREAD

**Issue by blickly** [google/closure-compiler#249]
This issue was imported from Closure Compiler's previous home at http://closure-compiler.googlecode.com

The original discussion is archived at:
http://blickly.github.io/closure-compiler-issues/#992

**Comment by Dominator008** [comment]
Quoting @acleung:

> It's puzzling sometimes.

I have tried on a few occasions to do something like this. It has minor improvement on unzipped size and in almost all cases hurts gzipped size.

I wish I can explain to you why.....
