### ISSUE TITLE
Failed test: PeepholeFoldConstantsTest

### ISSUE THREAD

**Issue by aloiret** [google/closure-compiler#2491]
Hello,

The commit 8e0f742c62429141f1d3d1387197403f3a960c87 leads to the following failing test:

Failed tests: 
  TestSuite$1.warning Class com.google.javascript.jscomp.PeepholeFoldConstantsTest has no public constructor TestCase(String name) or TestCase()

This makes the build from source failing on Debian 9 (testing) with Java version :
openjdk version "1.8.0_131"
OpenJDK Runtime Environment (build 1.8.0_131-8u131-b11-1-b11)
OpenJDK 64-Bit Server VM (build 25.131-b11, mixed mode)

Thank you.

**Comment by MatrixFrog** [comment]
Should be fixed by 3b7ac226cca37b72568eb7054dd67e1e7ea0e263
