### ISSUE TITLE
[NTI] Expecting too-specific a type for overridden interface methods

### ISSUE THREAD

**Issue by shicks** [google/closure-compiler#2497]
[Repro][1]

I have the following:
```js
/** @record */
class Record {
  method()
}

/** @interface @extends {Record} */
class SubInterface {}

/** @implements {SubInterface} */
class Base {
  /** @override @this {!SubInterface} */
  method()
}

/** @implements {SubInterface} */
class Concrete {}
Concrete.prototype.method = Base.prototype.method
```

NTI complains that
```
WARNING - The right side in the assignment is not a subtype of the left side.
Expected : function(this:Record):?
Found    : function(this:SubInterface):?

Concrete.prototype.method = Base.prototype.method;
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

This type error is reasonable, due to contravariance of `this`, but it's being unreasonable to expect `this` to be the record here.  If I were to override `method` in the class body, it would implicitly have a `this` of `Concrete`.

[1]: https://closure-compiler-debugger.appspot.com/#input0%3D%252F**%2520%2540record%2520*%252F%250Aclass%2520Record%2520%257B%250A%2520%2520method()%2520%257B%257D%250A%257D%250A%250A%252F**%2520%2540interface%250A%2520%2520%2520%2520%2540extends%2520%257BRecord%257D%2520*%252F%250Aclass%2520SubInterface%2520%257B%257D%250A%250A%252F**%2520%2540implements%2520%257BSubInterface%257D%2520*%252F%250Aclass%2520Base%2520%257B%250A%2520%2520%252F**%2520%2540override%250A%2520%2520%2520%2520%2520%2520%2540this%2520%257B!SubInterface%257D%2520*%252F%250A%2520%2520method()%2520%257B%257D%250A%257D%250A%250A%252F**%2520%2540implements%2520%257BSubInterface%257D%2520*%252F%250Aclass%2520Concrete%2520%257B%257D%250A%250AConcrete.prototype.method%2520%253D%2520Base.prototype.method%253B%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26MISSING_PROPERTIES%3D1%26TRANSPILE%3D1%26CHECK_TYPES%3D1%26CHECK_TYPES_NEW_INFERENCE%3D1%26CLOSURE_PASS%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1

**Comment by shicks** [comment]
FWIW, making `Record` a nominal `@interface` doesn't resolve the issue.

**Comment by shicks** [comment]
This issue is still open, and should probably be prioritized.  To be clear, #2500 provides an even simpler repro case, which I've adapted [here]:

```js
/** @record */
class Foo {
  // /** @this {?} */
  foo() {}
}

// /** @implements {Foo} */
class Bar {
  // /** @this {!Foo} */
  foo() {}
}

const /** !Foo */ foo = new Bar();

foo.foo.call('expected to fail');
```

Uncommenting any of the three annotations in the above will cause the assignment to `foo` to succeed.  The first one (declaring `@this {?}`) has the unintended side effect of suppressing the expected warning when calling on the interface with a random non-`Foo`.

I think the underlying issue is that NTI is trying to prove that the class implements the interface without assuming it from the start.  Given that explicitly tagging the class as `@implements {Foo}` makes NTI happy, my guess is that in that case `Bar` is already set as a subtype of `Foo` and then we just check whether that's true or not, and it is since all the methods work out.  But without that hint, it's too pessimistic when it sees `this:Foo` vs `this:Bar` and since it hasn't yet proved it *is* a subtype, it thinks that it isn't.

I wonder if we could simply pre-seed the `SubtypeCache` and this would just work?

[here]: https://closure-compiler-debugger.appspot.com/#input0%3D%252F**%2520%2540record%2520*%252F%250Aclass%2520Foo%2520%257B%250A%2520%2520%252F%252F%2520%252F**%2520%2540this%2520%257B%253F%257D%2520*%252F%250A%2520%2520foo()%2520%257B%257D%250A%257D%250A%250A%252F%252F%2520%252F**%2520%2540implements%2520%257BFoo%257D%2520*%252F%250Aclass%2520Bar%2520%257B%250A%2520%2520%252F%252F%2520%252F**%2520%2540this%2520%257B!Foo%257D%2520*%252F%250A%2520%2520foo()%2520%257B%257D%250A%257D%250A%250Aconst%2520%252F**%2520!Foo%2520*%252F%2520foo%2520%253D%2520new%2520Bar()%253B%250A%250Afoo.foo.call('expected%2520to%2520fail')%253B%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26MISSING_PROPERTIES%3D1%26TRANSPILE%3D1%26CHECK_TYPES%3D1%26CHECK_TYPES_NEW_INFERENCE%3D1%26CLOSURE_PASS%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1

**Comment by dimvar** [comment]
Sounds good, i'll prioritize this. (Note to self: ES5 repro below.)

````
/** @record */
var Foo = function() {};

Foo.prototype.foo = function() {};

/** @constructor */
var Bar = function() {};

Bar.prototype.foo = function() {};

/** @type {!Foo} */
var x = new Bar;
````

**Comment by shicks** [comment]
I guess my issue with unknown is more subtle - in particular, the following should be an error (since `Bar.prototype.foo` likely depends on implementation details of `Bar`) but I don't see a clean and ergonomic way to catch it, short of being a lot stricter about enforcing this-contravariance on uses of `call`/`apply`.

```js
/** @record */ class Foo { foo() {} }

class Bar { foo() {} }
class Baz { foo() {} }

const /** !Foo */ foo = new Bar();
foo.foo.call(new Baz());
```
