### ISSUE TITLE
FlowSensitiveInlineVariables backed off on string concatenation

### ISSUE THREAD

**Issue by blickly** [google/closure-compiler#250]
This issue was imported from Closure Compiler's previous home at http://closure-compiler.googlecode.com

The original discussion is archived at:
http://blickly.github.io/closure-compiler-issues/#993

**Comment by Dominator008** [comment]
Closed by https://github.com/google/closure-compiler/commit/58d892bbddb92bc64e7fbf42494000560b4bc0c3.
