### ISSUE TITLE
Invalid "Missing return statement" warning

### ISSUE THREAD

**Issue by vobruba-martin** [google/closure-compiler#2501]
```javascript
/** @return {number} */
function x() {
	return 0;
	alert('x');
};
```
> WARNING - Missing return statement. Function expected to return number.
> function x() {
> ^^^^^^^^^^^^^^
> 
> WARNING - unreachable code
> 	alert('x');
> 	^^^^^^^^^^^

Or even

```javascript
/** @return {number} */
function x() {
	return 0;;
};
```
> WARNING - Missing return statement. Function expected to return number.
> function x() {
> ^^^^^^^^^^^^^^

**Comment by dimvar** [comment]
I'm guessing this is with NTI? Detecting dead code after returns makes the missing-return check much more complicated than it needs to be. The old missing-return check has a bunch of special-case code for this. I don't think it's worth the complexity to support the bad code pattern of dead code after a return, so we didn't support this in NTI.
