### ISSUE TITLE
async/iterator polyfill does not support throw/reject with value undefined

### ISSUE THREAD

**Issue by mitchellwills** [google/closure-compiler#2503]
The iterator polyfill does not correctly handle if undefined is throws/the value rejected in a promise. The polyfill continues on as if no value was thrown.

For example the following code should print 2, 3 but prints 1, 3 after being compiled using closure compiler.

```
async function hello() {
  try {
    await Promise.reject(undefined);
    console.log('1');
  } catch (e) {
    console.log('2');
  }
  console.log('3');
}
hello()
```

http://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%2540language%2520ECMASCRIPT8%250A%252F%252F%2520%2540formatting%2520pretty_print%250A%252F%252F%2520%2540compilation_level%2520SIMPLE_OPTIMIZATIONS%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250A%250Aasync%2520function%2520hello()%2520%257B%250A%2520%2520try%2520%257B%250A%2520%2520%2520%2520await%2520Promise.reject(undefined)%253B%250A%2520%2520%2520%2520console.log('1')%253B%250A%2520%2520%257D%2520catch%2520(e)%2520%257B%250A%2520%2520%2520%2520console.log('2')%253B%250A%2520%2520%257D%250A%2520%2520console.log('3')%253B%250A%257D%250A%250Ahello()

**Comment by brad4d** [comment]
I believe this is actually due to an error in the underlying generator transpilation.

**Comment by brad4d** [comment]
fix is in the works for this. Should be out in a day or two.

**Comment by brad4d** [comment]
fix submitted internally yesterday, should be in the next push to github
