### ISSUE TITLE
requestAnimationFrame closure definition is missing return definition

### ISSUE THREAD

**Issue by andersforsell** [google/closure-compiler#2506]
It looks like closure definition is missing return definition:
https://github.com/google/closure-compiler/blob/master/externs/browser/w3c_anim_timing.js#L26

This affects the GWT Elemental 2 library in that I have to return an object:

DomGlobal.requestAnimationFrame(event -> {
        myPresenter.loadContent();
        return null;
      });

**Comment by MatrixFrog** [comment]
Does requestAnimationFrame use the return value of the callback? I'm guessing not, so it should probably be `function(number): void`

**Comment by tbroyer** [comment]
Fwiw, `FrameRequestCallback` is defined as `void (DOMHighResTimeStamp time)`
https://www.w3.org/TR/animation-timing/#framerequestcallback

**Comment by tbroyer** [comment]
Should this issue be reopened then?

**Comment by MatrixFrog** [comment]
Yes, I'm working on rolling forward.
