### ISSUE TITLE
Consume npm package

### ISSUE THREAD

**Issue by manfredsteyer** [google/closure-compiler#2508]
I'm wondering, if it is possible use an npm package like sha256 with a project that is compiled with Closure, like https://github.com/angular/closure-demo. 

I don't want to use global variables with externs but sth like require('sha256') or import ... from 'sha256';

Is this currently supported?

Wishes,
Manfred

**Comment by teppeis** [comment]
See https://github.com/google/closure-compiler/issues/2479
