### ISSUE TITLE
[NTI] Array prototype methods don't typecheck well due to {length: number} alternative in receiver

### ISSUE THREAD

**Issue by shicks** [google/closure-compiler#2513]
The following NewTypeInferenceTest case is broken:

```
typeCheck(LINE_JOINER.join(
    "function f(/** !Array<number> */ arr) {",
    "  arr.push('asdf');",
    "}"),
    NewTypeInference.NOT_UNIQUE_INSTANTIATION);
```

The cause is that `Array.prototype.push` is defined as

```
/**
 * @param {...T} var_args
 * @return {number}
 * @this {{length: number}|!Array.<T>}
 * @template T
 * @modifies {this}
 */
Array.prototype.push = function(var_args) {};
```

which ends up as `<T> function(this: !Object, ...T)`, which unifies just fine with `function(Array<number>, ...string)`.  This is a general problem with many `Array` methods due to the way they accept non-parametrized alternatives.

**Comment by brad4d** [comment]
Perhaps the problem is just that `NewTypeInferenceTest` is providing its own externs and gets them wrong? In `es3.js` the method is annotated as `@this {IArrayLike<T>}`.
