### ISSUE TITLE
Unreasonable JSC_COMMONJS_SUSPICIOUS_EXPORTS_ASSIGNMENT warning

### ISSUE THREAD

**Issue by kommen** [google/closure-compiler#2515]
When consuming some CommonJS modules, I get some `WARNING: JSC_COMMONJS_SUSPICIOUS_EXPORTS_ASSIGNMENT. Suspicious re-assignment of "exports" variable. Did you actually intend to export something?` warnings.

They do seem unreasonable to me though. The code producing the warning, for example:

`exports = module.exports = require('./lib/cheerio');` (https://github.com/cheeriojs/cheerio/blob/master/index.js#L5)

`exports = module.exports = require('./debug');`
(https://github.com/visionmedia/debug/blob/master/src/browser.js#L7)

**Comment by ChadKillingsworth** [comment]
The warning occurs if you assign directly to `exports` and then later assign to `module.exports`:

```js
exports = { foo: 'bar'}; // this export does nothing
module.exports = { baz: 'foobar' };
```

We could special case a chained assignment, but it's pretty low priority (it's just a warning).

**Comment by ChadKillingsworth** [comment]
I believe this is now fixed.
