### ISSUE TITLE
disambiguateProperties does not rename certain names, despite known type

### ISSUE THREAD

**Issue by syranide** [google/closure-compiler#2516]
Original discussion here:
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/closure-compiler-discuss/nNJqsgVcdb8/KqaYOQC8AQAJ

It seems something is preventing GCC from disambiguating certain property names. I don't really know more than that but Chad and Tyler seem to agree that it's a "bug".

Here's the repro provided by Tyler above for `max`: https://goo.gl/gFBSBR

# Going further

However, I went a step further and looked if there were more and found the following list of names that it would refuse to rename:

> NumberFormat, SubtleCrypto, abort, altKey, app, apply, arguments, assign, body, bubbles, button, buttons, cache, call, caller, cancel, cancelable, capture, clientX, clientY, close, code, configurable, connect, construct, create, credentials, ctrlKey, data, deltaX, deltaY, detail, done, entries, error, filename, get, has, headers, height, install, is, isPrimary, iterator, key, keys, lastError, length, loaded, locale, location, log, max, message, metaKey, method, min, mode, name, next, once, passive, port, readable, referrer, relatedTarget, repeat, runtime, screenX, screenY, sendMessage, set, shiftKey, sign, start, status, statusText, timeout, toJSON, toString, total, type, unique, value, values, version, view, watch, width, window, writable, write

Here is a repro file with just the above names:
https://gist.github.com/syranide/2a5f3619bdaad6431e4cdad1e9dc67f9

Some of these probably makes sense even though GCC is able to accurately deduce the signature. Such as `call`, `apply`, `length`, `create`, `is`, etc and others probably make sense for technical reasons. But I leave them in for accuracy and posterity (or perhaps I'm wrong about them).

# Method

I took all files from contrib and grabbed every word. Inserted each of them into the below template, put it all into a big file and compiled with GCC (v20170521). Then I grabbed the strings from the compiled file, which means they weren't optimized away. I put in a file with 8354 names and the above 91 names did not get optimized away.

```js
(new (class {NAME() { return "NAME"; }})).NAME();
```
```
java -jar compiler.jar -O ADVANCED --js in.js --js_output_file out.js --language_in ES6_STRICT --language_out ES5_STRICT --new_type_inf --env BROWSER
```

**Comment by shicks** [comment]
Is this related to #2132, which prevents removing calls to no-side-effect methods with the same name as an extern property?

**Comment by syranide** [comment]
@shicks Yeah that seems like the root cause (to my untrained eye), but as far as I understand it (from the original thread) the point of this issue is primarily to investigate "bad externs". I.e. why on earth are the property names `NumberFormat` and `SubtleCrypto` not being renamed.

**Comment by shicks** [comment]
Per discussion on #2132, it looks like the solution is to go through the externs and find anything that looks like
```js
/** @const */ var foo = {};
foo.bar = baz;
```
and rewrite them as
```js
/** @record */ function FooApi() {};
FooApi.prototype.bar = baz;
/** @const {!FooApi} */ var foo;
```

**Comment by ChadKillingsworth** [comment]
Correct - `@record` has known issues with disambiguation.
