### ISSUE TITLE
Unexpected behavior for function types with no specified return

### ISSUE THREAD

**Issue by shicks** [google/closure-compiler#2518]
[Example](https://closure-compiler-debugger.appspot.com/#input0%3Dvar%2520%252F**%2520function()%2520*%252F%2520f%2520%253D%2520function()%2520%257B%257D%253B%250Avar%2520%252F**%2520number%2520*%252F%2520x%2520%253D%2520f()%253B%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26MISSING_PROPERTIES%3D1%26TRANSPILE%3D1%26CHECK_TYPES%3D1%26CHECK_TYPES_NEW_INFERENCE%3D1%26CLOSURE_PASS%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1)

It's surprising that there's no type error here:

```js
var /** function() */ f = function() {};
var /** number */ x = f();
```

This is because the compiler parses `function()` as `function(): ?` rather than `function(): void` or `function(): *`.  I think the latter might be a more appropriate choice, though I'm not sure how feasible it would be to actually change.

**Comment by dimvar** [comment]
drive-by comment.

The problem is not the type, it's the empty-function value `function() {}`. It's treated specially because it's frequently used as a stub, eg, in interface definitions and in externs. Making checking stricter here is probably too much work to be worth it.

**Comment by shicks** [comment]
That doesn't appear to be the issue.  Adding a [non-empty body](https://closure-compiler-debugger.appspot.com/#input0%3Dvar%2520%252F**%2520function()%2520*%252F%2520f%2520%253D%2520function()%2520%257B%2520console.log(42)%253B%2520%257D%253B%250Avar%2520%252F**%2520number%2520*%252F%2520x%2520%253D%2520f()%253B%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26MISSING_PROPERTIES%3D1%26TRANSPILE%3D1%26CHECK_TYPES%3D1%26CHECK_TYPES_NEW_INFERENCE%3D1%26CLOSURE_PASS%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1) still doesn't produce a warning as one would hope.

**Comment by dimvar** [comment]
Oh you're right, that's what it is. In the inline function type, a missing return means unknown. Yeah, I don't think it's worth it to change that.
