### ISSUE TITLE
JSDoc Tag @implicitCast is not documented

### ISSUE THREAD

**Issue by blickly** [google/closure-compiler#252]
This issue was imported from Closure Compiler's previous home at http://closure-compiler.googlecode.com

The original discussion is archived at:
http://blickly.github.io/closure-compiler-issues/#351

**Comment by realityforge** [comment]
@brad4d This can be closed as it is now documented at https://github.com/google/closure-compiler/wiki/Annotating-JavaScript-for-the-Closure-Compiler#implicitcast

**Comment by brad4d** [comment]
@realityforge thanks
