### ISSUE TITLE
I made the alternative to Closure Compiler

### ISSUE THREAD

**Issue by photopea** [google/closure-compiler#2522]
Hi, I have made my own "compiler" (temporary name SQZR.js), which is
- 60x faster than Closure Compiler
- performs Advanced compilation with results equivalent to Closure Compiler

I have been using CC for a long time, but as my code size exceeded 1 MB, I started to mind the long compilation time.
Right now, my 1.3 MB code is compiled into 
- 660 kB by CC in 65 seconds
- 695 kB by SQZR in 1 second

SQRZ parses JS, replaces all variable names and **property names** (i.e. it has the database of "externs") with much shorter words. Then it passes the syntax tree again and preforms some basic minification (false into !1, "stacking" variable definitions etc.). It does not do any advanced code analysis, it ignores the comments completely. Also, there is no support for ES6 / 7 / 8 features right now.

The little UI is here http://closure-compiler.ivank.net/sqzr.html and the library is here http://closure-compiler.ivank.net/SQZR.js . 90% of the library is the database of "browser externs" at the end of the file. It uses acorn.js for parsing JS and escodegen.js for stringifying the syntax tree.

Would anybody be interested in contributing to such project, or using it instead of CC? Otherwise, I will probably keep it as my internal project for my own purposes.

**Comment by Dominator008** [comment]
Feel free to publish it but I don't think this is an issue with Closure Compiler.

**Comment by photopea** [comment]
You closed my last issue about the speed of Closure Compiler  https://github.com/google/closure-compiler/issues/2467  So I wanted to show you, that faster compilation is possible.

Would you @Dominator008  be interested in developing an alternative, faster compiler from scratch in JS instead of Java?  Maybe you have some ideas about how a better system should work, and it is often easier to start making a new system from scratch than tweaking an existing, complex system.

**Comment by Dominator008** [comment]
@photopea We'd certainly work on making Closure Compiler faster, but perhaps not by writing a completely different minifier as there are enough of these. Feel free to create your own repo for your project and move discussions there.

**Comment by MatrixFrog** [comment]
This sounds very cool! Let's discuss on https://groups.google.com/forum/#!forum/closure-compiler-discuss though rather than on the issue tracker.
