### ISSUE TITLE
line feeds are not parsed correctly in --output_wrapper

### ISSUE THREAD

**Issue by clarkbw** [google/closure-compiler#2523]
I'm testing with version `20170521.0.0`

I'm trying to use the FAQ answer for [including source maps](https://github.com/google/closure-compiler/wiki/FAQ#source-maps-and-sourcemappingurl) and it doesn't appear to work because the `\n` is included in as-is in the output.

Here's the FAQ answer:

```
--output_wrapper "%output%\n//# sourceMappingURL=output.js.map"
```

Here's a simplified test case for the problem:

```
$ echo "" | java -jar build/compiler.jar --output_wrapper "(function(){%output%})()\n//# sourceMappingURL=output.js.map"
The compiler is waiting for input via stdin.
(function(){})()\n//# sourceMappingURL=output.js.map
```

You can see the output includes a `\n` instead of the actual line break.

This issue was brought up in #436 but I don't think it was ever fixed.

**Comment by ChadKillingsworth** [comment]
This is highly dependent on your shell: https://unix.stackexchange.com/a/20039

**Comment by clarkbw** [comment]
I see, sorry. Something like this does work: 
```
 --output_wrapper=$'%output%\n//# sourceMappingURL=bundle.js.map'
```

**Comment by ChadKillingsworth** [comment]
It's confusing I know. But there are SO many variations in shell processing it's hard to properly document.

**Comment by kirschkern** [comment]
The following worked for me on Windows 10:

--output_wrapper=$"%output%
//# sourceMappingURL=../../js/core/runtime.map"

Yes, two lines
