### ISSUE TITLE
Assigning to @const used in goog.string.Const.from expression should result in error, not just warning

### ISSUE THREAD

**Issue by xtofian** [google/closure-compiler#2524]
`ConstParamCheck` intends to enforce that the argument to `goog.string.Const.from` is a compile time constant; i.e. should produce a compilation error in code where this is not so.  `goog.string.Const` is primarily used in security-related APIs, such as the `goog.html.TrustedResourceUrl` type.

`ConstParamCheck` in turn relies on the `InferConsts` pass, which in turn essentially trusts the `@const` annotation.  However, ignoring an `@const` annotation only results in a compiler warning, not an error. 

For example:
http://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540compilation_level%2520SIMPLE_OPTIMIZATIONS%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250Avar%2520goog%2520%253D%2520%257B%257D%253B%250Agoog.string%2520%253D%2520%257B%257D%253B%250Agoog.string.Const%2520%253D%2520%257B%257D%253B%250Agoog.string.Const.from%2520%253D%2520function(x)%2520%257B%257D%253B%250A%250A%250A%252F**%2520%2540const%2520*%252F%250Avar%2520y%2520%253D%2520'foo'%253B%250A%250Afunction%2520evil(foo)%2520%257B%250A%2520%2520y%2520%253D%2520foo%253B%250A%2520%2520return%2520goog.string.Const.from(y)%253B%250A%257D%250A

Ideally, assigning to an `@const` that is used as part of a `goog.string.Const` expression should result in a compilation error, not just a warning.

**Comment by vrana** [comment]
We can also stop trusting `IS_CONSTANT_NAME` at https://github.com/google/closure-compiler/blob/fb05a42b/src/com/google/javascript/jscomp/Var.java#L130 and trust only `IS_CONSTANT_VAR`. If I understand it correctly, `IS_CONSTANT_NAME` is used for `@const` (even if overridden) and `IS_CONSTANT_VAR` is used for variables the compiler thinks are constant. Any `IS_CONSTANT_NAME` that is not overridden should be also `IS_CONSTANT_VAR`.

**Comment by brad4d** [comment]
If you want this warning to be an error, just add `--jscomp_error=const` to the compiler command line.
