### ISSUE TITLE
Write $jscomp.setPrototypeOf and rework Reflect.setPrototypeOf and Object.setPrototypeOf to use it

### ISSUE THREAD

**Issue by brad4d** [google/closure-compiler#2529]
Motivation for this change is we need the functionality of `setPrototypeOf` in `$jscomp.inherits()`, but it's problematic for that method to directly depend on methods that must themselves be polyfilled.

See PR #2419 for why we need this functionality in `$jscomp.inherits()`

**Comment by brad4d** [comment]
[`src/com/google/javascript/jscomp/js/es6/util/construct.js`](https://github.com/google/closure-compiler/blob/master/src/com/google/javascript/jscomp/js/es6/util/construct.js) does something similar for `Reflect.construct`.

**Comment by ChadKillingsworth** [comment]
@brad4d I can handle this if you want. I'm reverting most of the changes in #2419, so it will be a pretty small PR.

**Comment by brad4d** [comment]
@ChadKillingsworth that would be great. Thanks!

**Comment by brad4d** [comment]
Failed to mark the change that closed this, but it is done.
