### ISSUE TITLE
[externs] Add WebAssembly JS API externs

### ISSUE THREAD

**Issue by rongjiecomputer** [google/closure-compiler#2533]
WebAssembly has reached MVP in March 2017. WebAssembly JS API specification can be found at http://webassembly.org/docs/js/.

Externs rules of WebAssembly JS API is added in Emscripten at [here](https://github.com/kripken/emscripten/blob/incoming/src/closure-externs.js#L912).

I want to send a PR for this. Should I add externs rule in `html5.js` or a new `webassembly.js` file? It looks like I also need to regenerate `src/com/google/javascript/jscomp/resources.json`, how do I do that?

Note: WebAssembly is not part of JS specification, but it is usually implemented in JS engine side rather than in browser side, so this is not a browser API and Node.js also can use WebAssembly.

**Comment by MatrixFrog** [comment]
I would say let's put it in a new file. Our google<->github syncing process will automatically regenerate resources.json I think.

**Comment by rongjiecomputer** [comment]
Externs added.

**Comment by RReverser** [comment]
Hmm, what ever happened to WebAssembly externs? An up-to-date Closure Compiler is complaining about variable WebAssembly being undeclared, and the file seems to be missing where it was added originally.
