### ISSUE TITLE
[ES6] Class breaks marked @extends and @implements

### ISSUE THREAD

**Issue by badfortrains** [google/closure-compiler#2537]
In es5 you could create a class that @extends a typedef and @implements an interface. Doing the same with an es6 class fails.
````
/** @interface */
class Foo {
  /** @return {string} */
  someMethod() {}
}

/**
 * @typedef {{
 *   id: string,
 * }}
 */
let MyId;


// ES5 works fine
/**
*@constructor
* @extends {MyId}
* @implements {Foo}
*/
function FooOld() {
    /** @type {string} */
    this.id ='123';
}

/** @override */
FooOld.prototype.someMethod = function() {
 return '123';
}

//ES6 breaks, complains that property someMethod is not defined.
/**
* @extends {MyId}
* @implements {Foo}
*/
class FooImpl {
  constructor() {
    /** @type {string} */
    this.id ='123';
  }
  /** @override */
  someMethod() {
    return 'yes';
  }
}
````

JSCompiler demo:
https://closure-compiler-debugger.appspot.com/#input0%3D%252F**%2520%2540interface%2520*%252F%250Aclass%2520Foo%2520%257B%250A%2520%2520%252F**%2520%2540return%2520%257Bstring%257D%2520*%252F%250A%2520%2520someMethod()%2520%257B%257D%250A%257D%250A%250A%252F**%250A%2520*%2520%2540typedef%2520%257B%257B%250A%2520*%2520%2520%2520id%253A%2520string%252C%250A%2520*%2520%257D%257D%250A%2520*%252F%250Alet%2520MyId%253B%250A%250A%250A%252F**%250A*%2540constructor%250A*%2520%2540extends%2520%257BMyId%257D%250A*%2520%2540implements%2520%257BFoo%257D%250A*%252F%250Afunction%2520FooOld()%2520%257B%250A%2520%2520%2520%2520%252F**%2520%2540type%2520%257Bstring%257D%2520*%252F%250A%2520%2520%2520%2520this.id%2520%253D'123'%253B%250A%257D%250A%250A%252F**%2520%2540override%2520*%252F%250AFooOld.prototype.someMethod%2520%253D%2520function()%2520%257B%250A%2520return%2520'123'%253B%250A%257D%250A%250A%252F**%250A*%2520%2540extends%2520%257BMyId%257D%250A*%2520%2540implements%2520%257BFoo%257D%250A*%252F%250Aclass%2520FooImpl%2520%257B%250A%2520%2520constructor()%2520%257B%250A%2520%2520%2520%2520%252F**%2520%2540type%2520%257Bstring%257D%2520*%252F%250A%2520%2520%2520%2520this.id%2520%253D'123'%253B%250A%2520%2520%257D%250A%2520%2520%252F**%2520%2540override%2520*%252F%250A%2520%2520someMethod()%2520%257B%250A%2520%2520%2520%2520return%2520'yes'%253B%250A%2520%2520%257D%250A%257D%250A%250A%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26MISSING_PROPERTIES%3D1%26TRANSPILE%3D1%26CHECK_TYPES%3D1%26PRETTY_PRINT%3D1

**Comment by MatrixFrog** [comment]
I don't think `@extends` was ever intended to work with typedefs.

**Comment by badfortrains** [comment]
Okay that makes sense then, I'll close this
