### ISSUE TITLE
bogus array index warning

### ISSUE THREAD

**Issue by pdknsk** [google/closure-compiler#2542]
```JavaScript
var y = [1];
console.log(y['0']);
```
```
JSC_TYPE_MISMATCH: restricted index type
found   : string
required: number at line 3 character 14
console.log(y['0']);
              ^
```
As per [ECMA-262](https://www.ecma-international.org/publications/files/ECMA-ST/Ecma-262.pdf).

> An _integer index_ is a **String‑valued** property key that is a canonical numeric String (see 7.1.16) and whose numeric value is either +0 or a positive integer ≤ (2^53)‑1. An _array index_ is an integer index whose numeric value _i_ is in the range +0 ≤ i < (2^32)‑1.

And further.
> The abstract operation CanonicalNumericIndexString returns _argument_ converted to a numeric value if it is a String representation of a Number that would be produced by ToString, or the string "‐0".

**Comment by ChadKillingsworth** [comment]
This is by design. String indexes are frequently a mistake. The type checking of the compiler forces numeric indexes.

**Comment by pdknsk** [comment]
​How can I disable it? I tried `/** @suppress​ {checkTypes} */` but it doesn't work.

**Comment by dimvar** [comment]
You can add the suppression on the enclosing function. https://github.com/google/closure-compiler/wiki/@suppress-annotations

**Comment by pdknsk** [comment]
Thanks.

I just want to add the use case where I encountered this.
```JavaScript
var x = {};
var y = [1];
y.forEach(function(item, index) {
  x[index] = item;
});
for (var i in x)
  console.log(y[i]);
```
If Closure had this functionality, it could easily infer that the code is safe, I think.
