### ISSUE TITLE
Bad type annotation in typedef when omitting trailing comma

### ISSUE THREAD

**Issue by lukesandberg** [google/closure-compiler#2543]
the following program
```js
goog.provide('ns.testSwitch.Params');

/**
 * @typedef {{
 *  boo: ?,
 *  goo: ?
 * }}
 */
ns.testSwitch.Params;
```
issues the following warning
input0:5: WARNING - Bad type annotation. type not recognized due to syntax error. See https://github.com/google/closure-compiler/wiki/Bad-Type-Annotation for more information.
 *  goo: ?
          ^

0 error(s), 1 warning(s), 100.0% typed

this can be fixed by either wrapping the `?` in parens or by adding a trailing comma to the record.  This is pretty confusing and i think the warning is getting issued on the newline character... perhaps the error message could be improved?

**Comment by MatrixFrog** [comment]
https://closure-compiler-debugger.appspot.com/#input0%3D%252F**%250A%2520*%2520%2540typedef%2520%257B%257B%250A%2520*%2520%2520boo%253A%2520%253F%252C%250A%2520*%2520%2520goo%253A%2520%253F%250A%2520*%2520%257D%257D%250A%2520*%252F%250Ans.testSwitch.Params%253B%26input1%26conformanceConfig%26externs%3Dvar%2520ns%253B%250Ans.testSwitch%253B%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26MISSING_PROPERTIES%3D1%26TRANSPILE%3D1%26CHECK_TYPES%3D1%26CLOSURE_PASS%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1

This is weird.

**Comment by MatrixFrog** [comment]
Maybe there's still some old code in JSDocInfoParser which treats `,` as a valid separator for a union type. I thought we'd changed it to only allow `|` whereas previously it allowed `|` or `||` or `,` but maybe we never got around to actually removing `,`
