### ISSUE TITLE
Add support for character (U+0CA0)

### ISSUE THREAD

**Issue by binarykitchen** [google/closure-compiler#2544]
When trying to compress a project of mine with rollup + closure-compiler-js I get this error

```
Input_0:14447 (JSC_PARSE_ERROR)
Parse error. Character 'ಠ' (U+0CA0) is not a valid identifier start char
}

var iOS8or9 = typeof document === 'object' && 'object-fit' in document.head.style && !matchMedia('(-webkit-video-playable-inline)').matches;

var ಠ = 'bfred-it:iphone-inline-video';
    ^
var ಠevent = 'bfred-it:iphone-inline-video:event';
var ಠplay = 'bfred-it:iphone-inline-video:nativeplay';
var ಠpause = 'bfred-it:iphone-inline-video:nativepause';


🚨   (closure-compiler-js plugin) Error transforming bundle with 'closure-compiler-js' plugin: compilation error, 1 error
```

Looks like your closure compiler isn't supporting that special character. Could it be supported?

To reproduce, `git clone https://github.com/binarykitchen/videomail-client/tree/feature/rollupjs` and run `yarn build`

**Comment by ChadKillingsworth** [comment]
I don't believe that's valid Ecmascript: https://mathiasbynens.be/notes/javascript-identifiers-es6

**Comment by binarykitchen** [comment]
yeah never mind, already have submitted a PR to replace those special characters in https://github.com/bfred-it/iphone-inline-video/commit/758f7b91a2988f28769d26fa4ccc711397b8e98a
