### ISSUE TITLE
Compiler doesn't know about inherited static properties

### ISSUE THREAD

**Issue by fejesjoco** [google/closure-compiler#2551]
Code sample:

```
class MyXHR extends XMLHttpRequest {}
console.log(XMLHttpRequest.HEADERS_RECEIVED);
console.log(MyXHR.HEADERS_RECEIVED);
```

This totally works in browsers, it prints 2 twice. By static property I'm referring to HEADERS_RECEIVED and similar.

In JSCompiler, both old and new type checker, this gives a warning:

```
Property HEADERS_RECEIVED never defined on MyXHR of type MyXHR<|function(new:MyXHR,...?):undefined|>
```

**Comment by brad4d** [comment]
We are working to provide better support for static properties.
@dimvar does it make sense to assign this to you?
I suspect it's a duplicate.

**Comment by dimvar** [comment]
This will just be handled as part of typechecking ES6 natively. No need to have a separate issue.
