### ISSUE TITLE
Allow trailing comma at the end of a param list

### ISSUE THREAD

**Issue by MatrixFrog** [google/closure-compiler#2552]
I missed that this had been added to the spec, I guess.

https://jsconsole.com/?function%20f(x%2C%20y%2C%20)%20%7B%7D works at least in Chrome 59. Should be a pretty easy fix.

**Comment by MatrixFrog** [comment]
It looks like this moved to stage 4 almost a year ago https://github.com/tc39/proposal-trailing-function-commas/commit/8318eda8605b88a7f84cb37b268179b3accf46e1 so I'm not sure if it's in the 2016 or 2017 language mode

**Comment by ChadKillingsworth** [comment]
@MatrixFrog 2017 - https://github.com/tc39/proposals/blob/master/finished-proposals.md

**Comment by concavelenz** [comment]
This seems like a nice summary of what version added what: 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/New_in_JavaScript/ECMAScript_Next_support_in_Mozilla
