### ISSUE TITLE
special line of commented code is causing a 500 internal server error

### ISSUE THREAD

**Issue by klevstul** [google/closure-compiler#2557]
### short description
the following line is causing a 500 internal server error using the api:
`//# sourceMappingURL=whatever`

### code example
example request, in perl, that causes http status code 500:
```
    my $url = "http://closure-compiler.appspot.com/compile";
    my $userAgent = LWP::UserAgent->new();
    my $request = POST $url, [
        js_code => `//# sourceMappingURL=whatever`,
        compilation_level => 'WHITESPACE_ONLY',
        output_format => 'text',
        output_info => 'compiled_code',
        output_info => 'errors'
    ];
```

result:
`500 Internal Server Error`

### background
this was discovered trying to compile/minimise the following js code:
```
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var platform_browser_dynamic_1 = require("@angular/platform-browser-dynamic");
var core_1 = require("@angular/core");
var app_module_KDBUILD_1 = require("./app/modules/app.module.KDBUILD");
if (window.location.hostname !== 'localhost') {
    core_1.enableProdMode();
}
platform_browser_dynamic_1.platformBrowserDynamic().bootstrapModule(app_module_KDBUILD_1.AppModule);
//# sourceMappingURL=main.js.map
```

**Comment by bs85** [comment]
Thanks a lot for reporting this, helped me figure out why my build was broken!

Lots of minified libraries include this line, eg https://cdnjs.cloudflare.com/ajax/libs/backbone.js/1.3.3/backbone-min.js

**Comment by tadeegan** [comment]
I suspect that this is a result of:
https://github.com/google/closure-compiler/commit/fa5af790fc86b8bde261a19152eb222d61458333

Although, it should be outputting an warning, not crashing the compiler. See:
https://github.com/google/closure-compiler/blob/fa5af790fc86b8bde261a19152eb222d61458333/src/com/google/javascript/jscomp/SourceMapInput.java#L57

Here is a repro with the debugger, which is different than the api but they both run on app engine so I bet its the same crash.
https://closure-compiler-debugger.appspot.com/#input0%3D%252F%252F%2523%2520sourceMappingURL%253Dsomething%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26MISSING_PROPERTIES%3D1%26TRANSPILE%3D1%26CHECK_TYPES%3D1%26CLOSURE_PASS%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1

**Comment by tadeegan** [comment]
Stack trace for reference:

```
Error for /compile
java.lang.NoClassDefFoundError: Could not initialize class com.google.apphosting.runtime.security.shared.stub.java.nio.file.FileSystems
	at com.google.javascript.jscomp.SourceMapResolver.getRelativePath(SourceMapResolver.java:73)
	at com.google.javascript.jscomp.SourceMapResolver.extractSourceMap(SourceMapResolver.java:53)
	at com.google.javascript.jscomp.JsAst.parse(JsAst.java:164)
	....
```

**Comment by brad4d** [comment]
@tadeegan are you working on a fix for this?

**Comment by tadeegan** [comment]
@brad4d I could. How do you think we should handle it? We could turn off source map parsing for the app engine version.

**Comment by sucat** [comment]
```
alert();
//# sourceMappingURL=alert.js.map
```

gives me 
```
500: Internal Server Error
Original Post Data: 
output_format=json&output_info=compiled_code&output_info=warnings&output_info=errors&output_info=statistics&compilation_level=SIMPLE_OPTIMIZATIONS&warning_level=default&output_file_name=default.js&js_code=alert()%3B%0A%2F%2F%23%20sourceMappingURL%3Dalert.js.map
```

Are you going to fix it? It was working a few days ago.
It's affecting our production deployments (we use REST API)

**Comment by brad4d** [comment]
@tadeegan and I discussed this. I believe he's working on a fix to ignore the sourceMappingURL when the compiler is running in appengine or the debugger.

**Comment by brad4d** [comment]
I've rolled back our appengine service to the previous release, so this bug should no longer happen there.
It'll still happen in the debugger, but that doesn't seem worth worrying about.

@tadeegan has submitted a fix internally which will be in the next internal release.
