### ISSUE TITLE
Error with js_module_root

### ISSUE THREAD

**Issue by wumvi** [google/closure-compiler#2565]
Hello! I have some trouble with js_module_root
closure compiler v20170626

## First problem 
I have two files 
\# /tmp/run.js
import '**/tmp/common**';   console.log('run');
\# /tmp/common.js
console.log('common');

and run with cmd 

> java -jar /www/build/bin/closure-compiler.jar --compilation_level ADVANCED --module_resolution NODE --language_in ECMASCRIPT6 --js_module_root /tmp/ --js /tmp/run.js --js /tmp/common.js

a have a error

> /tmp/run.js:1: ERROR - required "module$tmp$common" namespace never provided
> import '/tmp/common';

but, if run with cmd
> java -jar /www/build/bin/closure-compiler.jar --compilation_level ADVANCED --module_resolution NODE --language_in ECMASCRIPT6 --js_module_root /blablablafakeblablabla/ --js /tmp/run.js --js /tmp/common.js

it workes fine

## Secord problem
I have two files 
\# /tmp/run.js
import '**common**';   console.log('run');
\# /tmp/common.js
console.log('common');

if I run with cmd

> java -jar /www/build/bin/closure-compiler.jar --compilation_level ADVANCED --module_resolution NODE --language_in ECMASCRIPT6 --js_module_root /tmp/ --js /tmp/run.js --js /tmp/common.js

it works fine, BUT with warning

> /tmp/run.js:1: WARNING - Failed to load module "common"
> import 'common';

**Comment by ChadKillingsworth** [comment]
Your first problem is expected. With a `--js_module_root /tmp`, your import statement should be `import '/common';`. There was an incorrect behavior that was fixed as part of the [20170423 release](https://github.com/google/closure-compiler/wiki/Releases#april-23-2017-v20170423). Module roots now provide an anchor point for absolute paths (they didn't before).

Your second problem is also expected. With the node module resolution, a relative import MUST begin with `./` or `../`. So your import should be `import './common';`. With the way you have it written, the compiler is looking for a `node_modules/common/index.js` (or similar) file.
