### ISSUE TITLE
Parser can't handle ES6 short-hand methods with string-literal keys

### ISSUE THREAD

**Issue by shicks** [google/closure-compiler#2566]
[Repro]

```js
var x = {
  'foo'() {},
};
```

This is perfectly valid syntax.

[Repro]: https://closure-compiler-debugger.appspot.com/#input0%3Dvar%2520x%2520%253D%2520%257B%250A%2520%2520'foo'()%2520%257B%257D%252C%250A%257D%253B%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26MISSING_PROPERTIES%3D1%26TRANSPILE%3D1%26CHECK_TYPES%3D1%26CLOSURE_PASS%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1

**Comment by shicks** [comment]
(numbers fail, too)

**Comment by brad4d** [comment]
but computed properties work...

```javascript
let x = {
  ['foo']() {},
};
```
