### ISSUE TITLE
Trace current variable type

### ISSUE THREAD

**Issue by ikabirov** [google/closure-compiler#2574]
Is in possible to add function that forces the compiler tracing information about variable?

```
const arr = ["string"];
traceType(arr);
/* compiler output:
main.js:2: WARNING - Trace variable type
Found    : Array<string>
*/
```

**Comment by dimvar** [comment]
Please ask questions on the mailing list: https://groups.google.com/forum/#!forum/closure-compiler-discuss. The github issue tracker is just for bugs.

For this question, I don't know what you mean about tracing a variable. Can you explain?
