### ISSUE TITLE
[NTI] Templated array typecast error

### ISSUE THREAD

**Issue by ikabirov** [google/closure-compiler#2575]
```
class Parent {}
class Child extends Parent {}

const a1 = [new Child];
const a2 = ["hello", new Child];

/** @type {!Array<!Child>} */(a1);  // OK
/** @type {!Array<!Parent>} */(a1); // OK
/** @type {!Array<!Child>} */(a2);  // OK
/** @type {!Array<!Parent>} */(a2); // WARNING - invalid cast - the types do not have a common subtype
```

https://closure-compiler-debugger.appspot.com/#input0%3Dclass%2520Parent%2520%257B%257D%250Aclass%2520Child%2520extends%2520Parent%2520%257B%257D%250A%250Aconst%2520a1%2520%253D%2520%255Bnew%2520Child%255D%253B%250Aconst%2520a2%2520%253D%2520%255B%2522hello%2522%252C%2520new%2520Child%255D%253B%250A%250A%252F**%2520%2540type%2520%257B!Array%253C!Child%253E%257D%2520*%252F(a1)%253B%2520%2520%252F%252F%2520OK%250A%252F**%2520%2540type%2520%257B!Array%253C!Parent%253E%257D%2520*%252F(a1)%253B%2520%252F%252F%2520OK%250A%252F**%2520%2540type%2520%257B!Array%253C!Child%253E%257D%2520*%252F(a2)%253B%2520%2520%252F%252F%2520OK%250A%252F**%2520%2540type%2520%257B!Array%253C!Parent%253E%257D%2520*%252F(a2)%253B%2520%252F%252F%2520WARNING%2520-%2520invalid%2520cast%2520-%2520the%2520types%2520do%2520not%2520have%2520a%2520common%2520subtype%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26MISSING_PROPERTIES%3D1%26TRANSPILE%3D1%26CHECK_TYPES%3D1%26CHECK_TYPES_NEW_INFERENCE%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1

**Comment by ChadKillingsworth** [comment]
Looks like the compiler is correct here. By design it prevents unsafe casts.

**Comment by ikabirov** [comment]
All casts is potentially unsafe. But why you think that **Array<string, Child> -> Array<Child>** and  **Array<Child> -> Array<Parent>**, but  **Array<string, Child> -> Array<Parent>** is unsafe?

**Comment by dimvar** [comment]
We could probably handle the array contents better in this case to avoid warning.
