### ISSUE TITLE
@typedef on Array confuses Closure

### ISSUE THREAD

**Issue by pelchats** [google/closure-compiler#2578]
The following code result in a compilation warning

```javascript
/** @typedef {window.Array} */
const A = window.Array;

/** @return {!A<string>} */
function f() {
  return [];
}

for (const v of f()) {
}
```

```
JSC_TYPE_MISMATCH: actual parameter 1 of $jscomp.makeIterator does not match formal parameter
found   : (Array|null)
required: (Arguments<?>|Array<?>|Iterable<?>|Iterator<?>|string) at line 9 character 16
for (const v of f()) {
                ^
```

It looks like for some reason Closure thinks f returns a possibly null value, which is not what the type annotation on f says.

http://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540compilation_level%2520ADVANCED_OPTIMIZATIONS%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%2540formatting%2520pretty_print%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250A%252F**%2520%2540typedef%2520%257Bwindow.Array%257D%2520*%252F%250Aconst%2520A%2520%253D%2520window.Array%253B%250A%250A%252F**%2520%2540return%2520%257B!A%253Cstring%253E%257D%2520*%252F%250Afunction%2520f()%2520%257B%250A%2520%2520return%2520%255B%255D%253B%250A%257D%250A%250Afor%2520(const%2520v%2520of%2520f())%2520%257B%250A%257D%250A

**Comment by MatrixFrog** [comment]
Generally typedefs should be explicitly non-null:

```
/** @typedef {!window.Array} */
const A = window.Array;
```

and then you if you want a nullable A you can write `?A`

**Comment by pelchats** [comment]
I see, thanks!

**Comment by concavelenz** [comment]
Note also that @typedef declarations should never be assigned a value.  

If you want to alias a type simply use @const:

  /** @const */
  const A = window.Array;

**Comment by shicks** [comment]
@concavelenz `@const` and `const` should be redundant - you only need one or the other, right?

@MatrixFrog That's opposite what I've been advising people to do.  In light of our [style guide](https://google.github.io/styleguide/jsguide.html#jsdoc-nullability), I've argued that consistency would recommend capitalized names be nullable.  Maybe that's a moot point in light of the mandate to use explicit `!` and `?` always for capital names, anyway.  Is there a reason the compiler works better if you define `@typedefs` to be non-null?
