### ISSUE TITLE
PolymerPass: properties: {'declaredInQuotes'} aren't typechecked

### ISSUE THREAD

**Issue by danbeam** [google/closure-compiler#2588]
contents of x-blah.js:
```js
Polymer({
  is: 'x-blah',
  properties: {'counter': Number},
  count: function() { this.counter++; },
});
```

command used to invoke compiler.jar
```shell
$ java -jar compiler.jar --checks_only --polymer_pass --externs polymer-1.0.js --jscomp_error=checkTypes x-blah.js
```

output
```
x-blah.js:4: ERROR - Property counter never defined on XBlahElement
  count: function() { this.counter++; },
                           ^^^^^^^

1 error(s), 0 warning(s), 90.9% typed
```

Removing the quotes around `'counter'` fixes the issue.

The fix probably involves which `Node name` is passed to `MemberDefinition` when extracting from the `properties` Object - [PolymerPassStaticUtils.java:120](https://github.com/google/closure-compiler/blob/635406e1b81f0e367fe2d9d9976fbd8dc1c0a1bb/src/com/google/javascript/jscomp/PolymerPassStaticUtils.java#L120)

/cc @rictic @jklein24 @MatrixFrog

**Comment by MatrixFrog** [comment]
Quoted properties are generally not typechecked, so this isn't really special to PolymerPass. After a recent @ChadKillingsworth change we had to unquote some properties in Google projects to get rid of type errors.

**Comment by MatrixFrog** [comment]
We probably should have put that in the release notes.

**Comment by ChadKillingsworth** [comment]
This was very much by design. Quoted properties in declared properties should have similar behavior to quoted properties everywhere else in the compiler: typechecking is better and renaming occurs without quotes.

And yes, I still need to rewrite the documentation on that pass.

**Comment by freshp86** [comment]
Not typechecking properties is not the same as having them not be defined at all though. Mentioning this because the errors I am getting in Chromium codebase indicate the latter. Pasting below:

```
(ERROR) Error in: files_tooltip.js
## /b/build/slave/linux/build/src/ui/file_manager/file_manager/foreground/elements/files_tooltip.js:122: ERROR - Property showTimeout never defined on FilesTooltip
##         this.visibleTooltipTarget_ ? 0 : this.showTimeout);
##                                               ^^^^^^^^^^^
## 
## /b/build/slave/linux/build/src/ui/file_manager/file_manager/foreground/elements/files_tooltip.js:142: ERROR - Property hideTimeout never defined on FilesTooltip
##         this.hideTooltip_.bind(this), this.hideTimeout);
##                                            ^^^^^^^^^^^
```

The file in question is [here](https://cs.chromium.org/chromium/src/ui/file_manager/file_manager/foreground/elements/files_tooltip.js?type=cs&q=files_tooltip.js&sq=package:chromium&l=22).

**Comment by ChadKillingsworth** [comment]
This violates one of the core tenets of the compiler: a quoted property != it's unquoted version. That's why it was changed.

@MatrixFrog Should this behavior be corrected for `--polymer_version=1`? It was only intended to be this way for v2.

**Comment by MatrixFrog** [comment]
No, I think I'd prefer to leave it as it is, so that people don't write any more quoted properties between now and when they switch to v2

**Comment by danbeam** [comment]
note: the issue Chrome hit involved having already quoted properties that were broken by changed in behavior of Closure Compiler.  here's hoping folks that hit this issue find this thread / figure it out.
