### ISSUE TITLE
[question][type-checking] Calling methods on null?

### ISSUE THREAD

**Issue by DanielBaulig** [google/closure-compiler#2601]
Does the type system of closure compiler not prevent arbitrary method calls on `null`? The following code compiles without complains in closure compiler

    /** @type {SomethingWithoutMethod} */
    var something = null;
    something.method();

Am I doing something wrong? Is this not something that is caught by closure compiler? Is this a bug (possibly in an old version; I'm running quite an old version of CC on this project)? Anything else I may be missing?

**Comment by dimvar** [comment]
You can use a [conformance check](https://github.com/google/closure-compiler/wiki/JS-Conformance-Framework#bannullderef).

FYI, we prefer questions on the [mailing list](https://groups.google.com/forum/#!forum/closure-compiler-discuss). The github issue tracker is for bugs.

**Comment by DanielBaulig** [comment]
@dimvar Thanks, appreciate your response.
