### ISSUE TITLE
new Date() compiles (Both Simple & Advanced)  to new Date (without the brackets)

### ISSUE THREAD

**Issue by nicholas-george** [google/closure-compiler#2608]
Both Simple & Advanced compilation changes new Date() to new Date (without the bracket), which browsers like Safari cannot understand.

Have tried with the latest (v20170626) version. And also using the online complier service.
This
```
let date1 = new Date(Date.now());
let date2 = new Date();
console.log(date1,date2);
```

SIMPLE
`var date1=new Date(Date.now()),date2=new Date;console.log(date1,date2);`

ADVANCED
`console.log(new Date(Date.now()),new Date);`

**Comment by MatrixFrog** [comment]
This is very surprising to me. What version of Safari are you seeing this in?

**Comment by ChadKillingsworth** [comment]
I am extremely skeptical that this is correct. This would have been reported years ago. It most certainly works in my version of Safari.

**Comment by nicholas-george** [comment]
Apologies. I mixed up Safari's lack of support for lastModifiedDate error with this one, as I was using both in the same line.

Yes. this is not an issue. Apologies again.
