### ISSUE TITLE
[NTI] IObject type suspiciously specialized to structural type

### ISSUE THREAD

**Issue by ikabirov** [google/closure-compiler#2615]
We use objects with dynamic properties for keys obfucation. But (?) type does not work correctly:
```
/** @param {?} keys */
function serializeTextFormat(keys) {
  const res = {};
  res[keys.bold] = true; // keys - ?
  res[keys.italic] = true; // keys - string
  res[keys.underline] = false;
  return res;
}
```

https://closure-compiler-debugger.appspot.com/#input0%3D%252F**%2520%2540param%2520%257B%253F%257D%2520keys%2520*%252F%250Afunction%2520serializeTextFormat(keys)%2520%257B%250A%2520%2520const%2520res%2520%253D%2520%257B%257D%253B%250A%2520%2520res%255Bkeys.bold%255D%2520%253D%2520true%253B%250A%2520%2520res%255Bkeys.italic%255D%2520%253D%2520true%253B%250A%2520%2520res%255Bkeys.underline%255D%2520%253D%2520false%253B%250A%2520%2520return%2520res%253B%250A%257D%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26MISSING_PROPERTIES%3D1%26TRANSPILE%3D1%26CHECK_TYPES%3D1%26CHECK_TYPES_NEW_INFERENCE%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1

**Comment by dimvar** [comment]
NTI can specialize variables typed unknown to find more errors. E.g.,
````
function f(/** ? */ x) {
  var y = x - 1;
  var /** string */ s = x; // warning, we know x is a number
}
````
We think this is an improvement over the old type checker.

The more questionable NTI behavior in your example is that we optimistically inferred keys to be string because of the bold property. That's not always a correct heuristic, but it's usually correct. If you want some other type, you can explicitly annotate keys with that type.

**Comment by ikabirov** [comment]
is it possible to compile that code without warnings?

**Comment by dimvar** [comment]
Yes, e.g., you can do:
````
/** @param {{bold: ?, italic: ?, underline: ?}} keys */
function serializeTextFormat(keys) {
  const res = {};
  res[keys.bold] = true;
  res[keys.italic] = true;
  res[keys.underline] = false;
  return res;
}
````

**Comment by ikabirov** [comment]
text format is just sample. I need ability to add new key (e.g. keys.strike) without method signature change

**Comment by dimvar** [comment]
Try `IObject<string, ?>`.

**Comment by ikabirov** [comment]
```
input0:5: WARNING - Property italic never defined on keys of type {bold: ?}
  res[keys.italic] = true;
      ^^^^^^^^^^^

input0:6: WARNING - Property underline never defined on keys of type {bold: ?}
  res[keys.underline] = false;
      ^^^^^^^^^^^^^^
```

https://closure-compiler-debugger.appspot.com/#input0%3D%252F**%2520%2540param%2520%257BIObject%253Cstring%252C%2520%253F%253E%257D%2520keys%2520*%252F%250Afunction%2520serializeTextFormat(keys)%2520%257B%250A%2520%2520const%2520res%2520%253D%2520%257B%257D%253B%250A%2520%2520res%255Bkeys.bold%255D%2520%253D%2520true%253B%250A%2520%2520res%255Bkeys.italic%255D%2520%253D%2520true%253B%250A%2520%2520res%255Bkeys.underline%255D%2520%253D%2520false%253B%250A%2520%2520return%2520res%253B%250A%257D%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26MISSING_PROPERTIES%3D1%26TRANSPILE%3D1%26CHECK_TYPES%3D1%26CHECK_TYPES_NEW_INFERENCE%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1

**Comment by dimvar** [comment]
The warning when you use IObject is weird. Reopening the bug to look into that.

For this case, you can do one of two things. Either obscure the use of the bold property, to avoid the not always correct heuristic from NTI (see below), or declare the structural type with all the properties, as I suggested earlier.

````
/** @param {?} keys */
function serializeTextFormat(keys) {
  const res = {};
  res[keys['bold' + '']] = true;
  res[keys.italic] = true;
  res[keys.underline] = false;
  return res;
}
````
