### ISSUE TITLE
@suppress doesn't work in some cases

### ISSUE THREAD

**Issue by nazar-pc** [google/closure-compiler#2621]
In my case `@suppress` doesn't work in a big file, but starts working as soon as I make it smaller.
Demo: https://github.com/nazar-pc/closure-compiler-bug-suppress

**Comment by MatrixFrog** [comment]
It looks like the compiler is considering the jsdoc to be attached to the assignment `module.exports = function(...` rather than the function itself. Removing the parentheses might help; I'm not sure. However, what I think will work is

```
/**
 * @fileoverview
 * @suppress {uselessCode}
 */
```

which applies the suppression to the entire file.

**Comment by nazar-pc** [comment]
Did you happen look at `good.js` and not `bad.js`?
I'm trying to get warning suppressed for `asm` function from `bad.js` file (in the middle of it, search for `@suppress`.

Also in trivial examples from few lines that are similar to `bad.js` suppression works correctly.

Entire file is not a solution too, since outside of `asm` function there might be valid warnings that I'd like to catch and fix.

**Comment by MatrixFrog** [comment]
Yes I did, but I mixed up which one was good and which was bad, sorry. In bad.js, is the right side of the var statement just a function, or is it an IIFE? If it's an IIFE then the jsdoc will attach to the var statement, not the function, but you could fix it by doing this (admittedly awkward) thing:

`var asm = (/** @suppress {uselessCode} */ function() {...})();`

**Comment by nazar-pc** [comment]
It was indeed IIFE and you suggestion helped, thank you!
Feel free to close the issue if this is not something you're going to be improving.

**Comment by MatrixFrog** [comment]
Supporting the output of other compilers (asm.js, Coffeescript, ...) is generally tricky so yeah this is probably not going to change very soon.
