### ISSUE TITLE
Rename but not optimize

### ISSUE THREAD

**Issue by JohannBlake** [google/closure-compiler#2623]
I would like to break my app into multiple modules that compile separately. The documentation indicates that this should be avoided as it is almost certain to break your code. I have found this to be true.

Forcing all the code into a single module that gets compiled has some major drawbacks. I am developing an Electron app and it would be nice if certain parts of the app could be updated periodically by downloading the minified compiled module that it needs. Unfortunately this is not possible due to the compiler breaking the code.

A solution I would love to have is simply to have the Closure Compiler rename variables but dispense with the optimization. I don't need optimization. I only want renaming to provide some minimal amount of protection of my intellectual property. Since Electron apps are intended to be downloaded and installed, optimization has a pretty low priority, unlike websites that do need optimization because they get accessed constantly.

Any chance of providing a feature to do renaming but disable optimization?

**Comment by brad4d** [comment]
@JohannBlake
It's both the renaming and code removal that prevent you from breaking a project into separately compiled modules in the first place. The compiler has to know about all the code to guarantee it can consistently rename things across all uses and definitions and can correctly recognize code that is unused.

If you want to break a project into pieces, we typically suggest that you define APIs that link the pieces, mark those API classes and methods with `@export` and explicitly export them with `goog.export`. Then you use your own custom externs files for part A of your project when compiling part B that needs to talk to it.

However, that's all about preventing unwanted renaming and code removal. You're asking to keep renaming for purposes of obfuscation, but still allow separate compilation. This would require creation of some way to synchronize the renaming across multiple compilations. I don't think we're likely to support that. Sorry.

**Comment by ChadKillingsworth** [comment]
Code splitting is definitely supported - it just needs to be done in a single compilation: https://stackoverflow.com/a/10401030/1211524

**Comment by JohannBlake** [comment]
@brad4d I was referring to obfuscation. There is nothing to stop you from obfuscating and using exports at the same time. But the issue I'm raising is more like this:

You compile your app into components and package them as a single delivery. You then update one component and want to send that to the client where it should replace the older component. In reality, even if the GCC has all the code available in the initial compilation and resolves everything, it can still generate a compiled component that will not work with the rest of the app. I have seen this. You can create a function in one module that when compiled creates code in such a way that variables are created outside of the function with the same name as functions or variables in other modules causing the instance variables to be overwritten during runtime.

The proper way to do obfuscation is just to rename stuff without optimizing it. The code itself should never be altered other than the renaming.

As it stands, the suggestion on Google's site for the GCC states clearly that you should not compile your code in separate modules.

**Comment by ChadKillingsworth** [comment]
Code splitting is the mechanism you have to do renaming across separate files - and is what is used to accomplish renaming across files.

In ADVANCED mode, closure-compiler cannot properly rename properties without the entire set of code. We call it "whole world optimization". It's the only way to safely rename properties.

The optimizations are not the problem.

If you are trying to accomplish something akin to webpack's hot module replacement - it just isn't supported. We don't support incremental compilation of a subset.

The only way to accomplish this is use simple mode, or use externs and exports as @brad4d suggested.

**Comment by JohannBlake** [comment]
@ChadKillingsworth The optimization is definitely the problem. If I make significant coding changes in one module and recompile the entire app again, many variables will get renamed and not just the ones in the module I modified. That means, that if I sent only the modified module to the client, it would almost certainly fail.

**Comment by ChadKillingsworth** [comment]
It will not fail if you use exports and externs. Other module's variables will be renamed, but you shouldn't care. Their public signatures will remain unchanged.

**Comment by JohannBlake** [comment]
@ChadKillingsworth Sure, the public signatures will remain the same but you are forgetting that optimization can and does create code outside of functions in order to support those functions in an optimized way. This isn't an issue if you plan on sending the entire javascript code to the client and not just the modified module. This is typical of most websites. However, I am working on an Electron app where the entire javascript is packaged and delivered with the app. The javascript is not downloaded from a backend. That means that you have to employ some mechanism to update the javascript. One method is to update the entire app, which is what apps like Slack do. But a more efficient approach is to update only the modules that need updating. So even if the signatures remain the same, the optimized code that gets generated outside of that function is bound to collide with code that already exists in an older version of the app on the client's computer.
