### ISSUE TITLE
Webgl 2.0 externs

### ISSUE THREAD

**Issue by rosw12** [google/closure-compiler#2624]
Webgl 2.0 is now supported by chrome and firefox, but the externs are not yet present.

**Comment by brad4d** [comment]
@rosw12 do you have a link to specifications for the WebGL 2.0 API you could add to this issue?
Thanks.

**Comment by rosw12** [comment]
https://www.khronos.org/registry/webgl/specs/latest/2.0/

**Comment by brad4d** [comment]
@rosw12 
Thanks. That'll be a big help to whoever picks this up to create a pull request.

**Comment by rosw12** [comment]
One of the biggest points is WebGLRenderingContext.texSubImage2D, particularly for users looking to achieve 0 warnings. This triggers an "actual parameter does not match formal parameter" warning which I was unable to suppress. This function cannot be added to a custom extern file because the webgl 1.0 version is already defined in externs/browser/webgl.js.  

My temporary workaround to suppress this warning is to use texSubImage2D.apply(...)

**Comment by Dirklectisch** [comment]
The externs for WebGL2 have been added back in may. This issue can be closed.

https://github.com/google/closure-compiler/commit/827ad5437bc6d3d3968ca01a33afdc59333efbf7
