### ISSUE TITLE
Support type inference for record types

### ISSUE THREAD

**Issue by blickly** [google/closure-compiler#263]
This issue was imported from Closure Compiler's previous home at http://closure-compiler.googlecode.com

The original discussion is archived at:
http://blickly.github.io/closure-compiler-issues/#953

**Comment by Dominator008** [comment]
Input:
```js
/** @typedef {{a:string, b:function(boolean)}} */
var x;

/** @param {{x:function(boolean)}} a */
function f(a) {};

f({x:function(a) {
  /** @type {number} */
  var warn1 = a;
}});

/** @param {function(boolean)} a */
function g(a) {};

g(function(a) {
  /** @type {number} */
  var warn2 = a;
});
```
NTI gives 2 warnings.

**Comment by dimvar** [comment]
Closing since we're only making top-priority changes in the old type checker.
