### ISSUE TITLE
Using code from CJS module in ES6 module will try to access non-existing default property

### ISSUE THREAD

**Issue by Deraen** [google/closure-compiler#2634]
Found a problem with React-leaflet (which is written in ES6) which uses prop-types (CommonJS). The code converted from ES6 module, tries to access `default` property in the converted CommonJS module, which will fail, as CommonJS module doesn't export `default` property:

```
❯ cat default-problem.js  
import Foo from './foo';

Foo.oneOfType();

❯ cat foo.js              
module.exports = {
  oneOfType: function() {
    return true;
  }
};

❯ java -jar target/closure-compiler-1.0-SNAPSHOT.jar --js foo.js default-problem.js  --process_common_js_modules --module_resolution NODE

var module$foo={oneOfType:function(){return!0}};
var module$default_problem={};
module$foo.default.oneOfType();
//          ^
//          Problem, should bee just module$foo.oneOfType
```

**Comment by blickly** [comment]
In ES6 modules,
```javascript
import Foo from './foo';
```
is just syntactic sugar for
```javascript
import {default as Foo} from './foo';
```
so unless I'm misunderstanding, I think this example is WAI

**Comment by ChadKillingsworth** [comment]
@blickly So the problem here is that other transpilers add a special property definition to ES6 modules so that `import Foo from './foo';` is actually `import * as Foo from './foo'` when './foo' is a common js module.

I neither agree with this nor encourage it, but it is very common.

**Comment by blickly** [comment]
I thought TypeScript had a special non-JS syntax for this pattern that was something like
```typescript
import Foo = require('./foo');
```
to not avoid changing the meaning of native ES6 syntax, but still have some way of importing the entire "bag". But I'm not as familiar with the other transpilers.

**Comment by ChadKillingsworth** [comment]
Well in the case above, it would be fixed with:

```js
import * as Foo from './foo';
```

That gives you the export object directly.

**Comment by blickly** [comment]
Good point

**Comment by Deraen** [comment]
This use is encouraged by prop-types readme, so I think this might quite common in React libs written in ES6 and using prop-types: https://github.com/facebook/prop-types#importing

**Comment by Deraen** [comment]
And so does React guide: https://facebook.github.io/react/docs/installation.html#hello-world-with-es6-and-jsx (React is CommonJS module also)

**Comment by ChadKillingsworth** [comment]
I don't know that this can be solved by Closure-compiler. It's highly dependent on the way Babel decided to transpile modules and requires knowing what type of module you are importing.

Closure-compiler rewrites a module in isolation. One file at a time.

**Comment by Deraen** [comment]
Could this issue be opened to keep track of how common this problem is? And to keep track of possible fixex, if such can be found later.

**Comment by ChadKillingsworth** [comment]
I guess I would be ok with injecting:

```js
module.exports.default = module.exports;
```

That would support interop. It's not technically correct, but I feel like this is a losing battle.

**Comment by blickly** [comment]
Sounds reasonable to me.

**Comment by teppeis** [comment]
According to [the latest spec](https://github.com/nodejs/node-eps/blob/master/002-es-modules.md#46-es-consuming-commonjs) of Node.js about interop between ESM and CJS,

> create an ESM with `{default:module.exports}` as its namespace

So all three import patterns should work.
```javascript
// foo.js
module.exports = {
  oneOfType: function() {
    return true;
  }
};

// import1.mjs
import foo from './foo';
foo.oneOfType();

// import2.mjs
import * as bar from './foo';
bar.default.oneOfType();

// import3.mjs
import {default as baz} from './foo';
baz.oneOfType();
```

Babel or other transpilers are not strict in the spec.

**Comment by ChadKillingsworth** [comment]
That spec is node specific - Closure-compiler is not. CommonJS is also not node specific (though that is by far the biggest use case).

Adding a default property to module.exports automatically is problematic in some cases:

```js
// Can't add a default property ...
module.exports = undefined;
module.exports = null;
module.exports = true;
module.exports = 4;
```

In cases where module.exports is an object, we could add a default property if it has not already been defined:

```js
if (module.exports !== null
    && typeof module.exports === "object"
    && typeof module.exports.default === "undefined") {
  module.exports.default = module.exports;
}
```

That would probably cover the vast majority of use cases.

**Comment by Deraen** [comment]
Exporting a function is also a common case.

Any pointers where this should be implemented? Es6RewriteModules visitExport maybe: https://github.com/google/closure-compiler/blob/master/src/com/google/javascript/jscomp/Es6RewriteModules.java#L287 ?

**Comment by ChadKillingsworth** [comment]
It needs added to the CommonJS rewriting (backwards of Babel). I'd add it right after this line: https://github.com/google/closure-compiler/blob/master/src/com/google/javascript/jscomp/ProcessCommonJSModules.java#L132

You'll need to guard it with an `if(finder.isCommonJsModule())` call.

**Comment by ChadKillingsworth** [comment]
Oh and you'll need to use the module name - not literally `module.exports`.

**Comment by Deraen** [comment]
Oh right, CommonJS processing. I was thinking backwards.

**Comment by ChadKillingsworth** [comment]
@Deraen I thought of a much better way to do this.

In common js module processing:

- Change the module rewrite name to be of the form `moduleName + "_cjs"`.
- Change all `require(path)` type statements to be rewritten `moduleName + "_cjs"`.
- Add a `/** @const */ var moduleName = { default: moduleName + "_cjs" }` statement to the end of the cjs script

In ES6 rewritting (when commonjs processing is enabled):

- Add a `/** @const */ var moduleName_cjs = modulename;` statement to the bottom of the script

This should fully support interop and provide better dead code elimination.

**Comment by ChadKillingsworth** [comment]
We would also need to check that typechecking is preserved across these aliases.

**Comment by ChadKillingsworth** [comment]
I have a fix for this. It's blocked by #2641
