### ISSUE TITLE
Can't use @lends on prototypes in ES6, CommonJS modules

### ISSUE THREAD

**Issue by rconnamacher** [google/closure-compiler#2639]
Closure Compiler produces a warning when using `@lends` with the prototype of a class if it's in an ES6 module.

```js
export class MyClass {}

Object.defineProperties(MyClass.prototype, /** @lends {MyClass.prototype} */ {
  name: {
    get: function() {
      return "Hello There";
    }
  }
});
```

```
JSC_UNKNOWN_LENDS: Variable MyClass.prototype not declared before @lends annotation. at line 3 character 77
Object.defineProperties(MyClass.prototype, /** @lends {MyClass.prototype} */ {
                                                                             ^
JSC_INEXISTENT_PROPERTY: Property name never defined on MyClass at line 12 character 26
console.log(new MyClass().name);
```

This same code produces no warnings when not in an ES6 module.

It makes no difference if it's in ES5 constructor/prototype syntax: defining MyClass with `function MyClass() {}` still produces the error.

(Bug still exists as of v20180506)

**Comment by rconnamacher** [comment]
Closure Compiler Service link: https://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%2540compilation_level%2520ADVANCED_OPTIMIZATIONS%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250Aexport%2520class%2520MyClass%2520%257B%257D%250A%250AObject.defineProperties(MyClass.prototype%252C%2520%252F**%2520%2540lends%2520%257BMyClass.prototype%257D%2520*%252F%2520%257B%250A%2520%2520%2509name%253A%2520%257B%250A%2520%2520%2520%2520%2520%2509%2509get%253A%2520function()%2520%257B%250A%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520return%2520%2522Hello%2520There%2522%253B%250A%2520%2520%2520%2520%2520%2520%2520%2520%257D%250A%2520%2520%2520%2520%257D%250A%257D)%253B%250A%250A%250Aconsole.log(new%2520MyClass().name)%253B

**Comment by rconnamacher** [comment]
Update: it doesn't matter if the class is exported, only if it's in a module.

This doesn't produce a warning, when not interpreted as an ES6 module:

```js
class Class { }

Object.defineProperties(Class.prototype, /** @lends Class.prototype */ {
    name: {
        value: "Steve"
    }
});

window['Class'] = Class;
```

```
$ java -jar node_modules/google-closure-compiler/compiler.jar  --compilation_level=ADVANCED bug-reductions/* --entry_point=bug-reductions/lends.js 
function a(){}Object.defineProperties(a.prototype,{name:{value:"Steve"}});window.Class=a;
```

But, this does produce the warning (only difference being the `import` statement at top):

```js
import "./empty.js";

class Class { }

Object.defineProperties(Class.prototype, /** @lends Class.prototype */ {
    name: {
        value: "Steve"
    }
});

window['Class'] = Class;
```

```
$ java -jar node_modules/google-closure-compiler/compiler.jar  --compilation_level=ADVANCED bug-reductions/* --entry_point=bug-reductions/lends.js 
bug-reductions/lends.js:5: WARNING - Variable Class.prototype not declared before @lends annotation.
Object.defineProperties(Class.prototype, /** @lends Class.prototype */ {
                                                                       ^

0 error(s), 1 warning(s), 100.0% typed
function a(){}Object.defineProperties(a.prototype,{name:{value:"Steve"}});window.Class=a;
```

**Comment by ray007** [comment]
It's also a problem with common-js modules, see https://groups.google.com/forum/#!topic/closure-compiler-discuss/OTbUD91vPws

**Comment by ray007** [comment]
Anything I could do to help this?
Caveat: not really a Java-programmer here...

**Comment by ray007** [comment]
This should be tagged as bug.

**Comment by lauraharker** [comment]
This was fixed in the v20181028 release by https://github.com/google/closure-compiler/commit/4b1a60c69c410ddc988f176167014d393909d836. Looks like we forgot to update this issue at the time, sorry about that.

The original repro does not error anymore.

**Comment by ray007** [comment]
The original warnings are gone, but now I got a type error:

Property definition:
```JS
Object.defineProperties(lwebControl.prototype, /** @lends lwebControl.prototype */ {
// more property definitions
// inverted flag
_visible: {
	/** @this {lwebControl} */
	get: function() {
		return !(this._appFlags & lwebAppFlags.CMF_HIDDEN);
	},
	/** @this {lwebControl} */
	set: function(value) {
		if (value)
			this._appFlags &= ~lwebAppFlags.CMF_HIDDEN;
		else
			this._appFlags |= lwebAppFlags.CMF_HIDDEN;
	}
},
});
```

Error message:
```
www/js/loytec/controls.js:1706: ERROR - condition always evaluates to true
left : {get: function(this:module$loytec$controls.default.lwebControl): ?, set: function(this:module$loytec$controls.default.lwebControl, ?): undefined}
right: boolean
	var chg = (this._visible !== vis);
	           ^^^^^^^^^^^^^^^^^^^^^
```

**Comment by ray007** [comment]
Update: the new error seems to be the same issue as #2439
