### ISSUE TITLE
[NTI] Infer const for namespaces

### ISSUE THREAD

**Issue by shicks** [google/closure-compiler#2643]
[debugger]

In migrating tests to NTI, I'm seeing a lot of cases where type checking falls down due to things like the following:

```js
var a = {};
/** @constructor */
a.B = function() {};

/** @param {!a.B} arg */
function f(arg) {}
```

This is fine in OTI, but NTI complains:

```
input0:5: WARNING - Type annotation references non-existent type a.B.
/** @param {!a.B} arg */
             ^^^
```

The warning can be fixed by adding `@const` to the namespace declaration, but if it's never reassigned, we should be able to infer that it's const and treat it as such.

[debugger]: https://closure-compiler-debugger.appspot.com/#input0%3Dvar%2520a%2520%253D%2520%257B%257D%253B%250A%252F**%2520%2540constructor%2520*%252F%250Aa.B%2520%253D%2520function()%2520%257B%257D%253B%250A%250A%252F**%2520%2540param%2520%257B!a.B%257D%2520arg%2520*%252F%250Afunction%2520f(arg)%2520%257B%257D%26input1%26conformanceConfig%26externs%3D%252F**%2520%2540constructor%2520*%252F%250Afunction%2520Function()%2520%257B%257D%250A%252F**%2520%2540constructor%2520*%252F%250Afunction%2520Object()%2520%257B%257D%26refasterjs-template%26CHECK_SYMBOLS%3D1%26MISSING_PROPERTIES%3D1%26TRANSPILE%3D1%26CHECK_TYPES%3D1%26CHECK_TYPES_NEW_INFERENCE%3D1%26CLOSURE_PASS%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1

**Comment by dimvar** [comment]
I think it's good to require the `@const`. It gives a uniform way of defining a namespace, rather than the compiler trying to be smart. (We allow omitting the `@const` in externs for legacy reasons.)
