### ISSUE TITLE
Remove assignment to superClass_ in $jscomp.inherits, or else add a regression test

### ISSUE THREAD

**Issue by shicks** [google/closure-compiler#2648]
The `$jscomp.inherits` polyfill assigns to the `superClass_` property of the subclass constructor.  Removing this does not cause any tests to fail, nor is the property read from anywhere, as far as I can tell.

If there's a reason it needs to exist, we should define a regression test to make this clear.  If not, we should remove it.

**Comment by brad4d** [comment]
This seems to be needed for internal google code that expects `superClass_`.

**Comment by brad4d** [comment]
I'll add a runtime test for the `superClass_` setting behavior.
