### ISSUE TITLE
Compilation bug of async/await

### ISSUE THREAD

**Issue by daoenpan** [google/closure-compiler#2651]
Compilation of await expression in function argument did not complete successfully. see

`async function foo() {
  console.log(await aget());
}`

[snippet](https://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540compilation_level%2520SIMPLE_OPTIMIZATIONS%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250A%252F%252F%2520ADD%2520YOUR%2520CODE%2520HERE%250Aasync%2520function%2520foo()%2520%257B%250A%2520%2520console.log((await%2520aget()))%253B%250A%257D%250A%250A%250A)

**Comment by MatrixFrog** [comment]
I think you can fix this by manually extracting the await expression:

```
async function foo() {
  let temp = await aget();
  console.log(temp);
}
```

so I'll mark this as a feature request for the compiler to do that extraction automatically.

**Comment by brad4d** [comment]
If you know your code won't run on old IE8 browsers, you can specify the 
`--allow_method_call_decomposing` flag to allow code like this to transpile.
