### ISSUE TITLE
Why not an option for dropping of console.* statements?

### ISSUE THREAD

**Issue by vitaly-zdanevich** [google/closure-compiler#2656]
As I understand now I can drop `console.*` statements only using such construct:

```
if (DEBUG) {
  console.log();
}
```
For me it is strange - why not an option? [Uglify-es has an option `drop_console`](https://github.com/mishoo/UglifyJS2/tree/harmony#compress-options).

**Comment by ChadKillingsworth** [comment]
Questions on features should be posted to the [Mailing List](https://groups.google.com/forum/#!forum/closure-compiler-discuss)
