### ISSUE TITLE
Fail to resolve node module when using compiler options --module_resolution NODE and --process_common_js_modules

### ISSUE THREAD

**Issue by jbeard4** [google/closure-compiler#2659]
Please see the following reduced test case: https://github.com/jbeard4/test-closure-compiler

This is a minimal example that attempts to use closure compiler options `--module_resolution NODE` and `--process_common_js_modules` in order to resolve the tiny-events node module. I have attempted to compile with the following options:

`java -jar node_modules/google-closure-compiler/compiler.jar --module_resolution NODE --entry_point index.js --js_output_file dist/test.js --js index.js --process_common_js_modules`

This results in the following error:

```
index.js:1: WARNING - Failed to load module "tiny-events"
const EventEmitter = require('tiny-events').EventEmitter;
                     ^

0 error(s), 1 warning(s)
```

When I remove the option --process_common_js_modules option, compilation succeeds, but the resulting file dist/test.js does not include the tiny-events module.

Is there a way to use the closure compiler to compile a node module  that requires other node modules, and include the contents of the node module dependency in the resulting browser build?

Tested using closure compiler version:
Version: v20170910
Built on: 2017-09-12 14:27

**Comment by ChadKillingsworth** [comment]
You aren't passing source files from node_modules into the compiler. You need to include flags like `--js node_modules/tiny-events/**/*.js --js node_modules/tiny-events/package.json`.

The compiler doesn't discover and add files from disk - you have to provide the full source set.

**Comment by jbeard4** [comment]
Thank you for the quick reply. I wanted to confirm that the following command successfully compiled:

java -jar node_modules/google-closure-compiler/compiler.jar --module_resolution NODE --entry_point index.js --js_output_file dist/test.js --js index.js --process_common_js_modules --js node_modules/tiny-events/lib/index.js --js node_modules/tiny-events/package.json
