### ISSUE TITLE
Spread operator fails on Set when specified as param type

### ISSUE THREAD

**Issue by jbeard4** [google/closure-compiler#2660]
Please consider the following reduced example:

The following program compiles successfully using the following options:

`java -jar node_modules/google-closure-compiler/compiler.jar --compilation_level ADVANCED --js_output_file dist/test3.js --js test3.js`

```js
const x = new Set(['foo','bar','bat']);
const y = [...x];
y.forEach(z => console.log(z))
```

However the following fails to compile with the following error:

```js
const x = new Set(['foo','bar','bat']);

/**
 * @param {Set<string>} n
 */
function foo(n){
  const y = [...n];
  y.forEach(z => console.log(z))
}
```
```
found   : (Set<string>|null)
required: (Arguments<string>|Array<string>|Iterable<string>|string)
  const y = [...n];
                ^

0 error(s), 1 warning(s), 90.9% typed
```

The program successfully compiles when the `@param` directive is removed.

Is there a way to specify an ES6 Set as a param type such that the spread operator succeeds?

**Comment by MatrixFrog** [comment]
It looks like we just need to put an `@implements {Iterable<T>}` on the definition of `Set`

**Comment by MatrixFrog** [comment]
Scratch that. We already have it. I think the issue here is nullability. Just change the param to `{!Set<string>}` (or explicitly check for null and handle it in some way)

**Comment by jbeard4** [comment]
Thank you for the quick reply.
