### ISSUE TITLE
Object.assign polyfill should work with Structural Interfaces

### ISSUE THREAD

**Issue by anthonytordillos** [google/closure-compiler#2670]
```
/** @record */
class SampleType {
  constructor() {
    /** @type {boolean} */
    this.works;
  }
}

// Passes type check.
const /** !SampleType */ x1 = {works: true};
// Fails.
const /** !SampleType */ x2 = Object.assign({}, {works: true});
```

Object.assign is a useful construct for working with immutable data, and is common when working with frameworks like [Redux](http://redux.js.org/docs/basics/Reducers.html).

**Comment by MatrixFrog** [comment]
@dimvar would it make sense for the NTI to have a special understanding of what `Object.assign`'s type is: If the second arg is an object literal, then the return type is the type of the first arg, plus the fields from the second arg, or something like that.

**Comment by dimvar** [comment]
Yes, we can do that.
