### ISSUE TITLE
@template with lower-case variables gives inscrutable error

### ISSUE THREAD

**Issue by DavidSouther** [google/closure-compiler#2679]
Code:

```
/**
 * @template U, k
 * @param {?} router
 * @param {?} url
 * @param {?} params
 * @return {?}
 */
function debugNavigate(router, url, params) {
    const /** @type {?} */ link = url.prefilledLink();
    for (const [param, value] of params) {
        link.set(param, value);
    }
    const /** @type {?} */ built = link.build();
    router.navigate(built, { queryParamsHandling: 'merge' });
}
```

Error:

ERROR: 
[com.google.javascript.modules.compiler.ErrorManager.printSummary] 1 error(s):
[redacted path]/index.js:53:
Originally at:
[redacted path]/index.ts:39: ERROR - Bad type annotation. Invalid type name(s) for @template annotation. See https://github.com/google/closure-compiler/wiki/Bad-Type-Annotation for more information.

Bug:

https://github.com/google/closure-compiler/wiki/Bad-Type-Annotation has no mention that template generics must be uppercase.

**Comment by MatrixFrog** [comment]
`@template` types must start with a capital letter: https://github.com/google/closure-compiler/blob/master/src/com/google/javascript/jscomp/parsing/JsDocInfoParser.java#L1296-L1303

I don't remember why this restriction is in place, so I'm inclined to say we should remove it. But if we don't then we should document it better.

**Comment by DavidSouther** [comment]
Yeah I don't see how I'd have ever gotten to that information from the link provided in the error ;)
