### ISSUE TITLE
OTI does infer return type of un-annotated functions.

### ISSUE THREAD

**Issue by jplaisted** [google/closure-compiler#2681]
```
/** @type {number} */
var item = 42;

/** @return {!Promise<string>} */
function bar() {
  return Promise.resolve().then(() => { return item; });
}
```

Expecting an error that the return type of the function is Promise<string> but really is Promise<number>. NTI seems to handle this correctly.

[Repo case](https://closure-compiler-debugger.appspot.com/#input0%3D%252F**%2520%2540type%2520%257Bnumber%257D%2520*%252F%250Avar%2520items%2520%253D%25202%253B%250A%250A%252F**%2520%2540return%2520%257B!Promise%253Cstring%253E%257D%2520*%252F%250Afunction%2520foo()%2520%257B%250A%2520%2520return%2520Promise.resolve().then(()%2520%253D%253E%2520%257B%2520return%2520items%253B%2520%257D)%253B%250A%257D%250A%250A%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3Dtrue%26CHECK_SYMBOLS%3Dtrue%26MISSING_PROPERTIES%3Dtrue%26TRANSPILE%3Dtrue%26CHECK_TYPES%3Dtrue%26CLOSURE_PASS%3Dtrue%26PRESERVE_TYPE_ANNOTATIONS%3Dtrue%26PRETTY_PRINT%3Dtrue)

**Comment by jplaisted** [comment]
Drilling down more generally it seems that return types from anonymous functions are just incorrect.

```
/** @type {number} */
var items = 2;

/** */
function bar() {
  var s = function() { return items; };
  wantStringFn(s);
}


/** @param {!function(): string} fn */
function wantStringFn(fn) {}
```
[Link](https://closure-compiler-debugger.appspot.com/#input0%3D%252F**%2520%2540type%2520%257Bnumber%257D%2520*%252F%250Avar%2520items%2520%253D%25202%253B%250A%250A%252F**%2520*%252F%250Afunction%2520bar()%2520%257B%250A%2520%2520var%2520s%2520%253D%2520function()%2520%257B%2520return%2520items%253B%2520%257D%253B%250A%2520%2520wantStringFn(s)%253B%250A%257D%250A%250A%250A%252F**%2520%2540param%2520%257B!function()%253A%2520string%257D%2520fn%2520*%252F%250Afunction%2520wantStringFn(fn)%2520%257B%257D%26input1%26conformanceConfig%26externs%26refasterjs-template%26CHECK_SYMBOLS%3Dtrue%26MISSING_PROPERTIES%3Dtrue%26TRANSPILE%3Dtrue%26CHECK_TYPES%3Dtrue%26CLOSURE_PASS%3Dtrue%26PRESERVE_TYPE_ANNOTATIONS%3Dtrue%26PRETTY_PRINT%3Dtrue)

[Explicitly stating ](https://closure-compiler-debugger.appspot.com/#input0%3D%252F**%2520%2540type%2520%257Bnumber%257D%2520*%252F%250Avar%2520items%2520%253D%25202%253B%250A%250A%252F**%2520*%252F%250Afunction%2520bar()%2520%257B%250A%2520%2520%252F**%2520%2540type%2520%257B!function()%253A%2520number%257D%2520*%252F%2520%250A%2520%2520var%2520s%2520%253D%2520function()%2520%257B%2520return%2520items%253B%2520%257D%253B%250A%2520%2520wantStringFn(s)%253B%250A%257D%250A%250A%250A%252F**%2520%2540param%2520%257B!function()%253A%2520string%257D%2520fn%2520*%252F%250Afunction%2520wantStringFn(fn)%2520%257B%257D%26input1%26conformanceConfig%26externs%26refasterjs-template%26CHECK_SYMBOLS%3Dtrue%26MISSING_PROPERTIES%3Dtrue%26TRANSPILE%3Dtrue%26CHECK_TYPES%3Dtrue%26CLOSURE_PASS%3Dtrue%26PRESERVE_TYPE_ANNOTATIONS%3Dtrue%26PRETTY_PRINT%3Dtrue)the type of the function causes an error.

**Comment by dimvar** [comment]
Yes, it's a known limitation of the old type checker that it doesn't infer signatures for unannotated functions. It's not something that can be easily changed.
