### ISSUE TITLE
String with quotes are renamed

### ISSUE THREAD

**Issue by exotfboy** [google/closure-compiler#2682]
I am building an application, and use the `Advanced` compile mode, and find that the string with quote are renamed.

The compiled codes with `debug` throw errors like this:

![image](https://user-images.githubusercontent.com/16457917/31920497-ff74f79c-b89b-11e7-8159-bbb4939ad8e4.png)
![image](https://user-images.githubusercontent.com/16457917/31920575-84b3abec-b89c-11e7-99cc-98b5b72c8863.png)

And  this is the sources  for `if ($candidate$jscomp$1$$.$a$($rendererType$$)) {`   :

`if (candidate['handles'](rendererType)) {` 

You can find the full codes [here](https://github.com/openlayers/openlayers/blob/master/src/ol/pluggablemap.js#L1421)

Note the undefined `$a` is indeed `['handles']`, but why it is renamed ?

BTW, I use [closure-util ](https://github.com/openlayers/closure-util)  with the following config:
```
{
  "lib": [
	"node_modules/openlayers/src/**/*.js",
	"node_modules/openlayers/build/ol.ext/**/*.js",
	"src/**/*.js"
  ],
  "compile": {
	"externs": [
	  "node_modules/openlayers/externs/bingmaps.js",
	  "node_modules/openlayers/externs/cartodb.js",
	  "node_modules/openlayers/externs/closure-compiler.js",
	  "node_modules/openlayers/externs/esrijson.js",
	  "node_modules/openlayers/externs/geojson.js",
	  "node_modules/openlayers/externs/proj4js.js",
	  "node_modules/openlayers/externs/tilejson.js",
	  "node_modules/openlayers/externs/topojson.js"
	],
	"define": [
	  "ol.ENABLE_WEBGL=false"
	],
	"js": [
	  "node_modules/openlayers/src/ol/typedefs.js",
	  "node_modules/openlayers/externs/olx.js",
	  "node_modules/openlayers/externs/oli.js"
	],
	"extra_annotation_name": [
	  "api", "observable"
	],
	"rewrite_polyfills": "false",
	"compilation_level": "ADVANCED",
	"output_wrapper": "(function(){%output%})();",
	"manage_closure_dependencies": true,
	"use_types_for_optimization": true,
	"debug":true
  }
}

```

**Comment by MatrixFrog** [comment]
Hm yeah that definitely should not happen! Is it possible that closure-util is somehow compiling everything twice by accident, or running the code through some other tool first, before it invokes the closure compiler?

**Comment by exotfboy** [comment]
You mean this maybe caused by `closure-util` instead of `closure-compiler` itsefl? 😆

**Comment by MatrixFrog** [comment]
It is possible. I haven't looked at what closure-util does. If you can figure out a minimal reproduction with just the compiler itself that would be great.

**Comment by exotfboy** [comment]
I can not provide the reproduction at the moment, but I tried to print the commands:

`java -server -XX:+TieredCompilation -jar D:/ws/app-root/node_modules/closure-util/.deps/compiler/416a3e2f199e3b8ae5c051ece4b8ef57dc365ec0/closure-compiler-v20170910.jar --flagfile=C:\Users\xx\AppData\Local\Temp\compile-flags-117924-1692-12esseb.g5ylvaq0k9.txt
`

And the flagfile can be found [here]([url](https://gist.github.com/exotfboy/dd9b831f9aae346482e099cd64dac9c8)).

**Comment by fredj** [comment]
It was an issue in OpenLayers (fixed with https://github.com/openlayers/openlayers/pull/7333) not in closure-util or closure-compiler.

**Comment by MatrixFrog** [comment]
Cool, thanks.
