### ISSUE TITLE
NPE in NTI, ObjectType.isAmbiguousObject() for function(new:?)

### ISSUE THREAD

**Issue by supersteves** [google/closure-compiler#2687]
I came across this in some code of mine which uses this pattern to manage circular references:

``` javascript
goog.provide("ns1");

/** @constructor */
ns1 = function() {}

/**
 * @type {function(new:?)}
 */
ns1.something;
```
``` javascript
goog.provide("ns2");
goog.require("ns1");

/** @constructor */
ns2 = function() {}

ns1.something = ns2;
```
```
null
  Node(GETPROP): input0:9:0
ns1.something;
  Parent(EXPR_RESULT): input0:9:0
ns1.something;

	at com.google.javascript.jscomp.newtypes.ObjectType.isAmbiguousObject(ObjectType.java:1608)
	at com.google.javascript.jscomp.newtypes.JSType.isAmbiguousObject(JSType.java:2101)
	at com.google.javascript.jscomp.newtypes.JSType.isSomeUnknownType(JSType.java:1774)
	at com.google.javascript.jscomp.ConformanceRules$AbstractTypeRestrictionRule.isSomeUnknownType(ConformanceRules.java:291)
	at com.google.javascript.jscomp.ConformanceRules$BanUnknownTypedClassPropsReferences.checkConformance(ConformanceRules.java:1283)
```

In this case triggered by `BanUnknownTypedClassPropsReferences`.

I can solve this by using a tighter type annotation (not ? or *). But it's an internal compiler error you might want to know about.

https://closure-compiler-debugger.appspot.com/#input0%3Dgoog.provide(%2522ns1%2522)%253B%250A%250A%252F**%2520%2540constructor%2520*%252F%250Ans1%2520%253D%2520function()%2520%257B%257D%250A%250A%252F**%250A%2520*%2520%2540type%2520%257Bfunction(new%253A%253F)%257D%250A%2520*%252F%250Ans1.something%253B%250A%26input1%3Dgoog.provide(%2522ns2%2522)%253B%250Agoog.require(%2522ns1%2522)%253B%250A%250A%252F**%2520%2540constructor%2520*%252F%250Ans2%2520%253D%2520function()%2520%257B%257D%250A%250Ans1.something%2520%253D%2520ns2%253B%26conformanceConfig%3Drequirement%253A%2520%257B%250A%2520%2520type%253A%2520CUSTOM%250A%2520%2520java_class%253A%2520'com.google.javascript.jscomp.ConformanceRules%2524BanUnknownTypedClassPropsReferences'%250A%2520%2520error_message%253A%2520'blah%2520blah'%250A%257D%250A%26externs%26refasterjs-template%26includeDefaultExterns%3Dtrue%26CHECK_SYMBOLS%3Dtrue%26MISSING_PROPERTIES%3Dtrue%26CHECK_REQUIRES%3Dtrue%26CHECK_PROVIDES%3Dtrue%26TRANSPILE%3Dtrue%26CHECK_TYPES%3Dtrue%26CHECK_TYPES_NEW_INFERENCE%3Dtrue%26CLOSURE_PASS%3Dtrue%26PRESERVE_TYPE_ANNOTATIONS%3Dtrue%26PRETTY_PRINT%3Dtrue

**Comment by dimvar** [comment]
I fixed a NPE in this method just yesterday, should be pushed externally today. I'm guessing that will fix this issue as well.

**Comment by supersteves** [comment]
Confirmed.

**Comment by supersteves** [comment]
Thanks @dimvar
