### ISSUE TITLE
Spurious "property constructor on abstract class ... is not implemented by type" warning

### ISSUE THREAD

**Issue by supersteves** [google/closure-compiler#2688]
Closed source reproduction. Can't repro this in the debugger, but it's like this:

``` javascript
/** 
 * @abstract 
 * @extends SomethingFromExterns
 */
class A extends X {
  constructor(p) {
    super(p);
  }
  // some abstract methods
}

/**
 * @abstract 
 * @extends {A}
 */
class B extends A {
  constructor(p) {
    super(p);
  }
  // some implementations of abstract methods
  // some more abstract methods
}

/**
 * @extends {B}
 */
class C extends B {
  constructor(p) {
    super(p);
  }
  // all abstract methods implemented
}
```

```
path/to/C.js:20: WARNING - 
  property constructor on abstract class A$...$A is not implemented by type C$...$C
  18| class C extends B {
  19| 
  20|     constructor(p) {
  21|         super(p);
  22|     }
```

It appears that `TypeValidator.expectAbstractMethodsImplemented` is considering the `constructor` to be an abstract method, and probably wants to do something like `!maybeAbstractMethod.isConstructor()` at line 753. I think. Am I right? Or would this mask an underlying problem?

Although I don't know why I can't reproduce this in the [debugger](https://closure-compiler-debugger.appspot.com/#input0%3D%250A%252F**%2520%250A%2520*%2520%2540abstract%2520%250A%2520*%2520%2540extends%2520X%250A%2520*%252F%250Aclass%2520A%2520extends%2520X%2520%257B%250A%2520%2520constructor(p)%2520%257B%250A%2520%2520%2520%2520super()%253B%250A%2520%2520%257D%250A%257D%250A%250A%252F**%250A%2520*%2520%2540abstract%2520%250A%2520*%2520%2540extends%2520%257BA%257D%250A%2520*%252F%250Aclass%2520B%2520extends%2520A%2520%257B%250A%2520%2520constructor(p)%2520%257B%250A%2520%2520%2520%2520super(p)%253B%250A%2520%2520%257D%250A%257D%250A%250A%252F**%250A%2520*%2520%2540extends%2520%257BB%257D%250A%2520*%252F%250Aclass%2520C%2520extends%2520B%2520%257B%250A%2520%2520constructor(p)%2520%257B%250A%2520%2520%2520%2520super(p)%253B%250A%2520%2520%257D%250A%257D%250A%26input1%26conformanceConfig%26externs%3D%252F**%2520%2540type%2520%257Bfunction(new%253A%253F)%257D%2520*%252F%250Avar%2520X%253B%250A%26refasterjs-template%26includeDefaultExterns%3Dtrue%26CHECK_SYMBOLS%3Dtrue%26CHECK_MISSING_RETURN%3Dtrue%26CHECK_SUSPICIOUS_CODE%3Dtrue%26MISSING_PROPERTIES%3Dtrue%26CHECK_REQUIRES%3Dtrue%26CHECK_PROVIDES%3Dtrue%26CHECK_GLOBAL_NAMES%3Dtrue%26CHECK_DEPRECATED%3Dtrue%26CHECK_VISIBILITY%3Dtrue%26CHECK_CONSTANTS%3Dtrue%26CHECK_ES5_STRICT%3Dtrue%26CHECK_GLOBAL_THIS%3Dtrue%26CHECK_UNREACHABLE_CODE%3Dtrue%26TRANSPILE%3Dtrue%26CHECK_TYPES%3Dtrue%26CHECK_TYPES_NEW_INFERENCE%3Dtrue%26CHECK_REPORT_MISSING_OVERRIDE%3Dtrue%26CLOSURE_PASS%3Dtrue%26PRESERVE_TYPE_ANNOTATIONS%3Dtrue%26PRETTY_PRINT%3Dtrue). Perhaps it's because I'm running in checks-only mode. This has been introduced sometime since the March version, probably.

**Comment by dimvar** [comment]
The old type checker is in maintenance mode at this point, so we're unlikely to fix this. If you see a similar issue with NTI, let us know.
