### ISSUE TITLE
Expose an option to turn off mangling

### ISSUE THREAD

**Issue by gaearon** [google/closure-compiler#2690]
Hey! I chatted a bit with @MatrixFrog, and he asked me to file an issue.

We recently started using GCC for building [React](https://github.com/facebook/react) and are loving it! Unfortunately, we can only use GCC for the open source builds, and not the ones we use at Facebook.

For the Facebook builds, we could only use GCC if there was an option to turn off name mangling in simple mode. We have our own minifier, and we can’t check in minified code into the repository as it makes debugging traces very difficult. Even if we checked in sourcemaps, those wouldn’t work with our internal tooling.

Currently, we use Uglify for internal builds. It provides a `mangle: false` option that keeps dead code elimination and other optimizations, but doesn’t transform the names. I am asking to provide a similar option for GCC so that we can use excellent other GCC optimizations while keeping the production build source human-readable. Our ideal setup right now would be GCC in simple mode with turned off mangling + Prettier for formatting the output nicely.

I recognize options are a huge maintenance burden and totally understand if that’s not something you would consider. We would very much appreciate even an “unofficial” flag though.

Thanks.

**Comment by ChadKillingsworth** [comment]
By name mangling, you mean any type of local variable renaming?

**Comment by ChadKillingsworth** [comment]
And one more question, are you using any module rewriting? (ES6, CommonJS, etc)

**Comment by gaearon** [comment]
Yes, I mean renaming of variables and functions in the simple mode.

>are you using any module rewriting? (ES6, CommonJS, etc)

We are compiling CommonJS (and soon ES6) with Rollup, and running GCC on the output.

**Comment by ChadKillingsworth** [comment]
@gaearon Can you test a custom build? In theory we should just be able to set the renaming policies to "OFF".

If you build from this branch: https://github.com/ChadKillingsworth/closure-compiler/tree/renaming-flag you should be able to test out a `--renaming=false` flag.

If it works for you, I'll PR it to the main repository and probably even publicly advertise it.

**Comment by gaearon** [comment]
I haven't built from source yet but can give it a try on Monday. We're currently using the JS version but as I understand this is the upstream so it needs to be added here first.

**Comment by ChadKillingsworth** [comment]
I can make a build for you. Just email me and I'll send you a link - but it will be the Java version. Adding flags is a bit different for the JS version.

**Comment by gaearon** [comment]
Emailed. If this works for us and you get it merged, what steps do we need to do to expose it on JS version? I'm happy to spend a few days myself if that's something I could contribute.

**Comment by anmonteiro** [comment]
@gaearon adding it to the JavaScript version should be just a matter of changing the `GwtRunner` class (https://github.com/google/closure-compiler/blob/master/src/com/google/javascript/jscomp/gwt/client/GwtRunner.java)

**Comment by gaearon** [comment]
Would that need to be done on top of @ChadKillingsworth’s branch, or is master enough?

**Comment by ChadKillingsworth** [comment]
I can do it to both in the same PR.

**Comment by gaearon** [comment]
That would be super sweet. Would I still need to try the Java version to confirm the behavior works for us?

**Comment by gaearon** [comment]
Is there anything I could do to help?

**Comment by ChadKillingsworth** [comment]
@gaearon Did you get my email with the custom build link?

**Comment by gaearon** [comment]
Yes! Sorry, was checking the wrong email.

I can look into getting the Java version to work, but there's a simple way to expose it on the JS version that would be amazing. Although I understand it's more limited. (I'd love to know why btw. I thought it's just compiled to JS somehow, why is it less powerful?)

**Comment by ChadKillingsworth** [comment]
I believe parsing is considerably slower. Stack traces from compiler crashes are not great. All the core devs work with the Java version.

The JS version is definitely viewed as experimental. While it's the same core code base that gets transpiled down, there is logic that cannot be shared. Particularly the logic around flags and starting a compile job. It's always just the last piece that gets attention.

There are also advanced features (such as restricting code patterns) that are simply not available in JS version.

**Comment by gaearon** [comment]
I have a PR that does what I want in https://github.com/google/closure-compiler/pull/2707.
Thanks everyone for discussion, and I hope this is something you’d consider merging.

**Comment by gaearon** [comment]
Fixed via #2707.
