### ISSUE TITLE
CommonJS rewriting is being skipped for explicit deps entry points

### ISSUE THREAD

**Issue by supersteves** [google/closure-compiler#2692]
CommonJS module rewriting isn't happening in particular cases. I'm finding `require("...")` calls left in the output.

In this case I'm using the Compiler via the Java API in a continuous build+test process, in checks-only mode primarily to identify developer errors but also using the bundled output as part of a jasmine unit test. This process of ours detects developer edits and only builds those compilation units (and their dependencies) that were edited. In the example below, TestGoogModOnly.js was edited by a developer, and thus triggering compilation with TestGoogModOnly as the explicit entry point.

I've narrowed the test case down to:
* Dep management: prune, drop moochers
* Entry point in DependencyOptions: `es6modulesdemo.sub.TestGoogModOnly`
* Enable CJS modules rewriting

TestEs6Only.js:
``` javascript
export default "TestEs6Only";
```
TestGoogModOnly.js:
``` javascript
goog.module("es6modulesdemo.sub.TestGoogModOnly");
goog.module.declareLegacyNamespace();
let t = require("./TestEs6Only");
```

Output:
``` javascript
var es6modulesdemo = {};
es6modulesdemo.sub = {};
es6modulesdemo.sub.TestGoogModOnly = {};
var module$contents$es6modulesdemo$sub$TestGoogModOnly_t = require("./TestEs6Only");
```

I've narrowed down the problem to the logic in `Compiler.findDependenciesFromEntryPoints`. Here, TestGoogModOnly is present in `inputsByProvide` keyed by `es6modulesdemo.sub.TestGoogModOnly`. But in [Compiler:1957](https://github.com/google/closure-compiler/blob/a71036ea696ba5ec600f9dcb9c2c787084032986/src/com/google/javascript/jscomp/Compiler.java#L1957) it's being looked up by `module$...` internal path-based provide name. As such it never appears in entryPoints, and thus never in orderedInputs, and skipped from `ProcessCommonJSModules`. Effectively it's skipping any files from CJS rewriting if they can only be found from entry points given explicitly by dependency options.

I'm not sure if the fix is to lookup in inputsByProvide, or to change the end of the method to also iterate through skipped inputs, for CJS rewriting.

Perhaps @ChadKillingsworth will know about this?

**Comment by ChadKillingsworth** [comment]
I think your entry point is wrong - It should be `goog:es6modulesdemo.sub.TestGoogModOnly`. We have tests that cover using a goog module or provide as an entry point.

**Comment by supersteves** [comment]
@ChadKillingsworth, I'm using the Java API directly:
```
DependencyOptions depOptions = new DependencyOptions();
depOptions.setDependencyPruning(true);
depOptions.setDependencySorting(true);
options.setDependencyOptions(Arrays.asList(ModuleIdentifier.forClosure("es6modulesdemo.sub.TestGoogModOnly")));
```

**Comment by ChadKillingsworth** [comment]
@supersteves I think you'll need to create a repo case using the command line version.

**Comment by supersteves** [comment]
@ChadKillingsworth It took a little while as we always use the Java API. [Here's the test case attachment](https://github.com/google/closure-compiler/files/1430243/cc.bug.zip); I've narrowed it down as much as possible. It uses the latest release JAR (v20171023).



Command:
```
java -jar closure-compiler-v20171023.jar --entry_point goog:test.TestGoogModOnly --module_resolution NODE  --dependency_mode STRICT  --process_common_js_modules --externs require.js --js **/*.js --language_in ECMASCRIPT_2015 --new_type_inf --warning_level VERBOSE --formatting PRETTY_PRINT
```
Output:
``` javascript
var module$exports$test$TestGoogModOnly = {}, module$contents$test$TestGoogModOnly_t = require("../TestEs6Only");
```

**Comment by supersteves** [comment]
In case it makes it easier to eyeball this issue, the attachment and issue in general can be summarised as:

require.js:
(to suppress a secondary error which would otherwise halt compilation).
``` javascript
/**
 * @param  {string} module
 * @return {*}
 */
var require = function(module) { return {}; };
```

test/TestGoogModOnly.js:
``` javascript
goog.module("test.TestGoogModOnly");
let t = require("../TestEs6Only");
```

TestEs6Only.js:
``` javascript
export default "TestEs6Only";
```

build.bat:
```
java 
  -jar closure-compiler-v20171023.jar 
  --entry_point goog:test.TestGoogModOnly 
  --module_resolution NODE  
  --dependency_mode STRICT  
  --process_common_js_modules 
  --externs require.js --js **/*.js 
  --language_in ECMASCRIPT_2015 
  --new_type_inf 
  --warning_level VERBOSE 
  --formatting PRETTY_PRINT
```

Output:
```
var module$exports$test$TestGoogModOnly = {}, 
    module$contents$test$TestGoogModOnly_t = require("../TestEs6Only"); // <<< Here be the problem
```

**Comment by supersteves** [comment]
@ChadKillingsworth (I think you're the expert in this area) - is there any chance you could eyeball this repro and give me an initial reaction? If it's not a bug, I'll need to figure out what I'm doing wrong. If it's a bug, but not a priority, I'll need to develop my own workaround, or ideally develop a PR fix if it's within my abilities. 

In any event I'm blocked from updating to a recent version of the compiler (to move from frowned-upon dependency on internal module provide names, which no longer work, to CJS require processing) until I know more. Thanks!

**Comment by ChadKillingsworth** [comment]
This really sounds like an if block logic around goog.module detection is wrong. I've explicitly fixed something very much like that somewhere (I've got a lot of active branches right now). I'm going to try to look at this today.

**Comment by supersteves** [comment]
@ChadKillingsworth Brilliant. At a glance this looks like exactly what I was talking about further up and probably will fix this case. Thanks!
