### ISSUE TITLE
Externs and require

### ISSUE THREAD

**Issue by lellisga** [google/closure-compiler#2704]
I'm currently trying to compile this file:

// index.js
var events = require("events");
var EventEmitter = events.EventEmitter;

var myEmitter = new EventEmitter();

myEmitter.on('event', () => {
    console.log('an event occurred!');
});

myEmitter.emit('event');
java -jar ../closure/compiler-latest/closure-compiler-v20171023.jar 
        --externs './node.js-closure-compiler-externs-master/events.js' 
        --js index.js
        --js_output_file output/index-compiled.js 
        --compilation_level ADVANCED  
        --process_common_js_modules 
        --module_resolution NODE 
        --entry_point index.js 
        --warning_level VERBOSE
this is what I receive:

index.js:1: ERROR - Failed to load module "events"
var events = require("events");
    ^

index.js:1: ERROR - Failed to load module "events"
var events = require("events");
             ^

2 error(s), 0 warning(s)
Am I missing something?

**Comment by ChadKillingsworth** [comment]
I don't see a flag to pass in the source for events. The compiler does not discover source files - they have to be explicitly provided.

**Comment by lellisga** [comment]
I tried this and it didn't work either. `events` is a node internal module.

**Comment by ChadKillingsworth** [comment]
The compiler does not provide polyfills for internal node modules. You'll have to use something that does.
