### ISSUE TITLE
Element externs missing insertAdjacentElement/Text

### ISSUE THREAD

**Issue by JamesXNelson** [google/closure-compiler#2715]
insert-adjacent is supported by all evergreen browsers, and should be included in the browser externs (needed for a j2cl project)

https://caniuse.com/#feat=insert-adjacent

If project owners are okay with inclusion, I can submit a pull request (not sure which dom file to best put it in).

It would technically be nice to have outerHTML as well, but I'll ask for one thing at a time ^_^

**Comment by MatrixFrog** [comment]
The externs are not well-organized to be honest. Just put it in whatever file seems to have roughly similar/related properties in it.
