### ISSUE TITLE
Proposal: Ban mutable ES6 exports

### ISSUE THREAD

**Issue by jplaisted** [google/closure-compiler#2717]
Explained [here](https://docs.google.com/document/d/18hgSdOVRSY-Q_jKZTP2yi4WIvu8_-kOQna5y44o9yCs/edit?ts=5a0a31de#heading=h.khq92xfsstpk).

tl;dr
- Bad pattern (static mutable state).
- Many cases where exports are mutated, not always clear.
- Zero IE8 support.
- Currently broken in the compiler today.

This is meant to track any discussion before proceeding.

**Comment by mprobst** [comment]
This will make Closure Compiler incompatible with (some) JavaScript that follows the ECMAScript spec. That'll make it hard for users to use JavaScript that they might not control (e.g. third party). It might be worth considering the fallout from that in this decision.

**Comment by swannodette** [comment]
I also strongly disagree with this proposal. If they are var in the original module then I think this behavior is perfectly fine. In fact it's necessary for languages that want hot-code reloading of modules such as ClojureScript.

**Comment by ChadKillingsworth** [comment]
I believe @jplaisted research said Babel didn't handle this properly either.

**Comment by jplaisted** [comment]
Babel handles about half of Lvalues correctly.

```
export var x = 0;

// Correctly reassigns the export
x += 2; 
f(x++);
--x;
for (x = 0; x < 20; x++) {}

// Incorrect, does not reassign the export
var x = 3;
for (x in Obj) {}
var {x} = Obj;
var [x] = Obj;

// Correct, but probably only by coincidence of transpilation
for (x of Obj) {}
```

That being said I actually agree that we should support it, this was just a proposal for to test the waters!

I'll close this and open a new issue to detect mutable exports and throw an unimplemented error for now. Per #2710 they currently are not working correctly.

**Comment by jplaisted** [comment]
Also maybe worth noting another case we have to look out for (that btw Babel doesn't get right).

```
import { imported } from './file.js';
export { imported };
```

Acts like an `export from`.
