### ISSUE TITLE
Unrecognized option: --allow_method_call_decomposing

### ISSUE THREAD

**Issue by trxcllnt** [google/closure-compiler#2725]
version: `google-closure-compiler@20171112.0.0`

I'm attempting to compile TS-generated es2015 downlevel'd async-generators with the new
[`--allow_method_call_decomposing`](https://github.com/google/closure-compiler/wiki/FAQ#i-get-an-undecomposable-expression-error-for-my-yield-or-await-expression-what-do-i-do) flag, but the compilation fails with this error:

```
Unrecognized option: --allow_method_call_decomposing
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

The git-blame [says](https://github.com/google/closure-compiler/commit/1de0f4b6ebb3e56d003666c60de21f2148b67552) the commit to add the flag was merged 7 days ago, and npm claims `20171112.0.0` was published 6 days ago. Did 1de0f4b6ebb3e56d003666c60de21f2148b67552 make it into this release?

**Comment by MatrixFrog** [comment]
Probably not, so you'll need to build from head for now if you want that flag. Usually there's a delay of a day or two between the commit the release is built from, and the time it actually goes out. If you're using Maven, there are snapshots at https://oss.sonatype.org/content/repositories/snapshots/com/google/javascript/

**Comment by trxcllnt** [comment]
@MatrixFrog thanks! that works.

Now the last blocker to moving to raw ES6 -> ES5 with CC is that Iterator#return throws [`"Not yet implemented"`](https://github.com/google/closure-compiler/blob/f8e657686c864db0554534213d7581a36a5545ef/src/com/google/javascript/jscomp/Es6RewriteGenerators.java#L1423) errors. VMs/libs are generally tolerant of iterators that don't have `return` functions, but since CC generates a stub that throws, it gets called.

Instead of throwing, would it be possible not to compile in the `return` function until it's fully implemented? If there's not an issue about this yet, I'd be happy to open one to track.

**Comment by brad4d** [comment]
@trxcllnt 
I've filed #2728 for implementing the return method.
I'm reworking the generator transpilation to address a few problems, and implementing the return method should fall out of that work.
