### ISSUE TITLE
Create an enum value type from the enum class object

### ISSUE THREAD

**Issue by koba04** [google/closure-compiler#2730]
I'd like to create an enum value type from the enum class object.
The following example is trying to create an enum value type by using generic types.

```js
/**
 *
 * @param {T} value
 * @param {I} enumObject
 * @return {I<T>}
 * @template T, I
 */
function castEnumValue(value, enumObject) {
  let returnValue;
  // check the value whether a value of Enum of not.
  Object.values(enumObject).forEach((v) => {
    if (value === v) {
      returnValue = v;
    }
  });
  if (!returnValue) {
    throw new Error(value + ' is not an enum value');
  }
  return returnValue;
};

/**
 * @enum {number}
 */
var Corner = {
  OK: 1,
  NG: -1
};

/**
 *
 * @param {Corner} corner
 */
function useCorner(corner) {
}

var target = 1;

// want to be a Corner<number>
var enumValue = castEnumValue(
  target,
  Corner
);

// found   : enum{Corner}
// required: Corner<number>
// useCorner(enumValue);
//           ^^^^^^^^^
useCorner(enumValue);
```

https://closure-compiler-debugger.appspot.com/#input0%3D%252F**%250A%2520*%250A%2520*%2520%2540param%2520%257BT%257D%2520value%250A%2520*%2520%2540param%2520%257BI%257D%2520enumObject%250A%2520*%2520%2540return%2520%257BI%253CT%253E%257D%250A%2520*%2520%2540template%2520T%252C%2520I%250A%2520*%252F%250Afunction%2520castEnumValue(value%252C%2520enumObject)%2520%257B%250A%2520%2520let%2520returnValue%253B%250A%2520%2520%252F%252F%2520check%2520the%2520value%2520whether%2520a%2520value%2520of%2520Enum%2520of%2520not.%250A%2520%2520Object.values(enumObject).forEach((v)%2520%253D%253E%2520%257B%250A%2520%2520%2520%2520if%2520(value%2520%253D%253D%253D%2520v)%2520%257B%250A%2520%2520%2520%2520%2520%2520returnValue%2520%253D%2520v%253B%250A%2520%2520%2520%2520%257D%250A%2520%2520%257D)%253B%250A%2520%2520if%2520(!returnValue)%2520%257B%250A%2520%2520%2520%2520throw%2520new%2520Error(value%2520%252B%2520'%2520is%2520not%2520an%2520enum%2520value')%253B%250A%2520%2520%257D%250A%2520%2520return%2520returnValue%253B%250A%257D%253B%250A%250A%252F**%250A%2520*%2520%2540enum%2520%257Bnumber%257D%250A%2520*%252F%250Avar%2520Corner%2520%253D%2520%257B%250A%2520%2520OK%253A%25201%252C%250A%2520%2520NG%253A%2520-1%250A%257D%253B%250A%250A%252F**%250A%2520*%250A%2520*%2520%2540param%2520%257BCorner%257D%2520corner%250A%2520*%252F%250Afunction%2520useCorner(corner)%2520%257B%250A%257D%250A%250Avar%2520target%2520%253D%25201%253B%250A%250Avar%2520enumValue%2520%253D%2520castEnumValue(%250A%2520%2520target%252C%250A%2520%2520Corner%250A)%253B%250A%250A%252F%252F%2520found%2520%2520%2520%253A%2520enum%257BCorner%257D%250A%252F%252F%2520required%253A%2520Corner%253Cnumber%253E%250A%252F%252F%2520useCorner(enumValue)%253B%250A%252F%252F%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%255E%255E%255E%255E%255E%255E%255E%255E%255E%250AuseCorner(enumValue)%253B%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3Dtrue%26CHECK_SYMBOLS%3Dtrue%26MISSING_PROPERTIES%3Dtrue%26TRANSPILE%3Dtrue%26CHECK_TYPES%3Dtrue%26CLOSURE_PASS%3Dtrue%26PRESERVE_TYPE_ANNOTATIONS%3Dtrue%26PRETTY_PRINT%3Dtrue

But I got `enum{Corner}`, not `Cornder<number>`. What is `enum{Corner}` type? How can I use this?
I think type casting a number or string value to an enum value type after validation is a use case that is needed sometimes.
I know it is possible to use type casting comment. But it can't create a function like `castEnumValue` because type casting comment can't use generic types.
I hope it would be nice if there is a way to create an enum value type from the enum class object. What do you think?

Thanks!

**Comment by brad4d** [comment]
@koba04 
I think the gist of what you're asking for is an automatic way to ensure that a value is a valid member of an enum type.

```javascript
/** @enum {number} */
const MyEnum = {
  ONE: 1,
  GEORGE: 1,
  TWO: 2
};
```

The values 1 and 2 would be valid, but no other values would be.

You also seem to want to convert a primitive value to an object that represents the corresponding enum value.
No such thing actually exists. `MyEnum.ONE` is just an alias for the value 1.

The closest thing to that would be to convert the enum value to the string name.
e.g.

```javascript
let x = hypotheticalEnumValueToNameFunction(1, MyEnum); // 'ONE' or 'GEORGE'?
MyEnum[x]; // gives us back 1 again
```

This has problems such as what name to give for a value with more than one name, and isn't very useful anyway. I should also point out that in `ADVANCED_MODE` the compiler will end up renaming your enum values, so you really shouldn't create any logic that depends on particular names.

If you want to be able to map back and forth between a value and a string or object that somehow represents that value, you'll need to use the new ES6 `Map` type or an `Object` or an `Array`. Enums aren't what you want for that.
