### ISSUE TITLE
Mix different js module together

### ISSUE THREAD

**Issue by exotfboy** [google/closure-compiler#2735]
Hi:

There are two kinds of js module types in my project:

1  closure-library

The `goog.require`  `goog.provide` are used .

2 ES6

Where the `exports class.... ` are used.

After read the wiki of [Managing Dependencies](https://github.com/google/closure-compiler/wiki/Managing-Dependencies) and [JS Modules](https://github.com/google/closure-compiler/wiki/JS-Modules).

I add the `process_common_js_modules` flag during compiling.

However I got the error: `'import' and 'export' may appear only with 'sourceType: module'`

What's going on?

**Comment by ChadKillingsworth** [comment]
What's your `language_in` flag set at? It has to be ECMASCRIPT6 or higher ...

You also cannot use `goog.provide` in the same file that uses either the `import` or `export` keyword. That's mixing module types.
