### ISSUE TITLE
Wrong arg to Set.contains()?

### ISSUE THREAD

**Issue by supersteves** [google/closure-compiler#2752]
I came across this issue after seeing this Eclipse warning:
```
Unlikely argument type Deque<Map<String,Node>> for contains(Object) on a Collection<Node>
Es6TypedToEs6Converter.java	
/closure-compiler-parent/src/com/google/javascript/jscomp	
line 429	
Java Problem
```
https://github.com/google/closure-compiler/blob/d66ab8e8562c313b873070ba59a3f1211a30f7eb/src/com/google/javascript/jscomp/Es6TypedToEs6Converter.java#L429

@Dominator008 git blame shows you as the author.

**Comment by MatrixFrog** [comment]
Looks like we probably meant `containsAll`.

**Comment by MatrixFrog** [comment]
This pass is not really supported anyway; we might be able to just get rid of it.
