### ISSUE TITLE
Advanced mode is replacing constructor reference with null

### ISSUE THREAD

**Issue by supersteves** [google/closure-compiler#2754]
Using a clean build from source, at today's tip (307258717f7068662190713ac72bac07d06d77d6), the following code...
``` javascript
goog.provide("ns.Bean");

/** @constructor */
ns.Bean = function() {};

ns.Bean.x = function(a=null) {
    if (a===null || a===undefined) {
        //console.log(a);
        a = ns.Bean;
    }
    return new a();
};

window.foo = ns.Bean.x;
```
... using the command...
```
java -jar closure-compiler-tip.jar 
    --entry_point goog:ns.Bean 
    --js ns/*.js --language_in ECMASCRIPT_2015 
    --compilation_level=ADVANCED 
    --formatting PRETTY_PRINT
```
... results in ...
``` javascript
window.a = function(b) {
  b = void 0 === b ? null : b;
  if (null === b || void 0 === b) {
    b = null;
  }
  return new b;
};
```
Note that `null` is being assigned to `b`, and the constructor declaration has been removed as if it were unused. Uncommenting the `console.log` line and recompiling magically fixes it, resulting in:
``` javascript
function c() {
}
window.a = function(b) {
  b = void 0 === b ? null : b;
  if (null === b || void 0 === b) {
    console.log(b), b = c;
  }
  return new b;
};
```

This is a recent regression. The last release build (`closure-compiler-v20171203.jar`) does not have this problem.

**Comment by brad4d** [comment]
This is related to work @lauraharker has been doing on `AggressiveInlineAliases`. She's working on a fix.

**Comment by lauraharker** [comment]
Submitted a fix internally.

**Comment by supersteves** [comment]
Thanks. With this kind of bug, our own functional tests caught it because our app crashed somewhere. I know that the compiler has a pretty sizeable set of tests, but they didn't catch it. What were the characteristics of this bug, in terms of what triggers it? I'm trying to get a feel for how widespread it was, and in practice how you catch this kind of (scary) bug. Do internal google users of the compiler form an extended delayed-effect functional test, which helps prove official release versions, for example?

**Comment by brad4d** [comment]
@supersteves 
If you hadn't noticed this, one of our internal Google projects surely would have.
In fact I think they did and @lauraharker was already fixing it when you filed your report.

**Comment by supersteves** [comment]
OK. Thanks. I'll try to be quicker next time! 👍
