### ISSUE TITLE
[NTI] if condition doesn't narrow the inferred type of a variable

### ISSUE THREAD

**Issue by rcfox** [google/closure-compiler#2764]
Without NTI, it's possible to guide the compiler's type inference with if conditions: If you go down a path where the variable can't possibly be null, the compiler can figure out that the variable isn't null.

```
/** @return {number} */
function foo() {
  var a = null;
  for (var i = 0; i < 10; i++) {
    if (a === null) {
      a = i;
    } else {
      return a;
    }
  }
  return 0;
}
```

```
$ java -jar closure-compiler-v20171203.jar --warning_level VERBOSE --jscomp_error=* test.js
function foo(){for(var a=null,b=0;10>b;b++)if(null===a)a=b;else return a;return 0};
```

However, with NTI, the compiler sees the variable 'a' as only being a null type inside the else branch.

```
$ java -jar closure-compiler-v20171203.jar --new_type_inf --warning_level VERBOSE --jscomp_error=* test.js
test.js:8: ERROR - Returned type does not match declared return type.
Expected : number
Found    : null

      return a;
      ^^^^^^^^^

1 error(s), 0 warning(s)
```

If the last line is changed to `return a;`, then both NTI and non-NTI see the type as (null|number) at that point.

Here's the version I'm using:
```
$ java -jar closure-compiler-v20171203.jar --version
Closure Compiler (http://github.com/google/closure-compiler)
Version: v20171203
Built on: 2017-12-05 14:07
```

**Comment by dimvar** [comment]
You can explicitly declare the type of `a` to work around this. NTI generally narrows the types, but your example is a limitation in the way NTI handles loops. We may or may not improve it.

**Comment by rcfox** [comment]
Ah, that's unfortunate. Perhaps you could add a hint to the error message about declaring the type if you end up with a null and/or undefined as the only types?

**Comment by lauraharker** [comment]
Closing since NTI is deprecated.
