### ISSUE TITLE
--source-map-input + --source-map-include-content

### ISSUE THREAD

**Issue by jahorton** [google/closure-compiler#2766]
My team is in the process of converting a JavaScript project over to TypeScript and have run into an issue with sourcemaps.  In particular, we seem unable to get Closure to include the TypeScript sources in the sourcemap result for Closure's minification of the resulting Javascript.  Any natively-JS inclusions at the minification level (such as `goog.exportPath` calls) are perfectly documented, but the TypeScript source is missing.

Viewed in Firefox, attempting to see the source for one of the TS files yields:

```
Error while fetching an original source: TypeError: NetworkError when attempting to fetch resource.
Source URL: ../source/kmwbase.ts
```

The TypeScript sourcemap provided as an argument to `--source-map-input` has the TS sources, and if I leave those sources out, the non-inlined sourcemaps work perfectly - which is fine for debugging, but not for distribution.  Is this an implementation gap within Closure's implementation of sourcemaps?

**Comment by ChadKillingsworth** [comment]
Questions are best asked on [StackOveflow](http://stackoverflow.com/questions/tagged/google-closure-compiler) or on  the [Mailing List](https://groups.google.com/forum/#!forum/closure-compiler-discuss)

There are multiple flags for source maps and also multiple ways to format a source map. The compiler handles the most common ones, but not all. You may need a pre or post processing tool.

It's also helpful if you create a minimal repo case to look at.

In general though, the compiler can handle your use case.
