### ISSUE TITLE
Imported types lost if exported after definition (NTI + ES6 modules)

### ISSUE THREAD

**Issue by supersteves** [google/closure-compiler#2769]
Using the compiler to check types with NTI is failing to emit warnings within e.g. another class constructor, or a function as shown here: 

A
``` javascript
class A {
    constructor() {
        /** @type {boolean} */
        this._fibble;
    }
}
export default A;
```
B
``` javascript
import A from "./A";
(function() {
    let /** null */ x = A; // should fail, but doesn't
    let a = new A();
    a._fibble = true; // valid
    a._fibble = 5; // should fail, but doesn't
    a.fibble = "x"; // should fail, but doesn't
})();
```
The warnings are emitted correctly if the above lines are outside of the function. Or with OTI. Or if exporting as follows:
``` javascript
export default class A {...
```

I'm using 92c3c84c1b96d6d3adda92ddcad4c2f651ba4c30 however this is also happening in the [**debugger**](https://closure-compiler-debugger.appspot.com/#input0%3Dclass%2520A%2520%257B%250A%2520%2520%2520%2520constructor()%2520%257B%250A%2520%2520%2520%2520%2520%2520%2520%2520%252F**%2520%2540type%2520%257Bboolean%257D%2520*%252F%250A%2520%2520%2520%2520%2520%2520%2520%2520this._fibble%253B%250A%2520%2520%2520%2520%257D%250A%257D%250Aexport%2520default%2520A%253B%250A%26input1%3Dimport%2520A%2520from%2520%2522.%252Finput0%2522%253B%250A(function()%2520%257B%250A%2520%2520%2520%2520let%2520%252F**%2520null%2520*%252F%2520x%2520%253D%2520A%253B%2520%252F%252F%2520should%2520fail%252C%2520but%2520doesn't%250A%2520%2520%2520%2520let%2520a%2520%253D%2520new%2520A()%253B%250A%2520%2520%2520%2520a._fibble%2520%253D%2520true%253B%2520%252F%252F%2520valid%250A%2520%2520%2520%2520a._fibble%2520%253D%25205%253B%2520%252F%252F%2520should%2520fail%252C%2520but%2520doesn't%250A%2520%2520%2520%2520a.fibble%2520%253D%2520%2522x%2522%253B%2520%252F%252F%2520should%2520fail%252C%2520but%2520doesn't%250A%257D)()%253B%250A%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3Dtrue%26CHECK_SYMBOLS%3Dtrue%26MISSING_PROPERTIES%3Dtrue%26TRANSPILE%3Dtrue%26CHECK_TYPES%3Dtrue%26CHECK_TYPES_NEW_INFERENCE%3Dtrue%26CLOSURE_PASS%3Dtrue%26PRESERVE_TYPE_ANNOTATIONS%3Dtrue%26PRETTY_PRINT%3Dtrue).

**Comment by supersteves** [comment]
See other bug, it's probably the same thing, and pretty serious. We've just switched wholly to NTI, and realise we've been relying on OTI for type errors in all these cases. Simply adding `/** @const */` to `export default A;` also solves it.

**Comment by supersteves** [comment]
Also possibly related:
https://github.com/google/closure-compiler/issues/2257 
https://github.com/google/closure-compiler/issues/2236#issuecomment-326360585

**Comment by supersteves** [comment]
We're putting `@const` jsdoc on every `export default <alias>` to work around this.

**Comment by supersteves** [comment]
I notice there are a bunch of open NTI issues I reported in the past, such as this one. Should I close them all?

**Comment by concavelenz** [comment]
If you don't mind that would be helpful.  Or rebrand them if they still exist and you would like us to take a look.
