### ISSUE TITLE
Super class call not being included in the constructor

### ISSUE THREAD

**Issue by dmitrysteblyuk** [google/closure-compiler#2773]
Sorry, I couldn't catch this issue in any simple example I tried to create, but it exists. It breaks functionality of Angular Cdk https://github.com/angular/cdk-builds/blob/master/esm2015/a11y.js. Basically it removes super call and converts this code:

```
class ListKeyManager {
    constructor(_items) {
        this._items = _items;
.............. // ListKeyManager code here

class FocusKeyManager extends ListKeyManager {
    setActiveItem(index) {
        super.setActiveItem(index);
        if (this.activeItem) {
            this.activeItem.focus();
        }
    }
}
```
to
```
function NA(a) {
    this.Wh = a;
........... // NA (ListKeyManager) code here

function PA() {}
PA.prototype.zg = function(a) {
    NA.prototype.zg.call(this, a);
    this.Be && this.Be.focus()
}
```

There's this issue also https://github.com/angular/material2/issues/9018, which is caused by this behavior.

**Comment by MatrixFrog** [comment]
If there is no constructor, I believe the Closure Compiler is supposed to generate one that essentially just calls `super(...arguments)`, per step 10 of https://tc39.github.io/ecma262/#sec-runtime-semantics-classdefinitionevaluation

Either it's failing to do that, or some later pass is incorrectly removing that synthetic constructor definition.

**Comment by dmitrysteblyuk** [comment]
Actually, closure removes constructor even if it's there like this:

```
class FocusKeyManager extends ListKeyManager {
    constructor(items) {
         super(items);
    }
    ........................
```

Eventually I had to use this dirty fix below, because nothing else worked:

```
class FocusKeyManager extends ListKeyManager {
    constructor(items) {
         super(items);
         Object.assign(this, new ListKeyManager(items));
    }
    ........................
```

**Comment by MatrixFrog** [comment]
This sounds like `RemoveSuperMethodsPass` which @Dominator008 added, perhaps.

**Comment by dmitrysteblyuk** [comment]
I tested several versions starting from 20170521.

**Comment by dmitrysteblyuk** [comment]
Turned out to be tsickle bug.
