### ISSUE TITLE
Adding default value of destructuring object in function parameters leads to warning

### ISSUE THREAD

**Issue by miroshko** [google/closure-compiler#2775]
```
    /**
     * @returns {number}.
     * @param {{bar: number}|undefined} args Params.
     */
    function foo ({bar} = {bar: 0}) {
        return bar;
    }
```

gives a warning

WARNING - parameter args does not appear in foo's parameter list
    foo ({bar} = {bar: 0}) {
    ^

the same for this:

```
    /**
     * @returns {number}.
     * @param {{bar: (number|undefined)}|undefined} args Params.
     */
    function foo ({bar} = {}) {
        return bar;
    }
```

although both `function foo ({bar = 0}) {` and `function foo ({bar}) {` work fine so only the presence of a default object breaks it

**Comment by ChadKillingsworth** [comment]
This is expected and intended. You'd need to use alternate syntax:

```js
/** @type {function({bar: (number|undefined)}):undefined):number} */
function foo ({bar} = {}) {
  return bar;
}
```

**Comment by miroshko** [comment]
thanks, your proposal works with this simple function, but I cannot use this syntax with class methods because if I do so the GCC complains about misplaced annotation and requires parentheses around the function which are not allowed around class methods by JS syntax.

can you maybe tell more why is that intended to behave like this only in this specific case? as I mentioned it works if I remove the `= {}` part, even though the name in JSDoc is still the same and not corresponding to the actual parameter name, e.g.

```
/**
 * @returns {number|undefined}.
 * @param {{bar: (number|undefined)}|undefined} args Params.
 */
function foo ({bar}) {
    return bar;
}
```

**Comment by blickly** [comment]
@MatrixFrog, do you remember what the current state is about JSDoc-annotating destructuring method parameters with default values?

**Comment by MatrixFrog** [comment]
I don't think our JSDoc parsing changed at all in response to destructuring or other ES6 features. In other words you'd annotate it the same as if destructuring didn't exist.

**Comment by lauraharker** [comment]
This seems to work now. Can we close this bug?

[original example 1](https://closure-compiler-debugger.appspot.com/#input0%3D%2520%2520%2520%2520%252F**%250A%2520%2520%2520%2520%2520*%2520%2540returns%2520%257Bnumber%257D.%250A%2520%2520%2520%2520%2520*%2520%2540param%2520%257B%257Bbar%253A%2520number%257D%257Cundefined%257D%2520args%2520Params.%250A%2520%2520%2520%2520%2520*%252F%250A%2520%2520%2520%2520function%2520foo%2520(%257Bbar%257D%2520%253D%2520%257Bbar%253A%25200%257D)%2520%257B%250A%2520%2520%2520%2520%2520%2520%2520%2520return%2520bar%253B%250A%2520%2520%2520%2520%257D%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3Dtrue%26CHECK_TYPES%3Dtrue%26TRANSPILE%3Dtrue%26CLOSURE_PASS%3Dtrue%26PRESERVE_TYPE_ANNOTATIONS%3Dtrue%26PRETTY_PRINT%3Dtrue)
[original example 2](https://closure-compiler-debugger.appspot.com/#input0%3D%2520%2520%2520%2520%252F**%250A%2520%2520%2520%2520%2520*%2520%2540returns%2520%257Bnumber%257D.%250A%2520%2520%2520%2520%2520*%2520%2540param%2520%257B%257Bbar%253A%2520(number%257Cundefined)%257D%257Cundefined%257D%2520args%2520Params.%250A%2520%2520%2520%2520%2520*%252F%250A%2520%2520%2520%2520function%2520foo%2520(%257Bbar%257D%2520%253D%2520%257B%257D)%2520%257B%250A%2520%2520%2520%2520%2520%2520%2520%2520return%2520bar%253B%250A%2520%2520%2520%2520%257D%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3Dtrue%26CHECK_TYPES%3Dtrue%26TRANSPILE%3Dtrue%26CLOSURE_PASS%3Dtrue%26PRESERVE_TYPE_ANNOTATIONS%3Dtrue%26PRETTY_PRINT%3Dtrue)

**Comment by brad4d** [comment]
I think so.
