### ISSUE TITLE
const when captured doesn't transpile properly

### ISSUE THREAD

**Issue by rauhs** [google/closure-compiler#2779]
The following code prints 0 to 9:

```js
(function f() {
    var x = (0);
    while (true) {
        if (x < 10) {
            const y = x;
            setTimeout(function() {return console.log(y);});
            x++;
            continue;
        } else {
            return null;
        }
    }
})();
```
But after advanced optimization it prints 9 times "9".

Side note: Changing `while (true)` to `for (;true;)` fixes it. :)

Link to reproduce:
https://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%2540compilation_level%2520ADVANCED_OPTIMIZATIONS%250A%252F%252F%2520%2540formatting%2520pretty_print%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250A(function%2520f()%2520%257B%250A%2520%2520%2520%2520var%2520x%2520%253D%2520(0)%253B%250A%2520%2520%2520%2520while%2520(true)%2520%257B%250A%2520%2520%2520%2520%2520%2520%2520%2520if%2520(x%2520%253C%252010)%2520%257B%250A%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520const%2520y%2520%253D%2520x%253B%250A%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520setTimeout(function()%2520%257Breturn%2520console.log(y)%253B%257D)%253B%250A%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520x%252B%252B%253B%250A%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520continue%253B%250A%2520%2520%2520%2520%2520%2520%2520%2520%257D%2520else%2520%257B%250A%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520return%2520null%253B%250A%2520%2520%2520%2520%2520%2520%2520%2520%257D%250A%2520%2520%2520%2520%257D%250A%257D)()%253B%250A%250A

**Comment by MatrixFrog** [comment]
Another repro (in the debugger, which may be easier to work with) https://closure-compiler-debugger.appspot.com/#input0%3D%250A(function%2520f()%2520%257B%250A%2520%2520%2520%2520var%2520x%2520%253D%2520(0)%253B%250A%2520%2520%2520%2520while%2520(true)%2520%257B%250A%2520%2520%2520%2520%2520%2520%2520%2520if%2520(x%2520%253C%252010)%2520%257B%250A%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520const%2520y%2520%253D%2520x%253B%250A%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520setTimeout(function()%2520%257Breturn%2520console.log(y)%253B%257D)%253B%250A%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520x%252B%252B%253B%250A%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520continue%253B%250A%2520%2520%2520%2520%2520%2520%2520%2520%257D%2520else%2520%257B%250A%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520return%2520null%253B%250A%2520%2520%2520%2520%2520%2520%2520%2520%257D%250A%2520%2520%2520%2520%257D%250A%257D)()%253B%26input1%26conformanceConfig%26externs%3Dvar%2520setTimeout%253B%250Avar%2520console%253B%26refasterjs-template%26includeDefaultExterns%3Dtrue%26CHECK_SYMBOLS%3Dtrue%26MISSING_PROPERTIES%3Dtrue%26TRANSPILE%3Dtrue%26CHECK_TYPES%3Dtrue%26CLOSURE_PASS%3Dtrue%26PRESERVE_TYPE_ANNOTATIONS%3Dtrue%26PRETTY_PRINT%3Dtrue

**Comment by MatrixFrog** [comment]
This seems to work correctly:

https://closure-compiler-debugger.appspot.com/#input0%3D%250A(function%2520f()%2520%257B%250A%2520%2520%2520%2520var%2520x%2520%253D%2520(0)%253B%250A%2520%2520%2520%2520while%2520(true)%2520%257B%250A%2520%2520%2520%2520%2520%2520%2520%2520if%2520(x%2520%253E%253D%252010)%2520%257B%250A%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520return%2520null%253B%250A%2520%2520%2520%2520%2520%2520%2520%2520%257D%250A%2520%2520%2520%2520%2520%2520%2520%2520const%2520y%2520%253D%2520x%253B%250A%2520%2520%2520%2520%2520%2520%2520%2520setTimeout(function()%2520%257Breturn%2520console.log(y)%253B%257D)%253B%250A%2520%2520%2520%2520%2520%2520%2520%2520x%252B%252B%253B%250A%2520%2520%2520%2520%257D%250A%257D)()%253B%26input1%26conformanceConfig%26externs%3Dvar%2520setTimeout%253B%250Avar%2520console%253B%26refasterjs-template%26includeDefaultExterns%3Dtrue%26CHECK_SYMBOLS%3Dtrue%26MISSING_PROPERTIES%3Dtrue%26TRANSPILE%3Dtrue%26CHECK_TYPES%3Dtrue%26CLOSURE_PASS%3Dtrue%26PRESERVE_TYPE_ANNOTATIONS%3Dtrue%26PRETTY_PRINT%3Dtrue

So I guess the bug only occurs when there's a const inside a block inside a loop body (not just a const directly inside a loop body).

**Comment by rauhs** [comment]
Just curious: Why not use an IIFE to capture the current value of the const? Like
```js
var y = x;
(function (y) {
   (function() {return console.log(y);})
})(y)
```

**Comment by MatrixFrog** [comment]
I don't remember now. I think maybe we didn't want the extra overhead (both in terms of code size and runtime performance) of another function object and function call.

**Comment by brad4d** [comment]
The problem appears to be that `Es6RewriteBlockScopedDeclaration.java` just puts the statement to update the internal object holding loop-iteration-local variables at the end of the loop, so it gets skipped on a continue.

Would the correct solution be to instead wrap the entire contents of the loop in a try / finally and stick such necessary updates in the finally block?

**Comment by MatrixFrog** [comment]
Good idea. I don't know if there's a performance cost to a try/finally but if we add it in only when there is a `continue` then we'd avoid that cost (if any) in most cases.

**Comment by rauhs** [comment]
> I don't remember now. I think maybe we didn't want the extra overhead (both in terms of code size and runtime performance) of another function object and function call.

But the current implementation is already creating an IIFE to capture the vars. But passing a single JS object with (potentially multiple) fields on the object. If instead, don't do this object indirection and instead pass in every closed over `const` we would:
1. Get rid of the "carrying over the state" statements
2. Though, we'd have to pass more vars and add more params to the IIFE.

It seems that overall the code size should be smaller however.

Given:
```
(function f() {
    var x = (0);
    for (;true;) {
        if (x < 10) {
            const aa = x;
            const bb = aa+1;
            const cc = bb+1;
            setTimeout(function() {return console.log(aa+bb+cc);});
            x++;
            continue;
        } else {
            return null;
        }
    }
})();
```

Currently generated:
```
(function() {
  for (var b = 0, a = {};; a = {a:a.a, b:a.b, c:a.c}) {
    if (10 > b) {
      a.a = b, a.b = a.a + 1, a.c = a.b + 1, setTimeout(function(a) {
        return function() {
          return console.log(a.a + a.b + a.c);
        };
      }(a)), b++;
    } else {
      return null;
    }
  }
})();
```
(correctly working)
Compiled size: 152 bytes gzipped (190 bytes uncompressed)

Proposed:
```
(function() {
  for (var b = 0,a,c,d;;) {
    if (10 > b) {
      a = b, c = a + 1, d = c + 1,
      setTimeout(function(a,b,c) {
        return function() {
          return console.log(a + b + c);
        };
      }(a,c,d)), b++;
    } else {
      return null;
    }
  }
})();
```
(could be simplified more)
Compiled size: 140 bytes gzipped (162 bytes uncompressed)

So overall a size win. I'm imagining the runtime would be better since no object lookup is involved.

**Comment by brad4d** [comment]
Using a finally block likely would be slower and doesn't seem like a good choice for that reason.
The idea of passing the vars separately in the wrapper is interesting.
I don't yet know enough about this code to know for certain whether there is a problem with that.
I'm looking into it, though.

**Comment by brad4d** [comment]
We cannot do the suggested "just pass in individual variables needed) idea described above,
because it won't be correct in the case where there are 2 or more closures created in the same loop
iteration.
They should share the same variables, but no longer will, because each has its own copy.

**Comment by Dominator008** [comment]
Maybe we just need to make sure the "carrying over state" statement appears everywhere the control flow exits the loop (break / continue)?

**Comment by brad4d** [comment]
I have a fix out for internal review.
Basic idea is to do the update as the first statement in the loop instead of the last.

**Comment by brad4d** [comment]
Came up with a better fix, which is now in internal review.
