### ISSUE TITLE
[NTI] Filter function argument type overrides array's type

### ISSUE THREAD

**Issue by rcfox** [google/closure-compiler#2780]
If a filter function supports a wider range of types than the filtered array, the compiler seems to forget about the type of the input.
```
/** @type {!Array.<number>} */
var a = [1,2,3,4];

/**
 * @param {number|string} x
 * @return {boolean}
 */
function alwaysTrue(x) {
  return true;
}

/** @type {!Array.<number>} */
var b = a.filter(alwaysTrue);
```
This seems like it should be acceptable. We're getting a subset of an array of numbers, using a function that could support strings if needed. However, the compiler sees the new result as an array of `number|string`:
```
$ java -jar closure-compiler-v20171203.jar --new_type_inf test.js 
Expected : Array<number>
Found    : Array<(number|string)>

var b = a.filter(alwaysTrue);
        ^^^^^^^^^^^^^^^^^^^^
```

Version info:
```
$ java -jar closure-compiler-v20171203.jar --version
Closure Compiler (http://github.com/google/closure-compiler)
Version: v20171203
Built on: 2017-12-05 14:07
```

**Comment by brad4d** [comment]
@shicks 
Could you comment on this? Is this behavior correct?

**Comment by dimvar** [comment]
Unfortunately, this is intended behavior. See the type of filter here: https://github.com/google/closure-compiler/blob/master/externs/es3.js#L759-L768. The contents of the return array are whatever type the callback takes.
