### ISSUE TITLE
[NTI] goog.inherits() is less strict than in non-NTI

### ISSUE THREAD

**Issue by rcfox** [google/closure-compiler#2781]
I'm not sure if this is a bug with the compiler or the library, but the issue only arises when using `--new_type_inf`, so I'll put it here.

With non-NTI, the compiler will complain if you inherit from a class without specifying `@extends {}`. It will also give an error if you try to inherit from a non-constructor. With NTI enabled, neither of these errors occur.

```
/** @constructor */
var Foo = function() {};


/** @interface */
var Bar = function() {};


/** @constructor */
var Qux = function() {};
goog.inherits(Qux, Foo);


/** @constructor */
var Hap = function() {};
goog.inherits(Hap, Bar);

```

Without NTI:
```
$ java -jar closure-compiler-v20171203.jar --js=closure-library-20171203/closure/goog/base.js --js=test.js --checks-only=true --jscomp_error=* --hide_warnings_for=closure_library-201271203
test.js:11: ERROR - Missing @extends tag on type Qux
goog.inherits(Qux, Foo);
^^^^^^^^^^^^^^^^^^^^^^^

test.js:16: ERROR - actual parameter 2 of goog.inherits does not match formal parameter
found   : function(this:Bar): ?
required: Function
goog.inherits(Hap, Bar);
                   ^^^

2 error(s), 0 warning(s), 95.6% typed

```

With NTI:
```
$ java -jar closure-compiler-v20171203.jar --new_type_inf --js=closure-library-20171203/closure/goog/base.js --js=test.js --checks-only=true --jscomp_error=* --hide_warnings_for=closure_library-201271203
```
(No output)

I'm using the v20171203 release of the Closure Library (though its package.json shows "version": "20171112.0.0").
```
$ java -jar closure-compiler-v20171203.jar --version
Closure Compiler (http://github.com/google/closure-compiler)
Version: v20171203
Built on: 2017-12-05 14:07
```

**Comment by brad4d** [comment]
@shicks are you familiar with the relevant part of the NTI code?

**Comment by rcfox** [comment]
I was surprised to see this closed without comment, but looking through the release notes, it seems NTI was abandoned. That's unfortunate, it looked promising.
