### ISSUE TITLE
[x].join("") is rewritten as ''+x in advanced

### ISSUE THREAD

**Issue by rauhs** [google/closure-compiler#2782]
This code:
```js
var x = {valueOf: function() {return "2"},
         toString: function() {return "3"}};

console.log([x].join(""));
console.log(''+x);
```

produces "3" then "2" but after advanced compilation produces "2", "2" since `[x].join("")` is being rewritten as `''+x` in advanced. This behavior changed at some point in mid-2017 release (GCC used to *not* rewrite this). This is for instance problematic for `goog.date.Date` instances that produce a different result.

Example:

https://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540compilation_level%2520ADVANCED_OPTIMIZATIONS%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250A%252F%252F%2520ADD%2520YOUR%2520CODE%2520HERE%250Avar%2520x%2520%253D%2520%257BvalueOf%253A%2520function()%2520%257Breturn%2520%25222%2522%257D%252C%250A%2520%2520%2520%2520%2520%2520%2520%2520%2520toString%253A%2520function()%2520%257Breturn%2520%25223%2522%257D%257D%253B%250A%250Aconsole.log(%255Bx%255D.join(%2522%2522))%253B%250Aconsole.log(''%252Bx)%253B%250A%250A

Clojurescript ticket: https://dev.clojure.org/jira/browse/CLJS-2395

**Comment by brad4d** [comment]
@concavelenz
I think I remember you making a change related to using `'' + x` in this way.
Is that right?

**Comment by brad4d** [comment]
@lukesandberg 
Actually made the change to start using `'' + x`.

**Comment by concavelenz** [comment]
This isn't related to lukes change.

**Comment by concavelenz** [comment]
PeepholeReplaceKnownMethods.java#tryFoldArrayJoin is the method that needs to be modified.

**Comment by rauhs** [comment]
@brad4d Not sure if it's correct to rewrite `[x].join("")` to `String(x)`. 

```
[null].join("") ;; => ""
String(null) ;; => "null"
```

**Comment by brad4d** [comment]
@rauhs 
Thanks for pointing that out! I didn't realize that join() turned nulls into empty strings.
Since that's the case, I think we need to remove the optimization entirely.

**Comment by brad4d** [comment]
@concavelenz 
I think we need to remove the logic for folding `[...].join()`, or at least do it only when the values themselves are literals, so we can know when we can replace a `null` with an empty string.

**Comment by brad4d** [comment]
Correction, I think this really only affects the single-element case.
We just need to leave `[x].join()` unchanged.

**Comment by brad4d** [comment]
Fix submitted internally.
