### ISSUE TITLE
compiler infers wrong type in unit test

### ISSUE THREAD

**Issue by myphysicslab** [google/closure-compiler#2785]
After upgrading to the new compiler I get a strange error, with the compiler inferring the wrong type.

When I developed these unit tests I found I could not use `goog.scope` at all in  the unit tests.  (Perhaps that has changed, I haven't tried again lately).  So I do the equivalent like this:

    goog.provide('myphysicslab.lab.util.test.ConcreteMemoList_test');

    goog.require('myphysicslab.lab.util.ConcreteMemoList');
    goog.require('myphysicslab.lab.util.MutableVector');
    goog.require('goog.testing.jsunit');

    var testConcreteMemoList1 = function() {
      var MutableVector = myphysicslab.lab.util.MutableVector;
      var vec1 = new MutableVector(1, 1);
      vec1.setTo(-1, -1);
      // more tests here....
    };
    goog.exportProperty(window, 'testConcreteMemoList1', testConcreteMemoList1);

Here is the error:

    src/lab/util/test/ConcreteMemoList_test.js:45: WARNING - Property setTo never 
    defined on vec1 of type myphysicslab.lab.util.GenericVector
      vec1.setTo(-1, -1);
      ^^^^^^^^^^

The error goes away when I use the long-name for the class instead:

    var testConcreteMemoList1 = function() {
      var vec1 = new myphysicslab.lab.util.MutableVector(1, 1);
      vec1.setTo(-1, -1);

Is `goog.scope` still incompatible with `goog.testing.jsunit`? Is there a better way to create short class names inside unit tests?

Note that [`MutableVector`](https://github.com/myphysicslab/myphysicslab/blob/master/src/lab/util/MutableVector.js) does implement [`GenericVector`](https://github.com/myphysicslab/myphysicslab/blob/master/src/lab/util/GenericVector.js) interface.  Here is [ConcreteMemoList_test](https://github.com/myphysicslab/myphysicslab/blob/master/src/lab/util/test/ConcreteMemoList_test.js). Here is [bash command for compiling unit tests](https://github.com/myphysicslab/myphysicslab/blob/master/compile_test.sh) that has compile options.

Here is the complete compile command with options

    + java -jar ../closure-compiler/target/closure-compiler-1.0-SNAPSHOT.jar
    --entry_point=goog:myphysicslab.lab.engine2D.test.CircularEdge_test
    --entry_point=goog:myphysicslab.lab.engine2D.test.EdgeSet_test
    --entry_point=goog:myphysicslab.lab.engine2D.test.Polygon_test
    --entry_point=goog:myphysicslab.lab.engine2D.test.RigidBodySim_test
    --entry_point=goog:myphysicslab.lab.engine2D.test.StraightEdge_test
    --entry_point=goog:myphysicslab.lab.engine2D.test.UtilEngine_test
    --entry_point=goog:myphysicslab.lab.engine2D.test.Vertex_test
    --entry_point=goog:myphysicslab.lab.model.test.ConcreteLine_test
    --entry_point=goog:myphysicslab.lab.model.test.EnergyInfo_test
    --entry_point=goog:myphysicslab.lab.model.test.NumericalPath_test
    --entry_point=goog:myphysicslab.lab.model.test.PointMass_test
    --entry_point=goog:myphysicslab.lab.model.test.SimList_test
    --entry_point=goog:myphysicslab.lab.model.test.Spring_test
    --entry_point=goog:myphysicslab.lab.model.test.VarsList_test
    --entry_point=goog:myphysicslab.lab.util.test.AbstractSubject_test
    --entry_point=goog:myphysicslab.lab.util.test.AffineTransform_test
    --entry_point=goog:myphysicslab.lab.util.test.CircularList_test
    --entry_point=goog:myphysicslab.lab.util.test.Clock_test
    --entry_point=goog:myphysicslab.lab.util.test.ConcreteMemoList_test
    --entry_point=goog:myphysicslab.lab.util.test.DoubleMath_test
    --entry_point=goog:myphysicslab.lab.util.test.DoubleRect_test
    --entry_point=goog:myphysicslab.lab.util.test.MutableVector_test
    --entry_point=goog:myphysicslab.lab.util.test.ParameterBoolean_test
    --entry_point=goog:myphysicslab.lab.util.test.ParameterNumber_test
    --entry_point=goog:myphysicslab.lab.util.test.ParameterString_test
    --entry_point=goog:myphysicslab.lab.util.test.RandomLCG_test
    --entry_point=goog:myphysicslab.lab.util.test.EasyScriptParser_test
    --entry_point=goog:myphysicslab.lab.util.test.Terminal_test
    --entry_point=goog:myphysicslab.lab.util.test.Timer_test
    --entry_point=goog:myphysicslab.lab.util.test.Util_test
    --entry_point=goog:myphysicslab.lab.util.test.Vector_test
    --entry_point=goog:myphysicslab.lab.view.test.CoordMap_test
    --entry_point=goog:myphysicslab.lab.view.test.DisplayList_test
    --entry_point=goog:myphysicslab.lab.view.test.DisplayShape_test
    --entry_point=goog:myphysicslab.lab.view.test.DisplaySpring_test
    --entry_point=goog:myphysicslab.lab.view.test.LabCanvas_test
    --entry_point=goog:myphysicslab.lab.view.test.ScreenRect_test
    --entry_point=goog:myphysicslab.lab.view.test.SimView_test
    --entry_point=goog:myphysicslab.sims.pendulum.test.DoublePendulum_test
    --entry_point=goog:myphysicslab.sims.springs.test.SingleSpring_test
    --entry_point=goog:myphysicslab.sims.roller.test.Roller_test
    --compilation_level=ADVANCED --define=goog.DEBUG=true 
    '--define=goog.LOCALE='\''de'\'''
    --define=myphysicslab.lab.util.Util.ADVANCED=true
    --define=myphysicslab.lab.util.Util.DEBUG=false
    '--define=myphysicslab.lab.util.Util.COMPILE_TIME=2018-01-11 01:18:40'
    --generate_exports --js=../closure-library/ --js=src/ --jscomp_error=checkTypes
    --jscomp_error=missingProperties --jscomp_error=missingProvide
    --jscomp_error=missingRequire --jscomp_warning=accessControls
    --jscomp_warning=ambiguousFunctionDecl --jscomp_warning=checkVars
    --jscomp_warning=const --jscomp_warning=constantProperty
    --jscomp_warning=fileoverviewTags --jscomp_warning=globalThis
    --jscomp_warning=invalidCasts --jscomp_warning=misplacedTypeAnnotation
    --jscomp_warning=missingReturn --jscomp_warning=strictModuleDepCheck
    --jscomp_warning=suspiciousCode --jscomp_warning=typeInvalidation
    --jscomp_warning=undefinedNames --jscomp_warning=undefinedVars
    --jscomp_warning=unknownDefines --jscomp_warning=uselessCode
    --jscomp_warning=visibility --emit_use_strict --language_in=ECMASCRIPT6_STRICT
    --language_out=ECMASCRIPT5_STRICT --new_type_inf --jscomp_warning=newCheckTypes
    --hide_warnings_for=../closure-library/
    --conformance_configs=/Users/erikn/Documents/Programming/myphysicslab/conformance_config.textproto 
    --dependency_mode=STRICT 
    --warning_level=VERBOSE

**Comment by brad4d** [comment]
@myphysicslab 
We're phasing out `goog.scope()` entirely.
Current best practice is to use `goog.module` instead of `goog.provide` and to assign `goog.require` calls like this.

```javascript
// defines MutableVector as an alias that can be used in both code and type annotations.
const MutableVector = goog.require('myphysicslab.lab.util.MutableVector');
```

I believe this form of assignment will work even if `MutableVector` is still defined with `goog.provide`.

Documentation for `goog.module` is here.
https://github.com/google/closure-library/wiki/goog.module:-an-ES6-module-like-alternative-to-goog.provide
