### ISSUE TITLE
Using goog.module() breaks ability to run in uncompiled (debug) mode

### ISSUE THREAD

**Issue by myphysicslab** [google/closure-compiler#2786]
Using a `goog.module()` based class breaks ability to run in uncompiled (debug) mode.  Due to `goog.scope` being deprecated, I'm starting to convert to using `goog.module`.  I've converted one class so far, and when compiled it works fine.  But when trying to run from uncompiled code that class seems to not be defined:

    TypeError: null is not an object (evaluating 'Util.ADVANCED')
    (anonymous function) — Vector.js:58
    scope — base.js:2002
    Global Code — Vector.js:20

occurs here:

    goog.provide('myphysicslab.lab.util.Vector');

    goog.require('myphysicslab.lab.util.GenericVector');
    goog.require('myphysicslab.lab.util.Util');

    goog.scope(function() {

    var Util = goog.module.get('myphysicslab.lab.util.Util');
    var GenericVector = myphysicslab.lab.util.GenericVector;
    /* ... */
    if (!Util.ADVANCED) {
      /** @inheritDoc */
      Vector.prototype.toString = function() {
        return 'Vector{x: '+Util.NF(this.x_)+', y: '+Util.NF(this.y_)
            + (this.z_ != 0 ? ', z: '+Util.NF(this.z_) : '')
            +'}';
      };
    };

The "run uncompiled" process involves loading `deps.js` which is generated by `depswriter.py`.  My `deps.js` contains this entry:

    goog.addDependency('../../../src/lab/util/Util.js', ['myphysicslab.lab.util.Util'], 
    ['goog.array', 'goog.asserts'], false);

I'm guessing that entire process of loading a `goog.module()` isn't working correctly in uncompiled code?

Being able to run from uncompiled code is super helpful at times for debugging.

**Comment by myphysicslab** [comment]
Mistake on my end, this is working just fine!

**Comment by myphysicslab** [comment]
Still a problem.  This seems to be something anticipated because of the detail of the error message:

    Error: Module myphysicslab.lab.util.Printable has been loaded incorrectly. Note,
    modules cannot be loaded as normal scripts. They require some kind of pre-processing
    step. You're likely trying to load a module via a script tag or as a part of a
    concatenated bundle without rewriting the module. For more info see:
    https://github.com/google/closure-library/wiki/goog.module:-an-ES6-module-like-alternative-to-goog.provide.
    module — base.js:389:120
    Global Code — Printable.js:15

I see a section there about [Bundling goog.module files with other javascript](https://github.com/google/closure-library/wiki/goog.module:-an-ES6-module-like-alternative-to-goog.provide#bundling-googmodule-files-with-other-javascript) but I have no idea how to apply that information in this case.

Do I need to modify depswriter.py so that it is outputting dependencies that work for goog.module files?  What would those dependency statements look like?  Something involving `goog.loadModule` I suppose?  Would depswriter.py copy the source in-place into the deps.js file?  The deps.js file would get quite large.

**Comment by MatrixFrog** [comment]
I will try to dig into this a bit.

**Comment by MatrixFrog** [comment]
I see that depswriter.py appears to have at least some support for goog.module (https://github.com/google/closure-library/blob/master/closure/bin/build/depswriter.py#L71) but it looks like it's out of date with the way deps.js files are actually expected to look. (Yes, this is Google, sometimes there are two or three different and slightly incompatible ways to do the same thing and it's a bit chaotic 🙃)

**Comment by myphysicslab** [comment]
Thanks for looking into it -- running uncompiled is a super valuable feature at times.

Here is a bit from my deps.js file.  Looks like that flag (indicating goog.module) is being correctly set to "true" where it should be.

    goog.addDependency('../../../src/lab/util/Parser.js',
    ['myphysicslab.lab.util.Parser'], ['myphysicslab.lab.util.Printable'], false);
    goog.addDependency('../../../src/lab/util/Printable.js',
    ['myphysicslab.lab.util.Printable'], [], true);
    goog.addDependency('../../../src/lab/util/Random.js',
    ['myphysicslab.lab.util.Random'], [], false);
    goog.addDependency('../../../src/lab/util/RandomLCG.js',
    ['myphysicslab.lab.util.RandomLCG'], ['myphysicslab.lab.util.Random'], false);
    goog.addDependency('../../../src/lab/util/Subject.js',
    ['myphysicslab.lab.util.Subject'], ['myphysicslab.lab.util.Printable'], true);
    goog.addDependency('../../../src/lab/util/SubjectEvent.js',
    ['myphysicslab.lab.util.SubjectEvent'], ['myphysicslab.lab.util.Printable',
    'myphysicslab.lab.util.Util'], true);

**Comment by MatrixFrog** [comment]
Am I doing this right? I followed the instructions at https://github.com/myphysicslab/test_module. For https://github.com/myphysicslab/test_module/blob/master/sampleConfig.mk#L10 I used a compiler built from head, then I opened build/test/SingleTest.html in a browser. It has a bunch of text, and no errors in the console. Maybe you just need to upgrade to the latest compiler?

**Comment by MatrixFrog** [comment]
Oh, or the latest closure-library.

**Comment by myphysicslab** [comment]
That project at https://github.com/myphysicslab/test_module was only set up to run compiled code; I've changed it to create debug/test/SingleTest_DEBUG.html which runs the uncompiled code.  But, it's working, to my surprise.  So now I'll try to figure out why it works in the small test_module project but not in the larger myphysicslab project.

I'll get back to you when I figure something out.

**Comment by myphysicslab** [comment]
I've added several more goog.module based classes to the test_module project, and I'm able to run uncompiled there.  I'm learning that I have to use the same ES6 class syntax for calls to `super`, which might be part of the problem in the larger project.  This problem is likely due to problems in my own code like that (still using `.call` to access a super-class constructor instead of `super`).

**Comment by jplaisted** [comment]
@MatrixFrog 

>but it looks like it's out of date with the way deps.js files are actually expected to look.

The last argument to addDependency is optional. It can either be an object literal containing flags (module and lang are the only flags right now) or a boolean. If the boolean is true it is the same as saying `{module: 'goog'}`. Boolean argument is legacy and thus is still supported. So there's nothing wrong with it besides being old. It should still load correctly.
