### ISSUE TITLE
Target ES6 or AMD/UMD modules for code splitting 

### ISSUE THREAD

**Issue by pauldraper** [google/closure-compiler#2792]
Closure Compiler output modules currently rely being executed in the same scope.

This requires one of 
1. Running the code in the global scope, polluting it and exposing it to other scripts, browser extensions, etc. which might modify the global scope in unpredictable ways.
2. Loading using eval(), which requires CSP `'unsafe-eval'` and may present security concerns.

If Closure Compiler instead outputted ES6 or AMD modules for code splitting, neither compromise would be required.

**Comment by ChadKillingsworth** [comment]
This is pretty much a duplicate of #2327 - or at least closely related.

**Comment by pauldraper** [comment]
@ChadKillingsworth yes. It was not clear to me what #2327 was, but if it intends to support https://github.com/google/closure-compiler-npm/issues/56 , then it is clear this issue is a duplicate of that.

**Comment by ChadKillingsworth** [comment]
@pauldraper google/closure-compiler-npm#56 is available in beta at https://github.com/webpack-contrib/closure-webpack-plugin. It's using a custom build of the compiler, but the last changes just landed today: d0867871bbcbba44eedcb94ed2fbdab661067f42

After the next release of closure-compiler, webpack will be an officially supported build tool.

**Comment by pauldraper** [comment]
Okay, so I this might not be a duplicate.

https://github.com/webpack-contrib/closure-webpack-plugin can only produce one module per input, or one module. I want to produce the same number of modules as the number of `--module` flags.

I don't necessarily want to change the input module resolution; I want to change output module mode.

a1.js
```javascript
goog.module('a1');
exports.print = function() { console.log('1'); console.log('3'); }
```
a2.js
```javascript
goog.module('a2');
exports.print = function() { console.log('2'); console.log('4'); }
```

b.js
```javascript
goog.module('b');
const a1 = goog.require('a1');
const a2 = goog.require('a2');
window['B'] = function() { a1.print(); a2.print(); }
```

c.js
```javascript
goog.module('c');
const a1 = goog.require('a1');
const a2 = goog.require('a2');
window['C'] =  function() { a1.print(); a1.print(); a2.print(); a2.print(); }
```

```sh
$ java -jar target/closure-compiler-1.0-SNAPSHOT.jar -O ADVANCED --module a:2: a1.js a2.js --module b:1:a b.js --module c:1:a c.js --module_output_path_prefix output-
```

output-a.js
```javascript
function a(){console.log("1");console.log("3")};function b(){console.log("2");console.log("4")};
```

output-b.js
```javascript
window.B=function(){a();b()};
```

output-c.js
```javascript
window.C=function(){a();a();b();b()};
```

which requires executing all JS in the same scope (by either running in the global scope, or using eval()).

I would like if I could load these output modules as ES6 or AMD modules.

output-a.js
```javascript
export function a(){console.log("1");console.log("3")};export function b(){console.log("2");console.log("4")};
```

output-b.js
```javascript
import * from 'a' as a;
window.B=function(){a.a();a.b()};
```

output-c.js
```javascript
import * from 'a' as a;
window.C=function(){a.a();a.a();a.b();a.b()};
```

**Comment by ChadKillingsworth** [comment]
@pauldraper With webpack, code splitting (output modules) is done via static analysis and dynamic imports (either `import()` or `require.ensure()`).

See https://webpack.js.org/guides/code-splitting/#dynamic-imports
