### ISSUE TITLE
ownerDocument.createNodeIterator not defined on Document

### ISSUE THREAD

**Issue by syranide** [google/closure-compiler#2793]
NPM version: 20180101.0.0

So apparently `createNodeIterator` is defined on Document, but not when accessing it via `ownerDocument`, despite still being of type Document.

```js
// OK
document.createNodeIterator(document.body, NodeFilter.SHOW_COMMENT);
```

```js
// WARNING - Property createNodeIterator never defined on document.body.ownerDocument of type Document
document.body.ownerDocument.createNodeIterator(document.body, NodeFilter.SHOW_COMMENT);
```

```
java -XX:+TieredCompilation -jar node_modules/google-closure-compiler/compiler.jar -O ADVANCED --js \"src/**.js\" --entry_point \"src/index\" --js_output_file \"output/bundle.js\" --create_source_map \"output/bundle.js.map\" --source_map_include_content --output_wrapper \"(function(){%output%}).call(this)\" --language_out ECMASCRIPT5_STRICT --new_type_inf --env BROWSER --module_resolution NODE --warning_level=VERBOSE --jscomp_warning=extraRequire
```

**Comment by syranide** [comment]
Or is `createNodeIterator` specific to only `HTMLDocument` and I have to explicitly cast it? I don't understand that specific W3C spec well enough to know (it says it's part of `DocumentTraversal`).

**Comment by MatrixFrog** [comment]
At least according to our externs, yes, it's only on `HTMLDocument` not on every `Document`: https://github.com/google/closure-compiler/blob/master/externs/browser/w3c_dom2.js#L249

You can definitely use a cast to get yourself unblocked, but maybe the type of the `ownerDocument` property should be `HTMLDocument` instead of `Document`.

**Comment by syranide** [comment]
@MatrixFrog OK. However, I just checked. `Document.prototype.createNodeIterator` has the function in both Chrome and Edge... browsers not following specs?

**Comment by MatrixFrog** [comment]
It is perhaps more likely that our externs are not following the specs :)

**Comment by syranide** [comment]
Do you want a PR or prefer to do it yourselves?
