### ISSUE TITLE
args4j dep should be upgraded to 2.33

### ISSUE THREAD

**Issue by paul-hammant** [google/closure-compiler#2802]

**Comment by ChadKillingsworth** [comment]
Why? Is there functionality you need from the new version?

**Comment by paul-hammant** [comment]
Diamond dependency problems - I have other things I am using in an large build that are clashing. My principle problem is with Guava (backward incompatible break - not for the first time in its multi-year history), but I'm reporting all upgrade opportunities where it is not to an alpha/beta/RC.

**Comment by MatrixFrog** [comment]
We switched to 2.33 in https://github.com/google/closure-compiler/commit/329f3001d7cb639c74e40ba6936085b99269df45

**Comment by paul-hammant** [comment]
My bad transitive deps problem in my scripts.
