### ISSUE TITLE
Destructuring doesn't work with Promise.all()

### ISSUE THREAD

**Issue by bkputnam** [google/closure-compiler#2817]
```javascript
Promise
  .all([
    Promise.resolve(true),
    Promise.resolve({foo: true, bar: 12})
  ])
  .then(([myBool, {foo, bar}]) => {});
```

Produces:

```
input0:6: WARNING - Property foo may not be present on $jscomp$destructuring$var2 of type (Boolean|{bar: number, foo: true}).
  .then(([myBool, {foo, bar}]) => {});
                   ^^^

input0:6: WARNING - Property bar may not be present on $jscomp$destructuring$var2 of type (Boolean|{bar: number, foo: true}).
  .then(([myBool, {foo, bar}]) => {});
                        ^^^

0 error(s), 2 warning(s)
```

May be related to #2595

This seems to be because the two Promises have different return types. If both Promises are `Promise.resolve({foo: true, bar: 12})` the destructuring works just fine. I would guess that somewhere in the generated js the array we're taking apart has type `Array<Boolean|{foo:boolean, bar: number}>` and that union type is the heart of the problem.

Weirdly, this problem doesn't exist if I use `goog.Promise.all(...)` instead of the native version.

I don't know if it affects the issue, but this has been happening for me with NTI turned on.

**Comment by brad4d** [comment]
I suspect the warnings do not appear when `goog.Promise.all()` is used because it actually provides type information.

This is something we cannot really fix until we implement tuple types, because that's what's needed to correctly define the type of the result of `Promise.all()`.
