### ISSUE TITLE
Eliminating local variables messes with operators with side effects

### ISSUE THREAD

**Issue by c0pperdragon** [google/closure-compiler#2818]
The process of eliminating local variables causes incorrect behavior in combination with certain expressions that have side effects on the variables:

```javascript
function side_effect_bug() {
    var x = 1;
    var y = x;
    console.log(x++,y);
}
```

compiles to :

```javascript
function side_effect_bug(){var a=1;console.log(a++,a)};
```

This is now incorrect because the original code outputs  1,1  while the new code outputs 1,2

**Comment by brad4d** [comment]
@lauraharker this seems like it could be related to the inlining stuff you've been working on lately.
Could you take a look? Thanks.

**Comment by lauraharker** [comment]
Yep, this is the FlowSensitiveInlineVariables pass.

For a variable definition like `var y = x;`, and usage like `console.log(x++, y)`, the pass checks for writes to `x` between the definition and usage of `y`, but not writes to `x` in the same control flow node as the usage.
