### ISSUE TITLE
Exponential operator in if condition is not transpiled

### ISSUE THREAD

**Issue by teppeis** [google/closure-compiler#2821]
Original source code:
```js
if (2 ** 3 > 0) { alert('test'); }
```
Expected transpiled code:
```js
0 < Math.pow(2, 3) && alert("test");
```
[Actual result](https://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540compilation_level%2520SIMPLE_OPTIMIZATIONS%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250Aif%2520(2%2520**%25203%2520%253E%25200)%2520%257B%2520alert('test')%253B%2520%257D)
```js
0 < 2 ** 3 && alert("test");
```

Same result in ternary operator.

----

Also, it throws an error [in Advanced Optimization](https://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540compilation_level%2520ADVANCED_OPTIMIZATIONS%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%2540formatting%2520pretty_print%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250Aif%2520(2%2520**%25203%2520%253E%25200)%2520%257B%2520alert('test')%253B%2520%257D).
```
JSC_INTERNAL_ERROR_UNEXPECTED_TOKEN: Internal Error: TypeCheck doesn't know how to handle EXPONENT at line 1 character 4
if (2 ** 3 > 0) { alert('test'); }
    ^
```

----
If another exponential operator is in body, [they are transpiled](https://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540compilation_level%2520SIMPLE_OPTIMIZATIONS%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%2540formatting%2520pretty_print%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250Aif%2520(2%2520**%25203%2520%253E%25200)%2520%257B%2520alert(2%2520**%25203)%253B%2520%257D).
Original:
```js
if (2 ** 3 > 0) { alert(2 ** 3); }
```
Transpiled:
```js
0 < Math.pow(2, 3) && alert(Math.pow(2, 3));
```

**Comment by MatrixFrog** [comment]
I can't seem to repro this with the compiler jar so this seems to be a quirk of the webservice. Will take a look.

**Comment by teppeis** [comment]
@MatrixFrog see this repo for repro https://github.com/teppeis-sandbox/closure-compiler-repro-2821

**Comment by brad4d** [comment]
@teppeis I've reproduced this in the unit test. I'm debugging it now.

**Comment by brad4d** [comment]
Even simpler repro

```javascript
(2 ** 3) / 3;
```
Looks like the root cause is in IRFactory.
It fails to record that the exponent operator is used in some cases.

**Comment by brad4d** [comment]
correction to repro
```2 ** 3 > 3```

**Comment by brad4d** [comment]
fix sent for internal review

**Comment by teppeis** [comment]
@MatrixFrog @brad4d thanks!
