### ISSUE TITLE
[JS] When building source maps getting p.getLineCount is not a function

### ISSUE THREAD

**Issue by arichiardi** [google/closure-compiler#2826]
Hello Google folks!

First of all I am sorry if this is not the place for this bug report, it is concerning the JS port.
Note that I don't have a reproducible case with only the compiler, but I can make one in case it is needed.

When generating source maps using `lumo`, which uses `google-closure-compiler-js`, I get an error:

```
p.getLineCount is not a function
	 HJ (google-closure-compiler-js.cljs:7737:245)
	 l2c (google-closure-compiler-js.cljs:6713:84)
	 zHb (google-closure-compiler-js.cljs:5842:99)
	 P1c (google-closure-compiler-js.cljs:6145:152)
	 tDb (google-closure-compiler-js.cljs:5056:103)
	 iDb (google-closure-compiler-js.cljs:7117:315)
	 jDb (google-closure-compiler-js.cljs:5569:102)
	 yIb (google-closure-compiler-js.cljs:6208:201)
	 TIb (google-closure-compiler-js.cljs:7722:452)
	 (UIb.VIb)
	 jJb (google-closure-compiler-js.cljs:4846:36)
	 wIb (google-closure-compiler-js.cljs:1758:23)
	 NIb (google-closure-compiler-js.cljs:6165:148)
	 (OIb.PIb)
	 jJb (google-closure-compiler-js.cljs:4846:36)
	 sjd (google-closure-compiler-js.cljs:6538:35)
	 jjd (google-closure-compiler-js.cljs:7692:407)
	 hK (google-closure-compiler-js.cljs:1833:29)
	 kK (google-closure-compiler-js.cljs:3201:44)
	 (google-closure-compiler-js.cljs:3404:46)
	 compile (google-closure-compiler-js.cljs:8106:15)
	 Function.lumo.closure.optimize.cljs$core$IFn$_invoke$arity$variadic (evalmachine.<anonymous>:2623:123)
...
```

The steps are described here https://github.com/anmonteiro/lumo/issues/361, but more importantly I was wondering whether the source map portion of the code is known to be stable.

Thanks a lot for your hard work!

**Comment by MatrixFrog** [comment]
It looks like we need to write an implementation at https://github.com/google/closure-compiler/blob/master/src/com/google/debugging/sourcemap/SourceMapObjectParserJs.java#L60

I assume just `return this.lineCount;` will do.

**Comment by arichiardi** [comment]
So this might be a very noob question but I got a compiler error saying that a `native` method cannot have an implementation. Additionally, it seems that `.getLineCount` is used only there being a private class. I might be wrong but maybe the intent there was to get rid of it?

Line 94 can become:

```java
    builder.setLineCount(sourceMap.lineCount() != null ? sourceMap.lineCount : -1);
```

What do you think @MatrixFrog?

**Comment by arichiardi** [comment]
Just came across the syntax with `*/`

Maybe:

```java
    @JsMethod
    native Object getLineCount() /*-{ return this.lineCount; }-*/;
```

?

**Comment by arichiardi** [comment]
I confirm the proposed PR solves the issue.
