### ISSUE TITLE
Closure Compiler does not look for ES6 module on its own

### ISSUE THREAD

**Issue by ctsrc** [google/closure-compiler#2838]
Minimal reproduction of issue:

    touch bar.js

    cat > foo.js <<EOF
    import * as bar from './bar.js'
    EOF

    npx google-closure-compiler --js foo.js

Result:

    foo.js:1: ERROR - Failed to load module "./bar.js"
    import * as bar from './bar.js'
    ^
    
    1 error(s), 0 warning(s)

Running the google-closure-compiler command under `strace -f` and grepping the output indicates that Closure Compiler makes no attempt at locating the bar.js file;

    strace -f npx google-closure-compiler --js foo.js 2>&1 | grep bar

Output:

    [pid 10024] read(5, "import * as bar from './bar.js'\n", 8192) = 32
    [pid 10010] write(2, "foo.js:1: ERROR - Failed to load"..., 85foo.js:1: ERROR - Failed to load module "./bar.js"
    import * as bar from './bar.js'

In order for Closure Compiler to find the referenced module it must be explicitly passed as an argument.

    npx google-closure-compiler --js foo.js --js bar.js

Could you make it so that it will look for the file at the location specified in the import statement without having to pass it as an argument on the command-line?

**Comment by MatrixFrog** [comment]
I think this is a case where I would argue "explicit is better than implicit" since this forces users to explicitly state all dependencies. Note that you can use globs like `*.js` to make this less tedious though.

**Comment by ChadKillingsworth** [comment]
Yes this is very much by design. All potential input files must be provided to the compiler using globs or a build tool that traces dependencies like webpack.

The compiler will order and drop any files not reachable.

**Comment by ctsrc** [comment]
Upon further thought I have come to realize that you are absolutely right it is better that it is explicit about this. Thank you for your time and sorry for the disturbance.
