### ISSUE TITLE
ES6 transpilation of arrow functions

### ISSUE THREAD

**Issue by digitalnature** [google/closure-compiler#2853]
I was testing the es6 transpilation feature on https://closure-compiler.appspot.com
and I noticed that the arrow functions are not bound to "this" in the output code. Is this normal?

Eg.

```
let x = 2;
f(v => {
  return x + v;
});
```

Output is:
```
var x = 2;
f(function(a) {
  return x + a;
});
```

But I think it should be:

```
var x = 2;
f((function(a) {
  return x + a;
}).bind(this));
```

**Comment by MatrixFrog** [comment]
If the function never references `this` then it doesn't matter. If it does, then `.bind(this)` would be one way of transpiling it, but we went with a different way:

https://closure-compiler-debugger.appspot.com/#input0%3Df(()%2520%253D%253E%2520alert(this))%253B%26input1%26conformanceConfig%26externs%3Dvar%2520alert%252C%2520f%253B%26refasterjs-template%26includeDefaultExterns%3Dtrue%26CHECK_SYMBOLS%3Dtrue%26MISSING_PROPERTIES%3Dtrue%26TRANSPILE%3Dtrue%26CHECK_TYPES%3Dtrue%26CLOSURE_PASS%3Dtrue%26PRESERVE_TYPE_ANNOTATIONS%3Dtrue%26PRETTY_PRINT%3Dtrue

As I recall, we heard from someone on the V8 team that this pattern (the "var self = this" pattern) is probably faster in general.
