### ISSUE TITLE
Missing extern for oMatchesSelector

### ISSUE THREAD

**Issue by blickly** [google/closure-compiler#286]
This issue was imported from Closure Compiler's previous home at http://closure-compiler.googlecode.com

The original discussion is archived at:
http://blickly.github.io/closure-compiler-issues/#892

**Comment by Dominator008** [comment]
Closed by https://github.com/google/closure-compiler/commit/263ff819da0541265f4b9b67474b970790ace2f3. Added here: https://github.com/google/closure-compiler/blob/cb6f30dd11b5d1fa77f3dde910448df9a22505ce/externs/browser/w3c_selectors.js#L107-L113.
