### ISSUE TITLE
v20180319 binaries not available

### ISSUE THREAD

**Issue by cnsgithub** [google/closure-compiler#2860]
v20180319 was released four days ago but is neither available on maven nor on https://github.com/google/closure-compiler/wiki/Binary-Downloads. Could you please add it? Thanks.

**Comment by MatrixFrog** [comment]
I'm having some trouble getting Maven to work. Hopefully it will be up today.

**Comment by ChadKillingsworth** [comment]
I would argue it hasn't been released yet.

The standard process is to tag a release and run it internally at Google first. If nothing breaks, the official open source release is made. Release notes haven't been posted either: https://github.com/google/closure-compiler/wiki/Binary-Downloads

**Comment by MatrixFrog** [comment]
gpg and Maven are not being kind to me today, sorry. @blickly is out today but he did the most recent release so I'll try to get some help from him on Monday.

**Comment by MatrixFrog** [comment]
It's up on Maven now (https://repo1.maven.org/maven2/com/google/javascript/closure-compiler/v20180319/) but not NPM yet or anywhere else. I'll try to finish the rest of the release process tomorrow and I'll send a note on the mailing list when it's done. Sorry for the delay.
