### ISSUE TITLE
Valid @suppress annotation is marked as bad

### ISSUE THREAD

**Issue by jplaisted** [google/closure-compiler#2866]
This is causing the Closure Library Travis build to fail:
https://travis-ci.org/google/closure-library/builds/356113423

Per @concavelenz this annotation is valid. Why did it just start failing? Also, assuming it is valid, then our documentation should be updated:
https://github.com/google/closure-compiler/wiki/@suppress-annotations

```
/**
 * The root JS object. Can be null.
 * @type {*}
 * @protected
 * @suppress {underscore|visibility}
 */
goog.ds.JsDataSource.prototype.root_;
```

**Comment by MatrixFrog** [comment]
I'm guessing this will be fixed with a compiler release. I'm working on getting the release out now.

**Comment by MatrixFrog** [comment]
Actually I take that back. Not a compiler release; just a compiler MOE push. Which should have happened yesterday but I didn't manage to get to it. I did one today though, so I'll try restarting the build and I believe it should pass this time.

**Comment by jplaisted** [comment]
Thanks!
