### ISSUE TITLE
Wired behaviour : Closure overwriting function argument

### ISSUE THREAD

**Issue by alaa-eddine** [google/closure-compiler#2869]
Hi,

I stumbled upon a very strange behavior, tried to make a simple code to demonstrate it 

this is the original js code : 

```javascript
function fadeTo(value, time = 250, delay = 0) {
    let contextResolve;

    const promise = new Promise((resolve, reject) => {
        contextResolve = resolve;
    });

    const tween = new Game.utils.Tween({})
        .to({ alpha: value }, time);
        
    tween.onComplete(contextResolve);
    tween.start();
    return promise;
}
```

When compiled using closure I obtain : 

```javascript
'use strict';
function fadeTo(a, d=250, b) { //<-- my "value" argument translated to "a"
    let c;
    b = new Promise((a,b)=>{
        c = a
    }
    );
    a = (new Game.utils.Tween({})).to({  //<-- Here is line 8
        alpha: a
    }, d);
    a.onComplete(c);
    a.start();
    return b
}
;
```

if you compare the codes I have a variable called "value" passed as first argument to fadeTo() function.
this variable got translated to "a" by closure compiler.

but if you see line 8, this same variable is used to reference the Tween object, which should use a different variable (my original code was const tween) .

this breaks the behavior of the code since "a" variable don't hold the original value anymore, and if I pass it to an internal object (like the alpha value in my code) it's the tween object which got passed instead of the original value.

I tried to move the code inside the promise but got similar broken code.

also tried with both : --language_out ECMASCRIPT6/ECMASCRIPT5 ... still broken.

is this an intended behavior or something wrong with my code ? or is it a bug ?

EDIT : here is an over simplified version, just compile it using the simple optimizations option
https://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%2540compilation_level%2520SIMPLE_OPTIMIZATIONS%250A%252F%252F%2520%2540formatting%2520pretty_print%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250A%250Afunction%2520Foo(value)%2520%257B%250A%2520%2520%2520%2520const%2520tween%2520%253D%2520Bar(%257Bparam%253Avalue%257D)%253B%250A%2520%2520%2520%2520tween.start()%253B%250A%2520%2520%2509return%2520tween%253B%250A%257D%250A%250A%250A%250A

**Comment by alaa-eddine** [comment]
for information this is the command line I used to compile the code 

```
java -jar closure-compiler.jar  --js /path/to/source.js  --js_output_file out.js --jscomp_off=internetExplorerChecks --language_in ECMASCRIPT6 --language_out ECMASCRIPT6

```

**Comment by lauraharker** [comment]
Hi,

Both your examples look like they are compiled correctly to me. This is something the compiler does in [CoalesceVariableNames](https://github.com/google/closure-compiler/blob/master/src/com/google/javascript/jscomp/CoalesceVariableNames.java).

In your original example, in `a = (new Game.utils.Tween({})).to({alpha: a}, d);`, first the current value of `a` is taken and used to create an object `{alpha: a}` that gets passed into the `to` method. Only after that method completes does `a` get reassigned to a Tween. There's no difference between `a = foo({alpha: a}); use(a);` and `const tween = foo({alpha: a}); use(tween);`

Marking as WAI - please reopen if you find an example that we can run in the console that produces different output post-compilation.
