### ISSUE TITLE
BanUnknownThis prevents the use of "this" in static ES6 methods

### ISSUE THREAD

**Issue by joeyparrish** [google/closure-compiler#2880]
[Shaka Player](https://github.com/google/shaka-player/) is using BanUnknownThis in our [conformance rules](https://github.com/google/shaka-player/blob/a09ae24b8533f2b8c6f2d9ee988f572010b7cd33/build/conformance.textproto#L47).  We are slowly transitioning to ES6, and today I noticed that `BanUnknownThis` prevents me from using `this` in static ES6 methods, even though `this` should refer to the class itself rather than some instance.

I'm still using the 20180204 release of Closure compiler, in case that's relevant.  Here's a simplified repro:

```
# unknownthis.textproto 
requirement {
  type: CUSTOM
  java_class: 'com.google.javascript.jscomp.ConformanceRules$BanUnknownThis'
  error_message: 'Failed to infer type of "this"!'
}
```

```js
// es6_static_this.js
goog.provide('ns.Foo');

ns.Foo = class {
  /** @return {number} */
  static bar() { return this.baz() + 1; }

  /** @return {number} */
  static baz() { return 1; }
};
```

```sh
java -jar compiler.jar \
  --jscomp_error=* \
  --conformance_configs unknownthis.textproto \
  es6_static_this.js \
  > /dev/null
```

This produces the output:
```
es6_static_this.js:6: ERROR - Violation: Failed to infer type of "this"!
  static bar() { return this.baz() + 1; }
                        ^^^^
```

I have found that without `--jscomp_error=*`, I don't get this violation at all, but I'm not sure how to interpret that.

Is this a duplicate of #2397, or is this something slightly different?

Is there a workaround you can suggest, other than whitelisting files for the BanUnknownThis rule?

Thanks!

**Comment by MatrixFrog** [comment]
debugger repro
https://closure-compiler-debugger.appspot.com/#input0%3Dgoog.provide('ns.Foo')%253B%250A%250Ans.Foo%2520%253D%2520class%2520%257B%250A%2520%2520%252F**%2520%2540return%2520%257Bnumber%257D%2520*%252F%250A%2520%2520static%2520bar()%2520%257B%2520return%2520this.baz()%2520%252B%25201%253B%2520%257D%250A%250A%2520%2520%252F**%2520%2540return%2520%257Bnumber%257D%2520*%252F%250A%2520%2520static%2520baz()%2520%257B%2520return%25201%253B%2520%257D%250A%257D%253B%26input1%26conformanceConfig%3Drequirement%2520%257B%250A%2520%2520type%253A%2520CUSTOM%250A%2520%2520java_class%253A%2520'com.google.javascript.jscomp.ConformanceRules%2524BanUnknownThis'%250A%2520%2520error_message%253A%2520'Failed%2520to%2520infer%2520type%2520of%2520%2522this%2522!'%250A%257D%26externs%26refasterjs-template%26includeDefaultExterns%3Dtrue%26CHECK_SYMBOLS%3Dtrue%26MISSING_PROPERTIES%3Dtrue%26TRANSPILE%3Dtrue%26CHECK_TYPES%3Dtrue%26CLOSURE_PASS%3Dtrue%26PRESERVE_TYPE_ANNOTATIONS%3Dtrue%26PRETTY_PRINT%3Dtrue

**Comment by MatrixFrog** [comment]
It looks like at https://github.com/google/closure-compiler/blob/b13f1a38f104683eccb617de6eb9fa53a6657e9a/src/com/google/javascript/jscomp/Es6RewriteClass.java#L475 we are explicitly adding `@this {?}` to the JSDoc but I don't remember why we did that, instead of the class name.

As a workaround, does it work to write `ns.Foo.baz()` instead?

**Comment by joeyparrish** [comment]
I believe it would work to use the class name explicitly instead of `this`.

**Comment by ChadKillingsworth** [comment]
See #2397

**Comment by princed** [comment]
I've checked, it was fixed by https://github.com/google/closure-compiler/commit/5b1e5316e5228d6d9f205e28440d67d9ec007f4b, see https://github.com/google/closure-compiler/issues/3340
