### ISSUE TITLE
Compiler (v20180402) produces invalid JS.

### ISSUE THREAD

**Issue by gumm** [google/closure-compiler#2883]
When compiling the following code:

```
const funcGetter = a => {
  const funcs = {
    'a': () => true,
    'b': () => false
  };
  return funcs[a] || undefined;
};
funcGetter('a');
```
with this compiler options:

`java -jar node_modules/google-closure-compiler/compiler.jar --language_in=ES6_Strict --language_out=ES6_Strict --compilation_level=SIMPLE err.js`

it produces this output:

`'use strict';const funcGetter=(a)=>{a:()=>!0,b:()=>!1}[a]||void 0;funcGetter("a");`

which is in fact not valid.

In my view, the valid version of this output should be:

`'use strict';const funcGetter=(a)=>({a:()=>!0,b:()=>!1}[a]||void 0);funcGetter("a");`

Is this a bug, or am I doing something wrong?
I am using compiler v20180402

**Comment by lauraharker** [comment]
Working on a fix in the code printer.

Object pattern assignments in an arrow function body also lack parentheses, e.g.
```javascript
var fn = () => ({a} = obj);
```
becomes
```javascript
var fn = () => {a} = {}; // syntax error
```
https://closure-compiler-debugger.appspot.com/#input0%3Dvar%2520a%253B%250Avar%2520fn%2520%253D%2520()%2520%253D%253E%2520(%257Ba%257D%2520%253D%2520%257B%257D)%253B%26input1%26conformanceConfig%26externs%26refasterjs-template%26CHECK_SYMBOLS%3Dtrue%26MISSING_PROPERTIES%3Dtrue%26CHECK_TYPES%3Dtrue%26CLOSURE_PASS%3Dtrue%26PRESERVE_TYPE_ANNOTATIONS%3Dtrue%26PRETTY_PRINT%3Dtrue

**Comment by lauraharker** [comment]
Submitted a fix internally.
