### ISSUE TITLE
NPE using NTI + TRANSPILE

### ISSUE THREAD

**Issue by Yannic** [google/closure-compiler#2884]
[repo](https://closure-compiler-debugger.appspot.com/#input0%3D%252F**%2520%2540interface%2520*%252F%250Afunction%2520Foo()%2520%257B%257D%250A%250A%252F**%2520%2540return%2520%257Bfunction(new%253AFoo)%257D%2520*%252F%250Afunction%2520implFoo()%2520%257B%257D%250A%26input1%26conformanceConfig%26externs%26refasterjs-template%26TRANSPILE%3Dtrue%26CHECK_TYPES_NEW_INFERENCE%3Dtrue)

It doesn't crash if TRANSPILE is disabled, or when NTI is disabled.

**Comment by concavelenz** [comment]
NTI is being removed.
