### ISSUE TITLE
Prototype renamed when specific set of passes are selected

### ISSUE THREAD

**Issue by Yannic** [google/closure-compiler#2885]
If `MISSING_PROPERTIES`, `TRANSPILE`, `AMBIGUATE_PROPERTIES` and `PROPERTY_RENAMING` passes are selected, the compiler will rename `prototype`. It doesn't seem to matter if any other pass is selected.

https://closure-compiler-debugger.appspot.com/#input0%3D%252F**%2520%2540interface%2520*%252F%250Afunction%2520Foo()%2520%257B%257D%250A%250A%252F**%2520%2540return%2520%257B!Foo%257D%2520*%252F%250AFoo.prototype.foo%2520%253D%2520function()%2520%257B%257D%253B%250A%26input1%26conformanceConfig%26externs%26refasterjs-template%26MISSING_PROPERTIES%3Dtrue%26TRANSPILE%3Dtrue%26AMBIGUATE_PROPERTIES%3Dtrue%26PROPERTY_RENAMING%3Dtrue%26PRESERVE_TYPE_ANNOTATIONS%3Dtrue%26PRETTY_PRINT%3Dtrue

**Comment by lauraharker** [comment]
This is really just an `AmbiguateProperties` issue. The other passes are needed to cause `AmbiguateProperties `to run. (It can't run on untranspiled code, doesn't run unless you select property renaming, and doesn't run unless typechecking is enabled, which MISSING_PROPERTIES triggers).

FWIW if you select "Include core externs", or ever reference `Function.prototype` in the externs, this doesn't happen. 

We could add a special case for `prototype` in `AmbiguateProperties` too, though. `RenameProperties` already treats `prototype` specially. https://github.com/google/closure-compiler/blob/23507048c07f56c650b26081cd3ab5db18bbc6b5/src/com/google/javascript/jscomp/RenameProperties.java#L88 Feel free to send a PR if you're interested in fixing this :)

**Comment by Yannic** [comment]
Good to hear that this is really only a special case.
Adding a special case to `AmbiguateProperties` sounds reasonable, though.
