### ISSUE TITLE
Remove unused method traverseEs6

### ISSUE THREAD

**Issue by thheller** [google/closure-compiler#2892]
https://github.com/google/closure-compiler/commit/fee5195c6e1aa9f5d446351be66aa0c81b823a7d

Removes the `NodeTraversal.traverseEs6` static function which I guess got refactored to be `NodeTraversal.traverse` now (which it also delegates to). I'm using it some [shadow-cljs](https://github.com/thheller/shadow-cljs/tree/master/src/main/shadow/build/closure) utility passes.

Please consider keeping the `NodeTraversal.traverseEs6` function around for a few versions since it creates unnecessary breakage otherwise. I will update my code but can't because `NodeTraversal.traverse` is not available yet.

Just removing the function without deprecating it first (it isn't deprecated in 20180402) makes upgrading a bit painful.

**Comment by MatrixFrog** [comment]
Ah sorry. We usually do keep it around for one version but I forgot to do it in this case. Would using one the "snapshot" builds from https://oss.sonatype.org/content/repositories/snapshots/com/google/javascript/closure-compiler/1.0-SNAPSHOT/ help?

**Comment by MatrixFrog** [comment]
Yeah, we'll put it back, at least for one release. My bad.
