### ISSUE TITLE
Cannot create an enum with computed properties

### ISSUE THREAD

**Issue by cvializ** [google/closure-compiler#2906]
I am trying to create an enum using computed properties with the values of another enum. I have a link to a Closure Compiler demo with code to reproduce.

[Closure Compiler demo link](https://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540compilation_level%2520ADVANCED_OPTIMIZATIONS%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250A%252F**%2520%2540enum%2520%257Bstring%257D%2520*%252F%250Aconst%2520DateFieldType%2520%253D%2520%257B%250A%2520%2520DATE%253A%2520'input'%252C%250A%2520%2520START_DATE%253A%2520'start-input'%252C%250A%2520%2520END_DATE%253A%2520'end-input'%252C%250A%257D%253B%250A%250A%252F**%250A%2520*%2520%2540enum%2520%257Bstring%257D%250A%2520*%252F%250Aconst%2520DateFieldNameByType%2520%253D%2520%257B%250A%2520%2520%255BDateFieldType.DATE%255D%253A%2520'date'%252C%250A%2520%2520%255BDateFieldType.START_DATE%255D%253A%2520'start-date'%252C%250A%2520%2520%255BDateFieldType.END_DATE%255D%253A%2520'end-date'%252C%250A%257D%253B%250A%250Aexport%2520default%2520DateFieldNameByType%253B)
```js
// ==ClosureCompiler==
// @compilation_level ADVANCED_OPTIMIZATIONS
// @output_file_name default.js
// ==/ClosureCompiler==

/** @enum {string} */
const DateFieldType = {
  DATE: 'input',
  START_DATE: 'start-input',
  END_DATE: 'end-input',
};

/**
 * @enum {string}
 */
const DateFieldNameByType = {
  [DateFieldType.DATE]: 'date',
  [DateFieldType.START_DATE]: 'start-date',
  [DateFieldType.END_DATE]: 'end-date',
};

export default DateFieldNameByType;
```

Compiling with Advanced Optimizations produces the following warning:

> JSC_ENUM_INITIALIZER_NOT_ENUM: enum initializer must be an object literal or an enum at line 11 character 6
> ```js
> const DateFieldNameByType = {
>       ^
> ```

Since this information is only needed at compile time, the compiler should be able to treat these computed properties as static values from the enum above and not produce the warning.

**Comment by brad4d** [comment]
An enum isn't the right way to solve this problem.
You should use a map.

```javascript
/**
 * @type {Map<DateFieldType, string>}
 */
const DateFieldNameByType = new Map(
    [DateFieldType.DATE, 'date'],
    [DateFieldType.START_DATE, 'start-date'],
);
```
