### ISSUE TITLE
JSC_REDECLARED_VARIABLE_ERROR: Illegal redeclared variable

### ISSUE THREAD

**Issue by thheller** [google/closure-compiler#2909]
```
let types;
[x, ...types] = [1,2,3];
```
Compiling this piece of code yields the following error in the Compiler but executes fine in Chrome.
```
JSC_REDECLARED_VARIABLE_ERROR: Illegal redeclared variable: types at line 3 character 7
[x, ...types] = [1,2,3];
```

Reproduced with the [closure-compiler.appspot.com](https://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540compilation_level%2520SIMPLE_OPTIMIZATIONS%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250A%252F%252F%2520ADD%2520YOUR%2520CODE%2520HERE%250Alet%2520types%253B%250A%255Bx%252C%2520...types%255D%2520%253D%2520%255B1%252C2%252C3%255D%253B%250A%250A) web compiler and the `v20180422` release.

Seen in the [jsonld](https://github.com/digitalbazaar/jsonld.js/blob/6da474f390807849bba761a5ddbb5b2492ad96c2/lib/compact.js#L490-L491) `npm` package.

**Comment by brad4d** [comment]
For some reason `REST` is included in the list of `DECLARATION_PARENTS` in `Reference.java`

**Comment by brad4d** [comment]
I'm sending a fix for internal review.
Thanks for the report @thheller .
