### ISSUE TITLE
dependencies in maven deployment

### ISSUE THREAD

**Issue by hbrackmann** [google/closure-compiler#2912]
currently the dependencies are embedded into the jar:
That cause major problems if you use the closure-compiler as a library:
-incompatible with Java 9/10
-impossible to resolve dependency conflicts

simular bug:
https://github.com/google/closure-compiler/issues/2815

**Comment by ChadKillingsworth** [comment]
There are 2 maven artifacts - the standard and an unshaded. I believe the unshaded one does not have dependencies bundled.

**Comment by hbrackmann** [comment]
thx, was confused cause the wepage don't list the dependencies but it works fine with the unshaded version.
