### ISSUE TITLE
Advanced compilation, easy mode

### ISSUE THREAD

**Issue by 1der1** [google/closure-compiler#2913]
The advanced compilation is so powerful; it should be easy to use.

I am using a lot of external APIs and the way to declare all these externs seems to be tedious.

What about having an advanced, easy mode to spare all these declarations for exports and externs?

My suggestions for the easy mode:
1) Unresolved symbols are considered externs. The compiler generates a list for you to check.
2) Global exports could be declared by providing a comma-separated list of symbols. These symbols are protected against renaming, no matter the functionality.

**Comment by ChadKillingsworth** [comment]
I'm closing this because while interesting there is nobody currently intending to work on it.

**Comment by concavelenz** [comment]
Consider using simple mode + --assume_output_wrapper which doesn't do property optimizations
