### ISSUE TITLE
Rate limiting

### ISSUE THREAD

**Issue by estraschnov** [google/closure-compiler#2916]
Hello,

I'm hitting some rate limiting issues (getting "Too many compiles"). Is there a way to avoid this? I'm happy to use a key and pay.

Thanks

**Comment by shicks** [comment]
Can you be more specific about where you're seeing this?  Closure Compiler is primarily a tool you run on your own machine, so there should be no rate limiting involved there.  If it's for an online version of the compiler, which one are you using?

**Comment by concavelenz** [comment]
The closure-compiler.appspot.com is provided as a free service and imposes limits. If you need more than that likely you should be running the compiler locally.
