### ISSUE TITLE
Doesn't remove code that never reaches

### ISSUE THREAD

**Issue by apatozi** [google/closure-compiler#2923]
when using Const Debug=false (same should be with var) at the top of document and then compiling it leaves code that will never be reached inside funcions 

E.X : var foo = {
    bar: function(){
          if(Debug){
               //do some debug things
          }
          //do some other things
    }
}

**Comment by blickly** [comment]
I wasn't able to reproduce this:
https://closure-compiler-debugger.appspot.com/#input0%3Dconst%2520Debug%2520%253D%2520false%253B%250Avar%2520foo%2520%253D%2520%257B%250Abar%253A%2520function()%257B%250Aif(Debug)%257B%250A%252F%252Fdo%2520some%2520debug%2520things%250Abaz()%250A%257D%250A%252F%252Fdo%2520some%2520other%2520things%250Abazz()%250A%257D%250A%257D%26input1%26conformanceConfig%26externs%3Dvar%2520baz%252C%2520bazz%253B%26refasterjs-template%26includeDefaultExterns%3Dtrue%26CHECK_SYMBOLS%3Dtrue%26MISSING_PROPERTIES%3Dtrue%26TRANSPILE%3Dtrue%26CHECK_TYPES%3Dtrue%26FOLD_CONSTANTS%3Dtrue%26INLINE_CONSTANTS%3Dtrue%26CLOSURE_PASS%3Dtrue%26PRESERVE_TYPE_ANNOTATIONS%3Dtrue%26PRETTY_PRINT%3Dtrue
