### ISSUE TITLE
Setting of global object property is optimized away despite being used in constructor

### ISSUE THREAD

**Issue by atom-b** [google/closure-compiler#2924]
This only repros with SIMPLE_OPTIMIZATIONS. Advanced generates code that behaves as expected.

Repro:

```
// ==ClosureCompiler==
// @output_file_name default.js
// @compilation_level SIMPLE_OPTIMIZATIONS
// @formatting pretty_print
// ==/ClosureCompiler==

var flags = {internal: false};

/** @constructor */
var checkFlag = function() {
	if(!flags.internal ) {
		throw ("Error: flags.internal is " + flags.internal + "!");
    }
};

var getCheckFlag = function() {
    flags.internal = true;
    var cf = new checkFlag();
    // flags.checkFlag = checkFlag(); // works
    flags.internal = false;
    return cf;
};

var myCheckFlag = getCheckFlag();
```

Output:

```
var flags = {internal:!1}, checkFlag = function() {
  if (!flags.internal) {
    throw "Error: flags.internal is " + flags.internal + "!";
  }
}, getCheckFlag = function() {
  var a = new checkFlag;
  flags.internal = !1;
  return a;
}, myCheckFlag = getCheckFlag();
```
`checkFlag()` throws because there is no `flags.internal = !0;` before `var a = new checkFlag;`.

Possibly related to #2874 ?

**Comment by lauraharker** [comment]
Debugger repro:
https://closure-compiler-debugger.appspot.com/#input0%3Dvar%2520flags%2520%253D%2520%257Binternal%253Afalse%257D%253B%250A%250A%252F**%2520%2540constructor%2520*%252F%2520var%2520checkFlag%2520%253D%2520function()%2520%257B%250A%2520%2520if%2520(!flags.internal)%2520%257B%250A%2520%2520%2520%2520throw%2520%2522Error%253A%2520flags.internal%2520is%2520%2522%2520%252B%2520flags.internal%2520%252B%2520%2522!%2522%253B%250A%2520%2520%257D%250A%257D%253B%250A%250A(function()%2520%257B%250A%2520%2520flags.internal%2520%253D%2520true%253B%250A%2520%2520var%2520cf%2520%253D%2520new%2520checkFlag%253B%250A%2520%2520flags.internal%2520%253D%2520false%253B%250A%2520%2520return%2520cf%253B%250A%257D)()%253B%250A%26input1%26conformanceConfig%26externs%26refasterjs-template%26CHECK_SYMBOLS%3Dtrue%26MISSING_PROPERTIES%3Dtrue%26TRANSPILE%3Dtrue%26CHECK_TYPES%3Dtrue%26DEAD_ASSIGNMENT_ELIMINATION%3Dtrue%26REMOVE_UNUSED_VARIABLES%3Dtrue%26CLOSURE_PASS%3Dtrue%26PRESERVE_TYPE_ANNOTATIONS%3Dtrue%26PRETTY_PRINT%3Dtrue

Looks like this is a bug in `DeadPropertyAssignmentElimination`. 

If I change `new checkFlag` to just `checkFlag()`, then `flags.internal = true;` is not eliminated. Probably something in the pass needs to handle NEW the same way it handles CALL
