### ISSUE TITLE
Add option to strip version #s (while preserving copyright info)

### ISSUE THREAD

**Issue by MattKohnen** [google/closure-compiler#2931]
Open source licenses typically require the preservation of copyright info, but do not require version #s to be retained.  And security considerations necessitate removing version #s.  It would be very helpful to have that as an option for the Closure compiler.

**Comment by ChadKillingsworth** [comment]
I have no idea how this would be done. The compiler simply recognizes comments with `/*!` /** @preserve */` or `/** @license */` and ensures they are kept. It also de-duplicates them.

That's the extent of the processing though.

This sounds like something better suited for a pre or post compilation tool.
