### ISSUE TITLE
Using the result of an assignment to module.exports causes an error

### ISSUE THREAD

**Issue by nichtverstehen** [google/closure-compiler#2932]
Simple code:
```
const width = 800;
const vwidth = exports.vwidth = width;
```
compiled with `--process_common_js_modules` results in an error:
```
a.js:2: ERROR - variable width is undeclared
const vwidth = exports.vwidth = width;
                                ^^^^^
```
With `--jscomp_warning=undefinedVars` and without optimization we get the following output:
```
var module$experimental$users$cyriln$js$a = {"default":{}};
module$experimental$users$cyriln$js$a["default"].vwidth = 800;
var vwidth$$module$experimental$users$cyriln$js$a = module$experimental$users$cyriln$js$a["default"].vwidth = width;
```
Where did `width` go?

**Comment by ray007** [comment]
You seem to only export `vwidth`, not `width`.

**Comment by nichtverstehen** [comment]
@ray007 Yes, that's true. I only intend to export `vwidth`. The error I am talking about happens within the module, not when a user module tries to access `width`.

If it helps, I could rename variables so:
```
const internalFoo = 800;
const internalBar = exports.vwidth = internalFoo;
```

If you compile solely this code even without anything to import this module, you will get the error: `internalFoo is undeclared`.

**Comment by cpcallen** [comment]
I just encountered this bug while trying to closure-compile [node-weak](https://github.com/TooTallNate/node-weak); I managed to work around it by adding an externs file containing definitions of the names the compiler claimed not to find (i.e., `width` in example above).

**Comment by ChadKillingsworth** [comment]
The fix for this will be part of the next release.
