### ISSUE TITLE
The return value from Function.prototype.bind.bind is not marked as pure

### ISSUE THREAD

**Issue by The-Peppester** [google/closure-compiler#2933]
Function.prototype.bind.bind is effectively marked as pure [as seen here](https://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540compilation_level%2520ADVANCED_OPTIMIZATIONS%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250A(function(%252F**%2540type%257BObject%257D*%252F%2520self)%257B%250A%2520%2520%2522use%2520strict%2522%253B%250A%2520%2520var%2520Function%2520%253D%2520%252F**%2540constructor*%252F%2520self.Function%253B%250A%2520%2520var%2520FunctionProto%2520%253D%2520Function.prototype%253B%250A%2520%2520var%2520Array%2520%253D%2520%252F**%2540constructor*%252F%2520self.Array%253B%250A%2520%2520var%2520ArrayProto%2520%253D%2520Array.prototype%253B%250A%2520%2520var%2520FunctionBind%2520%253D%2520FunctionProto.bind%253B%250A%2520%2520var%2520bindTo%2520%253D%2520FunctionBind.bind(FunctionBind)%253B%250A%2520%2520%252F%252Fvar%2520CALL_FUNCTION_BIND%2520%253D%2520bindTo(FunctionProto.bind)%253B%250A%2520%2520%252F%252Fvar%2520CALL_ARRAY_PUSH%2520%253D%2520bindTo(ArrayProto.push)%253B%250A%257D)(self)%253B%250A%250A). However, the problem is that the return value of Function.prototype.bind.bind is not marked as pure. As seen [here](https://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540compilation_level%2520ADVANCED_OPTIMIZATIONS%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250A(function(%252F**%2540type%257BObject%257D*%252F%2520self)%257B%250A%2520%2520%2522use%2520strict%2522%253B%250A%2520%2520var%2520Function%2520%253D%2520%252F**%2540constructor*%252F%2520self.Function%253B%250A%2520%2520var%2520FunctionProto%2520%253D%2520Function.prototype%253B%250A%2520%2520var%2520Array%2520%253D%2520%252F**%2540constructor*%252F%2520self.Array%253B%250A%2520%2520var%2520ArrayProto%2520%253D%2520Array.prototype%253B%250A%2520%2520var%2520FunctionBind%2520%253D%2520FunctionProto.bind%253B%250A%2520%2520var%2520bindTo%2520%253D%2520FunctionBind.bind(FunctionBind)%253B%250A%2520%2520bindTo()%253B%2520%252F%252F%2520should%2520be%2520consiered%2520pure%250A%257D)(self)%253B%250A%250A) (which should compile down to zero bytes), Closure Compiler does not consider it to be pure because it does not compile down to zero bytes.

**Comment by anonyco** [comment]
This issue has been solved and fixed. Let us close this issue.

**Comment by blickly** [comment]
Done, thanks!
