### ISSUE TITLE
Incorrect semantics for object rest

### ISSUE THREAD

**Issue by arv** [google/closure-compiler#2946]
Given:

```js
const {xx, ...yy} = o;
```

The generated code deletes xx from o which is not correct. The right hand side must not be mutated. yy should be new object with the keys of o except xx.

https://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540compilation_level%2520SIMPLE_OPTIMIZATIONS%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%2540formatting%2520pretty_print%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250Aconst%2520o%2520%253D%2520%257Bxx%253A%25201%252C%2520yy%253A%25202%252C%2520zz%253A%25203%257D%250Aconst%2520%257Bxx%252C%2520...yy%257D%2520%253D%2520o%253B%250Aconsole.log(o%252C%2520yy)%253B

**Comment by brad4d** [comment]
@MatthewMerrill I believe it makes sense for you to work on this.
Looks to me like the implementation of object rest destructuring was all written in a way that destroys
the right hand side object.

https://github.com/google/closure-compiler/blob/fa80945e5e55032c297393a26d05cfbd5e31215a/src/com/google/javascript/jscomp/EsNextToEs8Converter.java#L328

On the plus side, it's pretty obvious what is wrong...

**Comment by MatthewMerrill** [comment]
Submitted a fix, will be updated next push.
