### ISSUE TITLE
Unused functions with similar names from different classes are not removed

### ISSUE THREAD

**Issue by amitj-gdb** [google/closure-compiler#2952]
Closure compiler does not optimize following code:

```
class A {
  foo() {
    console.log('A.foo');
  }
  bar() {
    console.log('A.bar');
  }
}

class B {
  foo() {
    console.log('B.foo');
  }
  bar() {
    console.log('B.bar');
  }
}

const a = new A();
a.foo();
const b = new B();
b.bar();
```

Output from closure compiler:

```
function a() {
}
a.prototype.b = function() {
  console.log("A.foo");
};
a.prototype.a = function() {
  console.log("A.bar");
};
function b() {
}
b.prototype.b = function() {
  console.log("B.foo");
};
b.prototype.a = function() {
  console.log("B.bar");
};
(new a).b();
(new b).a();
```

expected result:

```
console.log("A.foo");
console.log("B.bar");
```

**Comment by lauraharker** [comment]
The web compiler at Appspot disables type-based optimizations by default, even in ADVANCED optimizations mode. This is the opposite of the command-line compiler.

Adding this line enables type-based optimizations:
```// @use_types_for_optimization true```

https://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%2540compilation_level%2520ADVANCED_OPTIMIZATIONS%250A%252F%252F%2520%2540use_types_for_optimization%2520true%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250Aclass%2520A%2520%257B%250A%2520%2520foo()%2520%257B%250A%2520%2520%2520%2520console.log('A.foo')%253B%250A%2520%2520%257D%250A%2520%2520bar()%2520%257B%250A%2520%2520%2520%2520console.log('A.bar')%253B%250A%2520%2520%257D%250A%257D%250A%250Aclass%2520B%2520%257B%250A%2520%2520foo()%2520%257B%250A%2520%2520%2520%2520console.log('B.foo')%253B%250A%2520%2520%257D%250A%2520%2520bar()%2520%257B%250A%2520%2520%2520%2520console.log('B.bar')%253B%250A%2520%2520%257D%250A%257D%250A%250Aconst%2520a%2520%253D%2520new%2520A()%253B%250Aa.foo()%253B%250Aconst%2520b%2520%253D%2520new%2520B()%253B%250Ab.bar()%253B

This option seems to be missing in the [API reference](https://developers.google.com/closure/compiler/docs/api-ref) - I'll try adding it.
