### ISSUE TITLE
Unused functions with similar names from different classes are not removed

### ISSUE THREAD

**Issue by amitj-gdb** [google/closure-compiler#2960]
#2952

Thank you for a quick reply. However, the optimization fails if I use 'language_out ECMASCRIPT6'

here is a link for quick reference
https://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%2540compilation_level%2520ADVANCED_OPTIMIZATIONS%250A%252F%252F%2520%2540use_types_for_optimization%2520true%250A%252F%252F%2520%2540language_out%2520ECMASCRIPT6%250A%252F%252F%2520%2540formatting%2520pretty_print%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250Aclass%2520A%2520%257B%250A%2520%2520foo()%2520%257B%250A%2520%2520%2520%2520console.log('A.foo')%253B%250A%2520%2520%257D%250A%2520%2520bar()%2520%257B%250A%2520%2520%2520%2520console.log('A.bar')%253B%250A%2520%2520%257D%250A%257D%250A%250Aclass%2520B%2520%257B%250A%2520%2520foo()%2520%257B%250A%2520%2520%2520%2520console.log('B.foo')%253B%250A%2520%2520%257D%250A%2520%2520bar()%2520%257B%250A%2520%2520%2520%2520console.log('B.bar')%253B%250A%2520%2520%257D%250A%257D%250A%250Aconst%2520a%2520%253D%2520new%2520A()%253B%250Aa.foo()%253B%250Aconst%2520b%2520%253D%2520new%2520B()%253B%250Ab.bar()%253B

**Comment by lauraharker** [comment]
Yes, we are working this quarter and next quarter on improving ES6+ support. Before this optimization will work on ES6 output, we need to natively typecheck ES6 code.

For now you will get better code size reduction with ES5 output. That should change in the next few months though.

**Comment by lauraharker** [comment]
Not yet, unfortunately. Our new estimate is the end of this quarter.

Right now we are wrapping work on native typechecking for ES6 code. The only work left is landing support for destructuring, default parameters, and async functions (ES2017 not ES6). The typechecker supports all other new features (classes, for-of, let/const, etc.)

After that's done I'll begin making this optimization ES6 compatible.

**Comment by lauraharker** [comment]
We turned on the property disambiguation optimization for ES6 output in v20181125, so the unused methods in the original repro are removed now. Let us know if you find any bugs in it!

We're not finished with other ES6 optimizations (like method inlining), but I think we can close this specific issue.
```
class A {
  foo() {
    console.log('A.foo');
  }
  bar() {
    console.log('A.bar');
  }
}

class B {
  foo() {
    console.log('B.foo');
  }
  bar() {
    console.log('B.bar');
  }
}

const a = new A();
a.foo();
const b = new B();
b.bar();
```
becomes
```
'use strict';
class a {
  a() {
    console.log("A.foo");
  }
}
class b {
  b() {
    console.log("B.bar");
  }
}
(new a).a();
(new b).b();
```
