### ISSUE TITLE
Transpilation bug: Warnings on multi-variable `let` declarations

### ISSUE THREAD

**Issue by rivo** [google/closure-compiler#2969]
The following code:

```js
{
  let x = 10,
      y = 20;
  console.log(y);
}

{
  let x = 30,
      y = 40;
  console.log(y);
}
```

gives the following warning:

```
JSC_CONSTANT_REASSIGNED_VALUE_ERROR: constant y assigned a value more than once.
Original definition at Input_0:4 at line 10 character 6
      y = 40;
      ^
```

(See for yourself on the [Closure Compiler web app](https://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540compilation_level%2520SIMPLE_OPTIMIZATIONS%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250A%252F%252F%2520ADD%2520YOUR%2520CODE%2520HERE%250A%257B%250A%2520%2520let%2520x%2520%253D%252010%252C%250A%2520%2520%2520%2520%2520%2520y%2520%253D%252020%253B%250A%2520%2520console.log(y)%253B%250A%257D%250A%2520%2520%250A%257B%250A%2520%2520let%2520x%2520%253D%252030%252C%250A%2520%2520%2520%2520%2520%2520y%2520%253D%252040%253B%250A%2520%2520console.log(y)%253B%250A%257D%250A).)

This is the ES5 output which also appears to be incorrect (`y` from the first block should not be reused):

```js
var x=10,y=20;console.log(y);var x$0=30;y=40;console.log(y);
```

The problem appears to be with declaring multiple variables with one `let` statement. If I give each variable its own `let` statement, it transpiles correctly without warnings:

```js
{
  let x = 10;
  let y = 20;
  console.log(y);
}

{
  let x = 30;
  let y = 40;
  console.log(y);
}
```

Output:

```js
var x=10,y=20;console.log(y);var x$0=30,y$1=40;console.log(y$1);
```

(There was some discussion about this already in [this StackOverflow thread](https://stackoverflow.com/questions/50637536/google-closure-compiler-warns-with-jsc-constant-reassigned-value-error-on-let-de).)

**Comment by lauraharker** [comment]
Thanks for the report!

I've submitted a fix internally, and it will be out in the next push to GitHub.
