### ISSUE TITLE
Support __esModule marker from babel&co.

### ISSUE THREAD

**Issue by thheller** [google/closure-compiler#2971]
A lot of code on `npm` is ESM code that was rewritten by `babel` or others to be compatible with CommonJS. Not all packages publish ESM+CommonJS. The code will contain a special `__esModule` marker on the `exports` which Closure currently does not support. `webpack` and others use this to enable a smoother interop between ESM/CommonJS.

[Example](https://babeljs.io/repl/#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=KYDwDg9gTgLgBAG2PAZhCcC8cCMBuAKCA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&sourceType=module&lineWrap=true&presets=env&prettier=false&targets=&version=6.26.0&envVersion=1.6.2):

```
export let foo = 1;
```
is rewritten to
```
"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
var foo = exports.foo = 1;
```

In `webpack` you can now `import { foo } from "...";` just fine since they detect the `__esModule` marker (in non-strict mode).

Currently when using the rewriting facilities from Closure prevent this from working at all since it treats the code as CommonJS and rewrites everything to `.default` meaning that you can only do `import X from "...";` and then `X.foo`. Unfortunately this breaks many `npm` packages  that seem to rely on the `webpack` style interop.

I'll try to create a proper reproducible example with some example `npm` packages but wanted to discuss this first. Maybe this has come up internally or some decision to not support this was already made.

`webpack` has documented there behaviour [here](https://medium.com/webpack/webpack-4-import-and-commonjs-d619d626b655)  and the case that is currently problematic is A2. (The document uses dynamic `import()` but the static `import ...;` acts the same).

Thoughts?

**Comment by ChadKillingsworth** [comment]
I purposefully didn't implement the `__esModule` detection. It adds significant complexity to CommonJS module processing and was never standardized anywhere.

The code is still usable - you just import it with the default property.

```js
import Foo from '...';
const {foo} = Foo;
```

**Comment by thheller** [comment]
Yes, I referred to that possibility above.

The problem is `npm` package A using `npm` package B. I don't have control over either and they are using `import { foo } from "b"` rather than the default export route since that works in `webpack`.

I'll find a different solution. Thanks for the statement.

**Comment by ChadKillingsworth** [comment]
You would need to use Babel and only transpile modules before Closure-Compiler, or just use Webpack with Closure Compiler. Either option works.

**Comment by ChadKillingsworth** [comment]
FYI those modules aren't going to work natively with Node either.

**Comment by ChadKillingsworth** [comment]
I just encountered this myself - and it wasn't pleasant to work around.

I think a path forward here my be to recognize these modules and switch the exports back to ES module export statements.

**Comment by ChadKillingsworth** [comment]
I took a hard run at this, and determined it's not fully possible without severely impacting the size of existing code.  Currently, the compiler has to know what the type of each module being referenced by `require` statements to properly reference them.

For instance, if importing an ES module, the CommonJS pass assumes that the `require` statement references the module object itself.

However when importing another CommonJS module, the pass assumes the `require` statement references the default property.

So truly referencing the import would requiring injecting runtime code to look for an `__esModule` property - it couldn't be done at compile time.

However, I did find several problems with the current rewriting in regards to consuming old babel transpiled ES Modules and have fixed them in #2989

**Comment by Jumblemuddle** [comment]
@ChadKillingsworth Were you able to find a workaround to consume these kinds of modules?

**Comment by ChadKillingsworth** [comment]
Now that #2989 is merged, they are re-written correctly. However, if you are importing them from a CommonJS module - you need to reference the default property:

```js
require('/babel/transpiled/es6.js').default
```

This should only affect code you own. In theory - other modules have also already been transpiled and contain a runtime method to test for the __esModule property.

**Comment by Jumblemuddle** [comment]
Thanks, @ChadKillingsworth! After building the closure compiler from source and then building the clojurescript compiler to use it, everything seems to be working as expected. :)
Thanks for all your help too, @thheller!
