### ISSUE TITLE
Phase Optimizer logging interferes with webpack error reporting

### ISSUE THREAD

**Issue by ChadKillingsworth** [google/closure-compiler#2984]
The PhaseOptimizer uses the java logger to report skipped passes. However, since this doesn't utilize the error reporter and outputs to standard error, this interferes with the ability to parse error messages and use them in a structured manner.

See https://github.com/google/closure-compiler/blob/e48d8acbd170e0e5a4468825450e1cc0bef3fac8/src/com/google/javascript/jscomp/PhaseOptimizer.java#L280

**Comment by brad4d** [comment]
@ChadKillingsworth 
do you have any idea how you'd like to fix this?

I suppose the pass skipping warnings could use the error reporter instead of the normal logger.
Would that resolve this?

**Comment by ChadKillingsworth** [comment]
My initial thought was to use the error reporter and add an "info" level warning. Not off - but not an error either.

**Comment by ChadKillingsworth** [comment]
I have a branch which adds a new CheckLevel called `INFO` and the pass skipping warnings use that instead of the normal logger.

But the more I think about it - the more I realize that perhaps just disabling logging entirely for the open source compiler is best. I can't think of a single reason a standard user would want those warning messages or be able to do anything with them. Only compiler devs care and they can make a custom build.

I'm just going to PR that first.

**Comment by ChadKillingsworth** [comment]
Fixed by  #2998.
