### ISSUE TITLE
Add an option to use closure-compiler-js to closure-compiler.appspot.com

### ISSUE THREAD

**Issue by phistuck** [google/closure-compiler#2986]
This can also remove usage limits.

**Comment by phistuck** [comment]
closure-compiler.appspot.com (as well as the service itself, I would guess) has usage limits. If you try to compile too many times (or too much code?) in a short period, it will throw a quota exception.
If you add an option to use the JavaScript version, on the browser itself (not convert the server implementation to use Node.js), it will not have any usage limits anymore.

**Comment by brad4d** [comment]
If you're having trouble with hitting the usage limits, why not just install closure-compiler locally?
That's really the preferred usage.

**Comment by phistuck** [comment]
I am not hitting them, I guess I thought it would not be a big deal to add support for it, so I suggested it.

**Comment by brad4d** [comment]
Fair enough, but I'm afraid it isn't easy and we don't really have motivation to do it.
I'm sure we'd entertain a PR though, if someone out there wants this badly enough to file one.
Thanks.

**Comment by phistuck** [comment]
@brad4d - a pull request to what? Am I missing something and closure-compiler.appspot.com is open source?

**Comment by ChadKillingsworth** [comment]
@phistuck Closure-Compiler is used internally at Google on almost any project with JavaScript. No PR or change to the compiler is allowed to break one of those projects. So with a change like this - a compiler team member has to make the PR that fixes every single project in Google in addition to the PR.

It _will_ get fixed. But not quite yet.

**Comment by phistuck** [comment]
@ChadKillingsworth - I think you might be commenting on the wrong issue? Perhaps you meant to comment on the [EventTarget one](https://github.com/google/closure-compiler/pull/2988)?
This (current) issue is discussing closure-compiler.appspot.com, not the compiler itself.

**Comment by ChadKillingsworth** [comment]
You are right - too many emails.

For JS one, yes I'd like to have a JS only web site. But it needs a whole new modern UI too. I just haven't had time to tackle it.

**Comment by phistuck** [comment]
@ChadKillingsworth - (not that it necessarily means that, but) are you a Googler again? :O

**Comment by ChadKillingsworth** [comment]
@phistuck I am not - nor have I ever been actually. I just know a LOT about how this works 😄

**Comment by phistuck** [comment]
@ChadKillingsworth - well, you tricked me. You contribute (or contributed? I have not been following the commits in a while) a lot of code without getting paid! Much appreciated!

**Comment by brad4d** [comment]
@phistuck I meant a pull request to change our appengine setup so that it provides an option to download and use the compiled-to-JavaScript-using-GWT version of the compiler.

There is actually already a JS-compiled version of the debugger UI on appengine.
https://closure-compiler-debugger.appspot.com/gwt_debugger.html
Normal debugger is
https://closure-compiler-debugger.appspot.com/

The GWT-compiled one is a lot more responsive, since there's no round trip to the server.

**Comment by brad4d** [comment]
However, it does look like that setup isn't open source.
I guess I dreamed that it was.
Sorry.
