### ISSUE TITLE
The implicit return type (Promise) of async functions is not inferred

### ISSUE THREAD

**Issue by phistuck** [google/closure-compiler#2991]
No warnings about this known-to-fail code in advanced optimization mode -
```
async function p()
{
  return {stop: function() {}};
}

p().stop();
```
https://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540compilation_level%2520ADVANCED_OPTIMIZATIONS%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250Aasync%2520function%2520p()%250A%257B%250A%2520%2520return%2520%257Bstop%253A%2520function()%2520%257B%257D%257D%253B%250A%257D%250A%250A%250Ap().stop()%253B

**Comment by brad4d** [comment]
We already require that JSDoc on a function must specifically state that the return value is at least an `IThenable` if not a `Promise`.
If you add such JSDoc, the desired error appears here.

That said, this should be fixed.
I believe the fix would be to make `TypeInference` infer async functions return `!Promise<?>` instead of just `?`.

**Comment by lauraharker** [comment]
Fixed in v20181125.

Note that the compiler will still just infer the function returns `!Promise<?>`, not `!Promise<{stop: function(): undefined}>`.

**Comment by phistuck** [comment]
@lauraharker - thank you!
Should I file a new issue about it not being inferred as `!Promise<{stop: function(): undefined}>`?

**Comment by lauraharker** [comment]
We have an issue tracking return types for callbacks specifically here:
https://github.com/google/closure-compiler/issues/2894

I'd guess we would fix that before moving to the  more general case of return types for function declarations
