### ISSUE TITLE
Document.window.devicePixelRatio is missing from DomGlobal.window

### ISSUE THREAD

**Issue by treblereel** [google/closure-compiler#2993]
the devicePixelRatio method is missing from DomGlobal.window. It would be very nice to add it.

maybe it could be done like this 
https://github.com/treblereel/closure-compiler/commit/32ee04bb9141085752561cb167a2e9cf1c45e28f

**Comment by niloc132** [comment]
Another option would be to add it to `dom_missing_api.js`, like Location and Selection and others currently do. The `devicePixelRatio` property is defined in webkit_dom.js only, but it works in other browsers (according to https://developer.mozilla.org/en-US/docs/Web/API/Window/devicePixelRatio, is available in IE11 and above).
