### ISSUE TITLE
Parse error: destructured parameter in a property setter

### ISSUE THREAD

**Issue by rslawik** [google/closure-compiler#3002]
The following code does not compile:
```
const a = {
  set foo({x, y}) {
    console.log(`x=${x} y=${y}`);
  }
}
a.foo = {x: 1, y: 2};
```
[Closure Compiler Service](https://closure-compiler.appspot.com/home#code%3Dconst%2520a%2520%253D%2520%257B%250A%2520%2520set%2520foo(%257Bx%252C%2520y%257D)%2520%257B%250A%2520%2520%2520%2520console.log(%2560x%253D%2524%257Bx%257D%2520y%253D%2524%257By%257D%2560)%253B%250A%2520%2520%257D%250A%257D%250Aa.foo%2520%253D%2520%257Bx%253A%25201%252C%2520y%253A%25202%257D%253B)

It is valid JavaScript and runs in Chrome.

**Comment by lauraharker** [comment]
Fixed in https://github.com/google/closure-compiler/commit/220454e87c8f1b6f3bb1bd531e0c9f199a350bc2.
