### ISSUE TITLE
animation & animationDuration in DOMElement.style are getting obfuscated

### ISSUE THREAD

**Issue by esseswann** [google/closure-compiler#3006]
Couldn't find if anybody reported or is it even considered a problem, but for some reason compiler renames `animation` and `animationDuration` properties when setting style to DOMElement if using `ADVANCED_OPTIMIZATIONS`.
```javascript
const test = document.createElement('div')
test.style.animation = 'test'
test.style.animationDuration = '3s'
test.style.padding = '16px'
```
I would understand if it would rename any `style` property, but as [you can see](https://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540compilation_level%2520ADVANCED_OPTIMIZATIONS%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250A%252F%252F%2520ADD%2520YOUR%2520CODE%2520HERE%250Aconst%2520test%2520%253D%2520document.createElement('div')%250Atest.style.animation%2520%253D%2520'test'%250Atest.style.animationDuration%2520%253D%2520'3s'%250Atest.style.padding%2520%253D%2520'16px') `padding` is not obfuscated

**Comment by lauraharker** [comment]
It looks like our externs are missing `animation` and `animationDuration` (but have `padding` here):
https://github.com/google/closure-compiler/blob/6250a23fc5ac60b0a34b7a44e53dc6cfd5bb075d/externs/browser/w3c_css.js#L1533

Probably we just need to add `animation` and `animationDuration` to the other CSS 3 externs here:
https://github.com/google/closure-compiler/blob/6250a23fc5ac60b0a34b7a44e53dc6cfd5bb075d/externs/browser/w3c_css.js#L1805

Are you interested in sending in a PR?

**Comment by esseswann** [comment]
Sure, will do. I will also check for other properties

**Comment by esseswann** [comment]
I do not quite understand why [w3c_css.js](https://github.com/google/closure-compiler/blob/6250a23fc5ac60b0a34b7a44e53dc6cfd5bb075d/externs/browser/w3c_css.js#L1805) doesn't contain `animationName` but still [isn't obfuscated](https://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540compilation_level%2520ADVANCED_OPTIMIZATIONS%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250A%252F%252F%2520ADD%2520YOUR%2520CODE%2520HERE%250Atest%2520%253D%2520document.createElement('div')%250Atest.style.animationName%2520%253D%2520'test'%250Atest.style.animationDuration%2520%253D%2520'3s'%250Atest.style.animationTimingFunction%2520%253D%2520'ease-in'%250Atest.style.animationIterationCount%2520%253D%25201%250Atest.style.animationDirection%2520%253D%2520'alternate'%250Atest.style.animationPlayState%2520%253D%2520'paused'%250Atest.style.animationDelay%2520%253D%2520'3s'%250Atest.style.animationFillMode%2520%253D%2520'forwards'%250Atest.style.animation%2520%253D%2520'test%25203s')
