### ISSUE TITLE
SyntaxError after SIMPLE optimizations (ES_2015 object destructuring)

### ISSUE THREAD

**Issue by laszlopandy** [google/closure-compiler#3019]
### test.js
```js
(function (obj) {
    var A = obj;
    class B { }
    console.log(B);
    const {
        default: C
    } = obj;
    return { A, C };

})({ default: 1 });
```

### Compile with SIMPLE optimizations
```
java -jar closure-compiler-v20180610.jar --js_output_file test.out.js --js test.js --compilation_level SIMPLE --language_in ECMASCRIPT_2015 --language_out ECMASCRIPT_2015
```

### Run with node:
```
node test.out.js
```

### Output
Expected output: nothing
Actual output: `SyntaxError: Identifier 'a' has already been declared`

The problem seems to be that Closure uses `a` as the first local variable name without considering that a class has already been declared with that name.

**Comment by lauraharker** [comment]
The output code is
``` javascript
'use strict';(function(b){class a{}console.log(a);var {default:a}=b;return{A:b,C:a}})({default:1});
```

Looks like the `CoalesceVariableNames` pass needs to either a) remove the `var` from `var {default:a}=b;` or b) not rename it to `a`. 

[Debugger repro](https://closure-compiler-debugger.appspot.com/#input0%3D(function%2520(obj)%2520%257B%250A%2520%2520%2520%2520var%2520A%2520%253D%2520obj%253B%250A%2520%2520%2520%2520class%2520B%2520%257B%2520%257D%250A%2520%2520%2520%2520console.log(B)%253B%250A%2520%2520%2520%2520const%2520%257B%250A%2520%2520%2520%2520%2520%2520%2520%2520default%253A%2520C%250A%2520%2520%2520%2520%257D%2520%253D%2520obj%253B%250A%2520%2520%2520%2520return%2520%257B%2520A%252C%2520C%2520%257D%253B%250A%250A%257D)(%257B%2520default%253A%25201%2520%257D)%253B%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3Dtrue%26COALESCE_VARIABLE_NAMES%3Dtrue%26INLINE_VARIABLES%3Dtrue%26PRESERVE_TYPE_ANNOTATIONS%3Dtrue%26PRETTY_PRINT%3Dtrue)
