### ISSUE TITLE
Support for ES2018 Regular Expressions

### ISSUE THREAD

**Issue by IvanRF** [google/closure-compiler#3028]
I'm getting a Warning for a Regular Expression but it actually works.

Javascript code:
```
function getIframesSources(html) {
	return html.match(/(?<=<iframe.* src\s*=\s*").*?(?=")/gmi);
}
```

Warning thrown by Closure Compiler v20180716:
`WARNING - Malformed Regular Expression: Malformed parenthetical: (?<=<iframe.* src\s*=\s*").*?(?=")`

Working RegEx test: https://regex101.com/r/4YyzKP/1

**Comment by tjgq** [comment]
The regular expression in question contains a positive lookbehind assertion `(?<=...)`, which is expected to be part of the next version of the standard (ES2018).

**Comment by brad4d** [comment]
@MatthewMerrill will be working on this in the next few weeks.

**Comment by brad4d** [comment]
Bear in mind, though, that closure-compiler does not attempt to make new regular expression features work on old browsers. For now, the best you can hope for is that the compiler will stop considering the regular expression to be an error and start issuing you a warning that it may not work at runtime.

We'll be able to make that warning go away when we can support `ES_2018` level output, but I'm guessing that's a year away.

**Comment by IvanRF** [comment]
@tjgq @brad4d thanks, I didn't know this kind of RegEx was so new. I end up changing it in order to support old browsers. I will change the issue title.

**Comment by EatingW** [comment]
Sorry, I don't quite remember the context of why I assigned myself (maybe by mistake?). In any case I'm not working on this so un-assigning.

**Comment by brad4d** [comment]
We've done all we plan to do for supporting the `RegExp` features added in `ES_2018`.
closure-compiler will recognize them and not choke on them.
However, if your output language is earlier than `ES_2018`, then the compiler will issue a suppressible error to tell you that it cannot transpile the new `RegExp` features to make them work where they are not natively supported.

**Comment by L3P3** [comment]
Why is closure-compiler not including newer RegExp formats? I think there should be at least some kind of polyfill or fallback. On still somewhat common browsers, now vscode fails to open due to a new RegExp included in a .ts file. This is very ugly.
