### ISSUE TITLE
MessageFormat "Missing or invalid plural value element" from extra newline

### ISSUE THREAD

**Issue by dgp1130** [google/closure-compiler#3030]
Consider the following code:

    const MSG_VIEWS = goog.getMsg(`{VIEWS, plural,
      =1 {1 View}
      other {# Views}
    }`);
    new MessageFormat(MSG_VIEWS).format({'VIEWS': 5});

This throws the error: `Assertion failed: Missing or invalid plural value element.`

By contrast, the following code works error free:

    const MSG_VIEWS = goog.getMsg(`{VIEWS, plural,
      =1 {1 View}
      other {# Views}}`);
    new MessageFormat(MSG_VIEWS).format({'VIEWS': 5});

Note the only difference is that the final `}` was pulled from its own line. I don't feel that this one piece of whitespace should break the formatter and it should handle that appropriately.

**Comment by brad4d** [comment]
This is really a closure-library issue, so I've filed it there as
https://github.com/google/closure-library/issues/914
