### ISSUE TITLE
DevirtualizePrototypeMethods has colliding JSCompiler_StaticMethods_*

### ISSUE THREAD

**Issue by supersteves** [google/closure-compiler#3040]
In advanced mode our method call is being replaced with the wrong one. We are calling a method in the externs, but at runtime it's calling another method of ours with the same name.

Externs
``` javascript
/** @constructor */
var SomeExternType = function() {
  /** @type {function()} */
  this.restart;
}
```

Code
``` javascript
class X {
    restart(n) {
      console.log(n);
    }
}
/** @param {SomeExternType} e */
function f(e) {
    new X().restart(5);
    e.restart();
}
```

Result
```
var X = function() {
};
var JSCompiler_StaticMethods_restart = function(JSCompiler_StaticMethods_restart$self, n) {
  console.log(n);
};
function f(e) {
  JSCompiler_StaticMethods_restart(new X, 5);
  JSCompiler_StaticMethods_restart(e);
}
;
```

As you can see there are two types here, one in externs, one local, both have member function `restart`, both correctly identified (I've verified this) for type checking purposes as distinct, but being rewritten to the same (now global) method `JSCompiler_StaticMethods_restart`.

[Debugger](https://closure-compiler-debugger.appspot.com/#input0%3Dclass%2520X%2520%257B%250A%2520%2520%2520%2520restart(n)%2520%257B%250A%2520%2520%2520%2520%2520%2520console.log(n)%253B%250A%2520%2520%2520%2520%257D%250A%257D%250A%250A%252F**%2520%2540param%2520%257BSomeExternType%257D%2520e%2520*%252F%250Afunction%2520f(e)%2520%257B%250A%2520%2520%2520%2520new%2520X().restart(5)%253B%250A%2520%2520%2520%2520e.restart()%253B%250A%257D%250A%250A%26input1%26conformanceConfig%26externs%3D%252F**%2520%2540constructor%2520*%252F%250Avar%2520SomeExternType%2520%253D%2520function()%2520%257B%250A%2520%2520%252F**%2520%2540type%2520%257Bfunction()%257D%2520*%252F%250A%2520%2520this.restart%253B%250A%257D%250A%26refasterjs-template%26includeDefaultExterns%3Dtrue%26CHECK_TYPES%3Dtrue%26TRANSPILE%3Dtrue%26DEVIRTUALIZE_PROTOTYPE_METHODS%3Dtrue%26CLOSURE_PASS%3Dtrue%26PRETTY_PRINT%3Dtrue).

**Comment by supersteves** [comment]
Strangely, changing the externs to this solves it:
```
/** @constructor */
var SomeExternType = function() {};
SomeExternType.prototype.restart = function() {};
```

This is peculiar since I've verified that SomeExternType is correctly interpreted for both patterns of externs (by testing `let /** null */ test = e`).

**Comment by supersteves** [comment]
Note we're using the following (record) pattern everywhere, in externs and code. Which also has the above problem. Is this style of declaring members of types not fully supported in externs?
```
/** @record */
var SomeExternType = function() {
  /** @type {function()} */
  this.restart;
}
```

**Comment by blickly** [comment]
Hmm, your analysis sounds right to me that DevirtualizePrototypeMethods seems to not backoff correctly for this properties in externs.

@brad4d, could you take a look and/or triage?

**Comment by nreid260** [comment]
The issue is that the `DevirtualizePrototypeMethods` depends on `DisambiguateProperties` to work correctly.

`DevirtualizePrototypeMethods` is fairly naive; it basically treats all methods with the same name and a single definition to the interchangeable. The secret-sauce is that when `DisambiguateProperties` runs first, all the potentially different methods with the same name are renamed. Doing so eliminates a lot of heavy-lifting from `DevirtualizePrototypeMethods`.

We *should* make this relationship more obvious (also for other inter-pass dependencies).

**Comment by concavelenz** [comment]
@nreid260 This assessment is incorrect. Devirtualize methods should back off if it see two different definitions.  However, clearly it doesn't recognize the stub definition in the constructor as a definition.  Historically, the contents of functions in externs were ignored.  It maybe the devirtualize methods still holds this "belief".

**Comment by brad4d** [comment]
Created Google internal issue b/119639300
