### ISSUE TITLE
Wrong 'goog.base in ES6 class is not allowed'

### ISSUE THREAD

**Issue by nomean42** [google/closure-compiler#3042]
```
 /**
 * @inheritDoc
 */
_method() {
	const foo = {
		base: function() {/* ... */}
	}

	foo.base();
}
```

got
 `ERROR - incorrect use of goog.base: goog.base in ES6 class is not allowed. Use super instead.`

ver 20160911.0.0

**Comment by ChadKillingsworth** [comment]
You are on a very old compiler. This has been fixed.
