### ISSUE TITLE
Function Inlining loses captures of "super"

### ISSUE THREAD

**Issue by ChadKillingsworth** [google/closure-compiler#3046]
Rewriting Async methods produces code such as:

```js
class Foo extends Bar {
  baz() {
    const jscomp$get$super$baz = () => super.baz;
    const jscomp$this = this;
    return function() {
      jscomp$get$super$baz().call(jscomp$this);
    }
  }
}
```

Currently, function inling will inline the `super.baz` return value from the arrow function to produce an invalid reference to `super`. This only seems to show up with ES2015 out as a language.

**Comment by MatthewMerrill** [comment]
Submitted fix internally
