### ISSUE TITLE
for-await syntax doesn't inject makeasynciterator.js runtime

### ISSUE THREAD

**Issue by teppeis** [google/closure-compiler#3049]
It throws `TypeError: $jscomp.makeAsyncIterator is not a function`

- [Input](https://github.com/teppeis/closure-compiler-es-compat-table/blob/e46b574cedeb36fb8bd8a452198d3feb57ce4a78/es2016plus/v20180805/2018_features/Asynchronous_Iterators/for-await-of_loops/in.js)
- [Output](https://github.com/teppeis/closure-compiler-es-compat-table/blob/e46b574cedeb36fb8bd8a452198d3feb57ce4a78/es2016plus/v20180805/2018_features/Asynchronous_Iterators/for-await-of_loops/out.js)

In this commit,`makeiterator` is injected actually for `Feature.FOR_AWAIT_OF`
https://github.com/google/closure-compiler/commit/d5aa5b484abdbc7bce636ec65c12f60408cc50eb#diff-736e46eac02f9c85fc7276d91a175e1eR89

```java
    if (used.contains(Feature.FOR_AWAIT_OF)) {
      compiler.ensureLibraryInjected("es6/util/makeiterator", /* force= */ false);
    }
```

but I think `makeasynciterator` should be injected.

**Comment by MatthewMerrill** [comment]
Submitting a fix internally, will be available next release. A hacky workaround for the time being would be to add an unused async generator anywhere to force injection of makeasynciterator.

**Comment by MatthewMerrill** [comment]
Included other stuff that got rolled back, submitting again with just the minimal fixes.

**Comment by MatthewMerrill** [comment]
Submitted  :+1:
