### ISSUE TITLE
Class overwritten after WHITESPACE optimizations (with --process_common_js_modules)

### ISSUE THREAD

**Issue by laszlopandy** [google/closure-compiler#3051]
### test.js
```js
"use strict";
class Base {}
exports.Base = Base;

class Impl extends exports.Base {
    getString() {
        return "test";
    }
}
exports.Impl = Impl;

const w = new exports.Impl("a")
console.log(w.getString());
```

### Compile with SIMPLE optimizations
```
java -jar closure-compiler-v20180805.jar --js_output_file test.out.js --entry_point test.js --js test.js --compilation_level WHITESPACE --language_in ECMASCRIPT_2015 --language_out ECMASCRIPT_2015 --dependency_mode STRICT --process_common_js_modules
```

### Run with node:
```
node test.out.js
```

### Output
Expected output: `test`
Actual output: `TypeError: w$$module$test.getString is not a function`

If you view the output in `test.out.js` you can immediately see a bad assignment which seems to be caused by using `--process_common_js_modules`:
```js
'use strict';
var module$test = {
    default: {}
};
module$test.default.Base = class {};
module$test.default.Impl = class extends module$test.default.Base {
    getString() {
        return "test"
    }
};
module$test.default.Impl = module$test.default.Base;
const w$$module$test = new module$test.default.Impl("a");
console.log(w$$module$test.getString());
```

The line: `exports.Impl = Impl;` (from test.js)
Gets compiled into:  `module$test.default.Impl = module$test.default.Base;`, overwriting the Impl class with the Base.

I have created a one file example to demonstrate the problem, but in my real world code I have many common js files being bundled together and `--process_common_js_modules` is needed.

**Comment by brad4d** [comment]
@ChadKillingsworth this does look weird, perhaps you could take a look.

@laszlopandy if it's convenient, perhaps you could run your example with `--print_source_after_each_pass` and post the output here?

That will make it clear whether the incorrect code is generated directly by the module rewriting or is created later by incorrect optimization logic. (I'm suspicious of variable inlining in particular.)

**Comment by laszlopandy** [comment]
Not sure how helpful it is, but here is the output from `--print_source_after_each_pass`
```
java -jar closure-compiler-v20180805.jar --js_output_file test.out.js --entry_point test.js --js test.js --compilation_level WHITESPACE --language_in ECMASCRIPT_2015 --language_out ECMASCRIPT_2015 --dependency_mode STRICT --process_common_js_modules --print_source_after_each_pass

// parseInputs yields:
// ************************************
'use strict';class Base{}exports.Base=Base;class Impl extends exports.Base{getString(){return"test"}}exports.Impl=Impl;const w=new exports.Impl("a");console.log(w.getString());
// ************************************
```

**Comment by brad4d** [comment]
@laszlopandy that looks strange to me. It's like no passes ran at all after parseInputs.
That can't be right, since the code is actually modified.
Hmmm...

**Comment by ChadKillingsworth** [comment]
I'll see what I can figure out. Having a test case should make it pretty straight forward.

**Comment by concavelenz** [comment]
@ChadKillingsworth Were you able reproduce this?

**Comment by ChadKillingsworth** [comment]
Yes - the test case worked perfectly. The hard part was figuring out "why" it failed.

**Comment by concavelenz** [comment]
@brad4d For the record the CommonJs modules handling is *extremely* early and doesn't really fit into the compiler's general architecture.
