### ISSUE TITLE
Exported name of static method is incorrect when @export is used

### ISSUE THREAD

**Issue by Yannic** [google/closure-compiler#3055]
[Repro](https://closure-compiler-debugger.appspot.com/#input0%3Dgoog.module('foo.bar')%253B%250A%250Aclass%2520Foo%2520%257B%250A%2520%2520%2520%252F**%2520%2540export%2520*%252F%250A%2520%2520foo()%2520%257B%257D%250A%250A%2520%2520%252F**%2520%2540export%2520*%252F%250A%2520%2520static%2520bar()%2520%257B%257D%250A%257D%250Agoog.exportSymbol('Foo'%252C%2520Foo)%253B%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3Dtrue%26TRANSPILE%3Dtrue%26CLOSURE_PASS%3Dtrue%26GENERATE_EXPORTS%3Dtrue%26PRESERVE_TYPE_ANNOTATIONS%3Dtrue%26PRETTY_PRINT%3Dtrue)
```javascript
goog.module('foo.bar');

class Foo {
   /** @export */
  foo() {}

  /** @export */
  static bar() {}
}
goog.exportSymbol('Foo', Foo);
```

`Foo.bar` will be exported as `module$contents$foo$bar_Foo.bar` when transpile pass is enabled.

**Comment by ChadKillingsworth** [comment]
See #2072
