### ISSUE TITLE
Linux command line compiler does not work with addEventListener

### ISSUE THREAD

**Issue by David-Else** [google/closure-compiler#3056]
I am using the command line Linux version extracted from the latest NPM version:

```
Version: v20180805
Built on: 2018-08-09 20:09
```
I am not a very experienced user, so sorry if I can't be of more help than just pasting in these results.
```
function keyHandler(event) {
  switch (event.code) {
    case 'KeyF':
      console.log('f');
      break;
    case 'ArrowLeft':
      event.preventDefault();
      console.log('l');
      break;
    case 'ArrowRight':
      event.preventDefault();
      console.log('r');
      break;
    case 'KeyP':
      break;
    // no default
  }

  // no default
}

addEventListener('keydown', keyHandler);
addEventListener('keyup', keyHandler);
```

Works fine here (select advanced):
`https://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540compilation_level%2520ADVANCED_OPTIMIZATIONS%250A%252F%252F%2520%2540language_out%2520ES5%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250A%252F%252F%2520ADD%2520YOUR%2520CODE%2520HERE%250Afunction%2520keyHandler(event)%2520%257B%250A%2520%2520switch%2520(event.code)%2520%257B%250A%2520%2520%2520%2520case%2520'KeyF'%253A%250A%2520%2520%2520%2520%2520%2520console.log('f')%253B%250A%2520%2520%2520%2520%2520%2520break%253B%250A%2520%2520%2520%2520case%2520'ArrowLeft'%253A%250A%2520%2520%2520%2520%2520%2520event.preventDefault()%253B%250A%2520%2520%2520%2520%2520%2520console.log('l')%253B%250A%2520%2520%2520%2520%2520%2520break%253B%250A%2520%2520%2520%2520case%2520'ArrowRight'%253A%250A%2520%2520%2520%2520%2520%2520event.preventDefault()%253B%250A%2520%2520%2520%2520%2520%2520console.log('r')%253B%250A%2520%2520%2520%2520%2520%2520break%253B%250A%2520%2520%2520%2520case%2520'KeyP'%253A%250A%2520%2520%2520%2520%2520%2520break%253B%250A%2520%2520%2520%2520%252F%252F%2520no%2520default%250A%2520%2520%257D%250A%250A%2520%2520%252F%252F%2520no%2520default%250A%257D%250A%250AaddEventListener('keydown'%252C%2520keyHandler)%253B%250AaddEventListener('keyup'%252C%2520keyHandler)%253B%250A%250A%250A%250A`

But on the command line using the equivalent options it gives an error:
`
./compiler --compilation_level ADVANCED --warning_level VERBOSE --language_out ES5 bundle.js --js_output_file compressed.js`

```
bundle.js:26: ERROR - variable addEventListener is undeclared
addEventListener('keydown', keyHandler);
^^^^^^^^^^^^^^^^

1 error(s), 0 warning(s)
```
Other code is compiling fine with these settings.

**Comment by ChadKillingsworth** [comment]
The web service assumes any undefined reference is external and does not rename it. The command line does not use that behavior by default.

addEventListener is not defined as a global function in the standard externs. So the undefined error is correct.

**Comment by David-Else** [comment]
Thanks for your quick reply.

Sorry to take up your valuable time, but how can I mark addEventListener as an extern using JSDoc so it compiles in advanced mode?

I have looked at https://github.com/google/closure-compiler/wiki/Annotating-JavaScript-for-the-Closure-Compiler but can't find the answer. @externs does not seem suitable. Maybe I need another solution? My final file to compress has been created using Rollup and is wrapped in an IIFE.

**Comment by brad4d** [comment]
@David-Else 
Option 1: Call addEventListener as `window.addEventListener()`.
This makes it clear to the reader that you're adding the listener on the window, so it's just more readable and a better choice all around.

Option 2: Add your own externs file to the compilation.

Create a file containing something like this to pass to the compiler with the rest of your sources.
I copied the annotations from `EventTarget.prototype.addEventListener` `w3c_event.js`

```javascript
/**
 * @fileoverview Custom externs for my project.
 * @externs
 */
/**
 * @param {string} type
 * @param {EventListener|function(!Event):(boolean|undefined)} listener
 * @param {(boolean|!AddEventListenerOptions)=} opt_options
 * @return {undefined}
 */
var addEventListener = function(type, listener, opt_options) {};
```

**Comment by David-Else** [comment]
@brad4d Thanks so much! That was just the information I needed.
