### ISSUE TITLE
CSS property user-select is not fully supported

### ISSUE THREAD

**Issue by marci4** [google/closure-compiler#3069]
The CSS property `user-select` is currently not fully supported:
Working:
- WebKitUserSelect
- MozUserSelect

Not working:
- UserSelect
- MsUserSelect

I know, that this property is still a working draft but it is already supported by most browsers (with vendor prefix)
See https://developer.mozilla.org/en-US/docs/Web/CSS/user-select

**Comment by lauraharker** [comment]
To double-check, by not working you mean the compiler is renaming these properties?

We'd accept a PR to add the missing properties to the `CssProperties` externs. I believe the correct files are
https://github.com/google/closure-compiler/blob/master/externs/browser/ie_css.js
and
https://github.com/google/closure-compiler/blob/master/externs/browser/w3c_css.js.

**Comment by marci4** [comment]
Yeah, sorry if I was not clear with that.
