### ISSUE TITLE
webgl 2.0 texsubimage2d extern conflicts with webgl 1.0 extern

### ISSUE THREAD

**Issue by rosw12** [google/closure-compiler#3075]
I had a similar issue previously when attempting to define these externs manually. 

found   : HTMLCanvasElement
required: (ArrayBufferView|null|undefined)
        gl.texImage2D(gl.TEXTURE_2D, 0, this.gl.RGBA, dims[0], dims[1], 0, this.gl.RGBA, gl.UNSIGNED_BYTE, canvas);

**Comment by tjgq** [comment]
Can you provide a full example?

`externs/browser/webgl2.js` defines a `WebGL2RenderingContext` interface (note the `2`), which extends the `WebGLRenderingContext` defined in `externs/browser/webgl.js`. When retrieving the WebGL2 context from the canvas, make sure you store it in a variable of the former type.

**Comment by rosw12** [comment]
I think you are absolutely correct, I missed the 2.
