### ISSUE TITLE
Distribute each compiler platform independently on npm

### ISSUE THREAD

**Issue by ChadKillingsworth** [google/closure-compiler#3078]
Some developers have been asking to have npm packages with just the compiler executable itself - platform specific (java, js, graal linux, graal osx). I've resisted suggesting this due to the work of maintaining separate repositories.

However, I recently have been exploring the idea of housing all of these packages in a single repository. Here's a start on a design document: https://docs.google.com/document/d/1TA1K-AAlUkt9ftYFZmLs1KK3ANrO6og8FxEVAQi2JNw/edit?usp=sharing

**Comment by concavelenz** [comment]
Is there a reason not to do thing?

**Comment by brad4d** [comment]
Thanks for writing up the proposal, Chad.
I can't see any reason not to proceed with your plan.

**Comment by ChadKillingsworth** [comment]
I have a branch with a good start on this: https://github.com/google/closure-compiler-npm/tree/mono-repo

I've also setup Travis to build the compiler from master and run the full test suite daily.
