### ISSUE TITLE
WeakMap polyfill breaks `deep-freeze` on IE11

### ISSUE THREAD

**Issue by longlho** [google/closure-compiler#3080]
Right now the WeakMap polyfill inject hidden `jscom_hidden_xxxx` prop into object (https://github.com/google/closure-compiler/blob/50713dceb16b369f8f317e5b49e8a9dec2b47496/src/com/google/javascript/jscomp/js/es6/weakmap.js#L88) which causes `Out of stack limit` on IE11 when used with `deep-freeze` (https://github.com/substack/deep-freeze/blob/master/index.js#L9) since it recursively calls `Object.freeze` on non-primitive properties.

This manifests into Google SDKs (e.g recaptcha or Google Maps) breaking hosts' codes. We found out the issue during a SEV within Dropbox.

Can we replace the polyfill with a less intrusive version please? I'm happy to submit a PR if possible.

**Comment by concavelenz** [comment]
I think I have a solution for this, let me put together a patch.

**Comment by concavelenz** [comment]
My proposal is not to allow adding the "weak map membership" property to a Object used as a "weak map membership" object.
