### ISSUE TITLE
java.lang.NullPointerException: No warning class for name: '*'

### ISSUE THREAD

**Issue by Getfree** [google/closure-compiler#3081]
In Windows I run the following command:
`java -jar "closure-compiler-v20180805.jar" --jscomp_off '*'`
And I get the error:
```
java.lang.NullPointerException: No warning class for name: '*'
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:980)
        at com.google.javascript.jscomp.DiagnosticGroups.setWarningLevel(DiagnosticGroups.java:679)
        at com.google.javascript.jscomp.AbstractCommandLineRunner.setWarningGuardOptions(AbstractCommandLineRunner.java:355)
        at com.google.javascript.jscomp.AbstractCommandLineRunner.setRunOptions(AbstractCommandLineRunner.java:370)
        at com.google.javascript.jscomp.AbstractCommandLineRunner.doRun(AbstractCommandLineRunner.java:1102)
        at com.google.javascript.jscomp.AbstractCommandLineRunner.run(AbstractCommandLineRunner.java:538)
        at com.google.javascript.jscomp.CommandLineRunner.main(CommandLineRunner.java:2155)
```

If I pass the asterisk without quotes, it is expanded to all the files in the directory.

I don't know who's performing the expansion, either the command interpreter or the `java` program.
Either way, I have no way of passing a `*` to the `--jscomp_off` option.

This is on Windows 7, in a regular cmd.exe window.

Closure Compiler version:
```
Version: v20180805
Built on: 2018-08-09 19:53
```
Java version:
```
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) Client VM (build 25.121-b13, mixed mode)
```

**Comment by concavelenz** [comment]
Wouldn't that be `--warning_level QUIET` that you want?

**Comment by Getfree** [comment]
I also tried that but, no, I did want `--jscomp_off`.

But anyways, it doesn't really matter what I want. I'm reporting an issue.

**Comment by concavelenz** [comment]
I didn't mean to discount your report, the compiler shouldn't crash.  But I curious what you are hoping jscomp_off will do for you?

**Comment by Getfree** [comment]
I'd like to see if `--jscomp_off *` will make an error go away. But since I have no way of passing a `*`, I don't know if it's going to work.

The error in question is this:

**file1.js**
`let GLOBAL_1 = GLOBAL_2 ;`

**file2.js**
`let GLOBAL_2 = 1 ;`

**Then:**
`java -jar closure-compiler-v20180910.jar --language_out NO_TRANSPILE -O SIMPLE file1.js --chunk file1Out:1 file2.js --chunk file2Out:1`

**Result:**
```
file1.js:1: ERROR - Illegal variable reference before declaration: GLOBAL_2
var GLOBAL_1 = GLOBAL_2 ;
               ^^^^^^^^

1 error(s), 0 warning(s)
```

I use the `--chunk` option so that each file is compiled to its own output file.

Right now I see two solutions to the problem, none of which is satisfactory in my situation.

**Solution 1:**
Reverse the order of the files in the command line:
`java -jar closure-compiler-v20180910.jar --language_out NO_TRANSPILE -O SIMPLE file2.js --chunk file2Out:1 file1.js --chunk file1Out:1`

This is not doable in my case, because my build system generates that command line automatically from the files in the directory. So the files end up in whatever other they are in the file system.

**Solution 2:**
Run instead two command lines:
`java -jar closure-compiler-v20180910.jar --language_out NO_TRANSPILE -O SIMPLE file1.js --js_output_file file1Out.js`
`java -jar closure-compiler-v20180910.jar --language_out NO_TRANSPILE -O SIMPLE file2.js --js_output_file file2Out.js`

This is also not acceptable because it takes too long to complete. We currently have about 16 thousand lines of Javascript spread across 44 files. Running `java -jar closure-compiler-v20180910.jar` 44 times would take more than 3 minutes, while a single command line does it in less than 20 seconds.

----
That's why I'd like to see if I can get rid of that error, because it's meaningless in this case.

**Comment by concavelenz** [comment]
A couple of things:

* We definitely shouldn't be reporting that with reporting warning_level="QUIET" would you mind filing a separate issue for that?

* In the meanwhile perhaps https://github.com/facebook/nailgun will allow you to work around the issue? Eventually, Graal will support windows and you will be able to get instant startup for these kinds of tasks.
