### ISSUE TITLE
"-W QUIET" doesn't turn off "ERROR - Illegal variable reference before declaration"

### ISSUE THREAD

**Issue by Getfree** [google/closure-compiler#3082]
I'm comming from #3081 where @concavelenz explained that `-W QUIET` should turn off the error that occurs in the following case:

**file1.js**
`let GLOBAL_1 = GLOBAL_2 ;`

**file2.js**
`let GLOBAL_2 = 1 ;`

**Command:**
`java -jar closure-compiler-v20180910.jar --language_out NO_TRANSPILE -O SIMPLE -W QUIET file1.js --chunk file1Out:1 file2.js --chunk file2Out:1`

**Result:**
```
file1.js:1: ERROR - Illegal variable reference before declaration: GLOBAL_2
let GLOBAL_1 = GLOBAL_2 ;
               ^^^^^^^^

1 error(s), 0 warning(s)
```

I use the `--chunk` option so that each file is compiled to its own output file.

Compiler Version: v20180910

**Comment by brad4d** [comment]
I believe this is working as intended.
`-W QUIET` is only supposed to silence warnings.
Referring to a variable before it is declared is an error.

**Comment by concavelenz** [comment]
Traditionally, "check symbols" has been optional.   In simple mode, it is unclear that cross script references should be considered.

**Comment by Getfree** [comment]
May I suggest that this error becomes part of an error group, so that we can turn it off using `--jscomp_warning errorGroup -W QUIET`.
