### ISSUE TITLE
Unwanted el.dataset.obfuscated_name

### ISSUE THREAD

**Issue by radogado** [google/closure-compiler#3099]
[advanced optimizations] Hi, I'm using HTML data attributes via dataset, but sometimes they get obfuscated.

> el.dataset.active → el.dataset.active
> el.dataset.sliding → el.dataset.a, breaking my app
> 

As those names are a part of the HTML, I think they shouldn't be obfuscated. Is there an option to disable it? Thanks.

**Comment by ChadKillingsworth** [comment]
You will either need to use externs or quote the properties to block renaming.
