### ISSUE TITLE
ES6 Out: Captures of Super Fail in MS Edge - breaks async/await transpilation

### ISSUE THREAD

**Issue by ChadKillingsworth** [google/closure-compiler#3101]
The following code will infinitely loop and alert `"Child foo"` in MS Edge. All other browsers seem to handle this correctly.

```js
class Base {
  foo() {
    alert('base foo');
  }
}

class Child extends Base {
  foo() {
    const parent = () => super.foo;
    alert('Child foo');
    parent().call(this);
  }
}

(new Child()).foo();
```

This breaks async / await transpilation with ES2015 out.

**Comment by brad4d** [comment]
added a comment on PR #3103 
a more robust solution is needed

Note that compiling to ES5 is a workaround for this problem.

**Comment by ChadKillingsworth** [comment]
Chakra bug: https://github.com/Microsoft/ChakraCore/issues/5784
