### ISSUE TITLE
Parse error. Invalid RegExp flag 's' 

### ISSUE THREAD

**Issue by gg4u** [google/closure-compiler#3130]
I am running command:
`java -jar compiler.jar --js_output_file=out.js myFile.js`

and meet following error:

```
ERROR - Parse error. Invalid RegExp flag 's'
              e = e.replace(/;.*/s, "");
```

I am manipulating strings like this:

```
try {
          // I get first 3 most important nodes and trim titles after chars: ; - ( 
          title = getMostRelevantNodes( graph , 3).map(function(item){ 
              

              // decorate Query Nodes on Graph > using same function
              highlightQueryNode(item.key);

              var e = readCache( item.key).name;
              
              // names like 2,6-Diaminopurine: reutrn
              if ( /\d/.test(e) ) return e; 

              e = e.replace(/;.*/s, "");
              e = e.replace(/-.*/s, "");
              e = ( e.indexOf('(') > -1) ? e.substring(0, e.indexOf('(')).replace(/\s+$/, '') : e;

              return e
          });
```

How should I fix it to make closure not return an error?

**Comment by ChadKillingsworth** [comment]
The error message here seems pretty clear: the `s` flag you are using isn't a [valid RegExp flag](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp#Parameters).

I'm not sure what you expect the `s` flag to do - but it's not valid in EcmaScript regular expressions.

**Comment by brad4d** [comment]
Actually, the '/s' flag is valid in `ES_2018`.
You'll need to set both language in and language out to be `ES_2018` to avoid getting compile errors, though, because `closure-compiler` doesn't try to new regular expression features for older language outputs.
