### ISSUE TITLE
Compiler should recognize "== NaN" as always false.

### ISSUE THREAD

**Issue by shicks** [google/closure-compiler#3134]
This came up in a style guide discussion.  The expressions `x == NaN` and `x === NaN` are always false, and there is no reason to ever write them.  It would be great if the compiler could recognize and flag them.

**Comment by shicks** [comment]
Also Number.NaN.  I wonder if it would make sense to pull out a special subtype of number for known-always-NaN values?

**Comment by ChadKillingsworth** [comment]
I thought something like this was done long ago... As in pre-github
