### ISSUE TITLE
Closure Compiler doesn't handle the ideographic space cahracter

### ISSUE THREAD

**Issue by jason-patel-ensighten** [google/closure-compiler#3135]
Hi we're currently using closure compiler to compile some user entered javascript are receiving the following error. The compilation is using ES2018, WHITESPACEONLY, with setEmitUseStrict(false).

Nov 02, 2018 12:09:48 AM com.google.javascript.jscomp.LoggerErrorManager println
SEVERE: input.js:1451: ERROR - Parse error. Character '　' (U+3000) is not a valid identifier start char
   　yadsRequestAsync({
   ^

Nov 02, 2018 12:09:48 AM com.google.javascript.jscomp.LoggerErrorManager printSummary
WARNING: 1 error(s), 0 warning(s)

Upon investigation, there is definitely an ideographic space character in here , but we had previously been using the 2012-12-21 version which had handled compiling this out just fine. Was this change intended, if so, is there any way we can reintroduce the behavior through a options setting?

**Comment by EatingW** [comment]
This looks like a bug in the compiler where the Parser is not treating 0x3000 as a valid whitespace character. I'm going to submit a fix to add the character, and you can check whether this fixes your problem after.

**Comment by jason-patel-ensighten** [comment]
Thanks! Is the plan to include just that whitespace character, or all irregular whitespace characters as defined by ESLint?

**Comment by EatingW** [comment]
Right now we only plan to add only the ideographic space character, unless there is a strong reason to add any others.
