### ISSUE TITLE
Incorrect type definition reported for IntersectionObserver root property

### ISSUE THREAD

**Issue by tmb-github** [google/closure-compiler#3138]
In advanced mode, the Closure Compiler issues the following warning for the 'root' property of the IntersectionObserver:

```
JSC_TYPE_MISMATCH: actual parameter 2 of IntersectionObserver does not match formal parameter
found   : {
  root: (Element|null|undefined),
  rootMargin: (string|undefined),
  threshold: (?|undefined)
}
required: (undefined|{
  root: (Element|undefined),
  rootMargin: (string|undefined),
  threshold: (Array<number>|number|undefined)
}) at line 935 character 65
            observer = new IntersectionObserver(handleIntersect, options);
                                                                 ^
```

The spec at https://www.w3.org/TR/intersection-observer/ states:

> root, of type Element, readonly, nullable
> The root Element to use for intersection, or null if the observer uses the implicit root.
> 

This is also reproduced at the MDN entry on the root property of IntersectionObserver at https://developer.mozilla.org/en-US/docs/Web/API/IntersectionObserver/root

The type definition found here in the Closure Compiler would seem to be incorrect:

https://github.com/google/closure-compiler/blob/50713dceb16b369f8f317e5b49e8a9dec2b47496/externs/browser/intersection_observer.js#L108

```
/**
 * Options for the IntersectionObserver.
 * @see https://wicg.github.io/IntersectionObserver/#intersection-observer-init
 * @typedef {{
 *   threshold: (!Array<number>|number|undefined),
 *   root: (!Element|undefined),
 *   rootMargin: (string|undefined)
 * }}
 */
var IntersectionObserverInit;
```

`root` here should reference `null`, not `undefined`, yes?

**Comment by brad4d** [comment]
created internal Google bug b/119309514

**Comment by brad4d** [comment]
The type for the `root` property should probably be `?Element`.

**Comment by realityforge** [comment]
@brad4d This change has been applied to the externs so the issue can be closed

**Comment by brad4d** [comment]
@realityforge thanks
