### ISSUE TITLE
Add DOMRect .x .y properties

### ISSUE THREAD

**Issue by noell** [google/closure-compiler#3140]
<element>.getBoundingClientRect() returns a DOMRect. The DOMRect interface defines .x and .y properties [1].  Closure does not define them in its interface for DOMRect, aka ClientRect, sadly.

[1] https://www.w3.org/TR/geometry-1/#DOMRect

**Comment by noell** [comment]
See ClientRect in https://github.com/google/closure-compiler/blob/HEAD/externs/browser/w3c_css.js

**Comment by brad4d** [comment]
MDN says the `DOMRect` interface is not supported at all for IE or Edge.
https://developer.mozilla.org/en-US/docs/Web/API/DOMRect

It also says that the `x` and `y` properties on the return value from `getBoundingClientRect()`
are unsupported on IE, Edge, Safari and possibly some other mobile browsers.

The documentation referenced in our externs for `ClientRect` now uses the name `DOMRect`
https://www.w3.org/TR/geometry-1/#dom-domrect

It also does now define the `x` and `y` properties.

**Comment by brad4d** [comment]
Created internal Google bug b/119283989

@noell would you be interested in doing a pull request that just adds the `x` and `y` properties to `ClientRect`?
Doing more than that begins to risk breaking things, so I'm not sure we want to do it now.

**Comment by brad4d** [comment]
We should also update the doc reference link in the externs to
https://www.w3.org/TR/geometry-1/#dom-domrect

**Comment by noell** [comment]
Can't push a change to the closure repository for some reason:

remote: Permission to google/closure-compiler.git denied
fatal: unable to access 'https://github.com/google/closure-compiler.git/': The requested URL returned error: 403

Whatevs, made you a gist instead, see:
https://gist.github.com/noell/42d6162fc9a2036ded352731c2ee552f

**Comment by brad4d** [comment]
General FYI, you have to create your own fork google/closure-compiler, put your fix on a branch there, then make a pull request to get that change into google/closure-compiler.

In this case though, I've been communicating with @noell through another channel.

**Comment by realityforge** [comment]
@brad4d This can be closed as the externs have already been updated.

**Comment by brad4d** [comment]
@realityforge thanks
