### ISSUE TITLE
Make RescopeGlobalSymbols usable in a node environment

### ISSUE THREAD

**Issue by thheller** [google/closure-compiler#3146]
I'm using the `RescopeGlobalSymbols` compiler pass via the `options.setRenamePrefixNamespace` compiler option in `shadow-cljs`. This works great for Browser-targetted builds but `node.js` targetted builds break since the compiler is rewriting all of the node "specials".

```
module.exports -> window.module.exports
require("foo") ->  (0,window.require)("foo")
global -> window.global
```

This could be fixed by either making `SPECIAL_EXTERNS` configurable or just including the node-specific globals by default.

https://github.com/google/closure-compiler/blob/4c97e69df965da4179b639ea3ee2020c98cc3621/src/com/google/javascript/jscomp/RescopeGlobalSymbols.java#L60-L82

Happy to open a PR for this just wanted to check in first about the preferred way.

The added externs would be `global, process, require, module, exports, __filename, __dirname`.

**Comment by brad4d** [comment]
Created Google internal issue b/119770296

**Comment by brad4d** [comment]
@thheller I think your suggestion is a reasonable one, but I'm not personally familiar with this pass, so I could be wrong.

We're unlikely to work directly on this ourselves anytime soon, but if you're willing to create a PR we can review it and merge it if it seems safe to do so.

**Comment by zavr-1** [comment]
`Buffer` is also needed as an extern for the node environment.

**Comment by thheller** [comment]
Indeed. Here is a more complete List: https://nodejs.org/api/globals.html

**Comment by thheller** [comment]
In https://github.com/google/closure-compiler/pull/3154 I opted to make this configurable instead adding another hardcoded fixed set of names.

**Comment by ChadKillingsworth** [comment]
The root issue here is that `RescopeGlobalSymbols` isn't designed for a NodeJS environment. For it to work correctly, the global object needs to be `global` instead of `window`.

That's still not going to fix `require` however, because it's not really global. It's provided as an argument to an IIFE wrapper that node adds around all CommonJS module sources. We don't have a good way to model that in the compiler right now.

**Comment by thheller** [comment]
> We don't have a good way to model that in the compiler right now.

I don't understand that comment. The way it is currently modeled in the compiler is via the `SPECIAL_EXTERNS` constant I initially linked. The PR I created just makes that configurable. As you mentioned `require` is not a global and the `SPECIAL_EXTERNS` just exempts anything in that Set from getting rescoped at all, which is exactly what we want for `require`.

The switch from `window` to `global` is also a configuration option in my PR.

**Comment by ChadKillingsworth** [comment]
`SPECIAL_EXTERNS` are a hack- and not really a sustainable way to express this constraint.

**Comment by thheller** [comment]
This commit seems to imply that things declared in externs are no longer rewritten at all which makes this issue obsolete.

https://github.com/google/closure-compiler/commit/cb0f8d9fd4a84cadba58dbeeaa65752d0d612067

Feel free to close.

**Comment by thheller** [comment]
This was fixed in https://github.com/google/closure-compiler/commit/5bdbce93916f02e268d8d0223023b0853984aba1 and available since release `v20190121`.
