### ISSUE TITLE
Cannot import a CommonJS named export into an ES6 module.

### ISSUE THREAD

**Issue by zavr-1** [google/closure-compiler#3151]
I'm trying to import some CommonJS export, however it does not work? It works fine with the ES modules, or if I use the `require` instead of import.

```js
// index.js
import { TEST } from './dep'
import { TEST2 } from './dep-es6'

console.log(TEST)
console.log(TEST2)
```
```js
// dep.js
module.exports.TEST = 'TEST'
```
```js
// dep-es6.js
export const TEST2 = 'TEST (es6)'
```

Output:

```fs
undefined
TEST (es6)
```

If I change the script to use `require`, it's fine:

```js
// index.js
// import { TEST } from './dep'
const { TEST } = require('./dep')
import { TEST2 } from './dep-es6'

console.log(TEST)
console.log(TEST2)
```
```fs
TEST
TEST (es6)
```
The command I run to compile:

```
java --compilation_level=ADVANCED --language_in=ECMASCRIPT_2018 --language_out=ECMASCRIPT_2017--module_resolution=NODE
  --process_common_js_modules=t/t2/dep-es6.js
  --process_common_js_modules=t/t2/dep.js
  --process_common_js_modules=t/t2/index.js
```

Even if I write `exports.Foo` it still does not work (https://github.com/google/closure-compiler/wiki/JS-Modules -- wiki also has an error saying `export.Foo` and not `exports.Foo`).

------
As I can see, there's no interoperability between ES6 and CommonJs and Wiki does not recommend it. However, you have to support this option please: ES6 modules is one of the best features of modern JS, and a lot of companies have invested into migrating to it from `require`. Because all packages on NPM have to be CommonJS, this means that to use Closure, the code has to be migrated back to the require syntax for external dependencies! It just does not make sense to write
```js
import { hello } from './world'
const { example } = require('world')
```
You're Google and have an important role for the growth of the web, and to promote the newest lang features has to be on top of the list! The ability to import CommonJS from ES6 modules is so essential because the use case to write modules for NPM with `import`/`exports`, transpile them into `require` for publishing, and then use in another modules is so common -- I don't know how people have not brought this up before! Thanks for understanding. 

![Interoperability](https://2k4s4k3wofhp2b3qaf1365bl-wpengine.netdna-ssl.com/wp-content/uploads/2015/10/Interoperability.jpg)

**Comment by ChadKillingsworth** [comment]
This is by design and matches the latest spec for modules in Node. CommonJS modules have a single export which is the default export.

**Comment by ChadKillingsworth** [comment]
See https://nodejs.org/api/esm.html#esm_interop_with_existing_modules
