### ISSUE TITLE
Generated sourcemap is invalid when using flag isolation_mode/output_wrapper with create_source_map

### ISSUE THREAD

**Issue by Aqours** [google/closure-compiler#3155]
compiler flags
```js
const flags = {
    js: "input.js",
    language_in: "ECMASCRIPT6",
    language_out: "ECMASCRIPT5",
    compilation_level: "ADVANCED",
    isolation_mode: "IIFE",
    create_source_map: "output.js.map",
};
```

I encounter an error: `Error: original.line and original.column are not numbers -- you probably meant to omit the original mapping entirely and only map the generated position. If so, pass null for the original mapping instead of an object with empty or null values.`(Ref https://github.com/mozilla/source-map/pull/265/files), when I want use the generated sourcemap with `source-map@0.6.1` npm package.

The error will disappear if I remove `isolation_mode` compiler flag.

reproduce
```js
var fs = require("fs");
var SourceMapConsumer = require("source-map").SourceMapConsumer;
var SourceMapGenerator = require("source-map").SourceMapGenerator;

var generatedSourceMap = fs.readFileSync("output.js.map", { encoding: "utf8" });
var sourceMap = SourceMapGenerator.fromSourceMap(new SourceMapConsumer(generatedSourceMap));
```

**Comment by tjgq** [comment]
It looks like `source-map@0.6.1` is broken for other people too: https://github.com/webpack/webpack-sources/issues/28

Can you try with a more recent version?

For what it's worth, I generated a source map with `--isolation_mode=IIFE` for a small Javascript file and I don't see anything wrong with it.

**Comment by Aqours** [comment]
Sorry, I did not make it clear. I use Node API but not command line.

node test script
```js
const fs = require("fs");
const SourceMapConsumer = require("source-map").SourceMapConsumer;
const SourceMapGenerator = require("source-map").SourceMapGenerator;
const { compiler: JavaCompiler } = require("google-closure-compiler");

const compiler = new JavaCompiler({
    js: "input.js",
    language_in: "ECMASCRIPT6",
    language_out: "ECMASCRIPT5",
    compilation_level: "ADVANCED",
    isolation_mode: "IIFE",
    create_source_map: "output.js.map"
});
compiler.run((code, stdOutData, stdErrData) => {
    if (!stdErrData) {
        const generatedSourceMap = fs.readFileSync("output.js.map", { encoding: "utf8" });
        const sourceMap = SourceMapGenerator.fromSourceMap(new SourceMapConsumer(generatedSourceMap));
    }
});

```

**Comment by tjgq** [comment]
Your example works with `source-map@0.7.3` (the latest npm version), if you add an `await` on the result of `new SourceMapConsumer`:

```
const fs = require("fs");
const SourceMapConsumer = require("source-map").SourceMapConsumer;
const SourceMapGenerator = require("source-map").SourceMapGenerator;
const { compiler: JavaCompiler } = require("google-closure-compiler");

const compiler = new JavaCompiler({
    js: "input.js",
    language_in: "ECMASCRIPT6",
    language_out: "ECMASCRIPT5",
    compilation_level: "ADVANCED",
    isolation_mode: "IIFE",
    create_source_map: "output.js.map"
});
compiler.run(async (code, stdOutData, stdErrData) => {
    if (!stdErrData) {
        const generatedSourceMap = fs.readFileSync("output.js.map", { encoding: "utf8" });
        const sourceMap = SourceMapGenerator.fromSourceMap(await new SourceMapConsumer(generatedSourceMap));
        console.log(sourceMap.toJSON());
    }
});
```

This logs to the console a source map equivalent to the one produced to the compiler, which suggests it's round-tripping correctly through the `source-map` library.

I don't know why `source-map@0.6.1` crashes, but that looks like a bug in `source-map`, not the compiler.

**Comment by Aqours** [comment]
I found [BasicSourceMapConsumer constructor(v0.7.3)](https://github.com/mozilla/source-map/blob/0.7.3/lib/source-map-consumer.js#L201) returns a promise, hence adding `await` on the result of `new SourceMapConsumer` works fine.

It seems not the compiler's bug. I close this issue, and thank you for your instruction
