### ISSUE TITLE
Compiler doesn't resolve node dependency using "main" key value in package.json

### ISSUE THREAD

**Issue by jmosney** [google/closure-compiler#3163]
package.json can declare a key "main" with a value that's a reference to a file in the package ([npm docs](https://docs.npmjs.com/files/package.json#main)). However Google Closure Compiler seems to ignore that value and always look for a file "index.js" as the default. So when a file using that package declares a dependency using require, GCC throws an error.

#### End user's project
**index.js**
`
const xtend = require('xtend');
`
**package.json**
`
{
  "dependencies": {
    "xtend": "4.0.0"
  }
}
`

#### npm project
**immutable.js**
`
... useful utility...
`

**package.json**
`
{
  "main": "immutable"
}
`

When the end user runs GCC (ensuring they've supplied the xtend package using the --js flag to the command) they will get this error:
`
my-project.js:1: ERROR - Failed to load module "xtend"
var xtend = require('xtend');
            ^
1 error(s)
`

This is sort of related to https://github.com/google/closure-compiler/issues/3149 (Packages with dir as "main" in package.json do not resolve.) but I'm filing it anyway just in case the solution for that bug doesn't address this.

I've patched xtend [here](https://github.com/jmosney/xtend/commit/8b9846f7fdb4ba7dd88f55f16a6e20cdd6959cfb) to fix material-components-web compilation via GCC for my project (I pull in my fork via my package.json).

**Comment by EatingW** [comment]
Created Google internal issue b/120550812.

**Comment by ChadKillingsworth** [comment]
@jmosney Did you supply the package.json file to the compilation? You need to pass `--js node_modules/immutable/package.json` along with your other source files.

**Comment by jmosney** [comment]
Ah, that did it! Thanks very much Chad!
