### ISSUE TITLE
BigInt support

### ISSUE THREAD

**Issue by infusion** [google/closure-compiler#3167]
Hello,

I wanted to ask for plans on supporting the new native primitive type `BigInt`. Babel, Typescript and particularly V8 now have support for BigInt constants with an `n` suffix and operator overloading. As I primarily use CC as a bundler, it would be nice to see support for it.

Thanks
Robert

**Comment by brad4d** [comment]
We plan to add support for it in 2019.

**Comment by EatingW** [comment]
Internal Google issue b/64388683 is relevant.

**Comment by concavelenz** [comment]
There are a couple of bits that make this non-trivial:
* enabling BigInt changes type inference.
* enabling BigInt changes optimizations.

Previously, the code could assume that various operators produced "number", where as not it will need to consider the inputs and assume (!bigint|number).

**Comment by maierfelix** [comment]
Any updates on this?

**Comment by brad4d** [comment]
We'll have both input and output support for ES_2019 done in the next few weeks.
Then it will be time to start working on the stage 3 proposals of which this is one.
https://github.com/tc39/proposals/blob/master/README.md

**Comment by vapier** [comment]
BigInt has hit stage4 and will be in ES2020 ...
https://github.com/tc39/proposal-bigint

but doesn't seem like it's in `ECMASCRIPT_NEXT` yet :/

**Comment by brad4d** [comment]
FYI, we're currently working on `??` and `?.`, which we expect will be more generally useful.

**Comment by brad4d** [comment]
We're actively working on this now and close to adding `BigInt` definitions into closure-compiler's externs files.

**Comment by logidelic** [comment]
I appreciate that this is sitll being worked on, but I just want to point out that (unless I've done something wrong) the current version of the closure compiler is actually quite dangerous if one has `BigInt`s in their code. For example, it will _silently_ change code such as:

```
BigInt(2) ** BigInt(n)
```
To:
```
Math.pow(BigInt(2), BigInt(n))
```

Which is wrong and will break the code (possibly without someone knowing until it's too late)...

Anyone know of a workaround?

**Comment by brad4d** [comment]
Thank you @logidelic for pointing out a case I hadn't considered. I've filed an issue for it.

https://github.com/google/closure-compiler/issues/3684

Otherwise, though, this work is essentially done.
