### ISSUE TITLE
Travis Failing due to missing file

### ISSUE THREAD

**Issue by ChadKillingsworth** [google/closure-compiler#3168]
When #3150 was imported and merged as part of ac821bb2af372d4871519495edf6cde84d7e4369,
the `travis_util/test_npm.sh` was either missed or excluded from the external repository.

This is why Travis is failing

**Comment by brad4d** [comment]
I'm on it.
Created internal Google issue b/120647789

**Comment by brad4d** [comment]
Created an internal change and sent it to @tjgq for review.
He's on triage duty this week, so I've also asked him to do our push to GitHub for the day as soon as the change is submitted.

**Comment by brad4d** [comment]
The internal change was submitted.
It's actually @EatingW who is on triage duty though.
I'm coordinating with her on today's push to GitHub.
