### ISSUE TITLE
Invalid JS Doc causes invalid destructuring optimizations

### ISSUE THREAD

**Issue by ChadKillingsworth** [google/closure-compiler#3175]
Invalid JS Doc causes destructuring to produce invalid code:

```js
/**
 * @param {{foo: string[]}} obj
 * @param {string} bar
 */
function someFn({ foo }, bar) {
  console.log(foo, bar);
}

window['someFn'] = someFn;
```

https://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250A%252F**%250A%2520*%2520%2540param%2520%257B%257Bfoo%253A%2520string%255B%255D%257D%257D%2520obj%250A%2520*%2520%2540param%2520%257Bstring%257D%2520bar%250A%2520*%252F%250Afunction%2520someFn(%257B%2520foo%2520%257D%252C%2520bar)%2520%257B%250A%2520%2520console.log(foo%252C%2520bar)%253B%250A%257D%250A%250Awindow%255B'someFn'%255D%2520%253D%2520someFn%253B

**Comment by ChadKillingsworth** [comment]
As a side note, the JSDoc array format of `string[]` is becoming ever more popular. We might want to consider supporting it.

**Comment by blickly** [comment]
Created internal bug b/121271660 to track
