### ISSUE TITLE
"Closure Compiler GWT App" fails on rebuild if `mvn clean` isn't done first

### ISSUE THREAD

**Issue by brad4d** [google/closure-compiler#3180]
Standard build command in README.md is `mvn -DskipTests`, but this currently fails during the GWT App part of the build.

Errors seem to be related to using AutoValue in `Source.java`, which is marked as `@GwtIncompatible`.

```
[INFO] Compiling module com.google.JsComp
[INFO]    Tracing compile failure path for type 'com.google.javascript.jscomp.bundle.AutoValue_Source'
[INFO]       [ERROR] Errors in 'file:/usr/local/google/home/bradfordcsmith/git/closure-compiler/target/classes/com/google/javascrip
t/jscomp/bundle/AutoValue_Source.java'
[INFO]          [ERROR] Line 250: codeSupplier cannot be resolved to a variable
[INFO]          [ERROR] Line 210: Source.Builder cannot be resolved to a type
[INFO]          [ERROR] Line 75: The method estimatedSize() of type AutoValue_Source must override or implement a supertype method
[INFO]          [ERROR] Line 175: The method originalCodeSupplier() is undefined for the type Source
[INFO]          [ERROR] Line 65: The method runtimes() of type AutoValue_Source must override or implement a supertype method
[INFO]          [ERROR] Line 253: Source.Lazy cannot be resolved to a type
[INFO]          [ERROR] Line 87: originalCodeSupplier cannot be resolved to a variable
[INFO]          [ERROR] Line 246: Source.Lazy cannot be resolved to a type
...
```
I've tried the build personally at head and the last 2 release tags (`v20181125` and `v20181210`).
I got these errors every time.

**Comment by brad4d** [comment]
Created internal issue b/122078344

**Comment by ChadKillingsworth** [comment]
When I get errors like this, a `mvn clean` usually fixes it.

**Comment by brad4d** [comment]
Thanks, @ChadKillingsworth 
The command `mvn clean && mvn -DskipTests` completed successfully at both the release tags I tried previously and at the head of the master branch.

So, the real issue here is that something makes rebuilding break.

**Comment by brad4d** [comment]
We have to replace GWT with J2CL in 2019Q4, so this issue is obsolete.
Hopefully we will avoid whatever causes this problem in the new J2CL version.
