### ISSUE TITLE
Type casting does not work

### ISSUE THREAD

**Issue by zavr-1** [google/closure-compiler#3186]
```js
console.log(this.state.auth)
// {user: {…}, positions: Array(2), csrf: "PAfRhLYo-rPc2zuM2D8fM-H2G5AVTy-l_eeg"}}
const auth = /** @type {{ user: Object }} */ (this.state.auth)
console.log(auth.user)
// undefined
```

It's really difficult to understand how to type a return value from XHR i've tried so many things none of them work.

**Comment by lauraharker** [comment]
Created internal issue http://b/122536490

**Comment by lauraharker** [comment]
Could you provide steps to reproduce? e.g. a command line & input file or a https://closure-compiler.appspot.com/home link. It will help us to know what flags you are using and how the `this.state.auth` object is originally typed.

And to clarify, is it correct that:
Your problem is that compilation removes the `user` property from the typecast object?

**Comment by zavr-1** [comment]
```
/* eslint-env browser */
import LinkedIn from './comments/LinkedIn.js'
import User from './comments/User.js'
import fetch2 from './comments/fetch.js'

if (!('fetch' in window)) window.fetch = fetch2

const { Component, h, render } = window.preact

const HOST = 'http://localhost:5000'

const getUser = async () => {
  const r = await fetch('/user')
  const j = await r.json()
  return j
}

class App extends Component {
  constructor() {
    super()
    const auth = {}
    this.state = {
      loading: true,
      auth,
    }
  }
  async componentDidMount() {
    await this.auth()
    this.setState({
      loading: false,
    })
  }
  async auth() {
    const auth = await getUser()
    this.setState({
      auth,
    })
  }
  render() {
    if (this.state.loading)
      return h('div', null, 'Loading...')
    const auth = /** @type {{ user: Object }} */ this.state.auth
    console.log(auth)
    console.log(this.state.auth.user)
    if (!this.state.auth.user)
      return h('div', null, h(LinkedIn, { host: this.props.host }))
    return h('div', null, h(User, {
      ...this.state.auth,
      onSignout: () => {
        this.setState({
          auth: {},
        })
      },
    }))
  }
}

render(h(App, { host: HOST }), document.getElementById('preact'))
```

It does not remove it, it renames it to `u` which makes the access impossible. I've figured it out that I have to use externs, but it's not clear from the documentation that externs can be used for XHR (it only talks about external APIs).

**Comment by lauraharker** [comment]
Were you looking at https://developers.google.com/closure/compiler/docs/api-tutorial3#mixed?

> If you use third-party JavaScript libraries or APIs like the OpenSocial API or the Google Maps API, you need to be sure that Closure Compiler doesn't rename the symbols you use that are defined in those external libraries. For example, if your code calls the OpenSocial JavaScript function opensocial.newDataRequest(), you do not want Closure Compiler to transform this call into a.b(). Your code must use the same names that the external file uses.
> 
> Closure Compiler provides a mechanism for declaring that a name is defined in external code and so should not be renamed. This mechanism is called the extern.

This applies to the API for data returned by your own server as well. The fact that you're getting this data through XHR specifically isn't really important; what matters is that the `user` property is defined in code external to what you provide the Closure Compiler, and you need to tell the compiler not to rename `this.state.auth.user` -> `this.state.auth.u`.

Here's a similar StackOverflow question: https://stackoverflow.com/questions/36889934/why-does-google-closure-compiler-rename-objects-properties-names

Does that answer your question?

Looks like the compiler is WAI but I'd gladly take suggestions for improving documentation.
