### ISSUE TITLE
--use_only_custom_externs IllegalStateException

### ISSUE THREAD

**Issue by blickly** [google/closure-compiler#319]
This issue was imported from Closure Compiler's previous home at http://closure-compiler.googlecode.com

The original discussion is archived at:
http://blickly.github.io/closure-compiler-issues/#755

**Comment by Dominator008** [comment]
The `--use_only_custom_externs` flag has been replaced by the `--env` flag. `--env CUSTOM` still loads the language externs, so the definitions for `NaN`, `Infinity` and `undefined` will always be present.
