### ISSUE TITLE
Bad compile-time performance with GWT version

### ISSUE THREAD

**Issue by alexandergunnarson** [google/closure-compiler#3202]
Moving [this issue from closure-compiler-js](https://github.com/google/closure-compiler-js/issues/24) over to here as requested.

tl;dr — The GWT version of closure-compiler takes an extraordinary amount of time to complete compilation when compared to the Java version.

**Comment by lauraharker** [comment]
Created Google internal issue http://b/123245057

**Comment by brad4d** [comment]
We recommend using the java or graal version.
