### ISSUE TITLE
Optimization of Array.push()

### ISSUE THREAD

**Issue by dan1wang** [google/closure-compiler#3212]
After I reported Issue #3211, I discovered Closure Compiler (ADVANCED_OPTIMIZATIONS) also doesn't optimize push().

I had
```
      obj.arrayProp.push( offsetSegment(mask, offsetX, 0) );
      obj.arrayProp.push( offsetSegment(mirroredMask, offsetX, 0) );
```
and I get
```
a.f.push(offsetSegment(c,d,0)),
a.f.push(offsetSegment(h,d,0)),
```
instead of 
`a.f.push(offsetSegment(c,d,0),offsetSegment(h,d,0)),`

**Comment by tjgq** [comment]
Created Google internal issue b/123406223

**Comment by ChadKillingsworth** [comment]
This would be a pretty good first contribution. It can be done with a peephole optimization.

**Comment by cshung** [comment]
I wanted to attempt this one.

**Comment by brad4d** [comment]
Once I looked more closely at the PR proposed to fix this issue, I realized it wasn't really an optimization we should add.

From the discussion on that PR:

> Overall this optimization doesn't strike me as a very useful one.
> It's not likely that a human author would put a lot of array.push(), right next to each other,
> so I'd think this would only be useful if other optimizations ended up putting them together, which
> then allowed this optimization to do something useful. That also seems likely to be a rare thing to me.
> 
> Execution time is precious for large projects.
