### ISSUE TITLE
Output code is invalid when input is { [a]: function*(){ } }

### ISSUE THREAD

**Issue by Getfree** [google/closure-compiler#3217]
**Input.js**
```
let a = 1 ;

let obj = {
	[a]: function*(){ }
} ;
```

**Command line:**
```
java -jar closure-compiler-v20190121.jar --language_out NO_TRANSPILE -O SIMPLE  --js_output_file Output.js Input.js
```
**Output.js**
```
'use strict';
let a = 1, obj = {*[a]:function*() {
}};
```

Output file contains invalid syntax. There's an extra asterisk before `[a]`.

**Comment by tjgq** [comment]
Repro: https://closure-compiler-debugger.appspot.com/#input0%3Dlet%2520a%2520%253D%25201%253B%250Alet%2520obj%2520%253D%2520%257B%2520%255Ba%255D%253A%2520function*()%257B%257D%2520%257D%2520%253B%26input1%26conformanceConfig%26externs%26refasterjs-template%26CHECK_TYPES%3Dtrue%26CLOSURE_PASS%3Dtrue%26PRESERVE_TYPE_ANNOTATIONS%3Dtrue%26PRETTY_PRINT%3Dtrue

Created Google internal issue b/123525805.
