### ISSUE TITLE
Unescaped line and paragraph sep in older lang versions with UTF-8

### ISSUE THREAD

**Issue by mfikes** [google/closure-compiler#3243]
Previously, if you specify UTF-8 and have unicode line or paragraph separators in strings, those characters would be escaped.

Here is an example of the previous behavior:

```
$ java -jar target/closure-compiler-1.0-SNAPSHOT.jar --charset UTF-8 --language_out ECMASCRIPT5
The compiler is waiting for input via stdin.
alert("\u0061\u2028\u2029\u0062");
<^D pressed here>
alert("a\u2028\u2029b");
```

With https://github.com/google/closure-compiler/commit/a6aeaab3ed2cd5f4a28344dedb3d346b8f99cbc1 these two characters are allowed to be emitted unescaped in the output JavaScript.  Here is an example with that commit:

```
$ java -jar target/closure-compiler-1.0-SNAPSHOT.jar --charset UTF-8 --language_out ECMASCRIPT5
The compiler is waiting for input via stdin.
alert("\u0061\u2028\u2029\u0062");
<^D pressed here>
alert("a<U+2028><U+2029>b");
```

Note that, in the above `<U+2028>` and `<U+2029>` are the actual unescaped characters (I chose to write them this way in this issue so that they are visible.)

It seem that the intent of https://github.com/google/closure-compiler/commit/a6aeaab3ed2cd5f4a28344dedb3d346b8f99cbc1 is to allow this unescaping when language out is `ES_NEXT`, but the example above illustrates that the unescaped versions of these two characters appears even for earlier language out versions.

**Comment by brad4d** [comment]
Created internal issue http://b/127294275

**Comment by jplaisted** [comment]
Will take a look!
