### ISSUE TITLE
Adding Custom Passes forces ES5 output

### ISSUE THREAD

**Issue by thheller** [google/closure-compiler#3246]
In [shadow-cljs](https://github.com/thheller/shadow-cljs) I am adding a few custom passes to process some of the generated ClojureScript code before the Closure Compiler optimizes it. The passes I'm adding don't really care about the language feature set and would support `ES_NEXT` but any custom pass is currently limited to [ES5](https://github.com/google/closure-compiler/blob/1976fb7ba59dd8fb5f48a099f8b70390c4dac4df/src/com/google/javascript/jscomp/DefaultPassConfig.java#L3197). Even if the passes do nothing but extract some data.

I'm adding the pass via ` compilerOptions.addCustomPass(BEFORE_CHECKS, ...)` and when combining this with a output feature set > ES5 I get an compiler error with latest release or compiler warnings with the previous release.

```
Attempted to run pass "runCustomPasses" on input with features it does not support. Skipping pass.
Unsupported features: [array pattern rest, arrow function, binary literal, block-scoped function declaration, class, class extends, class getters/setters, computed property, const declaration, default parameter, array destructuring, object destructuring, extended object literal, for-of loop, generator, let declaration, member declaration, new.target, octal literal, RegExp flag 'u', RegExp flag 'y', rest parameter, spread expression, super, template literal]
```

Everything works fine when running outputting ES5 and lower but there is technically no reason higher settings wouldn't work. It would be nice if either the passes could control which features they support themselves. Either by passing an extra option to `addCustomPass` or having the passes implement an interface or so? Maybe just adjust the hardcoded default to `ES_NEXT` and let custom passes complain themselves when they run into something they don't support?

`CompilerOptions.setSkipUnsupportedPasses` is also package-protected and can't be set properly so the latest release always errors out and there is no way to bump it down to a warning or ignore it in the first place.

**Comment by blickly** [comment]
Yeah, that seems like a bug in the API.  I think that either custom passes should be able to specify their version, or we should just assume that you can use them with the requested language versions.

**Comment by blickly** [comment]
Created internal issue http://b/127860581

**Comment by thheller** [comment]
Fixed in https://github.com/google/closure-compiler/commit/405124ff062b07ec8e0449224ff2d119f0e69ea1, available since `v20190325`.
