### ISSUE TITLE
`--js` doesn't follow symbolic links

### ISSUE THREAD

**Issue by teppeis** [google/closure-compiler#3253]
`--js path/to/symlinkdir` doesn't work because it doesn't follow symlinks.

`java.nio.file.Files.walkFileTree()` doesn't follow symlinks by default.

https://github.com/google/closure-compiler/blob/c2cefb684c57b69d82ead0236f2dd2fce129f57b/src/com/google/javascript/jscomp/CommandLineRunner.java#L2113-L2114

But it has an option to follow symlinks.
https://docs.oracle.com/javase/8/docs/api/java/nio/file/Files.html#walkFileTree-java.nio.file.Path-java.util.Set-int-java.nio.file.FileVisitor-
https://docs.oracle.com/javase/8/docs/api/java/nio/file/FileVisitOption.html#FOLLOW_LINKS

Can you specify the option?

**Comment by blickly** [comment]
This seems very unlikely to break anything.  @teppeis, would you mind creating a PR?

**Comment by teppeis** [comment]
@blickly I've send PR #3264 !
