### ISSUE TITLE
true/false in object initializer produces incorrect code in advanced mode

### ISSUE THREAD

**Issue by phb** [google/closure-compiler#3261]
This is easy to reproduce using the online google closure compiler

```
// ==ClosureCompiler==
// @compilation_level ADVANCED_OPTIMIZATIONS
// @output_file_name default.js
// ==/ClosureCompiler==

// ADD YOUR CODE HERE
function hello(name) {
  var x = {true: "hello", false: "bar"}
  alert(JSON.stringify(x));
}
hello('New user');

```

This results in the following translated code:
`alert(JSON.stringify({b:"hello",a:"bar"}));
`

**Comment by tjgq** [comment]
Created Google internal issue b/128546766

**Comment by concavelenz** [comment]
What do you feel is incorrect with this code?  I see that object properties are renamed but that is expected with property renaming enabled.

**Comment by phb** [comment]
Hi,

I expected that the object initializer would treat literals in the same way as a computed member expression. ie, shouldn't the Object Initializer treat true/false the same way as other primitive types (See below)

Ie, compare this output:
```
// ==ClosureCompiler==
// @compilation_level ADVANCED_OPTIMIZATIONS
// @output_file_name default.js
// ==/ClosureCompiler==

// ADD YOUR CODE HERE
function hello(name) {
  var x = {1: "hello", 0.42: "bar", "Thing": "baz"}
  alert(JSON.stringify(x));
}
hello('New user');
```
Which gets you
```
alert(JSON.stringify({1:"hello","0.42":"bar",Thing:"baz"}));
```

However, if I don't specify a primitive type, I would expect closure to rename the properties, ie, compare:
```
// ==ClosureCompiler==
// @compilation_level ADVANCED_OPTIMIZATIONS
// @output_file_name default.js
// ==/ClosureCompiler==

// ADD YOUR CODE HERE
function hello(name) {
  var x = {one: "hello", two: "bar", three: "baz"}
  alert(JSON.stringify(x));
}
hello('New user');
```

Which results in
```
alert(JSON.stringify({a:"hello",c:"bar",b:"baz"}));
```

**Comment by concavelenz** [comment]
true/false are not primitive values there. They are the property names 'true' and 'false' and as such they are renamed like any other property name.

**Comment by phb** [comment]
Thanks @concavelenz , sorry for the noise. I didn't understand that reserved words was valid property names and assumed numbers and booleans would be treated the same. Thank you
