### ISSUE TITLE
contrib/nodejs/buffer.js is outdated

### ISSUE THREAD

**Issue by Mikolaj** [google/closure-compiler#3263]
This 

https://github.com/google/closure-compiler/blob/master/contrib/nodejs/buffer.js 

is outdated wrt to 

https://npmdoc.github.io/node-npmdoc-buffer/build/apidoc.html#apidoc.element.buffer.Buffer.alloc

resulting in `JavaScript exception: TypeError: Buffer.nb is not a function` error (`JavaScript exception: TypeError: Buffer.$alloc$ is not a function` when compiled with `--debug`) in my code. The following addition (a partial hack) fixed it for me:

```
/**
 * @param {number=} size
 * @return {Buffer}
 */
buffer.Buffer.alloc;
```

Note that I get the same error when using https://github.com/dcodeIO/node.js-closure-compiler-externs/blob/master/buffer.js, which is more complete, but even older and so similarly outdated, so instead I report here.

**Comment by tjgq** [comment]
Would you like to send a PR?

**Comment by Mikolaj** [comment]
Here you go.
