### ISSUE TITLE
Add `name ` and `message` to DOMException externs?

### ISSUE THREAD

**Issue by banga** [google/closure-compiler#3266]
I get an error compiling `e.name` or `e.message` when `e insttanceof DOMException`. Looks like these were added as optional constructor parameters in https://github.com/google/closure-compiler/commit/824813707fe1a35ec98255ffd78a437c781e0f70 but haven't been added to the prototype.

**Comment by tjgq** [comment]
Can you send us a PR adding them to the prototype? Thanks.
