### ISSUE TITLE
Variable inlining increases bundle size in some cases

### ISSUE THREAD

**Issue by pvorona** [google/closure-compiler#3272]
Advanced mode. Consider the following example:
```
for(let i = 0; i < items.length; i++){window['b']+i}
// vs
var a='length';
for(let i = 0; i < items[a]; i++){window['b']+i}
```
If we use variable *length* certain amount of times instead of accessing property directly we can benefit from second approach becase variable name can get mangled and array property cant. 
I am wondering why compiler doesn't output something like
`var a='length';for(var i=0;i<b[a];i++){}`
when a certain amount of occurrences of variable *length* is met? In the above example **10 for loops** with an extracted variable can be expressed in 395 chars vs 420 now. And the more occurrences of word *length* the more we can benefit from extracting string variables or global objects properties.

Here is sandbox with this example: https://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%2540compilation_level%2520ADVANCED_OPTIMIZATIONS%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250Avar%2520a%253D'length'%253B%250Afor(let%2520i%2520%253D%25200%253B%2520i%2520%253C%2520items%255Ba%255D%253B%2520i%252B%252B)%257Bwindow%255B'b'%255D%252Bi%257D%250Afor(let%2520i%2520%253D%25200%253B%2520i%2520%253C%2520items%255Ba%255D%253B%2520i%252B%252B)%257Bwindow%255B'b'%255D%252Bi%257D%250Afor(let%2520i%2520%253D%25200%253B%2520i%2520%253C%2520items%255Ba%255D%253B%2520i%252B%252B)%257Bwindow%255B'b'%255D%252Bi%257D%250Afor(let%2520i%2520%253D%25200%253B%2520i%2520%253C%2520items%255Ba%255D%253B%2520i%252B%252B)%257Bwindow%255B'b'%255D%252Bi%257D%250Afor(let%2520i%2520%253D%25200%253B%2520i%2520%253C%2520items%255Ba%255D%253B%2520i%252B%252B)%257Bwindow%255B'b'%255D%252Bi%257D%250Afor(let%2520i%2520%253D%25200%253B%2520i%2520%253C%2520items%255Ba%255D%253B%2520i%252B%252B)%257Bwindow%255B'b'%255D%252Bi%257D%250Afor(let%2520i%2520%253D%25200%253B%2520i%2520%253C%2520items%255Ba%255D%253B%2520i%252B%252B)%257Bwindow%255B'b'%255D%252Bi%257D%250Afor(let%2520i%2520%253D%25200%253B%2520i%2520%253C%2520items%255Ba%255D%253B%2520i%252B%252B)%257Bwindow%255B'b'%255D%252Bi%257D%250Afor(let%2520i%2520%253D%25200%253B%2520i%2520%253C%2520items%255Ba%255D%253B%2520i%252B%252B)%257Bwindow%255B'b'%255D%252Bi%257D%250Afor(let%2520i%2520%253D%25200%253B%2520i%2520%253C%2520items%255Ba%255D%253B%2520i%252B%252B)%257Bwindow%255B'b'%255D%252Bi%257D%250A

Now compiler always inlines **length** variable. Am I missing something?

**Comment by tjgq** [comment]
We optimize for gzipped size, and gzip is pretty good at getting rid of recurring strings.

It's unlikely that we'd implement this optimization unless you can show real-world examples where it yields significant post-gzip gains.

**Comment by pvorona** [comment]
@tjgq I missed the point about gzipped size, thanks!
