### ISSUE TITLE
unwanted transformation

### ISSUE THREAD

**Issue by ray007** [google/closure-compiler#3280]
I tried to use google closure compiler to bundle the js libs for my app, but even with `compilation_level` set to `'BUNDLE'` or `'WHITESPACE_ONLY'` unicode character sequences (like `"\u2028"`) get replaced with the actual unicode chars. Which make IE/Edge barf on input with
```
SCRIPT1015: SCRIPT1015: Unterminated string constant
```
With current java-compiler invoked through gulp, `charset` set to `"UTF-8"`.

**Comment by brad4d** [comment]
I believe this is a duplicate of #3243
