### ISSUE TITLE
Feature request: support for unquoted destructuring assignment

### ISSUE THREAD

**Issue by steph643** [google/closure-compiler#3281]
In ADVANCED mode, the following code produces a questionable output:
```javascript
const obj = JSON.parse('{ "foo": "hello", "bar": "world" }')
console.log(obj)            // Output: {foo: "hello", bar: "world"}
const { foo, bar } = obj
console.log(foo, bar)       // Output: undefined undefined
```
The workaround is to replace line 3 with:
```javascript
const { ['foo']: foo, ['bar']: bar } = obj
```
However, this feels illogical. I think a destructuring assignment always corresponds to a search-by-name intent, so the names should be left untouched by the closure compiler.

**Comment by brad4d** [comment]
FYI, the square brackets aren't needed.

```javascript
const { 'foo': foo, 'bar': bar } = obj;
```

**Comment by brad4d** [comment]
repro
https://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540compilation_level%2520ADVANCED_OPTIMIZATIONS%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%2540formatting%2520pretty_print%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250A%252F%252F%2520ADD%2520YOUR%2520CODE%2520HERE%250Aconst%2520obj%2520%253D%2520JSON.parse('%257B%2520%2522foo%2522%253A%2520%2522hello%2522%252C%2520%2522bar%2522%253A%2520%2522world%2522%2520%257D')%250Aconsole.log(obj)%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%252F%252F%2520Output%253A%2520%257Bfoo%253A%2520%2522hello%2522%252C%2520bar%253A%2520%2522world%2522%257D%250Aconst%2520%257B%2520foo%252C%2520bar%2520%257D%2520%253D%2520obj%250Aconsole.log(foo%252C%2520bar)%2520%2520%2520%2520%2520%2520%2520%252F%252F%2520Output%253A%2520undefined%2520undefined%250A

**Comment by steph643** [comment]
> FYI, the square brackets aren't needed.

@brad4d, you are right, thanks. But notice that prettier (and VS Code) removes the quotes when there is no bracket, without any mean to disable this behavior. See [this thread](https://github.com/prettier/prettier/issues/4327).

**Comment by brad4d** [comment]
Better repro with more explanation in comments.
https://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540compilation_level%2520ADVANCED_OPTIMIZATIONS%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%2540formatting%2520pretty_print%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250A%252F%252F%2520ADD%2520YOUR%2520CODE%2520HERE%250Aconst%2520obj%2520%253D%2520JSON.parse('%257B%2520%2522foo%2522%253A%2520%2522hello%2522%252C%2520%2522bar%2522%253A%2520%2522world%2522%2520%257D')%250Aconsole.log(obj)%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%252F%252F%2520Output%253A%2520%257Bfoo%253A%2520%2522hello%2522%252C%2520bar%253A%2520%2522world%2522%257D%250A%250A%252F%252F%2520This%2520is%2520equivalent%2520to%250A%252F%252F%2520let%2520foo%2520%253D%2520obj.foo%252C%2520bar%2520%253D%2520obj.bar%253B%250A%252F%252F%2520compiler%2520warns%2520that%2520as%2520far%2520it%2520knows%250A%252F%252F%2520obj.foo%2520and%2520obj.bar%2520are%2520undefined%250Alet%2520%257B%2520foo%252C%2520bar%2520%257D%2520%253D%2520obj%250A%250A%252F%252F%2520because%2520they%2520are%2520unquoted%252C%2520properties%2520foo%2520and%2520bar%2520get%2520renamed%252C%250A%252F%252F%2520but%2520then%2520they%2520no%2520longer%2520match%2520the%2520literal%2520%2522foo%2522%2520and%2520%2522bar%2522%250A%252F%252F%2520properties%2520in%2520the%2520JSON%2520object.%250Aconsole.log(foo%252C%2520bar)%2520%2520%2520%2520%2520%2520%2520%252F%252F%2520Output%253A%2520undefined%2520undefined%250A%250A%252F%252F%2520this%2520way%2520works%2520correctly%250A(%257B%2520'foo'%253A%2520foo%252C%2520'bar'%253A%2520bar%2520%257D%2520%253D%2520obj)%253B%250Aconsole.log(foo%252C%2520bar)%253B%250A

This is working as intended.

The compiler cannot just decide that property names used in destructuring should be treated as quoted.
This would break destructuring cases where the code was designed with the intention that the properties be renamed.

Also note that the compiler does complain that you're accessing properties that appear to it to be undefined.

**Comment by brad4d** [comment]
@steph643 Thanks for the link to the prettier issue. I was unaware of that problem.

**Comment by steph643** [comment]
> This would break destructuring cases where the code was designed with the intention that the properties be renamed.

My initial post was denying the possibility that such intention ever exists:
> I think a destructuring assignment always corresponds to a search-by-name intent

So it seems I was wrong. Would you be kind enough to explain me where?

**Comment by ChadKillingsworth** [comment]
One of the major goals of using ADVANCED mode is to be able to rename properties below. This code should be completely safe in ADVANCED mode and should rename the properties.

```js
const obj = {foo: 'foo', bar: 'bar'};
const {foo, bar} = obj;
console.log(foo, bar, obj.foo, obj.bar);
```

**Comment by ChadKillingsworth** [comment]
Or to say another way, the only reason your code above had problems is you used `JSON.parse` so the original properties were not visible to the compiler.

**Comment by steph643** [comment]
Thanks, @ChadKillingsworth, I understand. 

For the record, this code shows the issue without relying on `JSON.parse`:
```javascript
const obj = { 'foo': 'hello', 'bar': 'world' }
console.log(obj)              // Output: {foo: "hello", bar: "world"}
const { foo, bar } = obj
console.log(foo, bar)       // Output: undefined undefined
```

Same for this one:
```javascript
function doIt({ foo, bar }) {
  console.log(foo, bar)
}
doIt({ foo: 'hello', bar: 'world' })     // Output: hello world
doIt({ 'foo': 'hello', 'bar': 'world' }) // Output: undefined undefined
```
