### ISSUE TITLE
Try-catch: If caught exception's name is "e" and it's in the global scope it will become longer (SIMPLE_OPTIMIZATIONS)

### ISSUE THREAD

**Issue by blickly** [google/closure-compiler#329]
This issue was imported from Closure Compiler's previous home at http://closure-compiler.googlecode.com

The original discussion is archived at:
http://blickly.github.io/closure-compiler-issues/#697

**Comment by Dominator008** [comment]
With the given code:
```javascript
try { throw "oops";}
catch (e) { }
```
, the web service produces
```javascript
try{throw"oops";}catch(a){};
```
under SIMPLE_OPTIMIZATIONS, which is expected.
