### ISSUE TITLE
Compiling to ECMASCRIPT_2018 using SIMPLE_OPTIMIZATIONS doesn't shorten variable names

### ISSUE THREAD

**Issue by DonaldDuck313** [google/closure-compiler#3295]
I tried to compile a file using the following command:

`java -jar closure-compiler-v20190215.jar --js myfile.js --js_output_file myfile.min.js --rewrite_polyfills=false --language_in ECMASCRIPT_2018 --language_out ECMASCRIPT_2018 --compilation_level SIMPLE_OPTIMIZATIONS`

The problem is that it doesn't make local variable names shorter, it just removes whitespaces and comments just like if I would have used `--compilation_level WHITESPACE_ONLY`. So if I give this Javascript code as input:

```
function foo(bar){
	alert(bar);
}
```

I get this output:

`function foo(bar){alert(bar)};`

But I would expect something like this:

`function foo(a){alert(a)};`

If I use `--language_out ECMASCRIPT_2017` instead it works, but I need some ECMAScript 2018 features in my Javascript code.

**Comment by EatingW** [comment]
Created Google internal issue http://b/129349982. We are in the process of updating optimization passes to work with supporting ECMASCRIPT_2018 right now. Have you tried closure-compiler-v20190301.jar?

**Comment by teppeis** [comment]
@EatingW @DonaldDuck313 Fixed in v20190325.

In detail, it's fixed in v20190301 but it throws an error:

```
ERROR - Attempted to run pass "normalize" on input with features it does not support. Running pass anyway.
Unsupported features: [object literals with spread, object pattern rest, async generator functions, for-await-of loop, RegExp flag 's', RegExp Lookbehind, RegExp named groups, RegExp unicode property escape]
```

v20190325 throws no errors.

**Comment by brad4d** [comment]
@teppeis Thanks for confirming the fix and reporting back.
