### ISSUE TITLE
Document @noinline

### ISSUE THREAD

**Issue by realityforge** [google/closure-compiler#3299]
I was just directed to an issue that indicates `@noinline` is supported by the compiler but it is not documented on the [wiki](https://github.com/google/closure-compiler/wiki/Annotating-JavaScript-for-the-Closure-Compiler). It would be great if a short description was that indicated any of the non-obvious implications ... if there are any :)

**Comment by blickly** [comment]
Internal issue created http://b/129431114

**Comment by lauraharker** [comment]
I added https://github.com/google/closure-compiler/wiki/Annotating-JavaScript-for-the-Closure-Compiler#noinline.

The only non-obvious implication is that there may be code paths in the compiler that do not honor this annotation, although it works in the common case. (See Bradford's comment here https://github.com/google/closure-compiler/issues/2751#issuecomment-353484914)
