### ISSUE TITLE
TypeCheck doesn't know how to handle MODULE_BODY

### ISSUE THREAD

**Issue by PorterNan** [google/closure-compiler#3304]
./lib/tslib.extern.js:25: ERROR - Internal Error: TypeCheck doesn't know how to handle MODULE_BODY
goog.module('tslib');
^^^^^^^^^^^^^^^^^^^^^

I got this after I updated google-closure-compiler into new version "google-closure-compiler": "^20190325.0.0" in npm
Actually this tslib extern file comes from a third-party git repo: https://github.com/angular/tsickle/blob/master/third_party/tslib/tslib.js

What can I do to be unblocked from this error?

**Comment by PorterNan** [comment]
Even reverted back to previous version does not work for me... wired..

**Comment by blickly** [comment]
I don't think there's enough information here to reproduce the issue.

Please reopen if you manage to come up with a way to reproduce

**Comment by PorterNan** [comment]
> I don't think there's enough information here to reproduce the issue.
> 
> Please reopen if you manage to come up with a way to reproduce

I got a repo to easily repro the issue, take a look here if you have time:
https://github.com/PorterNan/CC-Issue-repro

**Comment by PorterNan** [comment]
> I don't think there's enough information here to reproduce the issue.
> 
> Please reopen if you manage to come up with a way to reproduce

BTW, I cannot reopen it by myself, please help me reopen it thanks

**Comment by blickly** [comment]
OK, that's great.

Do you know if the behavior here changed with a recent release or not?

**Comment by blickly** [comment]
Also, what command/flags are you using to build?

**Comment by PorterNan** [comment]
All the options are in closure.js, you could firstly 

npm install

then

node closure.js

then you will see the issue

**Comment by PorterNan** [comment]
I haven't updated for months, but it happened when I updated yesterday, I believe that js npm package is just point me to the real jar file, even I reverted the version, that jar package is still not the one I used to have

**Comment by PorterNan** [comment]
In order to show it clear that's what I got in closure.js:
const closureCompiler = new ClosureCompiler({
  js: ['index.js'],
  module_output_path_prefix: 'closure_output/dist/',
  language_in: 'ECMASCRIPT5',
  language_out: 'ECMASCRIPT5',
  compilation_level: 'ADVANCED',
  externs: ["tslib.extern.js"],
});

**Comment by blickly** [comment]
Oh, I don't think you can use goog.module() inside externs files, so that is likely the issue.

**Comment by PorterNan** [comment]
It was working before, why it just stop working today, BTW, if it is not allowed, where should I put this goog.module() function? Somewhere we run the code?

**Comment by blickly** [comment]
That `tslib.extern.js` file, despite the filename, is clearly not an extern file. Passing it as source might work.

It's hard for me to imagine how this ever worked before.  Perhaps the file just wasn't being passed to the compiler before?

**Comment by PorterNan** [comment]
Hmmm, it works for me, I got a lot of code under tslib, and it actually helps me not to mangle all the properties under tslib, nvm, I will remove this line and try again
