### ISSUE TITLE
TypeCheck doesn't know how to handle MODULE_BODY

### ISSUE THREAD

**Issue by PorterNan** [google/closure-compiler#3306]
./lib/tslib.extern.js:25: ERROR - Internal Error: TypeCheck doesn't know how to handle MODULE_BODY
goog.module('tslib');
^^^^^^^^^^^^^^^^^^^^^

I got this after I updated google-closure-compiler into new version "google-closure-compiler": "^20190325.0.0" in npm
Actually this tslib extern file comes from a third-party git repo: https://github.com/angular/tsickle/blob/master/third_party/tslib/tslib.js

What can I do to be unblocked from this error?

I got a repo to easily repro the issue:
https://github.com/PorterNan/CC-Issue-repro

just
 npm install 
then
 node closure.js

**Comment by blickly** [comment]
Dup of #3304
