### ISSUE TITLE
NullPointerException related to getJSDocInfo

### ISSUE THREAD

**Issue by arv** [google/closure-compiler#3307]
I'm getting a NPE trying to print the `getJSDocInfo` from the following line:

```js
const goog = {};
```

from https://github.com/mihaip/react-closure-compiler/blob/94829a9313ac00146484a0ee0453e1eebfe5ea1c/test/info/persistent/react/jscomp/ReactCompilerPassTest.java#L1040

I think the issue is that `isNamespaceDecl` returns `true` but `getJSDocInfo` returns `null` in the call here.

https://github.com/google/closure-compiler/blob/c04566ca39ac32bee56d26d3b2318709418e6b83/src/com/google/javascript/jscomp/TypedCodeGenerator.java#L80-L81

It seems strange that these are out of sync?

**Comment by arv** [comment]
CC @mihaip

**Comment by blickly** [comment]
Interesting that we haven't seen this before; this looks like pretty old code.

Created internal issue http://b/129568331

**Comment by arv** [comment]
Maybe it is due to reordering some passes? If I change to `var` it works or if I add `@const` it also works.
