### ISSUE TITLE
HTMLCanvasElement is missing transferControlToOffscreen

### ISSUE THREAD

**Issue by sidnei** [google/closure-compiler#3311]
It is marked as experimental and supported by some browsers, so not sure if it should be present or not:

https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/transferControlToOffscreen

Trying to use it in places where the closure compiler is used leads to:

 Property transferControlToOffscreen never defined on HTMLCanvasElement  
      this.canvasEl_.transferControlToOffscreen() :
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by blickly** [comment]
I think the question of when an experimental API becomes stable enough to safely add externs for it is a good one

Created internal issue http://b/129796154

**Comment by lauraharker** [comment]
This extern was added in 9b7948222de73987cceff3e394147b4218a50559.
