### ISSUE TITLE
WHITESPACE_ONLY is changing functions

### ISSUE THREAD

**Issue by floggle** [google/closure-compiler#3315]
This is my entire js file:
```
function my_function(){

    for (let item of $('.a_class')){
        continue;
    }
}
```

I compile it via the CLI  (no externs, no other files) using the latest release (closure-compiler-v20190325.jar).
The output:
```
function my_function(){for(var $jscomp$iter$0=$jscomp.makeIterator($(".a_class")),$jscomp$key$item=$jscomp$iter$0.next();!$jscomp$key$item.done;$jscomp$key$item=$jscomp$iter$0.next()){var item=$jscomp$key$item.value;{continue}}};
```
Which then fails to execute:
```
ReferenceError: $jscomp is not defined
```
The docs are quite clear that WHITESPACE_ONLY isn't meant to change anything apart from whitespace.

It also doesn't work with SIMPLE_OPTIMIZATIONS (the result is actually MUCH longer too!):
```
var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.makeIterator=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};function my_function(){for(var a=$jscomp.makeIterator($(".a_class")),b=a.next();!b.done;b=a.next());};
```

**Comment by brad4d** [comment]
The changes you're seeing are due to the compiler trying to transpile `for-of` for you.
Make sure you're setting `--language_out` to at least `ES6`. The default is `ES5`, because that is still the lowest common denominator for web browsers. That may change soon, though...

**Comment by floggle** [comment]
@brad4d  - Thanks, I'll give that a go.

Incidentally, that's not what the docs say:
https://developers.google.com/closure/compiler/docs/compilation_levels -
```
The WHITESPACE_ONLY compilation level removes comments from your code and also removes line breaks, unnecessary spaces, extraneous punctuation (such as parentheses and semicolons), and other whitespace. The output JavaScript is functionally identical to the source JavaScript. 

 This compilation level provides the least compression of the three levels.
```
So this is a bug in the docs if not the code.

**Comment by christiantjl** [comment]
Can confirm this is a bug - `-O WHITESPACE` should not be transpiling anything, just removing comments and whitespace. There should be no `$jscomp` injection at all.
