### ISSUE TITLE
Property X never defined on Y

### ISSUE THREAD

**Issue by zavr-1** [google/closure-compiler#3319]
I'm running into this issue,
```js
// index.js
import Type from './Type'

const t = new Type()
t.fromXML('Hello world', { name: 'test', optional: false })
console.log(t.type)
```
```js
// Type.js
/**
 * A representation of a type.
 * @extends {typal.Type}
 */
export default class Type {
  fromXML(content, props) {
    this.type = props.name
    this.desc = content
  }
}
```

```js
// depack/prop/externs.js
/** @const */
var typal = {}
/**
 * @typedef {{ type: string, desc: string }}
 */
typal.Type
```

I'm pretty sure if something extends an extern, it should preserve its own methods as well.

```sh
-jar compiler.jar --compilation_level ADVANCED \
--language_out ECMASCRIPT_2017 \
--formatting PRETTY_PRINT --externs depack/prop/externs.js \
--module_resolution NODE \
--js depack/prop/index.js depack/prop/Type.js 
```
Compiles fine though

```js
class a {
}
;const b = new a;
b.type = "test";
b.desc = "Hello world";
console.log(b.type);
```
Don't want the warning though.
```
depack/prop/index.js:4: WARNING - Property fromXML never defined on Type
t.fromXML('Hello world', { name: 'test', optional: false })
  ^^^^^^^

0 error(s), 1 warning(s), 87.0% typed
```

**Comment by brad4d** [comment]
Created internal issue http://b/130165924

**Comment by brad4d** [comment]
Here's a repro using the online debugger, including a bit of extra stuff I was using to experiment.

https://closure-compiler-debugger.appspot.com/#input0%3D%252F**%2520%2540typedef%2520%257B%257B%2520type%253A%2520string%252C%2520desc%253A%2520string%2520%257D%257D%2520*%252F%250Avar%2520LocalType%253B%250A%250A%252F**%250A%2520*%2520A%2520representation%2520of%2520a%2520type.%250A%2520*%2520%2540extends%2520%257BLocalType%257D%250A%2520*%252F%250Aexport%2520class%2520Type%2520%257B%250A%2520%2520%252F**%250A%2520%2520%2520*%2520%2540param%2520%257Bstring%257D%2520content%250A%2520%2520%2520*%2520%2540param%2520%257B%257Bname%253A%2520string%252C%2520optional%253A%2520boolean%257D%257D%2520props%250A%2520%2520%2520*%252F%250A%2520%2520fromXML(content%252C%2520props)%2520%257B%250A%2520%2520%2520%2520this.type%2520%253D%2520props.name%253B%250A%2520%2520%2520%2520this.desc%2520%253D%2520content%253B%250A%2520%2520%257D%250A%257D%26input1%3Dimport%2520%257BType%257D%2520from%2520'.%252Finput0'%253B%250A%250Aconst%2520t%2520%253D%2520new%2520Type()%253B%250At.fromXML('Hello%2520world'%252C%2520%257B%2520name%253A%2520'test'%252C%2520optional%253A%2520false%2520%257D)%253B%250Aconsole.log(t.type)%253B%26conformanceConfig%26externs%3Dconst%2520console%2520%253D%2520%257B%257D%253B%250A%252F**%250A%2520*%2520%2540param%2520%257B...*%257D%2520args%250A%2520*%252F%250Aconsole.log%2520%253D%2520function(args)%2520%257B%257D%253B%250A%250A%252F**%2520%2540const%2520*%252F%250Avar%2520typal%2520%253D%2520%257B%257D%253B%250A%252F**%250A%2520*%2520%2540typedef%2520%257B%257B%2520type%253A%2520string%252C%2520desc%253A%2520string%2520%257D%257D%250A%2520*%252F%250Atypal.Type%253B%250A%250A%250A%252F**%250A%2520*%2520%2540record%2520%257B%257B%2520type%253A%2520string%252C%2520desc%253A%2520string%2520%257D%257D%250A%2520*%252F%250Atypal.TypeAsRecord%2520%253D%2520class%2520%257B%250A%2520%2520constructor()%2520%257B%250A%2520%2520%2520%2520%252F**%2520%2540type%2520%257Bstring%257D%2520*%252F%250A%2520%2520%2520%2520this.type%253B%250A%2520%2520%2520%2520%252F**%2520%2540type%2520%257Bstring%257D%2520*%252F%250A%2520%2520%2520%2520this.desc%253B%250A%2520%2520%257D%250A%257D%253B%250A%26refasterjs-template%26includeDefaultExterns%3Dtrue%26CHECK_TYPES%3Dtrue%26MISSING_PROPERTIES%3Dtrue%26TRANSPILE%3Dtrue%26CLOSURE_PASS%3Dtrue%26PRESERVE_TYPE_ANNOTATIONS%3Dtrue%26PRETTY_PRINT%3Dtrue

**Comment by brad4d** [comment]
The compiler should not allow you to say `@extends {typedefname}` on an ES6 class.
I'll file a separate issue for that.

@zavr-1 I believe you can resolve your problem by changing your code to be something like this.

```javascript
// externs
/** @const */
var typal = {};
/**
 * @record
 */
typal.Type = class {
  constructor() {
    /** @type {string} */
    this.type;
    /** @type {string} */
    this.desc;
  }
};
```

```javascript
// Type.js
/**
 * A representation of a type.
 * @implements {typal.Type}
 */
export default class Type {
  constructor() {
    /** @type {string} */
    this.type = '';
    /** @type {string} */
    this.desc = '';
  }

  /**
   * @param {string} content
   * @param {{name: string, optional: boolean}} props
   */
  fromXML(content, props) {
    this.type = props.name;
    this.desc = content;
  }
}
```

Please update this issue to let us know if that works for you.
Thanks.

**Comment by zavr-1** [comment]
hi yeah i've figured it out I could do that thank you, did something like that, please feel free to close this. 
```js
   /**
     * The name of the type.
     * @type {?string}
     */
    this.name = null
    /** @type {?string} */
    this.type = null
```

**Comment by brad4d** [comment]
@zavr-1 
I'm glad you've found a solution.
