### ISSUE TITLE
Add note about transpilation to WHITESPACE_ONLY docs

### ISSUE THREAD

**Issue by brad4d** [google/closure-compiler#3320]
See also #3315 

Compilation level docs don't point out that even in WHITESPACE_ONLY  mode transpilation will happen if `language_out != language_in`.

https://developers.google.com/closure/compiler/docs/compilation_levels

**Comment by brad4d** [comment]
Created internal issue http://b/130164161

**Comment by vishwanathd11** [comment]
This can be closed now. Comment is already incorporated in docs.
