### ISSUE TITLE
Error: Modules now detected as both CommonJS and ES6

### ISSUE THREAD

**Issue by ChadKillingsworth** [google/closure-compiler#3324]
As of the latest release, my projects are getting multiple errors such as:

`A file cannot be both a CommonJS module and an ES6 module.`

git bisect points to 0393c80ca01b6b861376dad7f91043a38bb37dc0

**Comment by brad4d** [comment]
Created internal issue http://b/130219932

**Comment by brad4d** [comment]
@ChadKillingsworth can you provide a minimal repro?

**Comment by ChadKillingsworth** [comment]
I'm just going to assign this to myself. It's just way easier to step through code with a real project - and at that point it's probably easier to make a fix than create a minimal repo.

**Comment by brad4d** [comment]
Thanks, @ChadKillingsworth . Sorry about the breakage.
I asked the breaking commit's author, @jplaisted, about this hoping he'd immediately see what the problem was, but no such luck.
