### ISSUE TITLE
the setter parameter is deleted, which leads to the error

### ISSUE THREAD

**Issue by blooddy** [google/closure-compiler#3326]
the setter parameter is deleted, which leads to the error: ```SyntaxError: Setter must be exactly one formal parameter.```

input:
```javascript
class A {

		/**
		 * @public
		 * @abstract
		 */
		get [ 'prop' ]() {}

		set [ 'prop' ]( value ) {}


}
window[ 'A' ] = A;
```
output:
```javascript
'use strict';
class a {
  get ["prop"]() {
  }
  set ["prop"]() {
  }
}
window.A = a;
```

**Comment by concavelenz** [comment]
This is trivially reproducible:

https://closure-compiler-debugger.appspot.com/#input0%3D%252F**%2520%2540unrestricted%2520%2540suppress%2520%257BcheckTypes%257D%2520*%252F%250Aclass%2520A%2520%257B%250A%250A%2509%2509%252F**%250A%2509%2509%2520*%2520%2540public%250A%2509%2509%2520*%252F%250A%2509%2509get%2520%255B%2520'prop'%2520%255D()%2520%257B%257D%250A%250A%2509%2509set%2520%255B%2520'prop'%2520%255D(%2520value%2520)%2520%257B%257D%250A%250A%250A%257D%250Awindow%255B%2520'A'%2520%255D%2520%253D%2520A%253B%26input1%26conformanceConfig%26externs%26refasterjs-template%26CHECK_TYPES%3Dtrue%26REMOVE_UNUSED_VARIABLES%3Dtrue%26CLOSURE_PASS%3Dtrue%26PRETTY_PRINT%3Dtrue

**Comment by lauraharker** [comment]
Created internal issue http://b/130353464
