### ISSUE TITLE
es2018 class properties compile error

### ISSUE THREAD

**Issue by blooddy** [google/closure-compiler#3339]
```javascript
class A {
prop=1;
}
```
```javascript
class A {
['asd']=1;
}
```
output:
```
JSC_PARSE_ERROR: Parse error. '(' expected at line 3 character 11
['generic']=1;
```
https://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540compilation_level%2520ADVANCED_OPTIMIZATIONS%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%2540language_out%2520ECMASCRIPT_2018%250A%252F%252F%2520%2540formatting%2520pretty_print%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250A%252F%252F%2520ADD%2520YOUR%2520CODE%2520HERE%250Aclass%2520A%2520%257B%250A%255B'generic'%255D%253D1%253B%250A%257D

**Comment by brad4d** [comment]
ES_2018 doesn't include class properties.
They're still in stage 3 of the TC39 process.
https://github.com/tc39/proposals/blob/master/README.md
See "Class Public Instance Fields & Private Instance Fields"

We expect them to be in ES_2020, and plan to add support for them then.

**Comment by blooddy** [comment]
> ES_2018 doesn't include class properties.
> They're still in stage 3 of the TC39 process.
> https://github.com/tc39/proposals/blob/master/README.md
> See "Class Public Instance Fields & Private Instance Fields"
> 
> We expect them to be in ES_2020, and plan to add support for them then.

but in chrome, the properties are already working!

**Comment by brad4d** [comment]
The fact that they're working in Chrome is one of the reasons we expect them to be added to the standard in ES_2020. The TC39 process requires working implementations of a feature before making it part of the standard.

The closure-compiler team's goal is to follow the standard rather than any particular browser implementation, even Google's own.

FWIW, I'm rather anxious to add support for these. I feel they're long overdue.

**Comment by blooddy** [comment]
@brad4d, it makes me cry, because for our project it is exactly the sugar that we need in a mug of bitter coffee.

**Comment by xmedeko** [comment]
Duplicate of #2731
