### ISSUE TITLE
ECMASCRIPT_2015 output omits variable function parameters used by 'arguments'

### ISSUE THREAD

**Issue by kdkd** [google/closure-compiler#3348]
```
Closure Compiler (http://github.com/google/closure-compiler)
Version: v20190415
Built on: 2019-04-17 17:05
```

Example source:

```
class c {
    /**
     * @param {...*} a
     */
    Fire(a) {
        console.log(arguments.toString());
    }
}

var x = new c();
x.Fire(1,2,3,4)
```

Using ECMASCRIPT5 for language_out produces valid code:

```
# java -jar compiler.jar --language_out ECMASCRIPT5 --language_in ECMASCRIPT6 --compilation_level  ADVANCED_OPTIMIZATIONS --js bug.js --js_output_file out.js

function a(){}a.prototype.a=function(b){console.log(arguments.toString())};(new a).a(1,2,3,4);
```

Using ECMASCRIPT_2015 omits the function parameters(1,2,3,4):

```
# java -jar compiler.jar --language_out ECMASCRIPT_2015 --language_in ECMASCRIPT6 --compilation_level  ADVANCED_OPTIMIZATIONS --js bug.js --js_output_file out.js

'use strict';class a{a(){console.log(arguments.toString())}}(new a).a();
```

Changing Fire to use the spread operator does work, but generates kind of silly code (converts to an array then back to arguments)

```
    Fire(...a) {
        console.log(...a);
    }
```
becomes:
```
'use strict';console.log(...[1,2,3,4]);
```

**Comment by blickly** [comment]
Created internal issue http://b/131256934

**Comment by NotWearingPants** [comment]
I believe this is the intended behavior, no? Deleting the unused argument reduces the size of the code.

**Comment by kdkd** [comment]
In my opinion, using 'arguments' within the function means that all arguments are potentially used. Switching from --language_out ECMASCRIPT5 to --language_out ECMASCRIPT_2015 is changing the behavior of the compiled script, which feels wrong. With this behavior, you can't pass a variable number of arguments to another function that also accepts a variable number of arguments.

**Comment by lauraharker** [comment]
@kdkd looks like this was fixed back in May by https://github.com/google/closure-compiler/commit/71660dfaa6a1c74b1bedf4694e37177cccc8df21. I can reproduce your original example with v20190513 but not v20190528 or later versions. Now the compiled output is:

``` js
'use strict';class a{a(b){console.log(arguments.toString())}}(new a).a(1,2,3,4);
```
