### ISSUE TITLE
Comma operator is not correctly wrapped in () in object literals (computed keys and values)

### ISSUE THREAD

**Issue by sjrd** [google/closure-compiler#3358]
Comma operators in the computed keys or in the values of an object literal are not correctly printed back to JavaScript source. They miss appropriate surrounding parentheses, causing `ParseError`s. This happens even in whitespace-only mode.

Reproduction:
```js
// ==ClosureCompiler==
// @compilation_level WHITESPACE_ONLY
// @output_file_name default.js
// @language_out ECMASCRIPT_2015
// @formatting pretty_print
// ==/ClosureCompiler==

function foo() {
  let array = [];
  const x = {
    [(array.push(1), "foo")]: (array.push(2), 3),
    [(array.push(3), "bar")]: (array.push(4), "foobar")
  };
  console.log(array);
  console.log(x);
}

foo(); foo();
```
is compiled with the above options as:
```js
'use strict';
function foo() {
  let array = [];
  const x = {[array.push(1), "foo"]:array.push(2), 3, [array.push(3), "bar"]:array.push(4), "foobar"};
  console.log(array);
  console.log(x);
}
foo();
foo();
```
[Appspot link](https://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540compilation_level%2520WHITESPACE_ONLY%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%2540language_out%2520ECMASCRIPT_2015%250A%252F%252F%2520%2540formatting%2520pretty_print%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250Afunction%2520foo()%2520%257B%250A%2520%2520let%2520array%2520%253D%2520%255B%255D%253B%250A%2520%2520const%2520x%2520%253D%2520%257B%250A%2520%2520%2520%2520%255B(array.push(1)%252C%2520%2522foo%2522)%255D%253A%2520(array.push(2)%252C%25203)%252C%250A%2520%2520%2520%2520%255B(array.push(3)%252C%2520%2522bar%2522)%255D%253A%2520(array.push(4)%252C%2520%2522foobar%2522)%250A%2520%2520%257D%253B%250A%2520%2520console.log(array)%253B%250A%2520%2520console.log(x)%253B%250A%257D%250A%250Afoo()%253B%2520foo()%253B%250A)

Note the following problems:

* In a computed key: `[array.push(1), "foo"]` should be `[(array.push(1), "foo")]`
* In a value: `array.push(2), 3` should be `(array.push(2), 3)`

The problem can be reproduced
* with or without pretty-printing,
* in WHITESPACE_ONLY, SIMPLE_OPTIMIZATIONS and ADVANCED_OPTIMIZATIONS,
* tested with version v20190415

**Comment by brad4d** [comment]
Created internal issue http://b/131906929

**Comment by brad4d** [comment]
@sjrd thanks for this report.

Your first point is actually incorrect

> * In a computed key: `[array.push(1), "foo"]` should be `[(array.push(1), "foo")]`

For a computed key the entire contents of the square brackets will be treated as a single expression,
so the parentheses are not needed.

However, you're quite right about the second point being a problem

> * In a value: `array.push(2), 3` should be `(array.push(2), 3)`

Thanks for submitting a PR for this.
I'll assign it to someone shortly.

**Comment by sjrd** [comment]
Thank you for the very quick follow up.

> For a computed key the entire contents of the square brackets will be treated as a single expression, so the parentheses are not needed.

At least v8, through node, seems to disagree with that assessment:
```js
$ node -v
v10.12.0
$ node
> ({[1,2]: "foo"})
({[1,2]: "foo"})
    ^

SyntaxError: Unexpected token ,

> ({[(1,2)]: "foo"})
{ '2': 'foo' }
>
```
I'm currently on mobile, so I can't double check on another JS engine right now. But I think I had observed something similar with Firefox.

I also believe the spec does not allow a comma operator in a computed property key. See http://www.ecma-international.org/ecma-262/9.0/index.html#prod-ComputedPropertyName : `ComputedPropertyName` wants an `AssignmentExpression`, which does not admit `,`.

Do you agree?

**Comment by brad4d** [comment]
Yep, looks like you're right.
Thanks for taking the time to point out the appropriate part of the spec.
That saved me having to look it up myself.
