### ISSUE TITLE
CommonJS compatibility does not work as expected

### ISSUE THREAD

**Issue by zavr-1** [google/closure-compiler#3360]
The compiler puts each commonJs module into `default` property of the imported object.
```js
// ecma
import commonJs from './common-js'

console.log('requiring a common js from ecma:')
console.log(commonJs)
```

<table>
<tr><th>CommonJS From ECMA</th><th>CommonJS From CommonJS</th></tr>
<td>

```js
// common-js.js
const commonJs2 = require('./common-js2')

module.exports = () => {
  console.log('default common js export')
}
module.exports['named'] = () => {
  console.log('named common js export')
}

console.log('requiring a ' +
'common js from common js:')
console.log(commonJs2)
```
</td><td>

```js
// common-js2.js
module.exports = () => {
  console.log('default common js ' 
+ 'export2')
}
module.exports['named'] = () => {
  console.log('named common js ' 
+ 'export2')
}
```
</td></tr></table>

Run the compiler
```fs
java -jar /Users/zavr/node_modules/google-closure-compiler-java/compiler.jar \
--compilation_level ADVANCED --language_out ECMASCRIPT_2017 --formatting PRETTY_PRINT \
--process_common_js_modules --entry_point \
example/commonjs/index.js --module_resolution NODE --js \
example/commonjs/index.js example/commonjs/common-js.js example/commonjs/common-js2.js
```

Get the output

```js
'use strict';
var a = () => {
  console.log("default common js export2");
};
a.named = () => {
  console.log("named common js export2");
};
var b = {default:() => {
  console.log("default common js export");
}};
b.default.named = () => {
  console.log("named common js export");
};
console.log("requiring a common js from common js:");
console.log(a);
console.log("requiring a common js from ecma:");
console.log(b);
```
Execute the output
```jsx
requiring a common js from common js:
{ [Function: a] named: [Function] }
requiring a common js from ecma:
{ default: { [Function: default] named: [Function] } }
```
This does not make sense. I shouldn't write `.default` as confirmed here https://github.com/google/closure-compiler/issues/3308. When it comes to Babel-compiled modules, it's a nightmare. Babel exports { default: code } itself, so the currently closure-compatible code becomes

```js
import erte from '@a-la/fixture-babel'

console.log(erte.default.default())
console.log(erte.default.c())
console.log(erte.default.b())
```

And if you actually try to execute in with babel, you get
```
console.log(_.default.default.default());
                              ^

TypeError: Cannot read property 'default' of undefined
```

Developers developers developers developers
Babel Babel Babel Babel
Default Default Default Default

**Comment by brad4d** [comment]
Created internal issue http://b/132070697

**Comment by ChadKillingsworth** [comment]
When you say "Try to execute with Babel", what do you mean?

The output you posted looks correct. I realize that the output is different than Babel, but that's intended.

**Comment by zavr-1** [comment]
@ChadKillingsworth but you said in the last post this is incorrect. How can exporting a module as `{ default: module }` be correct? In case of babel that becomes `{ default: { default: module } }` because with its transpilation achieves:
```
"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = exports.b = exports.c = void 0;

/**
 * A function that returns `erte`.
 */
const erte = () => {
  return 'erte';
};
/**
 * A function that returns `c`.
 */


const c = () => {
  return 'c';
};
/**
 * A function that returns `b`.
 */


exports.c = c;

const b = () => {
  return 'b';
};

exports.b = b;
var _default = erte;
exports.default = _default;
```
Therefore it's not correct the way it's been implemented!!! 
Because if I wanted to use babel for my dev, i.e., runtime, testing, I would need to do just `import erte from 'erte'; erte()`. When I now want to use closure compiler I have to write `import erte from 'erte'; erte.default.default()` this breaks the compatibility between the two! even if I don't use babel, I still have to do `import commonJs from 'commonJs'; commonJs.default('test'); commonJs.default.named('test')` and for sure it's not correct

**Comment by zavr-1** [comment]
the compiler should call `console.log(a.defaut);` not `console.log(a)`!!! and in case of babel, there should logic to check it is an `_esModule` and call `a.default.default` or flatten the exported default! cheers

**Comment by ChadKillingsworth** [comment]
Closure Compiler transpiles and converts modules to scripts. It's not intended that the output be consumed as a module with proper imports or exports.

We've just begun discussing what output module support would look like. However, support will be concentrated on what is native to browsers and nodejs. Babel interop is really not a focus.

**Comment by zavr-1** [comment]
@ChadKillingsworth please don't get me wrong you're in denial, the GCC currently breaks the commonjs compatibility and you don't want to accept im. I'm sorry I don't want to be rude but you're closing a real issue. I'm not talking about Babel support, I don't care for babel support I hate babel. I care for common-js compatibility. I'm telling you that I should not have to write
```js
import commonJs from 'commonJs'
commonJs.default()
commonJs.default.name()
```
I should be able to write 
```js
import commonJs from 'commonJs'
commonJs()
commonJs.name()
```
but it does not work!!! Without the advanced compilation, it works correctly. https://github.com/google/closure-compiler/issues/3363 here you can see the module is called as `console.log(module$a_or_b.default);`, but in advanced mode, it is `console.log(module$a_or_b.default);`.
What does it mean converts modules to scripts? If I want to import a module I should be able to do it regardless. There are tons of CommonJS modules that should just be able to be imported normally. It's not difficult. 

@brad4d could you please comment on that? Where an i wrong? It used to work fine until April's release. Without this, the compiler is limited to pure ES6 or google required modules. Although I'm happy that it moves the scene forward, but it's definitely a bug at the moment.

**Comment by brad4d** [comment]
#3363 definitely looks like a problem because no ES6 modules are involved at all, yet 'default' is creeping in somehow.

I'll try to clarify Chad's statement:
> Closure Compiler transpiles and converts modules to scripts. It's not intended that the output be consumed as a module with proper imports or exports.

It sounded like you were attempting to somehow treat the output of the compiler as a module and import it somewhere. That is not supported. If that's not what you were doing, then I really don't know what you mean by "Try to execute with Babel". Perhaps you could explain.

I am surprised to hear that this is a regression in behavior. The way @ChadKillingsworth described it to me yesterday it seemed like the only way ES6 import of a CommonJS module really could work, because ES6 has different export/import semantics. He is the primary maintainer of the CommonJS logic, but I suppose he could have been mistaken here, or else he had to change the interop behavior from what it was to fix some other problem.

I'm sorry you're feeling frustrated, but I assure you that our responses on this issue are only concerned with establishing whether this is a bug or not and explaining the behavior of the compiler. Module transpilation is a complicated thing to get right, and we would appreciate it if you could show more understanding an patience, especially if we're getting something wrong.

**Comment by concavelenz** [comment]
Do we know when this broke?

**Comment by concavelenz** [comment]
Do we know when this broke?

**Comment by ChadKillingsworth** [comment]
I haven't run Git bisect yet, but it's fairly recent. This would break all
of my projects.

**Comment by jplaisted** [comment]
The only thing I've done recently around this is https://github.com/google/closure-compiler/commit/92541e5239c9047b640d6cce8755fb9c155aff01. Maybe that will help your bisect. I don't see it as obviuosly breaking anything, but I would not rule it out.

In either case maybe the real action item here after this is fixed is to 

- Add unit tests to ensure future regressions don't happen
- Make this code less brittle by ensuring ES and CJS modules have some common code path (right now they work by coincidence of that they happen to rewrite in similar ways)

**Comment by jplaisted** [comment]
Wibbly wobbly time stuff... these posts are now out of order...

**Comment by ChadKillingsworth** [comment]
git bisect blames 0393c80ca01b6b861376dad7f91043a38bb37dc0

There are some commonJS integration tests, but looks like we are indeed missing some module interop integration tests: https://github.com/google/closure-compiler/blob/master/test/com/google/javascript/jscomp/CommonJSIntegrationTest.java

**Comment by brad4d** [comment]
@ChadKillingsworth can you provide such tests, since you're the one who knows how the CommonJS code is supposed to work?

**Comment by jplaisted** [comment]
I believe https://github.com/google/closure-compiler/commit/ec31e72924d7dbee7ecb0fa4abe75b2043814672 has fixed ES importing CJS. The other way may still not be fixed.
