### ISSUE TITLE
Array.prototype.fill requires minimum 1 argument

### ISSUE THREAD

**Issue by brianfreud** [google/closure-compiler#3361]
In advanced mode, the following will not compile:

`let makeSequentialIntFilledArray = (size = 0, init = 0) => Array(size).fill().map(() => init++);`

It throws a warning about Array.prototype.fill requiring at least 1 argument:

JSC_WRONG_ARGUMENT_COUNT: Function Array.prototype.fill: called with 0 argument(s). Function requires at least 1 argument(s) and no more than 3 argument(s). at line 2 character 59
let makeSequentialIntFilledArray = (size = 0, init = 0) => Array(size).fill()...

As I read it, the spec only says that arguments 2 and 3 are optional; it never states whether argument 1 is optional or required:

> _The fill method takes up to three arguments value, start and end.
> NOTE 1 The start and end arguments are optional with default values of 0 and the length of the this object. If start is negative, it is treated as length+start where length is the length of the array. If end is negative, it is treated as length+end._
(https://www.ecma-international.org/ecma-262/6.0/#sec-array.prototype.fill)

Testing with both Chrome v 71.0.3578.98 and Firefox v 64.0, 

`let makeSequentialIntFilledArray = (size = 0, init = 0) => Array(size).fill().map(() => init++);`

works perfectly, just as much as

`let makeSequentialIntFilledArray = (size = 0, init = 0) => Array(size).fill(1).map(() => init++);`

but only the latter is accepted as valid by the closure compiler, even though both _*should*_ be.  In the former version, the array passed to map() is simply an array of size 'size' filled with undefined, while the latter version passes map() an array of size 'size' filled with '1'.  map() isn't actually *using* the contents of the passed array.  fill() doesn't support using a function to iterate values, but fill().map() allows you to:

```
For makeSequentialIntFilledArray(10):

Array(size).fill(init++) // [0, 0, 0, 0, 0, 0, 0, 0, 0, 0] *not what we want*
Array(size).fill(() => init++); // [ƒ, ƒ, ƒ, ƒ, ƒ, ƒ, ƒ, ƒ, ƒ, ƒ] *not what we want*
Array(size).fill((x) => init++); // // [ƒ, ƒ, ƒ, ƒ, ƒ, ƒ, ƒ, ƒ, ƒ, ƒ] *not what we want*
Array(size).map(() => init++); // [empty × 10] *not what we want*
Array(size).map((x) => init++); // [empty × 10] *not what we want*
Array(size).fill(1).map(() => init++); // [0, 1, 2, 3, 4, 5, 6, 7, 8, 9] *works, and closure compiler friendly*
Array(size).fill().map(() => init++); // [0, 1, 2, 3, 4, 5, 6, 7, 8, 9] *works, not closure compiler friendly*
Array(size).fill().map(x => init++); *works, not closure compiler friendly*
```

I agree that there may not be many use cases for filling an array with undefined values, but this happens to be one where filling it with undefined is just as good as filling it with any particular value (and it's 1 byte shorter code, if we're code golfing.)

**Comment by brad4d** [comment]
@brianfreud Thanks for the detailed explanation of why you'd like this change.

I have to disagree with your reading of the spec, though.
All arguments for methods are required unless specifically indicated otherwise.
I don't have time to look up where this is explicitly stated, and maybe it isn't,
but that is the only way of reading the spec that makes sense to me.
There isn't a notation in the spec to indicate that a parameter is required, so that must be the default.

The spec is our primary guide here, so I don't think we should change our externs to allow the parameter to be dropped. Saving one byte for the intended use-case doesn't balance out catching the more likely case that leaving out the argument was a typo.
