### ISSUE TITLE
@template fails in generic functions with inline annotations

### ISSUE THREAD

**Issue by alexchandel** [google/closure-compiler#3362]
Template parameters are wrongly ignored by the compiler.

## Expected results

The following two definitions should pass the compiler:

```js
/**
 * @type {function(!Array<T>, function(T):*): !Map}
 * @template T
 */
function mparts (input, f) {
  let bins = new Map()
  for (let item of input) {
    let key = f(item)
    if (!bins.has(key)) bins.set(key, new Set())
    bins.get(key).add(item)
  }
  return bins
}
```
or

```js
/**
 * @template T
 */
function /** !Map */ mparts (/** !Array<T> */ input, /** function(T):* */ f) {
  let bins = new Map()
  for (let item of input) {
    let key = f(item)
    if (!bins.has(key)) bins.set(key, new Set())
    bins.get(key).add(item)
  }
  return bins
}
```

## Actual results:

Closure compiler fails to substitute the template parameter:

```
foo.js:14: WARNING - Bad type annotation. Unknown type T
 * @type {function(!Array<T>, function(T):*): !Map}
                          ^

foo.js:14: WARNING - Bad type annotation. Unknown type T
 * @type {function(!Array<T>, function(T):*): !Map}
                                       ^
```

or outright fails to recognize it has been used at all:

```
foo.js:14: WARNING - Misplaced template annotation. The template variable is unused. Please remove the @template annotation.
function /** !Map */ mparts (/** !Array<T> */ input, /** function(T):* */ f) {
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

## Workaround:

The following excessively verbose declaration passes the compiler:
```js
/**
 * @param {!Array<T>} input
 * @param {function(T):*} f
 * @return {!Map}
 * @template T
 */
function mparts (input, f) {
  let bins = new Map()
  for (let item of input) {
    let key = f(item)
    if (!bins.has(key)) bins.set(key, new Set())
    bins.get(key).add(item)
  }
  return bins
}
```

Related open issues: #1063 (annotations fail for anonymous functions)

**Comment by brad4d** [comment]
The workaround isn't a workaround. It is the preferred way to annotate a function definition.

The other 2 cases don't work because `@template` was never intended to work with them.
Sorry.

**Comment by alexchandel** [comment]
It should be, then.  Please consider this a feature-request and re-open.

**Comment by alexchandel** [comment]
In particular, requiring `@param` involves manual duplication of the parameter names, whereas `@type` contains enough information to completely construct these, without multiple `@param` entries or retyping of parameter names.

**Comment by brad4d** [comment]
@alexchandel feel free to file a new issue phrased as a feature request
