### ISSUE TITLE
SIMPLE_OPTIMIZATIONS breaks code emited by uhc's js backend

### ISSUE THREAD

**Issue by blickly** [google/closure-compiler#337]
This issue was imported from Closure Compiler's previous home at http://closure-compiler.googlecode.com

The original discussion is archived at:
http://blickly.github.io/closure-compiler-issues/#658

**Comment by Dominator008** [comment]
@DanielWaterworth is this still the case?

**Comment by DanielWaterworth** [comment]
Wow, this was a while ago. I don't know and it would take some effort to find out.

**Comment by concavelenz** [comment]
Reopen if info becomes available
