### ISSUE TITLE
Update window.scroll signature to accept an options object

### ISSUE THREAD

**Issue by ciampo** [google/closure-compiler#3371]
There is an alternative way of using `window.scroll` (and `window.scrollTo`) that allows to pass an object instead of the x and y coordinates.

See the [MDN docs](https://developer.mozilla.org/en-US/docs/Web/API/Window/scroll) for reference.

A change in the externs is needed around these lines:

https://github.com/google/closure-compiler/blob/964833f1af60a733cc6821f6c0737ac18fba9339/externs/browser/w3c_css.js#L2099-L2113

I'd be happy to help with a PR, if given some assistance in writing the externs correctly.

**Comment by mk0x9** [comment]
I can do it later.

**Comment by EatingW** [comment]
Created internal issue http://b/132449966.

**Comment by mk0x9** [comment]
@EatingW 

Looks like Window methods moveTo, moveBy, resizeTo, resizeBy have been standardised according to [Extensions to the Window Interface](https://www.w3.org/TR/cssom-view/#extensions-to-the-window-interface). Should their definitions be moved from ie_dom.js to w3c_css.js?

https://github.com/google/closure-compiler/blob/2375110b30ccb83b0a550c8c3d46c526e3896d62/externs/browser/ie_dom.js#L404-L418

https://github.com/google/closure-compiler/blob/2375110b30ccb83b0a550c8c3d46c526e3896d62/externs/browser/ie_dom.js#L442-L456

**Comment by EatingW** [comment]
I think moving them should be fine as long as we don't break anyone depending on the externs being in a particular file.

However, it should be a separate PR from this issue which addresses scroll and scrollTo, so that I can do some internal testing separately to make sure that we are not breaking anything.
