### ISSUE TITLE
Issues with numeric literal shortening - unnecessary zeros

### ISSUE THREAD

**Issue by blickly** [google/closure-compiler#338]
This issue was imported from Closure Compiler's previous home at http://closure-compiler.googlecode.com

The original discussion is archived at:
http://blickly.github.io/closure-compiler-issues/#279

**Comment by Dominator008** [comment]
Seems to have been fixed.

Input:
```js
a=0.1;
b=0.01;
c=0.001;
d=0.0001;
e=0.00001;
```
Output:
```js
a=.1;b=.01;c=.001;d=1E-4;e=1E-5;
```
No unnecessary zero was kept / added.
