### ISSUE TITLE
Parameter mismatch warning when type-casting parameters

### ISSUE THREAD

**Issue by l1bbcsg** [google/closure-compiler#3398]
I'm not entirely sure if this is a bug or not, but it's an undocumented change in behaviour that was introduced in v20190215. Newer versions also produce the warning.

This particular syntax of type casting arguments is not mentioned in the docs, but evidently it works.

My examples are artificial and redundant, but we had real code that required type casts in params.
I know workarounds and ways to fix this, but please still advise on the underlying issue.

Running Java version on MacOS.

## Example

`param-cast.js`:

```js
/**
 * @enum {string}
 */
const Item = {
	FOO: 'foo',
	BAR: 'bar',
	BAZ: 'baz'
};


/**
 * @type {!Object<Item, number>}
 */
const a = {
	'foo': 1,
	'bar': 2,
	'baz': 3
};


Object.keys(a).forEach((/** @type {Item} */ maybeItem) => {
	/**
	 * @type {Item}
	 */
	const strictlyItem = maybeItem;
});

```

## Old behaviour

```bash
npm i google-closure-compiler@20190121

npx google-closure-compiler --js param-cast.js --compilation_level ADVANCED_OPTIMIZATIONS --checks-only
```

Result: No warnings

## New behaviour

```bash
npm i google-closure-compiler@20190215

npx google-closure-compiler --js param-cast.js --compilation_level ADVANCED_OPTIMIZATIONS --checks-only
```

Result:

```
param-cast.js:25: WARNING - actual parameter 1 of Array.prototype.forEach does not match formal parameter
found   : function(Item<string>): undefined
required: (function(string, number, Array<string>): ?|null)
Object.keys(a).forEach((/** @type {Item} */ item) => {
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

0 error(s), 1 warning(s), 100.0% typed
```

## Notes

It seems like the previous behaviour of this:

```js
(/** @type {FOO} */ param) => {
	// ...
}
```

Was the equivalent of this:

```js
(param) => {
	param = /** @type {FOO} */ (param);
	// ...
}
```

But the new is the equivalent of this:

```js
/**
 * @param {FOO} param
 */
(param) => {
	// ...
}
```

I believe the old behaviour was more correct since type casting notation casted the parameter and did not change the function signature.

Was this an intended change?

**Comment by lauraharker** [comment]
This is intended, and this particular syntax was never intended to work as a type cast. Writing `(/** @type {string} */ s) => {}` has always been equivalent to `(/** string */ s) => {}`. See the documentation of 'inline parameter annotations' [here](https://github.com/google/closure-compiler/wiki/Annotating-JavaScript-for-the-Closure-Compiler#param-type-varname-description)

v20190215 fixed a type inference bug around inline parameter annotations on function literals passed  as arguments to a function. This bug made 
``` js
someFunction((/** @type {FOO} */ param) => {
	// ...
})
```

equivalent to

``` js
someFunction((originalParam) => {
	var param = /** @type {FOO} */ (/** @type {?} */ (originalParam));
	// ...
})
```

Note that this was more unsafe than a regular type cast. The compiler validates that normal type casts are to a supertype or a subtype. However, this bug let you 'cast' the parameter to any unrelated type, like number -> string.

The bug only affected function literals passed as parameters. For example, this seemingly equivalent code threw a type error even before v20190215.
``` js
/**
 * @enum {string}
 */
const Item = {
	FOO: 'foo',
	BAR: 'bar',
	BAZ: 'baz'
};


/**
 * @type {!Object<Item, number>}
 */
const a = {
	'foo': 1,
	'bar': 2,
	'baz': 3
};

const callback = (/** @type {Item} */ maybeItem) => {
	/**
	 * @type {Item}
	 */
	const strictlyItem = maybeItem;
};

Object.keys(a).forEach(callback);
```

This change should have been in the v201090215 release notes. I apologize for forgetting to include it.
