### ISSUE TITLE
Small typo in the Wiki

### ISSUE THREAD

**Issue by MaximYaskov** [google/closure-compiler#3403]
(function(){%output%)).call(this);

**Comment by tjgq** [comment]
I'm assuming this was in https://github.com/google/closure-compiler/wiki/FAQ#when-using-advanced-optimizations-closure-compiler-adds-new-variables-to-the-global-scope-how-do-i-make-sure-my-variables-dont-collide-with-other-scripts-on-the-page. I've fixed it.

**Comment by MaximYaskov** [comment]
And here too https://github.com/google/closure-compiler/wiki/Flags-and-Options

**Comment by tjgq** [comment]
Thanks. The flags page in the wiki is automatically generated from source. I will submit a change internally to fix the source, and the wiki will be updated the next time we do a release.
