### ISSUE TITLE
Latest download links are broken

### ISSUE THREAD

**Issue by alberanid** [google/closure-compiler#3409]
As of 2019-05-31, the following links return a 404 error:
* https://dl.google.com/closure-compiler/compiler-latest.zip
* https://dl.google.com/closure-compiler/compiler-latest.tar.gz

**Comment by Denyllon** [comment]
Hello @alberanid ,

Thank you for reporting the issue.
The problem is caused by the fact, that `closurecompiler` npm package is currently deprecated, but not removed from `package.json` after replacing it with `google-closure-compiler-js`.

Kind regards,
Daniel Studencki

**Comment by EatingW** [comment]
Looks like it has been fixed? Could you confirm? The links work for me now.

**Comment by alberanid** [comment]
I can confirm that now the links are working. Closing the issue.
Anyway, packages that have a dependency on **closurecompiler** should switch to **google-closure-compiler-js**

**Comment by colin0117** [comment]
This is happening again - both those links in the OP are giving 404s.

**Comment by ashish-r** [comment]
Getting 404 again

**Comment by brad4d** [comment]
We aren't publishing these 2 binaries anymore. 

Please see the explanation at https://github.com/google/closure-compiler/issues/3662#issuecomment-675524506
