### ISSUE TITLE
Support TypeScript bounded generic types notation

### ISSUE THREAD

**Issue by ikabirov** [google/closure-compiler#3410]
We use TypeScript as type checker for Closure Compiler project. Typescript allows declare bounded generics in JSDoc. But it is not compatible with Closure Compiler ("WARNING - Bad type annotation.")

Is it possible to just basic template type? E.g. parse
```
/**
 * @param {T} obj
 * @template {{id: string}} T
 */
function hello(obj) {
	console.log(obj.id)
}
```
as
```
/**
 * @param {T} obj
 * @template T
 */
function hello(obj) {
	console.log(obj.id)
}
```

**Comment by EatingW** [comment]
Created http://b/134435444 as a feature request.
