### ISSUE TITLE
java.lang.ClassCastException in JS Version

### ISSUE THREAD

**Issue by ChadKillingsworth** [google/closure-compiler#3414]
Yesterday's push started triggering build failures in the open source JS version: https://travis-ci.org/google/closure-compiler-npm/jobs/541539222#L1566

**Comment by blickly** [comment]
Is there a way to repro the travis failures locally?  I tried but got unrelated failures trying to `yarn test` locally.

Looking at the changes that landed on June 4, I lean toward suspecting https://github.com/google/closure-compiler/commit/d69699d47d57981bd129c754360c3a965e4e7b2f, but that's not very helpful without some way to test the theory.

**Comment by blickly** [comment]
Created internal issue http://b/134623076

**Comment by ChadKillingsworth** [comment]
You should be able to follow these steps:

1. clone the repo
2. update the git submodule
3. checkout the compiler submodule to the desired commit
4. in the root, run `yarn install`
5. `yarn clean`
6. `yarn build`
7. `yarn test`

If that doesn't work - ping me on hangouts with exactly the error you are seeing.

**Comment by ChadKillingsworth** [comment]
Looking at the tests that failed, this seems to be triggered by passing input source maps to the compilation.

**Comment by blickly** [comment]
OK, thanks for the repro steps. I think I was having trouble with the `yarn build` step, but I'll sync up with you once I get in to the office on how to repro consistently.

Taking a different tack, I was able to verify that rolling back truth didn't fix the travis errors, but that rolling back cf137a239ad8a23b82c4885d2b4125323c1738ee change did:
https://travis-ci.org/google/closure-compiler/builds/542534423

I'll loop in @nreid260 as well

**Comment by blickly** [comment]
OK, I think the issue was that I needed to remove the `jscomp.js` file to force rebuild of that file.  After that, I can repro the issue the same as travis

**Comment by blickly** [comment]
Submitted a rollback to avoid this issue in https://github.com/google/closure-compiler/commit/09e3df7dea53bf82a83dbedd758cd14bfbaf417e
