### ISSUE TITLE
opt_distance parameter in function definition for History.prototype.back

### ISSUE THREAD

**Issue by Andrew-Cottrell** [google/closure-compiler#3418]
In pull request https://github.com/google/closure-compiler/pull/3330, the `opt_distance` parameter was included in the function definition for `History.prototype.back`

https://github.com/google/closure-compiler/blob/v20190528/externs/browser/html5.js#L3154

    /**
     * Goes back one step in the joint session history.
     * If there is no previous page, does nothing.
     *
     * @return {undefined}
     */
    History.prototype.back = function(opt_distance) {};

This causes the following warning when calling `History.prototype.back` with zero arguments

    WARNING - [JSC_WRONG_ARGUMENT_COUNT]
    Function History.prototype.back: called with 0 argument(s).
    Function requires at least 1 argument(s) and no more than 1 argument(s).

**Comment by realityforge** [comment]
That was my fault. I should have completely removed the opt_distance parameter. I will submit a PR to do just that.

**Comment by brad4d** [comment]
internal issue created http://b/135115388

**Comment by lauraharker** [comment]
4877e4fb9d3def6b827e8c45b54003fe4dac01cc fixed the typing to make this parameter optional again.

https://github.com/google/closure-compiler/pull/3419 might still land to completely remove this parameter, but I believe this particular issue can be closed.
