### ISSUE TITLE
Optimize away anonymous functions used for local scope.

### ISSUE THREAD

**Issue by blickly** [google/closure-compiler#342]
This issue was imported from Closure Compiler's previous home at http://closure-compiler.googlecode.com

The original discussion is archived at:
http://blickly.github.io/closure-compiler-issues/#76

**Comment by Dominator008** [comment]
Should be fixed by https://github.com/google/closure-compiler/commit/ef9ff6433890d76eb9bc66148cc02c7dd0f96517. Besides, the original issue became too vague / broad during the discussion so I'm closing this.
