### ISSUE TITLE
Dynamic import cannot compile

### ISSUE THREAD

**Issue by HypnosNova** [google/closure-compiler#3420]
When using closure compiler to minify the js file, it throw an error when the code has dynamic import gramma.
![image](https://user-images.githubusercontent.com/7953802/59434985-3b357400-8e1f-11e9-8996-d46832b3ff3c.png)
How to solve it? Is it a bug or closure compiler doesn't support dynamic import?

**Comment by brad4d** [comment]
closure-compiler doesn't support dynamic import yet.
See #2770
