### ISSUE TITLE
Node.js core functions and variables are not recognized when type checking

### ISSUE THREAD

**Issue by chruxin** [google/closure-compiler#3433]
I'm trying to get closure compiler to type check some node scripts, but I'm running into some warnings that indicate the node core features are not recognized.

Example
```javascript
// test.js
const fs = require('fs');
const {promisify} = require('util');
const readFileAsync = promisify(fs.readFile);

console.log(__dirname);

module.exports = {};
```

Command
```
npx google-closure-compiler test.js --checks-only --warning_level VERBOSE --module_resolution NODE
```

Output
```
test.js:2: ERROR - [JSC_UNDEFINED_VARIABLE] variable require is undeclared
const fs = require('fs');
           ^^^^^^^

test.js:6: ERROR - [JSC_UNDEFINED_VARIABLE] variable __dirname is undeclared
console.log(__dirname);
            ^^^^^^^^^

test.js:8: ERROR - [JSC_UNDEFINED_VARIABLE] variable module is undeclared
module.exports = {};
^^^^^^

3 error(s), 0 warning(s)
```

These errors disappear once an externs.js file (like the one below) is included
```javascript
// externs.js
/**
 * @param {string} path
 */
function require(path) {};
/** @type {string} */
const __dirname = '';
/** @type {!Object} */
const module = {};
```
However, new errors occur:
```
test.js:3: WARNING - [JSC_POSSIBLE_INEXISTENT_PROPERTY] Property promisify never defined on ?
const {promisify} = require('util');
       ^^^^^^^^^

test.js:4: WARNING - [JSC_POSSIBLE_INEXISTENT_PROPERTY] Property readFile never defined on fs
const readFileAsync = promisify(fs.readFile);
                                   ^^^^^^^^

0 error(s), 2 warning(s), 60.0% typed
```

No matter what I do in externs.js, there's a warning telling me that `fs` is reassigned. I really would like to use `const` in the script when declaring `fs`. 😰

I also tried running the above commands with `--process_common_js_modules`, but got the following errors:
```
test.js:2: ERROR - [JSC_JS_MODULE_LOAD_WARNING] Failed to load module "fs"
const fs = require('fs');
           ^

test.js:3: ERROR - [JSC_JS_MODULE_LOAD_WARNING] Failed to load module "util"
const {promisify} = require('util');
                    ^

2 error(s), 0 warning(s)
```

How can I get closure compiler to type check node scripts? Is there anything I'm missing?

**Comment by lauraharker** [comment]
Created Google internal issue http://b/137762204

**Comment by lauraharker** [comment]
Using `--process_common_js_modules` is necessary to get the correct behavior. Otherwise the compiler treats your module as if it were just a regular script, and doesn't correctly rewrite requires and exports.

@ChadKillingsworth could you help out?

**Comment by rishipal** [comment]
Closing this issue as we do not have the resources to make this work for Node and the target for closure-compiler is browsers.

**Comment by icy0307** [comment]
I also encounter a similar issue, 
>  target for closure-compiler is browsers.

According to the [wiki](https://github.com/google/closure-compiler/wiki/JS-Modules)
> Closure Compiler recognizes several JS module systems, including:
[ES Modules](https://github.com/nzakas/understandinges6/blob/master/manuscript/13-Modules.md)
Common JS
[Closure-Library (goog.module)](https://github.com/google/closure-library/wiki/goog.module:-an-ES6-module-like-alternative-to-goog.provide)
During compilation, the compiler normalizes and inlines all of these disparate module by rewriting them into a form where the remaining passes can understand and optimize them fully. This is equivalent functionality to other module bundlers. You can use multiple modules types in a single compilation.

I found that if compilation_level is simple or whitespace only, cjs can be trasnpiled.
However, if compilation_level is advanced,
this error occurs
> src/cjs/class-foo.js:2:12: ERROR - [JSC_UNDEFINED_VARIABLE] variable require is undeclared
  2| const Bar = require('./class-bar')

But I cannot find any documentation regarding this, could you explain what is the under the hood? @rishipal
