### ISSUE TITLE
CONTRIB_PATH set wrong

### ISSUE THREAD

**Issue by ray007** [google/closure-compiler#3439]
I have installed `google-closure-compiler` with `npm`.

When I tried to use the supplied externs I found `closureCompiler.compiler.CONTRIB_PATH`
pointing to
`node_modules\google-closure-compiler-java\contrib` instead of `node_modules/google-closure-compiler/contrib`.

**Comment by lauraharker** [comment]
Created Google internal issue http://b/138237064

**Comment by brad4d** [comment]
I believe this is the same issue as
https://github.com/google/closure-compiler-npm/issues/142

**Comment by brad4d** [comment]
Fixed by https://github.com/google/closure-compiler-npm/pull/146
