### ISSUE TITLE
How do I access non-contrib externs in npm module?

### ISSUE THREAD

**Issue by epicfaace** [google/closure-compiler#3443]
How do I access https://github.com/google/closure-compiler/tree/master/externs from the distributed npm package? It seems like it's not included, and only the externs under `contrib` are.

**Comment by rishipal** [comment]
Created internal issue http://b/138590809

**Comment by rishipal** [comment]
Moved it to closure-compiler-npm 
https://github.com/google/closure-compiler-npm/issues/143
