### ISSUE TITLE
use_types_for_optimization does nothing (or very little)

### ISSUE THREAD

**Issue by rishipal** [google/closure-compiler#3444]
from discussion - 
{
I posted this as a question on stackoverflow, but no response, so I'm back here on the mailing list.
Here is the stackoverflow page, if you prefer to respond there:
https://stackoverflow.com/questions/57226922/closure-compiler-use-types-for-optimization-doing-nothing

I am using the appspot online service and specifying use_types_for_optimization this way:
// @use_types_for_optimization true

For a while I was seeing some minor differences in the results between true and false.  But after flattening some properties the results are identical.  The minor differences were just different 2-letter property names.  Setting it to true never renamed properties as unique within a type.  All properties on all objects are always unique across all objects.  I have tried all the JSDoc tags and combinations I can think of, but no positive results.

What must I do to make Closure Compiler rename properties uniquely with?
}

**Comment by rishipal** [comment]
Created internal issue http://b/138590154

**Comment by sidewayss** [comment]
I am the Original Poster of this.  Is this now where Closure Compiler questions are asked?

**Comment by rishipal** [comment]
No, this external issue is just for status tracking.
You should expect communication regarding your issue on the Closure Compiler Discuss group.

**Comment by shicks** [comment]
This seems like more of a discussion than a bug, I'm not sure there's anything actionable here.  Let's move this back to the email list.

**Comment by sidewayss** [comment]
As the original poster, I agree :)

Any ideas?  What must I do to get use_types_for_optimization to work?
Does it requires @interface?  That doesn't seem right, but I read 
something that caused me to think about it on stackoverflow.
I responded to your comment on stackoverflow, but the text formatting is 
horrible.  Here is the text for running my .js file through the service:

// ==ClosureCompiler==
// @output_file_name default.js
// @compilation_level ADVANCED_OPTIMIZATIONS
// @language_out ECMASCRIPT_2017
// @use_types_for_optimization true
// @code_url https://sidewaysskullfinger.com/smaws/SMAWS.js
// ==/ClosureCompiler==

What other context can I provide you? I can work with a specific object 
as an example.

**Comment by rishipal** [comment]
@sidewayss - Moving the discussion to closure_compiler_discuss email list as Steve suggested.
