### ISSUE TITLE
Wrong transpile when class extends Object

### ISSUE THREAD

**Issue by davispuh** [google/closure-compiler#3454]
This doesn't compile correctly when transpiling to ES3

```js
const ClassA = (baseClass) => class extends baseClass {
	constructor() {
		super();
	}

	methodTest() {
		alert("Works! :)");
	}
}

let instanceA = new ClassA(Object);
instanceA.methodTest();
```

```
closure-compiler --language_out=ECMASCRIPT3 --js=bug.js
```

`instanceA` loses it's class methods.
```
instanceA.methodTest is not a function
```

See compiled output https://closure-compiler-debugger.appspot.com/#input0%3Dconst%2520ClassA%2520%253D%2520(baseClass)%2520%253D%253E%2520class%2520extends%2520baseClass%2520%257B%250A%2509constructor()%2520%257B%250A%2509%2509super()%253B%250A%2509%257D%250A%250A%2509methodTest()%2520%257B%250A%2509%2509alert(%2522Works!%2520%253A)%2522)%253B%250A%2509%257D%250A%257D%250A%250Alet%2520instanceA%2520%253D%2520new%2520ClassA(Object)%253B%250AinstanceA.methodTest()%253B%26input1%26conformanceConfig%26externs%26refasterjs-template%26CHECK_TYPES%3Dtrue%26TRANSPILE%3Dtrue%26CLOSURE_PASS%3Dtrue%26PRESERVE_TYPE_ANNOTATIONS%3Dtrue%26PRETTY_PRINT%3Dtrue

```js
  var input0$classdecl$var0 = function() {
    return baseClass.call(this) || this;
  };
  $jscomp.inherits(input0$classdecl$var0, baseClass);
  input0$classdecl$var0.prototype.methodTest = function() {
    alert("Works! :)");
  };
```

**Comment by lauraharker** [comment]
Created Google internal issue http://b/139671578

**Comment by lauraharker** [comment]
@davispuh the repro you sent does not work uncompiled either, as arrow functions like `ClassA` cannot be used with `new`. The compiler also warns about this.

In the Chrome DevTools:
``` js
const ClassA = (baseClass) => class extends baseClass {
        constructor() {
                super();
        }

        methodTest() {
                alert("Works! :)");
        }
}

let instanceA = new ClassA(Object);
instanceA.methodTest();
```
```
VM36:11 Uncaught TypeError: ClassA is not a constructor
    at <anonymous>:11:17
```

**Comment by lauraharker** [comment]
Closing this issue for now, unless you have an example that works uncompiled then fails compiled.

**Comment by davispuh** [comment]
Opps, trying to reduce example code I made mistake.

This code works in browser but not with transpile.

````js
const ClassFactoryA = (baseClass) => class extends baseClass {
	constructor() {
		super();
	}

	methodTest() {
		alert("Works! :)");
	}
}

let ClassA = ClassFactoryA(Object);
let instanceA = new ClassA();
instanceA.methodTest();

````

https://closure-compiler-debugger.appspot.com/#input0%3Dconst%2520ClassFactoryA%2520%253D%2520(baseClass)%2520%253D%253E%2520class%2520extends%2520baseClass%2520%257B%250A%2509constructor()%2520%257B%250A%2509%2509super()%253B%250A%2509%257D%250A%250A%2509methodTest()%2520%257B%250A%2509%2509alert(%2522Works!%2520%253A)%2522)%253B%250A%2509%257D%250A%257D%250A%250Alet%2520ClassA%2520%253D%2520ClassFactoryA(Object)%253B%250Alet%2520instanceA%2520%253D%2520new%2520ClassA()%253B%250AinstanceA.methodTest()%253B%26input1%26conformanceConfig%26externs%26refasterjs-template%26CHECK_TYPES%3Dtrue%26TRANSPILE%3Dtrue%26CLOSURE_PASS%3Dtrue%26PRETTY_PRINT%3Dtrue

**Comment by lauraharker** [comment]
Ok, thanks for the report!

The compiler has special logic [here](https://github.com/google/closure-compiler/blob/f0e78137f2e357b0f3146f0d86b117d731f7d45e/src/com/google/javascript/jscomp/Es6ConvertSuperConstructorCalls.java#L129) to handle transpiling `extends Object`, but it fails in cases like yours when the `extends` clause is not the literal name `Object`.


Working example: https://closure-compiler-debugger.appspot.com/#input0%3Dclass%2520ClassB%2520extends%2520Object%2520%257B%250A%2520%2520constructor()%2520%257B%250A%2520%2520%2520%2520super()%253B%250A%2520%2520%257D%250A%250A%2520%2520methodTest()%2520%257B%250A%2520%2520%2520%2520alert(%2522Works!%2520%253A)%2522)%253B%250A%2520%2520%257D%250A%257D%250Anew%2520ClassB().methodTest()%253B%26input1%26conformanceConfig%26externs%26refasterjs-template%26CHECK_TYPES%3Dtrue%26TRANSPILE%3Dtrue%26CLOSURE_PASS%3Dtrue%26PRESERVE_TYPE_ANNOTATIONS%3Dtrue%26PRETTY_PRINT%3Dtrue

Failing example: https://closure-compiler-debugger.appspot.com/#input0%3Dconst%2520baseClass%2520%253D%2520Object%253B%250Aclass%2520ClassA%2520extends%2520baseClass%2520%257B%250A%2520%2520constructor()%2520%257B%250A%2520%2520%2520%2520super()%253B%250A%2520%2520%257D%250A%250A%2520%2520methodTest()%2520%257B%250A%2520%2520%2520%2520alert(%2522Works!%2520%253A)%2522)%253B%250A%2520%2520%257D%250A%257D%250A%250Anew%2520instanceA().methodTest()%253B%250A%250A%250A%26input1%26conformanceConfig%26externs%26refasterjs-template%26CHECK_TYPES%3Dtrue%26TRANSPILE%3Dtrue%26CLOSURE_PASS%3Dtrue%26PRETTY_PRINT%3Dtrue

**Comment by blickly** [comment]
The issue with the failing example is that calling `Object.call(this)` inside an ES5 constructor doesn't return an object of the subclass (like `this` is), but rather a newly constructed `Object` instance.  Maybe this is yet another case of ES5 classes extending an ES6 class not working correctly?

**Comment by brad4d** [comment]
@blickly Thanks for the reminder of why we had to special-case things for `Object`.

This bug is just infeasible to fix.

Since `Object.call(this)` doesn't behave like a normal constructor would, the compiler must
**know** that the superclass is `Object` in order to transpile the call to `super()` correctly.
Unfortunately, it's not possible for the compiler to know this for all possible cases.

If you really **must** indirectly extend `Object` like this, the workaround is to instead extend an empty class.

```javascript
let ClassA = ClassFactoryA(class {});
```
