### ISSUE TITLE
optimization: division by constant as multiplication by inverse

### ISSUE THREAD

**Issue by gerardolima** [google/closure-compiler#3459]
Couldn't division by constants be optimized by replacing the operation by a multiplication of its inverse (_i.e x / 2 === x * (1/2) === x * 0.5_)

input
```javascript
// ==ClosureCompiler==
// @compilation_level ADVANCED_OPTIMIZATIONS
// @output_file_name default.js
// ==/ClosureCompiler==

function hello(x) {
 alert( x / 5);
}
const x = prompt('x')
hello(x);
```
output
```javascript
alert(prompt("x")/5);
```
better optimization
```javascript
alert(prompt("x")*0.2);
```
see example on "[closure-compiler.appspot.com](https://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540compilation_level%2520ADVANCED_OPTIMIZATIONS%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250Afunction%2520hello(x)%2520%257B%250A%2520%2520alert(%2520x%2520%252F%25205)%253B%250A%257D%250Aconst%2520x%2520%253D%2520prompt('x')%250Ahello(x)%253B%250A%250A)"

**Comment by rishipal** [comment]
Created internal issue - http://b/140444745

**Comment by tjgq** [comment]
Why do you believe this to be an optimization? For an integer divisor, multiplication by the reciprocal will always result in increased code size (in your example, `*0.2` is longer than `/5`).

If the intent is to optimize for execution speed rather than code size, this would need to be justified by a benchmark. It's very likely that JavaScript engines already perform the optimization you describe.

**Comment by gerardolima** [comment]
hey, @tjgq, while generally I'd agree with you, but there are more js engines around than I could benchmark (*). I expect `closure-compiler` project would have such test suits, though, that could shed some hard evidence on these numbers.

(*) some time ago, I did such benchmark ([here](https://stackoverflow.com/questions/10535605/javascript-performance-divide-or-multiply-vs/10536563#10536563)) and, at the time on my computer, chrome yielded 14% better performance and IE 10%.

**Comment by ts-thomas** [comment]
Performance rules over size in my opinion (especially when gzipping)

**Comment by tjgq** [comment]
This sort of optimization is best left to JavaScript engines and is not something we will attempt.
