### ISSUE TITLE
optimization: inlining

### ISSUE THREAD

**Issue by gerardolima** [google/closure-compiler#3460]
Couldn't inline substitution be applied to the following example?

input
```javascript
// ==ClosureCompiler==
// @compilation_level ADVANCED_OPTIMIZATIONS
// @output_file_name default.js
// ==/ClosureCompiler==

function hello(x) {
  alert( 123)
  alert( x / 5);
}
const x = prompt('x')
hello(x);
```
output
```javascript
var a=prompt("x");alert(123);alert(a/5);
```
better optimization
```javascript
alert(123);alert(prompt("x")/5);
```
see example on "[closure-compiler.appspot.com](https://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540compilation_level%2520ADVANCED_OPTIMIZATIONS%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250Afunction%2520hello(x)%2520%257B%250A%2520%2520alert(%2520123)%250A%2520%2520alert(%2520x%2520%252F%25205)%253B%250A%257D%250Aconst%2520x%2520%253D%2520prompt('x')%250Ahello(x)%253B%250A%250A)"

**Comment by rishipal** [comment]
Created internal issue - http://b/140444748

**Comment by tjgq** [comment]
I don't think this is a valid optimization since it changes the order of side effects.

**Comment by gerardolima** [comment]
@tjgq, you got a point about side effects; can't closure identify pure functions, though?

**Comment by lauraharker** [comment]
@gerardolima the compiler does try to identify pure and side-effect-free functions. For externs code, where the compiler cannot see the actual function definition, the compiler relies on the [`@nosideeffects`](https://github.com/google/closure-compiler/wiki/Annotating-JavaScript-for-the-Closure-Compiler#nosideeffects-modifies-thisarguments) annotation. The `prompt` function is indentionally not annotated `@nosideeffects`.

https://github.com/google/closure-compiler/blob/f175c3fc6b148376aa329c0f61d4d7175b187d9f/externs/browser/window.js#L135

If `prompt('x')` were replaced with a pure and side-effect-free function call, the compiler would inline that call:

``` js
function hello(x) {
  alert( 123)
  alert( x / 5);
}
const x = Math.floor(3.52)
hello(x);

```

becomes

``` js
alert(123);alert(.6);
```

[Webservice link](https://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540compilation_level%2520ADVANCED_OPTIMIZATIONS%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250Afunction%2520hello(x)%2520%257B%250A%2520%2520alert(%2520123)%250A%2520%2520alert(%2520x%2520%252F%25205)%253B%250A%257D%250Aconst%2520x%2520%253D%2520Math.floor(3.52)%250Ahello(x)%253B%250A)
