### ISSUE TITLE
Unused Field

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [google/closure-compiler#3466]
https://github.com/google/closure-compiler/blob/8f020037f410fd97164b64fb5ceb66c90fd6ad7e/src/com/google/javascript/jscomp/RewriteAsyncIteration.java#L64
This field is never used.

**Comment by brad4d** [comment]
Internal issue created http://b/140866535

**Comment by brad4d** [comment]
Fixed in a6cc52361920d426dd9eb462656bdb1fbf218cab
Apparently I didn't reference this issue correctly, so it didn't automatically close.
