### ISSUE TITLE
BUNDLE ignores wrapped goog.require statements

### ISSUE THREAD

**Issue by ribrdb** [google/closure-compiler#3468]
prettier wraps long goog.require lines as 
```js
const foobar = goog.require(
  'my.reallyreallyreallyreallyreallyreallyreallyreallyreallyreallyreally.long.module'
);
```
If compile in BUNDLE mode, these requires get skipped from the output. It seems like goog.require has to be a single line in BUNDLE mode.

**Comment by brad4d** [comment]
This is actually by design, because we need to be able to do a quick, regex-based, query through the files to find their dependencies without doing the whole JS parse.
It's even codified in our style guidelines.

https://google.github.io/styleguide/jsguide.html#file-goog-require
"If a long alias or module name would cause a line to exceed the 80-column limit, it must not be wrapped: require lines are an exception to the 80-column limit."

**Comment by ribrdb** [comment]
Shouldn't that be documented somewhere in the closure compiler docs?
I don't think I've seen any reference to google's style guide in the closure compiler docs, let alone a notice that parts of it are required for the closure compiler to work.

**Comment by brad4d** [comment]
@ribrdb, we definitely should document this.

Unfortunately, it's not clear to me where best to put that documentation.
If you reopen this issue and add a link to whatever documentation you were using that was missing this information, I'll go add it there. Thanks.

**Comment by ribrdb** [comment]
I don't think I have permission to re-open. I don't have a specific document I looked at, I was mostly googling around and couldn't find anything. Although here's some places that seem like it might make sense to document this:

- Somewhere on the Closure Compiler wiki. This is the first place I go to look for compiler issues. Maybe the FAQ or Compiler-Assumptions page? The JS modules page is another one I might have looked at, although it mainly seems to have docs for people not using goog.require.
- The api docs for goog.require. This is the first place I go for closure-library issues: https://google.github.io/closure-library/api/goog.html#require
- Probably also somewhere on developers.google.com. Maybe https://developers.google.com/closure/library/docs/gettingstarted and/or https://developers.google.com/closure/compiler/docs/limitations
