### ISSUE TITLE
31 line bulk

### ISSUE THREAD

**Issue by Lagicrus** [google/closure-compiler#3469]
I am using version 20190909 with the flags 
--compilation_level SIMPLE --js $FileName$ --rewrite_polyfills=false

My question is why on files that include async functions do I suddenly gain 31 lines at the start of the .min.js file even with the rewrite_polyfills flag? Is that a thing that the flag does not handle or is that something that will always get added to a file the moment you start going async?

**Comment by EatingW** [comment]
Created internal issue http://b/141321069

**Comment by EatingW** [comment]
Async functions are not polyfills so they are not part of the rewrite_polyfills flag. You would actually need the additional code for async to work.

**Comment by Lagicrus** [comment]
> Async functions are not polyfills so they are not part of the rewrite_polyfills flag. You would actually need the additional code for async to work.

Thanks that makes sense. However I have a question, do I only need that code in order for async to work in older JS/browser versions or what? Or is the 31 lines done so that its sped up by comparison or the like? Just trying to understand how a "regular" js file can just be `async def` and you are off to the races whilst here I need the additional lines for it to work.

**Comment by EatingW** [comment]
Yes, you would need the code in order for async to work in older browsers that do not understand async. The compiler does a transpilation to rewrite async functions if your language_out is set to ECMASCRIPT_2016 or earlier. 

If you don't need your compiled code to be compatible with ECMASCRIPT_2016 and earlier, use --language_out=ECMASCRIPT_2017 or a even later version. 

See https://github.com/google/closure-compiler/wiki/Flags-and-Options for the language options.

**Comment by Lagicrus** [comment]
> Yes, you would need the code in order for async to work in older browsers that do not understand async. The compiler does a transpilation to rewrite async functions if your language_out is set to ECMASCRIPT_2016 or earlier.
> 
> If you don't need your compiled code to be compatible with ECMASCRIPT_2016 and earlier, use --language_out=ECMASCRIPT_2017 or a even later version.
> 
> See https://github.com/google/closure-compiler/wiki/Flags-and-Options for the language options.

You are a star, that fixed my "issue" :D Thanks a bunch
