### ISSUE TITLE
GlobalNamespace::canCollapseOrInline is slow

### ISSUE THREAD

**Issue by phb** [google/closure-compiler#3479]
Starting with commit https://github.com/google/closure-compiler/commit/867d9b2b6255ed5ecdb3675b84eae215d6d74fd8 , GlobalNamespace::canCollapseOrInline will iterate over properties in an object literal
```
      if (getDeclaration() != null) {
        Node declaration = getDeclaration().getNode();
        if (declaration.getParent().isObjectLit()
            && stream(declaration.siblings()).anyMatch(Node::isSpread)) {
          // Case: `var x = {a: 0, ...b, c: 2}` where declaration is `a` but not `c`.
          // Following spreads may overwrite the declaration.
          return Inlinability.DO_NOT_INLINE;
        }
      }
```

This method seems really hot, as it's used by quite a few passes in their tree traversals.

In our case we have many extremely large object literals and as a result this section of code takes up around 40% of our compilation time (sampling profiling using jvisualvm, so not the most accurate)

I believe I can work around it for now by marking all my huge literals with @nocollapse, but I still wanted to highlight this with the hope that the section of code can be optimized by someone familiar with the closure compiler internals.

Thank you
/Johan

**Comment by concavelenz** [comment]
Thanks for the report.

**Comment by concavelenz** [comment]
Created internal issue http://b/142425639

**Comment by nreid260** [comment]
Do you have a profile you can share? It would be helpful to know specifically what is slow in that method and how much.

There are ways we could make the code more efficient, but it would be a bit less readable and I don't want to optimize prematurely.

**Comment by concavelenz** [comment]
We have traditionally avoided iterators for hot methods (and streams are worse), a method with a simple loop definitely be more efficient here.  NodeUtil.has might be an appropriate substitute.

**Comment by phb** [comment]
Hi @nreid260,

I can't provide a full profile unfortunately.
I just ran a compilation of a smaller target I have and here are a few screenshots (sorry I know it's not ideal but hopefully it should give you an idea what's going on). Ie, what @concavelenz states sesems right, the stream anyMatch is what's showing up on the profile. I'm not familiar with the streams API and just how much slower it would be compared to a simple loop -- Ie, I guess the other option would be to store some kind of metadata about whether the literal has a spread operator but I would imagine that to be a lot more intrusive.

<img width="1439" alt="Screen Shot 2019-10-10 at 6 24 18 am" src="https://user-images.githubusercontent.com/179816/66561118-d7019300-eb26-11e9-8bdc-e040dcacc7a3.png">
First screenshot shows hot methods from jvisualvm

<img width="1293" alt="Screen Shot 2019-10-10 at 6 25 02 am" src="https://user-images.githubusercontent.com/179816/66561117-d7019300-eb26-11e9-9074-0d19f227193c.png">
this is one of the forward call references. Note, this method is called from quite a few passes.

Hope this helps and thank you for taking the time to look at the issue.

**Comment by nreid260** [comment]
Do you have any call-count numbers?

We suspect the problem is less that a stream is being used and more that the number of streams used is linear in the size of the object literal. This leads to aggregate `O(n^2)` performance.

Either way, we'll probably improve the algorithm.

**Comment by phb** [comment]
I don't have call count numbers -- I'll try to collect some next time I have some time to look into this.

I attempted to add "@nocollapse" to all my object literals but sadly that broke the generated results (a minified property attempts to call something that does not exist)

**Comment by nreid260** [comment]
We've submitted a fix that should land in the next release. I believe it'll be available from source pretty soon. If you're curious please try it out.

**Comment by concavelenz** [comment]
https://github.com/google/closure-compiler/commit/900646b0e2426a24e93564c69697c19257f9444f#diff-4c42c8f1f38ce0e52d425419e38b3738
