### ISSUE TITLE
Error on a constant declaration for HTMLAudioElement

### ISSUE THREAD

**Issue by dascritch** [google/closure-compiler#3488]
When I have an `audiotag` typed as an `HTMLAudioElement`, and i'm checking `audiotag.readyState < audiotag.HAVE_CURRENT_DATA` , closure in ADVANCED_OPTIMIZATIONS mode doesn't like it : 

```
WARNING - [JSC_INEXISTENT_PROPERTY] Property HAVE_CURRENT_DATA never defined on HTMLAudioElement
```

As I'm reading, `HAVE_CURRENT_DATA` is defined here : https://github.com/google/closure-compiler/blob/master/externs/browser/html5.js#L1944
But not on `HTMLMediaElement.prototype` . So we cannot even use `HTMLAudioElement.HAVE_CURRENT_DATA`.

As I can read in https://developer.mozilla.org/en-US/docs/Web/API/HTMLAudioElement : 

    inherits properties from its parent, HTMLMediaElement, and from HTMLElement. 

Perhaps I'm wrong, but as any browsers is accepting my `audiotag.HAVE_CURRENT_DATA`, may be those declarations must be changed into : 

```
HTMLMediaElement.prototype.HAVE_CURRENT_DATA;
```

**Comment by kjin** [comment]
Created internal bug http://b/143219987

**Comment by kjin** [comment]
Is there any particular reason you can't write it as `audiotag.readyState < HTMLMediaElement.HAVE_CURRENT_DATA`? It's true that in browsers you can access it on any of `HTMLMediaElement` or its subclasses' definitions or prototypes, but given that it is a constant, would make more sense to access it as a static property of the base class itself?

**Comment by dascritch** [comment]
Funnily... The warning doesn't trigger in some cases : 

As today, I have to write it there
https://github.com/dascritch/cpu-audio/blob/57bacdd06071fff362b311d7ca18cabc9d3665b8/src/40_document_cpu.js#L247

But the warning won't trigger there
https://github.com/dascritch/cpu-audio/blob/57bacdd06071fff362b311d7ca18cabc9d3665b8/src/45_element_cpu.js#L82

**Comment by kjin** [comment]
Ah, got it. I do see that the HTML5 externs file does contain existing examples where constants exist on both a class and its prototype (like `WebSocket`) so this doesn't seem like an unprecedented change, it seems doable.

**Comment by kjin** [comment]
I've landed a change to add all of the constants on `HTMLMediaElement` to its prototype as well ( (should work for instances of type `HTMLAudioElement` too), and it should be in the next compiler release.
