### ISSUE TITLE
Documentation typo?

### ISSUE THREAD

**Issue by munizart** [google/closure-compiler#3495]
[Here](https://github.com/google/closure-compiler/wiki/Annotating-JavaScript-for-the-Closure-Compiler#nosideeffects-modifies-thisarguments) it reads
> Calls to these functions may be removed if the parameters provided to the function are otherwise known to be otherwise unused.

Shouldn't it reads this?
> Calls to these functions may be removed if the parameters provided to the function are otherwise known to be unused.

**Comment by kjin** [comment]
You're right, I've fixed it. Thanks!
