### ISSUE TITLE
Cache of prototype is created too late

### ISSUE THREAD

**Issue by ts-thomas** [google/closure-compiler#3497]
I recognize that the protoype is cached, when used very often. That's really nice. But I also see that the prototype is cached too late, some steps after it was accessed directly:

Example from my build:
```js
D.prototype.init = function(){};
D.prototype.apply= function(){};
// ....
// from here the closure compiler cache the prototype
q = D.prototype;
q.create = function(a){}
q.remove= function(a){}
```

The prototype wasn't cached right from the beginning.

**Comment by kjin** [comment]
Created Google internal issue http://b/143545890

**Comment by kjin** [comment]
Thanks for reporting this! Given the general trend towards ES6 classes and the relatively small amount of bytes likely saved from this, we will probably not be able to prioritize this enough to fix it.
