### ISSUE TITLE
CommandLineRunner.FormattingOption not public

### ISSUE THREAD

**Issue by mP1** [google/closure-compiler#3502]
The `CommandLineRunner` includes a non public enum `FormattingOption` and a method that parses Strings into `FormattingOption`.

I am authoring a maven plugin to handle @gwt-incompatible stripping, transpiling and closure compiling and because said artifacts are not public I cannot leverage the public method and enum to validate and hold a formatting parameter.

The solution for my selfish self is to make these public so others like me, can leverage without hardcoding available formatting options in our code.

```java
 /**
   * Set of options that can be used with the --formatting flag.
   */
  private static enum FormattingOption {
    PRETTY_PRINT,
    PRINT_INPUT_DELIMITER,
    SINGLE_QUOTES
    ;
```

```java
    @Option(name = "--formatting",
        usage = "Specifies which formatting options, if any, should be "
        + "applied to the output JS. Options: "
        + "PRETTY_PRINT, PRINT_INPUT_DELIMITER, SINGLE_QUOTES")
    private List<FormattingOption> formatting = new ArrayList<>();
```

**Comment by mprobst** [comment]
Created internal issue b144257095.

**Comment by mprobst** [comment]
Sounds reasonable - care to send a PR?

**Comment by mP1** [comment]
PR ready

**Comment by mP1** [comment]
Closed by https://github.com/google/closure-compiler/commit/38ec18274c366f651550ca457554e2608fb8e7cd
