### ISSUE TITLE
Transpiling a string literal adds a semicolon inside it

### ISSUE THREAD

**Issue by alejandromagnorsky** [google/closure-compiler#3504]
[Here](https://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540language_out%2520ECMASCRIPT_2015%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%2540compilation_level%2520SIMPLE_OPTIMIZATIONS%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250Aconst%2520A%2520%253D%2520'foo'%253B%250A%250Afunction%2520doSomething(c)%2520%257B%250A%2520%2520let%2520b%253B%250A%250A%2520%2520const%2520d%2520%253D%2520%2560%2524%257Bc%257D%2560%253B%250A%2520%2520if%2520(d%2520!%253D%253D%2520A)%2520%257B%250A%2520%2520%2520%2520b%2520%253D%2520c%253B%250A%2520%2520%257D%250A%250A%2520%2520return%2520b%253B%250A%257D) is the example to reproduce it.

Code:
```js
// ==ClosureCompiler==
// @language_out ECMASCRIPT_2015
// @output_file_name default.js
// @compilation_level SIMPLE_OPTIMIZATIONS
// ==/ClosureCompiler==

const A = 'foo';

function doSomething(c) {
  let b;

  const d = `${c}`;
  if (d !== A) {
    b = c;
  }

  return b;
}
```

Actual output contains a `;${a}` instead of `${a}`.

**Comment by mprobst** [comment]
Created internal issue: b/144336674.
