### ISSUE TITLE
com.google.javascript.rhino.TokenStream does not take into account new keywords in modern javascript

### ISSUE THREAD

**Issue by phb** [google/closure-compiler#3509]
TokenStream seems to not take into account newer javascript keywords such as 'let'. This results in incorrect optimized code for large projects where a renamed variable can be renamed to 'let'.

ie, in DefaultNameGenerator.java in generateNextName, it uses TokenStream to determine if a generated variable name is a keyword.

**Comment by rishipal** [comment]
Created internal issue - http://b/144934768

**Comment by rishipal** [comment]
Do you know which large project this occurs in?

**Comment by phb** [comment]
Internal project (can't share). It's actually causing us severe headaches at the moment -- if you have any ideas of workarounds that would be amazing.

**Comment by rishipal** [comment]
I was able to reproduce. I'm submitting a fix shortly. Thanks!

**Comment by rishipal** [comment]
Fixed with 78b2f14c5e5e985d8cbf2bcd1950c7ed1991bae5
