### ISSUE TITLE
Functions declared with explicit "window" are not properly recognized with advanced optimizations

### ISSUE THREAD

**Issue by StevenNL2000** [google/closure-compiler#3514]
Consider this input:
```javascript
window.testFunction = function() {
  console.log("Test");
}
testFunction();
```
If we compile it with simple optimizations, we get a correct output from the Java application and the REST API / web UI (with pretty print):
```javascript
window.testFunction = function() {
  console.log("Test");
};
testFunction();
```
However, now consider the output of the Java application with advanced optimizations:
```
test.js:4: ERROR - [JSC_UNDEFINED_VARIABLE] variable testFunction is undeclared
testFunction();
^^^^^^^^^^^^

1 error(s), 0 warning(s)
```
And the output of the REST API / web UI with advanced optimizations (and pretty print):
```javascript
window.a = function() {
  console.log("Test");
};
testFunction();
```

I am not aware if this difference between the Java application and the REST API is intentional, but neither are correct from my point of view.

**Comment by blickly** [comment]
This is one of the restrictions of using ADVANCED mode, which is documented inside the "Referring to variables as properties of the global object:" bullet at:
https://developers.google.com/closure/compiler/docs/limitations#restrictions-for-advanced_optimizations

Do you think there's a way we could have structured our documentation that would have made it easier for you to find?

**Comment by StevenNL2000** [comment]
I see. From that guide I assumed there was supposed to be a difference between assigning a variable and then referring to it with "window" and assigning a variable with "window" and then referring to it normally. The reason I believed that is because
```javascript
var testFunction = function() {
  console.log("Test");
}
window.testFunction();
```
compiles to `window.a();` in the Java application, while the opposite shown in the original post gives an error.

**Comment by blickly** [comment]
Since property renaming and variable renaming are independent, it isn't guaranteed that the code will always be broken in ADVANCED, only very likely for sufficiently large codebases.
