### ISSUE TITLE
Is there a way to create minified bundle/amalgamation of JS closure compiler?

### ISSUE THREAD

**Issue by juj** [google/closure-compiler#3515]
I am in the process of embedding the JS version of Closure compiler to the Emscripten toolchain.

Installing the compiler on demand with `npm install google-closure-compiler` has some trouble with the general setup of how Emscripten is distributed, and I am wondering if it's possible to create a redistributable minified amalgamation of JS Closure somehow, that we could statically check in to Emscripten repository?

**Comment by rrdelaney** [comment]
Created Google internal issue http://b/145817110

**Comment by ChadKillingsworth** [comment]
Each platform is distributed as it's own standalone repo. See https://www.npmjs.com/package/google-closure-compiler-js

npm is the only place we publish the JS version. You can statically check it in to your repo of course, but then you'll have to check in each and every version and users will have a hard time managing compiler versions separate from your toolchain. In general, it's best to utilize a package manager for this.

**Comment by juj** [comment]
Thanks, yeah - looks like we are ending up with setting npm arch to the compiler repository to manage this.
