### ISSUE TITLE
Element.insertAdjacentElement, Element.insertAdjacentHTML, Element.insertAdjacentText not supported. Please add to DOM extern file(s).

### ISSUE THREAD

**Issue by hvdmeulen** [google/closure-compiler#3516]
These methods are part of the w3c "DOM Living Standard" and have good browser support. Please add these to the DOM extern file(s):

- https://developer.mozilla.org/en-US/docs/Web/API/Element/insertAdjacentElement
- https://developer.mozilla.org/en-US/docs/Web/API/Element/insertAdjacentHTML
- https://developer.mozilla.org/en-US/docs/Web/API/Element/insertAdjacentText

**Comment by rrdelaney** [comment]
Tracked in http://b/145904477

**Comment by shicks** [comment]
PRs would be welcome here.  We likely won't get to this ourselves any time soon.

**Comment by DeltaFlush** [comment]
Submitted a PR for this at (https://github.com/google/closure-compiler/pull/3578)
