### ISSUE TITLE
String#matchAll polyfill should throw on non-global regex

### ISSUE THREAD

**Issue by teppeis** [google/closure-compiler#3517]
`"foo".matchAll(/foo/)` should throw but current polyfill doesn't.
Previously it didn't throw, but spec was changed on Oct 2019 TC39 meeting.
- https://github.com/tc39/ecma262/pull/1716
- https://github.com/tc39/proposal-string-replaceall/pull/24

https://github.com/google/closure-compiler/blob/60f0812b534f5498e85743475d98a94f23c23638/src/com/google/javascript/jscomp/js/es6/string/matchall.js#L44-L47

> but MDN and Chrome agree that a single match should be done instead.

MDN is not updated yet.
Chrome 80, Firefox 73, Safari TP and core-js have already implemented the new behavior.
https://kangax.github.io/compat-table/es2016plus/

I think Closure Compiler polyfill should follow the latest spec and major browsers.

**Comment by brad4d** [comment]
Thanks for pointing this out.
We noticed the discrepancy, but decided to implement what our current Chrome browser & MDN said the behavior should be while we gathered more info.

I actually got a response from the v8 team and had just filed a bug requesting we change our polyfill behavior just before I saw this GitHub issue.
