### ISSUE TITLE
String#matchAll polyfill returns an incomplete iterator object

### ISSUE THREAD

**Issue by teppeis** [google/closure-compiler#3518]
Expected:
```javascript
const iter = "".matchAll(/foo/g);
iter[Symbol.iterator]() === iter;
// true
```

But actually current polyfill throws an error:
```
TypeError: Property 'jscomp_symbol_Symbol.iterator_0' of object #<Object> is not a function
```
----
According to the spec, `String#matchAll()` returns a [RegExp String Iterator Object](https://tc39.es/ecma262/#sec-regexp-string-iterator-objects).
The prototype inherits [`%IteratorPrototype%`](https://tc39.es/ecma262/#sec-%iteratorprototype%-object) and it has `[ @@iterator ] ( )` method.

Because of this issue, [compat-table test](https://kangax.github.io/compat-table/es2016plus/#test-String.prototype.matchAll_basic_functionality) fails.

**Comment by brad4d** [comment]
Thanks for pointing this out.

@vxlydia could you fix this? Thanks.

**Comment by teppeis** [comment]
@brad4d @nreid260 @vxlydia Thanks!

It throws `ReferenceError: Symbol is not defined`.
Please insert `$jscomp.initSymbolIterator()` like `Set` polyfill.
https://github.com/google/closure-compiler/blob/bd3bb8e186eb3704336e6617ca81690dc17a74cd/src/com/google/javascript/jscomp/js/es6/set.js#L19
https://github.com/google/closure-compiler/blob/bd3bb8e186eb3704336e6617ca81690dc17a74cd/src/com/google/javascript/jscomp/js/es6/set.js#L75-L76
https://github.com/google/closure-compiler/blob/bd3bb8e186eb3704336e6617ca81690dc17a74cd/src/com/google/javascript/jscomp/js/es6/set.js#L156-L157

**Comment by teppeis** [comment]
Thanks!
