### ISSUE TITLE
Polyfill is not injected for equality operand 

### ISSUE THREAD

**Issue by teppeis** [google/closure-compiler#3519]
For example, `Map` polyfill is NOT injected for the following expressions unexpectedly.
```js
Map == null;
Map != null;
Map != null && new Map();
```
Otherwise it's injected for the following each expressions correctly.
```js
new Map();
Map;
Map < null;
```
Same for all the other polyfills.

**Comment by brad4d** [comment]
This is actually working as intended. We're trying to avoid injecting polyfills for code that was designed to work when the polyfilled value isn't present.

**Comment by teppeis** [comment]
make sense.
