### ISSUE TITLE
Feature request: explicit templated function type

### ISSUE THREAD

**Issue by VSjolund** [google/closure-compiler#3520]
This relates to closed issue https://github.com/google/closure-compiler/issues/3362. @brad4d recommended opening a new issue with a feature request, I could not find any open so here goes.

Currently there seems to be no way to adopt the typing scheme used internally by the compiler for returning templated function types (bounded or not). A simple example (coercing typing error to see what the compiler infers), run simply with `java -jar compiler.jar --compilation_level ADVANCED --js src/example.js`
```js
/**
 * 
 * @returns {function(string): *}
 */
function func() {
  return (
    /**
     * @template {!Function} T
     * @param {T} fn
     * @returns {T} 
     */
    function(fn) {
      return /** @type {T} */(
        function() { }
      );
    }
  )
}
```
Produces
```
example.js:13: WARNING - [JSC_TYPE_MISMATCH] inconsistent return type
found   : function(T extends Function): T extends Function
required: function(string): *
    function(fn) {
    ^^^^^^^^^^^^^^

0 error(s), 1 warning(s), 96.6% typed
```
Replacing `@returns {function(string): *}` with `@returns {function(T extends Function): T extends Function` (or similarly `@returns {function((T extends Function)): (T extends Function)}`) produces syntax error
```
example.js:3: WARNING - [JSC_TYPE_PARSE_ERROR] Bad type annotation. missing closing ) See https://github.com/google/closure-compiler/wiki/Annotating-JavaScript-for-the-Closure-Compiler for more information.
 * @returns {function((T extends Function)): (T extends Function)}
                         ^

0 error(s), 1 warning(s), 100.0% typed
```
Is this on the roadmap to implement? I have not found any related discussion. The syntax spat out by the compiler right now seems a bit contrived. The obvious possibility is:
```js
/** @type {function<T extends Function>(T): T} */ 
```
Another option is to disallow inline templated functions and instead add support for templated typedefs:
```js
/**
 * @template {Function} T
 * @typedef {function(T): T}
 */
var Callback;
/** @returns {Callback} */
function func() { /* snip */ } 
```
Regarding Typescript/JsDoc interop, the only way I could get syntax highlighting to work is through direct typescript syntax:
```js
/** @returns {<T extends Function>(fn: T) => T */
```
Seems to me as supporting compatibility is not desirable in this case.

**Comment by shicks** [comment]
There are quite a few types that the compiler can represent internally, but that can't be represented directly in JSDoc.  What is the use case for needing to write this specific type?  Would a `typeof` type be sufficient to meet that need?

Without a compelling use case, it's hard to justify adding a bunch of new syntax support.

**Comment by VSjolund** [comment]
The main use is chaining callbacks, e.g. when using wrappers around them and wanting to persist typing info passed to receiving function. As this would be solved with templated typedefs and there already is an open issue, I'll opt for that and we can merge them together. ref https://github.com/google/closure-compiler/issues/890
