### ISSUE TITLE
String#matchAll polyfill throws an error "Symbol is not defined"

### ISSUE THREAD

**Issue by teppeis** [google/closure-compiler#3521]
` "".matchAll(/foo/g)` throws `ReferenceError: Symbol is not defined`.

Please insert `$jscomp.initSymbolIterator()` like `Set` polyfill.
https://github.com/google/closure-compiler/blob/bd3bb8e186eb3704336e6617ca81690dc17a74cd/src/com/google/javascript/jscomp/js/es6/set.js#L19
https://github.com/google/closure-compiler/blob/bd3bb8e186eb3704336e6617ca81690dc17a74cd/src/com/google/javascript/jscomp/js/es6/set.js#L75-L76

Originally posted at https://github.com/google/closure-compiler/issues/3518#issuecomment-564529377

**Comment by shicks** [comment]
This looks like a pretty straightforward fix?

**Comment by brad4d** [comment]
@vxlydia has a fix in review

**Comment by teppeis** [comment]
Fixed in https://github.com/google/closure-compiler/commit/2146f6859db3f62f76fa0a04d50f1e222195ee47, thanks!
