### ISSUE TITLE
Incorrect destructuring optimisation

### ISSUE THREAD

**Issue by zavr-1** [google/closure-compiler#3524]
The compiler will drop a variable if it's not used however this leads to incorrect compilation.
```js
const data = {
  hello: 'abc',
  world: 'def',
}

const {
  hello,
  ...rest
} = data

console.log(rest)
```
Tested on tonight's nightly build.
```js
// code produced
'use strict';const {...a}={a:"abc",b:"def"};console.log(a);
```
This is obviously incorrect and outputs `{ a: 'abc', b: 'def' }` whereas only `{ b: 'def' }` is expected.

**Comment by brad4d** [comment]
Thanks for reporting this.
I'm working on a fix.

**Comment by brad4d** [comment]
fix submitted internally
It should be in the Monday push to GitHub
