### ISSUE TITLE
Does not infer type (regression)

### ISSUE THREAD

**Issue by zavr-1** [google/closure-compiler#3525]
This will result in a warning
```js
/**
 * Format object to Content-Disposition header.
 *
 * @param {Object} obj
 * @param {string} obj.type
 * @param {Object} [obj.parameters]
 */
function format (obj) {
  var parameters = obj.parameters
  // append parameters
  if (parameters && typeof parameters == 'object') {
    let param
    var params = Object.keys(parameters).sort()
    return params
  }
  return []
}

format({ test: true })
```
```
found   : (Object|null)
required: Object
    var params = Object.keys(parameters).sort()
                             ^^^^^^^^^^

0 error(s), 1 warning(s), 82.6% typed
```
This didn't happen the version before the previous stable one. `parameters` cannot be null here because it's inside the if statement. I'm using the nightly build.
This will not produce a warning
```js
/**
 * Format object to Content-Disposition header.
 *
 * @param {Object} parameters
 */
function format (parameters) {
  // append parameters
  if (parameters && typeof parameters == 'object') {
    let param
    var params = Object.keys(parameters).sort()
    return params
  }
  return []
}

format({ test: true })
```

**Comment by brad4d** [comment]
Here's a repro in the compiler web UI

https://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540compilation_level%2520ADVANCED_OPTIMIZATIONS%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%2540formatting%2520pretty_print%252Cprint_input_delimiter%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250A%252F%252F%2520ADD%2520YOUR%2520CODE%2520HERE%250A%252F**%250A%2520*%2520Format%2520object%2520to%2520Content-Disposition%2520header.%250A%2520*%250A%2520*%2520%2540param%2520%257BObject%257D%2520obj%250A%2520*%2520%2540param%2520%257Bstring%257D%2520obj.type%250A%2520*%2520%2540param%2520%257BObject%257D%2520%255Bobj.parameters%255D%250A%2520*%252F%250Afunction%2520format%2520(obj)%2520%257B%250A%2520%2520var%2520parameters%2520%253D%2520obj.parameters%250A%2520%2520%252F%252F%2520append%2520parameters%250A%2520%2520if%2520(parameters%2520%2526%2526%2520typeof%2520parameters%2520%253D%253D%2520'object')%2520%257B%250A%2520%2520%2520%2520let%2520param%250A%2520%2520%2520%2520var%2520params%2520%253D%2520Object.keys(parameters).sort()%250A%2520%2520%2520%2520return%2520params%250A%2520%2520%257D%250A%2520%2520return%2520%255B%255D%250A%257D%250A%250Aformat(%257B%2520test%253A%2520true%2520%257D)%250A

**Comment by brad4d** [comment]
Note that these declarations are invalid, and the example linked above does report that they are invalid.

```javascript
/**
 * Format object to Content-Disposition header.
 *
 * @param {Object} obj
 * @param {string} obj.type  INVALID!
 * @param {Object} [obj.parameters] INVALID!
 */
```

Here's a version of the same code with correct declarations that generates no warnings.
```javascript
/**
 * Format object to Content-Disposition header.
 *
 * @param {{type: (string|undefined), parameters: (!Object|undefined)}} obj
 */
function format (obj) {
  var parameters = obj.parameters
  // append parameters
  if (parameters && typeof parameters == 'object') {
    let param
    var params = Object.keys(parameters).sort()
    return params
  }
  return []
}

// NOTE: since this doesn't include `type` I allowed `type` to be undefined above.
format({ test: true })
```

**Comment by zavr-1** [comment]
I don't understand, why are they invalid. it's proper JSDoc and my compiler does not show those errors, only the online one. It's relevant to this issue here https://github.com/microsoft/TypeScript/issues/32783 i told the person that the compiler might be outdated online, but it's not the case. so why does my 20191218 not show warnings. 
this shouldn't be invalid i've been using it for years and compiling without warnings for almost a year as well. you shouldn't close this issue please.  it does not make sense to rewrite valid jsdoc into records `{ }`. also as i said i don't get those warnings locally

**Comment by brad4d** [comment]
The "JSDoc" used by closure-compiler is not the same as the "JSDoc" defined at https://devdocs.io/jsdoc/tags-param.

Our JSDoc format is documented at https://github.com/google/closure-compiler/wiki/Annotating-JavaScript-for-the-Closure-Compiler

It turns out that the default warnings level hides the non-standard (for us) JSDoc warnings.
I don't know why this is.

You'll see the JSDoc warnings if you use either `--jscomp_warning=nonStandardJsDocs"`.
The warnings enabled with `-W VERBOSE` will also include them.
