### ISSUE TITLE
Object.assign polyfill Error

### ISSUE THREAD

**Issue by angryxoma** [google/closure-compiler#3526]
**Console:**
Uncaught TypeError: Cannot use 'in' operator to search for 'Object' in undefined:
_e in b || (b[e] = {});
^_

**Source:**

```
const _objSource = {
  objVal1: { a: 1, b: 2, c: 3 },
  objVal2: { d: 4, f: 5, e: 6 }
};

let objTarget = Object.assign( {}, _objSource );

console.log( objTarget );
```

**Out:**

```
(function () {
  'use strict';
  var f = "function" == typeof Object.assign ? Object.assign : function (a, d) {
      for (var b = 1; b < arguments.length; b++) {
        var c = arguments[b];
        if (c) for (var e in c) Object.prototype.hasOwnProperty.call(c, e) && (a[e] = c[e])
      }
      return a
    }, g = "function" == typeof Object.defineProperties ? Object.defineProperty : function (a, d, b) {
      a != Array.prototype && a != Object.prototype && (a[d] = b.value)
    },
    h = "undefined" != typeof window && window === this ? this : "undefined" != typeof global && null != global ? global : this;

  function k(a, d) {
    if (d) {
      var b = h;
      a = a.split(".");
      for (var c = 0; c < a.length - 1; c++) {
        var e = a[c];
        e in b || (b[e] = {});
        b = b[e]
      }
      a = a[a.length - 1];
      c = b[a];
      d = d(c);
      d != c && null != d && g(b, a, {configurable: !0, writable: !0, value: d})
    }
  }

  k("Object.assign", function (a) {
    return a || f
  });
  var l = Object.assign({}, {g: {a: 1, b: 2, c: 3}, h: {d: 4, f: 5, e: 6}});
  console.log(l);
})();
```

**Comment by brad4d** [comment]
The problem actually has nothing to do with `Object.assign`, but rather with the fact that our attempt to find the global object failed in whatever environment you ran this in.

This assignment is ending up with `undefined`, so apparently neither `window` nor `global` is defined in your context.

```javascript
h = "undefined" != typeof window && window === this ? this : "undefined" != typeof global && null != global ? global : this;
```

Where are you running the code?
Looks like we need to update the logic for finding the global object to handle that environment.

**Comment by l1bbcsg** [comment]
I believe the polyfill failed because of strict mode (which was enabled by default in latest compiler release). 
In strict mode functions no longer have `this` boxed which causes IIFE to have `this` set to `undefined` as opposed to `window` and that's what `h` ends up being resolved to.

```js
(function() {
    'use strict';
    console.log(this); // undefined, would be Window without 'use strict'
})(); 
```

Perhaps another new feature, `globalThis` can help here?

**Comment by brad4d** [comment]
You're right, and I'm working on a fix.

**Comment by brad4d** [comment]
This was fixed by
https://github.com/google/closure-compiler/commit/b35283ab58a58951b676af26c85a90d9feadb4f8

I don't know why the "Fixes" part of its comment didn't close this issue automatically.
