### ISSUE TITLE
Type Transformation Language 

### ISSUE THREAD

**Issue by l1bbcsg** [google/closure-compiler#3527]
Certain externs like [`Promise`](https://github.com/google/closure-compiler/blob/master/externs/es6.js#L1198) contain advanced type definitions made with some kind of imperative grammar which I believe is named Type Transformation Language. This looks like it could be a very powerful feature that can drastically improve type coverage and perhaps allow to describe things not typically possible with jsdoc.

There are [`TypeTransformationTest`](https://github.com/google/closure-compiler/blob/master/test/com/google/javascript/jscomp/TypeTransformationTest.java) and [`TypeTransformationParser`](https://github.com/google/closure-compiler/blob/master/src/com/google/javascript/jscomp/parsing/TypeTransformationParser.java) that give some insight, but still not quite enough to understand how it works and how to properly use it.

Looks like it was swept under the rug when NTI was still planned, but what is the status of this feature now?

Is this something that is intended to be used publicly?
If this is the case, can we get some documentation describing it?

**Comment by brad4d** [comment]
We have no plans to remove TTL, but it is intended primarily to support JS native features that are complicated to type check. It's on the edge of what we really consider our public interface, so we'd really prefer our users not to depend on its syntax. It's a use-at-your-own-risk kind of thing, so we don't have any motivation to really document it for external use.
