### ISSUE TITLE
Destructuring quoted properties is broken for ES2015+ output

### ISSUE THREAD

**Issue by zavr-1** [google/closure-compiler#3529]
Destructured properties are renamed for ECMA-2015+ lang output.
```js
// t.js
const {
  'contenttype': ct,
  'content-type': ct2,
} = window

console.log(ct, ct2, window['contenttype'])
```
```sh
java -jar compiler.jar --compilation_level \
ADVANCED --language_out ES5
--js t.js
```
```js
var a=window;console.log(a.contenttype,a["content-type"],window.contenttype);
```
--- 
```sh
java -jar compiler.jar --compilation_level \
ADVANCED --language_out ECMASCRIPT_2015/16/17/18
--js t.js
```
```js
'use strict';console.log(window.b,window.a,window.contenttype);
```
I always assumed that using quoted props on destructuring behaves the same way as **accessing** a quoted property, and I'm pretty such it's how it's suppose to behave (see ES5), but the properties in the output are renamed.

**Comment by lauraharker** [comment]
I agree that quoted props should behave like quoted property accesses. Assigning to myself to investigate.

**Comment by zavr-1** [comment]
@lauraharker I'm sorry but this bug must have been the TOP priority since I filed it a month ago and fixed immediately. It's a breaking change since you moved from 
```js
const {createReadStream:h} = fs;
```
to
```js
const h = fs.createReadStream;
```
in other words, this was not the case before the November release (i think around november, maybe december).
btw, i have no idea what the reason behind this change is since it makes no difference i think the scope is lost either way -- i should probably read a newsletter. a quick check
```js
> const a = { b: 'test', a() { console.log(this.b) } }
undefined
> a.a()
test
undefined
> const c = a.a
undefined
> c()
undefined
undefined
> 
```
this bug has broken so much code everywhere! imagine i was getting 3rd party api requests, like 
```js
const res = await fetch('https://api.com')
const { 'data': data, 'error': error } = await res.json()
```
now this is broken in the Google's compiler for over a month! what's going on google? how do you even code internally? like this? 
```js
const res = await fetch('https://api.com')
const data = res['data']
const error = res['error']
```
i'm not passive aggressive but this bug is so crazy no? well at least thanks for not closing this issue on me.

**Comment by mprobst** [comment]
@zavr-1 a workaround is to explicitly declare externs for the data that
you're receiving from the server side. Something along the lines of:

```js
/** @externs */

/** @record */
class ApiResponse {
  constructor() {
    /** @type {...} */ this.data;
    /** @type {...} */ this.error;
  }
}
```

This gives you both type checking and renaming safety, and is the common
solution to this issue used at Google, I think.

Am Di., 28. Jan. 2020 um 18:43 Uhr schrieb zavr-1 <notifications@github.com

**Comment by zavr-1** [comment]
@mprobst yeah maybe if Google had quality assurance managers you'd have to explain the the workaround for the damage to reputation your company is taking. 1 tln dollar company they say... cannot add a test for destructuring of their compiler. but who am i hey

**Comment by lauraharker** [comment]
This was fixed in https://github.com/google/closure-compiler/commit/cee09b809050d297401bcab467fba07a7454bf9a

**Comment by zavr-1** [comment]
@lauraharker ok thanks i checked it on nightly and it's fixed, and sorry, i genuinely forgot i don't have to use the latest version of the compiler 🤦‍♂ (maybe it's partly because the previous one wasn't working either). and you'll understand what's wrong with me one day. i appreciate everyone's doing their job i'm not totally mental just give me 1 more day i promise you you'll see what's been going on but i realise i'm a step away from being banned here just please have a bit of compassion before judging.
