### ISSUE TITLE
--dependency_mode=STRICT no longer valid

### ISSUE THREAD

**Issue by NeilFraser** [google/closure-compiler#3534]
The [documentation states](https://github.com/google/closure-compiler/wiki/Managing-Dependencies#using---dependency_mode-to-drop-unreferenced-files) that one should use `--dependency_mode=STRICT` or `--dependency_mode=LOOSE`.

However, as of the most recent release, using this flag results in:
```
"STRICT" is not a valid value for "--dependency_mode"
Sample usage: --compilation_level (-O) VAL --externs VAL --js VAL --js_output_file VAL --warning_level (-W) [QUIET | DEFAULT | VERBOSE]
Run with --help for all options and details
```

`--help` reports that valid options are now `[NONE | SORT_ONLY | PRUNE_LEGACY | PRUNE]`, none of which is documented.

Surfaced by [Blockly Games issue 176](https://github.com/google/blockly-games/issues/176).

**Comment by tjgq** [comment]
Sorry about that. `PRUNE` and `PRUNE_LEGACY` are synonyms for the (first deprecated, and now removed) `STRICT` and `LOOSE`, respectively. The [flags page](https://github.com/google/closure-compiler/wiki/Flags-and-Options) was updated, but I forgot about this other wiki page. I've updated it myself.

**Comment by NeilFraser** [comment]
Thanks!
