### ISSUE TITLE
wrong context for static class method

### ISSUE THREAD

**Issue by ray007** [google/closure-compiler#3553]
I've been converting my old ES5 code to ES6, and I'm getting a warning that baffles me:

I have a static method which extracts xml from a data object:
```javascript
/**
 * get XML from loaded data (string or arraybuffer or xml)
 * @static
 * @private
 * @param {Object} data actual data is on property 'data'
 * @returns {Document|Element|Promise<Document>}
 */
static data2xml(data) {
	var xmlIn = data.data || data, s;
	if (xmlIn instanceof ArrayBuffer) {
		if (window.TextDecoder) {
			var a = new Uint8Array(xmlIn), td = new TextDecoder();
			s = td.decode(a);
			return /** @type {Document} */ (s && $.parseXML(s));
		}
		// no TextDecoder, go the long way
		xmlIn = new Blob([xmlIn], {type:'text/xml'});
	}
	if (xmlIn instanceof Blob) {
		return util.blob2txt(xmlIn).then($.parseXML);
	}
	// string or Element/Document
	if (!(xmlIn instanceof Element || xmlIn instanceof Document))
		xmlIn = $.parseXML(xmlIn);
	return xmlIn;
}
```
Then I'm trying to use it to decode a load result:
```p = this.loadAsset(lCfg).then(Project.data2xml);```

Which gives me a warning:
```
[13:06:55] gulp-google-closure-compiler: data/lweb_project.js:1872: WARNING - [JSC_TYPE_MISMATCH] actual parameter 1 of Promise.prototype.then does not match formal parameter
found   : function(this:(typeof module$data$project.default.Project), (Object|null)): (Document|Element|Promise<(Document|null)>|null)                              
required: (function(this:undefined, (Object|null)): ?|null|undefined)                                                                                                          
                                p = this.loadAsset(lCfg).then(Project.data2xml);                                                                                            
                                                              ^^^^^^^^^^^^^^^^                                                                                             
```
If I rewrite the call to
```p = this.loadAsset(lCfg).then(d => Project.data2xml(d));```
or add
```@this {undefined}```
to the doc-header of the static method, the warning goes away.

Is this a compiler type problem, or do I misunderstand something?

**Comment by shicks** [comment]
This looks like the compiler being extra conservative about how it treats static methods.  When you pass the method around, it ends up getting called differently - with `this` as `undefined`, rather than `Project`.  In your example, it's obvious enough that this is safe, but in general it's not.  By explicitly annotating the function as `@this {undefined}` you're telling the compiler that this is okay, and if you happen to use `this` in the body you'll get an appropriate warning.  And if you change the method reference to an arrow, you regain the "correct" value of `this`.

@nreid260 can possibly give more background.

**Comment by ray007** [comment]
I seem to have an understanding problem.
Since when do static methods have a meaningful `this` accessible?

**Comment by mprobst** [comment]
In ES6, `this` in a static method points to the class object.

**Comment by nreid260** [comment]
This is WAI. We infer `static` methods to have the type of their `this` parameter be the class. Doing so enables typechecking calls to other static methods within the first.

Possible solutions to yor situation:
      - Declare the function on a regular module, not a class.
      - Annotate the static method with `@this (*}` (or other "top-like" types)
      - Capture the call in an arrow (`(...x) => Project.data2xml(...x)`)

**Comment by ray007** [comment]
While using `this` in a static class method to recursively call itself works in the browser, it does not work with compiled code:
```
static buildTagCache(node, idCache) {
	if (!node || (node.nodeType !== 1)) return; // not an element node
	var nn = node.nodeName;
	if (nn === 'point' || nn === 'link') {
		// do some stuff
	}
	// search down
	util.do4children(node, n => {
		this.buildTagCache(n, idCache);
	});
}
```
has an `undefined` `this` at the child call.

**Comment by brad4d** [comment]
@ray007 
the fix for the broken `this` and `super` references in static methods is to enable a compiler option.
Unfortunately, there's no flag for it yet in `CommandLineRunner`. Maybe you'd like to add it?

I've just filed an issue for it.
https://github.com/google/closure-compiler/issues/3559

**Comment by Delilas56** [comment]
Null
