### ISSUE TITLE
How to map compiler warnings to JSDoc annotations?

### ISSUE THREAD

**Issue by juj** [google/closure-compiler#3554]
Closure compiler specifies warnings with [JSC_SOME_DIAGNOSTICS] tokens. 

https://github.com/google/closure-compiler/wiki/@suppress-annotations documents suppressions, and links to

https://github.com/google/closure-compiler/blob/master/src/com/google/javascript/jscomp/parsing/ParserConfig.properties#L155

but those do not match to the warning words that are issued.

Whenever I am looking to suppress a warning, like `JSC_INEXISTENT_PROPERTY` or `JSC_WRONG_ARGUMENT_COUNT` or `JSC_UNREACHABLE_CODE`, I go and cross-reference the above list, but struggle to find if a mapping exists or if the warning is one of the special ones that cannot be suppressed.

Would it be possible to have Closure either
a) generate warnings that are in the same format as https://github.com/google/closure-compiler/blob/master/src/com/google/javascript/jscomp/parsing/ParserConfig.properties#L155, or 
b) support `@suppress{JSC_INEXISTENT_PROPERTY}` annotations in the same format than what the compiler emits, or
c) document on the doc page what the mapping is from the `JSC_` properties to the JSDoc `@suppress{}` properties?

**Comment by lauraharker** [comment]
Probably we should generate documentation of the `JSC_` to `@suppress` tag mapping. https://github.com/google/closure-compiler/wiki/Flags-and-Options is already automatically generated as part of the release process.

There's an existing internal utility `MapDiagnosticToSuppression` that generates a JSON map from all suppressible `JSC_` errors to suppression based on [`DiagnosticGroups.java`](src/com/google/javascript/jscomp/DiagnosticGroups.java). It could be open sourced and made to generated Markdown.

For the meantime, I added https://github.com/google/closure-compiler/wiki/@suppress-annotations#error-to-suppression-map based on the output of `MapDiagnosticToSuppression`. Is that what you're looking for?

**Comment by juj** [comment]
Oh wow, great! Thanks @lauraharker a million, that reference is just amazing! You have no idea how much headache that will save me when doing warnings cleanup work.

This issue can be closed as fixed (although I wonder if that is a final solution, since that will require a manual workflow in place to keep that mapping reference up to date?)

Thanks again for the quick help, you saved my day :)
