### ISSUE TITLE
Canvas.cloneNode(deep) argument is optional

### ISSUE THREAD

**Issue by juj** [google/closure-compiler#3560]
In https://github.com/google/closure-compiler/blob/3d92d668e84d2e7767c523bd07a2dcc9ba35489c/externs/browser/gecko_dom.js#L430, the function parameter `deep` should be optional: https://developer.mozilla.org/en-US/docs/Web/API/Node/cloneNode

**Comment by brad4d** [comment]
@juj 
See the "Note" section a bit further down on the same MDN article you are referencing.

You should **always** provide the `deep` argument, even though it is technically optional.
I'm pretty sure this is why we require it.
