### ISSUE TITLE
Downloadmirror for latest version results in 404

### ISSUE THREAD

**Issue by SodY2** [google/closure-compiler#3561]
hey,

since today i cant reach anymore the "latest" download mirrors

https://dl.google.com/closure-compiler/compiler-latest.zip
https://dl.google.com/closure-compiler/compiler-latest.tar.gz

both result in 404

other "versioned" mirrors still work

best regards

**Comment by soleo** [comment]
I am having the same issue

**Comment by lauraharker** [comment]
Sorry about that, I made a typo while pushing a new release.

Should be fixed now.

**Comment by soleo** [comment]
This is almost the fourth time for this kind of issue in the past two years, perhaps you should consider automating publishing a new version. @lauraharker

**Comment by soleo** [comment]
Refer to https://github.com/google/closure-compiler/issues/3409 https://github.com/google/closure-compiler/issues/3072

**Comment by lauraharker** [comment]
I'll see how we can make this step less error-prone.
