### ISSUE TITLE
Closure compiler doesn't recognize `\u{XXXX}` in regular expression

### ISSUE THREAD

**Issue by upsuper** [google/closure-compiler#3563]
The following code:
```javascript
let x = /\u{ffff}/u;
```
would yield:
```
WARNING - [JSC_MALFORMED_REGEXP] Malformed Regular Expression: {ffff}
```
from closure compiler, but it's a valid regular expression, see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions/Character_Classes

**Comment by blickly** [comment]
Thanks for the report!
I think this might be a good starter issue for someone learning about the compiler.

**Comment by muachilin** [comment]
I am interested in handling this issue! Can I work on this? Thank you!

**Comment by blickly** [comment]
Sure, the `parsing` package is the right place to look.  I'd start with a unit test in:
https://github.com/google/closure-compiler/blob/master/test/com/google/javascript/jscomp/parsing/ParserTest.java

**Comment by VoronD** [comment]
Hi! I would like to start working on it.

**Comment by blickly** [comment]
Sounds good. Thanks!

I stand by my advice in https://github.com/google/closure-compiler/issues/3563#issuecomment-593548756 on where I'd recommend starting.

**Comment by lauraharker** [comment]
The original repro was completely fixed by https://github.com/google/closure-compiler/pull/3656 (thanks @VoronD!) so I'm closing this issue.

Please file a new issue if you find any remaining bugs.
