### ISSUE TITLE
Array.of can be optimized

### ISSUE THREAD

**Issue by bugreportuser** [google/closure-compiler#3566]
The compiler should always be able to optimize `Array.of` to `[]` when `language_out` is ES6. Is this something that can be added?

Example:

```js
function arrayOf(...values) {
    return Array.of(...values);
}
console.log(arrayOf(1, 2, 3));
```

```
$ closure-compiler --language_out ES6 --compilation_level ADVANCED array_of.js
```

Output (v20200224):

```js
'use strict';console.log(Array.of(...[1,2,3]));
```

Expected output:

```js
'use strict';console.log([1,2,3]);
```

**Comment by blickly** [comment]
This sounds like a valid optimization to me (regardless of the setting of language_out, isn't it?)

**Comment by bugreportuser** [comment]
@blickly Yes, you're right. I figured `Array.of` was standardized before array spread syntax, since I don't see why that function exists otherwise. If that were the case, this would have greatly increased output size.

Btw, are these optimizations performed late enough that errors such as this one would be preserved? The only reason I use `Array.of` is because [array literal types aren't inferred](https://github.com/google/closure-compiler/issues/312).

```js
const array = Array.of('1', '2', '3');
console.log(array[0] - array[1]);
```

```
$ closure-compiler --language_out ES6 --compilation_level ADVANCED --warning_level VERBOSE --jscomp_warning strictCheckTypes array_of.js
array_of.js:2: WARNING - [JSC_INVALID_OPERAND_TYPE] left operand
found   : string
required: number
console.log(array[0] - array[1]);
            ^^^^^^^^

array_of.js:2: WARNING - [JSC_INVALID_OPERAND_TYPE] right operand
found   : string
required: number
console.log(array[0] - array[1]);
                       ^^^^^^^^

0 error(s), 2 warning(s), 100.0% typed
'use strict';const array=Array.of("1","2","3");console.log(array[0]-array[1]);
```

**Comment by blickly** [comment]
The checks run before the optimizations, so adding this optimization shouldn't change any of the type checking results.

I think that since this can be done with just local knowledge, this could be done as a peephole optimziation, like those in:
https://github.com/google/closure-compiler/blob/master/src/com/google/javascript/jscomp/PeepholeReplaceKnownMethods.java

**Comment by bugreportuser** [comment]
That doesn't look too hard. I'll look into it when I have some time, if you haven't already implemented it by then.
