### ISSUE TITLE
non-standard IE Event.reason prototype breaks standard PromiseRejectionEvent.reason usage

### ISSUE THREAD

**Issue by vapier** [google/closure-compiler#3572]
the Event prototype has this old IE-only baggage:
```js
/** @type {number} */
Event.prototype.reason;
```

this doesn't exist at all in non-IE browsers, except for the new [`PromiseRejectionEvent` class](https://developer.mozilla.org/en-US/docs/Web/API/PromiseRejectionEvent):
* `PromiseRejectionEvent.reason`: A value or Object indicating why the promise was rejected, as passed to Promise.reject().

this conflict makes it difficult to work with the new [`unhandledrejection` event](https://developer.mozilla.org/en-US/docs/Web/API/Window/unhandledrejection_event) via the standard `addEventListener` interface:
```js
/**
 * @param {!Event} e
 * @return {boolean}
 */
const handler = (e) => {
  if (e.reason instanceof Object)
    return true;
  else
    return false;
};
window.addEventListener('unhandledrejection', handler);
```

closure has that API marked for taking an `Event` only, and closure also forces the ancient IE form, so this turns into a failure:
```sh
$ closure-compiler test.js --checks-only --language_in=ECMASCRIPT_2019 --jscomp_error='*'
test.js:6: ERROR - [JSC_TYPE_MISMATCH] deterministic instanceof yields false
found   : number
required: NoObject
  if (e.reason instanceof Object)
      ^^^^^^^^

1 error(s), 0 warning(s), 100.0% typed
```

**Comment by concavelenz** [comment]
Changing this to "?" (any) seems reasonable.  Do we know later IE version still support this?

**Comment by concavelenz** [comment]
@vapier Can you verify the change we made fully addresses the issues you were seeing?

**Comment by vapier** [comment]
the latest v20200504 release is working for me now, thanks
