### ISSUE TITLE
Compiler doesn't recognize dynamic import() 

### ISSUE THREAD

**Issue by tmb-github** [google/closure-compiler#3575]
Plain and simple, the Console Compiler does not recognize dynamic import(). It thinks all imports are static imports:

> ERROR - [JSC_PARSE_ERROR] Parse error. '}' expected
> import('./myModule.mjs').then(function {{default object}} {
> ^

Please prioritize :-)

**Comment by brad4d** [comment]
Perhaps you're using an older version of the compiler.

closure-compiler recognizes but does not support dynamic import.
Supporting dynamic import would require a very large change to the way closure-compiler generates output, and exactly what "support" means is likely quite different for different projects.
So, for now, we just refuse to accept it. Sorry.

https://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540compilation_level%2520SIMPLE_OPTIMIZATIONS%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250A%252F%252F%2520warns%2520%2526%2520errors%2520because%2520closure-compiler%2520explicity%2520does%2520not%2520support%250A%252F%252F%2520dynamic%2520import%250Aimport('foo').then(module%2520%253D%253E%2520console.log(module))%253B%250A%250A

**Comment by brad4d** [comment]
See also https://github.com/google/closure-compiler/issues/2770
