### ISSUE TITLE
Wiki's code sample for typedef annotation is wrong

### ISSUE THREAD

**Issue by DerekNonGeneric** [google/closure-compiler#3577]
The code sample for [the `@typedef` tag](https://github.com/google/closure-compiler/wiki/Annotating-JavaScript-for-the-Closure-Compiler#typedef-type) provided by the wiki is wrong.

It is currently displaying the following.

```javascript
/** 
 * @typedef {{
 *            foo:string,
 *            bar:number,
 *            foobar:number|string
 *          }}
 */
var Mytype;
```

This results in error because there are no parenthesis around the `|` operands.

I would PR the wiki if it were possible, so instead I've [demonstrated my proposed fix elsewhere](https://github.com/DerekNonGeneric/closure-compiler-wiki/pull/1/files).

**Comment by lauraharker** [comment]
Thanks for the report! I added parentheses to the example: https://github.com/google/closure-compiler/wiki/Annotating-JavaScript-for-the-Closure-Compiler/_compare/f933dd1632fbe3d1d0217fbc35d57da07b24f569...139296fdb6608615883ff4b5b99d90b3061fa372.

**Comment by DerekNonGeneric** [comment]
@lauraharker, thanks!

Might as well update [the one on the Annotating Types page](https://github.com/google/closure-compiler/wiki/Annotating-Types#typedef) while we're at it.

```javascript
/** 
 * @typedef {{
 *            foo:string,
 *            bar:number,
 *            foobar:number|string
 *          }}
 */
var Mytype;

/** @param {MyType} bar */
function foo(bar) {}
```

It has the same problem. :)

**Comment by lauraharker** [comment]
Nice catch! Thanks, fixed https://github.com/google/closure-compiler/wiki/Annotating-Types too.
