### ISSUE TITLE
Static methods in ES5 arguably mishandled by @extends

### ISSUE THREAD

**Issue by cpcallen** [google/closure-compiler#3582]
When using ES6 syntax, `@extends` understands that static methods are inherited; the following code [produces no warnings](https://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540compilation_level%2520ADVANCED_OPTIMIZATIONS%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250Aclass%2520Super%2520%257B%250A%2520%2520static%2520method()%2520%257B%250A%2520%2520%2520%2520return%2520'foo'%253B%250A%2520%2520%257D%250A%257D%250A%250A%252F**%250A%2520*%2520%2540extends%2520%257BSuper%257D%250A%2520*%252F%250Aclass%2520Sub%2520extends%2520Super%2520%257B%257D%250A%250Aconsole.log(Sub.method())%253B%2520%252F%252F%2520should%2520log%2520'foo'%250A):

```JS
class Super {
  static method() {
    return 'foo';
  }
}

/** @extends {Super} */
class Sub extends Super {}

console.log(Sub.method()); // should log 'foo'
```

… and optimises nicely to `console.log("foo");`.

When doing the same thing using ES5 syntax, however, static methods are assumed not to inherit, even when they they do, [causing a warning to be issued](https://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540compilation_level%2520ADVANCED_OPTIMIZATIONS%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250A%252F**%250A%2520*%2520%2540constructor%250A%2520*%252F%250Avar%2520Super%2520%253D%2520function()%2520%257B%257D%253B%250A%250ASuper.method%2520%253D%2520function()%2520%257B%250A%2520%2520return%2520'foo'%253B%250A%257D%250A%250A%252F**%250A%2520*%2520%2540constructor%250A%2520*%2520%2540extends%2520%257BSuper%257D%250A%2520*%252F%250Avar%2520Sub%2520%253D%2520function()%2520%257B%257D%253B%250AObject.setPrototypeOf(Sub%252C%2520Super)%253B%250AObject.setPrototypeOf(Sub.prototype%252C%2520Super.prototype)%253B%250A%250Aconsole.log(Sub.method())%253B%2520%252F%252F%2520should%2520log%2520'foo'%250A):

```JS
/** @constructor */
var Super = function() {};

Super.method = function() {
  return 'foo';
}

/** @constructor @extends {Super} */
var Sub = function() {};
Object.setPrototypeOf(Sub, Super);
Object.setPrototypeOf(Sub.prototype, Super.prototype);

console.log(Sub.method()); // should log 'foo'
```

I'm not sure what the correct thing to do is here, because I think most code doing ES5-style inheritance only worries about making sure that `Sub.prototype.__proto__` is `Super.prototype`, not about having `Sub.__proto__` be `Super`—but when using libraries like [Acorn](https://github.com/acornjs/acorn) that [depend on ES6-style inheritance of static methods](https://github.com/acornjs/acorn#plugin-developments) in ES5 code it would be preferable if there was some way to indicate that @extends also means to inherit static methods, so that all the static methods do not have to be redeclared on the subclass ([which at least works to suppress warnings, but doesn't help optimise the output](https://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540compilation_level%2520ADVANCED_OPTIMIZATIONS%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250A%252F**%250A%2520*%2520%2540constructor%250A%2520*%252F%250Avar%2520Super%2520%253D%2520function()%2520%257B%257D%253B%250A%250ASuper.method%2520%253D%2520function()%2520%257B%250A%2520%2520return%2520'foo'%253B%250A%257D%250A%250A%252F**%250A%2520*%2520%2540constructor%250A%2520*%2520%2540extends%2520%257BSuper%257D%250A%2520*%252F%250Avar%2520Sub%2520%253D%2520function()%2520%257B%257D%253B%250A%250AObject.setPrototypeOf(Sub%252C%2520Super)%253B%250AObject.setPrototypeOf(Sub.prototype%252C%2520Super.prototype)%253B%250A%250A%252F**%2520%2540override%2520*%252F%250ASub.method%253B%250A%250Aconsole.log(Sub.method())%253B%2520%252F%252F%2520should%2520log%2520'foo'%250A).)

**Comment by rishipal** [comment]
I believe this is WAI as JSCompiler disallows calling static class methods on a subclass that doesn’t define the method itself. 

For example:
class Base { /** @nocollapse */ static foo() {} }
class Sub extends Base {}
function callFoo(cls) { cls.foo(); }  // discouraged: don't call static methods dynamically
Sub.foo();  // Disallowed: don't call static methods on subclasses that don't define it themselves

You could work around it with module-local functions rather than private static methods if it's feasible and does not affect readability. 

Assigning to Bradford.

**Comment by cpcallen** [comment]
> Sub.foo(); // Disallowed: don't call static methods on subclasses that don't define it themselves

Given that—modulo a `@nocollapse`—this is basically the first example I gave above (which compiled without warnings or errors) I was pretty sure your claim was false, but I [went ahead and verified that](https://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540compilation_level%2520ADVANCED_OPTIMIZATIONS%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250Aclass%2520Base%2520%257B%2520%252F**%2520%2540nocollapse%2520*%252F%2520static%2520foo()%2520%257B%257D%2520%257D%250Aclass%2520Sub%2520extends%2520Base%2520%257B%257D%250Aconsole.log(Sub.foo())%253B%2520%252F%252F%2520Disallowed%253A%2520don't%2520call%2520static%2520methods%2520on%2520subclasses%2520that%2520don't%2520define%2520it%2520themselves).

> You could work around it with module-local functions rather than private static methods if it's feasible and does not affect readability.

None of these examples concern private static methods.  Since private fields/methods are not available in ES5 (or ES6, for that matter!) they could not be relevant to this bug report.

**Comment by brad4d** [comment]
@cpcallen 
**clarification**

> You could work around it with module-local functions rather than private static methods if it's feasible and does not affect readability.

"private" is not referring to the not-yet-standard `#classPrivateMethod` kind of privacy, but rather the `@private` annotation supported by closure-compiler.

**Comment by brad4d** [comment]
closure-compiler is meant to be paired with closure-library, and assumes that ES5 class inheritance will be done with the `goog.inherits()` method defined there.
The current behavior is consistent with that.

Unfortunately recognizing calls to `Object.setPrototypeOf()` and using that information in the type system is outside of the scope we're willing to support.

**Comment by cpcallen** [comment]
> "private" is not referring to the not-yet-standard `#classPrivateMethod` kind of privacy, but rather the `@private` annotation supported by closure-compiler.

Ahh, OK.  Not really relevant in this case, since none of these methods are `@private` either.

Obviously I could also call them via `Super.call(subclassInstance, ...args)`, but that's not very elegant.

> closure-compiler is meant to be paired with closure-library, and assumes that ES5 class inheritance will be done with the `goog.inherits()` method defined there.

Were I a closure-library user I'd file a bug report about `.inherits()`, too!

> The current behavior is consistent with that.
>
> Unfortunately recognizing calls to `Object.setPrototypeOf()` and using that information in the type system is outside of the scope we're willing to support.

Fair.  Were I to suggest a solution to this issue it would more likely be add new a new directive on the subclass constructor—perhaps `@extends @inheritStatic`—rather trying to detect it automagically, though of course the latter would be awfully nifty.

For the benefit of anyone else who runs in to the same issue and finds this bug report, there is an inelegant but useful work-around which [at least satisfies the type checker](https://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540compilation_level%2520ADVANCED_OPTIMIZATIONS%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250A%252F**%250A%2520*%2520%2540constructor%250A%2520*%252F%250Avar%2520Super%2520%253D%2520function()%2520%257B%257D%253B%250A%250A%252F**%2520%2540param%2520%257Bstring%257D%2520s%2520*%252F%250ASuper.method%2520%253D%2520function(s)%2520%257B%250A%2520%2520return%2520s%253B%250A%257D%250A%250A%252F**%250A%2520*%2520%2540constructor%250A%2520*%2520%2540extends%2520%257BSuper%257D%250A%2520*%252F%250Avar%2520Sub%2520%253D%2520function()%2520%257B%257D%253B%250AObject.setPrototypeOf(Sub%252C%2520Super)%253B%250AObject.setPrototypeOf(Sub.prototype%252C%2520Super.prototype)%253B%250A%250A%252F**%2520%2540override%2520%2540param%2520%257Bstring%257D%2520s%2520*%252F%250ASub.method%253B%250A%250Aconsole.log(Sub.method(200))%253B%2520%252F%252F%2520Gives%2520TYPE_MISMATCH%2520warning.), even if it doesn't result in the nicely-optimised output of the ES6 version: just redeclare the static methods on the subclass, like this:

```JS
/** @constructor */
var Super = function() {};

/** @param {string} s */
Super.method = function(s) {
  return s;
}

/**
 * @constructor
 * @extends {Super}
 */
var Sub = function() {};
Object.setPrototypeOf(Sub, Super);
Object.setPrototypeOf(Sub.prototype, Super.prototype);

/** @override @param {string} s */
Sub.method;

console.log(Sub.method(200)); // Gives TYPE_MISMATCH warning.
```
