### ISSUE TITLE
Advanced compilation removes export function arguments

### ISSUE THREAD

**Issue by trofim24** [google/closure-compiler#3584]
I use latest version `v20200406` of closure compiler.
Command for compilation: `java -jar closure-compiler-v20200406.jar --compilation_level=ADVANCED_OPTIMIZATIONS --js=with-bug.js`

Code in file `with-bug.js`:
```
function MyClass() {
  this.myField = null;
}

MyClass.prototype["putMyField"] = MyClass.prototype.putMyField = function (val) {
  this.myField = val;
};
MyClass.prototype["myMethod"] = MyClass.prototype.myMethod = function (myArgument) {
  if (undefined === myArgument) {
      myArgument = this.myField;
  }
  return "myMethod with argument: " + myArgument;
};

function globalMyMethod(oMyClass) {
  return oMyClass.myMethod();
}

window["MyClass"] = MyClass;
window["globalMyMethod"] = globalMyMethod;
```
After compilation export function `myMethod` lost argument:
`function b(){this.a=null}b.prototype.putMyField=function(a){this.a=a};b.prototype.myMethod=b.prototype.b=function(){if(void 0===a)var a=this.a;return"myMethod with argument: "+a};window.MyClass=b;window.globalMyMethod=function(a){return a.b()};`

But if you transfer the export of the function after it is declared, then everything will be fine

Command for compilation: `java -jar closure-compiler-v20200406.jar --compilation_level=ADVANCED_OPTIMIZATIONS --js=without-bug.js`
Code in file `without-bug.js`:
```
function MyClass() {
  this.myField = null;
}

MyClass.prototype["putMyField"] = MyClass.prototype.putMyField = function (val) {
  this.myField = val;
};
MyClass.prototype.myMethod = function (myArgument) {
  if (undefined === myArgument) {
      myArgument = this.myField;
  }
  return "myMethod with argument: " + myArgument;
};

function globalMyMethod(oMyClass) {
  return oMyClass.myMethod();
}

window["MyClass"] = MyClass;
MyClass.prototype["myMethod"] = MyClass.prototype.myMethod;
window["globalMyMethod"] = globalMyMethod;
```

After compilation export function `myMethod` did not lose argument:
`function b(){this.a=null}b.prototype.putMyField=function(a){this.a=a};b.prototype.b=function(a){void 0===a&&(a=this.a);return"myMethod with argument: "+a};window.MyClass=b;b.prototype.myMethod=b.prototype.b;window.globalMyMethod=function(a){return a.b()};`

**Comment by brad4d** [comment]
I'm working on a fix for this.
I actually have a change that will fix this specific problem already, but there are other cases I've noticed are also broken, so I'm working toward a more robust solution.
