### ISSUE TITLE
String.prototype.matchAll polyfill added when using Clients.matchAll

### ISSUE THREAD

**Issue by wesleyorbin** [google/closure-compiler#3585]
Hi there! When upgrading from `v20191111` to any of the 2020 builds, I noticed that the `String.prototype.matchAll` polyfill is being added to our service worker inappropriately. We use the [Clients.matchAll()](https://developer.mozilla.org/en-US/docs/Web/API/Clients/matchAll) method in our service worker and I believe the compiler may be confusing this method for the String method. Because our service worker is relatively lightweight, the polyfill adds a significant amount to its size (~800 bytes gzipped). It appears that the `String.prototype.matchAll` polyfill was added in the `20200101` release.

Here are our compiler flags:
`language_in: 'ECMASCRIPT6_STRICT'`
`language_out: 'ECMASCRIPT6'`
`compilation_level: 'ADVANCED'`
`module_resolution: 'BROWSER'`
`dependency_mode: 'STRICT'` (change to `PRUNE` when upgrading to 2020 builds)

**Comment by shicks** [comment]
Do you have an extern for this method?  The compiler will add the polyfill any time it can't guarantee that the method is _not_ `string`.  So if the type is `?` then it's going to add it.  Another thing you could try is to define a `@record` or `@interface` with `matchAll()` of the correct type and cast `Clients` to that before calling `matchAll` on it.  This isn't a great long-term solution, but it might help troubleshoot if you give it a try and report back whether it works or not.

**Comment by shicks** [comment]
FWIW, I found that the following externs prevented the polyfill from being injected:
```
/** @externs */
const Clients = {};
Clients.matchAll = function(...args) {};
```
whereas if `Clients` is only externed as a non-const `var` (which causes the compiler to treat it like a variable rather than a namespace) then the polyfill is injected.  So this seems like it should fix your issue.

**Comment by shicks** [comment]
If you want to contribute the extern as a PR, you're welcome to.  Otherwise, providing it yourself should at least fix your issue.
