### ISSUE TITLE
Path2D externs definition is missing optional constructor arguments

### ISSUE THREAD

**Issue by timdawborn** [google/closure-compiler#3598]
The `Path2D` constructor has an optional argument that is either a string or another `Path2D` object: https://developer.mozilla.org/en-US/docs/Web/API/Path2D/Path2D

The externs are currently missing this https://github.com/google/closure-compiler/blob/master/externs/browser/html5.js#L264

Version: any version of Closure.

**Comment by blickly** [comment]
Thanks for the report!

I'm hoping fixing this would be relatively easy to land.  Care to send a PR?

**Comment by timdawborn** [comment]
No worries. See linked PR.
