### ISSUE TITLE
Function names renaming reports?

### ISSUE THREAD

**Issue by juj** [google/closure-compiler#3600]
I would like to generate a `unmangled:mangled` name mapping file specifying what functions Closure minified. Is there a way to generate a renaming report of function names?

If I pass the documented [--property-renaming-report](https://github.com/google/closure-compiler/wiki/Flags-and-Options#reports) flag, I can get a file with property renames:
```
ABORT:J
ENVIRONMENT_IS_NODE:t
ENVIRONMENT_IS_SHELL:u
ENVIRONMENT_IS_WEB:q
ENVIRONMENT_IS_WORKER:r
ExitStatus:D
HEAP32:M
HEAPU8:L
INITIAL_INITIAL_MEMORY:N
...
```
and so on.

If I pass the documented `--variable_renaming_report` flag, I get a similar file with variable renames.

If I pass the undocumented flag `--create_renaming_reports=true`, that seems to enable both of the above.

If I do `--create_source_map output.map`, I can get a source map, that does contain the renaming info. However source writing a source map loader to is quite a complicated task, I think I would need to write a JS AST parser to be able to walk the mappings back to the unmapped names.

I wonder if there would exist a flag to achieve function renaming reports already, perhaps I am missing something?

**Comment by concavelenz** [comment]
I'm unclear what you are looking for that isn't provided.  For example, what is different from what you would like to see than what is provided by the "variable renaming report".  It might be helpful, if you stated *why* you wanted the information.

**Comment by juj** [comment]
The information that variable renaming report provides seems to be somehow partial. It does not contain all renamed functions or variables, not sure what is the common denominator of what's not there.

That all being said, I ended up going the way of writing an AST parser to extract the information via source maps, so can close this.
