### ISSUE TITLE
Resduce size of compiled Javascript by factoring "this" when it is massively ued in function

### ISSUE THREAD

**Issue by SuperPat45** [google/closure-compiler#3604]
Currently, if I compile:
```
function hello() {
  this.test1();
  this.test2();
  this.test3();
  this.test4();
  this.test5();
}
hello();
```
Closure compiler generate:
`function hello(){this.test1();this.test2();this.test3();this.test4();this.test5()}hello();`

It can be optimized like this where there are more than 4 this in a function:
`function hello(){var t=this;t.test1();t.test2();t.test3();t.test4();t.test5()}hello();`

I see a function where "this" is used 95 times...

**Comment by brad4d** [comment]
We'll be happy to entertain a PR to implement this, but it is unlikely to become a priority for us.

**Comment by kittenswolf** [comment]
This is unnessecary and even increases output size as the compiler assumes you use gzip.

> Closure Compiler assumes that you are using gzip compression.

(https://github.com/google/closure-compiler/wiki/FAQ#closure-compiler-inlined-all-my-strings-which-made-my-code-size-bigger-why-did-it-do-that)

**Comment by brad4d** [comment]
We had an "alias keyword" pass once before, but it did more harm than good.
It tended to undermine optimizations done by the JS engines.
