### ISSUE TITLE
Turf JSTS Object.defineProperties crash

### ISSUE THREAD

**Issue by andrewboltachev** [google/closure-compiler#3612]
Turf JSTS is part of turf.js project: https://github.com/DenisCarriere/turf-jsts

If you download it and run `yarn`, this would produce `jsts.min.js` file. I made a beautified version here. https://www.dropbox.com/s/01w0n8uudtccorj/jsts.min.beautified.js?dl=0

GCC ( da0872e ) would crash on that file. Example line is 11714, 11800 etc, where `Object.defineProperties` is.

---
Minimal similar code which would fail looks something like this:
```js
function aa() {
    var a = {}, b = null;
    a.a = 1,
    b.a = 2,
    Object.defineProperties(a, b);
}
```

Not sure what the problem is. Please help

**Comment by andrewboltachev** [comment]
@concavelenz I confirm, my actual stacktrace is exactly the same as above one

**Comment by concavelenz** [comment]
great, thanks for the report.

**Comment by concavelenz** [comment]
I can get it to reproduce here:

https://closure-compiler-debugger.appspot.com/#input0%3Dfunction%2520aa()%2520%257B%250A%2520%2520%2520%2520var%2520a%2520%253D%2520%257B%257D%252C%2520b%2520%253D%2520null%253B%250A%2520%2520%2520%2520a.a%2520%253D%25201%252C%250A%2520%2520%2520%2520b.a%2520%253D%25202%252C%250A%2520%2520%2520%2520Object.defineProperties(a%252C%2520b)%253B%250A%257D%250A%250Aalert(aa)%26input1%26conformanceConfig%26externs%3Dvar%2520alert%26refasterjs-template%26includeDefaultExterns%3Dtrue%26TRANSPILE%3Dtrue%26REMOVE_UNUSED_VARIABLES%3Dtrue%26SMART_NAME_REMOVAL%3Dtrue%26CLOSURE_PASS%3Dtrue

But occasionally it succeeds, there seems to be some kind of nondeterminism.
