### ISSUE TITLE
Travis CI has been failing ever since May 27

### ISSUE THREAD

**Issue by teppeis** [google/closure-compiler#3613]
The last successful build: https://travis-ci.org/github/google/closure-compiler/builds/691538538
Due to this problem, no nightly packages have been made since May 27.
https://www.npmjs.com/package/google-closure-compiler?activeTab=versions

Is anyone working on this issue?

**Comment by rrdelaney** [comment]
[Should be fixed now](https://travis-ci.org/github/google/closure-compiler/builds/696648256) 😄 Sorry about the interruption!

**Comment by teppeis** [comment]
@rrdelaney thanks!
