### ISSUE TITLE
No "Missing return statement" warning for function with empty body

### ISSUE THREAD

**Issue by vobruba-martin** [google/closure-compiler#3617]
```javascript
/**
 * @return {number}
 */
function fn() {}
```
`0 error(s), 0 warning(s), 100.0% typed`

```javascript
/**
 * @return {number}
 */
function fn() {
	console.log('');
}
```
```
test.js:4: WARNING - [JSC_MISSING_RETURN_STATEMENT] Missing return statement. Function expected to return number.
  4| function fn() {
     ^^^^^^^^^^^^^^^
  5| 	console.log('');
     ^^^^^^^^^^^^^^^^^
  6| }
     ^

0 error(s), 1 warning(s), 100.0% typed
```

**Comment by concavelenz** [comment]
This is, unfortuately, a long standing bug and was stupid hack to land it back in the day. We should just fix it and move on.

**Comment by lauraharker** [comment]
We tested how much effort it would take to fix this within the Google repo. Unfortunately there are more new errors than we have time to fix/suppress, so we don't think we can invest time into fixing this issue.
