### ISSUE TITLE
Static 'this' is not define

### ISSUE THREAD

**Issue by NoobSolver** [google/closure-compiler#3638]
While using this in a static class method to recursively call itself works in the browser, it does not work with compiled code:

static buildTagCache(node, idCache) {
	if (!node || (node.nodeType !== 1)) return; // not an element node
	var nn = node.nodeName;
	if (nn === 'point' || nn === 'link') {
		// do some stuff
	}
	// search down
	util.do4children(node, n => {
		this.buildTagCache(n, idCache);
	});
}

has an undefined this at the child call.

**Comment by niloc132** [comment]
It appears that this is how the compiler authors expect this to function, see the discussion in https://github.com/google/closure-compiler/issues/3553, and the follow up to improve logging in https://github.com/google/closure-compiler/issues/3559.

**Comment by rrdelaney** [comment]
Thanks for pointing to the discussion @niloc132!

@NoobSolver this is working as intended. Static methods cannot refer to `this`.

**Comment by NoobSolver** [comment]
Thanks for the help @niloc132
