### ISSUE TITLE
Travis deploy_snapshot.sh step sporadically failing

### ISSUE THREAD

**Issue by lauraharker** [google/closure-compiler#3646]
Deploying the most recent snapshot via Maven has been failing roughly half the time. The failure occurs while running https://github.com/google/closure-compiler/blob/master/travis_util/deploy_snapshot.sh.

Note that we don't deploy snapshots for builds from PRs, so this isn't blocking any new PRs from being tested.

Example of a successful build: https://travis-ci.org/github/google/closure-compiler/builds/709325916

Example of a failure: https://travis-ci.org/github/google/closure-compiler/builds/709265015

```
[INFO] --- maven-compiler-plugin:3.5.1:compile (default-compile) @ [secure]-gwt ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 779 source files to /home/travis/build/google/[secure]/target/classes
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received
The build has been terminated
```

I also found a build that passed Travis, but OOMed instead of successfully deploying a snapshot: https://travis-ci.org/github/google/closure-compiler/builds/708968448

```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Closure Compiler Parent ............................ SUCCESS [  4.003 s]
[INFO] Closure Compiler Externs ........................... SUCCESS [  3.330 s]
[INFO] Closure Compiler GWT App ........................... FAILURE [  8.166 s]
[INFO] Closure Compiler Main .............................. SKIPPED
[INFO] Closure Compiler Linter ............................ SKIPPED
[INFO] Closure Compiler Unshaded .......................... SKIPPED
[INFO] Closure Compiler ................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 24.270 s
[INFO] Finished at: 2020-07-17T00:04:54Z
Java HotSpot(TM) 64-Bit Server VM warning: INFO: os::commit_memory(0x00000000e7380000, 79691776, 0) failed; error='Cannot allocate memory' (errno=12)
```

**Comment by lauraharker** [comment]
I don't see any snapshots in https://oss.sonatype.org/content/repositories/snapshots/com/google/javascript/closure-compiler/1.0-SNAPSHOT/ since July 20th.

The most recent version is `closure-compiler-1.0-20200720.202227-820.pom | Mon Jul 20 20:22:32 UTC 2020 | 5508`.

Looks like the "passing" travis builds from the last two days failed the snapshot upload step with:

```
[INFO] --- gwt-maven-plugin:1.0-rc-6:compile (default-compile) @ [secure]-gwt ---
[INFO] Compiling module com.google.JsComp
[INFO] #
[INFO] # There is insufficient memory for the Java Runtime Environment to continue.
[INFO] # Native memory allocation (mmap) failed to map 174063616 bytes for committing reserved memory.
[INFO] # An error report file with more information is saved as:
[INFO] # /home/travis/build/google/[secure]/target/hs_err_pid16043.log
[WARNING] Java HotSpot(TM) 64-Bit Server VM warning: INFO: os::commit_memory(0x00000000e2d00000, 174063616, 0) failed; error='Cannot allocate memory' (errno=12)
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Closure Compiler Parent ............................ SUCCESS [  3.739 s]
[INFO] Closure Compiler Externs ........................... SUCCESS [  7.984 s]
[INFO] Closure Compiler GWT App ........................... FAILURE [01:01 min]
[INFO] Closure Compiler Main .............................. SKIPPED
[INFO] Closure Compiler Linter ............................ SKIPPED
[INFO] Closure Compiler Unshaded .......................... SKIPPED
[INFO] Closure Compiler ................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:21 min
[INFO] Finished at: 2020-07-22T17:41:12Z
[INFO] Final Memory: 32M/368M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal net.ltgt.gwt.maven:gwt-maven-plugin:1.0-rc-6:compile (default-compile) on project [secure]-gwt: GWT Compiler exited with status 1 -> [Help 1]
```

It seems odd to me that the deploy step is even building the GWT app, since I don't believe we deploy any of its artifacts to Maven.

**Comment by lauraharker** [comment]
I'll try running mvn deploy locally. I just need to figure out how to set up the credentials.

> It seems odd to me that the deploy step is even building the GWT app, since I don't believe we deploy any of its artifacts to Maven.

Never mind, I was missing https://oss.sonatype.org/content/repositories/snapshots/com/google/javascript/closure-compiler-gwt/

**Comment by lauraharker** [comment]
mvn deploy worked on my machine. New latest snapshot version is `closure-compiler-1.0-20200723.181428-821.pom | Thu Jul 23 18:14:30 UTC 2020 | 5508`.

So this is specific to the Travis setup.

These errors correlate with adding the J2CL build of the compiler.

https://travis-ci.org/github/google/closure-compiler/builds/703962937 is the first successful Travis build after adding J2CL (after https://github.com/google/closure-compiler/commit/c2360522206908a8fd6a244c781e594d49eb82b5 fixed the Travis build). It times out during mvn deploy.

**Comment by lauraharker** [comment]
@gkdn  do you think that Bazel workers running could be causing the `There is insufficient memory for the Java Runtime Environment to continue.` problems?

The last step in Travis before deploying builds the J2CL compiler via Bazel, and https://github.com/google/closure-compiler/blob/master/.bazelrc enables workers.

**Comment by concavelenz** [comment]
Perhaps we should just avoid workers in Travis?

**Comment by gkdn** [comment]
I would expect workers to speed up your build so probably it is not a good idea to disable them.
Also shutting down bazel in build_test.sh is not ideal since it might slow down who are using that for development.
However we can do a shutdown Bazel after bazel build is completed in Travis (if you are suspecting that's the root cause).

IIRC, also you are using an old image in Travis and updating that will generally improve things; potentially this one as well.

**Comment by lauraharker** [comment]
https://github.com/google/closure-compiler/commit/ffaa91068c0ea48bf146d3a5503940d80b04eec9 breaks Travis:

```
0.26s$ bazel shutdown
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=0 --terminal_columns=80
INFO: Reading rc options for 'shutdown' from /home/travis/build/google/[secure]/.bazelrc:
  Inherited 'common' options: --noshow_progress --noshow_loading_progress
ERROR: Unrecognized option: --noshow_loading_progress
The command "bazel shutdown" exited with 2.
```

**Comment by gkdn** [comment]
You can probably do `bazel --bazelrc=/dev/null shutdown`

**Comment by lauraharker** [comment]
Closing this issue. I don't see any new occurrences since https://github.com/google/closure-compiler/pull/3648.

Out of 12 Travis builds, 10 succeeded & deployed the snapshot to Maven. Two builds failed early on with what look like transient failures.
