### ISSUE TITLE
Download link on Closure homepage is broken

### ISSUE THREAD

**Issue by TomasRiker** [google/closure-compiler#3663]
The [download link](https://dl.google.com/closure-compiler/compiler-latest.zip) on [Closure's homepage](https://developers.google.com/closure/compiler) is broken.

**Comment by brad4d** [comment]
There's also a broken link on this page.

https://developers.google.com/closure/compiler/docs/gettingstarted_app

**Comment by brad4d** [comment]
The Maven repo containing all releases is at https://mvnrepository.com/artifact/com.google.javascript/closure-compiler

There doesn't seem to be a "latest" alias for the most recent release, so users will have to select the version they want.

**Comment by hanguokai** [comment]
Similar to Maven, https://unpkg.com/ is a tool site for NPM.

You can browse package files at https://unpkg.com/browse/google-closure-compiler-java/ , it will redirect automatically to the latest version, e.g. https://unpkg.com/browse/google-closure-compiler-java@20200719.0.0/ .

You can download the latest jar file at https://unpkg.com/google-closure-compiler-java/compiler.jar , it will redirect automatically to the latest version, e.g. https://unpkg.com/google-closure-compiler-java@20200719.0.0/compiler.jar

**Comment by hanguokai** [comment]
Note, although mvnrepository.com and unpkg.com are perfect for developers, they looks like developed and maintained by individual developers(https://twitter.com/frodriguez and https://twitter.com/mjackson).

**Comment by hanguokai** [comment]
Another jar download link is https://repo1.maven.org/maven2/com/google/javascript/closure-compiler/ . I found that mvnrepository.com is often delayed some time after a new release, but repo1.maven.org is always up to date. If you only want to download a jar file, this is better.
