### ISSUE TITLE
Travis build failing inconsistently

### ISSUE THREAD

**Issue by patrick-sko** [google/closure-compiler#3667]
The Travis build has been failing rather inconsistently for the last several days. The issue however seems to be consistent.

First build I found which contained the consistent error: https://travis-ci.org/github/google/closure-compiler/builds/721390007

The error I am seeing in the log states that 
```
WARNING: Download from http://bazel-mirror.storage.googleapis.com/repo1.maven.org/maven2/com/google/errorprone/error_prone_annotations/2.3.2/error_prone_annotations-2.3.2.jar failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
WARNING: Download from http://bazel-mirror.storage.googleapis.com/repo1.maven.org/maven2/com/squareup/javapoet/1.13.0/javapoet-1.13.0.jar failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
```

With the following final error message:
```
ERROR: /home/travis/build/google/[secure]/BUILD.bazel:166:1: Compiling 14 JavaScript files to compiler-j2cl.js failed: Worker process did not return a WorkResponse:
```

It seems to be an issue with the Bazel build.

**Comment by ohbus** [comment]
Is there by any chance I can work on migrating the Pipeline to github actions, while somebody tries to make the travis CI work.

**Comment by lauraharker** [comment]
Closing in favor of https://github.com/google/closure-compiler/issues/3669.

@ohbus I think @ChadKillingsworth might be looking into GitHub actions. Chad, is that right?
