### ISSUE TITLE
Transpilation of `**` breaks operations using BigInt

### ISSUE THREAD

**Issue by brad4d** [google/closure-compiler#3684]
If you specify a `--language_out` lower than `ES_2016` for code that uses BigInt, the compiler will generate broken code for `**` operations on bigint values.

The compiler will convert
```
BigInt(2) ** BigInt(n)
```
To:
```
Math.pow(BigInt(2), BigInt(n))
```

**Comment by brad4d** [comment]
The intention of closure-compiler team is that the target environment for any code that uses BigInt must be an environment that actually supports BigInt. The compiler will not make any attempt to polyfill it.

If you use BigInt literals in your code, but set the `--language_out` lower than `ES_2020`, then the compiler will report an error and refuse to compile your code. This avoids the problem described in this issue.

However, the compiler intentionally ignores uses of `BigInt()` to generate BigInt values. This is an intentional workaround that people had already been using before we officially supported BigInt. Basically, if you do this, we're trusting you are intentionally trying to work with an environment where you know BigInt is supported despite the `--language_out` you've given us.

I think the solution in this case is to modify the pass that transpiles `**` so that it checks the type of the arguments and reports an error if they are `BigInt` instead of actually transpiling.

**Comment by rishipal** [comment]
Fixed with d7d362cedf23af7d3ffde2ff446dee9ef8f1c142.
