### ISSUE TITLE
Typo in Documentation

### ISSUE THREAD

**Issue by TaneishaArora** [google/closure-compiler#3685]
"Additionally" is misspelled as "Additinally" in the last paragraph of the documentation on [this](https://developers.google.com/closure/compiler/docs/api-tutorial3) page. I have highlighted it in the screen cap below:

![image](https://user-images.githubusercontent.com/12291197/92684742-0bf40800-f2eb-11ea-81df-cd8f056671b2.png)

**Comment by rishipal** [comment]
Thanks, fixed.
