### ISSUE TITLE
Build instructions in README.md are no longer correct

### ISSUE THREAD

**Issue by brad4d** [google/closure-compiler#3691]
@nreid260 has updated our build to be entirely done with `bazel`. The `mvn` command is only used for pushing releases and snapshots to sonatype where users can download them.

However, the build instructions haven't been updated.

https://github.com/google/closure-compiler/blob/master/README.md

I made a couple of educated guesses at how to do the bazel build, but so far have not been successful.

For example:

```
$ bazel build //:compiler_unshaded
...
ERROR: Analysis of target '//:compiler_unshaded' failed; build aborted: Either the path attribute of android_sdk_repository or the ANDROID_HOME environment variable must be set.
```

**Comment by rrdelaney** [comment]
I believe Nick fixed this.
