### ISSUE TITLE
assume_function_wrapper doesn't seem to do anything

### ISSUE THREAD

**Issue by fstanis** [google/closure-compiler#3692]
With `SIMPLE_OPTIMIZATIONS` the following input:

```
(function(){
  const foobar = 'hello';
  console.log(document.title + foobar);
})();
```

...compiles into

```
(function() {
  console.log(document.title + "hello");
})();
```

However, the following input:
```
const foobar = 'hello';
console.log(document.title + foobar);
```

...remains the same, even when I set `assume_function_wrapper`.

Am I missing something here? I thought `assume_function_wrapper` would have the same result as the previous sample where I actually wrap my code inside a function.

**Comment by rishipal** [comment]
With `--assume_function_wrapper`, the JSCompiler inlines variable `foobar` into the `console.log`'s arg.
Output: 
`console.log(document.title+"hello");`

Are you seeing otherwise? 

Or, is your expectation that the output JS is generated as an IFFE, like in your first example?

**Comment by fstanis** [comment]
Sorry, my bad: I double-checked and it seems `assume_function_wrapper` is working as expected. I was originally testing with https://closure-compiler.appspot.com/ which doesn't seem to support it.
