### ISSUE TITLE
The class com.google.javascript.jscomp.ant.CompileTask is missing in the current release v20200920

### ISSUE THREAD

**Issue by kozi** [google/closure-compiler#3697]
The class `com.google.javascript.jscomp.ant.CompileTask` is **missing** in the current release **v20200920**

Is this correct? How can i solve this?

Downloaded the release jar from the linked maven repo.

**Comment by brad4d** [comment]
@nreid260 I suspect when you moved the build from `mvn` to `bazelisk` this `CompileTask` file got dropped from the rules for building the jar file.

@kozi, out of curiosity, does your interest in `CompileTask` indicate that you run closure-compiler via `ant` somehow?
AFAICT, we don't use it for anything, and it appears to have no associated tests.
I'm very surprised to find that anyone uses it, and more surprised to find it actually works with no tests to ensure that.

**Comment by nreid260** [comment]
I think this easy to fix; the sources just aren't being passed to //:compiler_lib.

It does raise some questions though as @brad4d has mentioned. The code in question hasn't been touched in years and isn't being tested. 

This big thing that surprises me is that the compiler artifacts would contain this ANT task when they're supposed to be CLI tools. I wish there were a better separation between the business logic that is "the compiler" and the various interfaces for running it.
