### ISSUE TITLE
RefasterJS code isn't really supported

### ISSUE THREAD

**Issue by brad4d** [google/closure-compiler#3702]
A helpful user on closure-compiler-discuss asked us about whether RefasterJS is still supported.

https://groups.google.com/g/closure-compiler-discuss/c/FtT2Y4Bi2CI/m/qeYtZYpZCAAJ

Sadly it appears the answer is, "no".

1. We haven't done development on RefasterJS in more than 4 years.
1. Our wiki page for it is 2 sentences and a link to a Google Doc that has instructions for building it with ant (!), which is 2 build systems ago for us. We switched from ant to Maven sometime before 2016 and recently switched again to bazel, which is much easier for us to maintain.
1. The ant build configuration is long gone, so there's no published way to build it.
1. This also means there is no testing to confirm it continues working.
1. We haven't published a binary form of it since 2015.

Several members of the team discussed this problem today and agreed that it would be best to drop the sources from our repository. It does significantly more harm than good for us to publish code that we don't really intend to maintain.

If interested users would like to grab the sources from our repo, work out how to build them, and start supporting it themselves, they are of course welcome to do so.

Work to be done to clean this up includes.

1. Officially announce on closure-compiler-discuss that RefasterJS is not supported.
1. Change the Wiki page about it to say it is no longer supported and drop the link to the Google Doc.
1. Put a big warning at the top of the Google Doc to point out it isn't supported. (Someone might have saved a link to it.)
1. Drop the compiled binary link from the downloads page. It's way too old to be useful with today's JS.
1. Drop the source files from our repository.

**Comment by brad4d** [comment]
Announcement sent
https://groups.google.com/g/closure-compiler-discuss/c/fbDw5jjs2MQ/m/bhHJPh6hAQAJ

**Comment by brad4d** [comment]
Wiki page and Google Doc updated.
All I could do on the Google Doc was add a suggestion and a comment.
I can't tell who owns the doc, but I've requested sharing access, so maybe I'll get a response to that.

**Comment by brad4d** [comment]
There don't actually seem to be any links to the RefasterJS binary on our downloads page, just in the Google Doc.
I've left a comment there saying I expect to delete the file shortly.

I think I'll give it just a few days for people to see the announcement before I actually remove the file (and all the older ones).

Incidentally, it looks like the most recent build was from 2015-07-06.
The one before that was 2014-11-21.
So, this was never really kept up-to-date.

**Comment by brad4d** [comment]
I'll also wait a week or so before actually removing the source files.

**Comment by QizorQ8** [comment]
> A helpful user on closure-compiler-discuss asked us about whether RefasterJS is still supported.
> 
> https://groups.google.com/g/closure-compiler-discuss/c/FtT2Y4Bi2CI/m/qeYtZYpZCAAJ
> 
> Sadly it appears the answer is, "no".
> 
> 1. We haven't done development on RefasterJS in more than 4 years.
> 2. Our wiki page for it is 2 sentences and a link to a Google Doc that has instructions for building it with ant (!), which is 2 build systems ago for us. We switched from ant to Maven sometime before 2016 and recently switched again to bazel, which is much easier for us to maintain.
> 3. The ant build configuration is long gone, so there's no published way to build it.
> 4. This also means there is no testing to confirm it continues working.
> 5. We haven't published a binary form of it since 2015.
> 
> Several members of the team discussed this problem today and agreed that it would be best to drop the sources from our repository. It does significantly more harm than good for us to publish code that we don't really intend to maintain.
> 
> If interested users would like to grab the sources from our repo, work out how to build them, and start supporting it themselves, they are of course welcome to do so.
> 
> Work to be done to clean this up includes.
> 
> 1. Officially announce on closure-compiler-discuss that RefasterJS is not supported.
> 2. Change the Wiki page about it to say it is no longer supported and drop the link to the Google Doc.
> 3. Put a big warning at the top of the Google Doc to point out it isn't supported. (Someone might have saved a link to it.)
> 4. Drop the compiled binary link from the downloads page. It's way too old to be useful with today's JS.
> 5. Drop the source files from our repository.

**Comment by brad4d** [comment]
@QizorQ8 thanks for the reminder.

**Comment by mkoryak** [comment]
There is a still a link to this tool from the wiki here:

https://github.com/google/closure-compiler/wiki/ at the very bottom
