### ISSUE TITLE
What is the best way to use google closure compiler?

### ISSUE THREAD

**Issue by classydraught** [google/closure-compiler#3705]
I have been using google-closure-compile@20201006.0.0 for quite a time. Since the start, I use it with a jar file (basically using JAVA).

example: `java -jar node_modules/google-closure-compiler-java/compiler.jar --file.js`

Recently I tried to compile it using npx

example : `npx google-closure-compiler --file.js`
And to my wonder, it was the fastest compilation to date. It just took me a few seconds to make a build whereas previously it used to take 2-3 minutes.

So my doubt is what is the best way to use google-closure-compiler as now because of the speed I feel like It's not that compiling with npx is not that powerful as java.

**Comment by concavelenz** [comment]
We deploy the compiler in two forms: the java version and the "graal native-image" versions.  The "native image" version don't require installing the JVM and are optimized as part of the build so they benefit from fast startup time.    In my tests when we first deployed this, the JVM versions would outperform the native-image version for compilation job that take more than a minute.      If you have many small jobs (per file, simple mode builds for example), the benefit in startup time is wonderous.

I would recommend the default native-image builds unless you start running into build performance problems, then the JVM version with something like https://github.com/facebook/nailgun many be a better solution.

**Comment by concavelenz** [comment]
Closing this as it is a question, not an issue.
