### ISSUE TITLE
Optimize "instanceof" in ADVANCED_OPTIMIZATIONS

### ISSUE THREAD

**Issue by adrianholovaty** [google/closure-compiler#3711]
Here's a potential improvement for ADVANCED_OPTIMIZATIONS. It could take typedefs into account and optimize away `instanceof` calls. Given this JS:

```js
function hello(/** (!HTMLCanvasElement) */ element) {
    if (element instanceof HTMLCanvasElement) {
        console.log('hello');
    }
}
hello(
    /** @type {!HTMLCanvasElement} */ (document.getElementById('mycanvas'))
);
```

Here's what the compiler currently generates:

```js
document.getElementById("mycanvas")instanceof HTMLCanvasElement&&console.log("hello");
```

Here's the command I used to generate that:

```
java -jar closure-compiler-v20200927.jar \
--language_in ECMASCRIPT6 \
--language_out ECMASCRIPT5 \
--compilation_level ADVANCED_OPTIMIZATIONS \
canvas_hello.js
```

Given that the `element` parameter has been marked as _always_ being an `HTMLCanvasElement` (via the typedef in the function definition and the typedef on the parameter in the one-and-only call to the function), the compiler should be able to safely determine that `element instanceof HTMLCanvasElement` is _always_ true — hence optimizing away that call.

The ideal output would be:

```js
console.log('hello');
```

**Comment by concavelenz** [comment]
The compiler treads a fine line and we can't prove (for optimization purposes) that "getElementById" returns the HTMLCanvasElement and that it is safe to remove the check.  We don't want to remove checks that are there for correctness.  For validating checks, the Closure Library provides a variety of methods that work with type checking and are intended to be removed from production code (in the goog.asserts package).   

Alternately, the check could be written explicitly to be removed but isn't as useful for type checking (if you don't care about that:

```
if (!COMPILED && ...) { ... }
```

**Comment by concavelenz** [comment]
The existing behavior is "working as intended" here.
