### ISSUE TITLE
need better message for parseInt() without radix parameter

### ISSUE THREAD

**Issue by blickly** [google/closure-compiler#372]
This issue was imported from Closure Compiler's previous home at http://closure-compiler.googlecode.com

The original discussion is archived at:
http://blickly.github.io/closure-compiler-issues/#111

**Comment by Dominator008** [comment]
The current behavior is desired and well documented: https://github.com/google/closure-compiler/blob/346d4dfa1a0bd230cb339aaf258a30a1cee9ba64/externs/es3.js#L184-L186. Closing.
