### ISSUE TITLE
Unable to set property as extern when compiling in ADVANCED level

### ISSUE THREAD

**Issue by Zabrane** [google/closure-compiler#3726]
Hi guys,

First of all, I'm new to closure-compiler, so please bear with me.

I'm unable to get my `web worker` module (below snippet) to work with `closure-compiler` when using the `ADVANCED` level.

```sh
$ closure-compiler --compilation_level ADVANCED --js trock.js
```

```javascript
var tRock;
self.addEventListener('message', (ev) => {
    /** @const */
    const msg = ev.data;

    switch(msg.tag) {
    case 'upload':
        tRock = msg.ep.tRock; // <------- error happens here after it's compiled
        [...]
        break;
    default:
        //console.error("unexpected msg from main thread", msg);
        self.close();
    }
});
```

When the compiler runs, it changes this:
```javascript

switch(msg.tag) {
    case 'upload':
        tRock = msg.ep.tRock
```
to:
```javascript
switch(a) {
    case 'upload':
        k=a.a.g
```

How i can prevent renaming `msg.ep` ?
I tried to put `/** @const */`, but it had no impact.

As this is a `web worker`, the *ev* message is received from elsewhere and the compiler should not rename its properties.

I was expecting the following correct output:
```javascript
switch(a.tag) {
    case 'upload':
      k=a.ep.tRock
```

Help appreciated.
Thanks

**Comment by rrdelaney** [comment]
Can you try setting `--language_out` to an ECMAScript version that has `String.protoype.replaceAll`?

**Comment by tjgq** [comment]
I think we're missing the extern for `replaceAll` - I don't see it anywhere in `es[356].js`.

**Comment by Zabrane** [comment]
Is there a better way to automatically rewrite object properties access from this syntax:

```javascript
str.length = 42;
```

to this one:

```javascript
str['length'] = 42;
```

Doing it by hand to solve my original problem is tedious and error-prone.

**Comment by rrdelaney** [comment]
If you were going to rewrite every property access to use `obj['property']` you might want to consider just turning off advanced optimizations.

**Comment by Zabrane** [comment]
@rrdelaney and what benefits i will get from disabling the `ADVANCED` optimization? Nothing IMHO. 

All other optimizers ([UglifyJS](https://github.com/mishoo/UglifyJS), etc.) give the same level of optimization compared to `closure-compiler` in `SIMPLE` mode.

Only `closure-compiler` in `ADVANCED` mode can make a true difference and that was my original question.

**Comment by rrdelaney** [comment]
If you were to rewrite all property access as you were saying you would effectively lose all benefits of advanced optimizations.

**Comment by brad4d** [comment]
@Zabrane I've just added a new wiki page that includes an example I hope will help you.

https://github.com/google/closure-compiler/wiki/How-do-I-make-closure-compiler-stop-breaking-my-API-by-renaming-things%3F

**Comment by rrdelaney** [comment]
Thanks Bradford, I think that doc should answer the question at hand.

**Comment by Zabrane** [comment]
@brad4d Thanks for your time. Explaining the externs on `Wiki` page was very informative.

But my issue isn't yet resolved. Here is a basic code (enclosed) to calculate `Fibonacci of 20` following your Wiki's example.

The `index.html` page:
```html
<html lang="en">

<head>
  <meta charset="UTF-8">
  <script src="app.js"></script>
  <title>Fibonnacci of 20</title>
</head>

<body>
    <button id="calculate" onclick="calculate()">Fibonacci of 20</button>
  <span id="fib"></span>
</body>

</html>
```

The `app.js`:
```js
let worker = new Worker("./worker.js");

const calculate = () => {
    const num = {val : 20};
    worker.postMessage(num);
};

worker.onmessage = event => {
    const result = event.data;
    var span = document.getElementById("fib");
    span.textContent = result;
};
```

and finally the `web worker` code `worker.js`:
```js
function fibonacci(val) {
  if (val <= 1) return 1;
  return fibonacci(val - 1) + fibonacci(val - 2);
};

self.onmessage = event => {
    const num = event.data;
    const result = fibonacci(num.val);

    self.postMessage(result);
    self.close();
};
```

Nothing's special so far.

You can this example using Python built-in HTTP server:
```bash
$ python3 -m http.server 8080 ## or: python -m SimpleHTTPServer
```
Then, simply point your browser to: [http://127.0.0.1:8080/](http://127.0.0.1:8080/)

As you can see, it's pretty basic (no class, etc.).

Could you please help me to generate an extern file for `app.js` and `worker.js`?

**Comment by brad4d** [comment]
The message you're passing from the page to the worker has the form `{val: 20}`.

In the externs file you could have:

```javascript
/** @record */
class FibonacciRequest {
  constructor() {
    /** @type {number} */
    this.val;
  }
}
```

Then you have to tell the compiler you're intentionally creating something to match it with a type annotation.

```javascript
const calculate = () => {
    /** @type {!FibonacciRequest} */
    const num = {val : 20}; // we want the Fibonacci of 20
    worker.postMessage(num);
};
```

Since you tell the compiler `num` is a `FibonacciRequest`, which is declared in the externs file, it knows not to rename its properties.

The message you're passing from the worker to the page is just a number, so nothing to define there.

HTH

**Comment by Zabrane** [comment]
@brad4d thank you very much. With your advices and nice tutorial, we are now able to fully benefit from `closure-compiler` **avanced level** in a much larger project involving `WebWorkers`.
