### ISSUE TITLE
invalid JSC_CONFORMANCE_VIOLATION warning.  property reference is typed as “unknown”

### ISSUE THREAD

**Issue by myphysicslab** [google/closure-compiler#3741]
I've recompiled my project with the latest Closure Compiler v20201207, and the latest Closure Library.  Everything works, but I'm getting a warning that doesn't make sense, and suspiciously disappears when a later line of code is removed.

Here is the code
```
  var at = new AffineTransform(1, 0, 0, 1, 0, 0);
  var r1 = at.transform(1, 2);
  var f1 = function() { return at.transform(1, 2) };
  // comment out the following line causes the compile warning to not occur
  at = new AffineTransform(1, 0, 0, 1, 0, 0);
```

The warning occurs on the line `var f1 = function() { return at.transform(1, 2) };`.
There is no warning on the second line `var r1 = at.transform(1, 2);`
The warning disappears after commenting out the last line.

Here is the compile command and the warning
```
java -jar ../compiler-latest/closure-compiler-v20201207.jar
--entry_point=goog:myphysicslab.test.UnitTest --compilation_level=SIMPLE
--define=goog.DEBUG=true '--define=goog.LOCALE='\''en'\'''
'--define=module$exports$myphysicslab$lab$util$Util.ADVANCED=false'
'--define=module$exports$myphysicslab$lab$util$Util.DEBUG=false'
'--define=module$exports$myphysicslab$lab$util$Util.COMPILE_TIME=2020-12-27 12:14:14'
--generate_exports --js=../closure-library/ --js=src --jscomp_error=accessControls
--jscomp_error=checkTypes --jscomp_error=checkVars --jscomp_error=const
--jscomp_error=constantProperty --jscomp_error=globalThis --jscomp_error=invalidCasts
--jscomp_error=misplacedTypeAnnotation --jscomp_error=missingProperties
--jscomp_error=missingProvide --jscomp_error=missingRequire
--jscomp_error=missingReturn --jscomp_error=strictModuleDepCheck
--jscomp_error=suspiciousCode --jscomp_error=typeInvalidation
--jscomp_error=undefinedNames --jscomp_error=undefinedVars
--jscomp_error=unknownDefines --jscomp_error=uselessCode --jscomp_error=visibility
--hide_warnings_for=../closure-library/
--conformance_configs=/Users/erikn/Documents/Programming/myphysicslab/conformance_config.textproto 
--emit_use_strict --language_in=ECMASCRIPT_2017 --language_out=ECMASCRIPT_2017
--dependency_mode=PRUNE --warning_level=VERBOSE
'--output_wrapper=/*Copyright_2020_Erik_Neumann_All_Rights_Reserved_www.myphysicslab.com*/%output%'

src/lab/util/test/CompilerTest.js:37:34: WARNING - [JSC_CONFORMANCE_VIOLATION] 
Violation: property reference is typed as “unknown”
The property "transform" on type "module$exports$myphysicslab$lab$util$AffineTransform"
  37|   var f1 = function() { return at.transform(1, 2) };
                                        ^^^^^^^^^
0 error(s), 1 warning(s), 98.6% typed
```

If you would like to try for yourself, my project is available at 
https://github.com/myphysicslab/myphysicslab
I boiled the problem down to the above 4 lines of code which are in this file:
https://github.com/myphysicslab/myphysicslab/blob/master/src/lab/util/test/CompilerTest.js
The AffineTransform class is defined here:
https://github.com/myphysicslab/myphysicslab/blob/master/src/lab/util/AffineTransform.js
Run `make unittest` to compile this file.

The same invalid warning happens with a different class:
```
const Vector = goog.require('myphysicslab.lab.util.Vector');
...
  var v = new Vector(1, 0);
  var r2 = v.multiply(2);
  var f2 = function() { return v.multiply(2) };
  v = new Vector(1, 0);
```
That Vector class is at https://github.com/myphysicslab/myphysicslab/blob/master/src/lab/util/Vector.js

The warning only occurs when that last line defines an object of the same type.   If instead the last line defines another type, like a string `v = 'foobar'` then no warning.

I tried using the online closure compiler with the following simplified test, but didn't get the invalid warning there.
```
class Vector {
/**
* @param {number} x the X value of the Vector
* @param {number} y the Y value of the Vector
*/
constructor(x, y) {
this.x_ = x;
this.y_ = y;
};
/**
@param {number} factor factor by which to multiply this Vector
@return {!Vector} product of this Vector and given factor
*/
multiply(factor) {
return new Vector(factor * this.x_, factor * this.y_);
};
}
var v = new Vector(1, 0);
var r2 = v.multiply(2);
var f2 = function() { return v.multiply(2) };
v = new Vector(1, 0);
```

**Comment by lauraharker** [comment]
Declaring the type of `at` should fix the error:

```
/** @type {!AffineTransform} */
var at = new AffineTransform(1, 0, 0, 1, 0, 0);
```

Closure Compiler has trouble handling property accesses on non-constant variables without declared types.

Deleting the line fixes the error because `at` becomes constant and the property access type inference goes down a different code path.

I think the error message could at least suggest that you explicitly declare `at`'s type.

**Comment by myphysicslab** [comment]
That makes sense.  I'm closing the issue.
