### ISSUE TITLE
Cannot satisfy the AudioWorkletNodeOptions extern

### ISSUE THREAD

**Issue by hills** [google/closure-compiler#3749]
The compiler is requesting a type AudioWorkletNodeOptions, but as far as I can understand this a name used in the specification but not an actual type on the target platform (Firefox, or Chromium).

When compiling the following fragment:

```
const options = {
    'processorOptions': {
        'amazingness': 6,
    },
};

this._worklet = new AudioWorkletNode(ac, 'fish', options);
```

```
rbx.js:44:53: WARNING - [JSC_TYPE_MISMATCH] actual parameter 3 of AudioWorkletNode does not match formal parameter
found   : {processorOptions: {channels: ??}}
required: (AudioWorkletNodeOptions|undefined)
  44|     this._worklet = new AudioWorkletNode(ac, 'fish', options);
                                                           ^^^^^^^
```

The declaration in question is here in [externs/browser/w3c_audio.js](https://github.com/google/closure-compiler/blob/e720076961b41152a6e2c497cdc9a3df2618c0fc/externs/browser/w3c_audio.js#L1505). The spec calls this the ['AudioWorkletNodeOptions dictionary'](https://webaudio.github.io/web-audio-api/#dictdef-audioworkletnodeoptions).

Is this a bug in the extern definition, being too constrained? 

It would not suprise me if I am expected to annotate this to be 'correct', but I have not found this for RTCPeerConnection's 'RTCConfiguration', which is similar. I attempted `@type {AudioWorkletNodeOptions}` but this seems to then start tripping up on the internals:

```
rbx.js:38:20: WARNING - [JSC_TYPE_MISMATCH] initializing variable
found   : {processorOptions: {amazingness: number}}
required: (AudioWorkletNodeOptions|null)
  38|     const options = {
                          ^
  39|         'processorOptions': {
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by nreid260** [comment]
`AudioWorkletNodeOptions` is declared as an `@record` in the externs. That means it's not intended to be a constructor you can call at runtime, but just the description of the "shape" of an object (a structural type). `AudioWorkletNodeOptions` is the name we give to this shape so it can be referenced in type annotations. Any object with the right properties can be passed where an instance is expected.

To fix your code, all you should have to do is unquote the keys in your options object. The compiler is looking for normal keys that match the shape of `AudioWorkletNodeOptions` and the quoting makes the compiler see your options as a dictionary, which doesn't have explicit properties.

You may have quoted the keys to prevent them from being renamed; this is unnecessary. The fact that `AudioWorkletNodeOptions` is declared as an extern already prevents its properties from renaming. That's the primary purpose of externs.

**Comment by hills** [comment]
Thanks, that information helps a lot.

But still unable to see a change in behaviour. It doesn't seem to be the quoting.

I tried each of these:

```
const options = {
    processorOptions: {
        'amazingness': 6,
    },
};

const options = {
    processorOptions: {
        amazingness: 6,        # this is bad though, because the options _are_ a dictionary
    },
};

const options = {
    numberofInputs: 6,
    numberofOutputs: 6,
    outputChannelCount: [1,2,3],
    parameterData: {},
    processorOptions: {
        'amazingness': 6,
    },
};

const options = {};
```

The empty object should be a good check? But as with all the other cases I get the same pattern of error:

```
rbx.js:37:53: WARNING - [JSC_TYPE_MISMATCH] actual parameter 3 of AudioWorkletNode does not match formal parameter
found   : {}
required: (AudioWorkletNodeOptions|undefined)
  37|     this._worklet = new AudioWorkletNode(ac, 'fish', options); /* codename */
                                                           ^^^^^^^
```

> You may have quoted the keys to prevent them from being renamed; this is unnecessary. 

Yes, just to fit in with the older version of the compiler we were using; I think we weren't clear how to construct an extern in this case (also assumed it was a dictionary, in that sense)

**Comment by nreid260** [comment]
I'm surprised that:

```
const options = {
    numberofInputs: 6,
    numberofOutputs: 6,
    outputChannelCount: [1,2,3],
    parameterData: {},
    processorOptions: {
        'amazingness': 6,
    },
};
```

doesn't work. What error message does it print?

One thing you could do is experiment with `const /** !AudioWorkletNodeOptions */ options = ...`. That should give you a more detailed error message.

Maybe your externs are from an old version of the compiler?

**Comment by hills** [comment]
The actual warning (sorry, said error before but it's classed as warning) is the same spirit as before; it just documents the new content of the node:

```
rbx.js:44:53: WARNING - [JSC_TYPE_MISMATCH] actual parameter 3 of AudioWorkletNode does not match formal parameter
found   : {
  numberofInputs: number,
  numberofOutputs: number,
  outputChannelCount: Array<?>,
  parameterData: {},
  processorOptions: {amazingness: number}
}
required: (AudioWorkletNodeOptions|undefined)
  44|     this._worklet = new AudioWorkletNode(ac, 'posh', options); /* codename */
                                                           ^^^^^^^
```

I see my mistaken in the above, now. I used ```numberofInputs``` instead of ```numberOfInputs``` (note the uppercase O). With that fixed, the compiler is happy with this example.

So, if I interpret the information in the [`@record` declaration](https://github.com/google/closure-compiler/blob/e720076961b41152a6e2c497cdc9a3df2618c0fc/externs/browser/w3c_audio.js#L1524) are you saying that all these fields are mandatory?

That's the behaviour I'm finding is expected from the compiler. But in practice, that is not true.

The spec makes is clear that: ```numberOfInputs``` and ```numberOfOutputs``` are optional with a default of 1, but the other parts of the spec are a lot more ambigous (eg. ```processorOptions``` is "any user-defined data" which suggests to me it may not even need to be an object, but could be a string or integer)

[The Mozilla docs](https://developer.mozilla.org/en-US/docs/Web/API/AudioWorkletNode/AudioWorkletNode) that I would have followed that led me to believe they are all optional.

**Comment by hills** [comment]
Hi, erm, I'm unclear why this has been closed?

The default externs in the compiler don't seem to match the spec, or the support in browsers.

**Comment by hills** [comment]
The commit broadens the definition of the record but it still does not get detected and results in a warning. Here's a self-contained test:

```
const /** !AudioWorkletNodeOptions */ options = {
    processorOptions: {
        'amazingness': 6,
    },
};

const ac = new AudioContext();
const worklet = new AudioWorkletNode(ac, 'fish', options);
```

Compiling is still insisting on values as mandatory:

```
$ java -jar closure-compiler-v20210106.jar -O ADVANCED proc.js
proc.js:1:48: WARNING - [JSC_TYPE_MISMATCH] initializing variable
found   : {processorOptions: {amazingness: number}}
required: AudioWorkletNodeOptions
missing : [numberOfInputs,numberOfOutputs,outputChannelCount,parameterData]
mismatch: []
  1| const /** !AudioWorkletNodeOptions */ options = {
                                                     ^
  2|     processorOptions: {
     ^^^^^^^^^^^^^^^^^^^^^^^
...
  4|     },
     ^^^^^^
  5| };
     ^

0 error(s), 1 warning(s), 100.0% typed
```

It seems like the fix of adding ```|undefined``` is not correct and really they should be notated as optional?

**Comment by nreid260** [comment]
Are you actually building against the most recent version of the `AudioWorkletNodeOptions` externs? I don't think there's been an external release since I updated them.

In Closure syntax `|undefined` is the way to express property optionality.

**Comment by hills** [comment]
My apologies. Some confusion between compiled version and the corresponding source. I also managed to make it produce a slightly different message, which convinced me something had changed.

I just tested ```closure-compiler-v20210202.jar``` and the original code is no longer producing a warning. Looks good. Thanks.
