### ISSUE TITLE
In deprecated.js, XSLTProcessor methods are defined as static rather than instance methods

### ISSUE THREAD

**Issue by TimBarham** [google/closure-compiler#3750]
`externs/browser/deprecated.js` defines two static methods (`importStylesheet` and `transformToDocument`) on `XSLTProcessor`. 

However, these are actually instance methods, and so should be defined on the prototype, not the constructor.

(Note: I'm happy to open a PR myself, but not sure how to trigger the change to `src/com/google/javascript/jscomp/resources/resources.json`)

**Comment by niloc132** [comment]
For what its worth, I believe the changesets are imported anyway rather than directly merged, so the `resources.json` change happens automatically.
