### ISSUE TITLE
New extern for CodeMirror

### ISSUE THREAD

**Issue by PeterTillema** [google/closure-compiler#3754]
I've manually written an extern file for CodeMirror, can it be added to the wiki? Thanks in advance :)

https://gist.github.com/PeterTillema/8e037add8416c891f72560b8ba153fb3

**Comment by blickly** [comment]
I think there is a wiki page for just this purpose:
https://github.com/google/closure-compiler/wiki/Externs-For-Common-Libraries

It looks to me like most of the edits are from google-external contributors, so I'm hoping that page is editable for you.

If not, let me know, and I can try to fix the permissions.

**Comment by PeterTillema** [comment]
Was looking at that too, yeah, but I sadly cannot edit that page.

**Comment by blickly** [comment]
Dang, sorry about that. It looks like the page was locked down over a year ago. See https://github.com/google/closure-compiler/issues/3759

For now, I've edited that page link myself, but was can also continue discussion on https://github.com/google/closure-compiler/issues/3759 about if there's a way we can reopen wiki access more broadly.

**Comment by PeterTillema** [comment]
Thanks! I will close this issue now, as it's fullfilled, goodluck figuring out a way to handle this more easily!
