### ISSUE TITLE
unable to edit wiki

### ISSUE THREAD

**Issue by myphysicslab** [google/closure-compiler#3759]
I'm unable to update this wiki page
https://github.com/google/closure-compiler/wiki/Debugging-Uncompiled-Source-Code
to reflect the new procedures discussed in [unable to generate deps.js](https://github.com/google/closure-library/issues/1109#)
Can you give me permission to update that page?

**Comment by blickly** [comment]
I was exploring if it was possible to open a PR for the github wikis, but it looks like the software that github wikis are built upon don't support this workflow: https://github.com/gollum/gollum/issues/265

**Comment by kjin** [comment]
I made a few adjustments and posted it: https://github.com/google/closure-compiler/wiki/Debugging-Uncompiled-Source-Code/_compare/c09396780561d6cec64e0db5af392fa04599edbf...4b4fffc1a4814b39a6c57080bd06364d6865245d

I'll close this bug now, thanks for bringing the issue up!
