### ISSUE TITLE
Closure Compiler made my code's size 3 times bigger

### ISSUE THREAD

**Issue by rushknight** [google/closure-compiler#3765]
My code:
`function removeDup(a) {
	var b = new Set(a)
	var c = [...b]
	return c
}`

When I used Simple Optimization, it gave me this result
`var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.makeIterator=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};$jscomp.arrayFromIterator=function(a){for(var b,c=[];!(b=a.next()).done;)c.push(b.value);return c};
$jscomp.arrayFromIterable=function(a){return a instanceof Array?a:$jscomp.arrayFromIterator($jscomp.makeIterator(a))};function removeDup(a){a=new Set(a);return[].concat($jscomp.arrayFromIterable(a))};`

Does this happen because my code can only work in ES6?

**Comment by tjgq** [comment]
Yes - the extra bits are polyfills needed to make your code work on ES5 browsers. Pass in the `--language_out` flag if you only need your code to work on modern browsers.
