### ISSUE TITLE
@ngInject fails when used in an exported class

### ISSUE THREAD

**Issue by schmidtk** [google/closure-compiler#3766]
My project defines AngularJS controller classes in ES6 modules using the following syntax:

```
export class Controller {
  /**
   * Constructor.
   * @param {!angular.Scope} $scope The Angular scope.
   * @param {!angular.JQLite} $element The root DOM element.
   * @ngInject
   */
  constructor($scope, $element) {
    ...
  }
}
```

This worked when using `goog.module` and `exports = {Controller}` instead of the inline `export`, but with the above we're getting the following error from the compiler:

```
ERROR in <file> from closure-compiler: @ngInject only applies to functions defined in blocks or global scope.
  constructor($scope, $element) {
  ^^^^^^^^^^^
```

It appears `@ngInject` is failing due to the inline export. I can work around this in a couple different ways, but I would prefer to use the inline export. Is this a bug, or expected behavior in the compiler?

**Comment by concavelenz** [comment]
REPRO:
https://closure-compiler-debugger.appspot.com/#input0%3Dexport%2520class%2520Controller%2520%257B%250A%2520%2520%252F**%250A%2520%2520%2520*%2520Constructor.%250A%2520%2520%2520*%2520%2540param%2520%257B!angular.Scope%257D%2520%2524scope%2520The%2520Angular%2520scope.%250A%2520%2520%2520*%2520%2540param%2520%257B!angular.JQLite%257D%2520%2524element%2520The%2520root%2520DOM%2520element.%250A%2520%2520%2520*%2520%2540ngInject%250A%2520%2520%2520*%252F%250A%2520%2520constructor(%2524scope%252C%2520%2524element)%2520%257B%250A%250A%2520%2520%257D%250A%257D%26input1%26conformanceConfig%26externs%3Dvar%2520angular%26refasterjs-template%26includeDefaultExterns%3Dtrue%26CHECK_TYPES%3Dtrue%26REWRITE_MODULES_BEFORE_TYPECHECKING%3Dtrue%26ANGULAR_PASS%3Dtrue%26CLOSURE_PASS%3Dtrue%26PRESERVE_TYPE_ANNOTATIONS%3Dtrue%26PRETTY_PRINT%3Dtrue

**Comment by lauraharker** [comment]
I don't see why `@ngInject` shouldn't work here. I'd guess it was an oversight when making @ngInject work in ES modules (https://github.com/google/closure-compiler/commit/c7ce36b60ea4fed0040a52adb4e5da1fbf1961e7);

**Comment by lauraharker** [comment]
Fixed in https://github.com/google/closure-compiler/commit/10ff080a126ec1640581430a87eab567b951ad67. The fix should go into the March release.

**Comment by schmidtk** [comment]
Thanks @lauraharker!
