### ISSUE TITLE
Object.create incorrectly used when transpiling to ES3

### ISSUE THREAD

**Issue by AdobeScripter** [google/closure-compiler#3769]
This code

```javascript
var whatever = Object.create({a: 123});
whatever.a = 42;
alert(whatever);
```

[gets compiled](https://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540compilation_level%2520ADVANCED_OPTIMIZATIONS%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%2540language_in%2520ECMASCRIPT5%250A%252F%252F%2520%2540language_out%2520ECMASCRIPT3%250A%252F%252F%2520%2540formatting%2520pretty_print%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250Avar%2520whatever%2520%253D%2520Object.create(%257Ba%253A%2520123%257D)%253B%250A%250Awhatever.a%2520%253D%252042%253B%250A%250Aalert(whatever)%253B) to

```javascript
var a = Object.create({a:123});
a.a = 42;
alert(a);
```

`Object.create` is not part of ES3.

**Comment by concavelenz** [comment]
Thanks for the report.  Support for ES3 is extremely limited and there is no attempt to translate or polyfill ES5 features when producing ES3.

What platform are you targeting that you feel ES3 is useful?  It is likely that we will drop targetting ES3 in the coming months.

**Comment by concavelenz** [comment]
Closing
