### ISSUE TITLE
Function.prototype.bind incorrectly used when transpiling to ES3

### ISSUE THREAD

**Issue by AdobeScripter** [google/closure-compiler#3770]
This code

```javascript
/**
 * @param {number} a
 * @constructor
 */
function Class(a) {
    this.a = a;
}

/**
 * @return {number}
 */
Class.prototype.fun = function() {
    return this.a;
};

/**
 * @param {number} a
 * @constructor
 */
function Other(a) {
    this.a = a;
}

/**
 * @param {function(): number} fun
 * @return {number}
 */
Other.prototype.callfun = function(fun) {
    return fun();
}

var c = new Class(42);
var o = new Other(49);
alert(o.callfun(c.fun.bind(c)));
```

[gets compiled](https://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540compilation_level%2520ADVANCED_OPTIMIZATIONS%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%2540language_in%2520ECMASCRIPT5%250A%252F%252F%2520%2540language_out%2520ECMASCRIPT3%250A%252F%252F%2520%2540formatting%2520pretty_print%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250A%252F**%250A%2520*%2520%2540param%2520%257Bnumber%257D%2520a%250A%2520*%2520%2540constructor%250A%2520*%252F%250Afunction%2520Class(a)%2520%257B%250A%2520%2520%2520%2520this.a%2520%253D%2520a%253B%250A%257D%250A%250A%252F**%250A%2520*%2520%2540return%2520%257Bnumber%257D%250A%2520*%252F%250AClass.prototype.fun%2520%253D%2520function()%2520%257B%250A%2520%2520%2520%2520return%2520this.a%253B%250A%257D%253B%250A%250A%252F**%250A%2520*%2520%2540param%2520%257Bnumber%257D%2520a%250A%2520*%2520%2540constructor%250A%2520*%252F%250Afunction%2520Other(a)%2520%257B%250A%2520%2520%2520%2520this.a%2520%253D%2520a%253B%250A%257D%250A%250A%252F**%250A%2520*%2520%2540param%2520%257Bfunction()%253A%2520number%257D%2520fun%250A%2520*%2520%2540return%2520%257Bnumber%257D%250A%2520*%252F%250AOther.prototype.callfun%2520%253D%2520function(fun)%2520%257B%250A%2520%2520%2520%2520return%2520fun()%253B%250A%257D%250A%250Avar%2520c%2520%253D%2520new%2520Class(42)%253B%250Avar%2520o%2520%253D%2520new%2520Other(49)%253B%250Aalert(o.callfun(c.fun.bind(c)))%253B) to

```javascript
function a() {
  this.a = 42;
}
a.prototype.g = function() {
  return this.a;
};
var b = new a, c = alert, d;
d = b.g.bind(b)();
c(d);
```

`Function.prototype.bind` does not exist in ES3.

**Comment by brad4d** [comment]
I'm afraid that closure-compiler has never made any attempt to polyfill `Function.prototype.bind` or otherwise recognize and convert uses of it.

This function is one of a few that fall into a no-man's land between ES3 and ES5 where you simply must avoid using them if you want the compiler's output to work in ES3. The most visible other cases are things like `Array.prototype.map`

We're working toward completely disabling ES3 output in the relatively near future, so we won't spend time trying to change this.
Sorry.

**Comment by brad4d** [comment]
I neglected to point out that the reason this gap exists is that developers were encouraged to use `goog.bind` from closure-library and methods from `goog.array` for the missing array methods. Polyfilling instance methods on `Function` and `Array` was deemed too risky.
