### ISSUE TITLE
Static method gets removed despite the definition in the externs file

### ISSUE THREAD

**Issue by ackh** [google/closure-compiler#3798]
I have the following JavaScript class that serves as a type of a public interface which means that the Closure Compiler should not rename/remove the class or any of its methods/properties:

````javascript
"use strict";

const attributeX         = "x";
const attributeY         = "y";
const attributeZ         = "z";
const attributeRotationX = "rotationX"
const attributeRotationY = "rotationY";

/** @suppress {checkTypes} */
class State {
  constructor(x, y, z, rotationX, rotationY) {
    this.x         = x;
    this.y         = y;
    this.z         = z;
    this.rotationX = rotationX;
    this.rotationY = rotationY;
  }

  static fromUrlSearchParams(searchParams) {
    return new State(parseInt  (searchParams.get(attributeX), 10),
                     parseInt  (searchParams.get(attributeY), 10),
                     parseInt  (searchParams.get(attributeZ), 10),
                     parseFloat(searchParams.get(attributeRotationX)),
                     parseFloat(searchParams.get(attributeRotationY)));
  }

  toUrlSearchParams() {
    let searchParams = new URLSearchParams();
    searchParams.set(attributeX        , this.x        .toString(10));
    searchParams.set(attributeY        , this.y        .toString(10));
    searchParams.set(attributeZ        , this.z        .toString(10));
    searchParams.set(attributeRotationX, this.rotationX.toString(10));
    searchParams.set(attributeRotationY, this.rotationY.toString(10));
    return searchParams;
  }
}
````
In order to prevent renaming/removing I have defined the following externs file:
````javascript
/**
 * @fileoverview
 * @externs
 */

/** @suppress {externsValidation} */
State = class {
  /**
   * @constructor
   * @param {number} x
   * @param {number} y
   * @param {number} z
   * @param {number} rotationX
   * @param {number} rotationY
   */
  constructor(x, y, z, rotationX, rotationY) {
    /** @type {number} */
    this.x = x;
    /** @type {number} */
    this.y = y;
    /** @type {number} */
    this.z = z;
    /** @type {number} */
    this.rotationX = rotationX;
    /** @type {number} */
    this.rotationY = rotationY;
  }

  /**
   * @param {URLSearchParams} searchParams
   * @return {State}
   */
  static fromUrlSearchParams(searchParams) {}

  /** @return {URLSearchParams} */
  toUrlSearchParams() {}
};
````
I'm using the following bash shell script to compile that sample:
````
#!/bin/bash

script_folder="$(cd "$(dirname "$0")" && pwd -P)"

/mnt/c/Tools/emsdk/node/14.15.5_64bit/bin/node \
--max_old_space_size=8192 \
/mnt/c/Tools/emsdk/upstream/emscripten/node_modules/.bin/google-closure-compiler \
--compilation_level ADVANCED_OPTIMIZATIONS \
--language_in ECMASCRIPT_2020 \
--language_out NO_TRANSPILE \
--warning_level=VERBOSE \
--emit_use_strict=false \
--externs "${script_folder}/state-externs.js" \
--js "${script_folder}/state-input.js" \
--js_output_file "${script_folder}/state.js" \
````
The result looks like this:
````javascript
class State {
  constructor(a, b, c, d, e) {
    this.x = a;
    this.y = b;
    this.z = c;
    this.rotationX = d;
    this.rotationY = e
  }
  toUrlSearchParams() {
    let a = new URLSearchParams;
    a.set("x", this.x.toString(10));
    a.set("y", this.y.toString(10));
    a.set("z", this.z.toString(10));
    a.set("rotationX", this.rotationX.toString(10));
    a.set("rotationY", this.rotationY.toString(10));
    return a
  }
};
````
I just can't figure out how to prevent that the static method `fromUrlSearchParams` gets removed. I have asked that question on [stackoverflow](https://stackoverflow.com/q/67064898) but I'm beginning to think that this could be a compiler bug.

Am I doing something wrong here or is the compiler not behaving as it should?

**Comment by brad4d** [comment]
The compiler is behaving as it is supposed to do.
If there's nothing that calls the static method, then the compiler will remove it as unused.

The compiler is intended for compiling entire programs, not libraries, so it doesn't leave anything behind that it is able to determine is unused.

However, if you want the compiler to specifically leave some things behind, you can supply it with an externs file defining
the global variables and properties that it should consider as either defined or accessed externally.

See further explanation at

https://github.com/google/closure-compiler/wiki/How-do-I-make-closure-compiler-stop-breaking-my-API-by-removing-and-renaming-things%3F

**Comment by brad4d** [comment]
Ok, I don't know how I missed your externs file.
Looking again.

**Comment by brad4d** [comment]
I have a couple of questions about your externs file.

1. Why isn't there a `var ` in front of `State`? There should be.
2. Why do you have `@suppress {externsValidation}`? I suspect whatever warning you're suppressing is a hint to what's wrong here.

You may also find it works better to define an interface in the externs file and have the class `@implements {StateInterface}` it.
Then you just need this in the externs file to prevent removal of the `State` class itself.

```javascript
// definition of StateInterface first, then

/** @type {!StateInterface} */
var State;
```

**Comment by ackh** [comment]
Regarding your questions:

1. If I put a `var` infront of `State = class {` (i.e. `var State = class {`) I end up with the following error message: `ERROR - [JSC_VAR_MULTIPLY_DECLARED_ERROR] Variable State declared more than once. First occurrence: <path>state-externs.js`. So, with the code as it is it compiles and prevents renaming of those symbols. Note that using `class State {` instead of `State = class {` also results in a `JSC_VAR_MULTIPLY_DECLARED_ERROR`.
2. My externs file is purely used to prevent the compiler from renaming symbols. I do not need to supply definition for external symbols. The [documentation](https://developers.google.com/closure/compiler/docs/api-tutorial3#mixed) states the following about that case:

>One important caveat here is that you may get "duplicate definition" diagnostics about the code defining the extern symbols. Closure Compiler assumes that any symbol in the externs is being supplied by an outside library, and can't currently understand that you are intentionally supplying a definition. These diagnostics are safe to suppress, and you can think of the suppression as a confirmation that you really are fulfilling your API. 

I end up with duplicate definition warnings because both the input and externs file contain a definition of `State`. Adding `/** @suppress {externsValidation} */` to the externs file and `/** @suppress {checkTypes} */` to the input file achieves what the documentation recommends: suppressing warnings about duplicate definitions.

>You may also find it works better to define an interface in the externs file and have the class @implements {StateInterface} it.
Then you just need this in the externs file to prevent removal of the State class itself.

Thanks for the tip. That would probably help with the `JSC_VAR_MULTIPLY_DECLARED_ERROR`. I was unaware that this is possible because I haven't seen any samples that do it this way.

**Comment by brad4d** [comment]
Another approach that both fixes the `JSC_VAR_MULTIPLY_DECLARED_ERROR` and removes the need for the interfaces is you could do this.

```javascript
globalThis['State'] = class {
...
};
```

The compiler knows you're intentionally setting a global here in a way it shouldn't mess with.
I think this would allow you to use your original externs file without the suppression.
You should still have `var State` in the externs file, though.

**Comment by ackh** [comment]
So, is `globalThis['State'] = class` supposed to replace `State = class` in the externs file or does it have to go into the input file?

If I put it in the externs file and add

````javascript
/**
 * @constructor 
 * @implements {State}
 */
var State;
````

at the end of the externs file I again end up with a `JSC_VAR_MULTIPLY_DECLARED_ERROR`.

**Comment by ackh** [comment]
Here's another attempt:
````javascript
"use strict";

const attributeX         = "x";
const attributeY         = "y";
const attributeZ         = "z";
const attributeRotationX = "rotationX"
const attributeRotationY = "rotationY";

/** @implements {StateInterface} */
globalThis['State'] = class {
  constructor(x, y, z, rotationX, rotationY) {
    this.x         = x;
    this.y         = y;
    this.z         = z;
    this.rotationX = rotationX;
    this.rotationY = rotationY;
  }

  static fromUrlSearchParams(searchParams) {
    return new globalThis['State'](parseInt  (searchParams.get(attributeX), 10),
                                   parseInt  (searchParams.get(attributeY), 10),
                                   parseInt  (searchParams.get(attributeZ), 10),
                                   parseFloat(searchParams.get(attributeRotationX)),
                                   parseFloat(searchParams.get(attributeRotationY)));
  }

  toUrlSearchParams() {
    let searchParams = new URLSearchParams();
    searchParams.set(attributeX        , this.x        .toString(10));
    searchParams.set(attributeY        , this.y        .toString(10));
    searchParams.set(attributeZ        , this.z        .toString(10));
    searchParams.set(attributeRotationX, this.rotationX.toString(10));
    searchParams.set(attributeRotationY, this.rotationY.toString(10));
    return searchParams;
  }
}
````
````javascript
/**
 * @fileoverview
 * @externs
 */

/** @interface */
class StateInterface {
  /**
   * @param {number} x
   * @param {number} y
   * @param {number} z
   * @param {number} rotationX
   * @param {number} rotationY
   */
  constructor(x, y, z, rotationX, rotationY) {
    /** @type {number} */
    this.x = x;
    /** @type {number} */
    this.y = y;
    /** @type {number} */
    this.z = z;
    /** @type {number} */
    this.rotationX = rotationX;
    /** @type {number} */
    this.rotationY = rotationY;
  }

  /**
   * @param {URLSearchParams} searchParams
   * @return {StateInterface}
   */
  static fromUrlSearchParams(searchParams) {}

  /** @return {URLSearchParams} */
  toUrlSearchParams() {}
};
````
This also results in
````javascript
globalThis.State = class {
  constructor(a, b, c, d, e) {
    this.x = a;
    this.y = b;
    this.z = c;
    this.rotationX = d;
    this.rotationY = e
  }
  toUrlSearchParams() {
    let a = new URLSearchParams;
    a.set("x", this.x.toString(10));
    a.set("y", this.y.toString(10));
    a.set("z", this.z.toString(10));
    a.set("rotationX", this.rotationX.toString(10));
    a.set("rotationY", this.rotationY.toString(10));
    return a
  }
};
````

**Comment by ackh** [comment]
I've been trying for days and I haven't found a single way to prevent the compiler from removing the static method. This feels really strange because I'm surely not the first human being attempting to do this, right?

Guys, could you please help me out here? After all you literally wrote that thing, right?

The only other options I see is to get rid of static factory methods which is a terrible idea, given that JavaScript only supports a single constructor or to get rid of the closure compiler.

**Comment by ackh** [comment]
With this it seems to work:
````javascript
"use strict";

const attributeX         = "x";
const attributeY         = "y";
const attributeZ         = "z";
const attributeRotationX = "rotationX"
const attributeRotationY = "rotationY";

/** @implements {StateInterface} */
globalThis["State"] = class {
  constructor(x, y, z, rotationX, rotationY) {
    this.x         = x;
    this.y         = y;
    this.z         = z;
    this.rotationX = rotationX;
    this.rotationY = rotationY;
  }

  /**
   * @nocollapse
   * @suppress {checkTypes}
   */
  static "fromUrlSearchParams"(searchParams) {
    return new globalThis["State"](parseInt  (searchParams.get(attributeX), 10),
                                   parseInt  (searchParams.get(attributeY), 10),
                                   parseInt  (searchParams.get(attributeZ), 10),
                                   parseFloat(searchParams.get(attributeRotationX)),
                                   parseFloat(searchParams.get(attributeRotationY)));
  }

  toUrlSearchParams() {
    let searchParams = new URLSearchParams();
    searchParams.set(attributeX        , this.x        .toString(10));
    searchParams.set(attributeY        , this.y        .toString(10));
    searchParams.set(attributeZ        , this.z        .toString(10));
    searchParams.set(attributeRotationX, this.rotationX.toString(10));
    searchParams.set(attributeRotationY, this.rotationY.toString(10));
    return searchParams;
  }
}
````
````javascript
/**
 * @fileoverview
 * @externs
 */

/** @interface */
class StateInterface {
  /**
   * @param {number} x
   * @param {number} y
   * @param {number} z
   * @param {number} rotationX
   * @param {number} rotationY
   */
  constructor(x, y, z, rotationX, rotationY) {
    /** @type {number} */
    this.x = x;
    /** @type {number} */
    this.y = y;
    /** @type {number} */
    this.z = z;
    /** @type {number} */
    this.rotationX = rotationX;
    /** @type {number} */
    this.rotationY = rotationY;
  }

  /**
   * @param {URLSearchParams} searchParams
   * @return {StateInterface}
   */
  static fromUrlSearchParams(searchParams) {}

  /** @return {URLSearchParams} */
  toUrlSearchParams() {}
};
````
Result:
````javascript
globalThis.State = class {
  constructor(a, b, c, d, e) {
    this.x = a;
    this.y = b;
    this.z = c;
    this.rotationX = d;
    this.rotationY = e
  }
  static["fromUrlSearchParams"](a) {
    return new globalThis.State(parseInt(a.get("x"), 10), parseInt(a.get("y"), 10), parseInt(a.get("z"), 10), parseFloat(a.get("rotationX")), parseFloat(a.get("rotationY")))
  }
  toUrlSearchParams() {
    let a = new URLSearchParams;
    a.set("x", this.x.toString(10));
    a.set("y", this.y.toString(10));
    a.set("z", this.z.toString(10));
    a.set("rotationX", this.rotationX.toString(10));
    a.set("rotationY",
        this.rotationY.toString(10));
    return a
  }
};
````
However, it only works with precisely this example. As soon as more (much more) code is added, the static method somehow disappears again. This feels totally random and I doubt that I will ever be able to make this work reliably. The resolution for me is to drop the closure compiler entirely and move to more sane tools.
