### ISSUE TITLE
[Regression] Incorrect elimination of scope in v20210406

### ISSUE THREAD

**Issue by AshleyScirra** [google/closure-compiler#3799]
Since upgrading from v20210302 to v20210406, Closure Compiler now appears to break our code. It appears related to a breakage in the handling of scopes. Sample in.js:

```js
"use strict";

{
	const someGlobal = window["someGlobal"];
	someGlobal["myApi"](someGlobal["getThing"]());
}
```

Note the use of a scope to avoid polluting the global namespace.

Compile this with the following command line:
`java -jar ./closure-compiler.jar --js in.js  --js_output_file out.js --compilation_level ADVANCED --language_in ECMASCRIPT_2020 --language_out ECMASCRIPT_2020 --formatting PRETTY_PRINT`

Expected out.js (as per v20210302):
```js
'use strict';
{
  const a = self.i, b = a.h();
  a.g(b);
}
;
```
Note it preserves the scope.

Observed out.js (as per v20210406):
```js
'use strict';
const a = self.i, b = a.h();
a.g(b);
```

Note the scope is now gone. The declarations that were previously private to the scope have now become global. This can then conflict with other files, defeating the purpose of the scope to prevent this global namespace pollution and conflict.

**Comment by rishipal** [comment]
This is working as intended and is mostly likely coming from 2981beb8a046616b2b9427f9b7455aca4412de8d (in this month's release). 

You can use --isolation_mode=IFFE to preserve the scopes. It will generate:

```
(function(){'use strict';
const a = window.someGlobal;
a.myApi(a.getThing());
}).call(this);
```

**Comment by AshleyScirra** [comment]
With modern JS though, you don't need an IIFE, a scope is enough - and faster. We switched from IIFE to scope and got something like a 50% startup performance boost a while back. Perhaps a new isolation mode could be added where it just uses a scope instead of IIFE?

**Comment by rishipal** [comment]
Laura, perhaps the block merging optimization could be restricted to happen only inside functions?

**Comment by lauraharker** [comment]
@AshleyScirra are you familiar with the [`--output_wrapper` flag](https://github.com/google/closure-compiler/wiki/Flags-and-Options#output)? 

e.g. `--output_wrapper='{%output%'}`.

My concern about exposing --isolation_mode=SCOPE would be that you'd need to know the only globals in the compiler output are block-scoped, no vars. (most of our internal Google users have pre-ES6 code somewhere in their deps)

**Comment by AshleyScirra** [comment]
I didn't know about the output_wrapper option. I will look in to using that. But is Closure smart enough to know that the output wrapper hides scopes when using chunking? It needs to know that variables it moved to the top scope can't be accessed in other chunks, if they get wrapped in a top-level scope. A specific scope isolation mode would probably be enough to tell Closure that this is happening.

FWIW I still think the original issue is a breaking change - the intent of a top-level scope is to hide all its content from the global scope, and Closure now reveals all its content to the global scope, allowing for naming clashes across scripts that are compiled independently.

Also FWIW we wrote all our code with this pattern years ago, as it makes classic scripts forward compatible with modules. You can just remove the "use strict" and top-level scope, and everything keeps working just fine as a module script, which enforces strict mode and a file-level scope. So (in theory) you can easily upgrade once you make the jump to modules.

**Comment by lauraharker** [comment]
Another aspect to this is that Closure Compiler will sometimes create new global variables, e.g. when transpiling certain language features like async functions and when rewriting modules to be in the global scope. [example](https://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540compilation_level%2520SIMPLE_OPTIMIZATIONS%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%2540pretty_print%2520true%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250A%250A%250A%2520%2520%252F**%2520%2540param%2520%257B!Promise%253Cnumber%253E%257D%2520p%2520*%252F%250A%2520%2520const%2520fn%2520%253D%2520async%2520function(p)%2520%257B%250A%2520%2520%2520%2520return%2520await%2520p%2520%252B%25201%253B%250A%2520%2520%257D%250A%2520%2520fn(window%255B'getPromise'%255D())%253B%250A%250A%250A)

So even if we reverted the change to Closure Compiler to fold block scopes into the global scope, it would still be possible to encounter global variable naming collisions.

It's definitely possible your project has so far avoided triggering any of the other ways Closure Compiler can introduce globals (if you're not using modules or transpilation). But I'm still not convinced of the value of carving out a fix for this one particular case when other compiler passes may still introduce globals, and in general I don't believe Closure Compiler has ever guaranteed it won't introduce globals.

**Comment by AshleyScirra** [comment]
In the end we migrated to modules so we get a file-level scope anyway, so we don't need to worry about changes Closure makes at the top-level any more. I guess you're right that Closure can introduce new globals at any time, at least with modules we can ensure any such cases are isolated from each other as we need.
