### ISSUE TITLE
SyntaxError: Unary operator used immediately before exponentiation expression. Parenthesis must be used to disambiguate operator precedence

### ISSUE THREAD

**Issue by domoritz** [google/closure-compiler#3810]
Closure compiler creates invalid output when optimizing `(-1)**x`.

```js
// ==ClosureCompiler==
// @compilation_level ADVANCED_OPTIMIZATIONS
// @output_file_name default.js
// @language_out ECMASCRIPT_2019
// ==/ClosureCompiler==

// ADD YOUR CODE HERE
function hello() {
  var a = Math.random()
  alert((-1)**a);
}
hello();
```

compiles to `'use strict';function hello(){alert(-1**Math.random())}hello();`, which is invalid JavaScript. 

https://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540compilation_level%2520ADVANCED_OPTIMIZATIONS%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%2540language_out%2520ECMASCRIPT_2019%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250A%252F%252F%2520ADD%2520YOUR%2520CODE%2520HERE%250Afunction%2520hello()%2520%257B%250A%2520%2520var%2520a%2520%253D%2520Math.random()%250A%2520%2520alert((-1)**a)%253B%250A%257D%250Ahello()%253B%250A%250A

**Comment by domoritz** [comment]
Would it better for `-x` to be parsed as `NEG { NUMBER(2) }` or to consider negative numbers in the second case?

**Comment by nreid260** [comment]
That's what what we eventually decided to do. I believe ebd18f4af964c351b97db0f0356115dc0f7b93df should have fixed this.
