### ISSUE TITLE
--json_streams `source_map` input is asymmetrical from `sourceMap` output

### ISSUE THREAD

**Issue by jespertheend** [google/closure-compiler#3811]
Coming from #3801

The input json on stdIn uses the format: `[{sourceMap:""}]`
Whereas the output json on stdOut uses: `[{source_map:""}]`
And the documentation says it is: `[{srcmap:""}]`

**Comment by nreid260** [comment]
This appears to be a mismatch in the NPM CLI, which we don't directly maintain.

I can't find "source_map" mentioned as a key in the [spec for SourceMaps](https://sourcemaps.info/spec.html)

**Comment by nreid260** [comment]
Hmm, this might be right repo after all. Sorry, these flags don't come up a lot day-to-day so when I saw JSON I immediately jumped to the NPM commandline.

**Comment by ChadKillingsworth** [comment]
It's both repos actually.
