### ISSUE TITLE
Compatibility with Web Assembly

### ISSUE THREAD

**Issue by catid** [google/closure-compiler#3812]
To use JS functions from Web Assembly, there is an exports object that needs to not be name mangled, but GCC mangles it.  Any work-arounds?

Example:

```
var Ua = {
    vb: {
        mb: function(a) {
            var g = F.O(a);
            setTimeout(function() {
                console.log(g)
            }, 50)
        },
        getMilliseconds: function() {
            return performance.now()
        }
    },
```

Looks like "getMilliseconds" made it through somehow but "mb" did not (was "consoleLog").  Also "vb" was the name of a module.

**Comment by ChadKillingsworth** [comment]
Have you reviewed https://developers.google.com/closure/compiler/docs/externs-and-exports ?

**Comment by nreid260** [comment]
Externs are definitely the solution here. Closing as WAI.

Feel free to reopen if you're using externs and the mangling is still happening. That would be a bug.
