### ISSUE TITLE
Indention causes closure compiler works differently

### ISSUE THREAD

**Issue by williamiced** [google/closure-compiler#3821]
Package version: **v20210505** 

Let's say we have the following files:

main.js
```
goog.provide('__main');
goog.require('__test');
```

test.js
```
goog.module('__test');
```

And running the following command can compile successfully:
`google-closure-compiler --entry_point __main --js main.js test.js`

However, if we change the main.js to:
```
goog.provide('__main');
goog.require(
    '__test');
```

Running the same command and the error is shown:
```
main.js:2:0: ERROR - [JSC_MISSING_MODULE_OR_PROVIDE] Required namespace "__test" never defined.
  2| goog.require(
     ^^^^^^^^^^^^^
  3|     '__test');
     ^^^^^^^^^^^^^

1 error(s), 0 warning(s)
```

I think the indention should not affect the result of closure compiler, so I guess it is a bug.
Thanks.

**Comment by williamiced** [comment]
It seems that goog.require() has a special rule that it should not have any new line in it.
https://google.github.io/styleguide/jsguide.html#file-goog-require

Not sure if it is possible to determine if it is such case and mention that rule in the error messages.
Anyways, please feel free to close it since it might not be a bug but an intended behavior.

**Comment by mprobst** [comment]
There are unfortunately many smaller programs that might parse requires and provides/modules using regexps and similar, and thus they can be fooled by whitespace  changes like your example.

That being said, I cannot repro this:

```
$ cat main.js
goog.provide('main');
goog.require(
  'test');
$ cat test.js
goog.module('test');
$ npx google-closure-compiler --entry_point main --js main.js test.js
var module$exports$test={};var main={};
```

Are you passing any other options, or are you using any other configuration somehow?

**Comment by williamiced** [comment]
Hmm, it is weird. I think my steps are almost identical as yours, but I can reliably reproduce this issue:
```
$ cat main.js 
goog.provide('__main');
goog.require(
    '__test');
$ cat test.js 
goog.module('__test');
$ npx google-closure-compiler --entry_point __main --js main.js test.js
main.js:2:0: ERROR - [JSC_MISSING_MODULE_OR_PROVIDE] Required namespace "__test" never defined.
  2| goog.require(
     ^^^^^^^^^^^^^
  3|     '__test');
     ^^^^^^^^^^^^^

1 error(s), 0 warning(s)
npm ERR! code 1
npm ERR! path /tmp/ClosureTest
npm ERR! command failed
npm ERR! command sh -c google-closure-compiler "--entry_point" "__main" "--js" "main.js" "test.js"

npm ERR! A complete log of this run can be found in:
npm ERR!     ***/.npm/_logs/2021-05-21T13_02_39_274Z-debug.log
$ npx google-closure-compiler --version
Closure Compiler (http://github.com/google/closure-compiler)
Version: v20210505
```

**Comment by mprobst** [comment]
Odd, I have the exact same version.

In either case, I believe this is likely the work of
JsFileRegexParser.java, which has this issue. The code indeed works by
splitting the file into lines, then testing each line with a regexp. It's
not really easy to fix that algorithm I believe. I'd suggest to use the
workaround to not wrap after `goog.require(` for now.

**Comment by williamiced** [comment]
I see. Thanks for the input!
Then I'll close this issue since there is not much we can do now.
