### ISSUE TITLE
Source Map Regression - invalid generated paths on Windows

### ISSUE THREAD

**Issue by thheller** [google/closure-compiler#3825]
In shadow-cljs (ClojureScript build tool) I'm using the closure-compiler via the Java API. Basically I'm calling `Compiler.compileModules` with previously create `JSModule` instances (now JSChunk). I'm extra careful in all the SourceFile names I pass to the compiler and they are all properly normalized (Windows paths changed `\` to `/` before ever being handed to the Compiler.

In the recent `20210505` release I noticed that suddenly source maps started showing weird `sources` names that I never handed the compiler.

```
 "sources": [
          "goog/base.js",
          ...
          "goog/math/long.js",
          "goog/string/stringbuffer.js",
          "cljs/core.cljs",
          "cljs\\core.cljs",
          ...
        ],
```

Note that all `.js` files seem to be properly handled. All `.cljs` however show up with the name I passed in (eg. `cljs/core.cljs`) and then in again with their path separator flipped back to the escaped windows `\`.

All source files are constructed via `SourceFile.fromCode` with the normalized name, the Compiler never touches any files on disk.

Any clues as to what may have changed? Is there some new restriction that only `.js` files are allowed as names? The compilation otherwise works totally fine but the source maps are useless.

 **Note that this problem only occurs on Windows**. Linux/macOS produce proper source maps without this issue.

Digging deeper I suspect this code is the root problem, introduced in 
https://github.com/google/closure-compiler/commit/328d88be1fb4d0d33b767e57312e8a100137022e#diff-6119022f2fb32f42043a9fde4c4e55c492c930fe02c914a3b2ac4d4645abf604R2899-R2903.

https://github.com/google/closure-compiler/blob/ac9bd2e0760c9c5c92ed2ac12ce9d7a5bd3a9038/src/com/google/javascript/jscomp/Compiler.java#L2941-L2944

It uses the platform native `Paths` which on windows will return paths with `\` but that will never match any of the paths the compiler actually uses anywhere since those are all normalized with `/`?

**Comment by thheller** [comment]
I narrowed this down further and confirmed that this is related to input source maps. Doesn't matter whether they are supplied via `Compiler.addInputSourceMap` or directly via inlined source maps together with the sources. On Windows the paths will resolve incorrectly and as such never map back to the provided input source maps.

**Comment by brad4d** [comment]
Well, drat. I thought I was making things better by using the Java native method.

I'll put back our custom version, but this time with a comment explaining that the
real reason we have it is to always use '/' regardless of the platform we're on.

**Comment by brad4d** [comment]
@thheller Thanks for the detailed analysis! That made it a snap to see what needed to be fixed.

**Comment by thheller** [comment]
@brad4d Thanks for the quick fix. :)
