### ISSUE TITLE
String.prototype.replaceAll gets renamed

### ISSUE THREAD

**Issue by jespertheend** [google/closure-compiler#3827]
`String.prototype.replaceAll()` doesn't seem to be defined in the externs at the moment. ([Appspot repro](https://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540compilation_level%2520ADVANCED_OPTIMIZATIONS%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%2540formatting%2520pretty_print%250A%252F%252F%2520%2540language_in%2520ES_NEXT%250A%252F%252F%2520%2540language_out%2520ES_NEXT%250A%252F%252F%2520%2540debug%2520true%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250Aconst%2520str%2520%253D%2520%2522aaa%2520bbb%2520ccc%2520aaa%2522%253B%250A%250Aconst%2520replaced%2520%253D%2520str.replace(%2522aaa%2522%252C%2520%2522zzz%2522)%253B%250Aconsole.log(replaced)%253B%250Aconst%2520replaceAlled%2520%253D%2520str.replaceAll(%2522aaa%2522%252C%2520%2522zzz%2522)%253B%250Aconsole.log(replaceAlled)%253B%250A))

I'm using `ES_NEXT` for both `language_in` and `language_out` so adding an externs file would work, but it'd be nice to have support by default in closure compiler.

**Comment by brad4d** [comment]
We expect to add this to the externs and implement a polyfill next quarter.

**Comment by brad4d** [comment]
Actually I'm currently reviewing a change from @rishipal that will add externs and a polyfill for `replaceAll()`.
I think it will probably land this week.
