### ISSUE TITLE
Random failures in online closure compiler (web and API)

### ISSUE THREAD

**Issue by pladaria** [google/closure-compiler#3831]
I'm using the closure compiler web service (closure-compiler.appspot.com) to compile a library but it seems to randomly fail when using simple or advanced optimizations

Here's a [link to closure compiler app example](https://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%2540compilation_level%2520ADVANCED_OPTIMIZATIONS%250A%252F%252F%2520%2540code_url%2520https%253A%252F%252Fraw.githubusercontent.com%252Fgooglei18n%252Flibphonenumber%252Fv8.12.24%252Fjavascript%252Fi18n%252Fphonenumbers%252Fasyoutypeformatter.js%250A%252F%252F%2520%2540code_url%2520https%253A%252F%252Fraw.githubusercontent.com%252Fgooglei18n%252Flibphonenumber%252Fv8.12.24%252Fjavascript%252Fi18n%252Fphonenumbers%252Fmetadata.js%250A%252F%252F%2520%2540code_url%2520https%253A%252F%252Fraw.githubusercontent.com%252Fgooglei18n%252Flibphonenumber%252Fv8.12.24%252Fjavascript%252Fi18n%252Fphonenumbers%252Fphonemetadata.pb.js%250A%252F%252F%2520%2540code_url%2520https%253A%252F%252Fraw.githubusercontent.com%252Fgooglei18n%252Flibphonenumber%252Fv8.12.24%252Fjavascript%252Fi18n%252Fphonenumbers%252Fphonenumber.pb.js%250A%252F%252F%2520%2540code_url%2520https%253A%252F%252Fraw.githubusercontent.com%252Fgooglei18n%252Flibphonenumber%252Fv8.12.24%252Fjavascript%252Fi18n%252Fphonenumbers%252Fphonenumberutil.js%250A%252F%252F%2520%2540use_closure_library%2520true%250A%252F%252F%2520%2540formatting%2520print_input_delimiter%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250Agoog.require('i18n.phonenumbers.PhoneNumberFormat')%253B%250Agoog.require('i18n.phonenumbers.PhoneNumberType')%253B%250Agoog.require('i18n.phonenumbers.PhoneNumberUtil')%253B%250Agoog.require('i18n.phonenumbers.PhoneNumberUtil.ValidationResult')%253B%250Agoog.require('i18n.phonenumbers.AsYouTypeFormatter')%253B%250Agoog.require('i18n.phonenumbers.metadata')%253B%250A%250Aconst%2520PhoneNumber%2520%253D%2520i18n.phonenumbers.PhoneNumber%253B%250Aconst%2520phoneNumberUtil%2520%253D%2520i18n.phonenumbers.PhoneNumberUtil.getInstance()%253B%250Aconst%2520PhoneNumberType%2520%253D%2520i18n.phonenumbers.PhoneNumberType%253B%250Aconst%2520ValidationResult%2520%253D%2520i18n.phonenumbers.PhoneNumberUtil.ValidationResult%253B%250Aconst%2520PhoneNumberFormat%2520%253D%2520i18n.phonenumbers.PhoneNumberFormat%253B%250Aconst%2520AsYouTypeFormatter%2520%253D%2520i18n.phonenumbers.AsYouTypeFormatter%253B%250Aconst%2520CountryToMetadata%2520%253D%2520i18n.phonenumbers.metadata.countryToMetadata%253B%250A%250Aexports%255B'PhoneNumber'%255D%2520%253D%2520PhoneNumber%253B%250Aexports%255B'phoneNumberUtil'%255D%2520%253D%2520phoneNumberUtil%253B%250Aexports%255B'PhoneNumberType'%255D%2520%253D%2520PhoneNumberType%253B%250Aexports%255B'ValidationResult'%255D%2520%253D%2520ValidationResult%253B%250Aexports%255B'AsYouTypeFormatter'%255D%2520%253D%2520AsYouTypeFormatter%253B%250Aexports%255B'CountryToMetadata'%255D%2520%253D%2520CountryToMetadata%253B%250A).

![image](https://user-images.githubusercontent.com/579417/121056220-475e2d00-c7be-11eb-9541-ae5a606ea58d.png)

It fails randomly (more often when using advanced optimizations), if I use the API instead of the web application, I get:

```
Error(23): java.lang.RuntimeException: java.lang.InterruptedException
	at com.google.javascript.jscomp.NodeTraversal.handleScript(NodeTraversal.java:772)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:832)
	at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:1000)
	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:868)
	at com.google.javascript.jscomp.NodeTraversal.traverse(NodeTraversal.java:459)
	at com.google.javascript.jscomp.NodeTraversal.access$200(NodeTraversal.java:38)
	at com.google.javascript.jscomp.NodeTraversal$Builder.traverse(NodeTraversal.java:398)
	at com.google.javascript.jscomp.ProcessDefines.reportInvalidDefineLocations(ProcessDefines.java:492)
	at com.google.javascript.jscomp.ProcessDefines.process(ProcessDefines.java:189)
	at com.google.javascript.jscomp.PhaseOptimizer$NamedPass.process(PhaseOptimizer.java:317)
	at com.google.javascript.jscomp.PhaseOptimizer.process(PhaseOptimizer.java:232)
	at com.google.javascript.jscomp.Compiler.check(Compiler.java:1063)
	at com.google.javascript.jscomp.Compiler.performChecksAndTranspilation(Compiler.java:861)
	at com.google.javascript.jscomp.Compiler.lambda$stage1Passes$4(Compiler.java:793)
	at com.google.javascript.jscomp.CompilerExecutor.runInCompilerThread(CompilerExecutor.java:127)
	at com.google.javascript.jscomp.Compiler.runInCompilerThread(Compiler.java:849)
```

Any ideas?

**Comment by blickly** [comment]
Both the fact that the stacktrace is an `InterruptedException` and the fact that it's worse when using ADVANCED optimizations than other modes would both be consistent with something like a timeout from using too much resources on app engine.

Are you ever able to reproduce this issue when running Closure Compiler on your local machine?

**Comment by pladaria** [comment]
I was unable to glue together the libphonenumber with closure-library and closure-compiler. I get strange errors like duplicated declarations lin closure-library... but that's probably my fault, I will review that to make it work. Can someone point me to an example of npm's closure-compiler using closure library?

The online compiler (even if it worked fine) isn't producing valid compilations anyway. Because libphonenumber seems to be using an old closure.library (eg, uses goog.isArray).

**Comment by pladaria** [comment]
In case someone comes here from a google search. To avoid exports to be wiped by closure compiler, create an `externs.js` file with this content:
```
const exports = {};
```
Then pass the `--externs externs.js` option to the compiler.
