### ISSUE TITLE
Specification of WebRTC createOffer() incorrect?

### ISSUE THREAD

**Issue by hills** [google/closure-compiler#3839]
I think the compiler's definition of the return type of ```createOffer()``` differs from the spec. The compiler is allowing for return of "undefined".

I belive this code fragment should be valid:

```
async function go() {
    const pc = new RTCPeerConnection({iceServers: []});

    /** @type {!RTCSessionDescription} */
    const offer = await pc.createOffer();
}
```

Compiling with type checking:

```
$ java -jar closure-compiler-v20210505.jar -O SIMPLE  --jscomp_error checkTypes < test.js
The compiler is waiting for input via stdin.


stdin:5:18: ERROR - [JSC_TYPE_MISMATCH] initializing variable
found   : (RTCSessionDescription|undefined)
required: RTCSessionDescription
  5|     const offer = await pc.createOffer();
                       ^^^^^^^^^^^^^^^^^^^^^^

1 error(s), 0 warning(s), 92.1% typed
```

I can't see the possibility of a return of undefined in either the [MDN docs](https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/createOffer) or, if I'm reading correctly, the [w3c specification](https://www.w3.org/TR/webrtc/#dom-rtcpeerconnection-createoffer).

**Comment by rishipal** [comment]
This is fixed with 757bf6e41521aba9519680dfe6742b6f7571e20a.
