### ISSUE TITLE
Inconsistent chunk variable naming between builds

### ISSUE THREAD

**Issue by AdrianBannister** [google/closure-compiler#3843]
Hi,

We’re using CC for chunking, but we’re getting inconsistent property renaming between builds. It is causing chunks that haven’t been changed to be rendered with new content hashes. That isn’t a great experience for returning customers, because we release on a daily basis and they will have to re-fetch all the chunks.

An example:
``` js
//entry.js
import './chunk.js';

console.log({ bar: 'bar' });
// console.log({ baz: 'baz' });
```

``` js
//chunk.js
export const obj = { foo: 'foo' };
console.log(obj);
```

Command used to compile: `google-closure-compiler --compilation_level ADVANCED --chunk_output_path_prefix ./out/ --js chunk.js --chunk chunk:1 --js entry.js --chunk entry:1:chunk --dependency_mode NONE`

The `foo` property is renamed to `h` in the `chunk.js` output file. When I make an unrelated change in `entry.js` by uncommenting  the last line, `foo` in `chunk.js` is now renamed to `i`.

First compile output:
``` js
// chunk.js
console.log({h:"foo"});

// entry.js
console.log({g:"bar"});
```

Second compile output:
``` js
// chunk.js
console.log({i:"foo"});

// entry.js
console.log({g:"bar"});console.log({h:"baz"});
```

Now I’m aware that there is a lot of different things that can affect the variable naming, but I was hoping there is a way in which we can provide the `—property_renaming_report` and `—variable_renaming_report` from a previous build as an input to the next build so that those previous variable renames can be reused to provide more stable chunks between builds.

If anyone has a different way of handling this issue we’d be happy to hear about it.

**Comment by changoesquivel** [comment]
HDAUDIO\FUNC_02&VEN_14F1&DEV_2C06&SUBSYS_14F1000F&REV_1000\4&11cf0c5b&0&0102

**Comment by mprobst** [comment]
This is working as expected: renaming is specific to each build, and changes to any input can change the renaming scheme used. You cannot use the chunks generated during one build together with the chunks from another build.

This indeed has the side effect of causing more frequent cache invalidations. It's a tradeoff between optimization quality/capability and cache effectiveness, I believe.

**Comment by AdrianBannister** [comment]
@mprobst thanks for the reply.

Just to clarify: the suggestion was to reuse the mapping reports, not the generated chunks from the previous report.
The idea is to initialize the `VariableMap` variables before the compilation starts. https://github.com/google/closure-compiler/blob/16783a1e6e7cf37e8de3855273d0da3b8735191e/src/com/google/javascript/jscomp/Compiler.java#L3100-L3107

I did a bit of digging in the source and found these two methods of interest: https://github.com/google/closure-compiler/blob/9f5a91596a65a1e77e9afa30445d0a86e381035c/src/com/google/javascript/jscomp/CompilerOptions.java#L2238-L2244

**Comment by mprobst** [comment]
Yes, those APIs exist, but unfortunately they are misleading in this context. @concavelenz points me to this document he wrote a while back that documents this:

https://docs.google.com/document/d/1ie-sbEhaMF0oVeOcdpvl9cBh6TRCeRycwWSVaBXSTeY/edit?resourcekey=0-AWmt5JhUEyQirZSrYWD9xA#heading=h.fw7eyxf0yfhs

I'll close this as working as intended - see the doc. Please reopen if there's still something missing for you.

**Comment by AdrianBannister** [comment]
I'm not sure that that document addresses the issue that we are raising here, it states:

> to split compilations and provide a stable obfuscated API

We are not trying to split compilations, we are simply trying to reuse the rename mappings from a previous compilation in the current compilation. And while looking at the actual implementation of the code it seems that it does exactly what we were hoping for:

https://github.com/google/closure-compiler/blob/9f5a91596a65a1e77e9afa30445d0a86e381035c/src/com/google/javascript/jscomp/RenameProperties.java#L193-L197

https://github.com/google/closure-compiler/blob/9f5a91596a65a1e77e9afa30445d0a86e381035c/src/com/google/javascript/jscomp/RenameProperties.java#L260-L276

The only problem we have is that those `setInputVariableMap` and `setInputPropertyMap` methods aren't exposed to the CLI. Would a PR exposing those methods to the CLI be considered?

**Comment by mprobst** [comment]
I think the document refers to what you're trying to do. When you use
chunks from a previous compilation, you're splitting compilations in the
sense of the document: there are two different compilation operations whose
results you're trying to combine.
