### ISSUE TITLE
Parentheses before tagged template literals are incorrectly removed

### ISSUE THREAD

**Issue by arttuka** [google/closure-compiler#3847]
This bug came up in another project: https://github.com/arttuka/reagent-material-ui/issues/20

Compiling with `--language_in ECMASCRIPT_NEXT --language_out ECMASCRIPT_2015` causes parentheses to be removed incorrectly in this case:
```js
// input
const x = (0, tag)`template`

// output
'use strict';const x=0,tag`template`;

// should be
'use strict';const x=(0,tag)`template`;
```

This is not limited to a comma expression inside the parens:
```js
// input
const x = (a ? b : c)`template`

//output
'use strict';const x=a?b:c`template`;

// should be
'use strict';const x=(a?b:c)`template`;
```

Compiling with `--language_out ECMASCRIPT5` works since the tagged template literal is transpiled first and the parentheses stay in their correct place:
```js
// input
const x = (a ? b : c)`template`

// output
var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.createTemplateTagFirstArg=function(d){return d.raw=d};$jscomp.createTemplateTagFirstArgWithRaw=function(d,e){d.raw=e;return d};var $jscomp$templatelit$470668781$0=$jscomp.createTemplateTagFirstArg(["template"]),x=(a?b:c)($jscomp$templatelit$470668781$0);

**Comment by mprobst** [comment]
Acknowledged, that seems to be a genuine bug in the code printer. We'll take a look.

**Comment by rahul-kamat** [comment]
This has been fixed and will be in the next open source release.
