### ISSUE TITLE
Wrong enforcement of single argument to createHTML function

### ISSUE THREAD

**Issue by shhnjk** [google/closure-compiler#3848]
[Trusted Types](https://web.dev/trusted-types/)' [`createHTML`](https://w3c.github.io/webappsec-trusted-types/dist/spec/#dom-trustedtypepolicy-createhtml) and others accepts multiple arguments. However, Closure compiler enforces it to be only 1.

https://github.com/google/closure-compiler/blob/7ff6e25843097791416d1544c88dc8711f6be64a/externs/browser/w3c_trusted_types.js#L40-L44

```
ERROR - [JSC_WRONG_ARGUMENT_COUNT] Function staticPolicy$$module$js$static_types.createHTML: called with 2 argument(s). Function requires at least 1 argument(s) and no more than 1 argument(s).
73|   return staticPolicy.createHTML('', literal);
```

**Comment by h-joo** [comment]
This is now resolved by https://github.com/google/closure-compiler/commit/46913e2e11347f9e16fd40f925b06af14dbdadad
