### ISSUE TITLE
ECMASCRIPT_2021 input not enabled in v20210808?

### ISSUE THREAD

**Issue by blq** [google/closure-compiler#3852]
The v20210808 version says `ECMASCRIPT_2021` should be available. 
But when setting compiler option `--language_in` to `ECMASCRIPT_2021` I get the crash:
=> `java.lang.IllegalStateException: Unexpected language mode: ECMASCRIPT_2021`
Although ECMASCRIPT_2021 seems to work for `--language_out`!

**Comment by brad4d** [comment]
It looks like the change to permit `ECMASCRIPT_2021` for `--language_in` was submitted on 2021-08-10, so it didn't make the cut for 2021-08-08. Sorry.
