### ISSUE TITLE
Code printer omits required parens around arrow function in some contexts

### ISSUE THREAD

**Issue by lauraharker** [google/closure-compiler#3862]
For example:

``` js
((x) => x)?.length  // 1
new ((x) => x); // runtime error
```

is pretty-printed as

``` js
x => x?.length;  // evaluates to arrow function
new x => x; // parse error
```

https://closure-compiler-debugger.appspot.com/#input0%3D%250A((x)%2520%253D%253E%2520x)%253F.length%250Anew%2520((x)%2520%253D%253E%2520x)%26input1%26conformanceConfig%26externs%26refasterjs-template%26REWRITE_MODULES_BEFORE_TYPECHECKING%3Dtrue%26CLOSURE_PASS%3Dtrue%26PRESERVE_TYPE_ANNOTATIONS%3Dtrue%26PRETTY_PRINT%3Dtrue

Found while looking at https://github.com/google/closure-compiler/issues/3857. (I think this is a separate issue from that crash)

**Comment by frost-cy** [comment]
Fixed by https://github.com/google/closure-compiler/commit/36d6205dd8df8171201fc906e17af538049df985
