### ISSUE TITLE
provide a wasm compiler

### ISSUE THREAD

**Issue by jimmywarting** [google/closure-compiler#3863]
It would be awesome if you would not need to install java or nailgun to compile stuff, or running the closure-compiler.appspot.com over an api.

instead it would be pretty sweet if NodeJS and the Browser could load a wasm file to do the parsing instead

**Comment by lauraharker** [comment]
In case you weren't aware, the https://www.npmjs.com/package/google-closure-compiler distribution defaults to a native binary version (via https://www.graalvm.org/).

**Comment by concavelenz** [comment]
Feel free to post to https://groups.google.com/g/closure-compiler-discuss if you have furthure questions.

**Comment by jimmywarting** [comment]
i was hoping that you could build a WebAssembly module that wasn't dependent on linux, windows or mac binaries... 
something like `import('./closure.wasm')`
