### ISSUE TITLE
Update Documentation for compilation level?

### ISSUE THREAD

**Issue by Daijobou** [google/closure-compiler#3871]
https://github.com/google/closure-compiler#basic-usage
says:

> Specifies the compilation level to use. Options: BUNDLE, WHITESPACE_ONLY, SIMPLE (default), ADVANCED

In https://developers.google.com/closure/compiler/docs/api-tutorial3 

> Using the Closure Compiler with a compilation_level of ADVANCED_OPTIMIZATIONS offers better compression rates than compilation with SIMPLE_OPTIMIZATIONS or WHITESPACE_ONLY.

Maybe there is a hint missing if which version the terms were changed?

**Comment by mprobst** [comment]
I'll fix the docs, but TL;DR is that both the longer and the shorter form can be used on the command line. The document uses the longer form to be more precise. On the command line, given that you have `--compilation_level` right in front of it, it's usually sufficient to use the short form.

**Comment by Daijobou** [comment]
Ah, Okay. To me it seemed as if SIMPLE_OPTIMIZATIONS was replaced by SIMPLE. 

And it should add  --rewrite_polyfills in --help und documentation. Its complete hidden but important to remove (unnecessary) polyfills.

**Comment by mprobst** [comment]
Can you file a separate issue to track the polyfill thing? Thanks.

Am Mo., 27. Sept. 2021 um 12:26 Uhr schrieb Daijobou <
***@***.***>:

**Comment by Daijobou** [comment]
There is already a report for this https://github.com/google/closure-compiler/issues/3104

**Comment by mprobst** [comment]
I fixed the docs.
