### ISSUE TITLE
Serious bug when compiling a formdata loop

### ISSUE THREAD

**Issue by jplevene** [google/closure-compiler#3885]
The code that causes the bug:-

**var formdata = new FormData();
formdata.set("my_param", "Not important what the values are");
// Looping through formdata is where it goes wrong
for (var pair of formdata.entries())
{
	// Gone wrong by the time you get to here
}**

White space - Just adds bad code so code doesn't run. Code is longer as well
Simple - Returns an error or returns far longer code that also doesn't run
Advanced - Far longer code with warnings that are incorrect

**Comment by lauraharker** [comment]
Is this the same issue as https://github.com/google/closure-compiler/issues/3856?

**Comment by jplevene** [comment]
Sorry, yes it is. I couldn't find my last report as I was being daft.

**Comment by blickly** [comment]
I think that the bug report in #3856 was more complete (included the output code), so if one needs to stay open, it should probably be that one.
