### ISSUE TITLE
"--emit_use_strict" not listed in help output

### ISSUE THREAD

**Issue by blq** [google/closure-compiler#3889]
I missed the `--emit_use_strict` flag since it's not listed in the `--help`

**Comment by concavelenz** [comment]
Can you file a issue on the GitHub issue tracker?

**Comment by blq** [comment]
I thought I did this here? Is there another issue tracker for Closure?

**Comment by lauraharker** [comment]
@blq sorry, yes, this is the correct issue tracker.

We should add `--emit_use_strict` to one of the categories here: https://github.com/google/closure-compiler/blob/07bfc89b5b08bb9687c74dd1d90c375f46222b79/src/com/google/javascript/jscomp/CommandLineRunner.java#L971
