### ISSUE TITLE
Regression: v20211107 drops 'static' from computed class functions

### ISSUE THREAD

**Issue by AshleyScirra** [google/closure-compiler#3891]
The latest v20211107 release has a regression that drops `static` from class functions, breaking code.

in.js:
```js
window["MyClass"] = class
{
	static ["Register"]()
	{
		console.log("Register");
	}
};

```

Command:

`java -jar ./compiler.jar --js in.js --js_output_file out.js --compilation_level ADVANCED --formatting PRETTY_PRINT --language_in ECMASCRIPT_2021 --language_out ECMASCRIPT_2021`

Output with v20211006:

```js
'use strict';
window.MyClass = class {
  static ["Register"]() {
    console.log("Register");
  }
};
```

Output with v20211107:

```js
window.MyClass = class {
  Register() {
    console.log("Register");
  }
};
```

Expected result: `static` to be preserved for method `Register`
Observed result: `static` has been incorrectly removed from the method `Register` - a breaking change

**Comment by concavelenz** [comment]
That is no good, thanks for the report.

**Comment by concavelenz** [comment]
http://ersatz/?v1=TY5Bi8IwEIX%2FypCLtcR2K3tZRNilePAgLOotCSXEkI0bJ6VJkCL970a9CI8ZeN8M77ElZVlksegHHePY9YPFSGg2nESTpNGdT3G9aXc%2Fh3a%2F%2FT12y4%2Fmiwja0EZQ9vmcjJH6Ii2eQ3UO%2Bdl4b6qLPyWni9kLzOYrjhzrsoTvkPqcFgLc1J9W%2F8ex12GCsuZ4tXjy12o3tk5mvgb13DeOACHKaBUwTvba2BD1wIko5i8IoDwG73TlvCneTx65ABPHaUWEoJicy42FuAM%3D
