### ISSUE TITLE
MediaElementAudioSourceNode() constructor signature is incorrect

### ISSUE THREAD

**Issue by DAB0mB** [google/closure-compiler#3894]
Currently, extern files suggest that `MediaElementAudioSourceNode()` should not accept any arguments: https://github.com/google/closure-compiler/blob/7ff6e25843097791416d1544c88dc8711f6be64a/externs/browser/w3c_audio.js#L640
As you can see on MDN, the constructor actually accepts a `context`, and an `options` object: https://developer.mozilla.org/en-US/docs/Web/API/MediaElementAudioSourceNode/MediaElementAudioSourceNode
In addition, `MediaElementAudioSourceNode.mediaElement` is missing: https://developer.mozilla.org/en-US/docs/Web/API/MediaElementAudioSourceNode/mediaElement

**Comment by rishipal** [comment]
Confirmed that the spec defines the constructor to accept the two parameters -https://www.w3.org/TR/webaudio/#mediaelementaudiosourcenode.

Starting test with the externs change to see if it breaks existing projects.

**Comment by rishipal** [comment]
Fixed this internally in 2 CLs. First added the 2 args but kept them optional (https://github.com/google/closure-compiler/commit/ca1b48174f9a9bda1a3719cd9ec7a3fdf350b62e). Second made the args non-optional (https://github.com/google/closure-compiler/commit/ca1b48174f9a9bda1a3719cd9ec7a3fdf350b62e).
