### ISSUE TITLE
declare var in with same value statement make compiler error

### ISSUE THREAD

**Issue by hUwUtao** [google/closure-compiler#3899]
Flags: `-O ADVANCED`
I wrote:
```js
let a = b = c = 1
```
And the compiler throw:
```
statement.js:1:8: ERROR - [JSC_UNDEFINED_VARIABLE] variable b is undeclared
  1| let a = b = c = 1
             ^
statement.js:1:12: ERROR - [JSC_UNDEFINED_VARIABLE] variable c is undeclared
  1| let a = b = c = 1
                 ^
```
Though the code on plain js works correctly, the compiler still throw error
Also same with compare statement: 
```
statement.js:3:0: WARNING - [JSC_USELESS_CODE] Suspicious code. The result of the 'gt' operator is not being used.
  3| a > b > c
     ^^^^^^^^^
```

**Comment by lvelden** [comment]
I you want to do multiple declarations on one line, you still have to assign the values to each variable individually:
```
let a = 1, b = 1, c = 1;
```

The error code in the compare statement is different, it says that the result isn't used, which is the case in the given example.
