### ISSUE TITLE
Compiler throws calling Compiler.buildKnownSymbolTable()

### ISSUE THREAD

**Issue by thheller** [google/closure-compiler#3907]
In [shadow-cljs](https://github.com/thheller/shadow-cljs) I'm using the Closure Compiler via the Java API. One thing I call after compilation (without optimizations) is `compiler.buildKnownSymbolTable()` to extract some information to help the CLJS compiler with JS interop.

This used to work fine but after bumping to `v20220104` it just throws this error. 

```
NullPointerException: Cannot invoke "com.google.javascript.rhino.jstype.JSType.isFunctionPrototypeType()" because the return value of "com.google.javascript.rhino.Node.getJSType()" is null
	com.google.javascript.jscomp.SymbolTable.fillNamespaceReferences (SymbolTable.java:837)
	com.google.javascript.jscomp.Compiler.buildKnownSymbolTable (Compiler.java:1676)
	shadow.build.closure/convert-sources* (closure.clj:1556)
	shadow.build.closure/convert-sources* (closure.clj:1423)
	shadow.build.closure/convert-sources (closure.clj:1763)
	shadow.build.closure/convert-sources (closure.clj:1695)
	shadow.build.compiler/maybe-closure-convert (compiler.clj:1218)
	shadow.build.compiler/maybe-closure-convert (compiler.clj:1211)
	shadow.build.compiler/compile-all (compiler.clj:1454)
	shadow.build.compiler/compile-all (compiler.clj:1330)
	shadow.build.api/compile-sources (api.clj:261)
	shadow.build.api/compile-sources (api.clj:253)
	shadow.build/compile (build.clj:463)
	shadow.build/compile (build.clj:453)
	shadow.cljs.devtools.server.worker.impl/build-compile (impl.clj:368)
	shadow.cljs.devtools.server.worker.impl/build-compile (impl.clj:349)
	shadow.cljs.devtools.server.worker.impl/eval15566/fn--15568 (impl.clj:448)
	clojure.lang.MultiFn.invoke (MultiFn.java:234)
	shadow.cljs.devtools.server.util/server-thread/fn--15324/fn--15325/fn--15333 (util.clj:269)
	shadow.cljs.devtools.server.util/server-thread/fn--15324/fn--15325 (util.clj:268)
	shadow.cljs.devtools.server.util/server-thread/fn--15324 (util.clj:241)
	java.lang.Thread.run (Thread.java:833)
```

I'll try to narrow it a little more but not sure where to start. Any hint on how I could track this further?

FWIW this [commit](https://github.com/google/closure-compiler/commit/788688574bca8bab9d97b17e0dfac3c42e7f1af9) seems to be the source of the problem.

**Comment by brad4d** [comment]
Thanks a ton for pointing at the specific commit.

Looks like the new code just assumed there would always be a `JSType` on the node, which is definitely not a safe assumption.

I'm working on a fix.

**Comment by thheller** [comment]
Thanks for the quick fix.

FWIW I narrowed it down to a use of `import core from "goog:cljs.core"` and any call on `core.assoc(null, 1, 2)`. The CLJS Compiler emits ClosureJS so I'm using the `goog:` to import it into a ES6 file. This doesn't have any type information because at the time of this compilation the CLJS is not compiled yet and only a stub is provided.
