### ISSUE TITLE
Experimental feature --allow_dynamic_imports no longer works after v20210505

### ISSUE THREAD

**Issue by jasowill** [google/closure-compiler#3914]
In releases v20210202, v20210302, and v20210406. This feature was working. It doesn't appear to have been removed from the code, which leads me to believe this was unintentional.

**Comment by rishipal** [comment]
Can you provide more details on "no longer works"? Are you seeing an error `JSC_DYNAMIC_IMPORT_USAGE: Dynamic import expressions cannot be transpiled.`? Also, are you using language version `ES2020`?

**Comment by jasowill** [comment]
Hi @rishipal. The actual error is: 
`ERROR - [JSC_JS_MODULE_LOAD_WARNING] Failed to load module "./index-c4cd8d47.js"
  11391|   this._module = await import("./index-c4cd8d47.js"); `

The command line has `--language_in ECMASCRIPT_2020 --language_out ECMASCRIPT_2020 --compilation_level ADVANCED_OPTIMIZATIONS --allow_dynamic_import`

This works fine for the builds mentioned in the description. But nothing outside of those builds.

Thanks for looking into this!

**Comment by h-joo** [comment]
@jasowill , I tried to reproduce this one, but I couldn't. May I ask if you can provide a repro?

**Comment by AshleyScirra** [comment]
This sounds the same as #3941 - v20210505 was meant to allow dynamic import by default, but instead broke the feature entirely.

**Comment by frigus02** [comment]
Thanks for the update. I'm going to close this as a duplicate of #3941 in that case.
