### ISSUE TITLE
--isolate_polyfills option in compiler does not exist

### ISSUE THREAD

**Issue by stasmilke** [google/closure-compiler#3916]
I need to use isolated polyfills if some file. I found polyfills description in the wiki and this methods does not works (https://github.com/google/closure-compiler/wiki/Polyfills)
> Enable with --isolate_polyfills or options.setIsolatePolyfills(true);

But compiler says:
_"--isolate_polyfills" is not a valid option_

"options.setIsolatePolyfills(true);" in my js file does nothing.

Also, I cannot find responsible code in the repo.
How can I isolate polyfills?

**Comment by lauraharker** [comment]
Sorry about that, we forgot to add the `--isolate_polyfills` flag to https://github.com/google/closure-compiler/blob/master/src/com/google/javascript/jscomp/CommandLineRunner.java.

I'll do that now.
