### ISSUE TITLE
@override function does not infer types correctly in some situations

### ISSUE THREAD

**Issue by anastasi-google** [google/closure-compiler#3923]
In some cases (see [this example in Chromium](https://chromium-review.googlesource.com/c/chromium/src/+/3500815/1/chrome/browser/resources/chromeos/accessibility/chromevox/background/smart_sticky_mode.js#31) and [the referenced interface definition](https://source.chromium.org/chromium/chromium/src/+/main:chrome/browser/resources/chromeos/accessibility/chromevox/background/chromevox_state.js;l=24?q=ChromeVoxStateObserver&ss=chromium)), the `@override` attribute does not infer types correctly, resulting in the following error message (path shortened for readability):

`..../chromevox/background/smart_sticky_mode.js:32:2: ERROR - [JSC_HIDDEN_INTERFACE_PROPERTY_MISMATCH] mismatch of the onCurrentRangeChanged property on type SmartStickyMode$$module$__$__$...$chromevox$background$smart_sticky_mode and the type of the property it overrides from interface `

`ChromeVoxStateObserver
original: function(this:ChromeVoxStateObserver, (cursors.Range|null), boolean=): undefined
override: function(this:SmartStickyMode$$module$__$__$...$chromevox$background$smart_sticky_mode, ?, ?): undefined`

  `32|   onCurrentRangeChanged(newRange, opt_fromEditing) {
        ^^^^^^^^^^^^^^^^^^^^^
`

The workaround, as used in the above example, is to duplicate the type annotations.

**Comment by rahul-kamat** [comment]
We recommend you duplicate the types, which we think is the preferred way to do this.
