### ISSUE TITLE
subprocess.CalledProcessError: Command '['java', '-version']' returned non-zero exit status 2.

### ISSUE THREAD

**Issue by wanming1994** [google/closure-compiler#3928]
closure-library/closure/bin/build/closurebuilder.py: Scanning paths...
closure-library/closure/bin/build/closurebuilder.py: 1844 sources scanned.
closure-library/closure/bin/build/closurebuilder.py: Building dependency tree..
closure-library/closure/bin/build/closurebuilder.py: Closure Compiler now natively understands and orders Closure dependencies and
is prefererred over using this script for performing JavaScript compilation.

Please migrate your codebase.

See:
https://github.com/google/closure-compiler/wiki/Managing-Dependencies

Traceback (most recent call last):
  File "closure-library/closure/bin/build/closurebuilder.py", line 293, in <module>
    main()
  File "closure-library/closure/bin/build/closurebuilder.py", line 282, in main
    compiler_flags=options.compiler_flags)
  File "E:\workspaceGit\virtual-program-demo\js\plugins\closure-library\closure\bin\build\jscompiler.py", line 144, in Compile
    java_version = _ParseJavaVersion(str(_GetJavaVersionString()))
  File "E:\workspaceGit\virtual-program-demo\js\plugins\closure-library\closure\bin\build\jscompiler.py", line 35, in _GetJavaVersionString
    return subprocess.check_output(['java', '-version'], stderr=subprocess.STDOUT)
  File "E:\python\lib\subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "E:\python\lib\subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['java', '-version']' returned non-zero exit status 2.

**Comment by wanming1994** [comment]
![image](https://user-images.githubusercontent.com/33286497/158962700-6e867f89-0e83-49e4-93de-c10e6eaa681a.png)

**Comment by brad4d** [comment]
Maybe you don't have java installed in a way that allows this script to find it under the name `java`?

**Comment by wanming1994** [comment]
> Maybe you don't have java installed in a way that allows this script to find it under the name `java`?

![image](https://user-images.githubusercontent.com/33286497/159217130-d3b78a65-b9dd-4198-beb7-0866d0bee836.png)

**Comment by brad4d** [comment]
The scripts shown in the screenshots, `closurebuilder.py` and `jscompiler.py` do not seem to be part of the current main branch of either `closure-compiler` or `closure-library`.

I don't remember ever having dealt with them (joined this project in 2016).

Sorry, I think you must have some very old and unsupported version of `closure-library` there.
