### ISSUE TITLE
chunks doesn't work with goog.requireType

### ISSUE THREAD

**Issue by koba04** [google/closure-compiler#3931]
Closure Compiler introduces [`closure-calculate-chunks`](https://github.com/chadkillingsworth/closure-calculate-chunks) as a tool to create an option to use chunks.

https://github.com/google/closure-compiler/wiki/Chunk-output-for-dynamic-loading#asking-closure-compiler-to-produce-chunks---the-easy-way

But it doesn't work well when we have a dependency referenced by `goog.requireType` because `google-closure-deps` doesn't list files referenced by `goog.requireType` as dependencies. `closure-calculate-chunks` accepts the `deps.js` generated by `google-closure-deps` so it means that `closure-calculate-chunks` cannot recognize the file because the file isn't in the `deps.js`.

- myapp.js

```js
goog.provide("myapp");

// mylib isn't listed as a dependency of `myapp.js`
goog.requireType("mylib");

myapp.foo = a => console.log(a);

// goog.addDependency('../../../../../src/myapp.js', ['myapp'], [], {'lang': 'es6'});
```

I think this is caused by the following problems

- `google-closure-deps` doesn't list files referenced by `goog.requireType` (this is not a problem of Closure Compiler itself)
- There is no way to specify files only referenced by `goog.requireType` as inputs of chunks
  - We could pass the files as `--js` options unless the dependencies don't include any circular dependency.

If Closure Compiler won't support the case of a circular dependency caused by dependencies of `goog.requireType`, this seems to be solved only by fixing `google-closure-deps`.

**Comment by frost-cy** [comment]
@ChadKillingsworth Do you know anything about this? 
Should I move it to [closure-calculate-chunks](https://github.com/chadkillingsworth/closure-calculate-chunks) ?

**Comment by ChadKillingsworth** [comment]
We can definitely solve it in closure-calculate-chunks. I need to get up to speed on the future of deps files in general.

**Comment by blickly** [comment]
I thought there was a way to "transfer" an issue from one repository to another, but I wasn't able to get it to work.  @koba04, could you refile this in https://github.com/ChadKillingsworth/closure-calculate-chunks/issues which is I think the right repo to track it in?

**Comment by ChadKillingsworth** [comment]
We can't transfer the issue because the destination is in a different GitHub org.

**Comment by koba04** [comment]
@blickly @ChadKillingsworth Thank you, I'll close this and create a new one in [closure-calculate-chunks](https://github.com/ChadKillingsworth/closure-calculate-chunks/issues).

I guess this would have to involve multiple repositories.
- Adding `goog.requireType` support in `google-closure-deps` (google/closure-library)
- Adding `goog.requireType` support as a new command-line option in `google-closure-compiler` (google/closure-compiler)
- Parsing `deps.js` including `goog.requireType` support and generating a result to pass it to `google-closure-compiler` (ChadKillingsworth/closure-calculate-chunks)
