### ISSUE TITLE
there is no options could support directory output

### ISSUE THREAD

**Issue by liuzongyang255** [google/closure-compiler#3933]
there is only one option `--js_output_file`  to suport a file output

i want to use this tool to build my javascripts,and do not want let them to merge into one file;

such as add one option  :  `js_output_dir`, to follow the provided `--js=D:/scripts/` directory

`java -jar closure-compiler.jar --js=D:/scripts/ --js_output_dir=D:/scripts2/`

the input files as follows

-- D:/scripts/dir1/test1.js
-- D:/scripts/dir2/dir21/test2.js

the output dir as follows

-- D:/scripts2/dir1/test1.min.js
-- D:/scripts2/dir2/dir21/test2.min.js

**Comment by h-joo** [comment]
Hello 🙂 may I ask what your intended use case for this feature is? If you're trying to do a per-file reduction, I guess you can try to call the compiler multiple times, would you have different use case?

**Comment by liuzongyang255** [comment]
dear h-joo！

I use it in the back-end single project. The JS files need to be uniformly compressed for project packaging. Because most JS files are introduced separately, they are not suitable for node projects. If there are too many files, it is time-consuming to `call the compiler multiple times`. I have tried about 30 JS files in the project, which takes an average of one second. For packaged projects, the efficiency is far lower than that of node projects

I tried to use the `--js` parameter to input folder compression, and the output speed is very fast

So I wonder if I can have a configuration that can output the folder path I want, and then I can overwrite it into my folder

**Comment by brad4d** [comment]
Hi @liuzongyang255 

The intent of closure-compiler's design is to take a potentially very large set of input `.js` files and squish them into a single application.

When the result is small enough, this should ideally be a single `.js` file.
When the result is big enough that it should be loaded in stages, closure-compiler can be told to produce multiple chunks of `.js` code to load dynamically. However those chunks are not a 1:1 map back to the original source files.

None of that is what you seem to want, which is just to minify a bunch of individual `.js` files which will still be served independently in the final application.

While what you're wanting to do is quite reasonable, it is not the use-case that closure-compiler was designed for,
so no we don't have the option you're looking for.

I hope that makes things clearer.
I'm sorry we're not the right tool for your use-case.

Best regards,
Bradford
