### ISSUE TITLE
Why is -jscomp_off=strictCheckTypes ignored?

### ISSUE THREAD

**Issue by FrontierDK** [google/closure-compiler#3936]
I am running this simple command:
java -jar closure-compiler-v20220405.jar --compilation_level ADVANCED --jscomp_off=strictCheckTypes --js test-in.js --js_output_file test-out.js

However, because I'm referencing some HTML-code via _document.myForm.myButton.disabled_, I'm given this error: test-in.js:13:10: WARNING - [JSC_INEXISTENT_PROPERTY] Property myForm never defined on HTMLDocument

According to https://github.com/google/closure-compiler - using _--jscomp_off=strictCheckTypes_ should disable this message. But it doesn't do that.

**Comment by h-joo** [comment]
Would you care to send the `test-in.js` file for repro of the bug?

**Comment by FrontierDK** [comment]
It's very easy - test-in.js can be just this one line:

_document.myForm.myButton.disabled=true;_

The line which I use to run, is:
_java -jar closure-compiler-v20220405.jar --compilation_level ADVANCED --jscomp_off=strictCheckTypes --js test-in.js --js_output_file test-out.js_

This will throw this error:
_test-in.js:1:9: WARNING - [JSC_INEXISTENT_PROPERTY] Property myForm never defined on HTMLDocument
  1| document.myForm.myButton.disabled=true;_

**Comment by lauraharker** [comment]
This is working as intended. `--jscomp_off=strictCheckTypes` only disables only a set of "strict" typechecker diagnostics defined [here](https://github.com/google/closure-compiler/blob/94985163b8236832cea08ae0287e75b56975219c/src/com/google/javascript/jscomp/DiagnosticGroups.java#L335-L337). 

To disable all `JSC_INEXISTENT_PROPERTY` warnings, you could either set
*  `--jscomp_off=checkTypes` (disables all typechecker errors)
* `--jscomp_off=missingProperties` (disables errors about missing properties but not all typechecker errors)

https://github.com/google/closure-compiler/wiki/@suppress-annotations#error-to-suppression-map also maps from a diagnostic name like `JSC_INEXISTENT_PROPERTY` to how to suppress it.

Could you point to where on https://github.com/google/closure-compiler you saw that `--jscomp_off=strictCheckTypes` should disable this particular error?
