### ISSUE TITLE
Template string placeholders not optimized away

### ISSUE THREAD

**Issue by rx80** [google/closure-compiler#3938]
Compiler version: v20220405

Input code:
```
let x="test";
console.log(`${Math.random()}/${x}`);
```

Generated output with `-O ADVANCED`:
```
console.log(`${Math.random()}/${"test"}`);
```

Expected output:
```
console.log(`${Math.random()}/test`);
```

**Comment by rx80** [comment]
Just a little bit more information:

Currently placeholders do get optimized away if _all_ of them can be:
```
let x="test";
console.log(`${x}/${x}`);
```
becomes:
```
console.log("test/test");
```
So it seems that step of removing the placeholders is there, just not done at the right stage.

**Comment by dloyda** [comment]
Encountering issues with quotation escaping and for each different case requires further investigation. Upon evaluation, the amount of characters that are saved due to inlining are not considered significant enough to pursue further.

**Comment by concavelenz** [comment]
There is no reason we can't conservatively inline values, if it doesn't contain `$` `{` or `` etc then we can inline the value.

**Comment by rx80** [comment]
> There is no reason we can't conservatively inline values, if it doesn't contain `$` `{` or `` etc then we can inline the value.

The thing is they do get inlined in certain cases (see my second comment), it just seems that the stages are a bit mixed up?

**Comment by lauraharker** [comment]
https://github.com/google/closure-compiler/commit/012158f93d41eab3910216b9a5cb4f6a1265c510 should fix `console.log(\\`${Math.random()}/${"test"}`);` -> `console.log(`${Math.random()}/test`);`

@rx80 thanks for pointing out 

```
let x="test";
console.log(`${x}/${x}`);
```

is already simplified! Looks like that was in https://github.com/google/closure-compiler/blob/2e61efb7683e686a7f15fa96a88d2382e0370953/src/com/google/javascript/jscomp/PeepholeSubstituteAlternateSyntax.java#L72.
