### ISSUE TITLE
ES2022 .at() polyfill doesn't inject Math.trunc() polyfill

### ISSUE THREAD

**Issue by teppeis** [google/closure-compiler#3962]
The polyfill of ES2022 `.at()` methods depends on `Math.trunc()`.
https://github.com/google/closure-compiler/blob/1c20adbffc49a5d8a28f1984ecbbe516a6cd6a91/src/com/google/javascript/jscomp/js/es6/util/atmethod.js#L36

But it doesn't inject `Math.trunc()` polyfill.
So ES5 runtimes cannot execute `.at()` polyfill.

**Comment by rahul-kamat** [comment]
Thanks for reporting this! We're adding a `'require es6/math/trunc';` line which will fix this.

**Comment by teppeis** [comment]
thanks! https://github.com/google/closure-compiler/commit/96dcbabd8eefbbbdb52ca2d7257981be67df1a7d
