### ISSUE TITLE
Parse Error when used with pdfJS

### ISSUE THREAD

**Issue by karelee7** [google/closure-compiler#3963]
Hi!

I'm trying to use Google Closure (v20220601) with pdfjs-dist (v2.14.305)
**Google Closure:** https://mvnrepository.com/artifact/com.google.javascript/closure-compiler/v20220601
**pdfjs:** https://github.com/mozilla/pdfjs-dist/tree/v2.14.305

But I keep getting a parsing error message in pdf_viewer.js:
```
src/third-party/doc/pdf_viewer.js:447:2: ERROR - [JSC_PARSE_ERROR] Parse error. '}' expected
  447|   #pagesRefCache = new Map();
```

I found that others had a similar issue [here](https://github.com/google/closure-compiler/issues/2731#issuecomment-892843654) and that there was some chatter about adding a fix for private class fields; is this already done?

**Comment by shicks** [comment]
It looks like this is using private class properties, which may not be supported.
