### ISSUE TITLE
`AsyncIterator#return` not called when error thrown in `for await of` loop

### ISSUE THREAD

**Issue by trxcllnt** [google/closure-compiler#3971]
The `AsyncIterator#return` method should be called by closure-compiler's async iteration polyfills, but doesn't seem to be (compiling with advanced opts):

```shell
$ node test.js 
> next: 0
> next: 1
> next: 2
> return called
> catch block
> finally block
all done

$ node test.min.js 
> next: 0
> next: 1
> next: 2
> catch block
> finally block
all done

```

<details><summary>test.js:</summary><pre>
test().then(() => console.log('all done'));<br/><br/>async function test() {<br/>  try {<br/>    for await (const i of source()) {<br/>      console.log(`> next: ${i}`);<br/>      if (i === 2) {<br/>        throw new Error('');<br/>      }<br/>    }<br/>    console.log(`> done`);<br/>  } catch (e) {<br/>    console.log(`> catch block`);<br/>  } finally {<br/>    console.log(`> finally block`);<br/>  }<br/>}<br/><br/>function source() {<br/>  return {<br/>    i: 0,<br/>    n: 3,<br/>    [Symbol.asyncIterator]() { return this; },<br/>    async next() {<br/>      if (this.i < this.n) {<br/>        return { done: false, value: this.i++ };<br/>      }<br/>      return { done: true };<br/>    },<br/>    async throw() {<br/>      console.log(`> throw called`);<br/>      return { done: true, value: undefined };<br/>    },<br/>    async return() {<br/>      console.log(`> return called`);<br/>      return { done: true, value: undefined };<br/>    }<br/>  };<br/>}<br/></pre></details>

<details><summary>test.min.js:</summary><pre>function $$jscomp$arrayIteratorImpl$$($array$jscomp$6$$) {<br/>  var $index$jscomp$100$$ = 0;<br/>  return function () {<br/>    return $index$jscomp$100$$ < $array$jscomp$6$$.length ? { done: !1, value: $array$jscomp$6$$[$index$jscomp$100$$++], } : { done: !0 };<br/>  };<br/>}<br/>var $$jscomp$defineProperty$$ = "function" == typeof Object.defineProperties ? Object.defineProperty : function ($target$jscomp$92$$, $property$jscomp$5$$, $descriptor$jscomp$1$$) {<br/>  if ($target$jscomp$92$$ == Array.prototype || $target$jscomp$92$$ == Object.prototype) {<br/>    return $target$jscomp$92$$;<br/>  }<br/>  $target$jscomp$92$$[$property$jscomp$5$$] = $descriptor$jscomp$1$$.value;<br/>  return $target$jscomp$92$$;<br/>};<br/>function $$jscomp$getGlobal$$($passedInThis_possibleGlobals$$) {<br/>  $passedInThis_possibleGlobals$$ = ["object" == typeof globalThis && globalThis, $passedInThis_possibleGlobals$$, "object" == typeof window && window, "object" == typeof self && self, "object" == typeof global && global,];<br/>  for (var $i$jscomp$3$$ = 0; $i$jscomp$3$$ < $passedInThis_possibleGlobals$$.length; ++$i$jscomp$3$$) {<br/>    var $maybeGlobal$$ = $passedInThis_possibleGlobals$$[$i$jscomp$3$$];<br/>    if ($maybeGlobal$$ && $maybeGlobal$$.Math == Math) {<br/>      return $maybeGlobal$$;<br/>    }<br/>  }<br/>  throw Error("Cannot find global object");<br/>}<br/>var $$jscomp$global$$ = $$jscomp$getGlobal$$(this);<br/>function $$jscomp$polyfill$$($property$jscomp$inline_10_split$jscomp$inline_7_target$jscomp$94$$, $impl$jscomp$inline_12_polyfill$jscomp$1$$) {<br/>  if ($impl$jscomp$inline_12_polyfill$jscomp$1$$) {<br/>    a: {<br/>      var $obj$jscomp$inline_6$$ = $$jscomp$global$$;<br/>      $property$jscomp$inline_10_split$jscomp$inline_7_target$jscomp$94$$ = $property$jscomp$inline_10_split$jscomp$inline_7_target$jscomp$94$$.split(".");<br/>      for (var $i$jscomp$inline_8_orig$jscomp$inline_11$$ = 0; $i$jscomp$inline_8_orig$jscomp$inline_11$$ < $property$jscomp$inline_10_split$jscomp$inline_7_target$jscomp$94$$.length - 1; $i$jscomp$inline_8_orig$jscomp$inline_11$$++) {<br/>        var $key$jscomp$inline_9$$ = $property$jscomp$inline_10_split$jscomp$inline_7_target$jscomp$94$$[$i$jscomp$inline_8_orig$jscomp$inline_11$$];<br/>        if (!($key$jscomp$inline_9$$ in $obj$jscomp$inline_6$$)) {<br/>          break a;<br/>        }<br/>        $obj$jscomp$inline_6$$ = $obj$jscomp$inline_6$$[$key$jscomp$inline_9$$];<br/>      }<br/>      $property$jscomp$inline_10_split$jscomp$inline_7_target$jscomp$94$$ = $property$jscomp$inline_10_split$jscomp$inline_7_target$jscomp$94$$[$property$jscomp$inline_10_split$jscomp$inline_7_target$jscomp$94$$.length - 1];<br/>      $i$jscomp$inline_8_orig$jscomp$inline_11$$ = $obj$jscomp$inline_6$$[$property$jscomp$inline_10_split$jscomp$inline_7_target$jscomp$94$$];<br/>      $impl$jscomp$inline_12_polyfill$jscomp$1$$ = $impl$jscomp$inline_12_polyfill$jscomp$1$$($i$jscomp$inline_8_orig$jscomp$inline_11$$);<br/>      $impl$jscomp$inline_12_polyfill$jscomp$1$$ != $i$jscomp$inline_8_orig$jscomp$inline_11$$ && null != $impl$jscomp$inline_12_polyfill$jscomp$1$$ && $$jscomp$defineProperty$$($obj$jscomp$inline_6$$, $property$jscomp$inline_10_split$jscomp$inline_7_target$jscomp$94$$, { configurable: !0, writable: !0, value: $impl$jscomp$inline_12_polyfill$jscomp$1$$ });<br/>    }<br/>  }<br/>}<br/>$$jscomp$polyfill$$("Symbol", function ($orig$jscomp$1$$) {<br/>  function $symbolPolyfill$$($opt_description$jscomp$2$$) {<br/>    if (this instanceof $symbolPolyfill$$) {<br/>      throw new TypeError("Symbol is not a constructor");<br/>    }<br/>    return new $SymbolClass$$($SYMBOL_PREFIX$$ + ($opt_description$jscomp$2$$ || "") + "_" + $counter$$++, $opt_description$jscomp$2$$);<br/>  }<br/>  function $SymbolClass$$($id$jscomp$5$$, $opt_description$jscomp$1$$) {<br/>    this.$$jscomp$symbol$id_$ = $id$jscomp$5$$;<br/>    $$jscomp$defineProperty$$(this, "description", { configurable: !0, writable: !0, value: $opt_description$jscomp$1$$ });<br/>  }<br/>  if ($orig$jscomp$1$$) {<br/>    return $orig$jscomp$1$$;<br/>  }<br/>  $SymbolClass$$.prototype.toString = function () {<br/>    return this.$$jscomp$symbol$id_$;<br/>  };<br/>  var $SYMBOL_PREFIX$$ = "jscomp_symbol_" + (1E9 * Math.random() >>> 0) + "_", $counter$$ = 0;<br/>  return $symbolPolyfill$$;<br/>});<br/>$$jscomp$polyfill$$("Symbol.iterator", function ($orig$jscomp$2_symbolIterator$$) {<br/>  if ($orig$jscomp$2_symbolIterator$$) {<br/>    return $orig$jscomp$2_symbolIterator$$;<br/>  }<br/>  $orig$jscomp$2_symbolIterator$$ = Symbol("Symbol.iterator");<br/>  for (var $arrayLikes$$ = "Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "), $i$jscomp$6$$ = 0; $i$jscomp$6$$ < $arrayLikes$$.length; $i$jscomp$6$$++) {<br/>    var $ArrayLikeCtor$$ = $$jscomp$global$$[$arrayLikes$$[$i$jscomp$6$$]];<br/>    "function" === typeof $ArrayLikeCtor$$ && "function" != typeof $ArrayLikeCtor$$.prototype[$orig$jscomp$2_symbolIterator$$] && $$jscomp$defineProperty$$($ArrayLikeCtor$$.prototype, $orig$jscomp$2_symbolIterator$$, {<br/>      configurable: !0, writable: !0, value: function () {<br/>        return $$jscomp$iteratorPrototype$$($$jscomp$arrayIteratorImpl$$(this));<br/>      }<br/>    });<br/>  }<br/>  return $orig$jscomp$2_symbolIterator$$;<br/>});<br/>$$jscomp$polyfill$$("Symbol.asyncIterator", function ($orig$jscomp$3$$) {<br/>  return $orig$jscomp$3$$ ? $orig$jscomp$3$$ : Symbol("Symbol.asyncIterator");<br/>});<br/>function $$jscomp$iteratorPrototype$$($iterator$jscomp$6_next$$) {<br/>  $iterator$jscomp$6_next$$ = { next: $iterator$jscomp$6_next$$ };<br/>  $iterator$jscomp$6_next$$[Symbol.iterator] = function () {<br/>    return this;<br/>  };<br/>  return $iterator$jscomp$6_next$$;<br/>}<br/>function $$jscomp$asyncExecutePromiseGenerator$$($generator$jscomp$1$$) {<br/>  function $passValueToGenerator$$($value$jscomp$99$$) {<br/>    return $generator$jscomp$1$$.next($value$jscomp$99$$);<br/>  }<br/>  function $passErrorToGenerator$$($error$jscomp$2$$) {<br/>    return $generator$jscomp$1$$.throw($error$jscomp$2$$);<br/>  }<br/>  return new Promise(function ($resolve$$, $reject$$) {<br/>    function $handleGeneratorRecord$$($genRec$$) {<br/>      $genRec$$.done ? $resolve$$($genRec$$.value) : Promise.resolve($genRec$$.value).then($passValueToGenerator$$, $passErrorToGenerator$$).then($handleGeneratorRecord$$, $reject$$);<br/>    }<br/>    $handleGeneratorRecord$$($generator$jscomp$1$$.next());<br/>  });<br/>}<br/>function $$jscomp$AsyncIteratorFromSyncWrapper$$($iterator$jscomp$8$$) {<br/>  this[Symbol.asyncIterator] = function () {<br/>    return this;<br/>  };<br/>  this[Symbol.iterator] = function () {<br/>    return $iterator$jscomp$8$$;<br/>  };<br/>  this.next = function ($param$jscomp$6$$) {<br/>    return Promise.resolve($iterator$jscomp$8$$.next($param$jscomp$6$$));<br/>  };<br/>  void 0 !== $iterator$jscomp$8$$["throw"] && (this["throw"] = function ($param$jscomp$7$$) {<br/>    return Promise.resolve($iterator$jscomp$8$$["throw"]($param$jscomp$7$$));<br/>  });<br/>  void 0 !== $iterator$jscomp$8$$["return"] && (this["return"] = function ($param$jscomp$8$$) {<br/>    return Promise.resolve($iterator$jscomp$8$$["return"]($param$jscomp$8$$));<br/>  });<br/>}<br/>function $__await$$module$node_modules$tslib$tslib_es6$$($v$jscomp$2$$) {<br/>  return this instanceof $__await$$module$node_modules$tslib$tslib_es6$$ ? this : new $__await$$module$node_modules$tslib$tslib_es6$$($v$jscomp$2$$);<br/>}<br/>; $__await$$module$node_modules$tslib$tslib_es6$$.prototype[Symbol.toStringTag] = "__await";<br/>Object.defineProperty($__await$$module$node_modules$tslib$tslib_es6$$, Symbol.hasInstance, {<br/>  writable: !0, configurable: !0, value($inst$$) {<br/>    return !(!$inst$$ || "__await" !== $inst$$[Symbol.toStringTag]);<br/>  }<br/>});<br/>function $source$jscomp$17$$() {<br/>  return {<br/>    $i$: 0, n: 3, [Symbol.asyncIterator]() {<br/>      return this;<br/>    }, next() {<br/>      const $$jscomp$async$this$$ = this;<br/>      return $$jscomp$asyncExecutePromiseGenerator$$(function* () {<br/>        return $$jscomp$async$this$$.$i$ < $$jscomp$async$this$$.n ? { done: !1, value: $$jscomp$async$this$$.$i$++ } : { done: !0 };<br/>      }());<br/>    }, throw() {<br/>      return $$jscomp$asyncExecutePromiseGenerator$$(function* () {<br/>        console.log("> throw called");<br/>        return { done: !0, value: void 0 };<br/>      }());<br/>    }, return() {<br/>      return $$jscomp$asyncExecutePromiseGenerator$$(function* () {<br/>        console.log("> return called");<br/>        return { done: !0, value: void 0 };<br/>      }());<br/>    }<br/>  };<br/>}<br/>(function () {<br/>  return $$jscomp$asyncExecutePromiseGenerator$$(function* () {<br/>    try {<br/>      var $$jscomp$forAwait$tempIterator0_JSCompiler_inline_result$jscomp$2$$, $iterable$jscomp$inline_14$$ = $source$jscomp$17$$(), $asyncIteratorFunction$jscomp$inline_15$$ = $iterable$jscomp$inline_14$$[Symbol.asyncIterator];<br/>      if (void 0 !== $asyncIteratorFunction$jscomp$inline_15$$) {<br/>        var $JSCompiler_temp$jscomp$17$$ = $asyncIteratorFunction$jscomp$inline_15$$.call($iterable$jscomp$inline_14$$);<br/>      } else {<br/>        var $iteratorFunction$jscomp$inline_21$$ = "undefined" != typeof Symbol && Symbol.iterator && $iterable$jscomp$inline_14$$[Symbol.iterator];<br/>        var $JSCompiler_inline_result$jscomp$19$$ = $iteratorFunction$jscomp$inline_21$$ ? $iteratorFunction$jscomp$inline_21$$.call($iterable$jscomp$inline_14$$) : { next: $$jscomp$arrayIteratorImpl$$($iterable$jscomp$inline_14$$) };<br/>        $JSCompiler_temp$jscomp$17$$ = new $$jscomp$AsyncIteratorFromSyncWrapper$$($JSCompiler_inline_result$jscomp$19$$);<br/>      }<br/>      for ($$jscomp$forAwait$tempIterator0_JSCompiler_inline_result$jscomp$2$$ = $JSCompiler_temp$jscomp$17$$; ;) {<br/>        const $$jscomp$forAwait$tempResult0$$ = yield $$jscomp$forAwait$tempIterator0_JSCompiler_inline_result$jscomp$2$$.next();<br/>        if ($$jscomp$forAwait$tempResult0$$.done) {<br/>          break;<br/>        }<br/>        const $i$jscomp$18$$ = $$jscomp$forAwait$tempResult0$$.value;<br/>        console.log(`> next: ${$i$jscomp$18$$}`);<br/>        if (2 === $i$jscomp$18$$) {<br/>          throw Error("");<br/>        }<br/>      }<br/>      console.log("> done");<br/>    } catch ($e$jscomp$18$$) {<br/>      console.log("> catch block");<br/>    } finally {<br/>      console.log("> finally block");<br/>    }<br/>  }());<br/>})().then(() => console.log("all done"));<br/></pre></details>

**Comment by lauraharker** [comment]
Thanks for the report, definitely looks like a bug.

**Comment by rishipal** [comment]
Fixed with. d228c12c1b10833634654e19d091cd726ab0c713
