### ISSUE TITLE
`.toString(16)` is not optimised away if the result is unused

### ISSUE THREAD

**Issue by copy** [google/closure-compiler#3972]
The following used to be compiled away (in `v20210601`, even without the type annotations and the typeof):

```js
// ==ClosureCompiler==
// @compilation_level ADVANCED_OPTIMIZATIONS
// @output_file_name default.js
// ==/ClosureCompiler==

/**
 * @param {number} n
 * @param {number=} len
 * @return {string}
 */
function h(n, len)
{
    let str;
    if(typeof n === "number")
    {
        str = n.toString(16);
    }
    else
    {
        str = n + "";
    }

    return "0x" + str.toUpperCase().padStart(len || 1, "0");
}

/**
 * @param {number} x
 */
window["main"] = function(x)
{
  h(x);
}
```

It now generates (tested with `v20220405` and [the service](https://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540compilation_level%2520ADVANCED_OPTIMIZATIONS%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250A%252F**%250A%2520*%2520%2540param%2520%257Bnumber%257D%2520n%250A%2520*%2520%2540param%2520%257Bnumber%253D%257D%2520len%250A%2520*%2520%2540return%2520%257Bstring%257D%250A%2520*%252F%250Afunction%2520h(n%252C%2520len)%250A%257B%250A%2520%2520%2520%2520let%2520str%253B%250A%2520%2520%2520%2520if(typeof%2520n%2520%253D%253D%253D%2520%2522number%2522)%250A%2520%2520%2520%2520%257B%250A%2520%2520%2520%2520%2520%2520%2520%2520str%2520%253D%2520n.toString(16)%253B%250A%2520%2520%2520%2520%257D%250A%2520%2520%2520%2520else%250A%2520%2520%2520%2520%257B%250A%2520%2520%2520%2520%2520%2520%2520%2520str%2520%253D%2520n%2520%252B%2520%2522%2522%253B%250A%2520%2520%2520%2520%257D%250A%250A%2520%2520%2520%2520return%2520%25220x%2522%2520%252B%2520str.toUpperCase().padStart(len%2520%257C%257C%25201%252C%2520%25220%2522)%253B%250A%257D%250A%250A%252F**%250A%2520*%2520%2540param%2520%257Bnumber%257D%2520x%250A%2520*%252F%250Awindow%255B%2522main%2522%255D%2520%253D%2520function(x)%250A%257B%250A%2520%2520h(x)%253B%250A%257D%250A)):

```js
 window.main=function(a){"number"===typeof a&&a.toString(16)};
```

I tend to write code similar to this a lot: `dbg_log("x=" + h(x) + " y=" + h(y))`, where `dbg_log` gets optimised away in the release build properly, leaving the (sometimes costly) `x.toString(16)` operation.

**Comment by lauraharker** [comment]
Interesting - Closure Compiler has always hardcoded that `toString()` with zero args has no side-effects here: https://github.com/google/closure-compiler/blob/ee55469d388cd1e132fb9f372fc878818e11ac3b/src/com/google/javascript/jscomp/AstAnalyzer.java#L67-L68

and we also assume it is side-effect free in the standard externs: https://github.com/google/closure-compiler/blob/ee55469d388cd1e132fb9f372fc878818e11ac3b/externs/es3.js#L1196

Not sure why the one-arg call stopped being dead-code eliminated, but maybe we should just extend the zero-arg hardcoding to handle multiple arguments (unless the args themselves have side effects)

**Comment by copy** [comment]
Invalid radices might be a problem:

```
> (42).toString(99)
Uncaught RangeError: toString() radix argument must be between 2 and 36
    at Number.toString (<anonymous>)
```

**Comment by lgrachov** [comment]
And look what the `make all` command in terminal said when I try to compile copy.sh/v86:
```
mkdir -p closure-compiler
# don't upgrade until https://github.com/google/closure-compiler/issues/3972 is fixed
wget -nv -O closure-compiler/compiler.jar https://repo1.maven.org/maven2/com/google/javascript/closure-compiler/v20210601/closure-compiler-v20210601.jar
make: wget: No such file or directory
make: *** [closure-compiler/compiler.jar] Error 1
```

**Comment by niloc132** [comment]
@lgrachov that works for me:
```
2023-06-01 08:30:53 URL:https://repo1.maven.org/maven2/com/google/javascript/closure-compiler/v20210601/closure-compiler-v20210601.jar [12634009/12634009] -> "closure-compiler/compiler.jar" [1]
```

Is it possible that a proxy was preventing you from loading the url? From time to time maven also has caching issues, can you confirm that https://repo1.maven.org/maven2/com/google/javascript/closure-compiler/v20210601/ shows the closure-compiler-v20210601.jar link as expected, and that your browser can download it?

**Comment by lgrachov** [comment]
@niloc132 My browser can download it
<img width="135" alt="Снимок экрана 2023-06-01 в 16 45 54" src="https://github.com/google/closure-compiler/assets/78234184/525928a7-1876-4afb-a668-d22934f550bd">

**Comment by spetterman66** [comment]
progress?
