### ISSUE TITLE
DOMMatrix inverseSelf does not exists, it is invertSelf

### ISSUE THREAD

**Issue by SalvatorePreviti** [google/closure-compiler#3978]
Raised a PR, there is a typo in externs/browser/w3c_geometry1.js - the right method is invertSelf, not inverseSelf
 
https://github.com/google/closure-compiler/pull/3977

**Comment by SalvatorePreviti** [comment]
It seems that is not the only issue with DOMMatrix, the definition seems outdated - for example, constructor can accept zero arguments now.

**Comment by mprobst** [comment]
From what I can tell, these definitions are based on a version of the spec from Dec 2018, and haven't seen much change. It's quite likely that they are not up to date.

**Comment by mprobst** [comment]
This was fixed in #3977 (thanks @SalvatorePreviti !)
