### ISSUE TITLE
JSC_JS_MODULE_LOAD_WARNING Failed to load module from URI

### ISSUE THREAD

**Issue by thdoan** [google/closure-compiler#3980]
I'm trying to compile a sample app from Firebase and running into this these errors:

```
[JSC_JS_MODULE_LOAD_WARNING] Failed to load module "https://www.gstatic.com/firebasejs/9.8.1/firebase-auth.js"
[JSC_JS_MODULE_LOAD_WARNING] Failed to load module "https://www.gstatic.com/firebasejs/9.8.1/firebase-app.js"
[JSC_JS_MODULE_LOAD_WARNING] Failed to load module "https://www.gstatic.com/firebasejs/9.8.1/firebase-firestore.js"
```

JavaScript code (mostly copied from Firebase documentation):

```
// Import functions we need from relevant Firebase SDKs
import {
  getAuth,
  signInAnonymously,
} from 'https://www.gstatic.com/firebasejs/9.8.1/firebase-auth.js';

import {
  initializeApp,
} from 'https://www.gstatic.com/firebasejs/9.8.1/firebase-app.js';

import {
  addDoc,
  arrayRemove,
  arrayUnion,
  collection,
  doc,
  getDoc,
  getFirestore,
  onSnapshot,
  updateDoc,
  serverTimestamp,
} from 'https://www.gstatic.com/firebasejs/9.8.1/firebase-firestore.js';
```

My flagfile conf:

```
--compilation_level=ADVANCED_OPTIMIZATIONS
--language_in=ECMASCRIPT_2017
--module_resolution=NODE
--process_common_js_modules
```

I've tried the default BROWSER module resolution and same issue. It doesn't seem like Closure Compiler supports importing from a URI. This could be related to issue 3740.

**Comment by mprobst** [comment]
JSCompiler does not support loading modules from external URLs, it only supports local files on disk.

I'm not sure if we want to support this: downloading external URLs as part of a build is often highly problematic - it implies that your builds will be non-reproducible, and you can get all kinds of fun effects from the network (missing files, arbitrary web server responses, etc).

What's your use case - why do you need to compile this code to begin with?

**Comment by thdoan** [comment]
@mprobst I had a special use case where I need to do my "webpacking" in an MS-DOS batch environment. I was using the [AjaxMin](https://github.com/microsoft/ajaxmin) CLI before and it was working great until I started to use ES6, which isn't supported by AjaxMin. I discovered this project while trying to find a replacement for AjaxMin.
