### ISSUE TITLE
Cannot use the same file for both input and output

### ISSUE THREAD

**Issue by laymonage** [google/closure-compiler#3984]
The closure compiler crashes with no output if the input and output file names are the same. I don't think this is intended behavior because it works fine if the input is passed through stdin.

The use case is simple: I have a .js script that I want to minify, without outputting it to a new file (so just overwrite the existing file).

Running the following:

```shell
google-closure-compiler --js script.js --js_output_file script.js
```

returns a non-zero exit code, and `script.js` contents aren't changed.

However, running

```shell
google-closure-compiler < script.js --js_output_file script.js
```

works fine, and `script.js` now contains the minified script.

**Comment by brad4d** [comment]
Sorry, but this is not something we would want to change.
We're following the standard behavior of many command-line commands that they do not allow output to go into an input file.
