### ISSUE TITLE
Closure Compiler Service API returns an empty response after v20220803

### ISSUE THREAD

**Issue by laymonage** [google/closure-compiler#3985]
The Closure Compiler Service API (https://closure-compiler.appspot.com/compile) returns an empty response for any given input.

Even hitting it from the home page also doesn't work: https://closure-compiler.appspot.com

I know that according to https://developers.google.com/closure/compiler/docs/gettingstarted_api, the API has been deprecated and will be removed. But when? Has it been removed now? If so, then I think the docs and homepage should be updated. Thanks!

**Comment by v88kaye** [comment]
not working for me as well

**Comment by gokaybiz** [comment]
I'm here with same issue.

**Comment by lauraharker** [comment]
Looks like something went wrong after updating the service to use the v20220803 compiler.

Temporarily reverted to the previous v20220719 version

**Comment by brad4d** [comment]
It appears our update script failed to re-create the embedded jar file containing closure library correctly.

I'm working to fix that and also add more error checking to the script so it will prevent pushing a failed build in the future.

**Comment by brad4d** [comment]
The service is now fixed and up-to-date with the current release.

**Comment by laymonage** [comment]
Can confirm that it works now, thanks!
