### ISSUE TITLE
"Variable redefined" with @type annotation, but not otherwise

### ISSUE THREAD

**Issue by supahero1** [google/closure-compiler#3986]
The contents of `test.js`:
```js
class a {
        constructor(b) {
                if(b) {
                        /** @type {number} */
                        this.c = 0;
                } else {
                        /** @type {number} */
                        this.c = 1;
                }
        }
}
```

Output:
```
test.js:8:8: WARNING - [JSC_DUP_VAR_DECLARATION] variable this.c redefined, original definition at test.js:5
  8| 			this.c = 1;
     			     ^

0 error(s), 1 warning(s), 87.5% typed
```

Compiled with `closure-compiler -O ADVANCED --js test.js --js_output_file test.min.js`
Compiler version `v20220601`
The issue does not appear without the type annotations, so naturally I suppose the issues lies within the duplicate checking of types rather than variables themselves. The variable will always be defined only once, and so only one type will be active at any given moment in the class.

Shorter code achieving the same issue, but adds a few warnings about dangerous `this` usage:
```js
function a(b) {
        if(b) {
                /** @type {number} */
                this.c = 0;
        } else {
                /** @type {number} */
                this.c = 1;
        }
}
```

**Comment by concavelenz** [comment]
This is working as intended.  There is only expected to be one type declaration in the constructor.  One option here is to use a "stub declaration" which is a promise to initialize it later:

```
        /** @type {number} */
        this.c;

        if(b) {
           this.c = 0;
        } else {
           this.c = 1;
        }
```
