### ISSUE TITLE
Make character set for renaming customizable

### ISSUE THREAD

**Issue by LiviaMedeiros** [google/closure-compiler#3996]
Character set seems to be hardcoded:
https://github.com/google/closure-compiler/blob/440d1f188e63079fc451a5010c9dbf3e744f5f4d/src/com/google/javascript/jscomp/DefaultNameGenerator.java#L89-L95

- The set is not exhaustive: variable/property name can start with `_`.
- The set contains `$`, which sometimes might be undesired. For example, we can do `Object.assign(someDiv.dataset, dataObj)` and be okay with properties of `dataObj` being mangled; but at some point users will get `DOMException: Failed to set a named property on 'DOMStringMap': 'data-$' is not a valid attribute name.` in runtime.

How about adding something like `--rename_variable_characters` option to adjust naming generation?

**Comment by gunan** [comment]
Thank you for bringing this issue to our attention.

Can we get some more information on why you need renaming on these attributes?

If you like to contribute a means of excluding `$` from the renaming, we can consider that PR.

**Comment by blickly** [comment]
Chad pointed out on the PR that setting `--polymer_version=2` effectively gives this desired behavior already.

So it seems like using that flag even on non-Polymer projects might be a workaround to get the behavior you want without landing a compiler change.

**Comment by blickly** [comment]
@LiviaMedeiros, can you try out adding that flag to your project and let us know if that works for your use case?

**Comment by LiviaMedeiros** [comment]
Yes, adding `--polymer_version=2` did the trick for me. As far as I can tell, it restricts all characters except lowercase letters, which is a bit overkill but is technically desired because it also helps to avoid camelCase conversion.
Also https://github.com/google/closure-compiler/pull/4001#issuecomment-1269869127 mentioned first characters but it seems to be applied to all characters, which is also desired.

If this flag looks like an adequate workaround in terms of reliability (i.e. not just convenient unintended side effect, and safe to use by default), feel free to close the issue.

Thanks!
