### ISSUE TITLE
ADVANCED_OPTIMIZATIONS - An option to keep exports variable in array form

### ISSUE THREAD

**Issue by plouffed** [google/closure-compiler#4005]
### What I am asking for
I would like to perform ADVANCED_OPTIMIZATIONS where the output of array properties stays as they are:
```javascript
obj2['prop'] = 2; // with a flag it could output: a['prop'] = 2; (instead of a.prop = 2;)
```
This will allow to perform multiple compilation without losing exports.

### A simple way to optimize further a code base would be as follows:

1. Compile with a flag like <code>--keep_exports_as_array</code>
2. Compile second time without  the flag

The problem by « compiling a second time » is obvious: all exported variables have been converted to their dot equivalent and the second compilation obfuscate them.

### Example of necessity
Let say you end up with some code like that after a bundle preprocessing:

```javascript

function aModule() {
  /**
   *  @enum {number}
   */
  const a = {
   b: 3,
   c: {
    d:4,
    e:5
   }
  }
  return a;
};

const a = aModule();

console.log(a.b);
console.log(a.c.e);
```
Which compiles to:
```javascript
var a={b:3,c:{d:4,e:5}};console.log(a.b);console.log(a.c.e);
```
One could think that it is the best optimization, but what if I compile the compiled code? I would get this:
```javascript
console.log(3);console.log(5);
```
Which is what I was expected from the first compilation, but somehow the wrapper function prevent this optimization.

### Should I use externs? 
As I am programming with closure-compiler in mind, sometimes I use dot properties and array properties
with the same name: before and after ajax call. So including externs would prevent too much optimization.

Obviously, I could create an extern file for the second compilation, but adding a flag makes things easier and prevent me from making mistakes by forgetting keywords...

**Comment by lauraharker** [comment]
Closure Compiler intentionally does not support re-compiling previously compiled code.

Besides the issue you've found with `a.b` vs. `a['b']`, some other potential issues I can think of (off the top of my head are) 1)  some JSDoc tags like `@nocollapse` affect optimizations, so we'd need to ensure they're included in the output 2) some compiler passes depend on property renaming not having run until ~the end of compilation.

Closing as infeasible. Regarding the wrapper function inhibiting optimizations: possibly this is something we'd want to fix, and we might consider a feature request to improve things. See also https://github.com/google/closure-compiler/wiki/FAQ#how-do-i-submit-a-feature-request-for-a-new-type-of-optimization.
