### ISSUE TITLE
Compilation level BUNDLE always fully parses file instead of only using regex parser

### ISSUE THREAD

**Issue by niloc132** [google/closure-compiler#4006]
The idea of BUNDLE is that files are reordered and slightly wrapped, transpiling only when necessary to allow them all to be in the same file instead of either requiring that the browser load multiple files, or fully transpiling contents (in another optimization level). In theory, this means that the `JsFileRegexParser` should be sufficient to pick up dependencies between the files to correctly order them for output, but at this time `JsAst.getAstRoot` is called for every file passed to the command line runner.

This can be easily confirmed by trying to bundle a small set of files with a breakpoint in `JsAst.parse`. There are roughly two paths to this call - `Compiler.orderInputs` runs before the bundle work gets started (only if the --dependencyMode is set to something that requires dependencies to be directly managed), but `AbstractCommandLineRunner.printBundleTo` also hits this in potentially two ways, if numParallelThreads is greater than 1 (ironically asking the compiler to parallelize will cause it to do substantially more work), or if preventLibraryInjection is false. 

There doesn't seem to be a way to "fix" PrebuildAst directly, but perhaps we could instead invoke CompilerInput.getDependencyInfo() on other threads, which in turn delegates to JsFileRegexParser. With that said, `parseInputs`, which calls `orderInputs` above, also does PrebuildAst work. It might be better to just encourage BUNDLE users to not set numParallelThreads.

But for the other two, the root issue is that while JsFileRegexParser does the parsing work as expected, it is then wrapped by a `LazyParsedDependencyInfo` instead before being returned. Then, several callers invoke `getLoadFlags().get("module")` to see if the file is an "es6" module (uses `import`/`export`), or a "goog" module (uses goog.provide/require/module/etc). However, while LazyParsedDependencyInfo.getLoadFlags() calls to the underlying `AutoValue_SimpleDependencyInfo` delegate to see the initial set of flags, it then calls `ast.getFeatures(compiler)`, which will actually run the parser. Some validation will then occur - if the parsed features happen to suggest that the file is an es6 module but the JsFileRegexParser didn't detect this, there will be an error.

That validation is the only value I see at a glance, and to my untrained eye it would be a compiler bug for the two parsers to disagree (the user shouldn't need to explicitly enable BUNDLE to use es6 modules, but perhaps other compilation levels would need that?), and Feature.MODULES only appears to be set when the parser encounters `import`, `import.meta`, or `export`. At a brief glance, `import.meta` might not be checked for in JsFileRegexParser, which could contribute to this...?

With this in mind, it seems reasonable to introduce convinience methods that call `getLoadFlags().get("module")` and compare to the two known values, "goog" and "es6", returning a boolean for each one. See the linked PR for a proposed draft of this change.

Finally, this doesn't completely remove all parsing - any es6 module needs to be parsed and rewritten to correctly map its imports and exports. Perhaps the PrebuildAst could be limited to only files with module=es6 to let that happen up front.

Here's a quick perf run, new then old. This run is on closure-library's source, some 1k JS files, showing a substantial speedup
```
[colin@runes closure-compiler (master *)]$ time java -jar compiler_new.jar --js ../closure-library/closure/goog/**/*.js --js ../closure-library/closure/goog/*.js --dependency_mode SORT_ONLY --compilation_level BUNDLE --js_output_file `pwd`/out.js

real    0m1.640s
user    0m6.588s
sys     0m0.418s
[colin@runes closure-compiler (master *)]$ time java -jar compiler_new.jar --js ../closure-library/closure/goog/**/*.js --js ../closure-library/closure/goog/*.js --dependency_mode SORT_ONLY --compilation_level BUNDLE --js_output_file `pwd`/out.js

real    0m1.597s
user    0m6.644s
sys     0m0.432s
[colin@runes closure-compiler (master *)]$ time java -jar compiler_new.jar --js ../closure-library/closure/goog/**/*.js --js ../closure-library/closure/goog/*.js --dependency_mode SORT_ONLY --compilation_level BUNDLE --js_output_file `pwd`/out.js

real    0m1.714s
user    0m6.759s
sys     0m0.420s
```
```
[colin@runes closure-compiler (master *)]$ time java -jar compiler_old.jar --js ../closure-library/closure/goog/**/*.js --js ../closure-library/closure/goog/*.js --dependency_mode SORT_ONLY --compilation_level BUNDLE --js_output_file `pwd`/out-old.js

real    0m4.232s
user    0m31.733s
sys     0m1.321s
[colin@runes closure-compiler (master *)]$ time java -jar compiler_old.jar --js ../closure-library/closure/goog/**/*.js --js ../closure-library/closure/goog/*.js --dependency_mode SORT_ONLY --compilation_level BUNDLE --js_output_file `pwd`/out-old.js

real    0m4.187s
user    0m30.468s
sys     0m1.193s
[colin@runes closure-compiler (master *)]$ time java -jar compiler_old.jar --js ../closure-library/closure/goog/**/*.js --js ../closure-library/closure/goog/*.js --dependency_mode SORT_ONLY --compilation_level BUNDLE --js_output_file `pwd`/out-old.js

real    0m4.010s
user    0m32.340s
sys     0m1.040s
```

The contents of the output files are identical, before/after.

**Comment by lauraharker** [comment]
Thanks for doing this investigation! Seems like a good improvement.
