### ISSUE TITLE
EXTERNS: JSON.stringify & JSON.parse should be a static function

### ISSUE THREAD

**Issue by dblachut-adb** [google/closure-compiler#4008]
Ad you can see here:
https://github.com/google/closure-compiler/blob/dd9c2dc0ab581a92e21ce55950799a685258c446/externs/es5.js#L265

Both JSON.stringify & JSON.parse are added via prototype, but those are static functions that does not require `this` argument.

**Comment by lauraharker** [comment]
We could fix the missing `this` type warning by adding `@this {?}` to the JSDoc.

Are there any other problems besides the `this` type?

**Comment by dblachut-adb** [comment]
To be more exact my use case is like this:
```js
var JSONParse = JSON.parse;
console.log(JSONParse("{}"));
```
which gives me an error:
> source.js:2: ERROR - "function (this:JSONType, string, function (string, *): *=): *" must be called with a "this" type
<hr><br>
I did some experiment with your proposal and  unfortunately it seems that it did not fix this issue.

1. externs.js
```js
/**
 * A fake type to model the JSON object.
 * @constructor
 * @this {?}
 */
function JSONType2() {}


/**
 * @param {string} jsonStr The string to parse.
 * @param {(function(this:?, string, *) : *)=} opt_reviver
 * @return {*} The JSON object.
 * @this {?}
 * @throws {Error}
 */
JSONType2.prototype.parse = function(jsonStr, opt_reviver) {};


/**
 * @param {*} jsonObj Input object.
 * @param {(Array<string>|(function(this:?, string, *) : *)|null)=} opt_replacer
 * @param {(number|string)=} opt_space
 * @this {?}
 * @return {string} JSON string which represents jsonObj.
 * @throws {Error}
 */
JSONType2.prototype.stringify = function(jsonObj, opt_replacer, opt_space) {};


/**
 * @type {!JSONType}
 * @suppress {duplicate}
 */
var JSON2;
```
2. source.js
```js
var JSONParse = JSON2.parse;
console.log(JSONParse("{}"));
```
3. compilation command
```
compiler.jar --externs externs.js --js source.js --jscomp_error=accessControls --jscomp_error=checkTypes --jscomp_error=checkVars --jscomp_error=constantProperty --jscomp_error=deprecated --jscomp_error=externsValidation --jscomp_error=globalThis --jscomp_error=invalidCasts --jscomp_error=misplacedTypeAnnotation --jscomp_error=missingProperties --jscomp_error=missingReturn --jscomp_error=nonStandardJsDocs --jscomp_error=suspiciousCode --jscomp_error=undefinedNames --jscomp_error=undefinedVars --jscomp_error=unknownDefines --jscomp_error=uselessCode --jscomp_error=visibility
```
4. results still in error
```
source.js:2: ERROR - "function (this:JSONType, string, function (string, *): *=): *" must be called with a "this" type
console.log(JSONParse("{}"));
```

**Comment by dblachut-adb** [comment]
Actually while we are at it and to do not make another issue I have problem with `Number.parseInt`, the second argument should not be required.
```
ERROR - [JSC_WRONG_ARGUMENT_COUNT] Function Number.parseInt: called with 1 argument(s). Function requires at least 2 argument(s) and no more than 2 argument(s).
  112|         const x = Number.parseInt('10');
                         ^^^^^^^^^^^^^^^^^^^^^^^^
```
If I pass `undefined` it works. Here is the source of the issue: https://github.com/google/closure-compiler/blob/9432f2ae28f46499ece00995c92e21e45e57b815/externs/es6.js#L1730
Similar with global parseInt:
https://github.com/google/closure-compiler/blob/9432f2ae28f46499ece00995c92e21e45e57b815/externs/es3.js#L371

Is there any way to make optional arguments?

**Comment by lauraharker** [comment]
Assigning to myself to add the `@this {?}` type.

re: parseInt - this was a deliberate decision, you can see discussion & a workaround in https://github.com/google/closure-compiler/issues/3548
