### ISSUE TITLE
Advanced compilation always gives error.

### ISSUE THREAD

**Issue by Zibri** [google/closure-compiler#4021]
Is the website at https://closure-compiler.appspot.com/home   down?
The advanced optimization ALWAYS times out and gives error.

**Comment by rahul-kamat** [comment]
advanced optimization is working for me:
![image](https://user-images.githubusercontent.com/42451886/210454626-0b0c15b7-2b0e-45e7-b2a7-6cb940b60d08.png)

**Comment by Zibri** [comment]
![image](https://user-images.githubusercontent.com/855176/210455393-c7beee0d-d732-4e87-aa63-1bf738275a13.png)

**Comment by Zibri** [comment]
If I use incognito mode it works.
No idea why it doesn't in normal mode.

**Comment by gunan** [comment]
We have been only keeping this service up to simplify bug reporting for our open source users.
Therefore, the service is only expected to be able to handle minimal bug reproductions.

Anything larger than those, failures are expected.
I will close this issue, as for small code snippets we can successfully build code using the service.

**Comment by Zibri** [comment]
This does not work:

https://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%2540compilation_level%2520ADVANCED_OPTIMIZATIONS%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250A((z)%253D%253E%257B%250Areturn%2520z%250A%257D)(%2522The%2520quick%2520brown%2520fox%2520jumps%2520over%2520the%2520lazy%2520dog.%2522)

**Comment by Zibri** [comment]
@gunan 
this works in simple but not in advanced.
https://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%2540compilation_level%2520SIMPLE_OPTIMIZATIONS%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250A((z)%253D%253Ez)(%2522The%2520quick%2520brown%2520fox%2520jumps%2520over%2520the%2520lazy%2520dog.%2522)
