### ISSUE TITLE
Accessing NodeList<Element> at any index never returns undefined according to types

### ISSUE THREAD

**Issue by fingerartur** [google/closure-compiler#4027]
Accessing `NodeList<Element>` at any index never returns `undefined` according to the types and it should.

```js
/**
* @type {!Element}
*/
const div = document.getElementsByTagName("div")[1000] // raises no error
```

The last line should raise error that div is potentially undefined. The return type should be `Element` (or `Element|undefined` which should be equivalent).

Possibly related to #4026

Compiler Version: v20221102
Build command:

```
java -jar ./scripts/closureCompiler.jar \
  --entry_point=./src/js/index.js \
  --js=./src/**.js \
  --dependency_mode=PRUNE \
  --warning_level=VERBOSE \
  --js_output_file=./dist/bundle.js \
  --module_resolution=WEBPACK \
  --compilation_level=ADVANCED \
  --jscomp_error=checkDebuggerStatement \
  --jscomp_error=unusedLocalVariables \
  --jscomp_error=reportUnknownTypes \
  --jscomp_error=strictCheckTypes;
```

**Comment by rishipal** [comment]
Do you expect the compiler to always consider the item indexed from the array to be union-ed with undefined? What about dynamic-sized arrays, or when the index into the array is not known statically to be within bounds?

**Comment by fingerartur** [comment]
Closing for the same reasons as described here #4026
