### ISSUE TITLE
Array methods such as `filter`,`map`, `forEach`, `reduce` are not getting type-checked

### ISSUE THREAD

**Issue by fingerartur** [google/closure-compiler#4041]
Some of the most frequently used array methods, the soul of JS programming, are not getting type-checked.

Specifically in methods that accept callback, such as `filter`,`map`, `forEach`, `reduce`, the parameters of the callback have unknown type.

In each of the examples below, all callback parameters are assumed to be `unknown` type, even though they are clearly numbers.
```js
const sum = [1,2,3].reduce((a, b) => a + b, 0);

const positive = [-1,0,1,2,3,4].filter((item) => item > 2);

[1,2,3,4].forEach((item) => console.log('item: ', item));

const double = [1,2,3,4].map((item) => item * 2);
```

The best way to check this is to use the `--jscomp_error=reportUnknownTypes` compiler option. With this option the compiler raises the following error whenever a callback parameter is used:

```
ERROR - [JSC_UNKNOWN_EXPR_TYPE] could not determine the type of this expression
```

Compiler Version: v20221102

Build command:
```
java -jar ./scripts/closureCompiler.jar \
  --entry_point=./src/js/index.js \
  --js=./src/**.js \
  --dependency_mode=PRUNE \
  --warning_level=VERBOSE \
  --js_output_file=./dist/bundle.js \
  --module_resolution=WEBPACK \
  --compilation_level=ADVANCED \
  --jscomp_error=checkDebuggerStatement \
  --jscomp_error=unusedLocalVariables \
  --jscomp_error=reportUnknownTypes \
  --jscomp_error=strictCheckTypes;
```

**Comment by blickly** [comment]
I believe that the root issue in these cases is the missing support for checking array literals, and that this is thus a duplicated of https://github.com/google/closure-compiler/issues/312

**Comment by fingerartur** [comment]
Good catch I did not realise that. You are right with one exception.

First, here is a proof that you are right - this code gets checked correctly:
```js
/**
 * @type {Array<number>}
 */
const arr = [1,2,3]
const double = arr.map((item) => item * 2);
```

The exception is the `reduce` method:
```js
/**
 * @type {Array<number>}
 */
const arr = [1,2,3]
const sum = arr.reduce((a, b) => a + b, 0); // Still getting an error: ERROR - [JSC_UNKNOWN_EXPR_TYPE] could not determine the type of this expression
```

**Comment by fingerartur** [comment]
I will move that to a new issue #4044
