### ISSUE TITLE
README.md Compiler Args documentation missing new supported ECMAScript versions

### ISSUE THREAD

**Issue by janhaertel** [google/closure-compiler#4045]
In the WIKI there are more **Compiler args** for **language_in** and **language_out** (ECMASCRIPT_2020,ECMASCRIPT_2021) than in the **README.md**.

**Comment by brad4d** [comment]
I'll update the `README.md` file with a pointer to the [Flags and Options page](http://go/closure-compiler-wiki/Flags-and-Options), which is updated during each release.
