### ISSUE TITLE
Closure modules defined with `goog.module` and `goog.require` do not work out-of-the-box

### ISSUE THREAD

**Issue by fingerartur** [google/closure-compiler#4049]
Closure modules defined with `goog.module` and `goog.require` do not work out-of-the-box. And the documentation [here](https://github.com/google/closure-compiler/wiki/JS-Modules) and [here](https://github.com/google/closure-library/wiki/goog.module:-an-ES6-module-like-alternative-to-goog.provide) does not specify how to get them to work, neither does FAQ. Actually I have not been able to get them to work at all.

Example:
```js
// ./src/js/index.js

goog.module('index')
// This declaration is here to work around an issue https://stackoverflow.com/questions/30784383/using-modules-in-google-closure-compiler

const utils = goog.require('utils'); // Raises ERROR - [JSC_MISSING_MODULE_OR_PROVIDE] Required namespace "utils" never defined.

console.log('add 1,2', utils.add(1, 2));

/**
* @type {{
*  require: Function,
*  provide: Function,
*  module: Function,
* }}
*/
var goog;
// This declaration is here to work around an issue https://github.com/google/closure-compiler/issues/4048
```

```js
// ./src/js/utils.js
goog.module('utils');

 /**
   * @param {number} a 
   * @param {number} b 
   * @returns {number}
   */
exports.add = (a, b) => a + b;
```

The compiler has not noticed that I have defined the dependency `utils` with `goog.module('utils');`.

It is possible that this is not a bug and that I just don't know what I have to do to make `goog.module` work. So there are two possible ways to fix this issue:
1. Either fix the error.
2. Or supplement the documentation, give a clear example how to use `goog.module` with `goog.require` that works out-of-the-box.

Compiler Version: v20221102

Build command:
```
java -jar ./scripts/closureCompiler.jar \
  --entry_point=./src/js/index.js \
  --js=./src/**.js \
  --dependency_mode=PRUNE \
  --warning_level=VERBOSE \
  --js_output_file=./dist/bundle.js \
  --module_resolution=WEBPACK \
  --compilation_level=ADVANCED \
  --jscomp_error=checkDebuggerStatement \
  --jscomp_error=unusedLocalVariables \
  --jscomp_error=reportUnknownTypes \
  --jscomp_error=strictCheckTypes;
```
Related [this issued on stackoverflow](https://stackoverflow.com/questions/30784383/using-modules-in-google-closure-compiler).
Slightly related #4048.

**Comment by brad4d** [comment]
closure-compiler is intended to be used with closure-library.

I have added a note flagged as **IMPORTANT** here

https://github.com/google/closure-library/wiki/goog.module:-an-ES6-module-like-alternative-to-goog.provide

to point out that the `closure/goog/base.js` file should be included as a `--js` input to the compiler.
