### ISSUE TITLE
The list of supported ES features is not updated to include ES2021 and ES2022

### ISSUE THREAD

**Issue by fingerartur** [google/closure-compiler#4051]
[The list of supported ES features](https://github.com/google/closure-compiler/wiki/Supported-features) is not updated. Specifically, it is missing features from [ES2021 and ES2022](https://www.javascripttutorial.net/es-next/).

It seems that the compiler supports ES2021 and ES2022 (e.g. `String.prototype.replaceAll` from ES2022 or `Array.prototype.at` from ES2021 are both supported), it is just not documented.

Compiler Version: v20221102

**Comment by teppeis** [comment]
See compat-table. Updated for the latest Closure Compiler.
https://kangax.github.io/compat-table/es2016plus/

**Comment by brad4d** [comment]
I went and updated the page:

https://github.com/google/closure-compiler/wiki/Supported-features

The source of truth for what features the compiler supports is really this definition and related code.

https://github.com/google/closure-compiler/blob/6bb9dd889aa152a34037425623662766f491774e/src/com/google/javascript/jscomp/parsing/parser/FeatureSet.java#L89

This definition indicates that at the moment it supports `ES_2021` as input and a few bits of `ES_2022`.
