### ISSUE TITLE
Broken links on `Externs For Common Libraries` page

### ISSUE THREAD

**Issue by fingerartur** [google/closure-compiler#4054]
In the [wiki page about Externs For Common Libraries](https://github.com/google/closure-compiler/wiki/Externs-For-Common-Libraries), there are several broken links:

1. https://github.com/firebase/firebase-js-sdk/tree/master/packages/firebase/externs
2. https://github.com/steida/react-externs
3. https://github.com/steida/react-externs/blob/master/externs.js
4. https://github.com/google/closure-compiler/tree/master/contrib/externs/youtubeplayer.js

**Comment by h-joo** [comment]
Thank you for the report, I've just updated the wiki page accordingly.
