### ISSUE TITLE
Advanced compilation breaks libraries from node_modules (e.g. Lodash)

### ISSUE THREAD

**Issue by fingerartur** [google/closure-compiler#4055]
Advanced compilation `--compilation_level=ADVANCED` potentially breaks libraries from `node_modules`, depending on their source code. A good example of a library that breaks is **lodash**.

The explanation is quite simple, [advanced compilation requires certain restrictions](https://developers.google.com/closure/compiler/docs/limitations) on source code to be met and when using a library from node_modules, I cannot know if the library meets these criteria and if it doesn't I do not have any means of fixing that anyway.

In case of Lodash, what happens is that the compilation is successful, and then in runtime I get the following error:

```
Uncaught TypeError: Cannot set properties of undefined (setting 'placeholder')
```

This error does not happen when `--compilation_level=SIMPLE` is used - proving that it came about as a result of advanced optimization.

A possible way of solving this problem would be to add a compiler flag, which prevents the compiler from minifying/optimizing code located in `node_modules` as a whole, or in specific sub-directories (such as `node_modules/lodash`).

Compiler Version: v20230103

Build command:

```
java -jar ./scripts/closureCompiler.jar \
  --entry_point=./src/js/index.js \
  --js=./src/**.js \
  --dependency_mode=PRUNE \
  --warning_level=VERBOSE \
  --js_output_file=./dist/bundle.js \
  --process_common_js_modules=true \
  --module_resolution=NODE \
  --js=node_modules/lodash/package.json \
  --js=node_modules/lodash/**.js \
  --hide_warnings_for=node_modules \
  --compilation_level=ADVANCED;
```

**Comment by niloc132** [comment]
> A possible way of solving this problem would be to add a compiler flag, which prevents the compiler from minifying/optimizing code located in node_modules as a whole, or in specific sub-directories (such as node_modules/lodash).

This is almost certainly much harder than it sounds - the "correct" solution today would be to simply not include those sources in the build, but instead offer externs (which describe the names/members/types of the library), and closure will leave references to those external libraries intact, then invoke the compiler with compilation_level=SIMPLE (or some other bundler/treeshaker) to end up with only one JS output file.

Asking closure-compiler to automatically do the above steps requires first assuming that it is possible for the compiler to auto-generate those externs in an accurate and complete way, which isn't feasible for an arbitrary JS library. The static type information has to come from somewhere for ADVANCED compilation to do what you would expect of it.

**Comment by fingerartur** [comment]
> the "correct" solution today would be to simply not include those sources in the build, but instead offer externs (which describe the names/members/types of the library), and closure will leave references to those external libraries intact

Could you elaborate a little on this? 
```
ERROR - [JSC_JS_MODULE_LOAD_WARNING] Failed to load module "lodash"
