### ISSUE TITLE
Transpile some ES6 features to ES5

### ISSUE THREAD

**Issue by MatrixFrog** [google/closure-compiler#406]
We need to decide which features we want to "step down" from 6 to 5, and probably add a `language_out` flag so users can specify that is what they want to do.

**Comment by concavelenz** [comment]
I think we can close this if we have a document talking about what we don't support.

**Comment by MatrixFrog** [comment]
We report a clear error for things we don't support. I think there is also a document somewhere; I'll try to dig it up if needed.
