### ISSUE TITLE
`CompilerOptions` is a giant object needing a refactoring

### ISSUE THREAD

**Issue by KOLANICH** [google/closure-compiler#4062]

**Comment by brad4d** [comment]
I'm sorry, but this is far too vague a statement to be actionable.

It would be great if we could eliminate some of our many options, but I don't see any benefit in breaking up the representation of options into multiple objects.

**Comment by KOLANICH** [comment]
>breaking up the representation of options into multiple objects.

Yeah, that is exactly what I meant to be done.

No benefit in the terms of raw count of lines of code within functions prototypes, but it can make prototypes of some functions smaller, so making them a bit easier to deal with.

**Comment by brad4d** [comment]
I'm afraid I don't understand what you mean.
For one thing, "functions prototypes" doesn't mean anything to me when we're talking about Java code rather than JavaScript.
Perhaps you'd like to elaborate?

**Comment by KOLANICH** [comment]
I have created Python bindings to Closure Compiler. [The prototype of `createCompilerOptions` function](https://github.com/KOLANICH-libs/ClosureCompiler.py/blob/40886c07ff00504ac2a2d7f213a3835e170a79eb/ClosureCompiler/lowLevel.py#L260-L322) is enormous, despite it covers only subset of functionality of `CompilerOptions`. I'd prefer to split it into several functions, but it'd be better if the hierarchy for organizing all these arguments was mirroring the hierarchy of types within Closure Compiler instead of being just a system to be later demolished and flattened.

**Comment by brad4d** [comment]
Very interesting. Thanks.

I can see how the size of the `CompilerOptions` class is annoying for your python library, but I don't quite see where the maintenance of closure-compiler itself would be improved by breaking up this class.

I'm not entirely sure what you mean by "mirroring the hierarchy of types within Closure Compiler".
Are you assuming that most options specifically affect a single class with the possible addition of its subclasses?
Are you picturing having separate `FooOptions` and `BarOptions` objects for options that affect the `Foo` and `Bar` classes?

**Comment by KOLANICH** [comment]
No, I mean just grouping the functionality of settings that are usually changed together into classes, used as types of fields within `CompilerOptions`, so `createCompilerOptions` can contain not the bunch of "all" of them, but can contain a few fields, and if a user (of an API) has to change a prop, it is likely he also needs to change an another prop. I can suggest such groups, but I guess my suggestions are poor here since I'm a newbie in using Closure Compiler (before I only used it via CLI and with setting few flags).
