### ISSUE TITLE
--chunk_output_type=ES_MODULES doesn't preserve esm exports

### ISSUE THREAD

**Issue by icy0307** [google/closure-compiler#4084]
According to the [wiki](https://github.com/google/closure-compiler/wiki/Chunk-output-for-dynamic-loading),
> The compiler will output es modules and cross chunk references will utilize the import and export statements. Since modules have built in isolation and modern browsers know how to load them, this option is by far the easiest.

However,  the below code produces empty export
```
export class Bar {
    bar() {
        console.log('ADVANCED');
    }
}

```
` npx google-closure-compiler --js=class-bar.js  --module_resolution=NODE --chunk_output_type=ES_MODULES`

the output is `export{};`.
Is this empty export an intentional behavior? `only exists for <script type="module">`? @ChadKillingsworth 

I notice some tools, like [rollup-plugin-closure-compiler](https://github.com/ampproject/rollup-plugin-closure-compiler)， make a great effort to preserve esm module syntax.
By utilizing [google closure compiler export mechanism](https://developers.google.com/closure/compiler/docs/externs-and-exports#purpose-of-exports), adding window['Bar'] to avoid renaming.
Why closure-compiler doesn't support esm export by default?

**Comment by ChadKillingsworth** [comment]
This is working as designed. The export is never referenced therefore the entire class is eliminated. The `export {}` statement exists to enforce that the output module is ESM and not a script. See https://developers.google.com/closure/compiler/docs/externs-and-exports#purpose-of-exports as that's why the rollup plugin adds an export.

**Comment by icy0307** [comment]
Thanks for your detailed explanation！😀
