### ISSUE TITLE
Does the latest version not support JDK8? Can the latest version compiled by JDK8 be provided?

### ISSUE THREAD

**Issue by zhchhawks** [google/closure-compiler#4086]
Does the latest version not support JDK8? Can the latest version compiled by JDK8 be provided?

Some of the components my project depends on do not support jdk11, which is contradictory.

**Comment by brad4d** [comment]
Sorry, no, we've moved forward and now require JDK11. It would just be a maintenance burden with no benefits for our team to try to maintain a version that works with JDK8.
