### ISSUE TITLE
using clousre compiler to compress three.js, got an error

### ISSUE THREAD

**Issue by liyqxtu** [google/closure-compiler#4088]
google-closure-compiler -O ADVANCED three.js --js_output_file three.min.js
three.js:26107:24: ERROR - [JSC_UNDEFINED_VARIABLE] variable XRWebGLLayer is undeclared
  26107|                                                glBaseLayer = new XRWebGLLayer( session, gl, layerInit );
                                                                          ^^^^^^^^^^^^

three.js:26142:22: ERROR - [JSC_UNDEFINED_VARIABLE] variable XRWebGLBinding is undeclared
  26142|                                                glBinding = new XRWebGLBinding( session, gl );
                                                                        ^^^^^^^^^^^^^^

2 error(s), 0 warning(s)

**Comment by concavelenz** [comment]
Why do you believe it should be exist? 

https://developer.mozilla.org/en-US/docs/Web/API/XRWebGLBinding states it is an experimental technology and as such won't be expected to be part of hte standard definitions.  If you want to use it you should either suppress the errors (in which case the compiler will pretend a definition exists) or provide it with a definition of the variables.

https://developers.google.com/closure/compiler/docs/api-tutorial3 provides some basic background if you haven't already see it.
