### ISSUE TITLE
Google closure compiler reports JSC_UNDEFINED_VARIABLE errors on javascript keywords

### ISSUE THREAD

**Issue by ghevge** [google/closure-compiler#4090]
Can anyone help me please with this problem: https://stackoverflow.com/questions/76149231/google-closure-compiler-reports-jsc-undefined-variable-errors-on-javascript-keyw

I've posted the details in the stackoverflow question above.
Thanks!

**Comment by h-joo** [comment]
I've noticed that you've found a workaround, so I'll close this for now. Please reopen if you again face the same issue.
