### ISSUE TITLE
Add Navigator.doNotTrack to browser externs

### ISSUE THREAD

**Issue by rr-it** [google/closure-compiler#4101]
Which is the correct default externs file to add `Navigator.doNotTrack`?
+ [externs/browser/gecko_dom.js](https://github.com/google/closure-compiler/blob/master/externs/browser/gecko_dom.js)  as used for `Navigator.sendBeacon`?

Additional information:
+ [W3C: Tracking Preference Expression: JS DOM](https://www.w3.org/TR/tracking-dnt/#js-dom)
+ [MDN: Web API: `Navigator.doNotTrack`](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/doNotTrack)
+ [MDN: Web API: `Navigator.doNotTrack` browser compatibility](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/doNotTrack#browser_compatibility): 'Before version 17, Edge implemented `window.doNotTrack`.'
+ [Microsoft: IE 9: `document.navigator.msDoNotTrack`](https://learn.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/platform-apis/gg699492(v=vs.85)#remarks)

**Comment by brad4d** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Navigator/doNotTrack#browser_compatibility

Since there is a big warning about it being deprecated and likely already gone in modern browsers, the answer is "nowhere".

If you need it yourself, the thing to do is create an externs file (`@externs` annotation in the `@fileoverview` comment) that defines it and use it just for your project.

**Comment by rr-it** [comment]
@brad4d Thank you for looking into this.

The [usage statistic on Caniuse](https://caniuse.com/do-not-track) says that ~78 % of global users use a browser that has `Navigator.doNotTrack` implemented.

**Comment by brad4d** [comment]
@rr-it Thanks for pointing out the percentage statistic.

Please see https://en.wikipedia.org/wiki/Do_Not_Track

I'm particularly looking at the "Adoption" section.

We apparently didn't need it in the default externs before now.
Regardless of whether this is still supported by a majority of browsers, it is clearly on its way out and is of minimal use, so there really doesn't seem to be any good reason to add it now.
