### ISSUE TITLE
MediaStreamTrackProcessor Constructor

### ISSUE THREAD

**Issue by nicopowa** [google/closure-compiler#4109]
I've been compiling a project using MediaStreamTrackProcessor instances for a long time, it was not included in the compiler so I was using a custom extern file with the following content : 

```
/**
 * @constructor 
 * @param {MediaStreamTrack} track : 
 */
var MediaStreamTrackProcessor = function(track) {};
```

The latest version returned a redeclared variable error, so I removed my extern file and got a new error : MediaStreamTrackProcessor is not constructor.

[externs.zip//w3c_rtc.js:3645:9](https://github.com/google/closure-compiler/blob/84e1928a81d2c267db88f551dacba0b0d04946dd/externs/browser/w3c_rtc.js#L3640)

I added two suppress annotations and re-included my externs file.

```
/**
 * @suppress {duplicate}
 * @suppress {checkTypes}
 * @constructor 
 * @param {MediaStreamTrack} track : 
 */
var MediaStreamTrackProcessor = function(track) {};
```

My project is compiling properly but I still get warnings about MediaStreamTrackProcessor not being a constructor.

**Comment by h-joo** [comment]
Would you mind sending a PR to update what correctly reflects the spec?

**Comment by nicopowa** [comment]
It would be my first pull request :-D
According to the docs, MediaStreamTrackProcessor should be a constructor.
Closure is one of the best programs I ever used.
Maybe I should share the code I built on top of it to compile all my vanilla ice cream projects with one click :)

**Comment by niloc132** [comment]
I'd be happy to work with you to get the PR ready to go. 

Sharing how you run the compiler would be great too - maybe a good post to [discussions](https://github.com/google/closure-compiler/discussions)?

**Comment by nicopowa** [comment]
That would be nice, maybe this week-end ? Should I clone the repository ?

I opened a [discussion ](https://github.com/google/closure-compiler/discussions/4112)!
