### ISSUE TITLE
Unknown diagnostic group: '2022'

### ISSUE THREAD

**Issue by Chester1978** [google/closure-compiler#4110]
When working with Google Closure Compiler, I like to be as strict as possible.

I like to use this flag: --jscomp_error *. I've always found this approach better than enumerating all possible errors.

According to the documentation, this option is still valid:
--jscomp_error VAL
Makes the named class of warnings an error. Must be one of the error group items. '*' adds all supported.

After January 2023, this was the first time I updated to a new version. I've noticed that even for very basic codes, with just one function for testing, I get the message "Unknown diagnostic group: '2022'" when using this flag. If I remove it, everything works fine.

**Comment by brad4d** [comment]
Try `--jscomp_err=*`

Do you, perhaps, have a file or directory named "2022" in the directory where you ran the command?

**Comment by Chester1978** [comment]
Yes, I have a directory with this name. Working fine now.  
Thank you!
