### ISSUE TITLE
ES2020 private members not supported

### ISSUE THREAD

**Issue by pfusik** [google/closure-compiler#4119]
C:\0\a8\asap>cat private.js
    class Foo
    {
        #privateField = 42;
        getAnswer() { return this.#privateField; }
    }

    C:\0\a8\asap>closure-compiler --version
    Closure Compiler (http://github.com/google/closure-compiler)
    Version: v20230802

    C:\0\a8\asap>closure-compiler private.js
    private.js:3:1: ERROR - [JSC_PARSE_ERROR] Parse error. '}' expected
      3|    #privateField = 42;
            ^

    1 error(s), 0 warning(s)

**Comment by lauraharker** [comment]
Please see https://github.com/google/closure-compiler/issues/2731 for updates on public & private class fields.
