### ISSUE TITLE
add getTargetRanges()

### ISSUE THREAD

**Issue by johanneswilm** [google/closure-compiler#4125]
> // TODO(charleyroy): Add getTargetRanges() once a consensus has been made
// regarding how to structure these values. See
// https://github.com/w3c/input-events/issues/38.
/**

https://github.com/google/closure-compiler/blame/38f2f840f50c96a823babcc2540838faa733fbf0/externs/browser/w3c_event.js#L553-L556

In the mentioned TODO it mentions an issue that since has been resolved. `getTargetRanges()` is being shipped by every major browser and has been for more than two years now.

**Comment by dloyda** [comment]
fixed
