### ISSUE TITLE
Removal of non deprecated method SourceFile fromInputStream

### ISSUE THREAD

**Issue by Lonzak** [google/closure-compiler#4157]
I wanted to update our (pretty) old version of the closure-compiler to a newer one. I was able to fix all issues except for the following. We are using the following method:

`SourceFile.fromInputStream(name, inpustream, StandardCharsets.UTF_8);`

The method still exists in version [v20210601](https://github.com/google/closure-compiler/releases/tag/v20210601) but was removed in version [v20210808](https://github.com/google/closure-compiler/releases/tag/v20210808)

Removal of deprecated method is not uncommon however there are two methods: one deprecated and one without deprecations - and both were removed. The commit can be found [here](https://github.com/google/closure-compiler/commit/f4e895567c549313230696aeb7297c1b92e3b5dd#diff-e85a83895f161d98c331c58e028f6a49684bde88f04f460fedd564e781a4b26f).

```
@Deprecated
  @GwtIncompatible("java.io.InputStream")
  public static SourceFile fromInputStream(String fileName, InputStream s)
      throws IOException {
    return builder().withPath(fileName).withContent(s).build();
  }

  @GwtIncompatible("java.io.InputStream")
  public static SourceFile fromInputStream(String fileName, InputStream s, Charset charset)
      throws IOException {
    return builder().withPath(fileName).withCharset(charset).withContent(s).build();
  }
```

The removal of an non deprecated method is not a good idea. Was this intentional? Could the method be added again?

**Comment by lauraharker** [comment]
Does switching `SourceFile.fromInputStream(fileName, s, charset);` => `SourceFile.builder().withPath(fileName).withCharset(charset).withContent(s).build();` work?

I agree it's best practice to deprecate methods before removing them, but as the SourceFile builder API still supports this pattern and it's been gone for a few years, I don't think it's reasonable to add back at this point.

**Comment by Lonzak** [comment]
Yes that is what I did - I replaced it with the code you mentioned... Some migration guide would have been helpful - took quite some research to figure that out :-)

**Comment by lauraharker** [comment]
Added something to the 20210808 release notes at https://github.com/google/closure-compiler/wiki/Releases#august-8-2021-v20210808.
