### ISSUE TITLE
Incorrect removal of parentheses

### ISSUE THREAD

**Issue by zhantx** [google/closure-compiler#4171]
Closure compiler removes parentheses from class declaration rendering the output code to be illegal 
input
```
let _Component;
class Component {}
class P extends (_Component = Component) {}
```
output
```
'use strict';
let _Component;
class Component {
}
class P extends _Component = Component {
}
;
```
The assignment at supercalss must have parentheses
<img width="1202" alt="image" src="https://github.com/google/closure-compiler/assets/14803931/891ac7d6-f3de-414b-a843-89cdcf637afb">

**Comment by brad4d** [comment]
@dloyda is working on this.

**Comment by dloyda** [comment]
Fixed by https://github.com/google/closure-compiler/commit/5a20d7dc12cf9acad8c84e3fe4e2bf10dec3ed0e
