### ISSUE TITLE
"Scorecard supply-chain security" GitHub CI action has been consistently failing

### ISSUE THREAD

**Issue by lauraharker** [google/closure-compiler#4175]
Example: https://github.com/google/closure-compiler/actions/runs/9704666554/job/26785314354

```
Error: Unable to resolve action `ossf/scorecard-action@v2`, unable to find version `v2`
```

**Comment by blickly** [comment]
Not a meaningful fix, but the misconfigured action is at least turned off as of https://github.com/google/closure-compiler/pull/4176, allowing us to see when the build breaks.
