### ISSUE TITLE
Release notes missing for v20231112

### ISSUE THREAD

**Issue by dasa** [google/closure-compiler#4193]
v20231112 exists at:
https://mvnrepository.com/artifact/com.google.javascript/closure-compiler/v20231112

There's no release notes for this version at:
https://github.com/google/closure-compiler/wiki/Releases

**Comment by 12wrigja** [comment]
https://github.com/google/closure-compiler/wiki/Releases

I fixed this - somehow the release notes for that release were bundled into the notes for the next release.
