### ISSUE TITLE
error installing ionic/react

### ISSUE THREAD

**Issue by sstraust** [google/closure-compiler#4196]
Hi! I attempted to install @ionic/react via npm, and I'm getting the following error message. The error message reads "INTERNAL COMPILER ERROR. Please report this problem",

so:

--- I'm reporting it!

LMK what's going on or if you need any more info

Failed to inspect file
/Users/sam/sstraust/eventplanner/eventplannerjs/node_modules/@ionic/core/node_modules/@stencil/core/internal/client/index.js

Errors encountered while trying to parse file
/Users/sam/sstraust/eventplanner/eventplannerjs/node_modules/@ionic/core/node_modules/@stencil/core/internal/client/index.js
{:line 1, :column 1, :message "The file could not be parsed as JavaScript."}

RuntimeException: INTERNAL COMPILER ERROR.
Please report this problem.

file uses import() with unsupported arguments and cannot be processed
Node(DYNAMIC_IMPORT): /Users/sam/sstraust/eventplanner/eventplannerjs/node_modules/@ionic/core/node_modules/@stencil/core/internal/client/index.js:81:9
[source unknown]
Parent(GETPROP then): /Users/sam/sstraust/eventplanner/eventplannerjs/node_modules/@ionic/core/node_modules/@stencil/core/internal/client/index.js:87:4
[source unknown]

**Comment by lauraharker** [comment]
Hey @sstraust , was there any more of the stack trace in the error message you could add?

I'm asking because I can't find this error message anywhere in the Closure Compiler repo - maybe this is another tool that's a Closure Compiler plugin.

**Comment by sstraust** [comment]
here's a link to the original report:

https://github.com/thheller/shadow-cljs/issues/1208#issuecomment-2410737327

I'm not an expert on this stuff, so I'm not sure where to point to here

**Comment by lauraharker** [comment]
Thanks!

The error is being thrown here: https://github.com/thheller/shadow-cljs/blob/896dcffa84477e1452bb635dfa17df2da7a1eb09/src/main/shadow/build/closure/JsInspector.java#L125-L132

I think the right thing is to close this issue & reopen https://github.com/thheller/shadow-cljs/issues/1208#issuecomment-2410737327 - if there's anything actionable we can do to support https://github.com/thheller/shadow-cljs/issues/1208#issuecomment-2410737327 please do file another issue.
