### ISSUE TITLE
Function hoisting difference when names overlap

### ISSUE THREAD

**Issue by hills** [google/closure-compiler#4204]
This minimal test case shows some kind of difference in function hoisting between Closure Compiler and Node/Chromium/Firefox.

It seems Closure Compiler deduces the inner ```jjj()``` declaration to be out of scope, which I would expect. But who's correct here?

FWIW the behaviour from Closure Compiler is the one that matched my expectations, and is superior because the addition of a new scope with ```{}``` cannot cause changes in behaviour to existing code. But I imagine the interpreter has some legacy here.

No relevant compiler warnings present themselves (neither in this example nor with ```--jscomp_error '*'``` which I normally use in production)

```
jjj();
aaa();
setTimeout(aaa, 0);

function aaa() {
    jjj();
}

function jjj() {
    console.warn('out');
}

{
    function jjj() {
        console.warn('in');
    }
}
```

```
$ node test.js
out
out
in                <--- surprise!
```

```
$ node --version
v20.15.1
```

```
$ java -jar closure-compiler-v20240317.jar --formatting PRETTY_PRINT -O ADVANCED test.js
console.warn("out");
console.warn("out");
setTimeout(a, 0);
function a() {
  console.warn("out");
}
;
```

```
$ java -jar closure-compiler-v20240317.jar --formatting PRETTY_PRINT -O WHITESPACE_ONLY test.js
jjj();
aaa();
setTimeout(aaa, 0);
function aaa() {
  jjj();
}
function jjj() {
  console.warn("out");
}
{
  function jjj() {
    console.warn("in");
  }
}
;
```

Modifying the example shows that it is _not_ caused by the compiler eliminating the un-used ```jjj()```. It further demonstrates the difference:

```
jjj();
aaa();
setTimeout(aaa, 0);

function aaa() {
    jjj();
}

function jjj() {
    console.warn('out');
}

{
    function jjj() {
        console.warn('in');
    }

    jjj();                // new addition
}

jjj();                 // new addition
```

```
$ node test2.js
out
out
in
in
in
```

```
$ java -jar closure-compiler-v20240317.jar --formatting PRETTY_PRINT -O ADVANCED test2.js
a();
a();
setTimeout(b, 0);
function b() {
  a();
}
function a() {
  console.warn("out");
}
console.warn("in");
a();
```

**Comment by shicks** [comment]
This has to do with strict vs sloppy mode.  If you run your NodeJS examples in strict mode, you'll see behavior consistent with the compiler.

I don't know what the defaults are for the options you're currently using, nor if you're able to tell it to use sloppy mode behavior.  In general, we try to run everything we can in strict mode, so in that case everything is consistent.  Do you have a use case where you need sloppy mode behavior?

**Comment by shicks** [comment]
I discussed this with the team - the compiler always assumes strict mode, so this is working as intended.

**Comment by hills** [comment]
Ah yes, you're totally correct. Thanks for taking the time here. I had heard of "strict" mode but didn't know of its relevance to this.

I appreciate closing the ticket, and apologise for sending you down a rabbit hole. But to avoid that in future could it be better to:

* document the behaviour? No explanation of strict assumption in the wiki documentation, not even [here](https://github.com/google/closure-compiler/wiki/Compiler-Assumptions)
* warn if "use strict" is not present in the source code? Since the compiler does not implement the opposite

The latter would avoid divergence in behaviour when built with ADVANCED vs WHITESPACE_ONLY. Even better (but harder) it could warn only if some code is present that leans on the strict behaviour.
