### ISSUE TITLE
Problems with --flagfile, --output_wrapper, and line feeds.

### ISSUE THREAD

**Issue by ghost** [google/closure-compiler#436]
Quotation marks around the `--output_wrapper` value in a flag file are treated as though they are part of the output wrapper, this prevents the use of any spaces within the output wrapper because the spaces are treated as argument separators.

The problem becomes obvious when you try to do something like the following ...

`--output_wrapper (function(){%output%})() //# sourceMappingURL=output.js.map`

The use of quotation marks around flag values should be consistent with command-line consoles which allow you to do something like the following without any unexpected behaviour ...

`--output_wrapper "(function(){%output%})() //# sourceMappingURL=output.js.map"`

Also line feeds within the output wrapper are not parsed correctly, the `\n` characters appear as-is in the generated file. This happens when using `--output_wrapper` on the command-line as well as in a flag file.

**Comment by kirschkern** [comment]
The following worked for me on Windows 10:

--output_wrapper=$"%output%
//# sourceMappingURL=../../js/core/runtime.map"

Yes, two lines
