### ISSUE TITLE
AMD conversion for libs with "optional" define() calls (such as those that exist in jQuery, Lo-Dash, etc.) throw an error

### ISSUE THREAD

**Issue by gregjacobs** [google/closure-compiler#457]
When trying to compile AMD modules that depend on libraries which have an "optional" `define()` call (such as jQuery or Lo-Dash), the compiler throws an error: "The define function must be called as a top-level statement."

This is the case with jQuery and other libraries, where the library only defines itself as an AMD module in the presence of an AMD loader (ex: RequireJS). You can see this call to `define()` about 30 lines up from the bottom of http://code.jquery.com/jquery-1.11.1.js:

```javascript
if ( typeof define === "function" && define.amd ) {
	define( "jquery", [], function() {
		return jQuery;
	});
}
```

Here is the error that is shown:
![image](https://cloud.githubusercontent.com/assets/302273/3143728/0c0bc050-ea08-11e3-8ab7-b17acb289cd7.png)

**Comment by avindra** [comment]
Hi, is there support for AMD loading underway? Having goog.require's in our code is kind of ugly.

**Comment by ChadKillingsworth** [comment]
See #1048. I actually think it closes this issue.

**Comment by Geoffrey-A** [comment]
I observed the same error as in the OP, with the latest version:

```
% npm --version
5.4.2
% npm install google-closure-compiler

% alias cc='java -jar node_modules/google-closure-compiler/compiler.jar'
% cc --version
Closure Compiler (http://github.com/google/closure-compiler)
Version: v20170910
Built on: 2017-09-12 14:27

% curl -sO http://code.jquery.com/jquery-1.11.1.js
% cc jquery-1.11.1.js --transform_amd_modules
jquery-1.11.1.js:10269: ERROR - The define function must be called as a top-level statement.
        define( "jquery", [], function() {
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

1 error(s), 0 warning(s)
```
Is it expected?
How can I work around that?

**Comment by ChadKillingsworth** [comment]
I intend to remove AMD module processing from the compiler entirely. It's unmaintained. You should switch to CommonJS or ES6 modules.
