### ISSUE TITLE
DeclareGlobalExternsOnWindow breaks non-browser environments

### ISSUE THREAD

**Issue by nicks** [google/closure-compiler#464]
DeclareGlobalExternsOnWindow assumes that there's a global window, which is not necessarily true. If you're using custom externs for non-browser environments, then window will not exist, and the compiler will spew all sorts of internal errors.

Some possible ideas:
1) DeclareGlobalExternsOnWindow checks if there's a global window, and does nothing if it doesn't exist.
2) DeclareGlobalExternsOnWindow falls back to other global symbols on other environments ("window", "globals", "this")
3) Add a flag to turn this option off

these ideas aren't necessarily mutually exclusive.
thoughts?

**Comment by teotigraphix** [comment]
Hi,

Just adding a bit here, I ran into this problem, I am working on a cross compiler in the Apache Flex project and using the GCC compiler to compile extern files, walk the AST in a couple passes and after all types/members are resolved, emit ActionScript API for use with a JavaScript API emitter.

I have all the es3, es5 and dom externs compiling but, when I started generating the .as code I noticed the Window object had all the global functions added tot he AST, which in my use case wasn't correct.

The only solution I have which seems kind of hackish but worked is subclass CompilerOptions in the com.google.javascript.jscomp package and set the internal declaredGlobalExternsOnWindow to false.

Does this sound right or am I missing something?

Thanks, Mike

**Comment by concavelenz** [comment]
@teotigraphix  Is there a non-global Window object in your environment?

**Comment by teotigraphix** [comment]
Well the way it works is, all global functions that seemed to get attached to the window need to be defined as package level functions in the SWC I compile. So when writing AS, you are just writing;

```alert("foo")``` 

for instance. The "package level" is the global Window namespace when things get cross compiled.

I may be missing something as I have not included all the dom externs yet but, there doesn't seem to be a ```window``` constant that gets parsed, I have looked through all the extern files or searched.
All things from window.js get compiled to package level constants so they are available in code completion, such as `document`;

```document.body```

There is a var const declared for document:HTMLDocument, this works perfectly. As document gets emitted to document.as as a public constant.

Maybe I am just doing something "out of the ordinary" and my question really isn't relevant to the project.

Mike

**Comment by MatrixFrog** [comment]
The original issue as reported here should be fixed now: If there is no `window` then the pass does nothing. @teotigraphix I'm not quite following what you're saying, can you open a new issue if there is still something to be done?

**Comment by teotigraphix** [comment]
No, I had a weird use case for the parser/compiler, so I figured it out in relation to what I needed from the AST and definitions. Thanks. (This was more of a question that a bug)
