### ISSUE TITLE
expose ide mode as a flag

### ISSUE THREAD

**Issue by ghosttie** [google/closure-compiler#478]
I would like to use IDE mode (i.e. error checking but no JS output) but it isn't exposed as a flag.

I think this could be a popular request - see [this discussion](https://groups.google.com/forum/#!topic/closure-compiler-discuss/9AdNq4wmqEE).

**Comment by danbeam** [comment]
what's the resolution to this thread?  is there a CHECKS_ONLY or IDE mode equivalent from flags?

**Comment by ghosttie** [comment]
--checks-only was added in https://github.com/google/closure-compiler/commit/601ce79200d657ebe959181a29c12ee66fc0d43c
