### ISSUE TITLE
Adding additional properties to Event externs

### ISSUE THREAD

**Issue by pauldraper** [google/closure-compiler#527]
For example, the `Event` received from a [`message`](https://developer.mozilla.org/en-US/docs/Web/API/Window.postMessage) listener adds the properties

* `data`
* `origin`
* `source`

Should these be added to the externs?

**Comment by Dominator008** [comment]
Looks like the current `MessageEvent` is exactly what you requested: https://github.com/google/closure-compiler/blob/1f896d0c4139c60bc9c59ccd5f1daa1cc58bac6d/externs/browser/html5.js#L1824-L1863.
