### ISSUE TITLE
Transpilation error with a 'let'-declared var in a case statement.

### ISSUE THREAD

**Issue by MatrixFrog** [google/closure-compiler#567]
Our parser considers the second child of a `case` node to be a block, even if there are no `{}` in the source. So, for this code:

    var foo = 0;
    switch (foo) {
      case 0:
        let y = 1;
      default:
        console.log(y);
    }

Traceur converts it to

    var foo = 0;
    switch (foo) {
      case 0:
        var y = 1;
      default:
        console.log(y);
    }

which I believe is correct, and prints `1`, whereas we get an error when trying to transpile:

    ERROR - variable y is undeclared
        console.log(y);
                    ^

**Comment by rikuayanokozy** [comment]
It's fixed by https://github.com/google/closure-compiler/issues/1208

```
$ java -jar build/compiler.jar --language_in=ES6 --language_out=ES5 test.js  
var foo=0;switch(foo){case 0:var y$0=1;default:console.log(y)};
```
