### ISSUE TITLE
Is there any possibility to pass --angular_pass flag to ant CompileTask?

### ISSUE THREAD

**Issue by voytool** [google/closure-compiler#591]
Hi,

I've been using ant task with closure compiler v20131014 and would like to pass additional flags to it. Is there any way to do so?

**Comment by wolfgangmeyers** [comment]
You're welcome ;)
https://github.com/google/closure-compiler/commit/4129ace5c79deb04f69942c930e4b4d1cd72bd7b#diff-20ea98e4dc915331f2c604b197321610

**Comment by MatrixFrog** [comment]
Oh cool :)
