### ISSUE TITLE
Feature Request: @extends for record types declarations

### ISSUE THREAD

**Issue by nickgeorge** [google/closure-compiler#604]
I'd really like to be able to do something like
```javascript
/**
 * @param {ShapeMessage} message Type-safe data for constructing shape.
 * @constructor
 */
Shape = function(message) {
  this.color = message.color;
};

/**
 * @typedef {{
 *   color: string
 * }}
 */
ShapeMessage;


/**
 * @param {SphereMessage} message Type-safe data for constructing sphere.
 * @constructor
 * @extends {Shape}
 */
Sphere = function(message) {
  goog.base(this, message);
  this.radius = message.radius;
};
goog.inherits(Sphere, Shape)

/**
 * @typedef {{
 *   radius: number
 * }}
 * @extends {ShapeMessage}
 */
SphereMessage;

new Sphere({color: 'white', radius: 5})
```
So then Sphere constructor can call goog.base to run the Shape constructor with the message safely, and then the Sphere constructor can interpret the Sphere-specific stuff itself.  This example is dopey, but you can imagine for larger trees of inheritance that this would be useful.  We create the leaf object with a fully-formed message. The message bubbles up to the base constructor, with each constructor reading the relevant parts, and type-safety guaranteed the whole way by defining a separate `type` for each constructor.

I'd be totally willing to hack around on this for a bit myself if y'all think it's worth it, but thought I'd get your opinions first.

This would obviously wouldn't work if the extended `type` were a primitive, but this should be relatively easy to detect and reject.

**Comment by bvaughn** [comment]
+1 for this request.

I find myself wanting to do the same thing for an API response-type that has some (local-only) data mixed-in by a controller.

**Comment by dimvar** [comment]
We will be making typing for interfaces structural, and this will provide extends for records for free.

**Comment by vpavlenko** [comment]
I've skimmed through the Release Notes but haven't found the answer: if there's already a way to inherit one @typedef from the another? Like reuse one @typedef declaration but add more fields to it?

**Comment by dimvar** [comment]
No there isn't a way to do that.

**Comment by concavelenz** [comment]
There is now experimental support for @record in the compiler.

**Comment by Dominator008** [comment]
`@record` is pretty stable now and can be used with inheritance.
