### ISSUE TITLE
Whitespace only mode breaks goog.module

### ISSUE THREAD

**Issue by concavelenz** [google/closure-compiler#611]
goog.module needs to be wrapped or rewritten and whitespace only mode does neither.

**Comment by concavelenz** [comment]
There is some disagreement on what to do here, as it is "whitespace" only.  Feel free to comment on your expectations.

**Comment by Dominator008** [comment]
@supersteves I assume this has been fixed by your PR (https://github.com/google/closure-compiler/pull/1365/commits/7c1631669e539d46c4532db4df9bc9cf994a2782)?
