### ISSUE TITLE
@enum should error (or warn?) on duplicate values

### ISSUE THREAD

**Issue by MatrixFrog** [google/closure-compiler#619]
```js
/**
 *@enum{number}
 */
MyEnum = {
  ALPHA: 0,
  BETA: 1,
  GAMMA: 2,
  DELTA: 2,
  EPSILON: 3
}
```

This is most likely a mistake; they probably meant DELTA to be 3 and EPSILON to be 4, rather than having two different values that are both 2.

I think this should be a fairly easy change, so if anyone is looking for an excuse to contribute to the compiler, give it a shot! :) Basically, when a node is annotated as `@enum`, we'd iterate over the object lit, looking for duplicates on the right sides of the colons. Report an error/warning when you see a duplicate. Maybe part of the "suspicious code" pass.

**Comment by ducklord** [comment]
Should it not be possible to suppress this behaviour?

**Comment by MatrixFrog** [comment]
I think we put it in the lintChecks so you can `@suppress {lintChecks}`. Generally if there are intentional duplicates it ought to be `@type {!Object<string, number>}` instead of an enum.

**Comment by ducklord** [comment]
That is what i thought from looking at the patch as well. But by tying to suppress lintChecks we just get this error. 
```/src/shared/defines.js:294: WARNING - Parse error. unknown @suppress parameter: lintChecks
 * @suppress {lintChecks}
```
We might have to change it to an object as you say. It is not per say intentional duplicates. It is in our case a @enum {string} that contains ID definitions.
