### ISSUE TITLE
@expose annotation causes JSC_UNSAFE_NAMESPACE warning

### ISSUE THREAD

**Issue by meyertee** [google/closure-compiler#636]
When compiling the following code in advanced mode it produces a `JSC_UNSAFE_NAMESPACE` warning. The problem appears when exposing a field that has a name that's equal to a component in a namespace, even though they are unrelated. Setting the `--use_types_for_optimization` makes no difference.

    // ==ClosureCompiler==
    // @compilation_level ADVANCED_OPTIMIZATIONS
    // @output_file_name default.js
    // @formatting pretty_print
    // ==/ClosureCompiler==
    
    goog.provide("com.whatever.A");
    goog.provide("com.problem.B");

    /**
     * @constructor
     */
    com.whatever.A = function () {
    	/**
    	 * @expose
    	 * @type {string}
    	 */
    	this.problem = "A here!";
    };

    /**
     * @constructor
     */
    com.problem.B = function () {
    	/**
    	 * @type {string}
    	 */
    	this.problem = "B here!";
    };

    var a = new com.whatever.A();
    var b = new com.problem.B();

    console.log(a.problem, b.problem);

You can paste the code into http://closure-compiler.appspot.com/home to see the warnings.

**Comment by moderndegree** [comment]
+1 --export_local_property_definitions would be very helpful

**Comment by moderndegree** [comment]
Any word on this? @meyertee Could you share the changes you made to CommandLineRunner?

**Comment by moderndegree** [comment]
@meyertee I think I got it figured out. I just submitted a pull request that should solve the problem. It appears to be working now.

**Comment by dpashkevich** [comment]
Thanks for merging in the `--export_local_property_definitions` flag into the published jar! I'm working on an Angular app and would really benefit from it. For now I'm using the deprecated `@expose` in the same way. I assume it will come out with the next release?

I have another quesion. The [guide on using Angular with Closure Compiler](http://google-styleguide.googlecode.com/svn/trunk/angularjs-google-style.html#compilerflags) also mentions:

> If you are using @export for properties, you will need to add the flags:
> "--generate_exports",
> "--remove_unused_prototype_props_in_externs=false",
> "--export_local_property_definitions",

It looks like the `remove_unused_prototype_props_in_externs` isn't present in the published compiler jar either, do I actually need it? Sorry if this is a lame quesion, I don't have a lot of experience with the closure compiler.

**Comment by moderndegree** [comment]
@dpashkevich, I think those docs are inaccurate. You should only need "--generate_exports" and "--export_local_property_definitions". As far as the release date, I have no idea. However, you should be able to compile your own jar until then.

**Comment by dpashkevich** [comment]
Ok, thanks for the clarification @moderndegree!
