### ISSUE TITLE
@ngInject fails when used in goog.scope

### ISSUE THREAD

**Issue by sinelaw** [google/closure-compiler#649]
```js
goog.scope(function() {

  /** @ngInject */
  function controller($scope) {
  }
});
```
gives:

    $ java -jar compiler.jar --angular_pass --js ~/googscope.js 
    /local-home/user18/googscope.js:4: ERROR - @ngInject only applies to functions defined in blocks or global scope.
            function controller($scope) {
            ^

    1 error(s), 0 warning(s)

**Comment by Dominator008** [comment]
As of 4db9c4e50c2a8ba41663e8c7a968b8ed42e4d78d, compiling the given code gives:
```js
var $jscomp={scope:{}};$jscomp.scope.controller=function(a){};$jscomp.scope.controller.$inject=["$scope"];
```
with no ERROR / WARNING, closing.
