### ISSUE TITLE
goog.format.InternationalizedEmailAddress.EAI_EMAIL_ADDRESS_ does not work after compilation

### ISSUE THREAD

**Issue by pstjvn** [google/closure-compiler#667]
So in source code everything is fine, but when I run in advanced compilation the resulting codes does not work:

```
Uncaught SyntaxError: Invalid regular expression: /^((?!\s)[+a-zA-Z0-9_.!#$%&'*\/=?^`{|}~Â€-ï¿¿FF-])+@((?!\s)[a-zA-Z0-9Â€-ã€ã€ƒ-ï¼ï¼-ï½ ï½¢-ï¿¿FF-]+[\.\uFF0E\u3002\uFF61])+(?!\s)[a-zA-Z0-9Â€-ã€ã€ƒ-ï¼ï¼-ï½ ï½¢-ï¿¿FF-]{2,63}$/: Range out of order in character class 
```
The code is compiled to the following:
```js
var $goog$format$InternationalizedEmailAddress$EAI_EMAIL_ADDRESS_$$ = RegExp("^((?!\\s)[+a-zA-Z0-9_.!#$%&'*\\/=?^`{|}~Â€-ï¿¿FF-])+@((?!\\s)[a-zA-Z0-9Â€-ã€ã€ƒ-ï¼ï¼-ï½ ï½¢-ï¿¿FF-]+[\\.\\uFF0E\\u3002\\uFF61])+(?!\\s)[a-zA-Z0-9Â€-ã€ã€ƒ-ï¼ï¼-ï½ ï½¢-ï¿¿FF-]{2,63}$");
```
I am not sure why this is broken, but it is.

**Comment by Dominator008** [comment]
@pstjvn Is this still happening? If so, can you provide a repro case?

**Comment by pstjvn** [comment]
Sorry, it was too long ago, also I submitted the bug informatively, back then it was critical to release asap so I have changed my code right away to use the simpler email address checks to avoid the issue and I already have no idea which code base was using this, so basically I cannot reproduce it. 

Maybe should be closed.
