### ISSUE TITLE
Opening project in NetBeans

### ISSUE THREAD

**Issue by Tom9729** [google/closure-compiler#682]
Netbeans gets confused trying to open this project because there are two pom files. Replacing `pom.xml` with `pom-main.xml` seems to fix this. Is there a reason that it is structured like this?

**Comment by lindner** [comment]
Pretty sure this is obsolete.  Can it be closed?

**Comment by Tom9729** [comment]
Thanks! I somehow lost track of this, sorry about that. Closing.
