### ISSUE TITLE
Pass as many tests as possible on @kangax's compat table

### ISSUE THREAD

**Issue by MatrixFrog** [google/closure-compiler#700]
http://kangax.github.io/compat-table/es6/ now has multiple tests for some features. We should make sure we pass as many of these as possible, and give clear failure messages for the rest.

**Comment by teppeis** [comment]
Now Closure supports 50% of ES6 table and I've created tracking issue for compat-table.
https://github.com/google/closure-compiler/issues/2899

I think we can close this issue. @concavelenz @MatrixFrog @blickly

**Comment by concavelenz** [comment]
Closing in favor of #2899
