### ISSUE TITLE
Promise chains are not correctly type-checked

### ISSUE THREAD

**Issue by benkwa** [google/closure-compiler#715]
The following (valid, afaict) code:
```javascript
Promise.resolve()
   .then(
       /** @return {!Promise<string>} */
       function() { return Promise.resolve('foo'); })
   .then(
       /** @param {string} s */
       function(s) { console.log(s); });
```

Produces errors:
> ERROR - actual parameter 1 of Promise.prototype.then does not match formal parameter
> found   : function (string): undefined
> required: (function (Promise\<string\>): ?|null|undefined)
>        function(s) { console.log(s); });
>        ^

The problem appears to be that the type-checker is not correctly unwrapping promised return values prior to type-checking them against the next callback in the chain.

**Comment by emspishak** [comment]
Is there any update on this? Or a recommended workaround?

**Comment by concavelenz** [comment]
I have a change to fix this using the TTL and am cleaning up some code in order to land it.  It should land later this week or next week unless something unexpected comes up.

**Comment by MatrixFrog** [comment]
https://github.com/google/closure-library/commit/ef8903451c009a5730d090e0dd7fee78523cc86d
