### ISSUE TITLE
Quoted methods being removed when compiling in advanced mode

### ISSUE THREAD

**Issue by alechewitt** [google/closure-compiler#722]
I am using closure with angular and I have come across an issue with methods on the prototype being removed even if they are in quotes when compiling in advanced mode.

With the below code in advanced mode I would expect the methods sayHello and sayGoodbye to be preserved as they are in quotes however they are completely removed.
```js
goog.provide('com.MyController');

/**
 * @export
 * @constructor
 */
com.MyController = function() {
   this.greeting = 'hello';
   this.goodbye = 'bye'
};

/**
* @export
*/
com.MyController.prototype = {

    'sayGoodbye': function() {
        return this.goodbye;
    },

    'sayHello': function() {
        return this.greeting;
    }
};
```

The output of this when using pretty print is the following:
```js
function a() {
}
goog.b("com.MyController", a);
a.prototype = {};
goog.a(a, "prototype", a.prototype);
```
The methods, sayGoodbye and sayHello are completely removed?

**Comment by Dominator008** [comment]
This seems to have been fixed.
