### ISSUE TITLE
Disallow types other than string as keys for Object

### ISSUE THREAD

**Issue by metaweta** [google/closure-compiler#727]
The introduction of the Symbol class in ES6 is to get around the restriction in ES3 and ES5 that all keys for objects get cast to strings.  The compiler should at least warn and preferably disallow anything but strings as keys to make that explicit, though number might be a reasonable exception.

`/** @type {Object<Object, string>} */ var myMap; // should fail to typecheck`

**Comment by nbeloglazov** [comment]
Similar check has been added to compile recently: https://github.com/google/closure-compiler/commit/78cd2730d4b201dc63d64c03683dddbb1d098c9e
It checks that types used as object keys are "stringifiable" meaning that their string representations are likely unique (like using numbers as keys makes sense as different numbers => different string representations). 
I think this bug can be closed?

**Comment by concavelenz** [comment]
yes.
