### ISSUE TITLE
Unknown types reported when transpiling ecmascript 6 class inheritance

### ISSUE THREAD

**Issue by kayahr** [google/closure-compiler#751]
I'm playing around with the ES6 to ES5 transpilation of classes and found a problem with the following simple code:

    class Base {
        constructor() {
        }
    }
    class Child extends Base {
        constructor() {
            super();
        }
    }

I compile the code with the following options:

    -W VERBOSE --jscomp_error reportUnknownTypes --language_in ECMASCRIPT6 --language_out ECMASCRIPT5

Closure compiler outputs the following warnings:

     [synthetic:2] :39: ERROR - could not determine the type of this expression
    $jscomp.IteratorResult.prototype.value;
    ^
    
     [synthetic:2] :163: ERROR - could not determine the type of this expression
        return parentCtor.prototype[methodName].apply(me, args);
               ^
    
    test.js:7: ERROR - could not determine the type of this expression
            super();
            ^

The first two warnings are not from my code, they seem to come from the complicated code the compiler automatically generated to perform the actual inheritance. The third warning looks like the compiler doesn't know the type of the super class constructor. My current workaround for this warning is using the ugly old way to call super constructors:

    Base.call(this);

By the way: The same problem exists when using the new type inference. But there are a lot more `[synthetic:2]` warnings then and the super constructor call yields a different warning, maybe it is useful to find the actual problem:

    test.js:7: WARNING - Property base never defined on function(new:Child):?
            super();
            ^

**Comment by MatrixFrog** [comment]
The issues with `super` should resolved by 3566f49ce24887662777a04ba87817c200b79b9c and there are just a couple errors in the runtime library. I'll keep this open to track those.
