### ISSUE TITLE
Allow unions of nominal-type|null in enums

### ISSUE THREAD

**Issue by nicks** [google/closure-compiler#755]
If I type,

```js
/** @constructor */
function F() {}

/** @enum {F} */ 
var G = {X: new F()}
```

I get the error message:

`Bad JSDoc annotation. An enum type cannot be a union type.`

which seems wrong, because I didn't type a union? It seems like it should just quietly assume this means non-null.

http://closure-compiler-debugger.appspot.com/#input0%3D%252F**%2520%2540constructor%2520*%252F%250Afunction%2520F()%2520%257B%257D%250A%250A%252F**%2520%2540enum%2520%257BF%257D%2520*%252F%2520%250Avar%2520G%2520%253D%2520%257BX%253A%2520new%2520F()%257D%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES%3D1%26CHECK_TYPES_NEW_INFERENCE%3D1%26MISSING_PROPERTIES%3D1

**Comment by dimvar** [comment]
Alternatively, enum declarations can automatically assume non-null, like extends declarations do.
