### ISSUE TITLE
Bogus 'incorrect jsdoc annotation' on function typedefs in new type inference

### ISSUE THREAD

**Issue by nicks** [google/closure-compiler#760]
New type inference rejects this pattern:

```js
/** @typedef {function()} */
var NoArgumentFunction;

/** @type {NoArgumentFunction} */
var f = function () {}
```

This is a useful pattern when you have a complicated function type that you need to pass around a lot. This is handled fine in old type inference.

http://closure-compiler-debugger.appspot.com/#input0%3D%252F**%2520%2540typedef%2520%257Bfunction()%257D%2520*%252F%250Avar%2520NoArgumentFunction%253B%250A%250A%252F**%2520%2540type%2520%257BNoArgumentFunction%257D%2520*%252F%250Avar%2520f%2520%253D%2520function%2520()%2520%257B%257D%250A%250A%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES%3D1%26CHECK_TYPES_NEW_INFERENCE%3D1%26MISSING_PROPERTIES%3D1

**Comment by dimvar** [comment]
Note to self: we should be allowing <code>@type</code> declarations where the initializer is a function to have a type that is a supertype of function, eg, a union that includes function.
