### ISSUE TITLE
The typechecker should know that a getelem on a Uint8Array is a number

### ISSUE THREAD

**Issue by MatrixFrog** [google/closure-compiler#766]
https://groups.google.com/d/topic/closure-compiler-discuss/x4nqNZcIIgg/discussion

If you have an `Array<number>` "arr" then the typechecker knows that `arr[0]` is a number. It should also know that for `Uint8Array`, `Int8Array`, etc.

```js
/** @type {Array<number>} */
var arr = [5];
var y = arr[0];
f(y);  // type mismatch

var typedArr = new Uint8Array([]);
var x = typedArr[0];
f(x);  // should be a type mismatch but there is no warning
```

https://closure-compiler-debugger.appspot.com/#input0%3D%252F**%2520%2540type%2520%257BArray%253Cnumber%253E%257D%2520*%252F%250Avar%2520arr%2520%253D%2520%255B5%255D%253B%250Avar%2520y%2520%253D%2520arr%255B0%255D%253B%250Af(y)%253B%2520%2520%252F%252F%2520type%2520mismatch%250A%250Avar%2520typedArr%2520%253D%2520new%2520Uint8Array(%255B%255D)%253B%250Avar%2520x%2520%253D%2520typedArr%255B0%255D%253B%250Af(x)%253B%2520%2520%252F%252F%2520should%2520be%2520a%2520type%2520mismatch%2520but%2520there%2520is%2520no%2520warning%250A%250A%26input1%26conformanceConfig%26externs%3Dfunction%2520f(%252F**%2520string%2520*%252F%2520x)%2520%257B%257D%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES%3D1%26MISSING_PROPERTIES%3D1

**Comment by dimvar** [comment]
I don't know if we'll handle typed arrays before handling ES6 in NTI. Marking as P3 for now.

**Comment by concavelenz** [comment]
I'm hope my intern will work on this.

**Comment by Dominator008** [comment]
This is now working in NTI.
