### ISSUE TITLE
Add an optional warning for types that are implicitly nullable

### ISSUE THREAD

**Issue by MatrixFrog** [google/closure-compiler#772]
Some people would like for their code to always use `{?Foo}` rather than just `{Foo}` for nullable types, because it's more explicit, and it makes it easier to switch everything to non-nullable by default in the future. We should have an optional warning for the latter form so that teams can ban it.

**Comment by eborden** [comment]
It looks like this hasn't been given access via jscomp_error={string}. Am I correct in this assumption?

**Comment by MatrixFrog** [comment]
It was added to the lintChecks a little later: https://github.com/google/closure-compiler/blob/master/src/com/google/javascript/jscomp/DefaultPassConfig.java#L1521

**Comment by eborden** [comment]
Great, thanks. In conjunction with this is it possible to have the inverse of @fileoverview suppression? This would make this feature much more helpful for existing code bases.

**Comment by tdkrzy** [comment]
Is there an accessible way to turn this off without disabling "lintChecks"?  I'm not sure whether or not I'm ready to switch to {?Foo} but I'd like to reap the benefits of all the other passes.

**Comment by MatrixFrog** [comment]
Not built-in, no, sorry. If you don't mind building the compiler yourself you can comment out the addition of the ImplicitNullabilityCheck pass in DefaultPassConfig.

**Comment by tdkrzy** [comment]
I thought that might be the case and just wanted to make sure I wasn't missing something.  I do see where I can comment it out fairly easy if I need to.  Thanks!
