### ISSUE TITLE
SIMPLE_OPTIMIZATIONS claim untrue/unclear

### ISSUE THREAD

**Issue by anywhichway** [google/closure-compiler#779]
The documentation for SIMPLE_OPTIMIZATIONS says this: "Compilation with SIMPLE_OPTIMIZATIONS always preserves the functionality of syntactically valid JavaScript, provided that the code does not access local variables using string names (by using eval() statements, for example)."

This is at best unclear and and worst untrue. It should perhaps say:  "Compilation with SIMPLE_OPTIMIZATIONS always preserves the functionality of syntactically valid JavaScript, provided that the code does not access local variables using string names (by using eval() statements, for example) or have semantics that depends on the names of functions themselves."

The documentation should probably be unpdated. Ideally, there would also be an additional compiler flag, PRESERVE_FUNCTION_NAMES, since compressing variable names would dramatically reduce code size. However, I am not a compiler expert, and since functions are ultimately just variables at a higher scope, a true compiler may not be possible to write, although a compressor could be.

The below example illustrates the above statement is at best unclear and at worst untrue.

1: Compiling this: 

`(function(exports) {
        function getFunctionName(f) {
		var str = f+"";
		var i = str.indexOf("function ");
		if(i===-1) {
			return null;
		}
		var j = i + "function ".length;
		var k = str.indexOf("(",j);
		if(k===-1) {
			return null;
		}
		return str.substring(j,k);
	}
        exports.getFunctionName = getFunctionName;
})("undefined"!=typeof exports&&"undefined"!=typeof global?global:window);`

2: Results in: 

`(function(d){d.getFunctionName=function(a){a+="";var b=a.indexOf("function ");if(-1===b)return null;var b=b+9,c=a.indexOf("(",b);return-1===c?null:a.substring(b,c)}})("undefined"!=typeof exports&&"undefined"!=typeof global?global:window);`

which has anonymized getFunctionname

3: So invoking: getFunctionname(getFunctionname)

results in null instead of "getFunctionName"

4. It may be argued that this is the way closures work and one should not expect to access the function name outside the closure. However, the below also fails to perform in accordance with the documentation:

This ...

`(function(exports) {
        function getFunctionName(f) {
		var str = f+"";
		var i = str.indexOf("function ");
		if(i===-1) {
			return null;
		}
		var j = i + "function ".length;
		var k = str.indexOf("(",j);
		if(k===-1) {
			return null;
		}
		return str.substring(j,k);
	}
        exports.getFunctionName = getFunctionName;
        console.log("Function name is:" + getFunctionName(getFunctionName));
})("undefined"!=typeof exports&&"undefined"!=typeof global?global:window);`

Compiles to: 

`(function(d){function a(b){b+="";var c=b.indexOf("function ");if(-1===c)return null;var c=c+9,a=b.indexOf("(",c);return-1===a?null:b.substring(c,a)}d.getFunctionName=a;console.log("Function name is:"+a(a))})("undefined"!=typeof exports&&"undefined"!=typeof global?global:window);`

which will print out "a"

**Comment by ChadKillingsworth** [comment]
You mean like what is listed under the [Restrictions for SIMPLE_OPTIMIZATIONS](https://developers.google.com/closure/compiler/docs/limitations) documentation?

**Comment by anywhichway** [comment]
Thanks for the quick response! So much documentation to read and remember these days!

And, my claim that it is at best unclear is true. The section on Compilation Levels (https://developers.google.com/closure/compiler/docs/compilation_levels?csw=1) could do with a tweak per my suggestion .. just 9 more words and then completely consistent with the further detail under restrictions on the SIMPLE_OPTIMIZATIONS buried two levels down in the doc.

Regardless, once again thank you.

**Comment by MatrixFrog** [comment]
Added a little more text there so it should be a bit clearer.
