### ISSUE TITLE
Allow function annotations on export nodes

### ISSUE THREAD

**Issue by MatrixFrog** [google/closure-compiler#781]
Currently this works, with no warning:

`/** @return {undefined} */ var f = function() {}`

but this gives a warning:

`/** @return {undefined} */ export var f = function() {}`

We should allow both without warnings.

**Comment by MatrixFrog** [comment]
Actually there are two issues. One is the warning, the other is that we are actually failing to attach the JSDoc, so the function won't be typechecked using the JSDoc that is there.

**Comment by concavelenz** [comment]
Yes, we should allow type declaration on exported declarations (of which this is one form).

**Comment by MatrixFrog** [comment]
In progress...
