### ISSUE TITLE
Missing whitespace before some identifiers when --formatting=PRETTY_PRINT

### ISSUE THREAD

**Issue by alexeagle** [google/closure-compiler#782]
alexeagle-macbookpro2:closure-compiler alexeagle$ cat bug1.js
var b = true;
var f = function() { return !b; }
alexeagle-macbookpro2:closure-compiler alexeagle$ java -jar build/compiler.jar --formatting=PRETTY_PRINT bug1.js
var b = !0, f = function() {
  return!b;
};

there is a missing space in "return !b"

Also this case:
alexeagle-macbookpro2:closure-compiler alexeagle$ cat bug2.js
var f = function() { return 'hello'; }
alexeagle-macbookpro2:closure-compiler alexeagle$ java -jar build/compiler.jar --formatting=SINGLE_QUOTES --formatting=PRETTY_PRINT bug2.js
var f = function() {
  return'hello';
};

there is a missing space in "return 'hello'"

**Comment by ChadKillingsworth** [comment]
Yes the code printer could do much better with human readable output. #131 has similar issues. Probably the only way this will be fixed though is by a patch submission.

**Comment by alexeagle** [comment]
Sent a pull request for it this afternoon. Thanks!

**Comment by alexeagle** [comment]
Fixed by https://github.com/google/closure-compiler/pull/790
