### ISSUE TITLE
addEventListener has wrong type

### ISSUE THREAD

**Issue by kvanberendonck** [google/closure-compiler#787]
Native addEventListener has wrong type (missing `|string` on return).

There is no way to add a well typed event listener using window.addEventListener if the event allows the user to return a string.

One such event that does this is onbeforeunload which lets you return a prompt message ...

Ticked carried over from closure-library#400

**Comment by ChadKillingsworth** [comment]
Cross link issue: google/closure-library#400

What benefit does strongly typing the return value of a listener provide? Why can't we simply annotate it such that it returns an unknown type?

```JavaScript
/**
 * @param {string} type
 * @param {EventListener|function(!Event):?} listener
 * @param {boolean} useCapture
 * @return {undefined}
 */
EventTarget.prototype.addEventListener =
    function(type, listener, useCapture) {};
    
/**
 * @param {string} type
 * @param {EventListener|function(!Event):?} listener
 * @param {boolean} useCapture
 * @return {undefined}
 */
EventTarget.prototype.removeEventListener =
    function(type, listener, useCapture) {};
```

**Comment by kvanberendonck** [comment]
Stops you from returning an object by accident (ie forgetting `.getText()`), I guess.

**Comment by Dominator008** [comment]
Technically the return type can be `?`, but I think it makes sense to restrict it to `(boolean|undefined)` or even just `undefined`. Returning anything other than `undefined` sounds like the code is relying on legacy behavior.

**Comment by kvanberendonck** [comment]
I'm sorry what do you expect the people to do who currently use closure compiler and rely on this?

**Comment by Dominator008** [comment]
@kvanberendonck You can either suppress the type check on the listener function:
```js
window.addEventListener("beforeunload",
  /** @suppress {checkTypes} */ function(e) {
  return "message";
}, false);
```
or cast the return value to `?` manually:
```js
window.addEventListener("beforeunload", function(e) {
  return /** @type {?} */ ("message");
}, false);
```

**Comment by kvanberendonck** [comment]
Another instance of this ...
```
  window.addEventListener('error',
    /** @suppress {checkTypes} */ (function (message, source, lineno, colno, error) {
    // do stuff
  }), false);
```

Throws error on type of handler function unless you suppress the type check.
`onerror` is living standard and definitely not legacy behaviour.

**Comment by ChadKillingsworth** [comment]
@kvanberendonck That's the wrong signature. That signature is only used for assigning to the `window.onerror` property:

```js
window.onerror = function (message, source, lineno, colno, error) {
  // do stuff
})
```

See the [global onerror](https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/onerror) handler vs the [ErrorEvent](https://developer.mozilla.org/en-US/docs/Web/API/ErrorEvent).

**Comment by kvanberendonck** [comment]
Yep my bad.
