### ISSUE TITLE
Broken links on https://github.com/google/closure-compiler/wiki/Externs-For-Common-Libraries

### ISSUE THREAD

**Issue by alexeagle** [google/closure-compiler#792]
For example, https://github.com/google/closure-compiler/tree/master/contrib/externs/angular.js

**Comment by MatrixFrog** [comment]
Looks like the right link is https://github.com/google/closure-compiler/blob/master/contrib/externs/angular-1.3.js (or s/1.3/1.2/ or whatever). The wiki should be editable by anyone.

**Comment by alexeagle** [comment]
Fixed.
