### ISSUE TITLE
Support trailing commas in typedefs

### ISSUE THREAD

**Issue by ewinslow** [google/closure-compiler#796]
Example input:

```js
/**
 * @typedef {{
 *  someProp: Foo,
 *  otherProp: Bar,
 * }}
 */
var TheTypeDef;
```

JS compiler currently gives a complaint like so:

```
the/file/path.js:11: WARNING - Bad type annotation. type not recognized due to syntax error
 * }}
   ^
```

Trailing commas are handy for being able to reorder the items listed easily. Plus, trailing commas are valid in JS, so it would seem natural to support them in this kind of context.

**Comment by MatrixFrog** [comment]
+1, I don't see a downside to this. We (optionally) warn about this for object/array literals, but since these are comments it should be fine.
