### ISSUE TITLE
Warn when something other than a string is used as an object key

### ISSUE THREAD

**Issue by MatrixFrog** [google/closure-compiler#797]
If you use something other than a string as an object key, it is converted to a string: http://jsfiddle.net/a7obbLdf/

Sometimes this is intentional, but in many cases (particularly if you're using an object that we know has no useful `toString` method) it's an error, so this would probably be good to warn about.

**Comment by concavelenz** [comment]
To be clear numbers are ok too.

**Comment by MatrixFrog** [comment]
I forgot we had a bug open for this. 78cd2730d4b201dc63d64c03683dddbb1d098c9e allows only "stringifiable" types, meaning strings and objects with a toString() method other than the default one that just returns "[object Object]"

You can use it with --jscomp_warning=lintChecks
