### ISSUE TITLE
Function generates invalid output when compiled with ADVANCED_OPTIMIZATIONS.

### ISSUE THREAD

**Issue by ILOVEPIE** [google/closure-compiler#807]
the following function which splits a string on the first occurrence of a string does not split the string at all when compiled with ADVANCED_OPTIMIZATIONS:

    //split once implementation
    String.prototype.splitOnce = function(separator) {
        var j = this.indexOf(separator);
        if (j == -1) return [this.trim()];
        return [this.slice(0, j), this.slice(j + 1).trim()];
    };

**Comment by MatrixFrog** [comment]
I tried this in closure-compiler.appspot.com and it seems to do the right thing:

    String.prototype.splitOnce = function(separator) {
      var j = this.indexOf(separator);
      if (j == -1) return [this.trim()];
      return [this.slice(0, j), this.slice(j + 1).trim()];
    };

    var s = 'foobar';
    alert(s.splitOnce('b'));

compiles to `alert(["foobar".slice(0,3),"foobar".slice(4).trim()]);`

Can you give a more complete example?

**Comment by ILOVEPIE** [comment]
sorry i misidentified the issue, i'm closing this issue and opening a new one with the correct problem
