### ISSUE TITLE
Closure compiler removes multiple consecutive spaces from inside regex expressions when using ADVANCED_OPTIMIZATIONS

### ISSUE THREAD

**Issue by ILOVEPIE** [google/closure-compiler#808]
the following code gets changed from having four spaces in the regex to having one when compiled with ADVANCED_OPTIMIZATIONS:

    alert("this is    borked ".replace(/    /g, " not "));

**Comment by nicks** [comment]
I just tried it, and I was not able to reproduce this issue. Here is the command I ran:

```sh
$ java -jar compiler.jar --version
Closure Compiler (http://github.com/google/closure-compiler)
Version: v20141215
Built on: 2014/12/17 09:05

$ echo 'alert("this is    borked ".replace(/    /g, " not "));' | java -jar compiler.jar -O=ADVANCED_OPTIMIZATIONS
alert("this is    borked ".replace(/    /g," not "));
```

are there additional repro steps? what version of the compiler are you using? Are you sure you don't have a script on top of closure-compiler that mangles the spacing?

**Comment by ILOVEPIE** [comment]
here's my version output:

    java -jar /home/pmartin/DevTools/Closure/compiler.jar --version
    Closure Compiler (http://github.com/google/closure-compiler)
    Version: v20141215
    Built on: 2014/12/17 09:05

actual code in my application that experiences this issue:

    _loadScript: {
        value: function(scriptname) {
            this._ifdepth = 0;
            var request = new XMLHttpRequest();
            request.open("GET", this._rootpath + "script" + window.PATH_SEPARATOR + scriptname, false);
            request.send(null);
            if (request.status == 200) {
                this._scriptReader["init"](request.responseText.replace(/    /g, "\t").replace(/\r/g, ""));
                this._currentScript = scriptname;
            }
            else if (this._scriptZip) {
                var file = this._scriptZip.file("script" + window.PATH_SEPARATOR + scriptname);
                if (file != null) {
                    this._scriptReader["init"](file["asText"]().replace(/    /g, "\t").replace(/\r/g, ""));
                    this._currentScript = scriptname;
                }
            }
        },
        writable: false
    },

command i'm using: 

    java -jar /home/username/DevTools/Closure/compiler.jar --compilation_level ADVANCED_OPTIMIZATIONS --js VNJSn.js --js_output_file VNJSn.min.js

result:

    M:{value:function(a){this.v=0;var c=new XMLHttpRequest;c.open("GET",this.e+"script"+window.g+a,!1);c.send(null);200==c.status?(this.j.init(c.responseText.replace(/ /g,"\t").replace(/\r/g,"")),this.J=a):this.$&&(c=this.$.file("script"+window.g+a),null!=c&&(this.j.init(c.asText().replace(/ /g, "\t").replace(/\r/g,"")),this.J=a))},writable:!1},

**Comment by nicks** [comment]
That code snippet does not compile by itself. When I wrapped it in something to make it compile, I was not able to reproduce the issue.

Again, can you provide exact repro steps?

**Comment by ILOVEPIE** [comment]
nevermind, i fixed it, there was an error with another program i was using, that ended up looking like closure was causing the issue.
