### ISSUE TITLE
create_source_map combined with the module flag creates only a single source map

### ISSUE THREAD

**Issue by metrofun** [google/closure-compiler#813]
Hi,

Currently `--create_source_maps` creates one source map file, even when using together with  `--module`. What is the most convenient way to create separate source maps for each compiled module?

**Comment by metrofun** [comment]
Well, looks like that's not a big deal to split the original file manually and add corresponding sourceMappingURLs :+1:

**Comment by ChadKillingsworth** [comment]
I actually think we should fix this one. Although it's probably going to be a lower priority.

**Comment by concavelenz** [comment]
This should be a very manageable fix if someone wants to contribute, the underlying wiring support this (as other command line runners for the compiler support this properly)

**Comment by ChadKillingsworth** [comment]
This was fixed. The `--create_source_map` flag must contain the string '%outname%' when output modules are used or the compiler warns.
