### ISSUE TITLE
ERROR - 'X' used but not goog.require'd

### ISSUE THREAD

**Issue by qudg74** [google/closure-compiler#814]
In the 20150126 release, I'm getting hundreds of errors like this:

ERROR - 'X' used but not goog.require'd

This happens if I have multiple files included with the '--js' option and function X is defined in one of them, but used in another. In my codebase this happens really often. I have many files without the goog dependency definitions. In all previous releases it worked, i.e. compiler did not require any goog dependency declarations.

I would still like to be able to include files that don't have goog dependency annotation and use functions from these files. For many external libraries it doesn't make sense that I should patch it myself and add goog annotations. I tried all 4 possible combinations of --manage_closure_dependencies true/false and --process_closure_primitives true/false, but in all 4 cases I still got the error.

My workaround for now is to use earlier compiler release.

I would call this new requirement (of having goog dependency annotations) a bug, as the compiler is no longer able to deal with sources which are not written with Closure compiler in mind.

**Comment by dimvar** [comment]
For now, you can use
--jscomp_off=missingRequire
to turn off the warning.

But yes, it's a bug to have this warning on by default in code that does not use the closure library.

**Comment by dimvar** [comment]
A clarification: are you using both Closure-style and non-Closure-style files in the same compilation, or are you only using non-Closure-style but get the warning anyway?

**Comment by qudg74** [comment]
Aha, it's missingRequire! Thanks for help. I always had in my compilation script:
--jscomp_error missingRequire
(together with all other --jscomp_error options I found in --help, kind of like -Wall, which I couldn't find).

So it's not the default compiler behavior that has changed. It's the behavior of missingRequire in the 20150126 release. But that's not a problem at all, so I'm closing this issue.

Regarding clarification, by closure-style one can mean 2 things: closure-compiler-style (with type annotations) and closure-library-style (with goog.* stuff). None of my files use any closure-library (goog.*) stuff. But most of them have closure-compiler-style (type annotations).
