### ISSUE TITLE
Advanced compilation of ES6 super.someMethod() is passing unobfuscated name "someMethod" to goog.base 

### ISSUE THREAD

**Issue by supersteves** [google/closure-compiler#815]
```
goog.module("my.namespace.MyClass");
var MySuperClass = goog.require("my.other.namespace.MySuperClass");
exports = class MyClass extends MySuperClass {
  constructor() {
  }
  /** @override */
  someMethod() {
    super.someMethod();
  }
}

```

The super call turns into:

```
Us.prototype.Kf=function(){Us.Er(this,"someMethod");}
```

and fails:
Uncaught TypeError: Cannot read property 'apply' of undefined

**Comment by MatrixFrog** [comment]
Hm, looks to be doing the right thing here: https://closure-compiler-debugger.appspot.com/#input0%3Dclass%2520MyClass%2520extends%2520MySuperClass%2520%257B%250A%2520%2520constructor()%2520%257B%250A%2520%2520%257D%250A%2520%2520%252F**%2520%2540override%2520*%252F%250A%2520%2520someMethod()%2520%257B%250A%2520%2520%2520%2520super.someMethod()%253B%250A%2520%2520%257D%250A%257D%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES%3D1%26LANG_IN_IS_ES6%3D1%26MISSING_PROPERTIES%3D1%26PRETTY_PRINT%3D1%26TRANSPILE%3D1

so maybe I need to try from the command line, with both files. It sounds like this is related to class transpilation, not goog.module handling, right?

**Comment by supersteves** [comment]
I'm using Closure Compiler from Java directly, and am using advanced compilation with full renaming of properties and so forth. This works fine except for the goog.base call which passes the method "someMethod" as a string, and it is forgetting to rename this value, presumably because it is now a literal string after transpiling?

**Comment by supersteves** [comment]
I tried the appspot page, how do I enable equivalent of CompilationLevel.ADVANCED_OPTIMIZATIONS and setLanguageIn(LanguageMode.ECMASCRIPT6_STRICT)

**Comment by supersteves** [comment]
Here it is with superclass and no warnings, but I don't know what I need to tick for advanced optimisations equivalent:

https://closure-compiler-debugger.appspot.com/#input0%3Dclass%2520MySuperClass%2520%257B%250A%2520%2520someMethod()%2520%257B%250A%2520%2520%2520%2520console.log(%2522super%2522)%253B%250A%2520%2520%257D%250A%257D%250Aclass%2520MyClass%2520extends%2520MySuperClass%2520%257B%250A%2520%2520constructor()%2520%257B%250A%2520%2520%257D%250A%2520%2520%252F**%2520%2540override%2520*%252F%250A%2520%2520someMethod()%2520%257B%250A%2520%2520%2520%2520super.someMethod()%253B%250A%2520%2520%257D%250A%257D%250Anew%2520MyClass().someMethod()%253B%250A%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES%3D1%26LANG_IN_IS_ES6%3D1%26MISSING_PROPERTIES%3D1%26PRETTY_PRINT%3D1%26TRANSPILE%3D1

**Comment by supersteves** [comment]
Ah, got it, here's the problem:
https://closure-compiler-debugger.appspot.com/#input0%3Dclass%2520MySuperClass%2520%257B%250A%2520%2520someMethod()%2520%257B%250A%2520%2520%2520%2520console.log(%2522super%2522)%253B%250A%2520%2520%257D%250A%257D%250Aclass%2520MyClass%2520extends%2520MySuperClass%2520%257B%250A%2520%2520constructor()%2520%257B%250A%2520%2520%257D%250A%2520%2520%252F**%2520%2540override%2520*%252F%250A%2520%2520someMethod()%2520%257B%250A%2520%2520%2520%2520super.someMethod()%253B%250A%2520%2520%257D%250A%257D%250Anew%2520MyClass().someMethod()%253B%250A%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES%3D1%26LANG_IN_IS_ES6%3D1%26MISSING_PROPERTIES%3D1%26PRETTY_PRINT%3D1%26PROPERTY_RENAMING%3D1%26TRANSPILE%3D1%26VARIABLE_RENAMING%3D1

**Comment by MatrixFrog** [comment]
Perfect, thanks. The handling for SuperClass.base is at https://github.com/google/closure-compiler/blob/master/src/com/google/javascript/jscomp/ProcessClosurePrimitives.java#L615 so we need to do something similar for ES6 classes.

**Comment by concavelenz** [comment]
If you are using goog.module, you want to enable closure processing anyway.

**Comment by supersteves** [comment]
"closure processing"? Is that an option in the appspot page? I'm not
familiar with this page; the link above was only the minimum options I
could tick to get the "someMethod" problem to arise. My experience is with
using a year-old version of Closure Compiler directly in Java, which (back
then) we customised heavily, configuring most options to maximise advanced
compilation.
​

**Comment by concavelenz** [comment]
The "closurePass" in the Java API.

**Comment by supersteves** [comment]
Thanks. We're using it implicitly, since we have ADVANCED_OPTIMIZATIONS. Additional options in full are:

dependency pruning+sorting, moocher dropping, a few entry points
cross module code+method motion
define replacements
various warning/error levels/checks
check suspicious+symbols+types
closure coding convention
extern exports=false
ES6strict IN
ES5strict OUT
sourcemaps v3

**Comment by MatrixFrog** [comment]
I have a fix in progress for this. We know the name of the superclass so rather than Subclass.base() we can just call the superclass method directly. The only time we _don't_ know the name of the super class is if you extend an arbitrary expression like `class X extends (foo()) {...` which we don't support anyway.
