### ISSUE TITLE
Constructing an ES6 class from a static method doesn't compile

### ISSUE THREAD

**Issue by supersteves** [google/closure-compiler#816]
Example (this works uncompiled in Canary):
```
goog.module("my.namespace.MyClass");
var MySuperClass = goog.require("my.other.namespace.MySuperClass");
exports = class MyClass extends MySuperClass {
  constructor() {
  }
  /** @override */
  someMethod() {
    super.someMethod();
  }
  static test() {
    new MyClass().someMethod();
  }
}
```
Error:
```
ERROR - variable MyClass is undeclared
```

**Comment by concavelenz** [comment]
How are you running the compiler?

I get a different error:

input0:3: ERROR - ES6-to-ES3 conversion of 'named class in an assignment' is not yet implemented.
exports = class MyClass extends MySuperClass {
          ^

Which makes sense.

http://closure-compiler-debugger.appspot.com/#input0%3Dgoog.module(%2522my.namespace.MyClass%2522)%253B%250Avar%2520MySuperClass%2520%253D%2520goog.require(%2522my.other.namespace.MySuperClass%2522)%253B%250Aexports%2520%253D%2520class%2520MyClass%2520extends%2520MySuperClass%2520%257B%250A%2520%2520constructor()%2520%257B%250A%2520%2520%257D%250A%2520%2520%252F**%2520%2540override%2520*%252F%250A%2520%2520someMethod()%2520%257B%250A%2520%2520%2520%2520super.someMethod()%253B%250A%2520%2520%257D%250A%2520%2520static%2520test()%2520%257B%250A%2520%2520%2520%2520new%2520MyClass().someMethod()%253B%250A%2520%2520%257D%250A%257D%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES%3D1%26CLOSURE_PASS%3D1%26LANG_IN_IS_ES6%3D1%26MISSING_PROPERTIES%3D1%26TRANSPILE%3D1

**Comment by supersteves** [comment]
John,

I got that error too, in the last release, until I updated to yesterday's
tip. There was a recent commit that fixed that.
​

**Comment by concavelenz** [comment]
Tyler was this something you were looking at?

**Comment by MatrixFrog** [comment]
No, but I'll look into it. I believe this will work correctly now if you use ES6 modules instead of goog.module (after f95081afa7e9a706e653b12f1943a6d0c5b7af67)

And of course this should also work:

    class MyClass {...}
    exports = MyClass;

**Comment by supersteves** [comment]
Are ES6 modules now fair game?  John's post here suggested otherwise, but that was a couple of weeks ago.
https://groups.google.com/d/msg/closure-compiler-discuss/Lh890LsQ8FY/F4MP70aQDYMJ
Let me know if it's a good time to delve back into testing this.

**Comment by MatrixFrog** [comment]
We currently convert ES6 modules to goog.require/goog.provides so if you're not using the Closure library it may not work well. And there are probably still some bugs here and there. So please do consider ES6 modules to be experimental, but let us know if you are playing around with them and you find any bugs.

**Comment by supersteves** [comment]
Thanks. I am using Closure Library. I'll try it.  In my group post, I asked the ES6 equivalent of this classic code:
```
goog.provide("my.namespace.MyClass");

goog.require("my.other.namespace.MySuperClass");

/**
 * @constructor
 * @extends {my.other.namespace.MySuperClass}
 */
my.namespace.MyClass = function () {
    my.other.namespace.MySuperClass.call(this);
};
goog.inherits(my.namespace.MyClass, my.other.namespace.MySuperClass);
```
John suggested trying this, which worked well:
```
goog.module("my.namespace.MyClass");

var MySuperClass = goog.require("my.other.namespace.MySuperClass");

exports = class MyClass extends MySuperClass {
  constructor() {
  }
}
```
How should this be changed to use ES6 modules in a form supported by Closure Compiler, and what additional options do I need to enable (rewriteEs6modules, for example)?

**Comment by MatrixFrog** [comment]
Yes, rewriteEs6Modules needs to be on, and I think this should work:

    var MySuperClass = goog.require("my.other.namespace.MySuperClass");

    export class MyClass extends MySuperClass {
      constructor() {
      }
    }

which makes `MyClass` available by name so you can do `import {MyClass} from 'mymodule';` Or:

    var MySuperClass = goog.require("my.other.namespace.MySuperClass");

    export default class MyClass extends MySuperClass {
      constructor() {
      }
    }

which makes it the default export, and then you can do `import MyClass from 'mymodule';`

**Comment by MatrixFrog** [comment]
It looks like this is fixed at head now. We must have tweaked the class transpilation slightly in the last few weeks.
