### ISSUE TITLE
NTI does not specialize the type of THIS to be non-nullable after an IF test

### ISSUE THREAD

**Issue by myphysicslab** [google/closure-compiler#830]
When using new type inference compile option --new_type_inf, I'm getting lots of warnings `Attempt to use nullable type FooBarType|null` in spite of having code that checks the object is non-null.

Here is one example of many:

```javascript
// in constructor...
  /**
  * @type {myphysicslab.lab.app.EventHandler}
  * @private
  */
  this.eventHandler_ = eventHandler || null;

// later on...
    var evtHdlr = 'null';
    if (goog.isDefAndNotNull(this.eventHandler_)) {
      evtHdlr = this.eventHandler_.toStringShort();
    }
```

The error is then
```
src/lab/app/SimController.js:308: WARNING - Attempt to use nullable type myphysicslab.lab.app.EventHandler|null.
      evtHdlr = this.eventHandler_.toStringShort();
                ^
```

I've tried using goog.Null().  With old type inference it is possible to use simple tests like `if (foo !=null)`.

**Comment by myphysicslab** [comment]
I've found a workaround is to assign the property to a local variable.  Rewriting the above example would be something like this:

```javascript
var eh = this.eventHandler_;
var evtHdlr = 'null';
if (eh != null) {
  evtHdlr = eh.toStringShort();
}
```

This compiles cleanly with new type inference.

**Comment by dimvar** [comment]
For some reason, this bug happens only when the receiver is this, not when it is some other variable name.

    /** @constructor */
    function Foo() {
      this.a = 123;
    }
    
    /** @constructor */
    function Bar(x) {
      /** @type {Foo} */
      this.b = x;
      if (this.b != null) {
        return this.b.a; // incorrect warning here
      }
    }
    
    function f(/** !Bar */ obj) {
      if (obj.b != null) {
        return obj.b.a; // no warning here
      }
    }

**Comment by myphysicslab** [comment]
Confirmed that this has been fixed in Version: v20150505-58-g39bb337
