### ISSUE TITLE
using closure-compiler debugger with es6

### ISSUE THREAD

**Issue by nicks** [google/closure-compiler#835]
is there a way to try out es6 support on the clousre-compiler-debugger? I just tried it and I got the error message:

com.google.javascript.jscomp.CompilerOptionsPreprocessor$InvalidOptionsException: ES6 is only supported for transpilation to a lower ECMAScript version. Set --language_out to ES3, ES5, or ES5_strict.

but I don't know how to set language_out on the debugger :\

http://closure-compiler-debugger.appspot.com/#input0%3Dclass%2520X%2520%257B%257D%26input1%26conformanceConfig%26externs%26refasterjs-template%26CHECK_SYMBOLS%3D1%26CHECK_TYPES%3D1%26LANG_IN_IS_ES6%3D1%26MISSING_PROPERTIES%3D1

**Comment by blickly** [comment]
The error message is not good, but you want to set the TRANSPILE option:
http://closure-compiler-debugger.appspot.com/#input0%3Dclass%2520X%2520%257B%257D%26input1%26conformanceConfig%26externs%26refasterjs-template%26CHECK_SYMBOLS%3D1%26CHECK_TYPES%3D1%26LANG_IN_IS_ES6%3D1%26MISSING_PROPERTIES%3D1%26TRANSPILE%3D1

**Comment by nicks** [comment]
ah, that works. ok.
