### ISSUE TITLE
nullable type in externs file in HTMLSelectElement

### ISSUE THREAD

**Issue by myphysicslab** [google/closure-compiler#840]
With new type inference, I get errors like this one when using an `HTMLSelectElement`:

```
src/lab/controls/ParameterChoice.js:241: WARNING - Attempt to use nullable type HTMLOptionsCollection|null.
  this.selectMenu_.options.length = 0;
  ^
```

where `selectMenu_` is defined like this:

```javascript
  /**
  * @type {!HTMLSelectElement}
  * @private
  */
  this.selectMenu_ =
      /** @type {!HTMLSelectElement} */(document.createElement('select'));
  this.selectMenu_.type = 'select-one';
```

I don't see anything in the www.w3.org documentation stating that options can be null.  Should the extern file `w3c_dom2.js` be changed so that options is a non-nullable type?

```javascript
/**
 * @type {HTMLOptionsCollection}
 * @see http://www.w3.org/TR/2000/CR-DOM-Level-2-20000510/html.html#ID-30606413
 */
HTMLSelectElement.prototype.options;
```

Or do I need to test for null whenever using options?

**Comment by ChadKillingsworth** [comment]
```JavaScript
var a = document.createElement('select');
a.options.length === 0; //not null
```

I think it can be safely marked as non-null. Would you like to create a pull request for this?

**Comment by myphysicslab** [comment]
The pull request https://github.com/myphysicslab/closure-compiler/pull/1 has fixed this.
