### ISSUE TITLE
lint warning if missing @return

### ISSUE THREAD

**Issue by nanaze** [google/closure-compiler#844]
https://github.com/google/closure-linter/blob/master/closure_linter/errors.py#L84

**Comment by nanaze** [comment]
We would like this to be an error, perhaps behind a flag like --lint_pass, so we needn't rely on the linter for this

**Comment by concavelenz** [comment]
Is this "missing @return" when there is a "return" present in the method body?

**Comment by nanaze** [comment]
I think so, though an empty return doesn't need @return
