### ISSUE TITLE
Error if opt_foo is not marked as "=" in type.

### ISSUE THREAD

**Issue by nanaze** [google/closure-compiler#845]
Same as linter error  E:0232: Optional parameter opt_staticNamesCallback type must end with =.

**Comment by concavelenz** [comment]
With the Google coding convention enabled

**Comment by MatrixFrog** [comment]
This is for when the param name has `opt_` but the type is lacking the `=`. Do we also want to warn in the opposite case, when the type has the `=` but the name _doesn't_ start with `_opt`?

**Comment by dimvar** [comment]
We shouldn't warn in the opposite case. The opt_ prefix was introduced as a convention for optional parameters before type checking in the compiler. Now many people use optional parameters and annotate it in the type, without using the opt_ prefix.

**Comment by MatrixFrog** [comment]
Actually the style guide currently says:

> Optional function arguments start with `opt_`.

though you're probably right that this rule predates the `=` syntax. In any case, I'll go ahead and implement it just to match gjslint and the style guide, for now, and then we can remove it if someone wants to get the style guide changed.

https://google-styleguide.googlecode.com/svn/trunk/javascriptguide.xml?showone=Naming#Naming

**Comment by nanaze** [comment]
All information regarding a type should be in the type signature. The prefix is just a style question.

As far as Google style goes, if the type contains "=", then the parameter name should be prefixed with "opt_". If a parameter name starts with "opt_", the type should contain "=". gjslint philosophy is that the style guide should be the arbiter of behavior.
