### ISSUE TITLE
Add --lint_pass flag that will refuse to compile a binary with lint errors

### ISSUE THREAD

**Issue by nanaze** [google/closure-compiler#849]
suggestion

**Comment by concavelenz** [comment]
Is it that you want the command-line to generate an error code when so it is possible to detect lint warnings?  Or do you want lint warnings only or what is the goal/use case here?

**Comment by nanaze** [comment]
we (GWS) are using #lintfix to keep track of a hotlist of bugs we're blocked on for moving to clang-format

**Comment by nanaze** [comment]
(so if you change the titles, please put the hashtag in the body)

**Comment by nanaze** [comment]
@concavelenz 

Publicly state-able context: GWS team wants to abandon gjslint in favor of clang-format. We're trying to establish a minimum set of functionality that gjslint provided that we need elsewhere before we're willing to cut off gjslint and move to clang-format.

Internal links for context:
https://b/18332378
https://18799715

**Comment by concavelenz** [comment]
I'm trying to understand what we need other than --jscomp_error=lintChecks

**Comment by nanaze** [comment]
That seems like a better option than a standalone flag.

**Comment by nanaze** [comment]
Looks like that already exists in DiagnosticGroups.java. Marking as closed.
