### ISSUE TITLE
Add support for 'new.target'

### ISSUE THREAD

**Issue by concavelenz** [google/closure-compiler#854]
I'm not sure what a polyfill would look like, but we need to at least parse it.

http://closure-compiler-debugger.appspot.com/#input0%3Dclass%2520foo%2520%257B%250A%2520%2520constructor()%2520%257B%250A%2520%2520%2520%2520if%2520(new.target)%2520%257B%2520%250A%2520%2520%2520%2520%2520%2520this.foo%2520%253D%25201%2520%250A%2520%2520%2520%2520%257D%250A%2520%2520%257D%250A%257D%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES%3D1%26LANG_IN_IS_ES6%3D1%26MISSING_PROPERTIES%3D1%26TRANSPILE%3D1

https://people.mozilla.org/~jorendorff/es6-draft.html#sec-arrow-function-definitions-runtime-semantics-evaluation
https://people.mozilla.org/~jorendorff/es6-draft.html#sec-built-in-function-objects

**Comment by MatrixFrog** [comment]
ctrl-F for `new.target` in the spec doesn't find anything particularly readable. http://www.2ality.com/2015/02/es6-classes-final.html has a much clearer explanation.

**Comment by brad4d** [comment]
I'm inclined to make new.target a token. Does that seem reasonable?

**Comment by MatrixFrog** [comment]
Is `new   .    target` syntactically valid? If so it might be easier if the `new` and the `.` and the `target` are all separate tokens.

**Comment by dimvar** [comment]
Tyler, are you proposing that we make it a getprop? AFAICT, we'll never treat new.target as a property access, it is its own separate thing, it just happens to have a dot in its name. But it should probably be a separate token.

**Comment by MatrixFrog** [comment]
No, I was just talking about how we'd tokenize it in https://github.com/google/closure-compiler/blob/master/src/com/google/javascript/jscomp/parsing/parser/Scanner.java -- I forgot we'd overloaded the word `Token`. Once we're done parsing, `Token.NEW_TARGET` probably makes sense.

**Comment by dimvar** [comment]
OK, cool, we're on the same page then.

**Comment by brad4d** [comment]
I was thinking in terms of a lexer token, but upon reflection and looking
at the spec, I won't do that.
Creating a Node with type = Token.NEW_TARGET makes sense, though.
