### ISSUE TITLE
goog.array.find bad type checking

### ISSUE THREAD

**Issue by myphysicslab** [google/closure-compiler#855]
This might be related to issue #837.  I'm getting several similar errors when using functions like goog.array.forEachRight, goog.array.find, goog.array.findIndex, goog.array.sort.  Here is one case:

```
src/lab/engine2D/Polygon.js:1083: WARNING - Could not instantiate type 
function(T,number,?):boolean|null with function(?=):boolean.
  var edge = goog.array.find(this.edges, function(e) {
                                         ^
```

The error occurs in this method:

```javascript
/** @inheritDoc */
Polygon.prototype.probablyPointInside = function(p_body) {
  // look for an edge with positive distance to the point,
  // which means the point is outside the body.
  var edge = goog.array.find(this.edges, function(e) {
      return e.distanceToLine(p_body) > 0;
    }
  );
  return edge == null;
};
```

Here is the definition for the field `this.edges`

```javascript
/** Creates a new {Polygon}, with no edges or vertices.
* @param {string} name
* @constructor
* @implements {myphysicslab.lab.model.PhysicsObject}
* @implements {myphysicslab.lab.engine2D.RigidBody}
* @extends {myphysicslab.lab.model.AbstractSimObject}
*/
myphysicslab.lab.engine2D.Polygon = function(name) {
  myphysicslab.lab.model.AbstractSimObject.call(this, name);

  /**
  * @type {!Array.<!myphysicslab.lab.engine2D.Edge>}
  */
  this.edges = new Array();
```

The `probablyPointInside` method is defined in the RigidBody interface:

```javascript
/** Returns true if the given body coords point is probably inside this polygon.

WARNING:  For debugging only.  Does not work for complex (non-convex) shapes.
@param {!myphysicslab.lab.util.Vector} p_body the point in body coords
@return {boolean} true if the given body coords point is probably inside this polygon
*/
RigidBody.prototype.probablyPointInside;
```

Additional Info
-------------------

Adding a type hint in the function doesn't help; here is the error

```
src/lab/engine2D/Polygon.js:1083: WARNING - Could not instantiate type 
function(T,number,?):boolean|null with function(myphysicslab.lab.engine2D.Edge):boolean.
  var edge = goog.array.find(this.edges, function(/** !myphysicslab.lab.engine2D.Edge */e) {
                                         ^
```

when adding the type hint like this:
```javascript
/** @inheritDoc */
Polygon.prototype.probablyPointInside = function(p_body) {
  // look for an edge with positive distance to the point,
  // which means the point is outside the body.
  var edge = goog.array.find(this.edges, function(/** !myphysicslab.lab.engine2D.Edge */e) {
      return e.distanceToLine(p_body) > 0;
    }
  );
  return edge == null;
};
```

For reference, here is the definition of `goog.array.find`

```javascript
/**
 * Search an array for the first element that satisfies a given condition and
 * return that element.
 * @param {Array<T>|goog.array.ArrayLike} arr Array or array
 *     like object over which to iterate.
 * @param {?function(this:S, T, number, ?) : boolean} f The function to call
 *     for every element. This function takes 3 arguments (the element, the
 *     index and the array) and should return a boolean.
 * @param {S=} opt_obj An optional "this" context for the function.
 * @return {T|null} The first array element that passes the test, or null if no
 *     element is found.
 * @template T,S
 */
goog.array.find = function(arr, f, opt_obj) {
  var i = goog.array.findIndex(arr, f, opt_obj);
  return i < 0 ? null : goog.isString(arr) ? arr.charAt(i) : arr[i];
};
```

```
Closure Compiler (http://github.com/google/closure-compiler)
Version: v20150126-82-g85da5b6
Built on: 2015/02/25 09:03
```

**Comment by myphysicslab** [comment]
In case it's helpful, here is a simpler example of this error:
```
src/lab/util/UtilityCore.js:262: WARNING - Could not instantiate type Array<T>|null with Array<?>.
  goog.array.sort(s);
                  ^
```
Happens on this function:
```
/** Returns list of names of methods (functions) defined on the given object.
* @param {!Object} obj object to examine
* @return {!Array.<string>} list of names of functions defined on the given object
* @static
*/
UtilityCore.methodsOf = function(obj) {
  var s = new Array(0);
  for (var p in obj) {
    if (goog.isFunction(obj[p])) {
      s.push(p);
    }
  }
  goog.array.sort(s);
  return s;
};
```

**Comment by dimvar** [comment]
Should be fixed here: https://github.com/google/closure-compiler/commit/2abe542b6179ba3e20dd9b274f7d434fe67c67be

**Comment by myphysicslab** [comment]
Still have same problem with latest compiler.

```
src/lab/engine2D/Polygon.js:1261: WARNING - Could not instantiate type 
function(T,number,?):boolean|null with function(?=):boolean.
  var edge = goog.array.find(this.edges_, function(e) {
                                          ^
```

However, the `UtilityCore.methodsOf` example is no longer getting that warning, so that one is fixed.

Closure Compiler (http://github.com/google/closure-compiler)
Version: v20150505-58-g39bb337
Built on: 2015/05/21 12:45

Re-open this issue?  File a new issue?  Do you need a test case?

**Comment by dimvar** [comment]
It seems that goog.array.find expects a function with 3 arguments, and you're passing it a function of 1 argument.

https://github.com/google/closure-library/blob/master/closure/goog/array/array.js#L512

**Comment by myphysicslab** [comment]
Here is what I get when passing a function with 3 arguments:

```javascript
/** Returns true if the given body coords point is probably inside this polygon.
@package
@param {!myphysicslab.lab.util.Vector} p_body the point in body coords
@return {boolean} true if the given body coords point is probably inside this polygon
*/
Polygon.prototype.probablyPointInside = function(p_body) {
  var edge = goog.array.find(this.edges_,
    function(e, index, arr) {
      return e.distanceToLine(p_body) > 0;
    }
  );
  return edge == null;
};
```
results in this warning
```
src/lab/engine2D/Polygon.js:1260: WARNING - Cannot access property distanceToLine of 
non-object type T.
      return e.distanceToLine(p_body) > 0;
             ^
```
Here is the relevant part of the constructor
```javascript
* @param {string} name
* @constructor
* @struct
* @implements {myphysicslab.lab.engine2D.RigidBody}
* @extends {myphysicslab.lab.model.AbstractSimObject}
*/
myphysicslab.lab.engine2D.Polygon = function(name) {
  myphysicslab.lab.model.AbstractSimObject.call(this, name);

  /** list of {Edge}s in this {Polygon}
  * @type {!Array.<!myphysicslab.lab.engine2D.Edge>}
  * @private
  */
  this.edges_ = new Array();
  // code omitted...
};
```

**Comment by myphysicslab** [comment]
Here is another example of `goog.array.find` not figuring out the type of the array:

```
src/lab/engine2D/RigidBodySim.js:827: WARNING - The right side in the assignment is not
a subtype of the left side.
left side  : myphysicslab.lab.engine2D.Polygon|null
right side : T|null

    bod = goog.array.find(this.bods_,
    ^
```

Happens in this method:

```javascript
/**
* throws exception if requesting a non-existing body.
* @param {number|string} numOrName
* @return {!myphysicslab.lab.engine2D.Polygon}
*/
RigidBodySim.prototype.getBody = function(numOrName) {
  /** @type {myphysicslab.lab.engine2D.Polygon} */
  var bod = null;
  if (goog.isString(numOrName)) {
    var name = numOrName;
    bod = goog.array.find(this.bods_,
      function(body, index, array) {
        return body.getName() == name;
      });
  } else {
    var bodNum = numOrName;
    if (bodNum < this.bods_.length && bodNum >= 0) {
      bod = this.bods_[bodNum];
    }
  }
  if (bod == null)
    throw new Error("no body "+numOrName);
  return bod;
};
```

Here is the definition of `this.bods_`

```javascript
/**
* @param {!myphysicslab.lab.model.SimList=} simList_opt
* @constructor
* @struct
* @extends {myphysicslab.lab.util.ConcreteSubject}
* @implements {myphysicslab.lab.model.EnergySystem}
* @implements {myphysicslab.lab.model.ODESim}
* @implements {myphysicslab.lab.model.CollisionSim}
* @implements {myphysicslab.lab.engine2D.DebugEngine2D}
*/
myphysicslab.lab.engine2D.RigidBodySim = function(simList_opt) {
  ConcreteSubject.call(this);
  /**
  * @type {!Array.<!myphysicslab.lab.engine2D.Polygon>}
  * @protected
  */
  this.bods_ = new Array(0);
  // code omitted...
};
```

**Comment by dimvar** [comment]
There is definitely sth weird here. We get a wrong warning for this code.

WARNING - Illegal instantiation for type variable T. You can only specify one type. Found [number, T].

    /**
     * @param {!Array<T>} arr
     * @param {?function(this:S, T, number, ?) : boolean} f
     * @param {S=} opt_obj
     * @return {T|null}
     * @template T,S
     */
    function gaf(arr, f, opt_obj) {
      return null;
    };
    
    /** @type {number|null} */
    var x = gaf([1, 2, 3], function(x, y, z) { return true; });

**Comment by myphysicslab** [comment]
Confirmed fixed in Version: v20150505-104-g0a435e9.  Now I pretty much only have "dangerous use of the global this object" warnings on my code!  See issue #834.

**Comment by dimvar** [comment]
> Now I pretty much only have "dangerous use of the global this object" warnings on my code!

Out of curiosity, did NTI find some real bugs that weren't found by OTI? Or were the new warnings false positives?

**Comment by myphysicslab** [comment]
NTI definitely found some bugs that OTI missed.  Here's what I can recall from my notes: there were some interfaces with multiple @extends statements, which I think NTI caught.  NTI caught some missing braces around types.  I was doing some non-kosher things like assigning prototype methods from another class.  Add type casts where needed.  I'm pretty sure there was at least one surprising and serious bug that NTI caught, but I can't find it in my notes.

The problem that started me using NTI was issue #826, and NTI is better at analyzing interfaces which I use heavily, so that is a great benefit.  

The "attempt to use nullable type" error was annoying and daunting, but ultimately very helpful.  In several classes it made me see the class was doing too much.  Here is a typical note from a log:
>Previously, these were combined in a single class, and there
    was a lot of switching code to decide which of the two cases was valid,
    and it was confusing and hard to read. Separating them makes it a lot
    easier to read, and therefore more likely to be correct.

Here is another:
>SimController was doing too much, it was spaghetti code with
    many class variables (fields) that could were used in some cases and not
    others, and lots of conditional code for the various cases. It is now
    much easier to read and understand.

One thing that NTI seems to make more difficult is when a function has parameters that can be multiple types, like {Foo | Bar | number}.  I often decided to simplify the function to have fewer options, which made the code cleaner and easier to read.  It's still possible to use multiple type arguments and I still have some functions that do this, but NTI complains more about the fast-and-loose Javascript style of mixing types if you don't carefully test the types. Here's a surviving example:
```javascript
/** Returns a copy of this rectangle translated by the given amount.
@param {!(number|myphysicslab.lab.util.Vector)} x horizontal amount to translate by,
    or {Vector} to translate by
@param {number=} y vertical amount to translate by; required when `x` is a number.
@return {!myphysicslab.lab.util.DoubleRect} a copy of this rectangle translated by the
    given amount
@throws {Error} when `x` is a number and `y` is not defined
*/
DoubleRect.prototype.translate = function(x, y) {
  if (x instanceof Vector) {
    y = x.getY();
    x = x.getX();
  }
  if (!goog.isDef(y))
    throw new Error();
  return new DoubleRect(this.left_ + x, this.bottom_ + y,
      this.right_ + x, this.top_ + y);
};
```
BTW, closure library uses that "multiple types of argument" style a lot.  This will make it more challenging to get closure library working with NTI.

**Comment by dimvar** [comment]
What is the issue with translate in NTI? Is NTI producing wrong warnings?

**Comment by myphysicslab** [comment]
Sorry I wasn't clear.  That `translate` function is an example where I decided to retain the arguments having multiple types, I just wanted to give an example of what I was talking about.  What I was trying to say is that NTI "encouraged" me to use "multiple type options for arguments" less often because in code that had those

1. there were several valid type errors that NTI was pointing out
2. fixing those errors would mean adding more type checking and casting and if/then branches
3. so I often decided the code would be better with fewer (or no) argument type options

BTW, that's a similar process to dealing with the numerous "attempt to use nullable type" errors as well:  fixing the numerous errors would sometimes mean adding so much more code that it was easier and cleaner to refactor.  For example, split a long method into multiple methods, or new classes.

For "attempt to use nullable type" it was usually a matter of just adding a ! before the type and ensuring there was an object immediately defined, and fixing calling code or using code.  But in some cases it helped push me to refactor in ways that I think were quite helpful -- the new code is much better organized.

**Comment by dimvar** [comment]
oh ok, that's great then.
