### ISSUE TITLE
Case-sensitive "Bad type annotation" for functions

### ISSUE THREAD

**Issue by YetiCGN** [google/closure-compiler#864]
When I set `--jscomp_error checkTypes` the Closure Compiler complains about a return type in the Sizzle library that I am including:

    build\my-library.js:2980: ERROR - Bad type annotation. expected closing }
     * @returns {Function(string, Object)} Returns the Object data after storing it on itself with

If I simply change the `Function` type to `function`, the error disappears. I think this check should be case-insensitive as it is with (all / most?) other types.

**Comment by nicks** [comment]
this is correct behavior. In JavaScript, `function` is a keyword for a function literal, and `Function` is the name of the function constructor. See:
http://closuretools.blogspot.com/2012/02/type-checking-tips.html

**Comment by nicks** [comment]
also, type-checking has never been case-insensitive. Do you know where you got that impression?

**Comment by dimvar** [comment]
All types are case sensitive. If you are thinking about number vs Number, they are different types. The first one represents the primitive numbers and the second one the boxed numbers.

**Comment by YetiCGN** [comment]
Ah yes, that's probably where I got misled.
