### ISSUE TITLE
Browserify + empty functions are not removed

### ISSUE THREAD

**Issue by tleunen** [google/closure-compiler#872]
I'm using Closure Compiler with a Browserify build, and I noticed the empty functions are not removed from the final build.

For example with this initial browserify generated code:

``` js
(function e(t,n,r){function s(o,u){if(!n[o]){if(!t[o]){var a=typeof require=="function"&&require;if(!u&&a)return a(o,!0);if(i)return i(o,!0);var f=new Error("Cannot find module '"+o+"'");throw f.code="MODULE_NOT_FOUND",f}var l=n[o]={exports:{}};t[o][0].call(l.exports,function(e){var n=t[o][1][e];return s(n?n:e)},l,l.exports,e,t,n,r)}return n[o].exports}var i=typeof require=="function"&&require;for(var o=0;o<r.length;o++)s(r[o]);return s})({
10:[function(require,module,exports){
var l = require(289);
l.debug('Allo!')
},{}],
289:[function(require,module,exports){
module.exports = {
    debug: function() {}
};
},{}]},{},[10])
```

And here is the output from the compiler:

``` js
(function l(d,e,f){function g(b,c){if(!e[b]){if(!d[b]){var a="function"==typeof require&&require;if(!c&&a)return a(b,!0);if(h)return h(b,!0);a=Error("Cannot find module '"+b+"'");throw a.code="MODULE_NOT_FOUND",a;}a=e[b]={a:{}};d[b][0].call(a.a,function(a){var c=d[b][1][a];return g(c?c:a)},a,a.a,l,d,e,f)}return e[b].a}for(var h="function"==typeof require&&require,c=0;c<f.length;c++)g(f[c]);return g})({
10:[function(k){k(289).debug("Allo!")},{}],
289:[function(k,d){d.a={debug:function(){}}},{}]},{},
[10]);
```

As you can see, the debug function is still there, even if its content is empty.

`k(289).debug("Allo!")` should know `debug` has an empty body and because of that, it should be removed.

**Comment by dhai** [comment]
Did you specify ADVANCED_OPTIMIZATIONS?

**Comment by tleunen** [comment]
Yes. I used the [Closure Compiler Service](http://closure-compiler.appspot.com/home) for the test, but it's the same thing with the executable.

**Comment by concavelenz** [comment]
I think this will help a bit:

https://github.com/google/closure-compiler/wiki/Understanding-Property-Removal

While it is talking about property removal the same basic rules apply to property inlining, etc.  The compiler would need to "unwind" the browserify bundling.

Why do you need browserify, could you instead use the complier CommonJs/AMD support?

**Comment by tleunen** [comment]
I'm using browserify because it's the way I used to build the project, with plugins and transformations.
I'm not sure I could use the commonjs option in closure compiler to do the same thing
