### ISSUE TITLE
jQuery externs for event handlers are too loose

### ISSUE THREAD

**Issue by eevee** [google/closure-compiler#876]
For example, `$.on` is annotated as follows:

```
/**
 * @param {(string|Object.<string,*>)} arg1
 * @param {*=} selector
 * @param {*=} data
 * @param {function(!jQuery.event=)=} handler
 * @return {!jQuery}
 */
jQuery.prototype.on = function(arg1, selector, data, handler) {};
```

The event handler is defined as taking an argument of type `!jQuery.event=`, or `jQuery.event|undefined`.  But I can't think of any circumstance in which jQuery _wouldn't_ pass an event object to an event handler...  so why is the `=` there?

I'm trying to upgrade Closure Compiler with an existing annotated codebase, and this is causing a slew of problems in code like:

```
/**
 * @param {jQuery.event} e
 **/
function quux(e) { ... }

$(...).on('.foo', '.bar', {}, function(e) {
    quux(e);
});
```

The compiler now rejects this, because according to the externs, the argument to the callback might be `undefined`.  But that should never happen.  Am I missing something?

**Comment by ChadKillingsworth** [comment]
I need to make these signatures have parity with the `addEventListener` callback signature.

The tricky part is supporting use cases where the callback function doesn't have the event argument.

```JavaScript
$('.foo').on('click', function() { console.log(this); } );
```

**Comment by ChadKillingsworth** [comment]
You can test the fixed version with https://raw.githubusercontent.com/ChadKillingsworth/closure-compiler/jquery-externs-cleanup/contrib/externs/jquery-1.9.js
