### ISSUE TITLE
Add an es6_entry_module option

### ISSUE THREAD

**Issue by DomBlack** [google/closure-compiler#881]
At the moment, if you are trying to write a ES6 module based application, due to #880 you are unable to specify a `--closure_entry_point` due to the ES6 module code not being includable by anything which has a `goog.provide` in it.

This becomes an issue if you want to use the closure library and require it from within the newer ES6 module code, the output file size becomes much larger than required due to the fact it is not removing files which are not transitive dependencies of your entry point - which would be an ES6 module.

Adding an `es6_entry_module` parameter which works alone the lines of the `closure_entry_point` would allow the removal of files noted required by the application, which cannot be removed simply using dead code removal.

**Comment by Dominator008** [comment]
This has been fixed by the new `--entry_point` flag: https://github.com/google/closure-compiler/wiki/Managing-Dependencies
