### ISSUE TITLE
Comments inside comments...

### ISSUE THREAD

**Issue by brianwestphal** [google/closure-compiler#885]
I'm sure this is a long shot, but I'm defining a large typedef to be used with an extern (chart.js) and I'm finding that I'd like to be able to add comments within my typedef.

For example

```javascript
/** @typedef {{
	// Common
	animation:(boolean|undefined),
	animationEasing:(string|undefined),
	animationSteps:(number|undefined),
	...
	tooltipXPadding:(number|undefined),
	tooltipYPadding:(number|undefined),

	// Bar, Doughnut / Pie, and Line Charts
	legendTemplate:(string|undefined),

	// Bar and Line Charts
	scaleShowGridLines:(boolean|undefined),
	scaleGridLineColor:(string|undefined),
	scaleGridLineWidth:(number|undefined),
	scaleShowHorizontalLines:(boolean|undefined),
	scaleShowVerticalLines:(boolean|undefined),
	...  
```

**Comment by concavelenz** [comment]
This has come up before.  We would really like to provide an alternate means of declaring record types.

**Comment by chrismiddleton** [comment]
I would just like to echo my desire for this feature, that is, allowing comments within a jsdoc typedef. It especially is useful for configuration objects, options objects, an image header info object, etc. Right now, I'm putting the comments down below, duplicating the property names, which obviously is prone to error.

**Comment by concavelenz** [comment]
@record can be used now for this.

**Comment by chrismiddleton** [comment]
Awesome job, that looks very useful. My only complaint is that you have to repeat the type name for each property; perhaps at some point in the future there could be sugar for it like

    /**
     * // the frob
     * @prop {Bar!} bar
     * // bazzes the frob
     * @prop {number} baz
    **/
    function Foo () {}
