### ISSUE TITLE
Why does let in for statement require an initializer?

### ISSUE THREAD

**Issue by rhashimoto** [google/closure-compiler#889]
Using Closure Compiler v20150315 on this code:

    "use strict";

    let s = 'foo fool food';
    const re = /foo/g;

    // This compiles.
    for (var m; m = re.exec(s);)
      console.log(m[0]);

    // This doesn't.
    for (let m; m = re.exec(s);)
      console.log(m[0]);

fails with:

    $ java -jar /opt/closure/closure-compiler//compiler.jar --js forlet.js --language_in ECMASCRIPT6_STRICT --language_out ECMASCRIPT5_STRICT
    forlet.js:11: ERROR - Parse error. let/const in for statement must have an initializer
    for (let m; m = re.exec(s);)
              ^

    1 error(s), 0 warning(s)

Is this really an error? The [ES6 grammar](http://people.mozilla.org/~jorendorff/es6-draft.html#sec-for-statement) says that `for` takes a *LexicalDeclaration*, which can produce *LetOrConst BindingIdentifier ;* (without an initializer). It seems strange that `var` works but `let` does not.

This construct works directly (without being compiled) in Chrome 41, IE 11, and Firefox 32.

**Comment by MatrixFrog** [comment]
We've had that error since the very first checkin of the new parser in the Closure Compiler codebase. My guess would be that the draft of the spec at the time required the initializer but the newest draft doesn't.
