### ISSUE TITLE
Allow ES6 classes in externs

### ISSUE THREAD

**Issue by MatrixFrog** [google/closure-compiler#893]
It would be nice to let people write types in externs as ES6 classes, perhaps even if they aren't planning to use ES6 in their code.

**Comment by concavelenz** [comment]
We also need to consider ES6 modules and what these externs would look like.

**Comment by joeyparrish** [comment]
Any update on this?

**Comment by brad4d** [comment]
I know that I recently saw transpilation code that was running on externs files to transpile them.
This may be working at least partially.

**Comment by blickly** [comment]
This looks to be working now:
https://closure-compiler-debugger.appspot.com/#input0%3Dclass%2520Bar%2520extends%2520Foo%2520%257B%257D%26input1%26conformanceConfig%26externs%3Dclass%2520Foo%2520%257B%257D%26refasterjs-template%26includeDefaultExterns%3Dtrue%26CHECK_SYMBOLS%3Dtrue%26MISSING_PROPERTIES%3Dtrue%26TRANSPILE%3Dtrue%26CHECK_TYPES%3Dtrue%26CLOSURE_PASS%3Dtrue%26PRESERVE_TYPE_ANNOTATIONS%3Dtrue%26PRETTY_PRINT%3Dtrue

**Comment by joeyparrish** [comment]
Awesome, thank you for the update!
