### ISSUE TITLE
Get different output after compression with simple optimizations

### ISSUE THREAD

**Issue by JacksonGL** [google/closure-compiler#896]
Not sure if this should be counted a bug. The following JavaScript code snippet prints ```longlongfunctionname```.
```javascript
function getFun() {
  return function longlongfunctionname() {}
}
fun = getFun();
console.log(fun.name);
```
After compression with ```SIMPLE_OPTIMIZATIONS``` mode, the minimized code prints an empty string.
```javascript
function getFun(){return function(){}}fun=getFun();console.log(fun.name);
```

**Comment by MatrixFrog** [comment]
> The Compiler renames functions and function parameters but does not change any strings in your code that refer to functions or parameters by name. You should thus avoid representing function or parameter names as strings in your code.

https://developers.google.com/closure/compiler/docs/limitations

**Comment by JacksonGL** [comment]
Oh, I see. It would be really great if the compiler could generate a warning if the input code uses those features that could potentially leads to a different semantics after compression.

**Comment by MatrixFrog** [comment]
That's probably hard to detect in general, but maybe we could warn on uses of Function.prototype.name
