### ISSUE TITLE
Allow closure_entry_point flag to accept a filename instead of a goog.provide'd symbol.

### ISSUE THREAD

**Issue by freshp86** [google/closure-compiler#897]
.... or add a new closure_enty_file flag instead of reusing the existing flag.

Asking for this because I am interested in compiling JSUnit tests individually (just for type checking, no intention to actually run the test in compiled mode for now). Because currently the flag is only accepting goog.provide'd symbols I have to add a goog.provide statement in each file, even though those namespaces are never ever need to be goog.require'd anywhere.

**Comment by dimvar** [comment]
You should not need to use closure_entry_point for these tests; it's only needed by manage_closure_dependencies, which again is not relevant if you are not executing the code.

**Comment by freshp86** [comment]
I tried your suggestion but it is not equivalent. By not using an "entry point" there is no pruning done by the compiler, which leads in the entirety of closure library (and any other included code) to be compiled. For example I am getting errors in completely unrelated parts of the closure library (pasting some of them below),

node_modules/closure-library/closure/goog/editor/plugins/basictextformatter_test.js:680: WARNING - Bad type annotation. missing opening (
 * @param {function} doSelect Function to select the "23" text in the test
                   ^

node_modules/closure-library/closure/goog/ui/richtextspellchecker_test.js:84: WARNING - Bad type annotation. expected closing }
 * @typedef {!Array<string><string>>}
                           ^

node_modules/closure-library/closure/goog/useragent/product_test.js:97: WARNING - Bad type annotation. expected closing }
 *             num: {string|number}, truth: boolean}>}>} userAgents
                           ^

node_modules/closure-library/closure/goog/useragent/product_test.js:97: WARNING - Bad type annotation. type not recognized due to syntax error
 *             num: {string|number}, truth: boolean}>}>} userAgents
                           ^

node_modules/closure-library/closure/goog/useragent/product_test.js:97: WARNING - Bad type annotation. expecting a variable name in a @param tag
 *             num: {string|number}, truth: boolean}>}>} userAgents
                                   ^

node_modules/closure-library/closure/goog/date/date_test.js:225: ERROR - This style of octal literal is not supported in strict mode.
               f(2010, goog.date.month.JAN, 03));
                                            ^

node_modules/closure-library/closure/goog/date/date_test.js:1138: ERROR - This style of octal literal is not supported in strict mode.
  var d = new goog.date.DateTime(2006, 01, 01, 12, 00, 00);


I would like to be able to compile only the code that is googe.required (transitively) by the JSUnit test I am compiling, which is exactly what closure_entry_point provides me (with the caveat of not allowing me to specify a file instead of namespace). Can we please re-open this issue?

**Comment by MatrixFrog** [comment]
A better solution would be to fix all the compiler errors in Closure's tests. I tried to do this at one point, and actually compile Closure's tests, but I had to roll it back because of some weirdness in Closure's setup :(

Still, we could fix most of these, and it would be good to do that.

**Comment by freshp86** [comment]
Sure, fixing Closure's test to not produce any errors would be nice, but still compiling the entire codebase without any pruning seems very wasteful and unnecessary. I am planning to compile about 100 JSUnit tests individually. I believe that pruning would make all those 100 build tasks to run faster (I believe). By not using an "entry point" I am basically forced to create the dependency graph myselfd and pass only those files to the closure compiler jar, but I would really want to avoid re-implementing functionality that the compiler already provides (creating a dep graph and pruning).

**Comment by MatrixFrog** [comment]
Are all the compiler errors in _test.js files? If so you should also be able to exclude those. From the docs for the --js flag: 

> You may also use
> minimatch-style glob patterns. For
> example, use --js='**.js' --js='!**_test.js'
> to recursively include all js
> files that do not end in _test.js

You still will end up compling a lot of Closure code you don't want, but it should get rid of the errors at least.

**Comment by freshp86** [comment]
Thanks for the suggestion. Yes all errors come from test files, but as you guessed, the fact that we would compile more code than necessary was the reason for not settling with simply filtering out files that are matching "_test.js" suffix.
  We ended up implementing a dependency scanner/pruner as a node script. If anyone is interested we could probably clean it up a bit and replace the python scripts with new shiny JS code. For now it will reside in https://github.com/google/lovefield repository.

**Comment by concavelenz** [comment]
Personally, I would love to see the python code replaced with JS code.

**Comment by MatrixFrog** [comment]
Definitely. @freshp86, keep us updated, and maybe we'll want to take your solution for lovefield and make it a general solution that anyone can use.

**Comment by freshp86** [comment]
The code resides at https://github.com/google/lovefield/blob/master/tools/scan_deps.js. It can be heavily cleaned up. Specifically I have in mind the following
1) the two helper classes RequireMap and ProvideMap can be replaced with native V8 Map classes. 
2) Some bits are Lovefield specific and would need to be removed. For example TransitiveDepsScanner class also looks into a temporary folder where auto-generated code resides.

Looking at the functions that are exported from this file ("exports.blah = foo") you can find the entry points and trace the code from there, but in short
genDeps() method produces the contents of the deps.js file.
getTransitiveDeps() method takes a file as an entry point and builds the pruned dependency graph from there.

I will probably do cleanup 1 myself relatively soon.
