### ISSUE TITLE
Different semantics caused by dead code elimination

### ISSUE THREAD

**Issue by JacksonGL** [google/closure-compiler#898]
The following JavaScript program prints ```2```:
```javascript
try {
	function Sun() {
		var b = this.bodies[i];
		this.y = 1;
		return this.y;
	}
	console.log(Sun());
} catch (e) {
	console.log(2);
}
```
After simple optimization, the compressed code prints ```1```:
```javascript
try{var Sun=function(){return this.y=1};console.log(Sun())}catch(e$$7){console.log(2)};
```

**Comment by MatrixFrog** [comment]
I believe the compiler is assuming that accessing this.bodies and this.bodies[i] will both have no side effects, so it believes it's safe to remove that entire line. This is documented [on the wiki](https://github.com/google/closure-compiler/wiki/Compiler-Assumptions) ("Property reads are assumed to be side effect free") but we should probably also mention it on https://developers.google.com/closure/compiler/docs/limitations too.
