### ISSUE TITLE
Different semantics caused by reordering function definitions

### ISSUE THREAD

**Issue by JacksonGL** [google/closure-compiler#899]
The following code prints ```2```:
```javascript
try {
	function fun(bodies) {
		console.log(1);
	}

	function fun(bodies) {
		console.log(2);
	}
	fun();
} catch (ex) {}
```
After simple optimization, the compressed code prints ```1```:
```javascript
try{var fun=function(a){console.log(2)},fun=function(a){console.log(1)};fun()}catch(ex){};
```

**Comment by dimvar** [comment]
The compiler does not try to preserve semantics when there are redeclared names in the same scope.

It should have actually warned here, unfortunately, this particular warning happens during type checking, which is off by default in simple mode, you'll see the warning if you try advanced mode.

(Also, the compiler doesn't handle functions declared inside nested blocks, you should only declare them at the top level of a scope.)

I also noticed some other issues you reported recently. As a rule of thumb, you should know that the compiler does not try to model all the dynamism of JS. Turn on as many of the checks as you can, and fix all warnings before checking the compiled output for correctness.

**Comment by JacksonGL** [comment]
Sorry about that. I will fix all warnings before reporting any issue.

**Comment by concavelenz** [comment]
We should make sure that we handle this properly in ES6 mode (where this code is valid).  The functions shouldn't be reordered in any event, that seems like a bug to me.
