### ISSUE TITLE
ERROR - assignment to property indexOf of goog.array

### ISSUE THREAD

**Issue by adhintz** [google/closure-compiler#904]
Sometime after https://github.com/google/closure-compiler/commit/2a2c1d596019020809c196352c1cd7bd08af5802 our travis-ci started breaking even though we didn't change any meaningful code and it looks like closure-library also did not change. Perhaps it's a bug in closure-compiler?

Here's what we're seeing:
.lib/closure-library/closure/goog/array/array.js:109: ERROR - assignment to property indexOf of goog.array
found   : function (?, ?, ?): ?
required: function ((Array<T>|null|{length: number}), T, number=): number
goog.array.indexOf = goog.NATIVE_ARRAY_PROTOTYPES &&
^

From this travis-ci run: https://travis-ci.org/google/end-to-end/builds/58082513

**Comment by MatrixFrog** [comment]
Yeah, I'm puzzled by this. Not sure how this is broken when compiling Closure alone, but not broken for the many internal projects that depend on Closure. I would probably recommend that you use the released version of the compiler rather than grabbing the latest from our master branch. We do a new release every month, so you're never too far behind.

**Comment by MatrixFrog** [comment]
By the way I think e87262264b39d237a3bb534dbf6a6c592b247f87 may be the commit that actually broke this.

**Comment by MatrixFrog** [comment]
The difference is that Closure uses a different CodingConvention than Google-internal projects. Fix (with a little more details) is in progress.

**Comment by adhintz** [comment]
> recommend that you use the released version of the compiler

Sounds good -- thanks! I didn't notice a latest release tag for closure-compiler. Some repos have a latest release tag, but I'm not sure how to make one. For now I'll just grab a particular release: https://github.com/google/end-to-end/pull/282

**Comment by MatrixFrog** [comment]
Just downloading from http://dl.google.com/closure-compiler/compiler-latest.zip should work too.

**Comment by ChadKillingsworth** [comment]
Or Maven or NPM

**Comment by concavelenz** [comment]
I think this can be closed now?

**Comment by MatrixFrog** [comment]
Yes thanks. For reference, the fix was 7f390a665ed2822451cc29a09502c57c152fe142
