### ISSUE TITLE
Feature Request: Allow use of use_only_custom_externs and standard input

### ISSUE THREAD

**Issue by dhai** [google/closure-compiler#905]
use_only_custom_externs does not get picked up when pushing in files via standard input:

	java -jar compiler.jar --use_only_custom_externs
	console.log("XYZ"); // stdin
	console.log("XYZ"); // stdout

This should result in an error.  Also, it would be nice if we could pass both the javascript to be compiled, and the externs, all in one pass via standard input (a delimiter maybe?).

	// the code to be compiled
	
	/* @hereth-beith-the-google-closure-compiler-externs */
	
	// externs definitions

**Comment by ChadKillingsworth** [comment]
You need to set your warning level or enable the proper checks:
```
echo 'console.log("XYZ");' | java -jar build/compiler.jar --use_only_custom_externs -W=VERBOSE
stdin:1: ERROR - variable console is undeclared
console.log("XYZ");
^
```

The magic annotation you are looking for is `@externs` and it operates at the `@fileoverview` block. See:  https://github.com/google/closure-compiler/blob/master/contrib/externs/jquery-1.9.js#L27

**Comment by ChadKillingsworth** [comment]
Although I just realized, `@externs` won't help when you pass multiple files in a single stream. That's not supported.

I'm guessing you are using a build system that utilizes streams? Like Gulp?

**Comment by dhai** [comment]
I've written my own precompiler that generates it's own externs.

You're right, I totally forgot the verbose flag.  doh!

Thanks for the note about the externs!

**Comment by dhai** [comment]
Just to clarify, since the externs annotation happens at the fileoverview level, I assume there is no way to pass in both the externs and code to be compiled via stdin?

java -jar bin/compiler.jar -- warning_level=VERBOSE --compilation_level=ADVANCED_OPTIMIZATIONS --language_in=ECMASCRIPT6_STRICT --language_out=ECMASCRIPT5_STRICT --use_only_custom_externs < "test.js"

where test.js is:

	console.log("XYZ");
	
	/**
	 * 	@externs
	 */
	
	/**
	 *	@constructor
	 *	@extends {Object.<string,*>}
	 *	@return {void}
	 */
	function Console(){
	};
	
	/**
	 *	@param {...*} args
	 *	@return {void}
	 */
	Console.prototype.log=function(args){};
	
	/**
	 *	@type {Console}
	 *	@const
	 */
	var console;

output is:

	"use strict";

Where I'm assuming the console.log is ignored, because it's being seen as an extern ....
