### ISSUE TITLE
Erronious output generated with --debug --formatting=PRETTY_PRINT --compilation_level ADVANCED_OPTIMIZATIONS set

### ISSUE THREAD

**Issue by ILOVEPIE** [google/closure-compiler#908]
I'm getting strange output with $s and incorrect formatting as well as syntax errors, it's supposed to simply print longer names and in a viewable format for debugging the output.

**Comment by MatrixFrog** [comment]
IIRC --debug is for debugging the compiler, so unless you're hacking on the compiler itself you probably don't need it.

**Comment by ILOVEPIE** [comment]
the documentation of the compiler said it was for debugging output

**Comment by ILOVEPIE** [comment]
and --formatting=PRETTY_PRINT isn't working

**Comment by ChadKillingsworth** [comment]
I use this all the time to debug - both flags.

Can you provide a repo case?

**Comment by ILOVEPIE** [comment]
i'm uncertain as to what specifically is causing this bug to occur with my .js files, considering that the one that's been giving me the most trouble is over 950 lines long, it will take me a while to come up with a repo case, the flags i'm using are:

    --debug --formatting=PRETTY_PRINT --compilation_level ADVANCED_OPTIMIZATIONS

and here is a snippet from the beginning of the output closure compiler creates from that 950 line file showing the strange abundance of dollar signs:

    Object.create(window.hbmp.renderer_prototype, {$_last_time$:{value:-1, writable:!0}, $_last_events$:{value:"", writable:!0}, $_animating$:{value:!1, writable:!0}, $_scaleRatio$:{value:1, writable:!0}, $_display$:{value:null, writable:!0}, $_context$:{value:null, writable:!0},

also note that everything came out on one line instead of pretty-printed, i'm using the latest version of the compiler.

**Comment by ihsoft** [comment]
"$" in debug output is totally OK. This is how compiler denotes renamed identifiers.

Pretty print is another story. What was the source you compiled? Did you try compiling with stable version? I frequently use debug & pretty print and never had problems.

**Comment by ChadKillingsworth** [comment]
Also try disabling the type based optimizations

    - - use_types_for_optimization false

**Comment by ILOVEPIE** [comment]
ah ok i didn't know about the $ thing, as for the pretty print, i'm using the compiler from this url: http://dl.google.com/closure-compiler/compiler-latest.zip

the source I compiled is part of the javascript based video player i've been working on for the past year and a half, i've been continually testing both the un-compiled and closure compiled versions, however when i updated my closure compiler today it broke the player, so i went to go debug it and the pretty print didn't work.

**Comment by ChadKillingsworth** [comment]
The latest compiler version enables the type based optimizations by default. Turning those off will more than likely fix your problem.
