### ISSUE TITLE
es6 classes with same name as called function

### ISSUE THREAD

**Issue by jhiswin** [google/closure-compiler#909]
class MyClass extends SomeOtherClass {
   init(config){
      window["SomeObject"].init(config);
   }
}
MyClass.init({});

compiles to
function a(b){a(b)}a({});

**Comment by MatrixFrog** [comment]
That's not what I'm seeing. http://closure-compiler-debugger.appspot.com/#input0%3Dclass%2520MyClass%2520extends%2520SomeOtherClass%2520%257B%250A%2520%2520init(config)%257B%250A%2520%2520%2520%2520window%255B%2522SomeObject%2522%255D.init(config)%253B%250A%2520%2520%257D%250A%257D%250A%250AMyClass.init(%257B%257D)%253B%26input1%26conformanceConfig%26externs%3Dvar%2520SomeOtherClass%253B%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES%3D1%26LANG_IN_IS_ES6%3D1%26MISSING_PROPERTIES%3D1%26PRETTY_PRINT%3D1%26PROPERTY_RENAMING%3D1%26TRANSPILE%3D1%26VARIABLE_RENAMING%3D1

**Comment by jhiswin** [comment]
I've narrowed it down to something strange.  I made a typo in init() along the lines of:
```javascript
//notice the assignment variable, which was supposed to be a comparison operator
if(this._privateVariable = GlobalEnum.EnumValue)
  window["SomeObject"].init(config);
```
And for some reason, it caused the init function to get confused and think it was calling itself recursively.
Note: init is not externed, and SomeObject does not (yet) exist

**Comment by concavelenz** [comment]
Can this be closed then?
