### ISSUE TITLE
Update extern to support referring to HTML5 history API directory

### ISSUE THREAD

**Issue by devraj** [google/closure-compiler#910]
At present you can refer to it as `window.history`, HTML5 allows referring to it the history API directory.

As per [discussion on the list](https://groups.google.com/forum/#!topic/closure-compiler-discuss/eWiXN2PkJK0) with @ChadKillingsworth the externals needs to be updated.

**Comment by MatrixFrog** [comment]
https://github.com/google/closure-compiler/blob/b8239c41b48feb8c527ed11c12aae7cae47617d8/externs/gecko_dom.js#L109

**Comment by MatrixFrog** [comment]
But there are a bunch of project-specific externs definitions inside Google so we probably have to delete all those so we don't get duplicate warnings :(

**Comment by ChadKillingsworth** [comment]
@MatrixFrog Do you want to handle this then? If not, I'll get a PR ready.

**Comment by MatrixFrog** [comment]
I probably won't get to it anytime soon. I think it should work with a `@suppress {duplicate}` so we don't have to do the Google-wide cleanup right away.
