### ISSUE TITLE
Implement the ChildNode interface in default externs

### ISSUE THREAD

**Issue by ChadKillingsworth** [google/closure-compiler#914]
See http://stackoverflow.com/a/29774898/1211524

References
 * https://developer.mozilla.org/en-US/docs/Web/API/ChildNode
 * https://dom.spec.whatwg.org/#interface-childnode

Also, HTMLSelectElement overloads the `remove` method.

**Comment by ChadKillingsworth** [comment]
Actually it looks like `.remove` is the only method of the interface currently implemented so we might just want to add that.

**Comment by Dominator008** [comment]
Should be similar to https://github.com/google/closure-compiler/pull/1726.
