### ISSUE TITLE
Document @nocollapse

### ISSUE THREAD

**Issue by ChadKillingsworth** [google/closure-compiler#915]
Suggested documentation:

## Tag
@nocollapse

## Syntax & Examples
@nocollapse
*For example:*

```JavaScript
/**
 * A namespace.
 * @const
 */
var foo = {};

/**
 * @nocollapse
 */
foo.bar = 42;

window['foobar'] = foo.bar;
```
# Description
Denotes a property that should not be collapsed by the compiler into a variable. The primary use for @nocollapse is to allow properties to remain mutable after exporting.

Without `@nocollapse`, static properties may be collapsed into global variables thereby making exports immutable. Property exports are mutable whereas variable exports are immutable.

**Comment by blickly** [comment]
Done: https://developers.google.com/closure/compiler/docs/js-for-compiler#tag-nocollapse
