### ISSUE TITLE
Different semantics caused by moving 'use strict'

### ISSUE THREAD

**Issue by JacksonGL** [google/closure-compiler#917]
Sorry, another issue report :) This time the compressed code throws exception on Firefox and Node.js. 
 * It does not seem to violate any [compiler assumptions](https://github.com/google/closure-compiler/wiki/Compiler-Assumptions). 
 * There is no warning under parameter ```--warning_level VERBOSE```

The following code executes normally:
```javascript
var f = function() { 
    "use strict";
	return {};
};
function f2() {
  var a = {};
	if(Math.random() < 100) {
		a = arguments;
	}
	return a.callee;
}
f2();
```
After compression with the following parameters:
```--compilation_level SIMPLE  --language_in=ECMASCRIPT5_STRICT --warning_level VERBOSE```
The compressed code throws an exception (on Firefox and node.js):
```javascript
'use strict';var f=function(){return{}};function f2(){var a={};100>Math.random()&&(a=arguments);return a.callee}f2();
```

**Comment by blickly** [comment]
--language_in=ECMASCRIPT5_STRICT means that the input should be treated as ES5 strict mode code, i.e. not depend on any sloppy mode behavior.

**Comment by JacksonGL** [comment]
Is there any way to preserve the function level strict mode? Thanks.

**Comment by ChadKillingsworth** [comment]
No - function level strict mode doesn't make sense when functions can get completely inlined. It's an all-or-nothing choice. Details of the implentation: https://code.google.com/p/closure-compiler/issues/detail?id=69
