### ISSUE TITLE
Migrate code.google.com closed issues

### ISSUE THREAD

**Issue by ChadKillingsworth** [google/closure-compiler#919]
When the move to github was made, open issues were migrated. However, closed issues were not. There are lots of great discussions there I still reference, like this one: https://code.google.com/p/closure-compiler/issues/detail?id=69

Can we import the closed code.google.com issues to github before code.google.com is turned off?

**Comment by MatrixFrog** [comment]
I agree we should definitely do this.

I don't remember how we did the migration, but we didn't use the super-easy auto-migrator (https://code.google.com/export-to-github/) because it didn't exist at the time. And if we run the auto-migrator now I'm not sure what would happen. Ben, do you remember what we did, or have ideas how to do this?

**Comment by ChadKillingsworth** [comment]
It looks to be more complicated. Open issues just reference to google code issue for discussion - they don't replicate it on github.

**Comment by blickly** [comment]
I've downloaded the database dump of the googlecode issue tracker (in a single huge json file), but I'm not sure what to do with it. Github doesn't allow renumbering of issue numbers, so we would never be able to number them consistently with what they were numbered before.

**Comment by ChadKillingsworth** [comment]
It's fine by me if they have different numbers. I rarely remember the number and find the issue through searches. Ideally importing would look like this:

1. Update any issue already imported with the old discussion. This could just be some kind of MD quote block of the discussion in the original post.
2. Add any non-imported issue (because it was already closed) as a new closed issue with the same MD quote block as the description.

**Comment by blickly** [comment]
Ok, I mirrored the old issues to http://blickly.github.io/closure-compiler-issues/#123 (where 123 is the old google code numbering). I also updated the first post in all of our migrated issues to point there instead.
