### ISSUE TITLE
Inline forEach

### ISSUE THREAD

**Issue by roman01la** [google/closure-compiler#923]
Is it possible to make Closure Compiler to inline `forEach` into a `for` loop? For some reason V8 still doesn't do this optimization.

Also optimizng array iteration functions like `map`, `filter`, etc. would be a great thing.

**Comment by concavelenz** [comment]
This is generally harder than it sounds to do correctly in the general case.  You can write a custom compiler pass to do this pretty trivially (see the compiler peephole passes) if you want to take that try this out for yourself.

**Comment by roman01la** [comment]
Ok, thank you!
