### ISSUE TITLE
Distributing the Contrib/Externs

### ISSUE THREAD

**Issue by ChadKillingsworth** [google/closure-compiler#924]
Most of my projects make use of at least one extern maintained in the contrib/externs folder. Currently I either have to use a dependency system to download the extern from the github contrib externs folder or check the extern into my project's source control. Neither are great solutions.

I'd like to distribute the contrib/externs folder as part of the NPM package. It would be updated on the same release cycle as the compiler. Are there objections to this?

**Comment by dimvar** [comment]
I'm fine with this. Remind me, why didn't we do it from the start?

**Comment by ChadKillingsworth** [comment]
> Remind me, why didn't we do it from the start?

I didn't occur to me.

To date, I just matched what was available in the other distributions. It's not in Maven, therefore I didn't include it in NPM.

**Comment by ChadKillingsworth** [comment]
Closed with the 20150505 release: https://www.npmjs.com/package/google-closure-compiler
