### ISSUE TITLE
Feature request: @constexpr

### ISSUE THREAD

**Issue by mashify** [google/closure-compiler#925]
I would like something like this:

    /** @constexpr */
    function count(to) {
      for(var i = 0; i < to; i++) {}
      return i;
    }
    console.log(count(3));

result into:

    console.log(3);

when compiled.
At the moment this would result into:

    for(var a=0;3>a;a++);console.log(a);

**Comment by dimvar** [comment]
We generally avoid adding jsdoc annotations that direct compiler optimizations. I don't think that <code>@constexpr</code> would be used often enough to justify the complexity of having it.

**Comment by ChadKillingsworth** [comment]
It's also not needed. The compiler will completely inline a function if it can. In your case, the `for` loop isn't unrolled.

Example:
```JavaScript
function count(from, to) {
  return from + to;
}
console.log(count(1, 3));
```

**Comment by mashify** [comment]
alright.. thank you very much for the fast responses.

**Comment by ihsoft** [comment]
This request somehow relates to `@nosideffects`. It's pity it cannot be applied to non-externs functions. In many cases prototype function could be inlined but compiler doesn't do this because of there could be side-effects, and there is no way to give a hint.
