### ISSUE TITLE
Non-existing type defined in externs/html5.js

### ISSUE THREAD

**Issue by oldergod** [google/closure-compiler#927]
See this code [externs/html5.js](https://github.com/google/closure-compiler/blob/master/externs/html5.js#L2813)
The `options` parameter of `MutationObserver.prototype.observe` is typed to `MutationObserverInit` and this type is also defined few lines above at [line 2747](https://github.com/google/closure-compiler/blob/master/externs/html5.js#L2747).

However, the type `MutationObserverInit` does not exist and for instance, the [example code at the Mozilla Developer Network](https://developer.mozilla.org/en/docs/Web/API/MutationObserver#Example_usage) would not compile because an `Object` ―not a `MutationObserverInit`― is passed to the function.

Would it not be better to define it like [WheelEventInit is defined](https://github.com/google/closure-compiler/blob/master/externs/html5.js#L1859).

**Comment by MatrixFrog** [comment]
Yeah, a typedef of a record type probably would have been better. For now, you can add a cast and it should work.

**Comment by MatrixFrog** [comment]
It's not letting me assign to him but @jklein24 has a fix for this.
