### ISSUE TITLE
jQuery load is over eagerly defined as deprecated

### ISSUE THREAD

**Issue by normanr** [google/closure-compiler#931]
The [load event](http://api.jquery.com/load-event/) is deprecated, but the [load method](http://api.jquery.com/load/) is not, but usages of both generate deprecation warnings.

It would be nice if the deprecation warnings were only generated for the deprecated method, and not the non-deprecated one.

There's even confusion on the [original bug](http://bugs.jquery.com/ticket/11733) to deprecate the event-handler-method vs load-data-from-server-method.

**Comment by ChadKillingsworth** [comment]
I can remove the `@deprecated` annotation, but since JavaScript doesn't support function overloading (and closure-compiler doesn't either), it's for both usages or neither.

**Comment by ChadKillingsworth** [comment]
The extern method has a comment for the `@deprecated` annotation specifically calling out the problems with this method. I'm going to leave the method marked as `@deprecated`. If you are using the ajax signature of `.load`, use `@suppress {deprecated}` to indicate that the usage is intentional.
