### ISSUE TITLE
Multiple arrow functions in the same function but different lexical scope result in invalid transpiled output

### ISSUE THREAD

**Issue by shicks** [google/closure-compiler#932]
Simple repro case:

    xss.forEach(xs => {
      xs.forEach(x => console.log(x));
    });

When attempting to compile the transpiled result, the inner arrow fails with

    ERROR - Redeclared variable: $jscomp$this

Presumably the resolution is to just detect that the call is nested and not redeclare the variable (or if it's possible that `this` is different, use `$jscomp$this$1`, though I can't imagine a case where that's possible).

**Comment by MatrixFrog** [comment]
Is this from a Haskell-to-JS compiler? :)

**Comment by shicks** [comment]
Scratch that - I looked back at it and it's not nested arrows, it's adjacent arrows in the same scope.

    xs.forEach(x => console.log(x));
    xs.forEach(x => console.log(x));

(Haskell-to-JS is a nice idea in theory, but in practice it's kinda annoying...)

**Comment by shicks** [comment]
The above code transpiles to

    var $jscomp$this = this;
    xs.forEach(function(x) { console.log(x); });
    var $jscomp$this = this;
    xs.forEach(function(x) { console.log(x); });

(Apologies if it's not exact - I'm hand-simplifying my actual output - it's possible that it actually does work if the functions don't actually use `this`... but it definitely fails if `this` is referenced in both arrows.)

**Comment by shicks** [comment]
Okay, it's more subtle than that.  It works if they're really adjacent, but fails if they're, say, at different levels of nesting from `if`s or `for` loops.  I'm going to put together a real minimal example I can just paste in.

**Comment by shicks** [comment]
var f = function(xs) {
      xs.forEach(x => this.log(x));
      if (xs.length > 1) {
        xs.forEach(x => this.log(x));
      }
      xs.forEach(x => this.log(x));
    }

Transpiled result:

    var f = function(xs) {
      var $jscomp$this = this;
      xs.forEach(function(x) {
        return $jscomp$this.log(x);
      });
      if (xs.length > 1) {
        var $jscomp$this = this;
        xs.forEach(function(x) {
          return $jscomp$this.log(x);
        });
      }
      xs.forEach(function(x) {
        return $jscomp$this.log(x);
      });
    };

As you can see, it reuses the `$jscomp$this` when both functions are in the exact same block, but in the `if`, it tries to make a new one, which is illegal.

**Comment by MatrixFrog** [comment]
Can you repro this on the debugger? I'm not seeing it.

https://closure-compiler-debugger.appspot.com/#input0%3Dvar%2520f%2520%253D%2520function(xs)%2520%257B%250A%2520%2520xs.forEach(x%2520%253D%253E%2520this.log(x))%253B%250A%2520%2520if%2520(xs.length%2520%253E%25201)%2520%257B%250A%2520%2520%2520%2520xs.forEach(x%2520%253D%253E%2520this.log(x))%253B%250A%2520%2520%257D%250A%2520%2520xs.forEach(x%2520%253D%253E%2520this.log(x))%253B%250A%257D%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES%3D1%26LANG_IN_IS_ES6%3D1%26PRETTY_PRINT%3D1%26TRANSPILE%3D1

**Comment by shicks** [comment]
Look again.  You don't get an error on the first pass, but your link's Module Binary Parent has a redeclared $jscomp$this.  I can't find the flags to enable the REDECLARED_VARIABLE check, but if you enable it and pass the transpiled output back through the compiler, you get a redeclared variable error.

**Comment by shicks** [comment]
Hmm... Nevermind, it seems to be working on the public debugger.  Could be a regression since that version was built, since the version at head is definitely broken.
