### ISSUE TITLE
missing ServiceWorker externs

### ISSUE THREAD

**Issue by nicks** [google/closure-compiler#935]
are there ServiceWorker externs yet?

I can contribute some if there are not
http://www.w3.org/TR/service-workers/

**Comment by ChadKillingsworth** [comment]
I haven't seen any come through.

**Comment by nicks** [comment]
OK, I sent a PR here:
https://github.com/google/closure-compiler/pull/936

**Comment by MatrixFrog** [comment]
Added in fd513f84fecbf83642b1f234c0aa45b250923c35 -- I did a quick diff of that version vs. the one you sent and it looked like they were similar but definitely had some differences. Of course, let us know if you see anything that looks wrong.
