### ISSUE TITLE
In externs, interfaces should be allowed to extend constructors

### ISSUE THREAD

**Issue by ChadKillingsworth** [google/closure-compiler#937]
HTML5 Service Workers are defined as an interface which extend a constructor (Worker). We should allow this.

See #936

**Comment by dimvar** [comment]
Is this an IDL thing? IIRC, there is not an exact match between that type system and ours.

I don't think we should allow this in the externs, we should have the same typing rules everywhere.

**Comment by ChadKillingsworth** [comment]
I thought we allowed interfaces to behave differently already, but I was mistaken. https://code.google.com/p/closure-compiler/issues/detail?id=250

**Comment by concavelenz** [comment]
As I recall IDL definitions are interfaces which is confusing.
