### ISSUE TITLE
--extra_annotation_name doesn't seem to do anything

### ISSUE THREAD

**Issue by jklein24** [google/closure-compiler#941]
I'm trying to use the --extra_annotation_name flag on the command line to avoid errors for some Polymer annotations that the compiler doesn't understand, but this flag seems to have no effect on anything. In the process, I tried copying the following 2 lines:

https://github.com/google/closure-compiler/blob/master/test/com/google/javascript/jscomp/CommandLineRunnerTest.java#L137-138

to the end of that test, and the test still passes. This indicates to me that the error will still fire regardless of whether the flag is set. I tried to do some quick debugging, but I don't see anything obviously wrong with the CommandLineRunner code with regards to this flag. Does anyone see anything I'm missing?

**Comment by jklein24** [comment]
@MatrixFrog

**Comment by MatrixFrog** [comment]
It looks like you're overriding the command line flags here: https://code.google.com/p/chromium/codesearch#chromium/src/third_party/closure_compiler/runner/src/org/chromium/closure/compiler/Runner.java&l=190

Will try to confirm.

**Comment by MatrixFrog** [comment]
Yeah, it looks like you can just nuke that line and everything works. It was probably copy-pasted from the runner used in third_party/WebKit/Source/devtools but afaict there aren't any `@suppressReceiverCheck`s in the code you're trying to compile.
