### ISSUE TITLE
Incorrect removal of named function variable assignment

### ISSUE THREAD

**Issue by Aedx** [google/closure-compiler#942]
When compiling code containing a variable assignment which involves a named function on the RHS, `closure-compiler` 'optimises' away the function naming, resulting in assignment of an anonymous function instead.

For example, contemplate the following rather useless code snippet:

```javascript
var foo = function foo() {};
```

`closure-compiler` returns the following:

```javascript
var foo=function(){};
```

This is quite the problem when utilising named function properties, such as `foo.name`; whereas from the first snippet, `foo.name` would return `"foo"`, but from the second snippet `""` would be returned instead. This obviously leads to unexpected behaviour.

**Comment by dimvar** [comment]
We don't support manipulating a function's name as a string in the code. See here limitations when working with the compiler:
https://developers.google.com/closure/compiler/docs/limitations

**Comment by Aedx** [comment]
That isn't the issue, the issue is the fact that the named function is being converted into an anonymous function, hence causing unexpected behaviour.

That is, there are a lot of differences in the way that named (`function foo() {}`) and anonymous (`var foo = function() {}`) behave; converting one type to the other should be avoided at all costs.

**Comment by dimvar** [comment]
You are right that they are different in general. But in the restricted JS subset that the compiler can optimize safely, they should behave the same.

**Comment by Aedx** [comment]
They don't behave the same... Also, I am slightly confused as to what you mean by 'restricted JS subset'.

**Comment by dimvar** [comment]
I mean that if you use the full dynamism of JS with Closure Compiler, the compiler will silently break your code. It cannot handle all of JS safely. Read through the limitations page to see which things to avoid.

**Comment by Aedx** [comment]
The limitations page mentions this nowhere.

I thought that the point of this tool was supposed to be that it 'compiles from JavaScript to better JavaScript' - not to break it instead.

**Comment by concavelenz** [comment]
Sorry, the compiler doesn't attempt to preserve function name properties.  We have documented the limitations the optimization impose here:

  https://developers.google.com/closure/compiler/docs/limitations?csw=1
  https://github.com/google/closure-compiler/wiki/Compiler-Assumptions

It isn't possible to do any optimization of JavaScript without making some assumptions (that includes only removing whitespace).   We have chosen what we feel is the best compromise for the use-cases we have seen.  If you feel the behavior should be different, backing it up with your use cases and, if possible, reference other libraries that use similar patterns would be best.

**Comment by Aedx** [comment]
Why not to use function declarations (FDs) and anonymous function expressions (AFEs)
------------------------------------------------------------------------------------

Before explaining the reasons behind my utilisation of NFEs, I will mention the major downfalls of both function declarations (`function foo() {}`) and anonymous functions (`var foo = function() {};`).

Function declarations are _evil_! They have various scoping problems, namely that they are defined anywhere within their block scope at runtime:

```javascript
var foo = function foo() {
    bar();  // N.B. pre-defined execution

    // Function declaration
    function bar() {
        console.log("Success!");
    }
};
foo();  // ↳ "Success!"

var foo = function foo() {
    bar();  // N.B. pre-defined execution

    // Anonymous function
    var bar = function() {
        console.log("Success!");
    };
};
foo();  // ↳ TypeError: undefined is not a function
```

This can lead to some confusion (and errors, if utilising strict mode) if conditionally defining functions.

As for anonymous functions, they are extremely tiresome to debug - the stack trace for an anonymous function can be quite unclear on various platforms, although thankfully these are being improved - e.g. in the V8 engine. Even after these improvements, they still do not (obviously) contain the various properties that named functions would have (`.constructor`, `.name`). 

I found this **[excellent review](http://kangax.github.io/nfe/)** of all the pros and cons to NFEs, AFEs and FDs. I advise you read it through, its creator has evidently researched functions in JS _really_ thoroughly.

Hence, I do not use function declarations. Ever. I repeat, they are _evil_. Also, I do not use anonymous functions, as they are not blessed with the useful `.constructor` and `.name` properties that named functions do.

NFEs have the best of both worlds. They contain useful properties, and are (relatively) painless to debug.

A list of use cases
-------------------

**1. Self-reference**

NFEs allow for recursion in IIFEs; as `arguments.callee` is depreciated (besides being disabled in strict mode) it is impossible to create a self-executing anonymous function. NFEs solve all of this.

As quoted from **http://stackoverflow.com/a/28596848/3979127**:

> Naming functions is useful if they need to reference themselves (e.g. for recursive calls). Indeed, if you are passing a literal function expression as an argument directly to another function, that function expression cannot directly reference itself in ES5 strict mode unless it is named.

As advised by MDN:

> Avoid using arguments.callee() by either giving function expressions a name or use a function declaration where a function must call itself.

Aside from FDs, the only solution here is to utilise an NFE.

**2. Conditional creation of functions**

Using NFEs, it is possible to conditionally create functions (generally increasing performance), i.e.:

```javascript
if (foo) {
    var bar = function bar() {
        return false;
    };
} else {
    var bar = function bar() {
        return true;
    };
}
bar();
```

Obviously this would not be useful in such a simple use case as just shown, and the following would suffice instead:

```javascript
var bar = function bar() {
    if (foo) {
        return false;
    } else {
        return true;
    }
};
```

However, in more complicated situations, conditional function creation would most likely be desirable - large-scale conditional function creation will result in a major performance gain, something which almost no programmer would deny is a **Good Thing™**

**3. Name-only properties**

NFEs also allow for function name checking via `.name`. I realise that closure-compiler may rename local/scoped functions; **this is not the problem**.

The `.constructor` property is also really useful when used on the child of a FD or NFE (unlike on an anonymous function), so it is possible to debug efficiently the parentage of a particular object. `.constructor` is also used very frequently in OOP.

An example:

```javascript
// NFE
var foo = function foo() {};
var bar = new foo;
console.log(bar.constructor);  // ↳ [Function: foo]

// Anonymous function
var foo = function() {};
var bar = new foo;
console.log(bar.constructor);  // ↳ [Function]
```

Libraries
---------

On the subject of libraries, I happen to be writing one myself. This library makes extensive use of NFEs, meaning that anyone who closure-compiles it with their own source code will run into many problems due to the malfunctioning source code which would arise as a result.

As far as projects which utilise this construct go, I believe that **[TypeScript](https://github.com/Microsoft/TypeScript)** and **[ESFormatter](https://github.com/millermedeiros/esformatter)** are a couple of fairly well known ones. Indeed, they are even utilised in Google's own **[Closure Library](https://github.com/google/closure-library/blob/2012c5372fdb02ce9531cf4b2561b05e3ce2ab39/closure/goog/labs/mock/mock_test.js#L455)**; testing **[this function](https://github.com/google/closure-library/blob/2012c5372fdb02ce9531cf4b2561b05e3ce2ab39/closure/goog/labs/mock/mock.js#L107-L113)** - usage of them can be found in **[various](https://github.com/google/closure-library/blob/2012c5372fdb02ce9531cf4b2561b05e3ce2ab39/closure/goog/asserts/asserts_test.js#L177)** **[other](https://github.com/google/closure-library/blob/2012c5372fdb02ce9531cf4b2561b05e3ce2ab39/closure/goog/async/workqueue_test.js#L37)** **[places](https://github.com/google/closure-library/blob/2012c5372fdb02ce9531cf4b2561b05e3ce2ab39/closure/goog/async/workqueue_test.js#L39)** also.

Conclusion
----------

Essentially, 'optimising' away these constructs take away a lot of useful programming possibilities, as well as confusing the heck out of anyone who closure-compiles code containing NFEs. Unfortunately, as I do not know closure-compiler's codebase well, I would be unable to submit a PR to fix this. However, I did put a lot of effort into explaining and clarifying this. Hopefully this has been useful.

**Comment by ChadKillingsworth** [comment]
The variations you point out are all well known to the authors and handled by Closure-compiler, but in ways you probably aren't aware of.

> They have various scoping problems, namely that they are defined anywhere within their block scope at runtime

The compiler will actually perform the function hoisting at compile time. The compiler will also emit an error if you try to conditionally define a function and specify the `--language_in=ECMASCRIPT5_STRICT` flag. It is not a goal to make the output JS easier to debug (in fact the opposite is true). Sourcemaps are for debugging.

As for your use cases.

## Self References:

The compiler will not remove the name of a function which is used in a reference:
```JavaScript
var a = function sumDown(num) {
  if (num <= 0) {
    return 0;
  }
  return num + sumDown(num - 1);
};

console.log(a(10));
```
becomes:

```Javascript
console.log(function b(a) {
  return 0 >= a ? 0 : a + b(a - 1);
}(10));
```

## Conditional creation of functions
This is fully supported. Example:
```Javascript
console.log((function() {
  var foo = window['foo'] || false;
  var bar; //variables are hoisted too
  if (foo) {
    bar = function bar() {
        return false;
    };
  } else {
    bar = function bar() {
        return true;
    };
  }
return bar();
})())
```
Becomes:
```Javascript
console.log((window.foo ? function() {
  return !1;
} : function() {
  return !0;
})());
```
## Name Only Properties 
It is not a goal of the compiler to preserve function names. In fact the opposite is true. You should be using sourcemaps to debug compiled code.

**Comment by Aedx** [comment]
Could you please clarify exactly what you mean by 'function names'? Is that their `.name` property, the variable to which they are assigned to in the code, etc.?

**Comment by ChadKillingsworth** [comment]
> Could you please clarify exactly what you mean by 'function names'? Is that their .name property, the variable to which they are assigned to in the code, etc.?

All of the above. There is nothing wrong with referencing a function's `.name` property, but the compiler is free to change the references from which that value is derived. You cannot rely on it to be preserved.

Since the `.name` property is an official part of the ES6 Harmony proposal, more work around this specific property may come in the future. In fact, #938 suggests an interesting idea regarding it. However, such support does not currently exist.

If you have a specific use case (not related to debugging), I'd post an example in the [closure-compiler-discuss group](https://groups.google.com/forum/#!forum/closure-compiler-discuss). There are usually other ways around the problem that do not violate the assumptions of the compiler.

If you want anonymous functions to be named for logging purposes and are not concerned that the function name does not match the original name, there is a [compiler option which will automatically name ALL anonymous functions](https://github.com/google/closure-compiler/blob/master/src/com/google/javascript/jscomp/CompilationLevel.java#L70). Enabling that option would require a custom build of the compiler however.

**Comment by Aedx** [comment]
I've not really had any problems with the `.name` derivation, only the anonymisation of NFEs. For an example, check the following code:

```javascript
var foo = function foo() {};
var bar = function bar() {};

var haveSameName = function haveSameName(functionA, functionB) {
    return functionA.name === functionB.name;
};

console.log(haveSameName(foo, foo);  // ↳ true
console.log(haveSameName(foo, bar);  // ↳ false
```

With the NFEs 'optimised' to AFEs:

```javascript
var foo=function(){},bar=function(){},haveSameName=function(a,b){return a.name===b.name};

console.log(haveSameName(foo, foo);  // ↳ true
console.log(haveSameName(foo, bar);  // ↳ true
```

---

I await the changes made for ES6 compliance; the issue which you referenced is interesting, seemingly it appears to be similar to one of the other functions which I found in Closure Library.
