### ISSUE TITLE
Improve error message for incompatible enums

### ISSUE THREAD

**Issue by dimvar** [google/closure-compiler#943]
Forked off #940. NTI catches the bug, but the error message is hard to understand for someone not very familiar with the type system. It reads

input0:16: WARNING - Cannot access property RED of non-object type bottom.
    case Color.RED:
         ^

input0:18: WARNING - Cannot access property ORANGE of non-object type bottom.
    case Color.ORANGE:
         ^

Code snippet:
```js
/** @enum {string} */
var Color = {
  RED: 'red',
  ORANGE: 'orange'
};

/** @enum {string} */
var Shape = {
  SQUARE: 'square',
  TRIANGLE: 'triangle'
};

/** @param {Shape} shape */
function f(shape) {
  switch (shape) {
    case Color.RED:
      alert('r');
    case Color.ORANGE:
      alert('o');
  }
}
```

**Comment by Dominator008** [comment]
@dimvar Looks like NTI stopped catching / reporting this?
https://closure-compiler-debugger.appspot.com/#input0%3D%252F**%2520%2540enum%2520%257Bstring%257D%2520*%252F%250Avar%2520Color%2520%253D%2520%257B%250A%2520%2520RED%253A%2520'red'%252C%250A%2520%2520ORANGE%253A%2520'orange'%250A%257D%253B%250A%250A%252F**%2520%2540enum%2520%257Bstring%257D%2520*%252F%250Avar%2520Shape%2520%253D%2520%257B%250A%2520%2520SQUARE%253A%2520'square'%252C%250A%2520%2520TRIANGLE%253A%2520'triangle'%250A%257D%253B%250A%250A%252F**%2520%2540param%2520%257BShape%257D%2520shape%2520*%252F%250Afunction%2520f(shape)%2520%257B%250A%2520%2520switch%2520(shape)%2520%257B%250A%2520%2520%2520%2520case%2520Color.RED%253A%250A%2520%2520%2520%2520%2520%2520alert('r')%253B%250A%2520%2520%2520%2520case%2520Color.ORANGE%253A%250A%2520%2520%2520%2520%2520%2520alert('o')%253B%250A%2520%2520%257D%250A%257D%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_TYPES_NEW_INFERENCE%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1
