### ISSUE TITLE
Unused parameter still makes their way to compiled code

### ISSUE THREAD

**Issue by MarbleDaemon** [google/closure-compiler#958]
The source code:

	/**
	 * @param {string=} x
	 * @constructor
	 */
	function A (x)
	{
		if (x)
		{
			console.log(x);
		}
	}

	new A();

would be compiled to

new function (a) {
		a && console.log(a)
	};

As parameter a is not given, it should not be in the compiled code along with all the process using it.

**Comment by dimvar** [comment]
The compiler removes a parameter when it is unused in the function body, not when it is never passed at the call sites. Using info from call sites requires whole-program analysis which is too expensive.

**Comment by concavelenz** [comment]
We do call site base parameter optimizations, but it is named based.  If you do:
```
/**
 * @param {string=} x
 * @constructor
 */
function A (x)
{
    if (x)
    {
        console.log(x);
    }
}

new A();
new A();
```

You will see that this is produced:

```
function a(){}new a;new a;
```

The pass just doesn't handle the case where the function function declaration is inlined into the callsite first (and is thus nameless).
