### ISSUE TITLE
@nocollapse should work on enums

### ISSUE THREAD

**Issue by nicks** [google/closure-compiler#963]
Run

```
/** @enum */
var Foo = {A: 1}

/** @nocollapse */
Foo.bar = 2;
```

with collapse properties on

Expected: Foo.bar should not get collapsed
Actual: Foo.bar gets collapsed, and the compiler warns that `@nocollapse` isn't allowed here (o.o)

http://closure-compiler-debugger.appspot.com/#input0%3D%252F**%2520%2540enum%2520*%252F%250Avar%2520Foo%2520%253D%2520%257BA%253A%25201%257D%250A%250A%252F**%2520%2540nocollapse%2520*%252F%250AFoo.bar%2520%253D%25202%253B%250A%250A%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES%3D1%26COLLAPSE_PROPERTIES%3D1%26MISSING_PROPERTIES%3D1

**Comment by dimvar** [comment]
I think the idea was that we shouldn't be supporting enums as namespaces indefinitely. Also, why would you want the prop to not be collapsed? Do you wanna pass the enum literal around?

Adding Chad since he added nocollapse.

**Comment by nicks** [comment]
yes, I want to pass the enum literal around.

**Comment by nicks** [comment]
I think your point about namespaces is cross-cutting.
- if enums aren't namespaces, then we shouldn't collapse at all, so this is a bug because it collapses
- if enums are namespaces, then we should collapse, and this is a bug because `@nocollapse` isn't supported
right?

**Comment by dimvar** [comment]
> and this is a bug because @nocollapse isn't supported right?

Since there is an error message that explicitly disallows nocollapse in this case, I wouldn't call this a bug; rather a feature request.

Anyway, Chad is the most appropriate person to discuss this.

**Comment by ChadKillingsworth** [comment]
This works though right?

```JavaScript
/** @enum */
var Foo = {
  A: 1,
  /** @nocollapse */
 bar: 2
}
```

**Comment by ChadKillingsworth** [comment]
Here's the original enum discussion: https://github.com/google/closure-compiler/pull/805#discussion_r26424792

**Comment by ChadKillingsworth** [comment]
After re-reading all the code comments and discussion, I can summarize:

1. Enums have been abused in the past when treated as a namespace.
2. I didn't have a use case for an enum with `@nocollapse` as I always consider them a constant.

So we purposefully disabled enums from using `@nocollapse`. As there is now a presented use case, I have no problem with enums being allowed to use `@nocollapse` as long as there is the understanding that there may be future restrictions on enums as namespaces.

I'll create a PR to this effect.
