### ISSUE TITLE
compiler infers wrong type for array

### ISSUE THREAD

**Issue by myphysicslab** [google/closure-compiler#965]
NTI (new type inference) compiler infers wrong type for elements of an array.  The warning is

```
src/lab/engine2D/DampingLaw.js:268: WARNING - Property getAngularVelocity never defined
on myphysicslab.lab.model.PhysicsObject
    var vw = bod.getAngularVelocity();
             ^
```

That line is in this method:

``` javascript
/** @inheritDoc */
DampingLaw.prototype.calculateForces = function() {
  /** @type {!Array.<!myphysicslab.lab.model.Force>} */
  var forces = new Array(0);
  goog.array.forEach(this.bods_, function(bod) {
    if (!isFinite(bod.getMass())) // skip infinite mass objects
      return;
    // translational damping: location is center of mass;
    // direction/magnitude is  -k*body.vx, -k*body.vy
    var cm = bod.getPosition();
    var f = new Force("damping_translational", bod,
        /*location=*/cm, CoordType.WORLD,
        /*direction=*/bod.getVelocity().multiply(-this.damping_), CoordType.WORLD);
    forces.push(f);
    // rotational damping:  two forces, f1, f2.
    // f1.location = (body.cm.x -0.5, body.cm.y)  // world coords
    // f2.location = (body.cm.x +0.5, body.cm.y)
    // let b = magnitude of damping force
    // f1.direction = (0, b*vw)
    // f2.direction = (0, -b*vw)
    var vw = bod.getAngularVelocity();
    var b = this.dampingType_ == DampingType.DAMPING_LEGACY ?
        this.damping_ * bod.momentAboutCM() : this.damping_;
    forces.push(new Force("damping_rotational", bod,
        /*location=*/new Vector(cm.getX() - 0.5, cm.getY()), CoordType.WORLD,
        /*direction=*/new Vector(0, b*vw), CoordType.WORLD));
    forces.push(new Force("damping_rotational", bod,
        /*location=*/new Vector(cm.getX() + 0.5, cm.getY()), CoordType.WORLD,
        /*direction=*/new Vector(0, -b*vw), CoordType.WORLD));
  }, this);
  return forces;
};
```

The array is defined here:

``` javascript
myphysicslab.lab.engine2D.DampingLaw = function(damping, dampingType, bods) {
  // code omitted
  /**
  * @type {!Array.<!myphysicslab.lab.engine2D.RigidBody>}
  * @private
  */
  this.bods_ = bods || [];
};
```

The `RigidBody` interface does define `getAngularVelocity`

``` javascript
/**
* @interface
* @extends {myphysicslab.lab.model.PhysicsObject}
*/
myphysicslab.lab.engine2D.RigidBody = function() {};

/** Returns angular velocity of rotation of this body about it's center of mass.
@method
@return {number} the angular velocity, in radians/second, with positive meaning
    counter-clockwise rotation about the body's center of mass
*/
RigidBody.prototype.getAngularVelocity;
```

The compiler thinks the elements of the array are of type `PhysicsObject` but they are declared to be of type `RigidBody`.

**Comment by dimvar** [comment]
This is most likely related to goog.array.forEach. If you annotate the type of bod in the function as

    function(/** !myphysicslab.lab.engine2D.RigidBody */ bod) { ...

does it work as expected?

**Comment by myphysicslab** [comment]
Yes, that seems to fix it.  I now have just 4 "dangerous use of the global this object" warnings for that file.

**Comment by myphysicslab** [comment]
Should I apply that fix wherever I see that error?  Or is this still a compiler problem?

**Comment by dimvar** [comment]
What do you get with the old type checker? Proper typechecking inside the callback, or no typechecking?

I'm not sure yet if this is sth we'll fix in NTI. When a function is passed as an argument, and it doesn't have type annotations, we try to grab a type from the callee. But in this case goog.array.forEach is generic, and we can't do much with that type.

**Comment by myphysicslab** [comment]
Without NTI I get proper typechecking with or without the annotation

```
function(/** !myphysicslab.lab.engine2D.RigidBody */ bod) { ...
```
For example I get this correct warning:
```
src/lab/engine2D/DampingLaw.js:270: WARNING - Property getFoo never defined on 
myphysicslab.lab.engine2D.RigidBody
      var foo = bod.getFoo();
                    ^
```

This seems similar to issue #855 except there its `goog.array.find` instead of `goog.array.forEach`.  But I tried annotating the type on the function passed to `goog.array.find` and just got a different warning.

**Comment by dimvar** [comment]
OK, perhaps OTI special cases these functions. I'll have to check what it does and copy it in NTI.

**Comment by myphysicslab** [comment]
This seems to be fixed.  I'm using NTI.  I have 129 instances of using `goog.array.forEach` and they are all working fine without any extra type annotation.
