### ISSUE TITLE
Lambda expression forgets context type

### ISSUE THREAD

**Issue by lgandras** [google/closure-compiler#967]
Hi,

don't quite now why this works:
```javascript
/**
 * @type {*}
 */
var x;
if (goog.isObject(x)) {
  /** @type {Object} */
  var y = x;
}
```
whereas this doesn't:
```javascript
/**
 * @type {*}
 */
var x;
if (goog.isObject(x)) {
  (function() {
    /** @type {Object} */
    var y = x;
  })();
}
```

**Comment by dimvar** [comment]
The test that tightens the type doesn't work across scopes. In general, it's harder to preserve type information across scopes, so most of the time the type checker gives up.
