### ISSUE TITLE
Externs for jQuery 2.x

### ISSUE THREAD

**Issue by alexandernst** [google/closure-compiler#970]
Maybe add externs for jQuery 2.x

**Comment by ChadKillingsworth** [comment]
As far as I know, the API hasn't changed for jQuery since 1.9/2.0. Did 1.11/2.11 have api changes?

**Comment by alexandernst** [comment]
Ah, you're right. Don't know why, but I was under the impression that the API changed between 2.0 and 2.1. Closing as this is clearly invalid.

**Comment by ChadKillingsworth** [comment]
I'd very open to finding a way to indicate that in the externs. The naming lends you to think we don't support the latest version.

**Comment by alexandernst** [comment]
True, my brain automatically shouted "<b>not supported!</b>" the moment I saw the listing of the extern files.

The very first thing that is passing on my mind right now: apply a ranges of versions to the extern's name. Example for jQuery extern: `jquery.1.9-2.1.js` (from v1.9 to v2.1). @ChadKillingsworth
