### ISSUE TITLE
Overriding intefrace methods

### ISSUE THREAD

**Issue by ihsoft** [google/closure-compiler#973]
When implementing class annotates interface method as `@override` compiler complains `property XXX not defined on any superclass of YYY`.

It's a perfectly fine error from a Java-side point of view. In both C++ and Java worlds we have these things honored _indirectly_ via errors like "abstarct class cannot be instantiated". As for now closure compiler inherits this legacy. And I dare to suggest either a distinc keyword or `@override` reuse to explicitly designate methods that are _implementations_ of an inherited interface(s). It doesn't hurt and can be just a warning (disabled by default). Though, for a language as Javascript is such compiler-time checking can be a big help for honoring a true OOP approach.

**Comment by dimvar** [comment]
> When implementing class annotates interface method as @override compiler complains property XXX not defined on any superclass of YYY.

That's not true. See this example. If you have another example where you see the message, please post the code.

http://closure-compiler-debugger.appspot.com/#input0%3D%252F**%2520%2540interface%2520*%252F%250Afunction%2520High()%2520%257B%257D%250A%250A%252F**%250A%2520*%2520%2540param%2520%257Bnumber%257D%2520x%250A%2520*%2520%2540return%2520%257Bnumber%257D%250A%2520*%252F%250AHigh.prototype.f%2520%253D%2520function(x)%2520%257B%257D%253B%250A%250A%252F**%2520%2540constructor%2520%2540implements%2520%257BHigh%257D%2520*%252F%250Afunction%2520Low()%2520%257B%257D%250A%250A%252F**%2520%2540override%2520*%252F%250ALow.prototype.f%2520%253D%2520function(x)%2520%257B%2520return%2520x%253B%2520%257D%253B%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES%3D1%26MISSING_PROPERTIES%3D1
