### ISSUE TITLE
How to do multiple @suppress in one function comment?

### ISSUE THREAD

**Issue by fixermark** [google/closure-compiler#976]
I have need to @suppress both duplicate and accessControls in some funny patch code. When I try to add two @suppress statements, I get an error rejecting duplicate @suppress in the same comment block. Trying comma-separated (@suppress {duplicate,accessControls} also does not work

The wiki [https://github.com/google/closure-compiler/wiki/Warnings] provides no guidance. This might be as easy to solve as adding explanation of how to set multiple values to the wiki

**Comment by dimvar** [comment]
Comma-separated is what we support. Please provide a specific code sample where you use comma-separated and you don't get the suppressions.

**Comment by MatrixFrog** [comment]
`@suppress {duplicate|accessControls}` should work.

**Comment by fixermark** [comment]
My apologies; comma-separated does work; I applied it to the wrong function.

Can you add the fact that comma separation works to the wiki?

**Comment by dimvar** [comment]
Good idea. Edited the wiki.
