### ISSUE TITLE
sourceMappingURL # vs. @

### ISSUE THREAD

**Issue by bardware** [google/closure-compiler#979]
[Google's own document](https://docs.google.com/document/d/1U1RGAehQwRypUTovF1KRlpiOFze0b-_2gc6fAH0KY0k/edit#) reads: 

```
The prefix for this annotation was initially “//@” however this conflicts with
Internet Explorer’s Conditional Compilation and was changed to “//#”.
It is reasonable for tools to also accept “//@” but “//#” is preferred.
```
Will you accordingly change the ant task `\closure-compiler\src\com\google\javascript\jscomp\ant\CompileTask.java` lin 378 to `source.append("//# sourceMappingURL=" + sourceMapOutputFile.getName());`

**Comment by concavelenz** [comment]
Please submit a pull request.  The ant task is maintained by the community.

**Comment by bardware** [comment]
I didn't want to create a pull request for just one character but I had another issue so I now created a pull request with another modification. #1017

**Comment by dimvar** [comment]
PRs for a single-character change are fine.

**Comment by dimvar** [comment]
Fixed by https://github.com/google/closure-compiler/commit/d16b3c3aa888e11a0842b1b940a364973b037b0b
