### ISSUE TITLE
Allow declaring type of jQuery deferred/promise

### ISSUE THREAD

**Issue by ihsoft** [google/closure-compiler#981]
As for now the only way to have strict type checking when using $.Deferred or $.Promise is explicit annotation of the functions. Like this:
```Javascript
var resp = $.Deferred();
resp
  .then(/** @param {string} data */ function(data) {
    console.log('Got data: ' + data);
  })
  .fail(/** @param {number} errCode */ function(errCode) {
    console.log('Got error: ' + errCode);
  });
```
Though, such approach is error prone when deferred or promise (which is more common) comes from a function call or a third party library. In fact, user of the promise have to take care about right type annotation which is not right approach. The right approach is when provider of the object declares the type. So, I propose to introduce an extended syntax to jQuery and closure promises:
```Javascript
/** @type {!jQuery.Deferred.<function(string), function(number)> */
var resp = $.Deferred();
resp
  .then(function(data) {  // Annotation comes from the first arg in jQuery.Deferred.<>
    console.log('Got data: ' + data);
  })
  .fail(function(errCode) {  // Annotation comes from the second arg in jQuery.Deferred.<>
    console.log('Got error: ' + errCode);
  });
resp.resolve('abc');  // Parameter annontations come from the first arg in jQuery.Deferred.<>
resp.reject(123);  // Parameter annontations come from the second arg in jQuery.Deferred.<>
```
For backward compatibility when no type annotation provided to a dererred object the old behavior is used.

**Comment by ChadKillingsworth** [comment]
We want to handle this the exact same way we did es6 promises. I'll have to check with @concavelenz on the particulars.

**Comment by pcj** [comment]
+1

However this can be implemented, it would be a very useful feature.

**Comment by ChadKillingsworth** [comment]
I've looked into this more and don't believe this is currently possible.b Adding annotations as you suggest are more involved then might first appear and it's not something I'm willing to tackle right now.

The problem lies in that the callback parameter value does not have to be related to anything and also doesn't fit our current generics support.
