### ISSUE TITLE
'arguments' misinterpreted in arrow function

### ISSUE THREAD

**Issue by MarbleDaemon** [google/closure-compiler#982]
Example:

https://closure-compiler-debugger.appspot.com/#input0%3D%255B1%252C2%252C3%255D.forEach(x%2520%253D%253E%2520console.log(x%252C%2520arguments.length))%253B%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES%3D1%26LANG_IN_IS_ES6%3D1%26MISSING_PROPERTIES%3D1%26TRANSPILE%3D1

The 'arguments' of the arrow function was misinterpreted as an outer scoped variable.

**Comment by MatrixFrog** [comment]
Actually we make essentially the same mistake with any use of `arguments` in the global scope. We act like it's a global variable: https://closure-compiler-debugger.appspot.com/#input0%3Dalert(arguments)%253B%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES%3D1%26MISSING_PROPERTIES%3D1

We should probably remove it from the externs (https://github.com/google/closure-compiler/blob/master/externs/es3.js#L61) but I don't know if that would break anything.

**Comment by blickly** [comment]
Arrow functions don't bind arguments. See:
https://people.mozilla.org/~jorendorff/es6-draft.html#sec-arrow-function-definitions-runtime-semantics-evaluation
