### ISSUE TITLE
[NTI] Inferring signature of unannotated function passed as an argument to a polymorphic function

### ISSUE THREAD

**Issue by dimvar** [google/closure-compiler#994]
See the following example. OTI warns about assigning a Foo to a Bar, whereas NTI warns about using global this, because it doesn't know the type of this inside the argument function.

``` js
/**
 * @template T
 * @param {function(this:T)} x
 * @param {T} y
 */
function poly(x, y) {}

/** @constructor */ function Foo() {}

/** @constructor */ function Bar() {}

poly(function() { var /** !Bar */ b = this; }, new Foo);
```

See also the `array.forEach` example in #834. OTI has some weird order of processing in order to get a correct type signature for the argument functions.

I'm not sure if it's worth it to replicate that, or if we should just tell people to use type annotations in this case.

**Comment by myphysicslab** [comment]
I can get rid of all the ***dangerous use of global this object*** warnings by giving type information about the function passed to `goog.array.forEach` (and other similar array functions).  But if using the `this` parameter to `goog.array.forEach` always results in an error, then those functions in closure library should be revised to eliminate the `this` parameter.  This is similar to issue #960.

Here is an example of how to get rid of the warning "dangerous use of global this object".  

Before:
```javascript
GravityLaw.prototype.calculateForces = function() {
  var forces = new Array(0);
  goog.array.forEach(this.bods_, function(body) {
    if (isFinite(body.getMass())) { // skip infinite mass objects
      forces.push(new Force("gravity", body,
        /*location=*/body.getPosition(), CoordType.WORLD,
        /*direction=*/new Vector(0, -this.gravity_ * body.getMass(), 0),
        CoordType.WORLD));
    }
  }, this);
  return forces;
};
```
After:  
Give type specification for the function passed to `forEach`, and use `goog.bind`:
```javascript
GravityLaw.prototype.calculateForces = function() {
  var forces = new Array(0);
  /** @type {function(this:GravityLaw, !PhysicsObject)} */
  var f = function(body) {
    if (isFinite(body.getMass())) { // skip infinite mass objects
      forces.push(new Force("gravity", body,
        /*location=*/body.getPosition(), CoordType.WORLD,
        /*direction=*/new Vector(0, -this.gravity_ * body.getMass(), 0),
        CoordType.WORLD));
    }
  };
  goog.array.forEach(this.bods_, goog.bind(f, this));
  return forces;
};
```

**Comment by dimvar** [comment]
I think your last comment is more related to #834, not to this issue. See my latest comment there. I have a fix pending for that.

**Comment by concavelenz** [comment]
I think this is a pretty important use case.   This eliminates the need for function annotations in may common uses (Array#forEach, etc) and greatly improves type information.  Can you explain the complication this causes for the NTI and why you can't support it?

**Comment by dimvar** [comment]
We haven't decided for sure yet that we won't support it, but it's not high priority.

The difficulty is the following. In my example, we can't pick the type <code>function(this:T)</code> as the declared type of the argument function, we want to instantiate T first. But the way we instantiate is that we look at the argument types (which are supposed to be non-generic) and try to match them with the formal parameter types (which are generic). The information flows from the arguments to the formals, whereas in this example we also want to get information back to the arguments.
