### ISSUE TITLE
The symbol  of lineDashOffset was shorten after ADVANCED_OPTIMIZATIONS compiling

### ISSUE THREAD

**Issue by weiwl** [google/closure-compiler#995]
When painting a dashed line, the symbol of `lineDashOffset`  was shorten after ADVANCED_OPTIMIZATIONS compiling.

```javascript
/**
 * @param {CanvasRenderingContext2D} context
 */
foo.bar.drawDashedLine = function(context, ...) {
  ...
  if (goog.isFunction(context.setLineDash)) {
    // for chrome/IE
    context.setLineDash(dash);
    context.lineDashOffset = offset;
  } else if ('mozDash' in context) {
    // for old firefox (latest firefox should support setLineDash)
    context['mozDash'] = dash;
    context['mozDashOffset'] = offset;
  }
  ...
}
```

`setLineDash` is kept but `lineDashOffset` not.

`lineDashOffset` should not be shorten, because all modern browsers already support it.

https://developer.mozilla.org/en/docs/Web/API/CanvasRenderingContext2D/lineDashOffset

**Comment by blickly** [comment]
I'm sure a pull request adding it to the externs would be accepted. Want to try?

**Comment by weiwl** [comment]
Yes, the patch will be very simple. But I haven't  signed the CLA yet.

**Comment by weiwl** [comment]
Resolved. Thanks a lot.
