### ISSUE TITLE
'use strict' is incorrectly stripped

### ISSUE THREAD

**Issue by kaaaahhhhnnnn** [google/closure-compiler#997]
(function(){
      'use strict';
      console.log(42);
    }());

    (function(){
      console.log(43);
    }());

compiles to...

    (function(){console.log(42)})();(function(){console.log(43)})();

Setting the language output to a `_STRICT` language incorrectly places the entire file in strict mode instead of just the one function.

**Comment by concavelenz** [comment]
Setting the language mode to ES5_STRICT correctly puts the entire file in strict mode, that is what the language mode means.  We don't support mixed strict and non-content in a single compilation job.  You need to put it into a separate file.

**Comment by kaaaahhhhnnnn** [comment]
That's fine, but `use strict` is stripped completely when the out language is `ES5`.  Is this really a "won't fix"?

**Comment by ChadKillingsworth** [comment]
Yes - it really is a "won't fix", but only because there are existing mechanisms in place. Using the `--output_wrapper` flag of the compiler is how most users do it. Example:

    --output_wrapper="(function(){'use strict';%OUTPUT%}).call(this)"

**Comment by kaaaahhhhnnnn** [comment]
And that's basically the same thing as `ES5_STRICT` mode.  The entire point of having function-level strict mode is that not everything passes in strict mode.  For instance if I have `var foo = require('someExternalModule')` and closure ends up inlining that code, there's a chance it won't pass and since it's not my code I don't want to change it (and I'm too lazy to go and fork the project).

Basically my only choice now is to leave everything as unstrict (which potentially introduces security issues around `eval`, etc)

**Comment by ChadKillingsworth** [comment]
Correct- that's about your only option. Here's the original discussion around strict mode: https://code.google.com/p/closure-compiler/issues/detail?id=69

We really don't have any plans to support a mix of strict/non-strict code in the same compilation. It's actually a pretty hard problem and just doesn't have a large use case.
